### ISSUE TITLE
Extensions page scrolls off the top of the screen as iOS keyboard appears

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#1006]
**Describe the bug**
When the beta Extensions page appears, most of the page is pushed up off-screen by the iOS keyboard.

**To Reproduce**
1. Go to 'https://makecode.microbit.org/beta#editor'
2. Click on the cog
3. Choose Extensions

**Expected behavior**
The text entry box should be visible, as it is if you close the keyboard then tap in the text box. I'm not sure it's helpful to automatically focus the text entry box so that the keyboard appears.

**Screenshots**
![img_0122](https://user-images.githubusercontent.com/989126/43482740-70c5882a-9501-11e8-8fed-42787d1c2612.png)

**Desktop (please complete the following information):**
 - OS: iPad Air 2; iOS 11.4.1
 - Browser : Safari
 - Version : makecode.microbit.org version:  1.1.38

**Comment by martinwork** [comment]
This seems to be partly fixed in beta, in that the page no longer scrolls up when the keyboard opens so that the search text is visible.

It would be better if the keyboard didn't open immediately, but waited for the user to tap in the search box.

**Comment by abchatra** [comment]
@martinwork  does this still repro?

**Comment by martinwork** [comment]
@abchatra It doesn't scroll off the top of the screen now.

**Comment by abchatra** [comment]
Fixed
