### ISSUE TITLE
unreachable code detected

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt-microbit#102]
creating an if-then-else block causes an error message (from TypeScript) because the block translates to "if (false) { } else { }"

![image](https://cloud.githubusercontent.com/assets/10767146/15988772/77036790-302a-11e6-979e-c5cf67227bdb.png)

**Comment by pelikhan** [comment]
Dead code warning that we treat as error.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by tballmsft** [comment]
This is a bad outcome for a block program - this is a regression from the Microsoft Block Editor experience.
