### ISSUE TITLE
Allow user to change the variable in a 'for' loop

### ISSUE THREAD

**Issue by microbit-rosslowe** [Microsoft/pxt-microbit#1029]
Changing the variable in the ‘for’ loop in the old editor is much easier than in the new editor, which doesn’t have any onClick behaviour for the ‘index’ variable, instead requiring the user to drag & drop a new variable into the box or drag ‘index’ out then reconnect it:
![Old editor behaviour](https://d2mxuefqeaa7sj.cloudfront.net/s_A1563C9E4CF3DA684C1233D4B3EF3E08833745681D5DAA3D66A1BF20A4B639D4_1533139307552_file.png)

![New editor behaviour](https://d2mxuefqeaa7sj.cloudfront.net/s_A1563C9E4CF3DA684C1233D4B3EF3E08833745681D5DAA3D66A1BF20A4B639D4_1533139377578_loops.gif)

**Suggestion**
The 'for' loop could automatically have a variable with a dropdown. It might also be useful to have a 'new variable' option here.

**Comment by abchatra** [comment]
We will address this.
