### ISSUE TITLE
two micro:bits not showing up

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt-microbit#103]
![image](https://cloud.githubusercontent.com/assets/10767146/16013617/2bbaa14e-315c-11e6-97f0-3b4bad0098cb.png)

**Comment by pelikhan** [comment]
Browser, screen size, JavaScript console output?

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by tballmsft** [comment]
laptop, Edge,

**Comment by tballmsft** [comment]
Simulator crashed, no error handler TypeError: Object doesn't support property or method 'sendNumber'

**Comment by tballmsft** [comment]
simulator: 2 -> 1
pxtsim.js (1650,17)
stopping simulator...
pxtsim.js (99,17)
building: microbit, microbit-radio, Untitled
pxtlib.js (2522,9)
Using cached extinfo
pxtlib.js (1039,17)
stopping simulator...
pxtsim.js (99,17)
starting frame sim-frame-10153688112631649050.9281798917613601
pxtsim.js (1763,13)
simulator: 1 -> 2
pxtsim.js (1650,17)
stopping simulator...
pxtsim.js (99,17)
starting yellow-12057098273160992850.6349346387626455
pxtsim.js (106,13)
setting up microbit simulator
sim.js (1713,13)
DONE
pxtsim.js (112,21)
Simulator crashed, no error handler TypeError: Object doesn't support property or method 'sendNumber'
   at _inline_9719 (eval code:254:5)
   at loop (https://az851932.vo.msecnd.net/app/hsbqo/c/pxtsim.js:1315:25)
   at currResume (https://az851932.vo.msecnd.net/app/hsbqo/c/pxtsim.js:1397:25)
   at runAction2 (https://az851932.vo.msecnd.net/app/hsbqo/c/pxtsim.js:225:17)
   at Anonymous function (https://az851932.vo.msecnd.net/app/hsbqo/c/pxtsim.js:1427:21)
   at Anonymous function (https://az851932.vo.msecnd.net/app/hsbqo/c/bluebird.min.js:30:28755)
pxtsim.js (1323,25)
page visibility: false
main.js (1116,9)
simulator: 2 -> 1
pxtsim.js (1650,17)
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block id="CGy=U!6@LW.|JVaJRyt#" type="device_forever" y="26" x="36">
    <statement name="HANDLER">
      <block id="33NcfsSGp4ao+LK!J3#I" type="radio_datagram_send">
        <value name="value">
          <shadow id="Uy#F,kVrme:Os8vWh^m*" type="math_number">
            <field name="NUM">0</field>
          </shadow>
          <block id="ZBL~=e}Uy1PW,PyJoKZk" type="device_acceleration">
            <field name="NAME">Dimension.X</field>
          </block>
        </value>
      </block>
    </statement>
  </block>
  <block id="6Zhsw,Xk/BSyOdXk}K2Q" type="radio_datagram_received_event" y="151" x="54">
    <statement name="HANDLER">
      <block id="]Pup4KDu)9.r;F??7/cn" type="device_plot_bar_graph">
        <value name="value">
          <shadow id="uBtr:Vc04LRx`%txQ@su" type="math_number">
            <field name="NUM">0</field>
          </shadow>
          <block id=")X0RZhdY3PsSm:;As]wK" type="radio_datagram_receive"></block>
        </value>
        <value name="high">
          <shadow id="=B%83FRbv1,5!/1YMybb" type="math_number">
            <field name="NUM">1023</field>
          </shadow>
        </value>
      </block>
    </statement>
  </block>
</xml>
main.js (1977,9)
stopping simulator...
pxtsim.js (99,17)
page visibility: true
main.js (1116,9)
building: microbit, microbit-radio, Untitled
pxtlib.js (2522,9)
Using cached extinfo
pxtlib.js (1039,17)
stopping simulator...
pxtsim.js (99,17)
starting frame sim-frame-10153688112631649050.9281798917613601
pxtsim.js (1763,13)
simulator: 1 -> 2
pxtsim.js (1650,17)
stopping simulator...
pxtsim.js (99,17)
starting green-15065322897952437220.8936586820465242
pxtsim.js (106,13)
setting up microbit simulator
sim.js (1713,13)
DONE
pxtsim.js (112,21)
Simulator crashed, no error handler TypeError: Object doesn't support property or method 'sendNumber'
   at _inline_11671 (eval code:254:5)
   at loop (https://az851932.vo.msecnd.net/app/hsbqo/c/pxtsim.js:1315:25)
   at currResume (https://az851932.vo.msecnd.net/app/hsbqo/c/pxtsim.js:1397:25)
   at runAction2 (https://az851932.vo.msecnd.net/app/hsbqo/c/pxtsim.js:225:17)
   at Anonymous function (https://az851932.vo.msecnd.net/app/hsbqo/c/pxtsim.js:1427:21)
   at Anonymous function (https://az851932.vo.msecnd.net/app/hsbqo/c/bluebird.min.js:30:28755)
pxtsim.js (1323,25)

**Comment by abchatra** [comment]
Doesnt repro anymore in the edge
