### ISSUE TITLE
Special symbol of parameter name lost when switching to JavaScript mode

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1035]
**Repro steps:**
1. Open this shared project https://makecode.microbit.org/_TMc3WhLm92EK
2. Observe the parameter name and click "{} JavaScript" to switch to JavaScript mode 
3. Observe the parameter name in JavaScript mode 

**Expected result:**
The parameter name should be "assssd*******hhh"
![8030002](https://user-images.githubusercontent.com/23466737/43628927-3837f20c-972e-11e8-816b-f6b30963d089.PNG)

**Actual result:**
Special symbol of parameter name lost when switching to JavaScript mode
![8010001](https://user-images.githubusercontent.com/23466737/43628819-f6386698-972d-11e8-9388-b29a1a8954fa.PNG)

**Comment by riknoll** [comment]
Thanks for the bug, this is the desired behavior. `*` is an invalid character for a JavaScript identifier so we strip them out when going from Blocks to JavaScript
