### ISSUE TITLE
The "else" part of the "if-else" block should be removable

### ISSUE THREAD

**Issue by FranklinWhale** [Microsoft/pxt-microbit#1037]
**Describe the bug**
In v1, after an "if" block is created, if the user accidentally adds an "else" part vis the "+" button, effectively making the block to an "if-else" block, there is no "-" button to remove the "else" part.

**To Reproduce**
1. Create an "if" block
2. Press the "+" button to add an "else" part

**Expected behavior**
There is a "-" button to remove the "else" part.

**Screenshots**
![if-block](https://user-images.githubusercontent.com/8416067/43656187-104d1bea-9784-11e8-89cd-0991000437fe.png)

**Comment by riknoll** [comment]
This behavior is intentional; we don't have a user experience for choosing between adding an "else" or an "else if" clause when clicking the (+) button so we made the conscious decision to provide two versions of the block in the toolbox: one with an undeletable else clause and one without an else clause and no way to add one.

**Comment by FranklinWhale** [comment]
> one without an else clause and no way to add one.

The current "if" block has a (+) button to add an "else" clause.

![if-block](https://user-images.githubusercontent.com/8416067/43671964-e9fe21e8-97d6-11e8-8634-040a3dadeaa9.png)

> we don't have a user experience for choosing between adding an "else" or an "else if" clause when clicking the (+) button

Although probably not intended, the current logic of the (+) button of the "if" block makes sense to me. When the "if" block doesn't have an else clause, it adds an "else" clause. Otherwise, it inserts an "else if" before the "else" clause.  With this logic, the user doesn't have to choose between adding an "else if" or an "else" clause. The only problem appears to be not providing an option to remove the "else" clause.

**Comment by abchatra** [comment]
Lets try to address this.

**Comment by abchatra** [comment]
This is not a high priority bug. Users can always drag the original bug from the toolbox. But good to fix if the level of effort is reasonable.

**Comment by pelikhan** [comment]
This issue is fixed in v1.1.55
