### ISSUE TITLE
API revision

### ISSUE THREAD

**Issue by tinfoilhatter** [Microsoft/pxt-microbit#104]
Some APIs are counterintuitive and may confuse children. I only have a couple of examples right now, but there may be more later.

The LED APIs **brightness** and **set brightness** sound as though they get/set how bright the LEDS _actually_ are on the LED screen. Instead, they are about the _potential_ brightness of the LEDs. If you set the brightness of the screen to 127 (on a scale of 0-255), that doesn't mean the screen is halfway illuminated. Instead, it means the screen would be halfway illuminated _if it were lit at all_. In other words, an LED can have a "brightness" of 255 and still be completely dark. "Brightness" has no effect on whether LEDs are lit or not.

I found this confusing. An informal survey of my acquaintances showed they understood "brightness" the way I initially did. I suggest that children would also find this confusing.

If we can't change these APIs, perhaps we can move the documentation to an advanced/supplementary section.

**Comment by tinfoilhatter** [comment]
As a reference point, here's one of the corresponding runtime APIS:

https://lancaster-university.github.io/microbit-docs/ubit/display/#setbrightness

**Comment by tballmsft** [comment]
Ron, I believe we are just following the Lancaster API on this, so hard to change now.

**Comment by tinfoilhatter** [comment]
With Bluetooth, we are accumulating a set of APIs that are unlikely to be of interest to (or intelligible by) children. Perhaps the APIs mentioned in this issue could be moved with Bluetooth to an "Advanced APIs" section.

**Comment by abchatra** [comment]
Brightness API are moved to More... section.
