### ISSUE TITLE
Block for inclusion of Bluetooth accelerometer service needed

### ISSUE THREAD

**Issue by smartyw** [Microsoft/pxt-microbit#105]
It would be great if there was a tray containing Bluetooth related blocks.

In this tray, there should/could be a block per Bluetooth "service".

Dragging a Bluetooth service block into a PXT app would result in the corresponding Bluetooth being included in the generated code.

This issue requests a block for the micro:bit **Bluetooth accelerometer service**.

C/C++ code required to include the Bluetooth accelerometer service is:

```C/C++
new MicroBitAccelerometerService(*uBit.ble, uBit.accelerometer);
```

Note that inclusion of Bluetooth services has consequences for memory configuration on the micro:bit, specifically with respect to GATT table size. I've suggested an approach to addressing this to Joe Finney of Lancaster University and we're evaluating. Will update issue once this discussion has progressed further.

**Comment by bluetooth-mdw** [comment]
Sorry that should have been posted from my Bluetooth SIG git account... this one to be precise :-)

**Comment by pelikhan** [comment]
What configuration flags does this service require?

**Comment by bluetooth-mdw** [comment]
None. A few of the services are brought into being by setting config flags and others require explicit instantiation in code. Most are of the latter type including this one.

**Comment by pelikhan** [comment]
``config.json`` tracked in #110
