### ISSUE TITLE
Implement Green screen

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1055]
This ticket is to track Implementing green screen mode for micro:bit. 

From https://github.com/Microsoft/pxt-microbit/issues/858#issuecomment-411158285

"consensus on our team was that it was too narrow a feature to give it such prime real estate and it adds a maintenance burden (we already have two themes for each of our editors)." @riknoll 

**Describe the solution you'd like**
As with other makecode editors, the ability to record tutorials using green screen would prove popular with teachers.

**Additional context**
The functionality is probably more teacher focussed, so may might be good to have this on a seperate URL eg makecode.microbit.org#editor?greenscreen=1 so young people don;t switch it on/off by accident. Cameras may also be blocked in schools.

For info @jaustin @halspeed

**Comment by abchatra** [comment]
Done this is part of experiment now. Will go through the normal release process for the release
