### ISSUE TITLE
Block for inclusion of Bluetooth button service needed

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#106]
It would be great if there was a tray containing Bluetooth related blocks.

In this tray, there should/could be a block per Bluetooth "service".

Dragging a Bluetooth service block into a PXT app would result in the corresponding Bluetooth being included in the generated code.

This issue requests a block for the micro:bit **Bluetooth button service**.

C/C++ code required to include the Bluetooth button service is:

```C/C++
new MicroBitButtonService(*uBit.ble);
```

Note that inclusion of Bluetooth services has consequences for memory configuration on the micro:bit, specifically with respect to GATT table size. I've suggested an approach to addressing this to Joe Finney of Lancaster University and we're evaluating. Will update issue once this discussion has progressed further.

**Comment by pelikhan** [comment]
- is there any ``config.json`` flags required?

**Comment by bluetooth-mdw** [comment]
Nope

**Comment by pelikhan** [comment]
It does need bluetooth enabled rigtht?
```
{
            "microbit-dal": {
                "bluetooth": {
                    "enabled": 1
                }
            }
```

**Comment by bluetooth-mdw** [comment]
Ah yes. They all do. Good point. Only just getting used to this new config file myself! :-)

**Comment by pelikhan** [comment]
``config.json`` handled in #110

**Comment by pelikhan** [comment]
``config.json`` handled in #110
