### ISSUE TITLE
Can we have a dropdown to pre-populate the showLED block?

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#1061]
**Is your feature request related to a problem? Please describe.**
One of the slight downsides to the showIcon block is that it reduces creativity as people rely on the pre-drawn icons. 
It's hard to start with a duck and then extend it to a swan, for example

**Describe the solution you'd like**
It would be good if the 'Show LEDs' block could be extended to include a set of icons that would populate the block, but leave it editable.

![image](https://user-images.githubusercontent.com/147113/43871220-8229f844-9b73-11e8-98df-3a705e5ab075.png)

The block could look like this, the 'drop down' could contain the icons, and selecting an icon would populate the LEDs to look like that icon, but it would be editable.

**Describe alternatives you've considered**
The showIcon block covers this somewhat, but the idea of an editable 'preview' would be great.

It might be better to use a different style to the dropdown I've drawn above - for example expanding the block out to the right to include a 'gallery' like in CodeKingdoms
![image](https://user-images.githubusercontent.com/147113/43871292-d10c92dc-9b73-11e8-8acb-74dd9d594da8.png)

**Additional context**
This is a request for an enhancement.

**Comment by abchatra** [comment]
No plans untill next release in June. Closing as "Revisit next release"
