### ISSUE TITLE
Importing a script with division from v0 doesn't convert it to "remainder of"

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#1062]
**Describe the bug**
When using division in a script in v0, and then importing that into v1 the division is not automatically converted to modulo/integer division

**To Reproduce**
1. Go to makecode.microbit.org
2. Create a script 'show number <1/2>'
3. Download the script
4. Go to makecode.microbit.org/beta
5. Drag the script downloaded in step (3) into the editor

**Expected behavior**
The division in the v0 script is converted to 'remainder of' blocks (modulo division)

**Screenshots**
![division-change](https://user-images.githubusercontent.com/147113/43871380-3f589eca-9b74-11e8-8b82-67fcdc39a02e.gif)

**Comment by riknoll** [comment]
I think `Math.floor()` might look a little cleaner. That is `Math.floor(a / b)` instead of `(a - (a % b)) / b`

@jaustin thoughts?

**Comment by riknoll** [comment]
Actually it should be `Math.trunc()`. Also the simulator in v0 is using `Math.floor()` so I'll fix that as well!

**Comment by jaustin** [comment]
Actually, @riknoll shouldn't it be Math.idiv()?

**Comment by riknoll** [comment]
There isn't a block for `Math.idiv`() right now. We could add one but I think it's more Javascript-y to use `Math.trunc()` since `Math.idiv()` is just something we made up.

**Comment by riknoll** [comment]
Just spoke with @mmoskal and he suggested we should go with `Math.idiv()` because it has much better performance. I'll add a block for `idiv` and `imul`

**Comment by riknoll** [comment]
I ended up adding it to the existing "math" block along with the other functions on the `Math` namespace
