### ISSUE TITLE
Variable to define a pin

### ISSUE THREAD

**Issue by daniel-pers** [microsoft/pxt-microbit#1064]
I'm a STEM teacher in France (K8 to K12). I use MakeCode with blocks only (no JavaScript).
If we study a temperature regulation for example, I can see that a block "digital write pin P0 to 1" give no information to my student about this use of P0. Instead a block "digital write HeatingPin to 1" make sense for a beginner. I just have to define the variable HeatingPin to 0 at the begining. Programs would be more readable.
This new feature does not require new blocks but only require updates of existing blocks.
What would be nice is that when I choose a Pin in a block (for reading, writing, control of a servo, ...), I can choose from this block a variable to which I give the value that I want (0 to 16), in the block "on start" a priori.
This new feature would also allow new algorithms, for example read or write several pins in a loop in relation to an array. In this case, the PinNumber variable could change dynamically.
Thanks a lot for your help.

**Comment by jaustin** [comment]
As this issue will likely start showing up for other people searching for this topic, there's a workaround that you can use with a custom block:

https://makecode.microbit.org/_CgUChwdhVP4a

This is a very quick example but could be extended for a specific activity or workshop.

```typescript
namespace custom {
    /**
     * Performs a digital read of the speficied pin P_
     * 
     * For pins not in the range 0-16, 18-20 return -1
     * 
     * @param n The pin number to read, eg 0 will read P0, eg: 0
     */
    //% block
    export function readDigitalPin(n: number): number {
        /* Plenty of ways for this to break. pins 17 & 18, for example!
         * The number 7 comes from 
         * https://github.com/Microsoft/pxt-microbit/blob/fa8dfd1dc328d0a349e25ff56ce384c58855a145/libs/core/enums.d.ts#L194
         */
        if (n < 17) {
            return pins.digitalReadPin(n + 7)
        } else if (n > 18 && n < 21) { 
            return pins.digitalReadPin(n + 5)
        } else {
            return -1
        }

    }
}
```

It would be nice if we could do something like this, though:
![image](https://user-images.githubusercontent.com/147113/43954825-d68eda12-9c95-11e8-85cb-e10394f89541.png)

**Comment by physicsdavid** [comment]
I would also find this very useful for my students as some of them are comfortable enough thinking about algorithms that require reading/writing dynamically chosen pins and ready to do it in blockcode but aren’t yet comfortable with writing code in js or micropython.

**Comment by philipphenkel** [comment]
@physicsdavid @HyperDuino Recently, we had a similar discussion and to decided to add some pin helpers to our MakerBit extension package. You could use the "set digital pin" with a variable and this turned out to be quite useful for our students. 
Drawback: I saw programs that did math on the variables (e.g. count down) and overwrote all pins by accident. It could introduce a new range errors... 

![bildschirmfoto 2018-10-02 um 23 38 32](https://user-images.githubusercontent.com/828416/46378589-65ce0b00-c69c-11e8-9759-0fc9a4a6c77e.png)

**Comment by abchatra** [comment]
It is hard to change APIS at this moment of time. Lot of teachers have screenshot.

I think right next step here is the extension with better APIs. Feel free to submit with the extension which does this.
