### ISSUE TITLE
W10 App: Process for publishing around v0/v1

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#1068]
We've agreed that we'll take the following steps to support users through the v0-->v1 transition with the Windows app, however they were based on the assumption that we could encourage users who needed to access from v0 in the app to install a specific version from the Windows store. I cannot see any way to do this, but perhaps the folks at Microsoft will know a way.

The plan was:
1) Release a new version of the W10 app into the store that loads v0 (so changing the MakeCode URL to include V0). Release the app out of beta with this URL
2) Before v1 is launched revert to the URL not containing v0 so that the app uses the latest version of MakeCode live
2) After v1 is launched, update the app to point to v1 explicitly and release a new version of the app that points to v1

For people using the latest version of the app:
The app will change from v0 to v1 at the same time as the website does

For people who need v0 in the app, they can stick to a particular version.

The last bit doesn't seem to be possible, and if it's not we may need to work out a way to load v0 in the app.

**Comment by pelikhan** [comment]
As discussed windows app to point to v1 and stay in “beta”
