### ISSUE TITLE
Block for inclusion of Bluetooth event service needed

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#107]
It would be great if there was a tray containing Bluetooth related blocks.

In this tray, there should/could be a block per Bluetooth "service".

Dragging a Bluetooth service block into a PXT app would result in the corresponding Bluetooth being included in the generated code.

This issue requests a block for the micro:bit **Bluetooth event service**.

Note that currently this service is included by default in builds. Given memory constraints it would make sense if it was only included when needed, either as a consequence of using a block which relies upon it (e.g. user events) or because it was explicitly included by dragging a new block into the code.

The Bluetooth event service is included by setting a configuration flag in config.json. See event_service property below.

```
        "bluetooth":{
            "enabled": 1,
            "pairing_mode": 1,
            "private_addressing": 0,
            "open": 0,
            "whitelist": 1,
            "advertising_timeout": 0,
            "tx_power": 0,
            "dfu_service": 1,
            "event_service": 1,
            "device_info_service": 1
        },
```

Note that inclusion of Bluetooth services has consequences for memory configuration on the micro:bit, specifically with respect to GATT table size. I've suggested an approach to addressing this to Joe Finney of Lancaster University and we're evaluating. Will update issue once this discussion has progressed further.

**Comment by pelikhan** [comment]
GATT size can be tracked in new bug. The service is exposed now.
