### ISSUE TITLE
Enable package extensions in the microbit target

### ISSUE THREAD

**Issue by rustynymph** [Microsoft/pxt-microbit#1083]
It would be really great if the microbit target could allow for package extensions in the same way the adafruit target does (for example, the pxt-neoanim package for adafruit).

I have designs for a microbit package that would make it easier to design large layouts of neopixels and program them, and I would like to have a package extension so it could open a new page where users can draw their designs and specify where they are placing their LEDs. 

I have been told that this is not as simple as just enabling the "allowPackageExtensions" flag within the target's pxt.json.

**Comment by abchatra** [comment]
Done
