### ISSUE TITLE
Can get locked into show LEDs block editing in iOS Safari

### ISSUE THREAD

**Issue by martinwork** [Microsoft/pxt-microbit#1095]
**Describe the bug**
In iOS Safari, if you accidentally scroll the page while editing the pattern in  a show leds block, taps stop working normally until the page is refreshed. For example, blocks can't be moved or added.

**To Reproduce**
1. Go to 'https://makecode.microbit.org/beta'
2. Tap 'New Project'
3. Tap 'Basic'
4. Tap 'show leds'
5. Tap in the show leds block to add a red pixel
6. Drag down in the left menu panel so the whole page is dragged down
7. Stop dragging so the page springs back
8. Try to move any block
8. Try to add a new block

**Expected behavior**
Should be able to continue as normal.

**Desktop (please complete the following information):**
 - OS: iOS 11.4.1
 - Browser: Safari
 - MakeCode Versions: 1.1.43, 3.22.10, dal-integration-1

**Comment by riknoll** [comment]
I can repro this but can't find a good way to debug it. Might need to track down a mac...
