### ISSUE TITLE
Block for inclusion of Bluetooth IO pin service needed

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#110]
It would be great if there was a tray containing Bluetooth related blocks.

In this tray, there should/could be a block per Bluetooth "service".

Dragging a Bluetooth service block into a PXT app would result in the corresponding Bluetooth being included in the generated code.

This issue requests a block for the micro:bit **Bluetooth IO pin service**.

C/C++ code required to include the Bluetooth IO pin service is:

```C/C++
new MicroBitIOPinService(*uBit.ble, uBit.io);
```

Note that inclusion of Bluetooth services has consequences for memory configuration on the micro:bit, specifically with respect to GATT table size. I've suggested an approach to addressing this to Joe Finney of Lancaster University and we're evaluating. Will update issue once this discussion has progressed further.

**Comment by pelikhan** [comment]
- What is the ``config.json`` for this service?

**Comment by bluetooth-mdw** [comment]
There is none.

**Comment by pelikhan** [comment]
Would you want those blocks under the same category as the current "devices" blocks? (take photo, etc...)

**Comment by bluetooth-mdw** [comment]
I think I'd prefer it to be in its own Bluetooth category, similar to the Radio category. So these are Blocks which are not tied to a particular use cause or function... they're Bluetooth building blocks (no pun intended). Does that sound OK to you?

**Comment by pelikhan** [comment]
What happens if you call ``new MicroBitIOPinService(*uBit.ble, uBit.io);`` multiple times?

**Comment by bluetooth-mdw** [comment]
Good question. I'd have to check the code / ask Joe. It ought to be a singleton. The Bluetooth spec allows multiple instances of a service but it would make no sense in this case.

So for all the Bluetooth service blocks I've requested you should be restricted to including one or zero blocks of a given type I think.

**Comment by pelikhan** [comment]
> So for all the Bluetooth service blocks I've requested you should be restricted to including one or zero blocks of a given type I think.

This is not supported. Either the DAL needs to be robust w.r.t. to this or our layer will have to keep track of which service is instantiated.

**Comment by bluetooth-mdw** [comment]
OK, thanks for explaining. I'll mention this to Joe to see what the score is there and update when I know.

**Comment by pelikhan** [comment]
The io pin service is hooked up in m.pxt.io/beta. To try it out: create a new project, click ``more``, ``Add package``, search for ``bluetooth`, then add ``microbit-bluetooth``. You should see the ``Bluetooth`` category pop up.

Martin's todo:
- [ ] add a documentation page ``/docs/reference/bluetooth/io-pin-service.md``
- test if it works :)

**Comment by bluetooth-mdw** [comment]
No, for some reason that didn't work. I flashed (using the nice microbit updater!), paired OK and reset. But I don't even see the device advertising. Is there a way to see the resultant C/C++ main class?

**Comment by bluetooth-mdw** [comment]
It could be memory of course. 

Try 

#define MICROBIT_SD_GATT_TABLE_SIZE             0x500

in microbit-dal/inc/core/MicroBitConfig.h

...just for testing purposes

**Comment by pelikhan** [comment]
Can this be set via config.json ?

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by pelikhan** [comment]
Make sure to remove the "radio" library from the project as it turns off BLE.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by bluetooth-mdw** [comment]
Ah yes you can do it from config.json as well. I think the plan is to remove those duplicate config settings from the header file. Keeps tripping me up!

        "gatt_table_size": "0x500",

Will remove the radio library. Thanks for the tip.

**Comment by bluetooth-mdw** [comment]
Dumb question: How do I remove the radio library? I'm not using any of its blocks but the category is displaying on the left. My code is just:

**Comment by pelikhan** [comment]
"More" -> "Show files" -> click on garbage button next to radio.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by pelikhan** [comment]
Sooo config like this?
```
            "microbit-dal": {
                "bluetooth": {
                    "gatt_table_size": "0x500",
                    "enabled": 1
                }
            }
```

**Comment by bluetooth-mdw** [comment]
Thanks. Removing Radio allowed Bluetooth advertising to start. Is it possible to make the two libraries mutually exclusive in the PXT UI then?

What I see is the IO Pin Service is there but only one of its three characteristics which is almost certainly a sign that the GATT table is too small in that build.

**Comment by pelikhan** [comment]
Please file a bug on the exclusion in the UI....

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by bluetooth-mdw** [comment]
Roger that....

**Comment by pelikhan** [comment]
Martin, could you check the config.json, is that what you expect?
```
            "microbit-dal": {
                "bluetooth": {
                    "gatt_table_size": "0x500",
                    "enabled": 1
                }
            }
```

**Comment by bluetooth-mdw** [comment]
Hi

the full config.json file I have locally right now and therefore use in my yotta builds is:

```
{
    "microbit-dal":{
        "bluetooth":{
            "enabled": 1,
            "pairing_mode": 1,
            "private_addressing": 0,
            "open": 0,
            "whitelist": 1,
            "advertising_timeout": 0,
            "tx_power": 0,
            "dfu_service": 1,
            "event_service": 1,
            "device_info_service": 1
        },
        "reuse_sd": 1,
        "gatt_table_size": "0x700",
        "heap_allocator": 1,
        "nested_heap_proportion": 0.75,
        "system_tick_period": 6,
        "system_components": 10,
        "idle_components": 6,
        "use_accel_lsb": 0,
        "min_display_brightness": 1,
        "max_display_brightness": 255,
        "display_scroll_speed": 120,
        "display_scroll_stride": -1,
        "display_print_speed": 400,
        "panic_on_heap_full": 1,
        "debug": 0,
        "heap_debug": 0,
        "stack_size":2048,
        "sram_base":"0x20000008",
        "sram_end":"0x20004000",
        "sd_limit":"0x20002000",
        "gatt_table_start":"0x20001900"
    }
}
```

Hoping the other values not shown in your fragment are defaults but I'd have to investigate to be sure about this.

**Comment by pelikhan** [comment]
GATT size can be tracked in new bug. The service is exposed now.
