### ISSUE TITLE
Integer Divide is not easy to find in menus because block doesn't match function

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#1100]
The integer divide block can show up in a program when importing from v0

However, it's hard to find this block in the list of blocks because a user looks for something with a slot either side of an operator, like the 'division' block

Instead, this functionality is lurking under the 'square root' block 
![image](https://user-images.githubusercontent.com/147113/44228943-7ed33900-a18e-11e8-93c4-100496f6efe3.png)

Which changes into a two-input block when you select some of the operations
![integer divite](https://user-images.githubusercontent.com/147113/44229050-c659c500-a18e-11e8-8494-b94c21d3fc38.gif)

It's hard to know that the sin/cos/tan  will be there too.
This is compounded by the fact that other operations show up with both options in the menu
![image](https://user-images.githubusercontent.com/147113/44229266-6b749d80-a18f-11e8-830f-4f3648e8c167.png)
Here we have 'min' and 'max' as independent blocks, and we also have 'absolute' as an independent block that isn't in the same drop down as square root.

I think with the addition of these new blocks it might be necessary to do some testing to find out how to make things discoverable

**Comment by riknoll** [comment]
I guess the question is how many blocks are we willing to show in the flyout? The motivation around the dropdown block was to keep the number low; min/max/absolute didn't get included because they were in the old editor.

Does integer division need to be discoverable? It requires more of an explanation than regular division so I thought that compatibility was the main scenario.

**Comment by abchatra** [comment]
We don't want to expose integer divide to students. This is present only for compatibility reasons when some one imports older projects. Won't fix from our end.
