### ISSUE TITLE
comments are broken when you move between blocks and java script

### ISSUE THREAD

**Issue by rhubarbdog** [microsoft/pxt-microbit#1104]
Hi
when you add comments to a list and click between blocks and java comments work as expected. As shown here https://makecode.microbit.org/_8502v7akdEjp

when i add a function in the java as it has parameters it breaks the list's comment and duplicates it in the java so i now have 2 comments. As shown here https://makecode.microbit.org/_4g6g3f1w1f3j

each time i click between blocks and java a new comment is added to the java

**Desktop (please complete the following information):**
 - Linux Mint 18.2
 - Mozilla Firefox
 - Version 60.0.1

and on my raspberry pi
- Rasbian 9.4
- chromium the open source port of Google Chrome
- Version 65.0.3325.181

**Comment by abchatra** [comment]
Fixed
