### ISSUE TITLE
Block for inclusion of Bluetooth magnetometer service needed

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#112]
It would be great if there was a tray containing Bluetooth related blocks.

In this tray, there should/could be a block per Bluetooth "service".

Dragging a Bluetooth service block into a PXT app would result in the corresponding Bluetooth being included in the generated code.

This issue requests a block for the micro:bit **Bluetooth magnetometer service**.

C/C++ code required to include the Bluetooth magnetometer service is:

```C/C++
    new MicroBitMagnetometerService(*uBit.ble, uBit.compass); 
```

Note that inclusion of Bluetooth services has consequences for memory configuration on the micro:bit, specifically with respect to GATT table size. I've suggested an approach to addressing this to Joe Finney of Lancaster University and we're evaluating. Will update issue once this discussion has progressed further.

**Comment by pelikhan** [comment]
- how can this service be tested?
- what is the "config.json" for this service?

**Comment by bluetooth-mdw** [comment]
Per temperature service. No config.json. Using my app or a generic tool.

**Comment by pelikhan** [comment]
``config.json`` tracked in #110
