### ISSUE TITLE
richer control over event handlers

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt-microbit#1129]
**Is your feature request related to a problem? Please describe.**

The current model for registering event handlers is not rich enough. In particular, for a given event pair (E,V), only one handler H can be registered for (E,V) and the last writer wins.  So, for example, if I have a library that does something each time a radio packet is received, using the onPacketReceived event handler, but a user app also registers a handler for onPacketReceived, the library handler will never be called. 

In general, this points to the lack of a "driver model" for MakeCode. The simplest way to address this right now is to allow lower-level packages to register before higher-level packages and user code. Then, an event bubbles up from lower levels to higher levels. 

This also points out the need to consider modes of execution of handlers (immediate, async) and how they work with the "driver model":

```
//   MESSAGE_BUS_LISTENER_REENTRANT
//   MESSAGE_BUS_LISTENER_QUEUE_IF_BUSY
//   MESSAGE_BUS_LISTENER_DROP_IF_BUSY
//   MESSAGE_BUS_LISTENER_IMMEDIATE
```

**Describe the solution you'd like**

My solution (currently implemented in a branch) is to allow a list of event handlers for each (E,V), which is the model actually supported underneath by DAL/CODAL.  Some concerns:
* if you register handlers in a loop, the list can grow without bound...
* do we allow duplicate handlers (recall handlers are really closures, so unbounded in number)?
* need to support removing an event handler (easiest way is to just specify the function; most precise is triple of (E,V,H))
* should we allow app/library to set a global default mode for dealing with event handlers?  How to deal with conflicts?  Or instead of a global mode, should we scope this by "driver model".

**Describe alternatives you've considered**

**Additional context**

**Comment by tballmsft** [comment]
@mmoskal: sounds like a plan. Thanks.

**Comment by abchatra** [comment]
@tballmsft still relevant?
