### ISSUE TITLE
Block for inclusion of Bluetooth temperature service needed

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#113]
It would be great if there was a tray containing Bluetooth related blocks.

In this tray, there should/could be a block per Bluetooth "service".

Dragging a Bluetooth service block into a PXT app would result in the corresponding Bluetooth being included in the generated code.

This issue requests a block for the micro:bit **Bluetooth temperature service**.

C/C++ code required to include the Bluetooth temperature service is:

```C/C++
    new MicroBitTemperatureService(*uBit.ble, uBit.thermometer);
```

Note that inclusion of Bluetooth services has consequences for memory configuration on the micro:bit, specifically with respect to GATT table size. I've suggested an approach to addressing this to Joe Finney of Lancaster University and we're evaluating. Will update issue once this discussion has progressed further.

**Comment by pelikhan** [comment]
How can this service be tested?

**Comment by bluetooth-mdw** [comment]
I have a handy Android app that includes a menu of many wondrous options... you can test any/all services with it. See http://bluetooth-mdw.blogspot.co.uk/p/bbc-microbit.html 

Alternatively there are generic applications like the Nordic nRF Master Control panel app for Android and iPhone that can be used albeit with a little more difficulty.

Let me know and I can send you an apk!

**Comment by pelikhan** [comment]
``config.json`` changes tracked in #110.

**Comment by pelikhan** [comment]
Martin, could you send a PR with the docs for this API?

**Comment by bluetooth-mdw** [comment]
Will do. Might be next week before I get to this but I'll make sure it happens.
