### ISSUE TITLE
Support Font Awesome 5

### ISSUE THREAD

**Issue by CleoQc** [microsoft/pxt-microbit#1130]
Font Awesome is required when developping a package and choosing the representative icon.
Font Awesome 5 has many new icons and they're not web specific. Many of those are appropriate for the Micro:bit.
I was attempting to use the footsteps icon for a step counter when I realized that Font Awesome 5 is not supported yet.

Thanks

**Comment by CleoQc** [comment]
Any hope for this? It's been a year. Just asking if I should keep on hoping.

**Comment by AlasdairAtKitronik** [comment]
I would like to add that this is something which I find regularly frustrating as we create new extensions, there's so many good icons that could be available.

**Comment by PhilAtKitronik** [comment]
Please get this updated! Its more like pot luck trying to find one that will import in and that is relevant to the blocks creating.

**Comment by abchatra** [comment]
@pelikhan do you know what does this entail?

**Comment by pelikhan** [comment]
Ask Sam :) it might be tied to semantic UI

**Comment by CleoQc** [comment]
Look! We even get COVID icons! https://blog.fontawesome.com/covid-19-awareness-icons/

**Comment by AlasdairAtKitronik** [comment]
I'm currently unable to process emails and don't know how long this will be the situation. I will obviously get back to you as soon as is possible, which is likely to be when restrictions to tackle COVID19 are lifted by the UK government. In the meantime Kitronik is currently still open, but running on a skeleton crew. Thanks for bearing with us during this difficult time.

**Comment by PhilAtKitronik** [comment]
I'm currently unable to process emails and don't know how long this will be the situation. I will obviously get back to you as soon as is possible, which is likely to be when restrictions to tackle COVID19 are lifted by the UK government. In the meantime Kitronik is currently still open, but running on a skeleton crew. Thanks for bearing with us during this difficult time.

**Comment by abchatra** [comment]
Done
