### ISSUE TITLE
The scroll bar works very slowly on Firefox when scrolling cursor mouse

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#1145]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta
2. Scroll down to the bottom of the page and click one example to open it
3. Scroll the cursor mouse and observe the scroll bar

**Expected result(Edge, Chrome& IE):**
The scroll bar should work normally
![issue82901com](https://user-images.githubusercontent.com/23466737/44775148-7ffd6080-aba7-11e8-867e-d4c65d8101b0.gif)

**Actual result(Firefox):**
The scroll bar works very slowly on Firefox when scrolling cursor mouse
![issue82901](https://user-images.githubusercontent.com/23466737/44774832-b7b7d880-aba6-11e8-8eeb-b9c830f4c1bb.gif)

**Comment by AimeeCao18** [comment]
The bug still repro on Firefox

**Comment by FranklinWhale** [comment]
If PXT updates the monaco-editor dependency to a version that has microsoft/monaco-editor#1575 fixed, this issue may also be fixed

**Comment by abchatra** [comment]
Closing more than an year old bugs. If this still reproduces please reopen.
