### ISSUE TITLE
String Contains

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt-microbit#1147]
**Is your feature request related to a problem? Please describe.**
I regularly find myself wanting to see if a particular word appears inside a long string of data (e.g. if this string has the word "jump" in it, do this...)

**Describe the solution you'd like**
A javascript and a blocks representation for string.contains.
e.g. if str.contains("jump") { do_something()}
an advanced flag in javascript to help with delimiters:
if str.contains("jump", ",") // would require jump to be at start or end of string or delimited by a comma. If not provided, default would be a space. If "" provided it would be an undelimited search.

Also, I'd like arrays (list) to have the same method, so that a list of words could be used interchangeably as a single string (easy to initialise or pass around) or as a list (easier to grow and shrink dynamically)

**Describe alternatives you've considered**
Currently I write functions but as functions cannot take parameters or return results in blocks view, this is a bit mucky with all the global variables.

**Additional context**
The main thing is that it's hard to do data-driven solutions easily with the current string/list implementations.
Also, strings are great for this because you can easily send them as payloads in radio messages.

**Comment by pelikhan** [comment]
The standard JavaScript function is “includes”

https://www.w3schools.com/jsref/jsref_includes.asp

Otherwise, this seems like a good opportunity to have a package of helper functions.

**Comment by pelikhan** [comment]
``indexOf`` and ``includes`` will be available in the next integration.

**Comment by DavidWhaleMEF** [comment]
Great, thanks @pelikhan - also your point about a package of helpers is a good idea. But these lower level functions will provide better performance, and we can always build a package of more advanced features on top of them.
