### ISSUE TITLE
Copy and paste of blocks through system clipboard

### ISSUE THREAD

**Issue by FranklinWhale** [microsoft/pxt-microbit#1149]
**Is your feature request related to a problem? Please describe.**
Allowing users to share some blocks across devices is important. It is currently impossible to copy some blocks out of the browser without extracting the relevant parts of JavaScript code in the JavaScript editor. That requires knowledge of JavaScript.

**Describe the solution you'd like**
Provide a "Copy to clipboard" option and a "Import blocks from clipboard" option in the context menu of the block editor:
  * The "Copy to clipboard" option will copy the JavaScript representation of the selected block and its descendants to the system clipboard. The JavaScript representation is visible in the tooltip in v0 but is currently missing as reported in #1148.
    
    *NOTE: The copying logic is not the same as that of the "Duplicate" option, which duplicates the selected block only.*
  * The "Import blocks from clipboard" option will open a dialog that has a text area and a button. The user is expected to paste the JavaScript to the text area and click the button to import the blocks.
    
    *NOTE: Modern browsers do not allow read access to the clipboard so a direct "Paste" option cannot be provided (See dotnet/try#67 and Microsoft/monaco-editor#391). However, browsers do provide native copy and paste context menu options to `<textarea>` and it may be used as a workaround.*

The "Copy to clipboard" option should be available in the read-only mode.

**Comment by abchatra** [comment]
There is substantial amount of dev work involved here. We don't have bandwidth to implement this.
