### ISSUE TITLE
Add black and white theme

### ISSUE THREAD

**Issue by lwchkg** [Microsoft/pxt-microbit#1163]
**Is your feature request related to a problem? Please describe.**
I want to create notes/tests/exam papers with screenshots from micro:bit. However, the screenshot cannot print clearly on black and white printers. Current implementation of high contrast mode is also unsuitable for the task.

**Describe the solution you'd like**
Add a option that turns the site into black and white. See the screenshot below for how it could work.

**Describe alternatives you've considered**
See https://userstyles.org/styles/159784/micro-bit-black-and-white. An external style sheet is made to make the blocks black and white. However, this does not affect the screenshot code.

**Additional context**
![screenshot of alternate solution](https://userstyles.org/style_screenshots/159784_after.png)

**Comment by pelikhan** [comment]
We have a “print code” feature in the gear wheel menu. Have you tried it?

**Comment by pelikhan** [comment]
![image](https://user-images.githubusercontent.com/4175913/45054466-f08dfc80-b041-11e8-9e39-c47acaf3b5c3.png)

**Comment by lwchkg** [comment]
@riknoll Just checked the High Contrast theme. Only the color of the menu and background are changed, but sadly nothing is done to the blocks. I guess we can make some real high-contrast themed blocks in the high-contrast theme. (Not sure about the technical details yet, because themes for blocks seems more complex than theme for the menu and background.)

@pelikhan The output is colored, so the print function shouldn't be able to solve my problems. What I need to have blocks (preferably vector graphics) to insert into my lesson notes / exam papers, which are going to be printed out in black and white. BTW, as a separate issue, I would appreciate if you can have "Print", "Download Screenshot" and "Download SVG Screenshot" accessible from the menu (put those in a separate group, of course).

**Comment by pelikhan** [comment]
When output should black-and-white when sent to the printer. We can improve the print CSS to be more readable.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by lwchkg** [comment]
@pelikhan I've made a printout and photographed it here, so we can make a reference from it.

Currently the lines dividing the blocks is nearly invisible. BTW, what is the most worrying for me is how the white-on-gray icons will print when passed to a photocopier. (But it was still a big improvement over the original theme in production.)

Personally I prefer black text on white background for black-and-white prints, because things get complicated (i.e. print quality problems) when the printout is mostly black.

BTW, once you make the decision I might be able to contribute some code. :-)

![img_20180905_085311](https://user-images.githubusercontent.com/4113719/45065118-f93a0d80-b0e9-11e8-9827-1f0dcefc4851.jpg)

**Comment by riknoll** [comment]
@lwchkg check out https://github.com/Microsoft/pxt/pull/4654
