### ISSUE TITLE
RPS teams doc

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1164]
micro:bit-support: 6884

**Describe the bug**
https://github.com/Microsoft/pxt-microbit/blob/master/docs/projects/rps-teams.md

The line "the team with the most players wins the game" is confusing. Does it mean the team that has the greatest number of rocks, paper or scissors wins, or the highest tally of either rocks, paper or scissors? Perhaps it just needs clarifying a bit further.

**Comment by ganicke** [comment]
The project provides description for just one team. Maybe say that: "players with the largest roster are the winners"?
