### ISSUE TITLE
The browser link of feedback page is not clear

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1167]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "More..." -> "Give Feedback" to navigate to feedback page 
3. Observe the browser link 

**Expected result:**
The browser link should be more clear

**Actual result:**
The browser link of feedback page is not clear
![issue90404](https://user-images.githubusercontent.com/23466737/45025268-960a9580-b06d-11e8-8dd2-a4730c519e21.PNG)

**Comment by abchatra** [comment]
P3 won't fix
