### ISSUE TITLE
Bluetooth and Radio libraries need to be made mutually exclusive

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#117]
If the Radio library is included ina  project which uses Bluetooth service blocks then Bluetooth will not "start" on the micro:bit. Request the two libraries be made mutually exclusive in PXT.

**Comment by tballmsft** [comment]
Not clear how we do this. Peli?

**Comment by pelikhan** [comment]
When we merge config.json from multiple packages, we can detect conflicting options and emit an error.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/blob/master/pxtlib/cpp.ts#L430
