### ISSUE TITLE
Packages relying on integer division may not work properly in v1

### ISSUE THREAD

**Issue by FranklinWhale** [Microsoft/pxt-microbit#1172]
**Describe the bug**
Some existing packages, such as [pxt-grove](https://github.com/Seeed-Studio/pxt-grove), [relies on integer division](https://github.com/Seeed-Studio/pxt-grove/blob/master/main.ts#L339) to work properly. Since floating point is enabled in v1, those functions may not work properly.

**To Reproduce**
Compare the result of `grove.createDisplay(DigitalPin.P0, DigitalPin.P14).show(9999)` in v0 and v1.

**Expected behavior**
`9999` is displayed

**Actual behavior**
`9999` is displayed in v0 while `   9` is displayed in v1.

**Comment by pelikhan** [comment]
Opened bug https://github.com/Seeed-Studio/pxt-grove/issues/5

**Comment by FranklinWhale** [comment]
@pelikhan Instead of requiring each impacted extension to update their code, is it possible to automatically transform `/` to `Math.idiv`? The automatic transformation may be enabled for extensions that are released to Github before a specific date to be announced or always enabled unless a comment parameter is set at the beginning of each ts file?

**Comment by pelikhan** [comment]
We have been working with most package authors to update their package. Doing the automatic translation is tricky and requires a lot of additional testing infrastructure. This package should have been flagged by our automated tester. Needs investigation.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pelikhan** [comment]
Tracked in https://github.com/Microsoft/pxt-microbit/issues/1172
