### ISSUE TITLE
window.applicationCache has been removed from firefox v62

### ISSUE THREAD

**Issue by jincheng-me** [Microsoft/pxt-microbit#1177]
the static pkg serve can't be access via firefox latest version;
because the appCache has been removed!

any solution?

**Comment by riknoll** [comment]
I think the appcache was only removed in [non-secure contexts](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache#Browser_compatibility). Are you hosting your own target or just developing locally?

**Comment by jincheng-me** [comment]
OK, ic

i am using this teaching tool in school's LAN by http; so my student can't access the serve via firefox, and more, the chrome warn me that it will also remove the appcache into secure comtexts;

my teaching env is school's LAN, only via IP address to access the serve, it is hard to add the https in my LAN.

there are any solution to me?

**Comment by riknoll** [comment]
We probably shouldn't crash if the appcache isn't available; I don't think there is a workaround... @pelikhan thoughts? This will probably become a more frequent issue as more browsers deprecate the API.

**Comment by riknoll** [comment]
Fixed in next release
