### ISSUE TITLE
v1-beta: blocks accepting an "Action" do not render correctly

### ISSUE THREAD

**Issue by Gadgetoid** [Microsoft/pxt-microbit#1178]
**Describe the bug**
Blocks accepting an "Action", IE: in the form:

```typescript
    //% blockId=touchbit_on
    //% block="When touch pad %touchpad| is %event"
    //% touchpad.fieldEditor="gridpicker" touchpad.fieldOptions.columns=6
    //% event.fieldEditor="gridpicker" event.fieldOptions.columns=2
    //% weight=100
    export function on(touchpad: TouchPad, event: TouchEvent, handler: Action) {
```
Do not render correctly in v1-beta.

**To Reproduce**
1. Go to https://makecode.microbit.org/beta
2. Create a new project
3. Add "https://github.com/pimoroni/pxt-touchbit" as an Extension
4. Drag and drop a `when touch pad < > is < >` block into the editor

![makecode-after](https://user-images.githubusercontent.com/1746967/45155642-915ff180-b1d3-11e8-95dc-ee6647fbd248.png)

**Expected behavior**
Perform the same steps above in the current release version for the expected result.

![makecode-before](https://user-images.githubusercontent.com/1746967/45155635-8c9b3d80-b1d3-11e8-9e18-34cf29b1ac63.png)

**Comment by FranklinWhale** [comment]
It's because the `Action` type has been removed in v1. You may replace it by `() => void` or add `type Action = () => void;` in your namespace.

**Comment by pelikhan** [comment]
@riknoll @mmoskal sounds like a breaking change. Can we get the Action back?

**Comment by mmoskal** [comment]
Should be fine to just add type Action = as mentioned by OP

**Comment by riknoll** [comment]
The action type is still there, I think this is probably a BlocklyLoader regression. I'll take a look
