### ISSUE TITLE
Problem reading out analogue Values from Pin 3, 4 and 10

### ISSUE THREAD

**Issue by fd0cwp** [Microsoft/pxt-microbit#1179]
Hi all, 
I am not sure if this is the right location / way to get help for getting reliable analogue inputs from the pins 3, 4 and 10 of the micro:bit using Python (Mu Eeditor 1.0.0). So I just post my problem and hope for answers. 😊
I would like to measure temperatures at different locations at the same time. So I bought the micro:bit starter kit where the temperature sensor TMP 36 is included to gain some knowledge. It went well so I bought 5 more pieces of this temperature sensor and planned to read them out via the analogue input pins 0, 1, 2, 3, 4 and 10. For the pins 0, 1 and 2 it is working quite well now but the pins 3, 4 and 10 return wrong values. I know that these pins are also used for the display somehow, so I switch off the display at the beginning and then continuously read out the pins in a loop and convert the return values to voltages and then to temperature values.
When I have a look at the voltage, for the first thee pins the read out and converted voltage values fit to the values which I can measure directly at the TMP sensor pins. Unfortunately, the last three pins return a lesser voltage. Surprisingly, when I measure it, it is the same as available on the 3V pin (about 3.3V).
When I just measure the voltage at the micro:bit pins without having anything connected to it, the first three pins show about 1.6V. But the other three show about 3.3V. So something is different there. 
I wanted to play around a little bit with the pull up / down resistors, but it seems that Python does not give access to it. Also, I found no way to specify that these pins are now used for input to ensure that they do not output a voltage.
When I similarly implement it in MakeCode as blocks / JavaScript it seems to work correctly. But I cannot use this as I want to make many temperature measurements, collect them and later evaluate them e.g. with MS Excel. For this purpose, I create a file on the micro:bit with open(fileName, 'w') and write the read out and converted values into it to later copy the file to a computer.
Is it also somehow possible to store these values using MakeCode?
Thank you in advance for your feedback!
Best regards, 
Christoph

As advised, here is further info:
**source code:**
```
from microbit import *

fileName = 'data.txt' 
values = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
valuesMin = [4, 4, 4, 4, 4, 4]
valuesMax = [1021, 1023, 1023, 1022, 1022, 1022]
volts = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
temps = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
uRef = 3270

display.show(Image.HAPPY)
sleep(1000)
display.off()

with open(fileName, 'w') as my_file:
    while not button_a.was_pressed():
        
        values[0] = pin0.read_analog()
        values[1] = pin1.read_analog()
        values[2] = pin2.read_analog()
        values[3] = pin3.read_analog()
        values[4] = pin4.read_analog()
        values[5] = pin10.read_analog()
        
        for x in range(6):
            volts[x] = values[x] - valuesMin[x]
            volts[x] /= valuesMax[x] - valuesMin[x]
            volts[x] *= uRef
            temps[x] = (volts[x] - 500) / 10
            
            my_file.write(str(x) + ': ' + str(values[x]))
            my_file.write(' ^= ' + str(volts[x]) + 'mV')
            my_file.write(' ^= ' + str(temps[x]) + '°C')
            my_file.write('\r\n')
        
        my_file.write('\r\n')
        sleep(1000)
        
display.on()        
display.show(Image.ASLEEP)
```

**Output:**
0: 233 ^= 736.312mV ^= 23.6312°C
1: 233 ^= 734.867mV ^= 23.4867°C
2: 234 ^= 738.076mV ^= 23.8076°C
**3: 203 ^= 639.224mV ^= 13.9224°C
4: 204 ^= 642.436mV ^= 14.2436°C
5: 203 ^= 639.224mV ^= 13.9224°C**

0: 233 ^= 736.312mV ^= 23.6312°C
1: 232 ^= 731.658mV ^= 23.1658°C
2: 234 ^= 738.076mV ^= 23.8076°C
**3: 204 ^= 642.436mV ^= 14.2436°C
4: 204 ^= 642.436mV ^= 14.2436°C
5: 204 ^= 642.436mV ^= 14.2436°C**

As all sensors are near to each other, so they should have the same values like for the first three sensors.

When I place the sensors connected to pin 0 and 3 between my fingers, also the value for the fourth sensor increases but too much:
**0: 242 ^= 765.25mV ^= 26.525°C**
1: 226 ^= 712.404mV ^= 21.2404°C
2: 232 ^= 731.658mV ^= 23.1658°C
**3: 251 ^= 793.408mV ^= 29.3408°C**
4: 184 ^= 578.192mV ^= 7.81924°C
5: 183 ^= 574.98mV ^= 7.49802°C

**0: 241 ^= 762.035mV ^= 26.2035°C**
1: 227 ^= 715.613mV ^= 21.5613°C
2: 232 ^= 731.658mV ^= 23.1658°C
**3: 252 ^= 796.621mV ^= 29.6621°C**
4: 181 ^= 568.556mV ^= 6.85559°C
5: 186 ^= 584.617mV ^= 8.46167°C
Interestingly, the values on pin 4 and 10 go down in this case.

**Comment by pelikhan** [comment]
I am afraid we cannot help you with MicroPython. We have a beta quality file system at https://github.com/Microsoft/pxt-filesystem that you could use.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by fd0cwp** [comment]
Hi @pelikhan, 
Thank you for the hint with the filesystem package. I added it to my project and created a small sample code:
```
files.appendString(
    "output.txt",
    "appendString"
)
files.appendLine(
    "output.txt",
    "appendLine"
)
files.appendNumber(
    "output.txt",
    0
)
files.fsClose(0)
basic.showIcon(IconNames.Heart) 
```
I can download the code to the microbit without errors and I see the heart on the microbit.
Unfortunately, I do not see the file in the Windows Explorer and I also do not see an option to access it in the MakeCode IDE. Did I miss something?
Best regards, Christoph

**Comment by pelikhan** [comment]
The bootloader does not support exposing those files via the MSC interface so you need to extract them “manually via serial”. There should be a block “sendToSerial”-ish to make it easier.
For example hook the AB press event to do that.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by fd0cwp** [comment]
Thank you for the quick answer!
I had a look for the serialization but I think this does not meet my needs as I would like to run the microbit standalone for some hours performing the measurement.
Additionally, I got another answer and now the Python version works correctly. So I will follow this approach for now.
The problem I see is the very limited flash memory of the microbit. If this becomes an issue, I might pick up the serialization approach again but obviously this needs some counterpart (receiving the data and writing it to a file) running on a connected computer which seems to be quite some additional effort for me.
Ideally, I would like to attach an external file storage (hard disk or memory stick) to the microbit where I can store (a lot of) data. So, if you further develop the file system project, maybe you can implement the possibility to not only store a file internally, but also externally? 😊
Best regards, Christoph

**Comment by pelikhan** [comment]
Companies like SparkFun provide shields to easily log data on a sim card

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
