### ISSUE TITLE
No menu option for deleting a package 

### ISSUE THREAD

**Issue by rharbird** [Microsoft/pxt-microbit#118]
I can add the Neopixel package using More->Add Package.

To remove the package I have to edit the text of Project Settings. This is not intuitive.

FYI, the i2c-fram package fails to load when added, nevertheless, an entry is left in the dependencies in Project Settings.

**Comment by pelikhan** [comment]
You can remove the package from the file list (which is hard to get to right now).

i2c-fram should be removed.

**Comment by pelikhan** [comment]
i2c-fram broken?

**Comment by mmoskal** [comment]
Works for me. Also there is now a button to remove package thanks to @pelikhan
