### ISSUE TITLE
While true loop with serial write causes CPU hogging / browser unresponsive 

### ISSUE THREAD

**Issue by microbit-giles** [Microsoft/pxt-microbit#1182]
**Describe the bug**
A while true loop with a serial write block causes my CPU to go to over 100% and the editor becomes unresponsive making it hard to remove the offending serial block and/or start a fresh project.

**To Reproduce**
1. Go to 
https://makecode.microbit.org/beta?webusb=1#editor
2. Load blocks like this:
![killer blocks](https://user-images.githubusercontent.com/42380137/45175487-7c03bb00-b205-11e8-8f46-04eb3dff9c83.png)
3. Browser becomes unresponsive, Chrome CPU usage goes to 100%, fans on my MacBook Pro start whirring. Almost impossible to remove the offending block as the browser is now so unresponsive.

**Expected behavior**
This is probably not a bug as such but it is confusing behaviour especially for a child/novice. Some way of trapping CPU-thrashing loops in the simulator might be good or at least preventing the blocks re-appearing when the editor is re-opened?

**Screenshots**
<img width="1345" alt="screen shot 2018-09-06 at 18 11 42 copy" src="https://user-images.githubusercontent.com/42380137/45175638-cedd7280-b205-11e8-88b5-08415ee4b17c.png">

After a very long delay (several minutes) Chrome finally reported the page as unresponsive:

<img width="482" alt="screen shot 2018-09-06 at 18 17 52" src="https://user-images.githubusercontent.com/42380137/45175672-e0bf1580-b205-11e8-9688-375697f03dc7.png">

**Desktop (please complete the following information):**
 - OS: OS X High Sierra 10.13.4 (17E199)
 - Browser: Chrome 
 - Version: 68.0.3440.106 (Official Build) (64-bit) for OS X

**Smartphone (please complete the following information):**
 - Device: N/A

**Comment by abchatra** [comment]
This is basically request for query continue. Where we should pause the simulator at timed interval and see if there is a infinite loop hogging the CPU.

**Comment by abchatra** [comment]
This is fixed
