### ISSUE TITLE
How can I create a function block with a param in gridpicker by image list just like basic.showIcon() ?

### ISSUE THREAD

**Issue by slipperstree** [Microsoft/pxt-microbit#1183]
How can I create a function block with a param in **gridpicker by image list** just like `basic.showIcon()` does?
I noticed that the "enum IconNames" has an option named `blockimage=1`, but I don't know how to use this option and also I don't know where those small pictures are stored.
Can some one give me some suggestion please?
Thank you.

**Comment by riknoll** [comment]
You need to include the assets as jres files.


[Here](https://makecode.com/jres) is some info for how to convert your icons to jres

[Here](https://github.com/Microsoft/pxt-common-packages/tree/master/libs/light) is a package that adds icons for a grid picker (this one is used in our makecode.adafruit.com editor).

The block is defined here:
https://github.com/Microsoft/pxt-common-packages/blob/master/libs/light/neopixel.ts#L1421

It's a little different from your case becuase you probably want an enum but if you look at the animations defined in that file, you'll notice they have a `jres` annotation which tells PXT to look for a similarly named icon file in the jres directory.

Hope that helps!
