### ISSUE TITLE
Cannot return to code editor after editing text of project settings 

### ISSUE THREAD

**Issue by rharbird** [Microsoft/pxt-microbit#119]
Choosing "Edit Settings as Text" allows me to edit project settings. I cannot return to the code editor without choosing to open the project again.

Rae

**Comment by tballmsft** [comment]
There is a "Back to Code" button for this. Peli - it would be good to highlight this button. It is too subtle a shift.

**Comment by tballmsft** [comment]
Ah ha! I didn't go all the way - indeed, the "Back to code" button disappears when you Edit Settings as Text. Good catch!

![image](https://cloud.githubusercontent.com/assets/10767146/16063112/a68c8d38-3265-11e6-86b0-6d3397e9673c.png)
