### ISSUE TITLE
v1 UI feedback

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1190]
from microbit-support: 17413

"I find the new blocks 
(a) more difficult to visually parse and read, and 
(b) the larger size means fewer blocks can fit on the same screen, and thus programs with any complexity will start requiring 3 and 4 total screen scrolls.  If zoom out is used to fit more on the screen, the smaller text will mean the labels will become unreadable more quickly.  Here is a side by side comparison:

![image1](https://user-images.githubusercontent.com/31242877/45205371-d9d1ea80-b279-11e8-8448-1cfe3de9f24f.png)

Notice that "on start" is both larger print in the current version, and less dead space above and below, compared to smaller text, more wasted space above and below, and more "blurring" to the text due to the anti-aliasing having fewer pixels to work with:

![image](https://user-images.githubusercontent.com/31242877/45205529-55339c00-b27a-11e8-81c8-dbac2ae782d8.png)

"

**Comment by pelikhan** [comment]
We are aligning the block rendering style of Scratch 3.0. You need to take those comments to the Scratch team.

**Comment by pelikhan** [comment]
Probably file a bug in their github repo.

**Comment by CleoQc** [comment]
The larger blocks in Scratch are meant for tablets, phones, and all touch interfaces. I'm not certain that microbits would even work with those (would they?)

**Comment by HyperDuino** [comment]
Changing the block style for tablets, and in particular iPads, is moving to the past, not the future.  Chromebooks are already past the 50% deployment in schools, and I see no sign whatsoever of that slowing.  The school audience is very different than the home (phone) audience.  Making the blocks bigger reduces the environment's utility on Chromebooks and its overall usefulness.

Is there any way we can have any influence on this?  At the very least, how about if there is a setting for block size to that they can retain their current form on laptops, and have a different form for phones.

**Comment by pelikhan** [comment]
Please try out the latest beta. The screenshots on this issue are outdated.
