### ISSUE TITLE
can't compile and download .hex file after pxt staticpkg 

### ISSUE THREAD

**Issue by jincheng-me** [Microsoft/pxt-microbit#1191]
Hi

i use the command `pxt staticpkg --output ../release`, build the pxt into static files(js/css/html)
then `http-server -c-1 ../release`, every thing run well

i use the editor to make a robot car,
when i download the code to local desktop, an error occur！

there are two request to back-end serve:
1: /clientconfig (get method)
2: /compile/extension (post method)

i think the browser client is asking for a compile for code, is it right ?

are there some reference manual to study for me ?

Tks

**Comment by pelikhan** [comment]
``staticpkg`` is not support in the master branch of microbit. Are you using the v1 branch? (it is not supported there either but it might work).

**Comment by pelikhan** [comment]
The support for staticpkg is broken in v0. Please use v1.

Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by JeffBrilliantLabs** [comment]
Did you remember to link pxt microbit to pxt?  From the pxt-microbit folder you have to npm link ../pxt
I had same issue and then realized I hadn't linked pxt or common packages to pxt-microbit

**Comment by pelikhan** [comment]
Heads: v1 was merged into master. Use master from now on.

**Comment by abchatra** [comment]
Fixed
