### ISSUE TITLE
There is no paste function on JavaScript content pane except IE

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#1192]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "{ }JavaScript" to switch to JavaScript content pane
3. Right click and observe

**Expected result(IE):**
There should have paste function on each browser
![issue90703c](https://user-images.githubusercontent.com/23466737/45210542-7e781a80-b2c2-11e8-98f2-272fa725aef9.png)

**Actual result(Edge, Chrome & Firefox):**
There is no paste function on JavaScript content pane except IE
![issue90703](https://user-images.githubusercontent.com/23466737/45210551-82a43800-b2c2-11e8-8461-87cbf640d228.png)

**Comment by FranklinWhale** [comment]
I think this was reported in Microsoft/monaco-editor#391. As rchande said in https://github.com/dotnet/try/issues/67#issuecomment-380166762, "Browsers other than Internet Explorer don't allow websites to paste from the clipboard".

**Comment by AimeeCao18** [comment]
The bug still reproduce

**Comment by Helen09** [comment]
Please help close this issue, thanks.
