### ISSUE TITLE
right-click to delete a project

### ISSUE THREAD

**Issue by HyperDuino** [Microsoft/pxt-microbit#1195]
I would like to be able to right-click on a project in the gallery to get an option to delete it.  Untitled and old versions of projects accumulate very quickly, and it can be tedious to have to open each one, click on settings, delete, confirm, etc.

![image](https://user-images.githubusercontent.com/13832091/45259855-c57e1280-b38b-11e8-8cf9-f3fcd4e76617.png)

**Comment by abchatra** [comment]
@Jaqster - fyi

**Comment by Jaqster** [comment]
Yes, please 👍

**Comment by abchatra** [comment]
Fixed by script manager in /beta
