### ISSUE TITLE
After clicking the guide link, the font size of link doesn't have any change 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1198]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta
2. Click "Microsoft" on the top-right corner of the home page
3. Click guide link such as "About", "Get Started", "Resources" on the top of the page

**Expected result:**
After clicking the guide link, the font size of link should have a change  

**Actual result:**
After clicking the guide link, the font size of link doesn't have any change 
 ![issue91001](https://user-images.githubusercontent.com/23466737/45285617-2b96a100-b516-11e8-94ea-3ab677ffa32b.gif)

**Comment by abchatra** [comment]
This site is owned by Microsoft.com owners. We don't have control. I am closing it as external and hopefully propagate this to other team
