### ISSUE TITLE
Deleting a project from More -> Project Settings is confusing

### ISSUE THREAD

**Issue by rharbird** [Microsoft/pxt-microbit#120]
Is it possible to see a list of my projects from a menu option? at the moment I can only see my projects from the "Open Project" dialogue. 

I would like to be able to delete a project when viewing the list of projects.

Rae

**Comment by pelikhan** [comment]
Currently, you would have to click on "more" -> "show files" -> click on the "delete" icon near "neopixel".

**Comment by abchatra** [comment]
This is not in our plans.
