### ISSUE TITLE
Chrome can't download screenshot in some program

### ISSUE THREAD

**Issue by shaoziyang** [Microsoft/pxt-microbit#1203]
**Describe the bug**
Chrome and Edge can't download screenshot in some program using makecode beta (V1), if try to download, it will get network error, but firefox works with same program. 

**To Reproduce**
1. open url below using **Chrome** or **Edge** browser.
2. Click Edit button
3. In makecode beta editor, right click and choice download screenshot
4. It will get Netwrok error

https://makecode.microbit.org/_7ARVJ0eo2a7H

**Expected behavior**
Chrome and Edge can't download screenshot in some program, if try to download screenshot, it will get error, but firefox works fine. 

**Screenshots**
![gif](https://user-images.githubusercontent.com/1037534/45333063-b3c48700-b5a6-11e8-8633-c99cfecf5409.gif)

**Desktop:**
 - OS: Win10, ubuntu 18.04
 - Browser: Chrome 67, 71, Edge

**Comment by pelikhan** [comment]
We try to generate a 1400x2000 png files which becomes longer that the encoded URL max length.
