### ISSUE TITLE
Simulator shows differently after adding package "Neopixel"

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#1205]
**Repro steps:**
1. Open shared project with different browsers
https://makecode.microbit.org/_UdqAj60AzELj
2. Click "Edit" to go to editor page
3. Move cursor mouse under simulator and observe

**Expected result(Firefox):**
![issue91101](https://user-images.githubusercontent.com/23466737/45352308-cd87bd80-b5ea-11e8-96d1-4ea9d1303182.gif)

**Actual result(Edge&Chrome):**
![issue91102](https://user-images.githubusercontent.com/23466737/45352322-d24c7180-b5ea-11e8-90e4-43f6dd13db3e.gif)

**Actual result(IE):** 
![issue91103](https://user-images.githubusercontent.com/23466737/45352329-d5dff880-b5ea-11e8-85f6-e33e9c6a38b3.gif)

**Comment by abchatra** [comment]
Closing more than an year old bugs. If this still reproduces please reopen.
