### ISSUE TITLE
"Tutorials" & "Games" except "Examples" don't have brief introduction on home page

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1206]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta 
2. Scroll down the scroll bar and click examples under "Tutorials" & "Games" one by one
3. Observe the opened window

**Expected result:**
Each tutorial and game should have a brief introduction 
![compare911](https://user-images.githubusercontent.com/23466737/45353698-22790300-b5ee-11e8-9c68-adc9051e3c6b.PNG)

**Actual result:**
"Tutorials" & "Games" except "Examples" don't have brief introduction
![issue91104](https://user-images.githubusercontent.com/23466737/45353681-17be6e00-b5ee-11e8-839e-5f2e3a6a89ed.gif)

**Comment by pelikhan** [comment]
@ganicke example will eventually go away as projects

**Comment by ganicke** [comment]
OK. I'll just fix the other categories with missing descriptions then.

**Comment by ganicke** [comment]
Fixed in #1222
