### ISSUE TITLE
Error shows when loading tutorial "Square"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1215]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta
2. Scroll down the scroll bar to "Turtle" and click "Square" 
3. Click "Start Tutorial" 

**Expected result:**
The tutorial should can load normally

**Actual result:**
Error shows when loading tutorial "Square"
![issue91202](https://user-images.githubusercontent.com/23466737/45406712-e3a08700-b699-11e8-8a23-71dccde96bfa.gif)

**Comment by pelikhan** [comment]
Requires https://github.com/Microsoft/pxt/commit/424ae6205c22f0ba2e2438127bb870ee009e30d5
