### ISSUE TITLE
Development lifecycle for code on microprocessor: Design, Develop, Debug requires serial monitor

### ISSUE THREAD

**Issue by rharbird** [Microsoft/pxt-microbit#122]
Younger learners need to debug even small amounts of code with the aid of all the outputs available to them: LEDs, print statements etc. A serial monitor is vital to this process. At the moment, the simplest thing for students to do is use the serial monitor that comes with the Arduino IDE - which can be used for both reading and writing.

Would prefer a more integrated solution than putty, the Arduino IDE etc.

**Comment by pelikhan** [comment]
We are still working on a smooth serial support. Please take a look at [](https://m.pxt.io/device/serial) as a start.

**Comment by pelikhan** [comment]
We are still working on the "debugger" support.

**Comment by tballmsft** [comment]
The  simulator - clearly not a replacement for the hardware - does allow rapid design/develop/debug for many scenarios.

**Comment by pelikhan** [comment]
Debugging is a missing feature that should come in.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by rharbird** [comment]
Thank you. Realise this is an enhancement. Serial read and write with serial monitor is important for learners using the board.

**Comment by pelikhan** [comment]
Serial is well supported and can even be streamed from the cloud. However it requires to install something on the client as no browser provides an API for it.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by abchatra** [comment]
Closing for now. Debugger is a separate feature which will be tracked in pxt repo
