### ISSUE TITLE
The block number range is from 4 to 400

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1224]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "Music" then drag block "set tempo to" and put it under "forever"
3. Drag the scroll bar to change the number

**Expected result:**
The block number range should from 0 to 400
![compare913](https://user-images.githubusercontent.com/23466737/45479303-b545a900-b778-11e8-9fa5-cc493ac0cf01.gif)

**Actual result:**
The block number range is from 4 to 400
![issue91301](https://user-images.githubusercontent.com/23466737/45479298-b080f500-b778-11e8-9ddb-5aecf4957b86.gif)

**Comment by AimeeCao18** [comment]
The bug still repro

**Comment by abchatra** [comment]
Zero beats per second doesn't makes no sense. So 4 is just a starting point, even that is low. This is intentional.
