### ISSUE TITLE
Make Fields more noticeable

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-microbit#1228]
Field colors are not consistent.  Make sure all Fields have the same darker background color.  For example, Show Icon field should be the same darker hue that you see for the "beat" field in the Play Tone block.

Can we also apply the same subtle white outline on hover to Fields that we're doing for nested blocks?

<img width="668" alt="blockfields" src="https://user-images.githubusercontent.com/22108954/45500506-a557a600-b733-11e8-9fe9-fa07fcc44366.PNG">

**Comment by pelikhan** [comment]
This seem to be a general Scratch 3.0 design decision
![image](https://user-images.githubusercontent.com/4175913/45500797-5e1de500-b734-11e8-9213-1bcf6ee355db.png)

**Comment by riknoll** [comment]
Bringing this over from the other thread:

A note on dropdown shapes:
* Round dropdowns are blocks and can be pulled out of the parent block (or if they are a shadow block, they can have other blocks placed on top of them).
* Rectangular dropdowns are "fields" which are fixed and cannot be removed from the parent block or covered.

**Comment by riknoll** [comment]
Someone needs to implement:
* Button states for fields (none, hover, active)

* Change the cursor to pointer over fields
