### ISSUE TITLE
Using intellisense to autocomplete pins.i2cWriteBuffer() fails 

### ISSUE THREAD

**Issue by rharbird** [Microsoft/pxt-microbit#123]
Using intellisense to autocomplete pins.i2cWriteBuffer() fails with "error, invalid character."

**Comment by tballmsft** [comment]
Indeed, there is a funny character there...

![image](https://cloud.githubusercontent.com/assets/10767146/16063241/2553d73e-3266-11e6-9352-4e357e131976.png)

**Comment by pelikhan** [comment]
This is the symbol that the intellisence inserts when we don't have a default construct for a type.

**Comment by tballmsft** [comment]
Hmm... we can do better than that... I'll take a look.

**Comment by abchatra** [comment]
I can't repro this issue.
