### ISSUE TITLE
There is no simulator in "Spiral" & "Scanner" tutorial

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#1232]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta
2. Scroll down scroll bar to "Turtle" and click "Spiral" & "Scanner"
3. Click "Show Instructions" to open tutorial 
4. Click "triangle" button and observe

**Expected result:**
There should show simulator in "Spiral" & "Scanner" tutorial

**Actual result:**
There is no simulator in "Spiral" & "Scanner" tutorial
![issue91401](https://user-images.githubusercontent.com/23466737/45527839-39973b00-b810-11e8-85c9-9d2941506c52.gif)

**Comment by AimeeCao18** [comment]
The bug still repro

**Comment by abchatra** [comment]
@ganicke Is this a documentation issue or product issue? Do you know?

**Comment by ganicke** [comment]
Seems the embedded sim doesn't load in a document when an extension (package) is necessary. The sim frame needs to know about what's in the ``package`` tag from hosting page. In this case it's the `turtle` extension. This is a "doc system" bug.

**Comment by ganicke** [comment]
Same problem as in #1608

**Comment by Helen09** [comment]
closed as fixed
