### ISSUE TITLE
Coin Flipper Tutorial typo

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-microbit#1247]
In Step 6 "your" instead of "you"

![tutorialtypo](https://user-images.githubusercontent.com/22108954/45576082-9c95cb80-b82a-11e8-9486-30d0a8d9484c.PNG)

Galen, if you have time, can you just go through all the Tutorials to double check for typos?

Thanks!

**Comment by ganicke** [comment]
Fixed in #1250
