### ISSUE TITLE
Show LED's not importing correctly from old script

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-microbit#1248]
Try importing this file

[microbit-Sun-Moon.hex.txt](https://github.com/Microsoft/pxt-microbit/files/2384978/microbit-Sun-Moon.hex.txt)

The Show LED blocks are blank

**Comment by Jaqster** [comment]
Was able to repro from a more recent program too.  Try importing: https://makecode.microbit.org/_eVA7sYRT6i4W

**Comment by pelikhan** [comment]
@riknoll related to your upgrade changes?

**Comment by riknoll** [comment]
We changed the XML format in v1, so I would assume it's related to that

**Comment by pelikhan** [comment]
Upgrade code needs to be updated then.

**Comment by riknoll** [comment]
Never mind, it's my fault. Looks like the target version in the project header is being overridden. I guess it isn't present in old scripts so it's getting filled in by the new editor.
