### ISSUE TITLE
Documentation for package management with pxt cli needs improvement

### ISSUE THREAD

**Issue by rharbird** [Microsoft/pxt-microbit#125]
Please can someone improve the  documentation for package management for the microbit using pxt cli?

In particular, I would like to create some packages. I have pxt installed successfully and can run pxt serve.

Thank you,

Rae

**Comment by tballmsft** [comment]
Here's what we have for now... https://www.pxt.io/target-creation

**Comment by mmoskal** [comment]
Docs have been updated at https://www.pxt.io/packages and https://codethemicrobit.com/packages
