### ISSUE TITLE
Delete all blocks doesn't work in app

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#1251]
In the Windows 10 app, the right-click Workspace 'Delete all blocks' command doesn't work.

**Comment by abchatra** [comment]
This is not a regression. Blocks are not able to delete in v0 as well. We should investigate.

**Comment by abchatra** [comment]
I do believe this is because of inability to pop up the are you sure dialog.

**Comment by pelikhan** [comment]
We should not be using the native js dialog anymore in blockly so this should be fixed by now.

**Comment by abchatra** [comment]
Closing old windows10 app bugs.
