### ISSUE TITLE
It should be 'us' in Chinese interface.

### ISSUE THREAD

**Issue by shaoziyang** [Microsoft/pxt-microbit#1255]
**Describe the bug**
There is a translation error here, it should be **us**.

**To Reproduce**
1. Go to 'input'
2. Click on 'more'

![us](https://user-images.githubusercontent.com/1037534/45592841-194fb380-b9ab-11e8-81c6-be4851046ed7.jpg)

**Comment by pelikhan** [comment]
Would you want to fix it in our crowdin project? Https://makecode.com/translate

**Comment by abchatra** [comment]
Closing here as this part of translation. 
Thanks @shaoziyang filing this. If possible please fix this in Crowdin.

**Comment by shaoziyang** [comment]
crowdin is too slow to edit. I use it before and give it up.
