### ISSUE TITLE
The text in "Square" banner is not complete in the 4th step

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1257]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta
2. Scroll down to "Turtle" -> click "Square" -> click "Start Tutorial" -> navigate to 4th step
3. Observe the text in the banner

**Expected result:**
The text in the banner should be complete

**Actual result:**
The text in the banner is not complete in the 4th step
![issue91701](https://user-images.githubusercontent.com/23466737/45609202-6f932400-ba89-11e8-8e1e-c6436b7a4526.gif)

**Comment by pelikhan** [comment]
We need to display 3 lines in our tutorial view.

**Comment by pelikhan** [comment]
Fixed in https://github.com/Microsoft/pxt-microbit/commit/0b30698fbcae71615aacc60340e3c8a1e1ef8229
