### ISSUE TITLE
The border of package "microturtle" is not clear on high contrast mode

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1259]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "More..." -> "High contrast on" to open high contrast mode
3. Click "Advanced" -> "Extensions" -> observe package "microturtle"

**Expected result:**
The border of package "microturtle" should be clear
 
**Actual result:**
The border of package "microturtle" is not clear on high contrast mode
![issue91703](https://user-images.githubusercontent.com/23466737/45616099-0cad8700-baa1-11e8-946d-c490392bc74a.PNG)

**Comment by abchatra** [comment]
This is a minor UI bug, Closing it as won't fix.
