### ISSUE TITLE
Allow Bluetooth pairing mode to be selected

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#126]
This may be difficult or impossible today with the runtime code as it is but at the very least I'd like to submit this as a placeholder for future consideration (I'll be creating a corresponding issue against the runtime DAL though).

There are/will be three security levels supported for micro:bit

a) No security - pairing is not required. No link encryption is used.
b) Just Works pairing - this is new and not yet in the main DAL codebase but it's coming soon (PR waiting for LU)
c) Passkey pairing - this is the current default in use at microbit.co.uk

(C) offers most protection during pairing but requires user interaction. (B) is a less secure pairing procedure but requires much less user interaction... initiating pairing is all that's required... no random numbers to enter etc. 

Some applications will favour ease of use over security whereas others will want the best security on offer.

It would be good to select a suitable default for whenever Bluetooth is in use but provide a Bluetooth Configuration block which allows the pairing method to be selected (and maybe other config options could end up in this block). You may well have a better way of approaching this... I'm totally open to ideas regarding how it's done of course..... just sharing the contents of my head on this topic :-)

The reason I say it may be difficult today is that the options are in a C header file not config.json today. I'll request they be moved to config.json to make this easier.

**Comment by pelikhan** [comment]
Please file a bug into the DAL about making this configurable.Then, we would be able to do something about this. This would most likely require to create "special" packages that enable each mode. We currently do not support setting custom config settings through blocks (and won't support that any time soon).

**Comment by abchatra** [comment]
Closing as per Peli comments (Please file a bug into DAL first)

**Comment by bluetooth-mdw** [comment]
In fact I've made the required change and have a PR pending. 

See https://github.com/lancaster-university/microbit-dal/pull/223
