### ISSUE TITLE
The number on content pane shows "NAN" when moving cursor mouse on simulator on IE

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#1265]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "{}JavaScript" to switch to JavaScript mode 
3. Copy below code on content pane
basic.forever(function () {
    led.plotBarGraph(
        input.acceleration(Dimension.X),
        1023
    )
})
4. Click "Show console" under simulator and move cursor mouse on simulator and observe content pane 

**Expected result(Edge, Chrome & Firefox):**
The number on content pane should change 
![issue918compare](https://user-images.githubusercontent.com/23466737/45673141-7d65a980-bb5c-11e8-9052-7076e240bd1b.gif)

**Actual result(IE):**
The number on content pane shows "NAN" when moving cursor mouse on simulator on IE
![issue91801](https://user-images.githubusercontent.com/23466737/45672947-092b0600-bb5c-11e8-9594-31cb4dd57b61.gif)

**Comment by abchatra** [comment]
Good catch @Helen09

**Comment by Helen09** [comment]
@abchatra Thanks!

**Comment by AimeeCao18** [comment]
The bug still repro

**Comment by abchatra** [comment]
No support for IE11 anymore
