### ISSUE TITLE
Bluetooth GATT table size needs to be set according to the Bluetooth services selected

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#127]
Hi, I just tested this:

```
bluetooth.startAccelerometerService();
bluetooth.startIOPinService();
bluetooth.startLEDService();
bluetooth.startTemperatureService();
bluetooth.startMagnetometerService();
bluetooth.startButtonService();
basic.showString("IO PIN");
```

Only three custom services were visible when I ran the resultant hex file and one service I checked had missing characteristics. This is a sure sign of the GATT table being insufficiently large as set in config.json:

```
        "gatt_table_size": "0x700",
```

Note that 0x700 is the largest value allowed (range is between 0x300 and 0x700).

As mentioned I've suggested a way of letting the DAL figure out its GATT table size and set it dynamically. Joe F is considering this.

Until then and at least while we're testing, maybe you should use the max 0x700 value whenever a Bluetooth service block is included? Just a thought....

Cheers

Martin

**Comment by pelikhan** [comment]
What is the complete "config.json" you are using?

**Comment by pelikhan** [comment]
I have now the Nordic app but I have no clue how to test this. We need VERY detailled steps in order to use this. Does it just work? Do I need to get the device in pairing mode? etc...

**Comment by pelikhan** [comment]
Martin, at this point, I think our time would be better spent by setting you up with a developer setup for PXT so that you can tinker with the changes. Then, you can simply submit a PR to get them in :) Let's skype!

**Comment by abchatra** [comment]
Closing this issue as there is no traction here.
