### ISSUE TITLE
Neopixel not working on hardware with v1

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt-microbit#1272]
**Describe the bug**
Neopixel not working on hardware with v1, but only when using radio with it as well. Perhaps a memory leak?

**To Reproduce**
Here's a sample code the repros.

https://makecode.microbit.org/_czVKw38zE4bU

**Comment by mmoskal** [comment]
Works for me (doesn't repro)

Note that you cannot power 30 neopixels from the 3V pad on the microbit. And if you power them with a 5V source, then the data pin at 3V might or might not work. Radio takes quite a bit of power on the MCU, so that might be a factor as well.

**Comment by abchatra** [comment]
No repro in the wild.
