### ISSUE TITLE
Some packages don't have pictures

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1275]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click Advanced -> "Extensions" -> input "a" in the search box and observe the packages

**Expected result:**
Each package should have picture

**Actual result:**
Some packages don't have pictures
![issue92002](https://user-images.githubusercontent.com/23466737/45810492-3f53bb80-bcfd-11e8-9897-a98e0965da17.PNG)

**Comment by abchatra** [comment]
@microbit-mark Can you ask package others to update an image for these packages?

**Comment by microbit-mark** [comment]
Have polled all these tickets again.

https://github.com/CoderDojoOlney/pxt-olney/issues/6
https://github.com/srs/pxt-bitbot/issues/15
https://github.com/chevyng/pxt-ucl-junkrobot/issues/4
https://github.com/Microsoft/pxt-bluetooth-temperature-sensor/issues/2
https://github.com/PaulDFoster/pxt-microbit-GY521/issues/5

**Comment by abchatra** [comment]
I am closing this issue from our end as there is no further action from our end.
