### ISSUE TITLE
Change enum checkmark to white v1

### ISSUE THREAD

**Issue by halspeed** [Microsoft/pxt-microbit#1276]
Change enum checkmark from black to white for more contrast

![image](https://user-images.githubusercontent.com/29285304/45848086-d1a29200-bcf2-11e8-90f8-70f3f40986df.png)

**Comment by abchatra** [comment]
Please use the bug or feature template. Thanks!

**Comment by halspeed** [comment]
I just followed what I saw in #1230, let me know if something is not clear

**Comment by abchatra** [comment]
It is ok for this bug as I figured out this is a set variable  block. Please use template going forward. Same goes for issue #1230.

**Comment by halspeed** [comment]
I think it's on every dropdown selection -- button pressed, pin pressed, true/false, music beat, melody, math operands, etc.

**Comment by abchatra** [comment]
Oh, yes I can see. This is good bug to address. I don't know the reasons why it is black.

**Comment by halspeed** [comment]
It was black checkmark with a white background in v0. 

By the way, the checkmark is black for the other targets too.

**Comment by pelikhan** [comment]
This is the default behavior in blocky/scratch3.0. I think we need to upstream this bug.

**Comment by halspeed** [comment]
From @rachel-fenichel -- https://github.com/google/blockly/blob/master/media/sprites.png
