### ISSUE TITLE
Printing Blocks code in Beta v1

### ISSUE THREAD

**Issue by KurtWAndrews** [Microsoft/pxt-microbit#1279]
**Describe the bug**
When you print blocky code, the values in the drop-down
 lists are illegible.

**To Reproduce**
1. Select the more... menu (gear icon)
2. Click on 'Print....'
3. On the document none of the blocks or fields that have drop-down lists are legible.

**Expected behavior**
I expect to be able to read all the information in the printed document

**Screenshots**
See Attachments

**Desktop (please complete the following information):**
See Attachments

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

[Microsoft MakeCode for micro_bit_2.pdf](https://github.com/Microsoft/pxt-microbit/files/2406574/Microsoft.MakeCode.for.micro_bit_2.pdf)
[Microsoft MakeCode for micro_bit.pdf](https://github.com/Microsoft/pxt-microbit/files/2406575/Microsoft.MakeCode.for.micro_bit.pdf)
[System Info.pdf](https://github.com/Microsoft/pxt-microbit/files/2406580/System.Info.pdf)

**Comment by pelikhan** [comment]
This issue will be fixed once we pick up pxt 4.0.

**Comment by pelikhan** [comment]
The printing feature is now available via the "Experiments" page (gearwheel -> About -> Print Code). This printing issue should be fixed now.
