### ISSUE TITLE
Side notes sometimes will not scroll in iOS

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#1282]
**Describe the bug**
With iOS, sometimes dragging over the side notes scrolls the editor screen.

**To Reproduce**
1. Go to 'https://makecode.microbit.org/v0'
2. Click on 'Projects'
3. Click on 'Projects' again
4. Scroll down to Compass
5. Tap on Compass
6. While it loads, tap and drag the main canvas
7. When finished loading drag side panel - editor screen scrolls 
8. The same can happen sometimes when reopening the side panel

**Expected behavior**
Dragging over the side panel should scroll the side panel.

**Screenshots**
![img_0139](https://user-images.githubusercontent.com/989126/45916286-40026400-be5b-11e8-91f0-863cd49c9c08.png)
![img_0138](https://user-images.githubusercontent.com/989126/45916287-40026400-be5b-11e8-93c3-a55a56389055.png)

**Desktop (please complete the following information):**
 - OS:  iPad iOS 11.4.1
 - Browser Safari
 - Version MakeCode 0.14.52

**Comment by abchatra** [comment]
Do you repro this on makecode.microbit.org/beta?

**Comment by martinwork** [comment]
Not really but with “Mood radio”, when at top or bottom, trying to scroll further drags editor.

**Comment by abchatra** [comment]
As we are planning to switch to /beta to live in next couple of months, if we the issue doesn't reproduce in /beta we will not take that up.

Seems like part of the issue (scroll drags editor) repros in /beta as well. Can you elaborate (screenshot or exact repro steps) on that issue?

**Comment by abchatra** [comment]
Fixed
