### ISSUE TITLE
Side notes buttons for script, simulation and download do not work in iOS

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#1283]
**Describe the bug**
The tiny blue buttons in the side panel for displaying the script and simulation and for downloading the code do not work in iOS.

**To Reproduce**
1. Go to 'https://makecode.microbit.org/v0'
2. Click on 'Projects'
3. Click on 'Projects' again
4. Scroll down to Compass
5. Tap on Compass
6. When finished loading, try the button

The first script button works; the second one blanks the panel.
Some of the middle buttons work sometimes, or blank the panel.
The download buttons do nothing or just blank the panel.

When running in a WKWebView, no messages are delivered when a button doesn't work.

**Expected behavior**
The buttons should work.

**Screenshots**
![img_0140](https://user-images.githubusercontent.com/989126/45916575-552dc180-be60-11e8-9711-b7ff44af4cdb.png)

**Desktop (please complete the following information):**
 - OS: iPad iOS 11.4.1
 - Browser Safari]
 - Version MakeCode 0.14.52

**Comment by martinwork** [comment]
On beta only the download buttons don’t work.

**Comment by martinwork** [comment]
On beta the download buttons do trigger a download message to the WKWebView.

**Comment by abchatra** [comment]
Try /beta on iOS. This should be fixed.

**Comment by martinwork** [comment]
This has changed quite a lot. Everything I tried worked. I couldn't find any download buttons.
