### ISSUE TITLE
Is radio strength now low by default?

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1284]
**Describe the bug**
Without setting radio power in the code, the default strength appears to be low with the signal only reaching about 30cm. This is the experience in v0 and v1

**To Reproduce**
1. Go to https://makecode.microbit.org/_6H0E3oFqDAeq (v1 program)
2. Flash script to two micro:bits. Press A to send string. Try extending distance between devices

**Expected behavior**
It used to be that radio strength was higher and this is still the case in the updated Python editor, so don't think this is a DAL issue.

Setting radio signal strength to 7 on start resolves the issue

**Desktop (please complete the following information):**
 - OS: Mac 10.13.6 Firefox 62

**Comment by abchatra** [comment]
Not an intentional change. Is there a change on our side. We should investigate.

**Comment by abchatra** [comment]
@pelikhan are you aware of any intentional change?

**Comment by microbit-mark** [comment]
@abchatra  https://github.com/lancaster-university/microbit-dal/commit/2a12ea23c12e725a2edda2752ae44e55cda76241?diff=unified#diff-02c86b17108efddd975b763f7215b1b1L279

no longer calls the setTransmitPower function

@microbit-sam will submit a fix

**Comment by abchatra** [comment]
Ok DAL issue right? We need to patch v0 as well.

**Comment by microbit-mark** [comment]
Yes. Both v0 and v1 experience the issue.

**Comment by pelikhan** [comment]
This is strange. The fix is easy, we can call setTransmitPower when initializing radio. See PR.

**Comment by pelikhan** [comment]
Fix in v0 https://github.com/Microsoft/pxt-microbit/commit/fa2c6bc6e507462b3c934fabcb26a4259ce9701a
Fix in v1 https://github.com/Microsoft/pxt-microbit/commit/eed66868a9020135f855c1eaf5c944d7317f4036
