### ISSUE TITLE
Block editor beta - unexpected behaviour when duplicating for index loop

### ISSUE THREAD

**Issue by Carlborg** [Microsoft/pxt-microbit#1290]
Running the beta block editor at https://makecode.microbit.org/beta#editor, on chrome on mac osx high sierra.

When I drag a "for index"-block to the canvas, duplicate it, and change the name of the index variable on one of them, both variable names get changed.

However, when I drag two "for index"-blocks to the canvas, and change the name of the index variable on one of them, only that one variable name gets changed.

This behaviour seems a bit unexpected, so I thought I'd raise it as a potential bug.
Cheers

**Comment by abchatra** [comment]
I see variable names being changes in both cases. Can you add a gif? (You can use screentogif software for the same on windows.

In future it is very helpful if you use bug template.

**Comment by abchatra** [comment]
I will reopen this when there is additional information.
