### ISSUE TITLE
Steps to take when switching v0 to v1

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt-microbit#1291]
- [x]  Change https://github.com/Microsoft/pxt-deployment-config/blob/master/production/config.json#L27 to v1
Pull request ready https://github.com/Microsoft/pxt-deployment-config/pull/75

- [x] Merge master into v1 for any documentation changes

- [x] Create a branch v0 in the target to serve v0 documentation (snapped from master)

- [x] set crowdin branch in v0 to v0, push a build to upload translations

- [x] set crowdin project in v1, push a build to upload translations

- [x] Validate shared script work well in v0 & v1

- [x] update index-ref.json to point to the v1 build?
Pull request ready: https://github.com/Microsoft/pxt-microbit/pull/1538
Pull request ready: https://github.com/Microsoft/pxt-microbit/pull/1539

- [x] do we still need to the v1 branch afterwards?
(This can be done after release)

- [ ] Ask AssignmentsUI to update microbit url from /beta to /
(This can be done after release)

- [x] Update the shareUrl of the v0 in pxtarget: https://github.com/Microsoft/pxt-microbit/pull/1501

**Comment by pelikhan** [comment]
It's probably wiser to review commits in master and cherry-pick them into v1.

**Comment by samelhusseini** [comment]
To Test: 
- [ ] Sharing page switches to use v1 as default. v0 share scripts still work. 
- [ ] Able to create shared scripts from both v0 and v1. 
- [ ] New docs page using v1 as default, v0 docs page
- [ ] Side docs uses v1 doc pages
- [ ] Able to pop out from both v0 and v1 editors into the respective documentation pages

**Comment by samelhusseini** [comment]
This doesn't need to happen before release, but certainly before we merge v1 into master: https://github.com/Microsoft/pxt-microbit/issues/1525

**Comment by abchatra** [comment]
Only the pending part is teams updating their URL.
