### ISSUE TITLE
v0 not automatically upgrading

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#1294]
I'm using Chrome Version 69.0.3497.100 (Official Build) (64-bit).

If I visit makecode.microbit.org in a normal session, and choose 'gear->about' I am still seeing:

> A Blocks / JavaScript code editor for the micro:bit powered by Microsoft MakeCode.
> 
> makecode.microbit.org version: 0.14.45
> 
> Microsoft MakeCode version: 0.19.13
> 
> C++ runtime version: v2.0.0-rc11

If I open an Incognito tab I get served the latest version.

> A Blocks / JavaScript code editor for the micro:bit powered by Microsoft MakeCode.
> 
> makecode.microbit.org version: 0.14.52
> 
> Microsoft MakeCode version: 0.19.16
> 
> C++ runtime version: v2.1.0

As the auto-update is important for people with the revised sensors I want to check there isn't some wider problem. Any useful debug I can share? I think @microbit-carlos also so this, perhaps with Firefox?

**Comment by microbit-carlos** [comment]
Yes, I've seen it on Firefox when the beta was being updated to different dal-integration-x releases, but it did eventually updated itself.

In fact right now I went to https://makecode.microbit.org and it was still showing me the previous MakeCode version with DAL v2.0.0-rc-11, without any indication that a new version was being downloaded (normally it used to show a dark overlay while it was updating).
After a couple of minutes I refreshed the page and it automatically loaded the latest MakeCode version (w/ DAL v2.1.0).

**Comment by abchatra** [comment]
Issue is with firefox. @pelikhan has put a workaround for this issue in the last release. You will have to manually refresh for now. 
 Closing as fixed.

**Comment by jaustin** [comment]
Are you sure it's Firefox only? I saw it with Chrome today (as in the original issue) and had to manually reload the page to get the newer version (which came as an autoupdate, not immediately). Could it be related to having multiple MakeCode tabs open?

**Comment by abchatra** [comment]
I haven't seen an issue on Chrome. Did you see any appcache errors in the console. Good to capture them.

**Comment by pelikhan** [comment]
We have a check when the “updateready” event triggers to ensure that the update state is ready. Firefox triggers that event BEFORE the update is ready (thanks ff) so we can’t rely on the event alone.

In such case, next reload gets the update.

**Comment by jaustin** [comment]
@abchatra I'm definitely seeing this in MakeCode on Chrome - for example I've just launched Chrome and I'm getting
makecode.microbit.org version: 0.14.52

Microsoft MakeCode version: 0.19.16

C++ runtime version: v2.1.0

(Currently in Firefox I have 0.14.53)

**Comment by abchatra** [comment]
What extension are you using? Failing to download files will result in not updating.

**Comment by jaustin** [comment]
This was uBlock Origin

**Comment by pelikhan** [comment]
@jaustin the latest v1 beta pulls ai.0.js from our CDN so it should not be blocked. Please try again.
