### ISSUE TITLE
MakeCode beta detecting firefox as safari

### ISSUE THREAD

**Issue by carlosperate** [Microsoft/pxt-microbit#1295]
Looking at the JS console in https://makecode.microbit.org I can see the following line:

```
Browser: firefox 62.0 on mac
```

makecode.microbit.org version: 0.14.52
Microsoft MakeCode version: 0.19.16
C++ runtime version: v2.1.0

In https://makecode.microbit.org/beta#editor I get:

```
Browser: safari 10 on mac
```

makecode.microbit.org version:  1.1.53
Microsoft MakeCode version:  3.22.20
microbit runtime version:  v2.1.0

Running Firefox 62.0 on macOS 10.13.6 High Sierra.

**Comment by abchatra** [comment]
@carlosperate Any issues with the website?

**Comment by pelikhan** [comment]
Detected probably on windows.
![image](https://user-images.githubusercontent.com/4175913/46045115-8e209d00-c0d1-11e8-8773-e260f954f018.png)
Could you run ``navigator.userAgent`` from the javascript console?
```
navigator.userAgent
"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0"
```

**Comment by carlosperate** [comment]
@abchatra there are no issues with the website, but I though it was worth mentioning as maybe it is used for logging/metrics.

User agent:
```
navigator.userAgent
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) Gecko/20100101 Firefox/62.0" 
```

**Comment by abchatra** [comment]
@darzu can you take look and see if this is still a case in Firefox on Safari?

**Comment by darzu** [comment]
Safari is reporting as Safari
Firefox is reporting as Safari "Browser: safari 10 on mac"

I'll fix that.
