### ISSUE TITLE
Base set of icon-based blocks

### ISSUE THREAD

**Issue by JosefJezek** [microsoft/pxt-microbit#1299]
Could you create extension for base set of icon-based blocks for young children (ages 5-7) as ScratchJr, OzoBlockly, LEGO WeDo or EdBlocks?

- http://scratchjr.org
- https://ozoblockly.com/editor?lang=en&robot=bit&mode=1
- https://github.com/LLK/scratch-blocks
- https://developers.googleblog.com/2016/12/scratch-blocks-update-making-it-easier-to-develop-coding-apps-for-kids.html
- https://play.google.com/store/apps/details?id=com.lego.education.wedo
- https://www.edblocksapp.com

**Comment by pelikhan** [comment]
Could you give more details about your request?
