### ISSUE TITLE
Manage projects directly from the home screen (Beta V1)

### ISSUE THREAD

**Issue by KurtWAndrews** [Microsoft/pxt-microbit#1305]
**Is your feature request related to a problem? Please describe.**

Every time I go to the home screen, I feel that I should be able to select a subset of my projects and do things like delete them or possibly create hex files directly from the home screen.

Either the solution or the alternative described below would work well.

**Describe the solution you'd like**

Select one or more projects
Click on a menu option displayed above the projects

The MarkProjectsSelectAction image shows a screen print of Google Drive.  The projects would be highlighted or marked with a checkmark, Then choose an action from a menu displayed above the projects (Google Drive +user, eye, trashcan icons, and a vertical ellipsis for more options.

*Describe alternatives you've considered**

Place an options menu on each project possibly denoted by an ellipsis and select the options from there.

**Additional context**

I've attached screenshots as examples.

![markprojectsselectaction](https://user-images.githubusercontent.com/2064542/46119663-bb547480-c1d1-11e8-9dbc-6837b2a4acc1.png)
![optionmenuoneachproject](https://user-images.githubusercontent.com/2064542/46119664-bb547480-c1d1-11e8-828a-aac2a9f8a1d2.png)
[System Info.pdf](https://github.com/Microsoft/pxt-microbit/files/2422229/System.Info.pdf)

**Comment by abchatra** [comment]
Good feature request @samelhusseini FYI

**Comment by samelhusseini** [comment]
Trying to understand the feature request a little more here and thinking specifically what it means for MakeCode.
I'm thinking this would be a grid (or list view) of all projects, and be able to select one or multiple, but besides delete, what features would you expect in a view like that?

**Comment by pelikhan** [comment]
We had request for the ability to "Clone" a project. We could start with just delete.

**Comment by KurtWAndrews** [comment]
Here are some ideas:

1. printing project
1. compiling the project
1. saving the project as JS
1. project settings
1. pairing if that is done at the project level (it looks to me like it is)

**Comment by microbit-mark** [comment]
More support for this from microbit support ticket: 19904 when will this be available to try in microbit makecode @samelhusseini ?

**Comment by abchatra** [comment]
We are working on getting this to /beta. ETA next friday.

**Comment by abchatra** [comment]
Script manager is live in /beta.
