### ISSUE TITLE
Block "start melody" can't play a complete music when putting it under "forever"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1306]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "Music" and drag block "start melody" 
![issue927](https://user-images.githubusercontent.com/23466737/46131714-eb9e2080-c26e-11e8-9a30-297f9fc2202b.PNG)
3. Put this block under "on start" & "forever" separately

**Expected result:**
When putting this block under "forever", it should play a complete music as putting block under "on start"

**Actual result:**
**Issue1**: When putting this block under "forever" and the first parameter choosing "dadadum", there is no voice
**Issue 2**: When putting this block under "forever" and the first parameter choosing others, it can't play 
a complete music

**Comment by abchatra** [comment]
Same behavior in v0 as well. @pelikhan and @samelhusseini any clue on the reasons? 
@Helen09 good bug.

**Comment by pelikhan** [comment]
starting a melody stops the previous, it is not a queue. this is expected.

**Comment by carlosperate** [comment]
If by default it uses the `MelodyOptions.Once` instead of `MelodyOptions.OnceInBackground`, shouldn't the block finish before the next forever iteration? Or what would be the difference between those two options?

**Comment by abchatra** [comment]
This is by design and not planning to change.
