### ISSUE TITLE
When clicking button "A", simulator shows "2,1,3,1,4"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1307]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Drag block show number "1" and put it under block "forever"
3. Drag block show number "2, 3, 4" and put them under "on button A pressed"
4. Click button "A" on simulator and observe simulator

**Expected result:**
When clicking button "A", simulator should show number "2,3,4"

**Actual result:**
When clicking button "A", simulator shows "2,1,3,1,4"
![issue92702](https://user-images.githubusercontent.com/23466737/46134621-edb7ad80-c275-11e8-8c68-6a4537496d33.gif)

**Comment by abchatra** [comment]
Show number has a pause inbuilt. So when you interleave two events forever 1 and 2,3,4 there will be control transfer to forever after each number. This is as designed.
