### ISSUE TITLE
triggering 'game over' shows A+B button and 'reset is not implemented in simulator yet'

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1308]
microbit-support:17781

**Describe the bug**

When using the 'game over' block it makes the A+B button appear on the simulator, when this is clicked it errors with the message "reset is not implemented in simulator yet"

![screen recording 2018-09-27 at 10 01 am](https://user-images.githubusercontent.com/31242877/46135307-c5f82380-c23c-11e8-82b2-6a6b48b2228a.gif)

This is a confusing experience, as there is no indication of why the A+B button appears and when selected the error message mentions 'reset'. Perhaps the help docs for the block could be updated and the error message to give more context.

**Comment by abchatra** [comment]
@microbit-mark I can't reproduce this. Can you?

**Comment by jwunderl** [comment]
Here is link to repr [link](https://makecode.microbit.org/_5tvTJA4i1c7P)

press `A`, then `A+B`

**Comment by abchatra** [comment]
I am able to reproduce this (Thanks @jwunderl).  Same behaviour in v0 as well.

**Comment by pelikhan** [comment]
Reset is now implemented.
