### ISSUE TITLE
The document is not translated when changing language to "Chinese"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1309]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "More..." -> "Language" -> "Chinese"
3. Right click on any block and check "help" document

**Expected result:**
The document should be translated to Chinese 

**Actual result:**
The document is not translated to Chinese when changing language to "Chinese"
![capture](https://user-images.githubusercontent.com/23466737/46136235-b8ad5a00-c279-11e8-986c-bf7c9b1be507.PNG)

**Comment by abchatra** [comment]
Documentation needs to be translated in Crowdin.  These are not translated yet. When they are translated these will be in chinese.
