### ISSUE TITLE
The first "on button A pressed" block disabled when changing its position

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1310]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Drag two "on button A pressed" blocks and put different block in it
3. Exchange these two blocks' position and observe

**Expected result:**
The first "on button A pressed" block should always enable

**Actual result:**
The first "on button A pressed" block disabled when changing its position
![issue92703](https://user-images.githubusercontent.com/23466737/46138371-4ee37f00-c27e-11e8-99f0-54b53abe77d8.gif)

**Comment by abchatra** [comment]
This is also as designed. In case of duplicate event handlers, left most survives.
