### ISSUE TITLE
Fix translation issues

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-microbit#1311]
@ganicke could you go through each of these errors and fix the syntax. It is either an extra space around the = or %
```
21 errors in translated blocks
bluetooth-strings.json pl bluetooth.uartReadUntil|block: block has space between %name and = : bluetooth uart | czytaj aż do %del = serial_delimiter_conv
bluetooth-strings.json hu bluetooth.onUartDataReceived|block: block has space between %name and = : bluetooth | kapott bekapcsolási adatok %delimiters = serial_delimiter_conv
core-strings.json hr music.changeTempoBy|block: block has extra spaces: promjena tempa za (bpm) | % vrijednostcore-strings.json hr pins.servoSetPulse|block: block has extra spaces: za servo motor postavlja puls | na pinu % vrijednost | za zadano vrijeme u (µs)
core-strings.json es-MX serial.readUntil|block: block has space between %name and = : serial|leer hasta %delimiter = serial_delimiter_conv
core-strings.json sv-SE control.onEvent|block: block has space between %name and = : vid händelse|från %src = control_event_source_id|med värdet %value = control_event_value_id
core-strings.json sv-SE control.raiseEvent|block: block has space between %name and = : starta händelse|från källa %src = control_event_source_id|med värdet %value = control_event_value_id
core-strings.json sl control.waitMicros|block: block has extra spaces: počakaj (μS) % Micro
core-strings.json pl basic.showArrow|block: block has space between %name and = : pokaż strzałkę %i = device_arrow
core-strings.json pl music.playTone|block: block has space between %name and = : zagraj | ton %note= device_note | przez %duration = device_beat
core-strings.json pl music.ringTone|block: block has space between %name and = : dźwięk dzwonka (Hz) |%note = device_note
core-strings.json no music.rest|block: block has space between %name and = : pause (ms) |%duration = device_beat
core-strings.json nl basic.showArrow|block: block has space between %name and = : toon pijl %i = device_arrow
core-strings.json de music.ringTone|block: block has space between %name and = : Klingelton (Hz) |%note = Device_note
core-strings.json da Array.length|block: block has extra spaces: længden af % værdi
core-strings.json da String.length|block: block has extra spaces: længden af % værdi
core-strings.json da control.raiseEvent|block: block has space between %name and = : hæv hændelsen | fra kilde %src = control_event_source_id | med værdi %value = control_event_value_id
core-strings.json cs game.LedSprite.change|block: block has extra spaces: %sprite| změna %property| % value
core-strings.json bg basic.showArrow|block: block has space between %name and = : покажи стрелка %i = device_arrow
core-strings.json bg music.setTempo|block: block has extra spaces: задаване темпо до (bpm) | % стойност
core-strings.json es-ES serial.readUntil|block: block has space between %name and = : serial|leer hasta %delimiter = serial_delimiter_conv
```

**Comment by ganicke** [comment]
OK, I think I got all of them...

Suggestion | File | Language | Time |  
-- | -- | -- | -- | --
задаване темпо до (bpm)\|%стойност | core-strings.json | Bulgarian | 22:48 | Undo
покажи стрелка %i=device_arrow | core-strings.json | Bulgarian | 22:46 | Undo
%sprite\|změna %property\|o %value | core-strings.json | Czech | 22:44 | Undo
hæv hændelsen\|fra kilde %src=control_event_source_id\|med værdi %value=control_event_value_id | core-strings.json | Danish | 22:39 | Undo
længden af %VALUE | core-strings.json | Danish | 22:38 | Undo
længden af %VALUE | core-strings.json | Danish | 22:37 | Undo
Klingelton (Hz)\|%note=device_note | core-strings.json | German | 22:34 | Undo
toon pijl %i=device_arrow | core-strings.json | Dutch | 22:33 | Undo
pause (ms)\|%duration=device_beat | core-strings.json | Norwegian | 22:31 | Undo
dźwięk dzwonka (Hz)\|%note=device_note | core-strings.json | Polish | 22:30 | Undo
zagraj\|ton %note=device_note\|przez %duration=device_beat | core-strings.json | Polish | 22:29 | Undo
pokaż strzałkę %i=device_arrow | core-strings.json | Polish | 22:26 | Undo
počakaj (μS)%Micro | core-strings.json | Slovenian | 22:25 | Undo
starta händelse\|från källa %src=control_event_source_id\|med värdet %value=control_event_value_id | core-strings.json | Swedish | 22:23 | Undo
vid händelse\|från %src=control_event_source_id\|med värdet %value=control_event_value_id | core-strings.json | Swedish | 22:19 | Undo
serial\|leer hasta %delimiter=serial_delimiter_conv | core-strings.json | Spanish | 22:16 | Undo
serial\|leer hasta %delimiter=serial_delimiter_conv | core-strings.json | Spanish, Mexico | 22:14 | Undo
promjena tempa za (bpm)\|%vrijednost | core-strings.json | Croatian | 22:09 | Undo
bluetooth\|kapott bekapcsolási adatok %delimiters=serial_delimiter_conv | bluetooth-strings.json | Hungarian | 22:02 | Undo
bluetooth uart\|czytaj aż do %del=serial_delimiter_conv | bluetooth-strings.json | Polish | 21:59 | Undo
bluetooth uart\|Napisz wartość %name\|= %value | bluetooth-strings.json | Polish | 21:59 | Undo

**Comment by ganicke** [comment]
@pelikhan these pass localization build now?

**Comment by ganicke** [comment]
Small fix of Slovenian string: 'počakaj (μS)%Micro' to 'počakaj (μS) %micros'. All should be OK now.

**Comment by microbit-mark** [comment]
@ganicke I think there may be another one for Text in Spanish ![20181219 bloques de texto estan en la parte superior superpuestos y no se pueden usar](https://user-images.githubusercontent.com/31242877/50299553-c68a0a00-0479-11e9-941e-1e5741bcaa60.JPG)

**Comment by ganicke** [comment]
Ah, si es un problema tambien.

I think it might be the format of the **charAt** block.
