### ISSUE TITLE
Improve the contrast between a block's primary colour and it's border

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt-microbit#1315]
We've received some feedback about the colours of the blocks as we transition from v0 to v1. The colours of the blocks are exactly the same, however the rendering has changed. The new rendering removes any sort of space between the blocks, and only keeps an outline (stroke) around the block. This stroke needs to have good contrast between the block's main colour and its boundary in order for the blocks to be distinct from one another (especially in the case where two blocks from the same category are connected to each other). 

I've taken this feedback over to our design team, and they've come back with the following recommendation: 
- Lighten the colours a tiny bit so we have more room to contrast with the darken outline.
- Darken the outline from 10% difference to 20% difference. 

The key things to keep in mind as we make this change:
- Colour contrast between the white text and the coloured background needs to be maintained at 3.0. (As you can zoom in to get to a AA-3 accessibility rating with 18px font size). We'll use https://contrast-ratio.com/ to test out colours. 
- Each category should have the same colour, so no colour switches to ensure screenshots are still mappable from printed books (ie: Basic will be Blue, Input will be magenta, etc)

I will be posting some screenshots to get feedback about this change.

@jaustin @Jaqster @pelikhan @halspeed  FYI

**Comment by samelhusseini** [comment]
Here's are the colours chosen by our design team. I've generated side by side comparisons of the editors with some code that uses blocks from all categories.

I've checked that all colours pass AA accessibility rating.

V0: 
![screen shot 2018-09-28 at 3 07 53 pm](https://user-images.githubusercontent.com/16690124/46235739-99253880-c330-11e8-91b8-80ffdde5015b.png)


V1: (Current)
![screen shot 2018-09-28 at 3 08 01 pm](https://user-images.githubusercontent.com/16690124/46235744-9cb8bf80-c330-11e8-93af-3a14775d0386.png)

V1: (Proposed)
![screen shot 2018-09-28 at 3 08 09 pm](https://user-images.githubusercontent.com/16690124/46235747-9fb3b000-c330-11e8-99f3-a6bb563075b1.png)

**Comment by samelhusseini** [comment]
Let me know if there are any colours you'd like to tweat and I can portray that information to our designers.

**Comment by jaustin** [comment]
Sam, I really like this. I think to the eye a user isn't going to consider these 'different colours' but the contrast is way better.

There are only a couple of issues - the whole thing is now more saturated, and I think specifically "Music", "Math" and perhaps the "Loops" are driving that. The others are all muted enough... 

If I'm totally honest, my first reaction was to move my head slightly further away from the screen with the brighter colours but I think it's just a few blocks influencing that,

**Comment by samelhusseini** [comment]
Thanks for the feedback @halspeed and @jaustin. I will shoot that over to our design consult. I mentioned to this to @jaustin offline but the tricky part with finding colours is the requirements are many: 
- meets AA accessibility contrast
- contrasts well with 30% darkened border colour. 
- In the case of Music, we need two orange colours, as Arrays is also orange so needs to be distinguishable 
- Same for Math as Math, Led and Images are all purple.

**Comment by samelhusseini** [comment]
New colours are in beta: https://makecode.microbit.org/beta

**Comment by abchatra** [comment]
This done.
