### ISSUE TITLE
Embedding limitations

### ISSUE THREAD

**Issue by luchotc** [Microsoft/pxt-microbit#1321]
Hi! In your docs about how to share a project I read the following:

> Rather than just sharing the link, you can also embed the project so that your visitors can use the simulator, edit blocks or code, or download the project without having to leave your site.

When trying it myself, I discovered that in order to actually edit the code (using either blocks or js), I had to leave the website and do it directly in the main page.

Are you planning on adding support for editing the project in the iframe?

Thanks in advance!

**Comment by pelikhan** [comment]
This is by design. Embedded editors might not have access to the local data (e.g. in OneNote) so we force it to be readonly. This also ensures a full screen editing experience.
