### ISSUE TITLE
gigglebot code not working from Firefox for one client

### ISSUE THREAD

**Issue by CleoQc** [microsoft/pxt-microbit#1328]
**Describe the bug**
I really don't know where to look for this one. We had one client report the gigglebot package wasn't working. Any hex downloaded from Makecode would fail. After investigation, it turns out only the client's Firefox would do this. His Chrome worked just fine. 
Firefox is my main browser and I don't have any issue.
He can use Firefox and Makecode without issues, except for the gigglebot package. 

I sent him a hex file and he could install it on his Gigglebot without issue. The same hex file loaded into Makecode and downloaded onto Gigglebot failed.  He sent me that hex file, it fails for me too (but works if I load it into Makecode and then download it).

It looks like it's the hex generation process that is an issue but I am clueless as to where to look.

**To Reproduce**
Not sure. I couldn't reproduce it. There's something in his Firefox...
user is on Firefox 62.0 64-bit on Ubuntu Linux 16.04.5 64-bit.  This is consistent behaviour for this user, btw. Just not for me (I'm on Windows)
Both the current and the Beta version will give him this issue. 
He has two Firefox extensions: uBlock Origin and PrivacyBadger
Disabling them doesn't help.

**Comment by ghalfacree** [comment]
I'm the user: MakeCode with Giggle (not Gigglebot) extension works fine when the hex file is generated and downloaded in Chrome, but not in Firefox. Identical extensions in both; Firefox tried with extensions disabled.

Attached are two hex files: the same program, generated in Chrome and Firefox. The Chrome version works, and is 605.3kB; the Firefox version does not, and is 572.1kB. The Firefox version appears not to run at all: no errors are output to the BBC micro:bit's display.

[microbit-test-firefox.hex.zip](https://github.com/Microsoft/pxt-microbit/files/2442515/microbit-test-firefox.hex.zip)
[microbit-test-chrome.hex.zip](https://github.com/Microsoft/pxt-microbit/files/2442517/microbit-test-chrome.hex.zip)

**Comment by pelikhan** [comment]
Could you check the version of editor in firefox/chrome? Go to the gear wheel and click “about”

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ghalfacree** [comment]
I'm seeing different versions, with Firefox being older:

Firefox:
makecode.microbit.org version: 0.13.52
Microsoft MakeCode version: 0.14.27
C++ runtime version: v2.0.0-rc11

Chrome:
makecode.microbit.org version: 0.14.53
Microsoft MakeCode version: 0.19.16
C++ runtime version: v2.1.0

Switching to makecode.microbit.org/beta actually gives me an even *older* version, oddly:
makecode.microbit.org version: 0.13.32
Microsoft MakeCode version: 0.14.10
C++ runtime version: v2.0.0-rc11

**Comment by ghalfacree** [comment]
As a follow-up, it appears that there's a stale MakeCode being stored by Firefox: opening MakeCode in a private window, without access to existing cache and local storage, results in:

makecode.microbit.org version: 0.14.53
Microsoft MakeCode version: 0.19.16
C++ runtime version: v2.1.0

So, the issue isn't as it first seemed: it's not that Firefox doesn't work with the Giggle extension, it's that the Giggle extension doesn't work with an older version of MakeCode and Firefox is refusing to load a newer version that it currently has in cache.

Interesting!

**Comment by ghalfacree** [comment]
And as a follow-up to my follow-up, deleting the local storage for MakeCode and hard-refreshing the page results in the same version numbers as in Chrome, and the Giggle extension then works fine. The delete-local-storage part was absolutely required, though: I'd tried hard-refreshing the page previously, which did not load the latest version.

How bizarre - but I guess we can count this as resolved, at least!

**Comment by CleoQc** [comment]
Thanks for digging into this one. It's been a learning experience for me. Next time a user has a similar issue I'll know how to handle it.
