### ISSUE TITLE
Download .hex file from the Getting Started side pane is only returning "Happy Face" and not actual sample

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt-microbit#133]
If you hit the little download button on one of the side pane samples, you only get the first block of code.

Repro:
* Side Pane
* Scroll to the last example of "Happy Face" called "your turn!"
* Click on the download button (in the right pane below the image) which creates a .hex file in the downloads directory
* Drag that .hex file into the editor
** Notice - it only shows the first block which is a smile face. Trying other samples, the same this happens

**Comment by darrenge** [comment]
Actually looking at it more ... it always is just building the "Happy Face" no matter what the project is. It just seemed like the first block as I was doing Happy Face type examples. The download button is hard coded to Happy Face.

**Comment by abchatra** [comment]
This issue still repro.

**Comment by abchatra** [comment]
fixed by https://github.com/Microsoft/pxt/pull/525
