### ISSUE TITLE
Events are notified twice when listing for ANY and a specific value

### ISSUE THREAD

**Issue by philipphenkel** [microsoft/pxt-microbit#1334]
**Describe the bug**
Events are notified twice when listing for ANY and a specific value for the same event source. This is caused by the implementation of registerWithDal.

**To Reproduce**
Run https://makecode.microbit.org/_MwM3KfKzCaU0
Press button A or B: it shows 2

**Expected behavior**
Event should be notified only once. Press button A or B: it shows 1

**Screenshots**
![bildschirmfoto 2018-10-02 um 23 24 19](https://user-images.githubusercontent.com/828416/46377914-5bab0d00-c69a-11e8-926a-92ed7cdb29f2.png)

**Desktop (please complete the following information):**
 - affects all platforms

**Comment by philipphenkel** [comment]
#1333 is a potential fix

**Comment by philipphenkel** [comment]
I'm surprised that this is standard DAL behaviour as I "fixed" it pxt-microbit code.

To be precise a specific event triggers currently **4 notifications** in pxt-microbit. I would expect that 1 event triggers 2 notifications only: the specific one and ANY.

@tballmsft Would it be helpful to analyze the behaviour of MicroPython?

**Comment by philipphenkel** [comment]
My example was overly complicated. Please have a look here:

<img width="992" alt="bildschirmfoto 2018-11-26 um 21 08 20" src="https://user-images.githubusercontent.com/828416/49039221-6fb54b80-f1bf-11e8-9542-90c712c89ee9.png">

https://makecode.microbit.org/_CLjbK0asz6zx

**Comment by philipphenkel** [comment]
@abchatra The behavior is still odd. As of today, the simulator shows 1 and the real device shows 4 when running my example: https://makecode.microbit.org/_CLjbK0asz6zx

**Comment by jwunderl** [comment]
For what it's worth, this same bug occurred in arcade https://github.com/microsoft/pxt-arcade/issues/959, and was fixed in that case with https://github.com/microsoft/pxt-common-packages/pull/829

**Comment by philipphenkel** [comment]
@jwunderl @abchatra Woohoo! The long-standing issue was finally fixed. Thanks a lot.

I tested with latest MakeCode.microbit.org
makecode.microbit.org Version:  2.0.6
Microsoft MakeCode Version:  5.15.12

**Comment by martinwork** [comment]
@philipphenkel But #2382

**Comment by philipphenkel** [comment]
@martinwork I already had a look at #2382. It's a slightly different case.
