### ISSUE TITLE
Failing to convert from code to blocks in some cases

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt-microbit#134]
I am running into cases where I have a script and I delete the code. I then drag the code from one of the projects. I try to convert to blocks ("show blocks") and I get the error that something went wrong.

I create a new project and drag exact same code to it and it does the Show Blocks just fine.

If I compile the one that failed and save it to hex and drag that hex file to a new project, it still fails to Show Blocks.

Repro:
* Open hex file (FailsToConvert.hex) in editor
* Show Blocks
** Get error

**Comment by darrenge** [comment]
One note - it actually runs ok just doesn't convert to blocks

**Comment by pelikhan** [comment]
Can you use the "publish" option to save the code and add the URL to this thread?

**Comment by darrenge** [comment]
https://m.pxt.io/xglasl

**Comment by darrenge** [comment]
Here is one that is blank that can't be converted to Blocks:
https://codethemicrobit.com/hxjcusdwcc

Maybe different issue.

**Comment by abchatra** [comment]
I can't see the repro. We have fixed bunch of issues on roundtrip. If this still exists please reopen in pxt repo
