### ISSUE TITLE
Setting game LED brightness does not work as expected

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1344]
from micro:bit support: 17724

**Describe the bug**
In this program 3 LEDs are created and set at varying values. Setting the LED brightness for the second varibale to 40 seems to have no effect and is still shown at full brightness. This is the same behaviour on the micro:bit

**To Reproduce**
https://makecode.microbit.org/_frDczuWLU4Ki

**Expected behavior**
``` javascript 
let itemBright: game.LedSprite = null
let itemDim: game.LedSprite = null
let itemDark: game.LedSprite = null
itemDark = game.createSprite(0, 0)
itemDark.set(LedSpriteProperty.Brightness, 0) // Turn off the led in position 0,0 - WORKS AS EXPECTED
itemDim = game.createSprite(2, 2)
itemDim.set(LedSpriteProperty.Brightness, 40) // Dim the led in position 2,2 - DOESN'T WORK AS EXPECTED - THE LED STILL SHOWS WITH MAX BRIGHTNESS
itemBright = game.createSprite(4, 4)
itemBright.set(LedSpriteProperty.Brightness, 255) // Turn brightness to max for the led in position 4,4 (default brightness) - WORKS AS EXPECTED
basic.pause(1000)
led.setBrightness(40) // Dim all the leds that are turned on - WORKS AS EXPECTED 
```

**Desktop (please complete the following information):**
- OS: Win 8.1/ Mac OS 10.13
- Chrome 69 

**Additional context**
Possibly related https://github.com/Microsoft/pxt/issues/3402

**Comment by microbit-mark** [comment]
Hi @abchatra can you take a look at this one for us?

**Comment by pelikhan** [comment]
Another sample https://makecode.microbit.org/_MhAi1zAosLFe

**Comment by pelikhan** [comment]
I think know what is going on. We are switching modes between non-greyscale and greyscale incorrectly.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
Fixed
