### ISSUE TITLE
Beta editor integer division share link bug

### ISSUE THREAD

**Issue by Carlborg** [Microsoft/pxt-microbit#1345]
**Describe the bug**
When creating a project with regular division math blocks, then creating a sharable link to that project, and opening it, the regular division blocks have changed to integer division blocks.

**To Reproduce**
1. Go to https://makecode.microbit.org/beta#editor
2. add show number block to forever
3. add 0/0 math block inside show number
4. press share
5. press publish
6. visit generated link
7. see that the regular division block has been changed to integer division 

**Expected behavior**
All blocks are left the same when sharing

**Desktop:**
 - OS: OSX 10.13.6
 - Browser Chrome
 - Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by abchatra** [comment]
I can't repro this bug. Can you add your editor version and the shared link? 
For example: https://makecode.microbit.org/_hkyKex5JpEYH

**Comment by abchatra** [comment]
I am able to repro in chrome and not in Edge.

**Comment by Carlborg** [comment]
Hi, 
a shared link that does the thing for me is https://makecode.microbit.org/_M2mfvddXfJeJ <https://makecode.microbit.org/_M2mfvddXfJeJ>
And my editor version is:

makecode.microbit.org version:  1.1.62 <https://github.com/Microsoft/pxt-microbit/releases/tag/v1.1.62>
Microsoft MakeCode version:  4.1.13 <https://github.com/Microsoft/pxt/releases/tag/v4.1.13>
microbit runtime version:  v2.1.0 <https://github.com/lancaster-university/microbit/releases/tag/v2.1.0>

**Comment by abchatra** [comment]
There is an additional bug here, on edge share link always goes to javascript. Seems incorrect to me.
