### ISSUE TITLE
Edge upgrade fails

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt-microbit#1351]
Below program is created in v0.
https://makecode.microbit.org/v1/61874-74423-81162-49231

**To Reproduce**
1. Navigate to above link in Edge.

Upgrade fails and javascript is shown. Upgrade correctly happens on Chrome 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge

**Comment by riknoll** [comment]
Fixed by https://github.com/Microsoft/pxt/pull/4869
