### ISSUE TITLE
add check box to prevent pop-up pairing window 

### ISSUE THREAD

**Issue by machinehistories** [microsoft/pxt-microbit#1356]
Add a check box to prevent pairing pop up from displaying after initial pair.
![pair](https://user-images.githubusercontent.com/26831444/46577618-a5983980-c99f-11e8-8d77-fed67a24c2ec.PNG)

**Comment by abchatra** [comment]
Closing > 2year old issues. We decided it is not possible to determine in the class room scenario to uniquely identify if the user has seen this dialog or not. So siding with keeping this even though we understand it might be bit annoying for few users.
