### ISSUE TITLE
The page is missing

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1362]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "Extensions" -> click "?" on the top-right of the page

**Expected result:**
The page should not miss 

**Actual result:**
The page is missing
![issue100902](https://user-images.githubusercontent.com/23466737/46662261-855dba00-cbed-11e8-91c5-8c5ba2749bde.gif)

**Comment by ganicke** [comment]
The big **?** goes to https://makecode.microbit.org/boards. What should really be attached to that? https://makecode.microbit.org/v1/extensions maybe?

**Comment by pelikhan** [comment]
Yes to "/extensions".

**Comment by ganicke** [comment]
I think that the **'?'** is tied to the help search mode set in _scriptsearch.tsx_:

```typescript
        const headerText = mode == ScriptSearchMode.Boards ? lf("Boards")
            : mode == ScriptSearchMode.Experiments ? lf("Experiments")
                : lf("Extensions");
        const description = mode == ScriptSearchMode.Boards ? lf("Change development board")
            : mode == ScriptSearchMode.Experiments ? lf("Turn on and off experimental features")
                : lf("Add an extension to the project");
        const helpPath = ScriptSearchMode.Boards ? "/boards"
            : mode == ScriptSearchMode.Experiments ? "/experiments"
                : "/extensions";
```

**Comment by pelikhan** [comment]
That’s bug...

**Comment by ganicke** [comment]
Wait, easy fix, need to add a the check for ``mode == ScriptSearchMode.Extensions``.

**Comment by ganicke** [comment]
Fixed in https://github.com/Microsoft/pxt/pull/4794
