### ISSUE TITLE
led.plot different in emulator to micro:bit.  Can miss pixels.

### ISSUE THREAD

**Issue by designingourtomorrow** [Microsoft/pxt-microbit#1363]
**Describe the bug**
led.plot is giving me different results on the web emulator and the micro:bit I am using.

**To Reproduce**

```
let screenValue = 10

for (let index = 0; index <= screenValue; index++) {
               led.plot(0, (index / 5))
           }
// on the emulator this fills in all of the LEDs from top left
// on my micro:bit it fills in the left-hand column`
```

**Expected behavior**
I would expect only the left hand column to be filled on the emulator.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
In the non-beta, I was able to use a mix of % and / to specify position to plot to.  In /beta, this broke down.
`led.plot(0, Math.round(index / 5))` in /beta gives the same output (left hand side of screen only) that I would have expected from the old editor.
Using` led.plot(Math.round(index % 5), Math.round(index / 5)) ` leads to a screen that has some unexpected gaps in it.

**Comment by pelikhan** [comment]
Fixed.
