### ISSUE TITLE
Add a third option when exiting project v1

### ISSUE THREAD

**Issue by halspeed** [Microsoft/pxt-microbit#1365]
**Describe the bug**
User is not given the option to not name their project.

**To Reproduce**
In the editor, select the Home icon and a dialog box appears with Exit Project -- Done/Cancel.

**Expected behavior**
Similar to Save/Don't Save/Cancel, I expect an option to not name my project and continue to the home screen. Consider asking "Do you want to name your project?" -- Yes/No/Exit

**Screenshots**
![image](https://user-images.githubusercontent.com/29285304/46684134-8f64c600-cbb7-11e8-95f8-7235e87a2883.png)

**Additional context**
If the canvas is empty, or hasn't changed, consider not showing the dialog box.

**Comment by pelikhan** [comment]
Let's pick this one up on our UI design meeting.

**Comment by abchatra** [comment]
Feedback from designer:
https://github.com/Microsoft/pxt/pull/4804

**Comment by samelhusseini** [comment]
Fixed by https://github.com/Microsoft/pxt-microbit/issues/1365
