### ISSUE TITLE
Inconsistency showing blocks in tutorials v1

### ISSUE THREAD

**Issue by halspeed** [Microsoft/pxt-microbit#1367]
**Describe the bug**
Some tutorials automatically show the programming blocks and some require the user to select hint to see the blocks.

**To Reproduce**
Go to the homescreen and select a tutorial

**Expected behavior**
I expect Flashing Hearts, Smiley Buttons, Love Meter and Coin Flip to show the programming blocks the same way as Name Tag and Dice show the blocks between steps.

**Screenshots**
Intro screen for Name Tag:
![image](https://user-images.githubusercontent.com/29285304/46685828-0e5bfd80-cbbc-11e8-9c50-30a310abec56.png)

**Additional context**
Snap the Dot is a tutorial but is listed under games, seems like it should be list as a tutorial.

**Comment by pelikhan** [comment]
I made the first tutorial steps go full screen. @ganicke can we add an intro "headless" step in each of them that shows explains what the tutorial will do?

**Comment by pelikhan** [comment]
We did a round of fixing. Reopen if more issues.
