### ISSUE TITLE
Inconsistency in the display of project instructions v1

### ISSUE THREAD

**Issue by halspeed** [Microsoft/pxt-microbit#1368]
**Describe the bug**
Instructions for some projects are embedded in the editor while some open a new webpage.

**To Reproduce**
Go to the homescreen and select a project with instructions.

**Expected behavior**
I expect the instructions to show in the editor with the option to expand into a webpage. Some projects such as Rock-Paper-Scissors open a new webpage instead of being embedded in the editor.

**Screenshots**
![image](https://user-images.githubusercontent.com/29285304/46685997-81657400-cbbc-11e8-8f2d-d73f10ab3218.png)

**Comment by ganicke** [comment]
This is due to the side docs experience not being as friendly to viewing for some projects that have large typescript sections or embedded videos. Unfortunately, we haven't standardized a sidedocs vs. full page format.

**Comment by abchatra** [comment]
By design today. We are looking into overhauling the system some point of future.
