### ISSUE TITLE
Home icon expands on mouse over v1 homescreen

### ISSUE THREAD

**Issue by halspeed** [microsoft/pxt-microbit#1369]
**Describe the bug**
When on the homescreen, the icon of the home expands on mouse over but is not selectable because the user is already on the homescreen.

**To Reproduce**
Go to the homescreen and mouse over the home icon at the top.

**Expected behavior**
Since the home icon is not selectable, I don't expect it to expand on mouse over.

**Comment by pelikhan** [comment]
Fixed.
