### ISSUE TITLE
Difference in timing between simulator/microbit for display string

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt-microbit#137]
If I do this on the simulator, I get a 400ms delay after each character press (annoying as I am using it on a button press and the delays slow down data entry). If I run this on the real micro:bit, there is no delay. I remember reporting this last year on Touch Develop.

text = String.fromCharCode(index + 64);
basic.showString(text);

In the javascript I can put a ,0 in the showString to take out the delay, but then I cant round-trip back to blocks any more as the parameter is not recognised by blocks.

**Comment by abchatra** [comment]
Can you please add the entire repro scenario here? I don't how to reproduce this. Also please reopen the issue in Microsoft/pxt repo.
