### ISSUE TITLE
Tutorial names listed under My Projects are not tutorials v1

### ISSUE THREAD

**Issue by halspeed** [microsoft/pxt-microbit#1371]
**Describe the bug**
Names of Tutorials listed under My Projects are not tutorials.

**To Reproduce**
1. Go to the homescreen and open a tutorial
2. Exit the tutorial
3. Under My Projects, select the name of the tutorial

**Expected behavior**
Selecting the name of the tutorial under My Projects would relaunch the tutorial.

**Additional context**
Consider adding "My" to the name of the tutorial when saved under My Projects to make the project different than the name of the tutorials.

**Comment by abchatra** [comment]
This is fixed. As we keep the current state of the tutorial and continue from there.
