### ISSUE TITLE
Page link on "Extension" page is same as the link on editor page

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1372]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "Advanced" -> "Extensions" to navigate to extension page
3. Observe the browser link

**Expected result:**
The page link on extension page should be different with editor page

**Actual result:**
Page link on "Extension" page is same as the link on editor page
![100903](https://user-images.githubusercontent.com/23466737/46715646-8fd28f00-cc93-11e8-9aeb-d0191628c29d.PNG)
![issue100904](https://user-images.githubusercontent.com/23466737/46715696-c4dee180-cc93-11e8-8916-2d5901c7241b.PNG)

**Comment by pelikhan** [comment]
We have limited support for navigation/history in pxt, e.g. pretty much only ``#editor`` is supported.

**Comment by abchatra** [comment]
By design
