### ISSUE TITLE
"Take me to the old editor" link may be too specific

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#1375]
When opening a program that contains an extension that doesn't upgrade well, we get the following dialogue

![image](https://user-images.githubusercontent.com/147113/46741599-4b4bf100-cc9d-11e8-94ac-a2d57dcfb0c7.png)

The 'go to the old editor' button takes me to
https://makecode.microbit.org/v0.14.54#editor

This exposes direct version selection in a way that could leave users saving URLs to older versions

is it better to send it to just /v0 ?

**Comment by pelikhan** [comment]
Good one we should use the major version only.

**Comment by abchatra** [comment]
We are going to fix this to redirect to v0.

**Comment by abchatra** [comment]
Fixed. Will be available in /beta soon.
