### ISSUE TITLE
An error shows in example "rock-paper-scissors" tutorial

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1378]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/projects/rock-paper-scissors/code
2. Scroll down to 7th step and copy the code to "JavaScript" editor page

**Expected result:**
The 3th line code should be "let tool  = Math.randomRange(0,2)" rather than "let tool = Math.random(3)"

**Actual result:**
An error shows in example "rock-paper-scissors" tutorial
![issue101101](https://user-images.githubusercontent.com/23466737/46777071-d6ca8e00-cd40-11e8-9e57-94f3901fd216.PNG)

**Comment by abchatra** [comment]
When you copy paste there is no chance for upgrade. But you download and drag the hex file to the beta editor your script will be update.d.

**Comment by Helen09** [comment]
I tried to download and drag the hex file to the beta editor, the script still can't be updated.
The detail is as below .gif.
![123](https://user-images.githubusercontent.com/23466737/46925632-6d5bbf80-d05f-11e8-9912-df1880f2b457.gif)

**Comment by abchatra** [comment]
@riknoll take a peek at this when you have time.

**Comment by riknoll** [comment]
There are a couple things going on here:

1. Looks like the hex files that we download from the docs are setting the "editor" flag to TS so they won't open in blocks by default
2. Our upgrade rules fix `Math.random()` in blocks but not in TS

That first one is causing the second issue. @samelhusseini @pelikhan is `Math.random()` not being upgraded in the TS an oversight or intentional?

**Comment by Helen09** [comment]
This issue also repros on project "Reaction Time", the detail is as below:
1. Navigate to https://makecode.microbit.org/projects/reaction-time/code
2. Copy or download and then import the code to JavaScript editor page and observe
![issue1023](https://user-images.githubusercontent.com/23466737/47338878-0461f080-d6cc-11e8-866b-af561de27241.PNG)

**Comment by abchatra** [comment]
We should update Math.random in TS. @pelikhan confirm.

**Comment by abchatra** [comment]
Fixed
