### ISSUE TITLE
Failing to get any life from packages

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt-microbit#138]
Is it possible for users to write their own packages?

I couldn't find any docs about it. When I tried and set the slider to 'public package' and hit the publish button, I could not find this in my list when searching to import a new package.

**Comment by tballmsft** [comment]
www.pxt.io/docs

**Comment by pelikhan** [comment]
needs more docs

**Comment by pelikhan** [comment]
Michal, can you go through the package creation experience from the command line and add it to the docs?

**Comment by pelikhan** [comment]
Related https://github.com/Microsoft/pxt-microbit/issues/125

**Comment by mmoskal** [comment]
Docs have been updated at https://www.pxt.io/packages and https://codethemicrobit.com/packages
