### ISSUE TITLE
Serial colours can be hard to read

### ISSUE THREAD

**Issue by designingourtomorrow** [Microsoft/pxt-microbit#1380]
**Is your feature request related to a problem? Please describe.**
I can't read yellow on white when I am looking at serial data

**Describe the solution you'd like**
I'd like to be able to order colours for different serial strands I am sending

**Describe alternatives you've considered**
Cutting out the yellow on white option is possible.  So is refreshing whenever it looks like my eyes will hurt.

**Additional context**
![yellow_on_white](https://user-images.githubusercontent.com/42643946/46805842-0b007780-cd5e-11e8-885f-b9e7024a252e.png)

Ow!  If this doesn't hurt, turn off transparency and squint again.

**Comment by pelikhan** [comment]
We are overriding default colors in pxtarget. Maybe we should just use the default.

**Comment by pelikhan** [comment]
Fixed, please reopen if you still find a problematic color.
