### ISSUE TITLE
Upgrade corner case: broken packages leave main scripts untouched

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#1381]
**Describe the bug**
When upgrading from v1 the normal behaviour for translating v0 scripts to v1 is to convert division to integer division

This works in the following cases I've tested
* upgrade from cache
* drag-and-drop of normal script

However, in the case that a script has a package in, and that package has an error on upgrade, the body of the program doesn't seem to get updated

**To Reproduce**
Working
![dividie-upgrade](https://user-images.githubusercontent.com/147113/46818474-3e9ccb00-cd79-11e8-9afc-8284b061eea2.gif)

Not working
![dividie-upgrade-badpkg](https://user-images.githubusercontent.com/147113/46818482-4197bb80-cd79-11e8-87c8-985cf9835443.gif)

**Expected behavior**
I think that the 'attempt to repair' option should probably fix the main script even if the package is the problem?

**Comment by abchatra** [comment]
This is as designed.  If we can't fix we leave it as it is.

**Comment by abchatra** [comment]
The upgrade is whole or none. This is by design not mess with half upgrade which results in various other issues.
