### ISSUE TITLE
Temp slider in simulator shows NaN on IOS devices

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt-microbit#1382]
**Describe the bug**
Previewing the micro:bit simulator on a mobile device (iPhone plus) and adjusting the temperature setting by sliding the thermometer gives you a reading of "NaN"

**To Reproduce**
1. On an IOS device
2. Add a temperature block
3. Try to adjust the temperature in the simulator
4. Receive NaN as a reading

**Expected behavior**
Show the values between the min and max temps

**Screenshots**
![dmyafy4vaaa1ynl](https://user-images.githubusercontent.com/16690124/46821130-bdbfde00-cd3c-11e8-8f9c-f411b0ad192c.jpg)

**Smartphone (please complete the following information):**
 - Device: Iphone Plus
 - OS: IOS

**Additional context**
Bug reported on Twitter: https://twitter.com/FergeeksonGirl/status/1037545901533753344

**Comment by microbit-mark** [comment]
micro:bit support: 20898
More users reporting this issue

**Comment by abchatra** [comment]
@jwunderl This is a good one to address
