### ISSUE TITLE
Array issue in javascript (typescript) generator: Generic type 'Array<T>' requires 1 type argument(s).

### ISSUE THREAD

**Issue by CenTdemeern1** [Microsoft/pxt-microbit#1387]
![microbit-screenshot 1](https://user-images.githubusercontent.com/24682280/46875929-4cb41f80-ce3d-11e8-8a81-742c98a750d4.png)
![mbscrnsht](https://user-images.githubusercontent.com/24682280/46876009-7ec58180-ce3d-11e8-91b6-fbc9539f295f.png)

**Comment by abchatra** [comment]
Empty array don't have any type information. We follow static type script and it requires type information. You will need to create with specific number or string array for  the first parameter
```javascript
let list: number[][] = []
list = [[1, 2], []]
```
