### ISSUE TITLE
No string indexing functions?

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt-microbit#139]
A really simple way of making things data driven is to append them to the end of a string, and then index into that string to get them back again later. I know you are intentionally constraining the blocks interfaces, but this would be a very useful feature that would allow quite a lot of mileage. For example, I could store a tune in a string, and then write a loop that plays back each note one by one.

Data driven programs are generally much more concise and more elegant, it would be nice to be able to teach an aspect of them using strings as the backing store for the data.

**Comment by abchatra** [comment]
This is part of the issue #72. Closing this one.
