### ISSUE TITLE
Digital Read Pin works in simulator, not in hardware

### ISSUE THREAD

**Issue by tinfoilhatter** [Microsoft/pxt-microbit#140]
The following code works in the simulator but does not work in a real-life micro:bit. The number `0` never increases on the display.

```
let item = 0;
basic.showNumber(item);
basic.forever(() => {
    if (pins.digitalReadPin(DigitalPin.P0) == 1) {
        item = item + 1;
        basic.showNumber(item);
    }
});
```

This code is a stripped-down version of the existing code sample for Digital Read Pin, which also works on the simulator, but not on a real micro:bit.

**Comment by pelikhan** [comment]
What is the physical setup you have?

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by tinfoilhatter** [comment]
I have tried it with two different micro:bits, and with battery power and USB power. I hold the `GND` pin and then hold `P0` with my other hand. The display reads `0` and never changes.

**Comment by tinfoilhatter** [comment]
Per pelikhan, **digital write pin** does not work with human touch. Unlike **on pin pressed**, it primarily uses pin-to-pin communication from another micro:bit. I have updated the documentation accordingly.
