### ISSUE TITLE
Blocks editor Compile button fails to upload in Firefox

### ISSUE THREAD

**Issue by tinfoilhatter** [Microsoft/pxt-microbit#141]
In Firefox 47.0, on Ubuntu 16.04, the **Compile** button in the blocks editor displays the message "Uploading .hex file", but never uploads the file.

I couldn't find the uploaded file the first few times I used it. (Uploading code from code examples in the Reference docs always sends .hex files to the **Downloads** folder.) I checked the Firefox **Show All Downloads** button (the blue downward-pointing arrow), and it did not register any of the downloads from clicking **Compile**. By contrast, it showed everything else I expected, including downloads from the code samples.

**Comment by abchatra** [comment]
I can't repro this.
