### ISSUE TITLE
pins.onPulsed() error

### ISSUE THREAD

**Issue by lioujj** [microsoft/pxt-microbit#1416]
When P8 pulses low, then the LED displays the string High. When P8 pulses high, then the LED displays the string Low.  It looks something wrong.
![microbit-screenshot 1](https://user-images.githubusercontent.com/34760803/46906829-1dd0a300-cf3c-11e8-9f35-02920d070727.png)

**Comment by pelikhan** [comment]
This API is not yet implemented in the simulator.

**Comment by lioujj** [comment]
> This API is not yet implemented in the simulator.

This result is not in the simulator, it's in my real micro:bit.

**Comment by abchatra** [comment]
This is likely fixed. If this is still an issue let us know.

**Comment by philipphenkel** [comment]
I'm pretty sure that the issue still persists because my IR extension relies on it and the extension is still working. I assume if we fix the logic we will break many programs that rely on `pins.onPulsed`.

**Comment by martinwork** [comment]
I think the apparent high/low swap might be right. "on pin pulsed high" is for measuring the "pulse duration" of a high pulse, which starts when the input goes high, and ends when the input goes low. So the high pulse handler is called when the signal goes low, to deliver the duration of the pulse.

**Comment by philipphenkel** [comment]
@martinwork What you describe would exactly match my expectation.
