### ISSUE TITLE
Refresh option for extension is too long

### ISSUE THREAD

**Issue by designingourtomorrow** [Microsoft/pxt-microbit#1421]
**Describe the bug**
The refresh option for an imported extension contains a long ID number, which is sitting over everything else.

**To Reproduce**
Import https://github.com/designingourtomorrow/pxt-stepcounter
(also tested with https://github.com/designingourtomorrow/pxt-stepcounter-test )
Click JavaScript
Expand Explorer options

**Expected behavior**
The 'refresh' icon should be a small single icon

**Screenshots**
![explorer_refresh](https://user-images.githubusercontent.com/42643946/46944026-f0354800-d068-11e8-9d68-04130d6bb5f0.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 Prf 64 Bit
 - Browser: Chrome
 - Version: 69.0.3497.100 (Official Build) (64-bit)

**Comment by mmoskal** [comment]
https://github.com/Microsoft/pxt/pull/4767

@pelikhan I guess we should display first 7 characters for the SHA, the way github does?

**Comment by pelikhan** [comment]
right, will fix.

**Comment by pelikhan** [comment]
Fixed. Thanks for reporting.
