### ISSUE TITLE
MakeCode v1 Import Bugs

### ISSUE THREAD

**Issue by microbit-sam** [Microsoft/pxt-microbit#1422]
**Describe the bug**
Importing into MakeCode v1 appears to have a few bugs:
- show string "hello world" -> show string ""
- show leds [1, 1, 1, 1, ...] -> show leds [0, 0, 0, 0, ...]
- Pin mappings are incorrect

**To Reproduce**
- Migrate a project from https://www.microbit.co.uk/app/?r=tbyga
- Change the URL to use MakeCode v1
- Observe differences

OR

- Drag and drop a .hex file compiled in the .co.uk editors

**Expected behavior**
The same program should be imported into MakeCode

**Screenshots**
![screen shot 2018-10-15 at 11 36 38](https://user-images.githubusercontent.com/32453267/46946130-b0715f00-d06e-11e8-90c5-35481119ddc2.png)
![screen shot 2018-10-15 at 11 36 50](https://user-images.githubusercontent.com/32453267/46946133-b404e600-d06e-11e8-94d1-8bf2d20f89ad.png)

**Comment by microbit-sam** [comment]
.co.uk -> v0 -> v1 works
I'll make sure to point the migrate button to v0 and document this for any user migrating a project

**Comment by abchatra** [comment]
Peli also added a redirect to v0 popup if someone drags these hex files
