### ISSUE TITLE
Place both running time blocks next to each other in menu

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt-microbit#1423]
![image](https://user-images.githubusercontent.com/5718354/46949628-5f6b6600-d082-11e8-96d7-a3f6bc247314.png)

It is easier to notice that running time blocks exist both in milliseconds and microseconds if the blocks would be placed directly after each other instead of with "calibrate compass" in between.

**Comment by abchatra** [comment]
Fixed by https://github.com/Microsoft/pxt-microbit/pull/1

**Comment by abchatra** [comment]
Fixed
