### ISSUE TITLE
Reference overview page needs Bluetooth adding

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#143]
Hi, the page with URL http://localhost:3232/reference when I run PXT locally provides a high level summary of the block packages. Could we have one for the new Bluetooth blocks please? I couldn't see where to add this myself.... happy to do so if you could point me in the right direction. Thanks.

**Comment by pelikhan** [comment]
It is at the bottom, I've added the summary. Feel free to change it.

**Comment by bluetooth-mdw** [comment]
I still don't see it when rendered in the browser. Which markdown file do you edit to put an entry onto the reference page? I see microbit-bluetooth in the ## Advanced section of reference.md but the web page itself contains nothing in that section.

**Comment by pelikhan** [comment]
That sentence is pulled in from the source. https://github.com/Microsoft/pxt-microbit/blob/master/libs/microbit-bluetooth/bluetooth.cpp#L7

**Comment by bluetooth-mdw** [comment]
OK but I see nothing on the reference page itself though. See https://drive.google.com/open?id=0B9Z54U0dfwbFT2lsX0lCRXpPV1k

**Comment by pelikhan** [comment]
Try running “pxt update” it should be rendered under “Advanced”. Rendering the Bluetooth stuff required to rev the pxt project.

(also, you can copy paste screenshots directly into the github text box…)

**Comment by bluetooth-mdw** [comment]
Same result but I looked at the HTML and despite seeing an empty code box in the Advanced section, the HTML contains:

```
<h2 id="advanced">Advanced</h2>
<pre><code class="lang-namespaces">devices.tellCameraTo(MesCameraEvent.TakePhoto);
bluetooth.onBluetoothConnected(() =&gt; {});
</code></pre>
<pre><code class="lang-package">microbit-devices
microbit-bluetooth
</code></pre>
    </div>
</div>
```

**Comment by pelikhan** [comment]
Your branch is probably stale. See https://codethemicrobit.com/reference where Bluetooth is present.

The “lang-package” section is a new feature that tells the documentation system which additional package need to be loaded in order to render the blocks.

**Comment by bluetooth-mdw** [comment]
That's it.... "lang-package" is nowhere on my machine. I assume this is defined in the pxt project as opposed to pxt-microbit? I ran pxt update though.... I'm not working on a branch for PXT afaik.... yes I forked pxt-microsoft but that's up to date wrt origin.

![image](https://cloud.githubusercontent.com/assets/8341666/16330276/0ed1c3be-39e0-11e6-9d50-22584cf491fa.png)

**Comment by pelikhan** [comment]
When you launch pxt serve, it should download the latest templates from the web (which renders the lang-package stuff). What is pxt update do for you?

**Comment by bluetooth-mdw** [comment]
(workspace) C:\workspaces\pxt-microbit>pxt update
Using PXT/microbit from C:\workspaces\pxt-microbit.
loading cli extensions...
[run] git pull
Already up-to-date.
Referenced pxt-core dep up to date: 0.2.179
[run] npm.cmd install
