### ISSUE TITLE
There is no Pair device on Edge, IE & Firefox

### ISSUE THREAD

**Issue by AimeeCao18** [Microsoft/pxt-microbit#1436]
Repro steps:
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "More..." to observe

Expected result(Chrome):
Pair device appears on Edge, IE & Firefox.
![1](https://user-images.githubusercontent.com/44188776/47008015-0546cf80-d16c-11e8-8095-72974f3adb54.png)

Actual result(Edge, IE & Firefox):
There is no Pair device on Edge, IE & Firefox.
![2](https://user-images.githubusercontent.com/44188776/47008021-08da5680-d16c-11e8-876d-185ee45b71c4.png)

**Comment by abchatra** [comment]
Edge IE & Firefox doesn't support WebUSB and hence no pair button.
