### ISSUE TITLE
v1: Bluetooth is now off by defualt. Should be JustWorks

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#1437]
**Describe the bug**

On v1 by default Bluetooth has been changed to 'No Pairing Required'

The default mode for Bluetooth should be JustWorks as it is in v0

What's weird is that I think https://github.com/Microsoft/pxt-microbit/blob/3b182fc11deb2825dfb74b1090a7ea724b5852d1/libs/bluetooth/pxt.json#L44  still claims JustWorks is default.

**Comment by jaustin** [comment]
@pelikhan is this something from some of your testing?

**Comment by pelikhan** [comment]
Let’s discuss this in the tech meeting. No pairing now also allow to go into pairing mode. This makes the whole experience consistent.

Just works does not just work on Windows mostly - specially with WebBLE.

**Comment by pelikhan** [comment]
Fixed in v1.1.74
