### ISSUE TITLE
PCA9685 Extension Errors

### ISSUE THREAD

**Issue by alankrantas** [Microsoft/pxt-microbit#1439]
The generic PCA9685 package (https://github.com/jdarling/pxt-pca9685) cause errors and stop working after recent updates.
**I've already file a issue at pxt-pca9685**, which was also updated a few days ago. I am sure it did work fine with V1 editor last week.
![1](https://user-images.githubusercontent.com/44191076/47037113-ac4d5a80-d1b0-11e8-8d4a-cde01a46d07b.jpg)

When I add PCA9685 into V1 editor, I get this error message right after the package downloaded:
![error](https://user-images.githubusercontent.com/44191076/47005117-ae3dfc00-d165-11e8-803b-af005ab227e7.jpg)
And "try to fix" does not work either.

I can proceed to download the code, but the PCA9685 parts will not function. (I use a motor board with built-in PCA9685 chip.)
I've tried built-in PCA9685 libraries from other custom packages (like those for Kitronik and Robot:bit motor boards). Nothing works.
The uDriver_PCA9585 package (https://github.com/tinkertanker/udriver_pca9585) works, but it can only turns regular servos about 90 degrees, even you set it as 0 to 180 degrees.

In V0 editor no immediate errors after downloading, however this message pops up when you try to download the code:
![error2](https://user-images.githubusercontent.com/44191076/47005776-0fb29a80-d167-11e8-8909-e7428f1858b5.jpg)

My older codes containing PCA9685 package (including stuff I've wrote last week) works.

I used Windows 10 with up-to-the-date Chrome browser.

**Comment by abchatra** [comment]
There seems to be error in that package. Package author needs to fix that error.

**Comment by abchatra** [comment]
Older code snaps to a particular version of the package. Can you share that version which works with the package author?

**Comment by pelikhan** [comment]
The package author also needs to create release tags.

**Comment by alankrantas** [comment]
I really knows nothing about this level of coding. We are an organization teaching children coding on micro:bit using MakeCode.

Recently we made a all-in-one expansion board for micro:bit, which features a PCA9685 for multiple servo projects (powered by built-in batteries). I am writing manuals and a book for it. I am scheduled to teach some teachers about it next Monday.

It means we have to stop and wait for the author to fix the problem, or possibly have to rewrite all the materials. The package author still have no updates yet. This delay is simply frustrating. And it looks like packages for two Kitronik boards and the Robot:bit (and maybe the Sloth:bit robot) used the same codes. Their boards will be as useless as ours if nothing is solved.

**Comment by pelikhan** [comment]
@alankrantas I suggest you file a complaint on the https://github.com/jdarling/pxt-pca9685 repo or call their customer service.
@microbit-mark the author of a supported package has broken his package: https://github.com/jdarling/pxt-pca9685 .

**Comment by pelikhan** [comment]
@alankrantas I saw you posted https://github.com/jdarling/pxt-pca9685/issues/3 . I suggest sending an email to the company that sold the board as they may not be monitoring the github issues.

**Comment by alankrantas** [comment]
I did reported it, yesterday afternoon (local time). No replies yet.

We are not using Kitronik boards. I just know they uses PCA9685 as well. The new boards are designed and made in Taiwan.

I am going to ask tinkertanker/udriver_pca9585 can they fix the 90 degree problem.

**Comment by pelikhan** [comment]
You are probably better off having your own repo/package for your product. Unfortunately, we don't know when this user will fix this issue.
@microbit-mark what is the procedure to downgrade a package?

**Comment by microbit-mark** [comment]
@pelikhan The user looks like they are actively developing the package. We would give them an opportunity to fix before taking any further action. One to discuss on next call.

**Comment by jdarling** [comment]
Sorry as I said I had some back problems that put me on my back for several weeks.  Had to use the little out of bed time to do day job related work.

**Comment by jdarling** [comment]
@microbit-mark changes have been rolled back in 0.0.3 and appear to be working again.

@alankrantas if you want control of the package I'll gladly add you to the package just ask.  I built it for a class I was teaching and put it out for anyone else to use.  You could have put in a PR so I could have had my wife click merge.
