### ISSUE TITLE
pins.analogWritePin seems to be stuck on one value

### ISSUE THREAD

**Issue by tinfoilhatter** [Microsoft/pxt-microbit#144]
This code seems to always write `1` to `P0`. If you replace **Math.random** with a constant value such as `88`, it does the same thing (writes `1`).

I observed this behavior in the simulator, and when writing values to the existing **analogReadPin** code sample on two micro:bits (the bar graph never changes). I also observed it when triggering with button `B`, rather than running inside a **forever** loop.

```block
basic.forever(() => {
    pins.digitalWritePin(DigitalPin.P0, Math.random(1024));
});
```

**Comment by tinfoilhatter** [comment]
Sorry, somehow I conflated **analogWritePin** with **digitalWritePin** in the description above.

This example uses **analogWritePin** and always writes `1`.

```
input.onButtonPressed(Button.B, () => {
    pins.analogWritePin(AnalogPin.P0, Math.random(1024));
});
```

**Comment by pelikhan** [comment]
Where do you read 1? What is the complete example?

**Comment by tinfoilhatter** [comment]
Here is the **read** half for the **write** script above. 

```
basic.forever(() => {
    let value = pins.analogReadPin(AnalogPin.P1)
    basic.showNumber(value)
});
```

As soon as you turn this script on, it begins displaying numbers, even when the button on the connected micro:bit is not pressed. They tend to cluster around a few ranges, such as the `300`s, the `900`s, the `3000`s, and the `32000`s. Many of these numbers are far out of bounds of what the other micro:bit is supposed to be writing.

The simulator still shows 1 when it is running the **write** script and the button is pressed.

**Comment by pelikhan** [comment]
Can you take a picture of the circuit you built for this?

**Comment by tinfoilhatter** [comment]
![0623161255b](https://cloud.githubusercontent.com/assets/10347626/16318316/809bb22c-3943-11e6-9eef-deb1564c79f6.jpg)

**Comment by tinfoilhatter** [comment]
**read side**: https://codethemicrobit.com/vycvduyhev

**write side**: https://codethemicrobit.com/zlergspwit

**Comment by tinfoilhatter** [comment]
It turns out that **analog write pin** does not write a continuous analog voltage, but a sine wave that must be sampled and averaged to get the target value.

The API docs now reflect this.
