### ISSUE TITLE
Rock Paper Scissors Tutorial

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-microbit#1441]
Hey Galen,
Can you put together a Rock Paper Scissors Tutorial?  It's one of the most popular projects, and would be great to have it in Tutorial format.
Thanks!
Jacqueline

**Comment by pelikhan** [comment]
Let’s convert the existing side-project into a tutorial.

**Comment by pelikhan** [comment]
I'm going to take a snap at this. Move the RPS project and replace by a simple tutorial

**Comment by pelikhan** [comment]
Updated tutorial is live. @ganicke give it a review pass. @Jaqster i moved the watch to "duct-tape-watch" under "fashion".

**Comment by ganicke** [comment]
I look at it now. RE: #1444

**Comment by pelikhan** [comment]
Done. Please test @Jaqster

**Comment by Jaqster** [comment]
Looks good.  Couple comments:
- One nit-picky comment, can we change the name of the variable from "tool" to "hand"?  Rock Paper Scissors is played with a hand.  Tool just seems a bit strange...
- Break up Step 3 into two different steps: Make a Variable should be it's own step - this may be the first time they have ever made a variable, so we should walk them through this
- Pick Random 1-3  I've seen people get confused with 0-2
- Love the gifs, but don't love the blurry text - looks like something is wrong. Would rather have it in English for other languages than blurry.
