### ISSUE TITLE
Czech Translation, especially Change by

### ISSUE THREAD

**Issue by mericidum** [Microsoft/pxt-microbit#1448]
Hi!
I just started to teach 22 kids with MicroBit and MakeCode. It's great, but I was really disappointed by Czech translation. Some is not "elegant", but there is one really horrible:
The "**Change by**" block is translated as "**Zaměnit za**", which means "**Exchange for**". This is really misleading and user expects function identical to "**Set to**".
I was wondering if this new version gives us opportunity to fix this problem (I propose "**zvyš o**") or improve the quality of Czech translation completely. I volunteer for this.
I only have limited experience in MakeCode, but program in LabVIEW, C, PHP. I have worked on translating Windows 95 into Czech as a student :-) and then translated hundreds of articles and pieces of software.
Thanks!

**Comment by pelikhan** [comment]
Our translations are crowdsource and we'd love to get some more help on the Czech side. You can register as a translator at https://crowdin.com/project/kindscript to start translating or fixing translation.
If you wish to become a proofreader (e.g. being able to validate translation), please send us your resume/linkedin. Thank you!
