### ISSUE TITLE
Embedded YouTube videos have distorted thumbnail image

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#145]
Looks like some scaling is messing the image up somewhere or maybe it's just low quality:

![image](https://cloud.githubusercontent.com/assets/8341666/16334394/8ecb118e-39f8-11e6-8d33-72a1f7e4ca5d.png)

**Comment by pelikhan** [comment]
Fixed now. Make sure the video has a standard 16:9 aspect ratio.
