### ISSUE TITLE
Query about serial redirect

### ISSUE THREAD

**Issue by DavidWhaleMEF** [microsoft/pxt-microbit#1451]
I wish to use serial tx routed to the USB, and serial RX routed to a pin, for a project. Both serial ports will be at the same baud rate, but I want to receive serial data from one device and transmit serial data across the USBSER.

I believe I can do this in MicroPython by passing None to the txpin and a pin object to the rxpin in init:

https://microbit-micropython.readthedocs.io/en/latest/uart.html?highlight=uart#microbit.uart.init

However, I can't see how I could replicate this split setup in MakeCode - is there some magic javascript I could use to create a redirect with a split setup? I can't see it though?

![screen shot 2018-10-17 at 12 23 15](https://user-images.githubusercontent.com/25079586/47083046-74253680-d207-11e8-8fbd-96452dbd2cf9.png)

![screen shot 2018-10-17 at 12 22 52](https://user-images.githubusercontent.com/25079586/47083053-76879080-d207-11e8-8602-0756181d1849.png)

**Comment by pelikhan** [comment]
@whaleygeek  Please test https://makecode.microbit.org/app/5e7315b5c43219136ed17de948c6965d882406da-7bf5c9f8ec'

**Comment by DavidWhaleMEF** [comment]
I didn't really have much success with this sadly. Could you share your test program, so I can see if it works this end? Thanks!

**Comment by pelikhan** [comment]
What is not working?
````
serial.redirect(
SerialPin.USB_TX,
SerialPin.USB_RX,
BaudRate.BaudRate9600
)
basic.forever(function () {
    serial.writeString("hello")	
})
````

**Comment by DavidWhaleMEF** [comment]
It seemed to me that when I redirected TX to USB_TX, the RX stopped working.

For reference, here is the equivalent system on MicroPython, which seems to work...

SENDER
````
from microbit import *

uart.init(baudrate=115200, tx=pin1)
display.show("s")
timeout = None

while True:
    if button_a.was_pressed():
        display.show("A")
        timeout = running_time() + 1000
        uart.write("A")

    elif button_b.was_pressed():
        display.show("B")
        timeout = running_time() + 1000
        uart.write("B")

    if timeout is not None and running_time() > timeout:
        timeout = None
        display.show("s")
```

BRIDGE
```
from microbit import *

uart.write("START\n")
uart.init(baudrate=115200, rx=pin0)
display.show("b")

timeout = None

while True:
    rx = uart.read()
    if rx is not None:
        uart.write(rx)
        display.show(Image.DIAMOND)
        timeout = running_time() + 1000
            
    if timeout is not None and running_time() > timeout:
        timeout = None
        display.show("b")
        
```

SETUP

sender P1 -> bridge P0
sender 3V -> bridge 3V
sender GND -> bridge GND
bridge USB -> mac USB (running serial terminal)

press A or B on sender, sends to bridge, bridge sends to Mac, A or B appears on serial terminal.

**Comment by pelikhan** [comment]
Please send the equivalent microbit-dal C++ sample.

**Comment by DavidWhaleMEF** [comment]
You already have a serial.redirect_to_usb (which does TX and RX simulataneously)

What I need is RX to be connected to a pin, and TX to be connected to USB, so that I can use it as a serial bridge where one half of the serial comes from the edge connector, and the outgoing chars go out via USBSER

**Comment by DavidWhaleMEF** [comment]
![2018-10-19 21 44 31-1](https://user-images.githubusercontent.com/25079586/47243306-7f37bc80-d3e9-11e8-8934-601f7b00b5e6.jpg)

**Comment by DavidWhaleMEF** [comment]
I'm not too fussed if this doesn't work - I have a python version that works now. It just would have been nice to have one microbit as makecode and the other as python.

It may take me some time to get a C++/DAL example together, as I have to progress with my project now. But I'll keep this ticket URL in my TODO list and next time I get a chance to try it again I will report back. Thanks for your help.

**Comment by pelikhan** [comment]
This is the DAL abstraction we are using https://github.com/lancaster-university/microbit-dal/blob/master/inc/drivers/MicroBitSerial.h#L436 . I don't know what Python is using.

**Comment by DavidWhaleMEF** [comment]
Ok great, thanks. I will see if I can reproduce a split redirect in DAL/C++ and report back if that doesn't work. Thanks for your help
