### ISSUE TITLE
Project has no name dialogue appears off screen on iOS

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#1454]
**Describe the bug**
Project has no name dialogue appears off screen because it is pushed up by the iOS keyboard.

It looks like something thinks the entire MakeCode page needs to be above the keyboard, rather than just the dialog, or just the edit control.

**To Reproduce**
1. Go to 'https://makecode.microbit.org/beta'
2. Click on 'New Project'
3. Click on 'Home'

**Expected behavior**
The edit control should be visible on screen and above the keyboard.

**Screenshots**
![img_0147](https://user-images.githubusercontent.com/989126/47090637-37633a80-d21b-11e8-902c-824354ee6384.png)

**Desktop (please complete the following information):**
 - OS: iPad Air, iOS 11.4.1
 - Browser Safari
 - Version makecode.microbit.org 1.1.74

**Comment by abchatra** [comment]
This is fixed
