### ISSUE TITLE
Edge - Show Icon field editor

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#1455]
On Edge, the Show Icon field editor cuts off the right column of icons

![showiconedge](https://user-images.githubusercontent.com/22108954/47113207-45aa5a00-d20d-11e8-85b0-a81e978bed50.png)

**Comment by Jaqster** [comment]
I'm on Microsoft Edge 44.17763.1.0, Microsoft EdgeHTML 18.17763.
You have to fiddle with it a bit... try clicking on different icons and opening/closing field editor

**Comment by samelhusseini** [comment]
Ah I see it now, that's so bizarre only happens just after selecting one of the options and then immediately going back to select a different one.

**Comment by abchatra** [comment]
Won't Fix old bugs on Edge or IE.
