### ISSUE TITLE
Can't edit "on event from" block in iOS

### ISSUE THREAD

**Issue by martinwork** [Microsoft/pxt-microbit#1460]
**Describe the bug**
The popup menus in the "on event from" block do not support scrolling properly. They disappear as soon as a drag-to-scroll finishes, so selecting items further down the list is extremely awkward.

**To Reproduce**
1. Go to 'https://makecode.microbit.org/beta'
2. Tap on 'New Project'
3. Add 'on event from' block from Advanced/Control
4. Try to change MICROBIT_BUTTON_A to MICROBIT_ID_IO_P12

**Expected behavior**
I expect the list to scroll and not disappear when I lift my finger, so I can tap to make a choice.

**Desktop (please complete the following information):**
 - OS: iPad Air iOS 11.4.1
 - Browser Safari
 - Version makecode.microbit.org 1.1.78

**Comment by abchatra** [comment]
I could repro this in Ipad.

**Comment by samelhusseini** [comment]
Do you mean to scroll to the ticket item? 
and could you provide a screenshot of what you mean by open at the top on Windows? 

Thanks

**Comment by samelhusseini** [comment]
Fix is here https://github.com/Microsoft/pxt-blockly/pull/157. 
Still needs to be integrated and released in a microbit release.

**Comment by samelhusseini** [comment]
Fixed.
