### ISSUE TITLE
the keycommand ctrl+left/right should jump between words, not open the menu

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt-microbit#1461]
**Describe the bug**
The normal behavior in text editors when you press ctrl+left/right is to jump between words. But the makecode editor steals this shortcut for opening the menu instead.

**To Reproduce**
1. Open editor
2. go to javascript
3. press ctrl+left arrow

**Expected behavior**
Jump between words

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser firefox
 - Version /beta

**Comment by abchatra** [comment]
@samelhusseini Is this by design?

**Comment by samelhusseini** [comment]
This was done for accessibility reasons but I hadn't realized that the CtrlCmd + arrow keys were already used for navigating around the editor. 
I am working on a change to use a different shortcut to get into the toolbox menu.

**Comment by samelhusseini** [comment]
https://github.com/Microsoft/pxt/pull/4867
