### ISSUE TITLE
Tutorial "Rock Paper Scissors" picture is not clear in tutorial 7th and 9th steps

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1462]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta
2. Scroll down to Games -> "Rock Paper Scissors" -> "Start Tutorial" -> click the tutorial steps one by one
3. Click to 7th and 9th steps and observe

**Expected result:**
The block picture should be clear in tutorial 7th and 9th steps

**Actual result:**
The block picture is not clear in tutorial 7th and 9th steps
![issue101901](https://user-images.githubusercontent.com/23466737/47200889-6bb93100-d3aa-11e8-8da0-02a9ce3c0eb6.gif)

**Comment by pelikhan** [comment]
By design.
