### ISSUE TITLE
An error shows in example "Karel the LED" tutorial

### ISSUE THREAD

**Issue by AimeeCao18** [Microsoft/pxt-microbit#1463]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/projects/karel
2. Scroll down to "Coding Karel the LED" step 
3. Copy the code to the "JavaScript" editor page

**Expected result:**
Error should not show when copying the example code to "JavaScript" editor

**Actual result:**
An error shows in example "Karel the LED" tutorial
![1](https://user-images.githubusercontent.com/44188776/47201520-bb98f780-d3ac-11e8-80d6-082157c029f7.png)

**Comment by abchatra** [comment]
Nice find. Thanks @AimeeCao18

**Comment by abchatra** [comment]
Although I am not able to repro. Can you try again?

**Comment by AimeeCao18** [comment]
I verified this issue again and it still can repro. Below is the published project
https://makecode.microbit.org/_3puJVFePu4yJ

**Comment by pelikhan** [comment]
TypeScript 2.0 is probably more strict that 1.0 (or the other way around.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
@riknoll can you take a peek?

**Comment by pelikhan** [comment]
I suspect the old version is still cached. I did rewrite that sample.

**Comment by ganicke** [comment]
Moving ``const board = new Board();`` (in the old karel) below the class seems tricksy enough to satisfy both versions in case of cache confusion.

**Comment by pelikhan** [comment]
Make sure to pull the source from https://makecode.microbit.org/v1/projects/karel
