### ISSUE TITLE
The instruction of the tutorial in red box is not clear

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1467]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta
2. Scroll down the scroll bar to Tutorials
3. Click "Micro Chat" and observe the short instruction of the tutorial

**Expected result:**
The instruction of the tutorial should be clear

**Actual result:**
The instruction of the tutorial in red box is not clear
![issue101902](https://user-images.githubusercontent.com/23466737/47211002-fc056f00-d3c6-11e8-9cb8-9f11dcca315a.PNG)

**Comment by ganicke** [comment]
Fixed in #1470
