### ISSUE TITLE
rightclick in menu in javascript mode does not work (firefox)

### ISSUE THREAD

**Issue by nielsswinkels** [microsoft/pxt-microbit#1468]
**Describe the bug**
When in javascript mode, rightclicking on a piece of code in the menu does not give the popup menu that should come up, but shows my browsers own right click menu.

**To Reproduce**
1. (in firefox) Go to javascript mode
2. open the toolbox/menu
3. right click a piece of code

**Expected behavior**
Should show a popup menu with for example the help button

**Screenshots**
![image](https://user-images.githubusercontent.com/5718354/47217270-1d0a9780-d3a8-11e8-9ad8-bab19cfd0aa3.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser firefox
 - Version 62.0.3

**Additional context**
It does work correct in the text editor part. Tested in /beta
makecode.microbit.org version:  1.1.78
Microsoft MakeCode version:  4.1.41
microbit runtime version:  v2.1.0

**Comment by abchatra** [comment]
We don't have right click on the toolbox. Can you add screenshot of other browsers?

**Comment by nielsswinkels** [comment]
Shouldn't there be a right click menu with at least the help option?

**Comment by nielsswinkels** [comment]
Blocks:
![image](https://user-images.githubusercontent.com/5718354/47283044-d6a07d00-d5e1-11e8-9517-6bde6efa2f65.png)

javascript:
![image](https://user-images.githubusercontent.com/5718354/47283080-051e5800-d5e2-11e8-9217-eccc7f0bed46.png)

**Comment by abchatra** [comment]
Monaco editor doesn't support these yet.

**Comment by pelikhan** [comment]
Monaco toolbox is on our side.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
@shakao should we add right click help on toolbox? We have ? now in the toolbox

![image](https://user-images.githubusercontent.com/6107272/77005151-93a12100-691d-11ea-96d1-a3e2393aab2a.png)

**Comment by abchatra** [comment]
We have ? for now for the help.
