### ISSUE TITLE
scrolling up/down with mousewheel click does not work (firefox)

### ISSUE THREAD

**Issue by nielsswinkels** [microsoft/pxt-microbit#1469]
**Describe the bug**
I want to scroll up/down in the text editor by clicking with the mousehweel and then move the mouse up/down. But this only lets me scroll horizontally.

**To Reproduce**
1. Go to javascript mode
2. write a lot of code so it does not fit vertically in the screen
3. mousewheel click
4. move mouse up/down

**Expected behavior**
Should scroll through the code up/down

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser firefox
 - Version 62.0.3

**Additional context**
Not sure if it makes a difference that i have a 4k screen when i tried this? Tested in the /beta

**Comment by abchatra** [comment]
Mouse scroll works fine for me on on Firefox 62 on Windows 10. This scrolls veritically  What is mousewheel click? Can you add a gif ?

**Comment by nielsswinkels** [comment]
when you press down on the mousewheel it clicks, it shows this 
![image](https://user-images.githubusercontent.com/5718354/47282647-588fa680-d5e0-11e8-8818-24159f260dbd.png)
Then you can move your mouse above it to scroll up and below to scroll down. But it doesn't work in the vertical direction in the makecode text editor

**Comment by nielsswinkels** [comment]
![20181022_095609_1](https://user-images.githubusercontent.com/5718354/47282847-0d29c800-d5e1-11e8-8a0c-03d967e7e09e.gif)

**Comment by nielsswinkels** [comment]
![20181022_095609_1](https://user-images.githubusercontent.com/5718354/47282948-65f96080-d5e1-11e8-9c06-edb6b7fbe218.gif)

**Comment by abchatra** [comment]
Monaco doesn't have support for this.
