### ISSUE TITLE
The step number shows error

### ISSUE THREAD

**Issue by AimeeCao18** [Microsoft/pxt-microbit#1473]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/projects/milky-monster
2. Scroll down the scroll bar and click "Code"
3. Scroll down the scroll bar and observe the step number

**Expected result:**
The numerical order of the steps is correct

**Actual result:**
The step number shows error
![capture2](https://user-images.githubusercontent.com/44188776/47284655-b93bd500-d61a-11e8-870f-b043b0155f73.PNG)

**Comment by abchatra** [comment]
Fixed
