### ISSUE TITLE
Printing lessons no longer produces coloured blocks

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1474]
microbit-support:18020

**Describe the bug**
Previously printing in makecode allowed you to print coloured blocks. Blocks are now rendered in black and white.

Children find the colours useful to differentiate blocks

**To Reproduce**
1. Go to 'https://makecode.microbit.org/lessons/beautiful-image'
2. Click on print
3. Preview is in black and white.

**Expected behavior**
Code blocks should print in colour

**Screenshots**
![screenshot 2018-10-22 at 11 34 23](https://user-images.githubusercontent.com/31242877/47288687-0a35d400-d5ef-11e8-8cb1-ce348c51cf5a.png)

![screenshot 2018-10-22 at 11 34 02](https://user-images.githubusercontent.com/31242877/47288705-1d48a400-d5ef-11e8-9904-13f3f2c041b2.png)

**Comment by pelikhan** [comment]
This is by design. Most schools can not afford printing in colors, and some schools still have low quality bw printers. Colored background will print mostly grey and unreadable in those cases.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by microbit-mark** [comment]
Thanks for the feeback @pelikhan. Could it be a choice for those that want to print colour or would you expect these people to create their own resources by downloading screenshots for example
?

**Comment by pelikhan** [comment]
Unfortunately, CSS does not give us a way to decide if we are going for HQ print or using the worst printer available. So we default to working everywhere - even if we have to lose colors.

**Comment by pelikhan** [comment]
See https://github.com/Microsoft/pxt-microbit/issues/1163
