### ISSUE TITLE
Device console does not display data for accelerometer strength over usb

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1475]
**Describe the bug**
Device console does not display data for accelerometer strength over usb

**To Reproduce**
1. Open [microbit-grav.hex.zip](https://github.com/Microsoft/pxt-microbit/files/2501060/microbit-grav.hex.zip) in makecode beta
2. Pair device and flash code
3. Try looking at simulator console, then at device console

![screen recording 2018-10-22 at 11 59 am](https://user-images.githubusercontent.com/31242877/47289453-ad3c1d00-d5f2-11e8-9e6e-ac640d3764a0.gif)

**Expected behavior**
Device data should display

**Desktop (please complete the following information):**
 - OS: Mac 10.14
 - Browser Chrome 70

**Additional context**
This did work initially, but then produced the error on subsequent flashes.

**Comment by abchatra** [comment]
Can you share the code? I don't see a new line after the code. It is necessary to flush the serial data out.

**Comment by pelikhan** [comment]
write value adds a new line but something must be wrong on the BLE stack. Did the device run out of memory?

**Comment by abchatra** [comment]
Can't repro.
