### ISSUE TITLE
radio package text rendered at the bottom of a tutorial hint

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt-microbit#1477]
**Describe the bug**
radio (package) text shows in the last tutorial hint of the micro chat tutorial. 

**To Reproduce**
1. Go to the v1 editor and open the micro chat tutorial
2. Navigate to the final step
3. See that the text "radio" shows at the bottom of the hint

**Expected behavior**
No text

**Screenshots**
<img width="931" alt="screen shot 2018-10-22 at 10 21 44 am" src="https://user-images.githubusercontent.com/16690124/47307683-81199f80-d5e4-11e8-84a2-be96cfef9698.png">

**Desktop (please complete the following information):**
 - OS: Mac Safari

**Additional context**
@pelikhan I thought you added a change to not render those. Has the been integrated or is this something different?

**Comment by pelikhan** [comment]
It’s probably not in the branch.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
Fixed
