### ISSUE TITLE
Sharing embed (code-embed) feature not working

### ISSUE THREAD

**Issue by samelhusseini** [microsoft/pxt-microbit#1478]
**Describe the bug**
Unable to embed code snippet using the "Code" embedding feature

**To Reproduce**
1. Create some code to share
2. Click on Share and publish
3. Click on Embed and on the first tab (Code)
4. Copy the produced HTML and paste it in a jsfiddle
5. See that it doesn't load and error in the console

Note: If testing beta, you will need to update the share URL to point to makecode.microbit.org/v1/

**Expected behavior**
Iframe loads and shows code snippet

**Error log**

bluebird.min.js:29 Unhandled rejection TypeError: Cannot read property 'lastIndexOf' of undefined    at Object.parseSourceFile (https://pxt.azureedge.net/blob/0492ac1eb98fc8eaf9cb5086fd8c2cc9ee30ee48/typescript.js:7689:91)    at Object.createSourceFile (https://pxt.azureedge.net/blob/0492ac1eb98fc8eaf9cb5086fd8c2cc9ee30ee48/typescript.js:7563:29)    at Object.getSourceFile (https://pxt.azureedge.net/blob/224c2acb29c3c41591fc04f5704ee85b07e1141e/pxtcompiler.js:8087:31)    at findSourceFile (https://pxt.azureedge.net/blob/0492ac1eb98fc8eaf9cb5086fd8c2cc9ee30ee48/typescript.js:40198:29)    at processSourceFile (https://pxt.azureedge.net/blob/0492ac1eb98fc8eaf9cb5086fd8c2cc9ee30ee48/typescript.js:40146:27)    at processRootFile (https://pxt.azureedge.net/blob/0492ac1eb98fc8eaf9cb5086fd8c2cc9ee30ee48/typescript.js:40056:13)    at https://pxt.azureedge.net/blob/0492ac1eb98fc8eaf9cb5086fd8c2cc9ee30ee48/typescript.js:39602:60    at Object.forEach (https://pxt.azureedge.net/blob/0492ac1eb98fc8eaf9cb5086fd8c2cc9ee30ee48/typescript.js:945:30)    at Object.createProgram (https://pxt.azureedge.net/blob/0492ac1eb98fc8eaf9cb5086fd8c2cc9ee30ee48/typescript.js:39602:16)    at Object.compile (https://pxt.azureedge.net/blob/224c2acb29c3c41591fc04f5704ee85b07e1141e/pxtcompiler.js:8117:30)    at https://pxt.azureedge.net/blob/757d610210210339562940a5e53f23d62773a591/pxtrunner.js:1329:33    at r (https://pxt.azureedge.net/blob/59afc96c4d4f42688a216db27c16c474c61ff9a1/bluebird.min.js:31:9367)    at i._settlePromiseFromHandler (https://pxt.azureedge.net/blob/59afc96c4d4f42688a216db27c16c474c61ff9a1/bluebird.min.js:30:14566)    at i._settlePromise (https://pxt.azureedge.net/blob/59afc96c4d4f42688a216db27c16c474c61ff9a1/bluebird.min.js:30:15369)    at i._settlePromise0 (https://pxt.azureedge.net/blob/59afc96c4d4f42688a216db27c16c474c61ff9a1/bluebird.min.js:30:16070)    at i._settlePromises (https://pxt.azureedge.net/blob/59afc96c4d4f42688a216db27c16c474c61ff9a1/bluebird.min.js:30:17400)

Tested on: 
Chrome OSX. 

JSFiddle: 
https://jsfiddle.net/xtb8qpca/

**Comment by pelikhan** [comment]
This is a versioning issue. This line is not being patched.
```
            pxtFrame.src = "/--docs?render=1"
```

**Comment by samelhusseini** [comment]
Fix here: https://github.com/Microsoft/pxt/pull/4887/files

**Comment by samelhusseini** [comment]
Fix is in master. Waiting on the github webhooks to be back alive and the cloud to recognize there's been a change. 

Use http://jsfiddle.net/sh48L7v5 to test
