### ISSUE TITLE
"stop animation" doesn't stop

### ISSUE THREAD

**Issue by tinfoilhatter** [Microsoft/pxt-microbit#148]
I have tried to stop several kinds of animation with **stop animation**. It was recommended I try it in combination with **show string**. Even this does not stop the animation, either in the simulator or on the micro:bit. 

Pressing the button in the code below seems to do nothing.

https://codethemicrobit.com/fqzywcwuch

```
basic.showString("STOP ME! STOP ME! PLEASE, WON'T SOMEBODY STOP ME?");
input.onButtonPressed(Button.B, () => {
    led.stopAnimation();
});
```

**Comment by microsoftsam** [comment]
You need to register the handler before showing the string. Swapping these two blocks works: 
```
input.onButtonPressed(Button.B, () => {
    led.stopAnimation();
});
basic.showString("STOP ME! STOP ME! PLEASE, WON'T SOMEBODY STOP ME?");
```

**Comment by tinfoilhatter** [comment]
It works!
