### ISSUE TITLE
Accelerometer simulator UI logic doesn't work in shared view

### ISSUE THREAD

**Issue by samelhusseini** [microsoft/pxt-microbit#1485]
**Describe the bug**
Accelerometer simulator UI logic doesn't work in shared view. 

**To Reproduce**
1. Create a project that uses the on shake block and share it
2. GO to the shared view and click on the simulator (tri) button at the top
3. Try to move the simulator by hovering over it
4. See how it's stuck in this view (see screenshot)

**Expected behavior**
The same behavior as in the simulator and full screen views

**Screenshots**
<img width="938" alt="screen shot 2018-10-22 at 11 27 51 am" src="https://user-images.githubusercontent.com/16690124/47311203-f6d63900-d5ed-11e8-8bfb-fd17162ca27b.png">

**Desktop (please complete the following information):**
 - OS: Mac
- Browser: Chrome
 - Version: 70

**Comment by abchatra** [comment]
This is fixed.
