### ISSUE TITLE
Issues with the function block field

### ISSUE THREAD

**Issue by JoshuaLowe1002** [Microsoft/pxt-microbit#1499]
**Describe the bug**
@samelhusseini already knows about this (discussed via an email over PXT-Blockly) but I thought i'd log it anyway. When you click on the function block text field, the text editor expands in a way that is different to other blocks (presumably because it's not a shadow block.

**To Reproduce**
1. Go to 'Functions'
2. Click on 'Create a function'
3. Click on the function name text field
4. See the bug with the text field editor

**Expected behavior**
The text field editor is not meant to go that big as it's not rendering properly.

**Screenshots**
Here is the function block next to a normal text field with another none expanded function block beneath it.

![image](https://user-images.githubusercontent.com/25752941/47369366-6a09a900-d6db-11e8-8a41-31b30313bc6a.png)

**Desktop (please complete the following information):**
 - OS: Windows + Ubuntu
 - Browser Firefox

**Comment by samelhusseini** [comment]
Thanks for logging @JoshuaLowe1002. This bug is already tracked in https://github.com/Microsoft/pxt-microbit/issues/1457

**Comment by JoshuaLowe1002** [comment]
Ah, didn't spot!
