### ISSUE TITLE
Losing the "bread crumbs" in Getting Started when go to "Projects" part

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt-microbit#150]
If you are stepping through the "Getting Started" there are bread crumbs at the top that allow you to go back (getting-started ->rock-paper-scissors). After Rock Paper Scissors, the next step is "Projects". On the Projects page, there is a bread crumb at the top.

**Comment by abchatra** [comment]
I cannot repro this. Please add a screenshot if you see this again.
