### ISSUE TITLE
"Square" tutorial is not complete on 4th and 6th steps

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1509]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta
2. Scroll down the scroll bar to "Turtle" -> click "Square" -> "Start Tutorial" -> click the tutorial steps one by one

**Expected result:**
The tutorial should be complete 

**Actual result:**
"Square" tutorial is not complete on 4th and 6th steps
![issue1024002](https://user-images.githubusercontent.com/23466737/47420292-a824cc80-d7b0-11e8-8583-1a245dca4e60.PNG)
![issue1024003](https://user-images.githubusercontent.com/23466737/47420297-abb85380-d7b0-11e8-9072-3e95f5621729.PNG)

**Comment by abchatra** [comment]
@Helen09 good find.

**Comment by ganicke** [comment]
Fixed in #1514
