### ISSUE TITLE
Bluetooth package contains 'newline' block

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#151]
- [ ] add ``blockHidden`` to CommentAttr
- [ ] do not add block to toolbox when populating
- [ ] annotate bluetooth library

![image](https://cloud.githubusercontent.com/assets/8341666/16375539/c7e9b986-3c53-11e6-9899-d0f150ae9b64.png)

**Comment by cpseager** [comment]
That is correct for the Blockly 'shadow block' way of doing things - it is required to be able to convert the uart read 'shadow' block into a 'real' block.

**Comment by bluetooth-mdw** [comment]
OK, that may well be how it works.... just saying it's an odd user experience and if possible it would be good to eliminated this. @pelikhan I think we'd be OK allowing unconstrained strings to be entered into the read uart block rather than have a drop down. I assume this would address the issue of the 'shadow block'?

**Comment by cpseager** [comment]
In this case a simple drop down list may be better and get rid of the shadow completely (e.g. see the Input > rotation block for a similar looking template).

**Comment by bluetooth-mdw** [comment]
Thanks for the suggestion. The original plan was to allow any *single* character to be specified as a delimiter. This proved difficult and led to using a drop down of finite values. I think I'd rather give developers the freedom to specify any value as the "end of message delimiter". There's actually no reason why they shouldn't specify more than one character i.e. a delimiter string so on reflection I think this is the way to go.

**Comment by pelikhan** [comment]
You can provide a string to this API. Try it JavaScript.

Remember that your audience are y7 and too much choice is confusing.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by bluetooth-mdw** [comment]
Year 7. Hmmm. Well OK let me do a 180 degree turn (again!). Leave it with a finite list/drop down but is there any way to get rid of the newline block? Just looks weird....

**Comment by abchatra** [comment]
No immediate plan of action here. Closing.
