### ISSUE TITLE
After clicking "Finish" button in the tutorial, pages jump to the home page

### ISSUE THREAD

**Issue by AimeeCao18** [Microsoft/pxt-microbit#1510]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta
2. Scroll down the scroll bar to Turtle-> Click "Square"-> Click "Start Tutorial"
3. Follow the tutorial steps to click Finished

**Expected result(Edge, Chrome & Firefox):**
Stay on the editor page.
![expect](https://user-images.githubusercontent.com/44188776/47420572-5892d080-d7b1-11e8-99f1-7142c2abcb61.gif)

**Actual result(IE):**
After clicking "Finish" button in the tutorial, pages jump to the home page
![actual](https://user-images.githubusercontent.com/44188776/47420579-5cbeee00-d7b1-11e8-8793-b35ac9f2d7b2.gif)

**Comment by abchatra** [comment]
This is intentional in IE. As there are issues with that browser reloading the same page. It is a non ideal. workaround. Good observation though!

**Comment by abchatra** [comment]
Can't fix
