### ISSUE TITLE
Embedded SVG blocks with V1 won't render

### ISSUE THREAD

**Issue by microbit-rosslowe** [Microsoft/pxt-microbit#1511]
**Describe the bug**
As described on https://makecode.microbit.org/blocks-embed (and https://makecode.microbit.org/v1/blocks-embed/) code snippets can be embedded as SVGs. Changing the src in `injectRenderer()` to `https://makecode.microbit.org/v0--docs?render=1`, blocks are still rendered correctly. However, replacing with `v1` or `beta`, blocks do not render and code doesn't render:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/30410608/47443889-339c5e80-d7ad-11e8-9275-1d95a8aaff5c.png">

**To Reproduce**
1. Copy embed code in https://makecode.microbit.org/blocks-embed, this also works with the given JSFiddle example https://jsfiddle.net/ndyz1d57/80/
2. Change the src in `injectRenderer()` as described above

**Expected behavior**
Blocks to render with v1/beta appearance.

**Screenshots**
Using `https://makecode.microbit.org/v0--docs?render=1`:
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/30410608/47444102-a574a800-d7ad-11e8-8aff-84939f8e901a.png">

Using v1 or beta:
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/30410608/47444124-b0c7d380-d7ad-11e8-9066-e6b9327f3731.png">

Console:
<img width="498" alt="image" src="https://user-images.githubusercontent.com/30410608/47444164-c6d59400-d7ad-11e8-97f9-91e2ab01e6aa.png">

<img width="498" alt="image" src="https://user-images.githubusercontent.com/30410608/47444216-e66cbc80-d7ad-11e8-9837-c03da5bd34d1.png">

**Desktop (please complete the following information):**
 - OS MacOS
 - Browser Safari
 - Version 12.0

**Comment by pelikhan** [comment]
A / is missing before —docs

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by samelhusseini** [comment]
Yeah that's our bade @microbit-rosslowe. 
Fix is coming up: https://github.com/Microsoft/pxt-microbit/pull/1512

**Comment by samelhusseini** [comment]
Fixed in beta

**Comment by pelikhan** [comment]
Try passing instead:

    options: {}

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by microbit-rosslowe** [comment]
@pelikhan That also works, thanks
@samelhusseini Great, does #1512 also fix layout issues?

**Comment by jaustin** [comment]
@microbit-rosslowe could you open another issue for the rendering issue please?

**Comment by samelhusseini** [comment]
There are a number of different layout modes that we can render in. 
Are you seeing issues with the default? Would be great to have a jsfiddle with a code snippet that repro's your layout issue. Thanks!

**Comment by pelikhan** [comment]
it's the snippetMode - it is supposed to rip out the "on start" block to only see the statement block.

**Comment by samelhusseini** [comment]
so do we need a better default @pelikhan? or is that a less used scenario which we should at a minimum update our documentation about?

**Comment by pelikhan** [comment]
This is a somewhat less known option. Definitely not to be used as a default.

**Comment by microbit-rosslowe** [comment]
Just a final note, to get the layout to work correctly I needed to completely remove `options` (`options:{}` still had the layout issue).
