### ISSUE TITLE
"Rock Paper Scissors" tutorial is not complete on 3th and 4th steps

### ISSUE THREAD

**Issue by AimeeCao18** [Microsoft/pxt-microbit#1517]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta
2. Scroll down the scroll bar to "Games" -> Click "Rock Paper Scissors" -> "Start Tutorial" -> click the tutorial steps one by one

**Expected result:(Chrome & Firefox)**
The tutorial should be complete

**Actual result:(IE & Edge)**
"Rock Paper Scissors" tutorial is not complete on 3th and 4th steps
![capture3](https://user-images.githubusercontent.com/44188776/47474028-ce497b80-d847-11e8-8f88-59588cc7a767.PNG)
![capture4](https://user-images.githubusercontent.com/44188776/47474039-d7d2e380-d847-11e8-98d8-f85f9be5fdfa.PNG)

**Comment by abchatra** [comment]
@AimeeCao18 good find.

**Comment by pelikhan** [comment]
This is fixed.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-microbit/commit/44a47a7e5c325accedfecbb32a95976c5d32e883

**Comment by pelikhan** [comment]
This is due to our picky parsing of tutorial steps.

**Comment by abchatra** [comment]
Fixed

**Comment by ganicke** [comment]
Was just gonna hit commit on that one. Better to fix the text parse.
