### ISSUE TITLE
buffer.createBufferFromArray is missing

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-microbit#1519]
Missing API from v0

**Comment by abchatra** [comment]
Do other API in that file need to be there as well? Like packedSize, packedBuffer, unpackBuffer etc?

**Comment by pelikhan** [comment]
We moved to common packages but we might have missed one. I think we can compare the locale strings.json files to flag any API differences we missed.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pelikhan** [comment]
Fixed by https://github.com/Microsoft/pxt-microbit/commit/11dbaabe3a46d5394f306419fd7cb0ce161a6142
