### ISSUE TITLE
Approved packages without releases

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-microbit#1522]
These packages do not have a valid release (e.g. ```v0.0.0```) and we are unable to lock them for v0.

- [x] jdarling/pxt-pca9685: no valid release found
- [ ] Imagimaker/pxt-imagimaker: no valid release found
- [x] Annikken/pxt-Andee: no valid release found
- [x] 4tronix/BitBot: no valid release found
- [x] sparkfun/pxt-moto-bit: no valid release found
- [ ] PaulDFoster/pxt-microbit-GY521: no valid release found
- [x] k8robotics/pxt-k8: no valid release found

**Comment by pelikhan** [comment]
@microbit-mark

**Comment by pelikhan** [comment]
I guess we could lock to a commit.

**Comment by microbit-mark** [comment]
I'll contact package owners and ask for a release
