### ISSUE TITLE
Update v0 target config so it points to the v0 branch

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt-microbit#1525]
V0 currently does not pass a version with the targetconfig call. 
This means that it will always get the targetconfig that's in master. We need to port over the logic to send the editor version to v0 before we move v1 into master, otherwise v0 will be using v1's targetconfig. 

@abchatra @pelikhan FYI

**Comment by abchatra** [comment]
@samelhusseini can you port the change to v0 and keep it ready?

**Comment by samelhusseini** [comment]
Fixed in v0/v0-beta
