### ISSUE TITLE
"Publish Project" doesn't work for code that cannot be represented as Blocks

### ISSUE THREAD

**Issue by eric-camplin** [Microsoft/pxt-microbit#153]
any code that cannot convert to blocks shows as reverted to the previous block friendly version  - see this when using the embed feature and fork to view code

**Comment by darrenge** [comment]
Might be a duplicate of #149

**Comment by eric-camplin** [comment]
The difference is that I don't expect the code to convert back to blocks, but I do expect code  to publish fore sharing in TypeScript format (no blockly)

**Comment by mmoskal** [comment]
You can remove 'main.blocks' from the file list (by editing pxt.json). I agree this is not perfect...

**Comment by mmoskal** [comment]
@pelikhan @tballmsft - we need to have a way of dropping blocks from project. There is also currently no way of starting a project without blocks.

**Comment by mmoskal** [comment]
I think it is fixed now

**Comment by eric-camplin** [comment]
Nicely done - tested working: [https://codethemicrobit.com/fgatsxwpcd](https://codethemicrobit.com/fgatsxwpcd)
