### ISSUE TITLE
It will be timeout in android phone first time download

### ISSUE THREAD

**Issue by shaoziyang** [microsoft/pxt-microbit#1531]
**Describe the bug**
When using webusb to download program in a android phone first time, it will be timeout. But if download a program from computer first then download from android phone, it will work fine.

**To Reproduce**
1. open chrome browser in a android phone.
2. open url "https://makecode.microbit.org/beta#editor?webusb=1"
3. pair device with microbit
4. download program

**Smartphone (please complete the following information):**
 - Device: android phone
 - OS: android 6/7
 - Browser: Chrome
 - Version : 67

**Comment by abchatra** [comment]
Closing more than an year old bugs. If this still reproduces please reopen.
