### ISSUE TITLE
"neopixel" and "microturtle" package details page simulator loading blank

### ISSUE THREAD

**Issue by AimeeCao18** [microsoft/pxt-microbit#1534]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "Advanced" -> "Extensions" -> Click on the "learn more" button in the "neopixel/microturtle" package
3. Click the "Triangle" button on the page to launch the simulator

**Expected result:**
The simulator works normally

**Actual result:**
"neopixel" and "microturtle" package details page simulator loading blank
![expect-neopixel](https://user-images.githubusercontent.com/44188776/47551300-66249380-d934-11e8-8085-0b2e860e6346.gif)
![expect-microtutle](https://user-images.githubusercontent.com/44188776/47551317-70df2880-d934-11e8-9b55-ae6ec5ddddb1.gif)

**Comment by abchatra** [comment]
This is fixed.
