### ISSUE TITLE
Video in About Bluetooth page is broken

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#154]
![image](https://cloud.githubusercontent.com/assets/8341666/16453690/b164db56-3e05-11e6-963d-04ab234c6087.png)

**Comment by thomasdenney** [comment]
It looks like this is fixed now. Are there any steps to reproduce? It works fine for me in Edge and Chrome.

**Comment by gingemonster** [comment]
looks fine here as well

**Comment by pelikhan** [comment]
Fixed.
