### ISSUE TITLE
"Move the .hex file to the {0}" not appear on Crowdin

### ISSUE THREAD

**Issue by sgk** [Microsoft/pxt-microbit#1547]
"Move the .hex file to the {0}" and other strings in "editor/extension.ts" does not appear on Crowdin. This is the reason it is not possible to add translations for these strings.
![image](https://user-images.githubusercontent.com/485416/47616696-a4bc7880-db03-11e8-90bb-c0e6d5dc03f2.png)

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/pull/4933/

**Comment by pelikhan** [comment]
The strings have been uploaded to crowdin.

**Comment by abchatra** [comment]
Fixed
