### ISSUE TITLE
404 in experiments help

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt-microbit#1548]
**Describe the bug**
This doc link is 404: https://makecode.microbit.org/experiments

**To Reproduce**
1. Go to 'settings'
2. Click on 'about'
3. Click on 'experiments'
4. Click on '?'

**Screenshots**
![image](https://user-images.githubusercontent.com/6107272/47618720-a0f10d80-da93-11e8-9917-6847faa43cd0.png)

**Comment by ganicke** [comment]
Hmm, the link itself https://makecode.microbit.org/experiments isn't working for me. What does the address tip show when you hover of the **?** symbol?

**Comment by pelikhan** [comment]
I think that page needs to be created.

**Comment by ganicke** [comment]
OK.

**Comment by ganicke** [comment]
Help link destination added in #1550
