### ISSUE TITLE
Simulator and compiled version not matching for Images

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt-microbit#155]
I have an image that only changes the offset when A, B and A+B are set. I actually think the simulator is correct as the device has LEDs that are lit up in the corners when there shouldn't be. Maybe compile issue.

Repro:
* Go to this one: https://codethemicrobit.com/xpdfstvlgv
* Press B 
* Press A
** Notice - on the device, the LED in upper right is still on but simulator has it off
* Press B
* Press A+B
** Notice - on the device, now the LED in upper left is still on but simulator has it off

**Comment by thomasdenney** [comment]
The generated Assembly correctly calls [`ImageMethods::showImage`](https://github.com/Microsoft/pxt-microbit/blob/master/libs/microbit/images.cpp#L42), so this isn't a compiler bug. This function then calls [`MicroBitDisplay::print`](https://github.com/lancaster-university/microbit-dal/blob/master/source/drivers/MicroBitDisplay.cpp#L688), which in turn calls [`MicroBitDisplay::printAsync`](https://github.com/lancaster-university/microbit-dal/blob/master/source/drivers/MicroBitDisplay.cpp#L556). This then calls [`MicroBitImage::paste`](https://github.com/lancaster-university/microbit-dal/blob/master/source/types/MicroBitImage.cpp#L490), which only [updates LEDs to turn them on](https://github.com/lancaster-university/microbit-dal/blob/master/source/types/MicroBitImage.cpp#L524). I therefore suggest that the showImage function is adapted to clear the screen first, seen as this doesn't go against what is documented in Lancaster's DAL.

**Comment by abchatra** [comment]
Ported to pxt repo: https://github.com/Microsoft/pxt/issues/555
