### ISSUE TITLE
Feature: Toggle between sideways scroll of projects and grid

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1553]
ticket:18298

**Is your feature request related to a problem? Please describe.**
On the homepage of the v1 editor 3 user projects are listed and you can then sideways scroll to the next 3 and the next 3 etc. In the v0 editor you could list more projects

from user: "as a teacher, [being able to see all projects] is important because I have A LOT of them. Now I can only see a few at a time, and I don't think all of my files even show up in the list anymore.

Is there anything you can do about putting a toggle in between the scrolling list and a screen array of files?"

**Describe the solution you'd like**
Toggle between side ways scroll and list view of projects

**Comment by samelhusseini** [comment]
That makes sense @HyperDuino. Thanks for the feedback, I’ll look into this :)

**Comment by HyperDuino** [comment]
Thank you! I appreciate the responsiveness.

**Comment by samelhusseini** [comment]
The latest script manager feature resolves this issue. I'll keep this open until it gets integrated into the microbit editor.

**Comment by microbit-mark** [comment]
microbit support: 19111 More support for this feature from another user.
@samelhusseini when will the script manager feature be integrated and can we demo it?

**Comment by abchatra** [comment]
ETA early Jan.

**Comment by abchatra** [comment]
Fixed, script manager live in /beta.
