### ISSUE TITLE
V1 "my projects" is different than V0

### ISSUE THREAD

**Issue by HyperDuino** [Microsoft/pxt-microbit#1556]
**Describe the bug**
When I look at "my projects" in V1, I see a different list than in V0

**To Reproduce**
https://makecode.microbit.org/:

![image](https://user-images.githubusercontent.com/13832091/47695884-6ab1ac00-dbc1-11e8-954b-63f637213680.png)

https://makecode.microbit.org/v0:

![image](https://user-images.githubusercontent.com/13832091/47695902-8321c680-dbc1-11e8-985d-5c51bb36e00d.png)

**Expected behavior**
The two lists should be the same.  

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: OX X 10.11.6
 - Browser: Chrome
 - Version Version 69.0.3497.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
n/a

**Additional context**
none

**Comment by pelikhan** [comment]
The projects in v0 and v1 will eventually diverge. The first time you open v1, we clone all your existing v0 projects but we only do this once. You can import v0 projects in v1 via a .hex file.

**Comment by HyperDuino** [comment]
There should probably be some information about that then when users are told that they can continue to use v0 for the next 2 years.  I was just going from the email announcement with the v0 option described.  I saw that another user in the "toggle" issue (https://github.com/Microsoft/pxt-microbit/issues/1553) said that they thought there were missing projects, and this is probably the cause.

**Comment by abchatra** [comment]
First time you move to v1 all the projects will be imported and then any new projects will be specific to v1 or v0. This is by design.
