### ISSUE TITLE
Advanced APIs

### ISSUE THREAD

**Issue by tinfoilhatter** [Microsoft/pxt-microbit#156]
Some APIs are probably too advanced to explain to children, and should be broken out into an Advanced section. The following is a tentative list.

* Bluetooth: All APIs
* Pins
    * analogSetPeriod
    * onPulsed
    * pulseDuration
    * servoWritePin
    * servoSetPulse
    * i2cReadNumber
    * i2cWriteNumber
    * setPull
* Serial
    * serial write line
    * serial write number
    * serial write value
    * serial write string
    * serial read line
    * serial redirect to
* Control
    * raise event
    * on event
    * event timestamp
    * event value
    * device name
    * device serial number

**Comment by tinfoilhatter** [comment]
To the list above add **Pins.map**.

**Comment by tinfoilhatter** [comment]
To list above, add **write value to serial** (Radio).

**Comment by abchatra** [comment]
All there are moved to advanced section
