### ISSUE TITLE
Reduce delay for events

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1563]
support ticket: 18290

**Is your feature request related to a problem? Please describe.**
Using the On Gesture event handling - with say - button pressing and/or orientation detection (i.e. up/down) is very slow to respond.

e.g. running the code below:
 
```
input.onButtonPressed(Button.A, function () { basic.showString("a")})
input.onButtonPressed(Button.B, function () { basic.showString("b")})
```
and then pressing the a and b buttons rapidly, buffers up the key presses.

I understand why it would be slow for shaking - but for button pressing this should either be (almost) instantaneous, or a different way to ask the state of the buttons/orientation would be invaluable.

**Describe the solution you'd like**
- Offer a reduced delay parameter before the event being handled - I realise this may not be feasible.
or
- Add an api call that returns the current state of the orientation and key pressed states - so that a loop can be performed checking for changes to values.

The latter could be something like the micro python solution - e.g. button_a.was_pressed(), button_b.is_pressed(), accelerometer.current_gesture()

**Additional context**
This also seems to be partly down to the display api, having a delay before displaying new data.

e.g. the following has almost instant response over serial:
 
```
let last_write = ""
function write_new(val: string) {
if (val != last_write) {
serial.writeLine(val)
last_write = val
}
}
function acceleration_direction() {
let x = input.acceleration(Dimension.X)
let y = input.acceleration(Dimension.Y)
let z = input.acceleration(Dimension.Z)
let xa = Math.abs(x)
let ya = Math.abs(y)
let za = Math.abs(z)
let result = "Z"
// N.B. Need a transfer 'zone' percentage
if ((xa >= ya) && (xa >= za)) { // X is biggest
if (x >= 0) {
result = "right"
} else {
result = "left"
}
} else if ((ya >= za)) { // Y is biggest
if (y >= 0) {
result = "forward"
} else {
result = "backward"
}
} else { // Z is biggest
if (z >= 0) {
result = "down"
} else {
result = "up"
}
}
return result
}
basic.forever(function () {
if (input.buttonIsPressed(Button.AB)) {
write_new("+")
} else if (input.buttonIsPressed(Button.A)) {
write_new("a")
} else if (input.buttonIsPressed(Button.B)) {
write_new("b")
} else {
write_new(acceleration_direction())
}
})
```

**Comment by pelikhan** [comment]
```basic.showString``` introduces a 400ms pause by design. Add ```led.stopAnimations()``` before show string to make it instant.

**Comment by abchatra** [comment]
This is by design.

**Comment by andrewfstratton** [comment]
Quick comment - it's led.stopAnimation()

> `basic.showString` introduces a 400ms pause by design. Add `led.stopAnimations()` before show string to make it instant.
