### ISSUE TITLE
Catch the Egg tutorial broken?

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1564]
support ticket: 18333

**Describe the bug**
There is some missing block documentation  in the tutorial at 
https://makecode.microbit.org/lessons/catch-the-egg-game/ have they been deprecated?
and
should https://makecode.microbit.org/lessons/catch-the-egg-game/tutorial render in blocks or is the user expected to copy and paste the JS?

**Additional context**
User who reported this has recreated the game at https://makecode.microbit.org/69274-26429-91642-73076

**Comment by abchatra** [comment]
@ganicke can you please fix this.

**Comment by pelikhan** [comment]
the "lesson" are activities we bulked migrated from the touchdevelop time. I wonder where they got surfaced.

**Comment by abchatra** [comment]
Fixed

**Comment by coderdojocastleknock** [comment]
A couple of comments re patch

1. An obsolete block is still referenced, i.e in https://makecode.microbit.org/lessons/catch-the-egg-game/activity challenge 1, game.removelife(1). This  cannot be recreated using current blocks.

as an aside, the leds are a 5x5 matrix,  counting from 0. So why is eggx  set from 0 - 5 in above link ?

**Comment by ganicke** [comment]
The **removeLife()** block is enabled in #1569 but won't appear until the next release.

**Comment by coderdojocastleknock** [comment]
short answer, google microbit catch the egg

first link is the old site
https://www.microbit.co.uk/td/lessons/catch-the-egg-game/tutorial

this is depreciated, so looked at 5th link


https://makecode.microbit.org/lessons/catch-the-egg-game/activity

**Comment by pelikhan** [comment]
A lot of these activities have been migrated at https://makecode.microbit.org/projects

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by coderdojocastleknock** [comment]
thats my point. Its migrated but broken. Tutorial uses blocks which do not
exist now - eg game-lives blocks. Also I reiterate point re picking a
random led x position on a 0 - 4 grid by looking for a random number from 0
- 5 !

**Comment by ganicke** [comment]
When you use the 'beta' editor: https://makecode.microbit.org/beta#editor you will notice the blocks for lives are present:

![image](https://user-images.githubusercontent.com/27789908/47970447-58f55c00-e03a-11e8-8b9b-1976dd3a3827.png)

The life APIs were always there, just not available as blocks. As mentioned earlier, they are turned on in a recent code update. The new blocks will be available when the current version (at https://makecode.microbit.org/#editor is updated at the time of its next release (when Settings -> About shows a version greater than 1.1.19).

As far as the tutorial code goes, we'll take a look at that. Thanks.

**Comment by coderdojocastleknock** [comment]
great. thanks.
