### ISSUE TITLE
v1 Serial blocks are confusing

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#1565]
support ticket: 18334
**Describe the bug**
In v0 the serial blocks made it obvious that they could accept an input/jigsaw piece
<img width="346" alt="screenshot 2018-10-31 at 15 06 51" src="https://user-images.githubusercontent.com/31242877/47797742-cb0a3000-dd1e-11e8-8c81-a549f6d1145f.png">

In v1 there isn't much contrast between serial write and serial read so the write block looks like it has a typo

![image](https://user-images.githubusercontent.com/31242877/47797947-45d34b00-dd1f-11e8-8306-76e9a43273fb.png)

Is there a way to make it more obvious that there are two blocks here?

**Comment by abchatra** [comment]
This is a valid concern. Is this the shadow block? @riknoll can you take a look?

**Comment by microbit-mark** [comment]
Can you update this one @abchatra

**Comment by abchatra** [comment]
I have marked it as next-release.

I am not sure how big this issue is. There is no way to create buffer in blocks. So only input for write buffer is read buffer. Do you have the use case scenario?

**Comment by microbit-mark** [comment]
The user who reported the issue was just confused, thinking there was a mistake in the software that had created a duplicate of serial read buffer within serial write buffer. It's more a design issue than a technical one. Maybe a border around the block indicating it's the input?

![47797947-45d34b00-dd1f-11e8-8306-76e9a43273fb](https://user-images.githubusercontent.com/31242877/48424810-5d68f580-e75b-11e8-908c-baf70909f763.png)
