### ISSUE TITLE
pin20 servo simulator error

### ISSUE THREAD

**Issue by shaoziyang** [microsoft/pxt-microbit#1566]
**Describe the bug**
When using pin20 as servo drive, it will not show correctly wire in simulator. It is not work in **wiring instructions**.

**To Reproduce**
1. set Pin20 as servo drive.
2. It will show wrong pin in simulator.
3. wiring instructions will show blank.

**Screenshots**
![pin20_sim_err](https://user-images.githubusercontent.com/1037534/47801030-51972f80-dd68-11e8-81c4-a245ab44e420.jpg)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: chrome
 - Version: 69

**Comment by pelikhan** [comment]
Fixed.
