### ISSUE TITLE
broken link scan

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#157]
i was at a conference presenting codethemicrobit.com and found broken links with MS partners.here is an example of broken link:

https://codethemicrobit.com/projects/lover-meter

Can you provide a link scan of codethemicrobit to ensure these pages are all in the correct locaiton?

**Comment by darrenge** [comment]
Peli has implemented something in the build process that already does this. We have the scan we just need to go through and fix the broken links.

**Comment by abchatra** [comment]
Correct link is https://codethemicrobit.com/projects/love-meter. Without the r in lover. Closing
