### ISSUE TITLE
Set brightness changes position of LEDs in Edge

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#1573]
**Describe the bug**
When using set brightness at different values the position of the LEDs is changed int he Edge browser

![screen recording 2018-11-02 at 11 40 am](https://user-images.githubusercontent.com/31242877/47913527-5953f280-de94-11e8-9763-7618ba20f6f5.gif)

**Expected behavior**
LEDs maintain position in all browsers

Maybe related
https://github.com/Microsoft/pxt-microbit/pull/651

**Comment by abchatra** [comment]
Won't Fix old bugs on Edge or IE.
