### ISSUE TITLE
Block can't be rendered in some Simplified Chinese's Reference Docs

### ISSUE THREAD

**Issue by imhori** [microsoft/pxt-microbit#1575]
**Describe the bug**
Below pages and related sub-level Docs pages have some rendering block fail.
https://makecode.microbit.org/reference/bluetooth
https://makecode.microbit.org/reference/devices

![bluetoothrenderfail](https://user-images.githubusercontent.com/41528875/47931404-ac1bc180-df09-11e8-9f47-f5dfa6634909.png)

![devicerenderfail](https://user-images.githubusercontent.com/41528875/47931563-1fbdce80-df0a-11e8-919f-63f46e50e2e9.png)

**Desktop (please complete the following information):**
 - OS: macos mojave 10.14.1
 - Browser [chrome]
 - Version [70.0.3538.77 ]

**Additional context**
Some blocks in sub-level Docs are all right in pop-up Help, but block rendering nothing after extend to enlarge in an new page.
![btenlargefail](https://user-images.githubusercontent.com/41528875/47931633-5693e480-df0a-11e8-925e-8dd985232762.png)

**Comment by abchatra** [comment]
Fixed
