### ISSUE TITLE
Activating BBC micro:bit extension

### ISSUE THREAD

**Issue by tinfoilhatter** [Microsoft/pxt-microbit#158]
https://codethemicrobit.com/device/serial

> BBC micro:bit Chrome Extension
> 
> If you are using the Google Chrome browser, you can use our extension to get serial data streaming in the editor.
> 
>     Install the Extension for BBC micro:bit on the Chrome Web Store.
>     Restart Chrome and open the web editor.

The web editor is hard to find in Chrome. This page should probably explain that you can access it from **More Tools > Developer Tools** (if I have the right command; it's not actually _called_ the "web editor").

**Comment by thomasdenney** [comment]
You actually need to open PXT and view the serial output below the simulator
