### ISSUE TITLE
Pick Random's upper limit become blank in imported V0 and V1 Beta projects

### ISSUE THREAD

**Issue by alankrantas** [Microsoft/pxt-microbit#1581]
**Describe the bug**

If you import older projects written in V0 and V1 beta projects, the Pick Random blocks's upper limit will be blank and hence only return zero.

**To Reproduce**

Simply create a code containing Pick Random blocks in V0 editor, download it and open it in V1.

**Expected behavior**

The upper limit shouldn't be blank.

**Screenshots**

![microbit-screenshot](https://user-images.githubusercontent.com/44191076/47954581-7688de00-dfc6-11e8-814b-cbc20b5c00de.png)

![microbit-screenshot 1](https://user-images.githubusercontent.com/44191076/47954582-78eb3800-dfc6-11e8-998a-6165c79c898d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 70.0.3538.77

**Additional context**

This also happens to codes I've written in V1 Beta editor (before V1 became officially online) back in September and October. If I import them now the upper limits are blank. I've already fixed many of them manually.

I have a sample file here. It was downloaded at Oct 22nd in V1 Beta.
[Downloads.zip](https://github.com/Microsoft/pxt-microbit/files/2545131/Downloads.zip)

**Comment by abchatra** [comment]
Please add RCA for this bug.  https://github.com/Microsoft/pxt/blob/master/docs/develop/RCATemplate.md

**Comment by abchatra** [comment]
@alankrantas we can't repro this bug. I tried to create a script in makecode.microbit.org/v0 and it correctly imported. Is it possible for you to share your program in v0 and give us the link to repro?

**Comment by abchatra** [comment]
Downloads.zip also got imported correctly in the latest editor

**Comment by alankrantas** [comment]
I just tried it again and the blocks are now loaded correctly. This was not the case before I reported this bug (happened on different computers I've used).

Perhaps it is related/tied to other issues and are already fixed.
