### ISSUE TITLE
Assembly generation when micro:bit is in 'Play' mode

### ISSUE THREAD

**Issue by programmingthomas** [Microsoft/pxt-microbit#159]
When developing JavaScript or block based programs for the micro:bit the Assembly file is generated and shown in the 'built' folder when you press the Compile button. However, when the editor is in 'Play' mode this file appears and then disappears shortly afterwards.

Steps to reproduce:

1. Create a new project and leave it empty
2. Click More, Show Files
3. Click 'built'
4. Click 'Compile' and then 'Done'
5. The .asm file is present in the 'built' folder
6. Click 'Play'; the .asm and .hex files immediately disappear
7. Click 'Compile' and 'Done' again; the .asm and .hex files are restored to the 'built' folder
8. Switch out of the tab, add or block, or do some other operation that changes the state
9. The .asm and .hex files are both absent

**Comment by abchatra** [comment]
Ported to pxt repo: https://github.com/Microsoft/pxt/issues/554
