### ISSUE TITLE
LED functions don't do anything in Chrome/Win10app, but work in Firefox

### ISSUE THREAD

**Issue by kristianpedersen** [Microsoft/pxt-microbit#1590]
On both Chrome and in the Windows 10 app, the LED functions aren't working on my machine.
They do however work as expected in Firefox.

The code below should display a heart, but nothing happens - not in the preview, and not on the microbit itself, but it works fine in Firefox.

basic.showIcon(IconNames.Heart)

**Comment by abchatra** [comment]
Please share the script and use the bug template to file the bug. We can't repro this issue.

**Comment by abchatra** [comment]
Can't repro

**Comment by kristianpedersen** [comment]
I figured out what was wrong. The LEDs don't work when I have loaded the "mearm" extension.
