### ISSUE TITLE
WebUSB enabled by default in Chrome

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1591]
Web USB is enabled in Chrome v70 in the editor , but it's still a feature we are testing in Beta.
![screenshot 2018-11-05 at 12 27 45](https://user-images.githubusercontent.com/31242877/47998235-7ab41900-e0f6-11e8-93e3-30d2bfa62595.png)

It's my understanding that we aren't  launching webUSB at this stage, so this should be removed.

^^ @halspeed @jaustin

**Comment by halspeed** [comment]
Nice catch @microbit-mark. This feels like it should be under "experiments" at the moment. I'd like to see us put some thought into automating/simplifying the firmware update.

I'd also like to see a status indicator in MakeCode that the micro:bit is successfully paired, as well as, a way to disconnect/unpair.

**Comment by abchatra** [comment]
This is as per discussion with @jaustin. Feature is hidden enough and there are clear enough instructions on how to upgrade.

**Comment by abchatra** [comment]
All other issues are tracked here: https://github.com/Microsoft/pxt-microbit/issues?utf8=%E2%9C%93&q=is:issue+is:open+label:webusb

**Comment by jaustin** [comment]
My bad, I got confused and tested in Firefox on desktop this morning not Chrome (! pre-coffee error !) and thought we had a thing with it on mobile not elsewhere. Agree that it's fine for it to be there without a flag but I think we're all agreed that it needs new Ux before it is no longer in beta... The things Hal suggests are good. Sorry for the confusion I caused here.

**Comment by pelikhan** [comment]
Still confused. So it stays in the menu right?

**Comment by halspeed** [comment]
It sounds like there's some confusion about Web USB being a shipping feature. I was not aware of that being the case. And we haven't included it in any of the comms about v1.

No offense @abchatra, but the instructions are clear for you and me. I'm not convinced they are clear for an elementary school teacher. At a bare minimum, a teacher only needs to download the .hex file, not the whole .zip file. Ideally, it would be a single "update" button.

**Comment by abchatra** [comment]
Browsers don't have access to hardware and can't update the hardware with the update button. (That is way WebUSB is such a game changer).

I agree, we should improve the instructions.

These docs can be updated live. Feel free to give pull request here; 
https://makecode.microbit.org/device/usb/webusb/troubleshoot
There is an edit button at the bottom.

**Comment by pelikhan** [comment]
I see that there is a new firmware guide https://microbit.org/guide/firmware/ . Is that what we should point to?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by halspeed** [comment]
FYI, they are also different versions 0249 vs 0250

**Comment by microbit-mark** [comment]
@abchatra https://microbit.org/guide/firmware/ is the right one to point to. We're pending a release that will update the firmware on that page to 250. This page should now be the source of truth for micro:bit firmware.

Since this is available to all users, can you assign an action to update your docs:

Specifically these statements need clarifying and offering better examples/gifs/vids of what users should expect from webUSB: eg.

**One-click Download**
Once your micro:bit is paired, MakeCode will use WebUSB to transfer the code without having to drag and drop. Happy coding!

and

**Console output**
MakeCode will be able to “listen” to your micro:bit and display the console output.

I'll be updating our KB, but having those examples will answer core questions about webUSB functionality before users hit support.microbit.org

**Comment by microbit-mark** [comment]
re-opening to 
1) update docs on web-usb
2) point ot firmware page

**Comment by abchatra** [comment]
Open a new issue.

**Comment by pelikhan** [comment]
We've updated the docs to point to the same .hex file and pointing to the guide page.
![image](https://user-images.githubusercontent.com/4175913/48153721-c643ff80-e27b-11e8-9f0b-ab6b545e241f.png)
