### ISSUE TITLE
Variable block allows keyboard symbols such as comparison operators

### ISSUE THREAD

**Issue by eric-camplin** [microsoft/pxt-microbit#1592]
Variable syntax not enforced in blocks - can have a variable name such as "x = 1"

New to coding teacher was following the left to build code on right and it was without error

![image](https://user-images.githubusercontent.com/12022944/48026523-2a8b8580-e0fb-11e8-9297-01a0db4922d2.png)

Note: in JavaScript view the "x=1" is "x1"

Expected: should have error for variable syntax with symbols such as @#$%^&*+=

Windows 10 Chrome

**Comment by samelhusseini** [comment]
Saw this on Twitter, thanks @eric-camplin for filing! We'll take a look.

**Comment by pelikhan** [comment]
Still repro.
![image](https://user-images.githubusercontent.com/4175913/58895167-35fe5980-86a8-11e9-81ed-bbcf21276408.png)

**Comment by abchatra** [comment]
Won;t fix
