### ISSUE TITLE
Can't type in text box on Android Chrome

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1594]
**Describe the bug**
When attempting to enter text into a show srting block on Android the on screen keyboard appears and dissapears before you are able to enter the text

**To Reproduce**
1. Go to 'makecode.microbit.org' in Chrome on Android
2. Create a show string block
3. Tap in the box to try and alter the text

**Expected behavior**
User should be able to edit the text

**Screenshots**
![screen recording 2018-11-06 at 08 22 am](https://user-images.githubusercontent.com/31242877/48051657-a4744b00-e19d-11e8-834a-1c8229c2574a.gif)

**Desktop (please complete the following information):**
 - OS: Android
- Browser: Chrome 70
-Keyboard: Swiftkey and GBoard

**Comment by abchatra** [comment]
This is fixed in /beta
