### ISSUE TITLE
Text on blocks not aligned

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-microbit#1596]
In the Windows app/Edge on an older Surface device, the text is bleeding off the left edge of the blocks.  Specifically in the Input and Radio blocks.
<img width="362" alt="input" src="https://user-images.githubusercontent.com/22108954/48077987-71ca5280-e19d-11e8-876e-3402a788f478.png">
<img width="447" alt="radio1" src="https://user-images.githubusercontent.com/22108954/48077994-74c54300-e19d-11e8-8038-f6c76de19f3b.png">
<img width="432" alt="radio2" src="https://user-images.githubusercontent.com/22108954/48077998-77279d00-e19d-11e8-9b01-f1d9efd17778.png">

**Comment by abchatra** [comment]
Looks to be fixed. If not let me know.
