### ISSUE TITLE
firefox browser issues - deleting blocks

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#16]
firefox browser issues - deleting blocks

repro go to this version of firefox
![firefox version](https://cloud.githubusercontent.com/assets/11206682/14156368/eb6b3610-f67a-11e5-8142-2ca7914303ec.JPG)

1. open ksf, blocks. 

2 add these blocks

![blocks not deleting](https://cloud.githubusercontent.com/assets/11206682/14156373/f0b41d62-f67a-11e5-95ae-afebb48c03e9.jpg)

3 expect to be able to delete these blocks, they are stuck in the drawers

**Comment by pelikhan** [comment]
no repro.
