### ISSUE TITLE
Neopixel clear block doesn't work as expected

### ISSUE THREAD

**Issue by Lorrainbow** [Microsoft/pxt-microbit#160]
In micro python when coding with neopixels you use
np.clear()
to clear all the lights

In pxt there is a block
np.clear

but it doesn't work. You have to do np.clear then np.show for it to work. 
Besides it being inconsistent with the micro python code it's not obvious that you have to clear then show to clear the lights

**Comment by darrenge** [comment]
I agree .. you shouldn't have to show after doing the clear.

**Comment by abchatra** [comment]
@pelikhan Do we want to add this behavior?  In PXT, you need to call ``show`` to make the changes visible.

**Comment by pelikhan** [comment]
Yes that is the way neopixels work. We should have a few simpler blocks for common usage.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
fixed by pull request https://github.com/Microsoft/pxt-neopixel/pull/6
