### ISSUE TITLE
v0 programs not upgrading/compiling correctly

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1601]
support ticket: 18458

**Describe the bug**
Larger projects that have been created in v0 will compile in the v1 editor but do not run on the micro:bit.

**To Reproduce**
1. Flash [microbit-acceleration-working(2).hex.zip](https://github.com/Microsoft/pxt-microbit/files/2561296/microbit-acceleration-working.2.hex.zip) to micro:bit, see program working
2. Open above file in makecode.microbit.org
3. Click on Download
4. Flash file to microbit
5. See issue (program does not run)

**Expected behavior**
Any program created in v0 should work as expected in v1 and on micro:bit

**Additional Info**
It is a large program. We also see this issue exhibited using this file https://faraday-secondary.theiet.org/media/2899/microbit-acceleration-test-new.hex
In this case a firmware upgrade from 0243 to 0250 fixes the issue. Any idea why that might be? @abchatra?

**Comment by abchatra** [comment]
There are arithmetic division in the hex file and they won't be upgraded to Math.idiv automatically. (They do when there is a blocks file). But these don't have a blocks file. Can you ask the user to upgrade divisions to Math.idiv if they need to be integer division and report back?

**Comment by abchatra** [comment]
Closing as no additional information is given.
