### ISSUE TITLE
The simulator loads blanks on the "Micro:Coin"

### ISSUE THREAD

**Issue by AimeeCao18** [microsoft/pxt-microbit#1608]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta#
2. Scroll down the scroll bar to "Radio Games"-> Click "Micro:Coin"-> Click "Show Instructions"
3. Click the button "Triangle" at the bottom right corner

**Expected result:**
The simulator works normally

**Actual result:**
The simulator loads blanks on the "Micro:Coin"
![actual](https://user-images.githubusercontent.com/44188776/48241757-2e791980-e413-11e8-85a5-9c864748d68d.gif)

**Comment by ganicke** [comment]
Embedded sim doesn't work if an extension is needed. In this case it's: https://github.com/microsoft/pxt-radio-blockchain

**Comment by ganicke** [comment]
Need labels like ``docs-render`` and ``docs-content``

**Comment by pelikhan** [comment]
Clsoed as fixed.
