### ISSUE TITLE
Old Scripts

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-microbit#1612]
I tried importing the following old scripts, and they didn't import correctly into Blocks:

[microbit-Calculator.hex.txt](https://github.com/Microsoft/pxt-microbit/files/2567533/microbit-Calculator.hex.txt)

[microbit-flashing-heart.hex.txt](https://github.com/Microsoft/pxt-microbit/files/2567537/microbit-flashing-heart.hex.txt)

**Comment by abchatra** [comment]
These files are shared when in typescript editor and they will be in typescript when opened.
