### ISSUE TITLE
Firmware failing to start?

### ISSUE THREAD

**Issue by smartyw** [Microsoft/pxt-microbit#1623]
**Problem**

1. See the code here: https://www.bittysoftware.com/temp/touchpad_control.js

2. Build and install that project that and you'll see a message scroll across the screen on start-up.

3. Uncomment the last line:

// control.onEvent(TOUCHPAD_CONTROL, 0, touchpadControl)

Build again and reinstall and you'll find that the start message does not appear and there's no Bluetooth advertising, suggesting the code has not started at all or crashed somewhere.

**Expected behavior**

With the stated line uncommented, the device should still start up with the same message scroll across the screen and Bluetooth advertising started.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 70

**Smartphone (please complete the following information):**
 - N/A

**Additional context**

**Comment by smartyw** [comment]
Correction. I'm converting some C/C++ that I know worked fine the last time I built it. Just read that DAL issue though and now understand that the latest DAL release may have reduced the RAM available for Bluetooth. I'll test that code built against the new DAL and check whether or not it still works.

**Comment by pelikhan** [comment]
Right, make sure you're trying it on the same DAL release.
