### ISSUE TITLE
readme directs to clone non-existent branch

### ISSUE THREAD

**Issue by johnstonmatt** [Microsoft/pxt-microbit#1625]
readme says: "git clone https://github.com/microsoft/pxt-microbit --branch v1" which does not exist
![screen shot 2018-11-12 at 5 34 52 pm](https://user-images.githubusercontent.com/5455542/48376461-5f6e7e00-e6a1-11e8-8018-f51c2943c2bc.png)

**Comment by abchatra** [comment]
Fixed
