### ISSUE TITLE
showString has different scheduling behavior in the v1 simulator and on the micro:bit

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [Microsoft/pxt-microbit#1628]
Support ticket: 18483

**Describe the bug**
showString has different scheduling behaviour in the v1 simulator and on the micro:bit.

**To Reproduce**

Use [this shared project](https://makecode.microbit.org/22389-36507-73288-52476) or the JavaScript below:

```javascript
input.onButtonPressed(Button.A, function () {
    basic.showString("A")
    basic.showString("B")
})
basic.forever(function () {
    basic.showNumber(1)
    basic.pause(1000)
    basic.showNumber(2)
    basic.pause(1000)
})
```

1. Click A in the simulator after "1" is displayed. Get sequence 1, A, 2, B, 1, 2 ...
2. Download the hex file and copy to a micro:bit
3. Push A on the device after "1" is displayed. Get sequence 1, A, B, 2, 1, 2 ...

In the simulator, control seems to be handed back to the scheduler between the button event handler subprogram steps showing A and B (as if there was a pause block between steps). On the device the subprogram completes without relinquishing control.

This caused confusion to a user trying to understand the event handling model.

**Expected behavior**
The device behaviour seems to match my understanding of [the documentation](https://makecode.microbit.org/device/reactive).

**Desktop (please complete the following information):**

macOS Chrome Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by abchatra** [comment]
Increase the pause to 5sec you will see the exact behavior in simulator as well. One sec is too small to account for all the fiber timing issues. Note desktop is not a exact emulation of hardware. Desktop is a simulation. 

No repro.
