### ISSUE TITLE
New Music Block: Stop Melody

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1629]
**Is your feature request related to a problem? Please describe.**
It is an often requested feature to be able to stop a melody in code. Eg within a forever loop. This example https://github.com/Microsoft/pxt-microbit/issues/1567 creates a program that 
plays a melody  in a loop but nothing is heard. Same with #1306 

**Describe the solution you'd like**
A block to stop melody, with a dropdown to choose whether this is forever/in background etc

**Describe alternatives you've considered**
The current workaround is to pass an empty array to stop the melody https://support.microbit.org/a/solutions/articles/19000082590 but this isn't intuitive for users.

**Additional context**

**Comment by pelikhan** [comment]
Fixed in /beta
![image](https://user-images.githubusercontent.com/4175913/54768044-9c043600-4bbb-11e9-95bd-8922c3564ffc.png)
