### ISSUE TITLE
Radio and Bluetooth packages must be mutually exclusive in a project

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#163]
The Radio and Bluetooth packages cannot both be included in the same project. If this is done (perhaps accidentally) then the Bluetooth stack will not come up and no advertising will take place.

The Radio package is included by default but Bluetooth is not.

Suggest the editor ensures users cannot include both of these mutually exclusive packages by automatically removing Radio whenever the Bluetooth package is added (with user notification).

**Comment by mmoskal** [comment]
This is fixed now, see a few commits here https://github.com/Microsoft/pxt/commits/1df3500dd2668d675465e0928e476470f6940f53

**Comment by bluetooth-mdw** [comment]
Thanks :-)

Is this live yet or not? Just tried it and I was able to have both Bluetooth and Radio packages in the same project.

**Comment by mmoskal** [comment]
Not live yet..






On Mon, Jul 11, 2016 at 8:28 PM +0200, "Martin Woolley" <notifications@github.com> wrote:












Thanks :-)



Is this live yet or not? Just tried it and I was able to have both Bluetooth and Radio packages in the same project.

**Comment by mmoskal** [comment]
It's live at https://codethemicrobit.com/beta but not yet on the main site
