### ISSUE TITLE
Issue with DAPLink 0234 and v1 hex file writing to RAM 

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#1631]
**Describe the bug**
MakeCode v1 writes the Source Embedding in RAM (starting at address 0x2000_0000), and this is causing some issues with micro:bits running DAPLink 0234 (the school drop).

We had a couple of reports from users saying that hex files that used to work in v0 no longer worked when imported to v1. We traced this down to an issue in DAPLink 0234, when writing data to RAM above a certain threshold.

On the example listed in the "steps to reproduce" section, if we modify the v1 hex file to only write until RAM address 0x2000_0C00 it works fine, but if any more data is left in the hex it causes the issue.

When the issue happens, the data that would go between addresses 0x2000_0C00 and 0x2000_1C00 end up written to flash after a full erase has been performed (removing all the user program).

Zip file includes the following hex files:
- example in v0 (working)
- example updated to v1 (not working)
- the read back from nRF51 flash when it doesn't work
- a manually edited version of the v1 hex that only writes up to 0x2000_0C00 (works)

[daplink-issue-mk-v1-hex-files.zip](https://github.com/Microsoft/pxt-microbit/files/2577494/daplink-issue-mk-v1-hex-files.zip)

We had another example from a user with a large v0 program that showed the same behaviour when converted to v1. However, in this case the RAM threshold was at address 0x2000_1050 instead.

**To Reproduce**
* Download DAPLink firmware 0234: https://mbed-media.mbed.com/cms_page_media/3291/0234_microbit_if.hex
* Flash 0234 to the micro:bit in MAINTENANCE mode
* Download https://faraday-secondary.theiet.org/media/2899/microbit-acceleration-test-new.hex
* You can flash it to the micro:bit verify it works
    - It should light up the display
* Open hex into makecode.microbit.org (v1)
* Download and flash to micro:bit running DAPLink v0234
    - Doesn't light up the display

**Expected behavior**
nRF51 to be flashed correctly.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
N/A.

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A.

**Comment by pelikhan** [comment]
@mmoskal

**Comment by mmoskal** [comment]
I thought daplink would stop interpreting hex file at "EOF" marker (01 record or something). I guess it doesn't. We can use any address for the embedded source, so we can just move it to 0x8000_0000 or something I guess.

**Comment by abchatra** [comment]
Is this specific to 0234?

**Comment by microbit-carlos** [comment]
We tested with 0234 and 0241+, and the problem presents itself only in 0234.
So something has changed or been fixed between those releases.

I can't say if 0241+ stops at the end of file marker, but at least it doesn't erase flash and write to it again.

I guess a simple test would be to add a malformed hex line after the EOF marker and see if DAPLink throws a fail.txt.

**Comment by DavidWhaleMEF** [comment]
I checked the DAPLink src for 0234. 

It's not completely conclusive, but...

When it sees the intel hex file 01 record (EOF_RECORD) it raises an event flag to request an MSC_DISCONNECT event from the USB stack. But this is an asynchronous flag and won't be processed immediately. I haven't unpicked the priority order of tasks to see when that event flag would eventually get processed.

But it looks like the host will continue to send hex data until it gets a 'usb surprise removal' instigated from the MSC_DISCONNECT (which happens possibly much later after the EOF record was processed). 

It is then feasible to assume that *any* data that follows the EOF record is then mis-interpreted as a new hex file, which will then cause the incoming intel hex parser to continue to feed data through to the flash programer code. As the EOF state was detected, this will no longer be detected as a non-contiguous memory address, but a NEW hex file at a new address, and if the normal logic of the loader executes, the first thing that does is to erase the target chip flash.

**Comment by carlosperate** [comment]
Great findings, thanks David.
Do you know if the newer versions of DAPLink make the MSC_DISCONNECT synchronous?

**Comment by DavidWhaleMEF** [comment]
I've not looked in any detail at the later code,there is quite a lot of it!

Another thought I had is I have vague memory that due to the host/function (master/slave) architecture of USB, a device initiated MSC_DISCONNECT may take a bit of time to propagate to the host, be detected and actioned by the host operating system. Thus the longer the hex file, this might indicate increased probability that post-EOF hex data is received and processed by the still active and already re-primed hex parser (and because the flag has been cleared by the goto msc_disconnect line) interpreted as a new hex file and triggering DAPLink to initiate a new device erase command on the target processor.

This is all hunches that would need further investigation. I was trying to find a readable functional change log between the two firmware versions to see if there was any mention of hardening the MSC_DISCONNECT logic.

Note that MSC_DISCONNECT might not actually be the same as USB disconnect in this case, I have another hunch that the USB stack is still running when this happens so the host doesn't see it as a surprise removal (which would more likely respond more quickly at the host end), but it would wait for the host file transfer operation to detect the driver disconnect message.

It might be instructive to run the same tests on a number of different OSes as they may handle MSC_DISCONNECT differently at the host end and cause different behaviours.

**Comment by jaustin** [comment]
@mmoskal it would be good to progress this as there are a lot of 0234 micro:bits out there and in use. There are some specific and popular resources that suffer this issue, and the user experience is just 'it doesn't work'. unexpectedly.

**Comment by microbit-mark** [comment]
> micro:bit support 24311

We have further reports of this issue in the wild from our partners who are working with a large amount c 100000  micro:bits that are expected to be DAPLink 0234.

**Comment by microbit-carlos** [comment]
Based on some tests and source code analysis of DAPLink we believe that the reason the MakeCode Source Embedding erases flash and writes the RAM contents into flash is because the EoF record in 0234 stops the processing of the current data block (usually 512-bytes, or a multiple of that), but doesn't stop processing any subsequent blocks.

So basically, at the end of flash data we ha something like:

```
...
:10F860000000000000000000000000000000000098
:04F870000000000094
:10FC00000100000000000000FE00000000000000F5
:10FC100000000000000000000000000000000000E4
:020000041000EA
:0410140000C0030015
:040000050003C0C173
:00000001FF

:020000042000DA
:1000000041140E2FB82FA2BBA6006F1C00000000E9
:100010007B22636F6D7072657373696F6E223A2213
:100020004C5A4D41222C2268656164657253697A8D
:1000300065223A3330332C227465787453697A65BB
:10004000223A3136323538312C226E616D65223AD2
...
```

That EoF record caused the rest of its 512-byte block to be dropped, which included the Extended Linear Address record for address `0x2000_0000`.
So the next data block just started with a normal data record, and DAPLink treated it as such.

A quick test with the original issue hex file shows that it works if we add padding (new lines was the quickest padding I came up with) to align the Source Embedding Extended Linear Address record to a new 512-byte block.

And reading the flash back show no corruption: [mk-v1-fixed-files.zip](https://github.com/microsoft/pxt-microbit/files/3911942/mk-v1-fixed-files.zip)

**Comment by microbit-mark** [comment]
Nudging this issue again as we've had reports of classroom use being affected for teachers and students.

This example has 3 MakeCode hex files attached that include the @KitronikLtd Halo HD extension. Test with a micro:bit running DAPLink 0234 and 0253:

[halo-example.zip](https://github.com/microsoft/pxt-microbit/files/4128343/halo-example.zip)
1. Geography Example Code DISPLAY SHAKE CONTROL.hex works on DAPLink 0253 but not on 0234

2. Geography Example Code DISPLAY SHAKE CONTROL-fixed.hex is the same file as 1., but I have removed the lines removed after the EoF on line 14351. This works on 0253 and 0234

3. Geography Example Code DISPLAY SHAKE CONTROL-noRadioSend.hex is the same as 1., but has the radio send block removed from on button press A+B

I think this is the same issue, but it is more significant if it affects day to day use of the micro:bit and peripherals. @mmoskal @pelikhan @abchatra

**Comment by DaveAtKitronik** [comment]
We will currently cover this in shipping products by adding an addendum that recommends updating the micro:bit firmware. This will prevent the symptoms, but will only help the first users of a product - the addendum will most likely get lost, or if a product is passed over without updated micro:bit the problem will reoccur. It also breaks the micro:bit philosophy of 'Just Works'  
If there is a fix it would be good to push it urgently

**Comment by microbit-mark** [comment]
I have tested the reproducer from https://github.com/Microsoft/pxt-microbit/issues/1631#issue-380361406 and https://github.com/Microsoft/pxt-microbit/issues/1631#issuecomment-579767280 and can confirm both appear to function as normal. Can you test with the hardware @DaveAtKitronik to make sure this fucntions as expected?

**Comment by DaveAtKitronik** [comment]
Can I just use the online makecode, or do I need to do something else?

**Comment by DaveAtKitronik** [comment]
Never mind, just saw the other email...
Will test with Halo HD

**Comment by DaveAtKitronik** [comment]
Works as expected with /beta editor V2.1.46, still fails (as expected) with normal editor 2.0.10

**Comment by pelikhan** [comment]
The fix is only in beta during test phase.

**Comment by DaveAtKitronik** [comment]
I expected as much, but I wanted to verify my test setup...

**Comment by martinwork** [comment]
On all platforms I tried, a file saved with beta will not load into live: "Sorry, we could not recognise this file".

Brief tests with the iOS micro:bit app and the new format HEX seem OK for transfer between app and hosted MakeCode, DFU and partial flashing.

Testing MakeCode in Safari on iPad, files were not routed to the iOS app, but saved in a Downloads folder in my iCloud drive. They seem to be typed as TXT, so they won't load back into MakeCode. Download opens a dialogue about connecting with a USB cable.

**Comment by mmoskal** [comment]
The files from beta are not supposed to load in current live. 

Not sure what's up with iOS but I doubt it has anything to do with this change.

**Comment by abchatra** [comment]
We only guarantee backward compat. Older hex files will work in newer editors (vice versa may not be true).

**Comment by martinwork** [comment]
Should it trigger a message about the file having been created with a newer version of MakeCode or is that only for major versions, V1, V2 etc?

Is there anything else out there, like the mobile apps, that could be broken by this change?

**Comment by microbit-mark** [comment]
@abchatra when will this make it into the live editor?

**Comment by abchatra** [comment]
Fix is scheduled to go tomorrow. 
@microbit-mark & others can you please test https://makecode.microbit.org/stable and make sure it address the issue outlined here?

**Comment by microbit-mark** [comment]
I have tested the reproducers again and can confirm both appear to function as normal. Can you test with the hardware in https://makecode.microbit.org/stable  @DaveAtKitronik?

**Comment by DaveAtKitronik** [comment]
Tried to earlier, but the editor at  https://makecode.microbit.org/stable wouldn't load for me. I'm working remote today, so will try again later

**Comment by DaveAtKitronik** [comment]
Tested with Halo HD - Edge browser. /stable works as expected, without /stable fails as expected. Looks like the fix is OK
