### ISSUE TITLE
Sending serial number via radio converts it to a float

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1640]
support ticket: 18385

**Describe the bug**
When sending a serial number via radio, if the serial number is a positive integer, the output adds additional decimal places.

serial is 0x791b328b  (2031825547 in decimal) is received as 2031825546.9999999
serial is 0x761b118b  (1981485451 in decimal) is received as 1981481450.999999
serial is -0x7292b83e (1922218046 in decimal) is recieved as 1922218046

**To Reproduce**
1. Go to 'https://makecode.microbit.org/_HCb2j14b199k '
2. Download to two micro:bits (making sure one has a positive serial number initially)
3. Press A on one
4. See serial number displayed on the other with added decimal places and over serial USB.

**Expected behavior**
Serial number should display as an integer

This is the behaviour in makecode and beta 

makecode.microbit.org version:  1.2.9

Microsoft MakeCode version:  4.6.2

microbit runtime version:  v2.1.0

**Additional info**
Not sure if this is a duplicate of #1535 and the fix you mentioned on the call @pelikhan @abchatra 

cc @microbit-carlos

**Comment by pelikhan** [comment]
This is a different bug.

**Comment by microbit-mark** [comment]
Nudging this one again @pelikhan @abchatra. Serial numbers with added decimal places is confusing.

**Comment by microbit-mark** [comment]
tagged with next-release as discussed @abchatra

**Comment by ChaseMor** [comment]
Looks like the issue comes from printing a number that is larger than 2^30.

**Comment by abchatra** [comment]
We don't support integers larger than 2^30 as it doesn't fit in tagged int strategy and will be converted to float. Floating point values don't have exact precision. This is a limitation in makecode. 

We won't be able to fix from our end.

**Comment by martinwork** [comment]
@microbit-mark Would it be useful to provide access to the 5 character micro:bit friendly name derived from the received serial number?

**Comment by osupk8** [comment]
Can ou give an example ?

**Comment by martinwork** [comment]
For the host micro:bit, control.deviceName is the friendly name (eg. tovip), derived from control.deviceSerialNumber, which corresponds to the A+B+Reset LED pattern used for Bluetooth pairing. I meant the equivalent of deviceName for the received serial number. I'm imagining a "device name" choice on the received packet block dropdown.

**Comment by abchatra** [comment]
Convert to string and send as a string? Even that has 8 character limit, but you can send multiple parts of as the string.

**Comment by pelikhan** [comment]
The serial number is encoded properly but the tostring might not handle it.

**Comment by martinwork** [comment]
Could a function like microbit_friendly_name()
https://github.com/lancaster-university/microbit-dal/blob/master/source/core/MicroBitDevice.cpp#L94
added to the C++ code could turn receivedSerial() into a String?

`radio.receivedPacket(RadioPacketProperty.SerialNumber)` and `control.deviceSerialNumber()`
are negative for my microbits. Is this a problem with javascript and unsigned 32bit integers?

writePacketAsJSON sends a negative number. The parameter is a signed int.

**Comment by martinwork** [comment]
https://makecode.microbit.org/_ichFL9KTR1ph

calcRadioSerial turns negative serial numbers into correct positive ones
calcRadioSerialText makes a text version of the serial number
calcRadioDeviceName derives the "tovip" type deviceName from the serial number

**Comment by martinwork** [comment]
@microbit-mark @osupk8 

https://makecode.microbit.org/_6bRUe30P9gtF

The  function "makeSerialString" uses a more compact trick to get the positive serial number and a string without decimal places. This could be one line like the last line of "on radio received" uses to dump the received value 4294967295 (0xFFFFFFFF).

**Comment by microbit-mark** [comment]
These are great workarounds, thanks @martinwork. I'll reference them in a support article if that's okay, so people who come up against this issue have a way to fix.

**Comment by martinwork** [comment]
The second example doesn't load into MakeCode for me at the moment. I suspect it's because I used beta

Here's a new version without function parameters.
https://makecode.microbit.org/_Rz5PfgcwWChR
