### ISSUE TITLE
Sprite brightness update create temporary and erratic screen artifacts when graph plot is performed

### ISSUE THREAD

**Issue by f-steff** [Microsoft/pxt-microbit#1645]
**Describe the bug**
Updating the brightness of sprites in functions where Graph Plot is enabled, produces temporary and erratic screen artifacts.
The behaviour is identical on both hardware and in the simulator.

**To Reproduce**
See the example code here: https://makecode.microbit.org/_R744U3hM2aX3
Read usage description in the blocks.

**Expected behavior**
No temporary and erratic screen artifacts when graph plot is performed.

**Screenshots**
See the example code here: https://makecode.microbit.org/_R744U3hM2aX3
Read usage description in the blocks.

**Desktop (please complete the following information):**
Not relevant.

**Smartphone (please complete the following information):**
Not relevant.

**Additional context**
 Tested on firmware 0234 and 0250.

**Comment by abchatra** [comment]
@pelikhan

**Comment by abchatra** [comment]
@f-steff Can you explain what you mean by  _temporary and erratic screen artifacts_? 
Plot graph takes over the screen and then the game engine takes over.

**Comment by pelikhan** [comment]
This is by design. The game engine rendering mixes with plotbargraph. In general, those cannot mix together.

**Comment by f-steff** [comment]
Apologizes where needed. I was under the impression the Plot Graph were for debugging in the GUI only. Sorry.
