### ISSUE TITLE
Both Ok and Finish buttons show up on last step of some tutorials

### ISSUE THREAD

**Issue by samelhusseini** [microsoft/pxt-microbit#1649]
**Describe the bug**
Both the ok and finish buttons appear on the last step of some tutorials (eg: dice).

**To Reproduce**
1. Go to Dice tutorial
2. Click on the last step or navigate through
3. See how both the ok button and the finish buttons show up when the lightbox appears

**Expected behavior**
For the finish button to not appear while we're in the lightbox. 

**Screenshots**
<img width="1172" alt="screen shot 2018-11-18 at 12 04 54 am" src="https://user-images.githubusercontent.com/16690124/48670060-c509a280-eac5-11e8-8906-c745dba040ba.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Safari

**Additional context**
Repro's on all browsers

**Comment by abchatra** [comment]
Fixed
