### ISSUE TITLE
Function serial.writeNumber() shows the wrong number on JavaScript pane

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1653]
**Describe the bug**
Function serial.writeNumber() shows the wrong number on JavaScript pane 

**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "{ }JavaScript" to switch to JavaScript pane
3. Copy below code on JavaScript pane and click "Show console Simulator" and observe 

**Expected result:**
**Code1:**
basic.forever(function () {
    serial.writeNumbers([1])
    basic.pause(1000)
})

![issuecompare](https://user-images.githubusercontent.com/23466737/48760858-2dcd6680-ece2-11e8-8db5-ba5ad2c6d4ac.PNG)

**Actual result:**
**Code2:**
basic.forever(function () {
    serial.writeNumber(1)
    basic.pause(1000)
})
Function serial.writeNumber() shows the wrong number on JavaScript pane 
![issue112001](https://user-images.githubusercontent.com/23466737/48760866-3160ed80-ece2-11e8-91ad-b131aa3d713a.PNG)

**Comment by pelikhan** [comment]
writeNumber does not introduce a space or a new line, eventually the line gets flushed with the 111111 value. This is by design.

**Comment by abchatra** [comment]
You need to use writeLine after writeNumber to get the results you expect. This is by design. WriteNumbers introduces a new line.
