### ISSUE TITLE
There doesn't have a parameter for user to add number for block "serial write numbers"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1654]
**Describe the bug**
There doesn't have a parameter for user to add number for block "serial write numbers"

**Steps to reproduce the behavior:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "Advanced" -> "Serial" -> Drag block "serial write numbers" 
3. Put it under block "forever" and observe

**Expected behavior**
Expected result1: There should have a parameter for user to add number
Expected result2: Error message should be clear enough
![capture](https://user-images.githubusercontent.com/23466737/48764239-12665980-ecea-11e8-98b2-1b61113e391b.PNG)

**Actual behavior**
Issue1: There doesn't have a parameter for user to add number
Issue2: Error message is not clear
![issue112002](https://user-images.githubusercontent.com/23466737/48764334-5c4f3f80-ecea-11e8-9034-6b14b09abf4b.gif)

**Desktop(please complete the following information):**

-  OS: Windows

-  Browser: repro's on all browsers

**Comment by pelikhan** [comment]
We do have a good default block to populate the shadow of an array parameter.
