### ISSUE TITLE
Local install for developers

### ISSUE THREAD

**Issue by CleoQc** [Microsoft/pxt-microbit#1655]
Are the steps in the [readme ](https://github.com/Microsoft/pxt-microbit/blob/master/README.md)still valid? 
I followed them to the letter and it didn't work for me.

I am trying to update my local dev environment so it's aligned with V1 instead of V0.  I know there's a github integration but I would rather develop and test locally. 

Errors I am getting when I run `pxt serve --cloud`:
error TS6053: File 'C:/Users/cleoq/Documents/local_makecode/pxt/built/lib.dom.d.ts' not found.
error TS6053: File 'C:/Users/cleoq/Documents/local_makecode/pxt/built/lib.dom.iterable.d.ts' not found.
error TS6053: File 'C:/Users/cleoq/Documents/local_makecode/pxt/built/lib.es2015.d.ts' not found.
error TS6053: File 'C:/Users/cleoq/Documents/local_makecode/pxt/built/lib.scripthost.d.ts' not found.
error TS2318: Cannot find global type 'Array'.
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
error TS2318: Cannot find global type 'String'.

**Comment by abchatra** [comment]
This is a known issue and doesn't impact the build.
