### ISSUE TITLE
Have makecode issue a warning to user when prepared hex file is likely too large for microbit

### ISSUE THREAD

**Issue by nbogie** [microsoft/pxt-microbit#1656]
Without much feedback, users may well spend a lot of time head-scratching when their program size hits the invisible wall.  They copy the hex to the microbit, it seems to go fine, but they see nothing running.

It'd be great if makecode could issue a warning when the prepared hex file is too large for the microbit.

I understand that a fail.txt gets written to the microbit directory when the copy fails.  That's great, but many users are unaware of that, and are not periodically looking in that directory.  Something directly from makecode would be much more likely to be noticed, and would also then speed the dev cycle as users tried different things to reduce their program size.

**Comment by DavidWhaleMEF** [comment]
+1 from me... The existing Python web (python.microbit.org) and Mu editors do this already based on size of generated hex image, so it must be possible, as we know in advance the highest supported lash memory address on the device. 

It would be good for the experience to be consistent across all editors.

**Comment by pelikhan** [comment]
@mmoskal i see that we assert https://github.com/Microsoft/pxt/blob/28e192df12889f36015c8ed7c80c146d0b2cd0bd/pxtcompiler/emitter/hexfile.ts#L501. do we have checks on the total size of the hex file?

**Comment by abchatra** [comment]
No plans to implement.
