### ISSUE TITLE
There is no individual block "create an array" in "Arrays" tool box

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1657]
**Describe the bug**
There is no individual block "create an array" in "Arrays" tool box

**Steps to reproduce the behavior:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "Advanced" -> "Arrays" -> scroll down the scroll bar to browse

**Expected behavior**
There should have an individual block "create an array" in "Arrays" tool box 
![issue112202](https://user-images.githubusercontent.com/23466737/48887363-f984b200-ee69-11e8-9b4e-492508216f8c.gif)

**Actual behavior**
There is no individual block "create an array" in "Arrays" tool box
![issue112202issue](https://user-images.githubusercontent.com/23466737/48887359-f8538500-ee69-11e8-995d-5218e989f31a.gif)

**Desktop (please complete the following information):**

-  OS: Windows & Mac

-  Browser: repro's on all browsers

**Comment by abchatra** [comment]
Added empty array block as here:
https://github.com/Microsoft/pxt/pull/5039

**Comment by abchatra** [comment]
Yes Microbit will be updated in the next release.
