### ISSUE TITLE
Tutorial "Coin Flipper" 2-6 steps' hints don't show automatically

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1658]
**Describe the bug**
There is no individual block "create an array" in "Arrays" tool box

**Steps to reproduce the behavior:**
1. Navigate to https://makecode.microbit.org/beta
2. Scroll down to "Games" -> open tutorial "Coin Flipper" steps one by one

**Expected behavior**
Each step should show hint automatically
![issue112201compare](https://user-images.githubusercontent.com/23466737/48888419-9e54be80-ee6d-11e8-92aa-b63e0c5843b3.gif)

**Actual behavior**
Tutorial "Coin Flipper" 2-6 steps' hints don't show automatically
![issue112201](https://user-images.githubusercontent.com/23466737/48888399-8da44880-ee6d-11e8-8f08-7a0c37653fae.gif)

**Desktop (please complete the following information)**
-  OS: Windows & Mac
-  Browser: repro's on all browsers

**Comment by abchatra** [comment]
@ganicke can you take a look it and add hint by default if need be?

**Comment by ganicke** [comment]
We could add ``@fullscreen`` to the sections but this starts to remove any challenge for learning/using the editor. If this was one of the projects in the "tutorial" section for getting started, well maybe then.
