### ISSUE TITLE
web ble-uart experiment: newline confusion 

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#1659]
With the current implementation of the web-bluetooth and UART experiment when working on real hardware it isn't clear what will result in the browser 'registering' a string being sent. 

For example, the following program: https://makecode.microbit.org/_dtf7jMFide7o
<img width="722" alt="image" src="https://user-images.githubusercontent.com/147113/48910882-048b1280-ee69-11e8-9b41-9136071249a9.png">

On the simulator I see 'Hi' whenever I press button A, and that's the expected behavior
On the hardware, when I press 'A' the serial viewer pops up (hooray!) but doesn't contain any contents until I press 'B' which sends the x:0 message and results in the previous instances of 'Hi' being sent:
```
HiHiHiHix:0
```
Not sure whether we should either have an explicit 'new line' on `bluetooth.uartWriteString()` or whether we should be printing in the viewer without the newline being present. I think the latter.

FWIW:
```
bluetooth.uartWriteString("Hi\n")
```
shows up immediately.

**Comment by pelikhan** [comment]
Same problem as in serial - not really related to bluetooth - we commit a string line by line in the console.

Use UART write line instead, or console.log

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jaustin** [comment]
But that's the thing, I don't think there is a bluetooth.uartwriteLine? Certainly not in blocks but neither in JS?

**Comment by pelikhan** [comment]
We should have one... maybe forgot to add it.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pelikhan** [comment]
Note that using console.log uses a new BLE service that has a smaller memory footprint than UART, makecode supports both. Every byte counts here.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jaustin** [comment]
Nice. That's useful to know for the MakeCode scenario but lots of people want UART because it works on other platforms etc.. Think writeline would be good as well..  Is that service always there?

**Comment by pelikhan** [comment]
It’s on demand like UART. But with UART we are more likely to go out of memory.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
