### ISSUE TITLE
JS Code editor right click menu rendered under the bottom tools area

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#1660]
**Describe the bug**
The right click menu from the monaco editor can be rendered underneath the "editor tools" bottom area.

Screenshot shows what I mean.

**To Reproduce**
1. Right click in the monaco editor in an area close to the bottom edge of the viewport, but that still causes produces the menu to be displayed below the mouse.

**Expected behavior**
Right click menu to either render on top of the bottom area of the page, or to be display on the top area from the mouse.

**Screenshots**

![image](https://user-images.githubusercontent.com/29712657/48915725-a580ca00-ee77-11e8-9b64-3b3cc06f826a.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox 63 and Chrome 70

**Smartphone (please complete the following information):**
N/A

**Additional context**
makecode.microbit.org version:  1.2.11
Microsoft MakeCode version:  4.4.7
microbit runtime version:  v2.1.0

**Comment by abchatra** [comment]
This is fixed in latest /beta.
