### ISSUE TITLE
Simulator don't have sound when putting block "play tone" under "forever"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1662]
**Describe the bug**
Simulator don't have sound when putting block "play tone" under "forever"

**Steps to reproduce the behavior:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "Music" in toolbox and drag block "play tone" then put it under block "forever"
![issue1123](https://user-images.githubusercontent.com/23466737/48932829-c8bf7e00-ef38-11e8-8540-ec69c7187ccd.gif)

**Expected behavior(Edge, Chrome & Firefox)**
Simulator should have sound when putting block "play tone" under "forever"

**Actual behavior(IE)**
Simulator don't have sound when putting block "play tone" under "forever"

**Desktop (please complete the following information)**
-  OS: Mac
-  Browser: IE(11.407.17134.0)

**Comment by abchatra** [comment]
There is no sound support in IE. This is a browser limitation. Can't fix
