### ISSUE TITLE
Music only plays on pin 0

### ISSUE THREAD

**Issue by rhubarbdog** [Microsoft/pxt-microbit#1663]
Music blocks have no pin argument so the speaker has to be connected to pin 0 and ground.
Surely not there should be a block to configure Music blocks or an argument to set the pin number on the 'start melody' block and family.
The issue is that music can be played on any PWM capable pin, where as the ADC is connected to pin 0

**Comment by pelikhan** [comment]
You can use https://makecode.microbit.org/reference/pins/analog-set-pitch-pin to change the music pin. Probably should have a more obvious way to do this.

**Comment by abchatra** [comment]
As designed.
