### ISSUE TITLE
For ever show number displays nothing on microbit, when the blocks contain serial and files

### ISSUE THREAD

**Issue by rhubarbdog** [Microsoft/pxt-microbit#1665]
For ever, show number displays nothing when serial and files are accessed in the same program via on button b pressed callback

**To Reproduce**
These  <a href="https://makecode.microbit.org/_RidEcegFvhjb">blocks</a> work on the simulator, but do nothing when flashed to a microbit.  Not only does nothing display, nothing displays or is squirted up the usb cable to serial program `screen`

<a href="https://makecode.microbit.org/_gRkbJ9C1U7cT">These simple blocks</a> work on the same microbit.

**Expected behavior**
when running the first set of blocks I expect the microbit to display a '9'
when button b is clicked it should display a '0' and  interact with serial and the file system

**Desktop (please complete the following information):**
 - OS: Linux Mint 17.04 a direct clone of ubuntu 16.04
 - Browser : Mozilla firefox
- Version 60.0.4

**Additional context**
This program appears to work perfectly well in the simulator pane

**Comment by abchatra** [comment]
File system package is unsupported. It is low quality and I recommend not using it.
