### ISSUE TITLE
Missing Quotation markt in download screenshot

### ISSUE THREAD

**Issue by ChrisDorna** [Microsoft/pxt-microbit#1668]
When I download a screenschot of a block with quotation marks in it, the marks are not vissible

<img width="428" alt="editor" src="https://user-images.githubusercontent.com/20975602/49014016-fa298b00-f17e-11e8-85e1-2a04ae4eb08c.png">

![download](https://user-images.githubusercontent.com/20975602/49014093-35c45500-f17f-11e8-9dd8-f37a9d41d057.png)

I am on Chrome in Windows 10

**Comment by pelikhan** [comment]
@samelhusseini for your screenshot test case... i guess the " are a SVG

**Comment by samelhusseini** [comment]
Yes, all part of the same issue of no <Defs> in the download screen, this should be fixed soon.

**Comment by ChrisDorna** [comment]
Any news about the fix? I still miss the quotations in the downloaded screendumps.
