### ISSUE TITLE
No warning that HEX download won't work on mobile devices

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt-microbit#167]
When you tap compile on an iOS device (I'm yet to test the behaviour on Android), the information about transferring the file to the micro:bit appears, however this isn't applicable on mobile devices where you a) can't download the file in the first place, and b) can't transfer the file directly to a micro:bit.

![image](https://cloud.githubusercontent.com/assets/20356546/16834832/868cd16e-49ad-11e6-85e3-0f7c46384720.png)

**Comment by thomasdenney** [comment]
On an iPhone I found that I was redirected to a `data:application/x-micro it-hex;base64...` page, which then gave me the option to email the file or upload it to Dropbox, etc (this is native Safari behaviour). However, tapping in the address bar then crashed Safari completely (due to the length of the base 64 encoded text file).

**Comment by tinfoilhatter** [comment]
HEX download also fails in Firefox (tested under Ubuntu 16.04). Firefox indicates that it's downloading something, but the dialog does not appear, and no HEX file is saved.

**Comment by thomasdenney** [comment]
@tinfoilhatter I've just tested on the latest Firefox 47 on Ubuntu 16.04 and it downloaded fine.

**Comment by tinfoilhatter** [comment]
@thomasdenney Did you get the dialog? Where did the downloaded file go?

I am running Firefox 47.0, and my download menu reads "No downloads for this session" after clicking **Compile**.

Are you running Firefox with root privileges? I found I had to type ``sudo pxt serve`` to get the Editor to launch properly. If you're not running with root privileges, how does your setup work? Thanks.

**Comment by tinfoilhatter** [comment]
Today, after clearing the browser cache of Firefox, and using the actual https://codethemicrobit.com site (as opposed to my local version of it), I was able to bring up the dialog box under Ubuntu. Not sure what caused the change in behavior, but my first guess would be clearing the browser cache, as alternately running Firefox as root (so I could ``pxt serve``) and as my own user caused a number of problems with other sites until I cleared it.

**Comment by pelikhan** [comment]
Significant work was done around browser downloads. CLosing.
