### ISSUE TITLE
on pin pulsed block does not configure digital pin in the simulator

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [Microsoft/pxt-microbit#1670]
Support ticket: 18750

Run the following code on the micro:bit simulator:

```javascript
pins.onPulsed(DigitalPin.P0, PulseValue.High, function () {
    basic.showIcon(IconNames.Heart)
})
```

The help for the block says: "Configure the specified pin for digital input, and then execute the associated code block whenever the pin pulses High or Low (as specified)."

**Expected behavior**

The user expected P0 to be configured for digital input but this does not happen. Clicking on the pin has no effect. This works as expected on the hardware.

Behavior is the same in v0 and v1.

**Comment by abchatra** [comment]
There is no support for pin pulsed on simulator. @pelikhan

**Comment by microbit-mark** [comment]
Can this be added for the simulator? Or if not, update the [docs ](https://makecode.microbit.org/reference/pins/on-pulsed)to say that this only works on the hardware

**Comment by microbit-mark** [comment]
@abchatra After discussion, docs to be updated as this will not be supported in the sim

**Comment by abchatra** [comment]
@ganicke we need to update the doc

**Comment by ganicke** [comment]
Should probably add a note to all of the pin docs for apis that don't have any sim actions. The I2C pages have this note currently:

![image](https://user-images.githubusercontent.com/27789908/49826093-e6635480-fd3a-11e8-9a51-8d28e6e1b249.png)

**Comment by ganicke** [comment]
Oop: задаване темпо до (bpm)|%стойност --- should be %value

**Comment by abchatra** [comment]
Fixed the docs
