### ISSUE TITLE
Performance unusable on Windows Surface RT tablet but was acceptable on microbit.co.uk

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [Microsoft/pxt-microbit#1672]
Support request: 18691

A code club user who needs to migrate from the microbit.co.uk blocks editor to makecode.microbit.org for the Spring term reports that the MakeCode editor is too slow for children to use on a Windows Surface RT tablet (Windows 8.1 running on a Tegra processor).

They have provided some helpful videos that illustrate the performance difference:

- microbit.org - https://youtu.be/7Wxr9orKcQc
- microbit.co.uk - https://youtu.be/D-QGOsJ-3eY

Both initial project creation and block drag and drop are significantly slower. Drag and drop is hard to use due to the lag, particularly for children.

I doubt that there's much that can be done for this particular user, but felt performance feedback is important to pass on.

**Comment by ed-xmos** [comment]
Hi, the originator of the support request here. Some more info for you:

- Microsoft surface tablet
- Windows RT 8.1 (latest updates applied) 32b. No upgrade path to W10 currently :(
- NVIDIA Tegra(r) 3 QUad core 1.3GHz
- 2.00GB 
- IE11 version 11.0.9600 - No Edge available :(

Let me know if you need anything else.

**Comment by abchatra** [comment]
We don't support winrt anymore.
