### ISSUE TITLE
can't display svg file in my extension

### ISSUE THREAD

**Issue by shaoziyang** [Microsoft/pxt-microbit#1673]
**Describe the bug**
I am try to upgrade my ds1302 extension, and add svg file, but it can't display svg file for the parts, only show a blank.

https://github.com/shaoziyang/makecode_dev

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: chrome, firefox

**Comment by abchatra** [comment]
If this is still relevant please reopen with a short repro.
