### ISSUE TITLE
Error message shows when clicking "cancel" pair device on Chrome

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1674]
**Describe the bug**
Error message shows when clicking "cancel" pair device

**Steps to reproduce the behavior:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "More..." -> "Pair device" -> click "Pair device" -> cancel (one device has been paired)

**Expected behavior**
Message should show "One device has been paired"

**Actual behavior**
Error message shows "Failed to pair the device: No device selected"
![issue112801](https://user-images.githubusercontent.com/23466737/49141895-9e076800-f332-11e8-815a-908cefff9bb0.gif)

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Chrome(70.0.3538.110)
- Micro: bit hardware firmware: 0250

**Additional context:**
makecode.microbit.org version:  1.2.14
Microsoft MakeCode version:  4.4.7
microbit runtime version:  v2.1.1

**Comment by abchatra** [comment]
Won't fix P3
