### ISSUE TITLE
better error message for 403

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt-microbit#168]
Delete all these pointers? (y/n): y
INTERNAL ERROR: Error: Bad HTTP status code: 403 at https://www.pxt.io/api/ptr-microbit-editor-documentation; message: {"message":"Invalid or missing access_token"}

**Comment by mmoskal** [comment]
You need to do pxt login first

**Comment by tballmsft** [comment]
ah... thx.

**Comment by mmoskal** [comment]
Need to say "please try pxt login" on this error

**Comment by mmoskal** [comment]
fixed
