### ISSUE TITLE
Right-click on "Servos" blocks, "help" is disabled

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1681]
**Describe the bug**
Right-click on "Servos" blocks, "help" is disabled

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "Advanced" -> "Extensions" -> choose "servo" to add
3. Click "Servos" in toolbox and right click on each block to check its help

**Expected behavior**
"Servos" blocks should have help tutorial

**Actual behavior**
Right-click on "Servos" blocks, "help" is disabled
![issue112903](https://user-images.githubusercontent.com/23466737/49209376-441ba680-f3f5-11e8-8c4e-ce1ffbbd2e31.gif)

**Desktop (please complete the following information)**
OS: Windows
Browser: Edge, Chrome, Firefox & IE

**Additional context**
makecode.microbit.org version: 1.2.16
Microsoft MakeCode version: 4.4.8
microbit runtime version: v2.1.1

**Comment by abchatra** [comment]
Fixed
