### ISSUE TITLE
BETA Print fails to print blocks when one is from Bluetooth extension

### ISSUE THREAD

**Issue by martinwork** [Microsoft/pxt-microbit#1683]
**Describe the bug**
If a block from the Bluetooth extension is included, Print only shows the project name

**To Reproduce**
1. Go to 'https://makecode.microbit.org/beta'
2. Click on 'New project'
3. Add the Bluetooth extension
4. Add the "bluetooth led service" block to "on start"
5. Print

**Expected behavior**
The printout should include the blocks

**Screenshots**
![image](https://user-images.githubusercontent.com/989126/49238770-0f115300-f3f9-11e8-86bd-8eeb619b2526.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, iOS
 - Browser Edge, Chrome, Safari
 - Version
![image](https://user-images.githubusercontent.com/989126/49239110-d0c86380-f3f9-11e8-83c2-f0ca746c51d4.png)

**Comment by pelikhan** [comment]
It reproes.
![image](https://user-images.githubusercontent.com/4175913/49239418-95a54080-f3b7-11e8-862b-a2374037cb1d.png)

**Comment by martinwork** [comment]
Seems to happen with "servo" extension too, but not neopixel or turtle.
