### ISSUE TITLE
Can't enter inverted commas character in JavaScript from iOS keyboard

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#1684]
**Describe the bug**
JavaScript gets the wrong kind of inverted commas from the iOS keyboard.

**To Reproduce**
1. Go to 'https://makecode.microbit.org/'
2. Click on 'New project'
3. Add a line "basic.showString("hello") using the keyboard
4. Try to switch to blocks or Download

**Expected behavior**
JavaScript should insert the right kind of inverted commas.

**Desktop (please complete the following information):**
 - OS: iOS 11
 - Browser Safari
 - Version makecode.microbit.org 1.2.11

**Comment by abchatra** [comment]
Fixed in /beta for both intellisense and toolbox.
