### ISSUE TITLE
simulator does not load (firefox)

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt-microbit#1691]
**Describe the bug**
Even if I start a new empty project, the simulator does not show up. 

**To Reproduce**
1. Go to https://makecode.microbit.org/#editor
2. Click on new project
3. Simulator does not show up

**Expected behavior**
A simulator should load.

**Screenshots**
![image](https://user-images.githubusercontent.com/5718354/49341951-8a227580-f654-11e8-8e20-4acf16c3d5c1.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser firefox 
 - Version [e.g. 22] 63.0.3

**Additional context**
Debug console outputs this error:

TypeError: pxsim.setupStringLiterals is not a function[Learn More] pxtsim.js line 4712 > eval:42:1
<anonymous>
https://pxt.azureedge.net/blob/7735e613f88068f46503f6789c3e35ae328d4cdb/pxtsim.js line 4712 > eval:42:1
Runtime
https://pxt.azureedge.net/blob/7735e613f88068f46503f6789c3e35ae328d4cdb/pxtsim.js:4712:13
run
https://pxt.azureedge.net/blob/7735e613f88068f46503f6789c3e35ae328d4cdb/pxtsim.js:2087:23
receiveMessage
https://pxt.azureedge.net/blob/7735e613f88068f46503f6789c3e35ae328d4cdb/pxtsim.js:2040:21

**Comment by nielsswinkels** [comment]
makecode.microbit.org version:  1.2.11

Microsoft MakeCode version:  4.4.7

microbit runtime version:  v2.1.0

**Comment by nielsswinkels** [comment]
More bugs: if i switch to blockprogramming, I can't open the menu with the blocks.

**Comment by abchatra** [comment]
I can't repro this

**Comment by nielsswinkels** [comment]
It is probably related to that i have a huge amount of projects in my browser cache. And i don't want to lose those.
