### ISSUE TITLE
Download Screenshot output omits quotations

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#1696]
support ticket: 18732

**Describe the bug**
The output of 'Download Screenshot' does not include quotes around strings, whereas the blocks themselves do

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to makecode.microbit.org
2. Click drag a 'show string' block into 'on start'
3. Right click, choose 'download screenshot'
4. Compare the screenshot with the view of the code.

**Expected behavior**
The screenshot should contain the quotes

**Screenshots**

Code in the editor
<img width="467" alt="image" src="https://user-images.githubusercontent.com/147113/49392076-46e40780-f725-11e8-8d98-bafd0011d25a.png">

Code from the screenshot:
![image](https://user-images.githubusercontent.com/147113/49392084-506d6f80-f725-11e8-862e-057b341fd549.png)

**Desktop (please complete the following information):**
 - OS: macOS 
 - Browsers: Firefox, Chrome
 - Version: 63.0.3, 70.0.3538.110 respectively

**Comment by samelhusseini** [comment]
Fixed in latest pxt-core.

**Comment by ChrisDorna** [comment]
Hi Sam, Perhaps a stupid question (Yes, I know that there are no stupid questions) but when is this fix visible in the online version? Or is there a way to 'test' the fix.

**Comment by samelhusseini** [comment]
That would be a question for @abchatra

**Comment by abchatra** [comment]
Early Jan (we are not releasing in December)

**Comment by ChrisDorna** [comment]
Hi @abchatra,
I have to make a lot of screenshots for a new book. Is it possible to 'test' the changes @samelhusseini  prepared?

**Comment by microbit-mark** [comment]
@ChrisDorna If you're able to create documentation online, you could create a series of embedded blocks that will always be up to date See. https://makecode.com/blocks-embed

There is also a [Gitbook plugin](https://plugins.gitbook.com/plugin/pxt) for blocks, so if you're able to publish via Gitbook and download the PDF for example, tht might be a good way to easily update the text.

**Comment by abchatra** [comment]
Fixed in /beta

**Comment by abchatra** [comment]
Repros still on Edge

**Comment by abchatra** [comment]
Fixed
