### ISSUE TITLE
Embedded code blocks overlap

### ISSUE THREAD

**Issue by microbit-giles** [Microsoft/pxt-microbit#1697]
**Describe the bug**
Tried to embed code blocks from a project https://makecode.microbit.org/_3VFKro2CFguy in a web page and the blocks overlap each other.

**To Reproduce**
1. Go to http://www.suppertime.co.uk/blogmywiki/2018/12/microbit-dog-collar/ 
2. Enter password: Ellie (capital E)
3. Scroll down to 'Here’s how a radio version might look. The dog would wear a micro:bit on its collar with the transmitter code'
4. See error in blocks below.

**Expected behavior**
I would expect the 'on start', 'forever' and 'on button A pressed' blocks not to overlap so they are all visible.

**Screenshots**
<img width="724" alt="screenshot 2018-12-04 at 10 07 43" src="https://user-images.githubusercontent.com/42380137/49435447-8c98e280-f7ae-11e8-8883-69fd8deeb4d2.png">

**Desktop (please complete the following information):**
 - OS: MacOS X Mojave 10.14.1
 - Browser Chrome or Safari
 - Version: Chrome v70

**Smartphone (please complete the following information):**
not tested

**Additional context**
Had exactly the same issue with another project with multiple blocks, both created in the last week.

**Comment by abchatra** [comment]
@samelhusseini is this something you have fixed recently?

**Comment by abchatra** [comment]
fixed
