### ISSUE TITLE
Please bring back internal/external inputs in v1

### ISSUE THREAD

**Issue by ChrisDorna** [microsoft/pxt-microbit#1698]
The internal/external option in the previous version realy helped to give the students a better view on complex functions like this:
![progr_04b_03](https://user-images.githubusercontent.com/20975602/49449740-d77d1f00-f7db-11e8-9f0a-c2f6f0ba7968.png)

In the previous version it was possible to breakdown the code to this:
![vb](https://user-images.githubusercontent.com/20975602/49449854-16ab7000-f7dc-11e8-9068-f713a7f85f25.png)

It would be great if the internal/external option returned in the new editor.

**Comment by abchatra** [comment]
Feedback from NYC schools
-	Blocks are too long horizontally - when you have nested blocks (math operators in conditional statements) it makes the blocks really long
-	Workspace issues are the biggest problem with students right now - they can zoom out, but then they can't read their code.  Some of their programs have quite a lot of blocks - and when they expand horizontally as well as vertically, it become very difficult for them manage/see/edit
-	Teachers collapse the Simulator - but students love seeing the simulator, so they don't want to collapse it
-	Classroom devices tend to be 13" screens or Chromebooks - more and more schools shifting away from computer lab desktops to computer carts with Chromebooks

**Comment by microbit-mark** [comment]
Some more support for this feature
![image](https://user-images.githubusercontent.com/31242877/49993739-6974ec80-ff7f-11e8-9c8b-f44583c4720e.png)

https://twitter.com/javierpiay/status/1073499500772233216

**Comment by abchatra** [comment]
What we have today is scratch blocks https://beta.scratch.mit.edu/ which is coming to scratch in Jan as well. It

**Comment by abchatra** [comment]
This is by design.

**Comment by ChrisDorna** [comment]
I am disappointed. Scratch is different from micro:bit and the inline view does not work for longer lines and there is already a 'vertical' view for arrays
<img width="236" alt="array" src="https://user-images.githubusercontent.com/20975602/77144259-a9315a80-6a85-11ea-998e-7030fc4e0f78.png">
