### ISSUE TITLE
Missing blocks in sig

### ISSUE THREAD

**Issue by tinfoilhatter** [Microsoft/pxt-microbit#170]
There are numerous doc pages where the **sig** block at the top of the page only shows text, and cannot show code blocks. We may have to use screenshots to replace them

Here are some sample pages where only text is shown in the **sig** block:

- Game

1. **Move**

- Images

1. **Show Image**
2. **Scroll Image**

**Comment by pelikhan** [comment]
Instance methods not yet supported in decompiler.

**Comment by abchatra** [comment]
Ported to https://github.com/Microsoft/pxt/issues/536
