### ISSUE TITLE
Shared/embedded view - 2nd micro:bit not showing for Radio

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-microbit#1700]
For Radio programs, when you click on the Play/Simulator view, don't see the 2nd micro:bit.
https://makecode.microbit.org/93468-53396-53534-83273 
![sharedradio](https://user-images.githubusercontent.com/22108954/49477994-718c9980-f7d3-11e8-8a2f-e65934d7b9d8.PNG)

**Comment by abchatra** [comment]
I can repro on Chrome and Edge.

**Comment by pelikhan** [comment]
Never supported in sharing mode.
