### ISSUE TITLE
Help side panel no longer displays the pop-out button when hosted in a WKWebView

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#1701]
**Describe the bug**
The side help panel normally displays a pop-out button. This is now missing when MakeCode is hosted in a WKWebView. 

**To Reproduce**
1. Go to Create Code in the iOS micro:bit app.
2. Long press on the forever block and choose Help
3. See that there is no pop-out button

**Expected behavior**
The pop-out button should be there to enable display of the help in Safari.

**Desktop (please complete the following information):**
 - OS: iOS 11
 - Browser WKWebView
 - Version [e.g. 22] MakeCode v1.2.11

**Comment by abchatra** [comment]
Again does this still reproduce?

**Comment by abchatra** [comment]
Fixed in /beta
