### ISSUE TITLE
A ".pdf" file can't be printed on IE

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1709]
**Describe the bug**
A ".pdf" file can't be printed on IE

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "More..." -> "print"  -> click "print" on the pop-window

**Expected behavior(Edge, Chrome, Firefox)**
A ".pdf" file should be printed

**Actual behavior(IE)**
A ".pdf" file can't be printed on IE
![issue12704](https://user-images.githubusercontent.com/23466737/49643727-69419200-fa51-11e8-8785-d70b439448bc.gif)

**Additional context:**
OS: Windows
Browser: IE(11.134.17763.0)

**Comment by abchatra** [comment]
Can we remove this from IE if it doesn't work?

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/pull/5378
