### ISSUE TITLE
this program doesn't work (showImage)

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt-microbit#171]
https://codethemicrobit.com/xasjpzjyha

**Comment by thomasdenney** [comment]
I can only replicate this on the website - the program compiles and runs on the micro:bit and in the simulator as of the latest commits to `master` and `notd`. Which commit is the website using at the moment?

**Comment by mmoskal** [comment]
Very old - https://github.com/Microsoft/pxt-microbit/commits/58f79ea6171bb0ac705760f1caecb8d92711ebc8

To find out commit you can do the following:

```
[10:55 tmp]$ pxt ptr microbit
Using PXT/core from /Users/michal/src/pxt.
{ ... htmlartid: '',
  releaseid: 'fjrzv',
  ... }
[10:57 tmp]$ pxt api fjrzv
Using PXT/core from /Users/michal/src/pxt.
{
 ... 
 "commit": "https://github.com/Microsoft/pxt-microbit/commits/58f79ea6171bb0ac705760f1caecb8d92711ebc8",
  "branch": "v0.2.180",
...}
[10:57 tmp]$
```

**Comment by mmoskal** [comment]
In fact, I guess it's easier to look at "more -> about" and PXT and PXT-microbit versions there and then look in changelog

**Comment by mmoskal** [comment]
This was in fact broken in the simulator. Fixed now.
