### ISSUE TITLE
String's quote is lost after printed on Edge

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1710]
**Describe the bug**
String's quote is lost after printed on Edge

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "{}JavaScript" to switch to JavaScript editor and copy below code to content pane
......................................................................................
let text_list: string[] = []
let text_list1: number[] = []
basic.forever(function () {
    text_list1 = [1, 2, 3]
    text_list = ["1", "2", "3"]
    basic.showString("Hello!")
})
........................................................................................
3. Click "More..." -> "print" -> click "print" on the pop-window

**Expected behavior(Chrome, Firefox)**
![capture11](https://user-images.githubusercontent.com/23466737/49644485-84ad9c80-fa53-11e8-88db-3077324e4f2e.PNG)

**Actual behavior(Edge)**
String's quote is lost after printed on Edge
![capture22](https://user-images.githubusercontent.com/23466737/49644480-837c6f80-fa53-11e8-8b0a-a39c74da5d6f.PNG)

**Additional context**
OS: Windows
Browser: Edge (44.17763.1.0)

**Comment by pelikhan** [comment]
@samelhusseini  did you fix this as part of your screenshot work?

**Comment by samelhusseini** [comment]
I didn't look into this code path, possibly fixed but would be a coincidence.

**Comment by pelikhan** [comment]
Is that fix in the microbit pxt branch by any chance :) ?

**Comment by pelikhan** [comment]
It seems that all xref svg elements are lost in Edge/IE. This also includes +/- images.

**Comment by samelhusseini** [comment]
I dont think so.

**Comment by Helen09** [comment]
"Print" function is not supported on Edge now

**Comment by abchatra** [comment]
Bug still repros
