### ISSUE TITLE
The printed icon on block "show icon" is not clear 

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#1711]
**Describe the bug**
The printed icon on block "show icon" is not clear 

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Drag block "show icon" and put it under block "forever"
3. Click "More..." -> "print" -> click "print" on the pop-window

**Expected behavior**
The printed icon on block "show icon" should be clear
![99](https://user-images.githubusercontent.com/23466737/49645220-030b3e00-fa56-11e8-85be-88ad408fe73b.PNG)

**Actual behavior**
The printed icon on block "show icon" is not clear 
![88](https://user-images.githubusercontent.com/23466737/49645223-04d50180-fa56-11e8-9e2e-3b972f0fb78e.PNG)

**Additional context**
OS: Windows
Browser: Edge, Chrome, Firefox

**Comment by Helen09** [comment]
This issue is only repro on Chrome now

**Comment by abchatra** [comment]
Fixed in /beta
