### ISSUE TITLE
Radio.sendString() has suprious preceding information

### ISSUE THREAD

**Issue by rhubarbdog** [Microsoft/pxt-microbit#1712]
**Is your feature request related to a problem? Please describe.**
This may be a bug
There is a lack of compatibility between blocks radio and micropython radio.

**Describe the solution you'd like**
When I have a micropython producer and a blocks consumer. I broadcast on channel 7 group 1 "Message" the consumer logs the message's arrival by executing `on RadioReceive` block but the message logged is blank.
When i have a blocks producer and a micropython consumer. I broadcast on group 1 and receive on channel 7 group 1.  The message is preceded by garbage. On the microbit it displays as `?<???????Hello` or `????F????Hello` . `screen` a serial terminal collects the following
```
        FHello
<Hello
```
I'd like to be able to produce Radio applications in both blocks and micropython that can communicate with each other 

I've also logged this on the microbit/micropython repository <a href="https://github.com/bbcmicrobit/micropython/issues/617">#617</a>

**Comment by abchatra** [comment]
See https://support.microbit.org/support/solutions/articles/19000053168-receiving-radio-data-from-the-makecode-editor-within-python

There are differences in implementation due to historical reasons.
