### ISSUE TITLE
Random/ music blocks failed to load correctly after editor update

### ISSUE THREAD

**Issue by alankrantas** [Microsoft/pxt-microbit#1716]
**Describe the bug**
It seems that after each editor update (the webpage downloaded the update and refreshed), for a period of time some old projects would not load correctly in the editor.

I've reported this before, but closed it when everybody (me included at that time) seems not be able to reproduce it. So I recorded a video this time, after the editor upgrade from v1.2.11 to v1.2.12.
https://www.youtube.com/watch?v=4v0TGdxtN3Q

When this issue occurred, the editor might switch to JavaScript right after you load the code. As far as I know, the upper limit of Random block might go missing and the notes of Play tone block might all reset to Middle C.

![microbit-screenshot 1](https://user-images.githubusercontent.com/44191076/47954582-78eb3800-dfc6-11e8-998a-6165c79c898d.png)

After a while, the issue would be no more for some reason.  Until the next update, that is. 

After the video I shot my music program can be loaded correctly, although the editor still switched to JavaScript first. Switch to block mode is ok. One of the game program loaded correctly now, again into JavaScript mode first, with the proper Random upper limit. However switched it to block mode the upper limit went missing again. Switch back to JavaScript and the upper limit shows 0.

One of my colleague (who is teaching some kids and need to prepare materials every week) also asked me why this happened a few days ago. This happens on multiple computers (Windows 8 and 10/up to date Chrome) in my home and office.

**Comment by abchatra** [comment]
@alankrantas can you please share the hex file you are loading which has this issue?

**Comment by abchatra** [comment]
@riknoll I can repro this and see in the file microbit-螞蟻過街.hex This is basically Math.random upgrade. Can you take a look? May be upgrade rules are incorrectly hitting for this case.

**Comment by alankrantas** [comment]
Hello all,

The projects were first created for our first micro:bit book during summer, downloaded in V1 Beta. However when I first encountered this problem in late October (after V1 officially online) I fixed and downloaded these projects manually. You can see the files were created in Oct 31th. Since the projects are provided online for our customers I'll update them again.

I reported this in early Nov but the problem cannot be reproduced at that time:
https://github.com/Microsoft/pxt-microbit/issues/1581

The play note block have the similar problem too, sometimes, as shown in my video. Can you guys check it as well?

Alan

**Comment by riknoll** [comment]
Thanks for the extra context Alan! I don't see any issues with the note blocks in the programs that you linked; they all seem to open in the editor correctly and have the correct notes. I'm using the same version of the editor as the one in the video too. Could you provide some details on your browser version?

**Comment by alankrantas** [comment]
The ones I used in my home and office are both Chrome version 70+ (I tested Bluetooth download and console last month).

Like I said, the note problem seems to happen right after an editor update, and the issue might dispensary some time after. Right now it works for me too. But it didn't work on the day the update dropped, as shown in my video. I also encountered this more than once before without being able to identify the cause.

Maybe I create a recent music project and test it after the next update?

**Comment by alankrantas** [comment]
Hi, me again.

I wrote a game in mid-Dec. When I loaded it again a few minutes ago the random blocks show the same problem too.

[microbit-星球防衛者.zip](https://github.com/Microsoft/pxt-microbit/files/2712448/microbit-.zip)

![1](https://user-images.githubusercontent.com/44191076/50480812-2d2e9b00-0a19-11e9-8065-ed450d899c59.jpg)

MakeCode version 1.2.13, Chrome 71.0.3578.98, Win 10.

**Comment by abchatra** [comment]
Fixed
