### ISSUE TITLE
Block generator puts "on start" last

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt-microbit#1721]
**Describe the bug**
When I use the service to translate javascript into a png of the corresponding block code, it always puts the "on start" part last (furthest down). I would like it to come first (on top).

**To Reproduce**
1. Create some javascript makecode that includes on start and some other function
2. use the javascript to generate a picture
3. See that the on start comes in the end

**Expected behavior**
I would expect the on start part to come first.

**Screenshots**
See it on this page: http://mermicrobit.se/

![image](https://user-images.githubusercontent.com/5718354/49701378-020c1500-fbec-11e8-9889-772021d85f6c.png)

![image](https://user-images.githubusercontent.com/5718354/49701344-8dd17180-fbeb-11e8-9534-f9afd4174dec.png)

**Additional context**
I use this url for the renderer: https://makecode.microbit.org/beta--docs?render=1

**Comment by nielsswinkels** [comment]
Why was it closed? Seems like it wasn't changed?

**Comment by abchatra** [comment]
We do not plan to fix this for legacy reasons. Won't fix. (Main reason is while loop in the on start will hog the fibers and event won't get registered). Valid expectation in the bug though.

**Comment by nielsswinkels** [comment]
But changing the position visually doesn't make any difference for what order stuff actually happens programmatically. My request is to have the "on start" block get generated as the topmost block, not the last.

**Comment by pelikhan** [comment]
You need to register the event before onstart starts otherwise they will not run while on start is running.

**Comment by nielsswinkels** [comment]
What i'm talking about is the renderer that generates the visual picture of the blockcode. This should have nothing to do with how the code actually works in the background?
