### ISSUE TITLE
Wiring Instructions printing fails on iOS and is slow on macOS

### ISSUE THREAD

**Issue by martinwork** [Microsoft/pxt-microbit#1722]
**Describe the bug**
The Wiring Instructions for this project fail to print on iOS. Either block on its own is OK, but not both together. macOS takes over 10s to display the preview with both blocks or 2s with either one.
 
![image](https://user-images.githubusercontent.com/989126/49701144-72ad3480-fbe0-11e8-929c-308b09ec1b3a.png)

**To Reproduce**
1. Go to 'https://makecode.microbit.org/beta'
2. Enable the Wiring Instructions Experiment
3. Create the project above
4. Try to print the instructions

The printout is blank, though the window is displaying the HTML.
![image](https://user-images.githubusercontent.com/989126/49701346-316a5400-fbe3-11e8-9183-37fc11922b98.png)

**Expected behavior**
The printout shouldn't be blank:
![image](https://user-images.githubusercontent.com/989126/49701308-b7d26600-fbe2-11e8-9557-330e70d6964f.png)

**Desktop (please complete the following information):**
 - OS: iOS 11.4 iPad Air
 - Browser: Safari
 - Version
![image](https://user-images.githubusercontent.com/989126/49701245-cc622e80-fbe1-11e8-836b-2e0730658ed3.png)

**Additional context**
I think iOS may be aborting because of high memory usage or possibly a limit on the size of images. I have caught the generated HTML and loaded it directly into Safari, with the same results. If I edit the HTML to remove some of the pages, all the pages will print, but not from the same file.

**Comment by abchatra** [comment]
We don't take bugs for experiments in this repo. They need to be part of the feedback issue on PXT (SEe here https://github.com/Microsoft/pxt/issues/4739)
