### ISSUE TITLE
radio menu does not display in Danish language

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1726]
microbit support 18932

![screenshot 2018-12-10 at 13 49 57](https://user-images.githubusercontent.com/31242877/49736627-90cb7100-fc82-11e8-8cd5-985a788ff130.png)

**Comment by abchatra** [comment]
This is likely translation issue. @ganicke or @pelikhan Can we somehow patch fix this at translation?

**Comment by pelikhan** [comment]
Assign translations issue to someone going forward, thank you.

**Comment by pelikhan** [comment]
See https://github.com/Microsoft/pxt/pull/5081

**Comment by pelikhan** [comment]
Also we should investigate why we are crashing and handle this case gracefully. Most likely trying to inject a block that does not exist in the blockly tree.

**Comment by abchatra** [comment]
@samelhusseini Can you please take a look? Ideally if it is a simple change in the translation we could just patch the Danish translation.

**Comment by samelhusseini** [comment]
Looks to be fixed. https://makecode.microbit.org/?forceLang=da#editor

Am I using the right language code?

**Comment by samelhusseini** [comment]
same deal.. Am i missing something?

**Comment by abchatra** [comment]
Yes I reloaded edge and it is fixed. Not sure how. Likely someone fixed the translation. I consistently repro'd this morning.

**Comment by microbit-mark** [comment]
Is this a localised language bug @abchatra? Same issue for Bulgarian in beta editor  

1. Choose the Bulgarian localization (still in beta): https://makecode.microbit.org/beta?liveforcelang=bg
2. Open the editor and expand the Music (Музика) tab
3. The blocks in the tab are one over another. (It seems the transform="translate(16,72)" attribute is not applied.)

**Comment by abchatra** [comment]
It is a localization issue (although flyout shouldn't crash).Bulgarian is not a supported language right? How did you get this issue?

**Comment by microbit-mark** [comment]
User reported it as they are developing Bulgarian language support. I guess in Crowdin?

**Comment by bsivanov** [comment]
Hello, I reported the issue. Bulgarian is still in beta so I decided to test the localization using the mentioned [https://makecode.microbit.org/beta?liveforcelang=bg](https://makecode.microbit.org/beta?liveforcelang=bg) link. I can still consistently reproduce the issue using different browser, with cleared cookies, etc. 

@abchatra, do you know the cause, or any workaround? I am an approved translator for the Bulgarian localization in Crowdin, so I can apply it in the translation if such is available.

**Comment by pelikhan** [comment]
If you open the JavaScript console and reload the page, you should see error messages (hopefully)

**Comment by ganicke** [comment]
We seem to be missing **@param value** and **@param handler** in the jsdoc for **music.onEvent**. Not sure if this is might affect the translated block render.

```typescript
/**
 * Registers code to run on various melody events
 */
  //% blockId=melody_on_event block="music on %value"
  //% help=music/on-event weight=59 blockGap=32
  export function onEvent(value: MusicEvent, handler: () => void) {
        control.onEvent(MICROBIT_MELODY_ID, value, handler);
  }
```

**Comment by samelhusseini** [comment]
What this means is that one of the translations to the blocks in crowdin (bulgarian) is malformed. 
in this case it's the setTempo block, looking into why..

**Comment by samelhusseini** [comment]
The translation for setTempo is: 
```
set tempo to (bpm)|%value
задаване темпо до (bpm)|%стойност
```

This is probably not that obvious, but you shouldn't translate the %variables ie: %value.

The correct translation for this would be: 
```
задаване темпо до (bpm)|%value
```

**Comment by samelhusseini** [comment]
I have fixed this instance in crowdin, shouldn't take long to propagate.

**Comment by ganicke** [comment]
Actually, that looks like my bad 🤕 

![image](https://user-images.githubusercontent.com/27789908/49830248-7a3a1e00-fd45-11e8-8691-8e9969f5fb21.png)

**Comment by samelhusseini** [comment]
Yeah haha.

**Comment by abchatra** [comment]
Thanks folks!

**Comment by ganicke** [comment]
Ha, no it was part of a batch of translation errors. Obviously I missed fixing this one.
