### ISSUE TITLE
Issues in packages.md

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1729]
When clicking through on the ALS robot extension,  we get a no README file found message
![screen recording 2018-12-11 at 12 29 pm](https://user-images.githubusercontent.com/31242877/49807003-f25a1100-fd50-11e8-87a5-c4b6899ad424.gif)

The README.md does exist here though

https://github.com/alsrobot-microbit-makecode-packages/ALSRobotKeyboard/blob/master/README.md

**Comment by pelikhan** [comment]
The released version does not have a readme.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pelikhan** [comment]
They need to bump.
