### ISSUE TITLE
Is Gitbook plugin still live?

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1732]
**Describe the bug**
A link in the docs goes to a Gitbook plugin for embedding blocks, the link from this page back to the Microsoft Github is broken
![screen recording 2018-12-11 at 04 25 pm](https://user-images.githubusercontent.com/31242877/49815244-3d7d1f80-fd63-11e8-9722-30e8513bf423.gif)

**To Reproduce**
1. Go to 'https://makecode.com/blocks-embed'
2. Click on 'https://plugins.gitbook.com/plugin/pxt'
3. Click on 'https://github.com/Microsoft/gitbook-plugin-pxt' under Plugin

**Expected behavior**
Link works as expected

**Comment by microbit-mark** [comment]
@samelhusseini

**Comment by samelhusseini** [comment]
Yes, please try again.

**Comment by abchatra** [comment]
fixed
