### ISSUE TITLE
Inconsistent appears of show LEDs block across browsers

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt-microbit#174]
Minor, but the LED block appears different in each browser.

Windows 10, Edge

![edge-led](https://cloud.githubusercontent.com/assets/20356546/17015948/af34f3f4-4f24-11e6-8901-702048ab56cf.PNG)

Windows 10, Chrome

![led-chrome](https://cloud.githubusercontent.com/assets/20356546/17015953/b55a457c-4f24-11e6-8213-de6b996a5e6a.PNG)

Windows 10, Firefox

![led-firefox](https://cloud.githubusercontent.com/assets/20356546/17015961/bbf78458-4f24-11e6-800f-2e3038ee2ab6.PNG)

OS X, Safari

<img width="199" alt="led-safari" src="https://cloud.githubusercontent.com/assets/20356546/17015967/c0818302-4f24-11e6-8dc7-8be9387dc58b.png">

**Comment by darrenge** [comment]
There was an issue in pxt repo on this already, but closing that (and keeping this open) as pxt-microbit is where we should put simulator issues.

**Comment by darrenge** [comment]
Also ... the LEDs should be more centered on all.

**Comment by microsoftsam** [comment]
Edge doesn't support text-shadow blur so it'll only show a blur around the box in Chrome, Safari and Firefox. Centering the box is difficult without making a change in blockly itself (x needs to change to -2 instead of -3). 
Applied a fix that will get it close to centered.

**Comment by pelikhan** [comment]
Marking this one with "Blockly Change" to track set of fixes for which we'll need to build a PR.
