### ISSUE TITLE
Help on external extensions cannot be translated

### ISSUE THREAD

**Issue by CleoQc** [microsoft/pxt-microbit#1740]
It is currently impossible to offer a translation of the help file from an external, approved, extension as it only reads from the Github README.md file

![translation](https://user-images.githubusercontent.com/4965628/49949287-4553d580-fec3-11e8-9de6-84b6d743f696.png)

I would like to be able to offer a fully translated extension. 
Thank you for considering this.

**Comment by abchatra** [comment]
@guillaumejenkins any pointers here?

**Comment by CleoQc** [comment]
I would be totally fine if having README.fr.md  was supported.

**Comment by soubsoub** [comment]
Yes please, add the support. It is important for teaching.

**Comment by abchatra** [comment]
Translations in extensions are supported.

**Comment by CleoQc** [comment]
The help file can be translated now? How?

**Comment by abchatra** [comment]
https://makecode.com/extensions/localization#4-add-the-translation-files-to-the-extension-configuration

**Comment by abchatra** [comment]
You can add file
_locales/ja/Readme.md 

and it should work

**Comment by abchatra** [comment]
Let us know if this doesn't

**Comment by pelikhan** [comment]
It is now supported in the beta
