### ISSUE TITLE
Experiments Feedback links only show when browser window is wide

### ISSUE THREAD

**Issue by martinwork** [Microsoft/pxt-microbit#1741]
**Describe the bug**
When the desktop browser window is reduced in width from full-screen towards nearly square, the Experiments Feedback links disappear.

The Feedback links do not show at all on iOS.

**To Reproduce**
1. Go to 'https://makecode.microbit.org/beta#editor'
2. Click on 'More...' then 'About...' then 'Experiments'
3. Except on iOS, reduce the width of the browser window

**Expected behavior**
The links should be visible, so users can read the instructions and give feedback.

The links are inside a div of class "ui extra content widedesktop only".

**Screenshots**
![image](https://user-images.githubusercontent.com/989126/50007893-51ff2900-ffaa-11e8-870d-46fcf08824e7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, macOS Mojave, iOS 11
 - Browser Chrome, Edge, Safari
 - Version
![image](https://user-images.githubusercontent.com/989126/50008325-b969a880-ffab-11e8-9470-a2b6912c09d5.png)

**Comment by jwunderl** [comment]
Unfortunately, there isn't enough room on mobile to fit a feedback link, as they switch to being small icons. The cards are still the same size in tablet view, though, so we can fix that at least; that's being addressed in https://github.com/Microsoft/pxt/pull/5428
