### ISSUE TITLE
Allow Bluetooth Client Event to be configured to support WRITE or WROTE WITHOUT RESPONSE or BOTH operation types

### ISSUE THREAD

**Issue by smartyw** [Microsoft/pxt-microbit#1742]
**Is your feature request related to a problem? Please describe.**

The Bluetooth Event service includes a characteristic called Client Event. This characteristic supports both forms of Bluetooth LE write operation, namely WRITE and WRITE WITHOUT RESPONSE. The first type is a request/response operation, offering a reliable way of communicating with a remote device (in this case a micro:bit) and the second is a fast operation which is of the "fire and forget" type. The client does not need to wait for a response (because none is defined for a WRITE WITHOUT RESPONSE operation) and so throughput of writes can be much higher. Which write type an application would use depends on the requirements and priorities of the application (reliability vs speed).

In the DAL the characteristic and its operations are defined here:

https://github.com/lancaster-university/microbit-dal/blob/master/source/bluetooth/MicroBitEventService.cpp#L49

Unfortunately, the Web Bluetooth specification has an error and does not provide distinct APIs for WRITE and WRITE WITHOUT RESPONSE because it assumes a characteristic will never support both. Web Bluetooth is at fault here and implementations are left to choose one or the other, automatically with the application developer having no control. This can result (for example) in laggy, badly responding applications when WRITE WITHOUT RESPONSE was needed, but Web Bluetooth selects the WRITE operation.

This issue is logged against the Web Bluetooth specification here: https://github.com/WebBluetoothCG/web-bluetooth/issues/238

One workaround is to remove one of the support operations from the characteristic according to the application need. With the BBC micro:bit Client Event characteristic, this can easily be achieved when programming in C/C++ but cannot be achieved when using MakeCode.

**Describe the solution you'd like**
I would like a new Project Configuration setting for MakeCode projects that use Bluetooth named something like "Client Event priority (Fast or Reliable?) with choices of Fast | Reliable | Both. The default would be Both. This would cause the generated C/C++ to either include the WRITE operation or the WRITE WITHOUT RESPONSE or both operation on the Client Event characteristic at https://github.com/lancaster-university/microbit-dal/blob/master/source/bluetooth/MicroBitEventService.cpp#L49 .

**Describe alternatives you've considered**
You could achieve the same with two blocks that could be usedin the On Start block. Something like "Support Fast Client Event Writes" and "Support Reliable Client Event Writes".

**Additional context**

**Comment by pelikhan** [comment]
Please file this on the microbit-dal repo. This requires a change over there first.

**Comment by smartyw** [comment]
Ok, will do.

**Comment by smartyw** [comment]
See https://github.com/lancaster-university/microbit-dal/issues/411

**Comment by abchatra** [comment]
This is external, dal  issue
