### ISSUE TITLE
Math.randomRange is not properly converted to blocks in Traditional Chinese version

### ISSUE THREAD

**Issue by FranklinWhale** [Microsoft/pxt-microbit#1744]
**Describe the bug**

**To Reproduce**
1. Switch MakeCode language to Traditional Chinese
2. Open a new project
3. Switch to JavaScript mode
4. Replace all content with `basic.showNumber(Math.randomRange(0, 8000));`
5. Switch to Blocks mode
6. Repeat the steps above in English

**Expected behavior**
The arguments passed to the `randomRange` method should be properly shown as block contents.
![randomrange_en](https://user-images.githubusercontent.com/8416067/50076922-ecb36e00-021d-11e9-8c9e-d85e1f67d4aa.gif)

**Actual behavior**
The second argument is always missing.
![randomrange_zh-hant](https://user-images.githubusercontent.com/8416067/50076944-fb018a00-021d-11e9-864d-aa3e4e0d10f6.gif)

**Desktop:**
 - OS: Windows 10 1803
 - Browser Edge 17, Chrome 71, Firefox 64

**Additional context**
1. Both screenshots above were captured using Firefox 64 with the following pxt version info:
makecode.microbit.org version:  1.2.13
Microsoft MakeCode version:  4.4.7
microbit runtime version:  v2.1.1
2. This issue may be related to #1716

**Comment by samelhusseini** [comment]
Fixed.

**Comment by abchatra** [comment]
Issue was with incorrect translation and might take a while to reflect

**Comment by FranklinWhale** [comment]
Verified fixed. Thanks!
