### ISSUE TITLE
Hex file does not compile in win10 app

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1745]
**Describe the bug**
User reports that [microbit-light_level_external_sensor_v63.hex.zip](https://github.com/Microsoft/pxt-microbit/files/2685842/microbit-light_level_external_sensor_v63.hex.zip) will open in the makecode web editor and recompile, but not in the win 10 app which reports a compilation failure. The file also runs on the micro:bit hardware without error.

**To Reproduce**
1. Open attached Hex in Windows10 app
2. Click on Download
3. See compilation error

**Expected behavior**
Code should compile as in web app

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**Desktop (please complete the following information):**
 - OS: Win 10 v1803

App version is out of sync with browser version. Is it supposed to auto update?
<img width="716" alt="screenshot 2018-12-17 at 11 40 26" src="https://user-images.githubusercontent.com/31242877/50085260-700a9a80-01f1-11e9-860f-5f18b2d59208.png">

**Comment by abchatra** [comment]
This hex file fails to download in Chrome and Edge browser as well

**Comment by abchatra** [comment]
And this is based on Filesystem package github:microsoft/pxt-filesystem#v0.9.3  which is buggy. Likely won't fix from our end.

**Comment by abchatra** [comment]
Please file the isse on the filesystem repo.

**Comment by abchatra** [comment]
Opened on filesystem repo.

**Comment by themarkness** [comment]
Strange. It worked for me in Firefox on mac, hence why I opened it here.
