### ISSUE TITLE
Make microbit_heap_print available

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#1748]
Now that microbit_heap_print() is available in the DAL could we please make it visible to a JavaScript programme?  Perhaps even as a checkbox option in MakeCode alongside 

```
    "yotta": {
        "config": {
            "microbit-dal": {
                "debug": 1,
                "heap_debug": 1
            }
        }
    }
```

https://github.com/lancaster-university/microbit-dal/issues/390#issuecomment-426228097

**Comment by pelikhan** [comment]
This could be enabled by an extension that brings those flags. Not really worth bringing it live for all users.
