### ISSUE TITLE
Reading magnetometer field strength should not require calibration

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-microbit#1750]
We should not calibrate when reading the magnetic field strength.
@finneyj could you confirm?

**Comment by finneyj** [comment]
Hi @pelikhan 

Ideally, the sensor *should* be calibrated for this, but there are a number of use cases where kids might want to simply get a best effort value and look for relative shifts in field strength e.g. for metal detector etc.

An uncalibrated sensor will give potentially give a very large error in result, and this error will be different from one micro:bit to another (so not deterministic across our ecosystem), so difficult to write examples/sample code for. Moreover, the magnetic field strength is calculated using Pythagoras across the 3 axes on the magnetometer, and each axis needs its own calibration value... so this means any rotation of an uncalibrated micro:bit will also have a large impact on the field strength value.

It may be better, for scenarios where calibration may not be possible, to read the value of just one axis instead (e.g. the z axis)...
