### ISSUE TITLE
console.log block

### ISSUE THREAD

**Issue by podenphant** [Microsoft/pxt-microbit#1751]
I would like a console.log() block in the blocks panel. Maybe under the Basic category?

When debugging or tracking down a bug it would be very helpful if there was a block representing console.log()

Especially when teaching kids to find errors in their own code.

As it is now we can switch to the javascript editor and write the code console.log() which is then represented in the blocks editor.

But when teaching smaller children we try to stay away from the javacript editor.

**Comment by abchatra** [comment]
Serial.writeLine is same as console.log which is already available in microbit.
