### ISSUE TITLE
Infection project is different on hardware

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1752]
microbit-support:19134

**Describe the bug**
https://makecode.microbit.org/projects/infection displays assigned user letters in simulator but not on the device

**To Reproduce**
1. Go to 'https://makecode.microbit.org/projects/infection'
2. Select JS and copy to makecode or click on makecode link
3. Press A+B in simulator and programme is initiated, showing number of connected users and letter on additional devices.
4. Flash same program to micro:bit
4. Press A+B, number of connected users is shown on master device, but additional micro:bits show smiley face and not assigned letter. 

**Expected behavior**
Docs says "When paired, a letter appears on the player’s screen, this letter is the player’s identity." This is expected behaviour

**Comment by rhl2401** [comment]
Anyone who have solved this problem?

**Comment by abchatra** [comment]
@pelikhan
