### ISSUE TITLE
Program throws 042 error on device

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1754]
**Describe the bug**
This program runs fine in the simulator but seems to start by setting the game LED and then throw an error.

https://makecode.microbit.org/_0Xm6ELJj7Mqm
[microbit-racing.hex.zip](https://github.com/Microsoft/pxt-microbit/files/2702343/microbit-racing.hex.zip)

**To Reproduce**
1. Go to 'https://makecode.microbit.org/_0Xm6ELJj7Mqm' see/demo program running in sim
2. Flash attached HEx or compile and flash to micro:bit
4. Briefly see pixel created at x=2 y=0 and then 042 error

**Expected behavior**
Program should run as in sim

**Additional context**
Initial version sent by user briefly displayed error "cannot mix game.LEDsprite with number"
![screenshot 2018-12-20 at 17 02 44](https://user-images.githubusercontent.com/31242877/50337831-32b44e80-050a-11e9-8eda-69dfe2affa3d.png) but this dissapeared and i can't recreate.

**Comment by martinwork** [comment]
The first "while" in the forever loop should check length > 0 rather than >=.

But why does it run in the simulator? And what is error 42?

**Comment by abchatra** [comment]
Simulator runs javascript and when there is out of boundary conditions it won't throw errors (eventhough we try to mimic as much as possible). But the hardware is different and is less tolerant. As @martinwork pointed out bug in the program is causing this.
