### ISSUE TITLE
block renderer does not show multiline comment

### ISSUE THREAD

**Issue by nielsswinkels** [microsoft/pxt-microbit#1756]
**Describe the bug**
I use the renderer to generate an image of the block-style translation of a bit of javascript. If i have a multi-line comment in it, it gets rendered as a yellow comment block without text.

**To Reproduce**
1. Write some code that includes a /* blockcomment */
2. Use the renderer to make it into block
3. The comment is empty

**Expected behavior**
I should show the text in the comment

**Screenshots**
Code:
```
/**
 * Detta är ett program som är gjort för att testa hur man skriver kommentar i kod
 */
// Den här raden visar en text på skärmen
basic.showString("Hello!")
// Här visas ett hjärta
basic.showIcon(IconNames.Heart)
// Här visas en (ganska abstrakt) ko
basic.showIcon(IconNames.Cow)
```

Result:
![image](https://user-images.githubusercontent.com/5718354/50393628-c464cb80-0757-11e9-8104-f0ad0b22c950.png)
See this page for live example: http://mermicrobit.se/lar-dig-mer/kommentar/

Expected behavior:
![image](https://user-images.githubusercontent.com/5718354/50393620-b3b45580-0757-11e9-8ded-276c37cff18c.png)

**Additional context**
I'm using https://makecode.microbit.org/beta--docs?render=1

**Comment by abchatra** [comment]
Fixed
