### ISSUE TITLE
Web USB system restart required to make functional (Linux Mint)

### ISSUE THREAD

**Issue by linker3000** [Microsoft/pxt-microbit#1763]
**Describe the bug**
Web USB failed to detect then flash the micro:bit until after the system had been rebooted. Possible bug to resolve, or need to update (Linux) documentation.

**To Reproduce**

1. Confirm firmware is at a supported version (beta program email said 0247, beta testing Web page at https://support.microbit.org/support/solutions/articles/19000084059-beta-testing-web-usb says 0250 - I used the latter)
2. Visit beta MakeCode page (https://makecode.microbit.org/beta#editor) and try to pair device - nothing is detected.
3. Follow Linux troubleshooting guidelines on beta testing Web page to create udev rules file, add user to plugdev group (I received "user is already a member...") and reload udev rules - still no device detected. 
4. Logout user and try again - still no device detected.
5. Restart computer and try again - device detected and pairing successful.
6. Create test application (On start, show some LEDs) and try to download it. micro:bit rear LED flickers until download times out (see screenshot). This is possibly expected behaviour (from the Linux troubleshooting notes).
7. Manually download test application - works fine.
8. Try direct download button - works fine.
9. Disconnect micro:bit, reconnect micro:bit, pair device, direct download still working.

**Expected behavior**
* Micro:bit should be detected after udev rules/group change/rules reload  ..OR.. instructions need revising to recommend a system restart.
* Recommend that the likely need to perform a manual .hex app download first be more prominent/highlight the error (as per screenshot) 

**Screenshots**
![screenshot from 2018-12-27 15-41-40](https://user-images.githubusercontent.com/19429471/50486721-1bd29800-09f3-11e9-8b34-29ae13e3d720.png)

**Desktop:**
 - OS: Linux Mint 19.1 Cinnamon
 - Browser: Chrome 
 - Version: 71.0.3578.98 (Official Build) (64-bit)

**Additional context**
`uname -a: Linux nigel-Aspire-ES1-512 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

[DETAILS.TXT](https://github.com/Microsoft/pxt-microbit/files/2712882/DETAILS.TXT)

**Comment by abchatra** [comment]
Do you have same connection issue when you try  https://python.microbit.org/v/beta? Click on Flash to activate WebUSB.

If the answer is yes, this should be filed on microbit foundation as the issue is with hardware itself.
