### ISSUE TITLE
The block for blank text looks like space

### ISSUE THREAD

**Issue by rhubarbdog** [microsoft/pxt-microbit#1764]
**Describe the bug**
How do i distinguish between the blank string and a single space both have text block `" "`
surely not blank should be block `""` and space `" "`

**To Reproduce**
<a href="https://makecode.microbit.org/_96Y6KodfiAuA">these blocks</a> show the problem.

**Expected behavior**
The block for blank should be easier to distinguish from single space. both the microbit and simulator diferentiate between blank and space, i just can't see it on the editor

**Desktop (please complete the following information):**
 - OS: Linux minit 18.2
 - Browser mozilla firefox
 - Version 63.0.3

**Comment by abchatra** [comment]
If you double click on the string block it will show the spaces or not

**Comment by rhubarbdog** [comment]
Hi,
Sorry to come back to this but i was using makecode on a touch screen. Your what i see as a work around. Doesn't apply i touch a block i'm editing it.

**Comment by kevinjwalters** [comment]
I'd say this is a bug, I was just about to report this as a new issue but then found this ticket.

The current version of arcade and beta version both show empty string and one space as identical in the block view, see example below. This is _not helpful_ from a teaching point of view! Can you re-open this and address this please?

![makecode-bogusemptystringrepresentationinblocks-20190808](https://user-images.githubusercontent.com/6851309/62714755-14e31d80-b9f7-11e9-9fa1-fb730ea0b7cc.PNG)

Flicking to JavaScript just to show they are set correctly to demonstrate this confusing block representation:

```
game.onUpdate(function () {
    nilspace = ""
    onespace = " "
})
```

**Comment by kevinjwalters** [comment]
Will the fix go into Arcade too?

**Comment by abchatra** [comment]
Yes this fix is likely in pxt. It will go to all editors.

**Comment by kevinjwalters** [comment]
I'm still empty string as `" "` (space between double quotes) in MakeCode Arcade `0.14.46 5.30.6`.

**Comment by woutput** [comment]
Also a single character (here "c") appears as if a space is before it (" c").
Screenshot taken today from https://makecode.microbit.org/#editor in Chrome:

![image](https://user-images.githubusercontent.com/14995512/71784764-72f04d00-2ff7-11ea-9625-5a1ef9ea08ba.png)

**Comment by woutput** [comment]
This issue appears to be the same as #2182

**Comment by riknoll** [comment]
so what is the new design? just move the quotes closer together?

**Comment by abchatra** [comment]
I guess? It does look like there is space before _c_ right?

**Comment by rhubarbdog** [comment]
yes it does mate it worse for "" and " " they look the same
