### ISSUE TITLE
Typo in Rock Paper Scissors Tutorial

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-microbit#1768]
In Step 9, the instructions are: "Click the + button again to add an else if section. Now, add a conditional block for hand = 1 to the condition in else if. Since hand can only be 1, 2, or 3, your code is covering all possible cases!"

The condition should be **hand = 2**.  And it's a comparison block they're using.  So I would replace this with "Now, add a comparison block for hand = 2..."

**Comment by ganicke** [comment]
Yea, I think @microbit-mark caught this one a while ago:

https://github.com/Microsoft/pxt-microbit/commit/b3be98f04696bec3d1df3ab6d133920ba282e15c#diff-ce5bc0b4e4e2dc3c7bec3ab702dfef61

**Comment by abchatra** [comment]
fixed
