### ISSUE TITLE
ShowString after addScore is not showing the string

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt-microbit#177]
When running this code, the string "WINS:" does not show. It seems to happen due to the "addScore" because if you take out the addScore part and just show a set number in the "showNumber" it works fine.

Repro:
input.onButtonPressed(Button.A, () => {
    game.addScore(1)
    basic.showString("WINS:")
    basic.showNumber(game.score())
})

** Notice - doesn't show "WINS:"

**Comment by abchatra** [comment]
This still repros.

**Comment by abchatra** [comment]
Ported to pxt repo: https://github.com/Microsoft/pxt/issues/552
