### ISSUE TITLE
'Duplicate' in 'more' (gear) options

### ISSUE THREAD

**Issue by HyperDuino** [Microsoft/pxt-microbit#1770]
There isn't currently a clear way to make a copy of a project.  Suggest adding 'Duplicate project' to the menu of the gear (more) icon: 

![image](https://user-images.githubusercontent.com/13832091/50540413-2a7d9400-0b46-11e9-8c07-60ad0a3c2c19.png)

Result would be duplicating the project with the current name + copy.

This would save a lot of time when starting a new project that needed extensions.  Just duplicate, delete all blocks, and proceed, rather than new, search, add extension1, search, extension2, etc.

**Comment by microbit-mark** [comment]
relates to #1772

**Comment by abchatra** [comment]
Fixed in beta.
