### ISSUE TITLE
Update docs to use the reporter blocks (For, For element)

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-microbit#1771]
Need to update the blocks in the documentation to use the red pull-out reporter variable blocks (instead of the drop-down menu).

https://makecode.microbit.org/blocks/loops
https://makecode.microbit.org/blocks/loops/for-of

**Comment by ganicke** [comment]
Hey @riknoll - the replaceable variable type isn't used in the block render for  \`\`\`cards and \`\`\`namespaces. The doc render is using a different block style for these?

Blocks in \`\`\`cards
![image](https://user-images.githubusercontent.com/27789908/51332837-539c9080-1a31-11e9-9fa6-05ab6141fadc.png)

Blocks in \`\`\`blocks

![image](https://user-images.githubusercontent.com/27789908/51332947-95c5d200-1a31-11e9-823b-5e278d095663.png)

**Comment by pelikhan** [comment]
Fixed.
