### ISSUE TITLE
Feature: Allow versioning of projects

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1772]
microbit-support: 19198

**Is your feature request related to a problem? Please describe.**
When altering a project name and clicking save the exisiting project is overwritten.

![screen recording 2019-01-02 at 01 32 pm](https://user-images.githubusercontent.com/31242877/50594140-414c1f80-0e93-11e9-9dad-a82de0c70103.gif)
 

**Describe the solution you'd like**
If you want to save different versions of your project it would be handy to have an option to save a  new version or overwrite the exisiting program.

**Describe alternatives you've considered**
Versioning is done by downloading the file and renaming on local machine.

**Additional context**
None

**Comment by abchatra** [comment]
We don't plan to add this feature in near future. Wont' fix.
