### ISSUE TITLE
Sample code needs to work on both Blocks and JavaScript

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt-microbit#178]
We have several parts of Help Sample code or Projects that do not work on Blocks. Either the compiler needs to be fixed or the sample code needs to be changed to work. Simple Help Samples should not be breaking.

Code that doesn't convert to Blocks:
- [ ] Rock Paper Scissors in Help
- [x] Projects -> Love Meter
- [ ] Projects -> Compass
- [x] Projects -> Hack Headphones
- [x] Projects -> Banana Keyboard
- [x] Projects -> Watch

**Comment by microsoftsam** [comment]
I've checked the projects listed above and they seem to be working just fine. 
If this still repros can we get a link / screenshot.

**Comment by darrenge** [comment]
Rock Paper Scissors still fails
input.onGesture(Gesture.Shake, () => {
    let weapon = Math.random(3)
    if (weapon == 0) {
        basic.showLeds(`
            # # # # #
            # . . . #
            # . . . #
            # . . . #
            # # # # #
            `)

    } else if (weapon == 1) {
        basic.showLeds(`
            . . . . .
            . # # # .
            . # # # .
            . # # # .
            . . . . .
            `)
    } else {
        basic.showLeds(`
            # # . . #
            # # . # .
            . . # . .
            # # . # .
            # # . . #
            `)
    }
})

**Comment by darrenge** [comment]
Compass still fails:
basic.forever(() => {
    let degrees = input.compassHeading();
    if (degrees < 45) {
        basic.showString("N");
    } else if (degrees < 135) {
        basic.showString("E");
    } else if (degrees < 225) {
        basic.showString("S");
    } else {
        basic.showString("W");
    }
});

**Comment by pelikhan** [comment]
The compass issue is due to our handling of local variables. The local variable gets moved to a global var. For now, we should just fix those docs.

**Comment by microsoftsam** [comment]
The docs are fixed, this should be a new issue in the conversion between blocks and Javascript, which improperly introduces global variables.

**Comment by darrenge** [comment]
Handled in issue #149
