### ISSUE TITLE
rounding issue when using i2c device

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#1781]
micro:bit support 19711

**Describe the bug**
 I've been experimenting with an I2C device. I get good comms but when I get a final number and attempt to round to 2dp it does not work on real Microbit, I get 15dp's although on 

**To Reproduce**
1. Go to 'https://makecode.microbit.org/_UwF0sDTLdcgj'
2. See 0.42 in simulator
3. Download to micro:bit
4. see 0.4200000000000001 on display

**Expected behavior**
hardware behaves as simulator does

Mac 10.14.2
Firefox 64

**Comment by microbit-mark** [comment]
@abchatra can you check this one out?

**Comment by abchatra** [comment]
Floating point math can't be accurately done in board or simulator. You will see these deviations.

**Comment by microbit-mark** [comment]
@abchatra can you explain this a bit more? What do you mean by it can't be accurately done?

**Comment by martinwork** [comment]
On both simulator and hardware, the result of c * 100 displays as 42 and compares as equal to a.

The problem occurs in toString(),

Try c = 0.123. Simulator says 0.12, hardware says 0.11999999999999999. showNumber does rounding. Using s = d.toString() and showString(s), simulator says 0.123, hardware says 0.122999etc.

**Comment by whaleygeek** [comment]
Perhaps add an optional 'precision' parameter to the conversion (a bit like the optional delay parameter in showString and the precision parameter in C sprintf??)

Floating point precision will always be a problem unless display formats are supported, due to the way floating point numbers are represented internally as a series of binary fractions. The issue here is display formatting.

**Comment by nielsswinkels** [comment]
Any progress on this? I had a question coming from a teacher that ran into this, and it is very confusing that it works differently in the simulator than in real.

**Comment by MKleinSB** [comment]
Even by simply using 

basic.showNumber(0.344) it shows 0.34000000000000003 on the microbit

same with 0.39, 0.49 , 0.59, 0.69, 0.79, 0.89, 0.99
1.39, 1.49 ....  works correct!

**Comment by martinwork** [comment]
See https://github.com/microsoft/pxt-microbit/issues/2192#issuecomment-515121326

**Comment by microbit-mark** [comment]
Another user reports this disparity between sim and hardware. It's confusing for users @abchatra. Can you take another look? There are several issues linked from this ticket that require a fix.

**Comment by pelikhan** [comment]
Fixed in beta.
