### ISSUE TITLE
Light level is always set at 255 when output over serial on device

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1786]
**Describe the bug**
When outputting light level over serial, the initial level appears as 255, this is not the case in the sim.

**To Reproduce**
Use this code, flash to micro:bit, open serial terminal, press A button, see '255'. Reset micro:bit to confirm
![image](https://user-images.githubusercontent.com/31242877/51026278-0c705480-1586-11e9-955b-bf125088051a.png)

**Expected behavior**
Light level should be correct calculation.

**Comment by microbit-mark** [comment]
^ @abchatra

**Comment by pelikhan** [comment]
You need to add a new line other you are going to get 12312312312312321321...

**Comment by martinwork** [comment]
@microbit-mark try this: https://makecode.microbit.org/_Wej7H3hCv147
Light level seems to read 255 at first. A read and small delay in on start gives it time to settle.

**Comment by microbit-mark** [comment]
That would work @martinwork, but it's not intuitive. @pelikhan is it the case that we have to trigger an initial reading of the light-level to read a true value on an event like a button press?

**Comment by pelikhan** [comment]
Went parse numbers line by line, serial write number does not introduce a lien so digits pile up

**Comment by pelikhan** [comment]
By design. You need a new line to guarantee correc tparing.

**Comment by martinwork** [comment]
I wrote a C++ sample which sends time (ms) and light level data. The data below, collected with TeraTerm, shows that the reading from MicroBitDisplay::readLightLevel takes about 80ms to settle after the first read.

The first read only creates the light sensor, ready to start reading from the 3 LED channels one at a time, synchronised with the display. The value is an average of the channels. You can see the value change every 30ms when each channel is read. Sensors needing a settle time after power up is a common problem.

t:180
v:255
t:190
v:255
t:200
v:255
t:210
v:222
t:220
v:222
t:230
v:222
t:240
v:103
t:250
v:103
t:260
v:0

**Comment by pelikhan** [comment]
We could handle first read differently but i fell this is really a DAL issue.

**Comment by pelikhan** [comment]
@microbit-mark @martinwork opened a DAL issue on this: https://github.com/lancaster-university/microbit-dal/issues/426
