### ISSUE TITLE
Offline app has small initial window size that cuts off tutorials

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microsoft/pxt-microbit#1788]
**Describe the bug**
The offline MakeCode app always seems to open with an 800x600 window size. If you resize the window it doesn't remember it on restart.

This size cuts off just below the projects list, so a user might not notice that there are tutorials. This is worse on mac where the scrollbar is hidden by default.

As MakeCode benefits from a lot of screen space perhaps it should start maximised by default?

**Desktop (please complete the following information):**
 - OS: mac
- Version: 1.2.13 makecode.microbit.org version from about modal.

**Comment by microbit-mark** [comment]
Are you able to progress this one @abchatra

**Comment by pelikhan** [comment]
Kids are not good at maximizing windows, we should always start maximized.

**Comment by jwunderl** [comment]
Will be fixed with the next release
