### ISSUE TITLE
Watch Challenges goes to Rock Paper Scissors instead of the challenges code

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt-microbit#179]
At the end of the Watch Project, there is a link that says "Go to Challenges". Normally that goes to the code of that specific project. For the Watch Project, that link is going to Rock Paper Scissors project.

Repro:
* Go to Watch Project
* Go to bottom ... click on "Challenges" link
** Notice - brings you to Rock Paper Scissors project ... it should bring you to the section where you get the code for the Watch part

**Comment by microsoftsam** [comment]
There is no Watch Project challenges, and that's the last project in the list, so no project to go to "Next". 
I'll remove "Go to Challenges" link.
