### ISSUE TITLE
Generic compilation error when accessing an array of 100 large numbers.

### ISSUE THREAD

**Issue by nbogie** [microsoft/pxt-microbit#1793]
**Describe the bug**

Compiling a program which accesses an array of 100 generally large* integers fails with no detailed error message, only "Compilation failed, please check your code for errors."  * Largest number is 260604669.  

A better error message would be useful, if we're hitting a known limitation here.

The issue goes away if we modify the code to use a much larger array (1000) of smaller integers (e.g. 1 - 1000).

**To Reproduce**

* visit https://makecode.microbit.org/_XrCgb8XfR4VL or make a new project with the code below.
* press download
* observe compilation error
* note the js runs fine in the simulator.

Code:
```
const myNumbers = [
    1, 185, 24603, 92102485, 19655237, 216566685, 170063685, 25,
    4466, 3722, 85189717, 34858021, 6274, 34636837, 129, 25795,
    119155, 7954, 186771, 87435, 2353764, 79291, 79219, 32011,
    87379, 120211, 81, 6786, 145310757, 86592085, 34687629, 21771,
    158839157, 248307, 87547, 143731, 119291, 144891, 9723, 110963,
    255227, 147339, 127299, 222459, 135419, 260604669, 8159996, 119155,
    17915, 252275, 214523, 79251, 16139, 258299, 63547, 65067069,
    222427, 64571, 161227, 4602, 197659, 8074, 49459, 135299,
    522, 234563, 70907, 169027, 259139, 170595, 48675, 236195,
    197883, 209, 7554, 166139, 4218, 202573029, 197859, 70723,
    35571, 248355, 34019, 6818, 171555, 233571, 102499, 104927333,
    166051, 121011, 5842, 147235, 249, 40843, 35684901];

basic.showNumber(myNumbers[0]);
```

**Expected behaviour**
Either the program should compile correctly, or an error message should be output identifying the problem.

**Actual behaviour**
* "Compilation failed, please check your code for errors."  
* built/output.txt says "Everything seems fine!"
* Browser's js console is empty

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome 71.0.3578.98

**Additional context**

This is an attempt to reduce [WC Leung's issue from Slack #makecode](https://microbit-community.slack.com/archives/C226FGXQX/p1547558194073600) today.

**Comment by CleoQc** [comment]
build/output says:
`error: main.ts(1,1): error TS9200:   -> Line 66 ('    ldr r1, _ldlit_2      ; WAS: ldlit r1, 184204971'), error: assembly error
   Maybe: ldr   R0-7, [R0-7, #0-124] (expecting [ at '_ldlit_2')
   Maybe: ldr   R0-7, [R0-7, R0-7] (expecting [ at '_ldlit_2')
   Maybe: ldr   R0-7, [pc, #0-1020] (expecting [ at '_ldlit_2')
   Maybe: ldr   R0-7, LABEL (argument out of range or mis-aligned at '_ldlit_2')
   Maybe: ldr   R0-7, [sp, #0-1020] (expecting [ at '_ldlit_2')
   Maybe: ldr   R0-7, [sp] (expecting [ at '_ldlit_2')`

if you open it before hitting the download button.

**Comment by abchatra** [comment]
Fixed in /beta
