### ISSUE TITLE
The Simulator background pattern is missing

### ISSUE THREAD

**Issue by JoshuaLowe1002** [Microsoft/pxt-microbit#1795]
Hi,

The simulator in Makecode normally has a micro:bit pattern background but it seems to be missing.
Taking a further look into it with the developer tools shows that this file is actually missing.

![image](https://user-images.githubusercontent.com/25752941/51351004-8ed6a800-1aa1-11e9-916f-89bd386e0a28.png)
![image](https://user-images.githubusercontent.com/25752941/51351009-926a2f00-1aa1-11e9-9f89-07732eb8c5a8.png)

**Comment by jaustin** [comment]
The image looks like it was coming from https://az742082.vo.msecnd.net/pub/psopafpj which got terminated as part of .co.uk. (https://support.microbit.org/support/solutions/articles/19000093355-switching-off-microbit-co-uk-december-31-2018)

@pelikhan and @abchatra is there any reason you weren't serving this image directly?

**Comment by microbit-rosslowe** [comment]
Original image:

![psopafpj](https://user-images.githubusercontent.com/30410608/52795902-ac7c3a80-306a-11e9-96f2-37803e7dd6d0.png)

**Comment by abchatra** [comment]
@microbit-rosslowe @jaustin Can you share the original image? We should fix this on our end. It probably stale code which was pointing to that location. I searched in the microbit repo and this is the only instance.
If you share the image as is, I will fix the issue on our end.

**Comment by jaustin** [comment]
@abchatra the image Ross posted is, as far as I can tell, the original image (resolution, format, etc same as psopafpj)

**Comment by microbit-mark** [comment]
See https://web.archive.org/web/20181203105726/https://az742082.vo.msecnd.net/pub/psopafpj for an index of it
