### ISSUE TITLE
Opening project with deleted local dependencies crashes MakeCode

### ISSUE THREAD

**Issue by lwchkg** [microsoft/pxt-microbit#1797]
**Describe the bug**
As titled.

**To Reproduce**
1. Browse https://makecode.microbit.org/
2. Start a new local extension. (Use sample code in tutorials.)
3. Start a new project. Add blocks that refers that local extension.
4. Delete the local extension.
5. Open the project created in step (2).

**Expected behavior**
The dialog in https://github.com/Microsoft/pxt/pull/4723#issuecomment-424156110 should appear, prompting for fixes for that missing dependency.

**Actual behavior**
App crashed.

**Screenshots**
![firefox_2019-01-19_22-02-20](https://user-images.githubusercontent.com/4113719/51427959-c62b8d00-1c38-11e9-976a-0b8e14ac726f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Firefox]
 - Version [e.g. 64.0.2]

- makecode.microbit.org version:  1.2.13
- Microsoft MakeCode version:  4.4.7
- microbit runtime version:  v2.1.1

**Comment by lwchkg** [comment]
@riknoll Can you have a look at this? Thanks!

**Comment by abchatra** [comment]
Closing more than an year old bugs. If this still reproduces please let me know.
