### ISSUE TITLE
Feature request: show values on data waveform in console

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#1799]
micro:bit support: 19882
**Is your feature request related to a problem? Please describe.**
When logging console data in the simulator, it would be useful to show written values on the waves peaks on mouseover.

**Describe the solution you'd like**
on mouseover show the data value eg where the circle is on this image.

![image](https://user-images.githubusercontent.com/31242877/51468450-e9545a80-1d66-11e9-91ba-ca6343fe49d0.png)

**Comment by microbit-mark** [comment]
support ticket: 02430

Another related request to show y-axis for data to show thresholds. eg

![screenshot 2019-02-01 at 9 48 43 am](https://user-images.githubusercontent.com/31242877/52197873-03a73180-2859-11e9-9e79-c62856cd1561.png)

**Comment by microbit-mark** [comment]
@abchatra @pelikhan ^

**Comment by microbit-mark** [comment]
pinging this one again

**Comment by microbit-mark** [comment]
Added enhancement label. Is this something we can add in @abchatra? It would be good to get back to the users.

**Comment by abchatra** [comment]
We already show the data time if you hover over.

**Comment by microbit-mark** [comment]
Do you have ann example? I don't see anything on hover

![screen recording 2019-03-05 at 03 42 pm](https://user-images.githubusercontent.com/31242877/53817526-82c57d80-3f5d-11e9-8e6f-6fb995dc3e3d.gif)

**Comment by abchatra** [comment]
Can you share your code?  

Try following it shows the tooltips on hover.
```javascript
basic.forever(function () {
    serial.writeNumber(input.acceleration(Dimension.X))
    serial.writeLine("")
})
```

**Comment by microbit-mark** [comment]
I still don't see waveform data on hover using that code. If I run that and go to console view then pause the console and mouseover the peaks and troughs (as in above gif) should I be seeing values? Tried in Chrome and Firefox on mac

**Comment by microbit-mark** [comment]
On windows chrome I see the values as i hover, so maybe this is an OS bug 
![screen recording 2019-03-05 at 04 43 pm](https://user-images.githubusercontent.com/31242877/53821514-dc31aa80-3f65-11e9-9af8-e7852eaa92f9.gif)

**Comment by jwunderl** [comment]
Working for me on osx 10.14.4, same as the gif above on safari / firefox / chrome. It looks like the issue might just be not showing the tool tip when the serial wave is paused, as in the second to last gif - 

![2019-05-28 21 22 49](https://user-images.githubusercontent.com/5615930/58529247-f824a100-818e-11e9-9b61-f9e2f750ffc8.gif)

**Comment by abchatra** [comment]
Fixed in latest safari
