### ISSUE TITLE
How to create an electron app from pxt-microbit local server

### ISSUE THREAD

**Issue by dmosyash** [Microsoft/pxt-microbit#1800]
I have setup a local server for pxt-microbit by following the documentation given at Readme file.
There is one electron folder having 2 files product.json and release.json, but I don't know what to do to create an electron app for windows

**Comment by abchatra** [comment]
This is not a supported feature.

**Comment by dmosyash** [comment]
Hello abchatra,
May I ask what is the use of that electron folder with 2 json files in it in the bundle.
