### ISSUE TITLE
Simulator and physical board get different result for idiv

### ISSUE THREAD

**Issue by xuefengedu** [Microsoft/pxt-microbit#1803]
**Describe the bug**
Simulator and physical board get different result

**To Reproduce**
Run `basic.showNumber(Math.idiv(4.5, 1.5))` in makecode editor javascript tab
Simulator result is 3
micro:bit physical board is 4

**Expected behavior**
Simulator result should be 4 to be same with micro:bit physical board

**Screenshots**

![simulator](https://user-images.githubusercontent.com/40351998/51783866-78a0aa00-217b-11e9-877e-45f295b1aee9.JPG)

core.cpp:
```
//%
int imul(int x, int y) {
    return x * y;
}

//%
int idiv(int x, int y) {
    return x / y;
}
} // namespace Math_
```

**Desktop (please complete the following information):**
 - OS: [Win7]
 - Browser [chrome]

**Additional context**
I am investigating to fix it.

**Comment by xuefengedu** [comment]
@riknoll do you know how to fix it?
I saw you done this feature before:
**Issue:**
#1062
**PRs:**
https://github.com/Microsoft/pxt/pull/4592/files
#1072

**Comment by xuefengedu** [comment]
I found `idiv` in 3 places about simulator:
https://github.com/Microsoft/pxt/blob/a8485c3bbd6d8c24cc3080c3ca1d6400263ad27a/pxtsim/libgeneric.ts#L212

https://github.com/Microsoft/pxt/blob/46fa060a90f782443d1ac71c61b775b526f79b46/libs/pxt-common/pxt-core.d.ts#L520

https://github.com/Microsoft/pxt/blob/46fa060a90f782443d1ac71c61b775b526f79b46/docs/static/playground/pxt-common/pxt-core.d.js#L520

**Comment by xuefengedu** [comment]
It seems this one is the problem one: 
**simulator side:**
https://github.com/Microsoft/pxt/blob/a8485c3bbd6d8c24cc3080c3ca1d6400263ad27a/pxtsim/libgeneric.ts#L212

```
export function idiv(x: number, y: number) {
            return (x / y) >> 0
        }
```
**core.cpp:**
```
//%
int imul(int x, int y) {
    return x * y;
}

//%
int idiv(int x, int y) {
    return x / y;
}
} // namespace Math_
```

**Comment by xuefengedu** [comment]
on simulator, `4.5/1.5=3`
on phycial board, `4.5` and `1.5` will convert to int, and become `4` and `1`, then `4/1=4`
so the difference happen.

**Comment by xuefengedu** [comment]
let me summarize:
**it converts inputs to integer, then do mul/div operation:**
`Math.imul(4.5, 1.5)` simulator side, result is 4
`Math.imul(4.5, 1.5)` board side, result is 4
`Math.idiv(4.5, 1.5)` board side, result is 4
**it do idiv operation without converting:**
`Math.idiv(4.5, 1.5)` simulator side, result is 3

Fix option 1:
If we want to keep `imul` 's simulator behavior: "it convert inputs to integer, then do mul operation." so fix `idiv` need to on simulator side.  https://github.com/Microsoft/pxt/blob/a8485c3bbd6d8c24cc3080c3ca1d6400263ad27a/pxtsim/libgeneric.ts#L212

Fix option 2:
If we want to keep `idiv` on simulator side(it just do divide without converting inputs), then we have to modify current core.cpp implementation of `imul` and `idiv` and also `imul` on simulator side(since now it convert inputs to integer first, then do mul. current simulator with `Math.imul(4.5, 1.5)` result is 4).

**Comment by xuefengedu** [comment]
@riknoll thanks for fixing it! do you know when will it affect on makecode.microbit.org? thanks.

**Comment by riknoll** [comment]
It will be in the next release, but I don't know when that will be yet. Hopefully within a few weeks.

**Comment by xuefengedu** [comment]
@riknoll thanks for sharing!
