### ISSUE TITLE
Feature: Allow tutors to hide tutorials from home screen

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1805]
micro:bit support: 20306
**Is your feature request related to a problem? Please describe.**
When I set makecode assignments for the students, it's too easy for them to refer to the tutorial code and copy and paste. 

**Describe the solution you'd like**
Could tutors hide the tutorials in a particular mode.

**Describe alternatives you've considered**
These don't appear when working offline, but it's not feasible to take our computers offline as it would cause issues for other teachers/IT in the school.

**Additional context**
From a discussion at BETT2019

**Comment by microbit-mark** [comment]
Perhaps they mean Projects which link out to the reference docs eg  https://makecode.microbit.org/projects/wallet/code

**Comment by xuefengedu** [comment]
I think they mean the first page of http://makecode.microbit.org, it shows new project button and some tutorial buttons there, but when off-line, it cannot download the tutorial.code from internet, so they meet problem when click the tutorial button in offline mode

**Comment by xuefengedu** [comment]
@abchatra they can switch to javascript and then they can copy, I just guess. :D

**Comment by microbit-mark** [comment]
I'm not sure of the answer to this, perhaps it's inevitable that if you set assignments based on freely available online projects with walkthroughs of code, students will copy this code.

**Comment by pelikhan** [comment]
The plagiarism issue is the same as today where all tutorials are already publically available.
I am looking into this feature.
