### ISSUE TITLE
basic.showNumber(1.14286) shows 1.14 on simulator

### ISSUE THREAD

**Issue by xuefengedu** [Microsoft/pxt-microbit#1806]
**Describe the bug**
basic.showNumber(1.14286) shows 1.14 on simulator

**To Reproduce**
basic.showNumber(1.14286) in javascript shows 1.14 on simulator

**Expected behavior**
it seems should show 1.14286? or others?

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser [chrome]

**Additional context**
https://makecode.microbit.org/#editor

**Comment by xuefengedu** [comment]
just see the code right now:
https://github.com/Microsoft/pxt-microbit/blob/master/libs/core/basic.ts#L13

**Comment by abchatra** [comment]
We round to 2 digits, otherwise it is very hard to see the scrolling number
