### ISSUE TITLE
Backing home page, it can't back to location of opened tutorial

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1811]
**Describe the bug**
Backing home page, it can't back to location of opened tutorial

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta
2. Scroll down to "Blocks To JavaScript"
3. Open one tutorial "Starter Blocks" 
4. Click "Home" to back to home page again

**Expected behavior**
Backing home page, it should back to location of opened tutorial

**Actual behavior**
Backing home page, it can't back to location of opened tutorial
![issue020201](https://user-images.githubusercontent.com/23466737/52161274-b8c4d700-26fd-11e9-9e3f-762cce5a6494.gif)

**Additional context**
- OS: Windows
- Browser: Edge, Chrome, Firefox, IE

**Comment by abchatra** [comment]
P3 won't fix
