### ISSUE TITLE
There is no naming convention for project name

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1812]
**Describe the bug**
Backing home page, it can't back to location of opened tutorial

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "Home" and input a project name in the text box

**Expected behavior**
There should have a naming convention for project name

**Actual behavior**
There is no naming convention for project name
![issue020202](https://user-images.githubusercontent.com/23466737/52161775-71dadf80-2705-11e9-8617-32f02b1d9920.PNG)

**Additional context**
- OS: Windows
- Browser: Edge, Chrome, Firefox, IE

**Comment by abchatra** [comment]
P3 won't fix
