### ISSUE TITLE
Ability to import a shared tutorial in the same way that a shared project can be

### ISSUE THREAD

**Issue by jonathanhogg** [microsoft/pxt-microbit#1817]
I am working on designing workshops that involve making objects out of scrap materials and then animating these with micro:bit boards, servos and LEDs. Part of the workshop involves writing simple code for the micro:bit.

It would be great to be able to follow a tutorial structure in the MakeCode editor for producing this code, but the tutorials that this would involve would not be the kind of standalone tutorials that would be usefully submitted to the core project. It would be good to be able to write our own tutorials, host these on GitHub and then import them into the editor with a URL.

Being able to import tutorials would also allow us to iterate them quickly as the workshops are designed and refined, without having to rely on core developers to merge our work or placing a burden on translation and QA teams.

At the moment we are planning to use shared projects instead that have the basic blocks and imported packages, and then use printed handouts that explain what to do next.

**Comment by pelikhan** [comment]
Do you have an example of such repository?

**Comment by jonathanhogg** [comment]
I haven't thought about what one might look like to be honest as I'm not familiar with the MakeCode codebase and what would be easiest to implement.

Perhaps something like a project containing a `pxt.json` file that references a `tutorial.md` file along with whatever additional resources (like images) that are required.

Using the `pxt.json` structure might be a useful way to be able to specify additional project settings/dependencies and provide `.ts` files with custom blocks – although I'm aware that you already have a special Markdown syntax for dependencies.

**Comment by jonathanhogg** [comment]
Ah. I see now that you are already ploughing on with implementing! I'm happy to create an example repo if you have a structure in mind from what you've already done.

**Comment by pelikhan** [comment]
All projects have a README.md by default so that is where it will be. See the docs in the PR

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jonathanhogg** [comment]
Gotcha!

Could there be a way to open a tutorial URL via the `Import` button? I don't think there's a way to navigate to a specific custom URL from within the iPad micro:bit app, which embeds a browser component to access MakeCode.

In fact, could one just add a flag to the `pxt.json` file like `isTutorial: true` and then import via the normal button?

**Comment by pelikhan** [comment]
Right need to think about the import story.

**Comment by abchatra** [comment]
Custom tutorial implemented. Keeping this alive for import story.

**Comment by abchatra** [comment]
Custom tutorial is implemented.
