### ISSUE TITLE
Radio not working with receive / send string

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#182]
here is simple example code that works perfectly on the simulator but not on the devices. The mbit devices have been calibrated by 'drawing a circle' before testing the BLE for compass. please review. 

```
let cOMPASS = 0;
basic.forever(() => {
    cOMPASS = input.compassHeading();
    if (cOMPASS < 45) {
        radio.sendString("N");
    } else {
        basic.showLeds(`
            . # . # .
            . # # # .
            # # # # #
            . # # # .
            . # . # .
            `);
    }
});
radio.onDataReceived(() => {
    basic.showString(radio.receiveString());
    led.stopAnimation();
});

```

**Comment by bluetooth-mdw** [comment]
This code is not using BLE i.e. Bluetooth. It's using the Radio package. This is not Bluetooth, it's a proprietary wireless protocol that uses the same radio hardware as Bluetooth but that's all. The remainder of the Bluetooth stack is not involved.

**Comment by abchatra** [comment]
@riknoll Does this repro for you? If not close.

**Comment by abchatra** [comment]
radio.sendString("N"); is too short and is always overwritten by the forever loop led animation. led.stopAnimation stops only the current animation . Try sending the larger strings which should that issue goes away.
