### ISSUE TITLE
Docs: /reference/bluetooth/bluetooth-pairing.md is outdated

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#1821]
**Describe the bug**
The text and videos [in this page](https://makecode.microbit.org/reference/bluetooth/bluetooth-pairing) relate to a previous pairing process and we want to encourage users to use the official apps and advice here:
https://microbit.org/guide/mobile/
https://support.microbit.org/a/solutions/articles/19000051025
https://support.microbit.org/a/solutions/articles/19000080745

Suggest updating or removing this page

**Comment by pelikhan** [comment]
@microbit-mark where are the Windows instructions?

**Comment by abchatra** [comment]
@ganicke help please.

**Comment by ganicke** [comment]
Sure, I'll help "re-pair" the page.

**Comment by ganicke** [comment]
BT pairing page updated in #1924
