### ISSUE TITLE
Strange console logs when using serial write

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1823]
**Describe the bug**
When using webUSB to output device data, the console view seems to implement multiple graph windows.

![screen recording 2019-02-07 at 03 26 pm](https://user-images.githubusercontent.com/31242877/52422212-8a743c80-2aed-11e9-9cb2-6acdd8d20a59.gif)

**To Reproduce**
With a sensor connected to pin0 
1. Go to 'https://makecode.microbit.org/_4D2RX5KAgDaq'
2. Pair micro:bit and download
3. Switch to console view and see issue.

Doesn't  reproduce outside of this example, eg setting read value as a variable first
https://makecode.microbit.org/_a42HWDezLaos

**Expected behavior**
One log for device and one for simulator

**Desktop (please complete the following information):**
 - OS: Mac 10.14
 - Browser: Chrome 71

**Smartphone (please complete the following information):**

**Additional context**

**Comment by microbit-mark** [comment]
^ @abchatra

**Comment by abchatra** [comment]
@darzu Can you take a look at this?
