### ISSUE TITLE
Radio docs: Older APIs discoverable by Google, newer API docs are less clear

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#1827]
**Describe the bug**
Consider someone making an example that attempts to use the 'received packet <signal strength>' block... They need to know the range of numbers this block is going to return.

The existing docs aren't clear on that:
<img width="360" alt="image" src="https://user-images.githubusercontent.com/147113/52655796-f6d7ad00-2eec-11e9-8cbf-42ab6bd71f60.png">

**To Reproduce**
1. Add the block for `radio.receivedPacket(RadioPacketProperty.SignalStrength)`
2. Right click on the block and choose 'help' (it loads https://makecode.microbit.org/reference/radio/received-packet)

Then compare the answer to the top result for "microbit radio received signal strength", which takes me here:
https://makecode.microbit.org/reference/radio/received-signal-strength
...and more usefully says the range (twice!)
<img width="746" alt="image" src="https://user-images.githubusercontent.com/147113/52656619-a19c9b00-2eee-11e9-9a3e-d0b09e1a2073.png">

However, this page contains a really old/unusual example of using the radio
<img width="514" alt="image" src="https://user-images.githubusercontent.com/147113/52656084-84b39800-2eed-11e9-83e5-205abd9e1afd.png">

If you notice that the API has been deprecated (a small note at the top of the page) and follow the link for the 'newer block' it directs you to:
https://makecode.microbit.org/reference/radio/on-data-packet-received

Which is still not the current way of using the radio, but is not listed as deprecated...

**Expected behavior**
1. The page for the  block (https://makecode.microbit.org/reference/radio/received-packet ) is updated to include ranges for each possible return type
2. https://makecode.microbit.org/reference/radio/ includes a link to https://makecode.microbit.org/reference/radio/received-packet in the list of blocks
3. https://makecode.microbit.org/reference/radio/on-data-packet-received is marked as deprecated if it is, in fact, deprecated?
4. Deprecated APIs are made more clear and harder to find (perhaps tell search engines not to index?)

**Comment by abchatra** [comment]
@ganicke let me know if you need any further information here.

**Comment by ganicke** [comment]
Thanks. I'll go through these. It's likely that there are more of these older/original micro:bit ref pages that need some attention too.

**Comment by abchatra** [comment]
Fixed. @jaustin please verify

**Comment by jaustin** [comment]
Thanks both, this looks fixed to me now! 👍
