### ISSUE TITLE
Toolbox "Arrays" can't be opened and it is empty after switching language to "Sinhala"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1830]
**Describe the bug**
Toolbox "Arrays" can't be opened and it is empty after switching language to "Sinhala"

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "More..." -> "Language" -> choose "Sinhala"
3. Click "Advanced" -> "Arrays"

**Expected behavior**
Toolbox "Arrays" should can be opened
![issue021402](https://user-images.githubusercontent.com/23466737/52768146-91f49200-3067-11e9-816d-1c38353d522a.gif)

**Actual behavior**
Toolbox "Arrays" can't be opened and it is empty after switching language to "Sinhala"
![issue021401](https://user-images.githubusercontent.com/23466737/52767753-6329ec00-3066-11e9-98e3-40d125fd0f9b.gif)

**Additional context**
- OS: Windows (build: 17763.1.amd64fre.rs5_release.180914-1434)
- Browser: Edge, Chrome, Firefox, IE

**Comment by abchatra** [comment]
Good catch

**Comment by pelikhan** [comment]
The issue is that built-in translations are not piped through our translation validator (and the translation is wrong).

**Comment by abchatra** [comment]
Hmm. Someone needs to fix the translation. Why is this issue closed?

**Comment by pelikhan** [comment]
I fixed the translation.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment]
Thanks peli. You are awesome.
