### ISSUE TITLE
"Support" and "Buy" text is not translated after switching language

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1831]
**Describe the bug**
"Support" and "Buy" text is not translated after switching language

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "More..." -> "Language" -> choose "Japanese"
3. Click "Help" -> hover on each items and observe the text

**Expected behavior**
"Support" and "Buy" text should be translated after switching language

**Actual behavior**
"Support" and "Buy" text is not translated after switching language
![issue021403](https://user-images.githubusercontent.com/23466737/52770140-493fd780-306d-11e9-8666-4ce788e585e1.gif)

**Additional context**
- OS: Windows (build: 17763.1.amd64fre.rs5_release.180914-1434)
- Browser: Edge, Chrome, Firefox, IE
- This issue also reproes after switching language to others

**Comment by pelikhan** [comment]
This is just a missing translation.

**Comment by Helen09** [comment]
@pelikhan Will this issue be fixed?
