### ISSUE TITLE
"Serial" can't be shown completely after switching language to "French"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1832]
**Describe the bug**
"Serial" can't be shown completely after switching language to "French"

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "More..." -> "Language" -> choose "French"
3. Click "Advanced" -> observe translated "Serial"

**Expected behavior**
"Serial" should can be shown completely

**Actual behavior**
"Serial" can't be shown completely after switching language to "French"
![issue21404](https://user-images.githubusercontent.com/23466737/52775294-4697af00-307a-11e9-8aa4-7e165c3c165b.PNG)

**Additional context**
- OS: Windows (build: 17763.1.amd64fre.rs5_release.180914-1434)
- Browser: Edge, Chrome, Firefox, IE

**Comment by Helen09** [comment]
This issue only repro on Firefox now

**Comment by pelikhan** [comment]
Fixed.
