### ISSUE TITLE
Toolbox "Text" can't be opened after switching language to "Spanish"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1833]
**Describe the bug**
Toolbox "Text" can't be opened after switching language to "Spanish"

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "More..." -> "Language" -> choose "Spanish"
3. Click "Advanced" -> "Text"

**Expected behavior**
Toolbox "Text" should can be opened
![issue021406](https://user-images.githubusercontent.com/23466737/52776726-2cab9b80-307d-11e9-922a-7c0eaa5a77dc.gif)

**Actual behavior**
Toolbox "Text" can't be opened after switching language to "Spanish"
![issue021405](https://user-images.githubusercontent.com/23466737/52776559-d6d6f380-307c-11e9-9c51-d193e59df319.gif)

**Additional context**
- OS: Windows (build: 17763.1.amd64fre.rs5_release.180914-1434)
- Browser: Edge, Chrome, Firefox, IE

**Comment by pelikhan** [comment]
The translation of charAt changed the order of arguments and uses the % notation.

**Comment by Helen09** [comment]
This bug repro on Edge(44.17763.1.0) and Firefox(65.0.2)

**Comment by pelikhan** [comment]
Fixed.
