### ISSUE TITLE
Simulator shows not normally when zooming out the page 

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#1834]
**Describe the bug**
Simulator shows not normally when zooming out the page 

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Zoom out the window until simulator shows on the left-bottom corner of the page
3. Observe simulator pins

**Expected behavior(Chrome & Firefox)**
Simulator should show normally
![issue21502](https://user-images.githubusercontent.com/23466737/52842416-03047a00-313a-11e9-98e4-766723ecb135.PNG)

**Actual behavior(Edge & IE)**
Simulator shows not normally when zooming out the page 
![issue21501](https://user-images.githubusercontent.com/23466737/52842415-013ab680-313a-11e9-8099-f4cf6ff0a195.PNG)

**Additional context**
- OS: Windows (build: 17763.1.amd64fre.rs5_release.180914-1434)
- Browser: Edge(44.17763.1.0), Chrome(72.0.3626.109), Firefox(65.0.1), IE(11.316.17763.0)

**Comment by Helen09** [comment]
This bug still repro, when zooming out site on Edge, the simulator doesn't show
![Cap1112ture](https://user-images.githubusercontent.com/23466737/57912751-b6a61300-78bd-11e9-95ce-d6c4025cf240.PNG)

**Comment by abchatra** [comment]
Won't Fix old bugs on Edge or IE.
