### ISSUE TITLE
Link "Learn more" is overlapped with the instruction text

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1835]
**Describe the bug**
Link "Learn more" is overlapped with the instruction text

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "More..." -> "Extensions"
3. Scroll down to the bottom of the page and observe the last extension

**Expected behavior**
Link "Learn more" should not overlap with the instruction text

**Actual behavior**
Link "Learn more" is overlapped with the instruction text
![issue021502](https://user-images.githubusercontent.com/23466737/52843415-fcc3cd00-313c-11e9-9d76-504ab94aebe8.gif)

**Additional context**
- OS: Windows (build: 17763.1.amd64fre.rs5_release.180914-1434)
- Browser: Edge, Chrome, Firefox, IE

**Comment by pelikhan** [comment]
We need to trim the description as needed.
