### ISSUE TITLE
Simulator does not load offline (Safari)

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#1836]
**Describe the bug**

**To Reproduce**
Open MakeCode editor in Safari when online.
Go offline and refresh the page
Simulator does not load

**Expected behavior**
Simulator loads as with Chrome

**Screenshots**
![screen recording 2019-02-15 at 10 00 am](https://user-images.githubusercontent.com/31242877/52849495-12b79a80-3109-11e9-9bef-ec60651dbbcc.gif)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Safari
 - Version 12.0.3

**Smartphone (please complete the following information):**
 - Device: iPad
 - Browser: Safari or WebKit in iOS app

**Comment by microbit-mark** [comment]
^ @abchatra

**Comment by darzu** [comment]
Do we know if this is a regression, or if this never worked in Safari?

**Comment by abchatra** [comment]
Not sure, might not have worked ever

**Comment by riknoll** [comment]
Is this fixed by service workers? I thought I tested safari...

**Comment by riknoll** [comment]
Yeah, fixed by service worker
