### ISSUE TITLE
Link "Learn more" doesn't show after changing the size of text in "Display settings"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1838]
**Describe the bug**
Link "Learn more" doesn't show after changing the size of text in "Display settings"

**Steps to reproduce the behavior**
1. Change the size of text, apps and other items to 125% in "Display settings"
2. Navigate to https://makecode.microbit.org/beta#editor
3. Click "More..." -> "Extensions"
4. Scroll down and observe the extension

**Expected behavior**
Link "Learn more" should show on the bottom of each extension
![issue21801compare](https://user-images.githubusercontent.com/23466737/52925604-092e6c80-336d-11e9-99a5-2a86a4a49ef4.gif)

**Actual behavior**
Link "Learn more" doesn't show after changing the size of text in "Display settings"
![capture123](https://user-images.githubusercontent.com/23466737/52925595-fe73d780-336c-11e9-9566-6a29eea56748.PNG)
![issue21801](https://user-images.githubusercontent.com/23466737/52925599-029ff500-336d-11e9-9d06-dabad6dfc085.gif)

**Additional context**
- OS: Windows (build: 17763.1.amd64fre.rs5_release.180914-1434)
- Browser: Edge, Chrome, Firefox, IE

**Reference:**
https://microsoft.sharepoint.com/portals/hub/_layouts/15/PointPublishing.aspx?app=video&p=p&chid=a30c8ac1-971e-48e2-bc0d-758478f64050&vid=2cd20426-9085-4cea-9519-aa041c69f3d7

**Comment by pelikhan** [comment]
By design, there isn't enough space to display the link.

**Comment by Helen09** [comment]
Closed as by design
