### ISSUE TITLE
Make the whole app a simple html5 app

### ISSUE THREAD

**Issue by selmen2004** [Microsoft/pxt-microbit#1840]
can be there a light version of the application that just have html and js files , I mean with no server needed at all  ? 
this is helpfull for users with slow computers  and with no internet like here in many schools in Tunisia (many still use windows xp so impossible to talk about nodejs or electron ) where we start teaching robotics and micro:bit for the first year?

**Comment by abchatra** [comment]
Unfortunately our editor will not run in windows XP today. Browser technology is too old to support any of the MakeCode features

If you are interested in no internet scenario try out our offline app (This is still pre-release and subject to change a lot)
https://makecode.microbit.org/offline-app
This doesn't require any internet.

Please give feedback on the offline-app when you have used it. Again not it is pre-release app and not battle tested.

**Comment by selmen2004** [comment]
I've alrea

**Comment by selmen2004** [comment]
I've already found a solution for offline  xp users 
using an online machine with google chrome and backing up the whole chrome user data and redistribute it , but that's not excellent idea
I already know about offline app wich only supports 64bit windows ,which is great , but  not what I want 
Thanks
