### ISSUE TITLE
There is no tutorial picture on home screen on Windows high contrast mode

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#1843]
**Describe the bug**
There is no tutorial picture on home screen on Windows high contrast mode

**Steps to reproduce the behavior**
1. Search "Ease of Access high contrast settings" in windows and turn it on
2. Navigate to https://makecode.microbit.org/beta on each browser 

**Expected behavior(Edge)**
![issue22001com](https://user-images.githubusercontent.com/23466737/53070196-4afc1600-3519-11e9-8c00-eb401933c677.gif)

**Actual behavior(Chrome, Firefox & IE)**
There is no tutorial picture on home screen on Windows high contrast mode
![issue22001](https://user-images.githubusercontent.com/23466737/53070200-4cc5d980-3519-11e9-9f32-e877f77d7031.gif)

**Additional context**
OS: Windows (build: 17763.1.amd64fre.rs5_release.180914-1434)
Repro browser: Chrome(72.0.3626.109), Firefox(65.0.1), IE(11.316.17763.0)

**Reference link:**
https://microsoft.sharepoint.com/portals/hub/_layouts/15/PointPublishing.aspx?app=video&p=p&chid=a30c8ac1-971e-48e2-bc0d-758478f64050&vid=e428a44b-8621-4a4c-8ace-45536604a0c3

**Comment by abchatra** [comment]
Fixed
