### ISSUE TITLE
Page Micro: bit can't refresh on high contrast mode automatically on Chrome & Firefox

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#1844]
**Describe the bug**
There is no tutorial picture on home screen on Windows high contrast mode

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta on each browser
2. Search "Ease of Access high contrast settings" in windows and turn it on

**Expected behavior(Edge & IE)**
Page Micro: bit can refresh on high contrast mode automatically

**Actual behavior(Chrome & Firefox)**
Page Micro: bit can't refresh on high contrast mode automatically on Chrome & Firefox

**Additional context**
OS: Windows (build: 17763.1.amd64fre.rs5_release.180914-1434)
Repro browser: Chrome(72.0.3626.109), Firefox(65.0.1), IE(11.316.17763.0)
![issue22002](https://user-images.githubusercontent.com/23466737/53071095-2bb2b800-351c-11e9-82bb-00caac3fbaa2.gif)

**Reference link:**
https://microsoft.sharepoint.com/portals/hub/_layouts/15/PointPublishing.aspx?app=video&p=p&chid=a30c8ac1-971e-48e2-bc0d-758478f64050&vid=e428a44b-8621-4a4c-8ace-45536604a0c3

**Comment by abchatra** [comment]
Fixed
