### ISSUE TITLE
The published project does not preserve high contrast mode

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1845]
**Describe the bug**
The published project does not preserve high contrast mode

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "More..." -> "High Contrast On"
3. Click "Share" -> "Publish project" -> copy this link and open it on a new window

**Expected behavior(Edge & IE)**
The published project should preserve high contrast mode

**Actual behavior(Chrome & Firefox)**
The published project does not preserve high contrast mode
![issue22003](https://user-images.githubusercontent.com/23466737/53072709-ef358b00-3520-11e9-8aff-ad3647561348.gif)

**Additional context**
OS: Windows (build: 17763.1.amd64fre.rs5_release.180914-1434)
Reference: https://microsoft.sharepoint.com/portals/hub/_layouts/15/PointPublishing.aspx?app=video&p=p&chid=a30c8ac1-971e-48e2-bc0d-758478f64050&vid=9d516a9e-d8cf-47b2-b906-86d8175c94f2&from=1

**Comment by pelikhan** [comment]
High contrast is a browser local mode and is not persisted in the project sources. By Design.
