### ISSUE TITLE
Bluetooth UART service needs to allow sending byte array or buffer

### ISSUE THREAD

**Issue by bittysoftware** [Microsoft/pxt-microbit#1847]
I want to be able to transmit fixed length byte arrays over the Bluetooth UART service. I looked at #274 and #276 and don't see the writeUntil function mentioned there. I'm not sure that's what is needed anyway. Bluetooth is not a serial cable so writing one byte at a time is not suitable.

The DAL contains this function and I'd like it exposed from within MakeCode please:

int send(const uint8_t *buf, int length, MicroBitSerialMode mode = SYNC_SLEEP);

Using the function looks like this:

    uint8_t buf[4] = {0x31, 0x32, 0x33, 0x34};
    int n = uart->send((uint8_t *)buf, 4);

And causes all four bytes (in this example) transmitted in a single Bluetooth packet as opposed to 4 individual bytes sent in 4 separate packets, which the existing writeNumber function would result in.

The UART service is the only way to send arbitrary byte sequences over Bluetooth so it has lots of applications.

Thanks in anticipation

@smartyw

**Comment by martinwork** [comment]
Yes, Bluetooth UART really needs to send multiple things to get speed. You can use console.log, which has a smaller footprint and the same problem. JavaScript seems to have bluetooth.uartWriteBuffer.

A blocks experiment... https://makecode.microbit.org/_1tW0FhiaxLfK. The MakeCode console in the iOS app seems to be happy receiving this but it's no good over my USB connection.

I think this method will do 5 unsigned or 4 signed/mixed byte-size numbers per packet. But it's not pretty!

bluetooth uart write line seems to be missing.

**Comment by smartyw** [comment]
Thanks @martinwork .

Surfacing this as a block would be great. And if possible, making the parameter a buffer might make the most sense.

**Comment by smartyw** [comment]
There should be no need for a delimiter, either. It should be possible to simply transmit the contents of a  buffer or array of a specified length.

**Comment by xuefengedu** [comment]
In fact, `bluetooth.uartWriteBuffer` already available in javascript, and the block is hidden at present: https://github.com/Microsoft/pxt-microbit/blob/fc73d71d638f54e488a66afcaf6727f9a1da44da/libs/bluetooth/shims.d.ts#L69 

javascript example:
```
    let buf = pins.createBuffer(4)
    bluetooth.uartWriteBuffer(buf)
```

for how to use buffer:

https://github.com/Microsoft/pxt-microbit/blob/master/docs/types/buffer.md

https://github.com/Microsoft/pxt-microbit/blob/master/docs/types/buffer/using-buffers.md

**Comment by smartyw** [comment]
Excellent, thank you.

But why is the block hidden?

**Comment by xuefengedu** [comment]
ok, not hidden, just not implement yeah.

**Comment by smartyw** [comment]
OK, thanks. I can start using the JavaScript function. I hope it will be exposed as a block to make it easier for people though.

**Comment by martinwork** [comment]
When I wrote "JavaScript seems to have bluetooth.uartWriteBuffer", I guess I should have typed LOUDER! :)

**Comment by smartyw** [comment]
;-)

Yes, well two of you were kind enough to point this out  :-) So, all good.

**Comment by pelikhan** [comment]
We don't expose buffer API in blocks as they are no block to manipulate them.

**Comment by smartyw** [comment]
Ok, thanks for explaining. At least I discovered there are suitable JavaScript APIs.
