### ISSUE TITLE
Implementing a dictionary in typescript

### ISSUE THREAD

**Issue by Raekt** [Microsoft/pxt-microbit#1848]
Is there a built-in dictionary/map data type for ES5 compiler?

**Comment by xuefengedu** [comment]
no dict or map at makecode at present.
common types: https://makecode.microbit.org/javascript/types

share a sample to implement by yourself, I don't have time now, might add it in the future if free:
```

/**
 * test blocks
 */
//% weight=100 color=#0fbc11 icon=""
namespace test {
    class Item {
        key: string;
        value: string;
        Item(a: string, b: string) {
            this.key = a;
            this.value = b;
        }
        getKey() {
            return this.key;
        }
        getValue() {
            return this.value;
        }
    }
    export class Dictionary {
        Dict: Array<Item>;
        Dictionary(a: Array<Item>) {
            this.Dict = a;
        }
        //% blockId="GetValue" block="GetValue %key"
        GetValue(key: string): string {
            for (let i = 0; i < this.Dict.length; i++) {
                if (this.Dict[i].getKey() == key) {
                    return this.Dict[i].getValue();
                }
            }
            return null;
        }
    }
}
``

**Comment by riknoll** [comment]
In the beta editor, we now support the "any" type in TypeScript which allows for the behavior you want.

```typescript
let dict: any = {}; 

dict["hello"] = "goodbye"
```

Currently, we don't support the usual TypeScript syntax for these types of data structures:

```typescript
let dict: {[index: string]: string} = {};

dict["hello"] = "goodbye";     // Gives and "unsupported indexer" error
```

@mmoskal this should be simple to add right? Just a typechecker bug

**Comment by mmoskal** [comment]
Right, should be simple - fix a check the emitter

**Comment by mmoskal** [comment]
btw, note that this does linear lookup, which isn't ever going to be a problem on microbit with it's 3k of RAM but might be a problem on a bigger devices.
