### ISSUE TITLE
Add offline app to offline documentation.

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt-microbit#1852]
Microbit offline documentation: https://makecode.microbit.org/offline

Please add information about offline app in the above page. Only Microbit and Mindstorms EV3 has this. 
Offline app is here: https://makecode.microbit.org/offline-app 

We want to make sure it is prominent and it is a pre-release app at this stage.

**Comment by abchatra** [comment]
@pelikhan @Jaqster FYI

**Comment by pelikhan** [comment]
CSS looks broken on the offline-app page.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment]
Yes we broke it today due to microbit update

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by xuefengedu** [comment]
it seems this issue has fixed and completed.
