### ISSUE TITLE
"Reference" can't load on each browser

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1857]
**Describe the bug**
"Reference" can't load 

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "Help" --> "Reference" 

**Expected behavior**
"Reference" should be loaded

**Actual behavior**
"Reference" can't load 
![issue22502](https://user-images.githubusercontent.com/23466737/53325499-6e123580-391e-11e9-84d6-e42c655f6cec.gif)

**Additional context**
OS: Windows (build: 17763.1.amd64fre.rs5_release.180914-1434)
Repro on Edge, Chrome, Firefox and IE

**Comment by pelikhan** [comment]
This issue was due to the cloud compilatoin service being down. Now fixed.
