### ISSUE TITLE
Some extension help tutorial can't be loaded completely 

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#1858]
**Describe the bug**
Some extension help tutorial can't be loaded completely 

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "Advanced" -> "Extensions" -> choose extensions to add ( Extensions: "Environment-and-Science-loT", "RingbitCar", "kitronik-motor-driver", "kitronik-servo-lite")
3. Right-click on the blocks to look added blocks' help 

**Expected behavior**
The help tutorial should be loaded completely

**Actual behavior**
Some extension help tutorial can't be loaded completely 
![issue225003](https://user-images.githubusercontent.com/23466737/53328400-d49a5200-3924-11e9-8c45-089f933ca52c.PNG)

**Additional context**
- OS: Windows (build: 17763.1.amd64fre.rs5_release.180914-1434)
- Repro on Edge, Chrome, Firefox and IE

**Comment by microbit-mark** [comment]
This still looks to be an issue @pelikhan or is this a different problem:

This is the help rendered for

https://makecode.microbit.org/pkg/kitronikltd/pxt-kitronik-klef-piano

<img width="1273" alt="Screenshot 2020-03-04 at 16 10 45" src="https://user-images.githubusercontent.com/31242877/75899101-fcbf6980-5e32-11ea-8472-cc3b7a877742.png">

**Comment by abchatra** [comment]
This is the package issue. They specified version  "version": "0.0.1", in the pxt.json but don't have tag fo r that version.
