### ISSUE TITLE
My functions and some variables are being given a suffix

### ISSUE THREAD

**Issue by rhubarbdog** [Microsoft/pxt-microbit#1859]
**Describe the bug**
I had to switch to java editor I noticed that my function names and some vaviables are being given a numerical suffix. My program only has an `on start block` and no blocks which are run in the background or as the result of some interrupt 

**To Reproduce**
here's my <a href="https://makecode.microbit.org/_Y4AevqTD8cPM">blocks</a>

**Expected behavior**
I expect variable names and function names not to be given fruity little suffixes

**Desktop (please complete the following information):**
 - OS: linux mint 18.2
 - Browser : Firefox
 - Version : 63.0.3

**Comment by pelikhan** [comment]
This issue is fixed in beta.

**Comment by rhubarbdog** [comment]
When will this be released to makecode.microbit.html
