### ISSUE TITLE
String char code conversions not working as expected in simulator

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt-microbit#186]
The following code sample works as expected, showing an `H` on the LEDs on both the simulator and the micro:bit:

```typescript
let s = "H"
let sNum = s.charCodeAt(0)
sNum = sNum + 0
let s2 = String.fromCharCode(sNum)
basic.showString(s2)
```

However, changing the third line causes nothing to display on the LEDs on the simulator:

```typescript
let s = "H"
let sNum = s.charCodeAt(0)
sNum = sNum + 1
let s2 = String.fromCharCode(sNum)
basic.showString(s2)
```

On the micro:bit this correctly displays as `I`. I did a diff of the generated JS for the simulator and the only difference (aside from variables being given different IDs) was the line that changed the value of `sNum` as expected:

![diff](https://cloud.githubusercontent.com/assets/20356546/17208639/6ecc84de-54b1-11e6-8889-ebd669d2d323.PNG)

**Comment by thomasdenney** [comment]
This bug still occurs, although the error displayed is now just 'sim: check failed' (and the fifth line is highlighted in yellow).

**Comment by abchatra** [comment]
Fixed by https://github.com/Microsoft/pxt/pull/545
