### ISSUE TITLE
Hardware simulator doesn't have any response after it's paired with Chrome

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1861]
**Describe the bug**
Hardware simulator doesn't have any response after it's paired with Chrome

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor on Chrome
2. Click "More..." -> "Pair device" to pair a hardware (Pair hardware successfully)
3. Drag a "show icon" block and put it under block "forever"
4. Click "Download" and observe the hardware simulator

**Expected behavior**
Hardware simulator should show "heart"

**Actual behavior**
Hardware simulator doesn't have any response after it's paired with Chrome

**Additional info:**
- Browser: Chrome(72.0.3626.119)
- Hardware interface version: 0250
- This bug is not repro on live site(https://makecode.microbit.org/#editor)

**Comment by pelikhan** [comment]
No repro. Please add screen recording.

**Comment by Helen09** [comment]
@pelikhan This bug is dupli with https://github.com/Microsoft/pxt-microbit/issues/1875, it is also repro on Chrome on Windows

**Comment by pelikhan** [comment]
I see. I did not understand the description.
