### ISSUE TITLE
Optional string array in custom block shows as array with 3 empty read-only circles

### ISSUE THREAD

**Issue by bosnivan** [microsoft/pxt-microbit#1864]
Optional string array in custom block shows as array with 3 empty read-only circles.

It's related to this extension:
https://github.com/bosnivan/pxt-wifibit

This function/block is problematic:
> /**
>      * Izvrši neku od HTTP metoda.
>      * @param method metoda koja će se izvršiti, eg: HttpMethod.GET
>      * @param host adresa servera, eg: "google.com"
>      * @param port port servera, eg: 80
>      * @param urlPath putanja na serveru, eg: "/search?q=something"
>      * @param headers zaglavlja
>      * @param body tijelo
>      */
>     //% weight=96
>     //% blockId="wfb_http" block="izvrši HTTP metodu %method|server: %host|port: %port|putanja: %urlPath||zaglavlja: %headers|tijelo: %body"
>     export function useHttpMethod(method: HttpMethod, host: string, port: number, urlPath: string, headers?: string[], body?: string): void {
>         let myMethod: string
>         switch (method) {
>             case HttpMethod.GET: myMethod = "GET";
>             case HttpMethod.POST: myMethod = "POST";
>             case HttpMethod.PUT: myMethod = "PUT";
>             case HttpMethod.HEAD: myMethod = "HEAD";
>             case HttpMethod.DELETE: myMethod = "DELETE";
>             case HttpMethod.PATCH: myMethod = "PATCH";
>             case HttpMethod.OPTIONS: myMethod = "OPTIONS";
>             case HttpMethod.CONNECT: myMethod = "CONNECT";
>             case HttpMethod.TRACE: myMethod = "TRACE";
>         }
>         // Establish TCP connection:
>         let data = "AT+CIPSTART=\"TCP\",\"" + host + "\"," + port
>         writeToSerial(data, 6000)
>         data = myMethod + " " + urlPath + " HTTP/1.1" + "\u000D" + "\u000A"
>             + "Host: " + host + "\u000D" + "\u000A"
>         if (headers && headers.length > 0) {
>             for (let i = 0; i < headers.length; i++) {
>                 data += headers[i] + "\u000D" + "\u000A"
>             }
>         }
>         if (data && !data.isEmpty() && data.length > 0) {
>             data += "\u000D" + "\u000A" + body
>         }
>         data += "\u000D" + "\u000A" + "\u000D" + "\u000A"
>         // Send data:
>         writeToSerial("AT+CIPSEND=" + (data.length + 2), 3000)
>         writeToSerial(data, 6000)
>         // Close TCP connection:
>         writeToSerial("AT+CIPCLOSE", 3000)
>     }

This is how it looks like in MakeCode block editor:
![microbit-screenshot](https://user-images.githubusercontent.com/27815255/53453147-ac454d00-3a23-11e9-9a8e-ed36cea38ae5.png)

Two same blocks are shown. First one is just added and it's OK. Second one is expanded with optional parameter which is problematic. If I switch to JS editor, param is translated to [] value.
If I start working from JS editor and switch to block editor, there's no problems.
Same behavior I got in MakeCode Playground.

I guess it's not needed for this problem, but here's my configuration:
Windows 10
Google Chrome 72.0.3626.109
makecode.microbit.org version:  1.2.13
Microsoft MakeCode version:  4.4.7
microbit runtime version:  v2.1.1

**Comment by pelikhan** [comment]
@riknoll what do we do with arrays in optional parameters?

**Comment by riknoll** [comment]
I don't think we do anything special, but I'll double check. I'm not sure I understand the desired behavior though? Seems like adding an array shadow block is the correct thing to do

**Comment by abchatra** [comment]
Array shadow is the right think to do here as there are no context on what needs to be there in those prefilled values.
