### ISSUE TITLE
"Karel the LED" doesn't run on hardware

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1865]
**Describe the bug**
"Karel the LED" doesn't run on hardware

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/projects/karel copy this project
2. Navigate to https://makecode.microbit.org/beta#editor and switch to "JavaScript" and paste this project
3. Click "Download" and copy this .hex file to hardware

**Expected behavior (on live site)**
"Karel the LED" should run on hardware

**Actual behavior (on beta site)**
"Karel the LED" doesn't run on hardware

**Additional info:**
This bug only repro on beta (download .hex form beta and drag this file to hardware)

**Comment by pelikhan** [comment]
This script uses the microbit Image object. Remove all reference to that object removes the hard crash.

**Comment by abchatra** [comment]
Good catch @Helen09

**Comment by pelikhan** [comment]
Smaller repro:
```
let bird = game.createSprite(0, 2)
bird.set(LedSpriteProperty.Blink, 300)
```

**Comment by pelikhan** [comment]
smaller:
```
let img = images.createImage(`
    . . . . .
    . . . . .
    . . . . .
    . . . . .
    . . . . .
    `)
let i = 0;
basic.forever(function () {
    img.setPixel(0, 0, !(i++ % 2))
    img.showImage(0)
})
```

**Comment by abchatra** [comment]
This should be fixed. Please verify.

**Comment by abchatra** [comment]
Please also verify all the dependent bugs

**Comment by Helen09** [comment]
This bug has been fixed
