### ISSUE TITLE
"Slow-Mo" can't be enabled

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1869]
**Describe the bug**
"Slow-Mo" can't be enabled

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Drag "show number" and "show string" and put it under block "forever"
3. Click "Slow-Mo" and observe blocks

**Expected behavior (on live site)**
"Slow-Mo" should be enabled
![issue227003com](https://user-images.githubusercontent.com/23466737/53479718-9af85100-3ab4-11e9-8b56-7bc3d95099b5.gif)

**Actual behavior (on beta site)**
"Slow-Mo" can't be enabled
![issue2270003](https://user-images.githubusercontent.com/23466737/53479252-91bab480-3ab3-11e9-9381-f76130750134.gif)

**Comment by abchatra** [comment]
@gushuro can you take look at this issue?

**Comment by gushuro** [comment]
Seems fixed for me in Beta.
Could you verify?

**Comment by Helen09** [comment]
@gushuro I have verified this bug, it still repros on each browser
![Issue31901](https://user-images.githubusercontent.com/23466737/54574665-1ef68680-4a2c-11e9-8fab-240f00ccd7fe.gif)

**Comment by abchatra** [comment]
I can also reproduce on safari

**Comment by pelikhan** [comment]
Fixed /beta
