### ISSUE TITLE
Support higher order array functions

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt-microbit#187]
JavaScript arrays have methods for [map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map), [filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter), and [reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce). It would be nice to add support for these.

**Comment by pelikhan** [comment]
Please move to PXT issue tracker...
