### ISSUE TITLE
Feature: is_gesture block equivalent

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1870]
micro:bit support: 18728

**Is your feature request related to a problem? Please describe.**
 You can detect whether button is pressed using either the event handler 'on button A' or by reading whether the logical value of 'button A is pressed' is true.
You can also detect a gesture using e.g. `on shake’.  But I can’t find a way to read a corresponding logical value to see if the micro:bit is shaken or not.
 
It appears that you can do this in microPython: https://microbit-micropython.readthedocs.io/en/latest/accelerometer.html

`microbit.accelerometer.is_gesture(name)`
 

**Describe the solution you'd like**
For the work I’m doing with beginner teachers using MakeCode it would be very useful to have JS block equivalent to this MicroPython statement.  Any chance?

**Describe alternatives you've considered**

**Additional context**

**Comment by pelikhan** [comment]
Available in /beta
