### ISSUE TITLE
Where can i download the whole Project at makecode.microbit.org?

### ISSUE THREAD

**Issue by bestony** [Microsoft/pxt-microbit#1871]
Hi， I use MicroSoft Make Code, And I found the explorer, and here are many Typescripe Code.

Where can i download the source code?

For Version Control and compile local.

![image](https://user-images.githubusercontent.com/13283837/53492465-eb32db80-3ad3-11e9-9a3e-8868eeeab09b.png)

**Comment by pelikhan** [comment]
You can run ```pxt extract yourhexfile.hex``` to extract the files. See https://makecode.microbit.org/cli
