### ISSUE TITLE
Expose display rotation from DAL to JS/Blocks

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#1874]
**Is your feature request related to a problem? Please describe.**

I'd like to demonstrate to a student how an accelerometer in a phone allows the phone to know which way around the display should be drawn (IE if the display is in portrait or landscape). 

In MakeCode at the moment we have 'logo up' and 'logo down' events, but using these to rotate the display requires a user to draw images upside down, etc (and they can't use icons or text).

This would also be useful for someone wanting to use icons and text scrolling when their micro:bit is in a robot a specific way up/down, etc.

**Describe the solution you'd like**

The DAL includes the `display.rotateTo()` function that I think would make logical sense in the LED category alongside setDisplayMode. 

Here's an example of the DAL working:

```C++
#include "MicroBit.h"

MicroBit uBit;

int main()
{
    // Initialise the micro:bit runtime.
    uBit.init();

    // Spin the display
    uBit.display.rotateTo(MICROBIT_DISPLAY_ROTATION_180);
    uBit.display.scroll("UPSIDE DOWN");
    uBit.display.rotateTo(MICROBIT_DISPLAY_ROTATION_270);
    uBit.display.scroll("ROUND THE SIDE");

    release_fiber();
}
```

**Describe alternatives you've considered**
Here's an example that allows me to demonstrate something similar but it's very 'hard-coded'
![image](https://user-images.githubusercontent.com/147113/53512134-e8c38800-3ab9-11e9-9f2d-c3762eba005a.png)

**Additional context**
This is already implemented and working in the DAL

**Comment by jaustin** [comment]
@pelikhan if this isn't trivial for someone to do in MakeCode, some pointers here on this ticket for how someone else can do this would be great.

**Comment by CaptainCredible** [comment]
this would be nice to have!

**Comment by abchatra** [comment]
Extensions is the right one for this. Please feel free to build an extension.
