### ISSUE TITLE
In place manipulation of strings

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt-microbit#188]
The current string API provides no way of changing a single character of a string. You currently have to do the following (requiring extra allocations):

```typescript
let s = "strjng"
s = s.substr(0, 3) + "i" + s.substr(4, 2)
```

Rather than:

```typescript
let s = "strjng"
s[3] = "i"
```

**Comment by pelikhan** [comment]
Not supported. Strings are immutable in JavaScript.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________
