### ISSUE TITLE
'getTopBlocks' of null error when converting script to blocks

### ISSUE THREAD

**Issue by FranklinWhale** [Microsoft/pxt-microbit#1880]
**To Reproduce**
1. Go to https://makecode.microbit.org/beta (which has PXT 5.5.13)
2. Switch to JavaScript
3. Paste the code below to the editor
```ts
function test(x: string[]) {
	basic.showNumber(x.length)
}
```
4. Switch to Blocks
5. Replace the content in the script editor with the code below
```ts
function test(x: string | null) {
    basic.showNumber(x ? x.length : -1)
}
test("abcde")
```
6. Switch to Blocks
7. Repeat Step 1 to 6 on https://makecode.microbit.org/ (which has PXT 4.4.7)

**Expected behavior**
The conversion from script to blocks should be successful.

**Screenshots**
After Step 4 and Step 6:
![image](https://user-images.githubusercontent.com/8416067/53469289-47780a00-3a98-11e9-8a26-257e9053d5b5.png)

**Comment by riknoll** [comment]
We can't support union types in blocks, but the string array should be fine. Looks like the `arg_reporter_custom` block is setting its output check to `string[]` when it should include `Array` to match what we do in blocklyLoader. I'll see if there's a way to fix this in pxt and not Blockly...

**Comment by FranklinWhale** [comment]
Regarding union type, the behavior of PXT 4.4.7 is acceptable, where the function with union type is converted to a grey block.

**Comment by riknoll** [comment]
Yeah, sorry, I should have been more clear in my comment. My plan is to restore that behavior (grey block for types not supported in blocks) and fix the type check for array types.
