### ISSUE TITLE
compileBlockAsync is broken by changes made in #5256

### ISSUE THREAD

**Issue by FranklinWhale** [Microsoft/pxt-microbit#1882]
**Describe the bug**
The changes made in Microsoft/pxt#5256 require variables be tracked in the `idToScope` map of the `Environment` before block-to-typescript compilation. However, `trackVariables` is only called in `trackAllVariables` which is further only called in `compileWorkspace`. The `Environment` made during `compileBlockAsync` never tracks variables and compilation fails when the blocks being compiled have any variable.

**To Reproduce**
The `compileBlockAsync` method is not currently called in pxt. One way to reproduce the issue is to bring back the TypeScript tooltip temporarily.

**Expected behavior**
A TypeScript representation of the blocks should be returned, as it has been before Microsoft/pxt#5256.

**Comment by abchatra** [comment]
@riknoll can you articulate the impact of this?

**Comment by FranklinWhale** [comment]
A quick fix to this issue appears to append the code below to https://github.com/Microsoft/pxt/blob/master/pxtblocks/blocklycompiler.ts#L1522

```ts
trackAllVariables([b], e);
```

**Comment by riknoll** [comment]
No impact for us; this is an old codepath we don't use anymore. @FranklinWhale how is this impacting you?

**Comment by pelikhan** [comment]
If we can, we should delete it.

**Comment by FranklinWhale** [comment]
I have a custom build of pxt-microbit that uses `compileBlockAsync()` to get the TypeScript of a block and its descendants. I am aware that such use is not officially supported and I currently don't have a strong argument against its deletion...
