### ISSUE TITLE
How to extend the package from the offline app without internet connection?

### ISSUE THREAD

**Issue by lionyhw** [microsoft/pxt-microbit#1886]
How to extendthe package from the offline app without internet connection?

**Comment by pelikhan** [comment]
@lionyhw could you give more details about your request?

**Comment by lionyhw** [comment]
Now I have downloaded the offline app and installed it, and then I cut off my internet, 
![](https://i.imgur.com/57GY4zm.png)
 I want to extend the package into the project, but it shows I failed to connect the internet and appears to be offline. 
![](https://i.imgur.com/EFYNmxB.png)
I found the "packages" in the files of offline app, will it do any favor to extend the package?
![](https://i.imgur.com/01R1bAh.png)
How to extend the package into the project without the internet connection?

**Comment by lionyhw** [comment]
@pelikhan Looking forward to your reply!

**Comment by pelikhan** [comment]
This is not supported yet. Could you explain further your scenario?

**Comment by lionyhw** [comment]
The students in the classroom have no access to the internet, how can we do to help the students to extend the package in this condition?

**Comment by pelikhan** [comment]
What packages are you missing?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lionyhw** [comment]
Look，I want to extend the package "Tinkercademy" and "Ring:bit car " , but the only way to achieve is to download through the internet connection.   
 ![](https://i.imgur.com/zrh6ocS.png)
But how can I do to extend these two packages to the offline App without the Internet connection? 
 ![](https://i.imgur.com/OL7A90b.png)

**Comment by abchatra** [comment]
The request the way I understand it. If they had the local github repo of the extension, can they somehow load it as an extension.

**Comment by lionyhw** [comment]
Yes. You understanding is correct. 
One computer is off-line. I copy the "makecode for micro:bit off-line app" to this computer by USB drive,but I can't extend any packages on this app when my computer is offline. So I want to try load local github repo. Will it works? If it don't work, is there any solutions?

**Comment by pelikhan** [comment]
In the next version of makecode, you will be able to import a .hex as an extension. So save your package as a .hex; then share it with your offline users.
