### ISSUE TITLE
Code converting issue on "Hack Your Headphones"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1888]
**Describe the bug**
Code converting issue on "Hack Your Headphones"

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/projects/red-light-green-light
2. Copy the code to https://makecode.microbit.org/beta#editor JavaScript content pane
3. Click "Blocks" to switch to blocks mode and observe

**Expected behavior** 
![image](https://user-images.githubusercontent.com/23466737/53555159-5932dd80-3b7c-11e9-89b4-8f79f96191d5.png)

**Actual behavior**
Code converting issue on "Hack Your Headphones"
![issue2282](https://user-images.githubusercontent.com/23466737/53555300-a1520000-3b7c-11e9-899f-43b9def2fb45.gif)

**Comment by pelikhan** [comment]
This looks correct.

**Comment by Helen09** [comment]
@pelikhan When converting to "Blocks", all results turn to "Middle C"
![issue0301](https://user-images.githubusercontent.com/23466737/53621980-53e49a00-3c33-11e9-9201-04ce4c348950.PNG)
