### ISSUE TITLE
Firefox fonts incorrect on macOS external displays

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#1889]
When using MakeCode on macOS (10.14.3) in Firefox (65.0.1) I get poorly rendered fonts when the window is on an external display:

This compares Firefox, Safari and Chrome on the external display (in that order top-to-bottom):
![image](https://user-images.githubusercontent.com/147113/53564647-61285880-3b4f-11e9-9f1f-56dcf0079a59.png)

Here are the same three windows on a Retina display, Firefox is off to the right
<img width="882" alt="image" src="https://user-images.githubusercontent.com/147113/53564720-8b7a1600-3b4f-11e9-9eaa-b855098f8e6c.png">

If you apply `-moz-osx-font-smoothing: grayscale` to `text.blocklyText` (and then toggle the font-weight property on/off to force re-rendering the font, it seems) then the situation clears up a lot:
![image](https://user-images.githubusercontent.com/147113/53564543-16a6dc00-3b4f-11e9-897d-73d353564f71.png)

Is this something to do with the fact that when I load MakeCode on Firefox I see the following in the console:
```
Browser: safari 10 on mac pxtapp.js:1730:13
PouchDB adapter: idb pxtapp.js:1730:13
```

**Comment by abchatra** [comment]
Closing more than an year old bugs. If this still reproduces please reopen.
