### ISSUE TITLE
Bluetooth documentation links have vanished

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#189]
It looks like the link to the Bluetooth documentation has disappeared from the Reference page: https://codethemicrobit.com/reference . It used to be there in a section titled "Advanced".

Also this page is blank too: https://codethemicrobit.com/reference/bluetooth 

Thanks

**Comment by pelikhan** [comment]
See https://github.com/Microsoft/pxt/issues/175

**Comment by pelikhan** [comment]
Fix is in flight but blocked by regression on package load system.

**Comment by pelikhan** [comment]
Fixed.
