### ISSUE TITLE
Console will not receive data until a Download has been performed

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#1893]
**Is your feature request related to a problem? Please describe.**

When MakeCode has just been launched in the browser (Windows, Chrome), the console USB/serial connection is not opened until a Download is performed.

If I have a micro:bit which is already sending data or ready to send data from RAM on a button press, MakeCode will not receive it.

**Describe the solution you'd like**

Is it possible to open the console USB/serial connection without downloading a project?

**Describe alternatives you've considered**

I tried renewing the pairing with the micro:bit.

**Comment by abchatra** [comment]
This doesn't repro with WebUSB. Data is received if it was already paired.

**Comment by martinwork** [comment]
There is no problem with this via Bluetooth in the iOS app, so long as micro:bit remains paired with the iOS device, because the iOS app has a menu entry to initiate the connection.

I thought it was OK with USB too when this was first reported to me.

I am testing with USB and Chrome on Windows, which I can pair with micro:bit and directly download.

Maybe I am misunderstanding "WebUSB".  Perhaps I don't know how to initiate the connection, so the "Show console Device" button appears.

Please try this program with the step-by-step below:
basic.forever(function () {
    serial.writeValue("x", 1)
    serial.writeValue("x", 2)
    serial.writeValue("x", 3)
})

**Download program:**
Connect micro:bit to USB
Open browser and MakeCode with program above
Pair with device if necessary
Download
"Show console Device" button appears
Close browser

**Collect data:**
Connect micro:bit to USB
Open browser and MakeCode
Pair with device if necessary
"Show console Device" button does not appear.

The bit I didn't understand at first is that MakeCode is closed completely after download and reloaded sometime later to collect data.

The practical scenario reported to me is that between uses of MakeCode the computer may be used for other activities. MakeCode may have been closed, perhaps paired with other micro:bits, the computer rebooted or download and collection are done on different computers. Meanwhile, the micro:bit has been collecting data to RAM under battery power in another room and is ready to send the data to serial on a button press.

**Comment by abchatra** [comment]
I am closing this as we always show the data if the webusb is connected. There is no feature in microbit yet to collect data and stream later on.
