### ISSUE TITLE
Pull-up/Pull-down block does not work as expected

### ISSUE THREAD

**Issue by adiazulay** [Microsoft/pxt-microbit#1895]
**Describe the bug**
Using the Pull-up/pull-down block with an analog read does not seem to have an effect.

**To Reproduce**
1. Add a pull-down block and select Pin10
2. Add an analog read block and read Pin10
3. Print that reading to Serial.
4. Reading will read around 551

**Expected behavior**
The reading in this case should be 0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**

**Comment by abchatra** [comment]
@adiazulay can you please share your code?

**Comment by adiazulay** [comment]
@abchatra here is the .hex file I generate from MakeCode. 
[PullDownNotWorking.zip](https://github.com/Microsoft/pxt-microbit/files/2984342/PullDownNotWorking.zip)

Also here are the MakeCode blocks https://makecode.microbit.org/_Mw3bCpcpkVHE

**Comment by martinwork** [comment]
The specified pull mode is only actually set on the pin when in digital read (and pulse or event modes,  I think), but is not changed by using analogue read. So adding a digital read to the on start block will have an effect on the analogue values read in the forever block.

**Comment by abchatra** [comment]
Thanks @martinwork
