### ISSUE TITLE
NeoPixels don't render in simulator on Safari and are buggy on Chrome

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#1897]
**Describe the bug**
Neopixel strips don't render properly on Safari and are a little less buggy in Chrome

**To Reproduce**
1. Go to makecode.microbit.org/beta (broken in non-beta too)
2. Create a new project
3. Add the "Neopixel" package
4. Add these blocks:
![image](https://user-images.githubusercontent.com/6453828/53673942-7da3be00-3c3f-11e9-8527-ccee5527c89b.png)
5. Notice the simulator doesn't render the neopixels properly

**Expected behavior**
Neopixel strips should be shown on the breadboard and when the mouse hovers over them they should expand to show a better view of the color pattern.

**Screenshots**
![neopixel-broken-safari-2](https://user-images.githubusercontent.com/6453828/53674029-04589b00-3c40-11e9-8c18-abdc03e9f990.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3 (18D109)
 - Browser Safari Version 12.0.3 (14606.4.5)
- MacBook Pro 2018, i9, 32GB

**Comment by pelikhan** [comment]
The zoomed neopixel view has been broken for a while.

**Comment by abchatra** [comment]
Over a year old bug. Won't fix.
