### ISSUE TITLE
All “ring tone” under "if...else if..." is "Middle C"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1900]
**Describe the bug**
All “ring tone” under "if...else if..." is "Middle C"

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/projects/hack-your-headphones/code
2. Copy the code to https://makecode.microbit.org/beta#editor JavaScript content pane
3. Click "Blocks" to switch to blocks mode and observe

**Expected behavior**
“ring tone” under different "if...else if..." should be different
![304compare](https://user-images.githubusercontent.com/23466737/53716895-5f350100-3e91-11e9-9197-78729fbf48d3.PNG)

**Actual behavior**
All “ring tone” under "if...else if..." is "Middle C"
![issue30401](https://user-images.githubusercontent.com/23466737/53716911-6b20c300-3e91-11e9-9209-9a4b25803a02.PNG)

**Comment by abchatra** [comment]
@Helen09 does this repro in live?

**Comment by pelikhan** [comment]
Looks fixed.

**Comment by Helen09** [comment]
@pelikhan This bug still repro now, the detail please see the shared page
https://makecode.microbit.org/projects/hack-your-headphones/code

**Comment by pelikhan** [comment]
The docs are running the released version which has the bug. I cannot repro this in /beta.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Helen09** [comment]
@pelikhan  Copy this code on beta JavaScript editor and switch to Block editor, the bug can repro
![Issue32201](https://user-images.githubusercontent.com/23466737/54797123-dd651600-4c8d-11e9-8aef-be5591f16d16.gif)

**Comment by riknoll** [comment]
I can repro this; looks like a decompiler bug
