### ISSUE TITLE
Home page projects scrolling can jump too far and skip a project

### ISSUE THREAD

**Issue by martinwork** [Microsoft/pxt-microbit#1901]
**Describe the bug**
On the Home page, the right chevron button can cause the projects carousel to scroll too far such that one or more projects are skipped.

**To Reproduce**
1. Go to 'https://makecode.microbit.org/beta'
2. Observe which projects are the 4th and 5th on "My Projects"
2. Resize the browser window so that the right chevron button overlaps the 3rd project
3. Click the right chevron
4. See that it has skipped the 4th project

When the apex of the chevron touches the right edge of the 3rd project, it skips one project. More overlap, up to half way, skips more projects.

**Expected behavior**
The scrolling button shouldn't skip projects.

**Desktop (please complete the following information):**
 - OS:  Windows and others
 - Browser: Chrome and others
 - Version: beta

**Comment by pelikhan** [comment]
Martin could you add a screen recording?

**Comment by martinwork** [comment]
![scroll](https://user-images.githubusercontent.com/989126/54167472-b6267180-4461-11e9-8558-37e9504c8861.gif)

**Comment by abchatra** [comment]
Fixed
