### ISSUE TITLE
function written in beta editor is gone in normal editor

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt-microbit#1902]
**Describe the bug**
I made a program using the /beta block editor, and added a function (no parameters). Then I shared the code by publishing it, but if you follow that link it opens in the normal editor and the function is gone. Instead a strange empty block is shown.

**To Reproduce**
1. Go to this link https://makecode.microbit.org/78974-98199-25421-27348
2. press edit.
3. See that there is no function called "move" but you see this weird block instead:
![image](https://user-images.githubusercontent.com/5718354/53811545-f2d20480-3f59-11e9-8206-c7b92b8cb357.png)

**Expected behavior**
It should show a function called "move"
You can see it by following this link to the project in the beta editor instead:
https://makecode.microbit.org/beta/#pub:78974-98199-25421-27348

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser firefox
 - Version 65.0.2

**Additional context**
I might have added a parameter and then removed it again when I created the function.

**Comment by abchatra** [comment]
Yes, functions in /beta will not work in live editor. We don't support upward mobility. But functions written in live will always work in /beta.

**Comment by abchatra** [comment]
This is because underlying structure of functions have changed in /beta
