### ISSUE TITLE
Tutorials not translated to DE (beta)

### ISSUE THREAD

**Issue by stritti** [Microsoft/pxt-microbit#1903]
**Describe the bug**
I think the content of tutorial description isn't loaded language specific. 

**To Reproduce**
1. Go to 'https://makecode.microbit.org/beta?liveforcelang=de'
2. Click on 'Blinkendes Herz' (Section'Anleitungen')

**Expected behavior**
The popup dialog of tutorial and the banner navigation (see screenshot) should be in German. 
The translations have been added already 3 days ago.

**Screenshots**
See circled elements: 
![Beta-MakeCode: German ](https://user-images.githubusercontent.com/184547/53819715-beb30f80-3f6a-11e9-922c-dfec99601688.png)

![German transations](https://user-images.githubusercontent.com/184547/53821607-6bdb5700-3f6e-11e9-8fd9-617ce7ec7296.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: Chrome
 - Version: 72

**Comment by pelikhan** [comment]
Are the translation validated?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stritti** [comment]
Is validation required on https://makecode.microbit.org/beta?liveforcelang=de
I thought it is especially to preview translation almost live.

**Comment by ganicke** [comment]
The `v1` [Flashing Heart](https://crowdin.com/translate/kindscript/990/en-de) tutorial isn't fully translated to German yet in Crowdin:

![image](https://user-images.githubusercontent.com/27789908/54462078-c2ddea80-472b-11e9-9350-13745892b469.png)

**Comment by stritti** [comment]
I was Shure I had translated it. Hm. Sorry for confusion. I translated it now and will check on Monday if it is visible on editor.

**Comment by stritti** [comment]
I have update the translations yesterday, but they are still missing in **beta**: 

https://crowdin.com/translate/kindscript/990/en-de ->
![image](https://user-images.githubusercontent.com/184547/54514141-9c9d9200-4959-11e9-9a90-e1eeb4dc3d17.png)

https://makecode.microbit.org/beta?liveforcelang=de -> 
![image](https://user-images.githubusercontent.com/184547/54514084-6fe97a80-4959-11e9-81cf-771fa6f1796d.png)

**Comment by pelikhan** [comment]
The strings are translated but not validated so they don't show up. Are you a proofreader?

**Comment by stritti** [comment]
Okay. Thanks. On Thursday I will have Girlsday workshop and looking forward German version.
No I am no proofreader but thought on beta the translated text will be shown without validation.
