### ISSUE TITLE
Error shows when converting "radio dashboard" code from "JavaScript" to "Blocks"

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#1904]
**Describe the bug**
Error shows when converting "radio dashboard" code from "JavaScript" to "Blocks"

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/examples/radio-dashboard
2. Copy the code to https://makecode.microbit.org/beta#editor JavaScript content pane
3. Click "Blocks" to switch to blocks mode and observe

**Expected behavior**
There should not show error when converting code from "JavaScript" to "Blocks"

**Actual behavior**
Error shows when converting "radio dashboard" code from "JavaScript" to "Blocks"
![issue30601](https://user-images.githubusercontent.com/23466737/53864662-0f3c7280-4028-11e9-96e6-ae09feb51cfc.gif)

**Comment by pelikhan** [comment]
This is advanced typescript code using classes. I think it is ok to refuse to go back to blocks.

**Comment by abchatra** [comment]
This is fixed.

**Comment by abchatra** [comment]
in /beta
