### ISSUE TITLE
Error shows when converting "Micro: Coin" code from "JavaScript" to "Blocks"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1905]
**Describe the bug**
Error shows when converting "Micro: Coin" code from "JavaScript" to "Blocks"

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/projects/micro-coin
2. Copy the code to https://makecode.microbit.org/beta#editor JavaScript content pane
3. Click "Blocks" to switch to blocks mode and observe

**Expected behavior**
There should not show error when converting code from "JavaScript" to "Blocks"

**Actual behavior**
Error shows when converting "Micro: Coin" code from "JavaScript" to "Blocks"
![issue306002](https://user-images.githubusercontent.com/23466737/53869775-d609ff80-4033-11e9-97a9-80fbbaa26aa1.gif)

**Comment by pelikhan** [comment]
micro:coin uses a package that needs to be added to the project.
