### ISSUE TITLE
Unable to find extension in offline app

### ISSUE THREAD

**Issue by kiate** [Microsoft/pxt-microbit#1907]
**Describe the bug**
I managed to install and run the newly released [Makecode offline](https://makecode.microbit.org/offline-app) but I couldn't find "reromicro" through its extension search. I still can add it in via github URL "[https://github.com/rerokit/pxt-reromicro](https://github.com/rerokit/pxt-reromicro)" though. The strange part is that other third-party extensions, eg: hummingbird-bit which is approved about the same time with reromicro can be found. 
Is there any problem with this extension's repo that causes this exclusion from the search result?

**To Reproduce**
1. Go to 'Extensions' of the offline app
2. Type in 'reromicro' at the search bar & click "Search"
3. It shows "We couldn't find any extensions matching 'reromicro'."

**Expected behavior**
Be able to find this approved extension just like how it works in the web version.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64-bit (version 1809)
- makecode.microbit.org version:  1.2.13
- Microsoft MakeCode version:  4.4.7
- microbit runtime version:  v2.1.1

**Comment by jwunderl** [comment]
There is no problem with your repo -- the offline app just uses the version of the ``targetconfig.json`` included with the release. In this case, that's v1.2.13, and ``hummingbird-bit`` is the last one included in the approved list there. The ``reromicro`` was first included in v1.2.19, so it will show up like it does on the website when the next version of the offline app is released.

**Comment by kiate** [comment]
Thanks for the clarification!
