### ISSUE TITLE
 "Turtle" code only run about 1 minute on hardware and reset button doesn't work on hardware

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1908]
**Describe the bug**
 "Turtle" code only run about 1 minute on hardware and reset button doesn't work on hardware

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/projects/turtle
2. Copy "Spiral" or "Scanner" code to https://makecode.microbit.org/beta#editor (JavaScript editor)
2. Download each example code and copy code to hardware
2. Observe hardware about 1 minute and press reset button

**Expected behavior**
The code should always run on hardware and reset button should 

**Actual behavior**
 "Turtle" code only run about 1 minute on hardware and reset button doesn't work on hardware

**Comment by abchatra** [comment]
@Helen09 Does this work on the live site?

**Comment by Helen09** [comment]
@abchatra This bug doesn't repro on live site

**Comment by pelikhan** [comment]
This bug is probably a duplicate of https://github.com/Microsoft/pxt-microbit/issues/1865 (uses a mutable image)
