### ISSUE TITLE
Documentation link is too close to the border-left on IE

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1914]
**Describe the bug**
Documentation link is too close to the border-left on IE

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "Help" -> "Reference" ->  click link on top-right corner to open documentation in new tab
3. Observe the documentation link on left

**Expected behavior**
![Issuecompare312](https://user-images.githubusercontent.com/23466737/54188916-af444100-44eb-11e9-944f-692a64a9ae74.PNG)

**Actual behavior(IE)**
Documentation link is too close to the border-left on IE
![Issue31201](https://user-images.githubusercontent.com/23466737/54188950-bff4b700-44eb-11e9-85c1-8638a84ec6fd.gif)

**Additional info:**
This bug only repro on IE and it is not related to screen size

**Comment by abchatra** [comment]
This is P3 and wont' fx
