### ISSUE TITLE
any type and typeof operator

### ISSUE THREAD

**Issue by FranklinWhale** [Microsoft/pxt-microbit#1915]
**Describe the bug**
In PXT 4.4, both `any` and `typeof` are disallowed with error shown if used.
![image](https://user-images.githubusercontent.com/8416067/54221637-e2f48a80-452e-11e9-8047-80e0f4e370e3.png)
In PXT 5.5, no error is displayed on the JavaScript editor but the code does not run.
![image](https://user-images.githubusercontent.com/8416067/54221776-1d5e2780-452f-11e9-84b2-34d131795214.png)
![image](https://user-images.githubusercontent.com/8416067/54221684-f6075a80-452e-11e9-872d-1863d1a55ff9.png)

**To Reproduce**
1. Go to https://makecode.microbit.org/beta
2. Switch to JavaScript
3. Paste the code below to the editor
```ts
function test(x?: any) {
    basic.showString(typeof x);
}
test(true);
test("x");
test(1);
test({});
test([]);
test();
```

**Expected behavior**
Either the use of `any` and `typeof` is disallowed or the code should run.

**Comment by FranklinWhale** [comment]
It appears that `any` type is now supported in PXT 5.5 because the code below works fine:
```ts
class A {

}
class B extends A {

}
function test(a: any) {
    basic.showString(a instanceof A ? "T" : "F");
}
test(new A());
test(false);
test(new B());
```

**Comment by riknoll** [comment]
Yep, `any` is supported now! See https://makecode.com/language

`typeof` should also be supported so this looks like a real bug.

**Comment by riknoll** [comment]
Works on hardware, I'll add sim support
