### ISSUE TITLE
Dialog still shows "Project has no name" after inputting a new name

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1917]
**Describe the bug**
Dialog still shows "Project has no name" after inputting a new name

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "Micro: bit" or "Home" 
3. Input a new project name in the text box and observe

**Expected behavior**
Dialog should show "Project has new name" after inputting a new name

**Actual behavior**
Dialog still shows "Project has no name" after inputting a new name
![Issue31301](https://user-images.githubusercontent.com/23466737/54259952-6d2a0680-45a2-11e9-931f-54eb5a3c1248.gif)

**Comment by abchatra** [comment]
This is by design.
