### ISSUE TITLE
Could Show console buttons be included in the portrait simulator view?

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#1919]
**Is your feature request related to a problem? Please describe.**

When the browser window has a portrait aspect ratio, there are no "Show console" buttons.

This is the case for all browsers on all platforms but is particularly relevant for tablets and phones.

**Describe the solution you'd like**

Could buttons be added?

**Describe alternatives you've considered**

**Comment by pelikhan** [comment]
@abalone23 @shakao we should fix this.

**Comment by abchatra** [comment]
@jwunderl while you are at tablet UI changes. Take a look at these.
