### ISSUE TITLE
bluetooth data feed

### ISSUE THREAD

**Issue by inibara** [Microsoft/pxt-microbit#192]
we need to port data from the microbit to an excel hack using bluetooth...students are creating instruments to measure wind speed and direction that will need to be linked to a PC for live data streaming...is this going to happen soon???peace

jb

**Comment by pelikhan** [comment]
Start from the Bluetooth documentation below. The micro:bit has a IO Pin service that allows to "read" the values of the pins via Bluetooth. You will need to ship a native app that pairs with the device and connects to the IO service.

* general bluetooth info
https://codethemicrobit.com/reference/bluetooth/about-bluetooth

* io pin service
https://lancaster-university.github.io/microbit-docs/ble/profile/#about-the-io-pin-service

**Comment by inibara** [comment]
thanks Peli...appreciate the support...if you get a chance stop by building 6 :-) peace

jb

**Comment by pelikhan** [comment]
Attach a micro:bit to the computer that acts as a gateway. Then upload a program that receives the packages and writes them to serial as JSON. From there, you serial client should be able to parse and process the data.

````
radio.onDataReceived(() => {
    led.toggle(2,2);
    radio.writeValueToSerial();
})
````

**Comment by tballmsft** [comment]
Closing this. Please reopen if you need more help.
