### ISSUE TITLE
A sprite shows on simulator after deleting "Spiral" or "Scanner" code

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1921]
**Describe the bug**
A sprite shows on simulator after deleting "Spiral" or "Scanner" code

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/projects/turtle
2. Copy "Spiral" or "Scanner" code to https://makecode.microbit.org/beta#editor (JavaScript editor)
3. Click "Advanced" -> "Extensions" -> add extension "microturtle"
4. Delete code on JavaScript content pane and observe simulator

**Expected behavior**
Simulator should have nothing after deleting code

**Actual behavior**
A sprite shows on simulator after deleting "Spiral" or "Scanner" code
![Issue31501](https://user-images.githubusercontent.com/23466737/54405769-80f47a80-4712-11e9-9b92-d7b446e294ee.gif)

**Additional info:**
This bug repro on Edge, Chrome, Firefox and IE on Windows

**Comment by pelikhan** [comment]
By design, the turtle library is still referenced.
