### ISSUE TITLE
ring tone note changed to middle C when changing the language to TC

### ISSUE THREAD

**Issue by DoraLC** [Microsoft/pxt-microbit#1922]
**Describe the bug**
ring tone note changed to middle C when changing the language to traditional Chinese. 

**To Reproduce**
1. Go to https://makecode.microbit.org/_Pb8JqhRYHLaK
2. Check that the note should be middle A. Download the code
3. Create a new project, change language to traditional Chinese. 
4. Import the code, the note changed to middle C

**Expected behavior**
Nothing will change when changing the language. 

**Screenshots**
https://drive.google.com/file/d/1I8OEa43nnSbObRu5Z9PwSZUJqjWo4zqR/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Win10 prof.
 - Browser chrome
 - Version 72.0.3626.121

**Comment by abchatra** [comment]
Likely related to https://github.com/Microsoft/pxt-microbit/issues/1900

**Comment by pelikhan** [comment]
Diplicate of 1900
