### ISSUE TITLE
403 error and deploy error

### ISSUE THREAD

**Issue by houcy** [Microsoft/pxt-microbit#1925]
I've cloned the pxt, pxt-common-packages, pxt-microbit projects and successfully built them. Then I run "pxt serve" to start the webserver.

I can visit the webpage by below link in which x.x.x.x is a public server IP :
http://x.x.x.x:3232/#local_token=dab997-07d9-48ba-7278-622217654a&wsport=3233

But when clicking the download button to save the program, below error happened in browser console:

> Error: Bad HTTP status code: 403 at /api/compile/extension; message: Error 403
>     at http://x.x.x.x:3232/blb/pxtapp.js:1030:35
> 

In fact all the /api/xxx requests failed, other requests have no error.

My question is:
1. How to solve this 403 error which seems authentication related?
2. Another error after running command "pxt deploy", please see below:
# pxt deploy
> Using target microbit with build engine yotta
>   target: v1.3.6 /root/makecode/pxt-microbit
>   pxt-core: v5.5.24 /root/makecode/pxt-microbit/node_modules/pxt-core
> Cannot find pxt.json in any of the parent directories.
> Are you in a package directory?

How to solve this deploy error?

Thanks!

**Comment by abchatra** [comment]
local serve only localhost is supported. Public IP is not supported.

**Comment by houcy** [comment]
> local serve only localhost is supported. Public IP is not supported.

Thanks, I've fixed this error.
