### ISSUE TITLE
offline app -- change language

### ISSUE THREAD

**Issue by lionyhw** [microsoft/pxt-microbit#1926]
**Describe the bug**
When language is changed in blocks page, the page always switches to JS page.

**To Reproduce**
1. Go to 'block page'
2. Click on 'more - language' button
3. The page change to JS page.

**Desktop (please complete the following information):**
 - OS: [Windows 10 Enterprise]
 - offline app Version [1.2.13]

**Comment by microbit-mark** [comment]
I've just tried this and it looks to be fixed so could be closed @jwunderl @abchatra
