### ISSUE TITLE
TODO's left in JS reference 

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1928]
User reports reference is incomplete for led.unplot()
https://twitter.com/NedtheYak/status/1107016905179561985

**To recreate**
1. Open https://makecode.microbit.org/_a2JAm5aWeFWV
2. Hover over values, see TODO in tooltip

**Expected result**
Should read "a decimal number" as with blocks
![Screenshot 2019-03-19 at 15 43 44](https://user-images.githubusercontent.com/31242877/54620260-d2c43a00-4a5d-11e9-9c4d-cc379930b21e.png)

**Comment by pelikhan** [comment]
@ganicke can you take a peek?

**Comment by ganicke** [comment]
It seems that if the parameter is not of exactly the type ``number`` then the hover tip is not displayed. Those defined as ``int`` or ``int32`` (in TS) won't display the tip. @riknoll?
