### ISSUE TITLE
WebUSB fails to upload in /beta

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-microbit#1932]
Try to pair then download to device.

**Comment by pelikhan** [comment]
Did you get WebUSB fix in?

**Comment by darzu** [comment]
Yeah, the fix went in with: https://github.com/Microsoft/pxt/pull/5303
I'll take a look. Might be a different cause

**Comment by abchatra** [comment]
@darzu please prioritize this if you can.

**Comment by pelikhan** [comment]
Probably broke this with .tsx refactoring. looking.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-microbit/blob/master/editor/tsconfig.json#L17

Looks like prepend is ignored and dapjs is not included.

**Comment by pelikhan** [comment]
Fixed.
