### ISSUE TITLE
Offline app will not install 

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1938]
microbit-support: 21318
**Describe the bug**
Trying to install the offline app results in this error
"This app will not run on your pc. To search a version of this app for your pc, please contact the app supplier."(translation 99% accurate from portuguese).  

**To Reproduce**
 On my w10 64x emachines D732-6643. Download the .exe and try to run the file
When I click the setup file it shows a message saying: This app will not run on your pc. To search a version of this app for your pc, please contact the app supplier. 

**Expected behavior**
App should run on 64bit win 10 machine.

**Comment by abchatra** [comment]
We need more information than above to debug the issue. Please ask the user to launch the system information and get all the information from there.

**Comment by microbit-mark** [comment]
Yep, already asked for this. Will update the ticket as it comes through.

**Comment by abchatra** [comment]
We found the issue with CDN corruption. Should be fixed now.
