### ISSUE TITLE
PXT_BUFFER_DATA fails to compile on MakeCode beta

### ISSUE THREAD

**Issue by firemansamm** [Microsoft/pxt-microbit#1941]
We've been informed that some of our packages are failing to compile on MakeCode beta. We've found this to be down to the following cloud compilation trace:

```
[snip]
In file included from /home/build/prj2/source/pxtbase.h:47:0,
                 from /home/build/prj2/source/pxt.h:8,
                 from /home/build/prj2/source/SSD1306_OLED/SSD1306_OLED.cpp:1:
/home/build/prj2/source/SSD1306_OLED/SSD1306_OLED.cpp: In function 'void OLED::showStringNoNewLine(pxt::String)':
/home/build/prj2/source/platform.h:6:41: error: 'class pxt::BoxedString' has no member named 'data'
 #define PXT_BUFFER_DATA(buffer) buffer->data
                                         ^
/home/build/prj2/source/SSD1306_OLED/SSD1306_OLED.cpp:33:22: note: in expansion of macro 'PXT_BUFFER_DATA'
   oled->printf("%s", PXT_BUFFER_DATA(text));
                      ^
/home/build/prj2/source/SSD1306_OLED/SSD1306_OLED.cpp: In function 'void OLED::showStringWithNewLine(pxt::String)':
/home/build/prj2/source/platform.h:6:41: error: 'class pxt::BoxedString' has no member named 'data'
 #define PXT_BUFFER_DATA(buffer) buffer->data
                                         ^
/home/build/prj2/source/SSD1306_OLED/SSD1306_OLED.cpp:39:24: note: in expansion of macro 'PXT_BUFFER_DATA'
   oled->printf("%s\n", PXT_BUFFER_DATA(text));
                        ^
ninja: build stopped: subcommand failed.
```

We suspect this might be due to https://github.com/Microsoft/pxt-common-packages/commit/08c13a08a68dd270a49c7748dd3566afb72fb70a#diff-32a5f970468fdfffc8fb945b20264c94L653 - is this change currently active in beta? (Or are we missing futher compatibility changes to string data access in C++?)

**To Reproduce**
1. Go to MakeCode beta.
2. Create a new project.
3. Add the Tinkertanker SSD1306 OLED extension.
4. Attempt to download the hex file.
5. Error.

**Expected behavior**
Project should compile successfully.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 67.0b5

cc: @zwliew @nioq

**Comment by pelikhan** [comment]
Correct, we are now using UTF8 strings and you access the string data using ``->getUTF8Data()``. We probably also need a macro to access the length ``->getUTF8Size()``
