### ISSUE TITLE
How to convert JS code into HEX file, using JS

### ISSUE THREAD

**Issue by dmosyash** [Microsoft/pxt-microbit#1947]
Hello there,

I want to create an editor of my own for micro:bit. I am using JavaScript as the base language for my editor. The programmer will use blockly blocks and then the editor will convert the blockly blocks into JS code.
And this JS code will further get converted into .hex file. I want to know how to convert JS code into hex code so that micro:bit can perform the instructions.

Thanks in Advance. Please help

**Comment by abchatra** [comment]
We have compiler from javascript to asm. Here is the spec https://makecode.com/language
You will need a compiler from your javascript to assembly code.
