### ISSUE TITLE
microbit docs don't change the locale locally that's passed in the GET parameters

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt-microbit#195]
If I go to http://localhost:3232/docs?lang=fr it doesn't use the relevant language selected (even if there exists translated .md files under _locales)

**Comment by microsoftsam** [comment]
This is very handy for testing locales locally. It's  a pain to change the browser language settings every time.

**Comment by mmoskal** [comment]
Sure! In the meantime you can create another profile in Chrome and set the language permanently there.

**Comment by abchatra** [comment]
I am going to close this one as we have work-around. We can open an issue in Microsoft\pxt when we want to address the same.
