### ISSUE TITLE
Beta: hat missing when downloading snapshot of function

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1950]
This is the snapshot downloaded from makecode.microbit.org/beta of a function with parameters

![microbit-screenshot(4)](https://user-images.githubusercontent.com/31242877/55462046-d45d3880-55ed-11e9-94d1-b041d035f92c.png)

This is the equivalent screenshot
<img width="364" alt="Screenshot 2019-04-03 at 08 49 40" src="https://user-images.githubusercontent.com/31242877/55462053-d7f0bf80-55ed-11e9-973d-f9a15b2271fb.png">

Expected:
hat should be included as part of the function when downloading the snapshot

**Comment by pelikhan** [comment]
This is size computation bug in blockly. Blockly does not take the hat into account when returning the size of the blocks -- so it gets clipped.
