### ISSUE TITLE
Memory corruption with infection on /beta

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-microbit#1954]
The infection game crashes on /beta. After pressing A+B, screen displays random images.

**Comment by abchatra** [comment]
Assumption is typescript radio is going to fix this.

**Comment by riknoll** [comment]
It did not fix it; still doesn't work with my changes in https://github.com/Microsoft/pxt-microbit/pull/2000

**Comment by riknoll** [comment]
Duplicate of https://github.com/Microsoft/pxt-microbit/issues/1752
