### ISSUE TITLE
Radio tutorials need updating for draggable params change

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#1966]
**Describe the bug**

micro-chat tutorial and possibly other tutorials say to find ``receivedString`` under Variables in the toolbox, but that flyout might not exist and doesn't contain the reporter with draggable params

**To Reproduce**

1. Go to micro-chat tutorial step 4
2. See error

**Expected behavior**

just say to drag from the event block

**Screenshots**

![Screen Shot 2019-04-05 at 11 08 02 AM](https://user-images.githubusercontent.com/5615930/55647780-65b9df80-5793-11e9-918c-2fe8c02c03da.png)

**Comment by pelikhan** [comment]
You cannot merge this until June!!!

________________________________

**Comment by abchatra** [comment]
@ganicke lets wait till the release  needs to be done.

**Comment by ganicke** [comment]
Ok...I'll be ready.

**Comment by abchatra** [comment]
@ganicke we have a release next week. Can you make sure this is ready?

**Comment by ganicke** [comment]
Sure, I'll update it now.

**Comment by ganicke** [comment]
Keep this open until merging in https://github.com/microsoft/pxt-microbit/tree/radio-doc-parm-updates.

**Comment by abchatra** [comment]
fixed
