### ISSUE TITLE
Tutorials - When translated to Spanish, "Hint" dialog overlaps text

### ISSUE THREAD

**Issue by gushuro** [microsoft/pxt-microbit#1967]
"Hint" is translated to Spanish, but it overlaps the rest of the text.
![image](https://user-images.githubusercontent.com/5607882/55649128-0fe73680-5797-11e9-8bb2-20f291ad612f.png)

**Comment by pelikhan** [comment]
It gets worse in Italian.

**Comment by pelikhan** [comment]
Fixed by new design.
