### ISSUE TITLE
Creating a var with the same name as a default in the flyout breaks toolbox

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt-microbit#1968]
How to reproduce:
1. Create a new project
2. Create a variable called "list"
3. Open the Arrays category and try dragging out any of the blocks with list variables

Here's a GIF:

![list_flyout_break](https://user-images.githubusercontent.com/13754588/55649183-34431300-5797-11e9-8245-3baf7ab21303.gif)

**Comment by riknoll** [comment]
I think this is new functions related

**Comment by abchatra** [comment]
Fixed
