### ISSUE TITLE
Incorrect search results in My Projects

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#1969]
**Describe the bug**
Search results returning projects that don't match the search string

**To Reproduce**
1. Create several projects with different names
2. Go to the "My Projects" view
3. Search for a couple different projects

**Expected behavior**
Should only return projects matching the search string.

**Screenshots**
![search](https://user-images.githubusercontent.com/34112083/55649114-05c53800-5797-11e9-906c-cdfc55c73a80.png)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by abchatra** [comment]
Fuzzy search returns the top 3. Won't fix unless you feel strongly.
