### ISSUE TITLE
Bar graph is not the full width of the control ... only in the right 1/4

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt-microbit#197]
Run https://codethemicrobit.com/dehlbf

Code:
basic.forever(() => {
    radio.sendNumber(input.acceleration(Dimension.X));
});
radio.onDataReceived(() => {
    led.plotBarGraph(radio.receiveNumber(), 1023);
});

You will notice the bar graph only goes from the right to the edge of the "Streaming off" button. I would expect it to go the full width of the control.

**Comment by darrenge** [comment]
![bargraph](https://cloud.githubusercontent.com/assets/3943962/17537557/706e22a2-5e52-11e6-9393-6135e0f10039.jpg)

**Comment by pelikhan** [comment]
The bar graph has a fixed width. This is the current design.

**Comment by darrenge** [comment]
ok ...
