### ISSUE TITLE
Some buttons in simulator require double click

### ISSUE THREAD

**Issue by jwunderl** [Microsoft/pxt-microbit#1970]
**Describe the bug**

Some elements of the simulator require double clicks on /beta (looks like one to focus then one to input) that don't on the live site. Example with shake: (top is safari, bottom is chrome)

![2019-04-05 11 42 21](https://user-images.githubusercontent.com/5615930/55653783-6d35b480-57a4-11e9-9259-5451334a18cc.gif)

same with light sensor and other simulator button, but only in safari

**To Reproduce**

1. Go to editor in safari
2. add a block that uses a simulator feature (here, on shake with anything in it)
3. see error (need to double click instead of single click on other things)

**Desktop (please complete the following information):**

 - OS: MacOS (and also iOS I think)
 - Browser safari

**Comment by abchatra** [comment]
All browsers
