### ISSUE TITLE
Experiments don't toggle correctly in Windows 10 App

### ISSUE THREAD

**Issue by ChaseMor** [Microsoft/pxt-microbit#1975]
**Describe the bug**
In the Windows 10 app, the experiments don't correctly render that they are enabled or disabled when clicked

**To Reproduce**
1. Open the MakeCode micro:bit Windows app
2. Create a new project
3. Open the settings
4. Select "About"
5. Click "Experiments"
6. Try to enable some of the experiments

**Expected behavior**
The ribbon should accurately show whether or not the experiment is enabled or disabled 

![experiments_bug](https://user-images.githubusercontent.com/13285164/55654834-504eb080-57a7-11e9-8860-bae631fd798f.gif)

**Comment by abchatra** [comment]
@ChaseMor  nice bug

**Comment by abchatra** [comment]
Repros only on windows 10 app.
