### ISSUE TITLE
Experiments add horizontal scroll bars in Windows App

### ISSUE THREAD

**Issue by ChaseMor** [microsoft/pxt-microbit#1976]
**Describe the bug**
When an experiment is enabled and the dialog saying so is shown above the editor, a horizontal scroll bar is added to the frame.

**To Reproduce**
1. Enable Experiments

![image](https://user-images.githubusercontent.com/13285164/55655174-4b3e3100-57a8-11e9-9f0b-e2d6544715d4.png)

**Comment by pelikhan** [comment]
It also puts the simulator in the middle of the screen if you are in tablet mode. That thing should be an overlay rather pushing down the DOM.

**Comment by abchatra** [comment]
Won't fix.
