### ISSUE TITLE
How to make makecode editor looks like offline desktop app which opens with an exe file

### ISSUE THREAD

**Issue by dmosyash** [Microsoft/pxt-microbit#1978]
I have downloaded the local server of the makecode which is pxt-microbit. But to run that I have to write command `pxt serve` and it will open the editor in browser with url `localhost:3232`. I want it to start like an exe file where I only double click on the exe file and it will open the editor like an app not in browser. Please help

**Comment by abchatra** [comment]
Try the offline app. https://makecode.microbit.org/offline-app

**Comment by dmosyash** [comment]
Wow, this is what I was looking for. Is this offline app created in electron, I want to create an offline app of my own. Please tell me how you guys have achieved it. Guide me to create this editor into an app.
