### ISSUE TITLE
devices.tellMicrophoneTo not implemented

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt-microbit#198]
Documented [here](https://codethemicrobit.com/reference/devices/tell-microphone-to), although not linked to from the documentation page for devices.

**Comment by pelikhan** [comment]
Fixed in https://github.com/Microsoft/pxt-microbit/commit/9d15c4e270786a9bc87f11cb5d0366a2df106ed2

This feature was cut by the BBC.
