### ISSUE TITLE
There is no "Variables" in the toolbox in tutorial "Micro Chat"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1982]
**Describe the bug**
There is no "Variables" in the toolbox in tutorial "Micro Chat"

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta
2. Open tutorial "Micro Chat" step one by one 
3. Click to 4th step and observe 

**Expected behavior**
There should have "Variables" in the toolbox

**Actual behavior**
There is no "Variables" in the toolbox in tutorial "Micro Chat"
![Issue40802](https://user-images.githubusercontent.com/23466737/55704568-0536d680-5a0f-11e9-8a18-9df956c97fa5.gif)
![Issue40801](https://user-images.githubusercontent.com/23466737/55704672-4e872600-5a0f-11e9-8b50-e43b7442363b.PNG)

**Comment by abchatra** [comment]
This is needs a doc update. 
@riknoll probably we should add the instance of the variable to drawer, just not the set block?

**Comment by abchatra** [comment]
Duplicate
