### ISSUE TITLE
Hardware shows error "847" in tutorial "Hack Your Headphones"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1985]
**Describe the bug**
Hardware shows error "847" in tutorial "Hack Your Headphones"

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/projects/hack-your-headphones 
2. Open tutorial "Hack Your Headphones" and make hardware step by step

**Expected behavior**
Hardware should have sound 

**Actual behavior**
Hardware shows error "847" in tutorial "Hack Your Headphones"

**Comment by microbit-mark** [comment]
I have another user report error 847 when using Neopixel and Crickit packages in a program and entering a new value for pause. Downloading the new file results in the error.

https://www.youtube.com/watch?v=QJKGs8bMl7U

It doesn't appear to be a documented error in pxt or DAL @abchatra

**Comment by abchatra** [comment]
@Helen09  nice catch

@microbit-mark  additional makecode error codes are here: https://makecode.com/js/errorcodes
