### ISSUE TITLE
Beta: Function created in live editor does not have call block in beta

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1987]
micro:bit support: 21593

**Describe the bug**
Creating a function in the current live editor and then downloading and opening the same program to test in beta results in a missing 'call function' block.

**To Reproduce**
1. Go to 'https://makecode.microbit.org/_JTmCVJJXw6dj'
2. Download code
3. Drag and drop into makecode.microbit.org/beta
4. Open function menu, you do not see call block. Adding a block to the function has no effect either.

**Expected behavior**
Call function block should be visible in beta as in live

**Screenshots**
![Screen Recording 2019-04-09 at 09 27 am](https://user-images.githubusercontent.com/31242877/55785237-f81af580-5aa9-11e9-849c-206a528b8fec.gif)

**Comment by abchatra** [comment]
This is a valid scenario. Someone would create a file in old editor and will try to import to released payload from beta.

**Comment by abchatra** [comment]
Fixed

**Comment by abchatra** [comment]
Fixed
