### ISSUE TITLE
Button "A" or "B" doesn't work and "A+B" disappears if "Slow-Mo" is enabled

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1988]
**Describe the bug**
Button "A" or "B" doesn't work and "A+B" disappears if "Slow-Mo" is enabled

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Drag blocks as below shared project
https://makecode.microbit.org/_8tm2UeK4W5Rj
3. Enable "Slow-Mo" and click button "A" or "B"

**Expected behavior (live site)**
Button "A" or "B" should work whether "Slow-Mo" is enabled or not
![Issue409001compare](https://user-images.githubusercontent.com/23466737/55785757-94aeb900-5ae5-11e9-96ac-98777e6070ca.gif)

**Actual behavior (beta site)**
Button "A" or "B" doesn't work and "A+B" disappears if "Slow-Mo" is enabled
![Issue40902](https://user-images.githubusercontent.com/23466737/55785503-24a03300-5ae5-11e9-867c-9122a58d659e.gif)

**Additional info:**
This bug doesn't repro on live site
It repros on beta 
makecode.microbit.org version:  1.4.4
Microsoft MakeCode version:  5.9.4

**Comment by riknoll** [comment]
Same bug as https://github.com/Microsoft/pxt-microbit/issues/1973

We should probably bump beta
