### ISSUE TITLE
led.CopyTo is not a function

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1989]
microbit support: 21598 

**Describe the bug**
Assigning an array of images to be called on random on press of a button results in the error led.CopyTo is not a function.

**To Reproduce**
1. Go to 'https://makecode.microbit.org/_bHkEbMAq5WxV'
2. Click on 'Button A until error appears'

**Expected behavior**
Program should continue to run without error

**Desktop (please complete the following information):**
 - OS: mac 10.14/Win7
 - Browser Firefox/Chrome
 - Version 66/73

**Additional context**

**Comment by jwunderl** [comment]
The shared program gives an error when it picks a value at index 3; ``length of array { list }`` returns 3, and ``pick random 0 to 3`` returns a value between 0 and 3 *inclusive*, which might be a bit unexpected for those with prior programming experience. 

the version below works (note the ``- 1`` before picking the random number)

https://makecode.microbit.org/_7vA3JU87AULy

![microbit-screenshot (1)](https://user-images.githubusercontent.com/5615930/55821519-8a26fc00-5ab2-11e9-9a41-91d52ac18d20.png)

Without changing how ``pick random 0 to { n }`` to give back a number between 0 inclusive and n exclusive (which would break a lot of instructional materials at least), I don't think we can get the given program to work as expected. Either a better error could be provided, or a ``pick random index`` block to handle this use case more appropriately.

**Comment by abchatra** [comment]
This is a bug in the user code. Array has 3 elements and you access luettelo[3] you are going to get undefined.
