### ISSUE TITLE
Feature: indexOf block

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#1990]
**Is your feature request related to a problem? Please describe.**
it would be useful to have a block representing indexOf for example to show the position of a character in a string. Not sure if this would fit within the text menu or elsewhere.

**Describe the solution you'd like**
https://makecode.microbit.org/_Am86eMhpg3jJ has an example of the code working
![microbit-screenshot(6)](https://user-images.githubusercontent.com/31242877/55792633-f7d62680-5ab8-11e9-8553-dfd5a38d28c8.png)

**Comment by abchatra** [comment]
Fixed
