### ISSUE TITLE
Suppress 'user-provided content' banner on official projects

### ISSUE THREAD

**Issue by microbit-giles** [Microsoft/pxt-microbit#1991]
**Is your feature request related to a problem? Please describe.**
We are creating school lesson plan Word documents and PowerPoints that contain hyperlinks to published code examples so teachers can try projects for themselves. When clicking on a hyperlink (e.g. https://makecode.microbit.org/_Mqt25iTbMX2s ) the user is taken to a landing page with a 'user-provided content' banner which looks somewhat unprofessional coming from an official Micro:bit Educational Foundation resource.

**Describe the solution you'd like**
Could there be a way of either suppressing the 'user-provided content' banner in some way when we provide hyperlinks to published resources or some way for Microsoft and Micro:bit Educational Foundation to publish 'official' / 'curated' micro:bit resources which do not show the banner?

**Describe alternatives you've considered**
Embedding the editor for a published project works well in web pages, but we cannot embed iframes in PowerPoints and Word documents which are the preferred delivery format for teachers in the UK.

**Additional context**
If official published projects cannot be 'blessed' in the way outlined above, could the disclaimer banner be moved below the code?
![image](https://user-images.githubusercontent.com/42380137/55798173-36261280-5ac6-11e9-86f8-35ffa874d07c.png)

**Comment by martinwork** [comment]
This works:
https://makecode.microbit.org/#pub:_Mqt25iTbMX2s

**Comment by microbit-giles** [comment]
@martinwork Thank you so much, I think that is just the ticket!
