### ISSUE TITLE
Debugger breakpoints don't stop* when in on start

### ISSUE THREAD

**Issue by jwunderl** [Microsoft/pxt-microbit#1995]
**Describe the bug**

Asterisk in title for 'unless there is a pause or something that cedes the fiber'.

Breakpoints don't work in on start 

**To Reproduce**

1. open https://makecode.microbit.org/_6JvEu0JDVgsx in beta and turn on debugger
2. set breakpoints on the two 'show number' blocks
3. run debugger, see intended behavior (stops on ``show number`` in ``on start``)
4. remove ``pause``, and run debugger again
5. see error, as in gif below

![2019-04-09 16 42 15](https://user-images.githubusercontent.com/5615930/55842202-54503a80-5ae7-11e9-91c8-21a417a43af7.gif)

**Expected behavior**

Behaves properly like step 3 from above:

![2019-04-09 16 43 07](https://user-images.githubusercontent.com/5615930/55842223-629e5680-5ae7-11e9-9d35-a1807f725d88.gif)

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by abchatra** [comment]
Does this repro with arcade? We don't file bugs on experimental features.

**Comment by jwunderl** [comment]
Does not currently repro with arcade, so closing for now

**Comment by abchatra** [comment]
Add as a comment to this issue https://github.com/Microsoft/pxt/issues/4729
