### ISSUE TITLE
Block "event timestamp" can't calculate right time

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#1996]
**Describe the bug**
Block "event timestamp" can't calculate right time

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Drag blocks as below shared project
https://makecode.microbit.org/_RWt3fxXEL1ww
3. Press button "A" and then press button "B" and observe simulator

**Expected behavior**
The time result should be right

**Actual behavior** 
Block "event timestamp" can't calculate right time
![Issue41001](https://user-images.githubusercontent.com/23466737/55861129-53331200-5ba8-11e9-9d20-baed5014294a.gif)

**Additional info:**
- Please reference https://makecode.microbit.org/projects/timing-gates
- makecode.microbit.org version: 1.4.4
- Microsoft MakeCode version: 5.9.4

**Comment by DoraLC** [comment]
I think the block gives us number of microseconds so the time should be correct?

**Comment by Helen09** [comment]
I also test this code on hardware, it also shows number more than million

**Comment by DoraLC** [comment]
> I also test this code on hardware, it also shows number more than million
1 million microsecond is equal to 1 second

I tried to let microbit run the code too and I have the following result in the serial monitor:
`
« 359141                        
« 360                           
`
code: https://makecode.microbit.org/_aD5PqDAhXXcv

I think the time is accurate enough

**Comment by abchatra** [comment]
@Helen09 can you do serial.writeln and see if the right time in microsecond is printed or not?

**Comment by Helen09** [comment]
@abchatra I tried to do serial.writeln and the right time is not printed, the detail is as below
![Issue41201](https://user-images.githubusercontent.com/23466737/56015729-99b17980-5d2c-11e9-8b82-f2bf74298670.gif)

**Comment by Helen09** [comment]
@DoraLC I think the time too accurate to read for kids

**Comment by abchatra** [comment]
Closing more than an year old bugs. If this still reproduces please reopen.
