### ISSUE TITLE
Hacking STEM docs update request

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-microbit#1998]
On this page: https://makecode.microbit.org/pkg/microsoft/pxt-hacking-stem

Change from: 
For Hacking Stem activities you will need excel add-on Data Streamer as well. To download Data Streamer click here. This extension helps build the code for emitting serial data in the format required by Data Streamer excel addon.

To:
For Hacking Stem activities you will need to enable the Data Streamer Add-in in Excel . For information on enabling Data Streamer click here (https://aka.ms/data-streamer). This extension helps build the code for emitting serial data in the format required by Data Streamer.

**Comment by ganicke** [comment]
Data streamer info changed in: https://github.com/Microsoft/pxt-hacking-stem/pull/4

**Comment by abchatra** [comment]
Fixed
