### ISSUE TITLE
convert input light level to JS - automatic set var to 0

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#2]
convert input light level to JS - automatic set var to 0

1 why do you need to store light level as 0?

2 enter this code in blocks

```
let light = input.lightLevel();
```
3 then press show in code

4 
this is the code that appears
```
 let light = 0;
light = input.lightLevel();

```

2 i would expect when converting from blocks to JS, the code would appear like this

```
let light = input.lightLevel();
```

**Comment by thomasdenney** [comment]
When using the 'set item to value' and assigning some expression the code `let light = input.lightLevel()` is generated, and when typing this is in code the corresponding blocks are correctly generated, so I think this issue can be closed.
