### ISSUE TITLE
Malformed JSON produced by radio.writeValueToSerial

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt-microbit#200]
The [radio.writeValueToSerial](https://github.com/Microsoft/pxt-microbit/blob/master/libs/microbit-radio/radio.cpp#L107) method, used for data streaming, produces malformed JSON:

![azure-2](https://cloud.githubusercontent.com/assets/20356546/17555866/209b0f1c-5f09-11e6-97a7-6328ef8c4144.png)

The keys should be quoted.

**Comment by pelikhan** [comment]
Fixed in https://github.com/Microsoft/pxt-microbit/commit/ffd4d9653931f88baedc3773cbba50df26137b0e
