### ISSUE TITLE
Flash memory usage meter

### ISSUE THREAD

**Issue by kiate** [microsoft/pxt-microbit#2001]
**Is your feature request related to a problem? Please describe.**
Is there a way for us to know the flash memory usage of our program? I have a program with Neopixel, OLED and rero:micro extensions and barely 450 lines of code. But I ran into compilation error. Troubleshooting led me to Music blocks. I commented all the Music blocks in my program and it compiled successfully. Then I take out some of the functions from Music blocks and use them as custom blocks, it works too. So my wild guess is that I've hit the max. Possible? Any way to verify this, with some workaround may be?

**Describe the solution you'd like**
Ideally, it's good to have a meter/bar/xx% showing the current memory usage of a program right in MakeCode.

**Describe alternatives you've considered**
Otherwise, any workaround that can be done to check the usage. Perhaps put a log file in micro:bit once the error occurs.

**Additional context**

**Comment by riknoll** [comment]
There is a way to check, but it's pretty hidden:

1. Go to JavaScript
2. Download your program (needs to be downloaded at least once)
3. In the explorer on the left, go to built > binary.asm
4. In the comments at the top of that file you should see the percentage of flash used

Here's a GIF:

![flash_percent](https://user-images.githubusercontent.com/13754588/55981568-d8233780-5c4b-11e9-9dbb-e41828579107.gif)

Do we currently give an error message when you run out of flash @mmoskal ?

**Comment by mmoskal** [comment]
I believe we do.

**Comment by kiate** [comment]
Thanks! That's helpful! I'll give it a try.

**Comment by kiate** [comment]
This is what I see in my binary.asm:
-------------------------------------------------------------------------------
; code sizes (bytes): 14712 (incl. 0 frags, and 556 lits); src size 0
; assembly: 11643 lines; density: 27.02 bytes/stmt
; total bytes: 238968 (98.5% of 237.0k flash with 3720 free)
; peep hole pass: 339 instructions removed and 966 updated
; peep hole pass: 220 instructions removed and 124 updated
; peep hole pass: 0 instructions removed and 0 updated
-------------------------------------------------------------------------------

Just want to confirm that I'm on the right track...
The flash memory used in this program is 238968 bytes (98.5%) and I still have 3720 bytes free?
If that's the case, the 'blank' program in your example GIF already has 218444 bytes (90.0%) occupied, indicating that flash available for user program is only 10.0%. Am I right?

**Comment by woutput** [comment]
This may be strongly related to #2577

**Comment by abchatra** [comment]
There is a workaround today and the feature request is for advanced users.
