### ISSUE TITLE
"Show console" doesn't show when putting "serial write number" under "on button pressed"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#2004]
**Describe the bug**
"Show console" doesn't show when putting "serial write number" under "on button pressed"

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Drag blocks as below shared project
https://makecode.microbit.org/_hddVmXg08Vrc
3. Press button "A" and then press button "B" and observe simulator

**Expected behavior**
"Show console" should show under simulator

**Actual behavior**
"Show console" doesn't show when putting "serial write number" under "on button pressed"
![Issue41202](https://user-images.githubusercontent.com/23466737/56017842-0891d100-5d33-11e9-95c1-761ebb99d978.gif)

**Comment by abchatra** [comment]
You need writeline after write number to flush the code. Otherwise it will not show. Can you validate?

**Comment by Helen09** [comment]
Sure, I have validated that need writeline after write number to flush the code
