### ISSUE TITLE
"Duplicate" duplicating blocks below selected block

### ISSUE THREAD

**Issue by jwunderl** [Microsoft/pxt-microbit#2007]
**Describe the bug**

"Duplicate" duplicates all blocks attached below the selected block now

**To Reproduce**

1. Go to microbit.makecode.com/beta
2. create a series of blocks
3. right click on the top most block and select 'duplicate'
4. See error (gifs below)

**Expected behavior**

duplicate should create a copy only of the blocks 'inside' the current block (e.g. the statements in an event handler), not the ones below it

**Screenshots**

### live site behavior:

![2019-04-15 17 50 06](https://user-images.githubusercontent.com/5615930/56174430-50b92980-5fa7-11e9-807a-bf6207e3da0d.gif)

### beta site behavior

![2019-04-15 17 49 34](https://user-images.githubusercontent.com/5615930/56174435-56167400-5fa7-11e9-9f34-58df1198f115.gif)

**Additional context**

looks like it's just duplicate thing <next> child of the blocks as well / no longer ignoring those

**Comment by shakao** [comment]
Looks like blockly removed the "delete next blocks" from the duplicate function in this change: https://github.com/google/blockly/pull/1817/files#diff-5b6a36b94fcf664e4f8481d6a12eee63L256

**Comment by jwunderl** [comment]
Isn't that line just split to https://github.com/google/blockly/pull/1817/files#diff-5b6a36b94fcf664e4f8481d6a12eee63R260 if it's not in a comment?

**Comment by shakao** [comment]
Oh hm, you're right--we must have got rid of deleteNext at some point? Just checked their playground and they don't copy the next blocks, so I guess I'll add it back in.

**Comment by jwunderl** [comment]
Sounds good, just filed because it was a change from previous behavior, but not necessarily a bad one as it does match drag behavior, as mentioned offline~

**Comment by abchatra** [comment]
This is by design now?

**Comment by jwunderl** [comment]
Yes, it changed to match the behavior of dragging the block out
