### ISSUE TITLE
Code in the toolbox in JavaScript mode is empty

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#2008]
**Describe the bug**
Code in the toolbox in JavaScript mode is empty

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta
2. Scroll down to "Blocks To JavaScript" and open tutorial "Hello JavaScript" or "Writing Code"
3. Navigate to https://makecode.microbit.org/beta#editor
4. Click "JavaScript" and switch to JavaScript content pane
5. Drag code from the toolbox
![image](https://user-images.githubusercontent.com/23466737/56277455-f8189680-6136-11e9-9327-8dfb1abbdeb5.png)

**Expected behavior(live site)**
User should can drag code from the toolbox on JavaScript mode
![Issue41702](https://user-images.githubusercontent.com/23466737/56277803-9d336f00-6137-11e9-8182-0f65e565da5a.gif)

**Actual behavior(beta site)**
Code in the toolbox in JavaScript mode is empty
![Issue41701](https://user-images.githubusercontent.com/23466737/56277679-64939580-6137-11e9-84c8-793bbe8e893b.gif)

**Additional info:**
1. makecode.microbit.org version: 1.4.5
2. Microsoft MakeCode version: 5.9.13

**Comment by pelikhan** [comment]
Nice catch

**Comment by pelikhan** [comment]
Fixed.
