### ISSUE TITLE
”Bluetooth Download“ can't be enabled on Edge&Firefox

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2011]
**Describe the bug**
”Bluetooth Download“ can't be enabled on Edge&Firefox

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click “More..." -> "About" -> "Experiments" -> enable "Bluetooth Download"

**Expected behavior(Chrome)**
”Bluetooth Download“ should can be enabled on each browser
![Issue41902](https://user-images.githubusercontent.com/23466737/56418321-2af29400-62c9-11e9-9afb-efc1392c352d.gif)

**Actual behavior(Edge, Firefox & IE)**
”Bluetooth Download“ can't be enabled on Edge&Firefox
![Issue41901](https://user-images.githubusercontent.com/23466737/56418334-35149280-62c9-11e9-9ace-57715a6728a9.gif)

**Additional info:**
1. makecode.microbit.org version: 1.4.6
2. Microsoft MakeCode version: 5.9.14

**Comment by pelikhan** [comment]
By design, WebBLE is chrome / Edgium only

**Comment by abchatra** [comment]
Yes by design. May be we shouldn't show the card in edge & firefox in experiments.

**Comment by Helen09** [comment]
closed as by design
