### ISSUE TITLE
Screenshot is empty on Edge when taking screenshot first time

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2012]
**Describe the bug**
Screenshot is empty on Edge when taking screenshot first time

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click “More..." -> "About" -> "Experiments" -> enable "Simulator Screenshots"
3. Drag block "show icon" and put it under forever
4. Click "take screenshot" under simulator and open the picture

**Expected behavior(Chrome&Firefox)**
”Bluetooth Download“ should can be enabled on each browser

**Actual behavior(Edge)**
Screenshot is empty on Edge when taking screenshot first time
![Issue41903](https://user-images.githubusercontent.com/23466737/56419841-41e7b500-62ce-11e9-8120-151fb8cb4f87.gif)

**Additional info:**
1. makecode.microbit.org version: 1.4.6
2. Microsoft MakeCode version: 5.9.14
3. This bug only repro on Edge

**Comment by abchatra** [comment]
Won't Fix old bugs on Edge or IE.
