### ISSUE TITLE
Project organisation - directory structure?

### ISSUE THREAD

**Issue by rhubarbdog** [Microsoft/pxt-microbit#2013]
**Is your feature request related to a problem? Please describe.**
I'm not a heavy user of Blocks, but my project list is becoming cluttered. And most recent project first makes finding older projects an impractical task

**Describe the solution you'd like**
Some File Manager capabilities  to use windows 3.1 parlance.  The ability to create directories would be useful. A sort button offering at least by name, in order, reverse order. It would be nice to have a project description of say 256 characters, but i guess that would make importing from a .hex problematic

**Describe alternatives you've considered**
None, there aren't any

**Comment by jwunderl** [comment]
The most recent [beta](https://makecode.microbit.org/beta) release has a project manager included. You can currently access it by clicking on `My Projects` or scrolling to the right until it ends with a `See all projects` card. It currently has sorting by name, and when the project was last updated.

![2019-04-19 21 14 54](https://user-images.githubusercontent.com/5615930/56452653-9304a280-62e8-11e9-891a-5a23d0d78360.gif)

**Comment by pxtravis** [comment]
fixed in betA
