### ISSUE TITLE
Project Saving / Export

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#202]
The way a project is saved locally and automatically opened restricts you to working on one project at a time. I wish it was possible to save and name projects and restore them separately.

Ignore me! You can open projects and provided you game them a title, they're all there. Maybe this is new? Never noticed this before!

**Comment by pelikhan** [comment]
It's always been there :). Also, the full project source is saved in the .hex file.

Answered in FAQ: https://github.com/Microsoft/pxt-microbit/commit/271128c07583981b535935cb89f7dbe6fa6e4549

**Comment by bluetooth-mdw** [comment]
Excellent, thanks. Spotted the capability about 500ms after submitting the issue :-)
