### ISSUE TITLE
Import project sometimes deletes my work

### ISSUE THREAD

**Issue by rhubarbdog** [Microsoft/pxt-microbit#2020]
**Describe the bug**
I want to create a project similar to some blocks i have previously created. I share the previously created blocks and import them. Once (i think) it creates 2 copies of the project usually it just allows me to effectively edit the previously created blocks

**To Reproduce**
1) create a new project and share it
2) import the new project
3) edit it and give it a new name 
4) There is only the new project the original copy has been deleted

**Expected behavior**
A new copy of the project to have been created. The import procedure should detect the name clash and either prompt for a new name or give the project a suffix to make it a unique name

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser firefox
 - Version 63.0.3

**Comment by abchatra** [comment]
What do you mean original copy is deleted. Can you share the URL of the original copy? We never delete the shared project and it is readonly? 

If you rename the project, in the home page only renamed project will be present.

**Comment by rhubarbdog** [comment]
Yes i have the shared url still. But only one project called "imported". When you import a project of the same name it replaces it. Just try it create some blocks called "new001". Share them import a copy. There is only one "new001"  not 2 as expected

**Comment by abchatra** [comment]
I can repro this bug. Thanks @rhubarbdog

**Comment by abchatra** [comment]
@jwunderl can you please take a look at this?
