### ISSUE TITLE
Don't force saving of empty untitled projects

### ISSUE THREAD

**Issue by HyperDuino** [Microsoft/pxt-microbit#2022]
If a user clicks on New Project, but doesn't actually add any blocks (I do this often just to explore block categories, block appearance, confirm editor features, etc. etc.) the editor forces the user to save the project:

![image](https://user-images.githubusercontent.com/13832091/56686798-a6699200-6689-11e9-81c5-a7ba4a4ddf67.png)

Not only does this take time to deal with, there is no "discard" button as an alternative do "done".  Eventually it's necessary to then take time to delete all the empty 'untitled' projects that get created.

Feature request:  add a 'Discard" (or equivalent) button to the save dialog, and consider whether to skip that dialog entirely in cases where no content has been added to a project that is still named 'untitled'.

**Comment by abchatra** [comment]
Beta gives option to skip

![image](https://user-images.githubusercontent.com/6107272/56693516-80e48480-6699-11e9-81ab-e0b46c86b8f7.png)

**Comment by abchatra** [comment]
makecode.microbit.org/beta

**Comment by abchatra** [comment]
We will ship around june.

**Comment by HyperDuino** [comment]
Clicking on "skip" still creates a project called "untitled".  It appears that skip has the same result as "save" if untitled is not renamed. 
![image](https://user-images.githubusercontent.com/13832091/57479651-c20c9500-7252-11e9-9821-985c7987c216.png)

**Comment by abchatra** [comment]
We don't delete student projects on purpose (As they might accidently click on Skip). You can use script manager to delete the projects.

**Comment by HyperDuino** [comment]
Then what's the functional difference between "Save" and "Skip"?

**Comment by abchatra** [comment]
There is no difference. Gives you an option to skip naming your project.  Intent of dialog is "Naming your project" and you can chose not to name it. It is arguable if this is a good design pattern. 

We can't delete student projects as many students don't even read the dialogs and just click on things.
