### ISSUE TITLE
reference directive in user code causes error

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2029]
**Describe the bug**

reference directive in user code causes an error with no error message

**To Reproduce**

1. Go to https://makecode.microbit.org/_7UUcpuTL7ibb
2. See error

```typescript
/// <reference path="./core/basic.ts" />

let x = 1
basic.showNumber(x + x + 42)
```

**Expected behavior**

I would guess it should just be ignored completely in user code? or at least list out an error when hovering over it

**Comment by abchatra** [comment]
There is a message now with the not found file. Fixed
