### ISSUE TITLE
Embedding published project not working?

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#203]
Maybe I don't understand what an embedded project should look like but if I publish and then use the embed HTML in my blog, what gets rendered is the micro:bit simulator rather than the blocks themselves.

**Comment by pelikhan** [comment]
We are working on embedding a source code view.

**Comment by pelikhan** [comment]
Try the source embedding at https://codethemicrobit.com/beta .

**Comment by pelikhan** [comment]
![image](https://cloud.githubusercontent.com/assets/4175913/17757895/6d6e50e2-649f-11e6-8964-1380d821af9d.png)
