### ISSUE TITLE
When creating a GitHub repo through makecode.microbit.org the generated README.md file has two incorrect URLs

### ISSUE THREAD

**Issue by FrogletApps** [Microsoft/pxt-microbit#2034]
**Describe the bug**
When creating a new GitHub repo through the import menu the README.md file that's created has two invalid URLs in it:  "https://makecode.microbit.org/packages/approval" and "https://makecode.microbit.org/packages/approval".  I asume packages needs replacing with extensions for both of those.

Here is an example of a generated file with the incorrect URLs
https://github.com/FrogletApps/microbit-readme-typo-demo/blob/master/README.md

**To Reproduce**
1. Go to 'https://makecode.microbit.org/'
2. Click on the import button (this is assuming you have already followed the steps here (https://makecode.com/extensions/getting-started) to link your GitHub account)
3. Click on the button labelled 'Your GitHub Repo...'
4. Click 'Create new'
5. Enter a name and description
6. Click 'Go ahead'
7. See the README.md file 

**Expected behavior**
Instead of "https://makecode.microbit.org/packages/approval" and "https://makecode.microbit.org/packages/approval" the URLs should be "https://makecode.microbit.org/extensions/approval" and "https://makecode.microbit.org/extensions/approval"

**Comment by abchatra** [comment]
@ganicke is this something you can fix or does this require product change?

**Comment by ganicke** [comment]
I thought we dealt with that using a redirect in a `*-ref.json`. Anyway, I'll see if the whole `packages` thing can be changed.

**Comment by ganicke** [comment]
@abchatra the `README.md` template was updated to format the links correctly on 2-16, see: https://github.com/Microsoft/pxt/commit/56d394c0952c5ebf4f147d5905e31ac4592f71f3#diff-6ed0ed60a8c936824d5bf782c1f2f6bf

micro:bit will catch this in the next release or maybe this works now in https://makecode.microbit.org/beta.

**Comment by abchatra** [comment]
Thanks @ganicke Fixed in beta.
