### ISSUE TITLE
String::getUTF8Data() -> Compilation Failed

### ISSUE THREAD

**Issue by DominikKoller** [microsoft/pxt-microbit#2038]
In the online makecode editor, when using the function
String::getUTF8Size() 
or
String::getUTFData()
I often get the error 'Compilation failed. Please check your code for errors'.
The editor then shows that there is one error in Math.ts, however on navigating there it seems to disappear.
I cannot reliably reproduce it - I get the error when trying to compile this:
https://makecode.microbit.org/_hDRiJs4ujCVH
but sometimes upon reloading, or changing the code then changing it back, it disappears (also not reliably though).

When running locally with _pxt serve_, this error does not appear. However it happens both in the online makecode editor and in the online makecode editor beta.

I did not have this error when not using any of these two functions.
Since this cannot be reliably reproduced, here are screenshots:

![screenshot0](https://user-images.githubusercontent.com/4418478/57080111-c6343200-6ce9-11e9-8c08-d0155370b8c7.PNG)
![screenshot1](https://user-images.githubusercontent.com/4418478/57080167-e237d380-6ce9-11e9-9678-c6fe39727224.PNG)
![math](https://user-images.githubusercontent.com/4418478/57080192-e95ee180-6ce9-11e9-9562-6e2559aafc4b.png)
Upon changing the code, then changing it back to exactly what it was, it sometimes disappears:
(the following was done with the exact same code as the screenshots above)
![working](https://user-images.githubusercontent.com/4418478/57080260-13180880-6cea-11e9-982d-9f0cb6c37513.PNG)

 - OS: Windows 10
 - Chrome 73.0.3683.103 (Official Build) (64-bit)
-  Makecode online editor and Makecode online editor beta

**Comment by jwunderl** [comment]
Those functions were added in with unicode support in January, so they won't work on the regular site. The ``PXT_STRING_DATA`` macro can be used to access string data in a way compatible with both the /beta site and live site; those macros are from https://github.com/Microsoft/pxt-common-packages/pull/782, and for an example use, see https://github.com/Tinkertanker/pxt-oled-ssd1306/pull/17

The link you shared fails for me on the live site, but succeeds on /beta; do you happen to have a case where it is failing in /beta as you mentioned? It definitely shouldn't result in an error there

**Comment by DominikKoller** [comment]
Ah right, thank you.

I did get the error on /beta as well with the project I linked, but now I don't. Before, it also appeared quite random as for when I would get it and when I wouldn't (in /beta). 

I definitely still get the same error in a larger project:
![image](https://user-images.githubusercontent.com/4418478/57092254-e3c1c580-6d02-11e9-8e7b-181592438143.png)
This is the project
https://github.com/DominikKoller/pxt-Parties
(on commit 84ee1e1ca4528020fd4ed3ab539add40c2817f94, currently master)
with the specific lines 232 and 238 of parties.cpp un-commented.

**Comment by DominikKoller** [comment]
Actually wait this is strange, it should complain about len being declared twice instead
Anyway if I remove line 233 in the above screenshot, I do not get the error (but am very confident that I got it before on the link I sent)

**Comment by DominikKoller** [comment]
Hm I can't reproduce this now in /beta either. Possibly I have made a mistake there and got mixed up with /beta and the regular site.
Can you tell me why it is that the error appeared in Math.ts and how to interpret that if it happens in the future?

**Comment by abchatra** [comment]
Issue fixed.
