### ISSUE TITLE
Typo in enum value BackAndWhite

### ISSUE THREAD

**Issue by editicalu** [microsoft/pxt-microbit#2041]
The micro:bit block for the LED mode "Black and white" uses the enum value `BackAndWhite`. However, the visual editor shows the 'black and white' option.

## Visual 
![Black and white](https://user-images.githubusercontent.com/22838908/57192249-a3468f80-6f2e-11e9-9d8a-c0f3ac5f5b51.png)

## JavaScript

```ts
led.setDisplayMode(DisplayMode.BackAndWhite)
```

## Reference

The reference talks about `BlackAndWhite`, but the user gets an error when he tries to add this.

![The error the user recieves](https://user-images.githubusercontent.com/22838908/57192309-3b447900-6f2f-11e9-90f8-fa13074c6dcb.png)

**Comment by Helen09** [comment]
This issue doesn't repro as I tried
![Issue51301](https://user-images.githubusercontent.com/23466737/57593399-d19b1f00-756d-11e9-9902-aa971fdc873b.gif)

**Comment by editicalu** [comment]
It clearly states `BackAndWhite` (without an L in bLack) in your screencast. The error occurs when entering `BlackAndWhite` manually.
