### ISSUE TITLE
Clicking pair button doesn't work 

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2045]
**Describe the bug**
Clicking pair button doesn't work 

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click “More..." -> "Project Settings" -> click button in the new page

**Expected behavior**
Button should work

**Actual behavior**
Clicking pair button doesn't work 
![Issue51401](https://user-images.githubusercontent.com/23466737/57668186-117b0880-7639-11e9-9fef-6612dbf3a271.gif)

**Additional info:**
1. makecode.microbit.org version: 1.4.7
2. Microsoft MakeCode version: 5.11.6
3. This issue doesn't repro on live site, it only repros on beta

**Comment by abchatra** [comment]
@Helen09 what browser is this?

**Comment by abchatra** [comment]
@pelikhan I can reproduce this in chrome as well. What is the expected behavior?

**Comment by abchatra** [comment]
This is a regression from live.

**Comment by Helen09** [comment]
@abchatra This bug repro on Edge, Chrome, Firefox & IE
