### ISSUE TITLE
Tutorial can't be opened normally on Edge

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2046]
**Describe the bug**
Tutorial can't be opened normally on Edge

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta
2. Choose one tutorial such as "Flashing Heart" and open it one by one

**Expected behavior**
Tutorial should can be opened normally

**Actual behavior(Edge)**
Tutorial can't be opened normally on Edge
![Issue51402](https://user-images.githubusercontent.com/23466737/57677855-6713dd00-765a-11e9-99f7-59a4ecdef57a.gif)

**Additional info:**
1. makecode.microbit.org version: 1.4.7
2. Microsoft MakeCode version: 5.11.6
3. This issue doesn't repro on live site, it only repros on beta
4. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)

**Comment by abchatra** [comment]
If this is reproducible we need to put some workaround. Flashing heart is first tutorial and we need to work on edge.

**Comment by Helen09** [comment]
This bug is not repro on latest version, closed as not repro
1. makecode.microbit.org version:  1.4.10
2. Microsoft MakeCode version:  5.12.14
