### ISSUE TITLE
The corrrect spelling and capitalisation of your project

### ISSUE THREAD

**Issue by rhubarbdog** [microsoft/pxt-microbit#2049]
Hi,
I'm planning to do some authoring of a microbit website. I plan to provide my listings in Micro"Python.  But without doubt will be guiding users into using blocks.  What's the official spelling and capitalisation of the project.  Is it  "Microsoft MakeCode Blocks"? should the blocks be capitalised?

Thanks
rhubardog

**Comment by abchatra** [comment]
"Microsoft MakeCode" is the name of the product. There is no Blocks @Jaqster
