### ISSUE TITLE
Should division produce integer or real number results?

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#205]
I'm grabbing the pitch value using the rotation block and then dividing it by 30. I expected to get a real number e.g. 45 / 30 = 1.5 but I seem to always get an integer which I think is being rounded down or maybe has the decimal part truncated. This may just be the way the number is displayed. Can you clarify here and perhaps in the reference docs what type of result the / operator should produce please?

![image](https://cloud.githubusercontent.com/assets/8341666/17728543/9ddafa20-6457-11e6-8259-0d79e230db57.png)

**Comment by pelikhan** [comment]
Currently, codethemicrobit does not have floating point numbers... All operations are using integer arithmetics.

**Comment by thomasdenney** [comment]
Currently the docs state 'returns the quotient of the two numbers', but I'm not sure if this would be clear to Year 7s.

![div](https://cloud.githubusercontent.com/assets/20356546/18269143/c8357e86-741e-11e6-8e92-6ab53ad133c6.PNG)

The government's [spec for KS2 maths](https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/443889/2016_KS2_Mathematics_framework_PDFA_V2.pdf) (page 15) suggests that the term 'remainder' will definitely have been introduced by Year 7, but I couldn't find any suggestion that the term 'quotient' would be explicitly introduced in KS2 or KS3 maths.

**Comment by abchatra** [comment]
There is no plan to support floating point numbers for microbit. I am closing this for now. Docs issue will be taken up as part overhaul of the documentation.
