### ISSUE TITLE
Feature: Mass project download

### ISSUE THREAD

**Issue by microbit-giles** [microsoft/pxt-microbit#2052]
**Is your feature request related to a problem? Please describe.**
I had a bit of a scare this morning when I thought my laptop had died. The only things I thought I'd miss were the MakeCode projects in my browser storage. Could we have a mass download / backup button so we could save and restore multiple projects in another browser / computer?

**Describe the solution you'd like**
A button to allow mass download of MakeCode projects either as a ZIP file that would expand into HEX files or as a file that could be restored to another browser / computer.

**Describe alternatives you've considered**
Downloading all HEX files manually - time consuming and inconvenient. Publishing all my projects and making a list of their URLs, also time-consuming.

**Additional context**
Would be a nice companion to mass delete features in the beta.

**Comment by microbit-mark** [comment]
Several user support requests ask for this feature or could do with this to resolve their issue.

One example was for a school that wants to periodically clear the browser cache/website data. Something like a download as zip button appearing in the project manager when you select multiple files would be great.

![Screenshot 2019-05-15 at 08 57 26](https://user-images.githubusercontent.com/31242877/57768426-80249880-7703-11e9-91b1-1a32a7036210.png)

**Comment by HyperDuino** [comment]
+1  Another consideration is that in school usage, the Chromebook can be lost and replaced, or replaced as a matter of course as students go through grade levels. When moving to a new machine, all existing MakeCode programs are lost.  Even just logging into a school account on a different machine gives the appearance that all projects have been lost because they don't show up on the other machine.

**Comment by abchatra** [comment]
Tagging this as part of identity feature.

**Comment by abchatra** [comment]
We do have zip download in the release version today. Select multiple projects and download as zip

**Comment by martinwork** [comment]
@abchatra Only beta and stable have the Download ZIP button on the My Projects screen.

**Comment by abchatra** [comment]
I am closing this again as /beta has it and we will do a new release in June.
