### ISSUE TITLE
extensions home page

### ISSUE THREAD

**Issue by elecfreaks** [microsoft/pxt-microbit#2053]
**Describe the bug**
Our "iot-environment-kit" was displayed on the home page, but why is it disappearing now?
Some teachers encountered this problem when using this package to teach.
29 Mar：
![](https://i.imgur.com/kjkabCV.png)

**Comment by abchatra** [comment]
There was a bug with your extension which didn't let it load. Following  issue https://github.com/Tinkertanker/pxt-iot-environment-kit/pull/20 and we removed it as it produced an error.  Please make sure your extension is of high quality and test it when you make changes. 

We update the list every 3 months, depending on the top 10 usage statistics.
