### ISSUE TITLE
Package cannot be searched

### ISSUE THREAD

**Issue by elecfreaks** [microsoft/pxt-microbit#2056]
**Describe the bug**
Our'cutebot'package cannot be searched, 
![](https://i.imgur.com/aMrEPb8.png)
But search for'https://github.com/elecfreaks/pxt-cutebot'.
It can be searched and downloaded， also be used normally.
![](https://i.imgur.com/2id1ano.png)
![](https://i.imgur.com/wXNaBuJ.png)
> {
  "name": "Elecfreaks Cutebot",
  "url":"/pkg/elecfreaks/pxt-cutebot",
  "cardType": "package"
},

**Comment by abchatra** [comment]
This is the issue. elecfreaks/pxt-cutebot is forked from lionyhw/pxt-cutebot. We don't search the forks as there will be lots of forks. Is it possible for you to create a repo from scratch instead of forking.

**Comment by abchatra** [comment]
@mmoskal

**Comment by mmoskal** [comment]
github doesn't search forks; there is nothing in the current architecture we can do about this

**Comment by elecfreaks** [comment]
If I deleted the repo and create a new repo with current files, does it work without making other revise?

**Comment by elecfreaks** [comment]
Do as you say. Now it works.
