### ISSUE TITLE
Support for Cozir package publication

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2057]
**Describe the bug**
There apeear to be a few issues with published extension  https://github.com/letstalkscience/pxt-cozir/ that result in the docsumentation not rendering correctly and the extension not being pulled in from Github.

**To Reproduce**
1) The code [README.MD](https://github.com/letstalkscience/pxt-cozir/blob/master/README.md) is not rendered properly here https://makecode.microbit.org/pkg/letstalkscience/pxt-cozir
2) Possibly related. When attempting to add the extension to the editor, it results in a 'network request failed' message with the following console output:

```Unhandled rejection requestAsync/<@https://pxt.azureedge.net/blob/b286c6d8cf9eb01f223386d4460cc4851c38b762/pxtapp.js:955:35 c@https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:72958 [65]</</</<[22]</e.exports/T.prototype._settlePromiseFromHandler@https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:46248 [65]</</</<[22]</e.exports/T.prototype._settlePromise@https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:47048 [65]</</</<[22]</e.exports/T.prototype._settlePromise0@https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:47747 [65]</</</<[22]</e.exports/T.prototype._settlePromises@https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:49074 [65]</</</<[2]</a.prototype._drainQueue@https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:3053 [65]</</</<[2]</a.prototype._drainQueues@https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:3111 a/this.drainQueues@https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:1325```

**Expected behavior**
Readme should show the code in the docs and extension should import correct.y

**Additional context**
Raising here. @pelikhan has already supported in Slack, so this is to to ask for support  getting over this final hurdle 😄 cc @letstalkscience

Original PR https://github.com/microsoft/pxt-microbit/pull/2039

**Comment by abchatra** [comment]
Seems fixed.

**Comment by kentang1102** [comment]
hello, i am having trouble adding the cozir extension to microbit on makecode. The extension can be found and downloaded, but there is nothing happened after the download. It just didn't show up in the command list.

Could you provide me some tips?

Thanks,

Ken

**Comment by letstalkscience** [comment]
Hello Ken,

When you download the extension you should see a rocket ship icon with a category “Let’s Talk Science” appear.  Does that show up in MakeCode for you?

[Image.jpeg]


Jennifer Ferguson
Education Specialist, Professional Learning
Let’s Talk Science

Cell: 403-390-2159

letstalkscience.ca | Facebook | Twitter | Instagram
parlonssciences.ca | Facebook | Twitter | Instagram
null

We’re here to help. Whether you’re a parent, educator or youth, we have a variety of resources for you - at no cost! Explore letstalkscience.ca to find lesson ideas, videos, hands-on activities and more!

Nous sommes là pour vous aider. Que vous soyez un parent, un/e enseignant/e ou un/e jeune, nous avons une foule de ressources gratuites pour vous! Explorez parlonssciences.ca pour découvrir des idées de cours, des vidéos, des activités pratiques, et plus encore!
________________________________
