### ISSUE TITLE
Serial console output inconsistent on sim/device

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2058]
**Describe the bug**
When outputting data via serial and viewing in the console, the output is inconsistent. On the micro:bit the output is correct. 

**To Reproduce**
1. Go to 'https://makecode.microbit.org/_HPzgY9RifUKV'
2. Click on 'show console simulator' and press A to see output
3. Output of numbers stops at ~473. Trying this a few times gives different output.
4. The downloaded output does not show every value either. It starts at 108 and finishes at 504[microbit-data-16-2019-09-01-25-0100.txt](https://github.com/microsoft/pxt-microbit/files/3186002/microbit-data-16-2019-09-01-25-0100.txt)

The same program run on the micro:bit completes as expected.

Is there a limit to how much stat the simulator will output?

**Expected behavior**
Sim should have same behaviour and output as device

**Screenshots**
![serial](https://user-images.githubusercontent.com/31242877/57837679-2da6b300-77bb-11e9-8d36-4a9c0a6b63c6.gif)

**Comment by jwunderl** [comment]
Minor update: if you end with a new line (https://makecode.microbit.org/_8rzJJiTp2PwD), it will print out as expected - this is the same issue as https://github.com/microsoft/pxt-microbit/issues/2004 (if you press A a bunch there it will eventually show up, too).

I can confirm that both behave differently on hardware (connected to terminal on mac at least) vs. the simulator in the browser, though, as described in this / the other issue, so I'm still looking into this

**Comment by abchatra** [comment]
New line missing. Required to flush the messages
