### ISSUE TITLE
There is no picture and feedback for "Debug Exension Code"

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2061]
**Describe the bug**
There is no picture and feedback for "Debug Exension Code"

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta
2. Click "More..." -> "About..." -> "Experiments" -> observe "Debug Extension Code"

**Expected behavior**
There should have picture and feedback for "Debug Exension Code"

**Actual behavior**
There is no picture and feedback for "Debug Exension Code"
![Capture2233](https://user-images.githubusercontent.com/23466737/57915495-7f3a6500-78c3-11e9-8544-644f9f7e73b9.PNG)

**Additional info:**
1. makecode.microbit.org version: 1.4.7
2. Microsoft MakeCode version: 5.11.6
3. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)

**Comment by abchatra** [comment]
Experiment bugs won't be fixed
