### ISSUE TITLE
Blocks are not visible in extension help

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#2062]
**To Reproduce**
1. Go to 'https://makecode.com/pkg/microsoft/pxt-neopixel'
2. You don't see blocks

**Expected behavior**
Blocks should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/6107272/57943991-6d889b80-788a-11e9-8929-aaa96cbaa7ae.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser: Chrome

**Comment by ChaseMor** [comment]
To view this readme, you need to use the link 
[https://makecode.microbit.org/pkg/microsoft/pxt-neopixel](https://makecode.microbit.org/pkg/microsoft/pxt-neopixel)

Plus, some of these blocks are defined in pxt-microbit so they wouldn't be able to be shown outside of that target.

Making sure this documentation only loads in supported targets with the required block definitions  would require changes to the backend which I am unable to do.

**Comment by abchatra** [comment]
My bad works fine. Thanks for investigating.
