### ISSUE TITLE
Tutorial introduction is not translated when switching language to Chinese

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2065]
**Describe the bug**
Tutorial introduction is not translated

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "More..." -> "Language" -> "Chinese (Simplified)"
3. Click "Home" to back to home page and click on any tutorial and observe

**Expected behavior**
Tutorial introduction should be translated

**Actual behavior**
Tutorial introduction is not translated
![Issue52101](https://user-images.githubusercontent.com/23466737/58071432-3807e900-7bcf-11e9-9b27-341ed293910e.PNG)

**Additional info:**
1. makecode.microbit.org version: 1.4.9
2. Microsoft MakeCode version: 5.12.14
3. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)

**Comment by abchatra** [comment]
@Helen09 does this repro in live?

**Comment by Helen09** [comment]
Yes, it also repro in live

**Comment by pelikhan** [comment]
This file is not translated https://crowdin.com/translate/kindscript/5124/en-zhcn . However, Crowdin gets really confused by the inlined JSON so we may need to find a compatible format.

**Comment by baradaran** [comment]
is there a way to include it locally? so can i add a tutorial translation myself without using Crowdin?  (like what happens with extensions)

**Comment by abchatra** [comment]
Fixed
