### ISSUE TITLE
Serial console output does not display data at different baud rates

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2066]
micro:bit support: 22040

**Describe the bug**
 1 - Using WebUSB. Editor Show CONSOLE Device button in the Simulator view does not show unless the SERIAL Redirect To At Speed block is set to 115200. Any other speed and the button does not show.
2 - If the SERIAL Redirect To At Speed block is used with anything other than 115200 speed,the Editor CONSOLE Device view does not display the Serial traffic at set speed. Garbage is displayed in the in Editor CONSOLE view.
3 - However, if an external Serial Terminal program is used, communication to / from micro:bit is correctly displayed at the other programs terminal window; meaning micro:bit correctly sets its own port speed according to the block speed used.

**To Reproduce**
Set baud rate to anything other than 115200 and direct to USB
![image](https://user-images.githubusercontent.com/31242877/58169251-3817ef80-7c88-11e9-8080-a92714bff543.png)

**Additional Context**
User also suggested having a way to input serial data via the console a la arduino
![image](https://user-images.githubusercontent.com/31242877/58169417-9644d280-7c88-11e9-8c9f-37395aa287b1.png)

**Comment by pelikhan** [comment]
This is by design. MakeCode assumes the serial port is set at 115200.
