### ISSUE TITLE
Extensions are not translated into Chinese

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2070]
**Describe the bug**
Extensions are not translated into Chinese

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "More..." -> "Language" -> "Chinese (Simplified)"
3. Click "Advanced" -> "Extensions" and observe

**Expected behavior**
Extensions should be translated

**Actual behavior**
Extensions are not translated into Chinese
![5 24](https://user-images.githubusercontent.com/23466737/58307838-73562200-7e32-11e9-831a-0e5a8a7172d3.PNG)

**Additional info:**
1. makecode.microbit.org version: 1.4.10
2. Microsoft MakeCode version: 5.12.14
3. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)

**Comment by abchatra** [comment]
@Helen09 does this bug repro in live?

**Comment by Helen09** [comment]
Yes, it also repro in live
