### ISSUE TITLE
After switching language to "Chinese", "About" page directory is not complete

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2071]
**Describe the bug**
After switching language to "Chinese", "About" page directory is not complete

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "More..." -> "Language" -> "Chinese (Simplified)"
3. Navigate to https://makecode.microbit.org/about and observe

**Expected behavior**
![Issue524003](https://user-images.githubusercontent.com/23466737/58309942-13627a00-7e38-11e9-9e7a-9b0b15229a15.gif)

**Actual behavior**
After switching language to "Chinese", "About" page directory is not complete
![5 2402](https://user-images.githubusercontent.com/23466737/58309951-18272e00-7e38-11e9-9156-58ccf9000560.PNG)

**Additional info:**
1. makecode.microbit.org version: 1.4.10
2. Microsoft MakeCode version: 5.12.14
3. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)

**Comment by Helen09** [comment]
This issue also repro when navigating to courses from "Show Instructions"
![Issue524004](https://user-images.githubusercontent.com/23466737/58316418-195f5780-7e46-11e9-929b-f7c7bc27627d.gif)

**Comment by abchatra** [comment]
@ChaseMor  please take a look at this.

**Comment by abchatra** [comment]
@riknoll can you take a look at this bug?

**Comment by riknoll** [comment]
The TOC is actually broken on every page in every non-English language @abchatra

**Comment by riknoll** [comment]
Looks like a backend issue

**Comment by abchatra** [comment]
This should be fixed in the latest docs.
