### ISSUE TITLE
serial.writeNumber is converting ints to floats

### ISSUE THREAD

**Issue by bennytheshap** [microsoft/pxt-microbit#2073]
**Describe the bug**
When I try to write a large integer over the serial line, I get a floating point value, rather than an integer.

**To Reproduce**
```
radio.onReceivedValue(function (name, value) {
    serial.writeNumber(radio.receivedSerial())
    serial.writeLine("^" + name + "^" + value)
})
```

This ends up outputting lines like this: `2067284048.9999999^moisture^529`

**Expected behavior**
There should be no decimal point ;-)

**Comment by martinwork** [comment]
See #1640.

https://github.com/microsoft/pxt-microbit/issues/1640#issuecomment-485918799

**Comment by bennytheshap** [comment]
Thanks! I somehow missed that one. 

Does the pxt team have a plan for how to fix this such that workarounds (like those described there) are not necessary?
