### ISSUE TITLE
Generation of dynamic blocks。

### ISSUE THREAD

**Issue by Ryuurock** [microsoft/pxt-microbit#2074]
If I have a drawing board like this:
![image](https://user-images.githubusercontent.com/25604544/58419349-f25e8b00-80bc-11e9-93b6-a09c0026ab1c.png)
How can I save it as a option block，it is temporary。like this:
![image](https://user-images.githubusercontent.com/25604544/58419550-829cd000-80bd-11e9-9f00-c0ad3ec726f3.png)

**Comment by abchatra** [comment]
You need to use show leds blocks. There is no way to save it into default icon images. They are prebuilt.

**Comment by Ryuurock** [comment]
> You need to use show leds blocks. There is no way to save it into default icon images. They are prebuilt.

I just want to create dynamic enumeration values of https://makecode.com/playground#language-create-enums, the layout as the grid picker
