### ISSUE TITLE
Remove @fullscreen for all steps in all Tutorials

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2078]
Hi Galen,

Can you remove the @fullscreen macro from all the steps in all the Tutorials?  Except leave it on the first Flashy Heart tutorial as that's the first one.

The Hint should remain a hint and not pop up for every step - it's duplicative, distracting, and covers the workspace.

Thanks,
Jacqueline

**Comment by abchatra** [comment]
This is fixed by getting back to full modal for @fullscreen.
