### ISSUE TITLE
Scroll Wheel

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#208]
I just had the pleasure of introducing a 'young person' to the delights of PXT.

After they'd spent a couple of hours using the tool and, I should add, achieving some success.... I asked enthusiastically "What did you think of PXT?"

I was surprised that the answer was "I didn't really like it!".

I asked why and it turned out that the issue was to do with the UI and the way it behaves in certain areas. I wasn't clear on a couple of them but will see if I can get clarity on them but the one stand out issue which was clear was the way the scroll wheel on a mouse works. 

"It should cause the window to scroll. It's a scroll wheel! It really annoyed me that it kept zooming!"

My young person/guinea pig hated the way they kept accidentally zooming in and out when they expected scrolling. I have to say I totally agree.... I just hadn't thought to mention it.

The scroll wheel causes scrolling when in the JavaScript editor btw. It's just in Blocks view it causes zooming so it's inconsistent too.

We have the +/- icons for zooming. So can we have the scroll wheel scroll please?

**Comment by pelikhan** [comment]
Zooming is disabled in blocks.

**Comment by pelikhan** [comment]
The scroll now moves the view up and down (just like the code editor) and Ctrl+wheel handles zooming.

**Comment by bluetooth-mdw** [comment]
Thank you :-)

**Comment by pelikhan** [comment]
Keep the feedback coming!
