### ISSUE TITLE
Tutorial 'unplugged' step does not continue when collapsed by clicking bar

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2080]
**Describe the bug**

The 'unplugged' sections don't continue automatically when collapsed by pressing the instruction area, like they do when you click elsewhere (e.g. the workspace) to skip to the first actual step

![2019-05-29 11 12 45](https://user-images.githubusercontent.com/5615930/58580899-06aca000-8203-11e9-9b06-30748e7ddde7.gif)

**To Reproduce**

1. Go to Flashing Heart tutorial
2. Click on instructions area ("Learn how to use LEDs"...)
3. dialogue collapses but tutorial does not advance

**Expected behavior**

when the dialogue is collapsed in an unplugged section, move on to next section automatically

**Comment by abchatra** [comment]
@jwunderl does this have unplugged as the first step?

**Comment by jwunderl** [comment]
Yes, I think in all the tutorials I've seen unplugged have been the first step if they exist.

**Comment by abchatra** [comment]
Fixed
