### ISSUE TITLE
Remove instructions from Hint box in all Tutorials

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2081]
Hi Galen,
Can you go through all the micro:bit Tutorials and remove the duplicative step instructions from the Hint box?  The Hint should only show the solution code, it shouldn't include the instructions.

![Tutorial](https://user-images.githubusercontent.com/22108954/58581321-22fd0c80-8204-11e9-9bcb-c53c433e810c.png)

Thanks!
Jacqueline

**Comment by ganicke** [comment]
The hint box shows all of the content of the step section. Have we coded a change to pull the step paragraph out of the hint display? Here's the full content for this step:

````
## Step 1 @fullscreen

We need 3 pieces of code: one to detect a throw (shake), another to pick a random number, and then one to show the number.

Place the ``||input:on shake||`` block onto the editor workspace. It runs code when you shake the @boardname@.

```blocks
input.onGesture(Gesture.Shake, () => {

})
```
````

**Comment by abchatra** [comment]
Fixed
