### ISSUE TITLE
Blocks view: Why do Array methods shift(), pop() and removeAt() require return values to be used?

### ISSUE THREAD

**Issue by kristianpedersen** [microsoft/pxt-microbit#2082]
**Array methods are confusing in blocks view**

My colleague needed some help in block view with removing things from an array.
He has experience with block-based programming (MakeCode and Scratch), while I have experience with JavaScript and Python.

At first I thought there would be a simple equivalent of array.shift() and array.pop(), but the way they're implemented requires you to use the returned value somehow.

Here's the workaround I found (please let me know if there's a better way)
![alt text](https://i.imgur.com/RTM2UhRg.png "Not looking so good :/")

Here's what we expected:
![alt text](https://i.imgur.com/p24M6AK.png "Looking good!")

```javascript
// Current way of removing from an array without getting grey blocks
const myList = [1, 2, 3, 4, 5]
let removedItem = myList.shift()
removedItem = myList.pop()
removedItem = myList.removeAt(2)
basic.showNumber(myList.length)

// This usage of shift(), pop() and splice() produces grey blocks,
// even though these are very basic array operations
const myList2 = [1, 2, 3, 4, 5]
myList2.shift()
myList2.pop()
myList2.splice(2, 1)
basic.showNumber(myList2.length)
```

**Suggested solution**
I was able to provide my colleague with more intuitive blocks by editing custom.ts as such:
```typescript
enum validArrayTypes { number, string }

//% weight=200 color=#10569C icon="\uf085" block="Array utilities"
namespace custom {
    //% block="first item from %x=variables_get(myList)"
    export function getFirst(a: validArrayTypes[]) {
        return a[0]
    }

    //% block="last item from %x=variables_get(myList)"
    export function getLast(a: validArrayTypes[]) {
        return a[a.length - 1]
    }

    //% block="remove first item in %x=variables_get(myList)"
    export function removeFirst(a: validArrayTypes[]) {
        a.shift()
    }

    //% block="remove last item in %x=variables_get(myList)"
    export function removeLast(a: validArrayTypes[]) {
        a.pop()
    }

    //% block="remove item at index %index in %x=variables_get(myList)"
    export function removeAtIndex(index: number, a: validArrayTypes[]) {
        a.splice(index, 1)
    }
}
```
I suggest something like this being implemented by default. It's more intuitive for everyone. 

I only recently discovered custom.ts, so please let me know if I missed anything. Cheers!

**Comment by kristianpedersen** [comment]
To clarify, I dont have any problems using array.shift() - it's just that I'd really like my code to be readable and not grey in blocks view for the kids, teens and teachers I'm teaching programming to.

**Comment by abchatra** [comment]
Thanks for explaining. It is valid feedback. Although it is bit hard for us to change the existing behavior as programs have dependent on it. Probably we can add new blocks which don't return anything.
