### ISSUE TITLE
Tutorial 1st steps with No Action

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2083]
There are a few Tutorials where the first step doesn't have any action for the user to take.  This is confusing in our current layout.  
There are a couple things we could do to remedy:
1.) Bring back the fullscreen modal dialog box (ala Code.org videos) that is used to just introduce the Tutorial and have that be Step 0 with a "Let's start" or something button to dismiss
2.) Compress steps 1 and 2 into a single step so we are introducing the Tutorial and also telling the user what to do first.

![TutorialStep1](https://user-images.githubusercontent.com/22108954/58581755-1e852380-8205-11e9-8ab1-6aeab4dd6254.png)

**Comment by abchatra** [comment]
Fixed
