### ISSUE TITLE
Closing the Hint bubble

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2084]
When we automatically pop the Hint dialog (like on @fullscreen), we should automatically close it after a certain time period.  The Hint bubble can be distracting and covers up the work you want to do - we pop it just to draw attention to it and make sure the user knows how to access it in the future.  We shouldn't leave it open.

Also, we should add toggle functionality to the Hint lightbulb icon so it can be used to both show and dismiss the Hint dialog.

Also, my other feedback on the Tutorial is here: https://github.com/microsoft/pxt-adafruit/issues/1039

**Comment by abchatra** [comment]
We don't automatically pop up anymore.

**Comment by Jaqster** [comment]
Reopening this issue, as we are automatically popping up the hint.

**Comment by abchatra** [comment]
@Jaqster what tutorial are you hitting this?

**Comment by Jaqster** [comment]
All of them.  Try Flashing Heart.  We put the Hint on the right side now, so that helps, but if we auto-pop a hint, we should make it disappear after a while.

**Comment by jwunderl** [comment]
yeah, authoring for these still use @fullscreen, should probably drop that except for where we really want it? e.g.  https://github.com/microsoft/pxt-microbit/blob/master/docs/projects/flashing-heart.md

**Comment by abchatra** [comment]
This is the markdown issue.

**Comment by abchatra** [comment]
@ganicke can you fix these markdown?

**Comment by ganicke** [comment]
Referring to the "hints", we really mean the popup dialogs? If so, I can pull off the `@fullscreen` attributes.

**Comment by jwunderl** [comment]
@ganicke yeah, I think just pull off `@fullscreen` everywhere unless it's completely necessary (like the only thing in the step is the hint, don't think we have that anywhere)

**Comment by ganicke** [comment]
Only in the `## Introduction` steps.

**Comment by jwunderl** [comment]
those are usually unplugged though, right? so they give a modal instead of the hint which covers the screen

**Comment by pelikhan** [comment]
They are useful for the first step to make sure kids know there is a hint. Keep them on the first step (non intro) for the row of tutorials.

**Comment by ganicke** [comment]
Gonna close this unless we really want the `@fullscreen` back on first step.
