### ISSUE TITLE
Turtle Spiral example blocks not loading properly 

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2085]
**Describe the bug**

Turtle Spiral isn't decompiling properly.

Also minor grammar error: This project uses **an** microturtle Extension

**To Reproduce**
1. Go to turtle spiral example
2. see error

**Expected behavior**

decompiles properly

**Screenshots**

![Screen Shot 2019-05-29 at 11 30 40 AM](https://user-images.githubusercontent.com/5615930/58582183-08c42e00-8206-11e9-8803-714c2a34a6a4.png)

**Comment by abchatra** [comment]
Good to fix, but I am assuming this is not a regression from live. Right?

**Comment by jwunderl** [comment]
Correct, not a regression
