### ISSUE TITLE
Tutorial hint bleeds off

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2086]
![image](https://user-images.githubusercontent.com/4175913/58582410-87b96680-8206-11e9-9ca7-b3ecc373da5b.png)

**Comment by Helen09** [comment]
This bug also repro on "Rock Paper Scissors"
![Issue60302](https://user-images.githubusercontent.com/23466737/58795010-2fca9780-862c-11e9-98cc-c865cf5b0cf3.gif)

**Comment by abchatra** [comment]
Fixed
