### ISSUE TITLE
Windows app - spinning download

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2087]
With micro:bit plugged in, on the second program download in my session, I got the forever spinning Download button and nothing downloaded to hardware.

I had to close the app and open back up again to get it to reset.

![Spinning download](https://user-images.githubusercontent.com/22108954/58582467-9a33a000-8206-11e9-932d-ef197abf9499.png)

Difficult to repro...

**Comment by abchatra** [comment]
Cant repro
