### ISSUE TITLE
breadboard should not be shown for music alone

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2088]
We should not show a breadboard unless necessary.
![image](https://user-images.githubusercontent.com/4175913/58582703-2f369900-8207-11e9-98bb-f94eb35cc890.png)

**Comment by abchatra** [comment]
@darzu

**Comment by abchatra** [comment]
Seems like a nice but to tackle. We shouldn't show breadboard unless it is necessary. Not required for neopixel or servo as well. Right?

**Comment by pelikhan** [comment]
Not required unless we use 2 of those together. There is a code path that should actually drop the breadboard if not needed. @darzu your good ol' breadboaring compiler...

**Comment by abchatra** [comment]
Fixed
