### ISSUE TITLE
Hide / Show Simulator

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#209]
Can we have the ability to hide/show the simulator pane on the left please? Using PXT on a smaller computer screen like a laptop, you need all the space you can get. I never use the simulator and would love to be able to hide it. Thanks.

**Comment by pelikhan** [comment]
The simulator hides itself in portrait mode. Otherwise, it is important to minimize the buttons on the interface to avoid kids getting confused (they might press the button and they can't find the simulator anyway).

For a pro experience, try the CLI https://pxt.io/cli
