### ISSUE TITLE
Windows app - trying to read compass heading as serial data values

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2090]
Weird bug - I downloaded this program to the micro:bit
https://makecode.microbit.org/_UbyWRFeM2UUL

It shows the text "Tilt to fill screen" - I think it's trying to calibrate the compass?
And then no data gets streamed into the app.

**Comment by abchatra** [comment]
This is the calibration. You will need to calibrate by filling the leds before streaming the data.
