### ISSUE TITLE
Windows app - serial data adding additional name/value graphs

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2091]
When reading serial values from the device, occasionally the serial data viewer will add graphs showing random name value pairs.

![Serial Data values](https://user-images.githubusercontent.com/22108954/58587963-76c32200-8213-11e9-8830-a265e6375d73.png)

**Comment by abchatra** [comment]
Parsing issues I believe

**Comment by pelikhan** [comment]
Repro program? It seems that we skip the new line character which led to new variable names.

**Comment by abchatra** [comment]
I can't repro this either. Closing.
