### ISSUE TITLE
Hide Simulator button has two chevrons in tablet view

### ISSUE THREAD

**Issue by ChaseMor** [microsoft/pxt-microbit#2093]
**Describe the bug**
In the tablet view, when the hide simulator button is on the bottom, a left chevron is visible behind the down chevron.

**Expected behavior**
Should just be the down chevron

**Screenshots**
![image](https://user-images.githubusercontent.com/13285164/58588810-5eec9d80-8215-11e9-83ba-fbeed26b71f5.png)

**Comment by jwunderl** [comment]
https://github.com/microsoft/pxt-adafruit/issues/1046 in adafruit too

**Comment by abchatra** [comment]
Probably P3. But lets fix it for microbit.

**Comment by ChaseMor** [comment]
Fixed in microsoft/pxt#5630
