### ISSUE TITLE
Spanish language text cut off of blocks on zoom

### ISSUE THREAD

**Issue by JacobBovee** [microsoft/pxt-microbit#2096]
**Describe the bug**
When zooming on blocks in Spanish the text seems to be too large and gets cut off.

**To Reproduce**
1. Change language to Spanish
2. Pinch and zoom in to blocks

**Expected behavior**
Blocks should be recomputed based on the size of the text

**Screenshots**

Spanish:
![image](https://user-images.githubusercontent.com/6301646/58591510-5303da00-821b-11e9-9c88-ad4209ade549.png)

English:
![image](https://user-images.githubusercontent.com/6301646/58591592-7e86c480-821b-11e9-9741-793cedab0242.png)

**Desktop (please complete the following information):**
 - OS: CromeOS
 - Browser: Chrome

**Comment by abchatra** [comment]
I believe this is a translation issue. Must be easy to fix. Notice the A is at the end instead of middle.

**Comment by abchatra** [comment]
@ganicke you know how to fix this?

**Comment by ganicke** [comment]
No puedo repro en Chromo...

![image](https://user-images.githubusercontent.com/27789908/58598266-666d7000-8230-11e9-8b38-3d831070d825.png)

**Comment by ganicke** [comment]
Also, scrape the event function from _core/input.cpp_, replace the block text with the Spanish from Crowdin, and throw it into [playground](https://makecode.com/playground) - 

```typescript
enum Button {
    A = 0,
    B = 1,
    //% block="A+B"
    AB = 2
};
/**
 * Events are functions that take a function (lambda) as the last argument
 */
//% color="#AA278D"
namespace testme {
    /**
     * Do something when a button (A, B or both A+B) is pushed down and released again.
     * @param button the button that needs to be pressed
     * @param body code to run when event is raised
     */
    //% help=input/on-button-pressed weight=85 blockGap=16
    //% blockId=device_button_event block="al presionarse el botón|%NAME|"
    //% parts="buttonpair"
    export function onButtonPressed( button: Button, handler: () => void) {
    }
}
```

**Comment by JacobBovee** [comment]
Zooming in is fine in playground however zooming out far enough gives you a little trouble with the text overflowing.

![image](https://user-images.githubusercontent.com/6301646/58598857-d2e96e80-8232-11e9-9962-4128e2133851.png)

**Comment by ganicke** [comment]
Hmm, try defining a block with a long English string and see if it behaves similarly. I don't have touch screen at the moment to try. I can't get it to squish with the zoom controls. If it happens with a English string too then it's a blocks render problem.

**Comment by abchatra** [comment]
Thanks @ganicke We will look into this.

**Comment by JacobBovee** [comment]
@ganicke I also found it to be cutoff with long english strings.
![image](https://user-images.githubusercontent.com/6301646/58645993-4635c380-82b9-11e9-8e61-73bb959dcf87.png)

The zoom on this chrome os laptop is very slow as well which may be part of the issue if it can't be reproduced.

**Comment by ganicke** [comment]
Is this a Blockly thing maybe?

**Comment by jwunderl** [comment]
Looks like a blocky thing, showed up in an arcade tutorial with a long extension block:

![Screen Shot 2019-06-18 at 11 02 40 AM](https://user-images.githubusercontent.com/5615930/59707966-9d43ff80-91b8-11e9-8bd5-184b0463cd44.png)

**Comment by abchatra** [comment]
This is text bleeding issue in blockly. Take a look if this fixed in latest.

**Comment by shakao** [comment]
![image](https://user-images.githubusercontent.com/34112083/77804130-0dcb5700-703c-11ea-855e-7d2e49860e8c.png)

Tested zooming in and out with long strings and this doesn't repro for me with latest blockly--but I don't know if this was a Chromebook-only bug? I also can't repro on live microbit (Chrome, Windows 10).

**Comment by abchatra** [comment]
Fixed it was everywhere int he past.
