### ISSUE TITLE
Repeatedly shaking the simulator crashes or reloads editor in Edge

### ISSUE THREAD

**Issue by ChaseMor** [microsoft/pxt-microbit#2097]
**Describe the bug**
If you shake the simulator (Not by pressing the button, but by moving the mouse around on the simulator) too much on Edge the page will either crash or reload. Especially a problem if students are testing their dice roller tutorial program.

**To Reproduce**
1. Go to [https://makecode.microbit.org/#editor](https://makecode.microbit.org/#editor) in Edge
2. Add an ``on shake`` handler
3. Move the mouse over the simulator
4. Shake it like a Polaroid picture. (See gif)

**Screenshots**
![Broken Shake](https://user-images.githubusercontent.com/13285164/58591940-3f0ca800-821c-11e9-997f-07ed2e435d35.gif)

**Comment by abchatra** [comment]
i can't repro this

**Comment by pelikhan** [comment]
https://youtu.be/8AGZziCh41c?t=17

**Comment by abchatra** [comment]
Can't repro. If you have reproduce please reopen
