### ISSUE TITLE
Some pages in docs have inaccurate bread crumbs and highlighted sidebar

### ISSUE THREAD

**Issue by JacobBovee** [microsoft/pxt-microbit#2099]
**Describe the bug**
Certain pages have inaccurate breadcrumbs and highlighted sidebar menu pages. It seems to be that when a page has a prefix shared with another page in the same category (i.e Game, Music, etc) it will highlight the shorter prefixed menu item and display that breadcrumb.
**To Reproduce**
1. Go to https://makecode.microbit.org/reference/led/plot-bar-graph

**Expected behavior**
Should highlight "Plot bar graph" and have "Plot bar graph" breadcrumb

**Screenshots**
Plot bar graph page showing Plot breadcrumb and highlighting Plot menu item
![image](https://user-images.githubusercontent.com/6301646/58593699-78dfad80-8220-11e9-851d-fbd9e1b3c0a3.png)

Is touching edge has touching edge breadcrumb
![image](https://user-images.githubusercontent.com/6301646/58596565-7e8dc100-8229-11e9-8c52-0e8fdbbc3cab.png)

Set score highlighting set
![image](https://user-images.githubusercontent.com/6301646/58596656-c0b70280-8229-11e9-9f92-d0be4fccff2e.png)

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome

**Comment by ganicke** [comment]
This looks like SUMMARY parse problem. It captures only first word out of the link text. A victim of being too clever at a RegEx match.

Here's the summary contents for ``led`` with one ``plot``  and another ``plot-`` pages.
```
* [Led](/reference/led)
    * [plot](/reference/led/plot)
    * [unplot](/reference/led/unplot)
    * [point](/reference/led/point)
    * [toggle](/reference/led/toggle)
    * [brightness](/reference/led/brightness)
    * [set brightness](/reference/led/set-brightness)
    * [stop animation](/reference/led/stop-animation)
    * [plot bar graph](/reference/led/plot-bar-graph)
    * [enable](/reference/led/enable)
```

**Comment by abchatra** [comment]
This fixed

**Comment by abchatra** [comment]
in latest docs
