### ISSUE TITLE
Load preferred packages automatically

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#210]
I never use the Radio package (so far). I always use the Bluetooth package. Therefore I always have to add the Bluetooth package and remove the Radio package. It occurred to me a better UX would be if the system could load the packages I used last time or have some other way of reinstating my usual set of packages when I start a new project. Just a thought :-)

**Comment by pelikhan** [comment]
It's important to keep the initial experience consistent in the classroom. The same computer may be shared by a number of students - if we started auto-tuning which initial project gets loaded, it might confuse the classroom.

If you create a new project, get the embed URL, you can use that one as your starting point (you can put the edit URL in a URL shortener to make it easier.

**Comment by bluetooth-mdw** [comment]
Good point. And I thought PXT was just for me ;-)
