### ISSUE TITLE
Game/Change reference doc does not render top block

### ISSUE THREAD

**Issue by JacobBovee** [microsoft/pxt-microbit#2100]
**Describe the bug**
Game/Change reference doc does not render top block.

**To Reproduce**
1. Go to https://makecode.microbit.org/reference/game/change

**Expected behavior**
Should render top block according to markdown of doc

**Screenshots**

Current behavior:
![image](https://user-images.githubusercontent.com/6301646/58594492-9ca3f300-8222-11e9-9582-71d9f1fcbac2.png)

Markdown
![image](https://user-images.githubusercontent.com/6301646/58596145-d1667900-8227-11e9-87b3-43f4f5aefce4.png)

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser: Chrome

**Comment by ganicke** [comment]
Fixed in https://github.com/microsoft/pxt-microbit/pull/2128/files#diff-85b462d0e2538d0950dc06ae2d6c9b1a
