### ISSUE TITLE
Serial documentation blocks under advanced section don't render

### ISSUE THREAD

**Issue by JacobBovee** [microsoft/pxt-microbit#2101]
**Describe the bug**
Although the blocks exist in the markdown. Nothing can be found under the Advanced section of the page. May be related to issue #2098. 

**To Reproduce**
1. Go to https://makecode.microbit.org/reference/serial

**Expected behavior**

**Screenshots**

Serial docs
![image](https://user-images.githubusercontent.com/6301646/58597149-923a2700-822b-11e9-9d7a-00534c432e38.png)

Serial markdown
![image](https://user-images.githubusercontent.com/6301646/58597176-a847e780-822b-11e9-95bf-0fb7b1786300.png)

**Desktop (please complete the following information):**
 - OS: Chrome OS
 - Browser: Chrome

**Comment by abchatra** [comment]
@ganicke is this a documentation issue?

**Comment by ganicke** [comment]
Looks like some of the APIs in "Advanced" don't decompile well. I think block definitions were removed for the buffer APIs. I'll have to remove these from "Advanced".

![image](https://user-images.githubusercontent.com/27789908/58597944-180ba180-822f-11e9-9440-4911bd8f5f16.png)

**Comment by ganicke** [comment]
Should work now with #2128 and #2144
