### ISSUE TITLE
Empty breadcrumbs in About page

### ISSUE THREAD

**Issue by JacobBovee** [microsoft/pxt-microbit#2102]
**Describe the bug**
An extra arrow seems to show up when on the about page

**To Reproduce**

**Expected behavior**
There should only be two breadcrumbs

**Screenshots**

![image](https://user-images.githubusercontent.com/6301646/58598548-be58a680-8231-11e9-9576-8d536d3c21ad.png)

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome

**Comment by abchatra** [comment]
P3 closing
