### ISSUE TITLE
Print button is broken on site

### ISSUE THREAD

**Issue by JacobBovee** [microsoft/pxt-microbit#2103]
**Describe the bug**
Clicking the print button highlights it but opens no print options.

**To Reproduce**
1. Go to https://makecode.microbit.org/hidflash

**Expected behavior**
A print dialog of some kind should be opened.

**Screenshots**
Clicked and highlighted
![image](https://user-images.githubusercontent.com/6301646/58599049-6c188500-8233-11e9-8942-29c272e5269d.png)

Click away and unhighlighted
![image](https://user-images.githubusercontent.com/6301646/58599080-7f2b5500-8233-11e9-90df-a077889e57aa.png)

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser: Chrome

**Comment by jwunderl** [comment]
Seems to be working now, tested on mac (chrome / ff / safari) and re-tested on chromebook. Some sort of weird transient issue?

**Comment by pelikhan** [comment]
Did you open the frame by popping out the side docs? For some reason, the print button does not work when opening it that way.

**Comment by jwunderl** [comment]
... huh. If you go to the page from anywhere else it works, but from the expand side docs it's broken like you said.

![2019-05-30 16 26 47](https://user-images.githubusercontent.com/5615930/58671529-d3980880-82f7-11e9-9570-ffe66863030c.gif)

**Comment by pelikhan** [comment]
The popout operation is done from the sandbox docs iframe, which inherits the iframe permission. Instead, the docs page should send back the current URL to the editor frame, which then opens the tab.

**Comment by ChaseMor** [comment]
Yeah. I was tossing around the ideas of doing that or just adding allow-modals to the sandbox iframe permissions. But I think opening the tab from the editor frame is a better option because we don't want users to be using our site with limited permissions. It will just create bugs in the future.

**Comment by pelikhan** [comment]
Weird bugs.

________________________________
