### ISSUE TITLE
set_pull_pin has no impact on the simulator

### ISSUE THREAD

**Issue by vijairaj** [microsoft/pxt-microbit#2104]
**Describe the bug**
`set_pull_pin` `P1` to `up` doesn't seem to have any impact on the simulator, so the `digital_read_pin` reads out `0` instead of `1` on restart.

**To Reproduce**
Please check the [snippet](https://makecode.microbit.org/91397-74083-35314-29491)

**Comment by abchatra** [comment]
Fixed
