### ISSUE TITLE
Tab navigation on home carousels do not advance carousels 

### ISSUE THREAD

**Issue by JacobBovee** [microsoft/pxt-microbit#2105]
**Describe the bug**
When tabbing through carousels on the home screen it will select the correct item however the carousel does not move up to the selected item. This causes the selected item to be off screen/hidden if it is further than the arrow button.

**To Reproduce**
1. Go to https://makecode.microbit.org/beta
2. Tab through until you reach the tutorials carousel with an arrow.
3. Tab until you should reach the end. A tutorial off screen will be selected

**Expected behavior**
The carousel should slide forward enough to show the highlighted tutorial.

**Screenshots**
Pre off screen tab
![image](https://user-images.githubusercontent.com/6301646/58645632-95c7bf80-82b8-11e9-92f2-b65f097b1770.png)

Cut off of screen
![image](https://user-images.githubusercontent.com/6301646/58645666-a9732600-82b8-11e9-92d9-dbfcfebf8047.png)

Shown when arrow button clicked
![image](https://user-images.githubusercontent.com/6301646/58645719-bee85000-82b8-11e9-995e-18aa99cd4d74.png)

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome

**Comment by abchatra** [comment]
This is fixed. As soon as you select the more button using space more cards are displayed
