### ISSUE TITLE
Use empty space above download button to show serial data

### ISSUE THREAD

**Issue by kristianpedersen** [microsoft/pxt-microbit#2108]
There's a lot of unused space above the download button, which I think could be used to show serial data:

![](https://i.imgur.com/49wNrV0.png "Logo Title Text 1")

I spend a lot of time clicking back and forth between my code and the console, or even logging with basic.showNumber(), which are both a bit tedious.

**Comment by abchatra** [comment]
This won't work on all screen sizes such as tablet. Design limitation.
