### ISSUE TITLE
"Function is already defined" exception

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#2109]
The most common exception we are getting in the telemetry is "Function already defined". Occurs in all browsers, stack trace points to the `mkEnv()` function in the blockly compiler.

**Comment by pelikhan** [comment]
It happens when two blocs have the same I’d?

**Comment by riknoll** [comment]
Yup. Seems to just be affecting blocks in packages (most common are the blocks in the game package). Also this is in beta.

**Comment by abchatra** [comment]
I am closing this old bug and reopen other telemetry bugs
