### ISSUE TITLE
Missing JS library support and blocks for decoding Key-Value radio pairs

### ISSUE THREAD

**Issue by bennytheshap** [Microsoft/pxt-microbit#211]
The micro:bit radio has the ability to send key-value pairs. For example, in Javascript:
`    radio.sendValue("x_accel", input.acceleration(Dimension.X))
`
But there don’t seem to be blocks or JS methods to receive those pairs. I can receive a number or receive a string, but not a k-v pair.

Can you please add JS support for being able to extract the key and value of a message? And, ideally, corresponding blocks?

**Comment by abchatra** [comment]
@riknoll Please take look if this will be fixed by your callback work on radio. If yes close this issue and tag it with the issue in pxt.

**Comment by riknoll** [comment]
Yep, working on this now. Tracked in https://github.com/Microsoft/pxt/issues/465
