### ISSUE TITLE
Create New github repo dialogue initially focuses on wrong input

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2111]
**Describe the bug**

`import` -> `your github repo` -> `create new` focuses on description initially instead of repo name (when repo name is the required parameter)

**To Reproduce**

1. Go to homepage with github integration
2. Click on import
3. click on 'your github repo'
4. click on 'create new'
5. see error

**Expected behavior**

should focus on field for repo name

**Screenshots**

![2019-05-31 14 54 35](https://user-images.githubusercontent.com/5615930/58736964-95acea00-83b4-11e9-850e-291c703b30ec.gif)

**Desktop (please complete the following information):**
 - OS:  mac
 - Browser chrome

**Comment by pelikhan** [comment]
It tabs through everything now. @jwunderl do you have samples to specify the default selected field in a dialog?
