### ISSUE TITLE
Creating a new repo with a duplicate name fails silently

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2112]
**Describe the bug**

Creating a new gh repo through the import dialogue fails silently if the repo already exists

**To Reproduce**

1. Go to homepage with github integration
2. Click on import
3. click on 'your github repo'
4. click on 'create new'
5. create a random repoo (e.g. 'asdf')
6. exit project, and repeat import with same name

**Expected behavior**

should error or poll for that repo and open it

**Screenshots**

![2019-05-31 15 01 15](https://user-images.githubusercontent.com/5615930/58737250-ad38a280-83b5-11e9-8c5e-04eabbb8057f.gif)

**Desktop (please complete the following information):**
 - OS:  mac
 - Browser chrome

**Comment by pelikhan** [comment]
Fixed.
![2020-03-23 07 05 30](https://user-images.githubusercontent.com/4175913/77324976-c314ac80-6cd4-11ea-9f01-65d4b8dfc51f.gif)
