### ISSUE TITLE
Invalid state error: Failed to execute 'transaction' on 'IDBDatabase': the database is closing

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#2113]
Seeing a lot of indexedDB exceptions from the telemetry. Seems to be Chrome specific. Unfortunately, the stacktrace is completely useless because the code is minified.

Relevant GitHub thread: https://github.com/pouchdb/pouchdb/issues/3415

**Comment by abchatra** [comment]
We upgraded pouchdb
