### ISSUE TITLE
"electron drive deploy failed"  for micro:bit offline app

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#2114]
Seeing this a lot in the telemetry. Stack trace is not helpful because it's minified.

Mostly happening in Windows 7 (but also Windows 10)

**Comment by abchatra** [comment]
@darzu might want to investigate this telemetry issue.

**Comment by darzu** [comment]
During standup I we decided to punt this. Right, @abchatra ? Want me to do anything further with this?

**Comment by abchatra** [comment]
Assign it to Richard .
