### ISSUE TITLE
Hint can't be closed on Edge

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2116]
**Describe the bug**
Hint can't be closed on Edge

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta
2. Open one tutorial such as "Flashing Heart" and click one the left of the banner to close hint

**Expected behavior(Chrome, Firefox)**
Hint should can be closed on each browser
![Issue60301com](https://user-images.githubusercontent.com/23466737/58791150-45d45a00-8624-11e9-8316-2b98e29b9599.gif)

**Actual behavior**
Hint can't be closed on Edge
**Issue1:** when clicking on the first step, it will navigate to second step and can't back
![Issue603011com](https://user-images.githubusercontent.com/23466737/58791466-d6129f00-8624-11e9-8d09-72e63c7281d0.gif)
**Issue2:** when clicking on other steps, hints can't be closed
![Issue60301co](https://user-images.githubusercontent.com/23466737/58791481-df037080-8624-11e9-9c6a-ad7f0f3b2367.gif)

**Additional info:**
1. makecode.microbit.org version: 1.4.11
2. Microsoft MakeCode version: 5.14.3
3. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)

**Comment by abchatra** [comment]
Fixed
