### ISSUE TITLE
Blocks for checking string equality

### ISSUE THREAD

**Issue by bennytheshap** [Microsoft/pxt-microbit#212]
It's currently possible to do many things with strings, including assigning them to variables, sending them out via serial and radio, etc. However, it doesn't seem possible to test whether two strings are equal using blocks.

Could you please add string equality checking? Currently the equality-testing block under Logic rejects string blocks.

**Comment by gingemonster** [comment]
I think you are right it cannot be done just using blocks at the moment due to "string" not being available in the blocks menu, BUT if you switch into script you can happily write it then switch back:

https://codethemicrobit.com/xpqrip

**Comment by bennytheshap** [comment]
Thanks, @gingemonster.

**Comment by abchatra** [comment]
This is part of #72
