### ISSUE TITLE
Cannot close the cookie banner in IE11

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#2120]
Repro:
1. Go to microbit.makecode.com/beta in IE11 in private session
2. Notice the cookie banner
3. Try to dismiss the cookie banner by clicking on it or anywhere else
4. Banner does not go away

![image](https://user-images.githubusercontent.com/6453828/58842203-fa20b100-8621-11e9-90dc-29a2a0695117.png)

**Comment by abchatra** [comment]
Clicking on new project dismisses the cookie banner. So doesn't look blocker to me.

**Comment by pelikhan** [comment]
This impacts all editors.

**Comment by abchatra** [comment]
Clicking on the cookie banner itself shouldn't dismiss it. User needs to make a meaningful interaction with the website to give consent. That is by design.

**Comment by pelikhan** [comment]
Right... confusing since it's different from pretty much all other web sites.
