### ISSUE TITLE
Some tutorials need to be clicked twice to back to the previous

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2122]
**Describe the bug**
Some tutorials need to be clicked twice to back to the previous

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta
2. Navigate to the last one tutorial
3. Click on each tutorial from the last one  

**Expected behavior**
Tutorials should be clicked once to back to the previous

**Actual behavior**
Some tutorials need to be clicked twice to back to the previous
![Issue60402](https://user-images.githubusercontent.com/23466737/58861234-7da0d780-86e0-11e9-9e7d-85caa1b7b6aa.gif)

**Additional info:**
1. makecode.microbit.org version: 1.4.12
2. Microsoft MakeCode version: 5.15.1
3. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)

**Comment by abchatra** [comment]
Fixed
