### ISSUE TITLE
Windows 10 app: New projects don't open if one has been opened before

### ISSUE THREAD

**Issue by kristianpedersen** [microsoft/pxt-microbit#2123]
Windows 10, version 1803, Build 17134.765

makecode.microbit.org version:  1.2.13
Microsoft MakeCode version:  4.4.7
microbit runtime version:  v2.1.1

1. Open an existing project or create a new one, and click home again.
2. Create 2nd new project. Nothing happens. New project doesn't open, and project list doesn't update. The project does update if I first enter an existing project and click home again, or if I restart the whole app.

**Comment by abchatra** [comment]
@darzu  please investigate

**Comment by darzu** [comment]
I wasn't able to repro the issue:
https://youtu.be/hs2m9Wyk3Ak

Using:
![image](https://user-images.githubusercontent.com/6453828/58916570-e3896100-86d8-11e9-94f4-d99da209109e.png)

@kristianpedersen, if you wouldn't mind, does the issue happen again if you close and re-open the app? Do any errors appear for you?

**Comment by abchatra** [comment]
No repro
