### ISSUE TITLE
"pxt serve -yt" doesnt actually appear to change what gets compiled in the hex file if you change c++ code

### ISSUE THREAD

**Issue by gingemonster** [Microsoft/pxt-microbit#213]
The readme suggests:

"If you need modify the .cpp files, turn on yotta compilation with the -yt flag (add sudo for Mac/Linux shells):

pxt serve -yt"

I had presumed that meant that changing a cpp file would then get compiled and if I then uploaded a hex file using the local website it would have the changes to the cpp code included.

It appears this isn't the case. Changing a cpp file does indeed kick of a yotta build in the console but seems to make not difference to the code in the hex file uploaded to the microbit.

I'd love to have a go a helping on this project, and building a few modules but could really do with a bit more help in the readme to get even the basics going.

Thanks

**Comment by abchatra** [comment]
Please reopen this issue in microsoft/pxt repo if issue still exists. We are tracking all the pxt related issues in one repo.
