### ISSUE TITLE
Function names can't show completely after opening "read more..." in JavaScript mode

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2130]
**Describe the bug**
Function names can't show complete after opening "read more..." in JavaScript mode

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "{ }JavaScript" to switch to JavaScript mode
3. Input "basic" and click the "read more..." on the right of the function

**Expected behavior**
Function names should show complete

**Actual behavior**
Function names can't show complete after opening "read more..." in JavaScript mode
![image](https://user-images.githubusercontent.com/23466737/58937049-e1400900-87a3-11e9-9324-21c0559a8ef9.png)

**Additional info:**
1. makecode.microbit.org version: 1.4.12
2. Microsoft MakeCode version: 5.15.1
3. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)

**Comment by Helen09** [comment]
This bug also repro when open "advanced" toolbox
![image](https://user-images.githubusercontent.com/23466737/58944605-c629c500-87b4-11e9-8ace-b26f64dbdc36.png)

**Comment by abchatra** [comment]
Can you add  a screen shot for 'read more...'

**Comment by Helen09** [comment]
‘read more...’ is on the right of the function
![Issue60601](https://user-images.githubusercontent.com/23466737/59000614-d5088a00-883d-11e9-8341-52fb2d93f571.gif)

**Comment by abchatra** [comment]
Fixed in latest monaco
