### ISSUE TITLE
Text "Share" is lost when switching language to others on IE

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2131]
**Describe the bug**
Text "Share" is lost when switching language to others on IE

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "more..." -> "language" -> "Chinese (Simplified)"
3. Observe menu bar on each browser

**Expected behavior(Edge, Chrome, Firefox)**
![image](https://user-images.githubusercontent.com/23466737/58938234-fbc7b180-87a6-11e9-9124-eeed4ccdb730.png)

**Actual behavior(IE)**
Text "Share" is lost when switching language to others on IE
![image](https://user-images.githubusercontent.com/23466737/58938124-c3c06e80-87a6-11e9-8ac0-3efa4ab113b4.png)

**Additional info:**
1. makecode.microbit.org version: 1.4.12
2. Microsoft MakeCode version: 5.15.1
3. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)

**Comment by Helen09** [comment]
This bug also repro when open "advanced" toolbox
![image](https://user-images.githubusercontent.com/23466737/58944605-c629c500-87b4-11e9-8ace-b26f64dbdc36.png)

**Comment by abchatra** [comment]
No support for IE11 anymore
