### ISSUE TITLE
Extensions not appearing in search

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2132]
Reported by @KitronikLtd but I've also seen this behaviour in recent days.

1. Search for eg 'Kitronik' in extensions
2. No results are returned

Here is the console output from a recent failed search

```
Document was loaded from Application Cache with manifest https://makecode.microbit.org/---manifest
(index):1 Application Cache Checking event
pxtapp.js:1730 Browser: chrome 74.0.3729.157 on windows
pxtapp.js:1730 enabled webusb
pxt.azureedge.net/blob/d7a1b6d0e456099543ac85d0ee2285efc8e22fe2/sim.webmanifest:1 Manifest: property 'start_url' ignored, should be same origin as document.
pxt.azureedge.net/blob/d7a1b6d0e456099543ac85d0ee2285efc8e22fe2/sim.webmanifest:1 Manifest: property 'scope' ignored, should be same origin as document.
pxtapp.js:1730 PouchDB adapter: idb
(index):1 Application Cache NoUpdate event
psopafpj:1 Failed to load resource: the server responded with a status of 404 ()
3(index):1 Uncaught (in promise) DOMException
pxtapp.js:1730 storage estimate: 0%, 139/133284Mb
pxtapp.js:1730 quota usage exceeded, clearing translations
pxtapp.js:1730 storage estimate: 0%, 139/133284Mb
pxtapp.js:1730 quota usage exceeded, clearing translations
icon:1 Failed to load resource: the server responded with a status of 404 (Not Found)
pxtapp.js:1730 storage estimate: 0%, 139/133284Mb
pxtapp.js:1730 quota usage exceeded, clearing translations
pxtapp.js:1730 storage estimate: 0%, 139/133284Mb
pxtapp.js:1730 quota usage exceeded, clearing translations
/api/ghsearch/microbit/microbit?q=kitronik:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/api/ghsearch/microbit/microbit?q=pxt-kitronik:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/api/ghsearch/microbit/microbit?q=pxt-kitronik-stopbit:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
pxtapp.js:1730 storage estimate: 0%, 139/133284Mb
pxtapp.js:1730 quota usage exceeded, clearing translations
pxtapp.js:1730 storage estimate: 0%, 139/133284Mb
pxtapp.js:1730 quota usage exceeded, clearing translations
pxtapp.js:1730 storage estimate: 0%, 140/133284Mb
pxtapp.js:1730 quota usage exceeded, clearing translations
DevTools failed to parse SourceMap: https://pxt.azureedge.net/blob/dd22520c096be24e7432f5b46e8aad59711f31f0/ai.0.js.map
DevTools failed to parse SourceMap: https://pxt.azureedge.net/blob/9a85cf9992061da7718b59a573ff5e9e17a64be5/vs/editor/editor.main.js.map
```

This appears to be sporadic and hard to consistently reproduce. Has anything changed re Github API rate limiting or similar?

**Comment by abchatra** [comment]
@darzu  likely related to server exception related to ghsearch

**Comment by microbit-mark** [comment]
@abchatra @darzu We're still hitting this issue with Kitronik extensions. Are you able to look into it.

**Comment by abchatra** [comment]
@microbit-mark  I don't repro this. I see lot of extensions when I search for kitronik

**Comment by AlasdairAtKitronik** [comment]
@abchatra The issue isn't that none of our extensions appear, it's that some of them are missing (often different each time) when 'Kitronik' is searched. Also that the 'Halo HD' search returns a missing error, when it definitely does exist and has previously been used.

**Comment by abchatra** [comment]
'Halo HD' succeeds for me. 

>> it's that some of them are missing (often different each time) when 'Kitronik' is searched.
We display top N and can you file a different issue for this one. we will look into increasing the top N limit.

**Comment by microbit-mark** [comment]
I can't repro, but I wondered if it was Github rate limiting again

**Comment by AlasdairAtKitronik** [comment]
@abchatra I will open a different issue for the 'top N' search return thing. However, I think that if you search the exact name of an extension it should come up - can that issue remain here?

**Comment by abchatra** [comment]
It does come up for you when I search 'Halo HD'. It is not coming up for you?

![image](https://user-images.githubusercontent.com/6107272/74946019-84c25f80-53ad-11ea-96d8-f25c57721810.png)

**Comment by AlasdairAtKitronik** [comment]
When I search 'Halo HD', I get this:
![image](https://user-images.githubusercontent.com/36475405/74946429-3040d380-53f1-11ea-8162-bf2616f282bb.png)
(Note: The extensions in the image are just my local ones)

**Comment by AlasdairAtKitronik** [comment]
This is the same for several of us in the office at the moment.
It also sometimes happens to other Extensions we have approved.

**Comment by abchatra** [comment]
This is because you have local setup of the same extension. I believe you built the extension.  Please try in-private (in-cognito in chrome) window and try searching the same extension. Consumers won't get that local extension as it is specific to you.

**Comment by AlasdairAtKitronik** [comment]
OK, yes, I was able to successfully search it in in-cognito mode.
Is that from have the GitHub repo cloned on my PC, or is it from being logged into GitHub through MakeCode in the browser?

**Comment by abchatra** [comment]
It is because you logged into GitHub through MakeCode in browser and you developed that extension.

**Comment by abchatra** [comment]
Fixed
