### ISSUE TITLE
Icon and message update for offline app

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#2135]
•	Use microbit icon
•	Check icon size for "medium" tile. See my Start menu... top is MakeCode for micro:bit (online) app; bottom is offline

![image](https://user-images.githubusercontent.com/6107272/58990442-c026ea80-879a-11e9-868a-507566a58c5b.png)

•	Seems like the mouse over needs updated to remove Electron

![image](https://user-images.githubusercontent.com/6107272/58990473-cf0d9d00-879a-11e9-99ef-dc089e8d2a9d.png)

**Comment by abchatra** [comment]
Not sure but you might have to set the following in pxt-deployment-config

        "appIconPath": null,

**Comment by microbit-mark** [comment]
Is it possible to name the app 'MakeCode for micro:bit (offline)' to help users differentiate it from the win10 app if they have both installed. Also this may make it clear for students/teachers opening it that it is intended to work offline.

**Comment by abchatra** [comment]
Fixed
