### ISSUE TITLE
Clicking on main.blocks in a dependency switches to blocks

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#2136]
Clicking on a `main.blocks` of a dependency in the Monaco explorer switches to the blocks editor (with the current project loaded, not the dependency's blocks). Instead it probably just shouldn't show the `main.blocks` in the explorer since it gets ignored anyways.

1. Go to the microbit editor
2. Import an extension with a `main.blocks` file (shared project works)
4. Switch to JavaScript
5. In the explorer, expand the dependency and click on the `main.blocks` file
6. The blocks editor will open

**Comment by abchatra** [comment]
Won't fix
