### ISSUE TITLE
Feature: MakeCode Blocks Poster/Cheatsheet

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2139]
**Is your feature request related to a problem? Please describe.**
We occasionally get requests for a printable poster of MakeCode blocks for the classroom, that could be annotated and used as a teaching tool.

**Describe the solution you'd like**
A way to render a printable A3/A2 sized sheet of a set of blocks, maybe everything above 'Advanced' or a pick your own tool to add in the blocks you want. Maybe this could be linked and/or generated in the reference docs.

**Describe alternatives you've considered**
You can use the snapshot tool to add in the blocks you want to the workspace and download, but this is more time consuming. 

**Additional context**
We have talked about this before in https://github.com/microsoft/pxt/issues/2327 but adding here to bring it back into pxt-microbit as we still get requests for it.

**Comment by microbit-mark** [comment]
Is this something you can follow up on @Jaqster? Let me know if we can help.

**Comment by abchatra** [comment]
This is already implemented. @ganicke can you please point to the docs where all the blocks are listed for microbit.

**Comment by ganicke** [comment]
A blocks listing is auto-generated when you hit this address:

https://makecode.microbit.org/block-gallery

Hopefully that is what @abchatra is referring to.

**Comment by microbit-mark** [comment]
Thanks @ganicke. This is really useful. I think the poster format requested would still be most useful, but good to know this is here.

Perhaps a TOC at the top of the page would help too.
