### ISSUE TITLE
installing as per readme on windows has issues with nodejs serial module

### ISSUE THREAD

**Issue by gingemonster** [Microsoft/pxt-microbit#214]
If you install the current repo on windows and follow the readme's instructions I found that you cannot start pxt serve as the windows binaries don't appear to be there.

To get round this I had to create an empty directly and run:

"npm install serialport@2.1.2"

then copy the modules it download over the modules in the "pxt-microbit\node_modules\pxt-core\node_modules\serialport" folder. Not sure is this is an issue with pxt-core or that ptx-microbit isnt getting the latest ptx-core?

**Comment by pelikhan** [comment]
Please try again. Fixed serialport number.
