### ISSUE TITLE
Feature: Menus with sub-menus remember state

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2143]
micro:bit support: 22579
**Is your feature request related to a problem? Please describe.**
"Each time I select and use a block from one of these, all of the sub menus collapse and close again. It's a bit annoying to have to keep expanding the same item over and over again."
![Screenshot_20190602-073128](https://user-images.githubusercontent.com/31242877/59095957-b2e03c00-8911-11e9-8109-a7421cdcd2b3.png)

**Describe the solution you'd like**
the blocks menu should remain in the last state it was in when you chose a block. For example if you click on menu, then a sub menu and then a block, you expect when you open the 
 menu again, to see the same submenu open.

**Comment by abchatra** [comment]
We should at-least keep the more option selected until another category is selected. This is more like a UI bug.
