### ISSUE TITLE
Micro chat tutorial step 3 hint parsed incorrectly

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2148]
**Describe the bug**

Step is rendered incorrectly

**To Reproduce**
1. Go to micro chat tutorial
2. go to step 3
3. See error

**Expected behavior**

should have blocks as hint

**Screenshots**

![Screen Shot 2019-06-07 at 11 34 45 AM](https://user-images.githubusercontent.com/5615930/59125918-8845b180-8918-11e9-9ece-c4425278fd84.png)

**Comment by abchatra** [comment]
Fixed
