### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2149]
Regression - the comments color is all black

Beta - 
![Comments Beta](https://user-images.githubusercontent.com/22108954/59126398-da3b0700-8919-11e9-8e9c-bdd9a8d24a0e.png)

Live - 
![Comments Live](https://user-images.githubusercontent.com/22108954/59126407-e1faab80-8919-11e9-855f-b77deefdbf8a.png)

**Comment by abchatra** [comment]
This is a regression from live. We should try to fix this.

**Comment by abchatra** [comment]
Fixed
