### ISSUE TITLE
Javascript snippets don't work in IE11

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#2151]
**Describe the bug**
![ie-snippet](https://user-images.githubusercontent.com/34112083/59131946-ae734d80-8928-11e9-9c51-6b1513f0eb25.gif)

**To Reproduce**
1. Go to editor, switch to Javascript
2. Drag block out from toolbox
3. No code snippet

**Desktop (please complete the following information):**
 - Browser: IE11

**Comment by abchatra** [comment]
@pelikhan this is your change? This is broken in IE11.
