### ISSUE TITLE
Editor, blocks embed doesn't use beta like simulator embed

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2154]
**Describe the bug**

Editor and blocks embed don't have beta in src like simulator embed does when sharing from the beta editor

**To Reproduce**

1. Go to project and share
2. Click on embed
3. see urls in src
4. editor and blocks do not maintain beta, simulator does

**Expected behavior**

embed links maintain blocks

**Screenshots**

![2019-06-07 13 44 50](https://user-images.githubusercontent.com/5615930/59132864-23478700-892b-11e9-8a8d-ce95effb6178.gif)

**Comment by riknoll** [comment]
@jwunderl @pelikhan @abchatra what is the decision here? Are we getting rid of the feature?

**Comment by abchatra** [comment]
Simulator embed should not point to /beta. Similar to share feature should always point to live. 

If someone want to point to /beta they have to manually edit it. 

Fix is to make sure simulator embed doesn't point to beta

**Comment by riknoll** [comment]
What about v0, v1, etc? Not that it really matters unless we're planning to make more of those

**Comment by abchatra** [comment]
Corner cases, I wouldn't worry about them.
