### ISSUE TITLE
Slider and analog value always display on pin press

### ISSUE THREAD

**Issue by kimprice** [microsoft/pxt-microbit#2158]
**Describe the bug**
The slider and analog value are displayed in the simulator on pin press even when the analog value is not being read.

**Expected behavior**
We should only show the slider and analog value when the workspace includes blocks/code relevant to reading the analog value like "readAnalogValue()."

**Screenshots**
![pinSlider](https://user-images.githubusercontent.com/15070078/59135011-3f025b80-8932-11e9-9c88-9f1fa15529a5.png)

**Comment by abchatra** [comment]
This is by current design.

**Comment by abchatra** [comment]
Decided to keep it for backward compat.
