### ISSUE TITLE
Fold commands in command palette do nothing

### ISSUE THREAD

**Issue by JacobBovee** [microsoft/pxt-microbit#2160]
**Describe the bug**
No fold commands in command palette do anything.

**To Reproduce**
1. Go to https://makecode.microbit.org/beta#editor
2. Click on JavaScript
3. Press f1
4. Navigate to and click on any fold command.

**Expected behavior**
The code should fold level 1 on fold and at least fold all on fold all or otherwise not exist.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge

**Comment by abchatra** [comment]
F1 is advanced. Unlikely kids will hit this.

**Comment by abchatra** [comment]
Closing P3.
