### ISSUE TITLE
Stop melody all does not stop melodies playing in the background.

### ISSUE THREAD

**Issue by kimprice** [microsoft/pxt-microbit#2162]
**Describe the bug**
Stop melody all does not stop melodies that are playing in the background.

**To Reproduce**
See picture.

**Expected behavior**
All melodies should stop playing.

**Screenshots**
![stopMelodyAll](https://user-images.githubusercontent.com/15070078/59136173-c3ef7400-8936-11e9-96a7-4695bbecaf5e.png)

**Comment by abchatra** [comment]
@pelikhan Expected?

**Comment by pelikhan** [comment]
This is the behavior of the new music library. We need to keep a list of melodies playing in order to stop them all.

________________________________

**Comment by pelikhan** [comment]
This might be a regression; a feature interaction with the microbit background sounds and the new sound engine.
