### ISSUE TITLE
Multiple functions written in javascript stack directly over each other in blocks

### ISSUE THREAD

**Issue by JacobBovee** [microsoft/pxt-microbit#2164]
**Describe the bug**
When making multiple functions in JavaScript decompiling to blocks overlays them over each other such that you only see the top most function.

**To Reproduce**
1. Go to https://makecode.microbit.org/beta#editor
2. Go to javascript
3. Write multiple functions
4. Compile to blocks

**Expected behavior**
Functions should spread over work spaces so that they can be found by users afterwards.

**Screenshots**
Javascript
![image](https://user-images.githubusercontent.com/6301646/59136449-18dfba00-8938-11e9-8a60-ceedfc50b7a3.png)

Blocks:
![image](https://user-images.githubusercontent.com/6301646/59136469-2eed7a80-8938-11e9-9e1f-534fcadc03ff.png)

After dragging top function:
![image](https://user-images.githubusercontent.com/6301646/59136495-4593d180-8938-11e9-8336-96c688d99a1e.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abchatra** [comment]
@JacobBovee I can't repro this. What browser is this?
