### ISSUE TITLE
Update offline EULA webpage

### ISSUE THREAD

**Issue by halspeed** [microsoft/pxt-microbit#2166]
On the [offline app EULA page](https://makecode.microbit.org/offline-app), update to something like this:

![image](https://user-images.githubusercontent.com/29285304/59170072-83dcec80-8b02-11e9-8684-706b74a251bf.png)

**Comment by pelikhan** [comment]
Could you provide more details on your request?

**Comment by halspeed** [comment]
@Jaqster asked me to take the call/email discussion and file an issue. Instead of having the long EULA and having to scroll in the browser, create a text box that allows the user to scroll in the text box. This also gives a clear indication of where the user is to accept the EULA.

You could also consider making it like a GitHub text box that the user can resize.

Once the box is checked, then you can display the download links like you do today.

**Comment by jwunderl** [comment]
(implemented a while ago, missed that this was assigned; closing)
