### ISSUE TITLE
Tutorial "Love Meter" and "Coin Flipper" hint can't be opened

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2168]
**Describe the bug**
Tutorial "Love Meter" and "Coin Flipper" hint can't be opened

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta
2. Open one tutorial "Love Meter" and "Coin Flipper" 
3. Click on the left of the banner to open and close hint

**Expected behavior**
Hint should can be opened and closed on each browser

**Actual behavior**
Tutorial "Love Meter" and "Coin Flipper" hint can't be opened
![Issue610002](https://user-images.githubusercontent.com/23466737/59187995-41221f80-8ba9-11e9-83b7-4fdce014a2f6.gif)

**Additional info:**
1. makecode.microbit.org version: 1.4.15
2. Microsoft MakeCode version: 5.15.5
3. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)
4. This bug repro on each browser on Windows

**Comment by pelikhan** [comment]
This bug looks related to the double toggle hint issue. Investigating.

**Comment by abchatra** [comment]
Fixed @Helen09 please validate.

**Comment by Helen09** [comment]
Validated, this bug has been fixed
