### ISSUE TITLE
Hint in tutorial "Name Tag" 5th step can't be clicked

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2169]
**Describe the bug**
Hint in tutorial "Name Tag" 5th step can't be clicked

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta
2. Open one tutorial "Name Tag" and navigate to 5th step
3. Click on the left of the banner to open the hint

**Expected behavior**
Hint should can be opened or should be removed

**Actual behavior**
Hint in tutorial "Name Tag" 5th step can't be clicked
![6003](https://user-images.githubusercontent.com/23466737/59188329-fb198b80-8ba9-11e9-8fc3-178ea09cea5c.gif)

**Additional info**
1. makecode.microbit.org version: 1.4.15
2. Microsoft MakeCode version: 5.15.5
3. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)
4. This bug repro on each browser on Windows

**Comment by abchatra** [comment]
@shakao  There is no hint in this step. So this is as expected?

**Comment by pelikhan** [comment]
From a user perspective, it is confusing since we taught them to tap on the icon to open the hint.

**Comment by pelikhan** [comment]
We should have hints on all steps...

**Comment by abchatra** [comment]
This is existing behavior in live. Probably we should remove light bulb if there is no hint.

**Comment by abchatra** [comment]
Fixed
