### ISSUE TITLE
Remove dialog close button

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2171]
Dialog in tutorials have a "OK" and a "X" button. Get rid of the X.
![image](https://user-images.githubusercontent.com/4175913/59207058-1c06c000-8b5b-11e9-9b6c-bcac7da0a033.png)

**Comment by pelikhan** [comment]
Why are we not fixing this? it's just about setting a "false" flag on the dialog instance.

**Comment by abchatra** [comment]
Not a regression from live. I don't want to pick improvement at this late stage. Feel free to fix. There are lot of blocking issues we need to fix first.
