### ISSUE TITLE
Offline app zip does not unarchive on Mac

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2175]
micro:bit support 22476
**Describe the bug**
Trying to download the Mac OS zip file from https://makecode.microbit.org/offline-app and the zip file is 'broken' - the OS won't unzip in Finder or on command line.

![Screenshot 2019-06-11 at 14 49 13](https://user-images.githubusercontent.com/31242877/59277612-6de14000-8c58-11e9-8cf6-70ba50aab1a9.png)

![7DA94D30-ADE6-44B6-A1C1-5FBC24E6F12C](https://user-images.githubusercontent.com/31242877/59278088-4a6ac500-8c59-11e9-9a4c-98c3940e4f77.jpg)

Also noticed there are erros on the download page where the mime-type for some assets is wrong, so files are blocked by the browser.  I don't think that this has a bearing on the download, unless there is something 'smart' happening that doesn't work.

![Screenshot 2019-06-11 at 10 39 09](https://user-images.githubusercontent.com/31242877/59277931-f4961d00-8c58-11e9-93c0-0ea2340778d3.png)

**Expected behavior**
App should install as expected

**Desktop (please complete the following information):**
 - OS: Mac 10.14.4

Tested this with 4 other people who get the same error

**Comment by microbit-mark** [comment]
@abchatra assigning you as this seems like a high priority one to fix for launch

**Comment by abchatra** [comment]
@jwunderl Can you please investigate and make recommendation. I understand we are unable to repro this.

**Comment by jaustin** [comment]
I just reproduced it and I've got:
MD5 (makecode-microbit-mac64-new-chrome.zip) = 055119139a21b64fcf5e30df4ecbde72
MD5 (makecode-microbit-mac64-new.zip) = 055119139a21b64fcf5e30df4ecbde72

Previously I got
MD5 (makecode-microbit-mac64.zip) = bddee775b7f82046edb62fb1fbca4cdd

**Comment by jaustin** [comment]
Works for me today. 

MD5 (makecode-microbit-mac64-release.zip) = 4814728f519bd5ff2f61466740afa751

**Comment by abchatra** [comment]
Fixed

**Comment by keshin** [comment]
I have same issue today:
```
MD5 (makecode-microbit-mac64.zip) = a5f1db00d35f3173c72cd10ad68bd498
```
