### ISSUE TITLE
"LedSprite" and "sprite" in make function dialog cannot be translated

### ISSUE THREAD

**Issue by sgk** [microsoft/pxt-microbit#2176]
**Describe the bug**
It is not able to translate the "LedSprite" and "sprite" words in the make function dialog. Other words have no problem ("Text", "text", "Boolean", "bool", "Number", "num").

**To Reproduce**
1. Under the "Functions" category, click the "Make a Function..." button.
2. Confirm the words "LedSprite" and "sprite".
3. Try to find these words in Crowdin.

**Expected behavior**
The "LedSprite" and "sprite" words should appear in Crowdin. 

**Screenshots**
![image](https://user-images.githubusercontent.com/485416/59287209-2edcda00-8cac-11e9-8440-1b4b9869103c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75.0.3770.80

**Comment by pelikhan** [comment]
Whoever built the function dialog need to fix this

**Comment by pelikhan** [comment]
Or maybe add block=“LedSprite” to the LedClass class decl
