### ISSUE TITLE
Download button spins forever and never times out

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#2179]
I don't have a good repro, but occasionally I've seen the download button spin indefinitely (on Chrome and on the Electron app at least):
![image](https://user-images.githubusercontent.com/6453828/59315363-56ad4d00-8c6e-11e9-999c-eeaeb3116ebf.png)

The only solution I've found is to refresh the page or close and re-open the electron app.

Regardless of how we got into this state, we should have some form of timeout such that we eventually give up and tell the user "something went wrong; we were unable to download. Please check that the microbit was connected and try again".

Current repro info:
- shows up in at least: winrt, chrome
- I saw this at Build so May 6th

**Comment by pelikhan** [comment]
I have seen that too. It’s utterly annoying.

**Comment by abchatra** [comment]
Without repro I don't know what we can do? Are there any exceptions?

**Comment by darzu** [comment]
I haven't seen any exceptions, I haven't caught it in the debugger, I haven't been able to repro it when trying. To really fix this, yes, we'll need a repro and we should all pay attention to it to see if we can learn something.

But we definitely can do something now. We can tell that we've shown the download spinner for > X seconds. We should have a timeout that eventually gives up and lets the user retry.

**Comment by darzu** [comment]
Other things we can do: inspect the download code paths to see if we can find functions that might be running forever. Set timeouts on these with telemetry logging when they're hit. Someone in the wild is going to hit this again and then we can see the telemetry data.

There's always something that can be done.

**Comment by darzu** [comment]
Repro from Joey:

```
Uncaught TypeError: Cannot read property 'preferredEditor' of undefined
    at MainPackage.Package.setPreferredEditor (pxtapp.js:8781)
    at e.syncPreferredEditor (main.js:5)
    at e.compile (main.js:5)
    at t.compile (main.js:83)
    at t.handleClick (main.js:83)
    at Object.ka (main.js:761)
    at Object.invokeGuardedCallback (main.js:761)
    at Object.invokeGuardedCallbackAndCatchFirstError (main.js:761)
    at Fa (main.js:761)
    at Ja (main.js:761)
    at La (main.js:761)
    at Ha (main.js:761)
    at Oa (main.js:761)
    at Pa (main.js:761)
    at Td (main.js:761)
    at batchedUpdates (main.js:761)
```

**Comment by jwunderl** [comment]
Might be worth noting that that occurred after changing the board from pybadge to meowbit

**Comment by Jaqster** [comment]
From a customer: "I can reproduce this bug all the time with v2.0.10 in the Windows 10 app by just taking a small break and then getting back to coding. Almost every time it will go into the spinning bug."

**Comment by abchatra** [comment]
Fixed
