### ISSUE TITLE
Block editor/Radio Lib/Serial number

### ISSUE THREAD

**Issue by martincottrell** [Microsoft/pxt-microbit#218]
You can switch sending the serial number on but there is no support to retrieve it from a packet?  There is documentation for Radio.RecievedNumberAt, would it be at position 0?  However this block does not exist in the editor?

**Comment by abchatra** [comment]
@riknoll Please take look if this will be fixed by your callback work on radio. If yes close this issue and tag it with the issue in pxt.

**Comment by riknoll** [comment]
I'm working on this right now. Tracked in https://github.com/Microsoft/pxt/issues/465
