### ISSUE TITLE
Update FAQ to mention offline apps

### ISSUE THREAD

**Issue by microbit-rosslowe** [microsoft/pxt-microbit#2180]
The existing FAQ currently says the following re using MakeCode offline:

> ### Can I use MakeCode when I’m not connected to the internet?
> Yes, when MakeCode first loads in the browser, it tells the browser to download the files it needs to work locally. If you later want to add an extension to use with your program, you will need to connect again. See the page about using MakeCode offline.

This doesn't make any immediate reference to the offline apps available for some targets. Could the copy be updated to call out offline apps, either with generic copy or with micro:bit-specific copy?

Suggested generic copy:

> ### Can I use MakeCode when I’m not connected to the internet (offline)?
> Some targets support using [offline apps](https://makecode.microbit.org/offline). Additionally, a cached version of MakeCode can be used offline - when MakeCode first loads in the browser, it tells the browser to download the files it needs to work locally. If you later want to add an extension to use with your program, you will need to connect again. For more information see the page about using MakeCode [offline](https://makecode.microbit.org/offline).

**Comment by ganicke** [comment]
FAQ updated in https://github.com/microsoft/pxt/pull/5669.
