### ISSUE TITLE
Functions are still not supported, only procedures and sub-routines

### ISSUE THREAD

**Issue by rhubarbdog** [microsoft/pxt-microbit#2181]
**Is your feature request related to a problem? Please describe.**
I thought i'd test function parameters with a simple recursive factorial calculation.
It is only possible via an itteritive method and  returning the value via a "special" global variable `return_value`

**Describe the solution you'd like**
Functions to support a return value 

**Describe alternatives you've considered**
Using a different algorithm and setting a global variable `return_value` which has to be dealt with in the main loop immediately after the call to the *procedure*

**Comment by rharbird** [comment]
Yes please for this feature.

**Comment by obrasier** [comment]
+1 for this feature. Was a little staggered return values aren't supported in function blocks.

**Comment by riknoll** [comment]
available now on makecode.microbit.org/beta
