### ISSUE TITLE
Strings look like they have a space prepended to them

### ISSUE THREAD

**Issue by rhubarbdog** [microsoft/pxt-microbit#2182]
**Describe the bug**
I type in the stgring `True` it looks like " True"

**To Reproduce**
add a `basic.showString` block to your code edit the string from "Hello" to say "True"
it looks like " True"
 
**Expected behavior**
The left and right quotes of a string paramter to appear close to the text, this would make the nul string look like "", single space as " " and any word as "any word"

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.2
 - Browser : Mozilla firefox
 - Version: 67.0

**Additional context**
This is the same on chromium which yeilds the following information when i enter command `chromium-browser --version`

Using PPAPI flash.
Chromium 74.0.3729.169 Built on Ubuntu , running on LinuxMint 18.2

**Comment by woutput** [comment]
This issue appears to be the same as #1764

**Comment by abchatra** [comment]
Duplicate #1764 which we are tracking for next release.
