### ISSUE TITLE
Single digits should have a space displayed after them

### ISSUE THREAD

**Issue by rhubarbdog** [microsoft/pxt-microbit#2183]
**Is your feature request related to a problem? Please describe.**
I display the number 0, followed by 97.
I get the display 0 pause, left scroll 097

**Describe the solution you'd like**
If a single digit is to be displayed followed by any text or numbers the display should scroll left before displaying the second element
 
**Describe alternatives you've considered**
adding the block `basic.showString(" ")`

**Comment by abchatra** [comment]
This is by design. Existing lights scoll off when you have to display a large number.
