### ISSUE TITLE
Tooltip is "Hide the simulator" even when hidden

### ISSUE THREAD

**Issue by sgk** [microsoft/pxt-microbit#2184]
**Describe the bug**
Even when the simulator is hidden, the tooltip of the show/hide vertical tab is "Hide the simulator".

**To Reproduce**
1. Hide the simulator in the editor.
2. Move the mouse pointer over the show/hide vertical tab.

**Expected behavior**
It should be better if the tooltip is "Show simulator" when the simulator is hidden.

**Screenshots**
![image](https://user-images.githubusercontent.com/485416/59351799-2e9b1800-8d5a-11e9-8396-7ee041aee593.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75.0.3770.80

**Comment by abchatra** [comment]
Fixed.
