### ISSUE TITLE
Less memory in beta without infinite array

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#2185]
**Describe the bug**
With this program maximum array size is 143 in live but only 58 in beta.

https://makecode.microbit.org/_KU11X1hWYPr0

**To Reproduce**
1. Go to 'https://makecode.microbit.org/_KU11X1hWYPr0'
2. Click on 'Edit'
3. Download
4. Observe 143 on micro:bit
5. Repeat with beta

**Expected behavior**
Ideally beta should not have much less memory available.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
makecode.microbit.org version:  1.4.17
Microsoft MakeCode version:  5.15.7
microbit runtime version:  pxtgc-0

**Comment by martinwork** [comment]
https://makecode.microbit.org/_WLDDmgKDp2j5

This similar program will handle 410 items in the array on v1, while v2 still only does 58. The change is that the GATT table size is reduced in settings. This only seems to make more memory available in v1.

**Comment by abchatra** [comment]
FIxed.

**Comment by martinwork** [comment]
Not fixed. Both of the examples above now show panic 844.

**Comment by abchatra** [comment]
Didn’t the limit increase with the GC fix?

**Comment by martinwork** [comment]
I believe the GC limit was increased, but was reduced again because it triggered other issues.

Note that the second example is an extension of the original example to BLE programs. It looks like with GC the extra memory freed by reducing the GATT table size is no longer available.

As I understand it, the big problem here is that the new memory model splits the available memory between types of use so many programs that previously used all of memory for one purpose will no longer work.

**Comment by atrus159** [comment]
Hi, about a week ago my code that had previously been able to store a 640 long array can now only store an 80 long array. Is this the same issue as mine?

**Comment by pelikhan** [comment]
Have you tried the largest beta?

**Comment by atrus159** [comment]
I gotta admit, don't actually know what the beta is.

**Comment by pelikhan** [comment]
Sorry our bad!  Try https://makecode.microbit.org/beta

**Comment by atrus159** [comment]
Seems to still have the same issue. Im gonna test with smaller arrays

**Comment by martinwork** [comment]
https://makecode.microbit.org/_6Df1sK6Uwio6

This is a similar example without BLE. In V1 (v1.2.13) (https://makecode.microbit.org/v1) the maximum array size seems to be 2042. In live (v2.0.6) and beta (v2.1.4) it's somewhere between 1750 and 1800. For size 1800, the panic is 844.

**Comment by abchatra** [comment]
@atrus159 can you share your program

**Comment by atrus159** [comment]
@abchatra 
https://github.com/Tinkertanker/pxt-oled-ssd1306
The issue seems to be the array in Main.ts called fonts. If I make it much shorter the error stops.

**Comment by martinwork** [comment]
It looks like the font array should be in flash rather than RAM. I don't know how that is specified in typescript. ReadonlyArray?

**Comment by abchatra** [comment]
Can't fix.
