### ISSUE TITLE
I can't publish a project from beta

### ISSUE THREAD

**Issue by rhubarbdog** [microsoft/pxt-microbit#2187]
**Describe the bug**
I wanted to include some blocks in a previous bug report. After clicking the relevant buttons.
I get the message "Oops! There was an error. Please ensure you are connected to the Internet and try again."

**To Reproduce**
1) Enter some blocks.
2) click "share"
3) click "publish"
I get the error message "Oops! There was an error. Please ensure you are connected to the Internet and try again."
4) I repeat step 3 still get the error
5) click on to java script listing and back to blocks it works!!
6) click onto java script
7) click "share"
8) click "publish", i get the error "Oops! There was an error. Please ensure you are connected to the Internet and try again."

**Expected behavior**
share/publish to work first time, it's not my internet (i believe) as the error happens so i open a new page (ebay.co.uk) without issue.

**Desktop (please complete the following information):**
 - OS:Linux mint 18.2
 - Browser - mozilla firefox
 - Version - 67.0

**Additional context**
It may be my internet is (very) temporarily slow. I'm using a 4G connection. If you can supply some test program or talk me through a quick performance test i can elliminate it being my ISP

**Comment by abchatra** [comment]
This error is displayed if the share page can't reach our server which means internet connection is bad.
