### ISSUE TITLE
Videos can't be opened in China for there is a limited access for YouTube in China

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2188]
**Describe the bug**
Videos can't be opened in China for there is a limited access for YouTube in China

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta
2. Scroll down to "Behind the MakeCode Hardware" and open videos one by one

**Expected behavior**
Videos should can be opened 

**Actual behavior**
Videos can't be opened in China for there is a limited access for YouTube in China
![6 11](https://user-images.githubusercontent.com/23466737/59396651-591dbd00-8dbc-11e9-9787-8a218ecc2cdc.PNG)

**Additional info**
1. makecode.microbit.org version: 1.4.17
2. Microsoft MakeCode version: 5.15.7
3. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)
4. This bug repro on each browser on Windows

**Comment by abchatra** [comment]
We can't fix this as of now. Closing.
