### ISSUE TITLE
Selected projects are not selected after changing display mode

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2189]
**Describe the bug**
Selected projects are not selected after changing display mode

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta
2. Click on "My Projects" to show all projects(such as there are many projects)
3. Select few projects and switch display mode("Name" or "Last Modified")

**Expected behavior**
Selected projects should be selected after changing display mode

**Actual behavior**
Selected projects are not selected after changing display mode
![Issue61301](https://user-images.githubusercontent.com/23466737/59408076-b2e6ad00-8de5-11e9-8373-b95b6089da8d.gif)

**Additional info**
1. makecode.microbit.org version: 1.4.17
2. Microsoft MakeCode version: 5.15.7
3. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)
4. This bug repro on each browser on Windows

**Comment by abchatra** [comment]
Won't fix.
