### ISSUE TITLE
Only the first step of "flashing heart" is translated into Chinese, others are not

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2190]
**Describe the bug**
Only the first step of "flashing heart" is translated into Chinese, others are not

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor 
2. Click "More..." -> "Language" -> choose "Chinese (Simplified)"
3. Back to home page and open tutorials one by one

**Expected behavior**
Each tutorial should be translated into Chinese

**Actual behavior**
Only the first step of "flashing heart" is translated into Chinese, others are not
![Issue61302](https://user-images.githubusercontent.com/23466737/59411994-1b865780-8def-11e9-87a5-d69a149a67b1.gif)

**Additional info**
1. makecode.microbit.org version: 1.4.17
2. Microsoft MakeCode version: 5.15.7
3. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)
4. This bug repro on each browser on Windows

**Comment by abchatra** [comment]
@jwunderl can you take a quick peek?

**Comment by jwunderl** [comment]
Can confirm only the first step is translated, but that seems to just be that crowdin only has 25% translations for that file?

![Screen Shot 2019-06-13 at 9 58 47 AM](https://user-images.githubusercontent.com/5615930/59452271-30002b00-8dc2-11e9-9d02-59d22a8fccca.png)

I can't immediately check the files to verify that the correct translations are showing up though as I'm not a member of the crowdin, had to put in a request for access

**Comment by ganicke** [comment]
Sometimes prior translations are invalidated when updates to a file occur. However, I see no suggested strings in the Translation Memory (TM) for any of the remaining untranslated sentences. I think we go to close on this issue.

**Comment by abchatra** [comment]
Requires translation in crowdin.
