### ISSUE TITLE
Funereal/Funeral Melody Mismatch

### ISSUE THREAD

**Issue by ChaseMor** [microsoft/pxt-microbit#2193]
**Describe the bug**
The melody is called `Funereal` in blocks, but is called `Melodies.Funeral` in JavaScript. 

**Expected behavior**
The two should match

![image](https://user-images.githubusercontent.com/13285164/59455412-fe3e9280-8dc8-11e9-8be7-9d6125c2ee65.png)

![image](https://user-images.githubusercontent.com/13285164/59455391-f383fd80-8dc8-11e9-931d-742197fdffad.png)

**Comment by abchatra** [comment]
@darzu

**Comment by darzu** [comment]
Hey @hristoramirez , here's a good first bug
