### ISSUE TITLE
On chromebook, blocks / javascript toggle has no vertical padding

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2194]
**Describe the bug**

On wide thin screens, the toggle loses the padding above / below it. This makes the drop shadow show up in the workspace slightly

**To Reproduce**
1. Go to microbit beta
2. make screen wide but short
3. See error

**Expected behavior**

live site:

![Screen Shot 2019-06-13 at 10 55 15 AM](https://user-images.githubusercontent.com/5615930/59455909-021ee480-8dca-11e9-815f-1a597de99bb1.png)

**Screenshots**

beta behavior:

![Screen Shot 2019-06-13 at 10 53 24 AM](https://user-images.githubusercontent.com/5615930/59455927-0ba84c80-8dca-11e9-8008-ce1261aee4f4.png)

**Desktop (please complete the following information):**
 - OS: chrome but repros everywhere when thin enough

**Comment by abchatra** [comment]
Done by @pelikhan to save space.
