### ISSUE TITLE
Offline - Tutorials don't work when not connected

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2195]
If you are disconnected, you can't run any of the Tutorials.  Reference docs work fine.

![Tutorials](https://user-images.githubusercontent.com/22108954/59456138-8c674880-8dca-11e9-9efc-283db984cb4f.png)

**Comment by abchatra** [comment]
Tutorials work fine for me in offline. We bundle them.

**Comment by abchatra** [comment]
@riknoll can you test this?

**Comment by abchatra** [comment]
fixed
