### ISSUE TITLE
Offline Videos

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2196]
We might think of a nicer way to handle videos in the Offline app.  Maybe we could run a script or something to pull them all out of the docs when we build the app?

![Video2](https://user-images.githubusercontent.com/22108954/59456392-144d5280-8dcb-11e9-8d38-d39ec8570a94.png)

![Video1](https://user-images.githubusercontent.com/22108954/59456406-17e0d980-8dcb-11e9-956f-489346b81cfc.png)

**Comment by abchatra** [comment]
Won't fix :-(. This will increase the size of the installer by a big margin.
