### ISSUE TITLE
Offline Green Screen

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2198]
Using the offline app, Green Screen can't connect to cameras - just shows the green background.

![GreenScreen](https://user-images.githubusercontent.com/22108954/59456759-ea486000-8dcb-11e9-96a3-8ef9f5a8d504.png)

![GreenScreen2](https://user-images.githubusercontent.com/22108954/59456770-ecaaba00-8dcb-11e9-9c6d-eff20dc81caa.png)

**Comment by abchatra** [comment]
Disable green screen may be in the offline for now (similar to other browsers

**Comment by pelikhan** [comment]
We can disable the cameras, leave the green screen.

**Comment by abchatra** [comment]
Fixed by disabling camera in offline mode.
