### ISSUE TITLE
pictures appear massive

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#22]
1 go to any page with images

2 example

http://localhost:3232/lessons/lucky-7/quiz

3 pictures appear massive

![image](https://cloud.githubusercontent.com/assets/11206682/14158258/0529704a-f684-11e5-9bc4-d5f12e606e8e.png)

**Comment by pelikhan** [comment]
@mmoskal Can we apply classes to image generated by marked?

**Comment by mmoskal** [comment]
You can try run a regular expression in docsrender.ts

**Comment by pelikhan** [comment]
Oh, it’s done in docsrender! Yes, will fix.

**Comment by mmoskal** [comment]
I'll have to deploy to server later - it's manual, this file has to be replaced https://github.com/Microsoft/TouchDevelop-backend/blob/master/external/backendutils.js , but you can test on localhost

**Comment by pelikhan** [comment]
I've made updates. will require update.

**Comment by pelikhan** [comment]
FIxed.
