### ISSUE TITLE
Offline - Reference can't be opened when network is not connected 

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2202]
**Describe the bug**
Offline - Reference can't be opened when not connected 

**Steps to reproduce the behavior**
1. Disconnect network
2. Click "Help" -> "Reference" -> "basic"

**Expected behavior**
Reference should can be opened

**Actual behavior**
Reference can't be opened 
![Issue61401](https://user-images.githubusercontent.com/23466737/59495915-f3682880-8ec2-11e9-80cc-71168e30539b.gif)

**Additional info**
1. makecode.microbit.org version: 1.4.18
2. Microsoft MakeCode version: 5.15.8
3. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)

**Comment by Helen09** [comment]
“Blocks”, "JavaScript" and "Hardware" also can't be opened. User need to open these with network firstly

**Comment by abchatra** [comment]
Won't fix. We can't bundle all the documentation in the offline app.
