### ISSUE TITLE
Offline - "Support" and "Buy" can't be opened when not connected

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2203]
**Describe the bug**
Offline - "Support" and "Buy" can't be opened when not connected

**Steps to reproduce the behavior**
1. Disconnect network
2. Click "Help" -> "Support" and "Buy" 

**Expected behavior**
"Support" and "Buy" should can be opened

**Actual behavior**
"Support" and "Buy" can't be opened
![Issue61405](https://user-images.githubusercontent.com/23466737/59497222-94f07980-8ec5-11e9-9e67-9b047cec63de.PNG)

**Additional info**
1. makecode.microbit.org version: 1.4.18
2. Microsoft MakeCode version: 5.15.8
3. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)

**Comment by pelikhan** [comment]
These are extenal web sites. They require internet.
