### ISSUE TITLE
Offline - Only few extensions can be loaded

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2204]
**Describe the bug**
Offline - Only few extensions can be loaded

**Steps to reproduce the behavior**
1. Disconnect network
2. Click "Advanced" -> "Extensions" 

**Expected behavior**
Extensions should can be loaded 
![Issue61408](https://user-images.githubusercontent.com/23466737/59501552-5ad7a580-8ece-11e9-9721-b87379c4b466.gif)

**Actual behavior**
Only few extensions can be loaded
![Issue614007](https://user-images.githubusercontent.com/23466737/59501432-19df9100-8ece-11e9-8c66-8facfd5fa062.PNG)

**Additional info**
1. makecode.microbit.org version: 1.4.18
2. Microsoft MakeCode version: 5.15.8
3. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)

**Comment by pelikhan** [comment]
Added docs on offline + extensions https://github.com/microsoft/pxt/pull/5678
