### ISSUE TITLE
Functions need to accept arrays as arguments

### ISSUE THREAD

**Issue by rhubarbdog** [microsoft/pxt-microbit#2205]
**Is your feature request related to a problem? Please describe.**
I have the need for a procedure which accepts an array of strings as an argument

**Describe the solution you'd like**
Arrays to be available as a type of argument to functions and procedures.  To make the logic easier for children to understand. Arrays probably need to be a copy of the array (a value) rather than a reference to it as it is in the C programming language.

**Describe alternatives you've considered**
Creating a procedure with n arguments and unpacking each array element into individual arguments and rebuilding the array in the procedure.
Because i know all the strings are 8 long i could pass the array of strings as one long concatenated string which i split into an array in the procedure 

**Additional context**
If functions (procedures with return values) are to be fully supported.  Returning an array would be nice, but i know this isn't really supported in the C programming language. Which i believe underlies all of the microbit programming languages/methods

**Comment by IowaDave** [comment]
The MakeCode editor enables users to create custom blocks that accept arrays as parameters and return arrays as values. I offer an example at this repository: [https://github.com/IowaDave/pxt-arrays-with-custom-blocks](https://github.com/IowaDave/pxt-arrays-with-custom-blocks),

**Comment by livcheerful** [comment]
In /beta now!
