### ISSUE TITLE
Beta no longer sees old projects

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#2207]
**Describe the bug**
When switching to beta on Windows Chrome, the projects listed on the Home screen are no longer the same as live.

My iPad microbit app updated to 2.0.2 and no longer had no old projects. 

**Expected behavior**
Not lose all old projects.

**Desktop (please complete the following information):**
 - OS: Windows, iOS
 - Browser chrome, safari

**Comment by martinwork** [comment]
Correction... My iPad hasn't updated live to 2.0.2. It's because it's using beta, which is 2.0.2. But beta projects are different from live.

**Comment by jwunderl** [comment]
We're looking into this now, thanks for pointing this out!

**Comment by martinwork** [comment]
On iOS Safari, beta is seeing very old projects from 7 or 8 months ago, but not more recent ones which are visible on live.

**Comment by martinwork** [comment]
Thanks!

**Comment by martinwork** [comment]
It was fine yesterday. Not sure about this morning.

**Comment by abchatra** [comment]
It is importing from v0 instead of v1.

**Comment by jwunderl** [comment]
Should be fixed with newest beta release: https://github.com/microsoft/pxt-microbit/pull/2208

**Comment by abchatra** [comment]
Fixed in 2.0.3

**Comment by abchatra** [comment]
Thank you very much @martinwork. This is a great find and MakeCode team really appreciates it finding and reporting it. @jaustin fyi

**Comment by martinwork** [comment]
Thanks. Lucky I was experimenting at the right time.

**Comment by jaustin** [comment]
Nice catch Martin and thanks MS team for the speedy fix :)
