### ISSUE TITLE
Dragging a hex file to editor is not setting the name correctly

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt-microbit#221]
This is a regression as it works with files create a couple weeks ago. 

If you create a hex file and drag it to the editor, it loads up the code but the title is showing "untitled". 

Repro:
* Create a new project .. make sure change title, add code etc
* Download to a .hex
* Go to new project
* Drag / drop that .hex file to the editor
** Notice - code is showing but title is showing as "untitled"

**Comment by darrenge** [comment]
Figure it is a hex issue since older hex files work

**Comment by mmoskal** [comment]
I think this is on @pelikhan side

**Comment by abchatra** [comment]
This is fixed.
