### ISSUE TITLE
Compilation error with beta version Friday June 14th

### ISSUE THREAD

**Issue by tototek** [microsoft/pxt-microbit#2213]
Compilation error with this code in new beta version (was working OK)

bluetooth.onBluetoothConnected(function () {
    basic.showString("C")
})
bluetooth.onBluetoothDisconnected(function () {
    basic.showString("D")
})
control.onEvent(EventBusSource.MES_DPAD_CONTROLLER_ID, EventBusValue.MICROBIT_EVT_ANY, function () {
    if (control.eventValue() == EventBusValue.MES_DPAD_BUTTON_A_DOWN) {
        maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CW, 220)
        maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CW, 220)
    } else if (control.eventValue() == EventBusValue.MES_DPAD_BUTTON_A_UP) {
        maqueen.motorStopAll()
    } else if (control.eventValue() == EventBusValue.MES_DPAD_BUTTON_B_DOWN) {
        maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CCW, 220)
        maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CCW, 220)
    } else if (control.eventValue() == EventBusValue.MES_DPAD_BUTTON_B_UP) {
        maqueen.motorStopAll()
    } else if (control.eventValue() == EventBusValue.MES_DPAD_BUTTON_C_DOWN) {
        maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CW, 0)
        maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CW, 255)
    } else if (control.eventValue() == EventBusValue.MES_DPAD_BUTTON_C_UP) {
        maqueen.motorStopAll()
    } else if (control.eventValue() == EventBusValue.MES_DPAD_BUTTON_D_DOWN) {
        maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CW, 255)
        maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CW, 0)
    } else if (control.eventValue() == EventBusValue.MES_DPAD_BUTTON_D_UP) {
        maqueen.motorStopAll()
    } else if (control.eventValue() == EventBusValue.MES_DPAD_BUTTON_1_DOWN) {
        maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CCW, 0)
        maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CCW, 255)
    } else if (control.eventValue() == EventBusValue.MES_DPAD_BUTTON_1_UP) {
        maqueen.motorStopAll()
    } else if (control.eventValue() == EventBusValue.MES_DPAD_BUTTON_2_DOWN) {
        maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CCW, 255)
        maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CCW, 0)
    } else if (control.eventValue() == EventBusValue.MES_DPAD_BUTTON_2_UP) {
        maqueen.motorStopAll()
    } else if (control.eventValue() == EventBusValue.MES_DPAD_BUTTON_4_DOWN) {
        music.ringTone(262)
    }
})
basic.showString("Q6")

Microbit and Maqueen BLE control working Ok  before the update.

Best Regards

Marcelo

**Comment by jwunderl** [comment]
To confirm, this is using the bluetooth and https://github.com/DFRobot/pxt-maqueen packages, correct?

**Comment by tototek** [comment]
Hi  Mr Joey,
Yes this package. I write more simple code and do not work.
bluetooth.onBluetoothConnected(function () {
basic.showString("C")
})
bluetooth.onBluetoothDisconnected(function () {
basic.showString("D")
})
control.onEvent(EventBusSource.MES_DPAD_CONTROLLER_ID,
EventBusValue.MICROBIT_EVT_ANY, function () {
if (control.eventValue() == EventBusValue.MES_DPAD_BUTTON_A_DOWN) {
maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CW, 0)
maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CW, 0)
} else if (control.eventValue() == EventBusValue.MES_DPAD_BUTTON_A_UP) {
maqueen.motorStopAll()
}
})
basic.showString("Q6")

Best Regards
Marcelo

**Comment by jwunderl** [comment]
Could you send a share link for the code that isn't working please? That one seemed to work for me as well for some reason.

**Comment by tototek** [comment]
Hi Joey, I send you the code screenshot
The error is "compilation failed "

Regards

Marcelo
