### ISSUE TITLE
Simulator Keyboard Shortcuts

### ISSUE THREAD

**Issue by microbit-sam** [microsoft/pxt-microbit#2219]
**Is your feature request related to a problem? Please describe.**

From support:

> I've been facing an issue with the UI experience of the simulator while doing my recent project. I have to tilt the board to each of the four directions and press the A button. The moment I drag the  pointer to up or down or right directions, I cannot press the 'A button' since it's present on the left of the board. I can do this nearly on a real Microbit board. Is there a way to do it or is that a bug with UI?

**Describe the solution you'd like**

Would it be possible to add keyboard shortcuts for the buttons e.g. listen for 'a' and 'b' and trigger the buttons when pressed

**Describe alternatives you've considered**

Tabbing through the  elements and pressing spacebar/enter to select - it worked for me but was either not clear enough for the user, or isn't supported by all browsers

**Comment by abchatra** [comment]
No plans to implement

**Comment by Vegz78** [comment]
Would be really nice, though!:
https://forum.makecode.com/t/2-questions-moving-multiple-blocks-in-editor-and-micro-bit-simulator-keyboard-control/31389

And maybe there are synergies for the micro:bit simulator with existing keyboard controls in or all the mouse and keyboard input stuff recently developed for Arcade?:
https://forum.makecode.com/t/keyboard-mouse-input-extension/5988/14
