### ISSUE TITLE
Do not calibrate when reading magnetic field strength

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-microbit#222]
UserVoice: https://touchdevelop.uservoice.com/forums/402381-code-the-micro-bit/suggestions/15720702-dont-ask-for-compass-calibration-when-only-measuri

**Comment by pelikhan** [comment]
https://github.com/lancaster-university/microbit-dal/issues/205

**Comment by abchatra** [comment]
Tracked by the issue in lancaster-university/microbit-dal#205
