### ISSUE TITLE
Need help with new radio blocks

### ISSUE THREAD

**Issue by CleoQc** [microsoft/pxt-microbit#2222]
In the previous version of Microbit makecode our package had pre-made remote control blocks which were using the (now old) radio.  They are now broken.

The original code is here: https://github.com/DexterInd/pxt-giggle/blob/master/giggle.ts#L146-L209

For the moment, I have something sorta working locally by duplicating the radio-broadcast blocks (nice feature btw, love it!). However I am struggling in passing actual information, basically two numbers from -100 to 100 which represent the motor powers.  Can I use radio packets with the radio-broadcast blocks?

**Comment by abchatra** [comment]
@riknoll can you take a look?

**Comment by CleoQc** [comment]
I think I'm going to be okay. I found a workaround (not pretty but works) that will keep using the new standard radio blocks. 
I'm just missing one final step, which is to convert a hexadecimal string back into a number. Should be straightforward but everything I try is not supported in makecode.

**Comment by pelikhan** [comment]
Why not working with a buffer and avoid string all together?

**Comment by CleoQc** [comment]
All good now. Love the new radio blocks once I did a deep dive!

As for using buffers, I'm not going that way cause the code made my eyes glaze over. The issue is with me, not with the code.

**Comment by riknoll** [comment]
Right, we added a new function called `radio.sendBuffer()` and `radio.onReceivedBuffer()` which are better suited to these kinds of use cases.

It would look something like this:

```typescript
function sendPower(powerLeft: number, powerRight: number) {
    // Buffer is 8 bytes (two 32-bit floating point numbers)
    const buf = control.createBuffer(8);
    buf.setNumber(NumberFormat.Float32BE, 0, powerLeft);
    buf.setNumber(NumberFormat.Float32BE, 4, powerRight);
    radio.sendBuffer(buf)
} 

radio.onReceivedBuffer(function (receivedBuffer: Buffer) {
    const powerLeft = receivedBuffer.getNumber(NumberFormat.Float32BE, 0);
    const powerRight = receivedBuffer.getNumber(NumberFormat.Float32BE, 4);
})
```

**Comment by riknoll** [comment]
Oh, great! Nevermind then

**Comment by CleoQc** [comment]
Hee hee. Posting at the same time. I do like your code example. Thanks a lot! 

Looks simple enough.  I might just switch over! 👍

**Comment by pelikhan** [comment]
You can pack more data with better layout control using a buffer.

**Comment by CleoQc** [comment]
Indeed you can.  I just couldn't make heads or tails of the API quickly enough under the circumstances. (Personal issues, nothing to do with the pxt code)

**Comment by CleoQc** [comment]
Yes! All good now with buffer.
Thank you everyone. I can go back to mourning now.
