### ISSUE TITLE
Use VS Code with Win 10 app

### ISSUE THREAD

**Issue by kristianpedersen** [microsoft/pxt-microbit#2223]
I would like to be able to use VS Code to edit my .ts files, but I can't figure out which location the app saves my projects to.

I've seen there's a CLI option, but it seems like a hassle to install, compared to just opening existing .ts files with VS Code.

**Comment by abchatra** [comment]
PXT saves files in a json format in webbrowser cache of electron. You will need to copy paste the ts file to work on VS Code today. We are planning to build a VS Code extension in the future.
