### ISSUE TITLE
Split view blocks/code

### ISSUE THREAD

**Issue by kristianpedersen** [microsoft/pxt-microbit#2224]
I would like to have a split blocks/code view, which updates whenever the other section is changed. If I add a block, the code should change, and vice versa.

Personally, I would like to have this functionality when making and testing new blocks in custom.ts. Switching between custom.ts and blocks view is a bit tedious.

If I change the block itself - by for example adding a new parameter - it would be nice to have those changes reflected in block view, or at least be able to see a preview of the new block.

**Comment by abchatra** [comment]
Please try https://makecode.com/playground which provides this functionality.
