### ISSUE TITLE
Error code 848

### ISSUE THREAD

**Issue by microbit-pauline** [microsoft/pxt-microbit#2225]
**Describe the bug**
A user has contacted micro:bit through support as they have an error code and cannot locate information on the error.

Can you provide some information?

Error code -  sad face 848

**Comment by pelikhan** [comment]
https://makecode.microbit.org/device/error-codes The list is outdated.

**Comment by martinwork** [comment]
https://makecode.com/js/errorcodes

> The error codes in the 800-899 are even more internal:
> 
> 84X - garbage collector errors

**Comment by martinwork** [comment]
Where does this panic occur in the source code?

**Comment by microbit-pauline** [comment]
I asked the user the question and the response was "When trying to display an image on the scrollbit".
I'm not sure if that is helpful.

**Comment by martinwork** [comment]
Sorry @microbit-pauline , if that was my question. I was hoping @pelikhan  or @mmoskal  might point me towards where panic 848 is generated in the MakeCode source code.

**Comment by mmoskal** [comment]
The GC errors 84x are not something users can diagnose. If you really want, you can search for oops(48) or check macro with 48 argument in gc.cpp

To diagnose it we need the user program

**Comment by martinwork** [comment]
Thanks @mmoskal . Found it in
https://github.com/microsoft/pxt-common-packages/blob/master/libs/base/gc.cpp

@microbit-pauline Can the user supply the program that causes the error?

**Comment by microbit-pauline** [comment]
@martinwork I've made the request

**Comment by ThScho** [comment]
I get error code 848 when displaying "Hello World" on a scroll:bit (https://shop.pimoroni.de/products/scroll-bit). micro:bit crashes (?) after displaying "Hel". Sometimes error code 848 is shown, sometimes not.

**Comment by ThScho** [comment]
After reinstalling the scroll;bit software onto the device the error didn't occur any longer.
