### ISSUE TITLE
Can't locate a webUSB button in android chrome

### ISSUE THREAD

**Issue by rhubarbdog** [microsoft/pxt-microbit#2226]
**Describe the bug**
I'm trying to test webUSB from my android phone. I go to page 
https://makecode.microbit.org/beta there's  no button to flash.

**Expected behavior**
Following instructions at 
https://microbit.us14.list-manage.com/track/click?u=e1c30f24b90ff3d70275cfff2&id=f3ca03eda9&e=5b7714d356 it implies that the android version of chrome and MakeCode support webUSB flashing.  There should be a flash button but i can't see it 

**Smartphone (please complete the following information):**
 - Device: samsung j5 mobile phone
 - OS: android 8.1.0, Samsung experience version 9.5
 - Browser chrome
 - Version 75.0.3770.101

**Comment by martinwork** [comment]
Try updating micro:bit firmware to 253 here: https://microbit.org/guide/firmware/

**Comment by martinwork** [comment]
Note that https://support.microbit.org/support/solutions/articles/19000084059-beta-testing-web-usb mentions 250. Needs to say 253, or perhaps latest. I nearly didn't bother because I knew I had 250.

**Comment by rhubarbdog** [comment]
I've just had success running `chromium-browser` on my ubuntu laptop with version 250 of the firmware. The instructions say it'll work with firmware 249.

The problem is that pair device is on the wheel button menu. Which doesn't display on android.

This has been reported in issue https://github.com/microsoft/pxt-microbit/issues/2227

**Comment by martinwork** [comment]
Oh I see. It didn't seem to work with 250 for me with Samsung tablet, but worked with 253.
