### ISSUE TITLE
Wheel icon's menu appears off screen

### ISSUE THREAD

**Issue by rhubarbdog** [microsoft/pxt-microbit#2227]
**Describe the bug**
I press the wheel button from the beta editor. Most of the menu options appear off the screen and i can't navigate to it

**To Reproduce**

1. Goto https://makecode.microbit.org/beta#
2. Click on any/new project to get to the blocks window
3. Press the wheel button
4. The menu appears mostly off screen and i can't scroll left to it

**Expected behavior**
The menu should appear on screen and be usable
**Screenshots**
![Screenshot_20190625-120532_Chrome](https://user-images.githubusercontent.com/33667064/60093583-b2cda200-9741-11e9-9019-89fcb06edc9b.jpg)

**Smartphone (please complete the following information):**
 - Device: samsung j5 mobile phone
 - OS: android 8.1.0, samsung experience version 9.5
 - Browser chrome
 - Version 75.0.3770.101

**Comment by martinwork** [comment]
Same problem on iPhone. Workaround: turn phone landscape.

**Comment by abchatra** [comment]
This is fixed.
