### ISSUE TITLE
Copy-Paste does not work

### ISSUE THREAD

**Issue by rei-vilo** [microsoft/pxt-microbit#2228]
**Describe the bug**
Copy-Paste does not work on input fields, *e.g.* `Rechercher ou entrer l'URL du projet...`

**To Reproduce**

<img width="512" alt="Capture  2019-06-25 à 19 34 34" src="https://user-images.githubusercontent.com/951776/60120160-8127fb80-9780-11e9-86e3-d963dd9abbcd.png">

+ Select an http address, *e.g.* https://github.com/MKleinSB/pxt-fischertechnik
+ Press ctrl-C
+ Select the field `Rechercher ou entrer l'URL du projet...`
+ Press ctrl-V

The field `Rechercher ou entrer l'URL du projet...` remains empty when the clipboard contains the http address, *e.g.* https://github.com/MKleinSB/pxt-fischertechnik

**Expected behavior**
Content of the clipboard goes on the input field.

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5 (18F132)
 - Browser   Safari 12.1.1 (14607.2.6.1.1), Chrome 75.0.3770.100 (64 bits)
 - Version 
<img width="512" alt="Capture  2019-06-25 à 19 46 05" src="https://user-images.githubusercontent.com/951776/60120842-095ad080-9782-11e9-96ac-da8e79a1ca69.png">

**Additional context**
N/A

**Comment by riknoll** [comment]
I can reproduce this in the macOS offline app. As a workaround, you can right click and paste.
