### ISSUE TITLE
block display in same position

### ISSUE THREAD

**Issue by shaoziyang** [microsoft/pxt-microbit#2229]
**Describe the bug**
I update DS1302 language, it is all fine in English language mode, but when I select Chinese language mode, all block display in same position. 

**To Reproduce**
1. Add DS1302 extension in makecode.
2. Select English language. 
3. Select Chinese language.

**Screenshots**

in Chinese language mode

![image](https://user-images.githubusercontent.com/1037534/60145292-2df18f80-97f8-11e9-8687-b0e5c690eb0f.png)

in English language mode

![image](https://user-images.githubusercontent.com/1037534/60145327-42358c80-97f8-11e9-8631-c44063b9e3e0.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome, Firefox, Internet explorer

**Comment by pelikhan** [comment]
Which package?

________________________________

**Comment by shaoziyang** [comment]
DS1302 package.
https://github.com/makecode-extensions/DS1302

**Comment by abchatra** [comment]
@pelikhan There is an issue in the translation of the block right? 

I am assuming this not PXT bug.

**Comment by ganicke** [comment]
I think you have a double ``%ds|`` in your block string. Remove one and give that a try.

See: https://github.com/makecode-extensions/DS1302/blob/71c9386333ce197b7dd66b66bc2aa9ff6f432c01/_locales/zh/DS1302-strings.json#L17

```
"DS1302.DS1302RTC.DateTime|block": "%ds|%ds|设置时间: 年 %year|月 %month|日 %day|星期 %weekday|时 %hour|分 %minute|秒 %second",
```

**Comment by ganicke** [comment]
Bug in https://github.com/makecode-extensions/DS1302 localization.
