### ISSUE TITLE
block comment can drag out of workspace

### ISSUE THREAD

**Issue by gengshenghong** [microsoft/pxt-microbit#2230]
**Describe the bug**
we can drag the comment of a block outside of the workspace, and cannot drag it back anymore.

**To Reproduce**
1. https://makecode.microbit.org/#editor
2. drag a block into workspace, any bloc. for example: show number
3. right click on the block, click "add comment"
4. drag the comment window, outside of the workspace
5. you can never drag it back as it is hidden, see below:
![屏幕快照 2019-06-26 下午3 51 25](https://user-images.githubusercontent.com/1018468/60161499-4e3a4200-982a-11e9-9529-5b9f2e18f36c.png)
6. you may drag multiple times if it is still inside your workspace. Finally, you cannot drag it back any more.

**Expected behavior**
The comment window should snap to edge of the workspace to avoid the issue, like the workspace comments.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Chrome
 - Version: 74.0.3729.169

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by abchatra** [comment]
Won't fix. Corner case, you can drag the block to get the comment back in the window .
