### ISSUE TITLE
webUSB times out before flashing is complete

### ISSUE THREAD

**Issue by rhubarbdog** [microsoft/pxt-microbit#2231]
**Describe the bug**
I currently have issues with my ISP, the internet is running real slow but works.  When I try and flash some blocks onto a microbit it times out. giving an error message "Some ting went wrong, it took too much time"

**To Reproduce**
With an overloaded/slow internet
1. create some blocks
2. click wheel button and select pair device from the menu
3. pair the microbit
4. click Download
5. After a few minutes the microbit will have flashed or the Error box will pop up

I'm unable to re-create this today, my internet connection is far more responsive than yesterday.

**Expected behavior**
Flashing to eventually work, even if it takes 10 minutes. it's obvious that the microbit is flashing as the yellow LED is blinking and it hasn't disconnected, unmounted and re-mounted.  Can't you approximate the flashing time by `ping`-ing a relevant MakeCode site and doing a calculation. Inform the user this operation will take upto X minutes.  Only timing out if the current time limit + X minutes has expired
 
It occurs on both desktop and smartphone
**Desktop (please complete the following information):**
 - OS: Linux Mint 18.2
 - Browser chromium
 - Version 74.0.3729.169

**Smartphone (please complete the following information):**
 - Device: samsung j5 mobile phone
 - OS: android 8.1.0 with samsung experience 9.5
 - Browser chrome
 - Version 75.0.3770.101

**Comment by abchatra** [comment]
This should be fixed now.
