### ISSUE TITLE
Clicking download creates a MakeCode second window and an Operating System one

### ISSUE THREAD

**Issue by rhubarbdog** [microsoft/pxt-microbit#2232]
**Describe the bug**
I'm using the beta editor. I create a program and want to put it onto a microbit. I click download
Both an operating system window to save/open file and a MakeCode secondary window are created.

**To Reproduce**
1. create some blocks
2. click download to save
3. both windows are simultaneously created

**Expected behavior**
The opeating system window should only open after i've clicked the button 'microbit-blocky.hex' as shown on screen shot 2

**Screenshots**
screen shot 1
![Screenshot at 2019-06-27 10-32-10](https://user-images.githubusercontent.com/33667064/60255297-69a75a80-98c7-11e9-84dd-c5e038c0255e.png)

screen shot 2
![Screenshot at 2019-06-27 10-34-37](https://user-images.githubusercontent.com/33667064/60255335-7deb5780-98c7-11e9-8d1d-9c2eac074c80.png)

**Desktop (please complete the following information):**
 - OS: Linux mint 18.2
 - Browser : Mozilla firefox
 - Version : 67.0

**Comment by riknoll** [comment]
This is the expected behavior

**Comment by rhubarbdog** [comment]
Are you sure? Or have i described this issue badly.
I click the purple 'dowload' button from the editor screen. This produces an os window and a makecode window. I click ok on the os window a hex file is created in my Download directory. I click the green 'microbit-blocky.hex' in the makecode pop up again an os window is created. So i click ok on that i now have a second .hex file.
`ls ~/Downloads` yields 
microbit-blocky(1).hex microbit-blocky.hex

2 hex files which one should i use?
Are you trying to confuse students and make teachers life more difficult?

**Comment by rhubarbdog** [comment]
By the way when i try to download a project as a .hex file. Your editor hangs and i have to click the cross icon (at the top right) of the MakeCode window

**Comment by riknoll** [comment]
Some browsers don't automatically start the download, so we give a button to start the download manually just in case. It's common practice for downloading files in the browser; both hex files are the same.
