### ISSUE TITLE
webUSB :Connecting a phone to Microbit needs documenting with a diagram

### ISSUE THREAD

**Issue by rhubarbdog** [microsoft/pxt-microbit#2233]
**Is your feature request related to a problem? Please describe.**
to connect my phone to a microbit I have a micro-usb -> usb MF connector and a usb -> micro-usb MM connector. When I plug them together it creates a micro-usb -> micro-usb MM conector.  The issue is it looks like it plugs either way (in fact it does) the issue is there is a correct way and an incorrect way to connect the phone to the microbit.

For illustration purposes i have used a 3G feature phone to represent my smart phone. I needed the smart phone to take the photographs.

This works and the yellow LED is illuminated.
![20190627_104722](https://user-images.githubusercontent.com/33667064/60257465-6910c300-98cb-11e9-8b1c-2f9490265a92.jpg)

where as this doesn't and the yellow LED remains unlit.
![20190627_104744](https://user-images.githubusercontent.com/33667064/60257498-7b8afc80-98cb-11e9-9fa1-49be290c4723.jpg)

**Describe the solution you'd like**
There needs to be a nice graphic showing this connection issue.

**Describe alternatives you've considered**
A genuine MM micro-usb to micro-usb cable is probably the solution to be used by students at school

**Comment by abchatra** [comment]
@riknoll @pelikhan Isn't micro usb bidirectional? Any way you connect should work right?

**Comment by abchatra** [comment]
Both directions need to work and no repro for us.  Please use different cables and retry, likely issue with the cable.
