### ISSUE TITLE
isGesture does not work without onGesture

### ISSUE THREAD

**Issue by andrewmh20** [microsoft/pxt-microbit#2234]
**Describe the bug**
The isGesture blocks do not work unless there is also a onGesture block. When writing code that uses the isGesture block it does not resolve as true when the gesture is done unless there is a corresponding onGesture block. The onGesture block may be empty, and it also works with an advanced onEventFrom block (using MICROBIT_ID_GESTURE and MES_GESTURE_DEVICE_SHAKEN. Additionally, the gesture chosen for the empty onGesture block may be different than the gesture you are attempting to note in the isGesture block. However the onGesture block must be a gesture, not an onButtonPressed block. With either of these empty blocks (functions in the javascript view) present the isGesture block works as expected.

**To Reproduce**
Write the following JS code in the makecode editor: 
```
basic.forever(function () {
    if (input.isGesture(Gesture.Shake)) {
        basic.showNumber(0)
        basic.pause(500)
        basic.showLeds(`
            . . . . .
            . . . . .
            . . . . .
            . . . . .
            . . . . .
            `)
    }
})
```
**Expected behavior**
I expected the microbit to show 0 for 500ms when shaken.
This behavior is attained when editing the code as follows, for example, as described above:

```
input.onGesture(Gesture.TiltLeft, function () {
	
})
basic.forever(function () {
    if (input.isGesture(Gesture.Shake)) {
        basic.showNumber(0)
        basic.pause(500)
        basic.showLeds(`
            . . . . .
            . . . . .
            . . . . .
            . . . . .
            . . . . .
            `)
    }
})
```

**Screenshots**
In block form the code that does not work:
![image](https://user-images.githubusercontent.com/1943441/60293725-cc135180-98ed-11e9-9213-0c355acc9bf9.png)

The code that does work:
![image](https://user-images.githubusercontent.com/1943441/60293707-c4ec4380-98ed-11e9-9641-2d4531d6e301.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 75

**Additional context**
The code that does not work on the microbit works as expected in the microbit simulator.

**Comment by andrewmh20** [comment]
#1873 #1870

**Comment by microbit-mark** [comment]
micro:bit support: 23214 another user reports this issue. Works in sim not on device

**Comment by microbit-mark** [comment]
micro:bit support 23681, 23680 more users report this issue.

**Comment by abchatra** [comment]
@pelikhan do you know why I gesture doesn't work without on gesture block?

**Comment by microbit-mark** [comment]
@pelikhan @abchatra just nudging this one again. Can we prioritise as this has had multiple reports.

**Comment by martinwork** [comment]
A call to MicroBitAccelerometer::requestUpdate() is needed to start accelerometer updates.

This happens if an onGesture block is present or if the accelerometer is read with an input/acceleration block, but isGesture just calls uBit.accelerometer.getGesture() which simply returns the value of a variable which isn't updated if MicroBitAccelerometer isn't updating.

Perhaps isGesture should call requestUpdate()?

**Comment by martinwork** [comment]
So a different workaround is to do this in onStart:
let dummy = input.acceleration(Dimension.X)

**Comment by pelikhan** [comment]
Thanks @martinwork

**Comment by martinwork** [comment]
https://github.com/lancaster-university/microbit-dal/blob/master/source/drivers/MicroBitAccelerometer.cpp#L275

If I am understanding this code, the 3g, 6g and 8g conditions will only occur as events. They never make it to the variable read by getGesture().

I certainly can't get 3g, 6g and 8g to work with isGesture, even with a matching onGesture block present.

Should these conditions be removed from the options for isGesture?

Should I make a new issue?

**Comment by microbit-mark** [comment]
Tested https://github.com/microsoft/pxt-microbit/pull/2413 in Beta and it fixes the issue, but not https://github.com/microsoft/pxt-microbit/issues/2234#issuecomment-527887020 so have opened a seperate issue. Thanks for raising this @martinwork
