### ISSUE TITLE
Windows offline app installer does not run

### ISSUE THREAD

**Issue by dleeapho** [microsoft/pxt-microbit#2236]
**Describe the bug**
The Windows offline app installer is not runnable

**To Reproduce**
1. Go to https://makecode.microbit.org/offline-app
2. Accept the EULA
3. download makecode-microbit-setup-win64.exe
4. Run the exe
5. Windows reports "This app will not run on your pc. To search a version of this app for your pc, please contact the app supplier."

**Expected behavior**
The installer runs and the app is installed.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 18362.175
 - Browser Chrome
 - Version 75.0.3770.100

**Additional context**
Re-occurrence of #1938 perhaps?

**Comment by abchatra** [comment]
@dleeapho  Are you running 32 bit windows 10? We only support 64 bit windows 10. See
 Settings > System > About 

![image](https://user-images.githubusercontent.com/6107272/61889447-4964be80-aeba-11e9-9ff7-a7a3c947f7ba.png)

**Comment by dleeapho** [comment]
@abchatra  no, I was running 64 bit Windows 10.

**Comment by SSoulard** [comment]
I agree, this app doesn't work on W10 (but is fine on Apple..).
I used the link below to download the offline app in my classroom and get a 111 109 ko file which can't be executed.
Have you any idea ?
https://makecode.microbit.org/offline-app

**Comment by abchatra** [comment]
@SSoulard  and @dleeapho. Does the following link work for you? 
https://pxt.azureedge.net/ghdl/242539eb4e33b5821603d8fe8c465bd8/makecode-microbit-setup-win64.exe

**Comment by SSoulard** [comment]
Hi, 
Unfortunately, we have the same error message.
I use an Intel Core I3 x64.

**Comment by zhengyangliu** [comment]
> @SSoulard and @dleeapho. Does the following link work for you?
> https://pxt.azureedge.net/ghdl/242539eb4e33b5821603d8fe8c465bd8/makecode-microbit-setup-win64.exe

Thanks, It's work for me~.
System: Win10 18362.657 x64 
CPU: Core i7 7700

**Comment by abchatra** [comment]
We can't repro this issue on x64 build.
