### ISSUE TITLE
Editor does not load on a 1st gen iPad mini with iOS 9.3.5

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#2237]
**Describe the bug**
On a 1st gen iPad mini with iOS 9.3.5, the home page loads but the editor does not.

This has been reported via a Foundation support ticket. V1 loads.

**To Reproduce**
1. Go to 'https://makecode.microbit.org/'
2. Tap 'New Project'
3. See error

**Expected behavior**
The editor should load.

**Screenshots**
![IMG_0958](https://user-images.githubusercontent.com/989126/60369389-5f7e7c80-99eb-11e9-90f3-d2d333e85671.png)

Or if launched with "#editor"...

![IMG_0957](https://user-images.githubusercontent.com/989126/60369397-65745d80-99eb-11e9-96f1-b75017494e6e.png)

**Desktop (please complete the following information):**
 - OS: 1st gen iPad mini with iOS 9.3.5
 - Browser Safari

**Comment by microbit-mark** [comment]
Can you triage this one @pelikhan @abalone23 @jwunderl ? User would like a response. Recent release of the editor no longer loads.

**Comment by jwunderl** [comment]
I can repro this in xcode simulator with iOS 9.3, it gives the very unhelpful ``[Error] Error: Script error. (---worker, line 4)`` message, which only indicates it's an error in ``pxtworker.js`` that caused it to not load. Seeing if I can narrow down where it broke exactly a bit more now~

**Comment by themarkness** [comment]
We have more users reporting this issue on iPad. This will be particularly problematic for iPad deployments such as those in UK libraries, who may be using older hard/software

**Comment by jwunderl** [comment]
Finally identified what broke and got a fix, but that needs to be ported to the live site - reopening until that makes it in.

**Comment by martinwork** [comment]
Brilliant. Thanks @jwunderl . When will it get to beta?

**Comment by jwunderl** [comment]
Fix is on live site now, will be on beta in a few days (somehow we managed to get that backwards this time :) )
