### ISSUE TITLE
Extensions > Import File

### ISSUE THREAD

**Issue by kiate** [microsoft/pxt-microbit#2241]
**Is your feature request related to a problem? Please describe.**
Hi, I'm looking at importing offline extensions on MakeCode Offline as mention here https://makecode.microbit.org/offline. I noticed that if the project HEX file I saved has program code in it, using Extensions > Import File feature to open this project HEX file will not only load the extension correctly, but also load the program code earlier. This program code will not be shown in the new project but the simulator is running it and if upload to micro:bit, this previous code will run first before the new code in 'on start' and run concurrently with new code in 'forever'.

I understand that the article does mention "You don’t need to add any program code to the project". But in many cases people will have internet access most of the time and are able to use MakeCode online as usual. The problem comes when internet downtime catch people off guard. There might be no project file with extension only (without other program code) to import from.

**Describe the solution you'd like**
Extensions > Import File feature should be able to automatically remove all program code that comes with the project HEX file and load the extension only. This provides a more intuitive user experience and eliminate unnecessary confusion when it comes to the beginners.

**Describe alternatives you've considered**
1. User has to remember to keep a copy of project HEX file in their local disk with the extension installed but without any program code and also has to remember to update this file whenever there's an update to the MakeCode or the extension.
2. User has to import the project HEX file directly at Home page, delete the code manually and start using the extension from there. 

**Additional context**
Video demo of the issue: https://files.slack.com/files-pri/T1ZMPDV9P-FKYLPGNJ0/download/makecode_offline_extension_import.wmv

Thank you.

**Comment by abchatra** [comment]
Thanks for the nice bug report @kiate

**Comment by abchatra** [comment]
@pelikhan  fyi

**Comment by abchatra** [comment]
This is implemented. We have extensions->import file now.
