### ISSUE TITLE
Backwards compatibility: script that works in old-style editor doesn't work in new editor

### ISSUE THREAD

**Issue by rharbird** [microsoft/pxt-microbit#2243]
**Describe the bug**
I have two scripts which provide different functions for a 2-wheel, stepper motor robot:

https://makecode.microbit.org/v0/77418-20868-49450-75100 and
https://makecode.microbit.org/v0/23251-35306-65508-70942

If the script is opened and run in the old-style editor, it works but if the script is opened in the new-style editor, it doesn't. 14 compilation errors are reported.

**To Reproduce**
1. Go to https://makecode.microbit.org/v0/77418-20868-49450-75100 or https://makecode.microbit.org/v0/23251-35306-65508-70942
2. Click on 'Edit in the old editor'. Use the blocks to write code, download to microbit -- THIS WORKS.

**Error**
3. Alternatively, go to https://makecode.microbit.org/v0/77418-20868-49450-75100 or https://makecode.microbit.org/v0/23251-35306-65508-70942
4. Click on the Edit button.
5. You will see that the simulation microbit never appears.
6. Switch to Javascript and look at the Explorer, there are 14 errors in custom.ts related to the use of the variable 'motor'.

**Expected behavior**
The script should work in the same way in both the new and old version of the editor.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version 75.0.3770.100 (Official Build) (64-bit)

**Additional context**
I use this scripts for training teachers to use a simple, cheap robot in the classroom. They are really useful.

**Comment by abchatra** [comment]
@jwunderl can you take a quick peek why this is not working in the latest editor?

**Comment by jwunderl** [comment]
Issue is with the type narrowing; that is, this is currently failing as a ``non-numeric indexer``: https://makecode.microbit.org/_bEuXkxXV3Ubz

```typescript
const a: 1 | 2 = Math.randomBoolean() ? 1 : 2;
const b: number[] = [1, 2]

b[a]
```

@mmoskal it looks like I should be able to just add support for numeric unions by just splitting on``|``'s and recursing on all at the end of this function to fix this, right? https://github.com/microsoft/pxt/blob/4da5ecd5d2583cd2b1d9e2ffb9a8595e44a841bf/pxtcompiler/emitter/emitter.ts#L2994

in this case, the issue is the check used on motor in a few functions:

```typescript
if (motor != 0 && motor != 1)
    return
// from this point on, the type of motor narrowed to ``1 | 0``, because anything else could not have reached this point
```

There's an easy hack fix in the code to make it work for now by casting 

```typescript
function stepOne4(motor: number, dir: direction) {
    if (motor != 0 && motor != 1)
        return
    motor = motor as number;

    switch (count[motor]) {
        case 0:
            writePins(motor, 0, 0, 1, 1)
        ...
```

**Comment by mmoskal** [comment]
@jwunderl yeah, that should work;  BTW there are probably quite a few places in the emitter where we enforce types, but not longer have to
