### ISSUE TITLE
Home page occasionally shows nothing besides local projects

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#2244]
I don't know how to repro this, but right now my home page looks like:

![image](https://user-images.githubusercontent.com/6453828/60533600-d9955680-9cb4-11e9-9e12-2ca66a84940b.png)

If I refresh the page or open it again in a new tab, I see the same issue with no JS errors.

If I open makecode.microbit.org in an incognito window, everything works fine. Joey and I suspect it's a cacheing issue.

Chrome 75 on MacOS 10.4.3 on Macbook Pro 2018

Possible steps forward:
1. Add code to identify when a section is empty
2. Report error telemetry

**Comment by abchatra** [comment]
Can't repro
