### ISSUE TITLE
Panic 020 with basic radio usage after gcPreAllocBlock() fix

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#2245]
**Describe the bug**
A panic ":( 020" occurs with this program: https://makecode.microbit.org/_JjAcytiDu5zC

**To Reproduce**
1. Open: https://makecode.microbit.org/_JjAcytiDu5zC in makecode.microbit.org/v2.0.4
2. Download to hardware device
3. Shake device, wait, press buttons, shake again, press buttons
4. Should see ":( 020" error scroll across

**Other repros:**
- https://makecode.microbit.org/_UMChbu6cYVuV

Seen on Edge on Windows and Chrome on Mac.

This only happens after this change:
https://github.com/microsoft/pxt-common-packages/pull/866
https://github.com/microsoft/pxt-microbit/pull/2216

FYI: @mmoskal 

This is a ship-blocker for the fix to https://github.com/microsoft/pxt-microbit/issues/2215 and https://github.com/microsoft/pxt-microbit/issues/2177

**Comment by mmoskal** [comment]
In non-microbit targets most of codal allocations happen in our GC heap, except for ones made in interrupt service routines. In microbit DAL allocates everything in its own heap so we have to decide on a split between DAL and GC. Long-term we should use the strategy from other targets in microbit as well.

**Comment by pelikhan** [comment]
Tested as fixed in v2.0.5
