### ISSUE TITLE
Update https://makecode.microbit.org/device/error-codes 

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2247]
https://makecode.microbit.org/device/error-codes The list is outdated.

_Originally posted by @pelikhan in https://github.com/microsoft/pxt-microbit/issues/2225#issuecomment-505046012_

We're in the process of updating https://microbit.org/guide/hardware/error-codes/ to include new information eg garbage collector errors. Are there any errors here https://makecode.com/js/errorcodes that ought to be included here https://makecode.microbit.org/device/error-codes

**Comment by ganicke** [comment]
@microbit-mark - we have an error codes page for the CODAL erros at https://github.com/microsoft/pxt-common-packages/blob/master/libs/base/docs/device/error-codes.md

Some/most of the codes are common probably but I can take the current defines from the Lancaster repo and update the page at https://makecode.microbit.org/device/error-codes.

**Comment by ganicke** [comment]
Update with GC error codes. #2327
