### ISSUE TITLE
Error: "Compilation failed, please check your code for errors

### ISSUE THREAD

**Issue by rharbird** [microsoft/pxt-microbit#2248]
**Describe the bug**
This bug may be related to #991 as it concerns the use of extensions with Windows 10 using chrome.

**To Reproduce**

1. Go to https://makecode.microbit.org and start a new project
2. Import the extension for the elecfreaks iot board: https://makecode.microbit.org/pkg/tinkertanker/pxt-iot-environment-kit
3. Use any blocks, I have tried the OLED blocks and the RTC blocks.
4. On downloading the hex file, the error message is displayed, see screen grab below.
5. here is a sample program: https://makecode.microbit.org/_20tg18VVq0EJ

**Expected behavior**
Hex file generated and downloaded

**Screenshots**
![image](https://user-images.githubusercontent.com/7621811/60657586-7f79ca00-9e49-11e9-888d-cfef45e9f972.png)
 

**Desktop (please complete the following information):**
 - OS: WIndows 10 Pro 1809
 - Browser: 
 - Version 75.0.3770.100 (Official Build) (64-bit)

**Additional context**
This bug has also been noted in conjunction with the [sparkfun micro:climate kit](https://learn.sparkfun.com/tutorials/microclimate-kit-experiment-guide/installing-the-weatherbit-extension-in-makecode). The fix described at the URL (reload the extension) does not work for me though with the elecfreaks iot blocks. I do not experience the problem when using the sparkfun weatherbit blocks.

Note: this bug is not reliably reproducable @lionyhw does NOT get this error when using:
Google chrome: the latest version and Windows10 education, 1803.

**Comment by riknoll** [comment]
I cannot reproduce this error either. Can you try the following for me:

1. Go to the JavaScript editor
2. Try to download the project
3. Below the simulator, you should see a blue "Explorer" box. Click that to open the explorer
4. In the explorer, expand the "built" tab and click "output.txt"
5. Paste the contents of that file here in a comment

If you don't see that file, make sure you did step 2; it will only appear if the download button is clicked at least once.

**Comment by rharbird** [comment]
Hello,

I did as you said, output.txt contains 1 line:

Everything seems fine!

**Comment by rharbird** [comment]
I tested the sample program: https://makecode.microbit.org/_20tg18VVq0EJ with internet explorer 11 and there are no errors so I only get this problem with Chrome.

![image](https://user-images.githubusercontent.com/7621811/60845219-88fd8c00-a1d3-11e9-9579-a1954387acde.png)

**Comment by riknoll** [comment]
Could you try opening the developer tools and checking the console for errors?

1. Press ctrl+shift+i in chrome to open the dev tools
2. Open the console tab in the dev tools window
3. Press the "download" button in MakeCode
4. See if any errors showed up in the console and post them here if possible

**Comment by XC16** [comment]
> Could you try opening the developer tools and checking the console for errors?
> 
> 1. Press ctrl+shift+i in chrome to open the dev tools
> 2. Open the console tab in the dev tools window
> 3. Press the "download" button in MakeCode
> 4. See if any errors showed up in the console and post them here if possible

Hi,I got a similiar error.Can you help me check this ?I got this error
This my codelink:https://makecode.microbit.org/_6zg5vsKL1iRu



error:
POST https://dc.services.visualstudio.com/v2/track 400 (104: Field 'time' on type 'Envelope' is newer than the allowed max date. Expected: now + 7200000ms, Actual: now + 53989067ms)
t._xhrSender @ ai.0.js:1
t.triggerSend @ ai.0.js:1
(anonymous) @ ai.0.js:1
setTimeout (async)
t._setupTimer @ ai.0.js:1
t.send @ ai.0.js:1
n._track @ ai.0.js:1
n.track @ ai.0.js:1
n.trackEvent @ ai.0.js:1
(anonymous) @ pxtweb.js:83
TelemetryQueue.track @ pxtweb.js:16
aiTrackEvent @ pxtweb.js:85
pxt.tickEvent @ pxtapp.js:95
t.compile @ main.js:83
t.handleClick @ main.js:83
ka @ main.js:758
invokeGuardedCallback @ main.js:758
invokeGuardedCallbackAndCatchFirstError @ main.js:758
Fa @ main.js:758
Ja @ main.js:758
La @ main.js:758
Ha @ main.js:758
Oa @ main.js:758
Pa @ main.js:758
Td @ main.js:758
batchedUpdates @ main.js:758
dc @ main.js:758
Xd @ main.js:758
interactiveUpdates @ main.js:758
Wd @ main.js:758
pxtapp.js:1945 warning: Compilation failed, please check your code for errors.

**Comment by abchatra** [comment]
Can't repro

**Comment by beepbeepgumy3231** [comment]
this also happens on mac m1 safari for some reason (the first time this happened in a few codes)

**Comment by abchatra** [comment]
@beepbeepgumy3231 can you share your program? Are you using any extension?
