### ISSUE TITLE
`if button_B` takes prioity over `on button_A+B` 

### ISSUE THREAD

**Issue by rhubarbdog** [microsoft/pxt-microbit#2250]
**Describe the bug**
I was showing my brothers kids microbit with blocks and i started with a program which prints "will" `on.Button_A` and "smells" `if isPressed.button_b` we thought to add his sister to this first program with `on.Button_A+B` prints "lara". when buttons A+B are pressed the text "smells lara" is displayed

**To Reproduce**
https://makecode.microbit.org/_h6sEeHJVXHXo

**Expected behavior**
button_A is pressed display "will"
button_A+B are pressed display "lara"
button_B is pressed display "smells"

**Desktop (please complete the following information):**
 - OS: Linux mint 18.2
 - Browser : mozillla firefox
 - Version : 67.0

**Comment by pelikhan** [comment]
This issue is likely in the DAL. Please reopen in https://github.com/lancaster-university/microbit-dal
