### ISSUE TITLE
Add localized extensions in the 'dependencies' of another extension

### ISSUE THREAD

**Issue by MiroChao** [microsoft/pxt-microbit#2251]
@pelikhan 
**Describe the bug**
I have this extension [https://github.com/CH-MAKER-Ed/pxt-Bit-GadgetKit](https://github.com/CH-MAKER-Ed/pxt-Bit-GadgetKit) that would load 3 different extensions at the same time (by including them in the 'dependencies' ) so users do not have to load them one by one. 

All my extensions are translated to Chinese and tested (if I load them separately, it works ), except for the neopixel one, which do not have a Chinese translation. However, if I load them using [https://github.com/CH-MAKER-Ed/pxt-Bit-GadgetKit](https://github.com/CH-MAKER-Ed/pxt-Bit-GadgetKit) , the editor will load them all but the translations won't work.  

My other extensions are translated following the instructions [https://makecode.com/extensions/localization](https://makecode.com/extensions/localization).

Please help.

**To Reproduce**
1. Add the extensions 'https://github.com/CH-MAKER-Ed/pxt-Bit-GadgetKit'
2. Check the package extension version in project setting, it should be 'v0.0.5', and it load 3 extensions, 'BitMaker', 'Grove' and 'Neopixel'
3. Change the language to 'Chinese 中文'
4. All the extensions keeps in English
5. In a new project, add the extension 'https://github.com/CH-MAKER-Ed/pxt-Grove'  , the extension  'https://github.com/CH-MAKER-Ed/pxt-BitMaker' and the 'neopixel' separately.
6. Check the 'Grove' and 'BitMaker' extension version, which should be 'v0.1.0' and 'v0.1.3' respectively
7. Change the language to 'Chinese 中文' 
8. The extensions are translated successfully (except for neopixel)

**Expected behavior**
When I add the extension 'BitMaker' 'Grove'  and 'Neopixel' using 'https://github.com/CH-MAKER-Ed/pxt-Bit-GadgetKit', the  'BitMaker' and  'Grove' extensions should be translated normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/11206594/60780714-23c57e80-a172-11e9-83a5-5ec22d3b184b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version : Chrome v75.0.3770.100

**Comment by abchatra** [comment]
Bug here is dependent package translations are not working even if they have translation.  For example: CH-MAKER-Ed/pxt-Grove has translations which are not working.

**Comment by riknoll** [comment]
@MiroChao there's a proper fix for this coming but in the meantime you can work around this issue by editing the pxt.json in your package. the entries for those two packages you mentioned in the dependencies object need to match the "name" field in the config of the dependency.

In other words, change `BitMaker` to `pxt-bit-gadgetkit` and `chmakered-grove` to `pxt-grove`

**Comment by MiroChao** [comment]
@riknoll OK thanks, I'll have a try.
