### ISSUE TITLE
Project name is lost when opening share dialog second time

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2252]
**Describe the bug**
Project name is lost when opening share dialog second time

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "Home" button and input "project1"
3. Click "project1" on home page and click "Share" -> click close icon 
4. Click "Share" again and observe text box

**Expected behavior**
Project name should show in share text box

**Actual behavior**
Project name is lost when opening share dialog second time
![issue70801](https://user-images.githubusercontent.com/23466737/60797862-af570380-a1a2-11e9-99c3-338e583eda1b.gif)

**Additional info**
1. makecode.microbit.org version: 2.1.2
2. Microsoft MakeCode version: 5.15.10
3. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)

**Comment by pelikhan** [comment]
fixed.
