### ISSUE TITLE
Preview shows pins 19 and 20 turning on and off, but physical units output constant 3.3v signal

### ISSUE THREAD

**Issue by kristianpedersen** [microsoft/pxt-microbit#2253]
I was struggling to use digitalWrite with some pins, but realised it was because of their internal connection to the LED screen. This issue was fixed with ```led.enable(false)```.

I'm still struggling with pins 19 and 20, however. When I try blinking them, they output a static 3,3v signal on my micro:bits, even though the MakeCode preview shows them working.

I've tried searching for a way to disable I2C, to see if that's the source of the error, but I've had no luck.

In the example below, P0 works as expected, while P19 and 20 output a static 3.3v signal.

```javascript
basic.forever(function () {
    const blink = input.runningTime() % 2000 < 1000 ? 1 : 0
    pins.digitalWritePin(DigitalPin.P0, blink)
    pins.digitalWritePin(DigitalPin.P19, blink)
    pins.digitalWritePin(DigitalPin.P20, blink)
})
```

**Comment by riknoll** [comment]
@jamesadevine should this work? I don't know if those two pins can be used for anything other than i2c.

If that's the case, the simulator needs to be updated to not blink those pins.

**Comment by jamesadevine** [comment]
@riknoll I don't think this will ever work given the way pxt-microbit is architected. pxt-microbit uses the MicroBit singleton class which creates an instance of I2C with P019 and P020 https://github.com/lancaster-university/microbit/blob/master/source/MicroBit.cpp#L65 

As @kristianpedersen points out, there is no way to disable I2C unless the destructor is called, which is not possible given the use of the singleton and the dependency on I2C introduced by the accelerometer and magnetometer.

I think the simulator should be updated to prevent digital IO operations on these pins.

@mmoskal @pelikhan agree?

**Comment by mmoskal** [comment]
yeah; maybe we should just remove these two pins from the dropdown?

**Comment by riknoll** [comment]
Probably can't remove them altogether, but we can set the `blockHidden=1` tag so that they don't show up

**Comment by mmoskal** [comment]
sounds good!

**Comment by microbit-carlos** [comment]
If the pins are removed from the dropdown, what would happen if a user loads a hex file using these pins?

**Comment by jamesadevine** [comment]
@microbit-carlos good point, I think @riknoll is suggesting that instead of removing them from blocks which would break some user programs, they are instead hidden from view. This would maintain both backwards compat, and prevent use of these pins in future programs.

**Comment by riknoll** [comment]
Yep! Existing programs will not change but if you drag a pin block out of the toolbox and open the dropdown you won't see the options for pins 19 & 20

**Comment by microbit-carlos** [comment]
Perfect, thanks!

**Comment by abchatra** [comment]
Fixed
