### ISSUE TITLE
Serial write number limit in simulator

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2254]
**Describe the bug**
Using serial write number and outputting to the ssimulator console there appears to be a limit on what the console can display.

**To Reproduce**
eg this program https://makecode.microbit.org/_0WbDRoDMFDjy should continually output data to the console up to the value of 512, but stops at 460. At this stage the character count in the sim console is 1296.

I can't reproduce this limitation with any other block and it doesn't reproduce on the device.

**Expected behavior**
Serial data should match the code

<img width="858" alt="Screenshot 2019-07-08 at 15 24 15" src="https://user-images.githubusercontent.com/31242877/60817909-7b74e180-a194-11e9-88e1-e260a43431cc.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome
 - Version 76

**Comment by pelikhan** [comment]
You need to add a "serial write line" block in the loop -- otherwise it generates a number that cannot be represented.
