### ISSUE TITLE
Issue reading light level and pin at the same time

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2256]
micro:bit support: 22530 and 23067
**Describe the bug**
When reading light level and pin over serial in the same program, readings become eratic. Light level reads 0-255, but the Pin should read 0-1023, but instead we get the majority of readings at 255

**To Reproduce**
1. Go to 'https://makecode.microbit.org/_UqL8yYVj9MyM' and flash program
2. Connect Pin0 to 3V, reading on Pin0 should be 1023
3. Read serial data out and see that the majority of readings are 255

**Expected behavior**
Pin data should read from 0-1023

Additional info,

Have tried recreating this in the DAL see
[Archive.zip](https://github.com/microsoft/pxt-microbit/files/3372717/Archive.zip) but can't get a reproducer

**Comment by martinwork** [comment]
Related? https://github.com/lancaster-university/microbit-dal/issues/448

**Comment by martinwork** [comment]
This repros without MakeCode if you read repeatedly and often, say 100Hz. There's a full 100% reading about every 0.05 seconds, with the ones between being 25%.

**Comment by abchatra** [comment]
This is tracked in the DAL repo. Closing here.
