### ISSUE TITLE
one time control.raiseEvent  trigger two times of control.onEvent

### ISSUE THREAD

**Issue by helloworld8686** [microsoft/pxt-microbit#2257]
main.ts:
makerbit.connectInfrared(DigitalPin.P2)
basic.showIcon(IconNames.Heart)
serial.redirect(
SerialPin.P8,
SerialPin.P12,
BaudRate.BaudRate115200
)
serial.writeLine("1")

test.ts:
// MakerBit blocks supporting a Keyestudio Infrared Wireless Module Kit
// (receiver module+remote controller)
namespace makerbit {

const MICROBIT_MAKERBIT_IR_MARK_SPACE = 777;

function pushMarkSpace(markAndSpace: number): number {
serial.writeNumber(markAndSpace);
serial.writeLine("\n");
return 0;
}

/**

IO口检测到电压变化时，记录下脉宽周期，当完成一次高低变化时，触发一次 MICROBIT_MAKERBIT_IR_MARK_SPACE 事件，并且把高低变化的时间推送给事件
@param
/
function enableIrMarkSpaceDetection(pin: DigitalPin) {
let mark = 0;
let space = 0;
pins.setPull(pin, PinPullMode.PullNone)
pins.onPulsed(pin, PulseValue.Low, () => {
// HIGH
mark = pins.pulseDuration();
control.raiseEvent(MICROBIT_MAKERBIT_IR_MARK_SPACE, mark);
});
/
pins.onPulsed(pin, PulseValue.High, () => {
// LOW
space = pins.pulseDuration();
control.raiseEvent(MICROBIT_MAKERBIT_IR_MARK_SPACE, space);
});*/
}
/**

Connects to the IR receiver module at the specified pin.
@param pin IR receiver pin, eg: DigitalPin.P0
*/
//% subcategory="遥控器"
//% blockId="makerbit_infrared_connect"
//% block="设置遥控器引脚 %pin"
//% pin.fieldEditor="gridpicker"
//% pin.fieldOptions.columns=4
//% pin.fieldOptions.tooltips="false"
//% weight=90
export function connectInfrared(pin: DigitalPin): void {
enableIrMarkSpaceDetection(pin);
control.onEvent(
MICROBIT_MAKERBIT_IR_MARK_SPACE,
EventBusValue.MICROBIT_EVT_ANY,
() => {
pushMarkSpace(control.eventValue());
}
);
}
}

**Comment by philipphenkel** [comment]
This is most probably related to #1334

**Comment by abchatra** [comment]
We need a clear description of the issue.  Copy paste of the code is not useful.
