### ISSUE TITLE
KeiganMotor became unable to receive RADIO packet when compiled by the latest makecode editor.

### ISSUE THREAD

**Issue by keigan-motor** [microsoft/pxt-microbit#2259]
**micro:bit cannot talk to KeiganMotor via RADIO when the firmware of micro:bit is compiled by the latest makecode editor.**
KeiganMotor is our product and could talk to micro:bit using the following.
https://github.com/keigan-motor/pxt-KeiganMotor

**There is no problem in the last month,** I made sure it in early June.
The problem occured since makecode micro:bit editor was updated recently, I think.
I checked the problem in the following cases and found that the old editor doesn't cause any problem.
 
**- v2.0.3(the latest)   NG**: https://makecode.microbit.org
**- v1.2.13                  OK**:  https://makecode.microbit.org/v1

**To Reproduce**
It seems to be hard to reproduce it because you don't have our device.
(We can send it to you if you need.)
But the problem is simple.
By using the following code, KeiganMotor should receive packet from micro:bit.
But it doesn't work when using the latest v2.0.3 editor.
`
input.onButtonPressed(Button.A, function () {
    radio.sendNumber(0)
})
radio.setGroup(0)
basic.forever(function () {
	
})
`

**Expected behavior**
KeiganMotor can receive packet from micro:bit.

**Screenshots**
![image](https://user-images.githubusercontent.com/31641835/61122524-f3b50d00-a4dc-11e9-8dcc-bfe0df6eb997.png)

**Request**
I think micro:bit runtime haven't been updated in these days.
Especially, there is no edit around RADIO.
https://github.com/lancaster-university/microbit-dal/
So I cannot understand this problem.
Do you have any idea about this problem?
And can you fix it?
We have a more request. Please keep the v1 version editor working. (Please do not erase from your server.)
Because we won't be able to use our devices unless using v1 editor.

**Desktop (please complete the following information):**
 - OS: Windows10 Home (latest) and MAC OS 10.14.1

**Smartphone (please complete the following information):**
 - Device: iPhone8plus
 - OS :iOS 12.3.2
 - App: micro:bit app

**Comment by pelikhan** [comment]
The radio package parser was rewritten: https://github.com/microsoft/pxt-microbit/blob/master/libs/radio/radio.ts

**Comment by pelikhan** [comment]
onDataPacketReceived is deprecated. Use this instead:

```
radio.onDataReceived(() => {
          const packet = RadioPacket.getPacket(readRawPacket());
          ...
})
```

**Comment by pelikhan** [comment]
Support dates for editor versions is documented at https://support.microbit.org/support/solutions/articles/19000058445-makecode-editor-updates

**Comment by keigan-motor** [comment]
Dear Pelikhan

Thank you for your comment.

This problem was not related to our extension pxt-keiganmotor directly.
Because if I only use radio without pxt-keiganmotor, there is a difference with .hex file 
between built by 
- v2.0.3(the latest) NG: https://makecode.microbit.org
and
- v1.2.13 OK: https://makecode.microbit.org/v1

I wonder it.
Just sending a packet from micro:bit, KeiganMotor can receive it from only one built by v1.2.13.

**Comment by pelikhan** [comment]
Did you see my comment? You need to update your extension and stop using onDataReceived

**Comment by abchatra** [comment]
The extension needs to update to new API. Old APi si deprecated.

**Comment by keigan-motor** [comment]
Yes, I have reflected that we don't use "onDataPacketReceived".
But still problem.

This problem is not related to our API in essence.
It can occur by using only radio like this.

radio.setGroup(0)
radio.sendNumber(0)

Built by 
v2.0.3(the latest) NG: https://makecode.microbit.org
and
v1.2.13 OK: https://makecode.microbit.org/v1

OK means that KeiganMotor can receive the message.
I don't understand this because I couldn't find change between them,
related to runtime and pxt-microbit.

**Comment by pelikhan** [comment]
Could you do a diff on the bytes received by your robot?
