### ISSUE TITLE
Breadboarding improvements

### ISSUE THREAD

**Issue by darzu** [Microsoft/pxt-microbit#226]
- [ ] IMO the wires should be slightly larger when hovered and 
- [ ] hovering should work on the wire itself - not just the dots
- [ ] the parts front page should have the link to the editor, maybe as a subtitle of the script name
- [x] tempted to call the button "Make" instead of "Parts"
- [ ] show logo on board in wireframe mode (daryl)
- [ ] handle popup blockers when opening parts view (peli)
- [x] full screen print of maker instructions

**Comment by abchatra** [comment]
Ported to pxt repo: Microsoft/pxt#533
