### ISSUE TITLE
Giant play button android

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2260]
On opening  a new project in MakeCode in Chrome on Android and dragging a block in, a 'play' icon appears above the simulator. Not sure i this is deliberate, but there is also a play button next to the sim that provides this function and it seems a bit out of place.

1. Open MakeCode editor on Android
2. Drag in show number block 
3. See issue

![Screenshot_20190709-132423](https://user-images.githubusercontent.com/31242877/61122973-0e669200-a49b-11e9-992f-d0a9fb82477f.png)

**Comment by pelikhan** [comment]
This happens when we detect that the environment is slow; we move into a "light" mode where we don't run the simulator at all time.
