### ISSUE TITLE
Memory error for 'run in background'

### ISSUE THREAD

**Issue by shaoziyang** [microsoft/pxt-microbit#2261]
**Describe the bug**
In MakeCode beta (v 2.1.2) will cause memory error (error code 020), same code is work in MakeCode v2.0.3.

**To Reproduce**
Demo code:
https://makecode.microbit.org/_9Ty9KDcmwEfk

![error](https://user-images.githubusercontent.com/1037534/61169733-857f5180-a593-11e9-875d-8dac9e8d1ebe.jpg)

**Comment by abchatra** [comment]
@mmoskal

**Comment by mmoskal** [comment]
does it repro with all the fixes I did? I don't these are in beta, are they?

**Comment by mmoskal** [comment]
works fine with https://github.com/microsoft/pxt-microbit/pull/2246

**Comment by pelikhan** [comment]
The fix is in /beta (with version >= v2.1.3). Please reopen if it happens again on beta.

**Comment by shaoziyang** [comment]
Yes, it works now.
