### ISSUE TITLE
"Hardware" can't be opened after clicking "Go back"

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2263]
**Describe the bug**
"Hardware" can't be opened after clicking "Go back"

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "Help" -> "JavaScript" 
3. Click "Help" -> "Hardware" 
4. Click "Go back" on the top of the side bar
5. Click “Help” -> "Hardware"

**Expected behavior**
Should can navigate to "Hardware" page

**Actual behavior**
"Hardware" can't be opened after clicking "Go back"
![issue71501](https://user-images.githubusercontent.com/23466737/61204549-0bc89e80-a720-11e9-8119-825254eaf419.gif)

**Additional info**
1. makecode.microbit.org version: 2.1.2
2. Microsoft MakeCode version: 5.15.10
3. OS: Windows (17763.1.amd64fre.rs5_release.180914-1434)

**Comment by ganicke** [comment]
This happens with any combination of docs when using ``<-- Go back``. It looks like the history is confused and it thinks that the current document is "Hardware" instead of "JavaScript" and therefore no new navigation is needed. @shakao what do you think?

**Comment by shakao** [comment]
hmm yeah, this looks like a bug with the sidedocs component. it always takes the first page we're navigating to, so the "go back" is probably not setting some state that it should be

**Comment by abchatra** [comment]
Seems to be fixed in /beta
