### ISSUE TITLE
How to trace MakeCode editor version (and force that specific version)

### ISSUE THREAD

**Issue by whaleygeek** [microsoft/pxt-microbit#2264]
**Is your feature request related to a problem? Please describe.**
Traceability to editor version

**Describe the solution you'd like**
How given a hex file, do I work out what version of makecode is baked into it, and how do I turn that into a URL to retrieve the identical editor version that created that file?

**Describe alternatives you've considered**
Stashing .hex files - no good if I want to allow others to change them (e.g. radio groups)

**Additional context**
There appears to be new typescript in the radio pipeline that slows things down. I have hex files written in older versions of the editor that work fine, but am worried that future editor versions will break the timing of this timing critical code (as others have already reported with the Microbit Orchestra). I need a way for users to change radio groups and some other settings but need to guarantee they use the same version of makecode that I used to develop the .hex, so that nothing else changes outside of my control. I'm relying on radio message consistency at the millisecond level for my code to work reliably (it measures the speed of sound).

**Comment by pelikhan** [comment]
Are you using the "time" field in radio package? They contain the precise timestamp when the radio package was received, regardless of any kind of delay due to code.

**Comment by abchatra** [comment]
Won't fix. We should strive to have backward compat of all hex files. Older hex files should work on newer editors. If not we should fix that bug.
