### ISSUE TITLE
Various error codes with hex files - 848, 022, 980

### ISSUE THREAD

**Issue by tanyafish** [microsoft/pxt-microbit#2267]
**Describe the bug**
All of these bugs are related to a previously working library for scroll:bit by @pimoroni - hex files are examples known to work on previous versions of the firmware (version 249 and before). Asked for the error codes from @microbit-mark as part of ticket #23245 - we seem to have cured the 848 by tweaking something in the library - see here https://github.com/pimoroni/pxt-scrollbit/commit/b5a609232a172dd1ba7803bd92152f50f047d541
They weren't needed in previous versions - wonder if there's a conflict with the update to the browser?

Various error codes are generated, hex files are below.

**To Reproduce**
To get the 022 error code, load tilt-ghost
To get the 848 error code, load scroll-words
I can't currently reproduce the 980 but thought it was still worth mentioning as they seem to be related.
[hex files.zip](https://github.com/microsoft/pxt-microbit/files/3401104/hex.files.zip)

**Expected behavior**
As mentioned before, the pxt library for the scrollbit was working fine, but there seems to be a conflict in the updated browser version of makecode, or with the memory allocation maybe?

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by pelikhan** [comment]
We have a fix for the memory allocation issue that you are seeing. Please again in https://makecode.microbit.org/beta and make sure the version is >= 2.1.3 .

**Comment by abchatra** [comment]
fixed in the latest release for memory. Reopen issue if that doesn't address this issue.
