### ISSUE TITLE
WCAG 1.4.4: Zooming and scaling must not be disabled (meta[name="viewport"])

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2274]
#### Issue
`Zooming and scaling must not be disabled` ([meta-viewport](https://dequeuniversity.com/rules/axe/3.2/meta-viewport?application=msftAI))
#### Target application
[Microsoft MakeCode for micro:bit](https://makecode.microbit.org/#editor)
#### Element path
meta[name="viewport"]
#### Snippet
`<meta name="viewport" content="width=device-width,height=device-height,user-scalable=no,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0">`
#### How to fix
    Fix any of the following:
      user-scalable=no on <meta> tag disables zooming on mobile devices
#### Environment
Chrome version 75.0.3770.142
This accessibility issue was found using Accessibility Insights for Web 2.7.1 (axe-core 3.2.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).

Not sure this is actually an issue, as zooming is supported in the editor, but it popped up. This occurs on all pages of the website.

**Comment by abchatra** [comment]
We do support zooming. This is fixed. 

![image](https://user-images.githubusercontent.com/6107272/75292102-65c23400-57d8-11ea-88da-643cd151edde.png)

**Comment by BhuwanNaswa** [comment]
Labels
#A11yMAS, #HCL, #HCL-MakeCode-E2E, #MAS1.4.4, #Win10-Chrome, #Win10-Edge, #accessibility, #K4W, #closed
