### ISSUE TITLE
WCAG 3.1.1: <html> element must have a valid value for the lang attribute (#sidedocsframe;html)

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2278]
#### Issue
`<html> element must have a valid value for the lang attribute` ([html-lang-valid](https://dequeuniversity.com/rules/axe/3.2/html-lang-valid?application=msftAI))
#### Target application
[Microsoft MakeCode for micro:bit](https://makecode.microbit.org/#editor)
#### Element path
#sidedocsframe;html
#### Snippet
`<html lang="@locale@" data-framework="typescript">`
#### How to fix
    Fix all of the following:
      Value of lang attribute not included in the list of valid languages
#### Environment
Chrome version 75.0.3770.142
This accessibility issue was found using Accessibility Insights for Web 2.7.1 (axe-core 3.2.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).

sidedocs lang not evaluating properly?

**Comment by abchatra** [comment]
Closing 2 year old bugs.
