### ISSUE TITLE
pxsim.pxt namespace clashes with pxt

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-microbit#228]
This is the old TypeScript namespace issue. The pxsim.pxt namespace prevents using anything from pxt in the simulator code.
- [ ] rename generated javascript to avoid pxt namespace

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-microbit/blob/edc489c83d3801edffbb05ad9555bb9cdf3ef879/sim/state/misc.ts#L160

**Comment by mmoskal** [comment]
fixed with https://github.com/Microsoft/pxt/commit/679d9660052ec8c1c361879bd5f91abc7ca3b18e
