### ISSUE TITLE
WCAG 2.4.4,WCAG 4.1.2: Links must have discernible text (a[href="mailto\:makecode\@microsoft\.com"])

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2285]
#### Issue
`Links must have discernible text` ([link-name](https://dequeuniversity.com/rules/axe/3.2/link-name?application=msftAI))
#### Target application
[Documentation - Microsoft MakeCode](https://makecode.microbit.org/docs)
#### Element path
a[href="mailto\:makecode\@microsoft\.com"]
#### Snippet
`<a class="item" href="mailto:makecode@microsoft.com" title="Send us an Email" rel="noopened">
                <i class="huge icon mail"></i>

![Screen Shot 2019-07-18 at 2 26 59 PM](https://user-images.githubusercontent.com/5615930/61493318-20977300-a968-11e9-90cc-1dcca61bc31e.png)

**Comment by abchatra** [comment]
Fixed
