### ISSUE TITLE
WCAG 2.4.4,WCAG 4.1.2: Links must have discernible text (a[rel="nofollow\ noopener"])

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2287]
#### Issue
`Links must have discernible text` ([link-name](https://dequeuniversity.com/rules/axe/3.2/link-name?application=msftAI))
#### Target application
[Intro to CS - Microsoft MakeCode](https://makecode.microbit.org/courses/csintro)
#### Element path
tr:nth-child(1) > td:nth-child(1) > a[rel="nofollow\ noopener"]
#### Snippet
`<a rel="nofollow noopener" href="/--docs#book:/courses/csintro/SUMMARY"><img class="ui centered image" src="https://pxt.azureedge.net/blob/742b46dab7e443d163e12e70f365e76604a3590a/static/courses/csintro/icons/html-24x24.png" alt="">

these are the icons under 'download it' in the cs intro course

![Screen Shot 2019-07-18 at 2 30 27 PM](https://user-images.githubusercontent.com/5615930/61493577-c21ec480-a968-11e9-924d-c29ba160f9d0.png)

**Comment by abchatra** [comment]
Closing 2 year old bugs.
