### ISSUE TITLE
More control over toolbar and toolbar actions when embedding MakeCode

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microsoft/pxt-microbit#2319]
**Is your feature request related to a problem? Please describe.**

As previously discussed with Microsoft, the Micro:bit Educational Foundation are  developing a web app that embeds MakeCode via an iframe and uses the postMessage-based API to interface with it (via the controller=1 URL parameter).

We'd like to be able to provide a single custom toolbar integrating MakeCode functionality and some relevant to our app, rather than providing the user with two levels of toolbar.

As I understand it, to hide the MakeCode toolbar currently requires a build-time option in pxtarget.json. We would like you to consider adding a runtime option (e.g. via the URL) to control this so that we can embed directly from the makecode.microbit.org deployment.

We would also like to be able to trigger via the postMessage API key user actions that are usually available from the toolbar but would not be if we hid it in this way.

- Print
- High contrast on
- Green screen on (lower priority - this one is new to me)
- Pair device

These actions could behave exactly as they do at the moment, triggering UI in MakeCode.

We'd also like control over language so that if our app changes language we can propagate this to MakeCode. I think this would make more sense as a postMessage message that sets the language based on choices made in our app, rather than having it trigger your language selection.

Access to the version numbers as used in the "About" dialog would be very useful to enable us to provide a clear combined dialogue of our own but I don't think we'd want to be able to trigger the about dialog itself.

We think project/extension settings might be something we can usefully control via the JSON file format directly. The project-related actions aren't relevant to us in the controller embedding.

**Describe the solution you'd like**

Any reasonable API to achieve the above. It might make sense to break this down further but I though one issue explaining the overall motivation would be a useful starting point.

**Comment by abchatra** [comment]
This is fixed.

**Comment by abchatra** [comment]
@microbit-matt-hillsdon  are the features working as expected in this change?

**Comment by microbit-matt-hillsdon** [comment]
@abchatra thanks for this. We've now tried using the new API to implement our toolbar and have a few issues / queries:

1. We have API to get the list of languages but, so far as I can tell, no API to change language. Would this make sense as another message type? We can change the URL, but that’s harder for us and I’m not sure whether it will lose any state for the user.
2. We need feedback when actions succeed or fail:
    1. The Javascript ↔ Blocks switch can fail when JavaScript is invalid. The user is warned and given the opportunity to cancel the action. From our toolbar, there’s no way for us to know that this has happened so our UI gets out of sync. This toggle is our most pressing issue.
    2. We ought to disable our toolbar actions while triggered actions are in progress. Currently, we can trigger nested green screen or flash dialogs, whereas in MakeCode the actions are disabled when dialogs are up. If we could rely on a corresponding success/failure/cancelled message, we could likewise disable our UI until the action was complete or cancelled.

What do you think?

**Comment by pelikhan** [comment]
For 1, you need to reload the editor with #lang=ISO or ?lang=ISO .

**Comment by microbit-matt-hillsdon** [comment]
Thanks. I've split my feedback above into new issues #2530 and #2531 as suggested.
