### ISSUE TITLE
add disable/enable block feature

### ISSUE THREAD

**Issue by shaoziyang** [microsoft/pxt-microbit#2321]
Sometime we need disable a block function, but not want delete. 

In code mode, we can use // or /* */ to comment code block, but in block mode, there is no similar approach.

So if add disable/enable block feature maybe helpful.

**Comment by woutput** [comment]
Is this really needed? I think a (sequence of) block(s) can be disabled temporarily by dragging the (first) block to an empty space. It will turn shaded gray/yellow.
Maybe this feature request was written before the described function was implemented?

**Comment by abchatra** [comment]
Won't fix. You can disconnect the blocks and they get disabled. Block paradigm is different from coding text.
