### ISSUE TITLE
Add blocks for breaking and continuing a loop

### ISSUE THREAD

**Issue by FranklinWhale** [microsoft/pxt-microbit#2324]
**Is your feature request related to a problem? Please describe.**
A block to break or continue with the next iteration of a loop will be help to reduce the use of nested or complicated if blocks.

**Describe the solution you'd like**
Add a block for continuing the loop or breaking the loop. Alternatively, a unique block for each.

**Additional context**
A similar feature exists in Blockly:
https://github.com/google/blockly/wiki/Loops

**Comment by Jaqster** [comment]
Hi Franklin!  I'm trying to learn more about this need in the classroom - can you share a specific example project or lesson where you are teaching this?  And also examples of 'nested/complicated if blocks' that you are using instead of break/continue would be helpful.  Thanks so much!

**Comment by FranklinWhale** [comment]
Hi @Jaqster, I am unable to find out the code that prefers using `break` or `continue` right now. However, I do remember that it's a `for` loop that performs certain actions based on 2 or more variables and in one case an early termination of the loop is preferred. In the end, the code was rewritten to use nested `if-else` blocks.

**Comment by abchatra** [comment]
Implemented.
