### ISSUE TITLE
WCAG 2.4.4,WCAG 4.1.2: Links must have discernible text (.focused[href="\/"][title="Go\ to\ editor"])

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2340]
#### Issue
`Links must have discernible text` ([link-name](https://dequeuniversity.com/rules/axe/3.2/link-name?application=msftAI))
#### Target application
[Documentation - Microsoft MakeCode](https://makecode.microbit.org/docs)
#### Element path
.sticky > div:nth-child(1) > .focused[href="\/"][title="Go\ to\ editor"]
#### Snippet
`<a href="/" class="header focused" tabindex="0" title="Go to editor">`

in docs, the 'go to home' icon

<img width="212" alt="Screen Shot 2019-08-02 at 3 44 16 PM" src="https://user-images.githubusercontent.com/5615930/62402393-6cd3dd00-b53c-11e9-8873-cda723395f1a.png">

**Comment by abchatra** [comment]
fixed
