### ISSUE TITLE
[Programmatic Access - Make Code - Extensions] Two control type is defined for single control(Login to GitHub) under 'Extensions' screen.

### ISSUE THREAD

**Issue by sonimishra** [microsoft/pxt-microbit#2350]
**User Experience:**
Screen reader users would be affected to get the correct control information if two control type is defined for single control as user would be confuse to get the correct control type information.

**Test Environment:**
Version 1903 (OS Build 18867.1000)
Platform: Edge, Chrome
Screen reader: Narrator, JAWS and NVDA

**Repro Steps:**
1. Launch application URL : https://makecode.microbit.org/#
2. Home page will open.
3. Navigate "New Project" option and select it.
4. Editor screen will open.
5. Navigate to "Settings" option appearing in header section and select it.
6. Navigate to "Extensions" option and select it.
7. Navigate through all the controls appearing under "Extensions" page
8. Verify that control type of 'Login to GitHub' link control by using screen reader using tab key and 'up/down' arrow key.

**Actual Result:**
Two control type is defined as 'link and button' for single control(Login to GitHub) under 'Extensions' screen, due to this user will be confused as they won't be able to decide which functionality he/she should perform.
 
**Expected Result:**
Role=button should not defined under <a> for 'Login to GitHub' link control under 'Extensions' screen so that user will take action accordingly.

**Note:** 
This issue also exists with Chrome + JAWS and NVDA

**MAS Reference:**
[MAS 4.1.2 - Name, Role, Value](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={248054a6-5e68-4771-9e1e-242fb5025730})

[Accessibility Insights!](https://microsoft.sharepoint.com/teams/msenable/Pages/PageNotFoundError.aspx?requestUrl=https://microsoft.sharepoint.com/teams/msenable/Pages/accessibility-tools.aspx
) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

![MAS4 1 2_Extensions_Two control type is defined for single control](https://user-images.githubusercontent.com/30456910/62536027-8a6db300-b86a-11e9-9d1a-3d92fa682eef.jpg)

**Comment by abchatra** [comment]
Please re-test using beta site https://makecode.microbit.org/beta . If it reproduces let me know. I will reopen the bug.

**Comment by sonimishra** [comment]
Issue has been verified and now only link is defined for the control.
Hence closing the bug.
