### ISSUE TITLE
[Keyboard navigation - Make Code - Homepage] Keyboard focus doesn't land on Soil moisture dialog screen.

### ISSUE THREAD

**Issue by sonimishra** [microsoft/pxt-microbit#2353]
**User Experience:**
User who rely on keyboard might get affected if keyboard focus does not land on interactive control after performing desire action and also user won't be able to get the flow of application as it will consume user's time and efforts to reach out expected screen

**Test Environment:**
Version 1903 (OS Build 18867.1000)
Platform: Edge, Chrome

**Repro Steps:**
1. Launch application URL : https://makecode.microbit.org/#
2. Home page will open.
3. Navigate to the controls appearing under "Science, Tools, Turtle" section in Home page.
4. Select any option like 'Soil moisture'.
5. Verify keyboard focus after selecting 'Soil moisture' option.

**Actual Result:**
Keyboard focus doesn't land on 'Soil moisture' dialog screen. Instead of that, keyboard focus moves to background and then only it comes to 'Soil moisture' dialog screen which consumes user's time & effort to reach out the expected screen.

**Expected Result:**
Keyboard focus should land on Show Instructions or Close controls of  'Soil moisture' dialog screen, instead of moving out to background so that end user could get the flow of application as well as user could save time & effort to reach out the expected screen.

**Note:**
This issue also exists with Chrome.

**MAS Reference**:
[MAS 3.2.1 - On Focus (06)](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame2.aspx?sourcedoc=%7ba4bbd37d-ee11-485e-b5c8-0539f0ac94b2%7dl)

[Accessibility Insights!](https://microsoft.sharepoint.com/teams/msenable/Pages/PageNotFoundError.aspx?requestUrl=https://microsoft.sharepoint.com/teams/msenable/Pages/accessibility-tools.aspx
[MAS3.2.1_Homepage_Keyboard focus.JPG.zip](https://github.com/microsoft/pxt-microbit/files/3472084/MAS3.2.1_Homepage_Keyboard.focus.JPG.zip)
)

**Comment by abchatra** [comment]
Please re-test using beta site https://makecode.microbit.org/beta . If it reproduces let me know. I will reopen the bug.

**Comment by sonimishra** [comment]
Same issue exists in https://makecode.microbit.org/beta
