### ISSUE TITLE
[Keyboard Navigation - Make Code - Delete Project] Keyboard focus does not retain back to 'more' menu item after select 'cancel' button on 'Delete project' pop-up window.

### ISSUE THREAD

**Issue by sonimishra** [microsoft/pxt-microbit#2356]
**User Experience:**
After selecting any element, if there is any unexpected focus movement then user who depends upon keyboard gets affected and create hindrance to use the application effectively.

**Test Environment:**
Version 1903 (OS Build 18867.1000)
Platform: Edge, Chrome

**Repro Steps:**
1. Launch application URL : https://makecode.microbit.org/beta
2. Home page will open.
3. Navigate "New Project" option and select it.
4. Editor screen will open.
5. Navigate to "Settings" option appearing in header section and select it.
6. Navigate to "Delete Project" option and select it.
7. Navigate through all the controls appearing under "Delete Project" dialog and select 'cancel' button.
8. Verify that keyboard focus moves expected control(More menu item) after selecting cancel button or not.

**Actual Result:**
Keyboard focus does not retain back to 'more' menu item control after select 'cancel' button on 'Delete project' pop-up window. Focus is getting lost and after using tab key focus moves on 'Skip to java script editor' control.
 
**Expected Result:**
Keyboard focus should not lost and also retain back to the expected control i.e. 'more' menu item after selecting 'cancel' button on 'Delete project' pop-up window.

**Note:** 
1. This issue also exists with Chrome.
2. Same issue exists with 'Report abuse and Select language' pop-up window.

**MAS Reference:**
[MAS 3.2.1 - On Focus
](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a4bbd37d-ee11-485e-b5c8-0539f0ac94b2})

**Labels**
#A11yMAS, #HCL, #HCL-MakeCode-E2E, #MAS3.2.1, #Win10-Chrome, #Win10-Edge, #accessibility

[Accessibility Insights!](https://microsoft.sharepoint.com/teams/msenable/Pages/PageNotFoundError.aspx?requestUrl=https://microsoft.sharepoint.com/teams/msenable/Pages/accessibility-tools.aspx
) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

[MAS3.2.1_Delete Project_Focus does not retain back to expected control.zip](https://github.com/microsoft/pxt-microbit/files/3472199/MAS3.2.1_Delete.Project_Focus.does.not.retain.back.to.expected.control.zip)

**Comment by abchatra** [comment]
Please re-test using beta site https://makecode.microbit.org/beta . If it reproduces let me know. I will reopen the bug.

**Comment by sonimishra** [comment]
Issue still exists in https://makecode.microbit.org/beta so reactivating the issue.

**Comment by jwunderl** [comment]
Is returning to the menu expected behavior? Most of the options are distinct / not things people would typically just walk through one at a time, and similar menus in chrome (for example) don't return the focus when a modal is closed:

![2019-08-29 11 14 12](https://user-images.githubusercontent.com/5615930/63965551-44150980-ca4e-11e9-9fdf-d4aa872bf90f.gif)

**Comment by abchatra** [comment]
This is as expected in our website. If you go to settings and select an option you drop back to the editor if you cancel the action or take affirmative action. This is inline with other websites as well.
