### ISSUE TITLE
[Screen Reader - Make Code - Report Abuse] Narrator focus moves out from 'Report abuse' pop-up window in scan mode.

### ISSUE THREAD

**Issue by sonimishra** [microsoft/pxt-microbit#2365]
**User Experience:**
User will be misguided if narrator focus moves out from the any pop-up window and they will skip further if screen reader announces blank on entire pop-up.

**Repro-Steps:**
1. Launch application URL : https://makecode.microbit.org/beta
2. Home page will open.
3. Navigate "New Project" option and select it.
4. Editor screen will open.
5. Navigate to "Settings" option appearing in header section and select it.
6. Navigate to "Report Abuse" option and select it.
7. Navigate through all the controls appearing under "Report Abuse" dialog in scan mode.
8. Verify that narrator focus moves out from 'report abuse' pop-up window or not.

**Actual Result:**
Narrator focus moves out from 'Report abuse' pop-up window in scan mode while using up arrow key after navigating 'report abuse' heading and narrator is reading blank which creates confusion to the screen reader user.

**Expected Result:**
Narrator focus should not move out from 'Report abuse' pop-up window in scan mode while using up arrow key after navigating 'report abuse' heading and narrator should not provide irrelevant information.

**Note:**
1. This issue doesn't exist with Chrome + JAWS.
2. This issue doesn't exist with Chrome + NVDA(Browse mode).
3. This issue also exists under 'Delete all blocks, Download to your micro:bit and Edit Function' pop-up window.

**MAS Reference:**
[MAS 4.2.10 - Tracking of Focus and Selection Attributes](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={b24201d1-2276-4471-8183-e1e5353031ad})

**Labels**
#A11yMAS, #HCL, #HCL-MakeCode-E2E, #MAS4.2.10, #Win10-Edge, #accessibility

[Accessibility Insights!](https://microsoft.sharepoint.com/teams/msenable/Pages/PageNotFoundError.aspx?requestUrl=https://microsoft.sharepoint.com/teams/msenable/Pages/accessibility-tools.aspx
) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

[MAS4.2.10_Report abuse_Focus moves out from pop-up.zip](https://github.com/microsoft/pxt-microbit/files/3476680/MAS4.2.10_Report.abuse_Focus.moves.out.from.pop-up.zip)

[MAS4.2.10_Function_Focus moves out from edit function pop-up.zip](https://github.com/microsoft/pxt-microbit/files/3484976/MAS4.2.10_Function_Focus.moves.out.from.edit.function.pop-up.zip)

**Comment by abchatra** [comment]
This is fixed in the latest edge.
