### ISSUE TITLE
Update https://makecode.microbit.org/offline-app as the offline app is now released

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2367]
Note 2 describes this software as in Pre-Release

PRE-RELEASE SOFTWARE. The software is a pre-release version. It may not work the way a final version of the software will. Microsoft may change it for the final, commercial version. We also may not release a commercial version. Microsoft is not obligated to provide maintenance, technical support or updates to you for the software.

Can this be updated to reflect that it is now released.

**Comment by abchatra** [comment]
Fixed
