### ISSUE TITLE
[Keyboard Navigation - Make Code - Share] Focus is moving out of pop up window after selecting 'Publish Project'

### ISSUE THREAD

**Issue by Deepika-0890** [microsoft/pxt-microbit#2369]
**User Experience:**
User might get affected if focus order is not logical or doesn't flow sequentially as he/she would be confused to get the user interface as well as find difficulty in navigation.

**Test Environment:**
Version 1903 (OS Build 18867.1000)
Platform: Edge, Chrome

**Repro Steps:**
1. Launch application URL : https://makecode.microbit.org/beta#
2. Home page will open.
3. Navigate "New Project" option and select it.
4. Editor screen will open.
5. Navigate to "Share" option appearing in header section and select it.
6. Navigate through all the controls of  "Share Project" dialog.
7. Verify if focus moves out of pop up window after selecting 'Publish Project' control.

**Actual Result:**
Keyboard focus moves out of pop up window after selecting 'Publish Project' button under 'Share', which is not logical and doesn't flow sequentially.

**Expected Result:**
Keyboard focus should not move out of pop up window it should move to 'Share Project' pop up after selecting 'Publish Project' button under 'Share', so that user could navigate the sequentially on user interface.

**Note:**
This issue doesn't exists with Chrome.

**MAS Reference:**
MAS 2.4.3 - Focus Order

[MAS2.4.3_Focus is  going out of pop up window after selecting publish project.zip](https://github.com/microsoft/pxt-microbit/files/3476769/MAS2.4.3_Focus.is.going.out.of.pop.up.window.after.selecting.publish.project.zip)

Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**Comment by jwunderl** [comment]
Just tested, repros on firefox as well, but not chrome / safari

**Comment by sonimishra** [comment]
Issue has been verified and fixed.
Hence closing the bug.
