### ISSUE TITLE
[Screen reader - Make Code - Share] In scan mode, Narrator focus moves out of 'Share Project' pop up window.

### ISSUE THREAD

**Issue by Deepika-0890** [microsoft/pxt-microbit#2370]
User Experience:
Users who depend on Screen reader will be confused if Narrator focus in scan mode is navigating to the Background of the pop up window.

**Test Environment:**
Version 1903 (OS Build 18867.1000)
Platform: Edge, Chrome
Screen reader: Narrator, JAWS and NVDA

**Repro Steps:**
1. Launch application URL : https://makecode.microbit.org/beta
2. Home page will open.
3. Navigate "New Project" option and select it.
4. Editor screen will open.
5. Navigate to "Share" option appearing in header section and select it.
6. Navigate through all the controls of  "Share Project" dialog.
7. Verify, if focus moves out of 'Share Project' pop up box or not.

**Actual Result:**
In scan mode, Narrator focus moves out of 'Share Project' pop up window.

**Expected Result:**
In scan mode, Narrator focus should not moves out of 'Share Project' pop up window it should stay in pop up box.

**MAS Reference:**
MAS 4.2.10 - Tracking of Focus and Selection Attributes

**Labels**
#A11yMAS, #HCL, #HCL-MakeCode-E2E, #MAS4.2.10, #Win10-Edge, #accessibility

**Accessibility Insights!** - Identify accessibility bugs before check-in and make bug fixing faster and easier.

[MAS4.2.10_Focus moves out of pop up box.zip](https://github.com/microsoft/pxt-microbit/files/3476836/MAS4.2.10_Focus.moves.out.of.pop.up.box.zip)

**Comment by jwunderl** [comment]
As far as I can tell as of https://github.com/microsoft/pxt/pull/6712 we've done about as much as we currently can on this; copying part of the description from over there that has a few more details:

Looks like OfficeDev/office-ui-fabric-react#6884 has the same basic problem, with the same attempt at a solution and the rest being left to future narrator updates (also nice write up on the associated issue: https://github.com/OfficeDev/office-ui-fabric-react/issues/6422#issuecomment-430331471).

with the linked change, we:

* give the modals the `dialog` role properly
* give the modals the `aria-modal` flag, which indicates the modal should constrain screen readers (everything else is handled by js, but screen readers basically do their own thing)
* give an element that contains (almost) all of the rest of the page (besides the modals and cookie banner) to `aria-hidden=true`, which _should_ also be blocking those elements from being read
