### ISSUE TITLE
Incorrect unicode from charCodeAt() on device

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2372]
> microbit support #23573

**Describe the bug**
Character codes are incorrectly represented on the device.

**To Reproduce**
In JS mode input:
```
let str = "a松岡b"

for (let i = 0; i < str.length; i++) {
let charcode = str.charCodeAt(i);
console.log(i.toString() + ": " + str.charCodeAt(i) + "\n");
}
```
and see result in Sim. 

![image](https://user-images.githubusercontent.com/31242877/62625346-e85ad300-b91c-11e9-9858-4ad1f43724ac.png)

Download this to micro:bit and see result from serial on device

![image](https://user-images.githubusercontent.com/31242877/62625380-f7da1c00-b91c-11e9-8472-f2b2268aaa0d.png)

**Expected behavior**
Unicode should be the same on device as on Simulator

**Comment by matsujirushi** [comment]
ping

**Comment by matsujirushi** [comment]
Could you tell me status of this issue?

**Comment by microbit-mark** [comment]
@abchatra @pelikhan are you able to prioritise this one please? The user is waiting on a fix in order to release a pxt-extension.

**Comment by mmoskal** [comment]
unicode is disabled on microbit - see https://github.com/microsoft/pxt-microbit/blob/master/pxtarget.json#L40

Bringing it in increases code size, I guess the idea was the microbit screen isn't good enough for most characters outside of ASCII anyways. Feel free to measure the code size increase (you can look in binary.asm at the top) and decide if it's worth it.

**Comment by jaustin** [comment]
Thanks @mmoskal - are there any proposed workarounds, for example if we wanted to be able to print a limited number of specific characters?

**Comment by mmoskal** [comment]
Not right now. It should be generally possible to have a package enable unicode, but it would require some work.

**Comment by matsujirushi** [comment]
@mmoskal Thanks for your support.
Could you tell me how to enable unicode for specified package?

**Comment by mmoskal** [comment]
It's currently not possible. Maybe upon next release (next summer).

**Comment by matsujirushi** [comment]
Oh.. Okay. Thank you.

**Comment by microbit-mark** [comment]
@matsujirushi I reached out to you via support.microbit.org on this one, is there anything further you want to add? Otherwise, we should probably turn this ticket into a feature request.

**Comment by abchatra** [comment]
@mmoskal probably we an support an extension to enable the subset of unicode support?

**Comment by mmoskal** [comment]
an extension could in principle enable unicode everywhere; this shouldn't cause much trouble other than code size increase

Currently, this is defined in pxtarget.json, but there is only two places in the emitter where target.utf8 is used, so should be relatively easy to make it a package option.
