### ISSUE TITLE
[Supporting the Platform - Make Code - Language] Links does not adapt high contrast theme under 'Select language' pop-up window.

### ISSUE THREAD

**Issue by sonimishra** [microsoft/pxt-microbit#2375]
**User Experience:**
Users who depend on High contrast theme will be impacted if link controls are not adapting  high contrast mode.

**Test Environment:**
Version 1903 (OS Build 18867.1000)
Platform: Edge, Chrome

**Repro Steps:**
1. Launch application URL : https://makecode.microbit.org/beta
2. Home page will open.
3. Navigate "New Project" option and select it.
4. Editor screen will open.
5. Navigate to "Settings" option appearing in header section and select it.
6. Navigate to "Language " option and select it.
7. Navigate through all the controls appearing under "Select Language" dialog.
8. Turn on the high contrast theme.
9. Verify the issue.

**Actual Result:**
Link controls like(English, Arabic, Danish, German, Help us translate) are not adapting high contrast theme under 'Select language' pop-up window. It looks as 'green' color instead of 'yellow' color.
 
**Expected Result:**
Link controls like(English, Arabic, Danish, German, Help us translate) should adapt high contrast theme under 'Select language' pop-up window. It should look as a 'yellow' color.

**Note:** 
This issue also exists with Chrome.

**MAS Reference:**
[MAS 4.3.1 - No Disruption of Accessibility Features](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={672c8a8b-ed4f-463f-868f-e8131caf9b74})

[Accessibility Insights!](https://microsoft.sharepoint.com/teams/msenable/Pages/PageNotFoundError.aspx?requestUrl=https://microsoft.sharepoint.com/teams/msenable/Pages/accessibility-tools.aspx
) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

[MAS4.3.1_Language_HC.zip](https://github.com/microsoft/pxt-microbit/files/3481109/MAS4.3.1_Language_HC.zip)

**Comment by jwunderl** [comment]
To clarify, this issue is to change the highlight over ``Arabic`` in this image to be yellow instead of the teal-ish color it currently is?

![Screen Shot 2019-08-08 at 10 50 26 AM](https://user-images.githubusercontent.com/5615930/62725653-69bc6f00-b9ca-11e9-9c00-c982efe17c43.png)

**Comment by sonimishra** [comment]
Issue has been verified in Ver 2.1.5 and seems not the link controls adopt HC color when focused with keyboard.
Hence closing the bug.
