### ISSUE TITLE
Radio-broadcast messages sending enum causes unexpected behaviour

### ISSUE THREAD

**Issue by obrasier** [microsoft/pxt-microbit#2391]
**Describe the bug**
When sending radio broadcast messages written on two devices with two micro:bits, using the [`radio-broadcast`](https://github.com/microsoft/pxt-microbit/tree/master/libs/radio-broadcast) extension, the recieved event is trigged on the _index_ of the ` enum RadioMessage` received, not the radio broadcast message created.

**To Reproduce**
1. Get two different devices with two micro:bits (A and B)
2. On device A programming micro:bit A, create two `radio-broadcast` custom messages in this order by clicking `Add a new msg...`:
  a. `foo`
  b. `bar`
3. On device B programming micro:bit B, do the same but in this order:
  a. `bar`
  b. `foo`
2. On micro:bit A, the `radio send **foo**` will trigger the `on radio **bar** received` event on micro:bit B.

**Expected behavior**
Sending event `foo` on micro:bit A to trigger event `foo` on micro:bit B.

This is because it would create the following enums:

micro:bit A:
```
enum RadioMessage {
    message1,
    foo,
    bar
}
```
micro:bit B:
```
enum RadioMessage {
    message1,
    bar,
    foo
}
```
Using an `enum` just sends the number, which is the wrong behaviour in this case. 

For students using this by programming on their device and sending messages to each other across a room, you expect message `foo` to trigger event `foo`, so the expected behaviour would be more like `send string` with an event-driven model. 

Assuming the `enum` on each device is the same is not a safe assumption.

**Screenshots**

Using the following code means you will receive a TICK on micro:bit A, but a CROSS on micro:bit B, when button A is pressed on micro:bit A:

![image](https://user-images.githubusercontent.com/4486457/62991955-02546280-be95-11e9-8294-1ed3f4b622b7.png)

**Comment by abchatra** [comment]
@pelikhan

**Comment by pelikhan** [comment]
This is a regression. The enum should have a hash value.

**Comment by abchatra** [comment]
regression by radio changes by @riknoll ?

**Comment by riknoll** [comment]
I don't think it's related to the radio changes; Looks like a Blockly compiler bug. Will take a look

**Comment by riknoll** [comment]
Never mind, this isn't a regression. The enum values have always been order dependent. We never had name hashing
