### ISSUE TITLE
Shake gesture not working in if statement

### ISSUE THREAD

**Issue by nicolaOB** [microsoft/pxt-microbit#2392]
**Describe the bug**
An 'if is shake gesture' block is not working on the micro:bit as expected (although the emulator behaves as expected.)  

**To Reproduce**
1. Create a project
2. Combine several if events within a forever loop: for example if a button pressed then show number 1, if b button pressed then show number 2, if shake gesture then show number 3.
3. Download to micro:bit
4. When micro:bit is shaken, no 3 appears on screen

**Expected behavior**
Expected to see 3 on screen

**Screenshots**
![Screen Shot 2019-08-14 at 2 37 50 pm](https://user-images.githubusercontent.com/41407379/62994980-fb801c80-bea1-11e9-8951-191cd86c4549.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS 10.14
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 76

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pennyplayer** [comment]
I replicated the problem for all gestures. 

(Event driven gestures still work fine)

**Comment by abchatra** [comment]
Does this reproduce if you don't use the event blocks in your program? Use the is _shake gesture block_ but don't sue the _on shake_ block on the same program.

I am assuming on shake is consuming the event.

**Comment by martinwork** [comment]
https://makecode.microbit.org/_euy2z5P7FYzT

This "is gesture" test works, but stops working if the "on" block is deleted.

**Comment by abchatra** [comment]
_on_shake_ will eat the event. This is how it is supposed to work. Otherwise back to back on shake will not be detected.

**Comment by martinwork** [comment]
On shake and if is shake seem to work fine together.

https://makecode.microbit.org/_bcAi8Ygd8PsH

This shows heart from the on handler followed by smile from the if-is block.
But nothing shows if the on block is deleted.

**Comment by microbit-mark** [comment]
Relates to #2234 - isgesture only works with ongesture present
