### ISSUE TITLE
Common string methods missing

### ISSUE THREAD

**Issue by kristianpedersen** [microsoft/pxt-microbit#2395]
I'm working on a setup that involves students sending a riddle answer to a receiver micro:bit, which does some stuff if their message was correct.

I want to accept both "Password", "password", "PASSWORD" and "password ", etc. This would be easy with `toLowerCase()` and `trim()`, but both of these methods are missing.

Maybe they're unnecessary in blocks mode, but it would be nice to have them available in JS mode, and converted to a grey block, like `forEach()` is.

**Comment by kristianpedersen** [comment]
Just discovered that toLowerCase() works now, but trim() results in this error: `Cannot read property 'iface' of undefined`

```javascript
const s = " Whitespace ".trim()
```

**Comment by jwunderl** [comment]
Ahh, fixed trim https://github.com/microsoft/pxt/pull/7476 but likely won't go out till next major update. Were there any other methods that you noticed were missing?

**Comment by kristianpedersen** [comment]
One that I've missed is the ability to do this:

```javascript
(21).toString(2) // "10101"
```

Especially since the code below does work:

```javascript
parseInt("10101", 2) // 21
```

Would be cool to have these available in blocks view. 

Maybe under the math section, named "convert number () to binary" and "convert binary number () to decimal"?

**Comment by abchatra** [comment]
Original issue implemented. Open new ones for the additional requests.
