### ISSUE TITLE
More than 57 variables crashes on loading with sad face 844

### ISSUE THREAD

**Issue by tomas-mbit** [microsoft/pxt-microbit#2398]
**Describe the bug**

A program having more than 57 variables throws an 844 error as soon as loading to the microbit is finished.

It seems to make no difference if variables are e.g. numbers or strings. Variables made local to functions in javascript appear not to count to the limit, thus this can serve as a mitigating workaround. (Is there a size limited pointer table for global variables?)

It seems that the blocks editor insists on making all variables global. Giving functions a dummy return value provides a (somewhat ugly) workaround for that problem, moving the code into gray blocks which remain untouched.

**To Reproduce**

This program:
https://makecode.microbit.org/_2AcekWVaz1eE
(Removing all references to one of the 58 variables makes the program load successfully )

![bild](https://user-images.githubusercontent.com/42862513/63199509-52424d80-c07e-11e9-8735-0657d41719e8.png)

....

![bild](https://user-images.githubusercontent.com/42862513/63199541-70a84900-c07e-11e9-9d57-2cc35950da4d.png)

**Expected behavior**

Program should not crash.
I know that the microbit doesn't have a lot of memory, but surely it should support a considerably larger number of variables?  Or did I get something completely wrong here?

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox Quantum 
 - Version 68.0.1 (64-bit)

**Comment by mmoskal** [comment]
OK, so this is because we only allocate the 7k of memory reclaimed from the bluetooth stack after allocating globals.
