### ISSUE TITLE
Switching between Jacascript and blocks adds parentheses in expression

### ISSUE THREAD

**Issue by tomas-mbit** [microsoft/pxt-microbit#2399]
When switching between editing in javascript and editing in blocks certain expressions acquire a new pair of parentheses around them for each switch. After a while of work there will be a ridiculous number of parentheses.

**To Reproduce**

https://makecode.microbit.org/_6pkPXXf5UDH4

![bild](https://user-images.githubusercontent.com/42862513/63228710-21395880-c1f7-11e9-9078-97bd798f85d5.png)

Edit the letter in the call to show in the forever loop. Switch to javascript and edit again. Switch to blocks and edit again, etc, etc. Watch the number of parentheses grow.

**Expected behavior**

Number of parentheses around expression should not change.
I suppose this isn't critical, as the value of the expression remains the same, but it does look weird after a while....

**Desktop (please complete the following information):**
    OS: Win10
    Browser Firefox Quantum
    Version 68.0.1 (64-bit)

**Comment by FranklinWhale** [comment]
This seems to be the opposite of #2345, where some required parentheses are missing there.
