### ISSUE TITLE
supported API, onLogoUp? 

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#24]
1 go to KSF, JS

2. enter this code

```

input.onLogoUp(() => {
    basic.showLeds(`
        . . # . .
        . # # # .
        # # # # #
        . . # . .
        . . # . .
        `)
})

```

3 the page does not render in Docs

http://localhost:3232/lessons/magic-logo/activity

4

![image](https://cloud.githubusercontent.com/assets/11206682/14158559/96ed12a6-f685-11e5-8518-da0b6293b34b.png)

**Comment by pelikhan** [comment]
LogoUp is not a block.

**Comment by mebrauns** [comment]
it appears here..

![image](https://cloud.githubusercontent.com/assets/11206682/14191708/42c794f2-f74e-11e5-9d6e-02f847065050.png)

**Comment by pelikhan** [comment]
Use on gesture

Sent from Outlook Mobile<https://aka.ms/djubve>




On Thu, Mar 31, 2016 at 2:38 PM -0700, "Michael Elliot Braun" <notifications@github.com<mailto:notifications@github.com>> wrote:


it appears here..

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fcloud.githubusercontent.com%2fassets%2f11206682%2f14191708%2f42c794f2-f74e-11e5-9d6e-02f847065050.png&data=01%7c01%7cjhalleux%40microsoft.com%7c6e6cc457b0e24d5868e308d359acd5bf%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=GcI0yjSbSj37bGvD8widkfslngQY1iGeoenY9wHP0nw%3d>

-
