### ISSUE TITLE
basic.showNumber(1.14286) shows 1.13999..... on real micro:bit

### ISSUE THREAD

**Issue by lwchkg** [microsoft/pxt-microbit#2403]
**Describe the bug**
See title. It should show 1.14 instead of 1.139999

**To Reproduce**
1. Make the program `basic.showNumber(1.14286)`
2. Flash to micro:bit
3. Read result

**Expected behavior**
Shows 1.14 (rounds to 2 d.p.)

**Actual behavior**
Shows 1.139999...... Apparently either `Math.roundWithPrecision(value, 2)` or the `toString` routine is wrong.

**Comment by martinwork** [comment]
Seems to be fixed in beta: https://makecode.microbit.org/beta

**Comment by lwchkg** [comment]
Confirm to be fixed on beta. Closing.
