### ISSUE TITLE
Direct www. traffic > makecode.microbit.org

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2405]
**Describe the bug**
https://www.makecode.microbit.org/ is often mistakenly quoted in Educational materials as the address for the editor, but it does not resolve. 

The British Council have found this an issue when working with teams across the globe 

Can we redirect traffic from https://www.makecode.microbit.org/ to https://makecode.microbit.org

**Comment by microbit-mark** [comment]
Hi @mmoskal I've made the DNS entry. Let me know if there's anything further

**Comment by mmoskal** [comment]
@abchatra we need to add domain redirect in deployment config

**Comment by abchatra** [comment]
Fixed
