### ISSUE TITLE
Microbit Seems to fail handling floats as expected with buffer.

### ISSUE THREAD

**Issue by ryanteck** [microsoft/pxt-microbit#2406]
**Describe the bug**

**To Reproduce**
1. Open makecode.microbit and create a new program.
2. Click javascript tab and copy in the following code:
```
input.onButtonPressed(Button.A, function () {
    let payload = ""
    let latBuf = pins.createBuffer(3);
    latBuf.setNumber(NumberFormat.Int32BE, -1, 52.1581 * 10000)
    let lonBuf = pins.createBuffer(3);
    lonBuf.setNumber(NumberFormat.Int32BE, -1, 1.2541 * 10000)
    let altBuf = pins.createBuffer(3);
    altBuf.setNumber(NumberFormat.Int32BE, -1, 10.1 * 100)
    payload = "" + payload + "0" + "1" + "88" + latBuf.toHex() + lonBuf.toHex() + altBuf.toHex()
    serial.writeLine(payload)
})


serial.redirectToUSB()

basic.forever(function () {

})
```

3. Download to micro:bit with WebUSB Enabled and setup.
4. Press A button on simulator, and then click show console simulator, pressing again should output expected result of  `018807f56d0030fd0003f2`
5. Press A button on microbit, then click show console device, upon pressing again device returns unexpected result of `0188000000000000000000`

**Expected behavior**
For `018807f56d0030fd0003f2` to be returned

**Screenshots**
![Screenshot from 2019-08-27 11-10-42](https://user-images.githubusercontent.com/1104745/63762805-5f034480-c8bb-11e9-9be6-a31f77eca9a7.png)

![Screenshot from 2019-08-27 11-10-51](https://user-images.githubusercontent.com/1104745/63762810-60cd0800-c8bb-11e9-8287-f89ecbd1f958.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Browser Chrome
 - Version 76

**Additional context**
Not sure if it's that I'm doing something wrong. It did start to work after updating to latest firmware but has broke again. Also tried makecode/beta as well without success.

**Comment by JoshuaLowe1002** [comment]
@ryanteck asked if i could reproduce this and i get the same result as above

**Comment by martinwork** [comment]
The buffer sizes need to be 4 for a 32 bit integer.

setNumber seems not to like offset -1. Is this a bug?

It works with buffer size 4 and offsets 0.

**Comment by martinwork** [comment]
Though it seems to work as-is in the simulator.

**Comment by ryanteck** [comment]
@martinwork I thought that it could be the issue. However as it worked in the simulator wasn't fully sure.  Primarilly it was the easiest way to get a 3 Byte hex for the value. 

I'm not fully sure if it should work or if it's just by chance the simulator works. I'll see if I can figure out an alternative.

**Comment by martinwork** [comment]
It could be that the 3 byte buffers should work. I don't know. JavaScript does a lot that feels like magic to me!

**Comment by ryanteck** [comment]
Upon more testing it seems 3 byte buffer works (but not quite how I need) and it's the -1 offset that fails.

I'll leave this ticket open to be closed as to weather the command should support a negative offset or not.
