### ISSUE TITLE
Pimoroni extension not appearing in search

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2407]
> micro:bit support #23783

**Describe the bug**
Searching for 'envirobit' for example, returns 500 error.
![image](https://user-images.githubusercontent.com/31242877/63835045-8ebf5480-c96e-11e9-8ce0-612589644d0f.png)

I can't recreate @abchatra, but Pimoroni report this issue. Is it related to the recent change in search?

**Comment by abchatra** [comment]
I can't repro this.

**Comment by microbit-mark** [comment]
@abchatraI have asked the user if it is still erroring. What more information would be useful here?

**Comment by abchatra** [comment]
F12 and any error in there

**Comment by microbit-mark** [comment]
No response from user on this so closing
