### ISSUE TITLE
Make TS error indicator clickable, and show list of clickable errors with line numbers

### ISSUE THREAD

**Issue by kristianpedersen** [microsoft/pxt-microbit#2408]
The red TypeScript error indicator with the number inside doesn't do anything, except telling me how many errors there are.

A clickable icon with a list of clickable errors would provide a better user experience.

![Untitled](https://user-images.githubusercontent.com/5204369/63844538-b15e6700-c988-11e9-8f20-c0c7f3f675ca.png)

If you don't know about F8 and Shift+F8, like myself until 2 minutes ago, you could scroll hundreds of lines of code, looking for tiny red squiggles.

Even for beginners with 10 lines of code, it would still be nice to see the errors written out, instead of having to hover over the red squiggly lines.

**Comment by pelikhan** [comment]
Errors are now clickable on the submenu itesm in /beta (it will open the file at the first error.)

**Comment by abchatra** [comment]
Fixed in /beta and it will expand to right file and you can click on the error there to take to a line number.
