### ISSUE TITLE
remember home page view setting

### ISSUE THREAD

**Issue by Geoffree3** [microsoft/pxt-microbit#2418]
** problem **
I have often have projects with names longer than will fit in the 'project boxes' on the standard home page (about 11 chars), so I have to select "See all projects" (after scrolling the list to the right), then click the "list" icon.  Then the full project names can be seen.
Opening a project is OK, but on returning to the home page, I'm back to the standard home page and have to go through the actions again to see the list.  This is annoying!

** solution **
Remember the setting/format for the home page

** other comments **
Anyone with more than a handful of projects, have to see them in the list view, so please do not make it tedious to see them!

**Comment by abchatra** [comment]
You can click on this to go to all projects:
![image](https://user-images.githubusercontent.com/6107272/77236678-11fbfe00-6b7e-11ea-8bfe-a2c7445decd6.png)

**Comment by abchatra** [comment]
May be the work is make this more visible.

**Comment by abchatra** [comment]
@jwunderl we should take this to design meeting to make it more visible to select all projects.

**Comment by Geoffree3** [comment]
Of course the user can click on My Projects, but even then they have to click again on list view to see the full project names.  The least is to remember if the user likes to see list view or project box view.    However, I suggest that pxt remembers that the user wants the list view and this is their default home page (until they decide to change to another view).  Users who use Makecode alot most probably do not want to see the tutorials on the current home page all the time!

**Comment by abchatra** [comment]
We are stateless and used in schools. So students change and remembering the state is not the best option for us. 

We will add those options when there is identity and we know it is the same user.

**Comment by abchatra** [comment]
View All right instead of > arrow next to my projects
![image](https://user-images.githubusercontent.com/6107272/77596597-b309f200-6eb9-11ea-8ad5-087a58a4ca36.png)
