### ISSUE TITLE
https://makecode.microbit.org/examples/servo-calibrator

### ISSUE THREAD

**Issue by SakeTimmermans** [microsoft/pxt-microbit#2419]
**Describe the bug**
Link doesnt work anymore: https://makecode.microbit.org/examples/servo-calibrator

**To Reproduce**

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jwunderl** [comment]
Looks like that was moved just about a year ago to https://makecode.microbit.org/projects/servo-calibrator in https://github.com/microsoft/pxt-microbit/pull/1218

**Comment by SakeTimmermans** [comment]
Great, Thanks!

I found the link here: https://makecode.microbit.org/projects/milk-carton-robot/code
Would be great if worked on the website again...
