### ISSUE TITLE
Invalid summary layout for Logic Lab

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2422]
Items somewhat spilled out in the main summary
![image](https://user-images.githubusercontent.com/4175913/64695612-6eed5d80-d451-11e9-95cb-f57c24606b77.png)

Would be nice to add a nest summary for all courses (logic lab, science lab) too

**Comment by pelikhan** [comment]
Don’t do anything to the css since we are revamping it. I would remove the nested topics and move them to nested summaries.

________________________________

**Comment by ganicke** [comment]
Right, will do the nested summaries...thanks.
