### ISSUE TITLE
I2C command

### ISSUE THREAD

**Issue by anakinnet** [microsoft/pxt-microbit#2426]
**Describe the bug**
I2C write number and I2C read number blocks are not functioning

**To Reproduce**
1. Go to 'Make Code'
2. Slide to change to {}JavaScript
3. Write this code 
let a = 0
serial.redirectToUSB()
basic.forever(function () {
    pins.i2cWriteNumber(
    0x32,
    0xA8,
    NumberFormat.Int8LE,
    true
    )
    basic.pause(100)
    a = pins.i2cReadNumber(0x33, NumberFormat.Int8LE, true)
    serial.writeNumber(a)
    serial.writeLine("")
})

**Expected behavior**
Get some response from accelerometer(0x32 for write | 0x33 for read) for just testing the I2C command.

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 76
![image](https://user-images.githubusercontent.com/10265839/64759694-2376a480-d562-11e9-8e97-88322f610146.png)

This is what happen by using make code accelerator command
![image](https://user-images.githubusercontent.com/10265839/64759799-5f116e80-d562-11e9-9dcc-61a99b9b6c87.png)

but I actually got this (see the address was not the same as the code.
![image](https://user-images.githubusercontent.com/10265839/64759847-7c463d00-d562-11e9-9405-2c159a831cad.png)

**Additional context**
I know that this command should be connect to other I2C devices with the difference addresses but I already try it but not working. So, this is the step back that I would like to see how it actually works.

**Comment by carlosperate** [comment]
I think Martin is right, since PXT does a bit shift, it means the Read/Write bit is supplied by the i2c method, and so we need to supply the 7-bit address 0x19, instead of 0x32/0x33.

Apart from that, make sure you are using the right addresses for the version of the micro:bit board that you've got. The link provided by Martin shows the different values based on the board version.

**Comment by pelikhan** [comment]
@ganicke can we make sure our docs reflect that?

**Comment by ganicke** [comment]
Sure, I'll get some info in for that.

**Comment by anakinnet** [comment]
Thank you everyone for your answer. I can sent the package now. I think, the problem is the word '7 bits address' intuitively for me is to delete the 1st MSB. However, after go through several sensor documentation, I found some vendor use the address with /2 but some not. that may cause a lot confusion. 

BTW, are there any plan to add pin.i2cReadBuffer as a block?

**Comment by anakinnet** [comment]
close
