### ISSUE TITLE
bluetooth uart

### ISSUE THREAD

**Issue by machinehistories** [microsoft/pxt-microbit#2429]
I am trying some basic uart bluetooth send such as seen here 
[https://makecode.microbit.org/v1/05069-00763-98849-50405](url)
but I am not getting any values transmitted. I am trying both adafruit bluefruit app as well as Lightblue and both pair to the microbit and both see the nordic uart service but the board only is sending no value.

**Comment by martinwork** [comment]
It needs the "bluetooth uart service" block on "on start", like this:

https://makecode.microbit.org/_bFghdkYewWka
