### ISSUE TITLE
Editor assumes number list/array

### ISSUE THREAD

**Issue by forritun** [microsoft/pxt-microbit#2431]
**Describe the bug**
The editor assumes a number array in some cases, causing errors.

**To Reproduce**
1. Initialize an empty array
2. Attempt to find index of string element in array
3. See error

**Expected behavior**
No error

**Screenshots**
Error:
![Screenshot from 2019-09-17 12-46-21](https://user-images.githubusercontent.com/43571435/65043530-927d4000-d94a-11e9-9474-02b77ce6561e.png)
No error:
![Screenshot from 2019-09-17 12-48-01](https://user-images.githubusercontent.com/43571435/65043537-97da8a80-d94a-11e9-98a4-20fe98ed8bde.png)
Error:
![Screenshot from 2019-09-17 12-58-32](https://user-images.githubusercontent.com/43571435/65043676-e4be6100-d94a-11e9-8582-55c4af398be4.png)

**Desktop:**
 - OS: Linux
 - Browser Firefox
 - Version
    makecode.microbit.org version:  2.1.4
    Microsoft MakeCode version:  5.19.8
    microbit runtime version:  pxtgc-0

**Additional information**
Going to JS and changing array type fixes the problem. Going back to blocks, the error appears again.

**Comment by abchatra** [comment]
MakeCode is based on strong types. If you add elements to your array then it would work as you expected. Empty array has unknown type and we assume it is number. 

This is by design.
