### ISSUE TITLE
Cannot download directly to micro:bit from windows app

### ISSUE THREAD

**Issue by ceculbe** [microsoft/pxt-microbit#2436]
**Describe the bug**
Clicking the "Download" button in a project results in a message box with "Oops, we couldn't find your micro:bit.'" even when a micro:bit device is connected, visible to Windows, and manual copying of .hex files is successful. 

**To Reproduce**
1. Connect a micro:bit to PC via USB cable
2. Run the MakeCode Windows App
3. Start a new project and add any minimal code you wish
4. Click the large green Download button

**Expected behavior**
The "Download" button should compile and load code directly to a connecte micro:bit and reset the micro:bit

**Screenshots**
![image](https://user-images.githubusercontent.com/10868522/65375674-db403c00-dc5d-11e9-851a-500be5285bf7.png)
![image](https://user-images.githubusercontent.com/10868522/65375749-79340680-dc5e-11e9-9fde-bbc10a7a0c1f.png)

**Desktop (please complete the following information):**
 - Windows 10 Enterprise build 17763.437
 - Windows App version of MakeCode
- makecode.microbit.org version:  2.0.6
- Microsoft MakeCode version:  5.15.12
- microbit runtime version:  pxtgc-0
- micro:bit device firmware 0253
 
**Additional context**
The screenshot shows how the micro:bit appears in Windows Device Manager. I have followed the "Mbed driver doesn't work" suggested fix. The correct driver was already installed.

The download functionality was working fully with an earlier version of the Windows app and this exact combination of computer and micro:bit device. Multiple micro:bit devices have been tested.

**Comment by abchatra** [comment]
@ceculbe does webusb work for you? In Chrome browser got to makecode.microbit.org -> New project  ->Settings->Pair device. 
Once you pair are you able to download directly to device?

**Comment by ceculbe** [comment]
The web version of MakeCode is able to pair a device and download code directly. However, the Windows App does not have the menu option to pair a device.

**Comment by kristianpedersen** [comment]
I've had the same problem with the Microsoft Store app, and pairing in Chrome isn't always reliable from my experience.

My solution:
Use the .exe version of MakeCode instead: https://makecode.microbit.org/offline-app

The download button works on all machines at work. 
We've also had course participants install it on a number of their own different laptop setups, and it seems to work well across the board.

Don't know if there's a simple way to transfer projects to the .exe version from Chrome or the MS Store though.

**Comment by ceculbe** [comment]
Thanks for the help. I wasn’t even aware that there was a non-MS Store app.

**Comment by pelikhan** [comment]
Unable to repro. Did you install the mbed serial drier by any change? This support ticket shows how to remove it as it interferes with the HID driver in the windows app.
https://support.microbit.org/support/solutions/articles/19000089574-micro-bit-does-not-connect-in-windows
