### ISSUE TITLE
Images not displaying when deploying with staticpkg

### ISSUE THREAD

**Issue by JeffBrilliantLabs** [microsoft/pxt-microbit#2437]
Hello!

Trying to figure out why a very small number of the images ( /static/mb/projects/flashing-heart/sim.gif for example or the images in the USB pairing pop up dialog - static/download/connect.png) aren't showing up when deploying to server from pxt staticpkg.  To see if the issue was server side I tried to also deploy using the github pages info in the docs found here: https://makecode.com/cli/staticpkg  and found that this was even worse with no images displaying at all.  

Any advice if this is related to routing would be greatly appreciated!

**Comment by pelikhan** [comment]
Those might be in common-docs and staticpkg does not understand those.

________________________________

**Comment by JeffBrilliantLabs** [comment]
Any suggestions for a workaround?

**Comment by pelikhan** [comment]
You could try copying those files into your repo /docs/static/...

________________________________

**Comment by JeffBrilliantLabs** [comment]
I figured it out... for my particular deployment it was looking for the USB pairing png files at static/download/*.png but staticpkg placed them in docs/static/download/ ...I edited the extension.tsx file and that did the trick for those 3 along with the png files associated with the Download dialog... now off to changing some of the tutorials :)

**Comment by jfo8000** [comment]
+1 on this problem, having used pxt-sample I can't load images on the example cards.
