### ISSUE TITLE
Feature: Import Hex file via URL

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2441]
> micro:bit support: #24177

**Is your feature request related to a problem? Please describe.**
I want to save hex files on my server and give URLS to the students for the .Hex file rather than publishing incomplete projects on MakeCode. For younger users, having to download from the link and then upload is an unfamiliar process esp. for those used to using tablets who may be unsure of the download location.

**Describe the solution you'd like**
The Import link on the home page should let users import a .Hex file from a link to the file if it is served on the web

**Describe alternatives you've considered**
Publishing URLs on MakeCode, but I am reluctant to publish unfinished projects.

**Comment by abchatra** [comment]
There are security issues in pointing to random hex files in the wild. We are unlikely support this.

**Comment by abchatra** [comment]
Users can always download the hex file into their local box and then add to the editor
