### ISSUE TITLE
Compilation failed error

### ISSUE THREAD

**Issue by gfrancesco** [microsoft/pxt-microbit#2447]
**Describe the bug**
Hi, I'm running `pxt-microbit` in a docker container, and cannot download the hex file from the web interface.
When I click on the download button I get the error _"Compilation failed, please check your code for errors"_

From the js console in the browser (tested Firefox and Safari on MacOS), I get this errors:
```
Error: "Bad HTTP status code: 403 at /api/compile/extension; message: Error 403"
     requestAsync/< pxtapp.js:1182
     requestAsync pxtapp.js:1179
     privateRequestAsync pxtapp.js:15425
     privatePostAsync pxtapp.js:15533
     downloadHexInfoCoreAsync/</< pxtapp.js:5045
     downloadHexInfoCoreAsync/< pxtapp.js:5044
     downloadHexInfoCoreAsync pxtapp.js:5034
     downloadHexInfoAsync pxtapp.js:5015
     getHexInfoAsync/< pxtapp.js:5194
     getHexInfoAsync pxtapp.js:5177
     [52]</Host</Host.prototype.getHexInfoAsync package.js:441
     MainPackage.prototype.getCompileOptionsAsync/< pxtapp.js:10067
     MainPackage.prototype.getCompileOptionsAsync pxtapp.js:10057
     compileAsync compiler.js:85
     [2]</ProjectView</ProjectView.prototype.compile app.js:2120
     [28]</EditorToolbar</EditorToolbar.prototype.compile editortoolbar.js:62
     [28]</EditorToolbarButton</EditorToolbarButton.prototype.handleClick editortoolbar.js:276
    React 18
pxtapp.js:2103:21
Object { sha: "84df2f5e4d653791f2c82974af25391842a9bfe000743c832e122963f3e0dbc5" }
pxtapp.js:2107:29
error: pxt_modules/core/math.ts(1,1): error TS9043: The hex file is not available, please connect to internet and try again.
pxtapp.js:2099:21
warning: Compilation failed, please check your code for errors.
```

**To Reproduce**
These are the steps I used to create the Docker image, taken from the README:

*For PXT*
1. `git clone https://github.com/microsoft/pxt`
2. `npm install`
3. `npm run build`

*For `pxt-common-packages`*
1. `git clone https://github.com/microsoft/pxt-common-packages`
2. `npm install`

*For `pxt-microbit`*
1. `git clone https://github.com/microsoft/pxt-microbit`
2. `npm install -g pxt`
3. `npm install`
4. `npm link ../pxt`
5. `npm link ../pxt-common-packages`

*To start the web interface*
- `pxt serve -h 0.0.0.0 --no-browser`
I can then access using my host browser by pointing at `http://0.0.0.0:3232`

**Expected behavior**
I expect to be able to download the HEX file, since the blocks/source code is correct, even simple programs with one `showLeds` instruction fail.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14 running a linux docker container
 - Browser: Firefox 69 and Safari 13 (didn't try any other)
 - NodeJS v8.12.0

**Additional context**
I mapped both the two standards ports for PXT (TCP 3232, 3233) when starting the container, so they can be accessed from the Host OS (Mac).

Not sure if it's a bug or my mistake in building/deploying, but any help is appreciated :)

**Comment by pelikhan** [comment]
pxt serve is not meant to be used as a local server. You have to provide a localToken to allow api calls.

________________________________

**Comment by gfrancesco** [comment]
Sorry failed to mention it, but I used the full URL provided by `pxt serve` to start the editor:
EX: `http://0.0.0.0:3232/#local_token=71587f63-c81a-448a-734e-f31403b75ec6&wsport=3233`

Is that what you meant?

**Comment by pelikhan** [comment]
Something else is going on then.

**Comment by gfrancesco** [comment]
I sorted it out, first of all is not a `pxt-microbit` issue. It's more related to `pxt` and the network configuration of the docker container and the host OS.

I will describe the solution here just in case anyone will bump into it:

1. In the docker container you have to start `pxt serve` by specifing the internal IP address of the container, I'm using this command: ```pxt serve -h `hostname -i` --no-browser```
2. `pxt` will start and will print the url to launch your editor (something like this in my case: `http://172.17.0.2:3232/#local_token=a00fea7f-3f5e-494e-8c58-a532dfd239ac&wsport=3233`) **however in your host machine you have to replace the container IP with `localhost`**
3. If we follow the example above, this is the address to be used on the host: `http://localhost:3232/#local_token=a00fea7f-3f5e-494e-8c58-a532dfd239ac&wsport=3233`

Small catch: you need to have either `localhost` or `127.0.0.1` in the URL, **and** use a port different from 80, otherwise the regular expression that checks if the editor is running on localhost will fail, with the consequences explained in my first message.
This is the location of the regular expression in `microsoft/pxt`:

https://github.com/microsoft/pxt/blob/75650d87edbf90f8c705d7efbb9d64137f3c053b/pxtlib/browserutils.ts#L132

**Comment by dotspotty** [comment]
so if I want to install pxt on cumputer A and visit the page on computer B's browser, what should i do ? A and B are in same LAN. Any one can help me?

**Comment by gfrancesco** [comment]
It looks to me more like a production environment setup, I have no experience about how to do it since you run on a different host than `localhost`.
