### ISSUE TITLE
Change variable only affects negative value once

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2453]
> micro:bit support #24317
 
**Describe the bug**
When using the change variable block with a negative number, it only seems to parse the number once and keep returning the same value.

**To Reproduce**
https://makecode.microbit.org/_YaDK1Xh0L8ra
Press A, see error issue. Value remains at -1
This also reproduces on the hardware

**Expected behavior**
Number should count down in the loop -1, -2, -3, -4

**Screenshots**
![microbit-screenshot(7)](https://user-images.githubusercontent.com/31242877/65945199-60c8a680-e42b-11e9-83ea-d932ef8f4ce7.png)

**Additional context**
This does not reproduce in v0 or v1

**Comment by martinwork** [comment]
The bug is that MakeCode uses the variable "i" to implement the repeat loop. v1 ensures the loop variable name doesn't clash. Workaround is to avoid using i as a variable name.

Here's the javascript:

```
let i = 0
input.onButtonPressed(Button.A, function () {
    i = 0
    for (let i = 0; i < 4; i++) {
        i += -1
        basic.showNumber(i)
    }
})

```

**Comment by microbit-mark** [comment]
Thanks @martinwork. Using the same code and changing the variable letter works.

@abchatra @pelikhan I don't think it's clear to users why they wouldn't be able to use 'i' in this program. Can we keep the behaviour from v1 that ensured there was no clash?

**Comment by abchatra** [comment]
@riknoll this looks like regression. Can you take a look?

**Comment by martinwork** [comment]
This doesn't seem to be fixed in beta. I still get

```
let i = 0
basic.forever(function () {
    for (let i = 0; i < 4; i++) {
        i += 1
    }
    basic.showNumber(i)
})
```

**Comment by martinwork** [comment]
Thanks @abchatra . Yes live is OK. Sorry, I didn't know you sometimes release straight to live.
