### ISSUE TITLE
Ability to hide toolbar when embedding in controller mode

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microsoft/pxt-microbit#2454]
#### Is your feature request related to a problem? Please describe.

As previously discussed with Microsoft, the Micro:bit Educational Foundation are developing a web app that embeds MakeCode via an iframe and uses the postMessage-based API to interface with it (via the controller=1 URL parameter).

We'd like to be able to provide a single custom toolbar integrating MakeCode functionality and some relevant to our app, rather than providing the user with two levels of toolbar.

As I understand it, to hide the MakeCode toolbar currently requires a build-time option in pxtarget.json. We would like you to consider adding a runtime option (e.g. via the URL) to control this so that we can embed directly from the makecode.microbit.org deployment.

Originally raised on #2319 but that covered multiple areas and @jaustin asked me to split out toolbar hiding after support for triggering various toolbar actions was added via https://github.com/microsoft/pxt/pull/5859.

#### Describe the solution you'd like

Any solution that allows us to control the hiding of the toolbar without the user ever seeing it (avoiding it showing briefly and then being hidden). A URL parameter that could be supplied alongside controller=1 would be an easy option for us.

**Comment by pelikhan** [comment]
Use https://makecode.microbit.org/beta**?hidemenu=1**

**Comment by microbit-matt-hillsdon** [comment]
Thanks @pelikhan, this is working well.
