### ISSUE TITLE
microbit_heap_print access

### ISSUE THREAD

**Issue by whaleygeek** [microsoft/pxt-microbit#2463]
**Is your feature request related to a problem? Please describe.**
I am running out of RAM

**Describe the solution you'd like**
I want to analyse heap usage dynamically

**Describe alternatives you've considered**
I want to access this function from within MakeCode: https://github.com/lancaster-university/microbit-dal/blob/9164922a519aa213a565cbf2abaa2cf4debf4977/source/core/MicroBitHeapAllocator.cpp#L66

**Additional context**
I think we just need to surface a shim for this? Or is there a magic way I can access this function already in MakeCode? cc @microbit-mark 

![Screen Shot 2019-10-07 at 07 52 30](https://user-images.githubusercontent.com/4086785/66290520-6e70a700-e8d7-11e9-99fb-d6ea6d1fd0af.png)

**Comment by whaleygeek** [comment]
cc @carlosperate you might have a view on this too, as according to @jaustin commit, it is there for release regression testing of memory growth... https://github.com/lancaster-university/microbit-dal/commit/3e37cc9c4ef4b9b560699f13c27bc57358b984a1

**Comment by carlosperate** [comment]
You should be able to enable it by manually editing the pxt.json file: https://github.com/lancaster-university/microbit-dal/issues/390#issuecomment-426228097

**Comment by abchatra** [comment]
@mmoskal

**Comment by mmoskal** [comment]
It won't tell you much of anything about makecode heap. We have ways of printing that through debugger interface but I think it only currently works with codal. There is an experimental feature in pxt to trace objects in Simulator. Would that help?

**Comment by whaleygeek** [comment]
@mmoskal Ah, so there are two heaps - the DAL heap and the MakeCode heap? Does MakeCode use the heap abstraction provided by the DAL (as that allows for more than 1 heap)? I'm really trying to find an easy way for a user (friend of mine) to work out why they are running out of memory and to help with optimising their code.

The simulator trace may help, is it enabled with 'experiments' at all?

**Comment by pelikhan** [comment]
control.headSnapshot is not yet in microbit. A couple days of wait...

**Comment by whaleygeek** [comment]
@pelikhan Ok thanks, will keep a lookout for it. We have optimised the code a bit and got more to fit, but as a longer term issue it would be good to experiment with anything you have in the making to se if we can get better visibility on RAM usage.

As an aside, do you fold string constants at compile time, or is there a more natural javascript way to do this so that the whole string goes in flash as one long string...

``` let data_frame_1 = "011111111111111110" +
    "111111111111111111" +
    "100000000000000001" +
    "110000000000000011" +
    "010000000000000010" +
```
I'm guessing we could just use qingle quoted strings across line boundaries, like you do in LED strings?

```
basic.showLeds(`
    . . . . .
    . . . . .
    . . . . .
    . . . . .
    . . . . .
    `)
```

**Comment by whaleygeek** [comment]
@edbye - have you tried single quoted strings as example above? ^^^

**Comment by whaleygeek** [comment]
@pelikhan are the newlines included in the multi line string? If so, @edbye you will have to parse out the newlines using this data entry technique.

**Comment by mmoskal** [comment]
Newlines are included in backtick literals, so this is indeed a better way. We currently don't constant fold strings (though the beta microbit does constant fold various numeric expressions), but I guess we should.

**Comment by whaleygeek** [comment]
Super, thanks for your help @mmoskal looks like we have a solution for our specific case here, but if you get any additional logging capability let me know as I would like to understand runtime memory usage better thanks!

**Comment by abchatra** [comment]
Workaround provided.
