### ISSUE TITLE
"Repeat Times" block does not work as expected when using var "i"

### ISSUE THREAD

**Issue by sgk** [microsoft/pxt-microbit#2468]
Following code does not work as you expect when you are watching only the blocks.

<img src="https://user-images.githubusercontent.com/485416/66669267-0da7ec80-ec92-11e9-9149-1b67d3b525ca.png" width=300/>

The reason is obvious when reading the converted JavaScript code.

```javascript
let i = 0
input.onButtonPressed(Button.A, function () {
    i = 9
    for (let i = 0; i < 4; i++) {
        basic.showNumber(i)
    }
})
```

However, it should be very hard to make students understand.

**Comment by abchatra** [comment]
fixed in microbit

**Comment by martinwork** [comment]
See https://github.com/microsoft/pxt-microbit/issues/2453.
