### ISSUE TITLE
MAKECODE_RADIO_EVT_BUFFER is gone?

### ISSUE THREAD

**Issue by CleoQc** [microsoft/pxt-microbit#2472]
**Describe the bug**
Latest update to Microbit Makecode breaks GiggleBot Extension. It seems got deprecated?

**To Reproduce**
1. Load the Giggle extension, with a green check mark. 
2. Look in Javascript Explorer, there are 2 errors.
Both errors are 
`error: pxt_modules/giggle/giggle.ts(203,61): error TS2339: Property MAKECODE_RADIO_EVT_BUFFER' does not exist on type 'typeof radio'.`

**Expected behavior**
Our radio blocks should still work.

**Desktop (please complete the following information):**
all

![deadgigglebot](https://user-images.githubusercontent.com/4965628/66853946-660b1280-ef4e-11e9-8bc9-dd35b8b102d1.png)

**Comment by FranklinWhale** [comment]
It was removed in #2461. Although I am not sure whether the constants and calls to raise event will be restored for backward compatibility, I think the [GiggleBot Extension](https://github.com/DexterInd/pxt-giggle/blob/master/giggle.ts) may also be affected by the race condition that @pelikhan intends to fix. Instead of relying on events, the stored callback is now directly called in `onDataReceived`.

**Comment by CleoQc** [comment]
Thanks for the pointer to the PR.  I'll dig into it for now

**Comment by abchatra** [comment]
These are just number constants. You can define your own for a quick fix. 
    export const MAKECODE_RADIO_EVT_NUMBER = 10;
    export const MAKECODE_RADIO_EVT_STRING = 11;
    export const MAKECODE_RADIO_EVT_BUFFER = 12;
    export const MAKECODE_RADIO_EVT_VALUE = 13;

We do strive for backward compat. Usually it involves API exposed to the user.
Internal constants sometimes might change as in this case. Sorry!

Is there anything else broken?

**Comment by abchatra** [comment]
@pelikhan

**Comment by CleoQc** [comment]
@abchatra  it wasn't just the constants, the whole radio behaviour was changed.
I've brought our code up to date with the changes.  Now I can close tons of tickets from our users having issues.

**Comment by abchatra** [comment]
Thanks @CleoQc. We will keep in mind about this extension when we change the radio next time.
