### ISSUE TITLE
Array of Strings automatically changes to an array of numbers

### ISSUE THREAD

**Issue by RetroJimmyX** [microsoft/pxt-microbit#2485]
**Describe the bug**
In the block editor, I create an array of strings 'On Start'.

I then use the on Input A Pressed block to show the string of an array value.

The code then errors because it thinks the array is made of numbers.

When I look at the javascript editor, there is a line 'let text_list: number[] = []' but I change this to 'let text_list: string[] = []' and go into the block editor. It errors again and if I go back to the javascript error, the line has change, again, to 'let text_list: number[] = []'.

If just using the JavaScript editor, the program works fine it is only the action of switching between editors that causes the error.

**To Reproduce**
1. Create an array of strings.
2. Use the 'Show string' block to show a value from the array.
3. Type error appears .

**Expected behavior**

**URL**
Can see the project here:
https://makecode.microbit.org/_LmYELjP5g4Ax

**Screenshot**
![mb](https://user-images.githubusercontent.com/51858595/67150870-36913880-f2b5-11e9-9f44-a0ce6c018a7a.PNG)
![mb1](https://user-images.githubusercontent.com/51858595/67150924-e4044c00-f2b5-11e9-9525-599367ca8c60.PNG)
![mb2](https://user-images.githubusercontent.com/51858595/67150925-e666a600-f2b5-11e9-86a5-a443a5f9b84d.PNG)

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser: Chrome
 - Version: 77.0.3865.120 (Official Build) (64-bit)

**Additional context**

**Comment by abchatra** [comment]
@RetroJimmyX   I can't reproduce this problem. Link you shared seemed to have right code and goes back to block correctly without producing any error

Is it possible to send video or additional steps on the bug you are experiencing?
