### ISSUE TITLE
Beta opens music projects with frequencies not note names

### ISSUE THREAD

**Issue by microbit-giles** [microsoft/pxt-microbit#2488]
**Describe the bug**

**To Reproduce**
1. Go to https://makecode.microbit.org/_8ktUVe56KEia
2. Download project as HEX file
3. Load project in beta MakeCode editor https://makecode.microbit.org/beta
4. See that note names have been changed to corresponding frequency numbers

**Expected behavior**
I expect to see note names not frequencies.

**Screenshots**
Original project looks like this:
![image](https://user-images.githubusercontent.com/42380137/67283084-ee4b6380-f4ca-11e9-98ef-951d07501214.png)

Looks like this when I open it in Beta:
![image](https://user-images.githubusercontent.com/42380137/67283116-f905f880-f4ca-11e9-8a09-ffaa7d6088cd.png)

**Comment by abchatra** [comment]
Fixed in /beta
