### ISSUE TITLE
Uploader for other platforms

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt-microbit#249]
The [uploader](https://codethemicrobit.com/uploader) currently only works on Windows, but it would be nice to have it available on other platforms. Whilst this is low priority, I may write one for OS X at some point.

**Comment by thomasdenney** [comment]
@pelikhan I've thrown together a simple uploader for OS X that is feature equivalent to the Windows version. Would it be best to

a) Distribute it as source, as an unofficial project, under my GitHub
b) The above and also distribute the binary signed with my Apple developer account (again, marked unofficial)
c) Distribute as a binary from codethemicrobit.com, possibly with Microsoft signing, like the Windows version
d) Nothing for now

**Comment by pelikhan** [comment]
Please put it under /clients in pxt-microbit for now (with readme.md on how to use). Awesome!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
