### ISSUE TITLE
Remove range settings from isGesture dropdown

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2492]
From https://github.com/microsoft/pxt-microbit/issues/2234#issuecomment-527887020

https://github.com/lancaster-university/microbit-dal/blob/master/source/drivers/MicroBitAccelerometer.cpp#L275

If I am understanding this code, the 3g, 6g and 8g conditions will only occur as events. They never make it to the variable read by getGesture().

I certainly can't get 3g, 6g and 8g to work with isGesture.

Should these conditions be removed from the options for isGesture?

**Comment by pelikhan** [comment]
This would require a breaking change.

**Comment by pelikhan** [comment]
@abchatra this would mean creating a new enum + upgrading rules.

**Comment by abchatra** [comment]
@pelikhan why there is no support for 3g, 6g & 8g in isGesture? I am confused.

**Comment by pelikhan** [comment]
The CODAL accelerometer does not store those events as "last gesture". 

https://github.com/lancaster-university/codal-core/blob/06e319138cf8884e03f5991a7d14879d0acb0ff8/source/driver-models/Accelerometer.cpp#L234

**Comment by abchatra** [comment]
Old behavior won't fix.
