### ISSUE TITLE
Enabling all Bluetooth services results in a OOM (020)

### ISSUE THREAD

**Issue by gbraad** [microsoft/pxt-microbit#2498]
When using the Bluetooth extension, and the following typescript as below, the device will show an Out of Memory (020):

```typescript
bluetooth.onBluetoothConnected(function () {
    basic.showLeds(`
        # . # # .
        . # # . #
        . . # # .
        . # # . #
        # . # # .
        `)
})
bluetooth.onBluetoothDisconnected(function () {
    basic.showLeds(`
        # . . . #
        . # . # .
        . . # . .
        . # . # .
        # . . . #
        `)
})
bluetooth.startAccelerometerService()
bluetooth.startButtonService()
bluetooth.startIOPinService()
bluetooth.startLEDService()
bluetooth.startTemperatureService()
bluetooth.startMagnetometerService()
```

Note: removing about two services enables the device to operate as 'expected'.

**Comment by microbit-mark** [comment]
BLE services are very memory hungry, so you may hot memory errors. As you say, removing services fixes the issue, so if you are able to do that then that would be the best workaround.

There is more context in this thread

https://github.com/lancaster-university/microbit-dal/issues/390

**Comment by abchatra** [comment]
BLE consumes lot of memory. We can't fix this from MakeCode.
