### ISSUE TITLE
Problem pulse length measurement

### ISSUE THREAD

**Issue by ChrisDorna** [microsoft/pxt-microbit#2500]
**Describe the bug**
We discovered that the value measured is consequently 2/3 of the actual pulse width. 

**To Reproduce**
<img width="320" alt="plaatje" src="https://user-images.githubusercontent.com/20975602/67863763-c9876980-fb24-11e9-9b78-3e2710f840e0.png">

**Expected behavior**
Show right pulse lenght

**Additional context**
Joe Finney had already a look on this issue and answered:
OK… That particular makeCode block (pulseIn) isn’t implemented using our DAL interrupt based code for this – instead it’s using its own software implementation shown below.

This would explain some of the jitter, but not the undershoot. Perhaps the system timer is running slow… but surely we would have noticed if it were so slow…
![plaatje 2](https://user-images.githubusercontent.com/20975602/67863928-19fec700-fb25-11e9-89b1-ae98df36d047.png)

**Comment by martinwork** [comment]
https://github.com/lancaster-university/microbit-dal/issues/451 might be relevant.

**Comment by pelikhan** [comment]
Fix coming https://github.com/microsoft/pxt-microbit/pull/3642

**Comment by abchatra** [comment]
fixed
