### ISSUE TITLE
isGesture does not work

### ISSUE THREAD

**Issue by ChrisDorna** [microsoft/pxt-microbit#2501]
**Describe the bug**
The blok isGesture works in simulator but not on micro:bit. The result is always False

**To Reproduce**
<img width="264" alt="plaatje 3" src="https://user-images.githubusercontent.com/20975602/67864169-84b00280-fb25-11e9-831d-478177f499e2.png">

**Expected behavior**
Block works on micro:bit

**Screenshots**
See above

**Comment by abchatra** [comment]
This should be fixed in /beta. Let me know if this is not fixed.
