### ISSUE TITLE
Can no longer Duplicate Function block

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2505]
> micro:bit support 26184

**Describe the bug**
The function block no longer offers the option to duplicate from the context menu. Copy and Paste still works. Duplicate is available in v1

**To Reproduce**
- Add function block
- Right Click to duplicate
- Option is not listed

**Expected behaviour**
User should be able to click to duplicate.

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

![Screenshot 2019-11-04 at 10 24 16](https://user-images.githubusercontent.com/31242877/68114369-c3f79e00-feed-11e9-93f3-accdd3c013b4.png)

**Comment by microbit-giles** [comment]
This affects Kids Code Jeunesse's recently-published Hour of Code activity, which includes an instruction to right-click and duplicate functions in the Snow Globe project: https://kidscodejeunesse.org/hour-of-code https://kidscodejeunesse.org/data/support_material/hour_of_code/2019/KCJ_HoC_MerryMicrobits_Project_2019.pdf

**Comment by microbit-mark** [comment]
@abchatra @pelikhan as mentioned on call, can you take a look at this one and prioritise a fix.

**Comment by abchatra** [comment]
Ctrl+C Ctrl+V works today. 

We will have the fix in next release.

**Comment by pelikhan** [comment]
Fixed in /beta.
