### ISSUE TITLE
Printing lessons should output all content on all pages

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2511]
> micro:bit support 26259

**Describe the bug**
Currently clicking on print in a docs lesson does not render the full content for the print out

**To Reproduce**
1. Go to 'https://makecode.microbit.org/lessons/truth-or-dare/'
2. Click on 'print'
3. See preview or print, it does not show full content
[truth or dare challenges.pdf](https://github.com/microsoft/pxt-microbit/files/3819099/truth.or.dare.challenges.pdf)
[truth or dare activity.pdf](https://github.com/microsoft/pxt-microbit/files/3819100/truth.or.dare.activity.pdf)
[truth or dare lesson.pdf](https://github.com/microsoft/pxt-microbit/files/3819101/truth.or.dare.lesson.pdf)

**Expected behavior**
I would expect all pages of the lesson, including the activity and challenges to be sent to the print queue and the full content

**Comment by microbit-mark** [comment]
@pelikhan mentioned this on a call. can you take a look.

**Comment by pelikhan** [comment]
This issue is fixed on master; fix needs to be integrated .

**Comment by microbit-mark** [comment]
Do you have a timeline for the integration?

**Comment by microbit-mark** [comment]
@pelikhan This still hasn't made it to live. Do you have a PR/release waiting?

**Comment by pelikhan** [comment]
Ask @abchatra for release schedule.

**Comment by abchatra** [comment]
This will go as part of next major release.

**Comment by abchatra** [comment]
Fixed in /beta
