### ISSUE TITLE
Some block drawers in JavaScript editor are empty

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#2518]
**Describe the bug**
Some block drawers in JavaScript editor are empty

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "JavaScript" to switch to JavaScript editor
3. Open "Basic" "Input" "Music" ....in toolbox and observe

**Expect behavior(live)**
![issue111303com](https://user-images.githubusercontent.com/23466737/68752226-ea2fe300-063d-11ea-8651-6d3c071e279e.gif)

**Actual behavior(beta)**
Some block drawers in JavaScript editor are empty
![issue111303](https://user-images.githubusercontent.com/23466737/68752233-edc36a00-063d-11ea-9409-13552ea9c61f.gif)

**Additional context**
1. OS: Windows(rs6)
2. makecode.microbit.org version: 2.1.25
3. Microsoft MakeCode version: 5.28.19

**Comment by abchatra** [comment]
Fixed
