### ISSUE TITLE
pause(0) will cause simulator halt

### ISSUE THREAD

**Issue by shaoziyang** [microsoft/pxt-microbit#2522]
**Describe the bug**
When run pause(0) function, simulator will halt. In real board it works.
Arcade has this bug too.

**To Reproduce**
![image](https://user-images.githubusercontent.com/1037534/68917471-60028e80-07a5-11ea-9515-430a74f0b0c5.png)

**Comment by jwunderl** [comment]
this is fixed in /beta; issue was here https://github.com/microsoft/pxt-arcade/issues/1098 and fix was here https://github.com/microsoft/pxt/pull/5948

**Comment by abchatra** [comment]
fixed
