### ISSUE TITLE
radio.onReceived handlers broken in beta

### ISSUE THREAD

**Issue by FranklinWhale** [microsoft/pxt-microbit#2523]
**Describe the bug**
`radio.onReceived` handlers are broken in beta

**To Reproduce**
1. Go to https://makecode.microbit.org/beta#editor
2. Click on `Radio` in Blocks mode

**Expected behavior**
![image](https://user-images.githubusercontent.com/8416067/68989402-361e9a00-0881-11ea-87f8-60636369bf8f.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/8416067/68989385-f0fa6800-0880-11ea-91a1-3768e641d9fe.png)

**Comment by pelikhan** [comment]
Good catch...

**Comment by FranklinWhale** [comment]
Verified fixed. Thanks!

**Comment by pelikhan** [comment]
Thanks for reporting!
