### ISSUE TITLE
Broken project tutorial direct link

### ISSUE THREAD

**Issue by kimchouard** [microsoft/pxt-microbit#2524]
**Describe the bug**
The links that used to jump right into a specific tutorial are not broken.
*Link example:* https://makecode.microbit.org/#tutorial:projects/name-tag
*Error*: "Please check your internet access and ensure the tutorial is valid. Network request failed"
*Console error:* "Unhandled rejection Error: Bad HTTP status code: 404 at https://makecode.microbit.org/api/gh/projects/name-tag/master/text

**To Reproduce**
1. Go to this link: https://makecode.microbit.org/#tutorial:projects/name-tag
*Note:* this `name-tag` could be changed to any other projects in the homepage.
2. See error

**Expected behavior**
It used to start the specific tutorial directly (whish was soooo cool and useful 🤩)

Basically, going to this link https://makecode.microbit.org/#tutorial:projects/name-tag was like doing all this:
1. Go to https://makecode.microbit.org/
2. Scroll to "Tutorials"
3. Click on "Name Tag"
4. Click "Start Tutorial".

**Screenshots**

![image](https://user-images.githubusercontent.com/2856923/69117865-02d93800-0a46-11ea-8cde-879d4fb0e8d6.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome & Safari
 - Version: Chrome 78.0.3904.97

**Smartphone (please complete the following information):**
N/A

**Additional context**
I was leveraging the direct link to guide students directly to the right content and it was extremely helpful.

I have solid JS abilities, so happy to contribute to bugfix that if I'm pointed in the right direction. (:

Thanks!!

**Comment by jwunderl** [comment]
I believe this changed to require a leading slash to disambiguate back when support was added for loading from gh links or share links: e.g. https://makecode.microbit.org/#tutorial:/projects/name-tag

**Comment by pelikhan** [comment]
@jwunderl can we make sure the docs are updated?

**Comment by jwunderl** [comment]
Not sure this feature is documented but it would be good to do so, is there a common docs "features for teachers" sort of page? Will look to see where its relevant and update

**Comment by pelikhan** [comment]
I think it is something like custom tutorials. Teacher tips and tricks page would be great

**Comment by pelikhan** [comment]
Also FAQ

**Comment by kimchouard** [comment]
This is great!!!! Thank you @pelikhan @jwunderl (: 

I checked the Teacher page as well, and it's pretty cool too, I wonder if it's **worth adding it to the menu on the left?** Right now it seems to be only accessible through a small link in the FAQ.

Also, the GIFs seems to be broken, they don't show up and links to a buggy URL, like `https://makecode.com/**not-found**/HEAD/static/teachers/how-to-print.gif `
