### ISSUE TITLE
Translations: Translated strings have been removed

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2527]
> microbit support: 26443, 26436, 26434

**Describe the bug**
Previously translated Blocks have reverted back to English.

**To Reproduce**
1. Go to MakeCode
2. Change language eg Japanese
3. Open Input block menu
4. Previously translated menu is now in English

**Additional context**
Users from Japan and Sweden have reported this issue on 19th November. It looks like an update was made on 18th Nov @pelikhan Could this have caused the issue?

<img width="1184" alt="Screenshot 2019-11-19 at 13 19 53" src="https://user-images.githubusercontent.com/31242877/69150425-8d667980-0ad0-11ea-9ab7-0312ac0da26c.png">

**Comment by pelikhan** [comment]
I'm reverting these updates and investigating.

**Comment by pelikhan** [comment]
The translations are fixed. It may take up to 24h for editors to update. Meanwhile, you can test this by opening a incognito window.

**Comment by pelikhan** [comment]
Recovery still in progress.

**Comment by abchatra** [comment]
Fixed
