### ISSUE TITLE
Electron app doesn't work

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt-microbit#253]
The electron app needs https://github.com/Microsoft/pxt-microbit/blob/master/clients/electron/main.js#L24 corrected so that it can run successfully on other computers.

We should document how to use the Electron app.

**Comment by thomasdenney** [comment]
On further investigation I think there's an issue with running the electron app from the subdir in PXT-microbit, as it requires installing a copy of pxt-microbit within itself.

**Comment by thomasdenney** [comment]
I've been experimenting with getting a new electron app working. There are various modifications that need to be made to the PXT source (it makes assumptions about the current working directory and node_module layout that aren't true when using pxt-microbit as a dependency) in order to get it to serve. Monaco's [module loader](https://github.com/Microsoft/vscode-loader) clashes with the Node module loader in Electron apps, so some [hacks](https://github.com/Microsoft/monaco-editor-samples/blob/master/sample-electron/index.html) are required to get round that (which I'm currently looking into).

**Comment by thomasdenney** [comment]
Rather than hacking around the module loader, using the [Electron webview](http://electron.atom.io/docs/api/web-view-tag/) tag it is possible to embed the editor and restrict its access to browser only API. It is therefore only necessary to modify some of PXT server code to make fewer assumptions about directory layout.

**Comment by pelikhan** [comment]
That was my initial thinking. We should be able to build on the local node server infrastructure we already have (needs work of course).

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
