### ISSUE TITLE
controller/postMessage API to change language 

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microsoft/pxt-microbit#2530]
**Is your feature request related to a problem? Please describe.**

This issue relates to embedding MakeCode via controller=1.

As of #2319, we have API to get the list of languages but no API to change language. We can change the URL, but that’s harder for us than sending MakeCode a message and I’m not sure whether it will lose any state for the user.

On https://github.com/microsoft/pxt-microbit/issues/2319#issuecomment-547477411 @pelikhan said:

> ...you need to reload the editor with #lang=ISO. That being said, it might be better if we (the editor) take care of safely reloading with the correct editor.

This issue tracks adding that API.

**Describe the solution you'd like**

Any reasonable API to trigger language change when embedding the editor.

**Comment by abchatra** [comment]
@microbit-matt-hillsdon 
We can't change language without reloading the editor. You need to send the language as the query parameter to the editor. Something like lang=zh-CN
