### ISSUE TITLE
Extension cannot be searched by keyword

### ISSUE THREAD

**Issue by lzl525898** [microsoft/pxt-microbit#2532]
**Describe the bug**
Unable to find new extensions in the extension library，I hope to be searched like a cruise.

**To Reproduce**
1. Enter the extension in makecode
2. Search in the search bar minicruise
3. To find the desired extension

**Expected behavior**
I hope to be searched like a cruise.

**Screenshots**
![11111](https://user-images.githubusercontent.com/14171603/69291736-1bf90900-0c3f-11ea-8ac7-4b0bf672df15.png)

**Additional context**
Currently [alsrobot-microbit-makecode-packages
] I am maintaining, adding a new package, I hope to add MiniCruise, the project address is https://github.com/alsrobot-microbit-makecode-packages/MiniCruise.git

**Comment by abchatra** [comment]
Only whitelisted extensions can be searched. Please go through the microbit foundation approval process for white listing the extension.

https://support.microbit.org/support/solutions/articles/19000054952-makecode-extension-approval
