### ISSUE TITLE
The content in my save file in the micro bit web is gone

### ISSUE THREAD

**Issue by ChongJF** [microsoft/pxt-microbit#2536]
When I save my project int the micro bit web, the content in it sometimes disappear.The file is still there, but there is nothing inside.

I have no idea how this happened. I definitely had save it. The first time i opened it,it was fine.I didn't change anything and click home. Then when I want to open the file again, there was nothing inside.

 - OS: Windows 10
 - Browser Chorme

**Comment by gbraad** [comment]
this could be due to several causes; please describe your environment in mor edetail, like versions of chrome, open tabs, etc. Especially, if you have MakeCode open in multiple tabs. or are you using the cookie removal function or other thirdparty tool to 'clean' your browser?

**Comment by abchatra** [comment]
We store the file in the browser cache. If you are any extension clears the browser cache or you use the browser incognito window then the projects won't be saved.

There might be bug in our editor which might cause to get erased as well. Can you give us all the details, like which browser and the actions before they get erased? 

 @darzu @riknoll

**Comment by microbit-mark** [comment]
Another user reports this experience. Could a recent update have caused projects to be removed?

**Comment by abchatra** [comment]
We have not updated the website in a while

**Comment by abchatra** [comment]
This might be code losing bug.

**Comment by abchatra** [comment]
Closing. Likely fixed in /beta.
