### ISSUE TITLE
Support maintaining block layout when rendering JavaScript to blocks via iframe

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microsoft/pxt-microbit#2539]
**Is your feature request related to a problem? Please describe.**

Many webpages on the microbit.org site use the renderblocks iframe API to render JavaScript to blocks. We've been considering making more use of embedding MakeCode more directly, via iframes with URLs of the form https://makecode.microbit.org/#pub:_i7i7Ayajq8cg. A major benefit of doing so is that the author's layout of the blocks is maintained.

In discussion with Microsoft there were performance concerns about this approach, as a lesson or project page might have several of these embeds. @pelikhan suggested the blocks rendering could be extended to respect block layout if provided with a project instead of just the JavaScript code. Then we can get the layout with similar performance characteristics to the current approach.

**Describe the solution you'd like**

We'd like the API that render JS to blocks to be extended to be able to take a MakeCode project JavaScript object, JSON, or similar, to maintain the blocks layout from that project when rendering the blocks.

**Describe alternatives you've considered**
We're open to other approaches.

**Additional context**
N/A

**Comment by pelikhan** [comment]
Try passing the share project id (after pub:) as ``options.packageId`` in the request --> https://github.com/microsoft/pxt/pull/6262/files
