### ISSUE TITLE
pxsim.bluetooth.onBluetoothConnected is not a function

### ISSUE THREAD

**Issue by smartyw** [Microsoft/pxt-microbit#254]
I started a new project and pasted some JavaScript code I've been working on into the JavaScript window. Every now and again a red error message appears saying onBluetoothConnected is not a function. You can see the error in the developer console of Chrome, pasted here:

![image](https://cloud.githubusercontent.com/assets/1387793/18556612/ca6d64c4-7b63-11e6-8ae5-f35318f9c11b.png)

The JavaScript code is:

```
bluetooth.onBluetoothConnected(() => {
    connected = 1
    basic.showString("C")
})
```

This code used to work OK.

**Comment by pelikhan** [comment]
This function is missing a simulator inplementation. For now we can have a no-op.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by smartyw** [comment]
OK, sounds like a plan :-)

To be clear (I suspect I wasn't), I didn't report this because I noticed the error in the console but because it pops up in a red box. It disappears quickly so it's hard to grab a screen shot. But.... I just managed to! It looks like this:

![image](https://cloud.githubusercontent.com/assets/1387793/18557403/b61b7436-7b66-11e6-9ed8-37d9601a4c77.png)

**Comment by abchatra** [comment]
This is fixed.
