### ISSUE TITLE
Certificate not trusted error

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2548]
**Describe the bug**
Users are finding issues accessing makecode.microbit.org as they are gettings a certificate error.
![Microbit](https://user-images.githubusercontent.com/31242877/70240951-17b40c00-1766-11ea-9de4-a2e13ccdd86d.PNG)
<img width="1270" alt="Screenshot 2019-12-05 at 13 49 50" src="https://user-images.githubusercontent.com/31242877/70240975-213d7400-1766-11ea-86e3-a62ead914c98.png">

5 users have reported this happening overnight, has there been a certificate update that has caused this issue?

**Comment by microbit-mark** [comment]
@abchatra @pelikhan I have 7 tickets raised about this now, can you take a look?

**Comment by abchatra** [comment]
@microbit-mark what is the browser? I can't repro in n ay browser

**Comment by abchatra** [comment]
@microbit-mark This might be particular to a firewall. We know the fix addressing it soon.

**Comment by carlosperate** [comment]
I'm also getting certificate errors when trying to check the links in the https://github.com/carlosperate/awesome-microbit/ list via GH Actions:

- https://github.com/carlosperate/awesome-microbit/commit/9c5744abe3f7c42cdc6a9657f43f0ba729e5b078/checks?check_suite_id=344315527

```

Issues :-(
> Links 
  01. [L050]  https://makecode.microbit.org SSL_connect returned=1 errno=0 state=error: certificate verify failed 
  02. [L051]  https://makecode.microbit.org/beta SSL_connect returned=1 errno=0 state=error: certificate verify failed 
  03. [L140]  https://makecode.microbit.org/extensions/build-your-own SSL_connect returned=1 errno=0 state=error: certificate verify failed 
  04. [L140]  https://makecode.microbit.org/extensions SSL_connect returned=1 errno=0 state=error: certificate verify failed 
  05. [L248]  https://makecode.microbit.org/uploader SSL_connect returned=1 errno=0 state=error: certificate verify failed 
  06. [L264]  https://tickleapp.com SSL_connect returned=1 errno=0 state=error: certificate verify failed 
  07. [L397]  https://makecode.microbit.org/projects/ SSL_connect returned=1 errno=0 state=error: certificate verify failed 
  08. [L502]  https://makecode.microbit.org/courses/csintro SSL_connect returned=1 errno=0 state=error: certificate verify failed 
  09. [L509]  https://makecode.microbit.org/courses/ucp-science SSL_connect returned=1 errno=0 state=error: certificate verify failed 
```

**Comment by carlosperate** [comment]
Since the checker runs daily I've look at the history and it started failing yesterday. The third of December at 9am GMT was working fine, but the 4th at 9am GMT was already producing the errors.

@microbit-mark does that align with the dates from your support tickets?

**Comment by abchatra** [comment]
Fixed. Certificate was renewed by lets encrypt yesterday and it had intermediate cert issue. This doesn't impact any browser as they likely bake in the lets encrypt x3.  
We fixed the intermediate cert issue in our backend.
