### ISSUE TITLE
Not able to run four continuos servos at same time from makecode

### ISSUE THREAD

**Issue by wackyworm** [microsoft/pxt-microbit#2550]
**Describe the bug**
I have micro:bit connected to 4 fs90r continuos servos using a "Keyestudio Sensor Shield V2" board, but only 3 of the 4 wheels are working using makecode, but it works using micropython so it is not a hardware problem

**To Reproduce**
Put this code in makecode web or windows app and download it to the micro:bit

    led.enable(false) // to enable P3
    pins.servoWritePin(AnalogPin.P0, 180)
    pins.servoWritePin(AnalogPin.P1, 180)
    pins.servoWritePin(AnalogPin.P2, 180)
    pins.servoWritePin(AnalogPin.P3, 180)

Connect the four fs90r servos to the board, only the ones in P1, P2 and P3 are running

If I change the order of the pins in the code, only the last 3 are working and the first one is not working, for example with:

    led.enable(false) // to enable P3
    pins.servoWritePin(AnalogPin.P1, 180)
    pins.servoWritePin(AnalogPin.P2, 180)
    pins.servoWritePin(AnalogPin.P3, 180)
    pins.servoWritePin(AnalogPin.P0, 180)

P1 is the one that doesn't works

But if I use micropython the 4 servos are working, example code:

    from microbit import *
    display.off()
    pin0.set_analog_period(20)
    pin1.set_analog_period(20)
    pin2.set_analog_period(20)
    pin3.set_analog_period(20)
    pin0.write_analog(1023*2/20)
    pin1.write_analog(1023*2/20)
    pin2.write_analog(1023*2/20)
    pin3.write_analog(1023*2/20)

It happens the same in makecode trying to use the analog functions, only 3 servos are working:

    led.enable(false)
    pins.analogSetPeriod(AnalogPin.P0, 20000)
    pins.analogSetPeriod(AnalogPin.P1, 20000)
    pins.analogSetPeriod(AnalogPin.P2, 20000)
    pins.analogSetPeriod(AnalogPin.P3, 20000)
    pins.analogWritePin(AnalogPin.P0, 1023 * 2 / 20)
    pins.analogWritePin(AnalogPin.P1, 1023 * 2 / 20)
    pins.analogWritePin(AnalogPin.P2, 1023 * 2 / 20)
    pins.analogWritePin(AnalogPin.P3, 1023 * 2 / 20)

**Expected behavior**
4 servos should be working as happens when using micropython

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 78

I tried with https://makecode.microbit.org/, https://makecode.microbit.org/beta and the windows app

**Comment by abchatra** [comment]
@pelikhan

**Comment by DaveAtKitronik** [comment]
Known 'feature' - the lower layer DAL only supports 3 PWM channels at any time.

**Comment by abchatra** [comment]
Thanks @DaveAtKitronik for the info.

**Comment by wackyworm** [comment]
Hello @DaveAtKitronik 

Sorry for my ignorance, but it works using micropython, is that "lower layer DAL" different between makecode and micropython?

Thanks

**Comment by DaveAtKitronik** [comment]
I'm not certain, but I think that Micro Python has its own lower level hardware abstraction which is different from the PXT lower layer. @dpgeorge might know for sure.  PXT uses the DAL in the lower layers. The DAL only has 3 PWM timers available due to the way that software is written.

**Comment by dpgeorge** [comment]
> Micro Python has its own lower level hardware abstraction which is different from the PXT lower layer

That's correct, it has a custom PWM driver that supports up to 19 pins at once.

**Comment by wackyworm** [comment]
Thank you @DaveAtKitronik and @dpgeorge for the clarification, I really appreciate that info
