### ISSUE TITLE
Catch the egg tutorial broken

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2551]
**Describe the bug**
The final code in catch the egg https://makecode.microbit.org/lessons/catch-the-egg-game/activity does not work properly

Probably related to https://github.com/microsoft/pxt-microbit/issues/2544

**To Reproduce**
1. Go to 'https://makecode.microbit.org/lessons/catch-the-egg-game/activity'
2. Load the final activity code
3. Note that a life is not lost for column 0 and 4, but is lost for column 1, 2 & 3 when trying to catch the egg

**Expected behavior**
egg can be caught in all columns

**Comment by microbit-mark** [comment]
@abchatra Can you take a look? I think tutorials might need a review to check if any issues have been introduced since we introduced floating point math. There have been a couple reported now.

**Comment by abchatra** [comment]
@ganicke

**Comment by microbit-mark** [comment]
Can you take a look @ganicke?

**Comment by ganicke** [comment]
Sure, I look through them and fix the remainder problem in needed.
