### ISSUE TITLE
TryStatement not supported

### ISSUE THREAD

**Issue by IowaDave** [microsoft/pxt-microbit#2553]
**Describe the bug**
try ... catch and try ... finally exception handling fails in MakeCode online editor for microbit

**To Reproduce**
1. Start a clean project: https://makecode.microbit.org/#editor
2. Click on JavaScript tab
3. Enter this code:
```javascript
try {
    let x = 1
} 
finally{}
```
4. See error: entire code gets red underlines. Error statement is 'TryStatement not supported'

**Expected behavior**
According to documentation, exception handling is supported. Expected this code to work.

**Desktop (please complete the following information):**
 - OS: Raspbian (Debian) Linux
 - Browser [Chromium
 - Version 74.0.3729.157 (Official Build) Built on Raspbian , running on Raspbian 10 

**MakeCode editor information**
makecode.microbit.org version:  2.0.10
Microsoft MakeCode version:  5.15.13
microbit runtime version:  pxtgc-0

Note the above version of MakeCode editor is what comes up after typing the url into the browser (after clearing the cache.)

**Comment by FranklinWhale** [comment]
Supported in beta version: https://makecode.microbit.org/beta#editor
```ts
let x;
try {
    x = 1
}
finally {
    basic.showNumber(x ? x : -1)
}
```

**Comment by IowaDave** [comment]
Confirmed. Thank you!

**Comment by abchatra** [comment]
Next release will have in the live.
