### ISSUE TITLE
Toolbox missing in Edge

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2556]
> micro:bit support: 26810

**Describe the bug**
"sometimes when my students go to MakeCode for Micro:bit, they cannot see the toolbox. The area where the toolbox normally is is just white. I have had them try different browsers and restart their computers. This resolves the situation for most students, but for one student in particular, this started last week and still has not resolved itself."

**To Reproduce**
Open program in MakeCode.

**Expected behavior**
Toolbox should load

**Screenshots**
Issue:
![image](https://user-images.githubusercontent.com/31242877/70709793-ac25ed80-1cd5-11ea-8d8d-b4e4df14e8e1.png)

Expected result:
<img width="835" alt="Screenshot 2019-12-12 at 11 45 57" src="https://user-images.githubusercontent.com/31242877/70709840-c65fcb80-1cd5-11ea-8140-168f2e76d991.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge

**Additional context**
Cannot recreate myself, so this appears to be a local issue.

**Comment by abchatra** [comment]
Can you please get the version of Edge? @microbit-mark

**Comment by microbit-mark** [comment]
No response from user on this one. I will close and re-open if needed
