### ISSUE TITLE
How to change the extension library name

### ISSUE THREAD

**Issue by lzl525898** [microsoft/pxt-microbit#2558]
Due to product changes, the extension 'minicruise' needs to be modified to 'Cruise-E'

How to make changes, or what information needs to be provided?

Currently I don't know how to modify the short name of the extension library

**Comment by microbit-mark** [comment]
If you are changing the repository extension, then https://github.com/microsoft/pxt-microbit/blob/master/targetconfig.json and https://github.com/microsoft/pxt-microbit/blob/master/docs/extensions.md need modifying.

If the repository name is not changing, then you just need to update your documentation and create a release.

**Comment by lzl525898** [comment]
![demo](https://user-images.githubusercontent.com/14171603/70964043-567e8600-20c5-11ea-97dd-a69ef1279098.png)

I want to search for "CruiseE" in the search box, and I can find the extension of the red box in the picture above
And minicruise changed to CruiseE

**Comment by abchatra** [comment]
Please change the description of your github repo. It says now:
"MiniCruise Package for Microsoft PXT"
Also rename your github package.
