### ISSUE TITLE
include base/control.ts from common packages in microbit

### ISSUE THREAD

**Issue by mmoskal** [microsoft/pxt-microbit#2563]
**Is your feature request related to a problem? Please describe.**

Folks were asking for certain features that are in common pkgs but not in microbit, in particular:

- [x] https://forum.makecode.com/t/read-free-memory-at-runtime/919 - free memory

- [x] https://forum.makecode.com/t/how-to-go-about-an-interval-extension/812 - intervals

- [ ] https://forum.makecode.com/t/how-can-i-access-the-name-of-my-program/764 - program name (this one was Ev3 but microbit isn't much of a stretch)

**Comment by abchatra** [comment]
@pelikhan will this come as your common-packages plan?

**Comment by pelikhan** [comment]
Yes we should bring this in.

**Comment by pelikhan** [comment]
I did not bring in program name but the rest is there. @mmoskal  close?

**Comment by mmoskal** [comment]
yeah, let's wait until someone asks
