### ISSUE TITLE
[MakeCode for micro:bit   & 1.1.0.0] Back button is not functioning properly      

### ISSUE THREAD

**Issue by leiz2010** [microsoft/pxt-microbit#2566]
[MakeCode for micro:bit   & 1.1.0.0]:- Back button is not functioning properly      

Environment: Desktop   
OS build: 19026, 18362, 17763   
OS: Windows 10 Insider   Preview, Windows 10      

Repro Steps:   1. Launch the application.   
2. Click on Blocks to Java Scripts in Home Page or Courses.   
3. Select Show Instructions.   
4. Click the back button.   
5. Observe.      

Actual Results:   Back button is not functioning properly.      

Expected Results:   Back button should be functioning without any issues.

**Comment by abchatra** [comment]
You need to click on HOME button to go back
![image](https://user-images.githubusercontent.com/6107272/71932195-3e45d800-3154-11ea-91c8-fc96dc0135b3.png)

MakeCode is a single app application today with no browser navigation ability.
