### ISSUE TITLE
Feature request: double click function call to jump to function definition

### ISSUE THREAD

**Issue by woutput** [microsoft/pxt-microbit#2567]
**Is your feature request related to a problem? Please describe.**
How to quickly find a function definition?

**Describe the solution you'd like**
Especially in bigger projects, function definitions may be hard (taking much time) to find. If a double click on the function call would jump to the function definition, I think it would help.

So double click this:
![image](https://user-images.githubusercontent.com/14995512/71784971-50abfe80-2ffa-11ea-8938-1c879c09b090.png)
to go to here:
![image](https://user-images.githubusercontent.com/14995512/71784976-64576500-2ffa-11ea-9096-adf95ed35671.png)

**Describe alternatives you've considered**
Searching all of the canvas to find the correct function definition which is no fun.

Please provide your opinion :)

**Comment by pelikhan** [comment]
Would collapsing functions help with the size of the program?

**Comment by woutput** [comment]
That sounds like a good idea too.

**Comment by abchatra** [comment]
Fold function will be provided as issue https://github.com/microsoft/pxt-microbit/issues/1753 Closing this as duplicate.
