### ISSUE TITLE
Screenshot feature in all makecode editors please

### ISSUE THREAD

**Issue by tanyafish** [microsoft/pxt-microbit#2570]
**Is your feature request related to a problem? Please describe.**
In the online version of the makecode editor, you can right click and take a shot of the code used. In the app version of the editor you can't.

**Describe the solution you'd like**
An easy code-only screenshot option on the app version.

**Describe alternatives you've considered**
I can screenshot the window and cut it to size, but I like the neatness of the built-in option.

**Additional context**
No context other than it would be super helpful to have.

**Comment by abchatra** [comment]
@tanyafish are you using windows store app or the offline ap?

**Comment by tanyafish** [comment]
This is on the windows store app.

**Comment by abchatra** [comment]
There is a Edge browser bug, on which the windows store app is dependent. We are waiting for the bug to fixed before we can enable the screen shot feature on the windows app.

**Comment by abchatra** [comment]
This is an Edge bug and we can't fix it. Hopefully new renderer from edge will fix this.
