### ISSUE TITLE
MicroBit MakeCode JavaScript program runs in emulator but won't download/compile

### ISSUE THREAD

**Issue by ikanode** [microsoft/pxt-microbit#2577]
The attached Javascript program runs in the emulator but won't download/compile. The project uses a 24 LED Neopixel ring and melodies for a two-year-old.

• No errors are shown in the editor
• I get the same behavior in different browsers and in the Windows: MakeCode for microbit
• The file will compile and run on the Micro:Bit by:
-- Commenting out some of the song arrays
or
-- Commenting out a few functions (it doesn't matter which ones)
(The FILE AS SENT WILL RUN because the last two functions (SixG & FreeFall) are commented-out.   It will fail if the comment block is removed.)

My guess is that it's a compile memory issue.

[microbit-3-Feature-Complete-23 Kanode.hex.zip](https://github.com/microsoft/pxt-microbit/files/4040918/microbit-3-Feature-Complete-23.Kanode.hex.zip)

Thanks,
Irv

**Comment by abchatra** [comment]
This program is too big by 1624 bytes!. Microbit hardware has limited memory and can't fit this in. @mmoskal any suggestion here to reduce the program size?

**Comment by mmoskal** [comment]
You can encode the melody as eg `"r,a4:4,b,c,d"` etc and then do `song.split(",")`; this may blow up the RAM though, but worth a try.

**Comment by ikanode** [comment]
@abchatra   Thanks!  
How can I know the memory size?

**Comment by abchatra** [comment]
If you go to developer tools (F12 in the browser), console window will show you the error.

**Comment by woutput** [comment]
> If you go to developer tools (F12 in the browser), console window will show you the error.

Could this be made more user friendly?

**Comment by abchatra** [comment]
@woutput, yes that is good suggestion.

**Comment by woutput** [comment]
This may be strongly related to #2001

**Comment by abchatra** [comment]
Workaround present. Advanced feature request.
