### ISSUE TITLE
Error message hidden for large blocks

### ISSUE THREAD

**Issue by woutput** [microsoft/pxt-microbit#2578]
**Describe the bug**
This works correctly on small blocks: When a block contains an error, a triangle with exclamation mark is shown on the block. When you click the triangle, an error message is shown.
This is the problem for big blocks: the error message is shown at the top of the block, not at the location of the triangle. So when you can't see the top of the block, clicking the triangle doesn't appear to do anything.

**To Reproduce**
1. Create a block which initializes a large list (actual type is String[])
2. Make the block generate an error
3. Scroll to the triangle
4. Click the triangle
5. Problem: don't see the error message

**Expected behavior**
If the error message would be shown next to the triangle, it would always be visible if you click the triangle.

**Screenshots**
This is the normal view which doesn't show the error message:

![image](https://user-images.githubusercontent.com/14995512/72201691-135ecb00-3457-11ea-94a0-e077fc6daec7.png)

This is the (unusual) zoomed out view which does show the error message at the top of the large block (of you look carefully)

![image](https://user-images.githubusercontent.com/14995512/72201700-25d90480-3457-11ea-9f98-f34df4095509.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by abchatra** [comment]
We have made improvement here. Please revalidate.
