### ISSUE TITLE
Feature: Support message blocks in sidebar docs

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2581]
**Is your feature request related to a problem? Please describe.**
Being able to edit the project README.MD to provide documentation is a useful feature and an alternative to using guided Tutorials. I've written this up here https://support.microbit.org/en/support/solutions/articles/19000109391-publishing-a-user-tutorial-in-a-makecode-project
but currently, it doesn't support all the features offered by MakeCode markdown eg message boxes from https://makecode.com/writing-docs/macros

<img width="1032" alt="Screenshot 2020-01-15 at 09 58 48" src="https://user-images.githubusercontent.com/31242877/72424546-17079000-377e-11ea-89a6-20a3f2ee1d88.png">

**Describe the solution you'd like**
Have the sidebar render message boxes like the online docs do.

**Comment by microbit-mark** [comment]
Interestingly `~hint` works here, but others do not

**Comment by pelikhan** [comment]
Only a subset of words work. See macros docs page

**Comment by pelikhan** [comment]
See https://makecode.com/writing-docs/macros , message boxes.

**Comment by microbit-mark** [comment]
@pelikhan Only one word out of that subset appears to work https://github.com/microsoft/pxt-microbit/issues/2581#issuecomment-582058723 unless the docs are incorrect?

<img width="788" alt="Screenshot 2020-02-05 at 09 14 55" src="https://user-images.githubusercontent.com/31242877/73827834-2bc4ca00-47f8-11ea-89b2-4e0eacef07af.png">

**Comment by abchatra** [comment]
@shakao  do you know why some of these are not working. I tried it out and it didn't work in the side docs in /beta

**Comment by shakao** [comment]
hmm, maybe the side docs rendering goes hits a slightly different path than the regular docs? i think the only macros that are enabled are the ones defined here https://github.com/microsoft/pxt/blob/master/pxtrunner/runner.ts#L756 (hint & tutorialhint are the only boxes i think). i can add the other ones if we want!

**Comment by abchatra** [comment]
Probably we should unifty. I will keep this bug for microbit release. Not urgent

**Comment by pelikhan** [comment]
Fixed.
