### ISSUE TITLE
Tfabworks - package not approved

### ISSUE THREAD

**Issue by rjmcl** [microsoft/pxt-microbit#2584]
**Describe the bug**
I have come across an ultrasonic sensor I was considering using in a project.
The sensor information came by way of the company "Tfabworks" linked through micro:bit.
Accessing the company information and data on the sensor in question and example micro:bit file was presented. When viewing the example file the 'extension' (STEM) was included in the download.
On checking out the 'Stem extension' I get the following page not found message:

https://makecode.microbit.org/pkg/tfabworks/pxt-stem#getdistance
 - package not approved

**Screenshots**
![image](https://user-images.githubusercontent.com/58401423/73082014-a6a3f180-3e96-11ea-9a0a-ef10661cad97.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 pro
 - Browser chrome
 - Version 79

Do you have any additional information such as if/when this software from Tfabworks will be approved. No information has been seen from the developer to suggest the software has not been approved for use by github and micro:bit users.

Regards

**Comment by abchatra** [comment]
Please ask https://tfabworks.com to go through the extension approval process through Microbit foundation.  Here is the link to the process.
https://support.microbit.org/support/solutions/articles/19000054952-makecode-extension-approval
