### ISSUE TITLE
Strings missing on Crowdin for 'core-jsdoc-strings'

### ISSUE THREAD

**Issue by ganicke** [microsoft/pxt-microbit#2585]
The `core-jsdoc-strings.json` uploaded to Crowdin is missing LOTS of strings. The built file has 560+ strings but the one on Crowdin has less than 100.

Noticed by Michael Klien, see: https://crowdin.com/translate/kindscript/65/en-de#286900

Strings file: https://crowdin.com/translate/kindscript/66/en-de

**Comment by abchatra** [comment]
@pelikhan any clue here?

**Comment by abchatra** [comment]
Fixed?
