### ISSUE TITLE
Time a project was created

### ISSUE THREAD

**Issue by CLDolphin** [microsoft/pxt-microbit#2588]
Hi
I am trying to retrieve the time a project was created .
I work in a school and I am trying to download the files created by certain students. For this I need to know the day and hour the project was created so I could tell which student created it. 
I've faced some problems while trying to retrieve this information.

The time format is could help more since it sometimes lists only that the project was created "3 months ago" for instance.  
The platform also only shows last time the project was modified.
So I loose precious information if I open it to download or if someone else opens it for the sake of curiosity. 

I would like a feature where I can sort the project list by the time it was created. It would be helpful because this time would not change if I open a project.

I am trying to retrieve this information injecting some javascript in the console. 
I made some progress as shown here: https://support.microbit.org/support/tickets/27480
But I'm still not able to do what I need.

**Comment by abchatra** [comment]
No plans to address this issue.
