### ISSUE TITLE
Ability to turn off second virtual Microbit when using 'radio' functions

### ISSUE THREAD

**Issue by edbye** [microsoft/pxt-microbit#2592]
**Is your feature request related to a problem? Please describe.**
Whilst working with some students developing code to use on two Mircobits radio linked, it became  apparent that in the simulator two virtual Microbits are displayed, with only the ability for one, common set of code. In their application differnt code is required on the two Microbits. The dual display causes great confusion and frustration.

**Describe the solution you'd like**
The ability to turn off the second virtual Microbit in the simulator would help clarity tremendously. It would be even nicer if two separate programming, one for each Microbit could be displayed, but then if more than two Microbits required, how would that work?

**Describe alternatives you've considered**
The only alternative is to result to the old fashion way of developing 'radio' related  code - using real Microbits and lots of flashing and testing, students loose interest.

**Additional context**
Nil ATM

**Comment by whaleygeek** [comment]
I've been chatting this over with Ed, I have had similar problems on a lot of my radio projects over the years and the frustration matches that of the child in this case. As I know what I am doing, I will often merge two programs into one and start them in different modes with a different button press; however this is too complex for beginner programmers.

I think this limits how far we can go with radio projects, and as Ed says, repeated flashing ends up slowing down the fast iteration and learning, and young people give in.

I had a thought that @pelikhan might want to comment on - how about a new block on radio that puts it into a 'remoting' mode, where we then plug a real micro:bit into the USB and the simulator sends and receives radio data via a real micro:bit running a pre-rolled hex? Could even be part of 'experiments'. The 'pre rolled hex' could be a link in MakeCode that you load into a micro:bit. Note also that this would then allow any number of different programs running in separate browser instances on different computers in a class, to collaborate wirelessly; I think it could really speed up experimentation with radio in a class situation, and make sure young learners stick at it and don't loose interest in radio features too quickly.

If you look at the networking book that I helped to write with @ciseng you will see that she wrote a mock radio wrapper that introduces random errors, which was a really nice design pattern, I thought, and it was this chapter (and work I did with my 196 micro:bit orchestra) that gave me the idea of using a micro:bit as a real wireless gateway with MakeCode (WebUSB might make this so much easier too!)

https://github.com/nominetresearch/microbit-networking-book/blob/master/index.md

Comments?? @jaustin

**Comment by jaustin** [comment]
Thanks for raising, 
@whaleygeek and @edbye does the user still need the simulator at all if they use webUSB for quick turn around debugging? If using primarily radio functionality it might be better to debug 'on the device' and propose the following
* Connect via webUSB
* Turn off the simulator
* hit 'download' to run/test on the micro:bit each time

Here's the support article for that https://support.microbit.org/support/solutions/articles/19000084059-using-web-usb-with-the-apps-and-editors

I know this isn't exactly what you're asking for, but wonder if it's a good workaround for the more advanced students that avoids either new blocks or added UI elements that will be in the path of everyone?

(And furthermore, while there's only one micro:bit in the simulator, it's hard to use it to test radio stuff easily...)

**Comment by edbye** [comment]
The schools I work in don't have/use webUSB and probably won't for some time, so that as a potential solution is of no use to me.

Agreed with final comment about testing radio stuff in simulator, yes hard to test. With two virutal Microbits and a common set of code, very confusing, hence my request to turn one off or provide facility for two independant sets of code.

**Comment by pelikhan** [comment]
Something like this?
![2020-02-04 22 28 46](https://user-images.githubusercontent.com/4175913/73816566-c6dc8600-479d-11ea-89c1-e66129449132.gif)

**Comment by edbye** [comment]
Wow, yes, thanks.
I think something like that would work well and be a vast improvement over the existing radio simulation and also very helpful when developing radio applications, especially for beginners.
Much appreciated and look forward to seeing an implementaion. 
Ed

**Comment by pelikhan** [comment]
Please try https://makecode.com/multi-editor . This is running micro:bit beta so you might need to wait for a refresh.

**Comment by pelikhan** [comment]
![2020-02-06 13 49 22](https://user-images.githubusercontent.com/4175913/73981941-32cb0580-48e8-11ea-95b7-73b1c529fae4.gif)

**Comment by whaleygeek** [comment]
Genius!!

Chuck-a-duck has a new life!!!!

![Screen Shot 2020-02-06 at 22 49 59](https://user-images.githubusercontent.com/4086785/73985436-12746880-4933-11ea-8d20-135c65e09a9e.png)

![Screen Shot 2020-02-06 at 22 50 14](https://user-images.githubusercontent.com/4086785/73985444-1607ef80-4933-11ea-8974-a81b07f374d7.png)

**Comment by edbye** [comment]
Wow,

That's great and such a quick result, thanks very much.

I'm with the student again on Weds and will see what she makes of 
it/with it.

Kind regards

Ed

Ed Bye MIET RCT Technical Director, Electro-Medical Diagnostics Limited

**Comment by edbye** [comment]
My student who highlighted the need for this tried it out yesterday.
She had struggled for almost 2 hours coding on the old version, within 15min she had her code completed and simulated on a pair of Microbits using your multi-editor.
Fantastic work thanks very much and also for your quick response.

**Comment by pelikhan** [comment]
In the beta, you can also open new tabs from the “my projects” now.
