### ISSUE TITLE
Missing pair device link

### ISSUE THREAD

**Issue by ToodleBit** [microsoft/pxt-microbit#2593]
I work with several schools and one of them does not have 'pair device' listed under the cog heading. I've check their Chrome version, which is 70+ and the MicroBit has the latest firmware 0253. The MicroBit also pairs on a non-school laptop. Can you advise what else I could check for? The laptops are managed by a separate company. Is there any restrictions they could have put in place?

Thanks Matthew

**Comment by pelikhan** [comment]
Have you tried support.microbit.org there might be a ticket for this already.

**Comment by abchatra** [comment]
@ToodleBit Can you share the exact Chrome version? If possible copy\paste the screen shot of the version.

**Comment by ToodleBit** [comment]
Thanks for your replies. I have now looked at the support.microbit.org page. These are older computers so might have been upgraded from Windows 7 to 10. I will follow up the following advice, _'If you have upgraded from a previous version eg Windows 7 > Windows 10 you may experience a confict with an old driver. If the Mbed Serial driver has been manually installed (by downloading and executing the .exe) it might interfere with the Windows 8/10 automatic installation of the WebUSB driver.'
Will also try and get the actual Chrome version number tomorrow when they reopen.

**Comment by microbit-mark** [comment]
@ToodleBit were you able to resolve this? If not,do you have any further info?

**Comment by ToodleBit** [comment]
Not yet. I am waiting on some information from the school, who have to wait for their technical support. This could take a while.

**Comment by abchatra** [comment]
I reopen when we have more information.
