### ISSUE TITLE
the submenus (...more) don´t change their content any more

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-microbit#2594]
since the last switch to pxt-core 5.32.21 like microbit/beta or calliopemini, the submenus (...more) don´t change their content:

![Unbenannt](https://user-images.githubusercontent.com/37311672/73748285-5d3a8880-4759-11ea-85f3-3ba55a7d2a89.png)

**Comment by pelikhan** [comment]
We’re looking into this
