### ISSUE TITLE
Code snipets on the README page of approved extensions are broken

### ISSUE THREAD

**Issue by paulobarcelos** [microsoft/pxt-microbit#2595]
**Describe the bug**
When opening the "read me" page of an approved extension (for example https://makecode.microbit.org/pkg/strawbees/pxt-robotic-inventions) the snipets of code are not rendered properly (they are rendered as unreable gray rectangles).

In contrast, opening the same page, as a "github page" (for example https://strawbees.github.io/pxt-robotic-inventions/) works correctly.

This is a serious problem since it renders the readme page totaly unusable. Also tested with different extensions and had the same problem.

**To Reproduce**
1. Go to https://makecode.microbit.org/pkg/strawbees/pxt-robotic-inventions
2. Scroll down past the image, to see the code examples.
3. See that you can't see any code, and instead just see unreable gray rectangles.

**Expected behavior**
To be able to see the code, rendered as makecode blocks.

**Screenshots**
<img width="1110" alt="Screenshot 2020-02-04 at 11 30 27" src="https://user-images.githubusercontent.com/122277/73753672-c910f700-4741-11ea-8701-2f7a5dd8469d.png">

**Desktop (please complete the following information):**
 - OS: Tested only in MacOS 
 - Browser: Chrome, Safari and Firefox
 - Version: 10.15.1

**Smartphone (please complete the following information):**
 - Device: Tested only in iPhone6
 - OS: most recent
 - Browser: Chrome and safari

**Additional context**
In the console, I can see the error printed:
`pxtembed.js:158976 Cannot load extension: Bad HTTP status code: 404 at /api/gh/strawbees/pxt-robotic-inventions/v0.0.7/text; message: {"message":"ref response: 404"}`

Uppon inspection, the url `https://makecode.microbit.org/api/gh/strawbees/pxt-robotic-inventions/v0.0.7/text` is indeed broken. However the url `https://makecode.microbit.org/api/gh/strawbees/pxt-robotic-inventions/0.0.7/text` (without a 'v' in the version number), works correctly. So it seems the problem could be related to how that url is genereated.

**Comment by pelikhan** [comment]
Our rendering engine is picky and assume "vMAJOR.MINOR.PATH" formatting of releases. Are you using the github integration in makecode.microbit.org/beta to create your releases?

**Comment by abchatra** [comment]
Yes that is the issue. It needs to be v0.0.7 and not 0.0.7 and the tag should be on master.

**Comment by paulobarcelos** [comment]
@pelikhan I am trying to make a release via MakeCode, but I won't allow me, since the repository is owned by an organisation. Is there any way to change that? Seems rather inconvenient to have fork the project instead of committing directly, since I am already a collaborator.

**Comment by paulobarcelos** [comment]
Did the release manually via git, using 'v' in the tag name and I can confirm it works.

**Comment by pelikhan** [comment]
Use a developer token when you sign in or approve our OAuth app in the organization.
