### ISSUE TITLE
Floating point numbers do not display correctly on hardware (using block editor)

### ISSUE THREAD

**Issue by ShawnHymel** [microsoft/pxt-microbit#2598]
**Describe the bug**
I’m trying to display a floating point value on the micro:bit’s screen. When I use the Show Number block after performing a division operation (e.g. (analog read pin P0) x 3 / 1023 ), the screen scrolls something like 12 decimal places. From my understanding, it is supposed to display only 2 decimal places by default.

The simulator works as expected.

**To Reproduce**
Run the following code on a micro:bit: [https://makecode.microbit.org/_b9i2Yd5YkVqe](https://makecode.microbit.org/_b9i2Yd5YkVqe)

Press B button to view voltage level.

**Expected behavior**
Voltage given with 2 decimal places.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 79.0.3945.130 (Official Build) (64-bit)

**Additional context**
Issue reported in [forum post](https://forum.makecode.com/t/how-to-limit-decimal-places-when-using-show-number-with-a-float/1012), and @mmoskal asked me to tag him here.

**Comment by MKleinSB** [comment]
I think it´s this one: https://github.com/microsoft/pxt-microbit/issues/1781

**Comment by pelikhan** [comment]
Fixed.
