### ISSUE TITLE
Tutorials stored in extension GitHub repos not working

### ISSUE THREAD

**Issue by AlasdairAtKitronik** [microsoft/pxt-microbit#2604]
Been trying to add a tutorial to one of our extension GitHub repos, but actually trying to run it just results in errors.

We just keep getting a message saying to check internet connection (which is fine) or whether the tutorial is valid (it is, tested the actual markdown code in the MakeCode tutorial tool and it worked correctly).

Followed the instructions on this page for where to store the file:
https://makecode.com/writing-docs/user-tutorials 

Then formed the tutorial link from the following template on that page:
'https://[editor url]/#tutorial:[GitHub repository url]/[filename]'

This is the GitHub repo:
https://github.com/KitronikLtd/pxt-kitronik-mini-motor

And this is the link to access the tutorial:
https://makecode.microbit.org/#tutorial:https://github.com/KitronikLtd/pxt-kitronik-mini-motor/MiniMotorTutorial

Tried several different forms of the tutorial link, but nothing worked.

**Comment by Jaqster** [comment]
@ganicke - any ideas?

**Comment by pelikhan** [comment]
Looks like a .md is missing in the url — or maybe the feature is not shipped.

**Comment by MKleinSB** [comment]
Try this: https://makecode.microbit.org/#tutorial:https://github.com/KitronikLtd/pxt-kitronik-mini-motor

**Comment by ganicke** [comment]
The logic for full spec page references might not be working correctly (as documented in at https://makecode.com/writing-docs/user-tutorials#multiple-tutorials-per-repository). We'll have to look into it.

**Comment by ganicke** [comment]
**UPDATE**: This works in `beta`.

https://makecode.microbit.org/beta#tutorial:https://github.com/KitronikLtd/pxt-kitronik-mini-motor/MiniMotorTutorial

**Comment by AlasdairAtKitronik** [comment]
@ganicke Thanks for the info regarding working in beta. Any ideas when this might make it into the current version of MakeCode?

**Comment by ganicke** [comment]
Seems like it should be there already since #5991 is prior to pxt - 5.31.31. @pelikhan?

**Comment by AlasdairAtKitronik** [comment]
A bit of an update on this issue.
The beta link provided by @ganicke does work (as in it opens the Tutorial and doesn't just return an error message), however, when I make changes to the Tutorial, push the changes to GitHub, do a GitHub release and then try and view the Tutorial, none of the changes are there. This is also the case with other Tutorials I am working on.

The first time this occured, I tried viewing the Tutorial in another browser that had never opened the Tutorial before and I could see my changes. But every time I made a change to the Tutorial, I had to use a new broswer that had never opened the Tutorial before. I have run of browsers, as has most of the rest of the office.

I have cleared cookies, cache, application cache, browser history, closed all tabs and restarted browsers, restarted my computer - none of this helps. The changes I initially made to a Tutorial took about a week to appear (that is, being able to view the Tutorial as intended a week previously in Chrome, my normal browser). 

I do not understand what the issue is. Is there something I'm doing wrong with how I upload/push/update etc? Or is there an issue at the MakeCode end? In a conversation with @pelikhan , he said something about caching the repo in the cloud. Is this something that is only updated once a week or so? Can we make it update more regularly? 

Would really appreciate some support with this as I have reached the end of my knowledge.

**Comment by DaveAtKitronik** [comment]
@jaustin @pelikhan @Jaqster  This is stopping us shipping a product, and if we cant resolve it soon we will have to include dead tree manuals. Once we do that there will be no reason for us to revisit the tutorials, or use the online tools in the future.  We would like to use online as a better user experience, but the opaqueness of the issue means we don't know how to fix this.  Help!

**Comment by abchatra** [comment]
>> I do not understand what the issue is. Is there something I'm doing wrong with how I upload/push/update etc? Or is there an issue at the MakeCode end? In a conversation with @pelikhan , he said something about caching the repo in the cloud. Is this something that is only updated once a week or so? Can we make it update more regularly?

We have CDN cache which stays alive for 1 full day. The way to trick the cache is to change the time on your computer to 2 days ahead or 2 days behind. Also always try the tutorial in inprivate (in congnito) mode of the browser. 

We are working on making it easy with a flag.

**Comment by abchatra** [comment]
>> Seems like it should be there already since microsoft/pxt#5991 is prior to pxt - 5.31.31. @pelikhan?

Multiple docs per repo support will be out for the next release around June 2020.

**Comment by abchatra** [comment]
I am keeping this bug alive for this work:

Add a nocache flag to the URL which disables all caching
- indexdb caching
- CDN caching
- Redis cache

**Comment by ganicke** [comment]
They gave up on the non-readme tutorial: https://github.com/KitronikLtd/pxt-kitronik-mini-motor/commit/dd160beb4e8a1a94e17aa3dd374c71569c8805b8

**Comment by pelikhan** [comment]
Fair enough...

**Comment by AlasdairAtKitronik** [comment]
Not given up, just had to remove them from that repo as we wanted to move the product forward and counldn't leave non functioning things there.
I've been working on Tutorials for one of our other products, see link:
https://github.com/AlasdairAtKitronik/pxt-kitronik-halohd
I've been able to view most of my changes by chaning my PC time to 2 days in the future, but this still only works in beta.

**Comment by AlasdairAtKitronik** [comment]
The two Tutorial links:
https://makecode.microbit.org/beta/#tutorial:https://github.com/AlasdairAtKitronik/pxt-kitronik-halohd/BasicClockTutorial

https://makecode.microbit.org/beta/#tutorial:https://github.com/AlasdairAtKitronik/pxt-kitronik-halohd/ClockAdjustmentTutorial

**Comment by pelikhan** [comment]
We are preparing a patch to support this scenario. you can test it at https://makecode.microbit.org/stable

https://makecode.microbit.org/beta/#tutorial:https://github.com/AlasdairAtKitronik/pxt-kitronik-halohd/BasicClockTutorial

https://makecode.microbit.org/stable/#tutorial:https://github.com/AlasdairAtKitronik/pxt-kitronik-halohd/ClockAdjustmentTutorial
https://makecode.microbit.org/stable/#tutorial:https://github.com/AlasdairAtKitronik/pxt-kitronik-halohd/ClockAdjustmentTutorial

Also in https://makecode.microbit.org/beta, you will find a button in the explorer view to test the tutorial locally without having to publish to github.

**Comment by AlasdairAtKitronik** [comment]
Thanks Peli, the new button is very useful.

**Comment by AlasdairAtKitronik** [comment]
Didn't feel starting a new issue was the right thing to do, it feels like it's under the same umbrella as this one.

I've been trying to add a GIF into my tutorial, and I've uploaded it to the GitHub repo (https://github.com/AlasdairAtKitronik/pxt-kitronik-halohd/blob/master/static/change_variable_drop_down.gif).

I added this line to my tutorial, based on how other GIFs are displayed in other tutorials:
![Animation that shows how to change variable drop-down](https://github.com/AlasdairAtKitronik/pxt-kitronik-halohd/blob/master/static/change_variable_drop_down.gif)

but it does not work, just displays the alt text.

Uploading my GIF to 'postimage' and linking from there with the following line does work:
![Animation that shows how to change variable drop-down](https://i.postimg.cc/SKD1qCxT/change-variable-drop-down.gif)

It seems a bit strange that I can't use things in the same repo, but can display any old thing I link to from the web.

**Comment by pelikhan** [comment]
I will investigate but, for sure, tutorials in repositories that are not validated will not display images.

**Comment by pelikhan** [comment]
the links to images in GitHub need to be formatted to work. This will not be supported until the big update in June.
You could patch the URLs to use the raw content route from GitHub.

**Comment by pelikhan** [comment]
The links to the files in github are now working on makecode.microbit.org . Thank you for the wait.

**Comment by pelikhan** [comment]
@AlasdairAtKitronik please open a new issue for image. You can upload images under the assets folder, then reference them via their full path in the GitHub Pages web site (https://ORG.github.io/NAME/assets/...)
