### ISSUE TITLE
Beta no longer reloads original when using URL containing "#pub:"

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#2605]
**Describe the bug**
When using a URL containing "#pub:" to load a shared project into the editor, live loads the original contents into a new project each time the URL is used. Beta returns to the same project on each use, even if it has been edited.

**To Reproduce**
1. Go to 'https://makecode.microbit.org/beta#pub:_PCRhJzFe8FVw'
2. Change the number
3. Go to 'https://makecode.microbit.org/beta#pub:_PCRhJzFe8FVw' again
4. See edited project rather than original

**Expected behavior**
Load the original shared contents for the URL.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version:
Live = makecode.microbit.org version:  2.0.10
Beta = makecode.microbit.org version:  2.1.47

**Comment by martinwork** [comment]
I think the problem is that the "pub" case in handleHash has been changed to use loadHeaderBySharedIdAsync. And the changed behaviour may be because it only tests `(h => h.pubId == id)`

The "pub" case in handleHash used to call loadHeaderBySharedId, which used to test `(h.pubCurrent && h.pubId == id)`. That test was removed by https://github.com/microsoft/pxt/pull/5535 so it always calls installByIdAsync. I'm pretty sure it used to work before that change, as far as this issue goes, and continued to work after the change. I agree with the reason for the change. I would expect it to always load a new project.

Related: https://github.com/microsoft/pxt-microbit/issues/1991

**Comment by martinwork** [comment]
Oh... It looks like loadHeaderBySharedIdAsync is just loadHeaderBySharedId renamed, with the old-file behaviour added back in.

I can only see it being called for "pub" URLs and for the Import URL dialogue, so it doesn't seem to need to show the old file at all.

**Comment by jwunderl** [comment]
@martinwork thanks for taking a look at this / noticing that the previous fix got changed, should be fixed in beta with one of the next few bumps :)

**Comment by martinwork** [comment]
Thanks for changing it quickly. I noticed it while testing the iOS micro:bit app beta, which uses this for opening its samples.
