### ISSUE TITLE
Using expandableArguments has error with formatting with variable as any

### ISSUE THREAD

**Issue by PhilAtKitronik** [microsoft/pxt-microbit#2606]
**Describe the bug**
Currently been developing some blocks for microbit makecode [https://github.com/KitronikLtd/pxt-kitronik-data-logger] The issue comes when using the add data block.  The block uses type any for inputting.  
However, when adding a new variable onto the end of the block it does not render the input area within the block.  It does generate a thin line (which assuming is one of the blocks), however

**To Reproduce**
1. Go to https://github.com/KitronikLtd/pxt-kitronik-data-logger add the block as an extension to the code.
2. click on add button on the data entry block.  No area appears.
3. Right mouse click, and format code.  One thin line (assuming is an input) appears.
4 Add another variable on the block and format code. Two extra thin lines appear.
5 If minus is pressed lines one extra is added

.

**Expected behavior**
Expected behaviour of the block is to add a grayed out input area into the block when a new variable is added.

**Screenshots**
![step 2](https://user-images.githubusercontent.com/37149430/74155153-f2cb9180-4c0b-11ea-829d-cdedb3297af6.PNG)

![step 3](https://user-images.githubusercontent.com/37149430/74155162-f8c17280-4c0b-11ea-913d-bf105de559e8.PNG)

![step 4](https://user-images.githubusercontent.com/37149430/74155170-fb23cc80-4c0b-11ea-90b4-0a87cc064a0f.PNG)

![step 5](https://user-images.githubusercontent.com/37149430/74155180-ff4fea00-4c0b-11ea-8ee6-c8e81d9bffed.PNG)

**Desktop (please complete the following information):**
 Using Windows 10 website editor
Also on the desktop windows 10 app

**Additional context**

**Comment by abchatra** [comment]
I can't reproduce this. Extension blocks seems to be broken and not written correctly.
![image](https://user-images.githubusercontent.com/6107272/77237523-3bb92300-6b86-11ea-9d7a-ea8567e70437.png)
