### ISSUE TITLE
Add more Science Experiments video cards

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2607]
Hi Galen,
We've got a few more Science Experiment videos.  Can you add them as cards to the Home Page?
[ ]  EMG Sensor  https://youtu.be/vxlPQZIwYRc  
![Science Experiments 05 EMG Sensor](https://user-images.githubusercontent.com/22108954/74199489-29f46f80-4c19-11ea-9bcf-52c40b8ecdf6.png)
[ ]  Egg Drop  https://youtu.be/tnDJFdC3Nd4  
![Science Experiments 06 Egg Drop](https://user-images.githubusercontent.com/22108954/74199532-4b555b80-4c19-11ea-86d2-3c7ac1341252.png)
[ ]  Battery Tester  https://youtu.be/gdlc34nhjK4  
![Science Experiments 07 Battery Tester](https://user-images.githubusercontent.com/22108954/74199592-72139200-4c19-11ea-97eb-e478a57b1786.png)
[ ]  Rocket Acceleration  https://youtu.be/m9ntqxh8FvQ  
![Science Experiments 08 Rocket Acceleration](https://user-images.githubusercontent.com/22108954/74199629-89527f80-4c19-11ea-955e-b7500a3bad90.png)

**Comment by ganicke** [comment]
Yes I can.
