### ISSUE TITLE
custom.ts does not refresh blocks

### ISSUE THREAD

**Issue by CleoQc** [microsoft/pxt-microbit#2610]
**Describe the bug**
custom.ts does not refresh blocks .

**To Reproduce**
start with a new project
switch to javascript and create a new custom.ts
Remove content of custom.ts and add a new block.
I added:
```
namespace custom {
    //% blockId=smile_wink block="smile and wink" blockGap=8
    export function smile_wink() {
            basic.showIcon(IconNames.Happy, 1000)
            basic.showLeds(`
. . . . .
. # . . .
. . . . .
# . . . #
. # # # .
`)
            basic.showIcon(IconNames.Happy)
    }
}
```

The new block never shows in the editor, until you save the project and reload it. 

**Expected behavior**
The blocks used to be updated fairly fast based on the changed definitions. 

**Screenshots**
these blocks still show even after deleting their definitions from custom.ts
![image](https://user-images.githubusercontent.com/4965628/74560220-16f0e080-4f34-11ea-9268-01d043280b12.png)

**Desktop (please complete the following information):**
Windows 10, Firefox

**Comment by microbit-mark** [comment]
This does not seem to reproduce in the beta editor makecode.microbit.org/beta

**Comment by abchatra** [comment]
Fixed in /beta
