### ISSUE TITLE
May I do how to do it?

### ISSUE THREAD

**Issue by crouse12** [microsoft/pxt-microbit#2612]
I try to pack pxt-blockly by using Electron.
However, the blocks disappear if I do it.
May I know how to pack it?
Since pxt-blockly cannot put any issue, I ask my question here.
I just want to know how to do it.

**Comment by abchatra** [comment]
We are unware how to do it. We haven't tried do it till now. What is the use case?

**Comment by crouse12** [comment]
Scratch use Electron to make offline Scratch 3.0.
I try to use pxt-blockly to control arduino esp32 etc.
I pack it by pyQt5 successdully.
pyQt5 is not good choice, so I try to pack it by Election.
 However, I cannot do it by Electron.
Thank for your response.
