### ISSUE TITLE
Feature: Truncate to n decimal places

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2613]
> micro:bit support 27779

**Is your feature request related to a problem? Please describe.**
Problem is when I show a fractional number on the LED screen, numbers are very long e.g. 25.12648306847334 which takes a long time to show and the kids I teach struggle to follow. 

**Describe the solution you'd like**
I would like to set a limit on the number of digits after the decimal points there are in a variable (preferably to 1 or 2). 

**Describe alternatives you've considered**
I have tried to multiply the variable by 10, truncate then divide by 10 but I just end up with the same long number e.g. 25.1000000000000. Clearly I could just round but that would lose the decimal which I need to keep.

Is there a way to limit this to 1 or 2 digital points (e.g. 25.1 or 25.12)?

**Comment by martinwork** [comment]
showNumber was changed to round to 2 decimal places, but converting the rounded number to text didn't always work. In beta, the conversion to text seems to have been fixed.

let v = 25.12648306847334
let tv = convertToText(v)
let r2 = Math.round(v * 100) / 100
let tr = convertToText(r2)
basic.showNumber(v)
basic.showString(tr)
basic.showString(tv)

**Comment by microbit-mark** [comment]
Yes, this works in beta so assuming it will be in the next release @abchatra?
