### ISSUE TITLE
Not all Extensions from an organisation are displayed when searching that organisation

### ISSUE THREAD

**Issue by AlasdairAtKitronik** [microsoft/pxt-microbit#2615]
When searching 'Kitronik' in the Extensions search, some of the Extensions are always missing (not always the same ones). I understand the current process just returns the top 'N' results, but as there is no way for users who aren't aware of this to know there are other Extensions, could this 'N' be increased?

**Comment by AlasdairAtKitronik** [comment]
I also get different numbers of Extensions displaying in different browsers.
Chrome (14 live approved):
![image](https://user-images.githubusercontent.com/36475405/74947014-19e74780-53f2-11ea-811b-d709140f874d.png)
Vivaldi (18 live approved - this is the full number):
![image](https://user-images.githubusercontent.com/36475405/74947081-3be0ca00-53f2-11ea-9a7e-c9feafed9c82.png)
Opera (14 live approved):
![image](https://user-images.githubusercontent.com/36475405/74947167-616dd380-53f2-11ea-888a-85aa23cb7912.png)
Edge (18 live approved - this is the full number):
![image](https://user-images.githubusercontent.com/36475405/74947258-85c9b000-53f2-11ea-8d80-a0baf47832f0.png)
Firefox (18 live approved - this is the full number):
![image](https://user-images.githubusercontent.com/36475405/74947453-caede200-53f2-11ea-9256-f0051a2baa81.png)

**Comment by riknoll** [comment]
Looks like this happens if you are signed into github in the browser

**Comment by AlasdairAtKitronik** [comment]
I'm currently unable to process emails and don't know how long this will be the situation. I will obviously get back to you as soon as is possible, which is likely to be when restrictions to tackle COVID19 are lifted by the UK government. In the meantime Kitronik is currently still open, but running on a skeleton crew. Thanks for bearing with us during this difficult time.

**Comment by pelikhan** [comment]
Ohhhh there might be a code path that goes through GitHub directly. We should remove that.

**Comment by riknoll** [comment]
Yeah, there is. Do you know what the reason is?

**Comment by pelikhan** [comment]
Probably trying to offload compute from our cloud. Not really necessary so let’s stay with a single code path.
I also change how we loaded tutorials to always try our cloud first.
