### ISSUE TITLE
serial.WriteBuffer outputting spurious extra data via UART

### ISSUE THREAD

**Issue by whaleygeek** [microsoft/pxt-microbit#2618]
**Describe the bug**
serial.writeBuffer of 1 byte, sends the byte and then sends an ASCII representation of that byte

**To Reproduce**
let send = false
let value = 0
basic.showIcon(IconNames.Heart)
serial.redirect(
SerialPin.P0,
SerialPin.P1,
BaudRate.BaudRate9600
)
basic.forever(function () {
    if (input.buttonIsPressed(Button.A)) {
        value += 10
        value = Math.min(value, 255)
        send = true
    }
    if (input.buttonIsPressed(Button.B)) {
        value += -10
        value = Math.max(value, 0)
        send = true
    }
    if (send) {
        let buffer = control.createBuffer(1)
buffer.setNumber(NumberFormat.Int8LE, 0, value)
serial.writeBuffer(buffer)
        led.plotBarGraph(
        value,
        255
        )
        send = false
    }
})

**Expected behaviour**
Only a single binary byte should be sent

**Screenshots**

![Screen Shot 2020-02-22 at 19 35 45](https://user-images.githubusercontent.com/4086785/75098151-9c1a6c00-55aa-11ea-95bf-f2ae389b02f2.png)

![Screen Shot 2020-02-22 at 19 36 13](https://user-images.githubusercontent.com/4086785/75098155-a2a8e380-55aa-11ea-971b-d0249bafb6ca.png)

**Comment by whaleygeek** [comment]
More data. The phantom ASCII version comes out exactly 6ms after the desired data. I suspect that's one fiber tick later?
![Screen Shot 2020-02-22 at 19 48 18](https://user-images.githubusercontent.com/4086785/75098316-6b3b3680-55ac-11ea-9b46-d256ad250a63.png)

**Comment by whaleygeek** [comment]
Also, I added a basic.showNumber(buffer.length) after the writeBuffer, and it always displays 1.

**Comment by pelikhan** [comment]
plotBarGraph also sends the number via serial.

**Comment by whaleygeek** [comment]
Ok, erm, thaaanks, I think?! Is that by design? Why would it need to do that?

Looks like an example of a library being too helpful!

Can we put a note in both the serial.write/writeBuffer docs AND in the plotBarGraph docs to say that it does this? It is definitely non obvious and unexpected behaviour! I checked both and there is no mention of this extra helpful behaviour, so how would anyone know that it is there?

Thanks!

**Comment by abchatra** [comment]
@ganicke Can we add this information to the plotBarGraph documentation https://makecode.microbit.org/reference/led/plot-bar-graph?

`plotBarGraph  API also sends the values via serial `

**Comment by abchatra** [comment]
Updated documentation.
