### ISSUE TITLE
Feature: Show write values on Pins in simulator

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2620]
> microbit support 27790

**Is your feature request related to a problem? Please describe.**
Currently setting `analog pin write` to any number results in the number 1 shown next to the pin in the simulator. This is presumably to show that the pin is active, but it is confusing for users as it's not the same value as the one being sent.

<img width="1383" alt="Screenshot 2020-02-25 at 13 45 27" src="https://user-images.githubusercontent.com/31242877/75252698-17f7fc80-57d5-11ea-9112-a6207621511e.png">

**Describe the solution you'd like**
When using `analog pin write`, show the value on the pin as currently happens with `ananlog pin read`

<img width="1094" alt="Screenshot 2020-02-25 at 13 49 46" src="https://user-images.githubusercontent.com/31242877/75253059-c13ef280-57d5-11ea-9806-48fca559eb87.png">

**Comment by microbit-mark** [comment]
Just circling back on this one. Is this possible to implement? @abchatra @pelikhan ?

**Comment by pelikhan** [comment]
Yes I will fix this.

**Comment by pelikhan** [comment]
Fixed in beta.
