### ISSUE TITLE
Simulator inconsistency in showing servos.  

### ISSUE THREAD

**Issue by DaveAtKitronik** [microsoft/pxt-microbit#2622]
Simulator inconsistency in showing servos.  

The following code has 2 blocks which wrap the pins.servo block. The first block (myservoTurn(…)) does not show a servo image in the simulator, the second block (my2ndservoTurn(…)) shows 2.
We were investigating why multiple servos turned up when only 1 was required and came across this when re writing the code to attempt to only make 1 call to pins,servoWritePin(…) and thus show only a single simulator object.

**To Reproduce**

//% weight=100 color=#0fbc11 icon=""
namespace custom {
    // Enum containing the different Servo Pin output options
    export enum MyServoPins {
        //% block="Pin 0"
        pin0,
        //% block="Pin 8"
        pin8
    }

    /**
     * Sets servo to a specific angle (for 180 deg servos) or rotation speed (360 deg servos)
     * @param servoPin the output pin to which the servo is connected
     * @param angle angle/speed for servo to turn to/at eg: 90
     */
    //% blockId=Mykitronik_mini_motor_servo_onasdas
    //% block="turn servo on %servoPin|to %angle"
    //% angle.min=0 angle.max=180

    export function myservoTurn(servoPin: MyServoPins, angle: number): void {
        let myPin = 0
        if (servoPin == MyServoPins.pin0) {
            myPin = AnalogPin.P0
        }
        else if (servoPin == MyServoPins.pin8) {
            myPin = AnalogPin.P8
        }
        pins.servoWritePin(myPin, angle)
    }

    /**
       * Sets servo to a specific angle (for 180 deg servos) or rotation speed (360 deg servos)
       * @param servoPin the output pin to which the servo is connected
       * @param angle angle/speed for servo to turn to/at eg: 90
       */
    //% blockId=My2ndkitronik_mini_motor_servo_onasdas
    //% block="turn servo on %servoPin|to %angle"
    //% angle.min=0 angle.max=180

    export function my2ndservoTurn(servoPin: MyServoPins, angle: number): void {
        let myPin = 0
        if (servoPin == MyServoPins.pin0) {
            pins.servoWritePin(AnalogPin.P0, angle)
        }
        else if (servoPin == MyServoPins.pin8) {
            pins.servoWritePin(AnalogPin.P8, angle)
        }
        pins.servoWritePin(myPin, angle)
    }

}

**Expected behavior**
myservoTurn(…) should show 1 simulated servo. 

**Screenshots**

![image](https://user-images.githubusercontent.com/25896029/75356029-47773980-58a7-11ea-802a-8f8e617e8b2a.png)

![image](https://user-images.githubusercontent.com/25896029/75356099-5d84fa00-58a7-11ea-9538-1fc2218c6e91.png)

**Desktop (please complete the following information):**
windows 10, appears to be Browser agnostic

Project here: https://makecode.microbit.org/_Ci08jfihJeou

**Comment by pelikhan** [comment]
The usage of servos is determine statically and not at run time. So the approach of determining pins is incompatible with our runtime.
