### ISSUE TITLE
The block is too small to see clearly on Complex Conditions

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2627]
**Describe the bug**
The block is too small to see clearly on Complex Conditions

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Blocks To JavaScipt-->Complex Conditions-->Show Instructions

**Expect behavior**
The block is clear to see

**Actual behavior**
The block is too small to see clearly

![Complex Conditions](https://user-images.githubusercontent.com/59192069/75609844-ecfc0880-5b46-11ea-9085-4f47251ae8e8.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.2.4
3.Microsoft MakeCode version: 5.35.2

**Comment by Sheila111** [comment]
Rotary Dial Radio also has the same issue
![image](https://user-images.githubusercontent.com/59192069/76406428-aa4af380-63c4-11ea-8040-166f45395a44.png)

**Comment by abchatra** [comment]
There is workaround with browser zoom. Won't fix
