### ISSUE TITLE
The result isn't complete on Mood Radio

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2628]
**Describe the bug**
The result isn't complete

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Radio Games-->Mood Radio-->Show Instructions
3.Run it

**Expect behavior**
This game can run completely
![1](https://user-images.githubusercontent.com/59192069/75609977-34cf5f80-5b48-11ea-979c-c1e5dbdda37b.gif)

**Actual behavior**
The result isn't complete. After perssing button A, it should show the other micro:bit
![2](https://user-images.githubusercontent.com/59192069/75609979-38fb7d00-5b48-11ea-817a-6e1d072198e8.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.2.4
3.Microsoft MakeCode version: 5.35.2

**Comment by pelikhan** [comment]
This is a known issue, the simulator in docs does not support multiple microbits.

**Comment by abchatra** [comment]
Docs don't support multiple microbits.
