### ISSUE TITLE
Block editor changed after converting Python editor to Block

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2632]
**Describe the bug**
Block editor changed after converting Python editor to Block

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Click New Project
3.Drag **show icon** block to **forever**
4.Convert to Python editor
5.Add some code
6.Convert to Block editor 

**Expect behavior**
Block editor shouldn't change

**Actual behavior**
Block editor changed. Previous block changed to python code
![python-convert](https://user-images.githubusercontent.com/59192069/75867982-6135f500-5e42-11ea-9357-ee8a4515e377.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.2.6
3.Microsoft MakeCode version: 5.35.6

**Comment by pelikhan** [comment]
The issue is that the python decompiler adds the optinal argument in showIcon
```    
basic.show_icon(IconNames.HEART)
```
becomes
```
basic.showIcon(IconNames.Heart, 600)
```
