### ISSUE TITLE
Code not indented should prompt error

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2633]
**Describe the bug**
Code not indented should prompt error

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Click New Project
3.Convert to Python editor

**Expect behavior**
Code not indented should prompt error and compile fail

**Actual behavior**
It desn't prompt error.And it seems compile is successful but the result isn't complete.
If code indented, the result is complete.
![python-indent](https://user-images.githubusercontent.com/59192069/75885457-8128e100-5e61-11ea-9162-490c4640e751.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.2.6
3.Microsoft MakeCode version: 5.35.6

**Comment by riknoll** [comment]
That's valid Python code. You don't need to indent properly in multi-line strings or within parentheses
