### ISSUE TITLE
Language button exists UI issue

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2635]
**Describe the bug**
**Language** button exists UI issue

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Click Settings

**Expect behavior**
Logo and text should be on the same horizontal line like **Report Abuse** button

**Actual behavior**
**Language** button exists UI issue
![image](https://user-images.githubusercontent.com/59192069/75974543-ef2ce100-5f11-11ea-8d50-132d8e6206da.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.2.9
3.Microsoft MakeCode version: 5.35.10

**Comment by riknoll** [comment]
I think that globe is one of our custom icons (e.g. in `svgicons/`) which probably explains the alignment issue

**Comment by pelikhan** [comment]
Yes it is custom.

**Comment by abchatra** [comment]
Won't fix P3.
