### ISSUE TITLE
offline PXT build doesnt work in edge

### ISSUE THREAD

**Issue by DaveAtKitronik** [microsoft/pxt-microbit#2636]
Developing a new package using the offline PXT build. 
Had issues with not being able to get a new project.
Did a totally clean re install of everything, following the readme in this repo.
Same issue.
Switched default browser form EDGE to Chrome. 
PXT serves as expected.

Microsoft Windows [Version 10.0.18362.657]
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18362

makecode.microbit.org version:  2.2.9
Microsoft MakeCode version:  5.35.10
microbit runtime version:  pxtgc-0

@AlasdairAtKitronik running same version of Edge and 
makecode.microbit.org version:  2.1.33
Microsoft MakeCode version:  5.30.5
microbit runtime version:  pxtgc-0

has a working offline setup.

**Comment by pelikhan** [comment]
2.2.9 is the beta version and probably we'll need to increase the minimum version of Edge. @abchatra currently our docs says Edge 38.0 but with the pouchdb changes; this might not be true anymore.

**Comment by abchatra** [comment]
We decided not to fix old Edge bugs. It should work as expected in the latest edge.
