### ISSUE TITLE
Type inference issue in python with global List

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#2637]
This code:

```python
choices = ["rock", "paper", "scissors"]

x = len(choices)

def next_choice(forward):
    global choices
    x = len(choices)
```

does not convert to JavaScript. The call `len(choices)` has no error outside of the function definition but does have an error inside the function definition

**Comment by abchatra** [comment]
Removing next-release flag. Let me know if you disagree.

**Comment by darzu** [comment]
Hmm, I think this is next-release. Getting the length of an array is pretty basic.

**Comment by darzu** [comment]
That code now gives me this error:
![image](https://user-images.githubusercontent.com/6453828/83782446-a980d100-a644-11ea-95e1-1104e1fdbb71.png)

**Comment by darzu** [comment]
The above code coverts to:
```
let choices = ["rock", "paper", "scissors"]
let x = choices.length
function next_choice(forward: any) {

    let x = choices.length()
}
```

notice the length() call

**Comment by darzu** [comment]
I was unable to find any case where this could be reached from blocks. Since the "global" here actually isn't needed. So I removed next-release
