### ISSUE TITLE
Doubt regarding offline working

### ISSUE THREAD

**Issue by sarthak-g** [microsoft/pxt-microbit#2642]
I want to integrate microbit into one of my project. I just want to know is there a way through which I can work microbit offline?
By offline I mean, it should run without running server (by pxt) locally i.e. I can just click on main html file and it will open in browser.

Any help you can give would be greatly appreciated.

**Comment by pelikhan** [comment]
Use our offline app for this scenario:  https://makecode.microbit.org/offline

**Comment by sarthak-g** [comment]
@pelikhan thanks for the reply.
Offline app have to be installed but I want to integrate into my existing web project.

**Comment by pelikhan** [comment]
There is no downloadable html file. However the editor is cached in the browser once loaded.

**Comment by sarthak-g** [comment]
So there is no way to integrate in web project without running server (pxt serve) ?

**Comment by pelikhan** [comment]
Please follow up with your request t support.microbit.org .

**Comment by sarthak-g** [comment]
Okay, thanks
