### ISSUE TITLE
Create a flipgrid for CS intro course + link each topic

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2645]
Create a flipgrid and link topics in CS intro course.

**Comment by ganicke** [comment]
Flipcode: **[csintromicrobit](https://flipgrid.com/csintromicrobit)**

**Comment by microbit-mark** [comment]
@ganicke @pelikhan  Spelling mistake on the first page: Desing Thinking > Design Thinking

![Screenshot 2020-03-10 at 08 12 56](https://user-images.githubusercontent.com/31242877/76292408-10415900-62a7-11ea-95ba-ed8cc9de0510.png)

**Comment by ganicke** [comment]
Oh, well that's embearasing.
