### ISSUE TITLE
accessibility menu does not show up in narrator scan mode in new edge

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2652]
**Describe the bug**

When using narrator in new microsoft edge, the hidden tab accessibility menu doesn't show up (visibly, the contents are read properly). It does show up when tabbing through

the focus box is placed a few hundred pixels above the browser when it does end up showing up, so it looks like it's not being repositioned?

**To Reproduce**
1. open browser (new edge), and go to https://makecode.microbit.org/beta
2. ctrl+windows+enter to enter narrator mode
3. caps lock + space to enter scan mode
4. use up / down arrow keys to move through accessibility menu; contents are read but not shown on screen

**Expected behavior**

should show up properly 

**Desktop (please complete the following information):**

 - OS: windows 10
 - Browser: edge Version 80.0.361.66 (Official build) (64-bit)

**Additional context**

behaves properly on chrome, firefox

**Comment by abchatra** [comment]
Fixed
