### ISSUE TITLE
Spiral missing Turtle Category

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2654]
**Describe the bug**
Spiral missing Turtle Category

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Turtle-->Spiral-->Show instructions

**Expect behavior**
Toolbox should have the Turtle category and  turn right block.
![Turtle](https://user-images.githubusercontent.com/59192069/76622440-76aacd80-656c-11ea-9922-54b154c4fd13.png)

**Actual behavior**
Missing the Turtle category and  turn right block.
![turn-right](https://user-images.githubusercontent.com/59192069/76622422-6eeb2900-656c-11ea-8b51-a3372e92945c.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.2.14
3.Microsoft MakeCode version: 5.35.17

**Comment by pelikhan** [comment]
Looks fixed.

**Comment by Sheila111** [comment]
@pelikhan  still exists
![image](https://user-images.githubusercontent.com/59192069/77997966-e7baf500-7362-11ea-9617-9df781a9c118.png)
