### ISSUE TITLE
There adds reading2 parameter after converting Python editor to Block

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2655]
**Describe the bug**
There adds reading2 parameter after converting Python editor to Block

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Tools-->Analog Pin Tester->Show Instructions
3.Click Python editor
4.Add code
5.Convert Python editor to Block editor

**Expect behavior**
No new parameter after converting Python editor to Block

**Actual behavior**
There adds reading2 parameter after converting Python editor to Block
![reading2](https://user-images.githubusercontent.com/59192069/76624747-d99e6380-6570-11ea-92fc-ce5a425ceb63.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.2.17
3.Microsoft MakeCode version: 5.35.20

**Comment by abchatra** [comment]
This is by design. As scoping rules in javascript differ from python. Can't fix.
