### ISSUE TITLE
Extension README renders html

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2663]
**Describe the bug**
The approved extension https://makecode.microbit.org/pkg/cytrontechnologies/pxt-edubit appears to render html code within the README, despite this not being present in the file.

![image](https://user-images.githubusercontent.com/31242877/76941779-891e6180-68f4-11ea-99d4-c0c7213003e0.png)

**To Reproduce**
1. Go to https://makecode.microbit.org/pkg/cytrontechnologies/pxt-edubit

**Expected behavior**
This should render as per https://github.com/CytronTechnologies/pxt-edubit/blob/master/README.md

**Comment by waiweng83** [comment]
Looks like it's fixed after I added description in the pxt.json file.
