### ISSUE TITLE
On button press behaviour is different on sim/hardware

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2667]
> micro:bit support: 27970

**Describe the bug**
When holding a button, the event does not seem to be triggered on the hardware as in the sim. Is this is a fiber scheduling issue?

**To Reproduce**
 https://makecode.microbit.org/_LK32Mcbsy1bP

![Screenshot 2020-03-19 at 10 26 35](https://user-images.githubusercontent.com/31242877/77057627-24ced100-69cc-11ea-9153-29d94b3bde17.png)

Hold button for 2 seconds then release
 - Behaviour in Sim: LED displays then clears
- Behaviour on hardware: LED does not display. Shorter button press and releases < 1 second are registered

**Expected behavior**
micro:bit should detect button was pressed and queue the image display. Does not seem to reproduce in the DAL

**Comment by pelikhan** [comment]
Looks like you are hitting the "hold" event instead of a click.

**Comment by abchatra** [comment]
This is as designed.
