### ISSUE TITLE
Cookie notification will not close on Android

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2681]
> micro:bit support: 28364

**Describe the bug**
When navigating to the editor on Android, the cookie notification does not disappear on first use

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31242877/77403563-48b55c80-6da8-11ea-884f-6ccb861d82cb.png)

**Smartphone (please complete the following information):**
Samsung Galaxy S7 SM-G930F Android 8.0.0 Firefox 68.6.0 

**Additional context**
Cannot recreate this in Android 9, Chrome 80 on Motog6

**Comment by abchatra** [comment]
@microbit-mark we need additional information on this. Bug report says it is on Chrome 80 on Android 9.  But it also says:

_Cannot recreate this in Android 9, Chrome 80 on Motog6_ 

Where does it repro?

**Comment by microbit-mark** [comment]
Hi @abchatra Further feedback from the user... this is actually in Samsung Galaxy S7 SM-G930F Android 8.0.0 Firefox 68.6.0

**Comment by abchatra** [comment]
We have no more cookie notificiation.
