### ISSUE TITLE
losing parameters when duplicating a function

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-microbit#2692]
**Describe the bug**
When duplicating a function with parameters the parameters are killed in the new function
(In Makecode Beta)

![Unbenannt](https://user-images.githubusercontent.com/37311672/77819159-f2faf000-70d8-11ea-9b6f-9189d176c6ec.png)

**Comment by MKleinSB** [comment]
Seemes to be fixed now

![Unbenannt](https://user-images.githubusercontent.com/37311672/77858251-94319580-7202-11ea-84d1-730617da8660.png)

**Comment by riknoll** [comment]
Fixed by https://github.com/microsoft/pxt-blockly/pull/274 I believe
