### ISSUE TITLE
Lack of "Play Video" option on edge browser

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2693]
**Describe the bug**
Lack of "Play Video" option on edge browser

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#(edge browser)
2.Navigate to https://makecode.microbit.org/beta#(google browser)

**Expect behavior**
There are two options "Start Tutorial" and "Play Video" when clicking tutorials
![image](https://user-images.githubusercontent.com/59192069/77888126-541ff080-729e-11ea-9b9e-a1a33c0e2557.png)

**Actual behavior**
Lack of "Play Video" option on edge browser
![image](https://user-images.githubusercontent.com/59192069/77888601-17082e00-729f-11ea-84cb-468ce1199c04.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.2.33
3.Microsoft MakeCode version: 5.37.3

**Comment by abchatra** [comment]
This might be a cache issue. Can you retry Sheila111 ?

**Comment by Sheila111** [comment]
@abchatra   I've tried again and the issue still exists on edge browser.
![1](https://user-images.githubusercontent.com/59192069/78619925-390e3b80-78b1-11ea-9f1b-f3332d1f84d1.gif)

**Comment by pelikhan** [comment]
Is this old Edge? Do we care?

**Comment by abchatra** [comment]
Yes old edge. We do care. It is 15% of current usage. 
If it is a corner case then may be we could have ignored. But not showing youtube is main scenario I believe.

**Comment by pelikhan** [comment]
I suspect the logic to test if YouTube is reachable fails on edge for some reason.

**Comment by pelikhan** [comment]
@Sheila111  Is YouTube blocked on your network by any change? We do try to pint youtube before showing the button. Does this happen in other browsers?

**Comment by Sheila111** [comment]
@pelikhan  This issue just happens in edge browser. And I don't do any change.

**Comment by pelikhan** [comment]
I don't have old edge anymore on any of my machines.

**Comment by abchatra** [comment]
@shakao I can repoduce in old edge. Can you help @pelikhan by fixing this? Appreciate your help.

This is what I see 

DOM7009: Unable to decode image at URL: 'https://www.youtube.com/favicon.ico?v=0.2423372717054435&origin=https%3A%2F%2Fmakecode.microbit.org' with MIME: 'image/x-icon'.

**Comment by pelikhan** [comment]
Basically, we try to download the favicon of youtube to test if it is rechable. I have no clue why this is failing for Old Edge... but we could just always assume that YT is reachable in Old Edge and get this solved.

**Comment by abchatra** [comment]
This is all old edge, not just China. I could repro on my old edge.
