### ISSUE TITLE
Edge browser doesn't work when the internet not connected

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2697]
**Describe the bug**
Edge browser doesn't work when the internet not connected

**Steps to reproduce the behavior**
1.Load /beta with internet connected. Try the simulator and a sample program.
2.Disconnect internet and close the browser.
3.Relaunch the browser and navigate to https://makecode.microbit.org/beta
4.See everything is working. 

**Expect behavior**
The sample program I opened before can work when the internet not connected as Google browser and Firefox browser
![google1](https://user-images.githubusercontent.com/59192069/77980525-1670a580-733a-11ea-9603-025dc7cd9be5.gif)

**Actual behavior**
Edge browser doesn't work when the internet not connected
![edge](https://user-images.githubusercontent.com/59192069/77979822-48810800-7338-11ea-8df2-fc531523ae33.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.2.33
3.Microsoft MakeCode version: 5.37.3

**Comment by riknoll** [comment]
I can't repro this. It works for me in Edge 44 (old Edge). It looks like you're loading a safelinks URL in the GIF, that will not work as it needs to hit the safelinks server to resolve the address. Can you retry this test by going to makecode.microbit.org/beta directly?

**Comment by Sheila111** [comment]
@riknoll  It seems that the issue repro when I click microbit/beta link in email directly. And if I paste this link in the address box, the issue can't repro.
![edge-repro](https://user-images.githubusercontent.com/59192069/78202729-ab54d980-74c7-11ea-922a-1e5195cfcdf7.gif)

**Comment by riknoll** [comment]
Great! Thanks for checking on that!
