### ISSUE TITLE
Custom editor needed for image editing

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2702]
Really missing the easy of drawing on blocks. Can we have a custom image editor for text (that supports more than 1 image)? Can we use the pixel editor?
![image](https://user-images.githubusercontent.com/4175913/78045015-42842a80-732a-11ea-8086-3094832f3efd.png)

**Comment by MTKilpatrick** [comment]
I hope you can consider making future enhancements versatile and configurable such that users have many pixel image editing capabilities for Microbit environment?

This issue follows on from the implementation in the 2020 beta release of custom-sized images, which I very much appreciate: https://github.com/microsoft/pxt-microbit/issues/2891

For example, creating an image editor of a user-defined size and with a user-defined list of colours (or monochrome) This would be immensely useful when tailored for use with any number of LCD or LED matrixes attached to a Microbit: whether a monochrome 8x8 LED array, a tri-colour 8x8 LED array, any multiple thereof daisy-chained into a larger display; a 16x9 or 17x7 monochrome array (such as the Pimoroni scroll:bit or the Adafruit display both employing the IS31FL3731 driver IC); devices made by Neopixel etc; or any hi-res LCD screen.

The writing of Extensions and Blocks for use with any display device would benefit from the user being able to construct a block with a field-editor comprising an appropriate number of pixels in a grid and with either a colour-picker or a toggle (for monochrome, as is employed by the standard Microbit 5x5 image editor) fields.

Alternatively, some simplified version of the "sprite editor" in the pxt-arcade environment could be ported to the Microbit world?

It would also be useful to have access to the basic piexl field-editor element as used in the Microbit image editor such that a toggle element other than the standard "sliding on/off toggle element" can be used within blocks where appropriate. This has potential advantages for blocks with a "pixel lit/unlit" custom field, for example.

**Comment by abchatra** [comment]
No plans to address this issue.
