### ISSUE TITLE
auto-complete broken

### ISSUE THREAD

**Issue by mmoskal** [microsoft/pxt-microbit#2707]
**Describe the bug**
I'm in https://makecode.microbit.org/beta

**To Reproduce**
Enter the following program:

```typescript
function fib(num:number) {
if(n)
}
```

The autocomplete at `if(n` doesn't show `num`.

Similarly, it doesn't show `number` as after colon, only `Number`.
<img width="376" alt="Screen Shot 2020-03-31 at 12 35 34" src="https://user-images.githubusercontent.com/10673976/78067686-fc3fc300-734b-11ea-9b3c-a8dacb3dfb06.png">
<img width="475" alt="Screen Shot 2020-03-31 at 12 35 50" src="https://user-images.githubusercontent.com/10673976/78067697-ff3ab380-734b-11ea-8be9-fbb6054a84cb.png">

**Comment by abchatra** [comment]
@darzu  to validate

**Comment by darzu** [comment]
Local variables and parameters are working.

But this isn't:
![2020-05-14 12 18 04](https://user-images.githubusercontent.com/6453828/81976179-0573af00-95dd-11ea-85a7-577cee39e9f5.gif)

related to the issue of intellisense not reseting on space
