### ISSUE TITLE
Conditional generation of config.json content

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#271]
I'd like to be able to create a block which determines some of the content of config.json files, according to the value of the block's properties. As I understand it, currently one static config.json file only is available and always included unchanged in the resultant C/C++ and build process. Can we change this so that the config.json file could have (say) symbols in it that can be substituted with variable data or something along those lines?

To make this more concrete and less abstract;

The microbit-dal now supports Bluetooth Just Works pairing or the original Bluetooth passkey pairing (or not pairing at all) as a config option. At the time of writing, the config selection is made by changing a header file but I just submitted a pull request which exposes this setting as a config.json property. I'd like to create a pairing mode block that lets the user decide which type of pairing, including no pairing at all, they want their hex file to require. We could perhaps default to Just Works pairing.

See https://github.com/lancaster-university/microbit-dal/pull/223 

Thanks

**Comment by abchatra** [comment]
Please move this issue to Microsoft/pxt repo which is going be the central repo for all the microbit\pxt issues going forward.

**Comment by abchatra** [comment]
Ported to https://github.com/Microsoft/pxt/issues/544
