### ISSUE TITLE
Homescreen icons are wrong color

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#2711]
**Describe the bug**
JS/Blocks/Python icon on new projects is not purple (old Edge)
![image](https://user-images.githubusercontent.com/34112083/78079768-ad9d2380-7361-11ea-8616-efffed77dd2d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge

**Comment by abchatra** [comment]
I would say won't fix old edge browser compat P2 bugs.
