### ISSUE TITLE
No image on 3rd party extensions. 

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#2715]
**To Reproduce**
1. Go to 'Blocks'
2. Click on 'Advanced->extensions'

No image on 3rd party extensions.

**Screenshots**
![image](https://user-images.githubusercontent.com/6107272/78080506-3cf70680-7363-11ea-9944-1d4454123df1.png)

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Browser: New Edge

**Comment by jwunderl** [comment]
not just no image, they're showing up as unapproved pkgs -- they have the `not endorsed by microsoft` footer. From that it looks like anything besides the top repos wouldn't be easily searchable either. Will figure this out~
