### ISSUE TITLE
Video link should pop a tab

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2717]
Not a regression, but in our Tutorials when we have links to videos, we should pop them out in a new tab or window.
![image](https://user-images.githubusercontent.com/22108954/78080703-9cedad00-7363-11ea-89cf-7faf46e704ec.png)

**Comment by pelikhan** [comment]
This is not a content issue but a rendering issue which needs to be fixed in our markdown render engine.

**Comment by pelikhan** [comment]
Fixed
