### ISSUE TITLE
monaco toolbox is selectable

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2718]
**Describe the bug**

can drag and highlight / select monaco toolbox

**To Reproduce**
1. Go to javascript / python editor
2. click outside toolbox buttons and drag

**Expected behavior**

toolbox shouldn't be selectable

**Screenshots**

![2020-03-31 15 26 15](https://user-images.githubusercontent.com/5615930/78081030-606e8100-7364-11ea-82e3-768bbf112238.gif)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser safari

**Additional context**

**Comment by abchatra** [comment]
I think this is browser specific to Safari.

**Comment by shakao** [comment]
i can repro in old Edge where it's a regression from live so i've put out a fix for that. i don't have access to safari and @jwunderl reports it's not a regression there so i will close this for now
