### ISSUE TITLE
monaco toolbox bounce applies to all advanced categories when opened

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2720]
**Describe the bug**

when you click advanced, all the categories bounce out at the same time

**To Reproduce**
1. Go to go to js / py editor
2. click advanced in toolbox

**Expected behavior**

either there shouldn't be a bounce when opening advanced, or they should do the trickling bounce / bounce one at a time like it does when opening the editor

**Screenshots**

(same gif as selectable issue)

![2020-03-31 15 26 15](https://user-images.githubusercontent.com/5615930/78081153-b8a58300-7364-11ea-94af-cfa063255059.gif)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser safari

**Additional context**

**Comment by shakao** [comment]
animation should also not re-run when entering/exiting fullscreen mode
