### ISSUE TITLE
Blockly connectors

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2721]
Hey, can we squeeze this feature in this release?
It's the Rudolph nose connector for embedded blocks. 
Sam has an implementation for it...

**Comment by abchatra** [comment]
Is it in the shipped blockly which we are using?

**Comment by abchatra** [comment]
@shakao

**Comment by abchatra** [comment]
--- Mail from blockly team
Hey all, 

As promised at the meeting, here's how you would go about adding a drag connection indicator to output connections. 

1. Add a new method to the path object (eg: setConnectionIndicator). 
2. When positioning the output connection in the renderer (ie: in drawLeftDynamicConnection_ or positionOutputConnection_), pass the path object the coordinates of the output connection by calling the above setConnectionIndicator.
3. Use these coordinates to set the coordinates of the output connection indicator svg.
4. Add some css to only show the connection indicator when dragging.

Keep in mind there's a few ways to go about this, so feel free to tinker and adjust as needed. Here's a change showing how I went about it:
https://github.com/google/blockly/compare/develop...samelhusseini:connection_indicator_svg

and a gif:
 
![image](https://user-images.githubusercontent.com/6107272/78710284-f016b100-78c9-11ea-98e6-bb3c6df1a5dc.png)

Cheers,
Sam
