### ISSUE TITLE
Comments getting lost roundtripping between Blocks and Python

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2723]
Add comments in Blocks or Python (workspace and block level). Switching back and forth will delete them.

**Comment by riknoll** [comment]
I cannot reproduce this. Do you have an example project I could use?

**Comment by Jaqster** [comment]
Try this: https://makecode.microbit.org/_ccRbvcUHD9ob and just toggle back and forth between Blocks and Python a bunch of times.
