### ISSUE TITLE
Collapsed blocks show text of first block

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2726]
Collapsed blocks show the text of the first block - 
![image](https://user-images.githubusercontent.com/22108954/78082190-3f5b5f80-7367-11ea-856a-a33556b75ff8.png)

**Comment by abchatra** [comment]
I think this is how the blockly works. 
@shakao should we just not show anything here and keep the event name or function name?

**Comment by abchatra** [comment]
Function signature (including params) would be great.
