### ISSUE TITLE
Old Edge - Make a Variable/Function button text offset

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2730]
Old Edge - 
Small nit-picky thing, but the text in the Make a Variable and Make a Function buttons are top aligned instead of center.
![image](https://user-images.githubusercontent.com/22108954/78082550-315a0e80-7368-11ea-9b11-8ac4a7763c3d.png)
![image](https://user-images.githubusercontent.com/22108954/78082580-459e0b80-7368-11ea-8eb0-92570c05479b.png)

**Comment by shakao** [comment]
Fixed by https://github.com/microsoft/pxt/pull/6827
