### ISSUE TITLE
projects view button text is misaligned

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2731]
**Describe the bug**

the text on the last modified button in the projects view is aligned to the top instead of the middle:
<img width="267" alt="Screen Shot 2020-03-31 at 4 03 22 PM" src="https://user-images.githubusercontent.com/5615930/78083067-5dc25a80-7369-11ea-8aa6-eb9cf8b9217a.png"> looks like a regression as it looks fine on live site, so other buttons might also have changed?

**Comment by pelikhan** [comment]
Looks like the .ui.menu comes also with some font-size overrides which expand the button.

https://github.com/microsoft/pxt/commit/0094fba541e188f67a5f1d173e07cdaae2d258a5
