### ISSUE TITLE
home  screen tab accessibility on safari

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2735]
**Describe the bug**

For some reason a handful of elements aren't reachable w/ tabs on safari, even though they are elsewhere (chrome, firefox):

- import button (***)
- microsoft makecode, terms of use and privacy links on footer (notably these ones are links where the other ones are buttons / pop up modals)

no immediately obvious reason why, they have right tab index / etc.

**Comment by jwunderl** [comment]
also top left microbit link and top right microsoft link in header

**Comment by abchatra** [comment]
Won't fix browser compat bug
