### ISSUE TITLE
Intellisense is inconsistent with enum completion

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#2736]
**Describe the bug**
Works for "A" and "AB" but not "B"
![intellisense_b](https://user-images.githubusercontent.com/34112083/78083880-9fec9b80-736b-11ea-88bb-6e4ce64aae65.gif)

**Comment by shakao** [comment]
![intellisense_note](https://user-images.githubusercontent.com/34112083/78084642-9a905080-736d-11ea-90ca-d743a1f1c04a.gif)

does not pop intellisense for "Note" when inside the playTone call

**Comment by Jaqster** [comment]
I'm going to add another one here - following a tutorial to add a Pick Random. When I type in "pickrandom" I don't get the randomRange API in intellisense
![image](https://user-images.githubusercontent.com/22108954/79599940-2fe45200-809b-11ea-8117-4dcba3dd8a05.png)

**Comment by Jaqster** [comment]
Adding more to this issue.  For both JS and PY, I don't get intellisense for Loops or Logic - 
![Intellisense1](https://user-images.githubusercontent.com/22108954/80241952-60873700-8619-11ea-831c-15de57fa9db4.png)
![Intellisense2](https://user-images.githubusercontent.com/22108954/80241960-62e99100-8619-11ea-9e6c-d2e656b77104.png)

**Comment by Jaqster** [comment]
Another one - looks like ShowNumber gets filtered out (or above) the displayed menu of options
![image](https://user-images.githubusercontent.com/22108954/80244706-41d76f00-861e-11ea-9fd8-53131605d474.png)

**Comment by abchatra** [comment]
Still reproduces

**Comment by darzu** [comment]
Specifically with the ".B" option:
![2020-05-14 12 16 14](https://user-images.githubusercontent.com/6453828/81976030-c8a7b800-95dc-11ea-8123-d5936b870618.gif)
