### ISSUE TITLE
Show LEDs pauses in the simulator but not on hardware

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#2739]
This works fine on released micro:bit but fails on beta

**To Reproduce**
1. Open this program in beta: https://makecode.microbit.org/_M0J2qjDWRaJd
2. press A in the sim and watch the animation
3. put it on hardware
4. Press A. Skips to last frame

**Expected behavior**
They should both pause.

**Comment by finneyj** [comment]
thanks @riknoll 

I have a c++ repro, so definitely a bug on my side.

**Comment by finneyj** [comment]
@riknoll @pelikhan @abchatra 

Fixed in https://github.com/lancaster-university/microbit-dal/commit/dd339a7f4c727172b51d1f0ac0d4fe6627fdb056

**Comment by abchatra** [comment]
Thanks @finneyj

**Comment by riknoll** [comment]
Thanks @finneyj!
