### ISSUE TITLE
UART & Bluetooth: Can only write a string to Bluetooth UART 

### ISSUE THREAD

**Issue by jezdean** [Microsoft/pxt-microbit#274]
![2016-10-11 21_53_23-code the micro_bit - blocks _ javascript editor](https://cloud.githubusercontent.com/assets/1617013/19288389/b787ac3a-8ffd-11e6-8668-3d612994e1cb.png)

You can write a number or a string to the serial: serial.writeNumber & serial.writeString

You can only write a string to the Bluetooth UART: bluetooth.uartWrite

**Comment by pelikhan** [comment]
Fixed.
