### ISSUE TITLE
Collapsed "on start show leds" looks odd

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#2743]
![950B6F9D-8425-4EFE-B9AA-70A4F83FCA86_1_201_a](https://user-images.githubusercontent.com/6453828/78084855-2904d200-736e-11ea-9e0b-5ce21553df26.jpeg)

**Comment by pelikhan** [comment]
Dup of https://github.com/microsoft/pxt-microbit/issues/2726
