### ISSUE TITLE
Share icon overlaps toggle in mobile view

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#2746]
**Describe the bug**
![image](https://user-images.githubusercontent.com/34112083/78085012-8a2ca580-736e-11ea-8045-be8cec465e62.png)

**Comment by pelikhan** [comment]
Triple toggle?

**Comment by abchatra** [comment]
In the past we have just removed the logo if there is not enough space.

**Comment by pelikhan** [comment]
it always need to be removed now.
