### ISSUE TITLE
iPad - Rudolph features mysteriously appeared

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#2747]
The last things I did were:
- turn accessibility on and off
- try the debugger

<img width="696" alt="Screen Shot 2020-03-31 at 4 43 18 PM" src="https://user-images.githubusercontent.com/6453828/78085102-d1b33180-736e-11ea-9ef8-570b9f27d9d9.png">

**Comment by shakao** [comment]
oh that's probably the accessibility marker not correctly clearing when you turned accessibility off

**Comment by shakao** [comment]
i don't have access to an ipad, but @darzu could you check if this still repros now that the accessibility has been moved to experiments? seems ok for me in chrome!

**Comment by darzu** [comment]
I can't repro it now, although it was a fluke before as well and I wasn't able to repro it the first time.

**Comment by shakao** [comment]
cool thanks! closing for now, can reopen if it appears again
