### ISSUE TITLE
Call stack exceeded in recursive block functions

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#2758]
If you have a recursive function that only returns a call to itself, you get an exception in the blockly compiler.

<img width="347" alt="Screen Shot 2020-04-01 at 5 42 52 PM" src="https://user-images.githubusercontent.com/13754588/78199371-5ae66900-7440-11ea-8295-168da8a861a7.png">

**Comment by pelikhan** [comment]
Support for tail call to?

________________________________

**Comment by riknoll** [comment]
@pelikhan ???
