### ISSUE TITLE
service worker reports that hex files failed to cache

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2760]
Wait for a update and look at output.
![image](https://user-images.githubusercontent.com/4175913/78213956-e8d64a00-7468-11ea-8943-dc9fb7821704.png)

**Comment by riknoll** [comment]
Those hexfiles were referenced by [the old release manifest](https://github.com/microsoft/pxt/blob/stable5.9/webapp/public/release.manifest#L25) in PXT so I included them in the service worker also. That being said, I couldn't find a target that was actually using them which is why I put error handling around it.

**Comment by riknoll** [comment]
The service worker can't have any 404s or else it won't cache anything. That's why I added them separately and catch the error (wasn't an issue in the old manifest which can 404)

**Comment by pelikhan** [comment]
When the CLI packages the editor, it also may compile one or many hex files files. These files are added to the manifest at build time so that the "download" button works offline.

If you don't cache the .hex file, the editor will fail to download that file offline.

**Comment by riknoll** [comment]
Okay, well I'm caching the same URLs as before

**Comment by pelikhan** [comment]
I'm confused here because we trigger those hex files compilation at build time, so the URLs should not 404.

**Comment by pelikhan** [comment]
Here is the repro:
- open makecode in anonymous mode
- open project
- shut down internet
- add bluetooth extension
- compile -> hex file missing.

**Comment by abchatra** [comment]
But does that mean you can't work in offline? Or just a spurious error?

**Comment by pelikhan** [comment]
You cannot compile to hex because the native hex is not cached.

**Comment by pelikhan** [comment]
We do cache .hex files in the old app manifest

https://makecode.microbit.org/---manifest

![image](https://user-images.githubusercontent.com/4175913/81711534-9e14fe00-9428-11ea-860b-c97d89cf4e1e.png)

**Comment by pelikhan** [comment]
They are still in the beta manifest https://makecode.microbit.org/beta---manifest

**Comment by pelikhan** [comment]
@abchatra we should fix this as it relates to offline support. Either the error message is wrong or our service worker is not properly caching .hex files.

**Comment by riknoll** [comment]
Or, those files weren't being cached by the old manifest either.

**Comment by pelikhan** [comment]
I don’t understand that statement. They are listed in the release—-manifest file so they are being downloaded and cached (maybe they are the wrong hex)

**Comment by riknoll** [comment]
IIRC browsers keep going if files listed in the manifest 404

**Comment by riknoll** [comment]
Oh wait, I think I see what the issue is... There is an @cdnurl@ in the url

**Comment by riknoll** [comment]
Aha! The stupid minifier is getting around my beautiful hack: https://github.com/microsoft/pxt/blob/master/webapp/src/serviceworker.ts#L197
