### ISSUE TITLE
Does not pop Intellisense when typing "Button." on javascript editor

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2761]
**Describe the bug**
Does not pop Intellisense when typing "Button." on javascript editor

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Tutorials-->Smiley Buttons->**JavaScript** Start Tutorial
3.Click step 4
4.Darg an on button pressed from tool box
5.Modify the code

**Expect behavior**
Pop Intellisense when typing "Button." on javascript editor

**Actual behavior**
Does not pop Intellisense when typing "Button." on javascript editor. But it works when typing "Button".
![intellsense](https://user-images.githubusercontent.com/59192069/78216907-7e1b2200-74ed-11ea-9529-39180ea9c58d.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.3
3.Microsoft MakeCode version: 5.37.6

**Comment by abchatra** [comment]
@darzu to validate.

**Comment by darzu** [comment]
Fixed
![2020-05-14 12 13 12](https://user-images.githubusercontent.com/6453828/81975721-51722400-95dc-11ea-9f6f-4822a313dc49.gif)
