### ISSUE TITLE
Lack of the Math category and randomRange block on tutorial Dice

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2762]
**Describe the bug**
Lack of the Math category and randomRange block on tutorial Dice

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Tutorials-->Dice->Python Start Tutorial
3.Click step 4

**Expect behavior**
There should add the **Math** category and **randomRange** block
![2](https://user-images.githubusercontent.com/59192069/78223423-69dd2200-74f9-11ea-96c2-9135e0625333.png)

**Actual behavior**
Lack of the **Math** category and **randomRange** block 
![1](https://user-images.githubusercontent.com/59192069/78223434-6e093f80-74f9-11ea-8ef6-a133b84321fa.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.5
3.Microsoft MakeCode version: 5.37.9
4.JavaScript tutorial has the same issue

**Comment by pelikhan** [comment]
It looks like this symbol does not have a block id.
