### ISSUE TITLE
Hint and instruction are inconsistent

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2763]
**Describe the bug**
Hint and instruction are inconsistent

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Tutorials-->Micro Chat->Python Start Tutorial
3.Click the hint on step 3
4.Click step 6

**Expect behavior**
Hint and instruction should be consistent

**Actual behavior**
Hint
![hint](https://user-images.githubusercontent.com/59192069/78233311-1c1be600-7508-11ea-87cc-72399c6be119.png)
Instruction
![1](https://user-images.githubusercontent.com/59192069/78233356-2b029880-7508-11ea-8462-f8946d242805.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.5
3.Microsoft MakeCode version: 5.37.9
4.JavaScript tutorial has the same issue

**Comment by pelikhan** [comment]
Duplicated for https://github.com/microsoft/pxt-microbit/issues/2751
