### ISSUE TITLE
Decompiler should ignore shadow blocks if the argument is of enum type

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#2766]
This is the underlying problem that caused https://github.com/microsoft/pxt-microbit/issues/2694

If you have a function that takes in an enum argument, it will **always** be a field even if you set a shadow block. The proper fix for this would be to change that behavior in the blocklyloader, but I don't think we can do that without breaking some blocks. Instead the decompiler needs to change to match that buggy behavior.

**Comment by abchatra** [comment]
Won't fix.
