### ISSUE TITLE
Lack of the on logo up block on tutorial Heads Guess

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2767]
**Describe the bug**
Lack of the **on logo up** block on tutorial Heads Guess

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Games-->Heads Guess->Start Tutorial
3.Click step 4

**Actual behavior**
Lack of the **on logo up** block on tutorial Heads Guess
![image](https://user-images.githubusercontent.com/59192069/78317024-be34e000-7593-11ea-8ae7-1bd755215ea1.png)

Additional context
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.6
3.Microsoft MakeCode version: 5.37.10

**Comment by Sheila111** [comment]
Also lack of the **on screen down** block and **on screen up** block. 
![image](https://user-images.githubusercontent.com/59192069/78316938-89288d80-7593-11ea-9cb1-b7fa0117bd97.png)
![image](https://user-images.githubusercontent.com/59192069/78316920-77df8100-7593-11ea-8b68-e95b50da94ee.png)

**Comment by abchatra** [comment]
It is in the drop down. 
![image](https://user-images.githubusercontent.com/6107272/78404331-08798980-75b3-11ea-87f5-28af99e953ff.png)

This is as designed.
