### ISSUE TITLE
Show variables' values while running preview. Could be placed between virtual micro:bit and download button.

### ISSUE THREAD

**Issue by kristianpedersen** [microsoft/pxt-microbit#2769]
When I want to see a variable's value, my current solution is to use the serial functions. 

I find it impractical to switch between serial monitor and code, and I imagine it would be difficult for beginners.

I wish there was a way to display all variables in a program, along with their values. Arrays could have a toggle switch to show either the 10 first or 10 last elements.

Here's a mock-up, inspired by Scratch:

![image](https://user-images.githubusercontent.com/5204369/78325662-8ec4aa00-7578-11ea-8c33-c77e3a3fe878.png)

**Comment by pelikhan** [comment]
In https://makecode.microbit.com/beta you will be able to use a debugger with a variable view. Could you give it a try ? You'll find the "bug" icon under the simulator.

**Comment by abchatra** [comment]
![image](https://user-images.githubusercontent.com/6107272/78404467-59897d80-75b3-11ea-8b0d-ffc983bc0bbb.png)

Implemented as a debugger feature.

**Comment by pelikhan** [comment]
The variable view should be updating while the debugger is running in slow-mo.
