### ISSUE TITLE
Download ... color doesn't match

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#2775]
Can we make ... the same color as the download button?

**Screenshots**
![image](https://user-images.githubusercontent.com/6107272/78407999-eab02280-75ba-11ea-80d3-290d3e28e3a6.png)

**Comment by pelikhan** [comment]
it does not match in arcade.
![image](https://user-images.githubusercontent.com/4175913/78408291-95c0dc00-75bb-11ea-918b-53e4c383c156.png)

**Comment by abchatra** [comment]
It is a darker shade in arcade.   Completely different color in microbit?

**Comment by abchatra** [comment]
@shakao help us out.

**Comment by pelikhan** [comment]
I don't see less variables to change the color of that menu.

**Comment by pelikhan** [comment]
Note that it should not be the same color -- otherwise the user won't know it is a different button.

**Comment by shakao** [comment]
it's the same color as all the buttons by default (blue in microbit), in arcade we manually override the color to be "darker than the download button" https://github.com/microsoft/pxt-arcade/blob/master/theme/style.less#L72 

i can update it to be darker by default, i don't remember exactly why the arcade css ended up  being separate
