### ISSUE TITLE
Exception message not shown in debugger

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2777]
When running in debugger and hitting an unhandled exception, the exception info is not show.
![image](https://user-images.githubusercontent.com/4175913/78450534-13283300-7634-11ea-877b-22784e2b77b4.png)

**Comment by abchatra** [comment]
@riknoll Is this a feature request? We do show the call stack & variables on exception right?

**Comment by pelikhan** [comment]
We don’t show the message.

**Comment by pelikhan** [comment]
![image](https://user-images.githubusercontent.com/4175913/78583641-f33b6f80-77eb-11ea-8438-8ad5041b4e18.png)

**Comment by pelikhan** [comment]
We also show a number of internal variables.
