### ISSUE TITLE
Neopixel simulator doesn't work on microbit beta

### ISSUE THREAD

**Issue by Steph77** [microsoft/pxt-microbit#2780]
**Describe the bug**
Neopixel in simulator doesn't work on makecode for microbit in the beta version

**To Reproduce**
Just test this simple program, it works on stable release but not in the beta : https://makecode.microbit.org/_72pM4bTw91tc

**Expected behavior**
Simulator should light on neopixel LED

**Screenshots**
On classic editor
![classic](https://user-images.githubusercontent.com/11035731/78466924-7df66e80-7707-11ea-9cec-21fa6920b825.gif)

On beta
![beta](https://user-images.githubusercontent.com/11035731/78466922-720aac80-7707-11ea-97ee-5120683a6b87.gif)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Chrome
 - Version 80.0.3987.163 (Build officiel) (64 bits)

**Comment by pelikhan** [comment]
https://github.com/microsoft/pxt-microbit/pull/2782/files

**Comment by pelikhan** [comment]
Fix comming, will also support simulating multiple strips at once.

**Comment by pelikhan** [comment]
![2020-04-06 09 40 56](https://user-images.githubusercontent.com/4175913/78582852-caff4100-77ea-11ea-81ca-c384dd398e08.gif)
