### ISSUE TITLE
Relational operator returns error when comparing two numbers 

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2781]
> micro:bit support: 28654 and 39411

**Describe the bug**
Using the == or != operators returns a cryptic error 'cannot be applied to types' when used to compare two numbers.

![Screenshot 2020-04-06 at 10 16 07](https://user-images.githubusercontent.com/31242877/78543921-495ee180-77f1-11ea-9747-89d9e8035f12.png)

**Expected behavior**
In this example I would expect the statement to return false and display the sad face.

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**Additional context**
This does not error in other languages eg Python

**Comment by abchatra** [comment]
7 !=6 . May be we just need better message or fold the path?

**Comment by riknoll** [comment]
Fold the path?

**Comment by abchatra** [comment]
https://en.wikipedia.org/wiki/Constant_folding

**Comment by microbit-mark** [comment]
Updated as another user has reported this issue in support ticket  39411

**Comment by microbit-Bisi** [comment]
another teacher has reported this. Ticket number:  51139

**Comment by abchatra** [comment]
Change one of the literal type to any and this will not error again.

**Comment by riknoll** [comment]
Fixed by https://github.com/microsoft/pxt/pull/8722
