### ISSUE TITLE
A problem of microbit hardware radio 

### ISSUE THREAD

**Issue by zfm076** [microsoft/pxt-microbit#2786]
**Describe the bug**
Switching on and off the microbit radio can cause jamming

**To Reproduce**
See bug： lancaster-university/microbit-dal#462

**Expected behavior**
In the future I would like to use the computer to send serial commands to control the radio  on and off

**Comment by pelikhan** [comment]
There is no command to turn off radio.

________________________________

**Comment by zfm076** [comment]
> There is no command to turn off radio.
> […](#)
> ________________________________ From: zfm076 <notifications@github.com> Sent: Monday, April 6, 2020 6:53:18 PM To: microsoft/pxt-microbit <pxt-microbit@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [microsoft/pxt-microbit] A problem of microbit hardware radio (#2786) Describe the bug Switching on and off the microbit radio can cause jamming To Reproduce See bug： [lancaster-university/microbit-dal#462](https://github.com/lancaster-university/microbit-dal/issues/462)<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flancaster-university%2Fmicrobit-dal%2Fissues%2F462&data=02%7C01%7Cjhalleux%40microsoft.com%7C71df953f163a4aa38f9508d7da9671eb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637218212001267629&sdata=x0TbuZfJDXY4IWvCy4dJ6TzScQc5gLHvngY5duMnQg8%3D&reserved=0> Expected behavior In the future I would like to use the computer to send serial commands to control the radio on and off — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fpxt-microbit%2Fissues%2F2786&data=02%7C01%7Cjhalleux%40microsoft.com%7C71df953f163a4aa38f9508d7da9671eb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637218212001267629&sdata=KZzWtkWoAPgx0Z%2BB5sFw%2FHS89mVW9KhpE%2BISARqs7Y0%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA73QKIVG3EH67NTWLCG6LTRLKBQ5ANCNFSM4MCXPW4A&data=02%7C01%7Cjhalleux%40microsoft.com%7C71df953f163a4aa38f9508d7da9671eb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637218212001267629&sdata=rcXfs9wb9DxuLaf%2BCj5ZTpEn75POZog%2B0LWmGEk6aec%3D&reserved=0>.

Hi, pelikhan. Turn off radio command is : uBit.radio.disable();

**Comment by abchatra** [comment]
This is not related to MakeCode. Issue tracked in the dal
