### ISSUE TITLE
Documentation can't load

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2789]
**Describe the bug**
Documentation can't load

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Games-->Rock Paper Scissors->Start Tutorial
3.Right click "on shake"-->help
4.Cilck  **on gesture**

**Expect behavior**
Documentation can load 

**Actual behavior**
Documentation can't load and it can load after clicking **Try Again**
![1](https://user-images.githubusercontent.com/59192069/78638697-4b06d300-78df-11ea-85f5-6af8403893a6.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.10
3.Microsoft MakeCode version: 5.37.15

**Comment by shakao** [comment]
duplicate/related to https://github.com/microsoft/pxt-microbit/issues/2724
