### ISSUE TITLE
Block moves when debugging

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2791]
**Describe the bug**
Block moves when debugging

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Games-->Rock Paper Scissors->Start Tutorial
3.Toggle debug mode

**Expect behavior**
Block doesn't move when debugging

Actual behavior
Block moves when debugging
![1](https://user-images.githubusercontent.com/59192069/78642385-3a595b80-78e5-11ea-9d01-0c58f355f559.gif)

Additional context
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.10
3.Microsoft MakeCode version: 5.37.15

**Comment by abchatra** [comment]
@riknoll as designed? We center on the highlighted block as it is necessary to see the block where the current cursor is present right?

**Comment by abchatra** [comment]
As deisgned.
