### ISSUE TITLE
Show expand blocks only when at least one top level block is collapsed

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#2792]
We should only show expand blocks only if there is atleast one block collapsed.
Similarly collapse block if at least one block is expanded. 

**To Reproduce**
1. Go to 'blocks workspace'
2. Right click
3. You see both expand blocks and collapse blocks 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6107272/78709358-5bf81a00-78c8-11ea-82bc-fb3c02fe7455.png)

**Comment by pelikhan** [comment]
Other commands are disabled instead of being hidden. Some are always on, like Format Code. Not consistent.

**Comment by abchatra** [comment]
Disabled is good

**Comment by abchatra** [comment]
@shakao can we just show expand all or collapse all if there is atleast one top level block to do so?
