### ISSUE TITLE
Plot bar graph reloads when switching High Contrast mode

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2793]
**Describe the bug**
Plot bar graph reloads when switching **High Contrast** mode

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/_fVp5dYcEgFR2
2.Click **Show console Simulator**
3.Switch **High Contrast** mode

**Expect behavior**
Switching **High Contrast** mode does not affect plot bar graph

**Actual behavior**
Plot bar graph reloads when switching **High Contrast** mode
![1](https://user-images.githubusercontent.com/59192069/78737718-ca011780-7982-11ea-8ec5-43ed24ef7451.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.10
3.Microsoft MakeCode version: 5.37.15

**Comment by abchatra** [comment]
Won't fix.
