### ISSUE TITLE
Button Is Pressed stuck in the if condition

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2795]
**Describe the bug**
**Button Is Pressed** stuck in the **if** condition

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/_dJ7PwxJPai2T
2.Click button A

**Expect behavior**
Show icon square when clicking button A

**Actual behavior**
The simulator seems to be stuck when clicking button A. It can show square sometimes.
And if I holding button A, the progarm takes effect
![1](https://user-images.githubusercontent.com/59192069/78758204-570e9580-79b0-11ea-9467-37effafa85cd.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.10
3.Microsoft MakeCode version: 5.37.15

**Comment by abchatra** [comment]
This is expected as you have a forever loop and it is continuously running.  It might give some cycles to read the input signal, but may not. Try adding an event on button A pressed and see if you still see the issue.
