### ISSUE TITLE
Can not translate my web http://code.ai4all.org.cn

### ISSUE THREAD

**Issue by myidcn** [microsoft/pxt-microbit#2796]
**Describe the bug**
I have make a web with pxt-microbit, I found the translations is get from   https://makecode.com . the links are as following：
https://makecode.com/api/mscc/code.ai4all.org.cn/zh-CN 404 (Not Found)
https://makecode.com/api/translations?lang=zh-CN&filename=strings.json&approved=true。
https://makecode.com/api/translations?lang=zh-CN&filename=microbit%2Ftarget-strings.json&approved=true
https://makecode.com/api/translations?lang=zh-CN&filename=microbit%2Fsim-strings.json&approved=true

when I change https://makecode.com in the Static pages js or change the “microbit” to same other strings in id in pxtarget.json the translations are Chinese partly and some are English。

my web is  code.ai4all.org.cn

**To Reproduce**
1. Go to 'http://192.168.0.113:8080/#editor'

**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [chrome, Firefox]
 - Version [2.2.19]

**Additional context**
How can make local translations right

**Comment by pelikhan** [comment]
Cloud translation support is only available for web sites hosted by Microsoft.

**Comment by myidcn** [comment]
how can i use local translation，i seems to only use the https://makecode.com/api/
