### ISSUE TITLE
global search - broken links..

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#28]
Can we make a global search for broken links? 

just found this broken link from quiz to 'tutorial'...

http://localhost:3232/lessons/zoomer/quiz

![image](https://cloud.githubusercontent.com/assets/11206682/14160412/129c2346-f691-11e5-811c-a3477b29ab7c.png)

we should also do a global change from /tutorial to /activity...

```
.../microbit/lessons/zoomer/tutorial 
```

should be...

```
.../microbit/lessons/zoomer/activity 

```

**Comment by tballmsft** [comment]
I've asked Darren to do this. Keep in mind, lessons are out of scope for the commercial release (for now).
