### ISSUE TITLE
Magnetometer units

### ISSUE THREAD

**Issue by edbye** [microsoft/pxt-microbit#2800]
**Is your feature request related to a problem? Please describe.**
I’m trying to develop an electric energy monitor using the magnetometer of the Microbit in Makecode/JavaScript for school projects.

Makecode/JavaScript reports the magnetic field values in integer units of microTesla (uT). The raw magnetometer output is in nanoTesla (nT), thus I cannot obtain enough sensitivity on the readings, +/- 500nT are lost.

**Describe the solution you'd like**
Provide a new block ‘magnetic force (nT)’ that reflects the sensor raw output units.

**Describe alternatives you've considered**
Make the output units of the magnetometer nanoTesla by removing the divide by 1,000 in the code, lines 355 -358 in “input.cpp”

Provide a ‘range switch’ option on the ‘magnetic force’ block to allow selection of units, either ‘uT’ or ‘nT’ with appropriate divisor.

Represent the value of magnetic force as a real number rather than an integer.

**Additional context**

**Comment by pelikhan** [comment]
I've updated the API to return double, and keep the precision.
