### ISSUE TITLE
incorrect completition suggestions.

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2803]
![screengrab](https://user-images.githubusercontent.com/4175913/78841636-bcfc1c80-79b2-11ea-9fa2-9e032c5c1c81.gif)

**Comment by darzu** [comment]
Reproing:
![image](https://user-images.githubusercontent.com/6453828/80989347-adbd9280-8de9-11ea-8052-f90ee1e5244c.png)

Working on this
