### ISSUE TITLE
Fireflies can't load block in Chinese

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2808]
**Describe the bug**
**Fireflies** can't load block in Chinese

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#editor
2.Radio Games-->Fireflies->Show Instructions

**Expect behavior**
Fireflies loads block as in English

**Actual behavior**
Fireflies can't load block in Chinese
![1](https://user-images.githubusercontent.com/59192069/78879854-12096280-7a87-11ea-9465-31aab4373fc4.gif)

Additional context
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.12
3.Microsoft MakeCode version: 5.37.19

**Comment by Sheila111** [comment]
**Hot or Cold, Red Light Green Light, Voting Machine, Rock Paper Scissors Teams, Best Friends** also have the same issue.

**Comment by jwunderl** [comment]
same as https://github.com/microsoft/pxt-microbit/issues/2698, it looks like someone went through a while ago (2+ years) and translated all the radio package use snippets to 无线 ; it's definitely not feasible to keep fixing this by hand as it seems like this breaks ~ weekly and we don't have a way to identify when they break besides manual testing on all projects & all languages or user reports (fixing is easy, just takes a long time to navigate to the individual translations / load things).

Taking a look at patching these after translations to ignore mistranslations (ideally any translations in snippets probably?) but not sure that's feasible

**Comment by pelikhan** [comment]
Don't fix the translation. Let's first try to make our parsing more robust in beta.

**Comment by riknoll** [comment]
It seems like this is fixed in master. This does repro on the live docs, but does not in local serve.

That would suggest to me that we are being smarter in how we handle mistranslations, since both beta and live are pointing to the same translations, right @jwunderl?

**Comment by jwunderl** [comment]
Hm, yeah that sounds right, I don't remember anything changing along those lines though.. if it's working currently then maybe fine to just take off next release and I can look into it a bit more later to see if there is anything left

**Comment by abchatra** [comment]
This should be fixed.
