### ISSUE TITLE
A part of block in editor page shows in hint when selected

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#2809]
**Describe the bug**
A part of block in editor page shows in hint when selected

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Games->Heads Guess->Start Tutorial
3.Drag out a block and select something
4.Open the hint and observe

**Expect behavior**
A part of block in editor page should not show in hint when selected.

**Actual behavior**
A part of block in editor page shows in hint when selected, and this bug also reproduce in other blocks and tutorials.
![Repeat](https://user-images.githubusercontent.com/58197774/78880116-7b897100-7a87-11ea-8059-7b5ff66b85d7.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version:  2.3.12
3.Microsoft MakeCode version:  5.37.19

**Comment by pelikhan** [comment]
z-index issue
