### ISSUE TITLE
Robot car simulator

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2810]
> micro:bit support: 28685

**Is your feature request related to a problem? Please describe.**
We are currently in Covid 19 lockdown, this means everyone is working from home. No exceptions.I have been working with some students via email, zoom and google classroom.

My students can code their 2 wheel drive robot cars, then send me the code and I can video the robot working and send back the video. They don’t have their robots in their homes.

**Describe the solution you'd like**
Can you make an online virtual robot simulator?  
 
 Students can upload their code and watch the path it makes.
I have asked one student to write his name with the front wheel as the pen.

**Describe alternatives you've considered**

**Additional context**
As part of our tech course we build our own cars.  I buy the electronics; 
one motor driver board , Two Hobbie DC motor and wheels, one battery pack a microbit and your off. We use a CNC to cut out a chassis and a vacuum former to make a cover.

**Comment by microbit-mark** [comment]
@pelikhan is there or is it possible to make a generic car/motor sim available so a student who does not have the parts at home that they have in the classroom are able to simulate the experience?

**Comment by pelikhan** [comment]
Every robot extension communicates differently with the hardware: ic2, spi, serial, etc... There is no universal story there so a simulator is going to be very tricky.
One way to solve this would be to host the simulator in a page, send iframe post message for each motor command and have the vendor write the simulator.

**Comment by abchatra** [comment]
No plans to address this issue.
