### ISSUE TITLE
inconsistent button hover behavior

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2813]
We should fix the theme of pxt so that all buttons have a consistent hovering (or at least some).
![2020-04-10 07 37 16](https://user-images.githubusercontent.com/4175913/78998805-38b6b000-7afe-11ea-8076-fbce95630038.gif)
![2020-04-10 07 38 42](https://user-images.githubusercontent.com/4175913/78998853-52f08e00-7afe-11ea-9cd2-c245cb11269f.gif)
![2020-04-10 07 38 30](https://user-images.githubusercontent.com/4175913/78998859-571cab80-7afe-11ea-9af4-67c830c10822.gif)

**Comment by pelikhan** [comment]
We should try to avoid custom theme in the traget and fix this in pxt instead.

**Comment by abchatra** [comment]
What is inconsistent? I don't understand.

**Comment by pelikhan** [comment]
Hovering behavior.

________________________________

**Comment by abchatra** [comment]
Like changing the color to green?

**Comment by pelikhan** [comment]
Yes. The hover style in dialog is too subltle.

________________________________

**Comment by pelikhan** [comment]
Duplicated of https://github.com/microsoft/pxt-microbit/issues/2813
