### ISSUE TITLE
Webusb is called different name

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#2814]
Same feature has different names. Please keep it consistent. Probably keep "pair device" for backcompat

![image](https://user-images.githubusercontent.com/6107272/79001942-47a06100-7b04-11ea-9c42-96b4cc56c86a.png)

![image](https://user-images.githubusercontent.com/6107272/79001960-5129c900-7b04-11ea-963c-07a06bf89256.png)

![image](https://user-images.githubusercontent.com/6107272/79001992-60107b80-7b04-11ea-91ec-b021049ac60f.png)

**Comment by pelikhan** [comment]
If the device is already paired, it connects to it automatically without showing the dialog. Pair != connect.

________________________________

**Comment by pelikhan** [comment]
The "connect" command will automatically connect to a known device, without going through the pairing dialog. If no device is available, it will go into a "pairing" dialog and connect. Pairing is a one-time event as the browser remembers the device (ignore browser clearning stuff).

**Comment by abchatra** [comment]
What is the behavior when a device is connected and you click on settings->pair device?

**Comment by pelikhan** [comment]
"Pair Device" always pops up the pairing dialog. This behavior has not changed and is still present for legacy purposes. However, users should do connect instead which is more seamless for a return user.

**Comment by abchatra** [comment]
Ok closing this as by design.
