### ISSUE TITLE
Block keyboard: instructions how to use

### ISSUE THREAD

**Issue by nielsswinkels** [microsoft/pxt-microbit#2815]
**Describe the bug**
I am missing information on how to use the experimental Block keyboard. Which keys are included, and what do they do?

**Comment by pelikhan** [comment]
For experiments, we typically open an issue to describe the experiment in pxt, then link it in the experiments.ts data.

**Comment by abchatra** [comment]
@shakao can you add something like this with instructions: https://github.com/microsoft/pxt/issues?q=is%3Aissue+is%3Aopen+experiments

**Comment by shakao** [comment]
added instructions here: https://github.com/microsoft/pxt/issues/6850

there is also a pop-up modal with brief instructions when you click the "Accessible Blocks On" setting item, let me know if there are any issues with that feature
