### ISSUE TITLE
how can i use local translation Instead of https://makecode.com/api/

### ISSUE THREAD

**Issue by myidcn** [microsoft/pxt-microbit#2818]
**Describe the bug**
I deploy a local website with pxt-microbit, but I found some translations are get from https://makecode.com/api/

the links are as following：
https://makecode.com/api/mscc/code.ai4all.org.cn/zh-CN 404 (Not Found)
https://makecode.com/api/translations?lang=zh-CN&filename=strings.json&approved=true。
https://makecode.com/api/translations?lang=zh-CN&filename=microbit%2Ftarget-strings.json&approved=true
https://makecode.com/api/translations?lang=zh-CN&filename=microbit%2Fsim-strings.json&approved=true

how can i use local translation Instead of https://makecode.com/api/
![makecode](https://user-images.githubusercontent.com/8453599/79289311-7bf89080-7efb-11ea-9936-171274d43d09.jpg)

To Reproduce

    Go to 'http://192.168.0.113:8080/#editor'
    See error

Desktop (please complete the following information):

    OS: [win10]
    Browser [chrome, Firefox]
    Version [2.2.19]

Additional context
How can make local translations right

**Comment by myidcn** [comment]
who could help me ，thank you very much

**Comment by myidcn** [comment]
@abchatra  hello can you show me the  folder structure in a screenshot include the subfolder  and files。 many thanks。

**Comment by myidcn** [comment]
I have found the method， thank you

**Comment by suraj022** [comment]
@myidcn were you able to solve the problem? if so how?

**Comment by yf-chen** [comment]
> I have found the method， thank you

were you able to solve the problem? if so how?
