### ISSUE TITLE
The radio part does not take effect  on hardware

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2823]
**Describe the bug**
The radio part does not take effect  on hardware

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Radio Games---->Mood Radio
3.Show Instructions
4.Click "Download"
5.Run it on the hardware

**Expect behavior**
This project uses the radio to share your mood with other micro:bits. When you press A, other microbit will see a smiley face too. When you press B,  other microbit will also see a frowny face.
![1](https://user-images.githubusercontent.com/59192069/79423018-79c42e00-7ff0-11ea-966a-7f11e466a1c0.gif)

**Actual behavior**
It just shows happy image when pressing button A. Another microbit shows nothing.
It seems that the radio part does not take effect  on hardware

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.15
3.Microsoft MakeCode version: 5.37.25
4.The live version runs normally on hardware

**Comment by abchatra** [comment]
@Sheila111 What is the behavior in live? (Is this a regression)?
Also try Radio -> "Set Group"  in On Start and see if the issue goes away

**Comment by Sheila111** [comment]
@abchatra  The live version runs normally on hardware even if I doesn't and "Set Group" in On Start.
And I tried Radio -> "Set Group" in On Start and the issue doesn't go away.

**Comment by mmoskal** [comment]
works for me on master

**Comment by pelikhan** [comment]
I can repro on /beta.

**Comment by pelikhan** [comment]
It works on /beta after setting the group in onstart.

**Comment by abchatra** [comment]
@finneyj @jamesadevine

**Comment by pelikhan** [comment]
We need to verify that we generate the same program hash on every compile. This works by setting group so it might be that our program hash is not stable anymore.

**Comment by pelikhan** [comment]
@mmoskal did we introduce a random seed in the generated code?

**Comment by mmoskal** [comment]
it's the incremental compilation I think
