### ISSUE TITLE
Enable "break" keyboard

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2828]
We've added return for the function with return values, let's get the story complete and enable "break" in micro:bit. It is very helpful to implement linear search and exit a loop.

**Comment by abchatra** [comment]
Can you add break & continue to the bottom of the loop category?

**Comment by abchatra** [comment]
I think the big issue is how to make it only available only inside loops.

**Comment by abchatra** [comment]
Otherwise it will be runtime error.

**Comment by pelikhan** [comment]
No typescript will find those errors and the error will be surfaced on the block level.

________________________________
