### ISSUE TITLE
Blank program doesn't work in Python

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#2836]
Repro:
1. Open a new project
2. Convert to Python
3. Notice all the errors (~10)

**Comment by darzu** [comment]
Looks like it has to do with handler names. E.g. the forever handler function is called "basic.forever()"

**Comment by abchatra** [comment]
Duplicate https://github.com/microsoft/pxt-microbit/issues/2837

**Comment by darzu** [comment]
Also this is a good opportunity to resurrect py decompiler tests
