### ISSUE TITLE
Python shows error on new Project

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#2837]
**To Reproduce**
1. Go to 'New Project'
2. Click on 'Python'

**Screenshots**
![image](https://user-images.githubusercontent.com/6107272/79598157-55bc2780-8098-11ea-8162-abe5d38c5366.png)

**Comment by darzu** [comment]
Looks like it has to do with handler names. E.g. the forever handler function is called "basic.forever()"

Also this is a good opportunity to resurrect py decompiler tests
