### ISSUE TITLE
Filter out deprecated API's from Intellisense

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2839]
input.onShake comes up in intellisense, but all our Tutorials use the new onGesture API's

![image](https://user-images.githubusercontent.com/22108954/79599265-11ca2200-809a-11ea-80b7-d29637e8f056.png)

**Comment by darzu** [comment]
Looks like onShake was just missing the "deprecated=true" annotation. Intellisense skips it when it's deprecated.
https://github.com/microsoft/pxt-microbit/pull/2941
Are there any others that we know are missing?
