### ISSUE TITLE
USB Icon flashes while flashing via webusb

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#2841]
In Chrome on MacOS

1. Pair a microbit via webusb
2. Open a project
3. Click download

![2020-04-17 11 12 13](https://user-images.githubusercontent.com/13754588/79600803-99189500-809c-11ea-9859-d4cb9f4f440a.gif)

**Comment by pelikhan** [comment]
Fixed by https://github.com/microsoft/pxt/pull/6877 . Probably needs another round of UI to design the webusb connectivity indicator.
