### ISSUE TITLE
Slowmo behavior on a sequence of synchronous operations gets interrupted by "forever"

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#2843]
If you have an event handler with a sequence of synchronous operations like assigning a variable or plotting an LED, slomo shows that the sequence is interrupted by the forever loop even though outside of slomo that is not the behavior. Synchronous sequences should be atomic.

This is not a regression, same thing happens on live site.

https://makecode.microbit.org/_e9xPET4gAWK8

![2020-04-17 11 14 40](https://user-images.githubusercontent.com/6453828/79600850-aa61a180-809c-11ea-84d9-57b72803684f.gif)

**Comment by abchatra** [comment]
Won't fix.
