### ISSUE TITLE
Global "Collapse Blocks" causes code to auto-format

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#2845]
We shouldn't auto-format automatically because a lot of users have a particular layout and don't like things to rearrange without consent.

**Comment by pelikhan** [comment]
Then it should be called collapse all and format. There is really no point on collapsing everything without compacting.

**Comment by darzu** [comment]
Sure there is. It's much easier to drag things around or see what's what when everything is collapsed. No need to format right away. Plus it's easy to collapse all and then format, but collapsing all and not formatting is impossible if they're joined

**Comment by abchatra** [comment]
I also think we shouldn't auto format just because some one collapsed all the blocks. Lots of users like their formatting and we shouldn't destroy their format.

**Comment by abchatra** [comment]
If they want then can right click and format again.
