### ISSUE TITLE
Better indicator of details card focus

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#2846]
**Describe the bug**
We auto-focus the first detail card when a user clicks on a homescreen project, right now the focus rendering just darkens the button which is very subtle; should probably add an outline or something like the hover state

![bug-details-focus](https://user-images.githubusercontent.com/34112083/79601367-89e61700-809d-11ea-925d-86dfa84612a5.gif)

**Comment by pelikhan** [comment]
Also dark green and black color is not a great contrast.  Should we be using the primary color for this button?
![image](https://user-images.githubusercontent.com/4175913/79719575-bbc0ce80-8293-11ea-8d65-d23bbfd9e508.png)
