### ISSUE TITLE
Settings: need choice for language

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt-microbit#285]
Hi
As there comes increased language support, the apparent need for a setting for language will occur:
default (browser) plus  choice of language other than the default

**Comment by abchatra** [comment]
Please open an issue on https://github.com/microsoft/pxt. This repo issues are not tracked

**Comment by riknoll** [comment]
There already is an issue tracking this in pxt: https://github.com/Microsoft/pxt/issues/493
