### ISSUE TITLE
Weird Debugger behavior

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2850]
Not sure exactly what's going on - but it doesn't highlight the Repeat block and goes back to On Start.
![Debugger](https://user-images.githubusercontent.com/22108954/79602949-4640dc80-80a0-11ea-8116-f9e40aed5717.gif)

**Comment by Jaqster** [comment]
This was on old Edge with this program https://makecode.microbit.org/_eeVCsjMWjDMi

**Comment by abchatra** [comment]
I can reproduce this in new edge too. Somehow breakpoint or even slow mo doesn't work on repeat block

**Comment by riknoll** [comment]
Not edge specific, I think this has to do with a repeat block being followed by an if statement. Here's a minimal repro:

https://makecode.microbit.org/_Uv4eDJ7UAEqz
