### ISSUE TITLE
Cannot unset breakpoints

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2851]
Clicking on the breakpoint sets it, but it cannot be unset. Reloading the project does not fix it.
![2020-04-18 18 47 08](https://user-images.githubusercontent.com/4175913/79677342-221af380-81a5-11ea-91ca-86d0597b0388.gif)

**Comment by jwunderl** [comment]
Dup #2488, looks like its not just ipad?

**Comment by pelikhan** [comment]
Mac, Chrome

**Comment by pelikhan** [comment]
This is about setting the breakpoints not related to music.

**Comment by jwunderl** [comment]
Oops, #2848

**Comment by pelikhan** [comment]
Duplicated.
