### ISSUE TITLE
navigate from function call to function body

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt-microbit#2853]
In large block programs, it would be really useful to have an option from right-mouse button on a function-call block to navigate to the function call.

**Comment by pelikhan** [comment]
The call site of a function has a "Edit function" button which edits the signature. It should be replaced by  "Go to function". Then the user can right click on the function and click "Edit function" -- in fact, we should have a button to enter the edit mode.
![image](https://user-images.githubusercontent.com/4175913/79680090-b6468400-81c0-11ea-938f-ccae64cf8848.png)

**Comment by pelikhan** [comment]
This needs to be fixed in pxt-blockly:
https://github.com/microsoft/pxt-blockly/blob/1e32af20568b9aeed4b810128b2ba6401e0d2fe0/blocks/extensions.js#L29

**Comment by riknoll** [comment]
Fixed by https://github.com/microsoft/pxt-blockly/pull/282

**Comment by pelikhan** [comment]
Yes!
