### ISSUE TITLE
Trace icon and Debugger icon need to merge

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2857]
I don't see any bug tracking the redesign of debugger+tracing icons. See design document.

**Comment by riknoll** [comment]
What is the new design?

**Comment by pelikhan** [comment]
I only remember that we had a lengthy discussion about it.

**Comment by Jaqster** [comment]
Remove the Slo Mo (snail) button from the Simulator toolbar.  This is being replaced by the Debugger (ladybug) button.

In the Debug window, we talked about having a Slow vs. Fast Run button.  But the first step is to remove the Snail.
