### ISSUE TITLE
It should only show current blocks and code 

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#2861]
**Describe the bug**

It should only show current blocks and code

**Steps to reproduce the behavior**

1.Navigate to https://makecode.microbit.org/beta#
2.Games->Reaction Time->Show Instructions
3.Click 'Let's get started!' button->Click 'Code' button
4.Choose the first 'Edit' button

**Expect behavior**

It should only show current blocks and code after clicking 'Edit' button.

**Actual behavior**

All blocks and code are showed.
![total](https://user-images.githubusercontent.com/58197774/79738062-d5fbba80-832e-11ea-9135-9b43e968aafe.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.17
3.Microsoft MakeCode version: 5.37.28

**Comment by ganicke** [comment]
Pressing **Edit** on any snippet will load the LAST one in the page. Also, the edit context goes to JavaScript regardless of the view in the page. This isn't a page bug.

This does NOT happen with the current build. I can't test on published beta since the refer URL with the HEX doesn't go to beta.
