### ISSUE TITLE
Lack of connect microbit option on edge and Firefox browser

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2863]
**Describe the bug**
Lack of connect microbit option on edge and Firefox browser

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#editor
2.Click Download

**Expect behavior**
After clicking download , there shows a prompt to connect microbit. 
![2-google](https://user-images.githubusercontent.com/59192069/79820980-2bcc7300-83c0-11ea-8c29-1d56d908d64f.gif)

**Actual behavior**
Lack of connect microbit option on edge and Firefox browser. So I can only click Download and save the .hex file to the MICROBIT drive to transfer the code into micro:bit.
![1](https://user-images.githubusercontent.com/59192069/79820983-2d963680-83c0-11ea-93c6-f2832c62da53.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.18
3.Microsoft MakeCode version: 5.37.29

**Comment by pelikhan** [comment]
This is by design in browsers that do not support WebUSB.

**Comment by abchatra** [comment]
By design
