### ISSUE TITLE
Pause sign is not centered on iPad

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2866]
**Describe the bug**
Pause sign is not centered on iPad

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta

**Expect behavior**
Pause sign is centered
![image](https://user-images.githubusercontent.com/59192069/79847338-2ab43980-83f2-11ea-97d8-e8995750b891.png)

**Actual behavior**
Pause sign is a little lower, not centered on iPad
![image](https://user-images.githubusercontent.com/59192069/79847311-212ad180-83f2-11ea-824c-75b92f9fba10.png)

**Additional context**
1.OS: iPad mini 4
2.makecode.microbit.org version: 2.3.18
3.Microsoft MakeCode version: 5.37.29

**Comment by abchatra** [comment]
Won't fix.
