### ISSUE TITLE
No intellisense on iPad

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2867]
**Describe the bug**
No intellisense on iPad

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#editor
2.Type Button. to see if there is intellisense

**Expect behavior**
There shows Intellisense
![image](https://user-images.githubusercontent.com/59192069/79848780-1d984a00-83f4-11ea-854a-7c4e96c0ef88.png)

**Actual behavior**
No intellisense on iPad
![1](https://user-images.githubusercontent.com/59192069/79848584-dad67200-83f3-11ea-951c-967c5d0c235a.gif)

**Additional context**
1.OS: iPad mini 4
2.makecode.microbit.org version: 2.3.18
3.Microsoft MakeCode version: 5.37.29

**Comment by jwunderl** [comment]
@Sheila111 could you check if this still repros with current beta when you get a chance? I don't have a physical iPad / iOS device around, but I'm not able to repro this in the xcode simulator which typically does a good job matching on this sort of thing, and it mostly works on my android phone.

**Comment by abchatra** [comment]
@Sheila111 Can you please validate this is fixed. I tried on ipad and intellisense seem to popup.

**Comment by Sheila111** [comment]
I checked it doesn't repro with current beta. Intellisense pops up on iPad.
