### ISSUE TITLE
The keyboard does not appear automatically sometimes on iPad

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2868]
**Describe the bug**
The keyboard does not appear automatically sometimes on iPad

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#editor

**Expect behavior**
The keyboard appears automatically when the mouse is placed on code

**Actual behavior**
The keyboard does not appear automatically when the mouse is placed on code sometimes on iPad. And I need to click the keyboard in the lower right corner  manually.
![1](https://user-images.githubusercontent.com/59192069/79849445-0efe6280-83f5-11ea-8a99-d4e3f05374dc.gif)

**Additional context**
1.OS: iPad mini 4
2.makecode.microbit.org version: 2.3.18
3.Microsoft MakeCode version: 5.37.29

**Comment by abchatra** [comment]
Won't fix. We have moved the keyboard icon to the top, user can click on it if the keyboard doesn't pop up automatically
