### ISSUE TITLE
Support paint on drag in melody editor

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2872]
The "show leds" block support drag and paint behavior; would be nice to have the same for melody editor.
![2020-04-21 14 35 25](https://user-images.githubusercontent.com/4175913/79916368-74def000-83dd-11ea-9ee9-91e8b653e10e.gif)

**Comment by shakao** [comment]
removing next-release for now, this will be more useful when we add the ability to have chords/multiple notes, otherwise it erases your current melody when you drag

**Comment by abchatra** [comment]
We discussed this in the design office hours. This is not a good pattern for melody at this point of time.
