### ISSUE TITLE
It seems that the function name doesn't support dots in python editor

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#2874]
**Describe the bug**
It seems that the function name doesn't support dots in python editor

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Game->Head Guess!->Choose python tutorial
3.The hint is different from the python code when getting to 4th

**Expect behavior**
The hint should be correct, if following the hint, the code shouldn't have any error.

**Actual behavior**
If following the hint, the code shows error. It seems that the function name doesn't support dots in python editor
![logo](https://user-images.githubusercontent.com/58197774/79952006-4c71f700-84ac-11ea-992f-2b8ba4d9e5e4.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.19
3.Microsoft MakeCode version: 5.37.30

**Comment by abchatra** [comment]
Snippet seems wrong in python. @KellyLuo1 nice bugs.

**Comment by pelikhan** [comment]
Duplicate fixed by https://github.com/microsoft/pxt/pull/6893

**Comment by abchatra** [comment]
Fixed
