### ISSUE TITLE
The situation is different than expected after clicking 'Edit' button

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#2875]
**Describe the bug**
The situation is different than expected after clicking 'Edit' button

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Game->Magic Button Trick!->Show Instructions
3.Click 'Edit' button

**Expect behavior**
It should show current blocks and code in editor page after clicking 'Edit' button

**Actual behavior**
It always show the same block and code in editor page.
![different](https://user-images.githubusercontent.com/58197774/79962656-e50f7380-84ba-11ea-9203-c62bb69dfb26.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.19
3.Microsoft MakeCode version: 5.37.30

**Comment by pelikhan** [comment]
good catch

**Comment by jwunderl** [comment]
I fixed this one a while ago in new docs https://github.com/microsoft/pxt/pull/6410, works on master / will work on next release

(I'd show an example on minecraft, but those edit buttons are set to be hidden in pxtarget on release minecraft for some reason; if you go to any tutorial page, search for `hideDocsEdit` in dev tools, and set a breakpoint / turn off the flag when loading the page you can test, but that's overly tedious.)
