### ISSUE TITLE
UI issues on iPad

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2876]
**Describe the bug**
UI issues on iPad

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Click a tutorial

**Expect behavior**
![image](https://user-images.githubusercontent.com/59192069/79968428-a8e01100-84c2-11ea-9ea0-0a271b41f758.png)

**Actual behavior**
UI issues on iPad. The text on the left seems to be cut off and YouTube icon shows beyond the background.
![image](https://user-images.githubusercontent.com/59192069/79968035-2fe0b980-84c2-11ea-9bec-2ab234a959ad.png)

**Additional context**
1.OS: iPad mini 4
2.makecode.microbit.org version: 2.3.18
3.Microsoft MakeCode version: 5.37.29

**Comment by shakao** [comment]
Fixed by https://github.com/microsoft/pxt/pull/6908 (moving Youtube link under description)
