### ISSUE TITLE
Block hint appears in the python tutorial

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2880]
**Describe the bug**
Block hint appears in the python tutorial

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Games--->Rock Paper Scissors--->Python Start Tutorial
3.Click step 3

**Actual behavior**
Block hint appears in the python tutorial and maybe it should be deleted.
![1](https://user-images.githubusercontent.com/59192069/80050691-ee472180-8548-11ea-8a46-578b41eb2719.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.22
3.Microsoft MakeCode version: 5.37.33
4.Javascript tutorial has the same issue

**Comment by abchatra** [comment]
We have gifs?

**Comment by ganicke** [comment]
There are 6 of them in there. I suppose those are bygone now unless we make a spy version along side the blocks one.

**Comment by pelikhan** [comment]
We should get rid of that gif.

**Comment by abchatra** [comment]
Or may be get rid of python and javascript options from these tutorials. @Jaqster  
Blind conversion of the tutorial is not great if you read the text.

**Comment by pelikhan** [comment]
I will rewrite them.

________________________________
