### ISSUE TITLE
Python code error on Tutorial Heads Guess

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2881]
**Describe the bug**
Python code error on Tutorial Heads Guess

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Games--->Heads Guess--->Python Start Tutorial
3.Click step 4

**Actual behavior**
Code error written by hint.
![1](https://user-images.githubusercontent.com/59192069/80064605-03cd4300-856b-11ea-8eb0-825a87251f6d.png)
Hint
![2](https://user-images.githubusercontent.com/59192069/80064630-10ea3200-856b-11ea-9c5c-3b62d143218e.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.22
3.Microsoft MakeCode version: 5.37.33

**Comment by pelikhan** [comment]
Duplicate fixed by https://github.com/microsoft/pxt/pull/6893

**Comment by abchatra** [comment]
Fixed
