### ISSUE TITLE
Right-click has no paste option

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2882]
**Describe the bug**
Right-click has no paste option only copy option

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#editor
2.Right-click copy code

**Expect behavior**
Right-click has paste option.

**Actual behavior**
Right-click has no paste option. Only Ctrl+V to paste the copied code.
![image](https://user-images.githubusercontent.com/59192069/80065187-4d6a5d80-856c-11ea-8cd0-82ea38a7c703.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.22
3.Microsoft MakeCode version: 5.37.33

**Comment by riknoll** [comment]
I think that @darzu must have fixed this with his monaco changes! It's there now in beta
