### ISSUE TITLE
Code grayed out when selected JavaScript editor

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2890]
**Describe the bug**
Code grayed out when selected JavaScript editor

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Tools--->Plot Acceleration--->Show Instructions
3.Click python or javascript
4.Switching to JavaScript editor

**Expect behavior**
The code displays normally
![image](https://user-images.githubusercontent.com/59192069/80198857-3fdbd300-8653-11ea-9b2f-1da29bf2446d.png)

**Actual behavior**
Code grayed out when selected JavaScript editor
![1](https://user-images.githubusercontent.com/59192069/80198775-29ce1280-8653-11ea-9da7-13d4bfa1b169.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.23
3.Microsoft MakeCode version: 5.37.34

**Comment by Sheila111** [comment]
@jwunderl  still not fix
![2](https://user-images.githubusercontent.com/59192069/81134452-65d47200-8f87-11ea-8dad-607ce798aa13.gif)

**Comment by jwunderl** [comment]
Fix is merged in, but won't show up in beta until pxt is bumped again -- probably sometime tomorrow, I can't do that quite yet :)
