### ISSUE TITLE
Image editor images.createImage() needs scaling flexibility and accessibiliy for other uses.

### ISSUE THREAD

**Issue by MTKilpatrick** [microsoft/pxt-microbit#2891]
**Summary of request**
Please add a "imageEditorScale" attribute as a block annotation such that a custom-sized image editor based on images.createImage() can have both a custom size and a custom scale on the screen in the block editor view, and ensure that custom-sized images are fully supported.

**Context**
For the Microbit there are two functions for editing images which have custom field editors in the block view for 5x5 and 10x5 pixel images:
```
images.createImage()
images.createBigImage()
```
However, there are many LED/LCD displays available for Microbit graphics -8x8, 17x7, 16x9 LED or higher-res OLED/LCD. Extension for these can have no facility for a pixel image editor of custom size within the Block environment.

On 23rd April 2020 the beta release of pxt-microbit was modified to remove the 5x size constrains such that _imageLiteralRows_ and _imageLiteralColumns_ combined with a _shim_ can create a custom-sized image editor as follows:

```
namespace mydisplaydriver {
    //% block="create 17x7 image"
    /* for the Pimoroni Scroll:bit 17x7 LED display */
    //% imageLiteral=1 imageLiteralColumns=17 imageLiteralRows=7
    //% shim=images::createImage
    export function myCustomImage(i: string): Image {   
        const im = <Image><any>i;  return im 
    }
}
```
**The problems**

- A large custom-sized image editor in block view will occupy an excessive part of the editor screen. This is clumsy for something such as a 16x8 image or larger.
- The lack of custom-sized image support is a big drawback when using external LED/LCD devices.

**Proposed solution**
A parameter to scale the screen view of the image editor would allow extensions not only to create images of any custom size but also avoid a ridiculously large block occupying most of the screen. A simple scale parameter could perhaps double or triple the density of the image editor? It might be used as follows:
```
namespace mydisplaydriver {
    //% block="create 24x12 image"
    //% imageLiteral=1 imageLiteralColumns=24 imageLiteralRows=12
    //% imageEditorScale=2   // double the on-screen density for this large image
    //% shim=images::createImage
    export function myCustomImage(i: string): Image {   
        const im = <Image><any>i;  return im 
    }
}
```
**Scope**
The solution requires the propagation of a parameter from the block annotation down to the core Blockly functions which generate the HTML view of the editor. The solution also requires that all constant constrains (multiples of 5) are removed from the core and replaced by appropriate references to _image.height_ and _image.width_ or determining that the changes kindly introduced by Pelikhan into the beta release have eliminated all such constraints.

Also, is the _imageLiteral_ parameter required?

**Comment by abchatra** [comment]
Fixed
