### ISSUE TITLE
Python completion for Math.randomRange is incorrect

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#2894]
There are a few different bugs here:
<img width="625" alt="Screen Shot 2020-04-24 at 10 44 51 AM" src="https://user-images.githubusercontent.com/13754588/80241593-b4455080-8618-11ea-9099-124bbeec8cbb.png">

1. It shows Math.random_range in the list of completions, when it should be randint
2. The snippet preview on the right does not match the completion item
3. If you commit the completion, you get `Math.randint(0, 10)` which is an error. The `Math.` should not show up

**Comment by Jaqster** [comment]
I feel like this is inconsistent.  How come we have randint(0, 10) in Python and Math.randomRange(0, 10) in JavaScript?  Shouldn't we stick to the namespace convention?

**Comment by riknoll** [comment]
randint is the python name for the function. Typically in python you import the function and reference it directly, but we could namespace it (less pythonic)

**Comment by pelikhan** [comment]
We should add randint to typescript also. Math.randomRange is not a built-in JS function either.

**Comment by Jaqster** [comment]
Yeah, I think we should stick more closely with the native language constructs, but let's try to be consistent across Typescript and Python...

**Comment by pelikhan** [comment]
There is no native "random range" in javascript. There is Math.random() which returns a uniform random value between 0..1.

**Comment by Jaqster** [comment]
Don't you think it's weird that these are equivalent expressions?
let myNum = Math.randomRange(0, 10)
myNum = randint(0, 10)

**Comment by pelikhan** [comment]
It would be more intuitive to use ``randint`` in both JS and Python. In Minecraft, we migrated to ``randpos`` because it was such a popular construct. Same for ``randint``, we use randomness all over the place in games.

**Comment by Jaqster** [comment]
Math.randomRange(min, max) feels more English-language meaningful to me and closer to our Blocks representation.  But if randint is a Python language construct, then maybe we should go with that..?

**Comment by pelikhan** [comment]
We abolustely need to use ``randint`` in python; so we might as well align out javascript with this api.
