### ISSUE TITLE
Some Javascript appears as valid Python, but does not convert to blocks

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#2897]
**Describe the bug**
`basic.showNumber(Math.random())` runs in the simulator in Python but does not convert to blocks (converts to Javascript, then we can convert back to blocks)

Same for `list1.length`

**Expected behavior**
Should be a compile error

**Comment by riknoll** [comment]
We treat snakification as optional in python; this bug is actually a blockly exception. Should we require snakified APIs though?

**Comment by shakao** [comment]
oops i was referring to the "Math.random()" bit actually.... didn't notice the shownumber was also JS.

**Comment by riknoll** [comment]
yeah, all JS names also work in python. I thought that was by design? @darzu @pelikhan

**Comment by shakao** [comment]
right now 
```
a = [1, 2, 3]
b = [4, 5]
c = len(a) + b.length

d = Math.random() + randint(0, 10)
```
is treated as valid python code, which feels like a lot of weird mixing to me. maybe the random one is ok, since they do different things, but sometimes having the namespace and sometimes not also seems confusing

**Comment by pelikhan** [comment]
we are a learning platform so we should be resilient and allow this IMO. However we should never generate mixed code through a transpiration.

**Comment by riknoll** [comment]
I think both are equally valid arguments. The length one bothers me a lot more than `Math.random`
