### ISSUE TITLE
Python tutorials don't offer much guidance outside of hints

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#2899]
A lot of the python tutorials are difficult to follow unless you already know the APIs. For example, this is the second step in the flashing heart tutorial:

<img width="1207" alt="Screen Shot 2020-04-24 at 10 55 53 AM" src="https://user-images.githubusercontent.com/13754588/80242489-49951480-861a-11ea-8194-9f72779b2dd8.png">

It doesn't say how to create a template string, or that show leds is in the basic category, or that you "draw" by using the characters "#" and ".". The only real way to move forward is to look at the hint.

**Comment by riknoll** [comment]
Here is the tug of LED python tutorial

<img width="1022" alt="Screen Shot 2020-04-24 at 11 00 35 AM" src="https://user-images.githubusercontent.com/13754588/80242868-ec4d9300-861a-11ea-9d05-c9c5796484e7.png">

it mentions "on start" even though that is not a thing in python

**Comment by Jaqster** [comment]
Agree.   We need a rewrite pass on our Python/JS tutorials.
![image](https://user-images.githubusercontent.com/22108954/80245610-dbebe700-861f-11ea-820f-7e46d401e1ca.png)

**Comment by Jaqster** [comment]
@ganicke - can you rewrite the Micro:bit tutorials in the SPY format for PY and JS?

**Comment by pelikhan** [comment]
IMO we should always show the hint in python.
