### ISSUE TITLE
maker activities - require published script IDs

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#29]
with maker activities, students receive a finished program to run on the micro:bit after completing the maker activity

http://localhost:3232/lessons/ornament-chain/activity

http://localhost:3232/lessons/the-watch/activity

here is an example of the issue

![image](https://cloud.githubusercontent.com/assets/11206682/14160770/88460e0c-f693-11e5-89cf-59700e7cb131.png)

**Comment by pelikhan** [comment]
delete ornament.

**Comment by mebrauns** [comment]
done
