### ISSUE TITLE
Python variable decompilation weirdness

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2901]
I wrote this program in Python: 

```python
basic.show_icon(IconNames.DUCK)
basic.show_number(10)
basic.show_string("Hello!")
a = "this is a"
b = 23
def on_gesture_shake():
    basic.show_string(a)
    a = "this is a++"
input.on_gesture(Gesture.SHAKE, on_gesture_shake)
def on_button_pressed_a():
    basic.show_number(b)
    b = b + 1
input.on_button_pressed(Button.A, on_button_pressed_a)
```

and then moved to blocks and got this.
![blocks](https://user-images.githubusercontent.com/22108954/80243230-ad6c0d00-861b-11ea-97f0-37457cbf28c7.png)

**Comment by Jaqster** [comment]
Also, shouldn't this work?  Why do we need a Global variable declaration?
![image](https://user-images.githubusercontent.com/22108954/80243339-eefcb800-861b-11ea-887c-278d5c3ebffc.png)

**Comment by riknoll** [comment]
This is working as expected. If you want to use a variable inside of a function, you need to use either `nonlocal` or `global`. Otherwise a new variable will be declared inside of the function block, which is what the `<python code>` blocks are doing. 

One of the most annoying python "features"
