### ISSUE TITLE
Blockly typing input block rendering

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2903]
This is hard to repro consistently, but on New Edge, sometimes I when I'm clicking in text/number fields, the block renders weirdly...
![Blockly](https://user-images.githubusercontent.com/22108954/80243650-734f3b00-861c-11ea-95d1-569643e93768.png)

**Comment by pelikhan** [comment]
You can make it happen by collapsing the simulator while being in that buggle.
