### ISSUE TITLE
Hint bubble placement

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2904]
I didn't already see a bug for this... but maybe this is a known issue...?
On new Edge the Hint bubble placement is off in all Tutorials (blocks, JS, PY)
![Hint](https://user-images.githubusercontent.com/22108954/80244040-23bd3f00-861d-11ea-9599-02ccc40b32b3.png)

**Comment by abchatra** [comment]
Can't repro.

**Comment by riknoll** [comment]
I can repro this in Chrome on the live site

**Comment by abchatra** [comment]
Fixed? If not lets reopen.
