### ISSUE TITLE
On first run of radio code, second microbit does not recieve message

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#2906]
**Describe the bug**
The first time you run the radio code, the second microbit slides in after the message has been sent, so your "on received" code does not run. Only displays on second+ runs

**Comment by pelikhan** [comment]
This has always been the case. The first exection there is no simulator to listen for that message, so we don't block and lazily launch the second simulator. Not trivial to fix.

**Comment by abchatra** [comment]
No plans to address this issue.
