### ISSUE TITLE
Hint animation - too quick?

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2907]
Maybe we can talk about this in our next design meeting... but I feel like the Hint animation may be showing too quickly.  I barely have time to finish reading the instructions before it starts flashing.  Can we set the threshold to a longer period of inactivity?

**Comment by abchatra** [comment]
@jwunderl  can you increase the inactivity time please? For a reasonable duration?

**Comment by pelikhan** [comment]
I got more feedback that the hint animation triggers too early and too many times. I think we have issues in our inactivity detection.
