### ISSUE TITLE
debugger pane is often blank

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt-microbit#2913]
When I get an exception failure in my program (https://github.com/microsoft/tileworld), I often run under the debugger in order to get a stack trace. However, it's often the case when I start up the debugger and run in the same situation that causes the failure, the debugger pane remains blank although the program has run to the failure and entered the debugger.

**Comment by abchatra** [comment]
Transferred to pxt-microbit.

**Comment by tballmsft** [comment]
nothing on console. Here's what it looks like:

![image](https://user-images.githubusercontent.com/10767146/80297599-66743980-8739-11ea-8fb9-7d75b768bc13.png)

breakpoint reach, but debugger pane not visible. I'll investigate more.

**Comment by tballmsft** [comment]
Here's more on the problem. I set a breakpoint at the first statement of:

```
            e.prototype.updateDebuggerToolbox = function() {
                var e = document.getElementById("monacoDebuggerToolbox");
                if (e && this.blockInfo) {
```
this.blockInfo is undefined, which appears to result in the pane not being populated

**Comment by tballmsft** [comment]
In particular, we never reach:
                    var n = t ? a.createElement(b.DebuggerToolbox, {
in

```
     e.prototype.updateDebuggerToolbox = function() {
                var e = document.getElementById("monacoDebuggerToolbox");
                if (e && this.blockInfo) {
                    var t = this.isDebugging();
                    t && this.flyout && this.flyout.setState({
                        groups: void 0
                    });
                    var n = t ? a.createElement(b.DebuggerToolbox, {
                        ref: this.handleDebugToolboxRef,
                        parent: this.parent,
                        apis: this.blockInfo.apis.byQName,
                        openLocation: this.revealBreakpointLocation,
                        showCallStack: !0
                    }) : null;
                    s.render(n, e)
                }
            }
```

**Comment by tballmsft** [comment]
My suspicion is that we have a race condition somewhere. The initialization of this.blockInfo takes place in an async:

```
    private beginLoadToolbox(file: pkg.File, hc?: boolean) {
        if (this.toolbox)
            this.toolbox.showLoading();
        compiler.getBlocksAsync().then(bi => {
            this.blockInfo = bi
            this.nsMap = this.partitionBlocks();
            this.updateToolbox();
            pxt.vs.syncModels(pkg.mainPkg, this.extraLibs, file.getName(), file.isReadonly())
            this.defineEditorTheme(hc, true);
        });
        this.blockIdMap = snippets.blockIdMap();
    }
```

**Comment by tballmsft** [comment]
Well, this is odd. I am not seeing beginLoadToolbox being called at all. That would explain why this.blockInfo is not initialized...

**Comment by tballmsft** [comment]
And when I try to put a breakpoint in, the chrome debugger hangs on me! 

![image](https://user-images.githubusercontent.com/10767146/80298420-0bdedb80-8741-11ea-9595-5a9b4178f767.png)

**Comment by tballmsft** [comment]
OK. I figured out what the problem is. This occurs because I have a bunch of .ts files other than main.ts and custom.ts. As a result, the monaco toolbox is not getting initialized properly for them (I think). When I hit the JavaScript toggle - I get the debugger pane!

**Comment by tballmsft** [comment]
I can now repro this behavior.

**Comment by pelikhan** [comment]
Nice find!
