### ISSUE TITLE
Simulator can't load on iPad

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2915]
**Describe the bug**
Simulator can't load on iPad

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Games---->Karel the LED---->Show Instructions

**Expect behavior**
Simulator shows normally
![2](https://user-images.githubusercontent.com/59192069/80303028-4b103980-87e0-11ea-9471-2b7ab2fac393.gif)

**Actual behavior**
Simulator can't load on iPad
![1](https://user-images.githubusercontent.com/59192069/80302915-79414980-87df-11ea-8cbc-2cf2bd8e48e1.gif)

**Additional context**
1.OS: iPad mini 4
2.makecode.microbit.org version: 2.3.28
3.Microsoft MakeCode version: 5.37.39

**Comment by abchatra** [comment]
@jwunderl can you verify this is fixed in the latest docs?

**Comment by jwunderl** [comment]
I don't have an iPad at home so I can't check on a physical device, but I tried w/ local serve on xcode ipad simulator and everything seems to be working fine. For reference, that's simulating iPad Pro 12.9in 3rd w/ gen ios 13.3

**Comment by Sheila111** [comment]
It's fixed on the current version.
