### ISSUE TITLE
No need to pop the keyboard

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2916]
**Describe the bug**
No need to pop the keyboard

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Games---->Hot Potato---->Block Start Tutorials
3.Click step 3
4.Click **pick random** block to change the number

**Expect behavior**
No need to pop the keyboard

**Actual behavior**
After clicking **pick random** block to change the number, a calculator-like tool will pop up to modify the numbers. So I think there is no need to pop the keyboard.
![1](https://user-images.githubusercontent.com/59192069/80303087-97f41000-87e0-11ea-8e45-ca6d41fb4351.gif)

Additional context
1.OS: iPad mini 4
2.makecode.microbit.org version: 2.3.28
3.Microsoft MakeCode version: 5.37.39

**Comment by abchatra** [comment]
Looks like we have removed the field editor. This doesn't repro anymore
