### ISSUE TITLE
It shouldn't turn off the high contrast automatically after switching language

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#2917]
**Describe the bug**
It will turn off the high contrast automatically after switching language

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Click New Project
3.Click high contrast on
4.Switch language

**Expect behavior**
It shouldn't  turn off the high contrast automatically after switching language

**Actual behavior**
It will turn off the high contrast automatically after switching language
![change](https://user-images.githubusercontent.com/58197774/80329024-8f004e80-8873-11ea-830c-0d43f4c0f1df.gif)

**Additional Context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.28
3.Microsoft MakeCode version: 5.37.39

**Comment by abchatra** [comment]
This is by design. Changing language reloads the editor and high contrast should be selected again.
