### ISSUE TITLE
Order of Function blocks in Toolbox

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2918]
Can we put the Call Function statement block first?  
Since that's the one most people will use.
Followed by Return and Call Function return value blocks?
![image](https://user-images.githubusercontent.com/22108954/80401388-1dbf9c00-8871-11ea-84bf-82ba7140a5df.png)

**Comment by abchatra** [comment]
I think the issue is if there are lot of functions you will have to scroll to get return statement every time. @riknoll what do you think?

**Comment by riknoll** [comment]
I think it makes sense to have it up top, personally

**Comment by Jaqster** [comment]
I see.  Hmmm.  What about adding a little separator then?  I can imagine that this drawer could get a bit confusing to navigate...

![image](https://user-images.githubusercontent.com/22108954/80823277-34c3fe00-8b91-11ea-80db-8a376a5cf96d.png)

Also, should we apply this same organizational logic to the Variable drawer as well? With the common blocks at the top, and the specific blocks at the bottom?

![image](https://user-images.githubusercontent.com/22108954/80823398-6b017d80-8b91-11ea-86ef-106c39ddf2d6.png)

**Comment by riknoll** [comment]
We can definitely add some space. And yeah, I guess I didn't think about variables. Whatever we end up doing should match
