### ISSUE TITLE
Debugger - can't unselect/remove breakpoints

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2919]
New Edge.  Trying to remove breakpoints, and it won't let me.
https://makecode.microbit.org/_d5AdY2DgcJ0X
![image](https://user-images.githubusercontent.com/22108954/80409002-f969bc80-887c-11ea-8d64-7291ff41a09d.png)

**Comment by jwunderl** [comment]
duplicate https://github.com/microsoft/pxt-microbit/issues/2848
