### ISSUE TITLE
Beta: Initial setVolume level is low when connected to a speaker

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2923]
![Screenshot 2020-04-28 at 12 19 14](https://user-images.githubusercontent.com/31242877/80481526-8890d600-894a-11ea-8c8a-a518407eb874.png)

The initial value of setVolume makes sound barely audible when connecting the micro:bit to a piezo speaker. 

Consider setting the initial volume midway eg 127 or change the increments to something like radio strength 0-7, setting it midway.

**Comment by pelikhan** [comment]
Set to 127
