### ISSUE TITLE
Slow-Mo not highlighted when high contrast on

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2925]
**Describe the bug**
Slow-Mo not highlighted when high contrast on

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#editor
2.Click high contrast on
3.Click Slow-Mo

**Expect behavior**
Slow-Mo  highlighted as high contrast off
![1](https://user-images.githubusercontent.com/59192069/80554668-770a0580-8a00-11ea-9756-a99d348b5a6e.gif)

**Actual behavior**
Slow-Mo not highlighted when high contrast on
![2](https://user-images.githubusercontent.com/59192069/80554673-796c5f80-8a00-11ea-9930-990cf10fe764.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.30
3.Microsoft MakeCode version: 5.37.41

**Comment by Sheila111** [comment]
The same issue when toggle debug mode.
![Debug](https://user-images.githubusercontent.com/59192069/80554967-6c9c3b80-8a01-11ea-885e-3ffc28d37a3b.gif)

**Comment by abchatra** [comment]
Debug or slow mo icon in the simulator is not highlighted in high contrast mode.
