### ISSUE TITLE
No Slow-Mo in the new version

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2929]
**Describe the bug**
No Slow-Mo in the new version

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#editor

**Expect behavior**
There is Slow-Mo under the simulator
![image](https://user-images.githubusercontent.com/59192069/80676390-3639eb80-8ae9-11ea-82c9-b980e1c3476d.png)

**Actual behavior**
No Slow-Mo  in the new version
![1](https://user-images.githubusercontent.com/59192069/80675835-0b02cc80-8ae8-11ea-813f-2cf09230753e.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.33
3.Microsoft MakeCode version: 5.37.45

**Comment by pelikhan** [comment]
This is by design. The Slow-Mo feature has been integrated into the debugger.
