### ISSUE TITLE
The content doesn't show in 'Sprial' and 'Scanner'

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#2930]
**Describe the bug**

The content doesn't show in 'Sprial' and 'Scanner'

**Steps to reproduce the behavior**

1.Navigate to https://makecode.microbit.org/beta#
2.Turtle->Spiral/Scanner
3.Right click blocks->Help

**Expect behavior**
Succeed to open 'Sprial' and 'Scanner', and the content shows normally

**Actual behavior**
The content doesn't show in 'Sprial' and 'Scanner', and the block's help is the same situation
![show](https://user-images.githubusercontent.com/58197774/80676629-c1b37c80-8ae9-11ea-89a5-351e784cb3c5.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.34
3.Microsoft MakeCode version: 5.37.46

**Comment by Sheila111** [comment]
All side doc can't open. Includes right-click--->help operation.
![1](https://user-images.githubusercontent.com/59192069/80684652-908e7880-8af8-11ea-8abe-572d01a9d4f5.gif)

**Comment by pelikhan** [comment]
Fixed by https://github.com/microsoft/pxt/pull/6946

**Comment by pelikhan** [comment]
Fixed.
