### ISSUE TITLE
Can't run the multi-edit URL in beta

### ISSUE THREAD

**Issue by Lorrainbow** [microsoft/pxt-microbit#2939]
**Describe the bug**
Hi, the URL https://makecode.microbit.org/multi doesn't work to test the multi-edit in beta. 

**To Reproduce**
I tried these URLs

- https://makecode.microbit.org/beta/multi
- https://makecode.microbit.org/multi/beta

**Expected behavior**
Expect to be able to test the multi screen editor as demonstrated on the blog
https://makecode.com/blog/microbit/2020-beta

**Desktop**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81.0.4044.122

**Comment by jwunderl** [comment]
Oh, it's hosted under the main makecode url: https://makecode.com/multi, that's a typo in the post. Thanks!
