### ISSUE TITLE
Beta: Neopixel, simulator showing green not red

### ISSUE THREAD

**Issue by Lorrainbow** [microsoft/pxt-microbit#2940]
**Describe the bug**
When setting a Neopixel strip to red, the simulator shows green

**To Reproduce**
1. Go to https://makecode.microbit.org/beta#editor
2. Scroll down to Extensions, click on it
3. Select Neopixel 
4. Inside "on start" add blocks

- set strip to Neopixel at pin P0 with 24 leds as RGB (GRB format)
- strip show color red

Error: The simulator shows a strip of green LEDs

**Expected behavior**
The simulator should show a strip of red LEDs

**Screenshots**
Neobug1.png 

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome
 - Version: 81.0.4044.122 

**Additional context**
I haven't downloaded the code to see it working on a real strip of lights

<img width="960" alt="neobug1" src="https://user-images.githubusercontent.com/5673444/80768307-f3583200-8b41-11ea-9b97-0eccb1797b4b.png">

**Comment by pelikhan** [comment]
The simulator currently only support RGB_RGB layout. Need to make it smarter.

**Comment by pelikhan** [comment]
Fix in https://github.com/microsoft/pxt-microbit/pull/3129 . Will have to ship the editor to completely fix this.

**Comment by abchatra** [comment]
Fuxed
