### ISSUE TITLE
Blockly setText outdate

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2947]
We have 2 instances of using setText in pxt.

- [ ] https://github.com/microsoft/pxt/blob/a4999f42aa24d69c8486272a315358cd73ee0266/pxtblocks/fields/field_melodySandbox.ts
- [ ] https://github.com/microsoft/pxt/blob/f9d7fd1aff72690d9350b5a62ed55eece7042231/pxtblocks/blocklyloader.ts

**Comment by pelikhan** [comment]
Minecraft triggers the 2nd

![image](https://user-images.githubusercontent.com/4175913/80813791-8b284100-8b7f-11ea-8cdc-0a2d6893b875.png)

**Comment by abchatra** [comment]
I don't know how to triage this. Is this minecraft only bug?

**Comment by shakao** [comment]
ah, melody one will apply to microbit as well for invalid strings. i will take a look
