### ISSUE TITLE
monaco toolbox descriptions selectable on safari

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2949]
**Describe the bug**

looks like they just need the no-select class

![2020-05-01 10 57 12](https://user-images.githubusercontent.com/5615930/80828839-d4d25500-8b9a-11ea-8a22-ada148b51169.gif)

**To Reproduce**
1. Go to monaco editor
2. open toolbox
3. click and drag on fn description

**Expected behavior**

should be not selectable, as it gets highlighted when you drag out depending on start location

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: safari

**Comment by abchatra** [comment]
Won't fix.
