### ISSUE TITLE
python global variable causes invisible error

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#2951]
This program fails but produces no visible error:
![2020-05-01 10 58 02](https://user-images.githubusercontent.com/6453828/80829011-2a0e6680-8b9b-11ea-9762-f00cc7bb0c46.gif)

Switching to Javascript shows the error:
<img width="633" alt="Screen Shot 2020-05-01 at 10 58 13 AM" src="https://user-images.githubusercontent.com/6453828/80829042-3c88a000-8b9b-11ea-87f9-01f3895a5e48.png">

**Comment by abchatra** [comment]
fixed.
