### ISSUE TITLE
Error List and Debug Extension Code experiments missing icons

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2957]
**Describe the bug**

These two experiments are missing icons in the experiments page. Need screenshot / etc to give indication of what it adds

**To Reproduce**
1. go to about, click experiments, see all available experiments.
2. see two are missing icons

@hristoramirez  if you wanna add the one for error list, just a screenshot of the current state for the error list is probably good; just needs a file dropped here: https://github.com/microsoft/pxt-microbit/tree/master/docs/static/experiments

**Comment by abchatra** [comment]
Some more with missing icons.

**Comment by ganicke** [comment]
RE: #4023
