### ISSUE TITLE
indentation off for line following gray block after decompilation 

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#2962]
**Describe the bug**

indentation off after compiling blocks -> typescript

**To Reproduce**
1. Go to https://makecode.microbit.org/_MRAJVE2zPWPr
2. open in editor
3. switch from blocks to javascript
4. See error -- the second `basic.showNumber(0)` immediately after gray block has no indentation

**Expected behavior**
should have proper indentation

**Additional context**
repros on live and beta

**Comment by abchatra** [comment]
Won't fix.
