### ISSUE TITLE
incorrect suggestion when declaring a function

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2964]
Suggesting "Function"

![image](https://user-images.githubusercontent.com/4175913/80846002-d5c9ad80-8bbf-11ea-8b2d-b4a76a475681.png)

VS Code is not much better

![image](https://user-images.githubusercontent.com/4175913/80846062-fb56b700-8bbf-11ea-9bae-e4d0f2ef44e2.png)

**Comment by abchatra** [comment]
Fixed
