### ISSUE TITLE
Trying to move to python fails silently

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2965]
I have a simple typo and trying to switch from js to python silently fails.

![e82ed1ba-424d-4f81-bbf6-d04f7ca6ca0e](https://user-images.githubusercontent.com/4175913/80846145-3b1d9e80-8bc0-11ea-9b7e-103b9aec7cda.gif)

**Comment by jwunderl** [comment]
related, if it fails to compile it still changes editor preference to python

I think this can be bundled into the same fix, but if not I'll file separately

![mkcd (5)](https://user-images.githubusercontent.com/5615930/81134163-c53f6d00-8f08-11ea-9e26-e18c64ea57d9.gif)
