### ISSUE TITLE
Missing strings for the two new music blocks

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-microbit#2967]
The Strings for the new music blocks are missing for translation.

![Unbenannt](https://user-images.githubusercontent.com/37311672/80858391-57b9e500-8c59-11ea-9fea-678c63a06c47.png)

**Comment by abchatra** [comment]
This needs to be added in crowdin. This is not a product bug. Translations will appear as and when they are added to crowdin.

**Comment by pelikhan** [comment]
There should be a “translate this block” item there.

**Comment by pelikhan** [comment]
Uploading docs is disabled on master so these strings are not visible.

**Comment by abchatra** [comment]
Fixed?

**Comment by pelikhan** [comment]
Fixed
