### ISSUE TITLE
Start value for for-loop

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-microbit#2968]
Feature request:

Especially for arrays it would be nice to add the possibility for a start value.

![Unbenannt](https://user-images.githubusercontent.com/37311672/80858526-03633500-8c5a-11ea-9498-f66d18de24b6.png)

btw. when I open a feature request at Github it appears as issue.

**Comment by philipphenkel** [comment]
We have a workaround implemented here: https://github.com/1010Technologies/pxt-makerbit-pins/blob/master/loops.ts
Native MakeCode support would be great!

**Comment by shakao** [comment]
closing as duplicate of https://github.com/microsoft/pxt-microbit/issues/3837 (further updates to be tracked in that issue!)
