### ISSUE TITLE
Right contextmenu doesn´t work in beta in some languages

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-microbit#2969]
**Describe the bug**
the contextmenu for snapshoot, reorder ... doesn´t work in beta V2.3.41
But onlny in some languages like arabic, german, greek, dansk...
In english, french and italian it works!

**To Reproduce**
tested on Windows 10, Edge, Chrome and Firefox
change language to one of the above languages

**Comment by abchatra** [comment]
Nice bug. I can reproduce in German. Right click on workspace is not working.
