### ISSUE TITLE
Better organization for Music blocks

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2971]
Hal suggests adding subcategories to the Music Toolbox drawer for better organization:
**Tone**
•	play tone [note] for [duration]
•	ring tone (Hz) [note]
•	rest (ms) [duration]
•	 [note]
**Melody**
•	start melody [melody] repeating [duration]
•	play melody [sequencer] at tempo [value] bpm
•	stop melody [all]
•	music on [event]
**Volume**
•	set volume [value]
**Tempo**
•	[duration] beat
•	tempo (bpm)
•	change tempo by (bpm) [value]
•	set tempo to (bpm) [value]

![image](https://user-images.githubusercontent.com/22108954/80931024-3d246080-8d6c-11ea-99c8-2160cec281fc.png)

**Comment by pelikhan** [comment]
See https://github.com/microsoft/pxt-microbit/issues/2971

**Comment by abchatra** [comment]
Fixed

**Comment by microbit-mark** [comment]
Not sure I agree that 'start melody' is an advanced feature? It seems simpler than creating a melody sequence from scratch ![Screenshot 2020-05-05 at 10 53 06](https://user-images.githubusercontent.com/31242877/81054389-a87e4780-8ebe-11ea-8062-1b2990559886.png)

The in initial set of melodies is common across MakeCode and MicroPython, so if you move between the two, you have a consistent experience. Could we not address this https://github.com/microsoft/pxt-microbit/issues/2835 by having 'play melody' as the old block and 'play melody sequence' as the new one. @halspeed @jaustin

**Comment by pelikhan** [comment]
We want to encourage kids to craft their own melodies, not just pick one from a list. It is “hard fun”. The other blocks are still there, but lower in the list.

**Comment by microbit-mark** [comment]
Revisiting this as we discussed not calling this section 'Advanced` @abchatra @Jaqster 
Also stop Melody still works with the play melody blocks, so it doesn't seem to make sense to hide it. Could we use a 'more' section for the older block?

Also, resource authors may be referencing the `start Melody` block and if they find `play Melody` first they might mistakenly use this which could cause confusion

**Comment by abchatra** [comment]
Is it ok to rename this to "More"?

**Comment by microbit-mark** [comment]
Re-opening so we can discuss outside the calls @halspeed @jaustin

**Comment by abchatra** [comment]
Fixed
