### ISSUE TITLE
bad intellisense suggestions on param of user-defined type (Rule)

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt-microbit#2977]
See https://makecode.microbit.org/_FtMfpAA6XeqJ

Go to function foo at the end of the file (with formal parameter r of type Rule) and try "r." to see bad suggestions, like:

![image](https://user-images.githubusercontent.com/10767146/81033440-8a760000-8e48-11ea-97a9-143b3233edfd.png)

**Comment by darzu** [comment]
Specifically enums don't work well:
![image](https://user-images.githubusercontent.com/6453828/81972650-c3943a00-95d7-11ea-9ac8-b70ad9ad4906.png)

interfaces, namespaces  and classes seem to work fine.

**Comment by darzu** [comment]
This is mostly fixed. It's true you'll get bogus in that example but only because the class has no members so intellisense defaults to showing you global scope things. 

![2020-05-14 15 32 56](https://user-images.githubusercontent.com/6453828/81992469-5b098500-95f8-11ea-9e4b-d760ec72610e.gif)

**Comment by darzu** [comment]
Fixed it to not show bogus members when there are members.
