### ISSUE TITLE
Cannot assign the enum value with value from another enum.

### ISSUE THREAD

**Issue by waiweng83** [microsoft/pxt-microbit#2978]
**Describe the bug**
There is error whenever I tried assigning other enum value to my own enum in javascript.

**To Reproduce**
1. Click on the Javascript Tab.
2. Type the following code:
`enum MyPin {
    Pin1 = DigitalPin.P14,
    Pin2 = DigitalPin.P15,
}`

**Expected behavior**
This works on the released version but not the beta version.

**Screenshots**
![image](https://user-images.githubusercontent.com/6369012/81037953-0fa7f600-8ed7-11ea-9c1c-35642f59bda6.png)

**Comment by pelikhan** [comment]
This is probably due to the typescript upgrade.

**Comment by waiweng83** [comment]
Is there any workaround? I'm using that extensively in my extension.

**Comment by jwunderl** [comment]
This is pretty weird. If you invoke any digital pin before assigning in the enum it works:

```typescript
DigitalPin.P0
enum MyPin {
    Pin1 = DigitalPin.P14,
    Pin2 = DigitalPin.P15,
}
```

this still fails:

```typescript
enum MyPin {
    Pin1 = DigitalPin.P14,
    Pin2 = DigitalPin.P15,
}
DigitalPin.P0
```

(for now this will fix things, but I don't think it's worth adding as we need to fix it on our side for sure)

**Comment by riknoll** [comment]
This is the part of the code causing the issue: https://github.com/microsoft/pxt/blob/master/pxtcompiler/emitter/driver.ts#L260

If you call getSemanticDiagnostics() on all files, it returns no errors. If you call it on the specific file, you get the error. Seems like a bug in the TypeScript compiler, or maybe it expects you to call it on the files in a certain order. In any case I don't think there is way for us to fix this without defeating the purpose of the incremental compile. We can't really "detect" this situation.

@mmoskal any thoughts? How much worse is perf if we always get diagnostics on all files?

**Comment by mmoskal** [comment]
I guess you would have to measure, maybe it's fine to ask for diags on all files?

I think ?compile=time will give you some stats.

**Comment by pelikhan** [comment]
Maybe try a single file first, then try all of it has errors?

________________________________

**Comment by riknoll** [comment]
@pelikhan I was thinking the same thing. Let me see what the timing looks like

**Comment by riknoll** [comment]
Yeah, it's about twice as fast with the incremental check (I'm using my holodate arcade game for testing, which is pretty large). Not much difference for micro:bit projects because there is just so much less TS

**Comment by mmoskal** [comment]
you should probably try on a small arcade game - then the time spent checking the library will be more dominating...

**Comment by riknoll** [comment]
Using a smaller arcade game (space destroyer) the diagnostic time is ~60ms as-is and ~75ms without the incremental check. This is with 6x CPU throttling on my mac (which in my experience is still significantly faster than a chromebook).

Seems like an acceptable change to me; big projects will suffer more. Probably doesn't matter for micro:bit perf.

**Comment by mmoskal** [comment]
Agreed.
