### ISSUE TITLE
Variable view does not scroll or expand

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2979]
It is not possible to drill deep into objects as the video does not scroll.
![image](https://user-images.githubusercontent.com/4175913/81042251-8d7ee980-8e64-11ea-898c-816d52c1cc77.png)

**Comment by abchatra** [comment]
Clicking or hover on the variable shows everything right?

**Comment by pelikhan** [comment]
Nothing happens.
