### ISSUE TITLE
Right click to download snapshot does not work

### ISSUE THREAD

**Issue by ChrisDorna** [microsoft/pxt-microbit#2981]
**Describe the bug**
Right click to download snapshot does not work

**To Reproduce**
1. a project
2. right click

**Expected behavior**
List of possibillities
![image](https://user-images.githubusercontent.com/20975602/81067619-379b5780-8edf-11ea-9bda-76094efa6eac.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81

**Comment by pelikhan** [comment]
Did a pop blocker stop this download by any chance?

**Comment by ChrisDorna** [comment]
Nope, it works ok in the current version of the editor

**Comment by abchatra** [comment]
I can't reproduce this.

**Comment by ChrisDorna** [comment]
Problem does not occur now
