### ISSUE TITLE
Must restart simulator after changing volume

### ISSUE THREAD

**Issue by ChrisDorna** [microsoft/pxt-microbit#2982]
**Describe the bug**
When I change the volume I must restart the simulator to hear the sound

https://makecode.microbit.org/_0DUKHH2vW7jX

**To Reproduce**
1. Create project with audio
2. Set the volume within On start
3. Start simulator
4. Change volume

**Expected behavior**
Expected to hear change in volume imidiately

**Screenshots**
https://makecode.microbit.org/_0DUKHH2vW7jX

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by pelikhan** [comment]
This is a good bug. The sound volume is leaked in the AudioContextManager.

**Comment by pelikhan** [comment]
I've reviewed the code and I'm not sure what the problem is.

**Comment by riknoll** [comment]
I can't reproduce the issue. What do you mean exactly by "change volume" in step 4? If I change the volume in the code, it works for me.

**Comment by abchatra** [comment]
Yes change volume in the code. 

@pelikhan where you able to reproduce this issue?

**Comment by pelikhan** [comment]
I don’t understand the bug.
