### ISSUE TITLE
Radio across browsers for remote users

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2983]
> micro:bit support: 37297

**Is your feature request related to a problem? Please describe.**
"At this moment it’s no possible to teach a programming lesson with real hardware.
The functionality of Bluetooth/radio connection between the real microbit is not possible."

**Describe the solution you'd like**
"So I was thinking if it’s possible to let the microbit simulator connect to the microbit simulator of [another remote user]. So even the student doesn’t have a physical micro:bit... they can use the simulator together."

https://makecode.com/multi exists to let one user  simulate a radio experiece across two instances of the editor. Could this be developed to let two remote users try out radio, presumably some synchronous connection would need to still take place ie a video link.

**Comment by abchatra** [comment]
No plans to address this issue.
