### ISSUE TITLE
When setting an individual neopixel up in python, default strip name is my_strip

### ISSUE THREAD

**Issue by Lorrainbow** [microsoft/pxt-microbit#2984]
**Describe the bug**
When I use the block 
**strip set pixel color at 0 to red** 
in python, python tries to use the variable my_strip which doesn't exist and causes an error

**To Reproduce**
1. Add the Neopixel extension
2. Click on the Python tab
3. Scroll down to Neopixel and setup your strip using the block "Neopixel at pin pin with 24 leds as mode". This creates the line of code
**strip = neopixel.create(DigitalPin.P0, 24, NeoPixelMode.RGB)**
4. Select Neopixel, More and select "strip set matrix color at x x y y to rgb" and drag it onto the screen. This creates the line of code
**my_strip.set_matrix_color(0, 0, neopixel.colors(NeoPixelColors.RED))**

**Expected behavior**
I expect the second line of code to be editing the variable strip that was created in the first line of code. 

**Screenshots**
<img width="960" alt="neopixelbug2" src="https://user-images.githubusercontent.com/5673444/81111177-90d1ae00-8f14-11ea-95f2-622c2580a619.png">

OS: Windows10
Browser: Chrome
Version: 81.0.4044.122

**Comment by abchatra** [comment]
Nice bug @Lorrainbow
