### ISSUE TITLE
Piano editor is broken

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#2987]
**To Reproduce**
1. Drag play note  block from music
2. Try to set the right tone
3. See piano editor doesn't pop up and you see left over UI elements

**Screenshots**
![musicbroken](https://user-images.githubusercontent.com/6107272/81215441-370dca00-8f8e-11ea-9370-a4904600b067.gif)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: New Edge

**Comment by abchatra** [comment]
Seems like a recent regression.

**Comment by abchatra** [comment]
@shakao - fyi

**Comment by shakao** [comment]
i can take a look, i think it's probably related to the block resizing
