### ISSUE TITLE
Lack of the Math category and randomRange block in all tutorials

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#2991]
**Describe the bug**
Lack of the Math category and randomRange block in all tutorials

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Tutorials-->Dice->start tutorial
3.Click step 4

**Expect behavior**
There should add the Math category and randomRange block

**Actual behavior**
Lack of the Math category and randomRange block, this bug also reproduces in other tutorials
![image](https://user-images.githubusercontent.com/58197774/81247572-f0cb7000-904c-11ea-84c0-b29b412e31d2.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.45
3.Microsoft MakeCode version: 5.37.56
4.JavaScript tutorials and Python tutorials have the same issue

**Comment by jwunderl** [comment]
Hm, we can't change them to be randint until the release... @riknoll we've run into this a few times, maybe it makes sense to ignore the deprecated flag in tutorials?

**Comment by abchatra** [comment]
Yes we need to prep the PR and release it when we release microbit.

**Comment by riknoll** [comment]
Yes, we should ignore it in tutorials. If it's in the markdown it should be in the tutorial
