### ISSUE TITLE
The corresponding results not ranked first searching by keyword

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2992]
**Describe the bug**
The best match not ranked first searching by keyword

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.My Projects---->View All
3.Search by keyword "Heads"

**Expect behavior**
The best match ranked first searching by keyword. 
For example, when I search by "Heads", "Heads Guess" should rank first not "Flashing Heart".

**Actual behavior**
The best match not ranked first searching by keyword
![1](https://user-images.githubusercontent.com/59192069/81249797-1eff7e80-9052-11ea-95e5-0370e93fb74e.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.45
3.Microsoft MakeCode version: 5.37.56

**Comment by abchatra** [comment]
We do fuzzy search (not exact match) as students usually have typos. Won't fix from our end.
