### ISSUE TITLE
No Math.random_range( ) intellisense in python editor

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2994]
**Describe the bug**
No Math.**random_range( )** intellisense in python editor

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Tutorials---->Dice---->Python Start Tutorial
3.Click step 4
4.Type **Math.** or **Math.random**

**Expect behavior**
Math.**random_range( )** intellisense when typing **Math.** or **Math.random**

**Actual behavior**
No Math.**random_range( )** intellisense
![2](https://user-images.githubusercontent.com/59192069/81271543-d611ef00-907e-11ea-9574-69e84911d521.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.45
3.Microsoft MakeCode version: 5.37.56

**Comment by abchatra** [comment]
Math.random_Range deprecated and is replaced by global randint(0, 10) in recent builds. Tutorials are being updated.  Tutorial will be fixed once the /beta editor goes live.
