### ISSUE TITLE
Monaco sidedocs cover entire editor

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#2995]
**Describe the bug**
![image](https://user-images.githubusercontent.com/34112083/81316767-d8555880-9040-11ea-9ae6-217e936e3128.png)

We do 50% of the screen which was okay for Minecraft (no simulator) but feels kind of big here

**Comment by abchatra** [comment]
I don't not sure this is important. They can always minimize it after reading help doc. I will leave it to you to fix it or not.
