### ISSUE TITLE
Some localized extensions stay in german

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-microbit#2998]
**Describe the bug**
Some localized extensions stay in german when you switch to english again in makecode beta 2.3.45

**To Reproduce**
load neopixel extension
switch to german
switch to english again
neopixelstrings stay german :-(
![grafik](https://user-images.githubusercontent.com/37311672/81325615-e9ca4f00-9098-11ea-935b-8e10fa396949.png)
Tested on Win 10, Firefox, Chrome, Edge
sorry, german bug again.

**Comment by abchatra** [comment]
I can't reproduce this. Can you try again?

**Comment by MKleinSB** [comment]
cleaning the browsercache cleans it! Sorry.
