### ISSUE TITLE
music blocks - blocks to JS

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#3]
music blocks - blocks to JS

1 in reference to the light beatbox lesson

http://localhost:3232/lessons/light-beatbox/activity

2 enter this code with blocks

```
let light = 0;
input.onButtonPressed(Button.A, () => {
    music.rest(music.beat(BeatFraction.Sixteenth));
    light = input.lightLevel();
    if (light < 25) {
        music.ringTone(music.noteFrequency(Note.C));
    }
    else {
        music.ringTone(music.noteFrequency(Note.A));
    }
});
```

3 press convert. 

4 i would expect the code to be equal to the following when using ringTone using JS without Blocks

```
input.onButtonPressed(Button.A, () => {
    music.rest(BeatFraction.Sixteenth)
    let light = input.lightLevel()
    if (light < 25) {
        music.ringTone(Note.C)
    }
    else {
        music.ringTone(Note.C);
    }
})

```
4 however, the conversion is not 1:1. Am i missing something when using music with JS vs using music  with blocks ?

**Comment by pelikhan** [comment]
Fixed.
