### ISSUE TITLE
catch the egg lesson - code not rendering

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#30]
catch the egg lesson - code not rendering - it works in simulator

catch the egg lesson ... 

go to

http://localhost:3232/lessons/catch-the-egg-game/activity

![image](https://cloud.githubusercontent.com/assets/11206682/14161042/56c08e14-f695-11e5-979b-701739360add.png)

**Comment by pelikhan** [comment]
Issue with Math.min. Investigating.

**Comment by pelikhan** [comment]
The seconds snippet uses function that are not in blocks.
