### ISSUE TITLE
serial.readLine waits for \n and not \r

### ISSUE THREAD

**Issue by sjmurdoch** [microsoft/pxt-microbit#3003]
The [documentation for serial.readLine()](https://makecode.microbit.org/reference/serial/read-line) indicates that the function waits until a \r character before returning. Actually it seems to wait for a \n. At least on MacOS, using screen as recommended, the delimiter sent by pressing enter will be \r and so readLine() will appear to not work. 

As can be seen from the [source of readLine()](https://github.com/microsoft/pxt-microbit/blob/32a7cc0d00f9f384782380c64f345093081c6b7f/libs/core/serial.ts#L91), this function calls readUntil() with a [delimiter of “\n”](https://github.com/microsoft/pxt-microbit/blob/32a7cc0d00f9f384782380c64f345093081c6b7f/libs/core/serial.ts#L105).

For me, calling readUntil() directly with “\r” directly fixed the issue with screen on MacOS. I however have not tested what would happen with other serial terminal software and/or other operating systems.

**Comment by pelikhan** [comment]
Fix deployed in beta. please test if this works for me. You should be able to change NEW_LINE_DELIMITER for your Mac.

**Comment by sjmurdoch** [comment]
If I set `serial.NEW_LINE_DELIMITER` to `Delimiters.CarriageReturn` then `serial.readLine()` works fine using screen on MacOS X. Thanks for sorting this out so quickly.
