### ISSUE TITLE
Clicking on an error sends to line 1

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3005]
https://makecode.microbit.org/_HTUKFCXvHefg

Should go to line 5, but goes to line 1 instead.

![image](https://user-images.githubusercontent.com/4175913/81488280-a3512d80-921b-11ea-95ce-4b7e2b37de6b.png)

**Comment by darzu** [comment]
Thanks @pelikhan . Feel free to assign error list stuff directly to @hristoramirez . @hristoramirez , if you have questions about issues that get filed, feel free to reach out directly to the issue creator

**Comment by hristoramirez** [comment]
@pelikhan when I place the cursor at the end of the error I use the endLine and endColumn properties of the error. I looked at the errors that were generated and python errors have these properties, while errors in javascript don't.

**Comment by pelikhan** [comment]
I would expect to be takened to line 5 since this is what the error list is displaying.
