### ISSUE TITLE
Error in Extensions screen using firefox on Win10

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-microbit#3006]
With the latest betarelease 2.3.50  there is an error in extensions screen in Firefox Win 10. Somtimes it´s correct, but mostly not. When you try scrolling the error is getting worse.
Chrome and Edge works correct.

![grafik](https://user-images.githubusercontent.com/37311672/81501703-099c8580-92da-11ea-8cd1-3c6318949dce.png)

**Comment by abchatra** [comment]
What is the firefox version? I am unable to reproduce on firefox 76 on windows. 
Also can you try in-private mode and see if the issue persists. 

These local extensions might be causing the issues.

**Comment by MKleinSB** [comment]
Tested in private mode on Firefox 76.0.1 (64-Bit)
Problem only appears on one of my PCs so I think it´s a problem of my Computer.
