### ISSUE TITLE
Excessive margin in blocks editor

### ISSUE THREAD

**Issue by Geoffree3** [microsoft/pxt-microbit#3007]
**Describe the bug**
As I've reported before, I think it is unnecessary to automatically add a margin to the top and left of any code, so the blocks are indented. It just wastes screen space and is confusing when blocks seem to shift down and to the right.  But, now this auto-indent appears to have gone into overdrive (see screenshot)!

**To Reproduce**
'Format code'
zoom out ('-') to try to see all the blocks

**Expected behavior**
No margin is added to the top or left.  It is unnecessary and would stop this behaviour.

**Screenshots**
<img width="1225" alt="Screenshot 2020-05-10 at 18 56 47" src="https://user-images.githubusercontent.com/3199856/81506817-f9dc6b80-92f0-11ea-86fa-3dbd64e592c7.png">

**Desktop (please complete the following information):**
 - MacOS 10.14.6
 - Chrome
 - 81.0.4044.129

**Comment by abchatra** [comment]
I don't understand this issue.

We center the code. You can pan the code wherever you want. It is supposed to be infinite on all directions.

**Comment by Geoffree3** [comment]
What you do is centre the top left corner of the top left block, this is not centering the code blocks as a whole.  Even worse, the extra margins you add after each 'centering' are cumulative so that, as in the screen shot, all blocks move to the bottom right corner.   Of course, the user can keep using the scroll bars to bring the blocks back into view, but after each adjustment or reformatting?  It's unnecessary and annoying.  I just cannot see how this is useful to the user. Just turn off your 'centering' and let the user position their blocks on the canvas.   The 'reformat code' should bring as many blocks as possible into view, but the best it can do is put them all in the bottom right quarter (as screenshot). 

<img width="1035" alt="4" src="https://user-images.githubusercontent.com/3199856/81546567-75323180-9372-11ea-9162-fa37dea7a4ec.png">

**Comment by pelikhan** [comment]
The format code operation should also update the view. I think what happens is that we move all the blocks but we don't recenter/fit screen the view.

**Comment by Geoffree3** [comment]
Yes, reformat should try to fit the screen.  However, you must fix ‘recenter’ as currently this pushes the code to the bottom right and means the user has to keep using the scroll bars to get back to see the blocks. Surely it would be less confusing if it fitted to the top left corner and not emulate an infinite canvas in all directions.

**Comment by Geoffree3** [comment]
Reformat works fine now as blocks are moved to upper left.  However, adding a new function displays the old behaviour (as below)!   Please check.
<img width="1043" alt="Screenshot 2020-05-16 at 11 20 11" src="https://user-images.githubusercontent.com/3199856/82117484-10a71600-9768-11ea-9740-8360cf41cf3c.png">
