### ISSUE TITLE
Something wrong on tutorial Squre

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3010]
**Describe the bug**
Something wrong on tutorial **Squre**

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Turtle--->Square

**Expect behavior**
Tutorial can be opened normally

**Actual behavior**
As soon as the tutorial opens, there will be a point in the center of the simulator.
![1](https://user-images.githubusercontent.com/59192069/81541398-9c562680-93a5-11ea-9bd1-e8a679b105e9.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.50
3.Microsoft MakeCode version: 5.37.61

**Comment by abchatra** [comment]
This is how the turtle extension works. There is a dot which you are supposed to move.
