### ISSUE TITLE
'random value' block is the wrong color in some tutorials

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#3011]
**Describe the bug**
'random value' block is the wrong color in some tutorials

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Game->Hot Potato
3.Step one by one

**Expect behavior**
'random value' block should be purple in all tutorials.

**Actual behavior**
'random value' block is orange in some tutorials.
![image](https://user-images.githubusercontent.com/58197774/81543742-176d0c00-93a9-11ea-8af2-e3459c0ec406.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.50
3.Microsoft MakeCode version: 5.37.61

**Comment by abchatra** [comment]
Fixed
