### ISSUE TITLE
Error ‘Program Error: sim error: noresume' pops up when restarting the simulator in 'Snap the dot'

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#3012]
**Describe the bug**
Error ‘Program Error: sim error: noresume' pops up when restarting the simulator in 'Snap the dot'

Steps to reproduce the behavior
1.Navigate to https://makecode.microbit.org/beta#
2.Game ->Snap the dot
3.Step one by one

**Expect behavior**
No error pops up when restarting the simulator

**Actual behavior**
This bug is unstable, If try many times, Error ‘Program Error: sim error: noresume' will pop up when restarting the simulator.
![error](https://user-images.githubusercontent.com/58197774/81546389-e098f500-93ac-11ea-9bf2-3a1182dfbd6c.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.50
3.Microsoft MakeCode version: 5.37.61

**Comment by pelikhan** [comment]
This is a simulator issue.

**Comment by riknoll** [comment]
Minimal repro:

```ts
basic.forever(() => {
    basic.pause(1);
})
```

It's being triggered by the game package which has a call to `forever` with a very short pause time. I think it might have something to do with overlapping executions because it always happens at the beginning of the program. I'm gonna see if checking the runtime fixes it
