### ISSUE TITLE
Instruction and hint are inconsistent on tutorial Level

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3013]
**Describe the bug**
Instruction and hint are inconsistent on tutorial **Level**

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Turtle--->Square
3.Click step 6

**Expect behavior**
Instruction and hint are consistent on tutorial **Level**

**Actual behavior**
Instruction and hint are inconsistent on tutorial **Level**
**Instruction**: show a **happy** image
**hint**: show a **square** image
![image](https://user-images.githubusercontent.com/59192069/81547675-c2cc8f80-93ae-11ea-8081-6170b923254c.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.50
3.Microsoft MakeCode version: 5.37.61

**Comment by Sheila111** [comment]
@pelikhan  Python and JS tutorial also need to be fixed.
![image](https://user-images.githubusercontent.com/59192069/82420203-ff387380-9ab1-11ea-801b-36b72692d4a7.png)

**Comment by Sheila111** [comment]
Python tutorial still not fixed.
![image](https://user-images.githubusercontent.com/59192069/83112890-6c26bb80-a0f9-11ea-90ec-b81e5540fddb.png)

**Comment by ganicke** [comment]
Please test with anonymous/incognito window. Your tutorial content is cached. The source document shows the change:

https://makecode.microbit.org/projects/spy/level

![image](https://user-images.githubusercontent.com/27789908/83167316-eee15380-a0c4-11ea-9934-016b68ff9df9.png)
