### ISSUE TITLE
The moving step is not accurate in tutorial 'Tug-Of_LED'

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#3025]
**Describe the bug**
The moving step is not accurate in tutorial 'Tug-Of_LED'

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Game->Tug-Of_LED
3.Step one by one

**Expect behavior**
1. The dot should move one step after clicking button A 10 times.
2. Everything should be normal when restarting the simulator

**Actual behavior**
1. The dot move one step after clicking button A 1 time. If changing rope by -1, the situation is same as before.
2. The dot will flash when restarting the simulator
![exactly](https://user-images.githubusercontent.com/58197774/81634844-54d1a800-9442-11ea-9714-c7379e795fcf.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.52
3.Microsoft MakeCode version: 5.37.62

**Comment by pelikhan** [comment]
I don't understand the bug.

**Comment by KellyLuo1** [comment]
@pelikhan Sorry, maybe I didn't express clearly.
1. In step 4, if **button A** pressed, then change rope by **-0.1**.
 So the dot should move **one step** when clicking button A **10 times**, But the dot moves **one step**  when clicking button A only **one time**.
![new](https://user-images.githubusercontent.com/58197774/81644737-e6e5aa80-945a-11ea-89c1-8d685b9f85c3.gif)

2. The dot flashes **back and forth** when **restarting** the simulator
![exactly](https://user-images.githubusercontent.com/58197774/81644939-3f1cac80-945b-11ea-84e0-a0244c130dc2.gif)

**Comment by Sheila111** [comment]
@ganicke ,    **Block tutorial** still has this issue:  
In step 4, If you want the dot to **move left** one step, you just need to click **button A only 1 time**, But if **moving right**, you need to click **button B 10 times**.
![1](https://user-images.githubusercontent.com/59192069/96838822-eece5f80-147a-11eb-86e3-114086ff3b5e.gif)

**Comment by ganicke** [comment]
Ah ok, this was only fixed for the ``spy`` version in #3138.

**Comment by Sheila111** [comment]
So **Block tutorial** also need to be fixed.  @ganicke

**Comment by ganicke** [comment]
@Sheila111 - I think so. I'll look at it today and make a fix. Thanks.
