### ISSUE TITLE
Adding custom.ts triggers null reference in compiler

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3027]
This is a race.
- add a custom.ts file to project
- notice "install error" which is masking the real error in the compiler

![image](https://user-images.githubusercontent.com/4175913/81637374-ff0de900-93ca-11ea-9a16-277f30924182.png)

**Comment by pelikhan** [comment]
![image](https://user-images.githubusercontent.com/4175913/81637729-ece07a80-93cb-11ea-85dc-b18233317168.png)

**Comment by abchatra** [comment]
Removing next-release flag. Let me know if you disagree.

**Comment by pelikhan** [comment]
This happens for any file added to pxt.json

**Comment by pelikhan** [comment]
Then the editor is in a broken state and requires a reload

**Comment by abchatra** [comment]
Any luck looking at this @mmoskal ?

**Comment by pelikhan** [comment]
let me take a peek

**Comment by abchatra** [comment]
Fixed
