### ISSUE TITLE
Support for errors in different files

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3028]
The error list should gracefully handle errors in a file that is **not** the current file:
- [ ] all errors in the project should be show
- [ ] errors in a different file than the current one should be sorted down
- [ ] needs a wording to specify that they are in a different file

![image](https://user-images.githubusercontent.com/4175913/81637995-9de71500-93cc-11ea-85cd-1db2d53ec957.png)

**Comment by darzu** [comment]
I agree, this would be useful.
Lower priority I think than supporting blocks errors and runtime errors.

**Comment by abchatra** [comment]
fixed
