### ISSUE TITLE
Multiple tab issue with WebUSB

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#3033]
**To Reproduce**
1. Open a tab with "Makecode.microbit.org/beta"
2. Pair the device using webusb
3. Download and see if the connection works.
4. Now open a second tab with beta and connect to same device.

**Expected behavior**
Fails with a error message.

**Actual behavior**
Fails silently.

Message in console
![image](https://user-images.githubusercontent.com/6107272/81773237-b888bf00-949c-11ea-9450-e0541483f08e.png)

**Desktop (please complete the following information):**
Windows
EDge

**Comment by pelikhan** [comment]
Fixed by https://github.com/microsoft/pxt/pull/7017

**Comment by abchatra** [comment]
Fixed
