### ISSUE TITLE
Error when streaming is in session and the tab change occurs

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#3034]
Here are the things I did:
Streamed continuous data through webusb from microbit.
Switched tabs for like 30 seconds
Came back and tried to flash again.

![image](https://user-images.githubusercontent.com/6107272/81773301-df46f580-949c-11ea-876b-e1f2e33b0c21.png)

**Comment by abchatra** [comment]
I am unsure if this could be reproduced easily

**Comment by pelikhan** [comment]
The fix always disconnect on tab change.

**Comment by abchatra** [comment]
Fixed
