### ISSUE TITLE
Beta hangs on iOS 9 and iOS 10

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#3038]
**Describe the bug**
Beta hangs on iOS 9 and iOS 10.
Seems OK on iOS 11, 12, 13.

Tested with
iPhone 6s (iOS 10.3.1),
iPad min gen 1 (iOS 9)
Simulated iPad Air 2 (iOS 10, 11, 12).
iPad Air 2 (iOS 13.3)

**To Reproduce**
1. Go to 'makecode.microbit.org' in Safari
2. Add '/beta' to the path
3. See error

**Expected behavior**
It works or generates an error.

**Screenshots**

![IMG_0005](https://user-images.githubusercontent.com/989126/81802986-ed355e80-950e-11ea-90a6-d0ea554b8249.PNG)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iPad mini gen 1 (iOS 9), Simulated iPad Air 2 (iOS 10)
 - Browser [e.g. chrome, safari] Safari

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 6s
 - OS: [e.g. iOS8.1] iOS 10.3.1
 - Browser [e.g. stock browser, safari] Safari

**Additional context**

**Comment by abchatra** [comment]
@shakao use browserstack for different versions of iOS

**Comment by abchatra** [comment]
This impacts around 1000 users per month on iPad. Repros on iPad iOs10.

**Comment by abchatra** [comment]
Below is the error. 
TypeError: performance.mark is not a function. (In 'performance.mark(t+" start")', 'performance.mark' is undefined)

We might just have to polyfill this function.

**Comment by shakao** [comment]
several of the performance APIs we use (mark, clearMarks, getEntriesByName) are not supported in < iOS11. it looks like they are only used in pxt.perf, to generate the performance report that logs to console, so i was thinking we could just skip those metrics if the performance APIs are not found. 

or maybe we should only print the performance report if there is a debug flag in the URL?

**Comment by pelikhan** [comment]
IMo, results should be logged to the cloud. This is valuable information.
If the api are not present, downgrade to polyfills.

**Comment by abchatra** [comment]
It is already logged into the cloud through application insights. 

Skip these for iOS 9 & iOS10.  They were added to debug the minecraft performance issues in the client machine through console.log

**Comment by abchatra** [comment]
>>  we could just skip those metrics if the performance APIs are not found.

I meant do the above.
