### ISSUE TITLE
In Beta, a user can sign into Github again without re-entering security details

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#3039]
**Describe the bug**
In Beta, a user can sign into Github again without re-entering security details after MakeCode has said it has signed out and has no "Sign out" entry on the "More..." menu.

**To Reproduce**
1. Go to 'https://makecode.microbit.org/beta'
2. Click on 'New project'
3. Click "create Github repository" button
4. Sign in
5. Click "Go ahead" button
6. Wait for repo creation
7. Choose "Sign out" from the "More..." menu.
8. Ignore the "Are you sure you want to sign out?" screen
9. Click "back" or open MakeCode again
10. Note no "Sign out" menu entry
11. Make changes and push to github
12. MakeCode signs in again without re-entering password

**Expected behavior**
MakeCode shouldn't display a "signed out" message before the user is actually signed out. The "Sign out" menu entry should be shown if the user isn't signed out.
Is it possible for MakeCode to take over the "are you sure?" stage and really know that sign out has happened?

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 81.0.4044.138 (Official Build) (64-bit)

**Additional context**

**Comment by abchatra** [comment]
I believe Github caches the authentication and not us.

**Comment by pelikhan** [comment]
This is by design. We give you an ooportunity to sign out from github but we don't know if you are still signed in on that domain.

**Comment by martinwork** [comment]
Thanks @abchatra and @pelikhan . I understand now why you leave it to the user to decide in the browser. It confused me why I was asked if I was sure after I had been signed out. The distinction between MakeCode's stored token and the browser's stored credentials is not obvious. When using a developer token in MakeCode, maybe it's not necessary to prompt for logout from the browser.

In the iOS app, logging in and out of github doesn't seem to affect github or MakeCode in the browser. When signing out of MakeCode, there are no other tabs in the app needing a github connection. So "are you sure" can only make sense if it's about MakeCode signing out. Going back from the "are you sure" page leaves me unable to logout without logging in again, and any subsequent user will get logged into my account. 

When in the webview, can logout bypass the "are you sure" prompt? If not, could MakeCode keep its token intact until it gets a message from the webview app to stay the user has logged out (the app can see the change from /logout to /). Either would make more sense to a user that doesn't understand the details of what's happening.

**Comment by martinwork** [comment]
@pelikhan Should I create a new issue for this?
