### ISSUE TITLE
Debugger breakpoints not stopping in Python

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#3049]
Setting a breakpoint in this program won't stop:

```
for i in range(5):
    for j in range(5):
        led.toggle(i, j)
        basic.pause(100)
```

![2020-05-13 09 55 12](https://user-images.githubusercontent.com/6453828/81841874-ea7f3d00-94ff-11ea-975d-cc71fc4ae949.gif)

**Comment by riknoll** [comment]
a little more detail: you need to press the refresh button for this to repro
