### ISSUE TITLE
It can still add or cancel the breakpoint when mouse under this breakpoint

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3060]
**Describe the bug**
It can still add or cancel the breakpoint when mouse under this breakpoint

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#editor
2.Add a breakpoint
3.Mouse under this breakpoint and click

**Expect behavior**
It should add a new breakpoint

**Actual behavior**
This operation just cancel the breakpoint above. 
![1](https://user-images.githubusercontent.com/59192069/82033689-acd10e80-96cf-11ea-841d-4103660cbf35.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.59
3.Microsoft MakeCode version: 5.37.71

**Comment by abchatra** [comment]
won't fix. P3
