### ISSUE TITLE
Beta on Android Chrome: Keyboard won't stay open

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#3061]
**Describe the bug**
Cannot use the keyboard to enter text. The keyboard opens, but closes immediately.

**To Reproduce**
1. Go to 'https://makecode.microbit.org/beta'
2. Click on 'New project'
3. Try to edit the project name
4. Keyboard opens, but closes immediately

**Expected behavior**
Keyboard should be usable.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Android 8.1 on Samsung SM-T580
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 81.0.4044

**Comment by jwunderl** [comment]
Hm, this repros across the editor for me in /beta on my phone (galaxy note 9) - e.g. https://makecode.microbit.org/_gzj4A50LUHgm hitting the text shows then hides. This does not happen in minecraft, so it's a relatively recent regression (autocomplete behavior is a bit wonky on android - after i fix this will file an issue / look at that).

For what it's worth, it seems like if you spam tap on the editor it'll pop up the keyboard after a few clicks - meaning its probably a wonky blur or resizing issue

**Comment by abchatra** [comment]
Piano editor also doesn't popup and issues. Might be same bug. Open a new once this is fixed if this not the same bug.
