### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by when-nobody-expects** [microsoft/pxt-microbit#3063]
**Is your feature request related to a problem? Please describe.**
I want to write javascript library for microbit makecode. I wonder how to write tests. I mean something like unit tests. In places where I expected to find tests (https://github.com/microsoft/pxt-microbit/blob/master/tests/hello.ts, https://github.com/microsoft/pxt-microbit/blob/master/tests/hat-game.ts, https://github.com/microsoft/pxt-neopixel/blob/master/neotest.ts) I found something which I rather call “show case”. There are no assertions at all in those files called “tests”. Moreover pxt seems to not have test build task (https://makecode.com/cli). Do you have any plans for support unit tests out of the box?

**Describe the solution you'd like**
Add `pxt test` task and some examples of simple unit tests for libs like core, radio etc.

**Describe alternatives you've considered**
Haven't any :)

**Additional context**
No additional context

**Comment by when-nobody-expects** [comment]
Just like that? I would have been glad if you had commented this in any way. I understand that this kind of feature could not be inline with your vision of project but it would be much more clear for community if you respond in more descriptive than "closed". Please consider this.

**Comment by abchatra** [comment]
Sorry, this was tagged as question and we close unanswered question after 6 months. 

Reading it again this was more of a feature request to add test framework. We don't have a bandwidth at this point of time to add one. If you are willing to help, feel free to send a PR.
