### ISSUE TITLE
[Serial lib] Getting current serial config

### ISSUE THREAD

**Issue by when-nobody-expects** [microsoft/pxt-microbit#3065]
**Is your feature request related to a problem? Please describe.**
I’m writing some lib which communicates using serial. But users should be able to use this lib with applications that are using serial for other purposes. Therefore I would be glad if there be any API to get current serial configuration. Then my lib could be working transparently for user.

**Describe the solution you'd like**
Some API like:
```javascript
export function doSth(message: string, messageLevel: LoggingLevel) {
  let oldTx = serial.currentTx;
  let oldRx = serial.currentRx;
  let oldRate = serial.baudRate;

  serial.redirect(myLibTx, myLibRx, myLibBaudRate);
  doSthWithDevice();
  serial.redirect(oldTx,  oldRx,  oldRate);
}
```

**Describe alternatives you've considered**
```javascript
temporaryRedirect(myLibTx, myLibRx, myLibBaudRate, doSthWithDevice);
temporaryRedirectToUsb(myLibTx, myLibRx, myLibBaudRate, doSthWithDevice);
```

**Additional context**
No additional context

**Comment by abchatra** [comment]
@mmoskal is this feasible through websub?

**Comment by mmoskal** [comment]
I think it's all on the TS side, nothing to do with webusb. We would need to keep track of the pins and expose them. Or else have an API like `temporaryRedirect(rx,tx,baud, () => { ... })`

**Comment by abchatra** [comment]
Oh I misread the issue. Makes sense. This is for an extension to redirect and still restore the old state.

**Comment by when-nobody-expects** [comment]
Yes, @mmoskal is right. I will add his proposition as alternative

**Comment by abchatra** [comment]
We have a workarouond.
