### ISSUE TITLE
Step Counter instructions open editor instead of docs

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#3069]
**Describe the bug**
1. Click on "Step Counter"
2. Click on "Show Instructions" 
3. See editor open instead of docs, empty project with no sidedocs/instructions

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: new Edge

**Comment by abchatra** [comment]
@ganicke I believe this is docs bug. If not let me know.

**Comment by Sheila111** [comment]
**Mood Radio** and **Tele-potato** have the same issue

**Comment by pelikhan** [comment]
Let me look. It should open docs.

**Comment by pelikhan** [comment]
(good bug)

**Comment by pelikhan** [comment]
bug introduced here https://github.com/microsoft/pxt/commit/012cd145fd0009b69d7fe70b458d90619e769f46
