### ISSUE TITLE
No hover help for sprite methods in Python (they work in TS)

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#3070]
Hovering over "move" or "turn" in python gives no hover help:

![2020-05-15 11 17 35](https://user-images.githubusercontent.com/6453828/82082924-b6da1980-969d-11ea-8ee1-5a1b1712f140.gif)
Example:
```
s = game.create_sprite(2, 2)
s.move(1)
s.turn_right(0)
```

It would be nice to have test cases for hover help. Maybe the test case could look like:
```
s = game.create_sprite(2, 2)

s.mo|||ve(1)
```
where `|||` represents cursor position, and the baseline would be:
```
(method) game.LedSprite.turnRight(degrees: number): void
```
or something

**Comment by darzu** [comment]
Doesn't repro in TS
Does repro in PY

IMO, this is important for beginners.

**Comment by shakao** [comment]
no longer repros in /beta!
