### ISSUE TITLE
Creating a github repo triggers error

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#3075]
I opened a new project and tried to create a github repo, but it failed with this error:

Bad HTTP status code: 201 at https://api.github.com/user/repos?anti_cache=0.8712046448937338; message: { "id": 264273001, "node_id": "MDEwOlJlcG9zaXRvcnkyNjQyNzMwMDE=", "name": "untitled", "full_name": "darzu/untitled", "private": false, "owner": { "login": "darzu", "id": 6453828, "node_id": "MDQ6VXNlcjY0NTM4Mjg=", "avatar_url": "https://avatars3.githubusercontent.com/u/6453828?v=4", "gravatar_id": "", "url": "https://api.github.com/users/darzu", "html_url": "https://github.com/darzu", "followers_url": "https://api.github.com/users/darzu/followers",

**Comment by darzu** [comment]
Looks like a 201 which is just "Created" successful so we're probably checking for === 200.

**Comment by pelikhan** [comment]
yes i probably broke this. let me check
