### ISSUE TITLE
rename a variable should edit the current variable name (blocks)

### ISSUE THREAD

**Issue by Geoffree3** [microsoft/pxt-microbit#3076]
**Describe the bug**
Usually when renaming a variable (or any other named object), the dialogue gives the current name for editing. In the block editor, the edit box is empty. Often it just correcting a spelling mistake and is annoying to have to retype it all again.
Note, formatting bug in rename dialogue where part of the variable name is obscured by the 'close icon'.

**To Reproduce**
Rename a variable in blocks editor.  
<img width="562" alt="Screenshot 2020-05-16 at 00 39 16" src="https://user-images.githubusercontent.com/3199856/82104286-2f78be80-970e-11ea-8586-837fa1970994.png">
In this case I just want to add an "s" to the end but have to enter all the text again

**Expected behavior**
Rename should give the current name ready for editing
<img width="562" alt="Screenshot 2020-05-16 at 00 39 45" src="https://user-images.githubusercontent.com/3199856/82104426-c80f3e80-970e-11ea-8ce1-281e49af99f8.png">
It's then easy to add the 's' as so ...
<img width="562" alt="Screenshot 2020-05-16 at 00 39 56" src="https://user-images.githubusercontent.com/3199856/82104451-e4ab7680-970e-11ea-975c-3ff54a5d9a95.png">

Note that the current variable name does not have to be given at the top of the dialogue if the current name is in the edit box already. This will avoid having to fix the formatting bug!

**Desktop (please complete the following information):**
 - MacOS 10.14.6
 - Chrome
 - Version 81.0.4044.129

**Comment by pelikhan** [comment]
Is this a blockly thing?

**Comment by Geoffree3** [comment]
Yes it is   :-)

**Comment by Geoffree3** [comment]
but I’m sure you can pass an initial value through ….

**Comment by shakao** [comment]
fixed!
