### ISSUE TITLE
blocks to python conversion of array - error

### ISSUE THREAD

**Issue by Geoffree3** [microsoft/pxt-microbit#3077]
**Describe the bug**
An array defined in blocks and given an initial value does not convert to python correctly.

**To Reproduce**
Create array and give a value to the first item
<img width="424" alt="Screenshot 2020-05-16 at 01 19 33" src="https://user-images.githubusercontent.com/3199856/82105588-0824f000-9714-11ea-8abe-74cf0ddf1b15.png">
Go to python
<img width="359" alt="Screenshot 2020-05-16 at 01 19 57" src="https://user-images.githubusercontent.com/3199856/82105603-1541df00-9714-11ea-9d87-8bac82a18918.png">
Gives error:
<img width="770" alt="Screenshot 2020-05-16 at 01 21 09" src="https://user-images.githubusercontent.com/3199856/82105619-24289180-9714-11ea-9e36-35ff7d865783.png">

**Expected behavior**
Should convert as so, to avoid error
<img width="357" alt="Screenshot 2020-05-16 at 01 20 18" src="https://user-images.githubusercontent.com/3199856/82105630-2db1f980-9714-11ea-9ae2-5f35f6523089.png">

**Desktop (please complete the following information):**
 - MacOS: 10.14.6
 - Chrome
 - 81.0.4044.129

**Comment by abchatra** [comment]
Can you share the program through share link? I am unable to reproduce this. As code looks javascript & not python

**Comment by Geoffree3** [comment]
Hi

Just been playing with it again and they connect OK, but I sometimes get these 2 error message, but not the ‘device in use’ as before.  





I’ve attached the project files. Yes, they originate in blocks.





Geoff

**Comment by Geoffree3** [comment]
Hi,  another thought.  I did have to restart my Mac a few hours ago so perhaps this reset/cleared whatever and sorted out the problem?
