### ISSUE TITLE
Inconsistent pairing with webUSB 

### ISSUE THREAD

**Issue by Geoffree3** [microsoft/pxt-microbit#3078]
**Describe the bug**
Pairing several microbits is rather hit and miss.  Sometimes a new device will pair OK, then others will not (all have updated firmware).  Then previously paired devices will then fail to pair again (even when attempted lots of times). The problem reported via the JS console is the same - 'unable to claim interface ... Device in use of not found'. (see screenshot)

**To Reproduce**
Try to pair several devices

**Expected behavior**
Reliable pairing of more than 1 device

**Screenshots**
<img width="836" alt="Screenshot 2020-05-17 at 13 15 30" src="https://user-images.githubusercontent.com/3199856/82145750-24bf4600-9842-11ea-90c0-fdfea3c8c59a.png">

**Desktop (please complete the following information):**
 - MacOS 10.14.6
 - chrome
 - Version 81.0.4044.129

**Additional context**
This problem occurred during one of the live demos the other week!

**Comment by abchatra** [comment]
We support pairing only one device at a time. @Geoffree3 are you trying to connect multiple hardware simultaneously?

**Comment by Geoffree3** [comment]
No, only one at a time.

**Comment by Geoffree3** [comment]
By the way, I cannot see a pattern in when a particular device is not connected, apart from the JS error message. As you see the devices are recognised OK.  I’ve tried with 3 different microbits and 2 different projects.  One of the projects has 'serial redirect to usb’, which I though may be the problem as I tried different devices but again, could spot a pattern here.

**Comment by abchatra** [comment]
@pelikhan any update here?

**Comment by pelikhan** [comment]
No

**Comment by abchatra** [comment]
Removed next-release tag.

**Comment by pelikhan** [comment]
I've added telemetry but there's not much to chew on here.

**Comment by abchatra** [comment]
This is likely fixed. Reopen if this is still an issue.
