### ISSUE TITLE
undo button showing as usable even if no undo available

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#3079]
**Describe the bug**

in beta, the undo button shows up as enabled when you open a new project, even though there's nothing to undo

![image](https://user-images.githubusercontent.com/5615930/82177169-a38da080-988d-11ea-984e-f79880519372.png)

on live site it's properly disabled:

![image](https://user-images.githubusercontent.com/5615930/82177210-b011f900-988d-11ea-8340-aaced8bcb51e.png)

in monaco editor both undo and redo appear to always be enabled (same on live and beta):

![image](https://user-images.githubusercontent.com/5615930/82177266-c5872300-988d-11ea-929d-f023c2c733a3.png)

**To Reproduce**
1. Go to beta site
2. open a new project
3. see undo button is enabled even though no action as been taken / it does nothing

**Expected behavior**

the editor `.hasUndo` (&& the monaco editor ``.hasRedo``)

**Comment by abchatra** [comment]
won't fix
