### ISSUE TITLE
Feature: Revise default array numbers

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3080]
> micro:bit support 37584

The default block for creating an array looks like this:

![image](https://user-images.githubusercontent.com/31242877/82182932-fe021d80-98dc-11ea-894f-cf263e242d15.png)

but the "1" is in position 0, the "2" in position 1, etc.

This means that students have to be guided to know that they won't find "1" at position 1, but instead have to retrieve the expected number of the default block at position n-1.  This is, at this point in the learning process, an unnecessary complication.

Better would be:

![image](https://user-images.githubusercontent.com/31242877/82182949-05292b80-98dd-11ea-985c-5baed952db55.png)

Please consider making this change to the default set list to array block when the beta is released.

**Comment by abchatra** [comment]
Fixed

**Comment by microbit-mark** [comment]
Thanks @pelikhan @abchatra
