### ISSUE TITLE
Pick random doesn't show when opening published project

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3081]
**Describe the bug**
**Pick random** doesn't show when opening published project

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/_RVe4gjgDU0fa
2.Click edit

**Expect behavior**
Published project shows normally

**Actual behavior**
Pick random doesn't show when opening published project
![1](https://user-images.githubusercontent.com/59192069/82183049-daa89400-9917-11ea-8462-9a55aa556bd6.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.62
3.Microsoft MakeCode version: 5.37.76

**Comment by pelikhan** [comment]
We've moved to using ``randint`` which is not available in the current relased version of micro:bit.

**Comment by abchatra** [comment]
@Sheila111 published projects run in the live editor.
If you open the shared project from /beta through import you should still be able see it. Please validate.

**Comment by Sheila111** [comment]
Yep. I tried to open the shared project from /beta through import, the issue doesn't exist.
