### ISSUE TITLE
Error message doesn't show in high contrast mode

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#3082]
**Describe the bug**
Error message doesn't show in high contrast mode

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#editor
2.Open a python/JavaScript editor
3.Write some wrong code

**Expect behavior**
Error message should show in contrast mode.
![expected](https://user-images.githubusercontent.com/58197774/82183916-5bb45b00-9919-11ea-8162-802f261a7107.gif)

**Actual behavior**
Error message doesn't show in contrast mode.
![error](https://user-images.githubusercontent.com/58197774/82183936-60790f00-9919-11ea-9818-7c4ccb762a6e.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.62
3.Microsoft MakeCode version: 5.37.76

**Comment by pelikhan** [comment]
@hristoramirez

**Comment by abchatra** [comment]
@hristoramirez this needs to be fixed for microbit release. Please prioritize.
