### ISSUE TITLE
No help for if else condition in Python & JS

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3083]
**Describe the bug**
No help for **if else** condition in Python & JS

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#editor
2.Drag **if else** block
3.Mouse hover it
4.Right click----->help

**Expect behavior**
Show help for **if else** condition in Python & JS

**Actual behavior**
No help for if else condition in Python & JS
![2](https://user-images.githubusercontent.com/59192069/82193216-accb4b80-9927-11ea-9270-0688044aa5b2.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.62
3.Microsoft MakeCode version: 5.37.76

**Comment by abchatra** [comment]
Won't fix
