### ISSUE TITLE
Beta: play Melody snapshot, does not contain melody or notes icon

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3084]
**Describe the bug**

Downloading an image of the code snaphot for the playMelody block results in a sequence of black blocks with the note icon missing 
![microbit-screenshot-5](https://user-images.githubusercontent.com/31242877/82207429-bb067100-9901-11ea-95f9-674fa704762e.png)

should be

![Screenshot 2020-05-18 at 12 18 03](https://user-images.githubusercontent.com/31242877/82207476-cc4f7d80-9901-11ea-8061-cb4097e3b109.png)

Firefox 76 mac OS 10.15.4

**Comment by pelikhan** [comment]
It seems that there are custom classes for the melody editor that need to be injected in the SVG when rendering.

**Comment by abchatra** [comment]
Nice bug @microbit-mark
