### ISSUE TITLE
Music tone value resets to default value when switching back to blocks

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3088]
> micro:bit support: 37679

**Describe the bug**
In traditional Chinese translation

![melody](https://user-images.githubusercontent.com/31242877/82226991-1abf4500-991f-11ea-8653-836bbd011748.gif)

When  you use this in JS view

`music.playTone(952, music.beat(BeatFraction.Whole)`
 
and convert it to Blocks, it will convert to
 
`music.playTone(262, music.beat(BeatFraction.Whole)`

the default note value.

 
Other languages can be converted correctly. 

**Expected behavior**
Should convert to same value in blocks

**Comment by kimprice** [comment]
This bug has been fixed by correcting a translation error in Crowdin. It is already reflected in the live version.
