### ISSUE TITLE
Code error in Micro:Coin

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3091]
**Describe the bug**
Code error in **Micro:Coin**

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Radio Games---->Micro:Coin---->Show Instructions
3.Copy code to JS editor

**Expect behavior**
No code error

**Actual behavior**
There are 4 code errors.  It needs to add **radio-blockchain** to **Extensions**.
![image](https://user-images.githubusercontent.com/59192069/82306034-19f6e380-99f1-11ea-8753-766f9bf0d079.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.64
3.Microsoft MakeCode version: 5.37.77

**Comment by pelikhan** [comment]
@ganicke could you extract the coding out of the content page and turn it into a tutorial? This would fix the missing step of adding the micro-coin library

**Comment by abchatra** [comment]
We should just document the step to add the extension.

**Comment by pelikhan** [comment]
It's a general issue in our tutorial engine, we don't support well this step.

**Comment by abchatra** [comment]
This is an documentation page, just copy pasting the code into the editor is not going to work. We can't convert every documentation page with extension into tutorial.

**Comment by pelikhan** [comment]
Correct we need to add a step.

**Comment by ganicke** [comment]
The "Show Instructions" and then clicking "Edit" works fine for me and adds the extension.

![image](https://user-images.githubusercontent.com/27789908/82507077-2e50e400-9ab6-11ea-8f80-8f5068332c2f.png)

Also, there already is a note to add the `radio-blockchain` extension. However, I've slightly updated that in the page.
