### ISSUE TITLE
GitHub Integration not pulling changes correctly from repo

### ISSUE THREAD

**Issue by AlasdairAtKitronik** [microsoft/pxt-microbit#3092]
MakeCode Beta GitHub integration not correctly pulling changes from live repos.

With an existing extension for micro:bit MakeCode, wanted to add some tutorials.

Wrote them and tested them, and then added to the GitHub repo from my local version.

Wanted to test them again using the beta feature in the MakeCode GitHub integration, so opened the repo with the GitHub import feature in beta MakeCode and attempted to pull changes from the real repo. It pulled in the tutorial ".md" files, but none of the content was in them, they were completely blank. MakeCode reckoned there were now no differences between the version of the repo it was showing me and the actual one, so there was no way for me to get the content. 

I tried reverting to a previous commit and pulling the changes, but the same thing happened - MakeCode will not correctly pull the changes from the live repo, not matter what I try.

**Comment by AlasdairAtKitronik** [comment]
Some updates with screenshots etc:
The repo I'm facing issues with is: https://github.com/KitronikLtd/pxt-kitronik-halohd

This is the start of one of the tutorial files, screenshot from opening it GitHub:
![image](https://user-images.githubusercontent.com/36475405/82309739-67f0f480-99bb-11ea-85bd-ee0337871e1b.png)

Same file after pulling changes into GitHub integration with MakeCode:
![image](https://user-images.githubusercontent.com/36475405/82309986-b56d6180-99bb-11ea-947b-e6b8d71ba1ca.png)
Completely blank!

And all of the tutorials are the same:
![image](https://user-images.githubusercontent.com/36475405/82310123-e5b50000-99bb-11ea-971c-f4feea973683.png)

**Comment by pelikhan** [comment]
Do you have the list of commits that are creating an issue? I tried pulling your repo and everything looked fine. So there seems to be some local corruption here.

**Comment by AlasdairAtKitronik** [comment]
Having tried it again this morning, it is also working for me - what I'm seeing in the MakeCode GitHub integration is the same as what I'm seeing in the actual GitHub repo. 

The problem files were the four tutorials listed in the screenshot; they have now been renamed to not start with numbers, now a, b, c etc. Could that have been the only issue, starting a file name with a number?

**Comment by pelikhan** [comment]
Do you remember which commit? I can try to fork and restore that one.

________________________________

**Comment by AlasdairAtKitronik** [comment]
It was commit: 93e155151ab1ee2a37345435517d67e85fc61966

**Comment by AlasdairAtKitronik** [comment]
Entitled: Added Clock Kit Tutorials

**Comment by pelikhan** [comment]
Is this still an issue?

**Comment by AlasdairAtKitronik** [comment]
No, I'm pretty sure this issue was solved with the change to started filenames with a letter rather than a number.

**Comment by abchatra** [comment]
fixed
