### ISSUE TITLE
Error appears when switching to python editor in tutorial 'Snap the dot'

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#3098]
**Describe the bug**
Error appears when switching to python editor in tutorial 'Snap the dot'

Steps to reproduce the behavior
1.Navigate to https://makecode.microbit.org/beta#editor
2.Game->Snap the dot->start tutorial
3.Finish the tutorial and switch to python editor

**Expect behavior**
No error appears when switching to python editor in tutorial 'Snap the dot'.

**Actual behavior**
Error appears when switching to python editor in tutorial 'Snap the dot'.
![error](https://user-images.githubusercontent.com/58197774/82421967-6bb47200-9ab4-11ea-80e3-55d919b11fea.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.65
3.Microsoft MakeCode version: 5.37.78

**Comment by abchatra** [comment]
@darzu can we prioritize this over other bugs. Seems important.

**Comment by darzu** [comment]
Will do

**Comment by darzu** [comment]
Repro'ing with this JS:
```
input.onButtonPressed(Button.A, function () {
    if (sprite.get(LedSpriteProperty.X) == 2) {
        game.addScore(1)
    } else {
        game.gameOver()
    }
})
let sprite: game.LedSprite = null
sprite = game.createSprite(2, 2)
basic.forever(function () {
    sprite.move(1)
    basic.pause(1000)
    sprite.ifOnEdgeBounce()
})
```

**Comment by darzu** [comment]
This py:
```
def on_forever():
    sprite.move(1)
basic.forever(on_forever)

sprite: game.LedSprite = None
sprite = game.create_sprite(2, 2)
```
goes to:
```
basic.forever(function on_forever() {
    sprite.move(1)
})
let sprite = undefined
sprite = game.createSprite(2, 2)
```
not sure why we dropped the type annotation.
