### ISSUE TITLE
Cannot save function parameters in Firefox

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3112]
**Describe the bug**
When adding parameters to a function and clicking don, the parameters do not update with the new values in the editor 

**To Reproduce**
1. Go to beta editor
2. Click on new functio, editor paramenters and click done
3. function does not update

**Expected behavior**
function updates as in Chrome

**Screenshots**
![Kapture 2020-05-21 at 8 38 26](https://user-images.githubusercontent.com/31242877/82535350-a9f67380-9b3e-11ea-99b4-5e4d50e7b2d0.gif)

**Desktop (please complete the following information):**
 - OS: Mac 10.15.4
 - Browser Firefox
 - Version 76

**Comment by riknoll** [comment]
I can't repro this

**Comment by shakao** [comment]
looks like renaming the function itself from the dialog is broken, which might have caused a crash somewhere. i'll investigate

**Comment by abchatra** [comment]
fixed
