### ISSUE TITLE
No  intellisense in JavaScript editor on ipad

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#3113]
**Describe the bug**
No  intellisense in JavaScript editor on ipad

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Open a JavaScript  project 
3.Type basic. or Math.

**Expect behavior**
It should have intellisense when typing code
![yes](https://user-images.githubusercontent.com/58197774/82546083-28c4ce00-9b8a-11ea-99f2-8bc07f471513.gif)

**Actual behavior**
No  intellisense in JavaScript editor
![no](https://user-images.githubusercontent.com/58197774/82545783-bb18a200-9b89-11ea-82d6-902e1fa81d62.gif)

**Additional context**
1.OS: iPad mini 4
2.makecode.microbit.org version: 2.3.66
3.Microsoft MakeCode version: 5.37.79

**Comment by abchatra** [comment]
This is fixed.
