### ISSUE TITLE
No PickRandom block showing up in Tutorial

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#3114]
Open Dice Tutorial
Navigate to Step 4
In instructions, Pick Random is highlighted in incorrect color
Math Toolbox category and Random block is not shown
![image](https://user-images.githubusercontent.com/22108954/82588222-4d4f8480-9b4f-11ea-85c5-8a6cb40b7b05.png)

**Comment by jwunderl** [comment]
this will be fixed with https://github.com/microsoft/pxt-microbit/issues/3096

**Comment by abchatra** [comment]
Fixed in /beta
