### ISSUE TITLE
No default blocks for Tutorials

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#3115]
This has been something we've talked about for a while.
Let's get rid of the default Forever and On Start blocks from all Tutorials.
It's confusing and clutters the workspace.
![image](https://user-images.githubusercontent.com/22108954/82588543-d36bcb00-9b4f-11ea-855a-a08d42ad3608.png)

**Comment by abchatra** [comment]
We do have authoring way to remove on start & forever. Tutorial needs documentation update.
