### ISSUE TITLE
No errors for event conflicts

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#3121]
No error for this code. I could see this being confusing for students.

input.onButtonPressed(Button.A, function on_button_pressed_a() {
    basic.showIcon(IconNames.Happy)
})
input.onButtonPressed(Button.A, function on_button_pressed_a2() {
    basic.showIcon(IconNames.Sad)
})
input.onButtonPressed(Button.A, function on_button_pressed_a3() {
    basic.showIcon(IconNames.Silly)
    basic.showIcon(IconNames.Surprised)
})

**Comment by Jaqster** [comment]
wonder if we can be smart with intellisense and automatically populate with Button.B if we see an existing Button.A in their code

**Comment by pelikhan** [comment]
It's perfectly valid in javascript to redefine events.

**Comment by abchatra** [comment]
It is valid to redefine functions in JavaScript. Done to override existing behavior.
