### ISSUE TITLE
Error message - too aggressive showing this

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#3123]
As a beginner student typing in JS or PY, the error messages are popping up way too often.
It's intimidating (especially as it's Red and says "Problem").
It's the opposite of what we want in a learning tool.
Let's revisit please.

**Comment by pelikhan** [comment]
We have a 500ms de-bouncing currently, we could try a few seconds.

**Comment by hristoramirez** [comment]
@Jaqster should I try 2 seconds for now and try out some user testing?

**Comment by pelikhan** [comment]
The automated build uploads a copy of the editor; you can extract the url from the build log.

**Comment by hristoramirez** [comment]
@pelikhan Is this to checkout out editor changes without having to make a lot of PRs just adjusting the debounce time? Also I tried looking for this, but I'm not sure if I'm looking at the right place.

**Comment by pelikhan** [comment]
Sorry those PRs don’t create a build. Record gifs with different speeds.


________________________________

**Comment by hristoramirez** [comment]
I tried a couple of different speeds

**original : 0.5 seconds**
![original-debounce](https://user-images.githubusercontent.com/46362603/82964333-124bb780-9f7a-11ea-87e0-ee639fd54a5a.gif)

**2 seconds**
![2s](https://user-images.githubusercontent.com/46362603/82964349-1b3c8900-9f7a-11ea-90bd-7016d4968ba6.gif)

**5 seconds**
![5s](https://user-images.githubusercontent.com/46362603/82964393-35766700-9f7a-11ea-81ef-09263b3c45f8.gif)

**Comment by pelikhan** [comment]
1 second?

________________________________

**Comment by hristoramirez** [comment]
**1 second**
![1s](https://user-images.githubusercontent.com/46362603/82965445-001f4880-9f7d-11ea-8177-364741de994c.gif)

**Comment by pelikhan** [comment]
Many students will type much slower than this. My vote is 2s. In the future, we could infer the typing speed of the current user and tune the timeout on the fly.

________________________________
