### ISSUE TITLE
Using the note picker freezes the editor in old edge

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#3124]
**To Reproduce**
1. Create a new project
2. Drag out a "play tone" block
3. Choose a note
4. The editor is frozen!

![bad_note](https://user-images.githubusercontent.com/13754588/82592202-678c6100-9b55-11ea-8137-a1eb4855fb5c.gif)

**Comment by shakao** [comment]
Fixed by https://github.com/microsoft/pxt/pull/7081
