### ISSUE TITLE
play melody: valid JS causes "Invalid Input" and clobbers melody when switching to/from blocks

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#3125]
**Describe the bug**
If you use the playMelody() block, certain valid input in JS view gets recorded as "invalid input" in the blocks view, and when switching back to JS the code is lost and "invalid input" is in the place it should be.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to makecode.microbit.org/beta
2. Drag in a play melody block, populate it with valid input (for example `music.playMelody("C D E F G A B C5 ", 120`)
3. Switch to JS. 
4. Edit the melody to be still valid (IE still work in the simulator!), and check it works in simulator - eg `music.playMelody("C D Eb F G Ab B C5 ", 120)`
5. Switch back to blocks
(6. Optional: Switch back to JS)

The melody I had written is now replaced with "Invalid Input" in blocks and in JS. If I have spent a long time choosing my melody I have lost my work 

Undo does not work

Note that even for invalid input, it would be better if the 'invalid' tune were preserved. For example `music.playMelody("C D", 120)` works on the simulator but doesn't work on the sequencer, or even just missing a '-' breaks the code.

**Expected behaviour**
I'd expect the melody to either be correctly expressed in the UI, or to get a 'greyed out block' sort of effect.

**Screenshots**
![melody invalid input](https://user-images.githubusercontent.com/147113/82592124-56187880-9b98-11ea-87f0-d90e30c023a5.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 81

**Comment by abchatra** [comment]
Moving to load balance. @riknoll can you take a look at this.

**Comment by riknoll** [comment]
It should preserve the input, I think this is a blockly upgrade bug. Looking into it
