### ISSUE TITLE
Tablet view add full screen icon instead of restart.

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#3128]
Replace restart icon with full screen. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6107272/82593197-f0f06300-9b56-11ea-89dd-536b3299ca8b.png)

**Desktop (please complete the following information):**
 - OS: Android Tablet

**Comment by jwunderl** [comment]
got it here: https://github.com/microsoft/pxt/pull/7067
