### ISSUE TITLE
No documentation for 'play melody' block

### ISSUE THREAD

**Issue by livcheerful** [microsoft/pxt-microbit#3131]
**Describe the bug**
There is no documentation shown when selecting help for the 'play melody' block

**To Reproduce**
1. In the editor, draw a 'play melody' block out
![image](https://user-images.githubusercontent.com/18712271/82593995-4a0cc680-9b58-11ea-9467-2f9bc656f5e5.png)

2. Right click on the block
3. Click 'Help'
4. The documentation screen is blank

**Expected behavior**
There should be info on the play melody block displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/18712271/82593116-d322fe00-9b56-11ea-893a-932d95a0f3e3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version  81.0.4044.138

**Comment by jwunderl** [comment]
I believe @ganicke just added this yesterday: https://github.com/microsoft/pxt-common-packages/commit/5ce17643c53162b82914394183db03a97ce8cb20 (I think just needs a bump of common packages)

**Comment by pelikhan** [comment]
Yup.

**Comment by ganicke** [comment]
Dup #3087

**Comment by abchatra** [comment]
Fixed
