### ISSUE TITLE
Arrow keys don't navigate the carousel 

### ISSUE THREAD

**Issue by livcheerful** [microsoft/pxt-microbit#3133]
**Describe the bug**
The left/right keys don't have any input on switching between items in the carousel

**To Reproduce**
1. Go to https://makecode.microbit.org/beta or https://makecode.microbit.org/
2. Click on one of the tutorials (Name Tag)
3. Push the right arrow key
4. Nothing happens

**Expected behavior**
We will cycle through the tutorial

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version  81.0.4044.138

**Additional context**
This doesn't work in the livesite either

**Comment by abchatra** [comment]
This is tab or shift tab to navigate. I tested and it works.
