### ISSUE TITLE
neopixel simulator doesn't match value being set

### ISSUE THREAD

**Issue by hristoramirez** [microsoft/pxt-microbit#3134]
The color being set does not match the color shown on the simulator when on GRB format
![neopixel](https://user-images.githubusercontent.com/46362603/82603817-294c6d00-9b68-11ea-8ff5-c46a99439c3a.gif)

**Comment by jwunderl** [comment]
Peli's got a fix, dup https://github.com/microsoft/pxt-microbit/issues/2940

**Comment by riknoll** [comment]
@jwunderl, you can close duplicates!

**Comment by jwunderl** [comment]
Oops, was going to, got distracted by the mixer chat!

**Comment by riknoll** [comment]
haha, np! that's more important
