### ISSUE TITLE
Using assembler in .cpp files in Makecode extensions

### ISSUE THREAD

**Issue by MTKilpatrick** [microsoft/pxt-microbit#3137]
Firstly, there is no apparent means to call an assembler function from within a C++ function in the .cpp for a Makecode extension, even though it is possible it use a shim to make a Typescript function call an assembler routine (which would be found in an accompanying .asm file).

Secondly, whilist it appears to be possible to write inline assembler code in C++ code, assembly code that works perfectly well when specified in a separate .asm file brings up compiler errors when used in the .cpp file. For example
```
void blah(int this, int that) {
  loop:
  asm (
    ...various opcodes....
    "adds r4, #1\n\t"
    "subs r5, #1\n\t"
    "bne loop\n\t");
}
```
Neither of the valid ARM opcodes ADDS and SUBS in the above are recognised and will not compile. This is unfathomable, unless there is a different format used for the opcodes - but I see no documents describing that.

Thirdly, assuming one can generate some working inline assembler code, there is no explanation of how to call external functions. When using a .asm assembler file, Microbit functions may be called easily, in the form `bl pins::getPinAddress`. The ARM compiler documentation suggests that for inline assembler code, external variables or functions can be referrred to in the following form  `__cpp(expression)` which suggest a call to a function might be possible in the following form or something similar: `bl __cpp(pins::getPinAddress`). However, this is not correct.

Is it possible to have explanations and solutions for the above problems?

**Comment by abchatra** [comment]
@mmoskal any explanation for this issue?

**Comment by mmoskal** [comment]
Sorry for (loooong) delay.

The inline assembly uses GNU assembler, check out GCC docs for that. The .asm files are assembled by MakeCode's built-in assembler, which uses related, but slightly different syntax. Sorry about that.
