### ISSUE TITLE
'Mute audio' and 'Toggle debug mode' don't show on iPad

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#3141]
**Describe the bug**
**Mute audio** and **Toggle debug mode** don't show on iPad

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Open  a project

**Expect behavior**
**Mute audio** and **Toggle debug mode** should show.
![image](https://user-images.githubusercontent.com/58197774/82652632-7efc4480-9c50-11ea-8687-6a4a7d4ba645.png)

**Actual behavior**
**Mute audio** and **Toggle debug mode** don't show on iPad.
![image](https://user-images.githubusercontent.com/58197774/82652502-4ceae280-9c50-11ea-9550-88348f8c5144.png)

**Additional context**
1.OS: iPad mini 4
2.makecode.microbit.org version: 2.3.68
3.Microsoft MakeCode version: 5.37.82

**Comment by abchatra** [comment]
These are only available in full screen view of simulator. This is per design. Click on simulator or expand button you should see these.

**Comment by abchatra** [comment]
As designed.
