### ISSUE TITLE
Doesn't play tone the first Middle C when pressing button A for the first time

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3142]
**Describe the bug**
Doesn't play tone **the first Middle C** when pressing button A **for the first time**

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/projects/guitar/displaybuttons
2.Run this program

**Expect behavior**
Play tone **C, C, D, C, F, E**

**Actual behavior**
Doesn't play tone **the first Middle C** when pressing button A **for the first time**
![2](https://user-images.githubusercontent.com/59192069/82652982-1cf00f00-9c51-11ea-8adc-0bb0bf1cfe36.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.68
3.Microsoft MakeCode version: 5.37.82

**Comment by abchatra** [comment]
@Sheila111 can you test this program in the /beta editor? Check if the issue reproduces in the simulator.

**Comment by Sheila111** [comment]
@abchatra  The issue doesn't reproduce in the /beta editor, just happens in the page.

**Comment by Sheila111** [comment]
Still not fixed when you press button A for the **first time** @abchatra
