### ISSUE TITLE
Moving "sendBuffer" assembly function to core pxt has broken Kitronik extensions

### ISSUE THREAD

**Issue by AlasdairAtKitronik** [microsoft/pxt-microbit#3143]
**Describe the bug**
The following commit to pxt-microbit has caused breaking changes for several KitronikLtd extensions in beta MakeCode:
https://github.com/microsoft/pxt-microbit/commit/b3ea206a58b1132c4d0076771c7ec2aa5442145d

Affected extensions:
https://github.com/KitronikLtd/pxt-kitronik-move-motor
https://github.com/KitronikLtd/pxt-kitronik-halohd
https://github.com/KitronikLtd/pxt-kitronik-zip-64
https://github.com/KitronikLtd/pxt-kitronik-zip-tile

**To Reproduce**
1. Go to BETA micro:bit MakeCode and start a new project.
2. Add any one of the 4 affected extensions listed above (Halo HD used in example here).
3. Create code to turn all LEDs on red:
![image](https://user-images.githubusercontent.com/36475405/82652505-a124a100-9c15-11ea-907b-2ac0ffe1a704.png)
4. Attempt to download the code file to program the micro:bit, this error message will appear:
![image](https://user-images.githubusercontent.com/36475405/82652612-cb765e80-9c15-11ea-8f56-f4d0e5f2913d.png)
5. Program the micro:bit with the downloaded hex file and try pressing button A (if you have Halo HD) - nothing will happen.

**Expected behavior**
If all the above steps are carried out in current live MakeCode (not beta), everything will work as expected; no error messages, and all the Halo HD LEDs will turn on red.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  81.0.4044.138

**Additional Info**
All four affected repos were working in beta MakeCode as of 12th May 2020. Having discovered an issue on 21st May 2020, I then went looking through the commits to pxt-microbit since the 12th. The most likely problem area seemed to be the change to make the ws2812b neopixel driver code be part of the core pxt. KitronikLtd are using a branched version of the Microsoft ws2812b driver repo (https://github.com/microsoft/pxt-ws2812b) which respects brightness changes whenever they are made (https://github.com/KitronikLtd/pxt-ws2812b). 

I believe the "Add auto-upgrade rule to use built-in neopixel" part of the adding to core commit means that any code which is using th ws2812b driver will automatically go and use the core assembly driver for the LEDs, even if - as in Kitronik's case - there is another repo listed in the dependencies. I tried changing the order of the dependencies, so that "core" came after our "ws2812b" driver version, but that did not fix the issue. The only work around I have found is to go and change the assembly function name in our "ws2812b" repo.

**Comment by pelikhan** [comment]
This change has been revered. It may take a day to be active.

**Comment by abchatra** [comment]
This is fixed.
