### ISSUE TITLE
bar graph doesn't take negative values into account

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3144]
**Describe the bug**
When using a negative value with the bar graph, the display treats it as a positive value, so displaying -1023 is the same as displaying 1023, similarly if you plot to a negative value from a positive one
<img width="912" alt="Screenshot 2020-05-22 at 11 58 08" src="https://user-images.githubusercontent.com/31242877/82661224-89541980-9c23-11ea-9d27-b791bfba7d18.png">

**Expected behaviour**
I would expect this not to display anything

**Comment by pelikhan** [comment]
If you plot the acceleration, it will look broken half of the time. This is the intended behavior.

**Comment by abchatra** [comment]
This is as designed. Bar graph plots unsigned values.
