### ISSUE TITLE
makecode python chr(code) Bug

### ISSUE THREAD

**Issue by acad8899** [microsoft/pxt-microbit#3152]
**Describe the bug**
in python:chr(65)="A"
but makecode python keyin chr(code) 
feedback: can't find called function "chr"
and strng.from.char.code(code) Bug

**To Reproduce**

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Please check the python bug!
show A to I : makecode  block OK
![image](https://user-images.githubusercontent.com/49807650/82828677-3361c900-9ee4-11ea-9197-75e20e186d30.png)
show A to I : makecode  python BUG
![image](https://user-images.githubusercontent.com/49807650/82828729-4f656a80-9ee4-11ea-9d79-5968bf74bbca.png)

**Comment by microbit-mark** [comment]
> Also reported in micro:bit support #38245

Video shows that this also errors if then moving into JavaScript https://www.youtube.com/watch?v=xsMSTZ4-vnk

**Comment by fejesgergorichard** [comment]
Is there a solution? I am facing the same issue

**Comment by darzu** [comment]
Indeed, this TS:
```ts
basic.showString(String.fromCharCode(65))
```
goes to this PY:
```py
basic.show_string(String.from_char_code(65))
```
which goes to this TS:
```ts
basic.showString(String@type.fromCharCode(65))
```

Repros in all targets. Investigating...
