### ISSUE TITLE
If there should remove the option to see explorer in tutorial view

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#3155]
**Describe the bug**
If there should remove the option to see explorer in tutorial view

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Tutorials->Flashing Heart->start python editor
3.Type some wrong code
4.Expand the explorer list and click **Remove it** button

**Expect behavior**
If there should remove the option to see explorer in tutorial view, There is no use deleting the python file as tutorial won’t switch back from python to blocks.

**Actual behavior**
It will switch to block editor after clicking **Remove it** button in python editor. The instruction is still python code, but it already switches to block editor. 
![python](https://user-images.githubusercontent.com/58197774/82851994-22d93f00-9f34-11ea-91a9-be03ffd0ed7a.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.69
3.Microsoft MakeCode version: 5.37.82

**Comment by abchatra** [comment]
@shakao can we just remove explorer from the tutorial view?
