### ISSUE TITLE
Content inconsistency in "Tug-Of-LED" python & JS tutorial

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3156]
**Describe the bug**
Content inconsistency in "Tug-Of-LED" python & JS tutorial

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Games---->Tug-Of-LED--->Python Start Tutorial
3.Click step 6, 7 , 8

**Expect behavior**
No content inconsistency 

**Actual behavior**
Content inconsistency in "Tug-Of-LED" python & JS tutorial
Step 6
![image](https://user-images.githubusercontent.com/59192069/82866273-27fdb480-9f5b-11ea-93eb-ba867ae8189f.png)
Step 7
![image](https://user-images.githubusercontent.com/59192069/82866347-4b286400-9f5b-11ea-8e84-8f8d27bdf1b0.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.69
3.Microsoft MakeCode version: 5.37.82

**Comment by abchatra** [comment]
Nice bugs @Sheila111

**Comment by ganicke** [comment]
Uh, like oops. #3174.
