### ISSUE TITLE
There shows error when opening 'Mood Radio' and 'Tele-potato' in Chinese

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3157]
**Describe the bug**
There shows error when opening 'Mood Radio' and 'Tele-potato' in Chinese

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Change language to Chinese
3.Open 'Mood Radio' and 'Tele-potato'

**Expect behavior**
The content shows in Chinese

**Actual behavior**
Documentation can't open and there shows error
![1](https://user-images.githubusercontent.com/59192069/82874194-2a1a4000-9f68-11ea-9442-d14bd8728229.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.69
3.Microsoft MakeCode version: 5.37.82

**Comment by shakao** [comment]
the `radio` package snippet got localized, fixed for these two files in crowdin! long-term we shouldn't send text to crowdin that we don't want localized (see https://github.com/microsoft/pxt-arcade/issues/3478)
