### ISSUE TITLE
The content of the 'Step Counter' is confusing in Chinese

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3158]
**Describe the bug**
The content of 'Step Counter'  is confusing in Chinese

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Change language to Chinese
3.Fashion---->Step Counter
4.Click step 2 , 3

**Actual behavior**
The content of the tutorial is confusing in Chinese
Step 2
![image](https://user-images.githubusercontent.com/59192069/82879797-107cf680-9f70-11ea-8d0a-66d3da12e443.png)
Step 3
![image](https://user-images.githubusercontent.com/59192069/82879948-48843980-9f70-11ea-8457-03157fea5c4b.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.69
3.Microsoft MakeCode version: 5.37.82

**Comment by abchatra** [comment]
This is fixed.
