### ISSUE TITLE
The list of 'Beta Deep Dive' doesn't show in Chinese

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#3159]
**Describe the bug**
The list of **Beta Deep Dive** doesn't show in Chinese

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Change language to Chinese

Expect behavior
The list of **Beta Deep Dive** should show in Chinese

**Actual behavior**
The list of **Beta Deep Dive** doesn't show in Chinese
![language](https://user-images.githubusercontent.com/58197774/82884735-b6336400-9f76-11ea-90b2-3b5e3f6d3c3d.gif)

**Additional context**
1.OS: Windows(rs6),iPad Mini4
2.makecode.microbit.org version: 2.3.69
3.Microsoft MakeCode version: 5.37.82

**Comment by abchatra** [comment]
Does it show in English?  If we can't reach Youtube we basically don't show the cards.

**Comment by abchatra** [comment]
@KellyLuo1

**Comment by pelikhan** [comment]
It might be that all the cards are hidden. I think we have a per-row youtube filtering as well that we should turn on for those galleries.

**Comment by KellyLuo1** [comment]
@abchatra It can show normally in English
![english](https://user-images.githubusercontent.com/58197774/82982287-6e691700-a020-11ea-9d72-cb958c9b9e11.gif)

**Comment by shakao** [comment]
looks like the markdown got messed up in translation, i'll fix on crowdin

**Comment by shakao** [comment]
fixed
