### ISSUE TITLE
The 'Mute audio' is selected automatically when creating a new project

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#3160]
**Describe the bug**
The **Mute audio** is selected automatically when creating a new project

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Create a new project

**Expect behavior**
The **Mute audio** shouldn't be selected automatically when creating a new project.

**Actual behavior**
The **Mute audio** is selected automatically when creating a new project.
![sound](https://user-images.githubusercontent.com/58197774/82885724-18409900-9f78-11ea-9639-a562380fe91a.gif)

**Additional context**
1.OS: iPad Mini4
2.makecode.microbit.org version: 2.3.69
3.Microsoft MakeCode version: 5.37.82

**Comment by jwunderl** [comment]
This is by design; on iOS devices the simulator starts muted due to browser policies.
