### ISSUE TITLE
Inchworm can't load block in the last page in Chinese

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3161]
**Describe the bug**
Inchworm can't load block in the last page in Chinese

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Change language to Chinese
3.Toys---->Inchworm
4.Click NEXT:Connect

**Actual behavior**
Inchworm can't load block in the last page in Chinese
![2](https://user-images.githubusercontent.com/59192069/82885622-fba46100-9f77-11ea-9cb4-db8238b657e4.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.69
3.Microsoft MakeCode version: 5.37.82

**Comment by abchatra** [comment]
Fixed
