### ISSUE TITLE
GitHub: Invite collaborators popup is very hard to tap on iOS

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#3168]
**Describe the bug**

The popup "Invite collaborators" is very hard to tap on iOS, in both Safari and the app.

The first tap usually just makes the button white. This behaviour exists on Windows and Android Chrome too.

A very brief, light tap eventually works. 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS 13.4.1
 - Browser [e.g. chrome, safari] Safari, webview

**Additional context**

**Comment by abchatra** [comment]
Invite collaborators completely makes the editor white. Seems broken. Please remove this button or address this.

**Comment by pelikhan** [comment]
I’ll remove it.

________________________________

**Comment by abchatra** [comment]
Fixed
