### ISSUE TITLE
autocomplete doesn't work properly on android monaco

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#3170]
**Describe the bug**

autocomplete / typing in general is incorrect in monaco on android

**To Reproduce**

1. Go to microbit/beta on android phone
2. open javascript editor
3. start typing; see that there is a duplicate character past the cursor
4. take a suggestion; see everything gets messed up
5. type part of a suggestion then take one (e.g. type con then click on continue in the dropdown); press enter and see that it applies a seemingly random suggestion on top of the selected one

![misbehaving-mobile-monaco](https://user-images.githubusercontent.com/5615930/82958080-6ef2a680-9f69-11ea-8f84-34338f735a15.gif)

gif from chrome devtools connected to physical device, looks like it repros on android studio emulator too which is good

**Expected behavior**
shouldn't auto fill random completions, and shouldn't have extra cursor

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 9
 - OS: android 10
 - Browser stock chrome 83.0.4103.60

**Comment by abchatra** [comment]
Disable autocomplete in android for now.
