### ISSUE TITLE
Debugger is too hard to find on tablet

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3173]
The debugger is almost impossible to find. Are we trying to hide it in tablet mode?

- start simulator
- go full screen
- click debugger icon
- go out of debugger

We need a top-level button for the debugger.

![image](https://user-images.githubusercontent.com/4175913/82975999-db35d000-9f92-11ea-80ed-a5d360575523.png)

**Comment by jwunderl** [comment]
I guess no harm in swapping editor toolbar restart button for debug mode? I had that at one point, think we had decided to swap that button for the stop / show

Do you know how you got into that view from the screenshot? For some reason the state is inconsistent / it didn't rerender after expanding the simulator, maybe missing a state update from somewhere else? Ill take a look.

**Comment by abchatra** [comment]
+1 swap restart with debugger.

**Comment by pelikhan** [comment]
I was using makecode.com/streamer with dual editors on the mac.  I did do: full screen, debugger, exit full screen, exit debugger

**Comment by jwunderl** [comment]
I got it to repro, just a selectivity fight in css (display:none overridden by display: inline-block) will fix both things in a few
