### ISSUE TITLE
Return statements do not work in else if conditions

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3177]
> micro:bit support: 37438

**Describe the bug**

When I have the not clause as an else statement all is ok and the function is valid but when I create the slightly awkward but never the less a correct program using else if, the analysis falls over detecting a function with no terminating return statement

The compiler is not able to identify that the second condition specified is the opposite of the first if statement, as such it believes that there should be an else statement anyway in order to cover all possibilities. 

**Expected behavior**
Statement should not error, this could be confusing for kids and teachers.

**Screenshots**
First function errors, second one does not
![image](https://user-images.githubusercontent.com/31242877/83021110-62ca2000-a021-11ea-8f3e-5178ee46b4d5.png)

This program does not error
![image](https://user-images.githubusercontent.com/31242877/83021184-8ab98380-a021-11ea-8131-75e031c34134.png)

**Comment by abchatra** [comment]
We dont' do flow analysis yet.

**Comment by abchatra** [comment]
Won't fix. We need a return in all the paths to ensure there is a return statement.
