### ISSUE TITLE
Beta: Function call should error if return statement can't execute

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3178]
> micro:bit support: 37523

**Describe the bug**
If the while loop is true, this function shuold execute. If set to False, the return statement has no chance of executing effectively creating a procedure, this should flag an error in the calling statement the oval call function block should no longer be available to showNumber

**To Reproduce**

![Screenshot 2020-05-27 at 15 41 50](https://user-images.githubusercontent.com/31242877/83034962-be4fda00-a030-11ea-8ce1-a545c6d70385.png)

**Expected behavior**
Error to appear in show number

**Comment by abchatra** [comment]
This is runtime error and can't be caught at compile time.
