### ISSUE TITLE
Feature: button to clear melody editor matrix

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3180]
**Is your feature request related to a problem? Please describe.**
The melody editor has quite a large matrix, it would be useful to be able to clear all
![Screenshot 2020-05-27 at 16 25 08](https://user-images.githubusercontent.com/31242877/83040119-d1fe3f00-a036-11ea-90e4-25447adb9453.png)

**Describe the solution you'd like**
Button to clear all in melody editor

**Describe alternatives you've considered**

**Additional context**

**Comment by abchatra** [comment]
Can't fix. There is not enough UI elements to add undo. There are workarounds like undo in the editor or drag a new block.
