### ISSUE TITLE
Something wrong with the content of 'Square'  in Chinese

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3183]
**Describe the bug**
Something wrong with the content of 'Square'  in Chinese

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Change language to Chinese
3.Turtle---->Square
4.Click step 3,4

**Expect behavior**
**turnright** not **turright**

**Actual behavior**
Something wrong with the content of 'Square'  in Chinese
Step 3
![image](https://user-images.githubusercontent.com/59192069/83091828-acbd0f80-a0ce-11ea-98ad-0cdda7631add.png)
Step 4
![image](https://user-images.githubusercontent.com/59192069/83092019-0e7d7980-a0cf-11ea-92e8-09cf5e7f6b6e.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.0.2
3.Microsoft MakeCode version: 6.0.2

**Comment by abchatra** [comment]
Should be fixed now. Please validate.
