### ISSUE TITLE
Old Edge: turtle LEDs are incorrectly offset

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#3190]
**Describe the bug**
![image](https://user-images.githubusercontent.com/34112083/83291804-cc6f3900-a19d-11ea-87b0-b303a7310cf1.png)

Code: https://makecode.microbit.org/_bJz5793Aa59u

LEDs from "pen down" do not line up with LEDs on simulator. Looks fine in Chrome

**Comment by abchatra** [comment]
Won't fix minor issues in old Edge
