### ISSUE TITLE
Debugger icon not visible in half screen

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3200]
The debugger button should always be next to the sim. Why are we hiding it?

![image](https://user-images.githubusercontent.com/4175913/83345446-0a687c00-a2c8-11ea-9460-a871eab39a82.png)

**Comment by jwunderl** [comment]
This is hitting the phone breakpoint - we had swapped the restart for full screen when that was in the portrait views, but yeah, i agree debug is more important than the full screen button in that size (as fullscreen is still accessible through clicking on sim)

Just gonna ping @abchatra on this change, will put up a pr to do it in a moment ~

**Comment by abchatra** [comment]
I disagree, full screen is more important than debug button in phone view.  Is this on a actual device?

**Comment by pelikhan** [comment]
Clicking anywhere on the simulator will go full screen.

This is in a full screen browser in the multi view.

**Comment by abchatra** [comment]
It is hard to figure out you can click on the simulator. May be restrict the fix only for multi view. 

I checked on 9 inch ipad portrait mode and we hit tablet view and not phone view. In phone view it is important to able to full screen.

**Comment by pelikhan** [comment]
Hiding the debugger icon is inconsistent and hiding an important educational feature. It makes it really hard to build an instruction that says “click on the debugger icon near the Microbit simulator”.

**Comment by abchatra** [comment]
Phone view, debugging is hard.

**Comment by abchatra** [comment]
Full screen will show all other icons.

**Comment by pelikhan** [comment]
This is not a phone. This is half of a 13” monitor. I should be able to enter the debugger in any view.

**Comment by abchatra** [comment]
If this is specific to multiview, then we should have a different fix.

**Comment by pelikhan** [comment]
Clicking on the debugger in full screen mode does nothing visible. One then needs to go out of full screen to see the debugger, it is too complicated.

**Comment by pelikhan** [comment]
Why are we not showing the 3 icons at all times?

**Comment by pelikhan** [comment]
The debugger icon should be visible consistently. Why are we hiding it?

________________________________

**Comment by abchatra** [comment]
I don't see how you can go to portrait view in 13''inch screen? That is the reason I am asking if this is specific to multi view? If yes make a different fix.

**Comment by abchatra** [comment]
I have 9inch tablet and it is tablet view in the portrait mode.

**Comment by pelikhan** [comment]
There is plenty of space for a debugger icon

![image](https://user-images.githubusercontent.com/4175913/83359070-aaf08780-a32c-11ea-8767-e01f779d2b4b.png)

**Comment by pelikhan** [comment]
I don't understand why we are not showing fullscreen/debugger/stop in all views?

**Comment by abchatra** [comment]
There is not enough space in the phone like 5''inch phone.

**Comment by pelikhan** [comment]
I am not using a phone, and clicking stop reclaims the space.

________________________________

**Comment by pelikhan** [comment]
We should have a consistent way to enter debugger mode. Space is not a good enough reason to hide it since the sim:buttons are hidden by stop anyway. This creates an inconsistent state which makes it hard to use the debugger. If 5” phones are the problem, we need a special view for those:
As shown in my screenshot, there is ample space to display the icon.

**Comment by jwunderl** [comment]
I guess we could probably get away with having all three on mobile, a few of the last changes I had made make the normal size fit a bit better in mobile / reduce the need for the smallest sim a bit:

![image](https://user-images.githubusercontent.com/5615930/83359198-9496fb80-a32d-11ea-9567-566691e10f9c.png)

![image](https://user-images.githubusercontent.com/5615930/83359217-bc865f00-a32d-11ea-80fa-2d66db8dfb2b.png)

**Comment by abchatra** [comment]
We should discuss. There is so little space in phone if you made simulator that large.

**Comment by pelikhan** [comment]
You don’t have the change the simulator size to add an icon. Again, I am not using a phone. I have using a half desktop screen with plenty of space to spare.

________________________________

**Comment by abchatra** [comment]
I think issue is specific to multiview.  We decide phone view soles based on the width of the screen. I you consider width & height, you could probably show tablet view in this scenario.

**Comment by pelikhan** [comment]
We need to a consistent experience to enter debugging mode. This means the icon is always visible near the simulator when the simulator is visible. The current design is broken.

________________________________

**Comment by abchatra** [comment]
We can't show all the icons in phone view. There is just not enough space. I do agree we need to do something for multi-view.

**Comment by pelikhan** [comment]
Adding an icon in phone mode while keeping the same simulator size would not impact the UI space (which is already overcrowded on 5”). We need a tiny phone view    For small phone to hide those buttons. There will be much more use the multi-view than 5” phones.


________________________________
