### ISSUE TITLE
Creation of release fails in github extension

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#3202]
**To Reproduce**
1. Go to import->GithubURL
2. Import https://github.com/microsoft/pxt-neopixel repo
3. Go to github page and try to create a release.

![image](https://user-images.githubusercontent.com/6107272/83383020-238d2d80-a399-11ea-9a78-543b92d3e5e9.png)

**Comment by pelikhan** [comment]
This is because the Microsoft org hasn’t allowed our OAuth app.

________________________________

**Comment by abchatra** [comment]
How do I create the release through our UI then?

**Comment by pelikhan** [comment]
Sign in with a developer token

________________________________

**Comment by abchatra** [comment]
Ok as designed. Closing. I though you had a new UI for this.

**Comment by pelikhan** [comment]
Apparently not wired everywhere.

________________________________
