### ISSUE TITLE
Sim restarts twice after switching JS or Python editor to Block editor

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3203]
**Describe the bug**
Sim restarts twice after switching **JS or Python** editor to **Block** editor

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Tutorials---->Name Tag
3.Switch **JS or Python** editor to **Block** editor

**Expect behavior**
Sim restarts once

**Actual behavior**
Sim restarts twice
![1](https://user-images.githubusercontent.com/59192069/83391350-eb7ffc00-a425-11ea-9946-01ed0c65699a.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.1
3.Microsoft MakeCode version: 6.0.6

**Comment by abchatra** [comment]
fixed
