### ISSUE TITLE
Kitronik MOVE Motor icon not appearing

### ISSUE THREAD

**Issue by KitronikLtd** [microsoft/pxt-microbit#3205]
THE image for the MOVE motor package is in the approved repo: 
https://github.com/KitronikLtd/pxt-kitronik-move-motor/blob/master/Icon.png
but it does not appear when the extension is searched in the makecode editor:

![image](https://user-images.githubusercontent.com/25480360/83410217-e020d680-a40d-11ea-851b-ee50233568c5.png)

**To Reproduce**
1. Goto makecode editor
2. add extension
3. Ssearch for MOVE motor

**Expected behavior**
icon appears in the grey area

**Desktop (please complete the following information):**
 - OS: Windows 10
 -Chrome and Edge

**Comment by pelikhan** [comment]
lower case icon.png

**Comment by KitronikLtd** [comment]
Have changed it. icon hasn't yet appeared, but sometimes there is a caching time lag.

**Comment by KitronikLtd** [comment]
@pelikhan  The icon is still a grey box. I did a bump, and the correct version is pulled into the editor.

**Comment by pelikhan** [comment]
Let's wait 24h.

**Comment by pelikhan** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/4175913/83537269-2e36e800-a4a9-11ea-9fb8-6609205f0df6.png)
