### ISSUE TITLE
Update approved extensions banner

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3207]
**Describe the bug**
The sentence in the banner for an approved extension doesn't read well, it should be 'a partner', but even that isn't very descriptive

<img width="450" alt="Screenshot 2020-06-02 at 12 52 52" src="https://user-images.githubusercontent.com/31242877/83516997-05761900-a4d0-11ea-83d4-25dc5b99ca11.png">

Not sure where to edit this, but could it be:

"The content below is provided by a third party and approved by the Micro:bit Educational Foundation" or
"The content below is provided by a partner and approved by the Micro:bit Educational Foundation"

**Comment by abchatra** [comment]
@ganicke these are likely generic docs. Is this possible?

**Comment by ganicke** [comment]
Fixed just as a general message, sorry - https://github.com/microsoft/pxt/pull/7125

**Comment by microbit-mark** [comment]
Thanks @ganicke This is fine.
