### ISSUE TITLE
Download broken in the windows 10 app

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#3212]
I keeps seeing compile error. There is no workaround. Likely caused by webusb changes. 

**To Reproduce**
- Install Visual Studio 2015 & windows SDK
- Load windows app solution
- Start debugging
- Load beta by load /@beta in the extensions
- Download

See error

**Screenshots**
![image](https://user-images.githubusercontent.com/6107272/83600508-975b4180-a523-11ea-9ab5-159502d52396.png)

![image](https://user-images.githubusercontent.com/6107272/83600445-74c92880-a523-11ea-9a9b-c606d60d0aa2.png)

**Comment by abchatra** [comment]
Firmware version is 0243 which is right version as per: https://makecode.microbit.org/device/windows-app/troubleshoot

**Comment by abchatra** [comment]
Works fine if I follow the same steps in live.

**Comment by abchatra** [comment]
Exact stack
![image](https://user-images.githubusercontent.com/6107272/83601966-7e07c480-a526-11ea-9247-15a66247ba13.png)

**Comment by pelikhan** [comment]
Looks like the winrt stack wasn’t loaded

________________________________

**Comment by pelikhan** [comment]
Of course it works locally. Notice how the USB icon is not visible which should be the case in winrt.
![image](https://user-images.githubusercontent.com/4175913/83661446-01eb9c00-a57b-11ea-9650-a241cb7b8076.png)

**Comment by abchatra** [comment]
This is still not fixed in /beta
![image](https://user-images.githubusercontent.com/6107272/83729644-c1ccfd80-a5fc-11ea-9ac9-7f12956e87fd.png)

Now it pops a dialog with option to save.

**Comment by abchatra** [comment]
I aslo see webusb icon
![image](https://user-images.githubusercontent.com/6107272/83729965-4750ad80-a5fd-11ea-9852-cd6400857f40.png)

**Comment by abchatra** [comment]
Also it looks flashed and waited and came back with this dialog
![image](https://user-images.githubusercontent.com/6107272/83730576-1f157e80-a5fe-11ea-9a04-0cb161c2aae2.png)

**Comment by abchatra** [comment]
Looks like issue is specific to Interface Version: 0243 
I tried one with 0253 and it worked like charm

**Comment by abchatra** [comment]
Tried live and bug doesn't exist. Repro: Try flashing on 0243 hardware.

**Comment by pelikhan** [comment]
The USB icon is expected as it is now using the same UI infrastructure. It indicates that windows is connected to the device.

**Comment by abchatra** [comment]
Fixed
