### ISSUE TITLE
Project icon color looks wrong in windows 10

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3217]
* browser
![image](https://user-images.githubusercontent.com/4175913/83665023-aff94500-a57f-11ea-94fb-0ab797834a68.png)

* windows 10

![image](https://user-images.githubusercontent.com/4175913/83665005-a7087380-a57f-11ea-80da-296ed49baf03.png)

**Comment by abchatra** [comment]
Won't fix edge specific bugs.

**Comment by abchatra** [comment]
Unless they are blocking. Won't fix UI bugs which are not blocking.
