### ISSUE TITLE
Remove microbit.co.uk and microbit touchdevelop support

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3218]
It's still there and most likely broken.

https://github.com/microsoft/pxt-microbit/blob/master/editor/extension.tsx#L26

**Comment by abchatra** [comment]
@pelikhan can you fix this one?

**Comment by pelikhan** [comment]
Just need to clear that array of converters.

**Comment by abchatra** [comment]
fixed
