### ISSUE TITLE
Windows 10 app not saving

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3220]
Seeing some conflicts on .simstate.json. It prevents saving in Windows 10 app.

    merge error for .simstate.json: previous content changed...

**Comment by abchatra** [comment]
Save icon works for me in the app.

**Comment by pelikhan** [comment]
I mean it is not saving to files. Changes are being lost because of a conflict on be sim file.

________________________________

**Comment by abchatra** [comment]
It is saving file for me. I modified appxmanifest to directly point to beta when I launch through VS. 

Can you elaborate your repro?

**Comment by pelikhan** [comment]
The .simsate.json should be consiste to ignored. It happens after changing code and using the editor. Hard to flag because the error is silent.

________________________________

**Comment by pelikhan** [comment]
Can't test since the beta is locked on 3.0

**Comment by abchatra** [comment]
I am porting the changes right now.

**Comment by abchatra** [comment]
Done. /beta points to 3.0.7

**Comment by pelikhan** [comment]
Fixed.
