### ISSUE TITLE
Error appears when switching to python editor in tutorial 'Heads Guess'

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3223]
**Describe the bug**
Error appears when switching to **python editor** in tutorial 'Heads Guess'

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#editor
2.Game->Heads Guess->Start Tutorial
3.Finish the tutorial and switch to python editor

**Expect behavior**
No error appears  as switching to **JS editor**

**Actual behavior**
Error appears when switching to **python editor** 
![1](https://user-images.githubusercontent.com/59192069/83709467-36ca2280-a651-11ea-9ebd-b69210faf9c7.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.0.6
3.Microsoft MakeCode version: 6.0.7

**Comment by abchatra** [comment]
@darzu can you prioritize this. Blockly to python and back meets the bar.

**Comment by darzu** [comment]
These blocks:
![image](https://user-images.githubusercontent.com/6453828/83782032-26f81180-a644-11ea-9df9-011e2cae220b.png)

becomes:
```
input.onButtonPressed(Button.A, function () {
    index = Math.randomRange(0, text_list.length - 1)
    basic.showString("" + (text_list[index]))
})
let index = 0
let text_list: string[] = []
text_list = ["a", "b", "c", "d"]
```
becomes:
```
def on_button_pressed_a():
    global index
    index = Math.random_range(0, len(text_list) - 1)
    basic.show_string("" + (text_list[index]))
input.on_button_pressed(Button.A, on_button_pressed_a)

index = 0
text_list: List[str] = []
text_list = ["a", "b", "c", "d"]
```
![image](https://user-images.githubusercontent.com/6453828/83782122-3d05d200-a644-11ea-9b35-fdd18433b6ec.png)

**Comment by darzu** [comment]
@abchatra , this issue is closely related to:
https://github.com/microsoft/pxt-microbit/issues/2637
which I definitely recommend as "next release", I don't understand why we slipped that one.

These issues may or may not have the same underlying cause but I think they're both basic scenarios we need to support.

**Comment by abchatra** [comment]
Issues unable to convert from typescript->python don't meet the bar
Issues unable to convert from Blocks->python meet the bar. 

#2637 Repro didn't state there is a blocks to python issue.

**Comment by darzu** [comment]
All blocks->python goes through typescript->python.
#2637 is about python compilation, which is neither of the above.

Just looking at #2637 python code, it seems like a very beginner scenario. Like this issue shows, getting the length of an array is very basic if you want to do anything with arrays.
Unless we state we're not supporting arrays in Python, we should fix #2637.

**Comment by abchatra** [comment]
What I mean is Typescript has more language constructs than blocks. So we are limiting it to Typescript    derivable from blocks should compile in python

**Comment by darzu** [comment]
> What I mean is Typescript has more language constructs than blocks. So we are limiting it to Typescript derivable from blocks should compile in python

I see, yes I agree. But length is definitely blocks-derivable.

**Comment by abchatra** [comment]
@mmoskal do you know how much is the work to support #2637?

**Comment by darzu** [comment]
#2637 is something I can fix too, it shouldn't be too bad

**Comment by abchatra** [comment]
Go for it
