### ISSUE TITLE
"on start" can't be searched by only typing "on"

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3225]
**Describe the bug**
**"on start"** can't be searched by only typing **"on"**

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Click New Project
3.Type **"on"** in the toolbox
4.Type **"on start"** in the toolbox

**Expect behavior**
"set value to" can show after typing "on"

**Actual behavior**
"set value to" can't be searched only typing **"on"**. But it can be searched if typing **"on start"**.
![3](https://user-images.githubusercontent.com/59192069/83722016-cfbb6680-a66e-11ea-9367-02e403602c2b.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.0.6
3.Microsoft MakeCode version: 6.0.7

**Comment by abchatra** [comment]
Won't fix. Fuzzy search is hard if you type only two letters.
