### ISSUE TITLE
No image on 'radio-firefly' extensions

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3226]
**Describe the bug**
No image on 'radio-firefly' extensions

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#editor
2.Click Extensions
3.Search by 'radio'

**Actual behavior**
No image on 'radio-firefly' extensions
![image](https://user-images.githubusercontent.com/59192069/83724120-4f970000-a672-11ea-8420-83473b47228c.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.0.6
3.Microsoft MakeCode version: 6.0.7

**Comment by abchatra** [comment]
@ganicke need help. If you can find an image that would be lovely.

**Comment by ganicke** [comment]
How about something like:

![image](https://user-images.githubusercontent.com/27789908/115665166-b60f2600-a2f7-11eb-87ba-7cdc715b0e32.png)

This will need to go into https://github.com/microsoft/pxt-radio-firefly as `icon.png`.

**Comment by ganicke** [comment]
@abchatra - you can approve and merge https://github.com/microsoft/pxt-radio-firefly/pull/1 to get the icon in.

**Comment by abchatra** [comment]
Thanks @ganicke!

**Comment by abchatra** [comment]
This looks awesome and I love it.

**Comment by ganicke** [comment]
Thanks!
