### ISSUE TITLE
The first icon zooms in automatically when clicking any tutorials

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3227]
**Describe the bug**
The first icon zooms in automatically when clicking any tutorials

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Click any tutorials

**Expect behavior**
The three icons are the same size, and which icon the mouse moves to, which icon is enlarged.
![5](https://user-images.githubusercontent.com/59192069/83726529-385a1180-a676-11ea-969d-a9cf34b31bf3.gif)

**Actual behavior**
The first icon zooms in automatically .And when the mouse moves to the second or third icon, it is still zoomed in.
![4](https://user-images.githubusercontent.com/59192069/83726371-06e14600-a676-11ea-9919-04ff94b1450d.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.0.6
3.Microsoft MakeCode version: 6.0.7

**Comment by shakao** [comment]
this is by design, for accessibility reasons. we focus the first tutorial card so that people using tab navigation can enter the tutorial with as few keystrokes as possible. maybe when you hover over the other cards it should clear the focus from the first one, though

**Comment by pelikhan** [comment]
Feels like we need a different UI effect on hover vs selected.

**Comment by Sheila111** [comment]
@shakao  still not fixed
![1](https://user-images.githubusercontent.com/59192069/86197314-b6330f00-bb87-11ea-9129-60d65467429a.gif)

**Comment by shakao** [comment]
@Sheila111 This change has not been released to microbit but you can see it in arcade.makecode.com/beta, if you click on one of the cards under "Community Games"

**Comment by Sheila111** [comment]
@shakao I see it in arcade. Thanks.
