### ISSUE TITLE
Edge event for pin is not working

### ISSUE THREAD

**Issue by waiweng83** [microsoft/pxt-microbit#3231]
**Describe the bug**
Rising or falling edge event for pin is not fired.

**To Reproduce**
```
pins.setEvents(DigitalPin.P8, PinEventType.Edge)
control.onEvent(EventBusSource.MICROBIT_ID_IO_P8, EventBusValue.MICROBIT_PIN_EVT_RISE, function () {
    led.toggle(0, 0)
})
```
This code doesn't work and the LED is not toggle when sending high to pin 8.

**Expected behavior**
This works on the released version but not the beta version.

**Comment by abchatra** [comment]
@mmoskal @pelikhan any clue here? Did we change anything?

**Comment by pelikhan** [comment]
Could be due to a change the constant value when normalizing to codal

**Comment by abchatra** [comment]
@mmoskal can you take a peek please?

**Comment by pelikhan** [comment]
dal value:
```
#define MICROBIT_PIN_EVENT_ON_EDGE          1
```
codal value: 
```
#define DEVICE_PIN_EVENT_ON_EDGE          2
```

**Comment by abchatra** [comment]
Good bug @waiweng83 Thanks for reporting.

**Comment by mmoskal** [comment]
Easier testcase for reference:

```typescript
pins.setPull(DigitalPin.P0, PinPullMode.PullDown)
pins.digitalReadPin(DigitalPin.P0)
pins.setEvents(DigitalPin.P0, PinEventType.Edge)
control.onEvent(EventBusSource.MICROBIT_ID_IO_P0, EventBusValue.MICROBIT_PIN_EVT_RISE, 
function () {
    led.toggle(0, 0)
})
```

To test, touch 3V to P0.

**Comment by waiweng83** [comment]
> Good bug @waiweng83 Thanks for reporting.

No problem. I was using it in my extension and it was broken.
Thanks.
