### ISSUE TITLE
App scroll bar is shown when expanding drop down in block

### ISSUE THREAD

**Issue by livcheerful** [microsoft/pxt-microbit#3234]
**Describe the bug**
The Windows App is generating a scroll bar when the workspace seems like it wants to go out of bounds

**To Reproduce**
1. Bring a block with a drop down menu to the bottom of the workspace
2. Click on the drop down
3. A scrollbar for the app is created on the right side

**Expected behavior**
No scrollbar should be made

**Screenshots**
Before clicking dropdown:
![image](https://user-images.githubusercontent.com/18712271/83911064-77dd3800-a720-11ea-8806-931bd64b570d.png)

After clicking dropdown: (scrollbar on right side)
![image](https://user-images.githubusercontent.com/18712271/83911113-95120680-a720-11ea-93c6-a840f5ab4de5.png)

**Desktop (please complete the following information):**
 - OS: Windows App

**Comment by abchatra** [comment]
Won't fix minor windows app bugs.
