### ISSUE TITLE
Can't right click for copy/paste in app

### ISSUE THREAD

**Issue by livcheerful** [microsoft/pxt-microbit#3235]
**Describe the bug**
When trying to import a project in the Windows app, I can't right click in the URL input to show copy/paste

**To Reproduce**
1. Go to the main page
2. Click 'Import'
3. Click 'Import URL'
4. Try to right click in the input box
5. Nothing happens

**Expected behavior**
A right click dropdown comes down to show copy/paste options like in the web version

**Screenshots**
The web version:
![image](https://user-images.githubusercontent.com/18712271/83914871-f0df8e00-a726-11ea-9749-ef02ad475b4c.png)

**Desktop (please complete the following information):**
 - Windows App

**Comment by abchatra** [comment]
Won't fix minor windows app bugs.
