### ISSUE TITLE
Muting simulator does not persist after changing language (sound automatically turns on)

### ISSUE THREAD

**Issue by kimprice** [microsoft/pxt-microbit#3236]
**Describe the bug**
If you mute the simulator and then change the language, when the editor refreshes in the selected language, the sound is automatically on.

**To Reproduce**
1. In the editor click the sound button under the simulator to mute.
2. Then change the language.
3. See the simulator automatically have the sound on.

**Expected behavior**
The mute setting should persist after language translation.

**Additional context**
I believe this error is unrelated to the medium/browser/desktop being used and it occurs both in live and beta. I have seen this behavior in chrome, edge, and on electron app.

**Comment by abchatra** [comment]
Won't fix editor reload bugs.
