### ISSUE TITLE
IntelliSense does not show local user-defined variables in Electron App (Windows offline)

### ISSUE THREAD

**Issue by kimprice** [microsoft/pxt-microbit#3237]
**Describe the bug**
In Electron App, intellisense does not show locally defined variable as option. In the example below, you see neither elapsed or score comes up as options. Variables defined in the global context do show up if you begin to type them. For example, "start" would have showed up if I began typing it.

**To Reproduce**
1. Create a variable in a local context such as within a button press function.
2. Start typing the variable name on a new line within the same scope and see that it does not come up as an option for completion.

**Expected behavior**
Local variables should be seen as options for intellisense completion.

**Gif and Screenshot**
![example](https://user-images.githubusercontent.com/15070078/83917565-21cebb80-a745-11ea-95fb-8235f4e01cff.gif)
![image](https://user-images.githubusercontent.com/15070078/83917588-2c895080-a745-11ea-9d51-d131542161ad.png)

**Desktop (please complete the following information):**
Electron App - Windows offline

**Comment by jwunderl** [comment]
This ones not a monaco bug, just an editor bug -- repros on website/beta as well

**Comment by darzu** [comment]
Fixed in latest JS and PY
![2021-04-13 10 27 11](https://user-images.githubusercontent.com/6453828/114595142-e80ef100-9c42-11eb-9167-de9341028f70.gif)

<img width="848" alt="image" src="https://user-images.githubusercontent.com/6453828/114595127-e3e2d380-9c42-11eb-80ea-c4de5e6959a5.png">
