### ISSUE TITLE
Cannot go to blocks from this program

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#3241]
From here: https://makecode.microbit.org/_T2TgUYLKMVDJ
in /beta
click "Blocks" and then "Discard and go to Blocks".

Nothing happens.

We should switch to blocks if there are any or at least a blank blocks canvas or something. As it  is, the only way the user can get to blocks is by deleting all the code and then  switching.

**Comment by abchatra** [comment]
The way it is designed is, we need to have blocks files to discard errors and go to last known good state. If not we can't go back to blocks. I am inclined to close this as by designed.

**Comment by jwunderl** [comment]
The issue here is that it doesn't go back to the last known good state (/ that doesn't exist maybe?) - when you click `discard and go to blocks` it doesn't actually go to blocks in that program

**Comment by abchatra** [comment]
It is strange. It stopped reproing for me in /beta

**Comment by abchatra** [comment]
Fixed
