### ISSUE TITLE
Can't share project in Windows offline use of Electron app

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3243]
**Describe the bug**
Can't share project in Windows offline use of Electron app

**Steps to reproduce the behavior**
1.Open Microbit app
2.New Project----->Drag some blocks
3.Share Project

**Expect behavior**
Share project in Windows offline use of Electron app

**Actual behavior**
Can't share project in Windows offline use of Electron app
![share-offline](https://user-images.githubusercontent.com/59192069/84128722-88204a80-aa73-11ea-8577-21eec55bf907.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.0.10
3.Microsoft MakeCode version: 6.0.11

**Comment by abchatra** [comment]
Yes sharing won't work if there is no internet. As it requires internet connection.
