### ISSUE TITLE
Electron app - Micro: Coin can't load blocks

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#3244]
**Describe the bug**
Electron app - **Micro: Coin** can't load blocks

**Steps to reproduce the behavior**
1.Open Microbit app
2.Radio Games -> Micro: Coin->Show Instructions

**Expect behavior**
**Micro: Coin** should show blocks normally 

**Actual behavior**
**Micro: Coin** can't load blocks
![coin](https://user-images.githubusercontent.com/58197774/84130678-244b5100-aa76-11ea-8a51-bb183264cd01.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.0.10
3.Microsoft MakeCode version: 6.0.11

**Comment by abchatra** [comment]
If you are completely offline. This is expected. All the extensions require connectivity and this tutorial uses extension radio-blockchain
