### ISSUE TITLE
Can’t download code in Electron app

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3252]
**Describe the bug**
Can’t download code in Electron app

**Steps to reproduce the behavior**
1.Open Microbit app
2.New Project---->add some code 
3.Click download

**Expect behavior**
Download code successfully

**Actual behavior**
Can’t download code and shows error online & offline
![download](https://user-images.githubusercontent.com/59192069/84372235-65c23480-ac0d-11ea-98bf-599b20b1001f.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.0.10
3.Microsoft MakeCode version: 6.0.11

**Comment by abchatra** [comment]
I can reproduce. Empty file it failed and other time it is spinning forever.
