### ISSUE TITLE
Indexing into string array does not compile in Python

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#3254]
These blocks error when converted to Python:
![image](https://user-images.githubusercontent.com/6453828/84422812-6d181c80-abd2-11ea-9f03-af7361f231cb.png)

converts to this JS:
```
let foo = ["bar", "baz"]

input.onButtonPressed(Button.B, function () {
    let s = foo[foo.length - 1]
    basic.showString(s)
})
```
and this python:
```
foo = ["bar", "baz"]

def on_button_pressed_b():
    s = foo[len(foo) - 1]
    basic.show_string(s)
input.on_button_pressed(Button.B, on_button_pressed_b)
```
which shows:
![image](https://user-images.githubusercontent.com/6453828/84422735-4f4ab780-abd2-11ea-8262-0c109bba65a5.png)

which is incorrect. This is a py->ts issue.

**Comment by darzu** [comment]
@abchatra , this we probably want to fix asap

**Comment by pelikhan** [comment]
This bug makes arrays completly unusable.
