### ISSUE TITLE
Simulator isn't displayed correctly after printing code

### ISSUE THREAD

**Issue by livcheerful** [microsoft/pxt-microbit#3256]
**Describe the bug**

**To Reproduce**
1. In the editor, click the gear button in the top right for settings
2. Click 'Print'
3. After the print dialog box in Chrome pops up, the simulator gets cut off to just one corner
4. After closing the dialogs, the simulator doesn't come back

**Expected behavior**
The simulator gets restored after returning back to editing

**Screenshots**
What the simulator looks like with the print dialog open
![image](https://user-images.githubusercontent.com/18712271/84423834-f2500100-abd3-11ea-9198-8ac18274b2ea.png)

After closing, it stays the same
![image](https://user-images.githubusercontent.com/18712271/84423758-d0567e80-abd3-11ea-8bf6-1d076e0e5f53.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 83.0.4103.97

**Comment by abchatra** [comment]
This seems to be fixed. If not let me know.
