### ISSUE TITLE
Editing the code then quickly switching languages erases the edit

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#3257]
**Describe the bug**
![bug-debounce](https://user-images.githubusercontent.com/34112083/84424449-f892ad00-abd4-11ea-9402-4ee190d295b7.gif)

Using old Edge, but also repros in Chrome. Possibly related to the debounce behavior?

**Comment by abchatra** [comment]
Reopening this as the fix had simulator autorun regressions
