### ISSUE TITLE
Comments aren't included when printing code

### ISSUE THREAD

**Issue by livcheerful** [microsoft/pxt-microbit#3258]
**Describe the bug**

**To Reproduce**
1. Make a block, and attach a comment to it
2. Go to settings -> Print
3. The comment isn't show when trying to print :(

Here's a project with a comment expanded:
https://makecode.microbit.org/_XmFcdb0z6Y7L

**Expected behavior**
If the comment is expanded, I'd expect it to be included in the print preview

**Screenshots**
Print preview: 
![image](https://user-images.githubusercontent.com/18712271/84425037-cc2b6080-abd5-11ea-9d61-daeb1bd85c0c.png)

Workspace:
![image](https://user-images.githubusercontent.com/18712271/84425064-d77e8c00-abd5-11ea-8389-0a46996dd37b.png)

**Desktop (please complete the following information):**

**Comment by abchatra** [comment]
Fixed
