### ISSUE TITLE
Old Edge: after switching languages, details pane missing Python/JS cards

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#3261]
**Describe the bug**
Happened twice in old Edge, but inconsistently, and I could not repro it in Chrome.

**To Reproduce**
1. On the home screen, scroll to the bottom and change the language
2. Once the page reloads, click on one of the tutorial cards
3. Observe that only the purple "Blocks" card is shown
4. On refresh, all cards appear

**Comment by abchatra** [comment]
Won't fix old edge bugs.

**Comment by yf-chen** [comment]
Why do I not display Chinese after I switch Chinese

**Comment by shakao** [comment]
@yf-chen hi! you can [file a bug](https://github.com/microsoft/pxt-microbit/issues/new/choose) for this here: https://github.com/microsoft/pxt-microbit/issues/new/choose 

please include screenshots and a clear description of what is happening, where possible!
