### ISSUE TITLE
Summary table of contents is broken in other languages

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#3263]
Not specific to micro:bit, also happens in arcade. The summary has several missing labels

<img width="262" alt="Screen Shot 2020-06-11 at 3 18 53 PM" src="https://user-images.githubusercontent.com/13754588/84444532-df025d00-abf6-11ea-9971-dbe034ac185d.png">

Happens for all languages except english. the localization is probably messing up the markup

**Comment by jwunderl** [comment]
@shakao here's the old issue for this in case anything in there helps give context: https://github.com/microsoft/pxt-microbit/issues/2807

**Comment by pelikhan** [comment]
Does this fix need to be ported to the backend?

**Comment by shakao** [comment]
oh yeah, i'll make a pr updating backendutils

**Comment by abchatra** [comment]
Fixed
