### ISSUE TITLE
Missing code highlighting in SPY tutorials

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#3264]
We're missing the line highlighting in the Spy tutorials.

![image](https://user-images.githubusercontent.com/22108954/84449875-7ec5e800-ac03-11ea-860b-c33145eddfb5.png)

**Comment by abchatra** [comment]
@pelikhan is this for @ganicke to add the right markdown things?

**Comment by pelikhan** [comment]
We should add

    ### @diffs true

**Comment by ganicke** [comment]
Closing per comments: https://github.com/microsoft/pxt-microbit/pull/3288#issuecomment-707828445 and https://github.com/microsoft/pxt-microbit/pull/3288#issuecomment-707910326.
