### ISSUE TITLE
tutorial/sidedocs not shown in Editor (online and in MS Teams)

### ISSUE THREAD

**Issue by DaniloJust** [microsoft/pxt-microbit#3269]
Hi 

tutorials are not shown anymore in the sidedocs (tutorials which are added to README.md).
see here: [https://makecode.microbit.org/#pub:_czm0kKMTkXXF](url)

When clicking on Javascript => readme.md than the sidedoc is shown.

**Comment by abchatra** [comment]
This is fixed and a hotfix released to microbit editor. Please test.

**Comment by DaniloJust** [comment]
Fix is working fine in Version 3.0.13 (tested with MS Teams plugin). Thx for the prompt response - the kids in our online coding course are happy to see the provided tutorials in editor now again by default :-) . Issue is closed
