### ISSUE TITLE
The simulator does not run automatically

### ISSUE THREAD

**Issue by asondemita** [microsoft/pxt-microbit#3273]
**Describe the bug**

The simulator does not run automatically.
Due to this effect, the downloaded program is the previous build images.
The problem occurs in v3.0.13.
It does not occur in v3.0.12.

**To Reproduce**
1. https://makecode.microbit.org/v3.0.13
2. Drop something block.

**Screenshots**

![simulator_auto_re-start](https://user-images.githubusercontent.com/7057616/84593678-539ffa80-ae88-11ea-8c1d-cba534c8cbb1.gif)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser chrome
 - Version 83

**Comment by abchatra** [comment]
Fixed in latest

**Comment by abchatra** [comment]
In 3.0.14

**Comment by abchatra** [comment]
Thanks @asondemita for reporting this quick
