### ISSUE TITLE
Simulator and code embeds no longer work

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3276]
micro:bit support 38117, 38133

**Describe the bug**
"When we share project, the embed link of the simulator is broken.
All the embed links off the simulator i've made on all my genially or others Moodle Cours arre broken"

User reports that when using the embed code for the simulator, the simulator does not appear.
I can reproduce this.

Another user reports taht code embeds do not work either

**To Reproduce**
1. Open MakeCode project
2. Share project
3. Select embed simulator or code and copy and paste code into an html file
4. Open html file, simulator shows as loading but does not load

**Expected behavior**
Sim should load as with editor and code

**Screenshots**
<img width="1437" alt="Screenshot 2020-06-15 at 12 50 38" src="https://user-images.githubusercontent.com/31242877/84654697-8c32e900-af07-11ea-916e-c947cfcae5c1.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abchatra** [comment]
Fixed

**Comment by abchatra** [comment]
And released as a hotfix 3.0.17

**Comment by microbit-mark** [comment]
Thanks for the quick fix. These work again, but appear to break old melody block embeds

![image](https://user-images.githubusercontent.com/31242877/85406511-d6e0e080-b559-11ea-8c03-faf8348c522c.png)

**Comment by microbit-mark** [comment]
@abchatra The Melody API embeds are still causing issues https://github.com/microsoft/pxt-microbit/issues/3276#issuecomment-648131178, can we fix for users that include these blocks

**Comment by abchatra** [comment]
@microbit-mark can you open a new issue? I am not sure this is the same issue as we fixed in the past.
