### ISSUE TITLE
Array indexing does not compute type information

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3277]
This demo program does not compile in python.  
![image](https://user-images.githubusercontent.com/4175913/84681872-a78efb80-aee9-11ea-8c30-3d216b37ea8c.png)

Smaller repro:
```
faces = [images.create_image("""
    . . . . .
    . . . . .
    . . # . .
    . . . . .
    . . . . .
    """)]
faces[0].show_image(0)
```

**Comment by abchatra** [comment]
Is this not same as https://github.com/microsoft/pxt-microbit/issues/3254?

**Comment by pelikhan** [comment]
Oh we had a bug on this. It's a P1. it makes arrays unusable.
