### ISSUE TITLE
when run pxt staticpkg or pxt serv command ,There have been some errors

### ISSUE THREAD

**Issue by sunt89** [microsoft/pxt-microbit#3282]
**env info:**
system: windows server 2016
npm version: 6.14.4
node version: v12.18.0
pxt version: pxt-6.1.17
visual studio version: visual studio community 2017
python version: 2.7.18
micorbit version: 3.0.14

**error info**
when i exec pxt staticpkg command, there are some errors in the log

C:\DevDir\makecode\pxt-microbit>pxt staticpkg
Using target microbit with build engine yotta
  target: v3.0.14 C:\DevDir\makecode\pxt-microbit
  pxt-core: v6.1.17 C:\DevDir\makecode\pxt-core
packaging editor to built/packaged
log strings: 31 files; 9 strings -> sim-strings.json
copying common-sim...
**error TS6053: File 'C:/DevDir/makecode/pxt-core/built/lib.dom.d.ts' not found.
error TS6053: File 'C:/DevDir/makecode/pxt-core/built/lib.dom.iterable.d.ts' not found.
error TS6053: File 'C:/DevDir/makecode/pxt-core/built/lib.es2015.d.ts' not found.
error TS6053: File 'C:/DevDir/makecode/pxt-core/built/lib.scripthost.d.ts' not found.
error TS2318: Cannot find global type 'Array'.
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
error TS2318: Cannot find global type 'String'.**
building compiler...
[run] cd compiler; node ../node_modules/typescript/bin/tsc

**Comment by abchatra** [comment]
Safe to ignore these.
