### ISSUE TITLE
Function call block missing in Traditional Chinese

### ISSUE THREAD

**Issue by FranklinWhale** [microsoft/pxt-microbit#3285]
**Describe the bug**
The `call XXX` block is missing after JavaScript to blocks conversion in Traditional Chinese.

**To Reproduce**
1. Set the language to Chinese (Traditional)
2. Switch to JavaScript
3. Paste the following code to the editor
```ts
function doSomething() {
    return 0
}
basic.showNumber(randint(0, doSomething()))
```
4. Switch to Blocks

**Expected behavior**
![image](https://user-images.githubusercontent.com/8416067/85005624-a7ae2600-b18b-11ea-84dc-457f35fadca8.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/8416067/85005707-bf85aa00-b18b-11ea-8c6b-228bdd338ec5.png)

**Additional context**
This issue is reproducible in the beta version. It works under English however.

**Comment by riknoll** [comment]
This is a bad translation on the randint block. The name of the second input was changed from limit to max

**Comment by jwunderl** [comment]
fixed translation, will take a bit to propagate https://crowdin.com/translate/kindscript/65/en-zhtw#937334

**Comment by abchatra** [comment]
Fixed. Translation will reflect in 24 hours. If not let us know.

**Comment by FranklinWhale** [comment]
Sadly the fix does not seem to work... I cleared cache, and tried in both live and beta.

**Comment by jwunderl** [comment]
Oops, looks like I missed the approve button; it didn't show up for some reason when I put in the fix and seemed like it was approved. Sorry about that, I guess another day for the cache now :(

**Comment by FranklinWhale** [comment]
Verified fixed. Thanks!
