### ISSUE TITLE
Feature: Address multiple pins for read/write

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3286]
micro:bit support: 38024
**Is your feature request related to a problem? Please describe.**
If I want to turn multiple pins on/off eg using digital.write, I have to duplicate lots of blocks to do so. I can use a function, but even this has to have multiple blocks within it.

**Describe the solution you'd like**
A block to set a number of pins eg write pins from 0 - 6 to a value

**Describe alternatives you've considered**
I can use a function, but it's still uses a lot of blocks in order to write it.
<img width="347" alt="Screenshot 2020-06-18 at 16 58 41" src="https://user-images.githubusercontent.com/31242877/85044037-04f2a900-b185-11ea-8ae7-cd6d3c35a296.png">
**Additional context**

**Comment by Arif1971** [comment]
Hi guys.
Developing this feature will minimize number of blocks used and shorten the sequence.
Hope we can see it shortly.

**Comment by pelikhan** [comment]
Best to create a new package that provides custom blocks to do these operationrs.

**Comment by abchatra** [comment]
No plans to address this issue.

**Comment by abchatra** [comment]
There are workarounds as well.
