### ISSUE TITLE
v2 and live are showing different projects

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#3289]
**Describe the bug**

I am seeing different projects for 
https://makecode.microbit.org/
and 
https://makecode.microbit.org/v2/

It looks like new files created with either don't appear on the other.
 
**To Reproduce**
1. Go to 'https://makecode.microbit.org/v2/'
2. Create a new project "new-v2"
3. Go Home
4. Go to 'https://makecode.microbit.org/'
5. See new-v2 is not visible

**Expected behavior**
New files created on v2 would be available on live.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows, mac OS
 - Browser [e.g. chrome, safari] Chrome, Safari

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPad air 2
 - OS: [e.g. iOS8.1] iOS 13.4.1
 - Browser [e.g. stock browser, safari] Safari

**Comment by abchatra** [comment]
That is how the version mechanism works.  There is one time portability of files when the upgrade happens and the files will not be reflected.  Usually compatibility is broken and new files won't work in older editor. If someone choses to use older editor they will have their files in that editor.

**Comment by martinwork** [comment]
Thanks for explaining @abchatra . I was looking at this as a way to target a specific version of MakeCode in the iOS app.

The iOS app currently uses the URL
`https://makecode.microbit.org/`
which means it is launching a version of MakeCode which has incompatible features.

Suppose the next upgrade of the iOS app was to start using the URL
`https://makecode.microbit.org/v3/ `
and the upgrade of the iOS app after the next MakeCode upgrade would use
`https://makecode.microbit.org/v4/`

Will that work without loss of projects?

**Comment by abchatra** [comment]
Please don’t use version tag for website. They are only to maintain backward compatibility. They don’t get any fixes (other than security) and documentation and reference are also frozen. Share pages don’t point to them. There is only backward compat and no forward compat in the website. Projects built in v3 will not work on v2 etc. 

That is not the right way to use the versioned website. What is the use case for your scenario?

**Comment by martinwork** [comment]
This was suggested to me as a way to protect the iOS app from incompatible changes in MakeCode.

For example the current version of the iOS app was not ready for the new MakeCode GitHub support.

I'm not sure exactly where the suggestion arose and perhaps I misunderstood.

@jaustin ?  @microbit-mark ?
