### ISSUE TITLE
Add note name labels on melody sequencer

### ISSUE THREAD

**Issue by microbit-giles** [microsoft/pxt-microbit#3290]
**Is your feature request related to a problem? Please describe.**
I tried to recreate a simple tune project using the melody sequencer and found it frustrating because the block editor does not show note names.

**Describe the solution you'd like**
I would like note name labels on the editor - either always present or on hover, perhaps inside the colour square - to make assembling a known melody easier.

**Describe alternatives you've considered**
You can switch to JavaScript to read note names but this is more complex 

**Additional context**

![Screenshot 2020-06-23 at 10 16 43](https://user-images.githubusercontent.com/42380137/85386011-f0266480-b53a-11ea-93ca-9abe96333729.png)

**Comment by abchatra** [comment]
Note names are not language agonistic. Hence we didn't add. Typescript is always English, so it is bit ok there.

**Comment by abchatra** [comment]
No plans to implement.
