### ISSUE TITLE
git repo creation does not use current project name

### ISSUE THREAD

**Issue by MINTGenie** [microsoft/pxt-microbit#3291]
**Describe the bug**
Name for git repo (or the project) cannot be changed after starting (for new projects)

**To Reproduce**
1. create a new project with a name (say “tmp”) and then save it with a different name (say “msg sender”) after starting
2. then the github project is still created with the original name (/tmp). 
Is this expected? 

**Expected behavior**
if the github project is not yet created why cant it use the name provided in the box at the time of push/commit.

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 
![image](https://user-images.githubusercontent.com/66748747/85520881-c8e79a00-b603-11ea-8b33-829aa9b2a09b.png)
![image](https://user-images.githubusercontent.com/66748747/85520918-d69d1f80-b603-11ea-9e7c-2baefa506796.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: chrome
 - Version: Version 83.0.4103.106

**Comment by shakao** [comment]
closing, as this no longer repros for me! feel free to reopen if the issue returns
