### ISSUE TITLE
Project names different in different views

### ISSUE THREAD

**Issue by MINTGenie** [microsoft/pxt-microbit#3292]
**Describe the bug**
Project names shown differently when viewed in default Home page and when clicked on "View all"

**To Reproduce**
1. Open project with a name
2. change the name of the project in the editor window
3. go back to home page by clicking on Home button 

**Expected behavior**
Names have to be same in all views

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 
![image](https://user-images.githubusercontent.com/66748747/85521483-98ecc680-b604-11ea-87d7-e7eecea7ce27.png)

![image](https://user-images.githubusercontent.com/66748747/85521500-9db17a80-b604-11ea-955f-44bfc9ddacc2.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome
 - Version: 83.0.4103.106

**Comment by abchatra** [comment]
This is likely related to https://github.com/microsoft/pxt-microbit/issues/3291
Names are not consistent in github projects.

**Comment by shakao** [comment]
fixed by peli with https://github.com/microsoft/pxt/pull/8081
