### ISSUE TITLE
Sign-in/out of github breaks makecode.com/multi editor

### ISSUE THREAD

**Issue by MINTGenie** [microsoft/pxt-microbit#3293]
**Describe the bug**
Sign-in/out of github breaks makecode.com/multi editor also if you have signed out of github, the multi-editor does not let you sign in

**To Reproduce**
1. in the multi editor - click Sign out
or
1. if not signed in already - click save to github icon (sign in page not displayed)

**Expected behavior**
multi editor also has to provides same interface to sign in/out of github just like main microbit editor (single)

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

------------Below is chrome console msg -------------------

[Deprecation] Application Cache API manifest selection is deprecated and will be removed in M82, around May 2020. See https://www.chromestatus.com/features/6192449487634432 for more details.
api.github.com/repos/mintgenie/tmp/git/refs/heads/master?rnd=0.4805799821190935:1 Failed to load resource: the server responded with a status of 404 (Not Found)
api.github.com/repos/mintgenie/tmp/git/refs/heads/?per_page=100&rnd=0.056625874972031864:1 Failed to load resource: the server responded with a status of 404 (Not Found)
api.github.com/repos/mintgenie/tmp/git/refs/heads/master?rnd=0.15735213908801304:1 Failed to load resource: the server responded with a status of 404 (Not Found)
api.github.com/repos/mintgenie/tmp/git/refs/heads/?per_page=100&rnd=0.7492599848181702:1 Failed to load resource: the server responded with a status of 404 (Not Found)
api.github.com/repos/mintgenie/tmp/git/refs/heads/?per_page=100&rnd=0.1605523719798969:1 Failed to load resource: the server responded with a status of 404 (Not Found)
api.github.com/repos/mintgenie/tmp/git/refs/heads/?per_page=100&rnd=0.6234482348035681:1 Failed to load resource: the server responded with a status of 404 (Not Found)
api.github.com/repos/mintgenie/tmp/git/refs/heads/?per_page=100&rnd=0.1877292016121228:1 Failed to load resource: the server responded with a status of 404 (Not Found)
api.github.com/repos/mintgenie/tmp/git/refs/heads/master:1 Failed to load resource: the server responded with a status of 404 (Not Found)
makecode.microbit.org/api/gh/mintgenie/tmp/refs?rnd=0.38759475659541875:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.github.com/repos/mintgenie/tmp/git/refs/heads/master:1 Failed to load resource: the server responded with a status of 404 (Not Found)
makecode.microbit.org/api/gh/mintgenie/tmp/refs?rnd=0.7698264018399184:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.github.com/repos/mintgenie/tmp/git/refs/heads/master:1 Failed to load resource: the server responded with a status of 404 (Not Found)
makecode.microbit.org/api/gh/mintgenie/tmp/refs?rnd=0.7212290877377456:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
multi#:1 A cookie associated with a cross-site resource at http://microbit.org/ was set without the SameSite attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with SameSite=None and Secure. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
pxtapp.js:1 Browser: chrome 83.0.4103.106 on windows
pxtapp.js:1 PouchDB adapter: idb
pxtapp.js:1 packetio: mk wrapper dap wrapper
api.github.com/repos/mintgenie/tmp/git/refs/heads/master:1 Failed to load resource: the server responded with a status of 404 (Not Found)
pxtapp.js:1 webusb: get devices
editor.js:2415 Connecting…
editor.js:2446 Connected
makecode.microbit.org/api/gh/mintgenie/tmp/refs?rnd=0.5057688745947952:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
pxtblockly.js:1 Deprecated call to Blockly.BlockSvg.prototype.setDisabled, use Blockly.BlockSvg.prototype.setEnabled instead.
Blockly.BlockSvg.setDisabled @ pxtblockly.js:1
api.github.com/repos/mintgenie/tmp/git/refs/heads/master:1 Failed to load resource: the server responded with a status of 404 (Not Found)
makecode.microbit.org/api/gh/mintgenie/tmp/refs?rnd=0.12420538399305192:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
pxtweb.js:1 performance report:
first JS running @ 1s272ms
DOM loaded @ 1s301ms
workspace init finished @ 1s500ms
loading started #changeheader @ 34s
loading done #updateeditorfile @ 35s
loading done #changeheader @ 35s
loading done #updateeditorfile @ 39s
loading done #updateeditorfile @ 1m3s
loading done #updateeditorfile @ 1m38s
simulator ready @ 1m38s

	loadBlockly took ~ 549ms
	domUpdate loadBlockly took ~ 1s339ms (35s - 36s)
	domUpdate loadBlockly took ~ 457ms
pxtapp.js:1 packetio: mk wrapper dap wrapper
pxtapp.js:1 webusb: get devices
editor.js:2415 Connecting…
editor.js:2446 Connected
pxtapp.js:1 packetio: mk wrapper dap wrapper
api.github.com/repos/mintgenie/tmp/git/refs/heads/master:1 Failed to load resource: the server responded with a status of 404 (Not Found)
pxtapp.js:1 webusb: get devices
editor.js:2415 Connecting…
editor.js:2446 Connected
pxtapp.js:1 webusb: get devices
editor.js:2415 Connecting…
editor.js:2446 Connected
makecode.microbit.org/api/gh/mintgenie/tmp/refs?rnd=0.03881354359496103:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.github.com/repos/mintgenie/tmp/git/refs/heads/master?rnd=0.3458423976070264:1 Failed to load resource: the server responded with a status of 404 (Not Found)
api.github.com/repos/mintgenie/tmp/git/refs/heads/?per_page=100&rnd=0.7839481203404117:1 Failed to load resource: the server responded with a status of 404 (Not Found)
api.github.com/repos/mintgenie/tmp/git/blobs?rnd=0.28344212133029556:1 Failed to load resource: the server responded with a status of 404 (Not Found)
api.github.com/orgs/mintgenie?rnd=0.44602560348267173:1 Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:1 Uncaught Error: Bad HTTP status code: 404 at https://api.github.com/orgs/mintgenie?rnd=0.44602560348267173; message: {
“message”: “Not Found”,
“documentation_url”: “https://developer.github.com/v3/orgs/#get-an-organization”
}

at https://pxt.azureedge.net/blob/90eb76d9d5fc5aa23f148af3b7a150ef720c3809/pxtapp.js:1:50461
at s (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1037554)
at S._settlePromiseFromHandler (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1011038)
at S._settlePromise (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1011838)
at S._settlePromise0 (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1012537)
at S._settlePromises (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1013864)
at https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:967689
From previous event:
at S.L [as _captureStackTrace] (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:980993)
at S._resolveFromExecutor (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1010580)
at new S (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1003824)
at o (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:480272)
at e.handleCommitClick (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:512541)
at Object. (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1437297)
at _ (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1437335)
at https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1437481
at x (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1437567)
at T (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1438012)
at C (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1437824)
at A (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1438172)
at xn (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1465118)
at le (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1551809)
at Tn (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1465723)
at On (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1466680)
at An (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1465968)
at s.unstable_runWithPriority (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1556600)
at Wi (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1481559)
at ae (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1550422)
at https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1465257
api.github.com/repos/mintgenie/tmp/git/refs/heads/master?rnd=0.5554397946985037:1 Failed to load resource: the server responded with a status of 404 (Not Found)
api.github.com/repos/mintgenie/tmp/git/refs/heads/?per_page=100&rnd=0.24362632737349887:1 Failed to load resource: the server responded with a status of 404 (Not Found)
api.github.com/repos/mintgenie/tmp/git/refs/heads/master?rnd=0.48144743367354614:1 Failed to load resource: the server responded with a status of 404 (Not Found)
api.github.com/repos/mintgenie/tmp/git/refs/heads/?per_page=100&rnd=0.4216242055151358:1 Failed to load resource: the server responded with a status of 404 (Not Found)
pxtapp.js:1 packetio: mk wrapper dap wrapper
pxtapp.js:1 webusb: get devices
editor.js:2415 Connecting…
editor.js:2446 Connected
api.github.com/repos/mintgenie/tmp/git/refs/heads/master:1 Failed to load resource: the server responded with a status of 404 (Not Found)
makecode.microbit.org/api/gh/mintgenie/tmp/refs?rnd=0.5964564135292976:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
multi#:1 A cookie associated with a cross-site resource at http://github.com/ was set without the SameSite attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with SameSite=None and Secure. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
multi#:1 A cookie associated with a cross-site resource at https://github.com/ was set without the SameSite attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with SameSite=None and Secure. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
Refused to frame ‘https://github.com/’ because an ancestor violates the following Content Security Policy directive: “frame-ancestors ‘none’”.

DevTools failed to load SourceMap: Could not parse content for https://pxt.azureedge.net/blob/1e5289a3427782f396a5498a6a3137c864c5d139/purify.min.js.map: Unexpected token ; in JSON at position 12
DevTools failed to load SourceMap: Could not load content for https://pxt.azureedge.net/commit/23c3d8c7f8a0f44f7681d1e3de648cb6b67220d2/dapjs.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not parse content for https://pxt.azureedge.net/blob/dd22520c096be24e7432f5b46e8aad59711f31f0/doccdn/ai.0.js.map: Unexpected token ; in JSON at position 12

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome
 - Version  83.0.4103.106

**Comment by abchatra** [comment]
Main use case of multi editor is radio programs. We don't have bandwidth to address this.
