### ISSUE TITLE
mobile monaco view broken in RTL

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#3294]
**Describe the bug**

The monaco toolbox doesn't follow the rtl switch, so it's on the left side; this makes it overlay on top of the sim view when on mobile / tablet. Only occurs in monaco / blocks view is correct.

**To Reproduce**
1. Open microbit with a small / phone size window
2. switch to arabic (or any RTL language)
3. open editor, switch to javascript

e.g. in this case the toolbox overlays on top of the control buttons
![rlt-mobile-monaco-view](https://user-images.githubusercontent.com/5615930/85605041-b3c03a80-b606-11ea-9abc-59a3b9775115.gif)

**Expected behavior**

Ideally the monaco toolbox would properly swap to the right side of the screen, and the monaco editor should also follow rtl; if that's nontrivial / a lot of work I can probably add another special case to the mobile sim to reposition it only on monaco / rtl

**Desktop (please complete the following information):**
 - OS: windows
 - Browser electron / chrome

**Comment by abchatra** [comment]
Won't fix.
