### ISSUE TITLE
Formating issues with workspace and block comments 

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3297]
**Describe the bug**
When sharing a project that contains multiple comments, the project at the shared URL does not render the comments as intended.

Selecting `format code` from the contextual menu, goes some way to improve this, but block comments do not seem to be aware of workspace comments, so you get inconsistencies and overlappping comments

**To Reproduce**
1. Create program eg this example ![2A36DE79-AD29-4347-84BC-8794AB03DFCE](https://user-images.githubusercontent.com/31242877/85739126-72a85300-b6f8-11ea-9a37-f84b53a35968.jpg)
2. Share URL for the project and open in browser eg https://makecode.microbit.org/_H96cPM8bRPyW
3. See issues.
![image](https://user-images.githubusercontent.com/31242877/85739525-c87cfb00-b6f8-11ea-9dc6-244144476146.png)
4. Click `format code` and get 
![Screenshot2020_06_25_150158](https://user-images.githubusercontent.com/31242877/85739570-d16dcc80-b6f8-11ea-9eef-ef1d3a8b474f.jpg)

**Expected behavior**
Comments should appear consistent with original project

**Desktop (please complete the following information):**
Mac, Firefox, Chrome

**Comment by microbit-mark** [comment]
This would be a good one to try and fix for next release. What do y9ou think @abchatra ?

**Comment by abchatra** [comment]
This would be summer release as the code is pretty involved.

**Comment by abchatra** [comment]
This is fixed by @riknoll and in /beta. Please test.
