### ISSUE TITLE
GitHub repo based project can't be saved to a hex file

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#3299]
**Describe the bug**
When a project is saved to or loaded from a GitHub repo, the Save button is hidden.

In Chrome on Windows with WebUSB there doesn't seem to be a way to save a hex file, without un-pairing and using the "Download" button to save.

The iOS app receives Download and Save as different messages, so saving seems to be impossible.

**To Reproduce**
1. Go to 'https://makecode.microbit.org/'
2. Create a new project
3. Save to GitHub

**Expected behavior**
The Save button could remain. Is there another way to Save?

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPad
 - Browser [e.g. stock browser, safari] iOS app WKWebKit

**Comment by abchatra** [comment]
We have design to put save under ...

**Comment by pelikhan** [comment]
Related to https://github.com/microsoft/pxt-microbit/issues/3734

**Comment by martinwork** [comment]
I just tested https://makecode.microbit.org/app/981a204b8eab269ab2f58bc2993534add19e6162-440b8f8359, mentioned in https://github.com/microsoft/pxt/pull/8181.

On Windows, save is on the three dots menu, but the three dots section of the Download button is not visible in iOS Safari or the micro:bit app.

So there still doesn't seem to be a way to save a local hex for a project that is github based.

The Download button icon has changed to a file, implying save-to-file. In the micro:bit app at least, this button has always been used to Download to micro:bit.

**Comment by riknoll** [comment]
Fixed by https://github.com/microsoft/pxt/pull/8194

**Comment by martinwork** [comment]
@riknoll @abchatra I can't reopen this issue, but I'm not convinced that the three dots menu is a sensible fix for this issue on iOS.

On iOS the three dots menu has a single action: "Download as file". In normal usage, this duplicates the action of the save button, so the three dots is just an extra pointless button. When the current project is linked to github, this is a workaround for the disappearance of the save button, but it feels to me that it would be simpler if the save button didn't disappear.

**Comment by abchatra** [comment]
Github integration is advanced scenario and the code is already backed up in the github. So downloading a hex file is not a primary scenario and hence we are ok with this change. There is always a compramise between number of UI elements we can show and the simplicity of the work flow.

**Comment by martinwork** [comment]
In the non-github case, the three dots is an extra button showing without providing additional functionality. In the github case, the same number of buttons is showing, but the single tap save button is replaced by a double step three dots menu.

**Comment by abchatra** [comment]
Good point @martinwork. Let me circle back with our designer. Although it might be good for consistency,

**Comment by martinwork** [comment]
Thanks @abchatra. I didn't see it until it was right in front of me, so I was making some screenshots...

In my mind, the Help menu entry doesn't count as extra functionality for the iOS app, because it's not needed. In the iOS app the situation is simple: Download sends to micro:bit; Save stores a file. These are not multi-stage processes that sometimes work in different ways, as on desktop. And the linked help, which would launch out of the app in Safari, doesn't mention iOS.

In iOS Safari, Download and Save do have varying behaviour, dependent on the Desktop/Mobile site configuration, that possibly could be explained in help.


No github:



![image](https://user-images.githubusercontent.com/989126/120031133-4c69f200-bff0-11eb-9b9c-60d394439bad.png)




Github



![image](https://user-images.githubusercontent.com/989126/120031315-918e2400-bff0-11eb-82ff-24c03eee8f34.png)
