### ISSUE TITLE
Snapshot downloads as 0kb for large projects

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3302]
> micro:bit support #38322

**Describe the bug**
When downloading a snapshot of a project with lots of blocks, this results in a 0kb file being produced. Collapsing the blocks results in an image being produced

**To Reproduce**
See image. Console only outputs   screenshot size 3601090b, shrinking to 5628x6808 when blocks are collapsed

**Expected behavior**
snapshot of collapsed or expanded blocks works

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

![image](https://user-images.githubusercontent.com/31242877/85845307-f23b2e00-b79b-11ea-9317-097fadae716f.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Chrome
 - Version 83

**Additional context**

**Comment by microbit-mark** [comment]
Attaching hex from use that triggers the issue [Microbit-Quiz-Homework.hex.zip](https://github.com/microsoft/pxt-microbit/files/4896847/Microbit-Quiz-Homework.hex.zip)

**Comment by microbit-mark** [comment]
This is still reproducing for users. Is there a size/program limit for the snapshot?

**Comment by RRWagner** [comment]
Collapsing functions does not change the result, nor then putting the resulting blocks as close together as possible. That is to say, it doesn't seem to be the x-y dimensions of the workspace so much as the total number of blocks, even if they're not visible.
