### ISSUE TITLE
Wrong block order since v3

### ISSUE THREAD

**Issue by FranklinWhale** [microsoft/pxt-microbit#3303]
**Describe the bug**
Since v3, custom blocks no longer appear in the intended order.

**To Reproduce**
1. Go to https://makecode.microbit.org/v2#editor
2. Switch to JavaScript
3. In Explorer, click "Add custom block"
4. In custom.ts, replace all contents with the contents below:
```ts
//% color="#AA278D" weight=100
namespace hello {
    //% block
    export function helloWorld() {

    }

    // note that Caml casing yields lower case
    // block text with spaces

    //% block
    export function camlCaseTwo() {

    }
}
```
5. Switch to Blocks
6. Go to https://makecode.microbit.org/#editor
7. Repeat Step 2 to 5

**Expected behavior**
The behavior in v2 is preserved in v3.

**Actual behavior**
v2:
![image](https://user-images.githubusercontent.com/8416067/85987559-566e2400-ba20-11ea-9628-024331acbdb2.png)

v3:
![image](https://user-images.githubusercontent.com/8416067/85987372-2292fe80-ba20-11ea-8881-8506db1b4af7.png)

**Comment by abchatra** [comment]
No bandwidth to fix.
