### ISSUE TITLE
OnReceivedBuffer() is now deprecated, but where is the new one?

### ISSUE THREAD

**Issue by CleoQc** [microsoft/pxt-microbit#3306]
**Describe the bug**
Gigglebot pre-made radio blocks are not working with the June release of makecode, due to OnReceivedBuffer() being different/gone ? 
**To Reproduce**
See this ticket: https://github.com/DexterInd/pxt-giggle/issues/21

This is the code that worked for a year, until the new release:
https://github.com/DexterInd/pxt-giggle/blob/master/giggle.ts#L203

I'm looking at the new pxt-microbit code, and I can't find radio.onReceivedBuffer() anymore. Only the deprecated version which tells me to use the non-deprecated one. But it's well hidden from me.

To take this outside the context of GiggleBot and extension, the code in this documentation no longer works. Yet the documentation is still up.
https://github.com/microsoft/pxt-microbit/blob/master/docs/reference/radio/on-received-buffer.md

**Additional context**
Similar thing happened last year:
See previous tickets: https://github.com/microsoft/pxt-microbit/issues/2472
and https://github.com/microsoft/pxt-microbit/issues/2222

**Comment by abchatra** [comment]
@pelikhan can you take a look. I believe you fixed this in the past.

**Comment by pelikhan** [comment]
This seems to work. You do need to handle the buffer passed as an argument in the function.

https://makecode.microbit.org/_gepLf2YPb2EK

```
radio.setGroup(1)

forever(function() {
    led.toggle(0, 0)
    const buf = pins.createBuffer(4)
    buf.setNumber(NumberFormat.Int32LE, 0, control.millis())
    radio.sendBuffer(buf)
})

radio.onReceivedBuffer(function (receivedBuffer: Buffer) {
    led.toggle(4, 4)
    console.log(receivedBuffer.toHex())    
})
```

**Comment by CleoQc** [comment]
It seems my issue is elsewhere and I'll open another issue for it.
However I still haven't found where the new code for onReceivedBuffer is.
