### ISSUE TITLE
Windows app - show LEDs block missing in Japanese translation

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3309]
> micro:bit support: 38382

**Describe the bug**
![image](https://user-images.githubusercontent.com/31242877/86350564-ca940c00-bc5a-11ea-98d1-7214500a8564.png)

**To Reproduce**
1. In Japanese language, open flashing heart tutorial
2. Open basic blocks from menu, show LEDs block is missing

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abchatra** [comment]
@jwunderl this is again a translation issue. I can reproduce this in the live website as well.

**Comment by jwunderl** [comment]
Fixed translation (https://crowdin.com/translate/kindscript/990/en-ja#286150); we'll probably want to do a small patch for the offline app to pick up this translation fix + czech toolbox fix + maybe the get volume help docs

**Comment by abchatra** [comment]
Go ahead and port to stable
