### ISSUE TITLE
how to solve 403

### ISSUE THREAD

**Issue by hardcao** [microsoft/pxt-microbit#3312]
pxtapp.js:1 GET http://makecode.zszc-xsm.com:3232/api/clientconfig 403 (Forbidden)
(anonymous) @ pxtapp.js:1
a._execute @ main.js:1
S._resolveFromExecutor @ main.js:1
S @ main.js:1
v.Util.httpRequestCoreAsync @ pxtapp.js:1
c @ pxtapp.js:1
d @ pxtapp.js:1
r.privateGetAsync @ pxtapp.js:1
(anonymous) @ pxtapp.js:1
(anonymous) @ pxtapp.js:1
s @ main.js:1
S._settlePromiseFromHandler @ main.js:1
S._settlePromise @ main.js:1
S._settlePromiseCtx @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
r @ main.js:1
a.hasDevTools.s.invoke @ main.js:1
S._then @ main.js:1
S.then @ main.js:1
u @ pxtapp.js:1
(anonymous) @ pxtapp.js:1
s @ main.js:1
S._settlePromiseFromHandler @ main.js:1
S._settlePromise @ main.js:1
S._settlePromise0 @ main.js:1
S._settlePromises @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
r @ main.js:1
a.hasDevTools.s.settlePromises @ main.js:1
S._fulfill @ main.js:1
S._resolveCallback @ main.js:1
S._settlePromiseFromHandler @ main.js:1
S._settlePromise @ main.js:1
S._settlePromise0 @ main.js:1
S._settlePromises @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
r @ main.js:1
a.hasDevTools.s.settlePromises @ main.js:1
S._reject @ main.js:1
S._settlePromise @ main.js:1
S._settlePromise0 @ main.js:1
S._settlePromises @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
r @ main.js:1
a.hasDevTools.s.settlePromises @ main.js:1
S._reject @ main.js:1
S._rejectCallback @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
c @ main.js:1
l.objectStore.get.onsuccess @ main.js:1
IndexedDB (async)
p._get @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
a._execute @ main.js:1
S._resolveFromExecutor @ main.js:1
S @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
s @ main.js:1
S._settlePromiseFromHandler @ main.js:1
S._settlePromise @ main.js:1
S._settlePromiseCtx @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
r @ main.js:1
a.hasDevTools.s.invoke @ main.js:1
S._then @ main.js:1
S.then @ main.js:1
e.getAsync @ main.js:1
e.cacheGetAsync @ main.js:1
a.getHexInfoAsync @ pxtapp.js:1
e.getHexInfoAsync @ main.js:1
(anonymous) @ pxtapp.js:1
(anonymous) @ pxtapp.js:1
(anonymous) @ pxtapp.js:1
(anonymous) @ pxtapp.js:1
a._execute @ main.js:1
S._resolveFromExecutor @ main.js:1
S @ main.js:1
__awaiter @ pxtapp.js:1
n @ pxtapp.js:1
(anonymous) @ pxtapp.js:1
(anonymous) @ pxtapp.js:1
(anonymous) @ pxtapp.js:1
r @ pxtapp.js:1
s @ main.js:1
S._settlePromiseFromHandler @ main.js:1
S._settlePromise @ main.js:1
S._settlePromiseCtx @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
r @ main.js:1
a.hasDevTools.s.invoke @ main.js:1
S._then @ main.js:1
S.then @ main.js:1
o @ pxtapp.js:1
(anonymous) @ pxtapp.js:1
a._execute @ main.js:1
S._resolveFromExecutor @ main.js:1
S @ main.js:1
__awaiter @ pxtapp.js:1
e.getCompileOptionsAsync @ pxtapp.js:1
n.compileAsync @ main.js:1
U.compile @ main.js:1
(anonymous) @ main.js:1
s @ main.js:1
S._settlePromiseFromHandler @ main.js:1
S._settlePromise @ main.js:1
S._settlePromise0 @ main.js:1
S._settlePromises @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
r @ main.js:1
a.hasDevTools.s.settlePromises @ main.js:1
S._fulfill @ main.js:1
S._resolveCallback @ main.js:1
S._settlePromiseFromHandler @ main.js:1
S._settlePromise @ main.js:1
S._settlePromise0 @ main.js:1
S._settlePromises @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
r @ main.js:1
a.hasDevTools.s.settlePromises @ main.js:1
S._fulfill @ main.js:1
S._resolveCallback @ main.js:1
S._settlePromiseFromHandler @ main.js:1
S._settlePromise @ main.js:1
S._settlePromise0 @ main.js:1
S._settlePromises @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
r @ main.js:1
a.hasDevTools.s.settlePromises @ main.js:1
S._fulfill @ main.js:1
S._resolveCallback @ main.js:1
S._settlePromiseFromHandler @ main.js:1
S._settlePromise @ main.js:1
S._settlePromiseCtx @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
r @ main.js:1
a.hasDevTools.s.invoke @ main.js:1
S._then @ main.js:1
S.then @ main.js:1
e.setContentAsync @ main.js:1
U.saveVirtualFileAsync @ main.js:1
(anonymous) @ main.js:1
s @ main.js:1
S._settlePromiseFromHandler @ main.js:1
S._settlePromise @ main.js:1
S._settlePromise0 @ main.js:1
S._settlePromises @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
r @ main.js:1
a.hasDevTools.s.settlePromises @ main.js:1
S._fulfill @ main.js:1
S._resolveCallback @ main.js:1
S._settlePromiseFromHandler @ main.js:1
S._settlePromise @ main.js:1
S._settlePromise0 @ main.js:1
S._settlePromises @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
r @ main.js:1
a.hasDevTools.s.settlePromises @ main.js:1
S._fulfill @ main.js:1
S._resolveCallback @ main.js:1
S._settlePromiseFromHandler @ main.js:1
S._settlePromise @ main.js:1
S._settlePromise0 @ main.js:1
S._settlePromises @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
r @ main.js:1
a.hasDevTools.s.settlePromises @ main.js:1
S._fulfill @ main.js:1
S._resolveCallback @ main.js:1
(anonymous) @ main.js:1
s @ main.js:1
S._settlePromiseFromHandler @ main.js:1
S._settlePromise @ main.js:1
S._settlePromise0 @ main.js:1
S._settlePromises @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
r @ main.js:1
a.hasDevTools.s.settlePromises @ main.js:1
S._fulfill @ main.js:1
S._resolveCallback @ main.js:1
S._settlePromiseFromHandler @ main.js:1
S._settlePromise @ main.js:1
S._settlePromise0 @ main.js:1
S._settlePromises @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
r @ main.js:1
a.hasDevTools.s.settlePromises @ main.js:1
S._fulfill @ main.js:1
S._resolveCallback @ main.js:1
(anonymous) @ main.js:1
a.<computed> @ pxtapp.js:1
recvHandler @ pxtapp.js:1
t.onmessage @ pxtapp.js:1
pxtapp.js:1

**Comment by abchatra** [comment]
This site is not owned by Microsoft or this repo.
