### ISSUE TITLE
Translations of extension does not follow language selection

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3314]
> micro:bit support: 38265

1. Switch to Hebrew
2. Add Hummingbird extension which aslo contains translated text
3.Add some blocks to the program
4. Switch to English
4. Blocks contain Hebrew translations still

![image](https://user-images.githubusercontent.com/31242877/87040735-0eea5380-c1e9-11ea-8f98-4d64a443ac53.png)

Also an issue where values to not follow either
![image](https://user-images.githubusercontent.com/31242877/87041031-815b3380-c1e9-11ea-90b9-4a847d177329.png)

**Comment by abchatra** [comment]
@microbit-mark I can't reproduce this issue. Can you?

**Comment by microbit-mark** [comment]
Yes, reproduces in Firefox 78 and Chrome 84 MacOS 10.15.6. Duplicate of https://github.com/microsoft/pxt-microbit/issues/3265 ?

**Comment by microbit-mark** [comment]
have tested with @abchatra and this no longer reproduces, so closing
