### ISSUE TITLE
Allow Bluetooth event, DFU and device information services to be excluded from project

### ISSUE THREAD

**Issue by smartyw** [microsoft/pxt-microbit#3316]
There is very little memory available these days if you're using Bluetooth. There never was, but things got worse when there were some changes made to the DAL last year and now, projects which used to work, result in error 0x02, Out Of Memory.

One way to help with this is to allow the three Bluetooth services which are always included by default, to be selectively excluded. The services in question are the DFU service, the Device Information Service and the Event Service. Someone using USB to update their micro:bit has no use for the DFU service. The event service does not need to be included unless you have a good reason to need it. And the device information service was always optional anyway, so I don't know why MakeCode always includes it.

It is/was possible to exclude these services from a C++ project in config.json (project settings) like this:

```
"bluetooth": {
            "enabled": 1,
            "open": 1,
            "dfu_service": 0,
            "event_service": 0,
            "device_info_service": 0
        },
```

Hope you can do this.

Thanks

**Comment by smartyw** [comment]
As an example, consider this code:

https://github.com/bittysoftware/bitty_data_logger_device_code/tree/master/microbit/makecode/CO2_monitoring

It allows the microbit to be used with a CO2 sensor as shown here: https://youtu.be/1Wz1_5ox3KM 

This was originally built against an older DAL and worked fine. I just recompiled with MakeCode and now get out of memory errors at runtime. I have removed some non-essential but useful functionality and have it working again but.... Memory is being used by the event service, DFU service and device information service, the code for which is automatically included in the hex file and I do not need any of these three services. Including them by default is fine, but please allow them to be selectively excluded from the build.

**Comment by abchatra** [comment]
This is a enhancement request for https://github.com/lancaster-university/codal-microbit-v2 
Please open the issue there.
