### ISSUE TITLE
getting error 050 for puzzling reasons

### ISSUE THREAD

**Issue by CleoQc** [microsoft/pxt-microbit#3317]
**Describe the bug**
I'm getting a 050 error on code that used to work before the June update, but only on some microbits, and only after doing a reset.

**To Reproduce**
I have 2 microbits, both on firmware 0253. One works just fine all the time, not the other. Both are hardware V1.5. Only difference I can see is the one that works has Bootloader Version: 0246, and the one with the issue as Bootloader Version: 0243. Everything else seems identical.

Also, the bug is related to the presence of the gigglebot library, even if I don't use blocks from that library.

Here's the code I load up:
```
let powerRight = 0
let powerLeft = 0
radio.setGroup(1)
basic.showIcon(IconNames.SmallHeart)
basic.forever(function () {
    powerLeft = 10
    powerRight = 10
    powerLeft = Math.idiv(powerLeft * -1 * input.acceleration(Dimension.Y), 512) + Math.idiv(50 * input.acceleration(Dimension.X), 512)
    powerRight = Math.idiv(powerRight * -1 * input.acceleration(Dimension.Y), 512) - Math.idiv(50 * input.acceleration(Dimension.X), 512)
    // limit those values from -100 to 100
    powerLeft = Math.min(Math.max(powerLeft, -100), 100)
    powerRight = Math.min(Math.max(powerRight, -100), 100)
    const buf = control.createBuffer(8);
buf.setNumber(NumberFormat.Float32BE, 0, powerLeft);
buf.setNumber(NumberFormat.Float32BE, 4, powerRight);
radio.sendBuffer(buf)
})
```

- Make sure the _gigglebot_ library is loaded. Either one of them (_gigglebot_, or _giggle_, although _gigglebot_ loads a smaller piece of code and generates the error on its own) 

- I transfer via bluetooth ( I don't expect this is related, but I'm being thorough).

- The code transfers just fine and I get my icon on the led grid. 

- I press the reset button, I get the icon followed immediately with the 050 error code on the microbit that gives me issues, not on the other one.

- I remove the library and transfer the code again, and both microbits work just fine even through many resets.

**Expected behavior**
There shouldn't be a 050 error code at all. This code has been working since we launched the Gigglebot.

**Additional context**
Problem was reported by a user. I had tested before the June release and it was fine. I guess I tested with a working microbit and not with every single microbit I own.

I would appreciate pointers into what might be going wrong.

**Comment by abchatra** [comment]
Error code here: https://support.microbit.org/support/solutions/folders/19000163393
This looks like an issue with the microbit hardware. Contact microbit support

**Comment by CleoQc** [comment]
It was also reported by a user, so it would be two microbits that are defective? I can go through all my microbits. I just picked one at random and it had the issue. The second one which I just received in the mail didn't have it.

**Comment by abchatra** [comment]
This is a hardware error. Microbit support should help you. Are you doing anything in the library w.r.t to accelerometer?

**Comment by CleoQc** [comment]
Last year, I had the same error code, and it was due to the radio having changed protocols, not the hardware. 

with extension, but no blocks from the extension, the lines where I read the accelerometer fails.
without the extension, the exact same code works just fine.

**Comment by CleoQc** [comment]
Issue that was filed with us: https://github.com/DexterInd/pxt-giggle/issues/21
_I find it unlikely to be a hardware issue as suggested by https://support.microbit.org/support/solutions/articles/19000097285-050 as other accelerometer usage not using this package works as expected_

again, just loading the extension, and not actually using it leads to this issue. This is new behaviour.

**Comment by CleoQc** [comment]
> Are you doing anything in the library w.r.t to accelerometer?

In pxt-giggle, we do. But in pxt-gigglebot we don't read the accelerometer at all. Yet both lead to the same issue. I'm really puzzled by this, and would appreciate any hints

**Comment by abchatra** [comment]
@pelikhan  @mmoskal any clue here?

**Comment by rhubarbdog** [comment]
hi
i thought i'd broke a microbit with error 050 because of the following reason.
i thought i'd write an improved version of the micropython `i2c,scan()` which produces a tuple (list) of all i2c device addresses linked to the microbit.
The issue i was trying to over come is the AM3220 (AoSong Temperature and humidity detector) sits in a low power wait mode to avoid the circuits warming up which would effect both the readings but especially the humidity.  but when you issue an `i2c.scan()` to detect it it doesn't respond so one can erroneously believe it is't connected correctly or is faulty.
you wake the device up with the following `pins.i2cWriteNumber(30,0,NumberFormat.Int8LE,false)` writing any junk is suffuicient, one then waits for 2 ms before writing the command for it to report the temperature and humidity as a 4? byte string.
what i was doing in a loop was
```
i2c,write(\x30,0)
sleep(2)
data=i2scan()
print(data)
# display.scroll(str(data))
```
sorry for using micropython, but not all blocks are available in makecode. `print(data)` is the same as `serial.writeNumbers([0, 1])`

the continual hitting of the accelerometer with `i2c.scan()` or the `i2c.write()` to it caused a 050 error

does the inclusion of blocks to a project automatically add code to the compiled version?  (the .HEX file)

@CleoQc is it possible to configure your robot's not to use pins 19 and 20 for their i2c comms with a block equivalent to micropython's `i2c.init(sda=pin1, sdc=pin2)` ?

**Comment by CleoQc** [comment]
@rhubarbdog I canm't reconfigure the robot but I'm now wondering if maybe there's a new timing issue? I'm off to test that theory.

**Comment by CleoQc** [comment]
Revisiting this to pare it down even more.

This is the code I'm now running:
```
basic.forever(function () {
    serial.writeNumbers([input.acceleration(Dimension.Y), input.acceleration(Dimension.X)])
})
basic.forever(function () {
    basic.showIcon(IconNames.Heart)
    basic.showIcon(IconNames.SmallHeart)
})
```
You can remove the beating heart, it was just to give me some visual cue.

As is, it works fine. I get data from the device:
![image](https://user-images.githubusercontent.com/4965628/88432366-135a6300-cdca-11ea-8ba9-5fc57a83eeff.png)

If I load the Gigglebot library https://github.com/dexterind/pxt-gigglebot/  (last released in Oct 2019) then the above code no longer works.  On the first download, all -seems-  fine but the console reads all 0s.
If I press the reset button, I then get the 050 error. 

This is linked to something in the Gigglebot library that got broken with the June makecode update.

**Comment by microbit-mark** [comment]
I have tested this against a 1.3b and 1.5 board, both using DAPLink v0249 in makecode.microbit.org and makecode.microbit.org/v2 and using the code in https://github.com/microsoft/pxt-microbit/issues/3317#issuecomment-663721162

On the 1.5 board, the error reproduces in both versions of MakeCode
On a 1.3b board, the error does not reproduce in either version of MakeCode

Removing the Gigglebot extension fixes the issue in both versions of Makecode. Could there be an i2c address conflict with the Gigglebot and the motion sensor? Addresses are here https://tech.microbit.org/hardware/i2c/

**Comment by martinwork** [comment]
I can't make it go wrong with v1.3 micro:bits.

@CleoQc What happens if you remove the initial call to Stop() from the extension?

Or insert a pause before calling Stop()?

**Comment by CleoQc** [comment]
Thanks for looking into this!
The gigglebot I2C address is 0x04, as far as I can see there are no conflicts.


@martinwork : 
I tried removing the call to stop() already, with no changes in behaviour. I didn't try with a pause, but since removing it didn't fix the issue, I doubt the pause would make a difference. 

See https://github.com/CleoQc/pxt_test
Project is here: https://makecode.microbit.org/_DmfJU9e5o87P

**Comment by carlosperate** [comment]
> The gigglebot I2C address is 0x04, as far as I can see there are no conflicts.

That address is reserved for I2C High Speed mode, could that be causing issues?
https://www.i2c-bus.org/addressing/

**Comment by CleoQc** [comment]
further investigation is showing that it is related to the address.  But I still don't see why.
I've removed the call to stop() from the init part of the code. At this point there should be no I2C calls done at all. And it still fails?  
I'm getting the logic analyzer out.

**Comment by martinwork** [comment]
I'm finding it's not causing a panic with the main repo, where the stop has been removed, but it is with the fork I made yesterday which still has the stop. Could it have been that when you tried removing stop before, you didn't get a recompiled version with the modified ts?

**Comment by CleoQc** [comment]
I'm still having a panic with the main repo though, I *just* tested it and it still fails for me.

**Comment by CleoQc** [comment]
oh my goodness I found it... 
of all places, it's in the way we handled neopixels. Shoot me now...

Thanks for digging into this.  We will look into changing the address of the robot. It seems something changed with version 1.5 and 0x04 can no longer be used properly.

**Comment by carlosperate** [comment]
Glad you found the issue @CleoQc !
Do you have a bit more info how the handling of neopixels is causing the issue?
Error 050 should only be raised when the DAL fails to communicate with the on board motion sensors, it'd be good to understand the issue in case it pops up again.

**Comment by CleoQc** [comment]
@carlosperate :
There was no issue with the neopixels. But in our code we poll the battery level in order to change the colour of a couple of neopixels to indicate low voltage. 
However in the case of the remote controller, there is no battery to be polled as the microbit is not inserted in the robot. 

I'd love to know why the microbit changed behaviour. V1.3b used to be forgiving of this, V1.5 just crashes.

**Comment by carlosperate** [comment]
Thanks for the clarification.
How do you poll the battery? The only reason the 050 error should appear is if there was an issue with the I2C comms on the micro:bit board, and I guess i am struggling to see the relation?

**Comment by CleoQc** [comment]
@carlosperate 
These are the lines I ended up removing (on top of the call to stop() )
https://github.com/DexterInd/pxt-giggle/blob/master/giggle.ts#L53-L56

And this is where the I2C calls are made:
https://github.com/DexterInd/pxt-gigglebot/blob/dde63f9d6bce6413d3d8555b89beb028ce14e3fc/gigglebot.ts#L1019

I think the issue is that the code is called when a gigglebot is NOT connected (as it's a remote control microbit). The I2C calls were failing nicely on a V1.3b, but not with a V1.5
I have no idea what changed inside the microbit for this to no longer work, but I would like to know, if you can spare a moment

**Comment by carlosperate** [comment]
The LSM303AGR, which is the new motion sensor on the micro:bit v1.5, is high-speed compatible, so it's quite possible that I2C messages to address 0x4 can misconfigure the sensor and leave it in an unknown state. If that happens, within 6ms (on the DAL ticker) the nrf51 will try to get a sample from the accelerometer, and if that transfer fails it will throw the 050 error.

**Comment by CleoQc** [comment]
I tested the address change a couple of days ago  and the error was not reproduced. So it does seem that it leaves the  LSM303AGR in an unknown state. 
Thanks for looking into it
