### ISSUE TITLE
Stuck on micro:bit face when loading in an Android Web View

### ISSUE THREAD

**Issue by microbit-sam** [microsoft/pxt-microbit#3318]
**Describe the bug**

MakeCode gets stuck on the micro:bit face when opening in an Android Web View
This only happens with makecode.microbit.org(/v3), and MakeCode will load and work correctly if the /v2 url is used

Console error is:

```
Browser: chrome 83.0.4103.106 on rpi
main.js:1 Uncaught TypeError: Cannot read property 'compile' of null
    at HTMLDocument.<anonymous> (main.js:1)
```

**To Reproduce**
- Download micro:bit Android beta (I can give you access to this if you send me your email)
- Tap 'Create Code'
- MakeCode doesn't finish loading

**Expected behavior**
- If you press and hold the micro:bit face on the home view, you can change the MakeCode URL that the app uses
- Setting it to makecode.microbit.org/v2 will allow MakeCode to start and function as expected

**Screenshots**
![Screenshot 2020-07-14 at 08 47 08](https://user-images.githubusercontent.com/32453267/87399021-a7e4ea00-c5ae-11ea-8cae-4b8e454da3f3.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Moto G7 (Detected by Chrome as RPi)
 - OS: Android
 - Browser WebView
 - Version 83.0.4103.106

**Additional context**

**Comment by jaustin** [comment]
@microbit-sam could you please share instructions on this ticket for @abchatra to reproduce with the debugger connected? Can he use any tools to demo this bug that aren't the app? Or does he need to connect Android dev tools to the beta app?

**Comment by microbit-sam** [comment]
The only method I know of is connecting the tools to the app 

I don't think you need Android Studio to do this, just a debug build of the Android app installed on a device, and then connect using the Chrome Remote Debugger
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews

**Comment by microbit-sam** [comment]
I've just tested this using the Android emulator in Android Studio and I get the same result.

It's possible to use the Chrome remote debugging tools with the emulator, so if that's a better option than finding an Android device to use you should be able to test it out without hardware

https://developer.android.com/studio/run/emulator

**Comment by abchatra** [comment]
Where is this app to download?

**Comment by microbit-mark** [comment]
@abchatra @riknoll It's this one https://play.google.com/store/apps/details?id=com.samsung.microbit&hl=en_US, but to test the beta we need to add a Google ID to our testers list. Let me know if you have one.

I have also forwarded you the APK via email, which yo can sideload to a device if you prefer.

**Comment by microbit-sam** [comment]
Note: the APK defaults to `makecode.microbit.org/v2`, to change the URL long press the micro:bit face on the home page

**Comment by riknoll** [comment]
Seems like the webview does not have DOM storage enabled. MakeCode assumes that localstorage exists, so it's crashing when trying to read/write settings. It was throwing exceptions in the v2 URL too, they were just being ignored (and probably causing some subtle bugs).

You can enable it using this API:

https://developer.android.com/reference/android/webkit/WebSettings#setDomStorageEnabled(boolean)

If that's not possible, I can look at fixing this on the MakeCode side but it seems like this should be an app fix.

**Comment by abchatra** [comment]
@microbit-sam Please enable dom storage in the app. There is no action required from MakeCode end. Closing as bug understood.
