### ISSUE TITLE
The need for a 'fast as possible' block?

### ISSUE THREAD

**Issue by rhubarbdog** [microsoft/pxt-microbit#3319]
**Is your feature request related to a problem? Please describe.**
In makecode blocks there was the addition of a short mandatory pause in loops in blocks. i believe  this was added so makecode could service background and asyncronous events like `input.onButtonPressed(Button.A, function () {}` .
using makecode i'm trying to demonstrate why the microbit thermometer `input.temperature()`  isn't what you want when making a weather station.  as the temperature `input.teperature()` is effected by the microprocessors temperature. the problem is because `input.temperature()` is an integer and this little asynchronous facilitating sleep prevents this effect from being demonstrated.

**Describe the solution you'd like**
The addition of a `control.asFastAsPossible` block which could bracket loops indicating to the compiler (pre-processor) not to insert little sleeps to facilitate asynchronous events

**Describe alternatives you've considered**
Learning to program a microbit in C to give me total control,  But describing C code to students may be a bit of a quantum leap in thinking

**Comment by abchatra** [comment]
No plans to address this issue. Please feel free to write an extension for the new API.
