### ISSUE TITLE
Chrome update disables HEX file download by default

### ISSUE THREAD

**Issue by microbit-giles** [microsoft/pxt-microbit#3321]
> micro:bit support 38678

**Describe the bug**
Google just updated Chrome so it blocks downloading HEX files unless you turn off security protection. Not a MakeCode bug but this will impact a lot of MakeCode users.

**To Reproduce**
1. Update Chrome
2. Go to https://makecode.microbit.org/
3. Download a .HEX file
4. See error 'may be dangerous so Chrome has blocked it'

**Expected behavior**
It should allow downloading of .HEX files by default

**Screenshots**
![image](https://user-images.githubusercontent.com/42380137/87807359-12688500-c850-11ea-8e33-a1bf88d2c678.png)

**Desktop (please complete the following information):**
 - OS: MAcOS
 - Browser Chrome
 - Version  83.0.4103.116 (Official Build) (64-bit)

**Additional context**
Same happens when trying to download .HEX files from any other website, e.g. microbit.org

To allow downloads of HEX files I had to switch from 'standard protection' to 'no protection' in Chrome security settings.

**Comment by microbit-carlos** [comment]
Related Chrome blog post: https://blog.chromium.org/2020/02/protecting-users-from-insecure.html

**Comment by microbit-mark** [comment]
@abchatra @pelikhan Can you take a look at this one? Seems like a high priority fix.

**Comment by microbit-mark** [comment]
opening chrome://downloads lets you 'keep dangerous file'

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/31242877/87814274-53b26200-c85b-11ea-8e64-b0ca7394219b.png">

**Comment by riknoll** [comment]
huh, I can't repro this at all. Tried on my mac and windows laptop with chrome and chrome canary (after updating to latest version)

**Comment by microbit-carlos** [comment]
Do you have the "Safe browsing" settings at "standard" (default) or "enhanced"?

**Comment by riknoll** [comment]
I tried with both standard and enhanced

**Comment by microbit-carlos** [comment]
Technically this was deployed with v84 of chrome, which (based on wikipedia) came out on the 14th. We only really noticed sometime today, and at least 4 different people in Foundation can replicate this, but we are all in the same region. I wonder if this is a Google controlled flag that is being deployed progressively.

**Comment by riknoll** [comment]
Could be. For the record, here is my chrome version:

Version 84.0.4147.89 (Official Build) (64-bit)

Let me double check on my windows machine

**Comment by riknoll** [comment]
hmmmm... no dice there either (and same chrome version). Let me ping the rest of the team and see if anyone can repro it.

**Comment by abchatra** [comment]
It got magically fixed now. I was able to reproduce this morning.

**Comment by microbit-mark** [comment]
Doesn't repro for me anymore either  in 84.0.4147.89, so I think it is fixed.
