### ISSUE TITLE
Makecode Extensions not found under Mac OS 10.15.6 Catalina using Safari

### ISSUE THREAD

**Issue by 4tronix** [microsoft/pxt-microbit#3324]
**Describe the bug**
The 4tronix ServoBit extension cannot be found when using MacOS Catalina. It works fine under Windows and even with MacOS 10.11.6 El Capitan

**To Reproduce**
Using Safari, open the Makecode website and start a new project. In Extensions, serch for "servobit" or "4tronix". The extension will not be found. The URL https://github.com/4tronix/ServoBit can be entered directly, but then gives the error "not approved by Microsoft"

**Expected behavior**
Extension should be found

**Screenshots**
None - this is a customer issue. We do not have the relevant OS 

**Desktop (please complete the following information):**
 - Mac OS 10.15.6 Catalina
 - Safari

**Additional context**
Customer complaining tht extension doesn't exist

**Comment by microbit-mark** [comment]
This is the search view from Safari on macOS10.15.6, so I don't think this is reproducable

![image](https://user-images.githubusercontent.com/31242877/89293395-c3935b80-d655-11ea-8ed8-5989bbd6233f.png)


![image](https://user-images.githubusercontent.com/31242877/89293284-95ae1700-d655-11ea-9056-395c8e5173ce.png)

**Comment by abchatra** [comment]
This should be fixed now.
