### ISSUE TITLE
Compiler /Editor Error in V3 vs V2 makecode

### ISSUE THREAD

**Issue by DaveAtKitronik** [microsoft/pxt-microbit#3325]
A customer has reported a bug which appears to have been present since the switch from the V2 editor. 
The :MOVE mini buggy instructions have a small code snippet to introduce the Neopixel package:

let headlights: neopixel.Strip = null
input.onButtonPressed(Button.A, () => {
    headlights.range(0, 2).showColor(neopixel.colors(NeoPixelColors.Red))
    headlights.setPixelColor(2, neopixel.colors(NeoPixelColors.Green))
    headlights.range(3, 2).showColor(neopixel.colors(NeoPixelColors.Blue))
})
headlights = neopixel.create(DigitalPin.P0, 5, NeoPixelMode.RGB)

In the V2  editor this produces the expected result of 2 red, 1 green, and 2 blue neopixels on a single press of button This is using Neopixel 0.6.1, with WS2812B dependency at 0.0.4

![image](https://user-images.githubusercontent.com/25896029/88167954-8bc9f400-cc11-11ea-8e6f-9a9e903528b5.png)

The Same code, with the same packages in the current editor: 
![image](https://user-images.githubusercontent.com/25896029/88167896-705ee900-cc11-11ea-858d-519fd4688fe5.png)

fails. On the first push of button 'A' the first 2 pixels light red, but the rest stay off. A second push on 'A' then lights all the pixels. Power cycling the neopixels, whilst maintaining the power to the microbit (via the usb lead) results in the expected operation of all pixels lighting on a single press. 

With Neopixel package 0.7.2 the same behaviour is observed - so I think its related to the editor, or a combo of editor and neopixel, rather than just the neopixel package. From the power cycle test it appears to be an initialisation error.

**To Reproduce**
Use the hex files in the zip. 
[Examples.zip](https://github.com/microsoft/pxt-microbit/files/4959602/Examples.zip)

Windows 10, Edge and Chrome, but not felt to be related to OS/Browser

**Comment by DaveAtKitronik** [comment]
I have seen a similar issue on our Halo HD (and a yet to be released board). On power cycle the LEDs are correctly set to a chosen colour, on reset then they are occasionally set to other colours.

**Comment by DaveAtKitronik** [comment]
Also reported to us from a customer using the :MOVE motor.

**Comment by abchatra** [comment]
@pelikhan

**Comment by abchatra** [comment]
This should be fixed now. If not let us know.
