### ISSUE TITLE
Polish 'text' blocks category 

### ISSUE THREAD

**Issue by microbit-josephine** [microsoft/pxt-microbit#3331]
**Describe the bug**
Polish 'text' blocks category has a bug where all except one of the blocks are not visible.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the makeCode editor
2. Click on Polish in the languages section
3. Select 'Tekst' ('Text') option in the advanced section

**Screenshots**
![Screenshot 2020-07-30 at 12 35 25](https://user-images.githubusercontent.com/54458430/88918319-286b4200-d261-11ea-848d-e4bd25fd1af6.png)

**Desktop (please complete the following information):**
 - OS: MacOS, Windows10
 - Browser: Chrome
 - Version : 84.0.4147.89

**Additional information**
This issue was raised in a support ticket https://support.microbit.org/a/tickets/38810

**Comment by abchatra** [comment]
This is someone messed up the translation.

**Comment by abchatra** [comment]
@jwunderl can you take a look when you have time?

**Comment by jwunderl** [comment]
translation for string.charAt block had swapped the order of the arguments (the string itself and the index) and is using the old % order based params, so the types were wrong. Removed the translation, so the category should be fixed the next time the translations for this get updated

**Comment by jwunderl** [comment]
Category is now fixed (if it still shows up as a broken for you, it might just be a cache issue; it will likely go away if you refresh the page.)
