### ISSUE TITLE
Neopixel extension does not appear in Menu

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3332]
> micro:bit support:  38836

**Describe the bug**
Neopixel extension appears to be added in File Explorer, but does not appear in Toolbox menu

**To Reproduce**
See video https://drive.google.com/file/d/1ie4r1FnOYNk43FP7yz_aiDx484spcmED/view?usp=sharing

**Expected behavior**
Neopixel blocks appear in menu

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac 10.15
 - Browser [e.g. chrome, safari] Chrome, safari, opera

**Additional context**
Tried to recreate in Chrome 84    Mac OS 10.15.6 and I can't reproduce the issue the user is having.

**Comment by abchatra** [comment]
Can you see F12 (dev tools) and see if there are any errors?

**Comment by abchatra** [comment]
Interesting, saw the video, there is no error in the F12

**Comment by philipphenkel** [comment]
This problem also happens with other extensions. I run into that already multiple times this year when using one of the MakerBit extensions. 
I cannot reproduce it consistently and thus I expect it to be a race condition.
As far I as remember, it started when I tested the 2020 Beta earlier this year. So it's most probably v3 related.
I saw it in Chrome, on Mac, definitely 84 and probably some before.

When this happens in a project, it will persist. A reload of the project won't help. The workaround is to create a new project and add the extension again.

**Comment by RRWagner** [comment]
I have even started new projects, and adding an extension shows the extension in the project explorer, but not the blocks category.

https://makecode.microbit.org/_3jmf8gW1We0c

![image](https://user-images.githubusercontent.com/2395551/94902457-094d8400-044d-11eb-9055-ef1e64bc7ec4.png)

![image](https://user-images.githubusercontent.com/2395551/94902486-14a0af80-044d-11eb-990e-5d7dd9efa004.png)

**Comment by philipphenkel** [comment]
@abchatra I ran into this multiple times now. It seem to survive reloads. @RRWagner wasn't even able to work around that by creating new projects. We are both using Chrome and there are no obvious errors in JavaScript console.

The incognito mode (private mode) helps and therefore I believe it is related to caching or local storage.

**Comment by abchatra** [comment]
@philipphenkel Thank you. We are going to investigate next week. If you have any additional information do let us know.

**Comment by RRWagner** [comment]
With these steps you can reproduce it:
1. clear cookies and cache
2. makecode.microbit.org
3. new project named test
4. add makerbit extension with https://github.com/1010Technologies/pxt-makerbit
-> result: blocks show
5. add lcd 1602 with search for lcd 1602 in extensions
-> result: lcd 1602 blocks show
6. home, new project named test2
7. add lcd 1602 with search for lcd 1602 in extensions
-> result: missing blocks, but extension present:

![image](https://user-images.githubusercontent.com/2395551/95411533-8fe5e380-08db-11eb-8168-412d00691049.png)
