### ISSUE TITLE
Project won't load immediately after created with github

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3334]
* create new project
* create repo
* leave editor
* try to reload crash

![image](https://user-images.githubusercontent.com/4175913/89049308-e942fc80-d305-11ea-82f7-57a9670cb8cb.png)
![image](https://user-images.githubusercontent.com/4175913/89049329-f2cc6480-d305-11ea-80f3-24e356637e9d.png)

**Comment by abchatra** [comment]
I can't repro this.
