### ISSUE TITLE
Updating dal.d.ts not possible

### ISSUE THREAD

**Issue by Amerlander** [microsoft/pxt-microbit#3335]
The process of recreating the dal.d.ts seem to require a repo, which is either private or not existing: https://github.com/microbit-foundation/codal

What can I do to recreate the dal.d.ts without having access to this repo?

**To Reproduce**

Following the Steps in the Readme for Updating dal.d.ts:
1. `cd libs/blocksprj`
2. `rm -rf built`
3. `PXT_FORCE_LOCAL=1 PXT_COMPILE_SWITCHES=csv---mbcodal pxt build`
4. ...

**Expected behavior**
The dal.d.ts should build.

**Screenshots**
![image](https://user-images.githubusercontent.com/3764089/89326197-37e7f200-d68a-11ea-9103-bd38556d4509.png)

I already got that hint to delete the `dalDTS` from `libs/core/pxt.json`, but that doesn't change anything.

**Comment by MKleinSB** [comment]
Perhaps ask in the forum?
https://forum.makecode.com/c/Custom-MakeCode-editors/8
