### ISSUE TITLE
Displaying the help triggers the editor to update.

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#3344]
**Describe the bug**
Displaying the help triggers the editor to update.

**To Reproduce**
1. Go to https://makecode.microbit.org/#editor
2. Click on Javascript
3. Right click on any function/method
4. Click on "Help"
5. The editor will update and reload

The editor updated itself when I first loaded it, and then I found this issue.
I was able to replicate this until I refreshed the page.
It's possible this only happens if the editor was updated at the beginning of the session.

**Expected behavior**
The help to be shown and the editor not to be updated

**Screenshots**

It's not to clear when GIF ends loops over, but it shows the editor updating twice in the same session when the Help is opened.

![update-help](https://user-images.githubusercontent.com/29712657/90663517-afe51900-e241-11ea-98fd-997dd1da2774.gif)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser Chrome
 - Version 84
 - makecode.microbit.org version:  3.0.17
 - Microsoft MakeCode version:  6.0.18
 - microbit runtime version:  v2.2.0-rc6

**Additional context**
N/A

**Comment by microbit-carlos** [comment]
I was able to replicate this again after a session in the beta editor started with an editor update.
This time I was also able to trigger it getting the help from the blocks instead of the javascript editor.

**Comment by microbit-mark** [comment]
On Mac 10.15.6 using Chrome 85 this does not seem to replicate.

**Comment by microbit-carlos** [comment]
Since my last message and before today, I was able to replicate a couple of times more (once in different computer), but I can confirm that I wasn't able to replicate this again today. 
It's been a while since I loaded MakeCode, so I started a session with an update today and I was able to load the help widget correctly from blocks and code, without any reloads.

Sounds like something has fixed this, so I'll close this issue 👍
