### ISSUE TITLE
Not able to add files through Explorer

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#3345]
This was reported by a customer trying to create a custom tutorial/extension through the MakeCode interface.
Repro -
- Open a project in JavaScript editor
- In Explorer pane, click plus to add custom.ts
- Try to add another file - you can't since the plus (+) icon disappeared

I guess in Micro:bit we only allowed 1 custom.ts file?

**Comment by jwunderl** [comment]
This flag is not turned on yet [addNewTypeScriptFile](https://github.com/microsoft/pxt-arcade/blob/master/pxtarget.json#L431) so the only way to add currently is for github projects
