### ISSUE TITLE
Custom blocks + Tutorial issue

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#3346]
Customer not able to create custom blocks and tutorial in same repo.
Repo: https://github.com/kiki-lee/goldendoor

The Tutorial link - https://makecode.microbit.org/#tutorial:/https://github.com/kiki-lee/goldendoor/tutorial
only pulls up the Readme file, not the Tutorial file.

**Comment by abchatra** [comment]
This is fixed.

**Comment by abchatra** [comment]
By mono repo
