### ISSUE TITLE
how can I put a microbit html into iframe and render in a pc view

### ISSUE THREAD

**Issue by myidcn** [microsoft/pxt-microbit#3347]
**Describe the bug**
When I   put a microbit html into iframe, it can not show the menu and block menu .
How can I do  to show the block menu  as in browser.

![the error](https://user-images.githubusercontent.com/8453599/90757411-2d775a80-e310-11ea-966d-7140e011e0da.png)

**Desktop (please complete the following information):**
 - Device: [e.g. pc]
 - OS: [e.g. win 10]
 - Browser [e.g. firefox]
 - Version [e.g. 79]

**Comment by abchatra** [comment]
We dont support this scenario.
