### ISSUE TITLE
Feature: Add interval to show image block

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3349]
**Is your feature request related to a problem? Please describe.**
Currently, the show Image block has an offset for displaying an image at an offset. It would be useful for animations etc to be able to set the time that the image displays for in a similar way that we can set the scroll rate for scroll image. This would enable fast switching between images and images at different offset points.

**Describe the solution you'd like**
Something like 
![microbit-screenshot(6)](https://user-images.githubusercontent.com/31242877/90771413-27bb4e00-e2eb-11ea-9814-7247eb7fcc4a.png)

**Describe alternatives you've considered**

**Additional context**
Maybe relates to #3319 having the image display as fast as possible in animation.

**Comment by microbit-mark** [comment]
@abchatra as discussed ^

**Comment by jaustin** [comment]
I think this would be really useful, for example to make a simple and responsive sprit level, etc.

I'm torn between extending the version with the 'at offset' parameter or just adding a new block with no offset for single images... I think in many ways the 'offset' is a more confusing concept than the delay/interval so having a block with no offset would be useful.

If we were two have two 'show image' blocks, I'd prefer:

`Show image <image> with interval <interval>`
and
`Show image <image> with interval <interval> and offset <offset>`

(and then deprecate the existing "show image with offset" block)

**Comment by abchatra** [comment]
@jaustin can you give me a sample program you want to build with this block? 

Interval in the scroll makes sense as it is time between successive image displays. 
What happens after the interval in the image elapses? Does the image disappear? What happens if someone sets another image before the interval expires? I am not sure I have answer for these.

**Comment by jaustin** [comment]
Good questions.

I think we're looking for exactly the same behaviour as `showLEDS(<pattern>, interval)' gives.

```
basic.showLeds(`
    . # . # .
    . . . . .
    . . . . .
    # . . . #
    . # # # .
    `, interval)
```

So the same semantics as this call, but in a block where the interval can be specified.

**Comment by abchatra** [comment]
See https://github.com/microsoft/pxt-microbit/pull/3408

**Comment by abchatra** [comment]
fixed
