### ISSUE TITLE
Stop melody does not stop all melodies from playing

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3350]
If you create multiple melodies in a loop, stop melody does not stop them all playing.  In this program, if you shake during the first melody, it stops and then passes back to the next melody to play.

![microbit-screenshot](https://user-images.githubusercontent.com/31242877/90875730-86d79c00-e399-11ea-8d0f-614299d52f8e.png)

I would expect this program to stop all melodies playing on shake ie not play the second melody.

This reproduces in MakeCode and on the device.

**Comment by microbit-mark** [comment]
The stop melody block seems confusing then. Perhaps the default should be 'Stop melody - current' to indicate that it will stop current melody playing but not 'all'.

**Comment by abchatra** [comment]
It is stopping all the melody which is running. It can't stop the melody which is going to run in the future.

**Comment by abchatra** [comment]
You can always start a melody once it is stopped.
