### ISSUE TITLE
Android: Simulator doesn't load first time

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3352]
**Describe the bug**
The simulator does not load on initiating a new project in Chrome on Android. There is just a grey block with a play button on it
![image](https://user-images.githubusercontent.com/31242877/90908215-fc5c6000-e3cb-11ea-9060-933614fe674a.png)

**To Reproduce**
1. Go to 'makecode.microbit.org' on Android Chrome

**Expected behavior**

I would expect the simulator to load first time and then the user can choose to hide it using the stop button if they wish

**Comment by microbit-mark** [comment]
Noted. Is this documented anywhere @abchatra? If not I will add it to our Knowledge base.

**Comment by abchatra** [comment]
Probably not. Feel free to document.
