### ISSUE TITLE
Feature: Load more and rotate extensions in gallery

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3353]
**Is your feature request related to a problem? Please describe.**
The extension gallery in MakeCode shows the top 10 or so extensions, but it's not clear that there are any more available 

The `?' icon links out to https://makecode.microbit.org/extensions but this could be made more prominent

**Describe the solution you'd like**
Could we have a tile or button to 'Load More` so that when that button is clicked the top ten are replaced by the top 11-20 or even another ten randomly selected extensions, clicking the button again, moves to the next ten etc.

This would show the breadth of extensions available to users.
![Image 2020-08-24 at 3 45 34 pm](https://user-images.githubusercontent.com/31242877/91058858-e2678b00-e620-11ea-9dea-eddb85ab5d7f.png)

**Describe alternatives you've considered**
Just have the tile link out to the extension gallery instead of the `?`

**Additional context**

**Comment by abchatra** [comment]
This is implemented in /beta
