### ISSUE TITLE
Call function missing from context menu

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3354]
**Describe the bug**
MakeCode v1 had an option to right click on a function and select 'create <function> to add a call function block

https://share.getcloudapp.com/YEupROm5

it appears this has been deprecated in the current editor

![image](https://user-images.githubusercontent.com/31242877/91411050-b5dd8a00-e83f-11ea-86aa-68a234ea2b69.png)

**Expected behavior**
Should be able to create a call block from the context menu.

**Comment by abchatra** [comment]
@riknoll do you know why we deprecated this. I remember discussing.

**Comment by riknoll** [comment]
I do not

**Comment by microbit-mark** [comment]
@abchatra @riknoll Can you follow up on why this was removed? WOuld be useful to provide a reason or please re-add

**Comment by abchatra** [comment]
Fixed
