### ISSUE TITLE
Confusing `serial.readUntil` behaviour

### ISSUE THREAD

**Issue by Parakleta** [microsoft/pxt-microbit#3355]
**Describe the bug**

When using serial.readUntil to read delimited data, the returned string doesn't line up with the delimiters.  I cannot figure out how it chooses what data to return.  I have tried several different delimiters and the result is always the same.

**To Reproduce**

Load the following program:
```
serial.setWriteLinePadding(0)
basic.forever(function () {
    serial.writeLine("||" + serial.readUntil(serial.delimiters(Delimiters.Colon)) + "##")
})
```

Then using a terminal program, send the following text `ab:cd:ef:`

**Expected behavior**

I should get back the following strings `||ab##`, `||cd##`, and `||ef##`.

**Screenshots**

I get the following output in Termite:

```
61 62 3a 63 64 3a 65 66 3a                       ab:cd:ef:       
7c 7c 61 62 3a 63 23 23 0d 0a 7c 7c 23 23 0d 0a  ||ab:c##..||##..
7c 7c 65 66 23 23 0d 0a                          ||ef##..        
```

**Comment by abchatra** [comment]
@pelikhan can you answer this question?

**Comment by pelikhan** [comment]
It only works with the first character of the string.

**Comment by abchatra** [comment]
Questions answered

**Comment by Parakleta** [comment]
Sorry, but what does that mean?

**Comment by pelikhan** [comment]
Only the first character of the delimiter string is used, the rest is ignored.

**Comment by Parakleta** [comment]
How does that apply to the example I’ve given? I’m only using the colon character as a delimiter and it’s clearly not breaking at any consistent point

**Comment by pelikhan** [comment]
Sorry i read the sample wrong.

**Comment by abchatra** [comment]
@pelikhan is this is a bug?

**Comment by Parakleta** [comment]
Also curious to know what your basis for saying only the first delimiter character is used.  It's not clear from the documentation about the `readUntil` method but the `onDataReceived` method clearly states "delimiters is a string containing any of the character to match" which suggests that it delimits on any matching character, and I would have assumed `readUntil` would operate the same way.  Could you also please clarify this point since we're here?

**Comment by Parakleta** [comment]
I would assume anything with inconsistent behaviour is a bug, which is why I reported it.  :)

**Comment by pelikhan** [comment]
Looks like a bug

________________________________

**Comment by martinwork** [comment]
It's OK with V2 but not V1. I've created https://github.com/lancaster-university/microbit-dal/issues/480

**Comment by abchatra** [comment]
this is a dal external issue.
