### ISSUE TITLE
WebUSB paired micro:bit is reset every time the editor is opened

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#3357]
**Describe the bug**

If a micro:bit is connected via USB cable and has been WebUSB paired, opening the editor causes micro:bit to reset.

This doesn't happen in MakeCode V2.

Switching browser tabs also triggers a reset.

Try this program:

basic.showIcon(IconNames.Heart)
basic.pause(100)
basic.clearScreen()

**To Reproduce**
1. Go to 'https://makecode.microbit.org/'
2. WebUSB pair with micro:bit 
3. Download a program which shows when micro:bit resets
4. Click on Home
5. Click on any project or create a new project
6. See error

**Expected behavior**

Only cause the connected micro:bit to reset when a user action requires it.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome, Edge

**Comment by abchatra** [comment]
@pelikhan any clue what is wrong here?

**Comment by pelikhan** [comment]
DAPLink resets the editor when we set the baud rate when we connect. This only happens once now.
