### ISSUE TITLE
Syntax highlighting missing 

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3359]
> micro:bit support: #39057

**Describe the bug**
Syntax colour highlights are missing in the current editor. They do work in the previous version of the editor

![image](https://user-images.githubusercontent.com/31242877/92120075-82c36980-edf0-11ea-96e7-667a5f2d97e9.png)

Vs. Caliope editor

![image](https://user-images.githubusercontent.com/31242877/92120038-793a0180-edf0-11ea-961e-49be79fb136b.png)

**Expected behavior**
I would expect blocks to be colour highlighted to match the menu

**Comment by abchatra** [comment]
We have removed the syntax highlighting in the latest version as that had various bugs. This will be in the future versions

**Comment by abchatra** [comment]
No plan to address this.
