### ISSUE TITLE
Embedding blocks is ignoring assignments

### ISSUE THREAD

**Issue by jxns** [microsoft/pxt-microbit#3364]
Hello!
I created a simple block, just like the following:
`
let counter = 0
basic.forever(function () {
	basic.showString("" + (counter))
	counter += 1
})
`

But the statement `let counter = 0` is ignored after the rendering into the blocks. It is just ignored if you try to assign a 0. Other values (1, 500, 378789, ...) are working as expected.
I know that the assignment with 0 is redundant, but, in my opinion, this shouldn't be ignored from the block rendering.

Is this a bug or intended?

**Comment by abchatra** [comment]
Blocks & typescript are not 1-1. In blocks all the variables are global & initialized to zero by default. We have to make these assumptions to make blocks not verbose. This is by design.
