### ISSUE TITLE
020 error with bluetooth

### ISSUE THREAD

**Issue by machinehistories** [microsoft/pxt-microbit#3365]
I am trying to use web bluetooth examples with the microbit in chrome. There are several examples and repositories available on gitub for this. They all require you to load up several ble services on the board. Here is one of the files I am currently trying which leads to the error. [https://makecode.microbit.org/_YHtdtK9kt9Rz](url)  I also noticed if I try to add fewer services I can partially avoid the 020 but when I scan the board using Lightblue or BLE Scanner on ios it immediately loses a connection. Is there a previous firmware and software version better suited to experimenting with bluetooth. I've tried the 3 options for bluetooth pairing and they all generated the error.

**Comment by martinwork** [comment]
Looking at the example, BLE_t2b... In Project settings, none of the pairing options are selected. In "Edit settings as text", I can see that the bluetooth options are not complete. There is a targetVersions section. I don't know what that does.

I removed the magnetometer service and selected "No Pairing Required". After that, iOS nRF Connect sees it and can connect to it. The iOS micro:bit app can connect and communicate with the all the services. I also tried JustWorks pairing. BLE Scanner sees the services.

"No Pairing Required" is probably the mode for experimenting with WebBLE. If switching pairing modes, forget the pairing in Settings/Bluetooth and re-pair. Switching from passkey to justworks/open or from justworks to open may be OK without re-pairing.


```
    "targetVersions": {
        "branch": "v1.2.13",
        "tag": "v1.2.13",
        "commits": "https://github.com/Microsoft/pxt-microbit/commits/5d5b348757b15c6d00f5b7f560fd69592ca29424",
        "target": "1.2.13",
        "pxt": "4.4.7"
    },

```

**Comment by machinehistories** [comment]
Thank you for the info. I made a new basic  bluetooth file with on connected/on disconnected blocks and I added uart service to on start and a few uart write messages in the loop. I've tried to run this with both justworks and with open in the settings. However shortly after connecting to a ble app, if I try to turn on indicate and show the uart notifications the connection immediately disconnects. Here are the errors I get in nrf app. 
![IMG_2315](https://user-images.githubusercontent.com/26831444/92420962-24b5bf80-f12b-11ea-8460-47a92ec4aebc.PNG)
I notice if I program the microbit with arduino [https://github.com/adafruit/Adafruit_Microbit](https://github.com/adafruit/Adafruit_Microbit) I am able to use the ble uart with a larger number of ble apps. Also if I load the espruino firmware the ble uart consistently works with those apps. I am having difficulties with the makecode ble. In particular I'd like to use it with  [https://apps.apple.com/us/app/adafruit-bluefruit-le-connect/id830125974](https://apps.apple.com/us/app/adafruit-bluefruit-le-connect/id830125974). The app has a cool option to forward messages using mqtt but it just doesn't recognize microbit UART. You can see here that the espruino firmware shows uart but the microbit does not. So the board will connect to ble apps and it can even show all the services correctly, depending on the app, but I can't manage to transmit a message from the microbit to these apps. I am certain that I was able to use lightblue app in the past. Maybe this is a new ios issue. I will get a hold of an android device and see if the issues are the same. 
![uart](https://user-images.githubusercontent.com/26831444/92421512-b45c6d80-f12d-11ea-8151-cb36cf040db0.jpg)

**Comment by machinehistories** [comment]
Here is an example file. [https://makecode.microbit.org/_Dhm3hXJKx04X](https://makecode.microbit.org/_Dhm3hXJKx04X) In this case I am getting repeated 020 errors. I am trying various ble apps, such as nrf connect and I've tried different pairing methods. I've tried both android and ios and I get 020 errors with either.

**Comment by martinwork** [comment]
I am not familiar with all the apps you mention, but maybe the problems you are seeing with the BLE UART in those apps are related to these DAL issues:
https://github.com/lancaster-university/microbit-dal/issues/259
https://github.com/lancaster-university/microbit-dal/issues/407

The example above doesn't run out of memory if I remove the button service and the BlockyTalky extension, and then seems to work with nRF Connect.

Related:
https://github.com/microsoft/pxt-microbit/issues/3316

**Comment by machinehistories** [comment]
I see this is a rather complicated matter and it's been an issue for some time and it is definitely related to those issues. I know it's a totally different situation but I will mention the way espruino on microbit is handling ble uart is very dependable and works with a wide range of apps and with web bluetooth. Is it best to only use ble uart service on it's own or can it be used with any of the other services.

**Comment by martinwork** [comment]
I am not aware of any problems with using the BLE UART with other services, except for the RAM issue.

**Comment by machinehistories** [comment]
I used the official microbit sample program [https://support.microbit.org/support/solutions/articles/19000062330-using-the-micro-bit-bluetooth-low-energy-uart-serial-over-bluetooth-](https://support.microbit.org/support/solutions/articles/19000062330-using-the-micro-bit-bluetooth-low-energy-uart-serial-over-bluetooth-) [https://makecode.microbit.org/98535-28913-33692-07418](https://makecode.microbit.org/98535-28913-33692-07418). I have tried it no pairing using nrf connect, lightblue, and ble terminal apps and it is working. thanks

**Comment by machinehistories** [comment]
You mentioned this related post [#3316](https://github.com/microsoft/pxt-microbit/issues/3316). They suggest modifying what the default Bluetooth services as a way to help manage memory. Is this, or something similar, an option for dealing with these memory related errors. I was just getting ready for the fall term and I am trying out several previously working bluetooth example files, and it is somewhat common to see memory related errors. Is there anyway to provide a warning so that before the user downloads the hex file they can they can see they are over the memory limit and avoid frustration. Do you have any other suggestions on how to best work within the memory limits when bluetooth is enabled.

**Comment by martinwork** [comment]
I don't think there is any RAM usage analysis in the simulator.

Please try https://makecode.microbit.org/_EWjgHyeHW6Dp. This is your project modified along the lines discussed at https://github.com/lancaster-university/microbit-dal/issues/443.

The connected/disconnected handlers are combined into one. The bluetooth receive code is combined into one handler too, using a single delimiter (comma), with the text before the comma being used as the command. Event handlers use a lot of RAM relative to what's left after BLE is initialised,

See also Project settings / Edit as text. The partial flashing and event services are excluded from the build, and the RAM allocated to the GATT table (where services' data is stored) is reduced.

The iOS micro:bit app's gamepad-demo MakeCode sample is another example of using a single event handler for multiple events.

**Comment by machinehistories** [comment]
Wow thanks so much this is great info and I appreciate your time and expertise. I will certainly try this out.

**Comment by abchatra** [comment]
If this still an issue let me know. I will reopen the issue.
