### ISSUE TITLE
Add more docs on function blocks

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3367]
**Describe the bug**
It is unclear that a user has to drag a parameter from the block to use it in the program

![Screen Recording 2020-09-07 at 11 01 14 am](https://user-images.githubusercontent.com/31242877/92375944-bd334c00-f0f9-11ea-8400-b3822ad00681.gif)

The help links here

https://makecode.microbit.org/types/function/define

but there could be more info on how to use the drag and drop feature and something on the function editor too

![image](https://user-images.githubusercontent.com/31242877/92376997-5ca50e80-f0fb-11ea-9541-3c67e192660a.png)

**Comment by microbit-mark** [comment]
Can you process this one? It would be great to have some docs on this.

**Comment by abchatra** [comment]
@ganicke can we update the function documentation about variables & how to use them?

**Comment by ganicke** [comment]
Yea, I'll expand that page some to describe parameter usage.
