### ISSUE TITLE
 Delimiter missing in exported data

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3370]
**Bug**
Depending on the language selected, separators disappear in the exported file when writing to serial.
English, German, Ukrainian, Korean-works perfectly:
![image](https://user-images.githubusercontent.com/31242877/92485997-82a5de00-f1e3-11ea-83e4-c8a22d28d536.png)

Turkish and Russian do not add the delimiters:
![image](https://user-images.githubusercontent.com/31242877/92486048-905b6380-f1e3-11ea-881f-368e7922edd3.png)

**To Reproduce**
Steps to reproduce the behaviour:

1. Open https://makecode.microbit.org/_WW67csW1dbYc
2. open console in English and export file
3. do the same in Russian or Turkish

**Expected behaviour**
CSV file created is not in the correct format in Russian or Turkish

**Comment by microbit-mark** [comment]
Also reproduces in Finnish local. Can you take a look @abchatra

**Comment by pelikhan** [comment]
@ganicke looks like a loc bug

**Comment by ganicke** [comment]
Yes indeed. The trailing TAB char in `{id:csvseparator}` was missing in the following locales: `tr`, `ru`, `fi`, `frca`, `is`, `es`.
