### ISSUE TITLE
Link to edit github repo missing in v3?

### ISSUE THREAD

**Issue by IowaDave** [microsoft/pxt-microbit#3372]
**Is your feature request related to a problem? Please describe.**
Previous versions of the editor provided functionality for initiating a new repo in the online MakeCode editor. The link was located at the bottom of the page for importing Extensions. It said something like "Connect to github and work on your own extension." Not those exact words, but that was the concept.  The link was either moved or entirely removed in V3 -- I cannot find it.

**Describe the solution you'd like**
Please restore that link and the edit-repo capability in V3. Or, if it is there in a new location, please just tell me where to find it!  <smiling sheepishly>

**Describe alternatives you've considered**
Local creation of repo using the pxt toolchain: not applicable to my situation because not supported on Linux 
 or ChromeOS.
Create/edit in the github web page: not practical for me because I relied on MakeCode editor to auto-create files such as travis.yml and pxt.json, which I don't understand well. 

**Additional context**
My appeal is that providing the capacity to create/edit extensions in the MakeCode editor gives a more inclusive pathway for the user community to contribute extensions, for two reasons. It opens the door to young learners using Chromebooks or Linux. It relieves some of the cognitive burden placed on enthusiasts who are not yet schooled in languages such as yml and json. It should be possible to contribute an extension based solely on knowledge of STS/javascript.

**Comment by IowaDave** [comment]
Basically what I am asking for is to restore in V3 the functionality documented at the following URL:

[https://makecode.com/extensions/getting-started](https://makecode.com/extensions/getting-started)

**Comment by martinwork** [comment]
I haven't created an extension before, so this may be all wrong.... I think the button is next to the Download and save buttons. I created a new project, used the javascript editor to add namespace and blocks, used that button to save to github. then created a new project and imported the new extension via the github URL. Hope that helps!

**Comment by IowaDave** [comment]
Yes, there it was, all along. Thank you. This information resolves my
request.

**Comment by abchatra** [comment]
Yes it is right next to download button. Resolved

**Comment by abchatra** [comment]
We should update the documentation. @ganicke 
Can we update this https://makecode.com/extensions/getting-started documentation section below 

_From the main editor screen, go to the gear wheel and Extensions. Click on GitHub login at the bottom of the list and follow prompts to generate a personal access token (make sure to select the repo checkbox). Once logged in, the Import dialog on the home screen should have an option to create a new GitHub repository or clone an existing one. Follow it._

to use this?

![image](https://user-images.githubusercontent.com/6107272/93118821-b4042b00-f675-11ea-8005-b4aaafd376f6.png)

**Comment by abchatra** [comment]
@pelikhan fyi

**Comment by IowaDave** [comment]
Would you like for me to write a revision?

**Comment by abchatra** [comment]
@IowaDave thanks for the offer. @ganicke already fixed this: https://github.com/microsoft/pxt/pull/7460

In future feel free to give PR for any of the documentation issue. Appreciate your help.
