### ISSUE TITLE
Selectable call function name like selectable variable names

### ISSUE THREAD

**Issue by RRWagner** [microsoft/pxt-microbit#3373]
This feature request is related to the problem of not being able to easily edit an existing "call function" block within a loop or section of code to a different name the way that can be done with variable names.  There are many times where it would be very convenient to be able to duplicate a group of blocks, and then change which function is being called in the new group of blocks.  It is frustrating also because learners see that the editor allows this for variables, but it's not obvious why this isn't possible for functions.

The solution is to have the small triangle next to the function name in the call function block the same as in seen in the set or change variable blocks.

Thank you for considering this request.

**Comment by abchatra** [comment]
Request is for drop down in the call block to have the functions available.

**Comment by abchatra** [comment]
@riknoll fyi

**Comment by riknoll** [comment]
@abchatra that was the old design, we deliberately changed it when we added arguments to functions because the shape of the block can change. It isn't clear what we should happen to the blocks connected to the argument inputs.

**Comment by riknoll** [comment]
![2020-09-14 10 58 50](https://user-images.githubusercontent.com/13754588/93121207-5376ed00-f679-11ea-810b-e15eaccf2063.gif)

**Comment by abchatra** [comment]
Agreed. This enhancement request is asking for it to be back. We can track it for future release.

**Comment by abchatra** [comment]
No plan to address this.

**Comment by RRWagner** [comment]
I could imagine that what would happen to the arguments is that the current ones would disappear, and be replaced by the new arguments appropriate to the function chosen, since that list is already known to the editor.
