### ISSUE TITLE
Using "show leds block" can be downloaded, but when i use "shown icon" in my program, it can't be donwload.

### ISSUE THREAD

**Issue by Dolphinzzx** [microsoft/pxt-microbit#3375]
**Describe the bug**
Using "show leds block" in my progam, it can be downloaded.
But when i use "shown icon" in my program, it can't be donwload. And it will prompt as shown below.

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

![image](https://user-images.githubusercontent.com/31792429/93204830-53fea900-f789-11ea-8e00-d15849ac3f61.png)

![image](https://user-images.githubusercontent.com/31792429/93204937-86100b00-f789-11ea-8030-8251c30c5ff0.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chromei]

Thanks in advance.

**Comment by abchatra** [comment]
We can't reproduce this. Can you share the program? This is likely due to the extension you are using. 
Use the share icon at the top to share your program.

**Comment by abchatra** [comment]
No additional information provided.
