### ISSUE TITLE
Feature: Add X/Y axis to sim when plotting LEDs

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3383]
**Is your feature request related to a problem? Please describe.**
When plotting LEDs on the display it is not especially clear what x/y is or how it is represented on the sim

**Describe the solution you'd like**

It would be useful to show this on the sim, in a similar way to how we do it for accelerometer values. Maybe with the addition of an arrow pointing in the direction of the count.

![Image 2020-09-17 at 12 17 52 pm](https://user-images.githubusercontent.com/31242877/93463899-51629780-f8e0-11ea-9ecc-ff1769dbd45b.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by MKleinSB** [comment]
I think it should be better in the left upper Edge.

**Comment by jaustin** [comment]
I agree with MKleinSB, we should put the label at (0,0) which means top left. There's also more space there...

**Comment by ngammarano** [comment]
You could also add the X and Y numbers, something like this:
![image](http://brianaspinall.com/wp-content/uploads/2016/09/Screen-Shot-2016-09-06-at-8.24.31-AM.png)

**Comment by abchatra** [comment]
No plan to address this.

**Comment by microbit-mark** [comment]
Related in micro:bit support https://support.microbit.org/a/tickets/45695

Maths teacher says that the current orientation is confusing and the Y values should start from the bottom up, not the top down. 

It would be helpful if we had a way of showing how this works to users
