### ISSUE TITLE
Chrome patch breaks iframe embedding of examples

### ISSUE THREAD

**Issue by DaveAtKitronik** [microsoft/pxt-microbit#3386]
Following security patches to Google Chrome it is no longer possible to see a makecode program in an iframe embedded on to a third party website.

Test conditions:
On Google Chrome version 85.0.4183.102 we browser to the following page:
https://kitronik.co.uk/blogs/resources/using-bbc-microbit-control-servo

With this version of Chrome when the user scrolls down to “Example 1” they see the makecode iframe complete with program.

Chrome is upgraded to version 85.0.4183.121 and the same page is viewed. In this case one of two things will occur:

The page will load blank with a micro:bit logo in the background and throw an “Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.” This happens when the javascript tries to use the local storage to determine if it is showing blocks or script.

A program will load, however it will only be a blank on start and forever block. In this case it throws an error “Unhandled rejection SecurityError: Failed to execute ‘getDevices’ on ‘USB’: Access to the feature ‘usb’ is disallowed by feature policy.”

Yesterday (21 September) Google released an interim version of Chrome (85.0.4183.121) which includes fix 1100136, a security patch to prevent out of bounds reads in storage. My suspicions are that it is this change that has stopped makecode from functioning when in an iframe.

**To Reproduce**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 85.0.4183.121

@abchatra I think this is your area?

Dave

**Comment by microbit-mark** [comment]
I can recreate this using an incongito window
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/31242877/93861712-dec73280-fcb8-11ea-8991-dd1ef3b1e177.png">

**Comment by abchatra** [comment]
I can only reproduce this in incognito mode. We have a fix ready. Before releasing we want to confirm this information. Is anyone else seeing this non-incognito mode?

**Comment by pelikhan** [comment]
I could repro the issue yesterday but today on 85.0.4183.121 the iframe loads correctly.

**Comment by DaveAtKitronik** [comment]
It now appears (from a User PoV) to be working. There are still some serious looking errors in the Dev console though
