### ISSUE TITLE
Remove MakeCode App notice on the Science Course

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#3388]
Now that we have WebUSB, let's remove the notification that you have to have the MakeCode windows app to do this course.
https://makecode.microbit.org/courses/ucp-science
![image](https://user-images.githubusercontent.com/22108954/94045419-48604300-fd84-11ea-9a12-b41089613ca1.png)

**Comment by Jaqster** [comment]
Also on this page: https://makecode.microbit.org/courses/ucp-science/data-collection/overview
![image](https://user-images.githubusercontent.com/22108954/94045597-83fb0d00-fd84-11ea-8566-393bd87111ad.png)

**Comment by abchatra** [comment]
I think we need to say: Either MakeCode App or Webusb setup required?
