### ISSUE TITLE
Serial write blocks: writeNumber() doesn't include a line break, and it's causing confusion and inconsistency

### ISSUE THREAD

**Issue by kristianpedersen** [microsoft/pxt-microbit#3391]
I've seen a few beginners who want to log data, and try doing something like this:

```javascript
basic.forever(function () {
    serial.writeNumber(input.acceleration(Dimension.X))
})
```

This doesn't work because they don't have an empty `serial.writeLine("")` in their code, but that's not at all obvious or intuitive.

In my opinion, there's no good reason why `serial.writeNumber(0)` shouldn't log 0 to the console, while `serial.writeValue("x", 0)` does.

My reasoning also has to do with consistency and predictability in the blocks' layout:

There is already a distinction between string operations with and without line breaks: `serial.writeLine("")` and `serial.writeString("")`. I think it should be the same for numbers.

I think this layout would make a lot of sense for the MakeCode menu:
`serial.writeLine("")`
`serial.writeNumberLine(0)`
`serial.writeString("")`
`serial.writeNumber(0)`

This shouldn't affect backwards compatibility, and new users would have a more intuitive data logging experience.

**Comment by kristianpedersen** [comment]
> I've seen a few beginners who want to log data, and try doing something like this:
> 
> basic.forever(function () {
>     serial.writeNumber(input.acceleration(Dimension.X))
> })
> This doesn't work because they don't have an empty serial.writeLine("") in their code, but that's not at all obvious or intuitive.

This exact scenario happened to a colleague of mine yesterday. He thought there was a bug with the serial console or accelerometer, since he had previously had success logging text values with `serial.writeLine("")`.

**Comment by abchatra** [comment]
This is how these API worked for a long time. It is hard to change now by adding a flush character at the end. Won't fix from our end.

**Comment by keble6** [comment]
I found that this unexpected behaviour occurs also for _serial.writeLine(string)_.
The string is displayed on the console **only** if it is followed by _serial.writeString("")_
Surely this is not good practice!
Tagging @microbit-mark for info.

**Comment by abchatra** [comment]
@keble6  serial.writeLine flushes the cache. If not can open a new bug. 

If you only use serial.writeString then it will not.
