### ISSUE TITLE
ArrowNames enum is misleading to beginners: Replace "North" with "Up"?

### ISSUE THREAD

**Issue by kristianpedersen** [microsoft/pxt-microbit#3392]
Many beginners think this code should result in an arrow pointing towards north, but the arrow doesn't point north - it just points upwards on the display. ;)

```javascript
basic.forever(function () {
    basic.showArrow(ArrowNames.North)
})
```

Maybe `ArrowNames.Up` would be more correct and intuitive instead?

**Comment by abchatra** [comment]
For legacy reasons we can't fix this.
