### ISSUE TITLE
[Usability, blocks]: Add "Move up" and "Move down" to context menu

### ISSUE THREAD

**Issue by kristianpedersen** [microsoft/pxt-microbit#3396]
Moving blocks up or down is a bit awkward, and I see many users struggling with it. 

My suggestion is to have "Move up" and "Move down" in the right-click context menu.

The solution I end up demonstrating is:

> 1. Right-click/press+hold
> 2. Duplicate
> 3. Move duplicated block to correct spot
> 4. Find old block and right-click/press+hold
> 5. Delete

If the person is obviously comfortable with computers (and if we're using PCs), I'll show them this:

> 1. Left-click the block
> 2. CTRL+X --> CTRL+V
> 3. Drag block to correct position

However, explaining how to enter keyboard shortcuts, and having everyone remember X and V, two random letters, isn't the greatest solution.

Also, we constantly visit different schools, and many of them use iPads, so an improved solution is still needed.

My wish is to reduce this process to:

> 1. Right-click/press+hold
> 2. "Move up" or "Move down"

**Comment by abchatra** [comment]
@kristianpedersen I am not sure I understand the feedback. Are you only using keyboard and not mouse? Moving blocks up & down is drag of the block using mouse. 

If you are only using keyboard. Try the following experiment. Settings->About->Experiments to enable it.

![image](https://user-images.githubusercontent.com/6107272/94571307-b1cccf80-0224-11eb-94da-eaeda1c106f1.png)

**Comment by kristianpedersen** [comment]
That's not quite what I mean.

I just want to move a single block one line up/down. It's not intuitive for beginners how to achieve this.

In JavaScript mode, I can use Alt+ArrowUp or Alt+ArrowDown, but I think it's best to have a solution that works on iPad as well.

Here's an example, where a right-click menu item for moving up/down would have made this one single action.

![microbit-screenshot (2)](https://user-images.githubusercontent.com/5204369/94647543-f3c34780-02f0-11eb-8d3b-e564442598c2.png)

**Comment by pelikhan** [comment]
If you press Ctrl + Click, you will select the showNumber1 block only. Very hidden but probably what you want.

**Comment by kristianpedersen** [comment]
That's exactly what I want. It's hidden indeed, but simple enough to explain. Thanks!

Is there an iPad equivalent?

**Comment by pelikhan** [comment]
Touche! No iPad support that i know of.

**Comment by Jaqster** [comment]
What would really fix this is if we departed from Blockly and changed the default behavior to single-block move (vs parent), and we supported multi-block select with Shift (like most other app interaction models)

**Comment by kristianpedersen** [comment]
I agree, single-block move as the default mode makes sense.

I've even seen students delete individual bottom positioned blocks, one by one. They're doing it quickly and easily, so it seems like a natural way of doing things.

Using modifier keys is something I'm not so sure about. It's not something that's easy to discover, and doesn't work on touch devices.

My suggestion for accessing multi-block select would be to right-click/press+hold on one block, and choose "move with all connected blocks", or something like that.

**Comment by abchatra** [comment]
We are not going to deviate from blockly behavior.  Ctrl + Click is the alternative in desktop.
