### ISSUE TITLE
Melody blocks don't show the notes when using "renderblocks"

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microsoft/pxt-microbit#3398]
> micro:bit support: #39596

**Describe the bug**

Live reproduction: https://jsfiddle.net/50qmwha3/

The "play melody" block looks like this in MakeCode:

![image](https://user-images.githubusercontent.com/44397098/94541542-9cb16a00-023f-11eb-9e8d-d9a69c6c34fa.png)

but via "renderblocks" it does not show the note colours:

![image](https://user-images.githubusercontent.com/44397098/94541325-5cea8280-023f-11eb-9799-f32859c34abb.png)

Code is `music.playMelody("C5 B A G F E D C ", 120)`.

This affects educators using micro:bit classroom as they cannot tell whether any melody has been completed.

**To Reproduce**

See fiddle https://jsfiddle.net/50qmwha3/

This doesn't seem to be related to user input; the play melody block always seems to render like this.

**Expected behavior**
The melody block to look as it does in MakeCode.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by jwunderl** [comment]
Here's a fiddle with it fixed, will come with next release

**Comment by microbit-matt-hillsdon** [comment]
Great to see this fixed, thanks 🙂
