### ISSUE TITLE
collections not available in blocks... 

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#34]
what do you want to do with the teaching of collections? 

http://localhost:3232/lessons/headbands

**Comment by pelikhan** [comment]
I will rewrite.

Sent from Outlook Mobile<https://aka.ms/djubve>




On Thu, Mar 31, 2016 at 5:54 PM -0700, "Michael Elliot Braun" <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #34<https://github.com/Microsoft/kindscript-microbit/issues/34> to @pelikhan<https://github.com/pelikhan>.

-

**Comment by pelikhan** [comment]
Not supported in blocks for now.
