### ISSUE TITLE
Setting volume after calling 'ring_tone()' doesn't change the volume.

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#3400]
**Describe the bug**

The 'volume' block doesn't change the volume of a 'ringing' tone.

**To Reproduce**

<img width="736" alt="image" src="https://user-images.githubusercontent.com/147113/95103102-1fe52b00-072c-11eb-83b5-0ee71a224583.png">

**Expected behavior**
If the volume is set after a tone has been started, the volume will be reduced

[microbit-volume-test-ringtone.hex.zip](https://github.com/microsoft/pxt-microbit/files/5328501/microbit-volume-test-ringtone.hex.zip)

**Comment by abchatra** [comment]
Also ring tone (Hz) 0 doesn't work and need to work. See #805
