### ISSUE TITLE
Melody blocks do not work in embeds

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3404]
https://github.com/microsoft/pxt-microbit/issues/327 fixed the issue of embeds not loading when we updated to V3 of the editor, but melody blocks still do not seem to render. This may be a result of updating the melody APIs

![image](https://user-images.githubusercontent.com/31242877/85406511-d6e0e080-b559-11ea-8c03-faf8348c522c.png)

_Originally posted by @microbit-mark in https://github.com/microsoft/pxt-microbit/issues/3276#issuecomment-648131178_

**Comment by abchatra** [comment]
@microbit-mark We don't have have beginMelody block, we only have music.startMelody.
This block is likely deprecated. Can you please update the snippet to use playMelody or startMelody?

**Comment by microbit-mark** [comment]
I've asked the user to update their embed codes. If current API changes are made between releases, this will break embeds like this, so we should be mindful of this in future releases.

**Comment by abchatra** [comment]
This API was not deprecated in last year. It was deprecated in v0 which was 3 years back. I am unsure how this worked in the past. 
It is good to update the script to the latest one.
