### ISSUE TITLE
Simulator restarts in the background when stopped

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3413]
Notice how the overlay shows that the simulator should be stopped; but indeed it has been restarted in the background.
![bug](https://user-images.githubusercontent.com/4175913/95827981-41748280-0ce9-11eb-8ee5-372d107286c5.gif)

**Comment by abchatra** [comment]
How do I repro this?

**Comment by jwunderl** [comment]
Had this one happen too; it's not in /stable, it's off master, so not this release probably. If you do a local build based off master in pxt/-microbit/-common-packages, load this https://makecode.microbit.org/_Ly6bpj357afF, and stop the sim you'll see it

**Comment by jwunderl** [comment]
Will need to fix this, looks like it's https://github.com/microsoft/pxt/pull/7509 -- no messages are getting posted at all except broadcast ones. It's also breaking the mute button, which is testing another change I'm making hard, so I'll take a look~

**Comment by pelikhan** [comment]
Oops. The problem is that we are routing every message including things like react debugger messages etc... you can revert it and I’ll work another fix.

________________________________
