### ISSUE TITLE
Servo Write does not work with V2 board revision

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3414]
**Describe the bug**
This code has no effect on the pin output. ie the voltage does not change on the pins

```
basic.forever(function () {
pins.servoWritePin(AnalogPin.P1, 180)
pins.servoWritePin(AnalogPin.P2, 0)
basic.pause(1000)
pins.servoWritePin(AnalogPin.P1, 0)
pins.servoWritePin(AnalogPin.P2, 180)
basic.pause(1000)
})
```

Using Chrome, Win10, https://makecode.microbit.org/beta#editor

**Expected behavior**

Same code form makecode.microbit.org/beta on a V1.5 works as expected, a voltage change is seen on the pin and the servos move.

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jwunderl** [comment]
I think this looks like an issue in codal - we just call their method on the pin that is passed https://github.com/microsoft/pxt-microbit/blob/ea1b7002806db65de92e8b3b14d45fe351a50785/libs/core/pins.cpp#L285-L287

Little bit simpler to test example - if you connect pins 0 and 1 and press a / b, on v1 it will switch between displaying 2 and 1023, and on v2 it sends out a random value ~650-850

```typescript
input.onButtonPressed(Button.A, function () {
    pins.servoWritePin(AnalogPin.P0, 180)
    basic.pause(100)
    basic.showNumber(pins.analogReadPin(AnalogPin.P1))
})
input.onButtonPressed(Button.B, function () {
    pins.servoWritePin(AnalogPin.P0, 0)
    basic.pause(100)
    basic.showNumber(pins.analogReadPin(AnalogPin.P1))
})
```

 https://makecode.microbit.org/48146-95838-23530-90325

**Comment by abchatra** [comment]
@jaustin this is CODAL issue. Whom should this go? Does servo work in python?

**Comment by finneyj** [comment]
yep -bug in a pulsewidth calculation on the coal side. Fixed here: 
https://github.com/lancaster-university/codal-nrf52/commit/406a4e9b08fb4a227b979f95629764cae7bd8a1d

**Comment by pelikhan** [comment]
Tag? :)

________________________________

**Comment by finneyj** [comment]
:)

v0.2.12

**Comment by abchatra** [comment]
Fixed
