### ISSUE TITLE
NeoPixel extension does not work with V2 board revision

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3415]
**Describe the bug**
Using neopixel does not work on the latest micro:bit revision

![image](https://user-images.githubusercontent.com/31242877/95858380-e9736580-0d54-11eb-81e7-2c3a7bbad8cc.png)

**To Reproduce**
Flash a program using the neopixel extension and neopixels attached.
Works on V1.* not on V2

**Expected behavior**
Works on all board variants

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 4tronix** [comment]
Critical issue

**Comment by ryanteck** [comment]
Is there an ETA for this to be fixed, I'm in the same situation as @4tronix with it being an add-on breaking issue.

**Comment by CleoQc** [comment]
Critical issue for Gigglebot too

**Comment by jaustin** [comment]
@abchatra I think from #3411 this is now merged but lots of people are asking for a way to test the update. Certainly @DaveAtKitronik needs to know the steps for moving to the updated sendBufferASM, unless it will just work for Kitronik extensions?

I think, though, Kitronik need to do something specific with making a release of their extension before any changes, and then move over to the new core implementation. @pelikhan or @mmoskal can you please summarise here what they need to do based on the shims you have re-enabled and the sendBufferASM changes, and also @abchatra when the neopixel fix will end up in /beta?

**Comment by mmoskal** [comment]
There are two new functions in `light` namespace, see https://github.com/microsoft/pxt-microbit/blob/master/libs/core/shims.d.ts#L1108

Everyone that reimplements the bit banging assembly function, should publish an update to their extension that targets the new functions. Once this is done, let us a know and we can enforce this extension version to be minimal.

I'm not sure which branches these changes are available in though.

**Comment by DaveAtKitronik** [comment]
@AlasdairAtKitronik

**Comment by pelikhan** [comment]
You can test out those changes in https://makecode.microbit.org/v3.1 . Note that the final release will be based on v3.0 so some changes won't be there (this should not impact your product). We will get those changes in makecode.microbit.org/beta soon.

**Comment by CleoQc** [comment]
Am I testing this right?
I went to https://makecode.microbit.org/v3.1 and loaded up the neopixel extension.  I am using a Gigglebot but not the gigglebot extension. The standard neopixel blocks work in theory.

![image](https://user-images.githubusercontent.com/4965628/97224731-f443e680-17a7-11eb-825d-c78cefdedffd.png)

When I press either A or B, I see the X icon, never see the pixels turn on, and never see the checkmark. In fact, once I hit the X, nothing else works. I can't clear the screen for example.

And if I do something simple like the following, I need to do a complete power cycle on the microbit whenever I change the colour. I would expect simply flashing the new code would work, but it doesn't. 

![image](https://user-images.githubusercontent.com/4965628/97225352-ecd10d00-17a8-11eb-92fc-402b3f2af56d.png)

**Comment by AlasdairAtKitronik** [comment]
@pelikhan How can we test our extensions without causing breaking changes for products already out in the world?

For all our extensions using Neopixels I have created a new branch with the v3 MakeCode stuff, but I can't pull a specific branch of an extension into MakeCode to test. The 'Test Extension' in the GitHub integration also doesn't seem to be working properly, just constantly throws up compilation errors (with known working code). I've also tried to find the v3 GitHub repo to do an offline build, but I'm guessing that's private at the moment. Please can we have some pointers?

**Comment by AlasdairAtKitronik** [comment]
> Am I testing this right?
> I went to https://makecode.microbit.org/v3.1 and loaded up the neopixel extension. I am using a Gigglebot but not the gigglebot extension. The standard neopixel blocks work in theory.
> 
> ![image](https://user-images.githubusercontent.com/4965628/97224731-f443e680-17a7-11eb-825d-c78cefdedffd.png)
> 
> When I press either A or B, I see the X icon, never see the pixels turn on, and never see the checkmark. In fact, once I hit the X, nothing else works. I can't clear the screen for example.
> 
> And if I do something simple like the following, I need to do a complete power cycle on the microbit whenever I change the colour. I would expect simply flashing the new code would work, but it doesn't.
> 
> ![image](https://user-images.githubusercontent.com/4965628/97225352-ecd10d00-17a8-11eb-92fc-402b3f2af56d.png)

I have been trying similar tests to @CleoQc with the Kitronik :GAME ZIP64, but using the standard Neopixel extension in the v3.1 editor. Using the same code as above, I have some different results. 
The first program (with the button presses) correctly displays the icons on the micro:bit display, and allows the screen to be cleared, but doesn't display anything on the Neopixels. 
The second program (just trying to show all orange), again doesn't display anything on the Neopixels, regardless of resets or power cycles. 
However, interestingly, if I have the USB cable plugged into the micro:bit while either of these programs is running, when the micro:bit resets or powers up, all the Neopixels turn on full brightness white.
I have also programmed a V1.5 micro:bit with these same programs from the same v3.1 editor and they work as expected.

**Comment by mmoskal** [comment]
it appears daplink was interfering with our neopixel implementation. You should be able to test by making sure there's nothing trying to connect to daplink (webusb) and power cycling the microbit.

Otherwise, this PR https://github.com/microsoft/pxt-microbit/pull/3493 will fix it for future use

**Comment by microbit-mark** [comment]
Should this now be in  /v3.1 or /beta? Neither works for me with a V2 board and Neopixels on Pin0

**Comment by mmoskal** [comment]
should be available in 3.1.19 shortly

**Comment by microbit-mark** [comment]
Thanks @mmoskal. Now working!

**Comment by 4tronix** [comment]
Oh yes!!! Works Great!

------ Original Message ------

**Comment by CleoQc** [comment]
Yes for the gigglebot too!

and unrelated but we do appreciate this new block: 
![image](https://user-images.githubusercontent.com/4965628/97478777-c7b6d880-1927-11eb-80b2-f5a543fb998b.png)

**Comment by CleoQc** [comment]
Question for the others, @AlasdairAtKitronik  @4tronix . 
Do the neopixels shimmer constantly on your kits? Like, more than usual? It's fairly obvious on the gigglebot.  I'm honestly just happy they turn on at all but I wanted to reach out and see if this is common to all.

**Comment by ryanteck** [comment]
@CleoQc I don't notice any shimmer myself on mine.

**Comment by CleoQc** [comment]
It was a power issue. All good now!

**Comment by abchatra** [comment]
Make sure test on /beta.
