### ISSUE TITLE
Can't reference custom blocks in MakeCode namespace

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3416]
**Describe the bug**
https://github.com/microbit-foundation/pxt-microbit-v2-extension/blob/master/README.md uses custom blocks within the current MakeCode namespaces eg `input.soundLevel()`

These blocks do not seem to render in documenation

**To Reproduce**

## Does not work
![Image 2020-10-13 at 4 33 51 pm](https://user-images.githubusercontent.com/31242877/95883840-4847d780-0d73-11eb-902a-fe3f547e7f05.png)
## Works
![Image 2020-10-13 at 4 33 16 pm](https://user-images.githubusercontent.com/31242877/95883852-4b42c800-0d73-11eb-9824-0e1866606b00.png)

**Expected behavior**
I would expect blocks to render

**Comment by microbit-mark** [comment]
@pelikhan @abchatra as mentioned on our call. Should this work?

**Comment by microbit-matt-hillsdon** [comment]
I think we might have misunderstood here. I was trying to make sure that the README.md in the extension was working well, so I opened it in MakeCode (via file explorer) to see the rendered blocks. That's when the blocks don't render. I've since opened the sidebar README.md rendering for other extensions and it seems that they never render the blocks when opened like this. So perhaps this just isn't a valid way to preview our docs.

**Comment by microbit-mark** [comment]
Now the extension is approved, it appears that the help is not accessible at all

![image](https://user-images.githubusercontent.com/31242877/96228984-3b530000-0f8e-11eb-93c9-591b2643375e.png)

Help links to MakeCode docs https://makecode.microbit.org/reference/input/on-sound which aren't available.

What's the best way to fix this so we can provide early users access to some docs @pelikhan?

**Comment by microbit-matt-hillsdon** [comment]
I think that might be our fault. The blocks have references to help that we didn't write (with a view to writing it once it was in pxt-microbit). I'll try removing them unless anyone has other thoughts.

**Comment by microbit-matt-hillsdon** [comment]
We've fixed that in v0.4.2 of the extension and the blocks now link to https://makecode.microbit.org/pkg/microbit-foundation/pxt-microbit-v2-extension which renders OK.

We might look at taking advantage of the URL fragments that MakeCode passes later.

I think this can be closed now.

**Comment by microbit-mark** [comment]
Great. The original issue is resolved so closing
