### ISSUE TITLE
Flashing v2 via WebUSB restarts micro:bit twice 

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#3418]
**Describe the bug**

**To Reproduce**
1. Go to 'https://makecode.microbit.org/beta?compile=multiVariant#editor'
2. make a sound or on start https://makecode.microbit.org/_Ld8Ezr7rYMKD demos this well
3. Flash via webUSB to v2 micro:bit
4. Program starts twice so tone is heard twice

**Expected behavior**
micro:bit only resets once.

 This does not reproduce with v1 board. Could it be a DAPLink issue?

We are not having this issue with the Python Editor WebUSB implementation, so while I wouldn't discard an issue with DAPLink, it's worth looking into MakeCode first.

In case it helps, see
microbit-foundation/codal-microbit#89 (comment)
"After a USB flash... The bootloader is rebooting once before the application runs. I'm not sure if the reboot happens when there is no display. I'm pretty sure the bootloader is not rebooting on purpose, just that the first jump to 0x27000 ends up running the bootloader again."

This seems to reproduce for any program, whether we use the display or not. I can confirm it does not happen in the Python Eidtor when using webUSB

**Comment by abchatra** [comment]
Ported from https://github.com/microsoft/pxt-microbit-next/issues/64

**Comment by mmoskal** [comment]
this is due to https://github.com/microbit-foundation/DAPLink/issues/6

as a workaround, we could only set the baud rate once per session

**Comment by pelikhan** [comment]
We don't disconnect from DAPLink anymore; so we reset once when connecting to DALLink to set the baud rate.
