### ISSUE TITLE
Check DAPLink behaviour in Win10 app

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#3420]
Previous comment from @abchatra's testing:

I tested in the app for 1.47.2. App didn’t detect the microbit when connected for the first time. I download the hex file from the app and manually copied it.

After the first manual copy of MakeCode hex it worked seamlessly. I could directly download and see serial data.

Follow up:

I tested the current behaviour for this in the win10 app and the micro:bit is picked up by the app and able to direct flash on first connection, even with a hex file generated in the python editor on the nRF. It does not require a drag and drop first.

The same editor experience moving from Python editor to MakeCode is:

Flash Universal Python Editor hex (attached)
Open  MakeCode multivariant editor which automatically re-pairs the device if it has been paired before
Click download and program is flashed to device.
That's what we would expect and presumably, if webUSB can do a full flash, it would be the same in the win 10 app.

@abchatra
microbit__python_program.hex(1).zip
Are you able to check again with the python hex on the device first and then confirm whether you still have to drag and drop a MakeCode file to initiate the direct serial connection in the win10 app?

**Comment by jwunderl** [comment]
I was reading through some of the common exceptions and one that seems related (probably the cause) here:  `Bad response for 130 -> 255` at
https://github.com/microsoft/pxt-microbit/blob/0bf6864763822d4a0e45d07f05559c06145bba2b/editor/prepend/dapjs.js#L2391, coming from https://github.com/microsoft/pxt-microbit/blob/0bf6864763822d4a0e45d07f05559c06145bba2b/editor/flash.ts#L173

Looks like this logic was changed a bit in https://github.com/microsoft/pxt-microbit/pull/2794/files#diff-d4cae301c7fe5ef74f432b0709c9b908c98be497386263cb498c73852bc847f5R160 ~

```
exceptions
| where cookie = true
| where timestamp > ago(1day)
| where problemId contains "130 -> 255"
| where customDimensions.WindowsApp == 1
| summarize dcount(session_Id)
```

**Comment by jaustin** [comment]
At the moment the W10 app is confounding the few people who have V2 test devices because it doesn't know anything about v2, and weirdly it seems not to stop flashing after it failes (orange LED continues to blink). This then means the user will try drag-and-drop flash while HID is happening and get a 502 error (typically, could be 509).

I think there's no need for a point-fix to the W10 app, but something that determines for both live Makecode and the W10 app that a v2 baord is present and flips to MultiVariant would help these users in the interim. Enabling MultiVariant everywhere is another option.

**Comment by microbit-mark** [comment]
As per your comment in Slack @abchatra I have tested this with the beta editor "just go to extensions search bar and type /@beta and it will load beta" and can confirm your issue that direct HID flashing fails and drag and drop results in error 502 with micro:bit V2 using DAPLink 0255. Disconnecting and reconnecting the board does not resolve.

**Comment by microbit-mark** [comment]
This appears fixed when using latest DAPLink Bootloader 
```
# DAPLink Firmware - see https://mbed.com/daplink
Unique ID: 9904360249624e45003c601400000034000000009796990b
HIC ID: 9796990b
Auto Reset: 1
Automation allowed: 0
Overflow detection: 0
Incompatible image detection: 1
Page erasing: 0
Daplink Mode: Interface
Interface Version: 0255
Bootloader Version: 0255
Git SHA: 1436bdcc67029fdfc0ff03b73e12045bb6a9f272
Local Mods: 0
USB Interfaces: MSD, CDC, HID, WebUSB
Bootloader CRC: 0x828c6069
Interface CRC: 0x5b5cc0f5
Remount count: 0
URL: https://microbit.org/device/?id=9904&v=0255
 ```

**Comment by abchatra** [comment]
fixed
