### ISSUE TITLE
Radio does not work between board variants without first setting the group

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#3421]
<img width="414" alt="image" src="https://user-images.githubusercontent.com/31242877/95192082-92f0af00-07c9-11eb-87ce-65cbcb0ae6dd.png">

Does not work v2-v1
Works v1-v1
Works v2-v2

Setting the group in on start fixes this, but it should work without having to do this

**Comment by pelikhan** [comment]
The issue here is that the hash of the program is different between nrf51 and nrf52; which leads to a different random radio group. SOlutions are:
- always use group 1
- always use group 2
- always use group ...254
- add a new stable hash regardless of the architecture
@mmoskal

**Comment by mmoskal** [comment]
We could embed the project guid in the generated code, and use that as the group. Then the group wouldn't change as the user modifies program, but is different from other users.

**Comment by abchatra** [comment]
My vote is "always use group 254" and document it. If someone doesn't use a group, it is always 254. Easy to remember. No kid understands the hash logic. 

Most folks set their group anyway. 

@Jaqster @jaustin

**Comment by abchatra** [comment]
>> _Why not always default to group 1? easier to explain..._

There might be bunch of scripts out there with group 1 which might conflict if default group is also 1. Unlikely there are many scripts with group 254. Only for backward compat reasons. Otherwise group  1 is better.

**Comment by Jaqster** [comment]
How would the scripts conflict?  Wouldn't it just work anyways - whether group 1 is set explicitly by the user or default-under-the-covers?  To me, having the default group setting be something obvious and easy to explain is better...
![image](https://user-images.githubusercontent.com/22108954/96016723-f009e780-0dfd-11eb-81ca-892ae0ccf7e7.png)

**Comment by pelikhan** [comment]
The point of this feature was to avoid unexpected packet collisions between all the random projects running on micro:bit in a classroom. At this point, if we are to pick a number, we could just default to ``1`` and **always** start the tutorial with setting up the group number.

**Comment by Jaqster** [comment]
That's okay IMO.  Most times the group setting is optional - kids/teachers expect messages to flow to all micro:bits in the classroom.  I've seen Teachers say "if you want to send a secret message" then they have the students set the group number to something secret that only the sender/receiver know.

**Comment by abchatra** [comment]
Sounds good to me. Lets set to default group to "1"

**Comment by jaustin** [comment]
> That's okay IMO. Most times the group setting is optional - kids/teachers expect messages to flow to all micro:bits in the classroom. I've seen Teachers say "if you want to send a secret message" then they have the students set the group number to something secret that only the sender/receiver know.

I don't think the expectation that messages go to all devices is something I've seen as common - some very popular activities like "Chuck-a-duck" are predicated on this not being the case.

@microbit-giles do you have thoughts on this from your experience with teachers and in the classroom yourself?

**Comment by abchatra** [comment]
Expectation is going to some device though. Hash will ensure the code will go to no device. Unless you flash from the same PC.

**Comment by abchatra** [comment]
We have group setting in all our tutorials

**Comment by Jaqster** [comment]
The way I've seen this explained is that the Teacher talks about how a Radio works - a sender broadcasts messages out and receivers pick it up and hear the message.  Then they do a "send my name" activity in the classroom.  It's mahem and the students love it.  Then sometimes, the Teacher will do the "secret message" activity where they set the Radio group.

**Comment by Jaqster** [comment]
I think the hash is confusing and difficult to explain behavior.  Agree this would be a change to the API, but I think it's an improvement and much clearer to explain to Teachers.  We could wait on this until the next major release...

**Comment by pelikhan** [comment]
Many lessons tell user to change group to 1 and 1 is the default so better pick another one.

________________________________

**Comment by Jaqster** [comment]
> Many lessons tell user to change group to 1 and 1 is the default so better pick another one.

Why does this matter?

**Comment by pelikhan** [comment]
Getting random packets from any micro:bit is equally confusing. This issue can be solved by systematically introducing the concept of group in radio lessons. Also, we could display the group on the simulator.

**Comment by pelikhan** [comment]
> Why does this matter?

To avoid collisions with random program that haven't set the group number.

**Comment by Jaqster** [comment]
> > Why does this matter?
> 
> To avoid collisions with random program that haven't set the group number.

But if we clearly explain that "if you don't set a Radio Group, then it defaults to channel 1"  is a lot easier for people to understand than "there is a secret hash code for programs with no radio group set - you can't see it, and we can't tell you which programs are compatible"

**Comment by jaustin** [comment]
> Expectation is going to some device though. Hash will ensure the code will go to no device. Unless you flash from the same PC.

But this is the behaviour today and it really doesn't confuse people as far as I see? 

If you want two programs to communicate from different computers, set the group...

**Comment by abchatra** [comment]
It does confuse people. I have talked to so many who don't understand the default behavior. I just say set the group.

**Comment by abchatra** [comment]
>> But if we clearly explain that "if you don't set a Radio Group, then it defaults to channel 1" is a lot easier for people to understand than "there is a secret hash code for programs with no radio group set - you can't see it, and we can't tell you which programs are compatible"

Teaching a new behavior is not easy. People need to read documentation again. That is the reason I though "Group 254" is a good alternative. It will work for anyone who doesn't set the group and doesn't conflict with the usually set group of number 1-10.

**Comment by jaustin** [comment]
> > > Why does this matter?
> > 
> > 
> > To avoid collisions with random program that haven't set the group number.
> 
> But if we clearly explain that "if you don't set a Radio Group, then it defaults to channel 1" is a lot easier for people to understand than "there is a secret hash code for programs with no radio group set - you can't see it, and we can't tell you which programs are compatible"

I think the explanation I like for this is "if you don't set the group, you get a special group just for your program so it doesn't interfere with other programs in the room"

Without the hash - a teacher now has to allocate a different group to each student or group of students to stop them colliding! Before if you had students working on the same PC or groups working on one PC, that problem completely went away.

That's a additional overhead for a teacher if they're trying to help debug, because you can't be sure someone else hasn't got the same group  - Firstly asking if anyone else is using the same group, then checking they haven't actually got it wrong in their code, etc.

**Comment by abchatra** [comment]
I disagree @jaustin. Everything should work by default for kids. Primary purpose of radio is talk to another kids microbit. If it works just for one kid, is not a good default.

**Comment by jaustin** [comment]
> It does confuse people. I have talked to so many who don't understand the default behavior. I just say set the group.

I think that's fine though. I think confused but NON colliding is a lot better than confused AND colliding. The thing about a room where the group is set to the same default is that you see really odd behaviour you can't undestand. 
 * You get messages that aren't in the bounds of your program (so, expect numbers between 0-3 but someone else is sending numbers 0-9, now your code does really random stuff). 
* You get actions you didn't initiate, or that you can't work out why they happened. This is worse when people are doing stuff at the same time and their action conicides with your action, but their message is received first. Say your "on button A" sends 1, and theirs sends "2" you go mad trying to work out why your program did the wrong action

**Comment by abchatra** [comment]
Hash can be any number including 0-9. So you will get message sometimes. Explaining that is hard.

**Comment by jaustin** [comment]
I think we're discussing a change in behaviour because of a bug we can fix... why don't we fix the bug and then have a separate discussion about the change in behaviour.

**Fixing the bug:** seems like there's a viable way to do it listed in https://github.com/microsoft/pxt-microbit/issues/3421#issuecomment-708441434 that and keeps consistent behaviour. Let's do that first, because it is the least change for people.

**Changing the behaviour:** Let's do some research, have a wider discussion and make a breaking change at an annual boundary, or sooner if there's overwhelming evidence.

**Comment by Jaqster** [comment]
I think we need more user testing and to talk with Educators.  What I've seen has obviously been very different from what you're seeing Jonny.  I have never seen students with more than 1 micro:bit each, and most of the scenarios I've seen have been "Broadcast to everyone" or "Send a secret message".

**Comment by jaustin** [comment]
> Hash can be any number including 0-9. So you will get message sometimes. Explaining that is hard.

Yea, that's definitely true. Hashes colliding, or colliding with definitively selected groups is one of the downsides. In practice I've never seen this. But it's confusing as you say, because it breaks the truth of "you have a code just for your program"!

**Comment by jaustin** [comment]
> I think we need more user testing and to talk with Educators. What I've seen has obviously been very different from what you're seeing Jonny. I have never seen students with more than 1 micro:bit each, and most of the scenarios I've seen have been "Broadcast to everyone" or "Send a secret message".

Yes, agree with some wider user testing and discission with educators - also it's probably now quite a daunting thread for new people  to grok and chime in with as we're excalating the post count pretty quickly! :)

**Comment by pelikhan** [comment]
Settings the hash from a "computer PC id" could also be reasonable. It will work with your working buddy but it's unlikely that you get bothered by other people's scripts.

**Comment by abchatra** [comment]
Lets do user study and do the right thing. We tend to keep arguing in this point and do no progress. I oppose any new hash.

**Comment by jaustin** [comment]
Thinking a bit more broadly here are some wider suggestions that aren't just 'have a hash or have a fixed default'.

I don't think any of these is complete or quite nails it, but they're different to what I've thought about before on this... 

* Are there any things we can do to require a group being set? IE never have a default under people's feet? eg with blockly somehow showing errors, etc? Runtime errors are bad, but that kind of option exists.
* If we can't require the user to set a group, so instead we  are setting the group to a default or hash value, can we make that visible to the user - eg some other Ux that says "Your radio group is set to ZYX" - most of the complaints about either the hash or the default above is that people don't understand why messages are (or are not!) being received
* Make the group more explicit in the existing blocks language, so 'radio send X" could be "Radio send X to current group" and then it would be clear the 'group' block was crucial... (block behaviour doesn't change, just the text)

**Comment by Jaqster** [comment]
I like these ideas. Agree that making the group setting more explicit would help clear up a lot of confusion when it comes to explaining the "Radio Magic"...

**Comment by pelikhan** [comment]
Showing the invisible state - eg show group id - on the simulator is best - regardless of the default.

________________________________

**Comment by microbit-giles** [comment]
> I think we're discussing a change in behaviour because of a bug we can fix... why don't we fix the bug and then have a separate discussion about the change in behaviour?

I agree with @jaustin that we have two different things here. The micro:bit is all about continuity and stability, and this is especially sensitive as we introduce V2. We should preserve the existing behaviour at least for now, and fix it so the hash works across V1 and V2 devices.

Changes in the radio behaviour may be a good idea but would best be incorporated into future updates and not linked in users' minds with the introduction of V2 hardware.

**Comment by microbit-katie** [comment]
I agree with @pelikhan to show the invisible state - by showing the group ID. 

Can we do this with a 'radio set group' block that automatically appears in an 'on start' loop of the scripting area? 

It will default set the radio group, but allow the learner to change it if they wish.  @Jaqster @abchatra

**Comment by microbit-mark** [comment]
Setting the radio group was also discussed back in https://github.com/microsoft/pxt-microbit/issues/2017 and closed as we decided not to break compatibility at the time and discuss for the next release. Can we set the hash so it works between board variants for now as a workaround and then look to introduce a default radio group for the 2021 MakeCode release?

Here's an example in the wild of someone testing radio between board variants, who either debugged and found the workaround or was already setting the group in their program https://twitter.com/sw_education/status/1318111398690316288

**Comment by microbit-mark** [comment]
@abchatra @Jaqster is this one being discussed for the upcoming release?

**Comment by abchatra** [comment]
We made a change to set the default group to zero and there have been no complaints over 9 months now. Closing.
