### ISSUE TITLE
webUSB inconsistent/fails frequently 

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#3422]
**Describe the bug**

When using /stable, webUSB connections can be made, but they aren't reliable for me.

I've seen one or two partial flashes, but frequently MakeCode spends a long time blink the LED, then stops and gives a Download instead.

Sometimes the first change after doing a DnD program of the board works with partial flashing.

This seems to be associated with a high number of "bad response -> N" error messages, some of them visible in a red lozenge

The behaviour I see when it fails

LED starts flashing, after a few seconds, the 'downloading' face appears (fullscreen)
<img width="685" alt="image" src="https://user-images.githubusercontent.com/147113/92536727-4fd70680-f232-11ea-94d5-6136e399bfc2.png">
Then after another 20s or so, the blue downloading face disappears, but the LED keeps flashing
Blue 'downloading' face reappears, stays for around another 20s (led keeps blinking)
MakeCode starts a file download and the download dialogue appears
<img width="714" alt="image" src="https://user-images.githubusercontent.com/147113/92536643-17cfc380-f232-11ea-80e1-2e85f440ee0b.png">

**To Reproduce**

I don't know how to trigger the failure, but once it's started failing it is quite repeatable. It doesn't seem to need any v2 only extensions to trigger, though in the screencap below I'm using that.

Use webUSB with Chrome on a V1.4x board. It doesn't always happen. Seems to work for a long time once it's working properly.

**Expected behavior**

**Screenshots**
the orange LED is flashing on my device all the time through this screen capture until the 'download' dialogue pops up

![webusb unreliability](https://user-images.githubusercontent.com/147113/92537104-3a161100-f233-11ea-9ba7-cb392553b058.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 85

**Comment by abchatra** [comment]
Lot more details in the original issue. https://github.com/microsoft/pxt-microbit/issues/3422

**Comment by jaustin** [comment]
@mmoskal is it relevant that baords are now 9904 not 9903?

**Comment by mmoskal** [comment]
test is
```
                this.binName = (r[2] == 57 && r[3] == 57 && r[5] >= 51 ? "mbcodal-" : "") + pxtc.BINARY_HEX
```
so should be fine

**Comment by martinwork** [comment]
@jaustin @mmoskal Will universal hexes be changing to specify 9904 for v2? The iOS app is assuming 9903.

**Comment by mmoskal** [comment]
I didn't plan to touch it

**Comment by jaustin** [comment]
Using 9903 in the hex for v2 is correct. 9903 means "V2-like" and 9904 is a V2. @carlosperate will have some better language than that, but this is the idea.

**Comment by abchatra** [comment]
Fixed.
