### ISSUE TITLE
Implement simulator support for v2 features

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#3424]
- [x] Microphone
- [x] Logo touch
- [x] V2 edge connector
- [x] Possible v2 somewhere in the simulator.

**Comment by abchatra** [comment]
@pelikhan @riknoll

**Comment by abchatra** [comment]
@pelikhan let me know if you want someone else to do this.

**Comment by pelikhan** [comment]
This item should be broken down into separate features. Happy to mentor whoever wants to take on these tasks.

________________________________

**Comment by pelikhan** [comment]
There is already a "microphone" project in the pxt-microbit that just needs to be wired up with CODAL. @jwunderl  It uses our existing microphone blocks.

**Comment by pelikhan** [comment]
Mostly done. Details tracked in other bugs.
