### ISSUE TITLE
Capacative pin touch stops working randomly on P0 and P2

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3444]
Originally reported by @whaleygeek in https://github.com/microbit-foundation/microbit-issues/issues/21 this still reproduces.

## Bug Description

P0 and P2 pin touch sensing stops working

## How To Reproduce

run the attached hex file.
At the start screen (7 dots) touch 0 1 2 and logo, and you see they respond using the registered handlers.

Press A+B to start the game, it will now only accept you pressing 1 or logo, 0 and 2 are ignored.
The only way to recover these event handlers is ti power cycle or reset.

I have tried re-registering the captouch on game start but it makes no difference.

## Expected behaviour

P0 P1 P2 event handlers once registered should always work

## Environment

latest makecode stable
makecode.microbit.org version:  3.0.27
Microsoft MakeCode version:  6.0.24
microbit runtime version:  v2.2.0-rc6
[microbit-copybit14.hex(2).zip](https://github.com/microsoft/pxt-microbit/files/5385152/microbit-copybit14.hex.2.zip)

Also for reference is the typical touch-test program, which of course works, because nothing else happens in the program
[microbit-touch.hex.zip](https://github.com/microsoft/pxt-microbit/files/5385154/microbit-touch.hex.zip)

**Comment by abchatra** [comment]
@microbit-mark is this specific to MakeCode or the issue reproduces in python as well? If it reproduces in both, then probably this should go to CODAL repo.

**Comment by abchatra** [comment]
@jaustin @microbit-mark can you retry using new extension?

**Comment by pelikhan** [comment]
We've also pulled in the latest codal so worth retrying.

**Comment by pelikhan** [comment]
The current CODAL always starts the audio engine on pin P0 "silently" and eagerly.

**Comment by pelikhan** [comment]
is this a v1 or v2 issue? Is it possible reduce the size of the repro?

**Comment by pelikhan** [comment]
@microbit-mark  please provide a smaller repro. I don't understand what this is supposed to do.

**Comment by microbit-mark** [comment]
@whaleygeek do you have a smaller reproduce for this and does it still exhibit the issue?
