### ISSUE TITLE
MIDI blocks not supported with micro:bit v2

### ISSUE THREAD

**Issue by Mowgliart** [microsoft/pxt-microbit#3448]
Code created using the MIDI blocks which works on micro:bit version 1 gives error 841 with micro:bit version 2.

**To Reproduce**
Set a micro:bit to send any input to a second  microbit. Set the second microbit to convert the received signal to MIDI using MIDI use raw serial.

**Expected behavior**
It works as with version one of the microbit, MIDI is sent out of the microbit.

**What Happens**
the microbit converting to MIDI displays error 841

**Desktop (please complete the following information):**
microbit v2 with firmware 0254

**Comment by pelikhan** [comment]
This seems to be related to serial more than MIDI. @jaustin

**Comment by pelikhan** [comment]
@Mowgliart please try again using https://makecode.microbit.org/v3.1 . We have applied a couple fixes to the serial layer.

**Comment by pelikhan** [comment]
Please try again with the latest beta.
