### ISSUE TITLE
First light sensor reading is always duff

### ISSUE THREAD

**Issue by whaleygeek** [microsoft/pxt-microbit#3451]
**Describe the bug**
The first light sensor reading always seems to return 255

**To Reproduce**
Load file measure-fails.hex. Observe that the 'M' dims a little bit after a fraction of a second (this is the light sensing starting on-demand). Press B to read the max reading - it is always 255.

**Expected behaviour**
Load file measure-works.hex - this has a 100ms delay after the first reading and the first reading is junked. Press B to read the max reading - it is correctly the current maximum reading. (P.S. Don't try this if you are currently flying past the sun in a spacecraft, or sitting on a sun bed.)

**Additional context**
makecode.microbit.org version:  3.0.17
Microsoft MakeCode version:  6.0.18
microbit runtime version:  v2.2.0-rc6

[measure-fails.hex.zip](https://github.com/microsoft/pxt-microbit/files/5409638/measure-fails.hex.zip)
[measure-works.hex.zip](https://github.com/microsoft/pxt-microbit/files/5409639/measure-works.hex.zip)

Also paging @finneyj and @jaustin in case this is actually a DAL bug.

**Comment by microbit-mark** [comment]
This was raised on the DAL in https://github.com/lancaster-university/microbit-dal/issues/426

**Comment by abchatra** [comment]
Dal issue.
