### ISSUE TITLE
radio.writeReceivedPacketToSerial() block missing from categories

### ISSUE THREAD

**Issue by RRWagner** [microsoft/pxt-microbit#3452]
On this page, scrolling down to where it says, "Extended data recording",

https://makecode.microbit.org/device/data-analysis/remote

it shows the block for radio.writeReceivedPacketToSerial()

![image](https://user-images.githubusercontent.com/2395551/96615779-964e6500-12b6-11eb-8ef8-10fee82aeb3f.png)

However, in the radio category of the MakeCode editor, this block cannot be found.

If you click on the edit icon, it opens a MakeCode program with the block, but the block is still not in the categories list.

**Comment by abchatra** [comment]
This block is deprecated. We need to remove it from the documentation.

**Comment by RRWagner** [comment]
Is there a work-around for the functionality?

**Comment by abchatra** [comment]
You can just use serial category blocks to write to serial

![image](https://user-images.githubusercontent.com/6107272/96758416-9d937280-138b-11eb-9676-50e0a94938bd.png)

**Comment by abchatra** [comment]
@ganicke can we remove the deprecated API from the documentation.

**Comment by ganicke** [comment]
Sure thing. I'll take that out.
