### ISSUE TITLE
Asynchronous binary UART in background (NovaFitness SDS011)

### ISSUE THREAD

**Issue by irukard** [microsoft/pxt-microbit#3453]
Hi!

I'm not sure this report belongs to pxt-microbit. Maybe problem lay even deeper in core. Please advise.

I'm working on extension for makecode. I want to read binary serial data from NovaFitness SDS011 air quality sensor. Protocol is very simple, 10 bytes of data incoming every second. Datagram looks like this:

```
Header: AA C0
PM 2.5 value: XX XX
PM 10 value: XX XX
ID: XX XX
Checksum XX
Tail: AB
```

I managed to read the data using serial.readBuffer(10).

```
        sdsbuffer = serial.readBuffer(10)
        // check if frame starts with 0xAA 0xC0 and ends with 0xAB
        if (sdsbuffer.getNumber(NumberFormat.UInt8LE, 0) == 170
            && sdsbuffer.getNumber(NumberFormat.UInt8LE, 1) == 192
            && sdsbuffer.getNumber(NumberFormat.UInt8LE, 9) == 171) {

            pm25 = sdsbuffer.getNumber(NumberFormat.UInt16LE, 2) / 10
            pm10 = sdsbuffer.getNumber(NumberFormat.UInt16LE, 4) / 10
        }
```

But I encountered strange behavior. When I place block in main loop, everything works ok. Downside is that I have to wait for readBuffer to grab 10 bytes (which is done once per second, due to SDS011 data sending intervals). But when I place  readBuffer function in the background communication with micro:bit dies. Often shows 983 error code. 

Extension code: https://github.com/irukard/makecode-sds011/tree/d2607ea9d09d22ad1fc3d66a09c04825a346a156

It would be better to wait for any data on serial, like in micropythons uart.any(), and than read it byte by byte. That would be non blocking way, but I don't see that option in javascript.

I also tried to use serial.onDataReceived(serial.delimiters(0xAA), function () {}) but it doesn't work very well, strange things happen when 0xAA value is part of datagram. 

In current state (https://github.com/irukard/makecode-sds011/blob/8ca4a8eef51bad06233bf56a7732f290b51b40e6/sds011.ts) I made a "service" to read data in background. It uses infamous onDataReceived(serial.delimiters(0xAA). Code is very unstable. micro:bit hangs after 20-250 seconds. Very often without any visible error. Usually it reboots itself, however sometimes even reset button doesn't work. 

Code: https://makecode.microbit.org/_FCbgYge0wcM5
Required hardware:
- NovaFitness SDS011 connected via UART (P0, P1)
- 2004 LCD display with I2C converter (PCF8574)

I would really appreciate help with reading those 10 bytes in non-blocking micro:bit friendly way.

**Comment by abchatra** [comment]
@pelikhan any workaround here?

**Comment by pelikhan** [comment]
@irukard I've made a change so that you can pass 0 to readBuffer and it will read the buffered data without blocking. (see PR above). It will be testable in beta soon.

**Comment by pelikhan** [comment]
We fixed a GC bug in the read buffer function which explains 983 error. The fix will be avilable in /beta soonish along with using 0 as a length.

**Comment by pelikhan** [comment]
You can test the fix in https://makecode.microbit.org/v3.1#

**Comment by irukard** [comment]
Thank you! I will test that ASAP and let you know how stable it is.

**Comment by abchatra** [comment]
fixed
