### ISSUE TITLE
Now we have a touch icon the yellow fringe is a bit confusing

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#3467]
With the new simulator support for the touchable face (🎉) the yellow fringe colour becomes a bit confusing because it isn't clear that the fringe and the logo are different.

Very clear 
<img width="387" alt="image" src="https://user-images.githubusercontent.com/147113/96903054-3a8a0480-148d-11eb-80ef-4e7b9ba436b6.png">

Less clear
<img width="383" alt="image" src="https://user-images.githubusercontent.com/147113/96903031-32ca6000-148d-11eb-8d75-dc8d19b59218.png">

One small incremental step would be to not show a yellow V2 device ever. Another would be to differentiate the touchable logo from the yellow somehow, but that's trickier to do. Even in the SVG it's not that clear

<img width="423" alt="image" src="https://user-images.githubusercontent.com/147113/96903206-7755fb80-148d-11eb-9203-466695dca3d2.png">

The most dramatic option is to never show a yellow micro:bit in the simulator. Seems a shame though

**Comment by pelikhan** [comment]
https://github.com/microsoft/pxt-microbit/pull/3468
