### ISSUE TITLE
Hint not complete in "Multi Editors"

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3471]
**Describe the bug**
Hint not complete in "**Multi Editors**"

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Radio Games----->Multi Editors---->Show Instructions
3.Edit two radio programs side-by-side
4.Mouse over **bottom left corner . . .**  and observe the hint 

**Actual behavior**
![1](https://user-images.githubusercontent.com/59192069/96964639-66fd5980-153d-11eb-89ae-6c83550389f6.gif)
Hint not complete in "**Multi Editors**"
![image](https://user-images.githubusercontent.com/59192069/96965117-336eff00-153e-11eb-8004-6f8fdf871603.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.0.28
3.Microsoft MakeCode version: 6.0.24

**Comment by abchatra** [comment]
Won't fix.
