### ISSUE TITLE
Only one microbit shown when running radio program in "Multi Editors"

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3472]
**Describe the bug**
Only **one microbit** shown when running radio program in "**Multi Editors**"

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Radio Games----->Multi Editors---->Show Instructions
3.Edit two radio programs side-by-side
4.Run the radio program

**Expect behavior**
There shows **two microbit** when clicking **"SHAKE"**

**Actual behavior**
Only **one microbit** shown when running radio program in "**Multi Editors**"
![2](https://user-images.githubusercontent.com/59192069/96966095-cceae080-153f-11eb-8086-deff92ccfeda.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.0.28
3.Microsoft MakeCode version: 6.0.24

**Comment by pelikhan** [comment]
This is by design. WHen using multi-editor, only 1 mbit shows on each side.

**Comment by abchatra** [comment]
The microbit in each window communicate with each other.
