### ISSUE TITLE
Python/JS: Sim has a splash screen when running radio program

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3473]
**Describe the bug**
**Python/JS**: Sim has a splash screen when running **radio program**

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Tutorials----->Micro Chat---->Start Tutorial
3.Run the radio program in Block/Python/JS editor

**Actual behavior**
**Python/JS**: Sim has a splash screen when running **radio program**
![4](https://user-images.githubusercontent.com/59192069/96972083-9f566500-1548-11eb-9e46-c3eac7e9cd24.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.0.28
3.Microsoft MakeCode version: 6.0.24

**Comment by pelikhan** [comment]
There is an intermediate state where we have a scrollbar then none.

**Comment by abchatra** [comment]
Fixed
