### ISSUE TITLE
Prevent image variable from being sent over radio, as it can't be read on the receiving end

### ISSUE THREAD

**Issue by kristianpedersen** [microsoft/pxt-microbit#3474]
Yesterday, two students wanted to send images over radio. 

Radio messages have a limit of 18 characters, right? I don't see how this would be achieved without multiple calls and a relatively elaborate setup.

![microbit-screenshot](https://user-images.githubusercontent.com/5204369/96975461-c138f300-151a-11eb-8745-28c5414de464.png)

**Comment by pelikhan** [comment]
You could encode 1 bit per LED into a number and send it over. A bit more tricky for sure.

________________________________
