### ISSUE TITLE
Has UART changed with Micro:bit v2?

### ISSUE THREAD

**Issue by ryanteck** [microsoft/pxt-microbit#3481]
**Describe the bug**
With one of our Add-on boards we are noticing that the serial library is having issues where as the same code on V2 does not work.

I'm still trying to diagnose, but it's potentially an issue with readLine or writeString as our code sends a string then processes the response (https://github.com/PiSupply/pxt-iot-lora-node/blob/master/main.ts#L419 and https://github.com/PiSupply/pxt-iot-lora-node/blob/master/main.ts#L168 is roughly where it's hanging).

**Expected behavior**
The code should work as it does on V2, as to where the writing and reading of lines works fully.

**micro:bit version (please complete the following information):**

V2

**Desktop (please complete the following information):**
Doesn't matter, reproducable on multiple.

**Additional context**
Initially seeking to know if this code has changed to then further figureout where to diagnose.

**Comment by abchatra** [comment]
@jaustin who is looking at extensions.

**Comment by pelikhan** [comment]
@ryanteck we are seeing a few issues with serial. Please try the latest build https://makecode.microbit.org/beta which has some of the fixes.

**Comment by ryanteck** [comment]
Hi @pelikhan ,

I've tried the Beta and 3.1 editors but still seem to be experiencing it. It does seem to after writing a string that the read directly after fails.

I've also tested the same hex on a V1 and it works fine.

**Comment by pelikhan** [comment]
We pushed a fix for serial in v3.0.38. Please try again.

**Comment by ryanteck** [comment]
Thanks @pelikhan , I'll give it a try shortly.

**Comment by pelikhan** [comment]
It seems that serial was fixed in other instances. Please reopen if this issue persists.

**Comment by ryanteck** [comment]
Hi @pelikhan ,

I'm not seeing any difference on mine. I've tried with /beta, /v3.0 and /v3.1

The same hex & add-on works on my V1 still so no other changes. (Generated from the v3.0)

**Comment by finneyj** [comment]
Recent on-demand activation of the audio pipeline caused some interrupt priorities to be flipped in the underlying CODAL later... This was causing dropped/delayed RX characters on some occasions.

I've fixed this and added some performance/stability improvements to the serial code - now in master of codal-nrf52.

These changes will be in the v0.2.17 release - to be tagged shortly.

**Comment by ryanteck** [comment]
Hi @finneyj , thanks for looking into it. I'll test it when it's pushed.

Thanks

**Comment by finneyj** [comment]
Great - thanks @ryanteck. Let me know if fit helps!

**Comment by ryanteck** [comment]
I'm not sure if it's been pushed. But it seems to be working using the v3.1 editor! I'll double check to confirm it but think it looks right!

Thank you for all the help.

**Comment by finneyj** [comment]
yep - v3.1 will include the updates. Thanks for confirming!

**Comment by ryanteck** [comment]
It seems that UART reads are working right now but possibly an issue with UART writes. 

My code works through the system as if it's working and reading responses back to the commands fine. But not fully working which I suspect is a write issue. I'll try and get my UART adaptor out and probe the signal.

**Comment by abchatra** [comment]
This is fixed. @ryanteck I will reopen if this not fixed for you.

**Comment by finneyj** [comment]
no more changes @ryanteck.

Could you confirm if you think that there is a problem with send(), and if so try to describe the issue you're seeing?

**Comment by ryanteck** [comment]
Sorry about the delay, I'm back to working on this issue so here's a rough overview:

Essentially our library works perfectly fine on a V1 microbit with send and receive working as expected.

However on V2 it doesn't seem to work, it runs through the stages as we expect but it doesn't seem to communicate with our add-on in the same way. I'm working on debugging it today to try and see if I can find a more specific issue to describe.

**Comment by ryanteck** [comment]
I'm going to close this issue and re-open it as a new one with a more detailed description now I've found the issue.
