### ISSUE TITLE
Beta: Bluetooth extension does not work with V2 revision

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3482]
**Describe the bug**
Using a BLE service within a program causes a 927 error when compiled and used on the device

**To Reproduce**
1. Go to makecode.microbit.org/beta
2. Add BLE extension
3. Add BLE service to program
4. Flash to device
5. See Error 927

**Expected behaviour**
Extension should work on all board revisions

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**micro:bit version (please complete the following information):**
1.47.2

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jaustin** [comment]
This should be fixed by https://github.com/microsoft/pxt-microbit/pull/3455 - @abchatra any idea when that will make it to /beta?

**Comment by pelikhan** [comment]
Please test against https://makecode.microbit.org/v3.1
