### ISSUE TITLE
V2 output pin not working as expected

### ISSUE THREAD

**Issue by DaveAtKitronik** [microsoft/pxt-microbit#3483]
The inventors Kit uses various external circuits driven be the code in the micro:bit. Experiment 3 reads an analog and writes it back to drive an LED. THe LED is switched on and off by touching Pin 0.
The code is:

```
let light_state = 0
input.onPinPressed(TouchPin.P0, function () {
    if (light_state == 0) {
        light_state = 1
    } else {
        light_state = 0
    }
})

basic.forever(function () {
    if (light_state == 1) {
        pins.analogWritePin(AnalogPin.P2, pins.analogReadPin(AnalogPin.P1))
    } else {
        pins.digitalWritePin(DigitalPin.P2, 0)
    }
})
```
This functions as expected on a V1.5 micro:bit - the pin turns on and off the LED, and a pot attached to P1 controls the output of P2 and the LED brightness.
On a V2 micro:bit the first touch turns on the LED, but the LED remains on. 

Modifying the code to display 1 or 0 on the display:
```
let light_state = 0
input.onPinPressed(TouchPin.P0, function () {
    if (light_state == 0) {
        light_state = 1
    } else {
        light_state = 0
    }
})

basic.forever(function () {
    if (light_state == 1) {
        basic.showNumber(1)
        pins.analogWritePin(AnalogPin.P2, pins.analogReadPin(AnalogPin.P1))
    } else {
        basic.showNumber(0)
        pins.digitalWritePin(DigitalPin.P2, 0)
    }
})
```
shows that the input is still being read, but the output is not functioning as expected.

adding 

```
input.onButtonPressed(Button.A, function () {
    basic.showNumber(pins.analogReadPin(AnalogPin.P1))
})
```
Shows that the input is being read, and observing the LED the brightness changes when the display is showing 1, but not when showing 0.
Changing the pins.digitalWritePin(DigitalPin.P2, 0) to pins.analogWritePin(AnalogPin.P2, 0) results in the LED extinguishing as expected.

Looks like the mode change on the pins to digital no longer works as it used to

tested on Chrome, on /beta editor without any additional V2 extensions loaded. Don't think its browser related.

**Comment by pelikhan** [comment]
@jwunderl could be related to the servo issue.

**Comment by pelikhan** [comment]
@DaveAtKitronik please try again. There was a bug in the PWM layer that might have fixed this.

**Comment by DaveAtKitronik** [comment]
still broken in /beta 
![image](https://user-images.githubusercontent.com/25896029/97273900-d029e900-182b-11eb-8625-6bc7baacac1f.png)
using this code:
let light_state = 0
input.onPinPressed(TouchPin.P0, function () {
    if (light_state == 0) {
        light_state = 1
    } else {
        light_state = 0
    }
})

basic.forever(function () {
    if (light_state == 1) {
        basic.showNumber(1)
        pins.analogWritePin(AnalogPin.P2, pins.analogReadPin(AnalogPin.P1))
    } else {
        basic.showNumber(0)
        pins.digitalWritePin(DigitalPin.P2, 0)
    }
})

**Comment by pelikhan** [comment]
Please try again on https://makecode.microbit.org/v3.1

**Comment by abchatra** [comment]
/beta updated today. Sorry for the delay. Please try again in /beta.

**Comment by DaveAtKitronik** [comment]
still not working on /beta 
![image](https://user-images.githubusercontent.com/25896029/97450861-11ed8900-192b-11eb-991f-ac222bddb75c.png)

**Comment by pelikhan** [comment]
This is a short repro:
```
while(true) {
    led.toggle(0,0)
    pins.analogWritePin(AnalogPin.P2, 1023)
    basic.pause(500)
    led.toggle(1,0)
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.pause(500)
}
```
and the scope readings:
![image](https://user-images.githubusercontent.com/4175913/97676746-5160c600-1a4e-11eb-8104-13b6feb3accb.png)

**Comment by finneyj** [comment]
Rogue flag on NRF52Pin causing this CODAL side:
https://github.com/lancaster-university/codal-nrf52/commit/dff67e066e039358001ceafe406cc4dd902363c8

Will be fixed in v0.2.14

**Comment by abchatra** [comment]
Fixed. Please verify @DaveAtKitronik

**Comment by DaveAtKitronik** [comment]
fixed.

**Comment by abchatra** [comment]
Thanks for testing @DaveAtKitronik
