### ISSUE TITLE
Simplify 'on logo pressed' and released blocks

### ISSUE THREAD

**Issue by microbit-giles** [microsoft/pxt-microbit#3485]
**Is your feature request related to a problem? Please describe.**
The following project highlights a problem with the way we have currently implemented 'on logo pressed' and 'on logo released'. 
I would expect the surprised face to show while your finger is on the logo, and then when you let go it should leave a happy face on the display. In fact, usually it works the other way round:
![image](https://user-images.githubusercontent.com/42380137/97206914-43424980-17b1-11eb-8d73-477f5aa37b86.png)

**Describe the solution you'd like**
I think the various behaviours would be clearer if we had one 'on logo...' block with a dropdown and a default value of 'pressed':
On logo <pressed, touched, released, long pressed>

**Describe alternatives you've considered**
A single 'on logo touched' block and then more blocks to expose the other behaviours, but @jaustin and I like the idea of just one block with the simplest behaviour as the default.

**Comment by pelikhan** [comment]
Fixed in 3.1.15
