### ISSUE TITLE
Klip motor driver can only control motors once on a V2 using /beta editor.

### ISSUE THREAD

**Issue by DaveAtKitronik** [microsoft/pxt-microbit#3492]
Klip motor driver can only control motors once on a V2 using /beta editor.
![image](https://user-images.githubusercontent.com/25896029/97293027-f5c2ec80-1843-11eb-8631-e17dec9efdf5.png)

To remove the potential of a mistake in the package I have coded the equivalent code in 'base' blocks.
When turned on button A or button B will successfully start the motors running.
Button A+B has no effect - it does not stop the motors.
If Button A was pressed then pressing button B stops the motors.
They cannot be restarted without a power cycle.
The same download on a V1.5 micro:bit functions as expected.
Replacing the analogWritePin with equivalent digitalWritePin performs as expected.

```
input.onButtonPressed(Button.A, function () {
    basic.showIcon(IconNames.Rollerskate)
    pins.analogWritePin(AnalogPin.P13, 1023)
    pins.digitalWritePin(DigitalPin.P14, 0)
    pins.analogWritePin(AnalogPin.P16, 1023)
    pins.digitalWritePin(DigitalPin.P15, 0)
    // kitronik_klip_motor.motorOn(kitronik_klip_motor.Motors.Motor1, kitronik_klip_motor.MotorDirection.Reverse, 100)
    // kitronik_klip_motor.motorOn(kitronik_klip_motor.Motors.Motor2, kitronik_klip_motor.MotorDirection.Reverse, 99)
    basic.showIcon(IconNames.Happy)
})
input.onButtonPressed(Button.AB, function () {
    basic.showIcon(IconNames.No)
    pins.digitalWritePin(DigitalPin.P13, 0)
    pins.digitalWritePin(DigitalPin.P15, 0)
    pins.digitalWritePin(DigitalPin.P14, 0)
    pins.digitalWritePin(DigitalPin.P16, 0)
    // kitronik_klip_motor.motorOff(kitronik_klip_motor.Motors.Motor1)
    // kitronik_klip_motor.motorOff(kitronik_klip_motor.Motors.Motor2)
    basic.showIcon(IconNames.Skull)
})
input.onButtonPressed(Button.B, function () {
    basic.showIcon(IconNames.Rollerskate)
    pins.analogWritePin(AnalogPin.P14, 1023)
    pins.digitalWritePin(DigitalPin.P13, 0)
    pins.analogWritePin(AnalogPin.P15, 1023)
    pins.digitalWritePin(DigitalPin.P16, 0)
    // kitronik_klip_motor.motorOn(kitronik_klip_motor.Motors.Motor1, kitronik_klip_motor.MotorDirection.Reverse, 100)
    // kitronik_klip_motor.motorOn(kitronik_klip_motor.Motors.Motor2, kitronik_klip_motor.MotorDirection.Reverse, 99)
    basic.showIcon(IconNames.Happy)
})
basic.showIcon(IconNames.Tortoise)
```

This feels related to https://github.com/microsoft/pxt-microbit/issues/3483

**Comment by pelikhan** [comment]
Please try again on https://makecode.microbit.org/v3.1

**Comment by abchatra** [comment]
@jaustin

**Comment by DaveAtKitronik** [comment]
still broken using above code and this version:

![image](https://user-images.githubusercontent.com/25896029/97457514-bb377d80-1931-11eb-8b53-af0f439b3f4b.png)

**Comment by pelikhan** [comment]
Looks like a dup of https://github.com/microsoft/pxt-microbit/issues/3483

**Comment by abchatra** [comment]
Fixed. Please verify @DaveAtKitronik

**Comment by DaveAtKitronik** [comment]
Fixed in original test case and with the Klip motor blocks.

**Comment by abchatra** [comment]
Thanks for testing @DaveAtKitronik
