### ISSUE TITLE
On Screen Keyboard issues

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#3496]
This bug was reported by the Irish Microsoft DreamSpace Team.
They are using the Surface Hub 2 with new Edge and when clicking into a text field, the on-screen keyboard is not popping up.

I was able to reproduce a similar issue on my Surface Pro where the on-screen keyboard flashes momentarily and then disappears.

**Comment by pelikhan** [comment]
Does it repro in newer editors like Arcade?

**Comment by Jaqster** [comment]
Yes, it repros for me in Arcade too

**Comment by abchatra** [comment]
fixed in live
