### ISSUE TITLE
P0 has a 44khz PWM signal

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3497]
Audio stack is starting eagerly and taking over P0. Requires CODAL fix.

**Comment by finneyj** [comment]
Fixed in master of codal-microbit-v2 master:https://github.com/lancaster-university/codal-microbit-v2/commit/b542665d3b51dd8b030405a2be6319b622a24137

Bug due to audio pipeline being brought up at initialization - now on demand activation.

tag to follow soon pending a few other bugfixes.

**Comment by AlasdairAtKitronik** [comment]
This is causing issues for products with Neopixels connected on Pin0 - just setting them to white all the time, no control over them whatsoever.

**Comment by finneyj** [comment]
thanks @AlasdairAtKitronik.

Already fixed in master branch. The fix will propagate through shortly.

**Comment by finneyj** [comment]
Should be fixed in v0.2.13

**Comment by pelikhan** [comment]
Fixed in v3.0.38
