### ISSUE TITLE
WAV files to play new sounds in simulator.

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3498]
Need recordings of each sound as a wav file.

**Comment by pelikhan** [comment]
@jaustin

**Comment by jaustin** [comment]
[sounds.zip](https://github.com/microsoft/pxt-microbit/files/5460812/sounds.zip)
Here are all the sounds as wav files. I can convert them to any format sox supports if you'd prefer.

**Comment by pelikhan** [comment]
giggle missing

**Comment by jaustin** [comment]
Whoops, sorry.
[allsounds2.zip](https://github.com/microsoft/pxt-microbit/files/5461607/allsounds2.zip)

**Comment by pelikhan** [comment]
Added in v3.0.39
