### ISSUE TITLE
serial write is very slow on microbit V2

### ISSUE THREAD

**Issue by CaptainCredible** [microsoft/pxt-microbit#3500]
Sending serial data over USB (not tested sending serial on a pin yet) is about 10x slower on the microbit v2

using this editor:
https://makecode.microbit.org/beta#editor 

with this code:
```
let oldTime = 0
let newTime = 0
let diff = 0
serial.setBaudRate(BaudRate.BaudRate115200)
while(true){
    oldTime = newTime
    newTime = input.runningTime()
    diff = newTime - oldTime
    serial.writeValue("time to send = ", diff)
    led.toggleAll()
}
```
yields "time to send = 5ms" on old hardware and "time to send =  56ms" on new v2 hardware

**Comment by pelikhan** [comment]
Can you try again with v3.0.38 ?

**Comment by CaptainCredible** [comment]
Nice! I am now consistantly getting 3ms between iterations of the while(true)
