### ISSUE TITLE
New v2 blocks in Music toolbox in Monaco has errors

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#3501]
**To Reproduce**
1. Go to 'Typescript'
2. Drag new v2 Music blocks into the workspace
3. See errors

**Expected behavior**
"this" parameter doesn't make sense in the blocks and dragging them to the workspace produces errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/6107272/97396088-9d233c00-18a3-11eb-9b95-2341c734e83d.png)
![image](https://user-images.githubusercontent.com/6107272/97396103-a57b7700-18a3-11eb-9dd4-7f7ca3e3a322.png)

**Comment by jwunderl** [comment]
Looks like we need to port https://github.com/microsoft/pxt/pull/7286 for this

**Comment by abchatra** [comment]
Lets port just the change and ensure it doesn't break other scenarios. If it does lets take case by case basis.

**Comment by abchatra** [comment]
fixed
