### ISSUE TITLE
State of the Extension world

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3506]
See the documentation on how to fix in https://support.microbit.org/en/support/solutions/articles/19000121371-makecode-extension-compatibility-v1-and-v2

- [ ] error:  [tinkertanker/pxt-iot-environment-kit](https://github.com/tinkertanker/pxt-iot-environment-kit) build error / [new issue](https://github.com/tinkertanker/pxt-iot-environment-kit/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Ftinkertanker%2Fpxt-iot-environment-kit%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [microsoft/pxt-bluetooth-midi](https://github.com/microsoft/pxt-bluetooth-midi) build error / [new issue](https://github.com/microsoft/pxt-bluetooth-midi/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Fmicrosoft%2Fpxt-bluetooth-midi%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [laboratoryforplayfulcomputation/pxt-blockytalkyble](https://github.com/laboratoryforplayfulcomputation/pxt-blockytalkyble) build error / [new issue](https://github.com/laboratoryforplayfulcomputation/pxt-blockytalkyble/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Flaboratoryforplayfulcomputation%2Fpxt-blockytalkyble%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [microsoft/pxt-bluetooth-temperature-sensor](https://github.com/microsoft/pxt-bluetooth-temperature-sensor) build error / [new issue](https://github.com/microsoft/pxt-bluetooth-temperature-sensor/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Fmicrosoft%2Fpxt-bluetooth-temperature-sensor%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [minodekit/pxt-minode](https://github.com/minodekit/pxt-minode) build error / [new issue](https://github.com/minodekit/pxt-minode/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Fminodekit%2Fpxt-minode%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [sparkfun/pxt-gamer-bit](https://github.com/sparkfun/pxt-gamer-bit) build error / [new issue](https://github.com/sparkfun/pxt-gamer-bit/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Fsparkfun%2Fpxt-gamer-bit%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [microsoft/pxt-bluetooth-max6675](https://github.com/microsoft/pxt-bluetooth-max6675) build error / [new issue](https://github.com/microsoft/pxt-bluetooth-max6675/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Fmicrosoft%2Fpxt-bluetooth-max6675%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [pimoroni/pxt-scrollbit](https://github.com/pimoroni/pxt-scrollbit) build error / [new issue](https://github.com/pimoroni/pxt-scrollbit/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Fpimoroni%2Fpxt-scrollbit%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [pauldfoster/pxt-microbit-gy521](https://github.com/pauldfoster/pxt-microbit-gy521) build error / [new issue](https://github.com/pauldfoster/pxt-microbit-gy521/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Fpauldfoster%2Fpxt-microbit-gy521%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [pizayanz/pxt-linebeacon](https://github.com/pizayanz/pxt-linebeacon) build error / [new issue](https://github.com/pizayanz/pxt-linebeacon/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Fpizayanz%2Fpxt-linebeacon%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [sparkfun/pxt-gator-environment](https://github.com/sparkfun/pxt-gator-environment) build error / [new issue](https://github.com/sparkfun/pxt-gator-environment/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Fsparkfun%2Fpxt-gator-environment%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [muselab/pxt-wifi-shield](https://github.com/muselab/pxt-wifi-shield) build error / [new issue](https://github.com/muselab/pxt-wifi-shield/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Fmuselab%2Fpxt-wifi-shield%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [tinkertanker/pxt-alphanumeric-ht16k33](https://github.com/tinkertanker/pxt-alphanumeric-ht16k33) build error / [new issue](https://github.com/tinkertanker/pxt-alphanumeric-ht16k33/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Ftinkertanker%2Fpxt-alphanumeric-ht16k33%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [tinkertanker/microdriver_sht2x](https://github.com/tinkertanker/microdriver_sht2x) build error / [new issue](https://github.com/tinkertanker/microdriver_sht2x/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Ftinkertanker%2Fmicrodriver_sht2x%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [alsrobot-microbit-makecode-packages/cruisebit](https://github.com/alsrobot-microbit-makecode-packages/cruisebit) build error / [new issue](https://github.com/alsrobot-microbit-makecode-packages/cruisebit/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Falsrobot-microbit-makecode-packages%2Fcruisebit%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [tinkertanker/udriver_pca9585](https://github.com/tinkertanker/udriver_pca9585) build error / [new issue](https://github.com/tinkertanker/udriver_pca9585/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Ftinkertanker%2Fudriver_pca9585%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [dfrobot/pxt-dfrobot-naturalscience](https://github.com/dfrobot/pxt-dfrobot-naturalscience) build error / [new issue](https://github.com/dfrobot/pxt-dfrobot-naturalscience/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Fdfrobot%2Fpxt-dfrobot-naturalscience%3B%20pxt%20build%20--ignoreTests)
- [x] error:  [kitronikltd/pxt-kitronik-zip-tile](https://github.com/kitronikltd/pxt-kitronik-zip-tile) build error / [new issue](https://github.com/kitronikltd/pxt-kitronik-zip-tile/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Fkitronikltd%2Fpxt-kitronik-zip-tile%3B%20pxt%20build%20--ignoreTests)
- [x] error:  [4tronix/bitcommander](https://github.com/4tronix/bitcommander) build error / [new issue](https://github.com/4tronix/bitcommander/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2F4tronix%2Fbitcommander%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [tinkertanker/pxt-rotary-encoder-ky040](https://github.com/tinkertanker/pxt-rotary-encoder-ky040) build error / [new issue](https://github.com/tinkertanker/pxt-rotary-encoder-ky040/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Ftinkertanker%2Fpxt-rotary-encoder-ky040%3B%20pxt%20build%20--ignoreTests)
- [x] error:  [KitronikLtd/pxt-kitronik-zip-64](https://github.com/KitronikLtd/pxt-kitronik-zip-64) build error / [new issue](https://github.com/KitronikLtd/pxt-kitronik-zip-64/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2FKitronikLtd%2Fpxt-kitronik-zip-64%3B%20pxt%20build%20--ignoreTests)
- [x] error:  [KitronikLtd/pxt-kitronik-game-controller](https://github.com/KitronikLtd/pxt-kitronik-game-controller) build error / [new issue](https://github.com/KitronikLtd/pxt-kitronik-game-controller/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2FKitronikLtd%2Fpxt-kitronik-game-controller%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [Tinkertanker/pxt-tinkercademy-microbot](https://github.com/Tinkertanker/pxt-tinkercademy-microbot) build error / [new issue](https://github.com/Tinkertanker/pxt-tinkercademy-microbot/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2FTinkertanker%2Fpxt-tinkercademy-microbot%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [Tinkertanker/pxt-range-vl53l0x](https://github.com/Tinkertanker/pxt-range-vl53l0x) build error / [new issue](https://github.com/Tinkertanker/pxt-range-vl53l0x/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2FTinkertanker%2Fpxt-range-vl53l0x%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [Imagimaker/pxt-imagimaker](https://github.com/Imagimaker/pxt-imagimaker) build error / [new issue](https://github.com/Imagimaker/pxt-imagimaker/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2FImagimaker%2Fpxt-imagimaker%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [PiSupply/pxt-oled-ssd1306](https://github.com/PiSupply/pxt-oled-ssd1306) build error / [new issue](https://github.com/PiSupply/pxt-oled-ssd1306/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2FPiSupply%2Fpxt-oled-ssd1306%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [sparkfun/pxt-gator-particle](https://github.com/sparkfun/pxt-gator-particle) build error / [new issue](https://github.com/sparkfun/pxt-gator-particle/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Fsparkfun%2Fpxt-gator-particle%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [sparkfun/pxt-gator-microphone](https://github.com/sparkfun/pxt-gator-microphone) build error / [new issue](https://github.com/sparkfun/pxt-gator-microphone/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Fsparkfun%2Fpxt-gator-microphone%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [rebeccaclavier/pxt-bmp280](https://github.com/rebeccaclavier/pxt-bmp280) build error / [new issue](https://github.com/rebeccaclavier/pxt-bmp280/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Frebeccaclavier%2Fpxt-bmp280%3B%20pxt%20build%20--ignoreTests)
- [ ] error:  [mu-opensource/pxt-muvision](https://github.com/mu-opensource/pxt-muvision) build error / [new issue](https://github.com/mu-opensource/pxt-muvision/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Fmu-opensource%2Fpxt-muvision%3B%20pxt%20build%20--ignoreTests)
- [x] error:  [elecfreaks/pxt-PlanetX](https://github.com/elecfreaks/pxt-PlanetX) build error / [new issue](https://github.com/elecfreaks/pxt-PlanetX/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Felecfreaks%2Fpxt-PlanetX%3B%20pxt%20build%20--ignoreTests)
- [x] error:  [bsiever/microbit-pxt-timeanddate](https://github.com/bsiever/microbit-pxt-timeanddate) build error / [new issue](https://github.com/bsiever/microbit-pxt-timeanddate/issues/new?title=build%20error&body=Exit%20code%3A%201%20from%20cd%20temp%2Fghpkgs%2Fbsiever%2Fmicrobit-pxt-timeanddate%3B%20pxt%20build%20--ignoreTests)

**Comment by AlasdairAtKitronik** [comment]
@pelikhan Noticed that all the Kitronik extensions listed here are ones which include .cpp files.
Is the error you're getting (MakeCode 3.1.21)?:
![image](https://user-images.githubusercontent.com/36475405/97555403-fdaf9780-19cf-11eb-9060-afb4bb06270d.png)
Or this one (MakeCode 3.0.34)?:
![image](https://user-images.githubusercontent.com/36475405/97555519-2172dd80-19d0-11eb-9c0c-d7b998320af6.png)

I can't make the ZIP64 or ZIP Tile Extensions work at all with these versions of MakeCode, even after switching to the core version of the WS2812B driver, and using the C++preprocessor test from this issue: https://github.com/microsoft/pxt-microbit/issues/3494

**Comment by pelikhan** [comment]
yotta is broken right now and all packages with C++ fail.

**Comment by AlasdairAtKitronik** [comment]
> yotta is broken right now and all packages with C++ fail.

OK, good to know - I'll do something else!

**Comment by jaustin** [comment]
@microbit-sam FYI

**Comment by CleoQc** [comment]
Are we expected to do anything for our extension?

**Comment by microbit-mark** [comment]
@pelikhan @abchatra We have an example of one extension listed here as failing to build, that is tested as working in the /beta editor and with V1 and V2 boards, BrightWearables/pxt-microbit-brightboard @BrightWearables can you confirm this?

List was edited 2 days ago. Is there an update to this or is it just failing all extensions that use C++ and that is why we see it listed here.

**Comment by pelikhan** [comment]
This list is outdated. Look at the output of the GitHub action.

**Comment by microbit-mark** [comment]
Can you update the list @abchatra as we've linked to this for accessory makers to check.

**Comment by abchatra** [comment]
I still see all the same packages failing in the logs. How do I see the exact issue from the logs? @pelikhan

**Comment by microbit-mark** [comment]
The brightboard extension is still reporting a build failure in the latest logs @abchatra, but we can build locally with the warnings in https://github.com/microsoft/pxt-microbit/issues/3506#issuecomment-722272025. Do you know why that would be?

**Comment by pelikhan** [comment]
> I still see all the same packages failing in the logs. How do I see the exact issue from the logs? @pelikhan

Best to look at the action output. https://github.com/microsoft/pxt-microbit/runs/1377260278?check_suite_focus=true#step:7:22023

**Comment by pelikhan** [comment]
The build script is using pxt-microbit from master; which uses the latest version of pxt. In that version, we have fixed a compiler bug and we detect when you try to do a call on a property.

https://github.com/BrightWearables/pxt-microbit-brightboard/blob/master/brightboard.ts#L88

``buffer.length`` is a property, so the ``()`` should be removed.

**Comment by pelikhan** [comment]
I've modified the script to test both master and stable3.0.

**Comment by abchatra** [comment]
Still 41 extensions are failing in the latest /beta. @jaustin what is the plan here?

**Comment by abchatra** [comment]
I have updated the list at the top

**Comment by microbit-sam** [comment]
Hey @abchatra , I think the current plan is:

Extensions using Timer from mbed should build without any changes once this has merged:
https://github.com/lancaster-university/codal-microbit-v2/pull/23

Extensions using Button from mbed aren't compatible with CODAL button
There's an existing issue to add the constructor to CODAL, or it could be added as part of the compat layer
https://github.com/microbit-foundation/codal-microbit/issues/142 (private repo)

Other extensions using mbed features may need to include 'mbed.h', or include the features they actually need e.g. `DigitalIn.h`, `DigitalOut.h`. Were these previously included by `pxt.h`? 
For example `pxt-iot-environment-kit ` uses DigitalIn, but currently doesn't include 'mbed.h' or 'DigitalIn.h'

Extensions that use mbed BLE functions will need to be modified to support CODAL BLE

**Comment by jaustin** [comment]
@finneyj could we please merge lancaster-university/codal-microbit-v2#23 ASAP so we can get an updated list once we automunge the timer information?

**Comment by abchatra** [comment]
More extensions failed in the latest run. Total 31 excluding the warning. I am bit confused on what state these extensions are and what I need to disable.

**Comment by microbit-sam** [comment]
As you can see from the referenced issues above I've opened issues on the failing extensions

Having gone through the extension build logs to create these tickets, I think solving the compat issues with I2C/NRF52I2C, MicroBitFont, and MicroBitSerial is worth doing. For I2C/Serial I think it should just be an additional constructor that accepts mbed Pins as parameters

https://github.com/lancaster-university/codal-microbit-v2/issues/31

**Comment by pelikhan** [comment]
Microbit font should be a small fix. There is a Pr In the pimironi repo with a fix.

________________________________

**Comment by microbit-sam** [comment]
Todays action didn't output any errors, is it possible to reenable the disabeld extensions for this build

**Comment by microbit-mark** [comment]
We have replicated the guidance in https://github.com/lancaster-university/codal-microbit-v2/issues/31 on the micro:bit Knowledgebase in https://support.microbit.org/en/support/solutions/articles/19000121371-makecode-extension-compatibility-v1-and-v2

Please link to this if you see further issues @pelikhan @abchatra
