### ISSUE TITLE
P0 does not work as expected

### ISSUE THREAD

**Issue by DaveAtKitronik** [microsoft/pxt-microbit#3515]
In the inventors kit we use P0 for many experiment outputs / inputs.
P0 does not function as expected. 
The following code:

```
input.onButtonPressed(Button.A, function () {
    basic.showNumber(goal)
})
input.onButtonPressed(Button.B, function () {
    goal = Math.randomRange(0, 100)
    basic.showNumber(goal)
})

let goal = 0
goal = Math.randomRange(0, 100)
basic.showNumber(goal)

basic.forever(function () {
    pins.digitalWritePin(DigitalPin.P0, 1)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(goal * 5)
    pins.digitalWritePin(DigitalPin.P0, 0)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.pause(goal * 5)
})
```
Flashes 2 LEDS - on on P0, one on P1 at a random rate.
With V1.5 this functions as expected. With V2 P0 stays on and P1 flashes as expected.
Versions:
![image](https://user-images.githubusercontent.com/25896029/97551575-0ea9da00-19cb-11eb-86a6-9144af4e401e.png)

Possibly related to https://github.com/microsoft/pxt-microbit/issues/3497

**Comment by pelikhan** [comment]
v3.0.38 has a fix for P0. Please try again.

**Comment by pelikhan** [comment]
This looks fixed in beta
![image](https://user-images.githubusercontent.com/4175913/97677067-e6fc5580-1a4e-11eb-9aae-6fcce4ce1ec4.png)
