### ISSUE TITLE
Pin level change cannot trigger event

### ISSUE THREAD

**Issue by tangjie133** [microsoft/pxt-microbit#3524]
To Reproduce

Go to 'Makecade'.
Drag the new V2 pin event function to print pulse duration when pin 16 bit is low pulse.
Serial port printing data.
Expected behavior:
Serial printing pulse duration，This only works on V1 and fails on V2.

Screenshots:
![QQ截图20201030154346](https://user-images.githubusercontent.com/51323906/97673425-ba842000-1ac6-11eb-975a-22f990dad359.png)

**Comment by pelikhan** [comment]
You should add a ``serial write line`` after ``serial write number``. Can you add a toggle to see if the event gets triggered?

**Comment by pelikhan** [comment]
(if you could share the project, or the typescript, that'd be great)

**Comment by tangjie133** [comment]
https://makecode.microbit.org/_FVK1PMTHbHxJ

**Comment by tangjie133** [comment]
The p16 pin is connected with an infrared receiving head.

**Comment by tangjie133** [comment]
How long can this problem be solved.

**Comment by abchatra** [comment]
@abchatra get smaller repro.

**Comment by tangjie133** [comment]
High and low level events cannot be triggered by pins

**Comment by microbit-mark** [comment]
This should now be fixed in makecode.microbit.org/stable can you confirm @tangjie133?

**Comment by abchatra** [comment]
Fixed
