### ISSUE TITLE
WebUSB full flashing does not work for V2

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3525]
A simple program works when flashed over drag and drop, but not when flashed via webUSB. It works as expected on v1

![image](https://user-images.githubusercontent.com/31242877/97677032-85a5a800-1a89-11eb-9c02-8508a0c61ba0.png)

If you then connect webUSB after drag and drop and then flash an update to the program it works, so it looks like partial flashing is working.

@pelikhan @mmoskal

**Comment by pelikhan** [comment]
It works here but the cortex does not seem to restart after the full flash. We need to powercycle it to get it running again.

**Comment by abchatra** [comment]
@microbit-mark is this fixed?

**Comment by abchatra** [comment]
Closing for now. Will reopen if @microbit-mark can reproduce the issue.
