### ISSUE TITLE
Older projects do not update for latest V2 blocks

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3533]
**Describe the bug**

If you open an older project in makecode.microbit.org/beta the blocks do not automatically upadte to show the latest status.

Here the onSound blocks are missing
<img width="507" alt="image" src="https://user-images.githubusercontent.com/31242877/97698568-9b729780-1aa0-11eb-88cc-9b4e53da786c.png">

**To Reproduce**
Not sure if this will repro, buit this program does not have the mic blocks for me

https://makecode.microbit.org/_97zHuci2tMx6

**Expected behavior**
I would expect all V2 blocks to be present in any project I open.

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pelikhan** [comment]
This is because sound blocks are part of the "microphone" project, which is not added by default.

**Comment by abchatra** [comment]
This is confusing. Can we make it part of default package for any project?

**Comment by pelikhan** [comment]
I have been trying to keep microphone separate to match what we do in pxt-common-packages. @jwunderl  you can try this fix: https://github.com/microsoft/pxt-microbit/pull/3573

**Comment by abchatra** [comment]
Fixed
