### ISSUE TITLE
Sounds have audible clicks when played in browser.

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3534]
**Describe the bug**
I think this applies to most if not all sound playback oin the browser, but if you raise the volume, you can hear audible clicks at the end of the sound playback. I noticed this for the sound emoji eg

<img width="325" alt="image" src="https://user-images.githubusercontent.com/31242877/97699035-69ae0080-1aa1-11eb-9320-dde6c91584be.png">

but I think it repros for play melody too as each tone is played, but not when you are composing the melody in the editor. eg click the play button in here
<img width="333" alt="image" src="https://user-images.githubusercontent.com/31242877/97699347-e214c180-1aa1-11eb-8ad1-c5eba2929b08.png">

**Comment by riknoll** [comment]
Fixed by https://github.com/microsoft/pxt/pull/8200
