### ISSUE TITLE
Simulator SVG assets for V2 simulator

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#3538]
The V2 simulation in /beta is great but could do with some more accurate SVG assets

There's a full V2 SVG here https://github.com/microbit-foundation/microbit-svg/pull/5
I've pulled out some of the more useful assets 

@pelikhan as requested find attached
[microbit V2 assets.svg.zip](https://github.com/microsoft/pxt-microbit/files/5465699/microbit.V2.assets.svg.zip)

**Comment by jaustin** [comment]
Just a few more direct notes
* Could the mic icon please use the one in the image
* The notches on the edge connector are rounded as per the SVG attached above
* Can "V2" on the front please match how it looks on the back. Black text on white is fine, prefer that to yellow. Have given SVG of rendered font etc

**Comment by microbit-mark** [comment]
Also the mic input hole should be added, mentioned in  https://github.com/microsoft/pxt-microbit/pull/3540#issuecomment-719639880
![image](https://user-images.githubusercontent.com/31242877/98263986-5908f900-1f7f-11eb-88c4-d740d13d9cea.png)

 It would be useful to show the input. For kids learning about microphones and sound and for teachers demoing it on the big screen. It would avoid any confusion about the mic being mounted on the back, but the input being on the front.

**Comment by abchatra** [comment]
This is mostly implemented
