### ISSUE TITLE
I wanted to get the ultrasonic distance, but I couldn't make it

### ISSUE THREAD

**Issue by tangjie133** [microsoft/pxt-microbit#3544]
To Reproduce
I want to calculate the ultrasonic return distance by obtaining the pin high and low level changes, but the returned data is not correct，How long can this problem be fixed？
Expected behavior:
Serial printing pulse duration，This only works on V1 and fails on V2.

Screenshots:
![QQ截图20201102151352](https://user-images.githubusercontent.com/51323906/97839920-11376700-1d1e-11eb-973f-d72d106bca12.png)
link：https://makecode.microbit.org/_Joc6xW1jy2Ls

**Comment by abchatra** [comment]
@tangjie133 have you tried /beta?

**Comment by tangjie133** [comment]
Yes, the data returned by V1 version is continuous. Although V2 version can return data, but the returned data is not continuous, it will return "0"

**Comment by abchatra** [comment]
@jaustin

**Comment by pelikhan** [comment]
Fix coming in https://github.com/microsoft/pxt-microbit/pull/3642

**Comment by abchatra** [comment]
Fixed @tangjie133 please validate.

**Comment by tangjie133** [comment]
Using the same code to read ultrasound is still problematic, as is infrared.
Infrared library link:https://github.com/1010technologies/pxt-makerbit-ir-receiver
Ultrasonic link:https://github.com/DFRobot/pxt-maqueen
These two work normally in V1.

**Comment by abchatra** [comment]
@tangjie133 did you try /beta?

**Comment by tangjie133** [comment]
yes

**Comment by microbit-mark** [comment]
CODAL v0.2.24 has now been released to https://makecode.microbit.org/stable can you check here to see if this still reproduces @tangjie133 ?

**Comment by microbit-mark** [comment]
User reports that this issue still persists on Maqueen. Also raised here @tangjie133  https://github.com/DFRobot/pxt-maqueen/issues/27

**Comment by microbit-mark** [comment]
@tangjie133 We have reports from people using the extension that this is now fixed. I will close here, but feel free to re-open if you still see issues.
