### ISSUE TITLE
V2 calibration does not persist on power cycles

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3550]
**Describe the bug**
The compass calibration should persist through a power cycle/reset. This works for V1 boards, but not V2.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/31242877/97855654-fa2f4f80-1cf2-11eb-9abf-e48428035d03.png">

**To Reproduce**
- Flash file the uses the compass
- calibrate
- power cycle

**Expected behavior**
Calibration persists unless flashed using drag and drop

**Comment by abchatra** [comment]
@jaustin is this specific to MakeCode or is this issue in python as well?

**Comment by microbit-mark** [comment]
Yes persists in Python, so this is a CODAL bug

**Comment by pelikhan** [comment]
Micropython?

________________________________

**Comment by abchatra** [comment]
Repros in micropython

**Comment by microbit-mark** [comment]
This is now fixed
