### ISSUE TITLE
[Usable – Make Code – Create a project] Narrator focus moves out from 'Create a project' pop-up window while navigating in scan mode.

### ISSUE THREAD

**Issue by Shalini3457** [microsoft/pxt-microbit#3563]
**User Experience:**
If, in scan mode, Screen Reader focus moves out of the dialogue box, then the users who depends upon Screen Reader for navigation might get affected as the users will have to use extra tab to reach back to the dialogue box again to perform its function.

**Note**: User credentials should NOT be included in the bug.

**Repro Steps:**
1. Launch application URL.
2. Home page will open.
3. Navigate to the controls appearing under "My Project" section in Home page and select 'New Project' Button.
4. Navigate all controls under 'Create a Project' pop-up.
5. Verify whether Narrator focus moves out from 'Create a project' pop-up window while navigating in scan mode or not.

**Actual Result:**
Narrator focus moves out from 'Create a project' pop-up window while navigating in scan mode and reading as 'Blank'.

**Expected Result:**
Narrator focus should not move out from 'Create a project' pop-up window while navigating in scan mode. So, that the user can perform its function properly on the dialogue box.

**Note:**
This issue does not exists on Firefox & Chrome.
Same issue exists throughout the application.

**Test Environments:**
Version: 20H2 (OS Build: 19042.508)
Browser: Edge chromium DEV Build (Version 87.0.654.0)
Screen Reader: Narrator

**Comment by Shalini3457** [comment]
Labels:
#A11yUsable, #Accessibility, #A11ySev4, #HCL, #Benchmark-HCL-MakeCode-OCT2020, #Win10-Edge(Chromium)

[Usable_Create a project_Narrator focus moves out from pop-up.zip](https://github.com/microsoft/pxt-microbit/files/5479849/Usable_Create.a.project_Narrator.focus.moves.out.from.pop-up.zip)

**Comment by jwunderl** [comment]
no repro, likely fixed in edge update to match chrome
