### ISSUE TITLE
High contrast  off after refreshing the page

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3567]
**Describe the bug**
High contrast  **off** after **refreshing** the page

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.New Project
3.Click **High Contrast On**
4.**Refresh** the page

**Expect behavior**
It still keeps high contrast **on**

**Actual behavior**
High contrast  **off** after **refreshing** the page
![1](https://user-images.githubusercontent.com/59192069/97964710-2bdc0f80-1df4-11eb-8d73-1469833cf1e1.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.0.45
3.Microsoft MakeCode version: 6.0.30

**Comment by abchatra** [comment]
We don't save the high contrast. This is intentional.

**Comment by abchatra** [comment]
Because otherwise in a class room kids may not know to turn it off (if previous class student had turned it on).
