### ISSUE TITLE
[Keyboard Navigation – Make Code – Import File] Focus doesn't land on first interactive control after selecting 'Import file' button.

### ISSUE THREAD

**Issue by Shalini3457** [microsoft/pxt-microbit#3570]
**User Experience:**
Keyboard dependent users will face difficulty if visual focus does not land on first interactive element after activating button control then users who rely on keyboard will not able to predict the focus is actually on which control so the end users will get confused and this may lead to disorientation due to this issue.

**Note**: User credentials should NOT be included in the bug.

**Repro Steps:**
1. Launch application URL.
2. Home page will open.
3. Navigate to "Import" button and select it.
4. Navigate through the controls appearing under "Import" dialog.
5. Navigate to import file option and select it.
6. Verify that Focus land on first interactive control after selecting 'Import file' button or not.

**Actual Result:**
Keyboard focus doesn't land on first interactive control after selecting 'Import file' button. It moves on 'Go ahead' button.

**Expected Result:**
Keyboard focus should land on first interactive control that is 'Close' button instead of 'Go ahead' button after selecting 'Import file' button.

**Note:**
Same issue exists on Firefox & Chrome.

**WCAG Reference:**
[WCAG 3.2.1 - On Focus
](https://www.w3.org/WAI/WCAG21/Understanding/on-focus.html)

**Test Environments:**
Version: 20H2 (OS Build: 19042.508)
Browser: Edge chromium DEV Build (Version 87.0.654.0), Firefox(75.0), Chrome

**Comment by Shalini3457** [comment]
Labels:
#Accessibility, #A11ySev2, #HCL, #Benchmark-HCL-MakeCode-OCT2020, #WCAG3.2.1, #Win10-Edge(Chromium)

[WCAG3.2.1_Import File.zip](https://github.com/microsoft/pxt-microbit/files/5480267/WCAG3.2.1_Import.File.zip)

**Comment by jwunderl** [comment]
No repro, in the attached video it moved focus onto the 'choose file' section correctly / pressing space or enter would result in the file select dialog
