### ISSUE TITLE
Reset causes P1 and P2 to blip high on V2 micro:bit

### ISSUE THREAD

**Issue by DaveAtKitronik** [microsoft/pxt-microbit#3571]
The following code:

```
pins.analogWritePin(AnalogPin.P0, 0)
pins.analogWritePin(AnalogPin.P1, 0)
pins.analogWritePin(AnalogPin.P2, 0)
```
should do basically nothing. 
On reset however the P1 and P2 pins blip high.
P0 doesn't blip high. 
P0 used to make a click through the onboard buzzer, but does not seem to anymore.

Digital  write doesn't exhibit the same issue:
```
pins.digitalWritePin(DigitalPin.P0, 0)
pins.digitalWritePin(DigitalPin.P1, 0)
pins.digitalWritePin(DigitalPin.P2, 0)
```
![image](https://user-images.githubusercontent.com/25896029/97973455-fe746f00-1dbd-11eb-9b81-373475689b41.png)

**Comment by pelikhan** [comment]
Looks like a CODAL issue.

**Comment by abchatra** [comment]
@DaveAtKitronik does this still broken? What is the impact of this bug? Does go back to zero or stay high?

**Comment by DaveAtKitronik** [comment]
I cant tell at the moment - my V2 is having some issues. 
The pin blips high then low. This causes a spurious pulse. Depends what the micro:bit is attached to as to how serious it is.

**Comment by abchatra** [comment]
This should be fixed now.
