### ISSUE TITLE
[Screen Reader – Make Code – Import File] Screen reader doesn't provide any file uploading information after uploaded any file. 

### ISSUE THREAD

**Issue by Shalini3457** [microsoft/pxt-microbit#3578]
**User Experience:**
Properly defined information & relationship of an UI element helps people with different disabilities, by allowing user agents to provide proper navigation & content according to the needs of individual users.

**Note**: User credentials should NOT be included in the bug.

**Repro Steps:**
1. Launch application URL.
2. Home page will open.
3. Navigate to "Import" button and select it.
4. Navigate through the controls appearing under "Import" dialog.
5. Navigate to import file option and navigate through the all the controls of dialog.
6. Verify that Screen reader announces any file uploading information after uploaded any file or not.

**Actual Result:**
Screen reader doesn't provide any file uploading information after uploaded any file under 'Import File' pop-up window.

**Expected Result:**
Screen reader should provide file uploading information after uploaded any file under 'Import File' pop-up window.

**WCAG Reference:**
[WCAG 1.3.1 - Info and Relationships
](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html)

**Test Environments:**
Version: 20H2 (OS Build: 19042.508)
Browser: Edge chromium DEV Build (Version 87.0.654.0), Firefox(75.0), Chrome
Screen Reader: Narrator, NVDA, JAWS

**Comment by Shalini3457** [comment]
Labels:
#Accessibility, #A11ySev2, #HCL, #Benchmark-HCL-MakeCode-OCT2020, #WCAG1.3.1, #Win10-Edge(Chromium)

[WCAG1.3.1_Import File.zip](https://github.com/microsoft/pxt-microbit/files/5486143/WCAG1.3.1_Import.File.zip)

**Comment by jwunderl** [comment]
Looks like the browser side is just not surfacing the information here; other browsers do read out the file name. This is the default file input so if the browser isn't announcing the inputted file then that seems like the expected behavior on their end / to match the normal behavior of screen reader.
