### ISSUE TITLE
[Usable – Make Code – Sign in with GitHub] Narrator focus moves on hidden control in scan mode under 'Sign in with GitHub' pop-up window.

### ISSUE THREAD

**Issue by Shalini3457** [microsoft/pxt-microbit#3588]
**User Experience:**
It will be difficult for screen reader dependent users to understand full information of any control if screen reader focus lands on hidden elements and reads unnecessary information.

**Note**: User credentials should NOT be included in the bug.

**Repro Steps:**
1. Launch application URL.
2. Home page will open.
3. Navigate to "Import" button and select it.
4. Navigate through the controls appearing under "Import" dialog.
5. Navigate to "Your GitHub Repo" option and navigate through the all the controls of dialog "Sign in with GitHub"..
6. Verify that Narrator focus moves on hidden control in scan mode or not.

**Actual Result:**
Narrator focus moves on hidden control in scan mode under 'Sign in with GitHub' pop-up window and reading as ''Searching git hub repository'.

**Expected Result:**
Narrator focus should not move on hidden control in scan mode under 'Sign in with GitHub' pop-up window. It should move on only visually appearing control.

**Note:**
This issue does not exists under Firefox & Chrome.

**Test Environments:**
Version: 20H2 (OS Build: 19042.508)
Browser: Edge chromium DEV Build (Version 87.0.654.0)
Screen Reader: Narrator

**Comment by Shalini3457** [comment]
Labels:
#Accessibility, #A11ySev4, #HCL, #Benchmark-HCL-MakeCode-OCT2020, #Win10-Edge(Chromium)

**Comment by jwunderl** [comment]
no repro on new edge, likely due to chromium update
