### ISSUE TITLE
[Screen Reader – Make Code - Share] Narrator focus does not sync with keyboard focus while navigating to suggestion list item present under 'Share Project' pop-up.

### ISSUE THREAD

**Issue by Shalini3457** [microsoft/pxt-microbit#3591]
**User Experience**:
Cognitive impaired users and screen reader users will face difficulty if screen reader focus is not syncing with keyboard focus, users won't be able to perform functionality over such control.

**Note**: User credentials should NOT be included in the bug.

**Repro Steps:**
1. Launch application URL.
2. Home page will open.
3. Navigate "New Project" option and select it.
4. Editor screen will open.
5. Navigate to "Share" option appearing in header section and select it.
6. Navigate through all the controls of  "Share Project" dialog.
5. Navigate to "Name edit field" and try to put input.
6. Verify that Narrator focus sync with keyboard focus while navigating suggestion list item or not.

**Actual Result:**
Narrator focus does not sync with keyboard focus while navigating to suggestion list item present under 'Share Project' pop-up also screen reader is not reading any information.

**Expected Result:**
Narrator focus should sync with keyboard focus while navigating to suggestion list item present under 'Share Project' pop-up also screen reader should provide information.

**Note:**
This issue does not exists under Firefox +NVDA & Chrome + JAWS.

**WCAG Reference:**
[WCAG 4.2.10 - Tracking of Focus and Selection Attributes
](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={b24201d1-2276-4471-8183-e1e5353031ad}})

**Test Environments:**
Version: 20H2 (OS Build: 19042.508)
Browser: Edge chromium DEV Build (Version 87.0.654.0)
Screen reader: Narrator

**Comment by Shalini3457** [comment]
Labels:
#Accessibility, #A11ySev2, #HCL, #Benchmark-HCL-MakeCode-OCT2020, #WCAG4.2.10, #Win10-Edge(Chromium)

[WCAG4.2.10_Share.zip](https://github.com/microsoft/pxt-microbit/files/5493202/WCAG4.2.10_Share.zip)

**Comment by jwunderl** [comment]
that popup is not from us, appears to be system or browser extension. Not something we can control.
