### ISSUE TITLE
Ultrasonic sensors reading differently between V1 and V2 hardware

### ISSUE THREAD

**Issue by PhilAtKitronik** [microsoft/pxt-microbit#3599]
While testing the Kitronik MOVE Motor ultrasonic measuring block, it has been noticed that there has been a change from V1 hardware to V2.  

For the V1 hardware, to make the ultrasonic sensor read the correct distance, the formula had to be changed.  Typically it is read pulsein then math.idiv of the pulse.  The datasheet for the HC-SR04 say this divide should be by 58.  However with the V1 micro:bits this gave an incorrect reading, thus the value had to be changed to 39 to get the correct reading.

Now with V2, this code in our block does not work as the near correct value is 58. 
 When testing with 58 in the math.idiv, at 5cm gives reading of 4cm, 10cm gives reading 9cm and at 20cm gives reading of 18cm.

Here is a screenshot of the block code to make the ultrasonics work on the V1 micro:bit

![image](https://user-images.githubusercontent.com/37149430/98267376-3b3d9300-1f83-11eb-92cb-7d2f4778f1b4.png)

This is the code created (in beta editor) to get the ultrasonic readings to measure within 1cm.  The code has been copied out from the block and the correct pins added in the required place, so that its possible to adjust the value in the math.idiv calculation.  Also the remove of the enum for selection between reading being converted to cm or inches (which has the same issue with number 98 on V1 and 148 on V2)

![image](https://user-images.githubusercontent.com/37149430/98267529-67f1aa80-1f83-11eb-9839-bc61e67ac763.png)

The difference presuming is the measurement of pins.pulseIn which is different between the two version.

**Comment by martinwork** [comment]
I think the need for an altered time factor in V1 DAL is related to https://github.com/lancaster-university/microbit-dal/issues/451. The drift is triggered because pins.pulseIn reads the time in a tight loop.

**Comment by pelikhan** [comment]
We need a event based pulse computation problaby baked in CODAL.

________________________________

**Comment by pelikhan** [comment]
Fix coming in https://github.com/microsoft/pxt-microbit/pull/3642/files

**Comment by abchatra** [comment]
fixed

**Comment by PhilAtKitronik** [comment]
I have just tested the code on a V1 microbit and V2 microbit.  V1 still requires the value in the formula to be 39,  V2 requires the formula to have 58.  There does not seem to be any chance unless I have not received the latest update when coding on the beta editor.

With our current code V2 still will read a distance greater than it measures, at 15cm a V2 microbit reads 23cm.

The code for each time is
`basic.forever(function () {
    basic.showNumber(Kitronik_Move_Motor.measure())
    basic.pause(500)
})
`

**Comment by 4tronix** [comment]
This pulsein change seems to have broken single pin ultrasonics. See https://github.com/microsoft/pxt-microbit/issues/3731#issue-746688781

**Comment by microbit-mark** [comment]
CODAL v0.2.24 has now been released to https://makecode.microbit.org/stable, can you check here to see if this still reproduces for your accessory @PhilAtKitronik?

**Comment by abchatra** [comment]
Fixed
