### ISSUE TITLE
game library blocks - issues

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#36]
open js, enter code

```
 let ghost = 0;
 let food = 0;
 let hero = 0;
hero = game.createSprite(2, 2);
food = game.createSprite(4, 4);
ghost = game.createSprite(0, 0);


```

an issue occurs on latest

![image](https://cloud.githubusercontent.com/assets/11206682/14195130/b1060072-f76a-11e5-983c-7b806dc0b94d.png)

**Comment by mebrauns** [comment]
this code is not converting from blocks to JS correctly
```
hero = game.createSprite(2, 2);
food = game.createSprite(4, 4);
ghost = game.createSprite(0, 0);
ghost.change(LedSpriteProperty.Blink, 100);
food = led.brightness() == 8;
while (true) {
    basic.pause(400);
    if (ghost.get(LedSpriteProperty.X) < hero.get(LedSpriteProperty.X)) {
        ghost.change(LedSpriteProperty.X, 1);
    }
    else if (ghost.get(LedSpriteProperty.X) < hero.get(LedSpriteProperty.X)) {
        ghost.change(LedSpriteProperty.X,  -1 );
    }
    else if (ghost.get(LedSpriteProperty.Y) < hero.get(LedSpriteProperty.Y)) {
        ghost.change(LedSpriteProperty.Y, 1);
    }
    else if (ghost.get(LedSpriteProperty.Y) > hero.get(LedSpriteProperty.Y)) {
        ghost.change(LedSpriteProperty.Y,  -1 );
    }
    if (input.acceleration(Dimension.X) > 200) {
        hero.change(LedSpriteProperty.X, 1);
    }
    else if (input.acceleration(Dimension.X) <  -200 ) {
        hero.change(LedSpriteProperty.X,  -1 );
    }
    if (input.acceleration(Dimension.Y) > 200) {
        hero.change(LedSpriteProperty.Y, 1);
    }
    else if (input.acceleration(Dimension.Y) >  -200 ) {
        hero.change(LedSpriteProperty.Y,  -1 );
    }
    if (hero.isTouching(food)) {
        game.addScore(1);
        food.set(LedSpriteProperty.X, Math.random(5));
        food.set(LedSpriteProperty.Y, Math.random(5));
        if (food.get(LedSpriteProperty.X) < 2 && food.get(LedSpriteProperty.Y) < 2) {
            ghost.set(LedSpriteProperty.X, 4);
            ghost.set(LedSpriteProperty.Y, 4);
        }
        else if (food.get(LedSpriteProperty.X) > 2 && food.get(LedSpriteProperty.Y) < 2) {
            ghost.set(LedSpriteProperty.X, 0);
            ghost.set(LedSpriteProperty.Y, 4);
        }
        else if (food.get(LedSpriteProperty.X) < 2 && food.get(LedSpriteProperty.Y) > 2) {
            ghost.set(LedSpriteProperty.X, 4);
            ghost.set(LedSpriteProperty.Y, 0);
        }
        else {
            ghost.set(LedSpriteProperty.X, 0);
            ghost.set(LedSpriteProperty.Y, 0);
        }
    }
    if (hero.isTouching(ghost)) {
        game.gameOver();
    }
    basic.pause(20);
}
0.set(LedSpriteProperty.X, 4);



```

the issue is probably with the last line of code: 

```
0.set(LedSpriteProperty.X, 4);
```

what should this code be in JS?

**Comment by pelikhan** [comment]
Yup, that's a bug....

Sent from Outlook Mobile<https://aka.ms/djubve>




On Thu, Mar 31, 2016 at 6:39 PM -0700, "Michael Elliot Braun" <notifications@github.com<mailto:notifications@github.com>> wrote:


this code is not converting from blocks to JS correctly

hero = game.createSprite(2, 2);
food = game.createSprite(4, 4);
ghost = game.createSprite(0, 0);
ghost.change(LedSpriteProperty.Blink, 100);
food = led.brightness() == 8;
while (true) {
    basic.pause(400);
    if (ghost.get(LedSpriteProperty.X) < hero.get(LedSpriteProperty.X)) {
        ghost.change(LedSpriteProperty.X, 1);
    }
    else if (ghost.get(LedSpriteProperty.X) < hero.get(LedSpriteProperty.X)) {
        ghost.change(LedSpriteProperty.X,  -1 );
    }
    else if (ghost.get(LedSpriteProperty.Y) < hero.get(LedSpriteProperty.Y)) {
        ghost.change(LedSpriteProperty.Y, 1);
    }
    else if (ghost.get(LedSpriteProperty.Y) > hero.get(LedSpriteProperty.Y)) {
        ghost.change(LedSpriteProperty.Y,  -1 );
    }
    if (input.acceleration(Dimension.X) > 200) {
        hero.change(LedSpriteProperty.X, 1);
    }
    else if (input.acceleration(Dimension.X) <  -200 ) {
        hero.change(LedSpriteProperty.X,  -1 );
    }
    if (input.acceleration(Dimension.Y) > 200) {
        hero.change(LedSpriteProperty.Y, 1);
    }
    else if (input.acceleration(Dimension.Y) >  -200 ) {
        hero.change(LedSpriteProperty.Y,  -1 );
    }
    if (hero.isTouching(food)) {
        game.addScore(1);
        food.set(LedSpriteProperty.X, Math.random(5));
        food.set(LedSpriteProperty.Y, Math.random(5));
        if (food.get(LedSpriteProperty.X) < 2 && food.get(LedSpriteProperty.Y) < 2) {
            ghost.set(LedSpriteProperty.X, 4);
            ghost.set(LedSpriteProperty.Y, 4);
        }
        else if (food.get(LedSpriteProperty.X) > 2 && food.get(LedSpriteProperty.Y) < 2) {
            ghost.set(LedSpriteProperty.X, 0);
            ghost.set(LedSpriteProperty.Y, 4);
        }
        else if (food.get(LedSpriteProperty.X) < 2 && food.get(LedSpriteProperty.Y) > 2) {
            ghost.set(LedSpriteProperty.X, 4);
            ghost.set(LedSpriteProperty.Y, 0);
        }
        else {
            ghost.set(LedSpriteProperty.X, 0);
            ghost.set(LedSpriteProperty.Y, 0);
        }
    }
    if (hero.isTouching(ghost)) {
        game.gameOver();
    }
    basic.pause(20);
}
0.set(LedSpriteProperty.X, 4);





the issue is probably with the last line of code:

0.set(LedSpriteProperty.X, 4);


what should this code be in JS?

-

**Comment by pelikhan** [comment]
Please always provide the URL of the block program.
