### ISSUE TITLE
Change on-board speaker to built-in speaker for translatabiliy/clarity

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#3600]
It seems 'on-board' is less clear to translate from English to other langauges than 'built-in', and the effect in English is pretty similar so we prefer 'built-in' for the speaker block and API

<img width="243" alt="image" src="https://user-images.githubusercontent.com/147113/98272040-873f0680-1f88-11eb-91db-17342dddbfb3.png">
--> set built-in spekaer <on/off>

```setOnBoardSpeakerEnabled``` --> ```setBuiltInSpeakerEnabled```

**Comment by pelikhan** [comment]
What about not putting this adjective?

________________________________

**Comment by jaustin** [comment]
<img width="268" alt="image" src="https://user-images.githubusercontent.com/147113/98273309-054fdd00-1f8a-11eb-8ecb-c3c46ef55deb.png">
We've got some differing precedents there. I think I prefer keeping 'set'

**Comment by pelikhan** [comment]
I meat remove « builtin  » or « on board »

________________________________

**Comment by jaustin** [comment]
We don't wan't people to think this will apply to a connected speaker via an accessory. IE this will still make sound via P0 so we think 'built-in' is clearer. Lots of accessories/robots etc have speakers.

**Comment by pelikhan** [comment]
I think onboard or builtin is the same in terms of translation since it is not going to be translated literally.

________________________________

**Comment by jaustin** [comment]
@abchatra, @mmoskal, @carlosperate all felt that translating to their native language built-in was easier. That's not a huge sample size but here we've asked people and built-in is preferred anyway over on-board.
