### ISSUE TITLE
[Label & Instructions – Make Code - Publish project] Screen reader does not provide label information with their editing field under 'Share project' pop-up window.

### ISSUE THREAD

**Issue by Shalini3457** [microsoft/pxt-microbit#3606]
**User Experience**:
If instructions or labels does not clearly identify the controls in a form, the users will not know what input data is expected. The pages will look cluttered with unnecessary information and   people with disabilities will miss important cues and instructions

**Note**: User credentials should NOT be included in the bug.

**Repro Steps:**
1. Launch application URL.
2. Home page will open.
3. Navigate "New Project" option and select it.
4. Editor screen will open.
5. Navigate to "Share" option appearing in header section and select it.
6. Navigate to "Publish project" under  "Share Project" dialog and select it.
7. Navigate to all the control appearing like QR Code, Embed(Code, Editor and Simulator).
8. Verify that Screen reader provides label information with their editing field or not.

**Actual Result:**
Screen reader does not provide label information with their editing field under 'Share project' pop-up window and due to this user is not able the identify the label information on editing field.

**Expected Result:**
Screen reader should provide label information(Your project is ready! Use the address below to share your projects.) with their editing field under 'Share project' pop-up window, so that user can easily identify the label information on editing field.

**Note:**
Same issue appear under Chrome & Firefox.

**WCAG Reference:**
[WCAG 3.3.2 - Labels or Instructions](https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions.html})

**Test Environments:**
Version: 20H2 (OS Build: 19042.508)
Browser: Edge chromium DEV Build (Version 87.0.654.0), Firefox(75.0), Chrome
Screen reader: Narrator, NVDA, JAWS

**Comment by Shalini3457** [comment]
Labels:
#Accessibility, #A11ySev2, #HCL, #Benchmark-HCL-MakeCode-OCT2020, #WCAG3.3.2, #Win10-Edge(Chromium)

[WCAG3.3.2_Publish project.zip](https://github.com/microsoft/pxt-microbit/files/5499518/WCAG3.3.2_Publish.project.zip)

**Comment by jwunderl** [comment]
The url has a label that is read out on focus, all elements appear to be working.
