### ISSUE TITLE
[Visual Requirements - Make Code - Header] Tooltip of 'Select code editor language, Help, More' icons are getting disappeared when mouse pointer hover on it.

### ISSUE THREAD

**Issue by Shalini3457** [microsoft/pxt-microbit#3607]
**User Experience**:
If any control is getting disappeared when mouse hover is done, the end user who use magnifier will not able to magnify the tooltip to see the content and will miss the required information where tooltips are detailed in nature.

**Note**: User credentials should NOT be included in the bug.

**Repro Steps:**
1. Launch application URL.
2. Home page will open.
3. Navigate "New Project" option and select it.
4. Editor screen will open.
5. Navigate to "Select code editor language, Help, More" option appearing in header section.
6. Verify the issue.

**Actual Result:**
Tooltip of 'Select code editor language, Help, More' icons are getting disappeared when mouse pointer hover on it under 'Header' section.

**Expected Result:**
Tooltip of 'Select code editor language, Help, More' icons should not get disappear when mouse pointer hover on it under 'Header' section.

**Note:**
1. Same issue appear under Chrome & Firefox.
2. Same issue exists throughout the application.

**WCAG Reference:**
[WCAG 1.4.13 - Content on Hover or Focus](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html})

**Test Environments:**
Version: 20H2 (OS Build: 19042.508)
Browser: Edge chromium DEV Build (Version 87.0.654.0), Firefox(75.0), Chrome

**Comment by Shalini3457** [comment]
Labels:
#Accessibility, #A11ySev2, #HCL, #Benchmark-HCL-MakeCode-OCT2020, #WCAG1.4.13, #Win10-Edge(Chromium)

[WCAG1.4.13_Header.zip](https://github.com/microsoft/pxt-microbit/files/5499630/WCAG1.4.13_Header.zip)

**Comment by jwunderl** [comment]
Tooltip is from browser, which typically only displays tooltip when a use's mouse pointer is below a certain speed. If mouse is kept still it will remain indefinitely.
