### ISSUE TITLE
Searching for V2 blocks don't show

### ISSUE THREAD

**Issue by livcheerful** [microsoft/pxt-microbit#3613]
**Describe the bug**
When using the search bar and looking for "V2", I can't discover the new V2 blocks.

**Expected behavior**
I'd like the new logo block, sound blocks to appear. (Anything under the micro:bit V2 category)

**Screenshots**
This is what I get instead:
![image](https://user-images.githubusercontent.com/18712271/98403941-97092a00-201e-11eb-9031-daf4f41ecb9b.png)

**micro:bit version (please complete the following information):**
- not hardware bug -

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome 86

**Comment by abchatra** [comment]
Although there is a bug here, we don't want  users to know these apis by v2. As Microbit foundation wants to remove v2 tag in a six-twelve month timeframe. I will close this bug as wont' fix.
