### ISSUE TITLE
Cannot download to v2 via iPad

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#3615]
https://www.youtube.com/watch?v=PpDzOvaR9oE&feature=youtu.be

I plugged in a new v2 into my iPad via usb.
iPad app is up to date.
I follow the pairing protocol and I can see it paired successfully.
I opened the MakeCode interface.
I clicked and held back to switch to beta.
I create a new project and hit "Download".
It tells me the device needs to update.
Nothing changes on the micro:bit.

**Comment by martinwork** [comment]
Thanks @darzu We're working on an update to the app to match the recent change to SoftDevice and bootloader.

**Comment by microbit-mark** [comment]
@darzu if you drop me an email mark@microbit.org I will add you to the TestFlight for the latest beta release too.

**Comment by darzu** [comment]
> @darzu if you drop me an email [mark@microbit.org](mailto:mark@microbit.org) I will add you to the TestFlight for the latest beta release too.

Done!

**Comment by microbit-mark** [comment]
Added you. Please check the latest Test Flight for a reproducer

**Comment by abchatra** [comment]
Fixed
