### ISSUE TITLE
[Keyboard Navigation – Make Code – Green Screen] Focus doesn't retain back to the 'More' icon control after closing 'Choose a camera' pop-up.

### ISSUE THREAD

**Issue by Shalini3457** [microsoft/pxt-microbit#3619]
**User Experience:**
Keyboard dependent users will face difficulty if visual focus does not retain back to expected control after closing pop-up window then users who rely on keyboard will not able to predict the focus is actually on which control so the end users will get confused and this may lead to disorientation due to this issue.

**Note**: User credentials should NOT be included in the bug.

**Repro Steps:**
1. Launch application URL.
2. Home page will open.
3. Navigate "New Project" option and select it.
4. Editor screen will open.
5. Navigate to "Settings" option appearing in header section and select it.
6. Navigate to "Green Screen On" option and select it.
7. Verify that Green Screen setting is getting activated and the controls under "Choose a camera" dialogue. 
8. Verify that Focus doesn't retain back to the 'More' icon control after closing 'Choose a camera' pop-up.

**Actual Result:**
Focus doesn't retain back to the 'More' icon control after closing 'Choose a camera' pop-up.

**Expected Result:**
Focus should retain back to the 'More' icon control after closing 'Choose a camera' pop-up.
Same issue exists under 'Pair device, Delete project, Language, Report abuse, Reset, About' pop-up window.

**Note:**
Same issue exists on Firefox & Chrome.

**WCAG Reference:**
[WCAG 3.2.1 - On Focus
](https://www.w3.org/WAI/WCAG21/Understanding/on-focus.html)

**Test Environments:**
Version: 20H2 (OS Build: 19042.508)
Browser: Edge chromium DEV Build (Version 87.0.654.0), Firefox(75.0), Chrome

**Comment by Shalini3457** [comment]
Labels:
#Accessibility, #A11ySev2, #HCL, #Benchmark-HCL-MakeCode-OCT2020, #WCAG3.2.1, #Win10-Edge(Chromium)

[WCAG3.2.1_Green Screen.zip](https://github.com/microsoft/pxt-microbit/files/5508940/WCAG3.2.1_Green.Screen.zip)

**Comment by jwunderl** [comment]
the menu is not a permanent addition to the page; expectation when make a choice from a dropdown menu in an editor is typically that the menu will be dismissed.
