### ISSUE TITLE
[Keyboard Navigation – Make Code - Simulator] Keyboard focus does not remain on same control after activating.

### ISSUE THREAD

**Issue by Shalini3457** [microsoft/pxt-microbit#3628]
User Experience:
If focus order is not sequential and meaningful, then keyboard user will find hard to understand the actual flow of page and the actual feature of the page which degrades the user experience.

Note: User credentials should NOT be included in the bug.

Repro Steps:

1. Launch application URL
2. Home page will open.
3. Navigate "New Project" option and select it.
4. Editor screen will open.
5. Navigate to "Simulator" section appearing in left pane.
6. Navigate to "Start,Stop,Restart" option and select it.
7. Verify that user able to access all functionality.
8. Verify the issue.

Actual Result:
Keyboard focus does not remain on same control as 'restart the simulator' or ''launch in full screen' button after activating those buttons

Expected Result:
Keyboard focus should remain on same control as 'restart the simulator' or ''launch in full screen' button after activating those buttons

Note:

1. This issue also exists with Firefox and Chrome Browser.
2. This issue exists throughout the application

WCAG Reference:
[WCAG 3.2.1 - On Focus (06)](https://www.w3.org/WAI/WCAG21/Understanding/on-focus.html)

Test Environments:
Version: 20H2 (OS Build: 19042.508)
Browser: Edge chromium DEV Build (Version 87.0.654.0), Firefox(75.0), Chrome

**Comment by Shalini3457** [comment]
Labels:
#Accessibility, #A11ySev2, #HCL, #Benchmark-HCL-MakeCode-OCT2020, #WCAG3.2.1, #Win10-Edge(Chromium)

[Uploading MAS3.2.1_Focus moves to another control after pressing enter key.zip…]()

**Comment by jwunderl** [comment]
These buttons are both used to launch the simulator, so focus moves to the simulator when they are clicked.
