### ISSUE TITLE
Green Screen does not work/request camera

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3633]
> support  #40669

**Describe the bug**
When choosing green screen the camera selector seems to have no effect. The camera is not connected. Tis happens whether you are using an inbuilt camera or connected camera

**To Reproduce**
I go to the settings cog and select Green Screen On
![image](https://user-images.githubusercontent.com/31242877/98568620-36415200-22a9-11eb-9cc1-49dbfab4ac29.png)

Then I click GS On and get this screen
![image](https://user-images.githubusercontent.com/31242877/98568641-3d686000-22a9-11eb-9012-e727c0967a47.png)

Where I choose Camera 0 and then I get…
![image](https://user-images.githubusercontent.com/31242877/98568658-435e4100-22a9-11eb-902e-66c6bd99d86d.png)

Literally - a green screen ;-(

**Expected behavior**
Camera image is used when camera is selected.

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac
 - Browser [e.g. chrome, safari] Chrome 86

**Smartphone (please complete the following information):**

**Additional context**

**Comment by microbit-mark** [comment]
@abchatra can you take a look at this one, it's been open 11 days

**Comment by microbit-mark** [comment]
Also reproduces in iOS

**Comment by pelikhan** [comment]
I will take a look.

**Comment by pelikhan** [comment]
Fixed in 3.1.66 .
