### ISSUE TITLE
Block "on loud sound" not working as expected

### ISSUE THREAD

**Issue by ngammarano** [microsoft/pxt-microbit#3643]
**Describe the bug**
I set the loud threshold to 200, and the quiet threshold to 100.
When I lower the sound level in MakeCode simulator from >100 to <100, **both the "on loud sound" and the "on quiet sound" events are triggered**.

**To Reproduce**
1. Open [this project](https://makecode.microbit.org/_MH983xcouJC7) in [MakeCode beta](https://makecode.microbit.org/beta) (click [here](https://makecode.microbit.org/beta#pub:_MH983xcouJC7)).
2. Lower the sound level in the MakeCode simulator from >100 to <100 (100 is the quiet threshold).
3. See that both the "on loud sound" and "on quiet sound" events are triggered.

**Expected behavior**
Only the "on quiet sound" sould be triggered.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 86.0.4240.183

**Comment by abchatra** [comment]
@pelikhan is it possible to match the hardware behavior?

**Comment by ngammarano** [comment]
I think this has been corrected.
