### ISSUE TITLE
The new built in sounds for the micro:bit v2 are way too loud

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#3645]
The sounds from these blocks:

<img width="329" alt="Screen Shot 2020-11-10 at 8 44 05 AM" src="https://user-images.githubusercontent.com/13754588/98703913-e73eff80-2330-11eb-835b-206cdc500191.png">

They are too loud even if you call set volume with 1

**Comment by abchatra** [comment]
discussed in the meeting. @jaustin to send new .wav files to @pelikhan to update.

**Comment by pelikhan** [comment]
Someone from the MakeCode team could pick this up.

**Comment by abchatra** [comment]
I can update the files.

**Comment by jaustin** [comment]
Can we just check that the sound volume we care about is simulator not on the device?
Attached are a bunch of different volume reductions.
[quieter-sounds.zip](https://github.com/microsoft/pxt-microbit/files/5519774/quieter-sounds.zip)

```
for f in *.wav; do
    for vol in "0.01" "0.05" "0.1" "0.5"
    do
        sox -D -v $vol $f ${f%.*}-$vol.wav
    done
done
```

**Comment by abchatra** [comment]
This is simulator specific issue as per @riknoll and not hardware related. Is that your question @jaustin ?

**Comment by jaustin** [comment]
That was the question. Those wav files should still help based on what Peli was saying though

**Comment by pelikhan** [comment]
Misunderstanding :) The .wav files are exclusively used in the simulator and have no influence on the hardware sounds.

**Comment by abchatra** [comment]
-0.5 files are still high. I guess I will go with 0.1. @riknoll can you give it a try? 
@jaustin can we get 0.2?

**Comment by riknoll** [comment]
I can generate 0.2! I'll try it out in the browser
