### ISSUE TITLE
[Usable – Make Code – Language] Narrator announces irrelevant information after navigating 'Select language' heading in scan mode.

### ISSUE THREAD

**Issue by Shalini3457** [microsoft/pxt-microbit#3670]
**User Experience:**
User would be confused if screen reader announces irrelevant information for any control which doesn't relevant to that control and also he/she won't get the context of such irrelevant information. Not only this, they will proceed further and will miss the functionality.

**Note**: User credentials should NOT be included in the bug.

**Repro steps:**
1. Launch application URL.
2. Home page will open.
3. Navigate "New Project" option and select it.
4. Editor screen will open.
5. Navigate to "Settings" option appearing in header section and select it.
6. Navigate to "Language " option and select it.
7. Navigate through all the controls appearing under "Select Language" dialog.
8. Verify that Narrator announces irrelevant information after navigating 'Select language' heading in scan mode or not.

**Actual Result:**
Narrator announces irrelevant information as 'Selected selection contains 0 item' after navigating 'Select language' heading in scan mode.

**Expected Result:**
Narrator should not provide irrelevant information after navigating 'Select language' heading in scan mode. It should only announces visually appearing control information.

**Note:**
This issue does not exists with Firefox and Chrome Browser.

**Test Environments:**
Version: 20H2 (OS Build: 19042.508)
Browser: Edge chromium DEV Build (Version 87.0.654.0)
Screen Reader: Narrator

**Comment by Shalini3457** [comment]
Labels:
#Accessibility; #A11ySev4; #HCL; #Benchmark-HCL-MakeCode-OCT2020; #Win10-Edge(Chromium)

[Usable_Language_Irrelevant information.zip](https://github.com/microsoft/pxt-microbit/files/5529071/Usable_Language_Irrelevant.information.zip)

**Comment by jwunderl** [comment]
Appears fixed in edge update to match firefox/chrome
