### ISSUE TITLE
Android hex downloads are broken

### ISSUE THREAD

**Issue by microbit-sam** [microsoft/pxt-microbit#3674]
**Describe the bug**

Downloading programs from MakeCode in the Android app previously worked using the `data:  ;base64` URI, but this has now changed to a `blob:`

I had a look to try and find the commit where this changed but was unable to, @jaustin thinks it might have been a fix for Chrome 79

The Android WebViewClient can't access the blob, would it be possible to enable the base64 encoded hexes for urls including the `?androidapp` query string?

**To Reproduce**
1. Open the Android app
2. Open the Create Code screen
3. Hit download, the hex won't download

**Expected behavior**

A base 64 string that encodes the hex is passed as the download URI, this can be decoded by the Android app and stored as a hex file

**Comment by microbit-mark** [comment]
This is the Chrome 79 fix @microbit-sam https://github.com/microsoft/pxt/pull/7557

**Comment by jwunderl** [comment]
Is this needed for the ios app too? Or just android

**Comment by microbit-mark** [comment]
@martinwork ^

**Comment by martinwork** [comment]
In the MakeCode view (iOS 10+), the iOS app receives hex from Download and Save via host messages. The "microbithex" scheme is still implemented, but I think that was the old route. The application accepts various schemes like "data:application/x-microbit-hex;base64" for data coming from Safari, especially in iOS 9.

**Comment by jwunderl** [comment]
@martinwork then it sounds like we wouldn't need to disable the object download since you're getting it through a message? I guess the question is, is the current behavior working for the app when running /beta? If so, we're good!

If you do want me to switch it back to using data uri downloads in the ios app, I'd need the query parameter to toggle that; is it safe to assume there is an `?iosapp` being sent like the [androidapp](https://github.com/microsoft/pxt-microbit/issues/3376) flag is being sent

**Comment by martinwork** [comment]
Is "the object download" a new thing? In case I am misunderstanding, we are talking about data flowing from MakeCode to the app, right? 

I'm guessing now... Does the app need to support a new blob: scheme? From memory, the app registers a scheme so iOS knows it supports the data that MakeCode is sending.

As far as I know, it has been working, so is there any need to change any of the MakeCode/iOS App communications? 

MakeCode was already checking for iOS, and webkit host, so why need a query parameter?

When MakeCode detects iOS and webkit, it uses host messages to do Download and Save. When MakeCode is running in iOS Safari, it needs to do Download using the correct URLs so they get routed to the app.

I'll likely be running tests soon... I was hoping to wait until MakeCode switches to the new universal hex format.

The app doesn't use the WebKit window on iOS 9. Code editing is done in Safari. Is MakeCode supporting iOS 9? MakeCode beta hangs on my iOS 9 device.

**Comment by microbit-sam** [comment]
Thanks!
