### ISSUE TITLE
WebUSB flashing fails

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#3676]
**Describe the bug**
Trying to flash via WebUSB fails.
Red box with "Download fail, please try again" appears.
Errors are printed to the console.
Hex file is downloaded to the PC instead.

Tried closing and reopening the browser and unplugging and replugging the micro:bit.

**To Reproduce**
Pair and then click download

**Expected behavior**
WebUSB flashing to work

**Screenshots**

![image](https://user-images.githubusercontent.com/29712657/98960160-ffaf4580-24fb-11eb-8be7-29e899836605.png)

**micro:bit version (please complete the following information):**
V2

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 86.0.4240.183 

**Additional context**

https://makecode.microbit.org/beta
makecode.microbit.org version:  3.0.55
Microsoft MakeCode version:  6.0.32
microbit runtime version:  v2.2.0-rc6

**Comment by microbit-carlos** [comment]
I tried this with Edge Version 85.0.564.8 (Official build) Dev (64-bit) as well and have the same issue.

In one occasion it started flashing, but after a couple of seconds the same error appeared:
![image](https://user-images.githubusercontent.com/29712657/98961021-02f70100-24fd-11eb-8966-200939644f90.png)


https://makecode.microbit.org/beta
makecode.microbit.org version:  3.0.55
Microsoft MakeCode version:  6.0.32
microbit runtime version:  v2.2.0-rc6

**Comment by microbit-carlos** [comment]
WebUSB flashing from the Python editor 2.1.0-beta.6 is working though.

**Comment by pelikhan** [comment]
Please try again adding ?dbg=1 and copy the javascript console output. thanks.

**Comment by pelikhan** [comment]
Need a better repro.

**Comment by pelikhan** [comment]
No precise repro.
