### ISSUE TITLE
In-context button is not available in docs -> language dialog

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3678]
This is strange: the button "Translate this page" never shows up in the docs. Are we missing something on the backend?

https://github.com/microsoft/pxt/blob/dd50ec2dcb6194ac51614e18d6ed178ad774c95f/docfiles/langpicker.html#L16

**Comment by pelikhan** [comment]
@jwunderl

**Comment by jwunderl** [comment]
Does the ifdef need to be `<!-- @ifdef incontexttranslations -->` like https://github.com/microsoft/pxt/blob/master/docfiles/docs.html#L10? I had just copied that ifdef directly from it's previous location

**Comment by pelikhan** [comment]
incontexttranslations is set in the backend when the page needs to load the crowdin in-context javascript runtime. In this case, i would have expected this define when rendering server side but it does not seem so.

**Comment by jwunderl** [comment]
Ah, right. If you add ?translate=1 and sign it it does show up, so looks like https://github.com/microsoft/pxt-backend/blob/master/src/routing.ts#L1143 isn't getting hit -- should that be checking for `req.theme.crowdinProject` existing instead of `mdinfo.crowdinproject`?

**Comment by pelikhan** [comment]
Worth a try

________________________________

**Comment by pelikhan** [comment]
I am simply going to remove the ifdef

**Comment by pelikhan** [comment]
https://github.com/microsoft/pxt/pull/7626
