### ISSUE TITLE
[Usable – Make Code – Project Setting] Narrator focus taking extra keystroke to reached the controls in scan mode on 'Project Setting' screen.

### ISSUE THREAD

**Issue by Shalini3457** [microsoft/pxt-microbit#3688]
**User Experience:**
Screen Reader dependent users will confuse if it will take multiple keystrokes to read out the text and reached the controls.

**Note**: User credentials should NOT be included in the bug.

**Repro steps:**
1. Launch application URL.
2. Home page will open.
3. Navigate "New Project" option and select it.
4. Editor screen will open.
5. Navigate to "Settings" option appearing in header section and select it.
6. Navigate to "Project Settings" option and select it.
7. Navigate though all the controls appearing after select "Project Setting" option i.e. No Pairing Required: Anyone can connect via Bluetooth, Passkey pairing: Pairing requires 6 digit key to pair etc. 
8. Verify the issue by using narrator in scan mode.

**Actual Result:**
Narrator focus taking extra keystroke to reached the controls in scan mode on 'Project Setting' screen.

**Expected Result:**
Narrator focus should not take extra keystroke to reached the controls on on 'Project Setting' screen while navigating in scan mode.

**Note:**
1. This issue does not exists with Firefox and Chrome Browser.
2. This issue exists throughout the application.

**Test Environments:**
Version: 20H2 (OS Build: 19042.508)
Browser: Edge chromium DEV Build (Version 87.0.654.0)
Screen Reader: Narrator

**Comment by Shalini3457** [comment]
Labels:
#Accessibility; #A11ySev4; #HCL; #Benchmark-HCL-MakeCode-OCT2020; #Win10-Edge(Chromium)

[Usable_Project Setting_Extra keystoke.zip](https://github.com/microsoft/pxt-microbit/files/5535008/Usable_Project.Setting_Extra.keystoke.zip)

**Comment by jwunderl** [comment]
This appears to be behaving as expected for edge; focusing first on the whole row, then going through the elements individually. (overview -> reading label -> focusing on actionable button).
