### ISSUE TITLE
Better notches in Edge Connector V2

### ISSUE THREAD

**Issue by microbit-aimee** [microsoft/pxt-microbit#3697]
**Describe the problem**

The edge connector needs to be updated on the V2 simulator to reflect the exact shape.
 

**Describe the solution you'd like**

See the below SVG asset for the exact shape of the edge connector, we would like to see that implemented.
![image](https://user-images.githubusercontent.com/45098498/99092681-5d5d9380-25c9-11eb-8071-d93b0bfebdc3.png)

The above asset has been provided by @jaustin 

**Describe alternatives you've considered**
n/a

**Additional context**
For reference the current version looks like this in beta

![Screen Shot 2020-11-13 at 17 27 39](https://user-images.githubusercontent.com/45098498/99102274-c1865480-25d5-11eb-8fe7-486f07c4e132.png)

**Comment by pelikhan** [comment]
What is the difference?

________________________________

**Comment by microbit-aimee** [comment]
Rounded corners on the edge connector, looks less bitey

![image](https://user-images.githubusercontent.com/45098498/99104011-4e321200-25d8-11eb-8f75-3b0f7b6ba674.png)

**Comment by pelikhan** [comment]
Do you have a SVG of those corners?

________________________________

**Comment by jaustin** [comment]
SVG is in https://github.com/microsoft/pxt-microbit/issues/3538 - has V2 text and corners.
