### ISSUE TITLE
data on plot bar graph...

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#37]
expectation: You could receive data from a single micro:bit

1. open KSF, go to JS...

2 enter this code

```
basic.forever(() => {
    led.plotBarGraph(input.acceleration(Dimension.X), 1023);
});

```

3 it would be ideal to receive Excel data from a single micro:bit using acceleration, it doesn not appear possible.

**Comment by pelikhan** [comment]
Use the Windows app to receive serial data.
