### ISSUE TITLE
Change to menu text for V2 blocks

### ISSUE THREAD

**Issue by microbit-aimee** [microsoft/pxt-microbit#3700]
**Is your feature request related to a problem? Please describe.**
The text under all V2 blocks needs to change from micro:bit V2 (as in example below)

![image](https://user-images.githubusercontent.com/45098498/99104240-a8cb6e00-25d8-11eb-9bf4-1259826ef105.png)

**Describe the solution you'd like**
Text should change to micro:bit (V2) - enclosing V2 in brackets

**Describe alternatives you've considered**
n/a

**Additional context**
This aligns to our branding guidelines which request V2 is added in brackets after the word micro:bit

**Comment by pelikhan** [comment]
The purpose of this group is that indicate that those blocs are for the V2 board only.  What will ``micro:bit (V2)`` indicate? It seems that ``(V2)`` is an optional argument.

**Comment by microbit-aimee** [comment]
micro:bit (V2) is intended to indicate the same information; those blocs are for V2 only - enclosing the (V2) in brackets is simply to maintain consistency with our own guidelines

**Comment by pelikhan** [comment]
Fix in https://github.com/microsoft/pxt-microbit/pull/3720

**Comment by abchatra** [comment]
fixed
