### ISSUE TITLE
all notes sound same play melody field editor on macos safari

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#3703]
**Describe the bug**

On mac safari, all tones in the play melody and piano field editors sound the same. (e.g. clicking on red plays the same tone as clicking on green, clicking middle g sounds like high a). The simulator sounds fine, just the field editor

**To Reproduce**
1. open makecode microbit in safari on mac
2. create a new project, drag out a play melody block
3. start clicking on buttons with sound on

**Expected behavior**

each note should sound like the note that is being played

**not a regression**, though the tone is a bit deeper than it was before.

**Desktop (please complete the following information):**
 - OS: mac big sur 11.0.1
 - Browser safari
 - Version 14.0.1

**Comment by microbit-mark** [comment]
> Raised in micro:bit support #43304

Also reprodices on Safari for iOS and in the micro:bit app.

https://user-images.githubusercontent.com/31242877/108332526-cc99e380-71c7-11eb-8e0c-6b24dc355854.MP4

**Comment by Jaqster** [comment]
Had another Teacher report this same issue on iPads in her classroom.

**Comment by Jaqster** [comment]
Can we bump this up to a P1 bug?

**Comment by smith9** [comment]
Just got my micro:bit today and also experience the same thing in the iOS phone app.
Constant tone in the "play melody" editor, but ok in the simulator - steps:

1. enter visual coding screen in app
2. add play melody block to forever block
3. click on music icon in play melody block - brings up editor.
4. press gallery tab, select scale - populates the editor grid with descending note pattern
5. press grey play button, changes to a stop button, a vertical shaded bar progresses across the editor grid and a constant tone is played


Also noticed that there is no sound in the simulator until you press the speaker off and then speaker on again - steps:

1. press play button - no sound
2. click on micro:bit graphic next to stop button - shows microbit with 5 greyed out buttons at bottom of phone app
3. press speaker icon - it turns red
4. press speaker icon a second time - turns from red to a darker gray than all the other 4 buttons and music starts playing.

**Comment by abchatra** [comment]
Marked next-release.

**Comment by riknoll** [comment]
Only repros in latest Safari. I'll take a look!
