### ISSUE TITLE
Windows app: ctrl+v pastes text into searchbox

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#3705]
**Describe the bug**
If you have text copied to your clipboard and use ctrl+c ctrl+v to paste blocks, it will also paste the text into the toolbox search if previously focused. Does not appear to repro in the browser (Chrome).

**To Reproduce**
1. Open the Windows app, copy a string to your clipboard.
2. Click on the search box
3. Click on a block in the workspace, press ctrl+c ctrl+v to copy and paste
4. See that your clipboard text is also pasted to the toolbox search.

**Comment by abchatra** [comment]
Won't fix windows app issues.
