### ISSUE TITLE
Web USB connection timing out

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#3706]
The Web USB connection seems to time out.  When collecting serial data from the device, it seems to just stop.  I get a blank page for the data console view, and then the Show Console device button disappears (even though my browser is still paired to the device).
![image](https://user-images.githubusercontent.com/22108954/99107067-1b692900-259a-11eb-905f-685ed8444914.png)

**Comment by Jaqster** [comment]
This is Edge on Windows

**Comment by Jaqster** [comment]
Also, may be related - when I move off the page and come back, the Download button changes from Web USB to regular download:  
![image](https://user-images.githubusercontent.com/22108954/99107284-70a53a80-259a-11eb-9b97-811d56572639.png)

**Comment by pelikhan** [comment]
To collect WebUSB information, add ?dbg=1 to your url and copy the content of the JavaScript console. The problem here is that we disconnect from WebUSB when you leave the tab. This is a bit dubious and we might want to reconsider this since many people get confused by this behavior.

**Comment by pelikhan** [comment]
The current behavior is to shut down all webusb connections when switching tags. So this works as designed.

**Comment by abchatra** [comment]
Issue is tab switching and we disconnect immediately. 
One of the option is disconnect after 10 min of inactivity.
