### ISSUE TITLE
Serial data viewer appears blank when first visited if data isn't streaming

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#3708]
0. pair a v1 via webusb on chrome
1. load this simple program:
![image](https://user-images.githubusercontent.com/6453828/99107025-0b514980-259a-11eb-8230-deba4d70f947.png)
2. with the device paired, click the B button
3. Notice the "show device console" button appears
4. Click that button
5. See a blank page. If there's no interaction, the page stays blank. 

Step 5 is the problem. It looks broken to the user.
In the gif below I hit "B" again and this causes the page to show graphs.

![2020-11-13 10 19 21](https://user-images.githubusercontent.com/6453828/99107194-51a6a880-259a-11eb-977f-cafbb85871b1.gif)

**Comment by abchatra** [comment]
You need a writeline to flush. Known thing in these original APIS

**Comment by darzu** [comment]
Yeah but we could show something like an empty graph or message saying "waiting for data..."

**Comment by pelikhan** [comment]
I have a lot of grief with the serial view and it would be nice to make a few other improvements:
- ability to close a graph
- ability to see console full screen or graph full screen

**Comment by abchatra** [comment]
No plans to implement.
