### ISSUE TITLE
Unknown BLE characteristic in micro:bit V2

### ISSUE THREAD

**Issue by ngammarano** [microsoft/pxt-microbit#3709]
## Describe the bug
There is an unknown BLE characteristic with UUID 00002aa6-0000-1000-8000-00805f9b34fb and attribute READ under service Generic Access when using micro:bit V2 BLE. This characteristic is not present in the [micro:bit BLE profile](https://lancaster-university.github.io/microbit-docs/resources/bluetooth/bluetooth_profile.html).

## To reproduce
1. Open [this project in MakeCode editor version beta](https://makecode.microbit.org/beta#pub:_Fv82pR2UMDXe)
2. Download the project to a micro:bit V2
3. Scan the BLE services and characteristics (e.g. using Nordic Semiconductor's nRF Connect, or [with WebBLE](https://ngammarano.github.io/microbit-web-bluetooth/microbit-web-bluetooth-scan.html).

## Expected behavior
In micro:bit V1, that characteristic does not appear.

## micro:bit version
V2.00

**Comment by jaustin** [comment]
@martinwork do you know the source of the characteristic. Is it something we need to add to the profile/document properly? Or something else creeping in?

**Comment by martinwork** [comment]
00002aa6-0000-1000-8000-00805f9b34fb is not one I have come across before.
I don't see it in iOS nRF Connect. iOS keeps some characteristics hidden form CoreBluetooth apps. 

It's the Central Address Resolution characteristic, mandatory for the central role, optional for peripheral, created by softdevice and not under the application's control.


References:

https://www.bluetooth.com/specifications/assigned-numbers/service-discovery/

https://devzone.nordicsemi.com/f/nordic-q-a/21221/what-is-the-characteristic-uuid-0x2aa6-under-generic-access-service

https://devzone.nordicsemi.com/f/nordic-q-a/38478/unnecessary-central-address-resolution-characteristic-as-part-of-the-generic-access-service-breaking-hid-over-gatt-in-windows-10#:~:text=The%20Central%20Address%20Resolution%20(CAR,be%20disabled%20by%20the%20application.

**Comment by abchatra** [comment]
Question answered.
