### ISSUE TITLE
Network error when sharing >100 projects on 1 IP address

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3727]
**Describe the bug**

When students share projects 2 or 3 times in class with a teacher, on the last attempt they receive a network error

![IMG_0205](https://user-images.githubusercontent.com/31242877/99532268-f01c7a80-299b-11eb-92f0-3f8b8f3f2f63.jpg)

Is this rate-limiting and how can we improve it?

**To Reproduce**

1 public IP address

30 PCs using MakeCode

During class, students share 2-3 projects.

Teacher checks out students' work through shared links.

Students fail to share on the last project.

If you reconnect after a certain time, it will be shared.

The error appears only in the sharing function.

It seems to occur when there are around 100 shared links

**Expected behavior**

All links should be shared

**Comment by abchatra** [comment]
@eanders-MS for visibility. I am thinking we might have similar issue with login feature. Can you look at this issue? 

Simple workaround now may be to increase the limit.

@mmoskal - fyi

**Comment by mmoskal** [comment]
Script publish is throttled at 60s. You start with 1h of "credit", so in 40min you can publish 1h+40min = 100 scripts.

https://github.com/Microsoft/pxt-backend/blob/cc2bed1/node/src/sharing.ts#L494

**Comment by eanders-MS** [comment]
Does it sound reasonable to relax the cost to 15 secs? Should allow for 4x shares.
