### ISSUE TITLE
Extension using pulseIn errors 020 on V2

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3731]
**Describe the bug**

https://github.com/Seeed-Studio/pxt-grove
https://github.com/TinkerGen/pxt-Grove

On ultrasonic sensor, they get error 020. 

I can't reproduce without grove hardware, this program showed 0 on the screen for me using makecode.microbit.org/beta
![image](https://user-images.githubusercontent.com/31242877/99687253-58db2400-2a7c-11eb-867e-0fb40e2ceef6.png)

but for Seeed it errors 020

As the ultrasonic sensor is based on the API ‘pusle in (us) pin [P0] pulsed [high]’ , so they've tested the following code and still get an error E020.

![image](https://user-images.githubusercontent.com/31242877/99687488-a061b000-2a7c-11eb-9016-c65a129f0556.png)

**Comment by MiroChao** [comment]
Hi Mark,

We also tested micro.bit v1 for all the same projects and they all works well.

**Comment by MiroChao** [comment]
Any update? 

https://github.com/microbit-foundation/micropython-microbit-v2/issues/26

**Comment by markb139** [comment]
Hi,
I just received my Microbit V2. the onPulsed events don't seem to be working. I have a simple test to toggle an LED on a pulse. On V1 hardware the code works. On V2 it doesn't.

**Comment by MiroChao** [comment]
@microbit-mark @abchatra @jaustin 

Hi I've got the same **_error 020_** on V2 with the following code , the same code works well on v1.
![image](https://user-images.githubusercontent.com/11206594/100431705-7e4adc00-30d3-11eb-8985-db0939454e66.png)

**makecode.microbit.org version**:  3.0.60
**Microsoft MakeCode version**:  6.0.35
**microbit runtime version**:  v2.2.0-rc6
**microbit v2 bootloader version**: 0254

I figure this could be something related to the system memory
![image](https://user-images.githubusercontent.com/11206594/100431870-b7834c00-30d3-11eb-997d-c202a27b4110.png)

**Comment by MiroChao** [comment]
The error only appears when the _pins.pulseIn(DigitalPin.P1, PulseValue.High)_  runs multiple times in a loop

![image](https://user-images.githubusercontent.com/11206594/100433621-48f3bd80-30d6-11eb-9dba-037aafdb46f5.png)

**Comment by 4tronix** [comment]
This is also seen in #3785 
https://github.com/microsoft/pxt-microbit/issues/3785#issue-754231515

Critical

**Comment by abchatra** [comment]
@jaustin what is the plan for this issue?

**Comment by jaustin** [comment]
@abchatra I think the fix in https://github.com/microsoft/pxt-microbit/issues/3785#issuecomment-736839719 should work for the 020 issue. @finneyj will  v0.2.23 be out this week? Are you waiting for other things before it?

**Comment by finneyj** [comment]
Yes - looking to tag v0.2.23 today.

**Comment by MiroChao** [comment]
@finneyj How do we know it's updated to v0.2.23 ? I didn't find any versions related to this.
![image](https://user-images.githubusercontent.com/11206594/101141675-95e41080-364f-11eb-8d4e-43a3645a7f9e.png)

**Comment by finneyj** [comment]
Hi @MiroChao 

I'm not sure how MakeCode surfaces the v2 version number. v2.2.20-rc6 is the equivalent v1 version. It would be good to surface the v2 version too for tracking. Perhaps @abchatra can advise here?

We're just in final testing of the v0.2.23 this morning to ensure the pulse input code is now working fully for a range of applications. I'm hoping to release very soon today. I'm sure the MakeCode team will then pick up that version into beta as soon as they can.

**Comment by finneyj** [comment]
@MiroChao @4tronix 

Just FYI, v0.2.23 of codal-microbit-v2 now released which I hope will resolve these issues for you. @4tronix - we tested on one of your boards too.

I'm sure the MakeCode team will pull this onto /beta when they can.

**Comment by MiroChao** [comment]
@finneyj Hi, thanks for the update.
@abchatra Hi, it seems /beta is still v2.2.20-rc6, will the v0.2.23 of codal-microbit-v2 be updated this week?

**Comment by pelikhan** [comment]
Try https://makecode.microbit.org/beta v3.0.62 which points to codal-v2 v0.2.23

**Comment by MiroChao** [comment]
> Try https://makecode.microbit.org/beta v3.0.62 which points to codal-v2 v0.2.23

Hi @pelikhan , just tested it on V2, the pulse function seems working now, but for the same code, I got different reading on V2.
Still V1 is working well, but for V2 with ultrasonic sensor, I get a faulty result.

**Comment by markb139** [comment]
This fixes the issues I was seeing where there was no Pulse events.

**Comment by pelikhan** [comment]
@finneyj

**Comment by finneyj** [comment]
Hi @MiroChao 

Can you please check that v2 is returning a result that is faulty?  I suspect it may be the opposite. We have had reports of v1 running slow on pulse measurements. 

We have some discussions of if/how we should align v1, pending a v1 update from @martinwork.

**Comment by martinwork** [comment]
https://github.com/TinkerGen/pxt-Grove/blob/master/grove.ts#L159
This code is applying an extra factor to the distance = time/58 calculation, which is not necessary with V2.

The V1 update is being tested. Meanwhile, I think ( control.ramSize() > 0x4000) could be used to detect V2.

**Comment by finneyj** [comment]
Thanks for confirming @martinwork - really useful to know.

**Comment by MiroChao** [comment]
@finneyj  @martinwork If v1 and V2 are getting different result, can we detect V2 so that we can change the algorithm?

**Comment by abchatra** [comment]
@pelikhan is there a way to add a typescript API to query v1 or v2?

**Comment by microbit-mark** [comment]
CODAL v0.2.24 has now been released to https://makecode.microbit.org/stable can you check here to see if this still reproduces @MiroChao

**Comment by tsadowski** [comment]
Hello,
the STABLE release crashes for me reproducably at the second invocation but the current BETA seems to work fine.

**Comment by microbit-mark** [comment]
@tsadowski Can you provide a bit more info about the crash? Is this the 020 error on the hardware when using PulseIn or a browser issue? If it's a browser issue can you try running with the debug mode on https://makecode.microbit.org/stable#editor?dbg=1 and paste the console output from the browser when it crashes.

**Comment by tsadowski** [comment]
The 020 error appears with larger programs even when not connected to the computer. It also appeared when I tried to get the device console. There was no output on the console.

 I have a simple test program. There should be a measurement every 2 seconds. With the stable release I get:
Heart, Small Heart, distance in the serial terminal, Heart, Small Heart, Program Stops - all LEDs dark.

The program runs continuously with the beta release. However I get "Sim error: noresume" in the browser. 


let dist = 0
function Distanz () {
    pins.setPull(DigitalPin.P1, PinPullMode.PullNone)
    pins.digitalWritePin(DigitalPin.P1, 0)
    control.waitMicros(2)
    pins.digitalWritePin(DigitalPin.P1, 1)
    control.waitMicros(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    dist = pins.pulseIn(DigitalPin.P1, PulseValue.High)
}
basic.forever(function () {
    basic.showIcon(IconNames.Heart)
    basic.pause(1000)
    basic.showIcon(IconNames.SmallHeart)
    basic.pause(1000)
    Distanz()
    serial.writeValue("dist", dist)
})

**Comment by microbit-mark** [comment]
**stable**
@tsadowski I can't reproduce this in https://makecode.microbit.org/stable#editor with a V2 micro:bit. I don't get a 020 error for your code example and it seems to run as expected. What browser version, OS and device are you using with MakeCode?

**beta**
> The program runs continuously with the beta release. However I get "Sim error: noresume" in the browser.
This reproduces here for me.

**Comment by abchatra** [comment]
fixed
