### ISSUE TITLE
Improve download to device workflow when using WebUSB

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3734]
**Is your feature request related to a problem? Please describe.**

I've had a few issues raised from confused teachers and students who can no longer find downloaded hex files where they expect them. This is because they have paired the device with the browser via USB and the program is directly downloaded to the micro:bit. Whilst this is an easier workflow than using drag and drop, there are times when it is useful for the teacher or student to save the hex file so they can use it again in the next lesson.

It's not obvious that you can use the save to disk icon for this or disconnect the device/webUSB and then download. 

**Describe the solution you'd like**

Could we add a save to PC/device option to the Download more options menu, something like:

<img width="885" alt="image" src="https://user-images.githubusercontent.com/31242877/99779945-b9667180-2b0d-11eb-8079-1dda30736414.png">

We could even remove the floppy disk icon, or just move it into this menu.

**Describe alternatives you've considered**
Tell people somewhere in the editor that they should unplug the device or disconnect webUSB to download a file to disk?

**Additional context**

**Comment by abchatra** [comment]
There is a save button to save right?

**Comment by microbit-mark** [comment]
There is the floppy disk icon, but users may not be familiar with this and prior to moving the WebUSB connection to the download button, you could press Download and it would save the file to the computer.

If someone else uses the same computer and micro:bit, the browser retains the pairing, so again it's not obvious what happened to the old download function.

It seems strange to have it in a separate floppy disk button.

An alternative would be to facilitate disconnecting WebUSB in the editor as we have done with python.microbit.org

**Comment by microbit-mark** [comment]
This is still confusing people. It's not obvious that you are connected via webUSB or if you are, it's not clear what that means in terms of your .hex file, so an option to disconnect and/or use the download button to actually download a file to the machine would be handy. Is this one being considered for the upcoming release @abchatra @Jaqster?

**Comment by abchatra** [comment]
Yes we are going to evaluate all webusb related issues this release.

**Comment by abchatra** [comment]
Needs a design.

**Comment by abchatra** [comment]
Fixed
