### ISSUE TITLE
Ignore disabled extension list in /beta

### ISSUE THREAD

**Issue by microbit-sam** [microsoft/pxt-microbit#3735]
**Is your feature request related to a problem? Please describe.**

Would it be possible to ignore the disabled extension list in /beta

This would allow extension creators to validate their fix in the latest MakeCode build before requesting that they be renabled

**Comment by abchatra** [comment]
This is a good suggestion.

**Comment by abchatra** [comment]
This is asking for to ignore disable variants in /beta.
