### ISSUE TITLE
Remove BitCommander release 1.1.1 From List of Disabled Extensions

### ISSUE THREAD

**Issue by 4tronix** [microsoft/pxt-microbit#3736]
**Describe the bug**
Bit Commander extension 1.1.0 was incompatible with Microbit v2 software. This has been fixed in release 1.1.1 but gives Error 927

**To Reproduce**
1. Load extension for BitCommander, now at release 1.1.1
2. Download code to the Microbit v2 (any code - it doesn't matter what)
3. Microbit v2 will display E927

**Expected behavior**
Code should run normally. E927 should NOT be displayed

Remove BitCOmmander extension release 1.1.1 from list of excluded extensions

**Comment by 4tronix** [comment]
Any prgress on re-enabling this extension? It was disabled immediately, but re-enabling takes too long :(

**Comment by abchatra** [comment]
Fixed
