### ISSUE TITLE
'on logo released' event not always triggered

### ISSUE THREAD

**Issue by microbit-giles** [microsoft/pxt-microbit#3738]
**Describe the bug**
With this program, if you tap the logo twice quickly the heart gets stuck on the display, suggesting one of the 'on logo released' events is not being triggered.
![touch heart makecode blocks](https://user-images.githubusercontent.com/42380137/99812671-a6b86080-2b3e-11eb-8813-e25a798d2597.png)

**To Reproduce**
1. Go to MakeCode editor, create blocks above and flash to micro:bit 
2. Repeatedly tap twice quickly on touch logo sensor on V2 micro:bit 
3. See heart icon get stuck (resets if you touch again)

**Expected behavior**
I'd expect the heart always to vanish when you let go.

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**micro:bit version (please complete the following information):**
V2.00 RC1

**Desktop (please complete the following information):**
Happens regardless of OS version

**Additional context**

Hex file:
[makecode-touch-heart-11Nov20.hex.zip](https://github.com/microsoft/pxt-microbit/files/5574198/makecode-touch-heart-11Nov20.hex.zip)

Video showing project in use:
https://youtu.be/icW_JmWsrA8

**Comment by jaustin** [comment]
@finneyj could this be an issue with queueing? Any chance we only queue one of each type of event?

**Comment by finneyj** [comment]
I don't think so, no. this works as expected:

```
void onFaceDown(MicroBitEvent e)
{
    DMESG("TOUCH: DOWN");
}

void onFaceUp(MicroBitEvent e)
{
    DMESG("TOUCH: UP");
}

void onADown(MicroBitEvent e)
{
    DMESG("A: DOWN");
}

void onAUp(MicroBitEvent e)
{
    DMESG("A: UP");
}

int 
main()
{
    uBit.init();

    uBit.messageBus.listen(MICROBIT_ID_BUTTON_A, MICROBIT_BUTTON_EVT_DOWN, onADown);
    uBit.messageBus.listen(MICROBIT_ID_BUTTON_A, MICROBIT_BUTTON_EVT_UP, onAUp);
    uBit.messageBus.listen(MICROBIT_ID_FACE, MICROBIT_BUTTON_EVT_DOWN, onFaceDown);
    uBit.messageBus.listen(MICROBIT_ID_FACE, MICROBIT_BUTTON_EVT_UP, onFaceUp);

    while(1)
        uBit.sleep(1000);

}
```

"Show icon" adds a delay afterwards though doesn't it? 

Event handlers are (by default) configured an non-reentrant. So the second "touched" event handler won't fire until the first has completed.... but the same is not true of the "clear screen" operation, which will complete almost instantaneously....

If you're quick with your finger's I'm guessing your "released" event could get processed before the its corresponding "touched" event has finished?

**Comment by abchatra** [comment]
@microbit-giles  is this still an issue?

**Comment by microbit-giles** [comment]
Just tested again with a freshly-made new project in https://makecode.microbit.org/#editor and the heart still gets stuck on the display if I tap twice quickly.

**Comment by finneyj** [comment]
I think this is to be expected...  the issue is mostly likely the implicit delay in the show icon code.  Therefore your event handler for "on logo touched" doesn't complete until a while after it displays a heart.  The "on logo released" however completes almost instantaneously. 

If you're quick, you can therefore process both "released" events before the second "touched" event is processed. This works a charm:

![image](https://user-images.githubusercontent.com/11539567/107402648-20d40200-6afc-11eb-9677-b46e4e119812.png)

**Comment by finneyj** [comment]
This does beg the question of whether "clear screen" should implicitly stop any ongoing animation effects... but I think i'd be very cautious about changing such a well used API at this stage!

**Comment by microbit-giles** [comment]
Thanks Joe that makes sense - I agree that we should not change the behaviour of the clear screen block at this stage, but perhaps consider this for the future. Closing this issue.
