### ISSUE TITLE
override of handler doesn't work on micro:bit V2

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt-microbit#3742]
See the following program: https://makecode.microbit.org/_R0Hgt6f31eJ5:

```
// first press of A -> Happy Face
input.onButtonPressed(Button.A, function () {
    basic.showIcon(IconNames.Happy)
    // subsequent press of A -> Sad Face
    input.onButtonPressed(Button.A, function () {
        basic.showIcon(IconNames.Sad)
    })
})
```

Correct behavior is shown in simulator:
- first press of A button yields smile face 
- subsequent presses yield frown face:

Correct behavior on V1.

On V2, the second register of A handler is ignored.

**Comment by mmoskal** [comment]
https://github.com/microsoft/pxt-microbit/blob/master/libs/core/codal.cpp#L98

**Comment by finneyj** [comment]
I've just done a little testing C++ side against v0.2.23... and I'm afraid I can't repro this. 

There are three tests listed below that all seem to work as expected. I think the last one is a pretty faithful equivalent to what MakeCode is doing. Have I missed anything?


```
void
onClick1(MicroBitEvent)
{
    DMESG("CLICK1");
}

void
onClick2(MicroBitEvent)
{
    DMESG("CLICK2");
}

void test_handlers()
{

    DMESG("EVENT_HANDLER_TEST:");

    while(1)
    {
        uBit.messageBus.ignore(uBit.buttonA.id, MICROBIT_BUTTON_EVT_CLICK, onClick2);
        uBit.messageBus.listen(uBit.buttonA.id, MICROBIT_BUTTON_EVT_CLICK, onClick1);
        uBit.sleep(2000);

        uBit.messageBus.ignore(uBit.buttonA.id, MICROBIT_BUTTON_EVT_CLICK, onClick1);
        uBit.messageBus.listen(uBit.buttonA.id, MICROBIT_BUTTON_EVT_CLICK, onClick2);
        uBit.sleep(2000);
    }
}
```


```
void onClick1(MicroBitEvent);
void onClick2(MicroBitEvent);

void
onClick1(MicroBitEvent)
{
    DMESG("CLICK1");
    uBit.messageBus.ignore(uBit.buttonA.id, MICROBIT_BUTTON_EVT_CLICK, onClick1);
    uBit.messageBus.listen(uBit.buttonA.id, MICROBIT_BUTTON_EVT_CLICK, onClick2);
}

void
onClick2(MicroBitEvent)
{
    DMESG("CLICK2");
    uBit.messageBus.ignore(uBit.buttonA.id, MICROBIT_BUTTON_EVT_CLICK, onClick2);
    uBit.messageBus.listen(uBit.buttonA.id, MICROBIT_BUTTON_EVT_CLICK, onClick1);
}

void test_handlers()
{

    DMESG("EVENT_HANDLER_TEST:");
    uBit.messageBus.ignore(uBit.buttonA.id, MICROBIT_BUTTON_EVT_CLICK, onClick2);
    uBit.messageBus.listen(uBit.buttonA.id, MICROBIT_BUTTON_EVT_CLICK, onClick1);

    while(1)
    {
        uBit.sleep(2000);
    }
}
```

This works as expected too, and provides the correct parameter to the event handler:

```
void onClick1(MicroBitEvent, void *);
void onClick2(MicroBitEvent, void *);
void *cb_arg1 = (void *) 0x12345678;
void *cb_arg2 = (void *) 0x87654321;

void
onClick1(MicroBitEvent, void *a)
{
    DMESG("CLICK1: %p", a);
    uBit.messageBus.ignore(uBit.buttonA.id, MICROBIT_BUTTON_EVT_CLICK, onClick1);
    uBit.messageBus.listen(uBit.buttonA.id, MICROBIT_BUTTON_EVT_CLICK, onClick2, cb_arg2);
}

void
onClick2(MicroBitEvent, void *a)
{
    DMESG("CLICK2: %p", a);
    uBit.messageBus.ignore(uBit.buttonA.id, MICROBIT_BUTTON_EVT_CLICK, onClick2);
    uBit.messageBus.listen(uBit.buttonA.id, MICROBIT_BUTTON_EVT_CLICK, onClick1, cb_arg1);
}

void test_handlers()
{
    DMESG("EVENT_HANDLER_TEST:");
    uBit.messageBus.ignore(uBit.buttonA.id, MICROBIT_BUTTON_EVT_CLICK, onClick2);
    uBit.messageBus.listen(uBit.buttonA.id, MICROBIT_BUTTON_EVT_CLICK, onClick1, cb_arg1);

    while(1)
    {
        uBit.sleep(2000);
    }
}
```

**Comment by mmoskal** [comment]
well, makecode only ever uses the a single handler, but changes the argument; now sure how that would be different though...

**Comment by finneyj** [comment]
ahh, yes. Thanks. That's it actually! Thanks @mmoskal 

Quite the corner case...  I'll look into it. 
I suspect it's because deletions of event handlers are deferred when a fiber is active inside that handler.

**Comment by finneyj** [comment]
Thanks @mmoskal @tballmsft 

There was an optimization pathway for resurrecting event handlers that were scheduled for removal... it wasn't correctly honouring changes in the callback argument. Fixed in https://github.com/lancaster-university/codal-core/commit/f484d8d500b454e6fa288b208df41f20f0200315

This will make it's way into the next codal-microbit-v2 tag when it's released, which will be v0.2.24

**Comment by microbit-mark** [comment]
Tried this on V1 and V2 in https://makecode.microbit.org/stable#editor and it seems to work as expected. Can you confirm @tballmsft?

**Comment by abchatra** [comment]
This is fixd in v0.2.24.
