### ISSUE TITLE
function to determine which version of micro:bit is present

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt-microbit#3743]
I would like to write a program that uses micro:bit V2 play API (Giggle, for example), but still works on V1. So, I need a function to determine which micro:bit is running my program (V1 or V2).

**Comment by mmoskal** [comment]
`control.ramSize()` may be good

**Comment by abchatra** [comment]
Request is for typescript API for microbit version?

**Comment by abchatra** [comment]
@finneyj we are planning to build an API called control.hardwareVersion() for extension authors to have different behavior in v1 vs v2.  Is there way to get the exact hardware version?

Current implementation plan looks like this:

```C++
#CODAL 
  return 2
#else                       
  return 1
```
Exact hardware version would be great to be future proof .

**Comment by abchatra** [comment]
@tballmsft your job to test the API :-)

**Comment by finneyj** [comment]
apologies @abchatra  - I meant to get back to you on this on Monday. It looks like you have this in hand MakeCode side now, but for future reference:

For v2 we have a hardware version baked into the PCB, and interface firmware version which can be extracted from here at runtime: https://github.com/lancaster-university/codal-microbit-v2/blob/master/inc/MicroBitPowerManager.h#L187

We could wrap this in a static function also exposed on v1 if that would help (although we could only get major version number for v1 accurately).

If you need compile time version checking, I'd also be happy to add a #define for you on both v1 and v2.

**Comment by abchatra** [comment]
Thanks @finneyj. I think it is sufficient if there is an API in codal, I don't think specific v1 version is necessary.

@livcheerful can we use this function in #codal case?

**Comment by finneyj** [comment]
no worries @abchatra

@livcheerful FYI - there's already an instance of this class in the MicroBit singleton, so this should get you what you need:

`uBit.power.getVersion();`

I seem to recall the values returned from the hardware are a little cryptic. @carlosperate may be able to comment on whether we have a look up table defined to map them to the version number printed on the silkscreen on the PCB (like v2.00 etc).

**Comment by martinwork** [comment]
Related: https://github.com/lancaster-university/codal-microbit-v2/issues/77#issuecomment-855238467
