### ISSUE TITLE
Offline: app errors on windows 10 edu

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3746]
> micro:bit support #40988

**Describe the bug**

User has downloaded the offline app and is presented with an error when trying to run it

![image](https://user-images.githubusercontent.com/31242877/99978346-bed9eb00-2d9d-11eb-91ca-59437c228b0d.png)
 

Meta info: Chrome 86.0.4240.198, Windows 10 Edu

**Comment by jwunderl** [comment]
Should be fixed in the next patch release ~

**Comment by abchatra** [comment]
fixed. please verify
