### ISSUE TITLE
Editor hangs on compilation screen

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3747]
> micro:bit support 40963

**Describe the bug**

> Hi, i tried to download a project to my microbit as usual, however, it keeps staying on the compiling page and could not move on as usual. i tried to reboot and resave the file for many times but no luck. Is this because the project is too big in size? or what? But i've successfully downloaded it before and don't understand why fail in recent attempt. Would you pls help. Below is the project for your reference. 

**To Reproduce**
OPen https://makecode.microbit.org/_VA1UERV3Ae4z
Click download

https://github.com/d3jd/ir >> adding this extension on it's on causes the issue. It is not approved and uses C++ so may need updating. Removing this extension fixes

**Expected behavior**
Program compiles or fails with an error

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

Console output
![image](https://user-images.githubusercontent.com/31242877/99981709-a4a20c00-2da1-11eb-8fef-76a05f43e9ab.png)

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Program is using:

 https://github.com/DFRobot/pxt-motor
https://github.com/51bit/DFPlayerMini
https://github.com/microsoft/pxt-sonar
https://github.com/d3jd/ir >> adding this extension on it's on causes the issue.

**Comment by abchatra** [comment]
This is again an extension issue.  Please ask the extension author to do the following to work on v1 for now until they fix v2. 
https://github.com/TinkerGen/pxt-BitPlayer/pull/2

**Comment by abchatra** [comment]
"disablesVariants": [
        "mbcodal"
     ]
