### ISSUE TITLE
MakeCode keeps compiling forever after adding the extension

### ISSUE THREAD

**Issue by MiroChao** [microsoft/pxt-microbit#3749]
**Describe the bug**
I tried to test if our extension works on micro:bit V2, the MakeCode editor works as normal before I added the extension. However, after the extension is added, it fails to compile even with zero code blocks, 
![image](https://user-images.githubusercontent.com/11206594/100070418-df28a900-2e74-11eb-9472-1bdfcaa510e2.png)
![image](https://user-images.githubusercontent.com/11206594/100070685-27e06200-2e75-11eb-9602-5e2c53d70351.png)

**To Reproduce**
1. Go to 'https://makecode.microbit.org' or 'https://makecode.microbit.org/beta'
2. Add the extension 'https://github.com/TinkerGen/pxt-BitPlayer'
3. Click 'compile' to download the '.hex' file
4. The editor keeps compiling...

**micro:bit version (please complete the following information):**
micro:bit V2

**Desktop (please complete the following information):**
 - Browser: Chrome  v86.0.4240.198

**Additional context**

**Comment by jaustin** [comment]
@mmoskal is this compile-service related or is there something else happening here?

**Comment by microbit-mark** [comment]
I think this is the same as https://github.com/microsoft/pxt-microbit/issues/3747 and I have also had a report that adding https://github.com/xinabox/pxt-CW01 (unapproved extension) also results in this issue.

**Comment by mmoskal** [comment]
I have no access to the compile service, @abchatra  ?

**Comment by abchatra** [comment]
This is because this extension doesn't build due to v2 changes. I have put a PR in the extension repo. https://github.com/TinkerGen/pxt-BitPlayer/pull/2

This is an issue with the extension

**Comment by abchatra** [comment]
This extension is not allow listed extension.

**Comment by MiroChao** [comment]
> This extension is not allow listed extension.

Does it has to be allowed to work? I've merged your pull request, but the problem still exist.

**Comment by abchatra** [comment]
No it doesn't need to be allow listed. You need to make the required change in pxt.json if it is not allow listed. My PR does that.
