### ISSUE TITLE
Remove Kitronik ZIP Tile extension 0.1.0 from disabled list

### ISSUE THREAD

**Issue by AlasdairAtKitronik** [microsoft/pxt-microbit#3750]
**Describe the bug**
When programs using the Kitronik ZIP Tile extension (https://github.com/KitronikLtd/pxt-kitronik-zip-tile) are downloaded to a V2 micro:bit, E927 is immediately displayed on the screen. 
The ZIP Tile extension was updated to be V2 compatible, tested in /beta and checked by @microbit-sam (https://github.com/KitronikLtd/pxt-kitronik-zip-tile/issues/3). 

**To Reproduce**
1. Go to live MakeCode.
2. Create a new project and add in the Kitronik ZIP Tile extension.
3. Write a program which involves scrolling text.
4. Download to V2 micro:bit and see E927 scroll across micro:bit display.

**Expected behavior**
The program should run as it is written (like it does on a V1 micro:bit).

**Comment by AlasdairAtKitronik** [comment]
@abchatra @mmoskal 
From what I'm reading here: https://github.com/microsoft/pxt-microbit/pull/3726
The minimum version tag needs to be:
```javascript
"min:v0.1.0"
```

**Comment by abchatra** [comment]
Fixed
