### ISSUE TITLE
Remove Kitronik :GAME ZIP64 extension 0.1.0 and :GAME Controller 0.0.2 from disabled extensions list

### ISSUE THREAD

**Issue by AlasdairAtKitronik** [microsoft/pxt-microbit#3751]
**Describe the bug**
The Kitronik :GAME ZIP64 (https://github.com/KitronikLtd/pxt-kitronik-zip-64) and :GAME Controller (https://github.com/KitronikLtd/pxt-kitronik-game-controller) extensions have been disabled for V2 micro:bit due to C++ issues with the use of "MicroBitButton". These have now been fixed in CODAL, and are just waiting to be pulled into MakeCode (see comments by @microbit-sam https://github.com/KitronikLtd/pxt-kitronik-zip-64/issues/2 - relating to both extensions).

**Comment by AlasdairAtKitronik** [comment]
@abchatra @mmoskal 
From what I'm reading here: https://github.com/microsoft/pxt-microbit/pull/3726
The minimum version tags need to be as follows:
For ZIP64:
```javascript
"min:v0.1.0"
```

For Controller:
```javascript
"min:v0.0.2"
```

**Comment by abchatra** [comment]
Fixed
