### ISSUE TITLE
Makecode microbit taking forever to compile

### ISSUE THREAD

**Issue by KalbeAbbas** [microsoft/pxt-microbit#3755]
Microbit makecode editior is taking forever to compile extension containing cpp files. I tried to build both locally on PC and with microbit.makecode.com online editor. 

![](https://aws1.discourse-cdn.com/standard14/uploads/makecode/original/2X/d/df06c8d0a5d1d744f0c81796d7b6780931025916.png)

![](https://aws1.discourse-cdn.com/standard14/uploads/makecode/original/2X/e/ee1d0fe6bb68ccb695b1d299f0cd7fd881668a2b.png)

**Comment by jaustin** [comment]
@abchatra this looks like the compile service is the issue here too

**Comment by abchatra** [comment]
Compile service is up and running. Can you share the program? Likely extension is not compiling

**Comment by KalbeAbbas** [comment]
@abchatra https://github.com/xinabox/pxt-IM01

It used to work with the old microbit. Thanks

**Comment by abchatra** [comment]
We released v2 support in our editor last week. By default we build both on v2 & v1 hardware. If you don't want to build on v2 hardware right away, you can disable it for v2 by add the following to your extension. Then you should be able to just compile for v2.

```
    "disablesVariants": [
        "mbcodal"
     ]
```
See this PR for example: https://github.com/TinkerGen/pxt-BitPlayer/pull/2/files

**Comment by KalbeAbbas** [comment]
Thanks lot :)

**Comment by KalbeAbbas** [comment]
The server is running now and can compile with online editior. But, now I can't compile on my with `pxt build `command and is continuous polling. This is again with cpp files:

![image](https://user-images.githubusercontent.com/49709412/100317944-056a5800-2fdf-11eb-8562-cade1dbb6bf3.png)

Note that the repo I am using here doesn't contain any mbed dependencies. It contains cpp files.

**Comment by KalbeAbbas** [comment]
Reported this on new issue: https://github.com/microsoft/pxt-microbit/issues/3770#issue-751352884
