### ISSUE TITLE
Add CODAL version to About

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#3764]
**Is your feature request related to a problem? Please describe.**
I would like to be able to easily check which CODAL version is being used.

**Describe the solution you'd like**
Should the About box have a CODAL link below the DAL link?

**Describe alternatives you've considered**
None.

**Comment by abchatra** [comment]
- This is implemented but will be in the next summer release.

**Comment by microbit-mark** [comment]
@abchatra Any reason this can't be added sooner? It would really help when supporting people.

**Comment by microbit-mark** [comment]
Now in beta makecode.microbit.org/beta thanks @abchatra  

![image](https://user-images.githubusercontent.com/31242877/104425934-2c71ee80-5579-11eb-995c-4d85202df5eb.png)

**Comment by jaustin** [comment]
@abchatra it would still be really useful to have this cherry-picked into the stable branch if at all possible. I know it's only several clicks away but it's quite a step for many people to find the right location and it's extremely useful for us doing support to be able to ask people this information etc. 

Here's how you *do* find the information, in case you're new to this :)

![Uploading codal version.gif…]()

**Comment by abchatra** [comment]
Implemented in /beta
