### ISSUE TITLE
[new] Compilation taking forever for extension built with pxt CLI

### ISSUE THREAD

**Issue by KalbeAbbas** [microsoft/pxt-microbit#3770]
**Describe the bug**
Compilation for microbit makecode for extension containing cpp files taking forever when built on PC using pxt CLI

**To Reproduce**
1. Setup pxt toolchains as described in the [Command Line Tool](https://makecode.com/clil) 
2. Inside the `microbit `folder create `projects `folder
3. git clone this [repo](https://github.com/xinabox/pxt-SG35.git)
4. Inside the repo folder enter the command `pxt install` to install all the deps
5. Enter command `pxt build`. The CLI shows continuous polling screen now

**Expected behavior**
Polls continuously compilation service

**Screenshots**
![image](https://user-images.githubusercontent.com/49709412/100319689-ddc8bf00-2fe1-11eb-8a08-5c22bd40075b.png)

**micro:bit versions:**:
1. target version 3.0.61
2. pxt-core version 6.0.35

**Desktop**
 - Windows 10

**Comment by KalbeAbbas** [comment]
Seems that the issue is not only with pxt CLI. Its also happening on Github CI with newly created cpp extension:

![image](https://user-images.githubusercontent.com/49709412/100324106-8d089480-2fe8-11eb-8273-a2ba3106d62b.png)

https://github.com/KalbeAbbas/pxt-test-itr-repo/runs/1457708983

**Comment by KalbeAbbas** [comment]
Seems that only cached cpp extensions are compiling, with a very fast which seems abnormal to me. Previously the fast compilation was happening with pure TypeScript extensions.

**Comment by KalbeAbbas** [comment]
Here is the list of some extensions compiling fine and taking forever with online editor:

Compiling fine:
* https://github.com/xinabox/pxt-in-the-air-microbit2
* https://github.com/xinabox/pxt-IM01-2
* https://github.com/xinabox/pxt-SG35

Taking forever:
* https://github.com/xinabox/pxt-SG34
* https://github.com/xinabox/pxt-SL25
* https://github.com/xinabox/pxt-RL0x
* https://github.com/xinabox/pxt-CW01
* https://github.com/xinabox/pxt-IM01

Besides, the compiling ones seems to be giving cached extension as they are compiled very quickly.

**Comment by abchatra** [comment]
These extensions don't work on v2 hardware, please disable their compilation on v2 hardware by specifying the
```
    "disablesVariants": [
        "mbcodal"
     ]
```

**Comment by abchatra** [comment]
For how to fix the extension for v2 hardware as well, contact microbit support.
