### ISSUE TITLE
Embedded code breaks in Chrome

### ISSUE THREAD

**Issue by DaveAtKitronik** [microsoft/pxt-microbit#3771]
this url: https://kitronik.co.uk/blogs/resources/distance-sensing-microbit-hc-sr04-module
contains some sample code in an embedded frame.
the page appears to be fine in chrome and edge, but there are errors in the dev console. 
However opening in Chrome in incogneto mode breaks the code:
![image](https://user-images.githubusercontent.com/25896029/100333282-4e63e180-2fca-11eb-9ffc-36b9305da6fa.png)

Edge private browsing appears ok.

Windows 10, Chrome: 86.0.4240.198, Edge 86.0.0622.69

possibly related to #3386

**Comment by abchatra** [comment]
This is fixed. If not let us know
