### ISSUE TITLE
Error message when adding bluetooth dependency to tutorial

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3776]
> microbit-support: #41060

**Describe the bug**

Loading https://makecode.microbit.org/beta#tutorial:github:gitalm/microbit--phyphox-tutorial/tutorial results in 

![image](https://user-images.githubusercontent.com/31242877/100463307-8a2ea200-30c3-11eb-99d4-f3a6b851820e.png)

**To Reproduce**
Include Bluetooth dependency in tutorial as described in https://makecode.com/writing-docs/macros#dependencies

```package
bluetooth
```

**Expected behavior**
Tutorial loads with Bluetooth enabled

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by microbit-mark** [comment]
@pelikhan @abchatra please take a look when you get the chance.

**Comment by microbit-mark** [comment]
nudging this one @abchatra can you assign and prioritise as appropriate

**Comment by abchatra** [comment]
Following repo is not accessible for me.
gitalm/microbit--phyphox-tutorial/tutorial

**Comment by abchatra** [comment]
No additional information given.
