### ISSUE TITLE
Pin pulse event module not available

### ISSUE THREAD

**Issue by tangjie133** [microsoft/pxt-microbit#3782]
Pin pulse event module not available.
V1 version of the microbit can be used normally, V2 can not, please solve as soon as possible.
![QQ截图20201201144105](https://user-images.githubusercontent.com/51323906/100706101-5fa25900-33e3-11eb-9fb8-64854b034e08.png)

**Comment by microbit-mark** [comment]
> micro:bit support:  #41184

Also raised in micro:bit support testing P0

**Comment by tangjie133** [comment]
How long can this problem be solved.

**Comment by microbit-mark** [comment]
CODAL v0.2.24 has now been released to https://makecode.microbit.org/stable can you check here to see if this still reproduces @tangjie133?

**Comment by abchatra** [comment]
Fixed
