### ISSUE TITLE
Editor not loading for students

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3784]
> micro:bit support # 41015

Reported 26th Nov

**Describe the bug**

- using school office PC,  browsing the website works well  
- This issue occurs in the computer classroom:

- Teacher end  PC at school  computer classroom work well (but needed a little bit time)
- Student end PCs at school  computer classroom can not work well (over 30 minutes still can not local the editor)

Users are in Taiwan.

**To Reproduce**

Try to load makecode.microbit.org in Chrome

**Expected behavior**
Loads as expected on all PCs

**Screenshots**

![image](https://user-images.githubusercontent.com/31242877/100715591-51d2e080-33af-11eb-9e36-9a11a6653af9.png)

![image](https://user-images.githubusercontent.com/31242877/100715618-5c8d7580-33af-11eb-9a5a-6f3fc1fc160f.png)

![image](https://user-images.githubusercontent.com/31242877/100715644-6616dd80-33af-11eb-972e-a9721f7b0b2b.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 87

**Comment by abchatra** [comment]
Can't repro. Likely network issue.

**Comment by microbit-mark** [comment]
This is still reproducing. Any idea what the network issue might be @abchatra ?

- test upload and download speed it ok
- recheck firewall setting
- recheck win10 upgrade...

**Comment by abchatra** [comment]
Are all the sites unblocked ? https://makecode.microbit.org/faq
