### ISSUE TITLE
Ultrasonic on Single Pin Locks Up or Out of Memory

### ISSUE THREAD

**Issue by 4tronix** [microsoft/pxt-microbit#3785]
**Describe the bug**
Using the same pin for both Trigger and Echo - as we do on ALL our robots - causes the V2 Microbit to either lock up or give an Error 020 (out of memory?)
Using different pins, or using Microbit v1 and everything is fine.
![SonicIssue_01](https://user-images.githubusercontent.com/5825966/100722475-8d25dd00-33b8-11eb-8f1f-f44788362534.jpg)

**To Reproduce**
Use the ultrasonic extensions (or any 4tronix robot extension with ultrasonic) and set the Trigger and Echo pins to be the same. In the Forever loop show the distance alternatively with showing an icon so you can see activity. Here is the Javascript version of the blocks in the image:

basic.showIcon(IconNames.Heart)
basic.forever(function () {
    basic.showNumber(sonar.ping(
    DigitalPin.P15,
    DigitalPin.P15,
    PingUnit.Centimeters
    ))
    basic.showIcon(IconNames.Yes)
})

**Expected behavior**
We should alternately see (on the Microbit LEDs) a Tick icon and the distance to target.  In fact, we usually see the correct distance printed once, then either nothing at all, or the Error 020

**micro:bit version (please complete the following information):**
Microbit v1.xx is fine
Microbit v2.00 fails as described.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 83.0

**Additional context**

**Comment by 4tronix** [comment]
Related to https://github.com/microsoft/pxt-microbit/issues/3731#issue-746688781

**Comment by jaustin** [comment]
@finneyj is looking at this :)

**Comment by finneyj** [comment]
OK, Have tracked this down to case of mutual assured destruction between the IRQ edge detector code and the PWM measurement class. Sorry about that. 

Fixed in:
https://github.com/lancaster-university/codal-core/commit/147c24ce8641983dfd6ed584926b2a6a27abc017

and made the detector a little more tolerant in the case of missing the start of a pulse here, which could happen if you're turning the pin around:
https://github.com/lancaster-university/codal-nrf52/commit/2e6b66877617a5fe37b0c650e4f9447701b620a6

These updates will be included in the next codal-micrbit-v2 release which will be v0.2.23

**Comment by MiroChao** [comment]
@finneyj Hi, how do i update my microbit V2 to v0.2.23?

**Comment by MiroChao** [comment]
https://github.com/microsoft/pxt-microbit/issues/3731#issuecomment-736383385

**Comment by finneyj** [comment]
Hi @MiroChao 

The updates should be automatically pulled through onto the makecode.microbit.org/beta in the near future when it next updates.

**Comment by pelikhan** [comment]
https://makecode.microbit.og/beta (v3.0.62) has the fixes. Can you test?

**Comment by microbit-mark** [comment]
CODAL v0.2.24 has now been released to https://makecode.microbit.org/stable can you check here to see if this still reproduces for your robots @MiroChao?

**Comment by abchatra** [comment]
Fixed
