### ISSUE TITLE
please add extension to approvedlist

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt-microbit#3786]
please add the microsoft/ExpressivePixelsMakeCode (github.com) extension to the approvedlist for micro:bit.

**Comment by abchatra** [comment]
Here is the pull request. https://github.com/microsoft/pxt-microbit/pull/3788
I will wait for the final update of the blocks. I filed this issue in the repo.
https://github.com/microsoft/ExpressivePixelsMakeCode/issues/7
