### ISSUE TITLE
Pin is not pulled low on P16

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3791]
> micro:bit support: 40539

**Describe the bug**

<img width="727" alt="image" src="https://user-images.githubusercontent.com/31242877/101184231-61b92180-3648-11eb-8d5b-c2afba1edc44.png">

**To Reproduce**
1. Go to https://makecode.microbit.org/90021-04323-64968-24644
2.Flash to micro:bit
3. Connect P16 to GND
4. No change on screen

**Expected behaviour**
This works as expected on V1 and for other pins. It should show 4 on display when pin is pulled low

**Comment by microbit-mark** [comment]
Related https://github.com/lancaster-university/codal-microbit-v2/issues/17

**Comment by martinwork** [comment]
Created https://github.com/lancaster-university/codal-microbit-v2/issues/50
