### ISSUE TITLE
Bluetooth automatically disconnects from the phone.

### ISSUE THREAD

**Issue by chenjiegd** [microsoft/pxt-microbit#3792]
**Describe the bug**
The Bluetooth function of the micro:bit V2 will automatically disconnect after connecting to the phone for 2 minutes, and The phone needs to be connected to the micro:bit V2.0 again. This will happen when using the mobile APP Mbit and micro:bit .

**To Reproduce**
1. Go to https://makecode.microbit.org/_DHUctXDtuA7t
No Pairing Required: Anyone can connect via Bluetooth.
2. Flash to micro:bit.
3. Use the mobile APP to connect to micro:bit V2.0.
4. Wait for 2 minutes to disconnect.

**Expected behavior**
After the micro:bit V2.0 is connected to the mobile phone's Bluetooth, it is stable and not disconnected, which can be used normally on V1.5.

**Screenshots**
![image](https://user-images.githubusercontent.com/37208138/101229863-44826280-36dd-11eb-82ca-44355fb1c5e8.png)

**micro:bit version:**
micro:bit V2.0

**Smartphone:**
  -iPhone7
  -iOS14
  -APP:
![image](https://user-images.githubusercontent.com/37208138/101231603-4e10c800-36e7-11eb-9f53-203256ef28d2.png)

Mbit can be downloaded at https://apps.apple.com/cn/app/mbit/id1450346082

**Comment by martinwork** [comment]
Thank you @chenjiegd I'm sorry you had to pin this down and report it. A fix for this is included in the codal-micrbit-v2 v0.2.23 release, which should be available in MakeCode soon.

**Comment by chenjiegd** [comment]
Thank you.@martinwork

**Comment by chenjiegd** [comment]
https://tech.microbit.org/bluetooth/profile/
![image](https://user-images.githubusercontent.com/37208138/101970111-73f81880-3c63-11eb-8ee7-5545f2739ca5.png)

**Comment by martinwork** [comment]
Could you please re-test with a hex downloaded using MakeCode Beta:  https://makecode.microbit.org/beta.

MakeCode Beta can be selected in the mico:bit iOS app, by a long press on the MakeCode back button: 

![image](https://user-images.githubusercontent.com/989126/101985615-1bd00f00-3c81-11eb-85de-5a5e56f5249d.png)
