### ISSUE TITLE
Unable to edit I2C block code.

### ISSUE THREAD

**Issue by chenjiegd** [microsoft/pxt-microbit#3793]
**Describe the bug**
The previous version of MakeCode can use the I2C read and control functions normally, but now it seems that only PCA9685 can be used normally but cannot be edited.

**To Reproduce**
1. Go to https://makecode.microbit.org/_XWrEXM8vhFPK
2. See error

**Expected behavior**
The micro:bit can communicate with other devices normally

**Screenshots**
![image](https://user-images.githubusercontent.com/37208138/101232300-e5781a00-36eb-11eb-985e-4333321fdecf.png)

**micro:bit version:**
it's not hardware related

**Desktop (please complete the following information):**
  -OS: Win10
  -Browser: Microsoft Edge

**Comment by pelikhan** [comment]
This is a translation issue. We should have refused that translation too.

________________________________

**Comment by chenjiegd** [comment]
This code can run normally when using micro:bit V1.5, but it has no response under V2.0.
https://makecode.microbit.org/_Ftx2rbYsAMPo
![image](https://user-images.githubusercontent.com/37208138/101239564-4a029b80-3723-11eb-8967-6c57382422ce.png)

**Comment by jaustin** [comment]
> This code can run normally when using micro:bit V1.5, but it has no response under V2.0.
> https://makecode.microbit.org/_Ftx2rbYsAMPo
> ![image](https://user-images.githubusercontent.com/37208138/101239564-4a029b80-3723-11eb-8967-6c57382422ce.png)

@chenjiegd could you please file a separate issue for this problem specifically, so we can track it separately to the translation issue?

**Comment by abchatra** [comment]
Translation issue is fixed.
