### ISSUE TITLE
Offline app crashes on macOS Big Sur

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3803]
> micro:bit support: 41638

**Describe the bug**
It appears the MakeCode offline app works sporadically on Big Sur. Sometimes it crashes (see error image)

**To Reproduce**
Not reproduced by Foundation

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31242877/101502929-73146d80-3969-11eb-9889-ad3e57512ed4.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac

**Additional context**

Not certain how this error has surfaced, but it looks like it might be the MakeCode offline app. I have asked if the user can use the browser editor instead.

**Comment by jwunderl** [comment]
Same issue as https://github.com/microsoft/pxt-microbit/issues/3746, closing as duplicate.
