### ISSUE TITLE
Accelerometer reading not match the axis of LSM303AGR

### ISSUE THREAD

**Issue by MiroChao** [microsoft/pxt-microbit#3806]
I found out the accelerometer reading for micro:bit is not matched with the direction of the sensor LSM303AGR , why is that? Is this designed on purpose to have a different 3D axis with the sensor itself?

<img width="393" alt="LogoUp_ay_reading" src="https://user-images.githubusercontent.com/11206594/101715350-429e1200-3ad6-11eb-8dc3-850ab8574d28.png">
<img width="385" alt="tiltRight_ax_reading" src="https://user-images.githubusercontent.com/11206594/101715356-43cf3f00-3ad6-11eb-9ec0-a0ea92a85b87.png">
<img width="385" alt="ScreenUp_aZ_readings" src="https://user-images.githubusercontent.com/11206594/101715360-45006c00-3ad6-11eb-8259-8f64c0aea0ea.png">
<img width="670" alt="LSM303AGR Directions" src="https://user-images.githubusercontent.com/11206594/101715365-46319900-3ad6-11eb-92cf-feb326fbe291.png">

**Comment by MiroChao** [comment]
The sensor is on the backside of the micro:bit, so when I look at the screen, shouldn't the axis be like this？
![image](https://user-images.githubusercontent.com/11206594/101716097-9a894880-3ad7-11eb-9a75-cda1ff92a82d.png)

**Comment by abchatra** [comment]
@carlosperate ?

**Comment by carlosperate** [comment]
Yes, the sensor provides raw data in reference to its own axes, but then the software in the micro:bit transposes this data to match the board orientation, as the ultimate goal is to have the x, y, z axes to always match the board, independently of how the sensor is mounted.

**Comment by abchatra** [comment]
question answered.
