### ISSUE TITLE
Nyan Melody code not working for micro:bit user

### ISSUE THREAD

**Issue by microbit-pauline** [microsoft/pxt-microbit#3810]
Micro:bit support #41752

A micro:bit user has come through support to ask for help why the code for nyan melody is not working. I have looked over the code and it looks fine in the emulator but does not work for me either - can you please advise?

[microbit-PEGASUS-MUSIC.zip](https://github.com/microsoft/pxt-microbit/files/5679557/microbit-PEGASUS-MUSIC.zip)

**Comment by martinwork** [comment]
It's because the start melody block doesn't wait for the melody to finish.

Hear the difference between pressing A and B in https://makecode.microbit.org/_W76F0ye9xMcf

This may not be the best solution, but it works!

**Comment by microbit-pauline** [comment]
Thanks @martinwork

**Comment by microbit-pauline** [comment]
@martinwork The user is happy with your solution :)
