### ISSUE TITLE
Feature: Keep block layout when changing JS variable name

### ISSUE THREAD

**Issue by microbit-sam** [microsoft/pxt-microbit#3814]
From support ticket #41989

**Is your feature request related to a problem? Please describe.**

A user creates a block based script, changes to JS, and edits a variable name. When returning to block view, block formatting is lost

> on returning to the blocks view, all the block formatting is lost.  For a large program this is very inconvient, and requires the user re-organize the layout again.

**Describe the solution you'd like**

Block layout does not depend on variable name

**Additional context**

```
If the variable names in this snippet:

 
if (Select == 0 && (Rotate == 0 && Sunk == 0)) {
comment.comment("not selected, not rotated, not sunk")
strip.setBrightness(ShipBrightness)
strip.setMatrixColor(x, y, ShipColor)

are edited to:

 
if (Selected == 0 && (Rotated == 0 && Sank == 0)) {
comment.comment("not selected, not rotated, not sunk")
strip.setBrightness(ShipBrightness)
strip.setMatrixColor(x, y, ShipColor)

on returning to the blocks view, all the block formatting is lost.  For a large program this is very inconvient, and requires the user re-organize the layout again.

Is it possible to make the block layout more resilient?
```

**Comment by abchatra** [comment]
We have to decompile and it is hard to keep the exact layout when the decompilation trigger. Hard to fix from our end.
