### ISSUE TITLE
Feature: Add get/set calibration to MakeCode

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3815]
**Is your feature request related to a problem? Please describe.**
If you build the micro:bit into another project eg a cardboard rocket ship and  want to update a compass program, flashing via USB erases the compass calibration.

**Describe the solution you'd like**

It looks like the DAL has a means of retrieving and setting calibration data

https://lancaster-university.github.io/microbit-docs/ubit/compass/#getcalibration
https://lancaster-university.github.io/microbit-docs/ubit/compass/#setcalibration

So if you calibrated it once, you should be able to extract that data and set it programmatically.

Is this already available to MakeCode and if not, could it be in Javascript or Blocks, to enable a user to retrieve and set calibration data each time.

**Describe alternatives you've considered**
It is possible to partial flash via webUSB and just update parts of the program, so there is a workaround.

**Additional context**

**Comment by abchatra** [comment]
No plans to implement this.
