### ISSUE TITLE
I2C use problems

### ISSUE THREAD

**Issue by tangjie133** [microsoft/pxt-microbit#3816]
**Describe the bug**
The I2C driver OLED can not be implemented. This is only a problem in V2, but not in V1. After testing, we speculate that there may be a problem in the configuration of I2C, which leads to the problem caused by the weak driving ability.

**To Reproduce**
1. Go to  add “https://github.com/DFRobot/pxt-DFRobot-microIoT”
2. Drag module 
![QQ截图20201216094148](https://user-images.githubusercontent.com/51323906/102293933-1295b980-3f83-11eb-98cc-bc301c67b253.png)

**Expected behavior**
"DFRobot" is displayed in the first line of OLED, which is normal in V1, but not in V2

**micro:bit version :**
 - V2.0

**Desktop:**
-win10
-Google browser

**Additional context**
This is our modification. It works normally after modification.
![2SNWV9KHI2BJT3_A(8RN_J](https://user-images.githubusercontent.com/51323906/102293467-1ffe7400-3f82-11eb-86b7-707b265b5a39.png)

**Comment by jaustin** [comment]
Thanks, this is really usefull and @finneyj might well have an idea about why this is necessary for your code.

Could you please try without enabling the pull-down and just using the high-drive setting? We'd like to know which of the settings there for the pins is key.

**Comment by jaustin** [comment]
Just looking at this now with @finneyj we've noted that mbed used to configure the pins as follows
in mbed...

```
NRF_GPIO->PIN_CNF[scl] = ((GPIO_PIN_CNF_DIR_Input << GPIO_PIN_CNF_DIR_Pos) |
(GPIO_PIN_CNF_INPUT_Connect << GPIO_PIN_CNF_INPUT_Pos) |
(GPIO_PIN_CNF_PULL_Disabled << GPIO_PIN_CNF_PULL_Pos) |
(GPIO_PIN_CNF_DRIVE_S0D1 << GPIO_PIN_CNF_DRIVE_Pos) |
(GPIO_PIN_CNF_SENSE_Disabled << GPIO_PIN_CNF_SENSE_Pos));



NRF_GPIO->PIN_CNF[sda] = ((GPIO_PIN_CNF_DIR_Input << GPIO_PIN_CNF_DIR_Pos) |
(GPIO_PIN_CNF_INPUT_Connect << GPIO_PIN_CNF_INPUT_Pos) |
(GPIO_PIN_CNF_PULL_Disabled << GPIO_PIN_CNF_PULL_Pos) |
(GPIO_PIN_CNF_DRIVE_S0D1 << GPIO_PIN_CNF_DRIVE_Pos) |
(GPIO_PIN_CNF_SENSE_Disabled << GPIO_PIN_CNF_SENSE_Pos));
```
Could you please try the equivalent of this on V2? 
So not the pulldown config, but all else the same.

**Comment by tangjie133** [comment]
Yes, there is no problem with this configuration.
Use gpio configuration function to configure when power on.
> nrf_gpio_cfg(32,NRF_GPIO_PIN_DIR_INPUT,NRF_GPIO_PIN_INPUT_CONNECT,NRF_GPIO_PIN_NOPULL,NRF_GPIO_PIN_S0D1,NRF_GPIO_PIN_NOSENSE);
Please revise this question.

**Comment by jaustin** [comment]
@tangjie133 can you please let us know which device you're needing this configuration for so we can test it? We want to put this configuration in CODAL but need to test it before doing this. We haven't found other devices that need this, so far.

**Comment by tangjie133** [comment]
128X64 OLED screen

**Comment by microbit-carlos** [comment]
@tangjie133 is it possible the accessory has resistors in series for the I2C pins?

**Comment by tangjie133** [comment]
It is because there is a resistor in series on I2C that the communication is not successful.

**Comment by microbit-carlos** [comment]
Thanks @tangjie133, do you know what value resistor is it?

**Comment by microbit-carlos** [comment]
Okay, so looking at the pin configuration. 

## V2

Default CODAL I2C pins config (read via debugger), PIN_CNF[0_08] and PIN_CNF[0_16]:
- `0x0000000c`
- DIR `0b0` -> Configure pin as an input pin
- INPUT `0b0` -> Connect input buffer
- PULL `0b11` -> Pullup
- DRIVE `0b000` -> S0S1 (Standard '0', standard '1')
- SENSE `0b00` -> Disabled

<img width="858" alt="Screenshot 2021-02-08 at 19 20 28" src="https://user-images.githubusercontent.com/29712657/107270345-bdd26480-6a42-11eb-9207-fa03bff65fe0.png">


- samples commit: https://github.com/lancaster-university/microbit-v2-samples/commit/1b416f43df845694222f7e9717989fc538ee0db9
- codal-microbit-v2  commit: 2d8a6d4bf9bec22dba548633df2ae821861b29da
- codal-nrf52: https://github.com/lancaster-university/codal-nrf52/commit/6372c268567a5a75e72db0fdf09e088eb8738e12
- codal-core  commit: https://github.com/lancaster-university/codal-core/commit/969813d451c33daeccef3b41cf904f6c08e6974f
- codal-microbit-nrf5sdk commit:  https://github.com/microbit-foundation/codal-microbit-nrf5sdk/commit/691869a8261e08b283deb0e2267fae3c00c17dae

## V1

Default DAL I2C pins config (read via debugger), PIN_CNF[0_00] and PIN_CNF[0_30]:
- `0x00000600`
- DIR `0b0` -> Configure pin as an input pin
- INPUT `0b0` -> Connect input buffer
- PULL `0b00` -> No Pull
- DRIVE `0b110` -> S0D1 (Standard '0'. disconnect '1')
- SENSE `0b00` -> Disabled

![image](https://user-images.githubusercontent.com/29712657/109020157-9ec60a80-76b1-11eb-9130-6c6ef2c1c03f.png)

microbit-samples@v2.1.1: https://github.com/lancaster-university/microbit-samples/releases/tag/v2.1.1
```
info: get versions for microbit
info: download microbit@v2.1.1 from GitHub lancaster-university/microbit
info: get versions for microbit-dal
info: download microbit-dal@v2.1.1 from GitHub lancaster-university/microbit-dal
info: get versions for mbed-classic
info: download mbed-classic@microbit_hfclk+mb6 from GitHub lancaster-university/mbed-classic
info: get versions for ble
info: download ble@v2.5.0+mb3 from GitHub lancaster-university/BLE_API
info: get versions for ble-nrf51822
info: download ble-nrf51822@v2.5.0+mb7 from GitHub lancaster-university/nRF51822
info: get versions for nrf51-sdk
info: download nrf51-sdk@v2.2.0+mb4 from GitHub lancaster-university/nrf51-sdk
info: generate for target: bbc-microbit-classic-gcc 0.2.3 at /Users/microbit-carlos/workspace/deleteme/really-delete/microbit-samples/yotta_targets/bbc-microbit-classic-gcc
````

## Differencce

|           | V1 | V2 |
| ----- | ----- | ----- |
| Pull | None | Up|
| Drive | S0D1 (Standard '0'. disconnect '1') | S0S1 (Standard '0', standard '1') |

## Tested

- From https://github.com/microsoft/pxt-microbit/issues/3816#issue-768375469, V2 works with pull up and S0D1
- From https://github.com/microsoft/pxt-microbit/issues/3816#issuecomment-764490269 V2 works with no pull and S0D1

**Comment by abchatra** [comment]
This is a CODAL issue.
