### ISSUE TITLE
WaitMicros not working in the simulator

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#3817]
**Describe the bug**
When the wait microseconds blocks is used in the simulator (in this case with a value of 1_000_000 for a 1 second delay) it doesn't seem to delay the code.

**To Reproduce**
1. Run code as shown in the GIF
2. The LEDs toggle much quicker than expected

**Expected behavior**
An LED to toggle per second

**Screenshots**
![makecode-wait](https://user-images.githubusercontent.com/29712657/102366143-36232900-3fb0-11eb-9c0e-7e689945d31b.gif)

**micro:bit version (please complete the following information):**
N/A

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser Chrome
 - Version 87

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by pelikhan** [comment]
waitMicros should not be used for more than a few hundred micros (or at least less then 6ms)

**Comment by microbit-carlos** [comment]
Is there a technical limitation for that?
It wouldn't be obvious to the user that this would be the case. If we cannot fix it, should the input range of the block be limited?

**Comment by pelikhan** [comment]
waitMicros is busy wait and prevents any other code to run.

________________________________

**Comment by livcheerful** [comment]
I can add a max valid value for the input for the block!
