### ISSUE TITLE
 extension import Chinese display garbled Code

### ISSUE THREAD

**Issue by lzty634158** [microsoft/pxt-microbit#3822]
**Describe the bug**
 extension import Chinese display garbled Code.

the extention lib:      https://github.com/lzty634158/Tiny-bit

I don't know why it shows a garbled code?
 Can you tell me what format the extension file needs to be in so that it doesn't show the garbled code?   

Thank you!

**Comment by abchatra** [comment]
This should be fixed. Let me know if this is not.
