### ISSUE TITLE
"start melody" block plays in background but "play melody" doesn't - this is confusing

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#3823]
**Describe the bug**

The default behaviour for 'play melody' and 'start melody' with respect to whether music plays in the foreground or background is inconsistent and this  leads to confusion.

**To Reproduce**
Use the following script
https://makecode.microbit.org/_a3yKo2JcdTMW

![image](https://user-images.githubusercontent.com/147113/102889477-a3243c00-4452-11eb-82f9-5ba31a2bf635.png)

In this program, 
* when pressing button A you hear the whole of the scale and the whole of the entertainer melody (unless you press another button before it is finished). The tick shows before the entertainer melody has finished
* when pressing button B you only hear a tiny bit of the 'entertainer' melody before the scale starts, but the whole of the scale melody. The tick shows only after the scale has finished.
* Pressing buttons A+B is the same as pressing button B despite the explicit choice of 'in background'

**Expected behavior**

It is hard to define what is 'expected' here because a precedent has been set that 'start melody' should play in the background. This is confusing because there is an option to play it in the background explicitly, but no option to play it in the foreground.

I think adding an 'in foreground' option to the 'start melody' block might help?

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**micro:bit version (please complete the following information):**

Behaviour is consistent on V1 and V2

> micro:bit support: 42188

**Comment by abchatra** [comment]
I will close this as completed. We have organized the blocks as play paradigm.
