### ISSUE TITLE
Feature: µs blockly command

### ISSUE THREAD

**Issue by JLFra** [microsoft/pxt-microbit#3824]
Could you add µs cpmmand as you have millis (ms). I found it in javascript, but not in blocky ?
Thanks? Julien

**Comment by bsiever** [comment]
It's in the "Advanced > Control" menu.   Here's an example: https://makecode.microbit.org/_EJjAVTK9tUvL

**Comment by JLFra** [comment]
So could you add it please?
Thanks

**Comment by jaustin** [comment]
@abchatra 
I think this is a question for your team.
