### ISSUE TITLE
MakeCode - Simplified Chinese I2C block not available

### ISSUE THREAD

**Issue by microbit-pauline** [microsoft/pxt-microbit#3830]
Micro:bit Foundation support ticket - 42490

**Describe the bug**
A user has reported that the I2C read and write blocks are missing information. This may be a translation bug.

**Screenshots**
![image](https://user-images.githubusercontent.com/29146842/104023960-4cd92c00-51ba-11eb-9685-27f55b1e0a46.png)

**Comment by lionyhw** [comment]
![image](https://user-images.githubusercontent.com/32665689/104140891-bccff800-53ee-11eb-8fbc-f60e2cb87d16.png)
![image](https://user-images.githubusercontent.com/32665689/104140907-de30e400-53ee-11eb-8148-08fca351ac5b.png)
Serial also has broken blocks.

**Comment by microbit-mark** [comment]
@abchatra @pelikhan  can you take a look at this blocks translation issue

**Comment by abchatra** [comment]
@ganicke can you take a peek at the translation if have time. These are usually incorrect translations.

**Comment by ganicke** [comment]
The `%` token for variables was keyed in from another charset and wasn't valid.

* https://crowdin.com/translate/kindscript/65/en-zhcn#17310
>i2c read number|at address %address|of format %format|repeated %repeat
>2c读数|在地址％address |格式％format |重复％repeat

* https://crowdin.com/translate/kindscript/65/en-zhcn#17311
>i2c write number|at address %address|with value %value|of format %format|repeated %repeat
>i2c写数|在地址％address处，值％value |格式为％format |重复％repeat

**Comment by abchatra** [comment]
Thanks so much @ganicke You rock!

**Comment by ganicke** [comment]
I2C read / write functions:

![image](https://user-images.githubusercontent.com/27789908/105956313-77d1d580-602c-11eb-91b4-165f5fd0c3a7.png)

Serial write values:

![image](https://user-images.githubusercontent.com/27789908/105956477-b9628080-602c-11eb-8096-fb0aec1b0aa8.png)

Serial set padding:

![image](https://user-images.githubusercontent.com/27789908/105956571-db5c0300-602c-11eb-87be-af984a6fecd1.png)
