### ISSUE TITLE
String replace does not work in Python 

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3831]
> micro:bit support: 42344

**Describe the bug**

This script uses string replace to replace a decimal point ".", with a comma  ","

``` Python
a = 1.2
sa = str(a)
print(sa)
ssa = sa.replace(".", ",")
basic.show_string(ssa)
print(ssa)
```

This script works in real Python but in MakeCode Python in the editor and on the device it does not. The string is printed twice with the decimal point.

**Expected behavior**

Serial should print two different strings

1.2
1,2

**Comment by microbit-mark** [comment]
@abchatra can you take a look?

**Comment by abchatra** [comment]
This will be fixed as part of annual release.
