### ISSUE TITLE
Microbit V2 blocks translation issue

### ISSUE THREAD

**Issue by ElizabethRiffle** [microsoft/pxt-microbit#3833]
**Describe the bug**
Here is the tweet highlighting the issue: https://twitter.com/jaera_japan/status/1338411114493669377

Some of our microbit V2 blocks are not translating to the selected language. I looked a number of languages and it seems that this an issue for many languages. Out of the languages I looked at French and German translated, but Japanese, Chinese, Spanish, Danish, and others did not. 

**To Reproduce**
1. Change the language 
2. Look at the V2 blocks

**Expected behavior**
It would properly translate.

**Screenshots**
![image](https://user-images.githubusercontent.com/14082525/104074942-4c469280-51c6-11eb-875c-9cb6a6c394c7.png)
![image](https://user-images.githubusercontent.com/14082525/104074965-608a8f80-51c6-11eb-85e7-6a78c774a6c6.png)
![image](https://user-images.githubusercontent.com/14082525/104074981-67b19d80-51c6-11eb-98f0-98b9001eddaa.png)

**micro:bit version (please complete the following information):**
 V2 blocks. Not hardware related. 

**Desktop (please complete the following information):**
 I duplicated this error using Windows and Edge with makecode.microbit.org version 3.0.61 and Microsoft MakeCode version 6.0.35. But I would image the person who tweeted probably has other specifications.

**Comment by jwunderl** [comment]
All translations are all handled by the community translation members over on crowdin, so in all languages there will be missing localizations at times. If you want to reply to that tweet might be helpful to point them to https://makecode.com/translate in case they would like to participate.

These blocks are new in the last release, and just haven't been translated / had the translations approved yet; e.g. https://crowdin.com/translate/kindscript/65/en-ja#1026520 has a translation suggested for 'on logo pressed' but it has not been approved by one of the community translators who have the ability to check it. Closing as these will get handled by our translation community eventually~
