### ISSUE TITLE
MakeCode String Variable not working

### ISSUE THREAD

**Issue by microbit-pauline** [microsoft/pxt-microbit#3834]
From Micro:bit support ticket 42474

**Describe the bug**
A user has reported that the string variable does not work in MakeCode, it defaults back to a number variable.

The user said that they were able to work around by switching to Python and then back out again, but that is too complicated for their students.

**Screenshots**

Creating a new variable:
![image](https://user-images.githubusercontent.com/29146842/104216190-a4350180-5431-11eb-9f43-43d143c93fa9.png)

When user tries to make it a string variable by typing in "Hello!" it stays red and then reverts to 0 when the user clicks away.
![image](https://user-images.githubusercontent.com/29146842/104216321-cf1f5580-5431-11eb-9c47-5e72c9f8c807.png)

Reverts to: 
![image](https://user-images.githubusercontent.com/29146842/104216390-e78f7000-5431-11eb-8909-c8509d287327.png)

The user can change the variable to be other numbers, but not strings. If they go into Python they can change the variable to a string

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 87

**Comment by abchatra** [comment]
You need to drag the empty "" from the TEXT category for strings. This is because blocks are strongly typed in MakeCode. This is by design.

**Comment by siankerr** [comment]
I have the same question. Copying the text from the string block to edit still returns a '0' when clicked away

**Comment by CoolLondos** [comment]
This Helped Me So Much.
