### ISSUE TITLE
the P16 pin does not work on Microbit V2 board

### ISSUE THREAD

**Issue by 0hotpotman0** [microsoft/pxt-microbit#3838]
**The P16 pin problem**
I was using the ultrasonic sensor connect to P16  on Microbit V2 board, there is not any data return which means the sensor or the P16 pin did not work, but when I connect to P0 to P15, the sensor works very well.  

**code**
the code is simple as below:
![image](https://user-images.githubusercontent.com/47217650/104412015-7a511b80-55a6-11eb-9b4a-75a7f4d2fe17.png)

please help.

**Comment by jaustin** [comment]
Hello @0hotpotman0 - just to check, can you please confirm that the same sensor works properly on other pins, but not on P16?

It looks like you're using an extension here, could you please share what the extension is?

**Comment by martinwork** [comment]
Related:
https://github.com/microsoft/pxt-microbit/issues/3524
https://github.com/microsoft/pxt-microbit/issues/3791
https://github.com/lancaster-university/codal-microbit-v2/issues/50

**Comment by 0hotpotman0** [comment]
Hi jaustin
yeah, it is the same sensor, I do an extension board, the board has 6 groves connect port, one of grove port which is P16 have the problem, then for object exclusion problem, I used the clip to clamp the signal pin of Ultrasonic sensor on P16 pin, it still no data return, in the same way, when I try to use P0 - P15 pin the sensor was working very well, so I think it is not the extension board problem, it should be the V2 board, you can have a try. 

Best regards 
F

**Comment by microbit-mark** [comment]
This should now be fixed in makecode.microbit.org/stable 

Can you test and confirm @0hotpotman0

**Comment by abchatra** [comment]
Fixed
