### ISSUE TITLE
Constantly getting the 927 error.

### ISSUE THREAD

**Issue by Cerquaas** [microsoft/pxt-microbit#3839]
**Describe the bug**
I have the 927 error whenever I load my device. I have updated the firmware, flashed and reconnected multiple times.

**To Reproduce**
1. Power on device
2. See 927 error

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]
1.5
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 14
 - Browser: Micro:bit app
 - Version 14

**Additional context**

**Comment by jaustin** [comment]
Hello

Error 927 means the following:

> The program is incompatible with the micro:bit version you are using. You are trying to use a feature designed for micro:bit V2 on a micro:bit V1 or an extension that is only compatible with a micro:bit V1 board on a micro:bit V2.
(from https://support.microbit.org/support/solutions/articles/19000016969-micro-bit-error-codes)

As you have a micro:bit V1.5 it sounds like this might be due to you using a feature for the micro:bit V2.

Are you using any of the features for micro:bit V2 like the 'on Loud' block, or anything relating to the micro:bit sounds?

It would help if you could share the code you are trying to load onto the micro:bit.

**Comment by abchatra** [comment]
@Cerquaas need additional information here.

**Comment by abchatra** [comment]
No additional information given

**Comment by king-of-kool** [comment]
i am using no code for a version 2 but yet it is still saying error 927. it is so annoying
here is my code in python i have made it on the makecode for microbit site`def on_bluetooth_connected():
    basic.show_leds("""
        . . . . .
                . . . . #
                . . . # .
                # . # . .
                . # . . .
    """)
bluetooth.on_bluetooth_connected(on_bluetooth_connected)

def on_bluetooth_disconnected():
    basic.show_leds("""
        # . . . #
                . # . # .
                . . # . .
                . # . # .
                # . . . #
    """)
bluetooth.on_bluetooth_disconnected(on_bluetooth_disconnected)

def on_button_pressed_a():
    blockytalky.send_string("1", "message")
input.on_button_pressed(Button.A, on_button_pressed_a)
`

**Comment by martinwork** [comment]
@king-of-kool Your code includes a blockytalky call. That extension is marked as beta, and has not been updated to make it V2 compatible.  It will build for V1 but show error 927 on a V2.
https://github.com/LaboratoryForPlayfulComputation/pxt-BlockyTalkyBLE/issues/4

**Comment by king-of-kool** [comment]
why do you always pick me?
