### ISSUE TITLE
One of our microbit cards links to a project that's no longer there

### ISSUE THREAD

**Issue by kiki-lee** [microsoft/pxt-microbit#3840]
From Giles at micro:bit...

Under ‘Courses’ if you scroll along there’s a card called ‘Discover JavaScript Blocks’ (which is what we used to call MakeCode!) – that page no longer exists, and it redirects to our project page **, but it probably makes more sense to link a course page to our ‘First steps’ page https://microbit.org/get-started/first-steps/introduction/** and maybe have another card somewhere to link to our Make it: code it projects.

This sounds like three different requests: 

1) Remove the card that goes to a redirected page.  
2) Add a "First Steps" card under "Courses" that goes to https://microbit.org/get-started/first-steps/introduction/
3) Add a card somewhere else that links to https://microbit.org/projects/make-it-code-it/

**Comment by abchatra** [comment]
This is a request to update link to the "Discover javascript card"
