### ISSUE TITLE
Flashing Heart translates to Dutch on Chrome & Safari in UK

### ISSUE THREAD

**Issue by kiki-lee** [microsoft/pxt-microbit#3841]
Hi Kiki,

No, the translate icon doesn’t appear. It also looks the same in an incognito window in Chrome. It also has the Dutch translation for the title in Safari, but oddly not in Firefox! (I’m on a Mac, I think my colleague was using a Windows PC)

Best wishes
Giles
---------------
From: Kiki Prottsman <kprottsman@microsoft.com>

When on that page, do you happen to see this icon at the top of the page?  If so, Chrome is auto-translating (which is still a problem, if we assume that all of the UK speaks Dutch!)
 
![image](https://user-images.githubusercontent.com/1633958/104633149-96f75d00-5653-11eb-9910-601654a77261.png)

If it’s not there, it’s even more concerning, because it means there’s likely something else about your location that’s causing it that we haven’t accounted for. 
 
If this isn’t the case, I’ll do a little recon to see what other parts of the world experience the same issue.
 
--------------------- 
From: Giles Booth <giles@microbit.org> 

Hi Kiki, 
 
How odd! Yes both Chloe and I, see the same thing, we are in totally different locations in the UK.
 
Oddly I only see this in Chrome. In Firefox it appears normal. I have never knowingly switched Chrome to Dutch and its current setting is English, and only the title of this project is affected (once you start following the tutorial).
![image](https://user-images.githubusercontent.com/1633958/104632741-03be2780-5653-11eb-8a2d-6843317d8733.png)

Another colleague says she saw the same project with a Norwegian title a while back!
 
Cheers
Giles
-------------------- 
From: Kiki Prottsman <kprottsman@microsoft.com>
 
That’s so odd!  I can’t reproduce, in any of the coding languages.  It’s possible that their “languages” were changed at some point and they didn’t notice since so few of our instructions are translated.   
 
Will you let me know if you see the same thing from your browser?
 
~Kiki
---------------------------- 
From: Giles Booth <giles@microbit.org> 

Thanks Kiki.
 
By the way, our fund-raiser Chloe just noticed that when you start the Beating Heart project on the home page, the title seems to get translated into Dutch:
 
![image](https://user-images.githubusercontent.com/1633958/104632851-24867d00-5653-11eb-990f-c07e90f67442.png)

Thought I’d let you know!
 
Best wishes
 
Giles

**Comment by abchatra** [comment]
@kiki-lee I don't understand this issue. Can you please condense the right issue here?

**Comment by microbit-mark** [comment]
> when you start the Beating Heart project on the home page, the title seems to get translated into Dutch

 This was the issue, but no longer needs

Perhaps this was a cacheing problem as it no longer reproduces for me.

**Comment by abchatra** [comment]
Thanks @microbit-mark. Got it. I don't reproduce in Chrome and on iPad. I am unsure how this would happen.

**Comment by abchatra** [comment]
Can't reproduce.
