### ISSUE TITLE
Feature: Get the display buffer as an Image

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#3842]
> Support ticket 42465

**Is your feature request related to a problem? Please describe.**
Is there a way to get the full display buffer as an Image?

**Describe the solution you'd like**
A method in the `led` instance to return the buffer as an Image

**Describe alternatives you've considered**
We could form a string by calling `led.point(x, y)` on each individual LED, but then we cannot create an image from a variable:

![image](https://user-images.githubusercontent.com/29712657/104758913-03a75000-5757-11eb-90c6-1a8c8934a107.png)

**Additional context**
N/A

**Comment by abchatra** [comment]
Won't implement from our end. I am not sure what is the use case for string from image? It consumes more memory and hard to figure out the mutations.
