### ISSUE TITLE
MakeCode offline app - not installing

### ISSUE THREAD

**Issue by microbit-pauline** [microsoft/pxt-microbit#3843]
**Describe the bug**
A micro:bit support ticket was received where the user experienced problems downloading the MakeCode offline app. They confirmed that other teachers in Taiwan were experiencing the same issue.

**To Reproduce**
1. User went to https://makecode.microbit.org/offline-app
2. User downloaded makecode-microbit-set-up-win64.exe
3. User experienced error **"the application couldn’t execute on your computer. If you would like to find the one fits the version of your computer, please contacts the software launcher"**

**Expected behavior**
App to install and work on Windows 10, Chrome

**Desktop
 - Browser [Chrome]
 - Version [87.0.4280.141]

I downloaded a fresh copy of MakeCode offline to recreate issue.. It worked fine. I don't know whether this is a localised issue with schools in Taiwan.

**Comment by abchatra** [comment]
@microbit-pauline We need version of the operating system. We only support 64 bit windows or MAC.

**Comment by microbit-pauline** [comment]
@abchatra - The user replied  "Our version of our computer system is “windows 10 x64” which means 64bits windows"

**Comment by microbit-pauline** [comment]
@abchatra - Do you need any further information that what the user provided?

**Comment by abchatra** [comment]
We are unable to reproduce this. Any information on reproducing this would be good.

**Comment by microbit-pauline** [comment]
Hi @abchatra - This is what was provided on the ticket. 

![image](https://user-images.githubusercontent.com/29146842/106492930-6b2c0200-64b0-11eb-9596-56611e3fd52e.png)

Can you please advise what further information you will need?

**Comment by abchatra** [comment]
Ask them for the system information from the windows. It will list all the configuration of that machine.

**Comment by microbit-mark** [comment]
> Also reported in micr:bit support #43455

Windows 10 64-Bit (20H2)

---
I'm consistently getting the Error 'This app can't run on your PC
To find a version for your PC, check with the software publisher'
I have downloaded the .exe file from here: https://makecode.com/api/release/microbit/v3.0.65/win64
I also tried to disable UAC, Smartscreen, ran 'sfc /scannow' - stil no luck.
---

I will ask for system information

**Comment by abchatra** [comment]
I prefer not to ship something which doesn't work everywhere. If it is a backward compat issue let us know.

**Comment by abchatra** [comment]
Lets communicate that it is deprecated.

**Comment by jwunderl** [comment]
It seems like there's likely something going wrong with downloads in that region / cdn breaking? @microbit-mark if you could ask for the size of the file they downloaded / are trying to install that would be very helpful. re: https://github.com/microsoft/pxt-microbit/issues/3876

**Comment by microbit-mark** [comment]
@jwunderl I have requested this information. The person that reported it in  support ticket 43455 is based in Switzerland, so I've also updated the name of this ticket.

**Comment by abchatra** [comment]
Can't repro for us.
