### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ywc-hb** [microsoft/pxt-microbit#3848]
**Describe the bug**
When I want to compile a project which use the Waveshare extension to control their LCD 1in8 screen for microbit ( [here](https;//github.com/waveshare/WSLCD1in8) ), MakeCode returns that there is an error in my code, but the error depends on the OS and the browser I use. However, with the old version of MakeCode ( [this one](makecode.microbit.org/v2/) ) still work with this extension, but we can't use the hex file generated on microbit v2.      
The error is different as almost every time, but those are more regular : 
- _Cannot read property 'toString' of undefined_
- _Cannot read property 'hex' of null_

**To Reproduce**
1. Go to makecode.microbit.org and start an empty project
2. Add the waveshare extension https://github.com/waveshare/WSLCD1in8/
3. Add the following lines in javascript : 
`LCD1IN8.LCD_Init();     
LCD1IN8.LCD_Clear();     
LCD1IN8.LCD_Filling(0);`

**Expected behavior**
At least an hex file that can be run on microbit v2. 
This code must fill the entire screen in black.

**Screenshots**
![screenshot_22-01-2021_16:13:40](https://user-images.githubusercontent.com/58783406/105510365-d7e41700-5cce-11eb-9c5c-dbbf0ecce315.png)
![screenshot_21-01-2021_21:55:47](https://user-images.githubusercontent.com/58783406/105510374-dadf0780-5cce-11eb-9602-5618db67760b.png)

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to : *it's not hardware related*

**Desktop (please complete the following information):**
 - OS: Windows and Archlinux
 - Browser: Chrome and firefox, on both OS
 - Version: the latest version of makecode

**Additional context**
Here is the screen : https://www.waveshare.com/wiki/1.8inch_LCD_for_micro:bit

**Comment by abchatra** [comment]
I think issue here is this extension only works on v1 hardware and not on v2 hardware. 
There is a flag in pxt.json of the extension where we can specify only for v1 hardware. I can't seem to find the documentation for this. @mmoskal or @pelikhan do you remember?

**Comment by pelikhan** [comment]
Add « disablesVariants »: [« mbcodal »] in pxt.json

________________________________

**Comment by abchatra** [comment]
@microbit-mark can we document the above for package owners?

**Comment by microbit-mark** [comment]
@abchatra I have added a line to https://support.microbit.org/en/support/solutions/articles/19000121371-makecode-extension-compatibility-v1-and-v2

> If your extension is unable to support the V2 device, you can add a flag to pxt.json. Users will see a 927 error when downloaded to a V2 device :
> 
> `"disablesVariants": ["mbcodal"]`
>

**Comment by abchatra** [comment]
Lets give a patch to this extension.

**Comment by livcheerful** [comment]
I put up a PR to fix in the extension! Closing on our end
