### ISSUE TITLE
JSDoc type error in python

### ISSUE THREAD

**Issue by kitkittia** [microsoft/pxt-microbit#3849]
**Describe the bug**
Initializing an empty array in a loop in a function causes an error: `JSDoc types can only be used inside documentation comments.`

**To Reproduce**
```
def f1():
    while True:
        x = [] # Causes error

def f2():
    while True:
        x = [0] # No error

def f3():
    for _ in range(0):
        x = [] # Causes error

def f4():
    for _ in range(0):
        x = [0] # No error
```

**Expected behavior**
Expected no error

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Mozilla Firefox 84.0.2

**Additional context**
Happens on master branch, and on https://makecode.microbit.org

**Comment by darzu** [comment]
Indeed, this is an odd one since it doesn't reproduce if the "def" or "while" loop are missing.
<img width="579" alt="image" src="https://user-images.githubusercontent.com/6453828/115460498-32611680-a1dd-11eb-898c-a8285f90e401.png">
