### ISSUE TITLE
Feature request: programmable power managment

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3853]
**Is your feature request related to a problem? Please describe.**

User story: I need to make a sensing device that lasts a long time on batteries. Thus the device needs to power off under program control, and power up on an event, take a measurement, then go to sleep again.

**Describe the solution you'd like**
CODAL offers a power management API https://github.com/lancaster-university/microbit-v2-samples/blob/master/source/samples/PowerManagementTest.cpp and there is a published spec https://github.com/microbit-foundation/spec-power-management. It would be useful to surface this in MakeCode

**Describe alternatives you've considered**
None

**Additional context**

**Comment by jaustin** [comment]
I think it makes sense for us to implement this initially as an extension (perhaps called "power management" that wraps the CODAL interface (uBit.Power)

**Comment by abchatra** [comment]
Closing this as extension was preferred.
