### ISSUE TITLE
Remove devices block from top extensions list

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3854]
The devices Bluetooth blocks were marked as BETA some time ago as a large number of Android devices do not support them. We should remove them for the top ten extension tiles 

![image](https://user-images.githubusercontent.com/31242877/105871920-b5653d00-5ff1-11eb-99ed-baaca873087b.png)

**Comment by abchatra** [comment]
@pelikhan can we remove devices from the extension dialog?

**Comment by pelikhan** [comment]
@jwunderl ?

**Comment by abchatra** [comment]
One of us can do. I am asking if this is ok or do you have any concerns?

**Comment by pelikhan** [comment]
Absolutely not. Those blocks were kept as legacy for touchdevelop -> microbit v1 release. It's time to let them go until they are properly supported by the apps.

**Comment by microbit-mark** [comment]
@abchatra I think people should still have a way of adding these if they need to, rather than removing them completely. Are they part of core pxt-microbit or can they be added by URL?

**Comment by abchatra** [comment]
If it doesn't work what is the need to let users add it?

**Comment by microbit-mark** [comment]
@abchatra I think it still works with some devices including iOS. Another person has requested the use of these blocks in microbit support ticket 43486 as they started using them a fwe weeks ago.

I would prefer they still be available in a beta extension rather than removing completely. This ticket was just to remove them from the top 10 tiles

**Comment by microbit-mark** [comment]
Any update on this? Is it possible for someone to still add these blocks to a project?

**Comment by martinwork** [comment]
The iOS app camera sample uses blocks from the Devices extension. The gamepad demo used them too, but had to change to an ugly "on event from" block because changes in the DAL and MakeCode reduced the available RAM. Those blocks would be usable again with V2.

**Comment by abchatra** [comment]
Fixed

**Comment by microbit-mark** [comment]
Reopening as I think the issue is not quite resolved. We created

https://support.microbit.org/en/support/solutions/articles/19000125262-makecode-devices-extension which notes that the blocks are deprecated and gives people a workaround.

But the reference still exists.

https://makecode.microbit.org/reference/devices

Can we add a note to this to say that the blocks are deprecated? @abchatra @ganicke

**Comment by abchatra** [comment]
@ganicke can you remove these blocks from the documentation? 
https://makecode.microbit.org/reference/devices

We have removed the package from our extension.

**Comment by jturcotte** [comment]
It’s unfortunate that this is completely removed, I find the Bluetooth gamepad controls very useful for robot projects instead of having to buy a separate micro:bit gamepad. I’ve been able to make it work with the workaround above but I had to spend quite some time digging why it wasn’t available and applying the text project settings is cumbersome.

The extension is still referenced there, which led to my confusion:
- https://support.microbit.org/support/solutions/articles/19000117216-monitor-control-in-the-ios-app (as well as within the iOS app Monitor and Control help)
- https://makecode.microbit.org/v1/reference/devices

**Comment by abchatra** [comment]
Thanks for the feedback.
