### ISSUE TITLE
Serial Read Line crashes with 20+ Characters on V2

### ISSUE THREAD

**Issue by ryanteck** [microsoft/pxt-microbit#3855]
**Describe the bug**
I believe this is what's been causing some of our issues with the V2 and with lots of trial and error think this is what's causing it.

When a line of over 20 characters is received via the UART of the microbit V2 oddities occur.

Sometimes it will then read the next line and assume it has received a new line character before it has been sent, causing our program that sends data and waits for a response to keep sending data as the micro:bit thinks it has received the issue.

**To Reproduce**

Load the program at https://makecode.microbit.org/_TvL3UKWW7C8r onto a micro:bit v2.

Connect a UART adaptor to 2 GPIO pins on the micro:bit (I am using 14 for TX and 15 for RX) and then connect this to a PC.

Open up a terminal console (Putty, Screen etc at 115200 baud).

Connect microbit or press reset button, number 1 should appear.

Paste ```abcdefghijklmnopqrst``` into the terminal then press ctrl+j, you should see number 2 appear.

Then paste the string again but don't press ctrl+j, you should see numbers 3 & 4 appear.

**Expected behaviour**

The micro:bit should not jump to the next line (echo number 3) until it receives new line from the computer (\n | ctrl+j). 

This is what happens on a micro:bit v1 which is what is expected.

**Screenshots**
I've created a video trying to show this at https://www.youtube.com/watch?v=R-BM6IwEnm8&feature=youtu.be

Code running on the microbit (Just waits for read line and prints back what it expects is linked above.

**micro:bit version (please complete the following information):**

V2

**Desktop (please complete the following information):**
N/A, Happens on both Ubuntu & Windows.

**Additional context**
Any help is appreciated, I've had an issue open regarding serial problems since the V2 launched but had no further help hence closing that debugging further and opening a more specific issue. This is causing customers to have issues with our add-ons as well.

**Comment by martinwork** [comment]
@ryanteck Could you please test with https://makecode.microbit.org/stable, which has an updated CODAL v0.2.24 release

I haven't tested with redirection and a UART adaptor, but I have seen problems via the USB connector, which seem fixed in the new version.

Note that 20 is the default buffer size. To reliably support 20 byte messages (21 with newline), it would be advisable to increase the buffer size with serial.setRxBufferSize(21). By the way, I see "abcdefghijklmnopqrs" delivered on V1.

**Comment by ryanteck** [comment]
Thanks @martinwork , Will do.

I did notice when I experimented with the buffer size it didn't seem to help too much but will check both bits.

Thanks

**Comment by ryanteck** [comment]
Sorry about the delay.

I think it looks like it might be fixed now with the stable one, still got an issue with our library compared to V1 but it's certainly working better than before.

**Comment by martinwork** [comment]
@ryanteck I have created related issues:

https://github.com/lancaster-university/codal-microbit-v2/issues/79
https://github.com/lancaster-university/codal-microbit-v2/issues/80

Could either of those explain what you see?
Can you give me any more details about what issues are still occurring?

**Comment by ryanteck** [comment]
Hi @martinwork , My apologies for the delay.

Today it did seem to test fine with makecode version 3.0.67, microsoft version 6.0.39 and microbit runtime 2.2.0-rc6 as I wasn't able to replicate the issues we've been having.

**Comment by abchatra** [comment]
Fixed
