### ISSUE TITLE
Feature Request - Console window input

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#3857]
Feedback from Mr. Coxall - 
The requirement that I have is to be able to have "free flow" input of numbers and letters like I have in MakeCode Arcade but in MakeCode for Micro:Bit. 
I know I can do it with the console in the Python IDE, but I want to do it with a Micro:Bit using a block language.
Using the Python IDE for the Micro:Bit I can make a program like:
<img width="470" alt="Python1" src="https://user-images.githubusercontent.com/22108954/106076421-5de3d180-60c4-11eb-9a08-28a2e146c19a.png">

And then use the console to interact with it like:
<img width="448" alt="Python2" src="https://user-images.githubusercontent.com/22108954/106076427-60dec200-60c4-11eb-8277-0080cdf2bb9b.png">

Similarly, when I use MakeCode Arcade, I can write a program like:
<img width="887" alt="Arcade" src="https://user-images.githubusercontent.com/22108954/106076433-64724900-60c4-11eb-84a1-64cdbcf3148c.png">

The Console window for MakeCode micro:bit doesn't allow user input:
![MicrobitConsole](https://user-images.githubusercontent.com/22108954/106076520-8cfa4300-60c4-11eb-933c-a63966f8b788.png)

**Comment by abchatra** [comment]
This issue is asking for Repl style in the console view. We don't have any plans to implement the same. Closing as Won't Fix.

**Comment by Vegz78** [comment]
> This issue is asking for Repl style in the console view. We don't have any plans to implement the same. Closing as Won't Fix.

Keeps reemerging as a pronounced wish all over the place, though, as comparisons are made to the [official Python IDE / simulator](https://python.microbit.org/v/3) which has this, and basic console input and output is fairly ubiquitous in education:
https://forum.makecode.com/t/2-questions-moving-multiple-blocks-in-editor-and-micro-bit-simulator-keyboard-control/31389/6
