### ISSUE TITLE
Upgrade to crowdin v2 apis

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#3858]
**Is your feature request related to a problem? Please describe.**

Currently we are using crowdin v1 apis for handling translations. These are being phased out at the end of this year (2021), so we should migrate to the new v2 apis

**Describe the solution you'd like**

Migrate to v2 apis. 

**Describe alternatives you've considered**

no

**Comment by abchatra** [comment]
Done.
