### ISSUE TITLE
control.waitMicros() is not stable

### ISSUE THREAD

**Issue by matsujirushi** [microsoft/pxt-microbit#3860]
I am creating an Extension that communicates with DHT11.
Compared to v1, v2 is faster.
However, in v2, control.waitMicros() sometimes becomes long and can't communicate with DHT11 due to timing conflict.

In the following code, I compared v1 and v2.

```
basic.forever(function () {
    basic.pause(18);
    for (let i = 0; i < 17000; ++i)
    {
        pins.digitalWritePin(DigitalPin.P14, 1);
        control.waitMicros(28);
        pins.digitalWritePin(DigitalPin.P14, 0);
        control.waitMicros(28);
    }
})
```

![image](https://user-images.githubusercontent.com/8079404/106379036-93eac380-63ec-11eb-8f88-a04c7fedf4b2.png)

Is there any way to work around this, such as temporarily stopping the process running in background/interrupt?

**Comment by samlcy1997** [comment]
Facing the same issue, any solution to solve it or it is the hardware fault can not be resolve? Thank you.

**Comment by pelikhan** [comment]
@jaustin

**Comment by samlcy1997** [comment]
@abchatra Hello sir, do you have any update about that? Want to know is that able to solve. thx

**Comment by martinwork** [comment]
@samlcy1997  @matsujirushi There is a DHT11 extension for MakeCode. Search extensions for DHT11. Does that one work? Choose Learn more, then Github to find source code.

**Comment by abchatra** [comment]
Please look at the DHT11 extension and if that doesn't solve the issue, reopen the issue.
