### ISSUE TITLE
Keyboard disappearing in MakeCode

### ISSUE THREAD

**Issue by microbit-pauline** [microsoft/pxt-microbit#3862]
**Describe the bug**

Micro:bit Foundation support ticket - 42906.

The user has reported that the keyboard on her Galaxy A7 tablet will pop up and then disappear meaning that they cannot enter the text or numerical values. They have attached a video and have given me permission to share.

https://user-images.githubusercontent.com/29146842/106607578-640dfe00-655b-11eb-9ad2-016e7e8ce6b3.mov

**To Reproduce**
1. Go to 'https://makecode.microbit.org/#editor'
2. Add a variable
3. Attempt to change teh variable value
4. Keyboard briefly pops up and then disappears

**Expected behavior**
The keyboard remains in place

**micro:bit version V1:**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy A7 Tablet]
 - Browser [Chrome]
 - Version [83.0.4103.106]

**Additional context**

**Comment by microbit-pauline** [comment]
MakeCode settings
![QM39TbPBNTlzHf6aFTRAPEAZG4qCbq3teg](https://user-images.githubusercontent.com/29146842/106609370-63766700-655d-11eb-97c2-f732bb2774be.jpeg)

**Comment by livcheerful** [comment]
Fixed in beta!
