### ISSUE TITLE
Support bigger flash size of micro:bit V2

### ISSUE THREAD

**Issue by NeuerUser** [microsoft/pxt-microbit#3864]
**Is your feature request related to a problem? Please describe.**
I'm having a nice program which is slightly too big to fit onto a micro:bit V1. So, I bought a micro:bit v2 in the hope that the doubled flash size should allow it to fit. But the editor still tell me that the program is too big by the same amount.

**Describe the solution you'd like**
Ideally a small selection, what micro:bit I am using (v1 or v2). Depending on that the editor should allow to compile a bigger program for the v2.

**Describe alternatives you've considered**
Instead of a selector, the editor could automatically identify the micro:bit I am using via the blocks I use. It already does that, because it switches the simulator, when I have v2 blocks in use. But it does not change the max size of the compiled code.

**Additional context**
one of the main improvement of the v2 is the added flash and RAM size. Considering that around 90% of the flash is already used by the base code, the additional flash should allow for much bigger programs.

**Comment by abchatra** [comment]
@mmoskal can we increaes the size for v2?

**Comment by mmoskal** [comment]
Adding a v2-only extension might fix it

**Comment by pelikhan** [comment]
Add to pxt.json
```
"disablesVariants": {
   "mbdal"
}
```

**Comment by abchatra** [comment]
There is a workaround today.

**Comment by martinwork** [comment]
@pelikhan Can disablesVariants be added to a project? I seem to get errors using edit settings as text.

**Comment by pelikhan** [comment]
It should be allowed, make sure your JSON is properly formatted?

screenshot?

**Comment by carlosperate** [comment]
Make sure the values are in a list, I think I had to use it like this in the past:
```json
{
    "disablesVariants": [
        "mbdal"
    ]
}
```

**Comment by martinwork** [comment]
Thanks @carlosperate @pelikhan It works with the right shape brackets, so the settings text ends
```
    "preferredEditor": "blocksprj",
    "disablesVariants": [ "mbdal" ]
}
```
Adding V2 only blocks doesn't seem to work.

**Comment by paulinaeb** [comment]
> Adding a v2-only extension might fix it

it doesn´t, I already tried it.

**Comment by lobodpav** [comment]
It would be very helpful if he `"disablesVariants": [ "mbdal" ]` setting would be documented. It took me ages to find this issue out 😢

**Comment by abchatra** [comment]
Documented here: https://support.microbit.org/support/solutions/articles/19000121371-makecode-extension-compatibility-v1-and-v2

**Comment by lobodpav** [comment]
> Documented here: https://support.microbit.org/support/solutions/articles/19000121371-makecode-extension-compatibility-v1-and-v2

Thanks for the link. I think it would be great if this was referenced in the CLI help command as well as in the README. For some reason, I have never come across the link you posted, even when I searched all over Google.
