### ISSUE TITLE
Inconsistency in Forever in simulator and hardware

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3870]
**Describe the bug**
A clear and concise description of what the bug is. The behaviour of concurrent forever loops differs on simulator and hardware

![image](https://user-images.githubusercontent.com/31242877/107219009-5d263600-6a08-11eb-99ae-00c2ccef3815.png)

**To Reproduce**
1. https://makecode.microbit.org/_EMv5q0g0xgrs
2. Simulator passes program execution between Forever loops (displays 0, 3, 1, 4, 2, 5)
3. Download to V1. Program executes loops one after the other (displays 0, 1, 2, 3, 4, 5)
4. Download to V2. Program seems to execute loops concurrently (displays 0, 1, 2, 5)

**Expected behavior**
Behaviour on hardware should be as on simulator

**Additional context**
Related to https://github.com/lancaster-university/codal-microbit-v2/issues/18?

**Comment by abchatra** [comment]
Hard to fix the consistency from a timing perspective. Closing.
