### ISSUE TITLE
pxt-microbit >= 3.0.65 uses the development version of React

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microsoft/pxt-microbit#3875]
**Describe the bug**

pxt-microbit >= 3.0.65 uses the development version of React which is [only intended for development use](https://reactjs.org/docs/optimizing-performance.html#use-the-production-build).

You can see this most easily with React dev tools, but also from the logged warnings about deprecated lifecycle methods that didn't used to appear in live.

https://makecode.microbit.org/v3.0.64 is fine
https://makecode.microbit.org/v3.0.65 uses development React, as does the live version

Maybe related to switching to GitHub actions?

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

![image](https://user-images.githubusercontent.com/44397098/107808795-0ac77b00-6d62-11eb-8bac-716c53f3fa57.png)

**Comment by microbit-matt-hillsdon** [comment]
Asset sizes are also significantly bloated as it looks like some minimisation has been removed:

For example, take main.js:

3.0.64: 
https://pxt.azureedge.net/blob/5d9eb71a9f5a03538833b2d07eb04b0f0d869753/main.js
1.6M all on one line

3.0.65: https://pxt.azureedge.net/blob/37e3fd85a6337e2722f769e16a60f74c54d64465/main.js
Over 11MB (!) over thousands of lines

The same is true of the current live version. This must be having a meaningful impact on users with lower-end devices.

@abchatra, I'm pretty worried about this. Is live MakeCode being built in a development mode?

**Comment by abchatra** [comment]
@microbit-matt-hillsdon & @microbit-mark  test /stable and see if the issues are fixed. I will release it tomorrow if everything is good.

**Comment by microbit-matt-hillsdon** [comment]
I've confirmed that main.js file size is back down and that React dev tools reports production React is in use on stable.
