### ISSUE TITLE
can't extracted/expand makecode offline version for mac 

### ISSUE THREAD

**Issue by adhioutlined** [microsoft/pxt-microbit#3876]
today I'm trying to download makecode offline version for mac via https://makecode.microbit.org/offline-app page. The file was successfully downloaded, but it can't be extracted/expand.

- while I'm extracted/expand using archive utility from finder (I'm using osx high sierra 10.13.6).
![Screen Shot 2021-02-10 at 9 39 42 AM](https://user-images.githubusercontent.com/3907931/107850320-15eadb80-6e34-11eb-9647-23f879194773.png)
- when extracted from using `unzip` command in terminal, it will returned error.
![Screen Shot 2021-02-10 at 9 41 17 AM](https://user-images.githubusercontent.com/3907931/107850337-3155e680-6e34-11eb-8885-e237d1609e2e.png)

It's seems like broken file. Would you help me for this ? Or can you also upload offline version file at your github release page (https://github.com/microsoft/pxt-microbit/releases) ?

**Comment by microbit-mark** [comment]
This seems to work as expected in macOS11, so perhaps a legacy macOS issue?

**Comment by adhioutlined** [comment]
> This seems to work as expected in macOS11, so perhaps a legacy macOS issue?

Trying to download with Windows 10 and extracted, then still got the error message : 
![Screen Shot 2021-02-16 at 6 07 27 PM](https://user-images.githubusercontent.com/3907931/108054919-dfa29b80-7081-11eb-9c0b-44bf8ad2d7db.png)

would you like to sent me good one file to my email adhi.pri@gmail.com ?

**Comment by jwunderl** [comment]
This looks like the download was interrupted; the file size on the zip file looks like it's listed at 6.3mb, where the file size for the current version is ~177mb (I just downloaded / unzipped the current file to confirm and that worked on my machine).

I did see there was a similar issue that resolved itself in arcades offline app https://forum.makecode.com/t/announcement-new-offline-app-for-makecode-arcade/3356/14?u=jwunderl, so it's possible that it was a broken file in a cdn cache temporarily / might have resolved itself by now? Not immediately sure what else it could be, needs some investigation.

**Comment by adhioutlined** [comment]
Hi, 
According from Joey reply, I'm trying to download again. This time I accessing download page using VPN service from opengate via one of their japan server, then it's look promising. 
Download size was detected about 169 MB
![Screen Shot 2021-02-24 at 9 35 26 PM](https://user-images.githubusercontent.com/3907931/109016959-47dc2780-76e9-11eb-9a73-0dbd3dc65ae0.png)

after finishing download, it was successfully extracted and opened in my osx 10.13.6
![Screen Shot 2021-02-24 at 9 39 06 PM](https://user-images.githubusercontent.com/3907931/109017718-05671a80-76ea-11eb-8ac8-884ac2a2acc1.png)


FYI, Originally I'm from Indonesia. In my opinion, may be there is some configuration in server to reject or redirect connection from Indonesian IP address.

**Comment by jwunderl** [comment]
Interesting, thank you for checking / glad it seems to be working! I logged onto my personal device and checked a few different vpn servers I had access to in the area and was not able to reproduce the error :( We should not have any configuration like that, from https://forum.makecode.com/t/announcement-new-offline-app-for-makecode-arcade/3356/14?u=jwunderl it seems possible that it's an issue with broken versions sticking around in the CDN as that user appears to be in Europe with the same issue.

**Comment by abchatra** [comment]
Can't repro. If this issue still exists reopen.
