### ISSUE TITLE
Neopixel Brightness not working

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#3877]
Doing a workshop today and was working with NeoPixels.
Hooked up a single neopixel to the micro:bit (Flora) and noticed that the Brightness was not working - strip.setBrightness(0)
Sample code - https://makecode.microbit.org/_D3KbreAEfE5x

**Comment by abchatra** [comment]
@Jaqster v2 or v1 hardware?

**Comment by Jaqster** [comment]
v1 micro:bits

**Comment by MKleinSB** [comment]
You have to call again Showcolor
![grafik](https://user-images.githubusercontent.com/37311672/115993497-4ccb3380-a5d3-11eb-9dd0-245ce30018d2.png)

**Comment by livcheerful** [comment]
To confirm -- the desired behavior is to not have to call "Show Color" again before calling "Show"?

**Comment by abchatra** [comment]
Try @Jaqster  program with old editor (http://microbit.makecode.com/v2) and see if this is a regression. setBrightness just should change the brightness of the already lit up neopixel

**Comment by pelikhan** [comment]
setBrightness is destructive, values are moded in place so you need to first set the brightness, then set colors again, the show.

**Comment by abchatra** [comment]
Ok by design then?

**Comment by abchatra** [comment]
By design.
