### ISSUE TITLE
Hang removing controlled MakeCode iframe since v3.0.65

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microsoft/pxt-microbit#3879]
**Describe the bug**

Something changed in MakeCode v3.0.65 that means iframes using MakeCode cause Chrome tabs to hang when they are removed from the DOM.

This affected micro:bit classroom and led to a support request. We've since worked around it by hiding MakeCode on the classroom student congratulations screen rather than removing it.

**To Reproduce**

1. In Chrome, go to https://debug.microbit.org/works.html

Wait for MakeCode to load and click "Remove iframe to trigger hang". It is successfully removed. This version uses MakeCode 3.0.64.

2. Try again with https://debug.microbit.org/hangs.html 

This time, MakeCode is not removed and the tab hangs. You can't interact with it and Chrome will pop up a dialog.  This version uses MakeCode 3.0.65.

I first reproduced this locally, but you seem to need https (self-signed is fine) and a microbit.org domain (e.g. via a hosts file entry) so I set up the above examples.

The source of the pages is straightforward and self-contained so you can see what's going on. You can also try with live MakeCode at https://debug.microbit.org/latest.html.

**Expected behavior**
It's useful to be able to remove MakeCode from the DOM when moving on to other stages of an app that embeds MakeCode. This used to work well.

I've no idea what could cause this.  Perhaps we've tripped over a Chrome bug. It would be great if we could understand what's changed in MakeCode and reinstate if possible.

I wonder whether it could be related to #3875 or some similar build-time change, as I couldn't find anything obvious to blame in the diff between versions.

**Screenshots**

![image](https://user-images.githubusercontent.com/44397098/107966145-574dc900-6fa3-11eb-8ee2-da5004ed4eee.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 88.0.4324.150 (Official Build) (x86_64)

**Comment by abchatra** [comment]
3.0.65 had only codal update and a minor bug fix to remove a package. I am not sure how it can regress this scenario.

**Comment by microbit-matt-hillsdon** [comment]
@abchatra I agree it's unexpected. Can you reproduce it via my links?

Looking at the diff made me wonder about the build changes. Something odd has happened in 3.0.65 to cause live MakeCode to use the the development-time version of React - see #3875.

https://github.com/microsoft/pxt-microbit/compare/v3.0.64...v3.0.65
https://github.com/microsoft/pxt/compare/v6.0.35...v6.0.38

**Comment by abchatra** [comment]
@microbit-matt-hillsdon & @microbit-mark test /stable and see if the issues are fixed. I will release it tomorrow if everything is good.

**Comment by microbit-matt-hillsdon** [comment]
No more hang testing via https://debug.microbit.org/stable.html

I'll remove the debug pages references on this issue after you've released.
