### ISSUE TITLE
Games blocks example (crashy bird) Python error

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#3880]
> Support ticket 43316

**Describe the bug**
Running the Crashy Bird examples https://makecode.microbit.org/projects/crashy-bird works in Blocks and JS, but not Python.

**To Reproduce**
1. Go to https://makecode.microbit.org/projects/crashy-bird
2. Click on "Edit" in any of the complex examples (the first few do work)
    - For example: [this project](https://makecode.microbit.org/#project:XQAAgABmFwAAAAAAAAA9goAXHC4MqgeNHgoIMpsTCTurzyZquKQOb1TCv3qwnSSNmLVmmhapbG3CLd9v/08vze9hGTbDQcEgiQ7zameFHVXeaX1Bi+bpD0uW9wz0qHcNVIoLI0pa9n3oHdXD8L6PC6HkcsSPPhIsRhvgXYLU2fRKcqdq8OraCxeInVwaj/NxeWc22fFNmkZfVCcAKhkvXNoM5WlPeerioGzp586mCGGdoIbfcktwO7er3/n46PjsgTuYEsWiz1U6P1XCp/d2AgRJPfqyy7EKFjhaTgFMH/1OM1AlYmMRO8KlbQu4rKyirqMW7kvlXrzFNJrXaGzhzxhK5of4B29EkJMji1wlcK0PMsuzquMcC1WgirraJYsUqrBqba/SHdPXSXlWUYGA05N5ZbWB0yzHzSdPF14W3rCLKadv2XpwAVh33Sz9MOdmSh70x9qnhUM+yIf5hESCnrWH78PFJDcbpK98wd6K/7nRggAvNVOb0j9SES/9VjyNEc4cT/YDxRITY2MyNb5Bvfac3cNakUsM5oLdP8W+kdLCqPPEPL6SfDcOZmNkYE/xnJFPEpZ7pyQWViQOcLYjompUcvUJ5sBqpZ7k3blL+ZIWXiX1e9qxaHfywvStKjEetLXZvJoXYPfrgnKdX8oHvOLoo18GkAoeW/fKHK3xycV9dJEPZtPMwGVPelcRyDZhU1EpsfMQEbjMO8WvY40nO7iDZ2TVHNYbuDLrtOItftTkc9MxILrPIJwnRw6DcimDNV70DC64gLbQKFjo69JDA6y5WMrqbwqiWwfF7pqskJjLnsmzFJZKcF9Hu9DnG0s2i6tX0NYTnTRyEGMWuqtSi93QxOUro7KHJmo5r2ZBzcvngcJ5CEosSM5vRdGY/LR0eE4IknWntmomwp4d/wrDgQXqyPLKoZvFH+EWku5XxVGECcjCka2/studRKITKyrmYM85F+t2LtP2jLVWSZwmln6yKfnCi0dMQXf5WhF2alq6HstAof9Wea/2Ww9mIQH/W9SOvvagnsFYx/mu1DjJVGDG9HRbuvnrPevODtOspw7FUmWiJz0F/4lhXd2TcTDnNUtLS8x7xex/RKOue77j5DsoWLaZvfZxv0xaJ3q40L+6Acn8njotEGkhRfnBCiaD+KTHDsvId16zSmMD72QxiAajFBoLc58vUvmuKuO017thOOh+iVxZlgj3HIoKCa/GDWNa9U5eDIksTbqlbnRlSYaQPtX3xAYLL1+gE05BbbyQoYieQhNfpBvOPTkaywstytft4g8y61o7u5v+E1uEpi9FCduW46aISYxBX5IU+ZuADtfFfyrtUVReLyFrxEaaQqsc3vf4s/lfbujP7XJTiRNrwsXJzHu+MjKXkXvgnYrEeBQqHgp2w+tPmzoksKCXutD2KBPFNb4nt8l84nI0P9thOwvXui+62CiuK0TrhMjzMh4pyo7Cfd0efGSkdBlqb3+mWMMCx5r859ZMikb+mupA0gtGBuoB57x9z9g0Ygusl29/usAMJK7oWlQVVkriWdO33jvqkoYqm45BFuEn6cesnR0CYVbBcOvG/dwia2Xt40++exZLKPO41RufWSz++MDxsQ==)
3. Open the Python code
4. See error:
    - From Live editor:
      ![image](https://user-images.githubusercontent.com/29712657/107973404-16f34880-6fad-11eb-88f9-4c90909e9354.png)
        - makecode.microbit.org version:  3.0.66
        - Microsoft MakeCode version:  6.0.38
        - microbit runtime version:  v2.2.0-rc6
    - From beta:
      ![image](https://user-images.githubusercontent.com/29712657/107973563-41dd9c80-6fad-11eb-9e85-0564b00e4cd3.png)
       - makecode.microbit.org version:  3.1.52
       - Microsoft MakeCode version:  6.9.10
       - microbit runtime version:  v2.2.0-rc6
       - codal-microbit-v2 runtime version:  v0.2.24

**Expected behavior**
No errors in the Python code

**Screenshots**
Shown in the reproduction steps.

**micro:bit version (please complete the following information):**

N/A

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version 88

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by abchatra** [comment]
This is duplicate https://github.com/microsoft/pxt-microbit/issues/3579
