### ISSUE TITLE
Feature: Improve UX around using strings, booleans in variables

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3881]
micro:bit support: 43298 

**Is your feature request related to a problem? Please describe.**

The variable block defaults to an integer value. It is not obvious how to change this to a string (which would be the most common other option) or anything else.

You need to find an empty string from the text block menu

https://user-images.githubusercontent.com/31242877/108058268-b2d39180-704b-11eb-9db8-29d16aefaa51.mp4

**Describe the solution you'd like**

I's currently easier to assign a string in text mode, just by entering it between  `""` eg

```
let x = 0
let y = "string"
```

It should be just as simple to do this with the variable block, by entering a string in place of the number, but it is currently not possible

https://user-images.githubusercontent.com/31242877/108058844-8409eb00-704c-11eb-840e-9e8d206c933a.mp4

**Describe alternatives you've considered**

**Additional context**

**Comment by abchatra** [comment]
No plans to implement as it is impossible to figure out the right semantics. What if some one wants string "525"? We can't automatically detect these scenarios.
