### ISSUE TITLE
onPulsed() not working on pin 16 in micro:bit v2

### ISSUE THREAD

**Issue by kboyd12345** [microsoft/pxt-microbit#3882]
**Describe the bug**
The onPulsed() event doesn't appear to fire for pin 16 using v2 of the micro:bit.

**To Reproduce**
```
pins.onPulsed(DigitalPin.P16, PulseValue.High, function () {
    serial.writeLine("16")
})
```

(Note that it doesn't work with PulseValue.Low either)

This behaviour happens in v2 but not in v1.5, where it works as expected

**Comment by martinwork** [comment]
Related:
https://github.com/lancaster-university/codal-microbit-v2/issues/50
https://github.com/microsoft/pxt-microbit/issues/3791
https://github.com/microsoft/pxt-microbit/issues/3838

**Comment by kboyd12345** [comment]
I've been having a conversation with Martin on the other github page about this topic. There is clearly an issue with Pin16 and it's not working with edge events as per his post. He pointed me to https://makecode.microbit.org/reference/pins/set-events where it describes that you can use edge events using the makecode platform. This is a super-useful feature but I couldn't find this on the documentation until Martin pointed me there. Is there a reason for its reduced visibility?

**Comment by abchatra** [comment]
I am closing this bug in favor of existing one #3791
