### ISSUE TITLE
amplifier attached to P0 does not output sound on micro:bit V2

### ISSUE THREAD

**Issue by Aerospacesmith** [microsoft/pxt-microbit#3883]
We've been working with the Foundation for a while now developing our own product, the Spark:bit, which has an embedded V2 micro:bit inside. While working on our Makecode extension, we encountered an odd issue with the audioblocks, built-in speaker, and our own speaker. We have an external speaker connected to P0 via a capacitor and MOSFET amplifier which you can see below: 
![image](https://user-images.githubusercontent.com/5132118/108148023-9d835500-7095-11eb-8502-c5c7153fda97.png)

On the micro:bit V1, this worked great to give a nice, loud sound, but on V2, it does not work unless we use "analog set pitch pin". However, this means that V2 sound expressions do not work, as I see in issue https://github.com/microsoft/pxt-microbit/issues/3611 .

Using the block "set audio pin to P0" at first appeared to not output audio from P0. Using this block made no sound come from our speaker (melodies, beats, nor V2 expressions), but then I attached some earbuds to it and found that it is outputting the sounds, but nothing from our amplifier. What is the difference between the audio generated by the audio mixer method and the PWM output method? I do not have an oscilloscope available right now to look at the actual waveforms generated.

Below is the version info of the MakeCode beta I'm using:

makecode.microbit.org version:  3.1.52
Microsoft MakeCode version:  6.9.10
microbit runtime version:  v2.2.0-rc6
codal-microbit-v2 runtime version:  v0.2.24

**Comment by abchatra** [comment]
@jaustin ?

**Comment by jaustin** [comment]
The difference here is that when using the 'advanced' (V2) sounds the output is PCM audio - IE @finneyj has built a DAC with high-frequency (~45Khz) PWM - we have a higher carrier frequency than the audio. When you use the 'analog set pitch pin' we revert to the V1 compat audio that doesn't do this. this DAC approach is required for the advanced sounds on V2, so it's not really possible to offer the sounds without the 'DAC'. 

It seems like in this case perhaps something isn't switching fast enough.... The decoupling you have looks pretty similar to that on the board for the built-in speaker - with a 100nF/100K filter.

You will likely also want to look at the setSilenceLevel API - which is there for accessory makers to change the behaviour of P0 when the board should be 'silent' - some amplifier pick up noise in the idle carrier signal and so you can choose to ground P0 for silence (which is more like the V1 behaviour).

**Comment by Aerospacesmith** [comment]
It turns out the MOSFET we were using had too high gate charge and could not switch fast enough. After swapping to a faster MOSFET, the sound now works. Though as @jaustin pointed out, it now hisses when no audio is playing so we will need to implement setSilenceLevel.

**Comment by Aerospacesmith** [comment]
Using setSilenceLevel(0) works great. I'm closing this issue.
