### ISSUE TITLE
Link to File System extension not working in docs

### ISSUE THREAD

**Issue by ngammarano** [microsoft/pxt-microbit#3888]
**Describe the bug**
There is a broken link in [the docs in "Extensions"](https://makecode.microbit.org/extensions).
The "File System" extension under the ["Utilities"](https://makecode.microbit.org/extensions#utilities) category.

The link is not broken: https://github.com/microsoft/pxt-filesystem, but the problem is that as the GitHub repository is archived, the File System extension does not appear correctly:
https://makecode.microbit.org/pkg/microsoft/pxt-filesystem

**Comment by abchatra** [comment]
This package is deprecated as it didn't work. There is a new filesystem proposal which we are working on. I have removed it from the extensions. https://github.com/microsoft/pxt-microbit/pull/3889
