### ISSUE TITLE
Feature: more than 2 micro:bits in multi MakeCode editor

### ISSUE THREAD

**Issue by ngammarano** [microsoft/pxt-microbit#3890]
**Is your feature request related to a problem? Please describe.**
Some projects require 3 or more micro:bits interacting with each other. This is not possible to simulate in MakeCode, as the current [multi editor](https://makecode.com/multi) only has the possibility to show 2 different programs.

**Describe the solution you'd like**
I'd like the possibility to have more than 2 programs (for projects with more than 2 micro:bits).

**Describe alternatives you've considered**
I understand that if the screen is further divided, each screen would be very small, so maybe a micro:bit selector would be an interesting option. For example, a droupout selector where I can select micro:bit 1 and it shows the program of micro:bit 1. It would be also great to have an "add micro:bit" button or "remove micro:bit" as well as a "name micro:bit" so you do not have to remember which number is each micro:bit (e.g. "Tx micro:bit" and "Rx micro:bit" instead of "microbit 1" and "micro:bit 2").

I want to cover projects with more than 2 micro:bits interacting with each other, mainly with radio messages.

It would be awesome (en extra plus) if there could be also wire connections between micro:bits (program a pin of micro:bit 1 as output and connect it to a pin of micro:bit 2 programmed as input); but I think this is a completely different feature.

**Additional context**
I am thinking something like Autodesk Tinkercad Circuits, where you can add as many micro:bits as you like and edit their program independently. See for example [this Tinkercad Circuits project with micro:bit](https://www.tinkercad.com/things/bbCUlvOz1j8-microbit-controlled-tic-tac-toe) (based on [this project](https://www.instructables.com/Microbit-Controlled-Tic-Tac-Toe-Game/)).

**Comment by abchatra** [comment]
We don't have bandwidth to implement this.

**Comment by y2k04** [comment]
What do you mean by that? How do you not have enough bandwidth? It's not being simulated on the server, it is being simulated in the browser, so what would stop this from working?

**Comment by abchatra** [comment]
We don't have engineering bandwidth (or cycles) to implement this (not network bandwidth). We take pull request. If you want to implement this, feel free and do a PR>
