### ISSUE TITLE
Feature: group the SPI and I²C blocks under the same group

### ISSUE THREAD

**Issue by ngammarano** [microsoft/pxt-microbit#3898]
## Is your feature request related to a problem? Please describe.
When I use the micro:bit with SPI or I²C communication, I look for the blocks in the Advanced > Pins > more category.
But here the SPI and I²C blocks are mixed with the other pin blocks (they are not all together), so I take more time to look for those blocks.
SPI blocks are not all together.
![image](https://user-images.githubusercontent.com/54072413/109958839-7186e700-7cc5-11eb-8590-727c9920a28c.png)

## Describe the solution you'd like
I'd like a group "SPI" (one like the "micro:bit (V2)" group) in the category "Pins" > "more" that groups the blocks:
* spi write
* spi frequency
* spi format bits mode
* spi sets pins MOSI MISO SCK

I'd like a group "I²C" in the category "Pins" > "more" that groups the blocks:
* i2c read number at address of format repeated
* i2c write number at address with value of format repeated

**Comment by abchatra** [comment]
Lets try to categorize Pins and ideally other categories in this release.
