### ISSUE TITLE
Edge - Documentation  

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#39]
1 open Edge

2 codemicrobit.com/lessons

3 (example)  https://codemicrobit.com/lessons/charting/activity

4 i would expect the program this program to `run` in the simulator

![image](https://cloud.githubusercontent.com/assets/11206682/14362132/0bbf4026-fcb3-11e5-8827-4a9ec33d5124.png)

**Comment by pelikhan** [comment]
Fixed.
