### ISSUE TITLE
Icons or Images in drop down selectors

### ISSUE THREAD

**Issue by JoshuaAHill** [microsoft/pxt-microbit#3901]
**Is your feature request related to a problem? Please describe.**
Im developing an extention to do with sound, which allows the user to select different types of wave (sine, square etc.) to playback the sound. However this isnt overly beginner friendly.

**Describe the solution you'd like**
Instead of having words as a dropdown, icons or images provide a more visual, easier to understand selection option:
![image](https://user-images.githubusercontent.com/37069297/110783089-da3f0800-825f-11eb-8360-1643d9e2016f.png)
vs
![image](https://user-images.githubusercontent.com/37069297/110783296-25f1b180-8260-11eb-80cc-48383cf1d329.png)

**Describe alternatives you've considered**
tried using an icon - similar to how the icon for the category is defined - but dosnt seem like this is supported
![image](https://user-images.githubusercontent.com/37069297/110783002-bc71a300-825f-11eb-8b8e-5af209a00388.png)

**Additional context**
Are there any options that currently exist that provide a similar level of functionality or is it just text enums that can be added in the drop downs as the moment?

**Comment by joshkordek3** [comment]
Try this: https://makecode.com/playground#field-editors-gridpicker

**Comment by abchatra** [comment]
Yes that is the right field editor.

**Comment by JoshuaAHill** [comment]
Thanks Josh and abchatra for highlighting that field editor - really I would be looking to add icons/images to the list instead of text, as seen in the on input blocks added in this commit: https://github.com/microsoft/pxt-microbit/pull/803/commits/1f529255141a032bdee7d01d1742603233d31418
![image](https://user-images.githubusercontent.com/37069297/112822730-36879180-9080-11eb-8971-a77e6b194d77.png)

So I was hoping to replicate this functionality and add my own icons, however it seems like most of this is baked into pxt using a custom 'gestures' selector and not a gridpicker - is there any scope for achieving this as part of an extention?
