### ISSUE TITLE
Neopixel extension pack can't switch language.

### ISSUE THREAD

**Issue by Dolphinzzx** [microsoft/pxt-microbit#3902]
**Describe the bug**
Neopixel extension pack can't switch language.

After i add Neopixel extension pack, when i switch language it can't change language.

As shown below.
![image](https://user-images.githubusercontent.com/31792429/110910141-e86a5280-834b-11eb-95c9-b21d6a40c664.png)

**Comment by jwunderl** [comment]
I fixed this a while back with https://github.com/microsoft/pxt/pull/7622, but it hasn't made it's way to the live site yet; this works properly in makecode.microbit.org/beta now though / will work when we release!
