### ISSUE TITLE
Docs for Eddystone Bluetooth services do not exist

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3910]
Are the BLE docs incomplete or has something moved?

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/31242877/111662978-4abdca00-8808-11eb-8baa-e9fe38f072ed.png">

These links do not work
https://makecode.microbit.org/reference/bluetooth/advertise-uid
https://makecode.microbit.org/reference/bluetooth/advertise-url

This one does
https://makecode.microbit.org/reference/bluetooth/stop-advertising

**Comment by microbit-mark** [comment]
^ @ganicke

**Comment by pelikhan** [comment]
Eddystone is not supported by Google, we should deprecate this.

From: Mark ***@***.***>
Sent: Thursday, March 18, 2021 9:41 AM
To: microsoft/pxt-microbit ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/pxt-microbit] Docs for Eddystone Bluetooth services do not exist (#3910)


Are the BLE docs incomplete or has something moved?

[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F31242877%2F111662978-4abdca00-8808-11eb-8baa-e9fe38f072ed.png&data=04%7C01%7Cjhalleux%40microsoft.com%7C9da0bd295e274976238308d8ea2c94ff%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637516824484575976%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5th0lEA65ayYlbgmKpp%2BEhvnEDxj9%2BtXBAtoNi7lmGI%3D&reserved=0>

These links do not work
https://makecode.microbit.org/reference/bluetooth/advertise-uid<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmakecode.microbit.org%2Freference%2Fbluetooth%2Fadvertise-uid&data=04%7C01%7Cjhalleux%40microsoft.com%7C9da0bd295e274976238308d8ea2c94ff%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637516824484585972%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qBpKEaG5UQ2Ga6E73B%2BGZCdOLA%2B5c1IONd5gj%2BuUcYo%3D&reserved=0>
https://makecode.microbit.org/reference/bluetooth/advertise-url<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmakecode.microbit.org%2Freference%2Fbluetooth%2Fadvertise-url&data=04%7C01%7Cjhalleux%40microsoft.com%7C9da0bd295e274976238308d8ea2c94ff%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637516824484585972%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=b6YUZUpIX8z6d0rzNPJTWOQ2JFVZ3TYp6x2JdkJmVT0%3D&reserved=0>

This one does
https://makecode.microbit.org/reference/bluetooth/stop-advertising<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmakecode.microbit.org%2Freference%2Fbluetooth%2Fstop-advertising&data=04%7C01%7Cjhalleux%40microsoft.com%7C9da0bd295e274976238308d8ea2c94ff%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637516824484595971%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oka8ZxYqQXoHRCGUBksPt4EnIvULU%2Btbg%2BgKdMFxgAg%3D&reserved=0>

-
