### ISSUE TITLE
MakeCode project name inconsistent. Varies with view.

### ISSUE THREAD

**Issue by kjcole** [microsoft/pxt-microbit#3914]
**DESCRIPTION**

When browsing https://makecode.microbit.org/ and the list "**My Projects**" view is being shown, the projects retain their original names, despite being changed on GitHub and in the comment(?) (title? description?) field at the bottom of the project page, next to the GitHub upload icon (directly below the categories / modules menu to the left of the code being edited.

However, clicking the `View All` link shows the name -- albeit wrapped mid-word -- from the comment(?) field.

**EXPECTED BEHAVIOR**

There should be a way to rename a project and have it retain the new name in all views.

**HARDWARE**

micro:bit version 2.0

**DESKTOP**

OS: Linux (Ubuntu Studio 20.04)
Browser: Chromium (Version 88.0.4324.182) and Firefox (Version 86.0)

**Comment by abchatra** [comment]
Fixed
