### ISSUE TITLE
extension not appearing in blocks

### ISSUE THREAD

**Issue by joshkordek3** [microsoft/pxt-microbit#3916]
**Describe the bug**
I created an extension, but whenever I try to use blocks, it doesn't appear, in Javascript or Python it works just fine, what might be the cause?

**To Reproduce**
1. Go to 'makecode.microbit.org'
2. Create a new project
3. Switch to Blocks (If you haven't already)
4. Open files 
5. Download the file below
6. if necessary **Rename** the file below to .hex in files (I cannot send hex files, I think) again, **do not convert, only rename**
7. Click on settings
8. Click on Extensions
9. Scroll down to import
10. Import the file that you get from that you get from #5/#6
![microbit-worldgame-extension](https://user-images.githubusercontent.com/79750252/111892515-1c720180-8a37-11eb-945c-d8adcde5601e.hex)
if above does not work, use this file and do #6:
![microbit-worldgame-extension](https://user-images.githubusercontent.com/79750252/111892515-1c720180-8a37-11eb-945c-d8adcde5601e.jpg)

**Expected behavior**
It shows the game icon and has a name World beside it

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**micro:bit version**
it is not an issue with micro:bit so I cannot say.

**Desktop/Laptop/Computer**
 - Chrome OS (Chromebook)
 - Chrome
 - Version 89.0.4389.82 (of Chromebook)

**Additional context**
I see nothing wrong with the program.
here is the program (yes, I know there is ways to simplify it, but at least it works...) :
```
//% color=#088530 weight=50 icon="\uf11b" block="World"
namespace World {
//% block="move $leftrightupdown left/right/up/down by $steps"
//% group="Moving"
export function move (leftrightupdown: string, steps: number) {
    if (leftrightupdown == "left") {
        leftright_difference += steps
    } else if (leftrightupdown == "right") {
        leftright_difference += 0 - steps
    } else if (leftrightupdown == "up") {
        updown_difference += steps
    } else if (leftrightupdown == "down") {
        updown_difference += 0 - steps
    }
    show()
}
//% block="move $leftrightupdown and $leftrightupdown2 by $steps"
//% group="Moving"
export function move_ (leftrightupdown: string, leftrightupdown2: string, steps: number) {
    move(leftrightupdown, steps)
    move(leftrightupdown2, steps)
    show()
}
//% block="update the display of the world"
//% group="Diplaying"
export function show () {
    basic.clearScreen()
    for (let index = 0; index <= world.length - 1; index++) {
        led.plot(parseFloat(world[index].substr(0, 2)) + leftright_difference, parseFloat(world[index].substr(2, 2)) + updown_difference)
    }
}
//% block="x position"
//% group="Position"
export function x_pos () {
    return 2 - leftright_difference
}
//% block="y position"
//% group="Position"
export function y_pos () {
    return 2 - updown_difference
}
//% block="go to x: $x y: $y"
//% group="Position"
export function goto (x: number, y: number) {
    updown_difference = 2 - y
    leftright_difference = 2 - x
    show()
}
//% block="number of blocks in the world"
//% group="Position"
export function world_blocks_detect () {
    return world.length
}
//% block="is there a block at x: $x_pos y: $y_pos"
//% group="Detect"
export function block_detect (x_pos: number, y_pos: number) {
    temp_txt = convertToText(x_pos)
    temp_txt2 = convertToText(y_pos)
    for (let index6 = 0; index6 < 2 - temp_txt.length; index6++) {
        temp_txt = "0" + temp_txt
    }
    for (let index7 = 0; index7 < 2 - temp_txt2.length; index7++) {
        temp_txt2 = "0" + temp_txt2
    }
    return world.indexOf("" + temp_txt + temp_txt2) != -1
}
//% block="world $xy (x/y) coordinate at item $place (min=1)"
//% group="Position"
export function world_blocks (xy: string, place: number) {
    if (xy = "x") {
        return parseFloat(world[place - 1 ].substr(0, 2))
    } else if (xy = "y") {
        return parseFloat(world[place - 1].substr(2, 2)) 
    }
    return 0
}
//% block="world (array)"
//% group="Position"
export function all_world_blocks () {
    return world
}
//% block="add by $columnrow (column/row) from $from_xy to $to_xy on $xy"
//% group="Creating"
export function add_by (columnrow: string, from_xy: number, to_xy: number, xy: number) {
    if (columnrow == "column") {
        for (let index2 = 0; index2 <= to_xy - from_xy; index2++) {
            add(xy, index2 + from_xy)
        }
    } else if (columnrow == "row") {
        for (let index3 = 0; index3 <= to_xy - from_xy; index3++) {
            add(index3 + from_xy, xy)
        }
    }
}
//% block="add x $x and y $y to the world"
//% group="Creating"
export function add (x: number, y: number) {
    temp_txt = convertToText(x)
    temp_txt2 = convertToText(y)
    for (let index4 = 0; index4 < 2 - temp_txt.length; index4++) {
        temp_txt = "0" + temp_txt
    }
    for (let index5 = 0; index5 < 2 - temp_txt2.length; index5++) {
        temp_txt2 = "0" + temp_txt2
    }
    world.push("" + temp_txt + temp_txt2)
}
let temp_txt2 = ""
let temp_txt = ""
let world: string[] = []
let updown_difference = 0
let leftright_difference = 0
}
```

**Comment by abchatra** [comment]
We need simpler repro to look. Please share your extension.

**Comment by joshkordek3** [comment]
https://github.com/joshkordek3/world-game-extension
the extension does not appear, I can use it, but it does not show and therefore I am not able to use it in blocks:
![Screenshot 2021-03-26 12 22 48](https://user-images.githubusercontent.com/79750252/112576954-5758a880-8e2e-11eb-8ba1-b42d5ce12a89.png)

**Comment by abchatra** [comment]
Shows up for me 
![image](https://user-images.githubusercontent.com/6107272/112577379-71a07100-8db1-11eb-93f5-4ccbc0c0c09c.png)

**Comment by abchatra** [comment]
Refresh your page. May be it didn't refresh.

**Comment by abchatra** [comment]
Just search for https://github.com/joshkordek3/world-game-extension in the extension window. You will be able to see your extension and add it.

**Comment by jwunderl** [comment]
This repros if you go to add the extension twice, looks like another api caching bug. We should handle better it but I suspect it's https://github.com/joshkordek3/world-game-extension/blob/master/pxt.json#L2 having a slash in it -- you might be able to work around the issue for now by changing that line to

```
    "name": "world-game-extension"
```

**Comment by joshkordek3** [comment]
once I reload the page or change the language it disappears

**Comment by joshkordek3** [comment]
@jwunderl I do not understand

**Comment by jwunderl** [comment]
@joshkordek3 It looks like you applied the fix correctly / that it's working again for your project as of https://github.com/joshkordek3/world-game-extension/commit/988393ee39227418a84135866cd15c388f72c98d 

(the last portion of my comment was intended towards the team if that's the portion you did not understand - just pointing to where in our code this repo was breaking, in case someone else ends up taking a look at this issue before I get the chance to)
