### ISSUE TITLE
position degree in servo blocks does not work in Hungarian translation

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3917]
micro:bit support: 43994

When using the servo blocks with the Hungarian translation, the block to set the position does not allow the user to input the position.

![image](https://user-images.githubusercontent.com/31242877/111992458-5c0b1d00-8b0d-11eb-8f55-ec041ad1486c.png)

**Comment by pelikhan** [comment]
@ganicke  @jwunderl looks like a broken translation

**Comment by jwunderl** [comment]
Yeah, broken translation. Beta is filtering it out properly, will clear it in crowdin for now~

**Comment by jwunderl** [comment]
Fixed on crowdin, should show up in ~ 12-24 hrs
