### ISSUE TITLE
Feature: Allow to record sound or upload WAV file to be played by micro:bit V2 buzzer

### ISSUE THREAD

**Issue by ngammarano** [microsoft/pxt-microbit#3918]
## Is your feature request related to a problem? Please describe.
It would be great to have more variety of sounds to reproduce with the buzzer and invent new sounds with the microphone (like in Scratch) to be reproduced with the blocks "play sound" and "play sound until done" under the "Music" category.

## Describe the solution you'd like
To be able to upload a WAV file, or to record with the computer microphone a short audio for the buzzer to reproduce.

**Comment by microbit-matt-hillsdon** [comment]
> micro:bit support 48314

Interest expressed in this via micro:bit support with a similar request to

> "record your own sound and upload your own sound instead of just using plain notes and melodies".

**Comment by microbit-mark** [comment]
For reference, we have a ticket in CODAL for the creation of the APIs to support this https://github.com/lancaster-university/codal-microbit-v2/issues/70

**Comment by abchatra** [comment]
We don't have plan to support external wav files. But we will have support for recording your own sounds and play back in this release as  an extension.
