### ISSUE TITLE
Feature: Discarded blocks are saved

### ISSUE THREAD

**Issue by joshkordek3** [microsoft/pxt-microbit#3919]
**Is your feature request related to a problem? Please describe.**
Its frustrating that whenever I turn to Javascript or Python to change something, then all the blocks that I wasn't using were discarded

**Describe the solution you'd like**
whenever it converts to Python or Javascript I would like it to add the not used blocks as ```///``` and then the code (```///``` if Javascript, ```##``` if Python)

**Comment by abchatra** [comment]
We keep the discarded blocks when you go to javascript\python and come back.
