### ISSUE TITLE
Strange behaviour when using beta version via Brave browser

### ISSUE THREAD

**Issue by dsssssssss9** [microsoft/pxt-microbit#3922]
**makecode.microbit.org version:  3.1.62

Microsoft MakeCode version:  6.13.2

microbit runtime version:  v2.2.0-rc6

codal-microbit-v2 runtime version:  v0.2.25

Brave Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)**

When connected to the Micro:Bit in the Beta version of the editor via Brave Browser, when the editor window is active the Yellow LED on the reverse flashes constantly.

As soon as the editor window is not active or closed the flashing stops

I have not noticed this behaviour in the past so although it appears not to be particular serious or affect the operation of the Micro:Bit I thought i'd let you know

**Comment by abchatra** [comment]
We only support Firefox, Edge & Chrome today.
