### ISSUE TITLE
microbit not detected as PWA application

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3931]
PWA can be "installed" from Edge and CHrome. micro:bit must be missing a manifest because it is not detected as such.

**Comment by abchatra** [comment]
I could install microbit as pwa 
![image](https://user-images.githubusercontent.com/6107272/115627855-8c80db00-a2b4-11eb-8362-431c178dbdf8.png)

**Comment by pelikhan** [comment]
It is not suggested in the address bar in Edge/Chrome

________________________________

**Comment by abchatra** [comment]
Can you add a screenshot of the website which is suggested? I don't see this in even on bing.com site.

**Comment by pelikhan** [comment]
Outlook can be installed as PWA.

**Comment by pelikhan** [comment]
I’ll add screenshots

________________________________

**Comment by pelikhan** [comment]
You should see a little icon near the right side of the address bar. In my case, it's already installed
![image](https://user-images.githubusercontent.com/4175913/115635235-15e9da80-a2c0-11eb-93dc-579b70b99bd0.png)

**Comment by pelikhan** [comment]
More info on lighthouse checks for PWA https://web.dev/lighthouse-pwa/

**Comment by pelikhan** [comment]
There seems to be 2 minor issues that prevent proper PWA support (found by running lighthouse)
![image](https://user-images.githubusercontent.com/4175913/115727649-a8c65b80-a338-11eb-817c-c2dde3003392.png)

**Comment by pelikhan** [comment]
We are using the "sim.webmanifest" as the manifest of the main editor. This seems wrong.

![image](https://user-images.githubusercontent.com/4175913/117374105-65fc9b80-ae81-11eb-81b1-842eb0d994c0.png)

This is probably where the problem starts

https://github.com/microsoft/pxt/blob/d0ec5d92f120492142330e264cff57ba5d5cb364/docfiles/appmeta.html#L4

**Comment by riknoll** [comment]
The issue is that the manifest is being served from a different domain (pxt.azureedge.net). We need to hit the backend directly

**Comment by abchatra** [comment]
@riknoll is this fixed?

**Comment by riknoll** [comment]
No it is not. I had to switch to CDN stuff
