### ISSUE TITLE
Full Flash + JACDAC leads to 'Bad Trans #1`

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3938]
![image](https://user-images.githubusercontent.com/4175913/112626229-2a37d600-8ded-11eb-817c-df7bae5ff945.png)

Repro:

* use micro:bit v2
* open https://makecode.microbit.org/beta?dbg=1&webusbdbg=1&webusbfullflash=1#editor
* open a new project
* pair webusb
* add JACDAC extension
* download

**Comment by abchatra** [comment]
This one has a repro.

**Comment by pelikhan** [comment]
I added more logging in https://github.com/microsoft/pxt-microbit/pull/3950

**Comment by abchatra** [comment]
Closing for now.
