### ISSUE TITLE
custom.ts function-as-parameter-to-function makes for broken blocks

### ISSUE THREAD

**Issue by SquareFingers** [microsoft/pxt-microbit#3942]
**Describe the bug**
In custom.ts, if a function is made in which one of the parameters is a function itself, dragging the resulting block from the toolbox into the blocks view makes for broken code.

**To Reproduce**
1. Start a new project
2. Click 'JavaScript' (Convert code to JavaScript)
3. Click 'Explorer'
4. Click '+' next to 'Explorer'
5. Click 'Go ahead!'
6. Inside 'namespace custom' paste:
```
    //% block
    export function functionfunction(func: () => void):void {
        // TODO: write code here
    }
```
7. click 'Blocks' (Convert code to Blocks)
8. click 'custom'
9. drag 'functionfunction' from the toolbox to the workspace
10. See the warning triangle appear in the 'functionfunction' block (it may take a few seconds)

**Expected behavior**
The block dragged directly from the toolbox would not immediately give a warning triangle.
(Also, the block dragged from the toolbox would have a notch on the top and a bump on the bottom: what I get is a block without either, like a function definition block. - **EDIT** reporting this second bit was just ignorance on my part, it's dealt with in existing documentation, as is pointed out below.  But the first bit, the triangle, remains an issue.)

**Extra details**
It appears the default block generator (which gets used when there is no ```="block name"``` after the ```//% block```) generates one placeholder at the top of the block for each formal argument in the function declaration... *and* it has space 'inside' the block for statement blocks to go, like 'while' has an 'inside', and this space ends up effectively being another actual parameter.  So, you get the error "Expected 1 arguments, but got 2.".

**Comment by abchatra** [comment]
@SquareFingers does this repro with /beta?

**Comment by SquareFingers** [comment]
> @SquareFingers does this repro with /beta?

As of 7 April 2021, yes, the same happens in https://makecode.microbit.org/beta

**Comment by SquareFingers** [comment]
Also occurs in arcade.makecode.com for anyone who's interested.

**Comment by SquareFingers** [comment]
Also minecraft.makecode.com

**Comment by jwunderl** [comment]
in case this is blocking you in an extension you are trying to make, the issue here is just with default block 'automatic' creation when a block string is not specified -- if you specify the block itself it will work:

```
//% block="function function"
```

We should still fix that, just providing the workaround in case it helps you / anyone else who finds the issue :)

**Comment by SquareFingers** [comment]
> in case this is blocking you in an extension you are trying to make, the issue here is just with default block 'automatic' creation when a block string is not specified -- if you specify the block itself it will work:
> 
> ```
> //% block="function function"
> ```
> 
> We should still fix that, just providing the workaround in case it helps you / anyone else who finds the issue :)

Right... that does resolve the issue of the triangle appearing.

But, I expect what I drag from the toolbox to be a block like "call this function with this parameter... the parameter being code, in this case".  Something I can put inside a "while true do" block, for instance.  What I get from the toolbox is a block like a function-definition block.  It doesn't have a notch on the top.  And, no more than one can be dragged from the toolbox to the workspace.

Hm, you've actually brought my attention to another aspect.  I would expect the block that I drag from the toolbox to have a notch on the top, thanks for that.

**Comment by jwunderl** [comment]
Ah, for that I'll point you at https://makecode.com/playground#events and https://makecode.com/defining-blocks -- we support that style of block with `//% handlerStatement` . We use events *way* more often than we use handler statements so it is the default behavior. (and other things can be specified as well, e.g. allowing multiple duplicate events with `//% blockAllowMultiple=1`

**Comment by SquareFingers** [comment]
`//% handlerStatement` is exactly what I was looking for.  Thank you.
... I guess, it turns out, what I really wanted resolved wasn't what I originally described.  I just wrote a description of the first thing I saw as an obstacle to what I wanted.
Thanks for your help!

**Comment by SquareFingers** [comment]
Oh... yikes.  I guess, since you wrote "We should still fix that", I shouldn't have closed the issue - sorry.  The issue I wanted resolved is closed, but as I just wrote, the issue I described is something else.

**Comment by jwunderl** [comment]
Ah no worries, glad I could help! And thanks for reporting the initial issue as well, it's always good to find obstacles like this.

**Comment by SquareFingers** [comment]
This is probably clear to anyone who has spent time considering this aspect of makecode, but perhaps it's worth mentioning anyway. Another facet of this issue is that if the event has a formal parameter before its final function parameter, then, without ```//% block="function function"```, the block that is automatically generated has two placeholders for actual parameters plus the area for statements 'inside' (like the 'inside' of a while loop), and with ```//% block="function function"```, the block that is generated has no placeholders.  What's needed is something along the lines of ```//% block="function function with $param1"```.
