### ISSUE TITLE
Console Export data and Export text changing to blobs has broken the iOS app

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#3943]
**Describe the bug**
The console exports seem to have have changed from using "data:" to "blob:".

The iOS app is expecting "data:". Snapshot still uses "data:".

This change in MakeCode has broken the iOS app. Users see the "Exporting data..." message but no data is exported.

As far as I know, to catch a "blob:", the app would have to inject javascript into the page in order to read the blob and convert it into a "data:" or a WebKit message, which is convoluted and potentially fragile.

Could we could revert to "data:" right now so the current app release is fixed, and move to using WebKit messages for a future app release?

**To Reproduce**
1. Open MakeCode in the iOS app
2. Connect to a micro:bit sending data
3. Tap on Device console
3. Tap an Export button

**Expected behavior**
The iOS app receives a "data:" and shows a Share dialogue.

**micro:bit version (please complete the following information):**
not hardware related

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS  14.4 iPad Air 2
 - Browser [e.g. chrome, safari] WKWebView

**Comment by martinwork** [comment]
Issue raised in https://support.microbit.org/a/tickets/44255

**Comment by martinwork** [comment]
It looks like https://github.com/microsoft/pxt/pull/7557 has changed the blob/data condition from `!pxt.BrowserUtils.isMobile()` to test `window.URL?.createObjectURL`.

https://github.com/microsoft/pxt/pull/7557/files#diff-0129d0162432ea44235e8fe301cc97fb9f2c2ccbe5b11e964b0b331bf19c6666L372

https://github.com/microsoft/pxt/pull/7557/files#diff-0129d0162432ea44235e8fe301cc97fb9f2c2ccbe5b11e964b0b331bf19c6666R386

And I notice https://github.com/microsoft/pxt-microbit/blob/master/pxtarget.json#L573 has an option to disableBlobObjectDownload.

**Comment by martinwork** [comment]
Looking into this further (see code links below), I noticed:

- In the next version of the iOS app, blobs could be avoided by injecting some javascript to set
window.pxt.appTarget.appTheme.disableBlobObjectDownload.

- Hex downloads from Safari are no longer passed to the iOS app. That feature was implemented via a custom scheme which is registered by the app to make a direct link, but this is bypassed by the blobs. 

- The "data:" URLs used to specify the mime type, but now include a file name instead of the mime type. 


Code links...

The export options have always called browserDownloadAsync, passing a filename ending .CSV or .TXT and contentsType text/csv or text/plain: https://github.com/microsoft/pxt/blob/37ce9602d8f042f17bcdf4bdce75435f5eac4007/webapp/src/serial.tsx#L421

browserDownloadAsync calls browserDownloadBinText which calls browserDownloadBase64.
These used to pass on the contentType parameter, which was put into the data URL:
https://github.com/microsoft/pxt/blame/f14a84b0bff3a4972844e49953c65ea7dc3ff9de/pxtlib/browserutils.ts#L314

contentType has moved into "opts", and the file name rather than the contentType is passed to toDownloadDataUri, which forms the data URL: https://github.com/microsoft/pxt/blob/ff50ead085967bdc26cb47fc343c63472eb2f6ca/pxtlib/browserutils.ts#L400

toDownloadDataUri uses the protocol which is registered by the iOS app, for a direct link:
https://github.com/microsoft/pxt/blob/ff50ead085967bdc26cb47fc343c63472eb2f6ca/pxtlib/browserutils.ts#L359

**Comment by martinwork** [comment]
I have succeeded in downloading the "blob:"s and the mime type for the blob. I can't see a way to get the filename.

It would be good to use webkit messages. See: https://github.com/microsoft/pxt-microbit/issues/1689

Related: Snapshot still uses a "data:" URL with a mime type "application/octet-streamng", which maybe comes from a mistake in the regular expression at https://github.com/microsoft/pxt/blob/master/pxtblocks/blocklyloader.ts#L1578, which tries to replace "image/png", but only matches "image/p".

**Comment by abchatra** [comment]
@martinwork is this still an issue?

**Comment by martinwork** [comment]
Feel free to close. You might want to close https://github.com/microsoft/pxt-microbit/issues/1689 too,
The app now has workaround, but it's not ideal because it can't find the file name.

**Comment by abchatra** [comment]
Thanks! Let me close it for now. We can add new issues in the future when we have bandwidth to address these
