### ISSUE TITLE
Featuer: Add new Bluetooth Services for the micro:bit V2 sensors

### ISSUE THREAD

**Issue by ngammarano** [microsoft/pxt-microbit#3944]
## Is your feature request related to a problem? Please describe.
Currently, the micro:bit Bluetooth profile defines some Bluetooth services among which an accelerometer service, a magnetometer service, a temperature service, a button service, a LED service, an IO pin service, an event service and a UART service (see the Bluetooth profile [here](https://lancaster-university.github.io/microbit-docs/resources/bluetooth/bluetooth_profile.html) and [here](https://lancaster-university.github.io/microbit-docs/ble/profile/#gatt-services)).

With the new features implemented in the new micro:bit V2 (logo button, microphone, and speaker), there could be more Bluetooth services for those V2 features (e.g. a Logo Button Service -or to add the logo button in the current Button Service-, a Microphone Service that returns the sound level).

## Describe the solution you'd like
A "bluetooth logo button service" and a "bluetooth microphone service" blocks under the Bluetooth category in MakeCode.

**Comment by pelikhan** [comment]
This request needs to be upstreamed to CODAL. @microbit-mark @jaustin

**Comment by microbit-mark** [comment]
Raised in https://github.com/lancaster-university/codal-microbit-v2/issues/94

**Comment by abchatra** [comment]
I am closing this in MakeCode as we have a upstream bug tracked in codal.
