### ISSUE TITLE
file creating bug

### ISSUE THREAD

**Issue by joshkordek3** [microsoft/pxt-microbit#3947]
**Describe the bug**
when I create a new file for an extension, I use .json and I can create a file that uses json code, but if I try to create a file that uses .jres then it creates a file called (name).jres.ts

**To Reproduce**
1. Go to https://makecode.microbit.org
2. Click on 'create new project'
3. enter any name you want
4. Click 'ok'
5. write a tiny bit of code in javascript
6. upload to github
7. once it finishes uploading click 'explorer' (you have to be in javascript for the button to appear)
8. click the '+'
9. name the file test.jres
10. see the error?

**Expected behavior**
for it not to add .ts after I already specified the language

**Screenshots**
(I'm using an extension I made before, don't mind the name)
![Screenshot 2021-04-03 12 26 28](https://user-images.githubusercontent.com/79750252/113467890-0bce7c00-9478-11eb-9fe1-bad4582028e2.png)
![Screenshot 2021-04-03 12 26 36](https://user-images.githubusercontent.com/79750252/113467973-11c45d00-9478-11eb-8217-28c3587e4f10.png)
![Screenshot 2021-04-03 12 26 47](https://user-images.githubusercontent.com/79750252/113468064-17ba3e00-9478-11eb-9d96-9ab0cc262686.png)

**micro:bit version (please complete the following information):**
not hardware

**Desktop (please complete the following information):**
 - OS: Chromebook (Chrome OS)
 - Browser: Chrome
 - Version: 90.0.4430.36

**Additional context**
none

**Comment by joshkordek3** [comment]
and if I try to add it in the pxt.json, it just breaks the whole project:
(just ignore every project except for clock-extension)
![Screenshot 2021-04-03 12 33 36](https://user-images.githubusercontent.com/79750252/113468512-2bb26f80-9479-11eb-93b5-31663e3fd8f1.png)
![Screenshot 2021-04-03 12 33 42](https://user-images.githubusercontent.com/79750252/113468526-3b31b880-9479-11eb-8033-934214587956.png)
![Screenshot 2021-04-03 12 34 00](https://user-images.githubusercontent.com/79750252/113468529-41279980-9479-11eb-8ee0-88ca24032611.png)

**Comment by abchatra** [comment]
@joshkordek3  can you try /beta and see if this repros in /beta?

**Comment by joshkordek3** [comment]
I don't understand what is /beta

**Comment by abchatra** [comment]
makecode.microbit.org/beta

**Comment by joshkordek3** [comment]
it still happens, but if I create the file in pxt.json before adding it to github then it works.
