### ISSUE TITLE
```control.waitMicros``` not working

### ISSUE THREAD

**Issue by joshkordek3** [microsoft/pxt-microbit#3952]
**Describe the bug**
when I use ```control.waitMicros(1000000)``` its supposed to wait for at least one second, but it doesn't, it just never pauses

**To Reproduce**
1. open this link: https://makecode.microbit.org/_2iaKrbJ4w9gY
2. use the simulator
3. it never pauses...

**Expected behavior**
the program pauses for 1 second before running

**micro:bit version (please complete the following information):**
no hardware

**Desktop (please complete the following information):**
Google Chrome: Version 89.0.4389.116 (Official Build)  (64-bit)
Platform: 13729.72.0 (Official Build) stable-channel gnawty
Channel: stable-channel
Firmware Version: Google_Gnawty.5216.239.156
ARC Enabled: false
ARC: 
Enterprise Enrolled: false
Developer Mode: false

**Additional context**
none

**Comment by joshkordek3** [comment]
as well as makecode having trouble connecting to github, most of the time it fails to update my repository, says I'm not logged in or that I dont have internet (and I am both logged in and have internet). Was there an update that could have messed this up?

**Comment by pelikhan** [comment]
Please try sign off and sign in again with GitHub. GitHub changed the format of tokens and it might impact you.

**Comment by joshkordek3** [comment]
how do I sign out on makecode?

**Comment by martinwork** [comment]
It's on the More... cog menu.

**Comment by abchatra** [comment]
It does wait. Try with the bigger number like 10seconds. 1 second is pretty quick to see in the simulator.
