### ISSUE TITLE
Feature: Notes (Middle C)  Add a drop down triangle to select notes

### ISSUE THREAD

**Issue by microbit-pauline** [microsoft/pxt-microbit#3956]
**Describe the solution you'd like**
A drop down menu for different note selectors to help with user experience

![image](https://user-images.githubusercontent.com/29146842/113858247-67ac4400-979b-11eb-9659-731a82728d1c.png)

**Describe alternatives you've considered**
The alterative is the drop down piano which currently exists

**Comment by abchatra** [comment]
We have piano and we don't intend to change that.
