### ISSUE TITLE
Change to Feature: Propose a change from “ring tone” to “start tone” 

### ISSUE THREAD

**Issue by microbit-pauline** [microsoft/pxt-microbit#3957]
**Is your feature request related to a problem? Please describe.**
Users associate the words ring tone with a mobile phone and the MakeCode terminology can be a little confusing. Also, maybe not required to have Hz in block description as the shadow block handles the units

**Describe the solution you'd like**
Propose a change from “ring tone” to “start tone” and remove Hz because the shadow block handles the units

![image](https://user-images.githubusercontent.com/29146842/113858655-e30df580-979b-11eb-98ae-473fa1e23d8d.png)

**Additional context**

**Comment by abchatra** [comment]
We can't change this for legacy reasons. Screenshots & books. Won't fix from our end.
