### ISSUE TITLE
Change to Feature: Remove (ms) from rest block

### ISSUE THREAD

**Issue by microbit-pauline** [microsoft/pxt-microbit#3958]
**Is your feature request related to a problem? Please describe.**
We have rest (ms) and 1 beat, which can be confusing. Proposed to remove (ms)

![image](https://user-images.githubusercontent.com/29146842/113859520-e786de00-979c-11eb-953b-5e6c271026be.png)

**Describe the solution you'd like**
Proposed to remove (ms) from block description

**Comment by abchatra** [comment]
This is because you can drag the number block and use it with milliseconds as well. Although I agree this is confusing.

![image](https://user-images.githubusercontent.com/6107272/113955380-73662d80-97d0-11eb-8d4b-303bcf05cdd1.png)

**Comment by abchatra** [comment]
Won't fix as the block name is in the books and we can add numerical value for the rest too.
