### ISSUE TITLE
Crash in identity code after deleting script from the editor

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3959]
![image](https://user-images.githubusercontent.com/4175913/113860497-f64ca100-975a-11eb-88e2-5a80b443aab9.png)

![image](https://user-images.githubusercontent.com/4175913/113860565-05cbea00-975b-11eb-9d71-e788d68d0839.png)

**Comment by abchatra** [comment]
Hmm we don't have identity in microbit. Is this  a microbit bug?

**Comment by pelikhan** [comment]
It happened in the microbit editor.

________________________________

**Comment by darzu** [comment]
Yes, it's crashing in cloud code before it gets to the "has identity" check. I need to move the guard forward so this doesn't happen

**Comment by darzu** [comment]
The crash happens b/c we're assuming "header" is not null in the editortoolbox.tsx's renderCore fn, it just happens the cloud code is the first that assumes this.
I can't see a good reason why it should be able to be null but that's what we get for not using strictNullChecks.

**Comment by darzu** [comment]
@pelikhan , what's the repro? I tried:
1. new JS project
2. Add new file (custom.ts)
3. Delete custom.ts in explorer
4. no error..?

**Comment by pelikhan** [comment]
Import https://github.com/microsoft/pxt-jacdac
Delete project from editor
blank

**Comment by pelikhan** [comment]
Looks similar to https://github.com/microsoft/pxt-arcade/issues/3413
