### ISSUE TITLE
Feature request: Add a stave window (score) to the play melody music block

### ISSUE THREAD

**Issue by microbit-pauline** [microsoft/pxt-microbit#3960]
**Is your feature request related to a problem? Please describe.**
To enhance user experience for playing melodies, proposed adding a stave to the existing music block

**Describe the solution you'd like**
proposed adding a stave to the existing music block as per image below

![image](https://user-images.githubusercontent.com/29146842/113861223-e0f96600-979e-11eb-8fe9-83c2032e787b.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by abchatra** [comment]
No plans to implement this.
