### ISSUE TITLE
Minor Bug: scrolling

### ISSUE THREAD

**Issue by joshkordek3** [microsoft/pxt-microbit#3961]
**Describe the bug**
when I scroll in the radio raise event block then it scrolls too much.

**Expected behavior**
it doesn't scroll so much

**Screenshots**
![Screenshot 2021-04-07 20 13 58](https://user-images.githubusercontent.com/79750252/113864960-1c675500-97de-11eb-8567-1be249c27a6f.png)
![Screenshot 2021-04-07 20 14 04](https://user-images.githubusercontent.com/79750252/113864958-1bcebe80-97de-11eb-8b9c-901840263878.png)
![Screenshot 2021-04-07 20 14 12](https://user-images.githubusercontent.com/79750252/113864952-1b362800-97de-11eb-8b2b-dafc1002b913.png)
![Screenshot 2021-04-07 20 14 17](https://user-images.githubusercontent.com/79750252/113864949-1a04fb00-97de-11eb-882f-38bf9be273e2.png)

**micro:bit version (please complete the following information):**
NaN

**Desktop (please complete the following information):**
Google Chrome: Version 89.0.4389.116 (Official Build)  (64-bit)
Platform: 13729.72.0 (Official Build) stable-channel gnawty
Channel: stable-channel
Firmware Version: Google_Gnawty.5216.239.156
ARC Enabled: false
ARC: 
Enterprise Enrolled: false
Developer Mode: false

**Comment by abchatra** [comment]
This should be fixed now. If not let us know.
