### ISSUE TITLE
Feature Request: Creation of drop down icons/images for experimental sound features

### ISSUE THREAD

**Issue by microbit-pauline** [microsoft/pxt-microbit#3962]
**Is your feature request related to a problem? Please describe.**
We would like to expand our sound features by giving the user the ability to create sounds. This is experimental and we would like to refine the sound creation work with additional wave and curve type features.

**Describe the solution you'd like**
As per https://github.com/microsoft/pxt-microbit/pull/803, we propose having a drop down menu for a possible new sound creation block. 

We propose adding a **Wave Type** and **Curve Type** feature to sound

**Wave Type**
We have created a mock prototype block for Wave Type (which we can provide to you) as a drop down in words. It looks like:

![image](https://user-images.githubusercontent.com/29146842/113869919-2f136700-97a9-11eb-8169-0f0b8a7fa388.png)

We would like to propose changing the words to icons or images such as:

![image](https://user-images.githubusercontent.com/29146842/113870088-5f5b0580-97a9-11eb-8d70-309b935b2832.png)

**Curve Type**
We have created a mock prototype block for Curve Type (which we can provide to you) as a drop down in words. It looks like:

![image](https://user-images.githubusercontent.com/29146842/113881643-8539d780-97b4-11eb-9c7f-fb007c899421.png)

We would like to propose changing the words to icons or images such as:

Standard Curve
![image](https://user-images.githubusercontent.com/29146842/113881759-a26ea600-97b4-11eb-9d49-3113fd9f7538.png)

Linear Curve
![image](https://user-images.githubusercontent.com/29146842/113881727-98e53e00-97b4-11eb-98cb-0a5a5e02b615.png)

Exponential Rising Curve
![image](https://user-images.githubusercontent.com/29146842/113881821-b0bcc200-97b4-11eb-827c-951fd1203f15.png)

**Describe alternatives you've considered**
A drop down with words has been created and a request made by the Education team to replace words with icons

**Additional context**
This is part of the project on creating new sounds

**Comment by pelikhan** [comment]
@abchatra @soniakandah  could we get icons for those and use a similar widget as for the accelerometer events?

**Comment by microbit-pauline** [comment]
This ties in with the discussions on https://github.com/microsoft/pxt-microbit/issues/4049

**Comment by riknoll** [comment]
In beta now
