### ISSUE TITLE
Bug: not able to write any code

### ISSUE THREAD

**Issue by joshkordek3** [microsoft/pxt-microbit#3967]
**Describe the bug**
I can't do anything in Blocks, Javascript, or Python, pxt.json, nothing, I can't even see what is written there.

**To Reproduce**
I have no idea how it happened probably like this:
1. go to https://makecode.microbit.org
2. create a new project
3. switch to javascript
4. click explorer
5. click pxt.json
6. click on settings
7. click on extensions
8. download an extension

**Expected behavior**
just switches to main menu and I can code

**Screenshots**
![Screenshot 2021-04-09 11 28 52](https://user-images.githubusercontent.com/79750252/114124581-6019a600-9927-11eb-94aa-fbf4c98bc7a5.png)
![Screenshot 2021-04-09 11 28 57](https://user-images.githubusercontent.com/79750252/114124590-63149680-9927-11eb-9bc9-7a037b7e8709.png)
![Screenshot 2021-04-09 11 29 04](https://user-images.githubusercontent.com/79750252/114124595-67d94a80-9927-11eb-8662-e647516366a1.png)

**micro:bit version (please complete the following information):**
NaN

**Desktop (please complete the following information):**
Google Chrome: Version 89.0.4389.116 (Official Build)  (64-bit)
Platform: 13729.72.0 (Official Build) stable-channel gnawty
Channel: stable-channel
Firmware Version: Google_Gnawty.5216.239.156
ARC Enabled: false
ARC: 
Enterprise Enrolled: false
Developer Mode: false

**Comment by joshkordek3** [comment]
yes, I have tried to reload the page

**Comment by abchatra** [comment]
Thanks for the repro steps. I can reproduce in /beta as well
