### ISSUE TITLE
Extension Part Images Don't Load

### ISSUE THREAD

**Issue by bsiever** [microsoft/pxt-microbit#3968]
**Describe the bug**

I have a part image that displays correctly when I'm developing and the Extension is loaded from the "Local" version.  
It *does NOT* show the image when the official (released) extension is used. It shows an icon that looks like a broken link. (screenshots below)

The image declaration in pxtparts.json is based on other examples. It looks like: `"image": "parts/ds18b20probe2Wire.svg",`

I suspect the file location is processed differently for Local extensions.  Is this related to `computePartDefinitions`' use of `readFile` here: https://github.com/microsoft/pxt/blob/d0ec5d92f120492142330e264cff57ba5d5cb364/pxtlib/package.ts#L1265 ? 

Do I need to change the value associated with `"image"` to reference the file in a different way (`"./parts/..."` or  is the working directory the project root and it needs `"microbit-dstemp-2wire/parts/...."`)?

Here's the URL for the Extension: https://github.com/bsiever/microbit-dstemp-2wire
Here's an example project showing the error in the displayed image: https://makecode.microbit.org/_8k737CEd11W6

**To Reproduce**
1. Create a new project.
2. Add a new extension
3. Search for "dstemp-2wire" and add it.
4. Switch to JavaScript and paste in: 
    ``` 
      basic.forever(function () {
          basic.showNumber(dstemp2wire.celsius(DigitalPin.P0))
      })
    ```
5. Observe the broken link image in the simulator

**Expected behavior**

It should show the included image in the simulator (This image https://github.com/bsiever/microbit-dstemp-2wire/blob/master/parts/ds18b20probe2Wire.svg ; Expected look in screenshot below)

__**More importantly, the Local and deployed versions should work using the same `"image"` file path**.__

**Screenshots**

Here's the broken version:
<img width="175" alt="PublishedExtension" src="https://user-images.githubusercontent.com/1421446/114181935-bb3ba080-9907-11eb-9df2-80df7b866578.png">

And the version when I'm testing with a "Local" extension:
<img width="168" alt="LocalSimulated" src="https://user-images.githubusercontent.com/1421446/114181976-c098eb00-9907-11eb-8052-74d12490f281.png">

**Comment by pelikhan** [comment]
It looks like we are double encoding the image when loading it from a referenced project. It does not properly when loading the extension directly. Something is bogus.

**Comment by pelikhan** [comment]
Some nits on the blocks:

* It would be good to reformat your blocks to fit the MakeCode style.
![image](https://user-images.githubusercontent.com/4175913/114298259-c3394300-9ab5-11eb-8cbf-32f03b7e3c74.png)

``Temp. Celscius on ...`` --> ``temperature (°C) on ...``

* the event on sensor error should be moved lower as it is an advanced block use ``weight=0`` to move it down

**Comment by pelikhan** [comment]
Fix in https://makecode.microbit.org/beta (v3.1.74 and up)
