### ISSUE TITLE
Chrome extension for Makecode

### ISSUE THREAD

**Issue by joshkordek3** [microsoft/pxt-microbit#3974]
I would like there to be a makecode offline editor extension since some people use chromebooks, and usually there isn't any extensions, only apps that you can download for Windows or Mac.
(I mean like an extension you can get from https://chrome.google.com/webstore/category/extensions, if its not too much to ask)

**Comment by abchatra** [comment]
Our website will work offline if you download once. I am not sure what is the point of extension? You need to download it once as well right?

**Comment by abchatra** [comment]
We don't intend to work on this.
