### ISSUE TITLE
Filter "_" and other hidden members from TS intellisense

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#3978]
<img width="656" alt="image" src="https://user-images.githubusercontent.com/6453828/114600315-0b3c9f00-9c49-11eb-966e-989065a0f4ed.png">

With the switch to Monaco's standard TS support, we need to filter hidden members again.

**Comment by darzu** [comment]
Hi @alexdima, 

At MakeCode, we're using Monaco and monaco-typescript to provide typescript language service features for our users. Our audience is beginner coders so we want to filter out certain APIs from showing up in auto-complete, specifically ones that start with an "_". We're unsure what the best way to accomplish this is.

Looking at "https://github.com/microsoft/monaco-typescript/pull/65" (and "https://github.com/microsoft/monaco-editor/issues/17", "https://github.com/microsoft/monaco-editor/issues/1661"), it seems there are new hooks for providing an alternative TypeScriptWorker implementation. However, we're really hoping to just augment the existing worker specifically overloading "getCompletionsAtPosition" (https://github.com/microsoft/monaco-typescript/blob/main/src/tsWorker.ts#L225), but this class isn't exported in the public typings for monaco-typescript (as far as I can tell.)

<img width="876" alt="image" src="https://user-images.githubusercontent.com/6453828/116153018-88c9cb80-a69b-11eb-8254-951bb498b8ae.png">

So it seems like our best option is to fork monaco-typescript and modify the TypeScriptWorker class as needed.
Does this match your understanding? Or are we missing something?

CC @abchatra , @riknoll

**Comment by abchatra** [comment]
@alexdima, any thoughts for the above request? If it is easier, we can schedule a quick call as well. @riknoll fyi

**Comment by riknoll** [comment]
Looking through the monaco-typescript repo, seems like we can use the customWorkerPath setting to extend the TypeScriptWorker. I was looking at this example:

https://github.com/microsoft/monaco-typescript/blob/main/test/custom-worker.js

@alexdima is that the correct approach?

**Comment by alexdima** [comment]
> Looking through the monaco-typescript repo, seems like we can use the customWorkerPath setting to extend the TypeScriptWorker

:+1: Yes, that looks good.

**Comment by abchatra** [comment]
Thanks @alexdima
