### ISSUE TITLE
Pause icon on sim not centered

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3980]
**Describe the bug**
Pause icon on sim not centered

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Create a new project

**Expect behavior**
Pause icon on sim centered
![image](https://user-images.githubusercontent.com/59192069/114672869-2fc37480-9d38-11eb-8fd3-44a78569267b.png)

**Actual behavior**
Pause icon on sim not centered
![image](https://user-images.githubusercontent.com/59192069/114672751-11f60f80-9d38-11eb-9527-6b60a15bcebf.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.75
3.Microsoft MakeCode version: 6.13.18

**Comment by abchatra** [comment]
P3 won't fix.
