### ISSUE TITLE
Issue compiling extension in offline MakeCode for WIndows

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3984]
micro:bit support:  44697

**Describe the bug**

When using the cutebot package  https://makecode.microbit.org/pkg/elecfreaks/pxt-cutebot in offline MakeCode the compilation fails with "Compilation failed, please check your code for errors"

MakeCode version is 6.0.38

<img width="725" alt="image" src="https://user-images.githubusercontent.com/31242877/115024451-05002a00-9eb8-11eb-904e-8d82ce12490c.png">

This does not reproduce in MakeCode version 6.0.39 which is deployed to the online editors.

To reproduce. Add extension to offline app and use in a program, then try to download the program.

**Comment by mark2018888** [comment]
Hi @microbit-mark ,

Looks the Windows version 6.0.39 is still not available by downloading from https://makecode.microbit.org/offline-app, and the current windows 6.0.38 is still not available to compile with Cutebot extensions. 

Is there something you can do for proceeding with the offline windows solution? 

Thanks, 
Fu Sheng

**Comment by microbit-mark** [comment]
@abchatra is it possible to progress this so that the offline app works with the extension?

**Comment by abchatra** [comment]
We plan to release new offline apps by June 15th. Is that too late?

**Comment by mark2018888** [comment]
@abchatra No problem, it's approaching :-) , thanks!

**Comment by mark2018888** [comment]
@abchatra Hi, I just checked and it looks the updated offline Window app hasn't been released yet?

**Comment by abchatra** [comment]
This is released now.
