### ISSUE TITLE
Expandable arguments don´t work

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-microbit#3986]
Expandable arguments don´t work. They have to be fully expanded or they cause an error because of missing arguments.
Even in playground. Just go to "input format" and take the block "set the motor to run" move it into "on start" and deactivate it.
Switching to Javascript shows the missing arguments.
![grafik](https://user-images.githubusercontent.com/37311672/115160125-db512980-a096-11eb-9eaa-1bb57cabcf87.png)

![grafik](https://user-images.githubusercontent.com/37311672/115160217-5ca8bc00-a097-11eb-9ea3-e37e166218dc.png)

**Comment by Amerlander** [comment]
There is no value defined, which should be used, when there is no value given.

This can be done by just adding `= value` after the parameters.
```
    export function setMotorSpeed(
        direction: MotorShaftDirection = MotorShaftDirection.Clockwise,
        speed: number = 50,
        duration: number = 500) {
    }
```

Note, this is different from defining a default value with ` //% speed.defl = 50`. That would just define what number shows up when the block gets expanded:
```
    //% direction.defl=MotorShaftDirection.Clockwise
    //% speed.defl=40
    //% duration.defl=550
    export function setMotorSpeed(
        direction: MotorShaftDirection = MotorShaftDirection.Clockwise,
        speed: number = 50,
        duration: number = 600) {
    }
```

If there are expandable blocks without a definition of the standard value they have to be fixed.

**Comment by MKleinSB** [comment]
Thanks, that works but I don´t know if that´s the expected way to use expanded blocks.

**Comment by Amerlander** [comment]
I also dont know, but I guess. 
Parameters which are optional to be defined by the user, but always required to exist have to be declared this way.

**Comment by abchatra** [comment]
Yes this how it needs to be defined. Thanks @Amerlander
