### ISSUE TITLE
Need to add a "play video lesson" option for tutorial "Head Guess"

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3995]
**Describe the bug**
Need to add a "**play video lesson**" option for tutorial "**Head Guess**"

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Games----->**Head Guess*

**Expect behavior**
Need to add a "**play video lesson**" option for tutorial "**Head Guess**" as other tutorials
![image](https://user-images.githubusercontent.com/59192069/115650243-711cdb00-a35b-11eb-9851-818bc7f9fa51.png)

**Actual behavior**
No "**play video lesson**" option for tutorial "**Head Guess**"
![image](https://user-images.githubusercontent.com/59192069/115650220-6104fb80-a35b-11eb-8adc-b9936e3e67b4.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.75
3.Microsoft MakeCode version: 6.13.18

**Comment by ganicke** [comment]
Not all activities have an associated video. I've added the videos for those that do - #4051.
