### ISSUE TITLE
Couldn't find any extensions on MakeCode

### ISSUE THREAD

**Issue by kiate** [microsoft/pxt-microbit#3996]
**Describe the bug**
Unable to find all extensions using the search function. Both keywords and GitHub URLs don't work.

**To Reproduce**
Just try to add any extension on MakeCode. It will return "We couldn't find any extensions matching '[extension name]' "

**MakeCode version:**
https://makecode.microbit.org/
https://makecode.microbit.org/beta
https://makecode.microbit.org/v1

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome, Chrome Incognito, Firefox, Edge

**Comment by abchatra** [comment]
I can reproduce this bug.

**Comment by abchatra** [comment]
Update: We are actively investigating this. Looks like rate limiting from the github at this point of time.

**Comment by abchatra** [comment]
This should be fixed now. Apologies!

**Comment by microbit-mark** [comment]
Thanks for the quick fix @abchatra. We had a lot of teachers report this issue.

**Comment by kiate** [comment]
Thanks @abchatra !
