### ISSUE TITLE
It only returns to step 2 if clicking unfinished tutorial

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3998]
**Describe the bug**
It only returns to **step 2** if clicking unfinished tutorial

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Satrt any tutorials and unfinish it
3.Return to homepage
4.Click this unfinished tutorial

**Expect behavior**
It should return to **unfinished step** if clicking unfinished tutorial

**Actual behavior**
It only returns to **step 2** if clicking unfinished tutorial
![1](https://user-images.githubusercontent.com/59192069/115812534-20bd8000-a424-11eb-81f3-786501349eb7.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.75
3.Microsoft MakeCode version: 6.13.18

**Comment by abchatra** [comment]
Clicking on the microbit logo takes to home screen but doesn't preserve the tutorial step. Though clicking on exit tutorial keeps the steps.

**Comment by Sheila111** [comment]
But it returns to the correct step if clicking on the microbit logo now. So I think it was an issue before?
![1](https://user-images.githubusercontent.com/59192069/117629131-6d3ae680-b1ac-11eb-99c9-4dee668ab38b.gif)

**Comment by abchatra** [comment]
I still reproduce the issue.
