### ISSUE TITLE
Clicking + on file Explorer does not lead to "Custom.ts"

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#4000]
Looks like we've enabled adding any files to microbit projects by default. This is a change in behavior. By design?

- go to javascript
- expand explorer
- click +

expected: custom.ts
actual: add any file

**Comment by abchatra** [comment]
@riknoll @shakao ? 
I think it is by design. But we should by default name custom.ts & populate it?

**Comment by MKleinSB** [comment]
I think the reason was this:  https://github.com/microsoft/pxt-microbit/issues/3345

**Comment by shakao** [comment]
yep by design--i can add something to autofill the file name if there is no existing `custom.ts` though!

**Comment by pelikhan** [comment]
Can you auto-fill the textbox with "custom.ts" and fill the file with the template?
