### ISSUE TITLE
Github code crash when signing in to GH to create new repo

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#4004]
Repro:
- Ensure you're not logged into GH in MakeCode
- Open a new project
- Click the GH button
- Follow the sign in prompt and fill in repo details
- Notice that the GH button doesn't update and in the console has these errors:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6453828/115909795-dc7cb080-a420-11eb-8750-6969b1588e13.png">

**Comment by pelikhan** [comment]
I've created 2 repoes and i could not recreate this issue. It looks like a potential race condition. It would be good to have a network trace.

**Comment by pelikhan** [comment]
The commit being "undefined" is definitely suspicious.

**Comment by pelikhan** [comment]
@darzu is your default to create a "main" branch? It's trying to pull the master branch.

**Comment by abchatra** [comment]
This should be fixed now.
