### ISSUE TITLE
Immersive reader voice settings don't persist between tutorial steps

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/pxt-microbit#4005]
Windows store app. Beta mode. Dice tutorial (blocks).

Repro:
1. In tutorial step 1, open immersive reader.
2. Change reader voice to Male.
3. Play to verify male voice is active.
4. Close reader and return to tutorial.
5. Advance to tutorial step 2.
6. Open immersive reader.
7. Press play. Notice voice is female.

Expected: Voice settings would persist, similar to language and high-contrast settings.

**Comment by eanders-MS** [comment]
Would be good to persist all immersive reader settings for the user, and sync them to the cloud for authenticated users.
![image](https://user-images.githubusercontent.com/12176807/115912228-e358f280-a423-11eb-9ed3-5be43a546aeb.png)

**Comment by abchatra** [comment]
Save the settings in the local storage or indexdb? Probably immersive reader should have guidelines on how to start with the saved settings

**Comment by livcheerful** [comment]
oh yeah I can do that!
