### ISSUE TITLE
Chrome Accessibility Issue: Link Name

### ISSUE THREAD

**Issue by Jxwoon** [microsoft/pxt-microbit#4006]
**Describe the bug**
Link Name does not follow the accessibility compliance 

Snippet of code: 
```
<a class="ui icon link button attached" href="https://www.youtube.com/watch?v=dcSIy1dD5Rg&amp;list=PLMMBk9hE-SepocOwueEtTDyOPI_TBE9yC" target="_blank" rel="noopener noreferrer" role="presentation" tabindex="-1"><i class="icon youtube " aria-hidden="true" role="presentation"></i></a>
```
**To Reproduce**
Use Accessibility Insights for Web and run checks

**Screenshots**
![Screenshot (13)](https://user-images.githubusercontent.com/13580493/115910564-d76c3100-a421-11eb-9258-6de5296b458f.png)

**micro:bit version (please complete the following information):**

Beta

**Desktop (please complete the following information):**
 - Windows
 - Chrome

**Comment by jwunderl** [comment]
Could you put a screenshot of the element that this is failing on? (the one that pops up when you click highlight visible)

**Comment by Jxwoon** [comment]
> Hm, could you put a screenshot of the element that this is failing on if you have time? (the one that pops up when you click highlight visible)

Seems like this is no longer an issue when I re-ran this check... Closing this bug for now.
