### ISSUE TITLE
Smiley Button Python Tutorial instructions don't match code

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4012]
In step 4 of the Smiley Button Python tutorial, the code instructions don't match the default code snippet.
We increment the function name each time a new code snippet is pulled out:
on_button_pressed_a()
on_button_pressed_a2()
on_button_pressed_a3()

But the instructions specify 
on_button_pressed_b()

![PythonTutorial](https://user-images.githubusercontent.com/22108954/115912340-0edbdd00-a424-11eb-8ff1-e483fc7da9d1.png)

**Comment by Jaqster** [comment]
We either need a smarter TS --> Python transpiler (maybe with some custom rules for Toolbox snippets) or we need to have separate TS and Python tutorials....  @pelikhan  thoughts?

**Comment by pelikhan** [comment]
Probably easier to duplicate at this stage.
