### ISSUE TITLE
Notes briefly flash black when closing the melody editor

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#4013]
**Describe the bug**
![bug-melody-close](https://user-images.githubusercontent.com/34112083/115912989-e1436380-a424-11eb-905b-fc0ba8681282.gif)

Notes briefly all go black when closing the melody editor (new Edge)

**To Reproduce**
1. Drag out a melody block, click some notes
2. Click "Finish"
3. See all notes flash black

**Comment by abchatra** [comment]
P3 won't fix.
