### ISSUE TITLE
Blocks icon shows white when clicking editor switch in console page

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4018]
**Describe the bug**
Blocks icon shows **white** when clicking editor switch in **console page**

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/_09Hh8a8x9Yfc
2.Click **Show console Simulator** 
3.Click editor switch and observe **Blocks icon**

**Actual behavior**
Blocks icon shows **white** when clicking editor switch in **console page**
![2](https://user-images.githubusercontent.com/59192069/115988741-b5270e80-a5ed-11eb-98fc-b058c12857ac.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.79
3.Microsoft MakeCode version: 6.13.25

**Comment by abchatra** [comment]
P3 won't fix
