### ISSUE TITLE
Download button disappears in console page

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4019]
**Describe the bug**
**Download button** disappears in console page

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/_09Hh8a8x9Yfc
2.Click **Show console Simulator**
3.Observe **Download button**

**Actual behavior**
**Download button** disappears in console page
![3](https://user-images.githubusercontent.com/59192069/116020937-d2092380-a679-11eb-8a26-5b16cbb3c307.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.79
3.Microsoft MakeCode version: 6.13.25

**Comment by pelikhan** [comment]
This is by design, we specify that in the serial view.

**Comment by abchatra** [comment]
This is by design.
