### ISSUE TITLE
No image for PlayList card under "Coding for Teachers" and "Deep Dive"

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4020]
**Describe the bug**
No image for **PlayList** card under "**Coding for Teachers**" and "**Deep Dive**"

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.**Coding for Teachers**---->**PlayList**
3.**Deep Dive**---->**PlayList**

**Expect behavior**
Add an image for **PlayList** card
![image](https://user-images.githubusercontent.com/59192069/116040605-ced45e80-a69e-11eb-92f5-957e77315520.png)

**Actual behavior**
No image for **PlayList** card under "**Coding for Teachers**" and "**Deep Dive**"
![image](https://user-images.githubusercontent.com/59192069/116040468-a77d9180-a69e-11eb-9cbe-46cf47fb6b67.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.79
3.Microsoft MakeCode version: 6.13.25

**Comment by ganicke** [comment]
Playlist images added in #4042
