### ISSUE TITLE
No way to delete the added Extension

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4024]
**Describe the bug**
No way to delete the added **Extension**

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#editor
2.Add extension (**Advanced---->Extensions**)

**Expect behavior**
We can delete the added **Extension**

**Actual behavior**
No way to delete the added **Extension**
![image](https://user-images.githubusercontent.com/59192069/116380599-b0a96280-a846-11eb-9195-447f6b9feb98.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.79
3.Microsoft MakeCode version: 6.13.25

**Comment by jackkalvan** [comment]
I would also like to know how to delete an added extension. Sometimes the extensions seem to cause problems with a program compiling. I've had problems with Maqueen+ extension. and others.

**Comment by microbit-mark** [comment]
@jackkalvan You can remove an extension in the Javascript view, see out article https://support.microbit.org/support/solutions/articles/19000089673-update-remove-an-extension-from-the-makecode-editor

We are currently looking at updating this experience and would really appreciate your feedback on it. We are running a guided user study online at https://s2.userzoom.com/m/MSBDNjM3OFM1NyAg

**Comment by abchatra** [comment]
This is implemented in /beta
