### ISSUE TITLE
Multi Editors: Dragging the window divider makes page white

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4026]
**Describe the bug**
**Multi Editors:** Dragging the window divider makes page white

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Radio Games----->**Multi Editors**----->Show Instructions

**Actual behavior**
**Multi Editors:** Dragging the window divider makes page white
![1](https://user-images.githubusercontent.com/59192069/116530833-0d714f80-a911-11eb-9c4b-66c21a229182.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.79
3.Microsoft MakeCode version: 6.13.25

**Comment by pelikhan** [comment]
This is by design

**Comment by Sheila111** [comment]
But it's not a great experience for the user.

**Comment by pelikhan** [comment]
Resizing 2 makecode editors is laggy so we disable that while dragging.

**Comment by pelikhan** [comment]
@abchatra  design decision

**Comment by abchatra** [comment]
P3 won't fix.
