### ISSUE TITLE
Stop notification of bluetooth service after a few minutes

### ISSUE THREAD

**Issue by yokobond** [microsoft/pxt-microbit#4027]
**Describe the bug**
When I compile a project that uses a service that notifies data via Bluetooth with the latest MakeCode (v3.0.68), the micro:bit v2 stops notifying data after a few minutes (about 1-30 minutes).
(I have confirmed that it continues for more than 30 minutes in micro:bit v1.5)

**To Reproduce**
The following program can measure the elapsed time of the acceleration service.

MakeCode: https://makecode.microbit.org/_6JXVREHXELXD
Client: https://yokobond.github.io/microbit-playground/ble-notification-time/
(The client uses Web Bluetooth, so please open it with google Chrome 70+.)

Download the MakeCode project to micro:bit v2, then open the Client link in Chrome browser to measure.
Select your micro:bit from the list that appears when you click the [connect] button in Client. After connecting, measure the time the notifications are received and display them in the 'notification duration'.

As far as I can measure, the duration of the notifications varies from 9 seconds to 20 minutes, it seems to stop within 30 minutes at least.

**Expected behavior**
Use Bluetooth notification to send data without stopping.

**micro:bit version:**
micro:bit v2.0

**Desktop:**
 - OS: mac, windows, chromebook
 - Browser: chrome
 - makecode.microbit.org: 3.0.68
 - Microsoft MakeCode: 6.0.39
 - microbit runtime: v2.2.0-rc6

**Comment by abchatra** [comment]
@martinwork have you seen this? Probably leak in the codal or makecode?

**Comment by martinwork** [comment]
Seems likely related to https://github.com/lancaster-university/codal-microbit-v2/issues/98, so CODAL.

**Comment by Ziriax** [comment]
I'm not sure it is a memory leak on the device, because on my Android 10 phone with Chrome 90 it stops almost immediately.

**Comment by abchatra** [comment]
This is codal issue.
