### ISSUE TITLE
pair device in download dialog does not always show pair

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#4028]
Clicking on "pair device" does not always pop up the pair dialogUI.

**Comment by abchatra** [comment]
Hmm if you already have given permission in the past it will just pair right?

**Comment by pelikhan** [comment]
*   disconnect microbit
  *   click download
  *   click pair
  *   dismiss pair dialog
  *   click download/pair again
  *   no dialog


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by pelikhan** [comment]
We should really fix this one. It is now the main action button of the button dialog and it does not do anything.

**Comment by riknoll** [comment]
Fixed by https://github.com/microsoft/pxt/pull/8181
