### ISSUE TITLE
 I want to put the extension in a local service instead of downloading it

### ISSUE THREAD

**Issue by yf-chen** [microsoft/pxt-microbit#4030]
What do I need to do if I want to put the extension in a local service instead of downloading it
![image](https://user-images.githubusercontent.com/26783726/117097827-56a52180-ad9f-11eb-9e42-53a6383762f1.png)
![image](https://user-images.githubusercontent.com/26783726/117097884-776d7700-ad9f-11eb-8acf-8d4ad7a357e3.png)
![image](https://user-images.githubusercontent.com/26783726/117097905-82c0a280-ad9f-11eb-9a72-070afe731ca4.png)
I've tried all of the above but it doesn't work

**Comment by yf-chen** [comment]
@pelikhan Would you please give me a hand

**Comment by pelikhan** [comment]
This looks correct. Try ``pxt clean``, ``pxt serve`` to make sure those changes are picked up.

**Comment by yf-chen** [comment]
> This looks correct. Try `pxt clean`, `pxt serve` to make sure those changes are picked up.

Okay, I'll give it a try. Thank you for all the help from across the ocean. Thank you very much

**Comment by yf-chen** [comment]
@pelikhan I'm sorry to bother you again. This still doesn't solve my problem, which has been bothering me all day. Do you have any other solutions

**Comment by pelikhan** [comment]
Hard to tell without seeing the repo.

**Comment by yf-chen** [comment]
> Hard to tell without seeing the repo.
which repo? Is that all right with you?Could you please provide me with an example?I am very anxious. I beg your help

**Comment by yf-chen** [comment]
![image](https://user-images.githubusercontent.com/26783726/117104543-e7372e00-adae-11eb-975a-48a33bb654bc.png)
![image](https://user-images.githubusercontent.com/26783726/117104574-f74f0d80-adae-11eb-987b-3a444c2d1c07.png)
I can remove the extension this way, but I can't add the extension.

**Comment by yf-chen** [comment]
I would like to ask the most question.My goal is to deploy the Makecode on my own server. Now I have two problems: 1. After selecting the language Chinese, the page cannot display Chinese.2. Put the extension in your entire project instead of downloading it via GitHub.Can these two goals be achieved?If I can't I want to give up.I really need your help.I hope you can understand my impatience.If you have time, could you please help me? @pelikhan

**Comment by yf-chen** [comment]
I've been working on it all day and I think I'm finally going to make it.However, I encountered the latest problem. As shown in the figure, I clicked the extension to enter the programming page, but the extension was not displayed. @pelikhan 
![image](https://user-images.githubusercontent.com/26783726/117131889-a520e300-add4-11eb-9c5b-305c56d53979.png)
![image](https://user-images.githubusercontent.com/26783726/117131950-bb2ea380-add4-11eb-9e0d-8a059a119aec.png)

**Comment by yf-chen** [comment]
@abchatra Could you help me answer the question? I've been puzzled for a long time！

**Comment by yf-chen** [comment]
It was nice to spend another day working out the problem of putting the extension on a local service. Now both Tinkercademy-Tinker-Kit and Neopixel can run on a local service, but I ran into a new problem when I put the extension TM1637 on my own server.Always report an undefined exception to pxt.json when starting the service.The difference is submitting to GitHub for approval.

**Comment by pelikhan** [comment]
Again, we cannot diagnose this unless we see the sources. Of the top of my head, make sure that tm1637 is the name in pxt.json as well.

**Comment by yf-chen** [comment]
I want to put the extension on the local service instead of downloading it. I have tried several extensions, tinkercademy-tinker-kit and Neopixel are all OK, but TM1637 is not. I have shared the code on github, please help me have a look.I'm really at my wit's end.
[https://github.com/yf-chen/makecode-local/tree/master](url) 
Looking forward to your reply ,thank you very much @pelikhan @abchatra

**Comment by pelikhan** [comment]
Make sure all names match with proper casing. TM1637 != tm1637

Somehow can't access those submodules so it's unclear what TM1637 is made of.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by yf-chen** [comment]
I am very happy to receive your reply. Just now I finally found the problem. Thank you very much!It's so exciting.Hats off to the great Microsoft. Hats off to you @pelikhan
