### ISSUE TITLE
 MicroBit V2 error 841

### ISSUE THREAD

**Issue by dsssssssss9** [microsoft/pxt-microbit#4031]
When running the following code which plots /  unplots random rectangles on a 128*63 OLED connected via I2C i get error 841 appearing on the MicroBit display seemingly at random 

https://makecode.microbit.org/_E7gb4wFsr6Uy

BBC MicroBit V2

Linux Ubuntu 20.04 - 
Chromium Version 90.0.4430.93 (Official Build) but all browsers  tried seem to exhibit the same error

**Comment by abchatra** [comment]
This is an issue with the extension. Please file the issue in the extension repo: makecode-extensions/oled12864_i2c
