### ISSUE TITLE
Github access token causes error 'invalid token format'

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4034]
**Describe the bug**

When trying to use a token to sing in to Github, an error is thrown saying it is an invalid format.

![Screen Recording 2021-05-06 at 01 05 24 pm](https://user-images.githubusercontent.com/31242877/117295778-2a0b0b80-ae6c-11eb-9271-b9a1e7e6aa86.gif)

**Comment by abchatra** [comment]
Fixed in the beta. Github changed their token format. Please validate on beta

**Comment by jaydeetay** [comment]
Thanks for the fix. I'm the OP - verified that the token is accepted now.  BTW - although it now will happily create a repository for me in github, when I edit the code it doesn't offer to push it to the new repo.  All that gets created is the .gitignore file (example: https://github.com/jaydeetay/always-upright-hearts)

**Comment by abchatra** [comment]
@pelikhan

**Comment by pelikhan** [comment]
Is this a consistent issue or does it go away? Are you exclusively using a token or are you signing in?

**Comment by jaydeetay** [comment]
Seems to be consistent.  When opening an existing project, hitting the
github icon and then entering the token and then a (new) repo name the repo
gets created with a .gitignore but nothing else.

I can make changes to the python code but there's no option to push
anything - the github icon just opens a dialog asking for the repo name
again (complaining if I use the same one of course).  Here's another
almost-empty repo: https://github.com/jaydeetay/note

This is using makecode beta, btw.

I have a little more luck with importing existing github projects (though
at the moment I get to the "We need to add a few files to your GitHub
repository https://github.com/jaydeetay/makecode-tmp2 to make it work with
MakeCode." step and it reports "Network request failed".  The newly created
MakeCode project then can't be opened (I guess as it has no content).  Let
me know if I can try something else.

John
