### ISSUE TITLE
How do I deploy to my own server

### ISSUE THREAD

**Issue by yf-chen** [microsoft/pxt-microbit#4041]
How do I deploy to my own server

**Comment by pelikhan** [comment]
You can read about https://makecode.com/cli/staticpkg

**Comment by yf-chen** [comment]
I've deployed the code on my own server, but now I can't search for extensions and install extensions.How to solve this problem? @pelikhan

**Comment by yf-chen** [comment]
Could you give me a hand ?Some features are not available after I deploy the service. @pelikhan 
![image](https://user-images.githubusercontent.com/26783726/118349067-09843500-b581-11eb-9cc4-fdb2714ef827.png)
![image](https://user-images.githubusercontent.com/26783726/118349075-16088d80-b581-11eb-904f-7976f533f6bf.png)
