### ISSUE TITLE
Servo Calibrator: Link "Brief Guide to Servos" can't be opened

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4045]
**Describe the bug**
**Servo Calibrator**: Link "**Brief Guide to Servos**" can't be opened

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Tools----->Servo Calibrator------>Show Instructions
3.Click link "**Brief Guide to Servos**"

**Actual behavior**
**Servo Calibrator**: Link "**Brief Guide to Servos**" can't be opened
![2](https://user-images.githubusercontent.com/59192069/117773388-d41ed500-b26a-11eb-931e-876aee86f4df.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.79
3.Microsoft MakeCode version: 6.13.25

**Comment by Sheila111** [comment]
@ganicke  It's opened if you choose "**Open link in new tab**"。But It still can't be opened if you click this link directly.
![1](https://user-images.githubusercontent.com/59192069/120258403-8d018e00-c2c4-11eb-921f-a6fe351769c9.gif)

**Comment by ganicke** [comment]
Well, indeed this is a "opener" problem in Chrome. Seems to work OK on Edge. This occurs when clicking on the link when the page is embedded in a sidedoc. I turned off all blocking for the [makecode.microbit.org]() site in my Chrome security settings but to no avail.

The link renders in the page as:

```html
<a target="_blank" rel="nofollow noopener" href="https://www.kitronik.co.uk/pdf/a-brief-guide-to-servos.pdf">Brief Guide to Servos</a>
```

**Comment by abchatra** [comment]
Fixed
