### ISSUE TITLE
Coding and Innovation: Link is unsafe

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4046]
**Describe the bug**
**Coding and Innovation**: Link is unsafe

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Course----->**Coding and Innovation-**----->Show Instructions

**Actual behavior**
**Coding and Innovation**: Link is unsafe
![1](https://user-images.githubusercontent.com/59192069/117780062-d8022580-b271-11eb-8a19-fee24ae1ba60.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.79
3.Microsoft MakeCode version: 6.13.25

**Comment by Sheila111** [comment]
"**micro:bit of Things**" has the same issue.

**Comment by abchatra** [comment]
@ganicke lets remove the link. 
@Jaqster  -fyi

**Comment by Jaqster** [comment]
I can't reproduce this.  Both redirect to https://sites.google.com/ sites.  How are these unsafe?

**Comment by abchatra** [comment]
Probably their certificate expired and they renewed now. 

@Sheila111 are you able to reproduce this issue now?

**Comment by Sheila111** [comment]
It doesn't repro now.
![1](https://user-images.githubusercontent.com/59192069/118063683-27f4ff80-b3cc-11eb-8400-3f3d18ff0f94.gif)

**Comment by Sheila111** [comment]
@abchatra     **Coding and Innovation** and **micro:bit of Things** can't be opened again in new /beta version v3.1.91.
![1](https://user-images.githubusercontent.com/59192069/121458939-e3657f80-c9dc-11eb-8775-6f6aeb0895fd.gif)

**Comment by abchatra** [comment]
@Sheila111 seems to be working for me. Can you try again?

**Comment by Sheila111** [comment]
Sorry @abchatra，I did not specify the browser that reproduced the issue. It sill reproduces on new **edge** browser.

**Comment by ganicke** [comment]
Works for me with:

![image](https://user-images.githubusercontent.com/27789908/121581710-03983d00-c9e3-11eb-94ca-8f96c57b9a35.png)

and

![image](https://user-images.githubusercontent.com/27789908/121581948-4d812300-c9e3-11eb-9061-5f62020a8351.png)
