### ISSUE TITLE
Simulator not loading for some students

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4052]
microbit support: 44111

**Describe the bug**
<img width="562" alt="image" src="https://user-images.githubusercontent.com/31242877/117935364-8bfbc300-b2fb-11eb-916f-506411a63ffe.png">

The simulator is sporadically not loading for some students in the same classroom. This was reported on 2nd March and again on 10th May.

> I have a new group of students, and this error has popped up again.  Today there was just 3 students: 2 in-school and 1 at home.  Of the 2 in-school, one had the iframe error and the other did not.  (The student's at home worked fine.) Both in-school students had the same hardware: Chromebook (Dell 3100). Any insights?

We've also discussed a similar issue raised by @Jaqster on email that affected some iPad devices (3 in class and 2 at home) approx April 15th

![image](https://user-images.githubusercontent.com/31242877/117936319-a2eee500-b2fc-11eb-960d-dfabfe6a6cc6.png)

It seems to resolve itself over time but then reproduces at a later date.

**Comment by abchatra** [comment]
This is likely simulator domain being blocked. Please check with the customer https://makecode.microbit.org/faq
And reopen if there is report even after the domain is unblocked..

**Comment by microbit-mark** [comment]
Their school IT have said "it's not being blocked, and some students can see the virtual microbit.  Just not every student."

**Comment by abchatra** [comment]
It is possible there are multiple network in the school? Does this still happen? We can’t act in this bug at this moment.

**Comment by abchatra** [comment]
Only way this would happen is simulator domain is blocked or bug on our backend. Without more info there is not much we can do. Schedule a call with the customer if it still happens

**Comment by Jaqster** [comment]
Just to confirm for the Educator in Omaha who reported this, working with her IT department seemed to have done the trick:  _"If you recall, we were having trouble at our district level seeing the simulator for the Makecode microbits.  We got that resolved after our IT team whitelisted the sites you sent me.  Now it appears we are having issues with the arcade simulator.  Do you happen to know of links for that simulator that I can forward to our IT team?"_

**Comment by pelikhan** [comment]
We need a page that automatically pings all required domains that a IT/teacher amin can use to easily test things are ok. Discovering this by trial and error is messy.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by microbit-mark** [comment]
> We need a page that automatically pings all required domains that a IT/teacher amin can use to easily test things are ok. Discovering this by trial and error is messy. 

I've created https://github.com/microsoft/pxt-microbit/issues/4115 for this feature. We can leave the ticket here as closed and I'll follow up with the teacher seperately.
