### ISSUE TITLE
Expose code to allow block for continuous servos

### ISSUE THREAD

**Issue by edbye** [microsoft/pxt-microbit#4062]
**Is your feature request related to a problem? Please describe.**

A function exists, "servoSetContinuous()" in JS to allow servo to be set to contineous mode.

**Describe the solution you'd like**

Could a block be created to set a servo for contiueous operation please.

**Describe alternatives you've considered**

**Additional context**

With an increasing number of continuous servos now available and being used because of their high torque as robot buggy drivers, it would be very handy to have a block to set continuous mode on a servo

**Comment by abchatra** [comment]
<img width="487" alt="image" src="https://user-images.githubusercontent.com/6107272/223508084-66092f28-e8af-44da-a8aa-210e10344c4a.png">

Can you use the above API? Sorry if I misunderstood the request.
