### ISSUE TITLE
Javascript example does not run on simulator

### ISSUE THREAD

**Issue by microbit-Bisi** [microsoft/pxt-microbit#4065]
micro:bit support: 45141

**Describe the bug**
In the complex conditions tutorial, https://makecode.microbit.org/courses/blocks-to-javascript/complex-conditionals  the block example runs but the javascript one does not. This is a causing confusion for users. Example below:
![image](https://user-images.githubusercontent.com/46746914/118629980-0332ca80-b7c6-11eb-9772-696fa8114ee7.png)

https://github.com/microsoft/pxt-microbit/blob/e52e808ea1b936a2007f0f2cdf7be43db0eba8b6/docs/courses/blocks-to-javascript/complex-conditionals.md

**Expected behavior**
I would expect the code to run in the simulator. Currently nothing happens on the micro:bit display. 

```
if (input.buttonIsPressed(Button.A) || input.buttonIsPressed(Button.B)) {
    basic.showIcon(IconNames.Square)
}
```

**Comment by abchatra** [comment]
Unless you put this in forever loop it will not work:
```
basic.forever(function () {
    if (input.buttonIsPressed(Button.A)) {
        basic.showIcon(IconNames.Square)
    } else if (input.buttonIsPressed(Button.B)) {
        basic.showIcon(IconNames.Square)
    } else {
        basic.showIcon(IconNames.No)
    }
})
```

Sample is just explaining the conditional.

**Comment by microbit-mark** [comment]
The sample is explaining the condition, but this is still confusing for users as the UI suggests that the code example can be executed.

![Screen Recording 2021-05-20 at 02 14 21 pm](https://user-images.githubusercontent.com/31242877/118984796-c4437700-b975-11eb-9b31-54fbf1d0352b.gif)

We should either remove the option to run the code in the simulator, or complete the JS example so that it does run.

**Comment by abchatra** [comment]
>> We should either remove the option to run the code in the simulator, or complete the JS example so that it does run.
@ganicke can we do one of this?

**Comment by ganicke** [comment]
For these simple JavaScript analogs I can just change the code blocks to ```` ```typescript-ignore ````.
