### ISSUE TITLE
DOCUMENTATION: Bluetooth documentation links to broken external URL

### ISSUE THREAD

**Issue by kjcole** [microsoft/pxt-microbit#4067]
**DESCRIPTION**

The Bluetooth documentation says (on multiple pages) that the Eddystone beacon format has been depreciated and suggests a link to Google Developers that purports to explain. However, the result is a 404 Page Not Found error.

**TO REPRODUCE**

1. Go to https://makecode.microbit.org/reference/bluetooth
2. Click on the link [Google Beacon format (Deprecated)](https://developers.google.com/beacons/eddystone)
3. See error

**EXPECTED**

A clear and concise description for noobs of why Eddystone is depreciated and what alternatives exist.

**Comment by abchatra** [comment]
Remove these deprecated blocks & invalid link.
