### ISSUE TITLE
"Green Screen" doesn't take effect on homepage

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4074]
**Describe the bug**
"Green Screen" doesn't take effect on **homepage**

**Steps to reproduce the behavior**
1.https://makecode.microbit.org/beta#editor
2.Click **Green Screen On**
3.Return to **homepage**
4.Click any tutorial

**Actual behavior**
"**Green Screen**" doesn't take effect on **homepage**. It only take effect on tutorial page and editor page.
![1](https://user-images.githubusercontent.com/59192069/118950307-a7666e00-b98c-11eb-870c-c9b0cbeb2c8f.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.84
3.Microsoft MakeCode version: 6.13.34

**Comment by abchatra** [comment]
Won't fix.
