### ISSUE TITLE
Feature: Replace text with icons in Variable dropdown

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4075]
**Is your feature request related to a problem? Please describe.**

If the `rename variable` and `delete the variable` text was replaced by a symbol it would make the block more succinct and the image icons are descriptive of the purpose

![Image 2021-05-20 at 10 29 11 am](https://user-images.githubusercontent.com/31242877/118957733-a9aed500-b958-11eb-8715-2a0f2e2c7710.png)

You could also use the existing + symbol for adding a new variable.

**Comment by abchatra** [comment]
No plans to implement.
