### ISSUE TITLE
Stopwatch: Is it better to add a "integer ÷ " directly for step 6?

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4078]
**Describe the bug**
**Stopwatch**: Is it better to add a "**integer ÷** " directly for step 6?

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Tools---->**Stopwatch**----->Blocks Start Tutorial
3.Click step 6

**Actual behavior**
Is it better to add a "**integer ÷** " directly for step 6?
![image](https://user-images.githubusercontent.com/59192069/119103683-03dd9200-ba4e-11eb-9eb6-0b7ef7a97ff9.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.84
3.Microsoft MakeCode version: 6.13.34

**Comment by abchatra** [comment]
We don't have the way to do this. Can't fix.
