### ISSUE TITLE
Windows Store App: Compilation failed when using 'No Pairing' mode

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4079]
**Describe the bug**
When using the windows app, switching to 'No Pairing' mode in the project settings, the compilation will fail when you press download

![Image 2021-05-21 at 10 17 51 am](https://user-images.githubusercontent.com/31242877/119114534-28217a80-ba1e-11eb-8d70-df8c6bd1cf8f.jpg)

1.Open Win10 app
2. Switch to 'No  Pairing'
3. Press Download

Does not reproduce on mac offline app
Does not reproduce in browser

**Comment by abchatra** [comment]
We are deprecating winjs windows app and replacing it with pwa. Won't fix from our end.
