### ISSUE TITLE
It's not a good user experience for the font color and background color of "Next"

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4083]
**Describe the bug**
It's not a good user experience for the **font color** and **background color** of "**Next**"

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Click any tutorial

**Actual behavior**
It's not a good user experience for the **font color** and **background color** of "**Next**"
![image](https://user-images.githubusercontent.com/59192069/119321887-b06a7e80-bcaf-11eb-8dd1-df2999c0ff08.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.85
3.Microsoft MakeCode version: 6.13.39

**Comment by Jxwoon** [comment]
The "Next" button should not appear green when any tutorial is clicked due to this [fix](https://github.com/microsoft/pxt/pull/8186).

Also, when code validation is enabled and the user's code is correct, the "Next" button will turn a magenta color with white text. ( #4124 )
