### ISSUE TITLE
After reloading the editor, the download dialog does not show up again.

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#4085]
In a shared computer setting, the download dialog should show up again whenever the page is reloaded.

Expected:

- click download
- select don't show again in download dialog
- click download, does not show dialog again
- refresh page
- click download
- dialog shows up again

Actual:

- dowload dialog does not show up again.

**Comment by abchatra** [comment]
Expiry is per design.  We are banking on the fact that "don't show again" is clicked only by adults in their home PC.

**Comment by pelikhan** [comment]
If you are on a machine which blocks auto-started downloads and you click that checkbox, you are toast for an entire week. There is no way to cancel it and all downloads will fail.

**Comment by abchatra** [comment]
Alternative is in memory expiry. @riknoll

**Comment by pelikhan** [comment]
This design will break schools that block the auto-download, statistically some kids will decide to hide this dialog. IMO, we should never persist user preferences in EDU settings unless the user is signed in.

**Comment by abchatra** [comment]
@riknoll lets just do in memory like high contrast which stays only until browser tab is closed.

**Comment by riknoll** [comment]
will do!
