### ISSUE TITLE
[Windows app] No border on focused cards in homepage detail view

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#4088]
**Describe the bug**
![image](https://user-images.githubusercontent.com/34112083/119386496-7af86d80-bc7c-11eb-9c92-0113b0558dc9.png)

Does not repro on the browser, in /beta

**Expected behavior**
![image](https://user-images.githubusercontent.com/34112083/119386554-8f3c6a80-bc7c-11eb-8b8e-c8b76835b7aa.png)

**Comment by abchatra** [comment]
Won't fix.
