### ISSUE TITLE
[windows app & iOS app] monaco editor seems broken

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#4091]
**Describe the bug**

typescript / python view seems broken in windows app

**To Reproduce**
1. Go to windows app beta
2. open project
3. try to switch to javascript -> see error: stuck on loading screen, probably waiting for monaco bits?
4. go to tutorial from homepage, open as javascript tutorial
5. see error: monaco editor missing

![image](https://user-images.githubusercontent.com/5615930/119388716-826d4600-bc7f-11eb-95e6-6e668eb1fb88.png)

**Expected behavior**

monaco editor should work

**Desktop (please complete the following information):**
 - OS: windows
 - Browser windows app

**Additional context**

**Comment by abchatra** [comment]
This is broken in iOS app too

**Comment by abchatra** [comment]
Once you hit this bug even blocks editor is broken in the iOS app.

**Comment by martinwork** [comment]
What triggers the problem? I don't see it in the iOS app on my iPad with MakeCode beta.

**Comment by abchatra** [comment]
iOS 13.7 going to text mode you see a blank screen. This is monaco issue.

**Comment by martinwork** [comment]
Thanks @abchatra . Seems OK in iOS 14.4.2.

**Comment by livcheerful** [comment]
Okay, I just tested the Windows App w/ beta which has the updated Monaco version, and it still doesn't work :\ I will look into it more and see if it's a monaco bug
