### ISSUE TITLE
Web USB dialog polish - add Next/Previous

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4092]
Since these dialogs are now strung together like a Wizard, I think it would make sense to show how each window ties together.
Either with some sort of Step 1/3, Step 2/3, Step 3/3 indication (or dots like we do with Tutorials), or having Next --> and Previous <-- buttons at the bottom with arrows to show sequence.

Step 1
![image](https://user-images.githubusercontent.com/22108954/119389639-c3198f00-bc80-11eb-96b1-ef1cd5a9bbea.png)

Step 2
![image](https://user-images.githubusercontent.com/22108954/119389691-d3316e80-bc80-11eb-8668-f989baea6546.png)

Step 3
![image](https://user-images.githubusercontent.com/22108954/119389769-e8a69880-bc80-11eb-929a-9c8bd1f2b9dc.png)

**Comment by soniakandah** [comment]
Slightly adjacent to this request, I redid all the images used in the web usb flow. Here they are: 

1 - USB cable connect
![WebUSB_01](https://user-images.githubusercontent.com/22336391/121954000-18424100-cd13-11eb-9f4f-093c3dd7261c.png)

2 - Connect via browser
![WebUSB_02](https://user-images.githubusercontent.com/22336391/121954014-1bd5c800-cd13-11eb-9654-993b2bde5535.png)

3 - Transfer Hex File
![WebUSB_03](https://user-images.githubusercontent.com/22336391/121954012-1b3d3180-cd13-11eb-8f78-5ec0dd7e3473.png)

4 - Incompatible hardware
![WebUSB_04](https://user-images.githubusercontent.com/22336391/121954263-6a836200-cd13-11eb-95a1-bdaf3d58c158.png)

5 - Update device firmware
![WebUSB_05](https://user-images.githubusercontent.com/22336391/121954008-1aa49b00-cd13-11eb-8628-7ccb6b5fc448.png)

6 - Successfully connected
![WebUSB_06](https://user-images.githubusercontent.com/22336391/121954005-1a0c0480-cd13-11eb-9ee2-c2282ded5da7.png)

**Comment by Jaqster** [comment]
Oooh, these are great!! Love the micro:bit emojis! :-)
