### ISSUE TITLE
[windows app] high contrast mode home page icons contrast off

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#4094]
**Describe the bug**

Contrast for project type icon is off in high contrast mode in windows app

**To Reproduce**
1. Go to windows app beta
2. create a few projects
3. Scroll down to switch to high contrast mode

left is icon in windows app, right is beta site
![image](https://user-images.githubusercontent.com/5615930/119389914-20154500-bc81-11eb-9a18-803275e00470.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser app

**Comment by abchatra** [comment]
We decided we won't fix these for windows app
