### ISSUE TITLE
[windows app] delete project broken

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#4095]
**Describe the bug**

cog wheel -> delete project broken in windows app

**To Reproduce**
1. Go to windows app beta
2. go to cog wheel in a project -> delete project
3. see error: errors out on deleting / switches to in memory view

**Expected behavior**

should delete project

**Desktop (please complete the following information):**
 - OS: windows
 - Browser windows app

**Comment by abchatra** [comment]
@jwunderl is this a regression. If not I will not take up for this release.

**Comment by jwunderl** [comment]
Behavior is slightly different but it fails to delete with the current release as well (it doesn't push you out to the homescreen / doesn't delete the project, but it does remove the header for the session). Switching to the in memory database is new though, before it just completely silently failed to delete.
