### ISSUE TITLE
Download icons for file slightly misleading

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#4098]
![Animation](https://user-images.githubusercontent.com/4175913/119446900-f93c2a80-bce3-11eb-8b3a-a9ded3c6539f.gif)

The animation above is kind of misleading (since we don't know if the download was blocked or not) and could maybe used for a different purpose: we could keep the icon with a checkmark until a change is made. So that it actually means that you've download the latest version of the code or not.

**Comment by abchatra** [comment]
@pelikhan I am unable to understand this bug. Can you elaborate?

**Comment by pelikhan** [comment]
More a feature request. You can close.

In general, we do not clearly message that the latest downloaded program does not match the program in the editor (the simulator auto reloads). Not sure how to surface this and if it brings value.

**Comment by abchatra** [comment]
Let me close this now. I will keep this in mind for the future.
