### ISSUE TITLE
localhost - not able to open in Edge

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#41]
Repo. 

1 Go through steps to open localhost

2 Chrome opens by default

3 copy/paste localhost URL to Edge 

``` 

http://localhost:3232/index.html#

```

4 Edge is constantly saying loading... but never finishes loading

![image](https://cloud.githubusercontent.com/assets/11206682/14365322/ed5cf768-fcc1-11e5-8f87-2d52ec0d5aff.png)

**Comment by pelikhan** [comment]
You need to find the URL printed by the command line and use that one instead. It contains a secret that the browser needs to work.
