### ISSUE TITLE
Instructions: Text "@2020 Microsoft" need to be modified

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4101]
**Describe the bug**
Instructions: Text "@2020 Microsoft" need to be modified

St**eps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Music------>Hack Your Headphones------>Show Instructions

**Actual behavior**
Instructions: Text "**@2020 Microsoft**" need to be modified. It should be "**@2021 Microsoft**".
![image](https://user-images.githubusercontent.com/59192069/119457505-58468180-bd6e-11eb-815f-1cad2b2cd74d.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.85
3.Microsoft MakeCode version: 6.13.39

**Comment by abchatra** [comment]
Fixed. This will be updated in the next release.
