### ISSUE TITLE
Localised Blocks - Inconsistent language display

### ISSUE THREAD

**Issue by DaveAtKitronik** [microsoft/pxt-microbit#4102]
We are localising packages, and our translator has come across very strange behaviour:

**To Reproduce**
Switch localisation to Hungarian before creating a new project.
Import the StopBit blocks into the project (https://github.com/KitronikLtd/pxt-kitronik-stopbit)
See the blocks in the pallet are in Hungarian:

![1- create project, in hungarian , import blocks](https://user-images.githubusercontent.com/25896029/119456326-7abaa980-bd32-11eb-95df-63b727ab0124.PNG)

Switch to English localisation in the project
Notice that the blocks in the pallet all switch apart from the Stop:bit ones

![2 - Pallet fails to translate](https://user-images.githubusercontent.com/25896029/119456995-1e0bbe80-bd33-11eb-9eeb-67a6f6aea883.png)

Drag the blocks in an they remain in Hungarian:

![3 Block still in hungarian when dragger into editor](https://user-images.githubusercontent.com/25896029/119457078-311e8e80-bd33-11eb-9270-1ec2fa5a28d4.PNG)

There are a number of variations on a similar theme, where blocks do not translate, or remain translated when they should return to a previous langauge.

![english pallet](https://user-images.githubusercontent.com/25896029/119458244-71324100-bd34-11eb-8489-c329f33a426b.png)

Peter (the translator) has noticed:

It's so strange. If I open a new project then still I see the block in the group in English and on the Canvas in Hungarian. Then I opened a little project that was made with Hungarian blocks on Friday: the blocks both in the group of blocks and on the Canvas are in English. Again, it was made with Hungarian blocks.

There is a small difference in my browsers:
•	In Opera, everything is fine, I can work in Hungarian but if I import the already made project (2nd screenshot) it turns back to English. Maybe it's on purpose.
•	In Chrome I can't get Hungarian blocks. Everything, always in English (Editor set to HU).
•	In Firefox, the project opens in English, a new Project has the issue of the EN blocks of the group turning to HU when dragged onto the canvas.

This seems similar to  (but not quite the same as) https://github.com/microsoft/pxt-microbit/issues/3655

**Expected behavior**
Expect blocks to switch locales completely as required.

**Desktop (please complete the following information):**
Peter is using the latest Firefox, Opera and Chrome on up-to-date Windows 10 Pro x64 HU. The Editor behaves the same way in all of my browsers. - OS: [e.g. iOS]
I used Win10, Microsoft Edge Version 90.0.818.62 (Official build) (64-bit) for the test above

**Comment by DaveAtKitronik** [comment]
tagging @hellsing71 as the translator for info.

**Comment by jwunderl** [comment]
I fixed this a while back with https://github.com/microsoft/pxt/pull/7622, but it hasn't made it's way to the live site yet; this works properly in makecode.microbit.org/beta now though / will work when we release!
