### ISSUE TITLE
Connect Device: Screen Splash after you click Next and Connect

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4103]
**Describe the bug**
**Connect Device**: Screen Splash after you click **Next** and **Connect**

**Steps to reproduce the behavior**
1.https://makecode.microbit.org/beta#editor
2.Click **. . .** next **Download**
3.**Connect Device**----->**Next**---->**Next**---->Choose device and click **Connect**

**Actual behavior**
Screen Splash after you click **Next** and **Connect**

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.86
3.Microsoft MakeCode version: 6.13.41

**Comment by abchatra** [comment]
@Sheila111 can you add some screen shot. We are unsure what slash means here.

**Comment by Sheila111** [comment]
Sorry, the **splash screen** was so fast that I couldn't record it. But you will see the **splash screen** if you try to click **Next** and **Connect**.

**Comment by abchatra** [comment]
Can't repro. If this still exists please do a gif recording.
