### ISSUE TITLE
Reading microbit internal sensors causes microbit to freeze

### ISSUE THREAD

**Issue by mads-slx** [microsoft/pxt-microbit#4105]
**Describe the bug**
After updating dependencies during release of a new version of [pxt-wappsto](https://github.com/Wappsto/pxt-wappsto), we suddenly observe dead micro:bits. After debugging the extension code for a while, we tracked the issue down to being reproducible without our extension code. 
Using the official version available at makecode.microbit.org, we observe that reading of on-board sensors can cause a deadlock/livelock. During our tests, the issue will arise after a period of anything from 1 to approx. 30 minutes.
In more complex programs including e.g. background tasks handling i2c communication it happens faster.

**To Reproduce**
1. Go to makecode.microbit.org
2. Create a fresh program from this template: https://makecode.microbit.org/_E2X0gv55MYjv
3. Transfer the code to a micro:bit 
4. Observe the microbit halt execution within an hour. (indicated by halted "loading bar LED pattern")

**Expected behavior**
The micro:bit should continue execution of the forever loop.

**Screenshots**
![image](https://user-images.githubusercontent.com/69514791/119482982-c716e100-bd54-11eb-80d8-c301e3f73d25.png)

**micro:bit version**
Tested and reproduced on V2.0

**Desktop:**
 - OS: Ubuntu 20.04
 - Browser: chrome
 - Version: 89.0.4389.90

**Additional context**
makecode.microbit.org version:  3.0.68
Microsoft MakeCode version:  6.0.39
microbit runtime version:  v2.2.0-rc6

**Comment by abchatra** [comment]
@jaustin v2 specific issue? Can you take this up?

**Comment by martinwork** [comment]
Related: https://github.com/lancaster-university/codal-microbit-v2/issues/102

**Comment by mads-slx** [comment]
Seems to be fixed in https://github.com/lancaster-university/codal-nrf52/commit/31a06cf34da0d5bc3e5e82c3245bfb8e320fcb09, @martinwork :+1: for the pointer!
makecode.microbit.org/beta [v3.1.86](https://github.com/microsoft/pxt-microbit/commits/v3.1.86) has codal-microbit-v2 v0.2.26 and I can't reproduce the issue in beta.

I guess the issue can be resolved by bumping codal-microbit-v2 to v0.2.26 in stable3.0.

**Comment by abchatra** [comment]
This is codal issue and fixed. If not reopen.
