### ISSUE TITLE
Service workers cannot work

### ISSUE THREAD

**Issue by yf-chen** [microsoft/pxt-microbit#4113]
I successfully deployed the MakeCode on my own server, and now I find that the Service Workers are not working, which makes my access slow.My browser supports this function and has configured HTTPS. Could you please help me solve this problem?One step away from success!
![image](https://user-images.githubusercontent.com/26783726/119666070-983d5f80-be67-11eb-9ea6-68e48a7bb2b0.png)

**Comment by abchatra** [comment]
This issue report is only for the issues in the live site (makecode.microbit.org). We don't take up issues with your hosting. You are responsible for fixing those and we will take the pull request.
