### ISSUE TITLE
Double image rendering for docs with youtube videos

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#4114]
![image](https://user-images.githubusercontent.com/4175913/119743321-7aa7d000-be3e-11eb-899e-fe9ddf7f95c1.png)

https://makecode.microbit.org/v1/behind-the-makecode-hardware

**Comment by jwunderl** [comment]
Do we point at the v1 docs from anywhere? It doesn't repro on https://makecode.microbit.org/v2/behind-the-makecode-hardware / https://makecode.microbit.org/behind-the-makecode-hardware so it's pretty old / I wouldn't see us porting a fix back to that?

**Comment by abchatra** [comment]
Hmm we are not going to fix v1 which was released 5 years ago.

**Comment by pelikhan** [comment]
I can't remember how i landed on this.
