### ISSUE TITLE
Feature: Page that pings all required domains and lists status

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4115]
> Originally requested in https://github.com/microsoft/pxt-microbit/issues/4052#issuecomment-848905155

We need a page that automatically pings all required domains that a IT/teacher admin can use to easily test things are ok. Discovering this by trial and error is messy.

List of domains in https://makecode.microbit.org/faq

**Comment by abchatra** [comment]
Fixes https://github.com/microsoft/pxt-microbit/issues/4115

**Comment by abchatra** [comment]
This is implemented. You will need to wait for the release to test this out at this moment.

**Comment by abchatra** [comment]
/faq has a test domain button which will work after release
