### ISSUE TITLE
"Format Code" shouldn't be available if no code

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4117]
**Describe the bug**
"**Format Code**" shouldn't be available if no code

**Steps to reproduce the behavior**
1.Nabigate to https://makecode.microbit.org/beta#editor
2.Delete all blocks in **Blocks Editor**
3.Right-click

**Actual behavior**
"**Format Code**" shouldn't be available if no code. It should be gary.
![image](https://user-images.githubusercontent.com/59192069/119788781-05530280-bf05-11eb-8fc0-7493662db41b.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.87
3.Microsoft MakeCode version: 6.13.42

**Comment by abchatra** [comment]
P3 won't fix.
