### ISSUE TITLE
Mac: There appears blue frame line next "Documentation"

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4118]
**Describe the bug**
**Mac**: There appears blue frame line next "**Documentation"**

**Steps to reproduce the behavior**
1.Nabigate to https://makecode.microbit.org/courses/csintro/coordinates/overview
2.Click the icon next "**Documentation**"

**Expect behavior**
No frame line when clicking the icon next "**Documentation"**
![3](https://user-images.githubusercontent.com/59192069/119795129-c1fb9280-bf0a-11eb-86f1-b6858ff460db.gif)
![image](https://user-images.githubusercontent.com/59192069/119795244-dfc8f780-bf0a-11eb-81b5-d3a63453f112.png)

**Actual behavior**
Mac: There appears blue frame line next "**Documentation"** when clicking it
![2](https://user-images.githubusercontent.com/59192069/119791646-94f9b080-bf07-11eb-9d64-740a48ad2798.gif)
![image](https://user-images.githubusercontent.com/59192069/119795114-bd36de80-bf0a-11eb-8dce-69f5a7165761.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.87
3.Microsoft MakeCode version: 6.13.42

**Comment by abchatra** [comment]
P3 won't fix.
