### ISSUE TITLE
Serial Data from device not working in Chrome

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4120]
Can someone else try to repro this?
Create a program with some serial data (ie https://makecode.microbit.org/_00YaRo3Cpcoz)
Download to v1 or v2 hardware

I don't see the Show Console Device button show up.
Using Edge, this works.

**Comment by abchatra** [comment]
You need to add writelLine

**Comment by abchatra** [comment]
To flush the data

**Comment by Jaqster** [comment]
It works on Edge...

**Comment by abchatra** [comment]
Hmm though does it work on Chrome after adding writeLine?

**Comment by abchatra** [comment]
And are you using both the browsers together with WebUSB? Only one browser can connect to the device.

**Comment by Jaqster** [comment]
Gosh darnit, you're right!  
Happened again - my WebUSB connection was being hogged by Edge....
