### ISSUE TITLE
Empty field of "is sprite touching other" block looks like boolean

### ISSUE THREAD

**Issue by sgk** [microsoft/pxt-microbit#4130]
**Describe the bug**
The empty field of "is %sprite|touching %other" block (%other) looks like boolean because the field is hexagon. This is confusing for beginner users.

**To Reproduce**
1. Put "is sprite touching other" block in the programing area

**Expected behavior**
The empty field should be rounded shape.

**Screenshots**
![image](https://user-images.githubusercontent.com/485416/120078236-69362080-c0e9-11eb-9865-aa105a4cc06c.png)

**micro:bit version (please complete the following information):**

V2.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91

**Comment by abchatra** [comment]
I am not sure when it doesn't take a boolean parameter it is shown as a boolean. Can we fix this?
