### ISSUE TITLE
Touch logo does not work on simulator with build in speaker off

### ISSUE THREAD

**Issue by microbit-pauline** [microsoft/pxt-microbit#4134]
**Micro:bit support ticket 45682**

**Describe the bug**
When the touch logo is touched to stop the built in speaker from playing, it does not work in the simulator. Works when the code is run on the micro:bit

**To Reproduce**
![image](https://user-images.githubusercontent.com/29146842/120338243-f5b03100-c2eb-11eb-8b19-0241b3c6584a.png)

**Expected behavior**
The user expects that when the touch logo is placed then music will stop in the simulator

**Screenshots**
As above

**micro:bit version (please complete the following information):**
V2

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abchatra** [comment]
This block is specific to hardware. Simulator always plays sound if you have music\sound blocks. This is by design as user has headphones connected to pins and needs to hear out how the sound is played in the simulator.
