### ISSUE TITLE
Data Logger Extension Thumbnail

### ISSUE THREAD

**Issue by soniakandah** [microsoft/pxt-microbit#4141]
### **The Problem**

The thumbnail for the data logger extension is not very clear and may not attract our desired users. 

![image](https://user-images.githubusercontent.com/22336391/121089060-70b99180-c79b-11eb-97ab-aa9ccb48cb68.png)

We should create a new asset for this extension. 

@jwunderl  for visibility

**Comment by microbit-giles** [comment]
It's a tricky concept to get across visually, but I agree this image should be updated (it would be good for a thermal printer driver!). Perhaps something with a simple line graph and table of numbers would work?

**Comment by soniakandah** [comment]
Here's my take on the data logging extension thumbnail, let me know what y'all think!
 
![Data_Logger_Ext](https://user-images.githubusercontent.com/22336391/121942873-d232b080-cd05-11eb-989f-696fac15dff7.png)

**Comment by jwunderl** [comment]
This is great, I'll update at same time as https://github.com/microsoft/pxt-microbit/issues/4142 ~

**Comment by microbit-giles** [comment]
Much clearer! Do the curved lines suggest it's a radio feature? I wonder if it would be just as good without them?

**Comment by soniakandah** [comment]
@microbit-giles Ah I meant it to refer to like either using the speaker, shaking the device, etc. But yeah I guess it's not communicated well, should I change them?

**Comment by soniakandah** [comment]
The team talked about this during our design sync and I will be replacing the radio waves with "V2 Only"

**Comment by soniakandah** [comment]
Here's the updated image!

![Data_Logger_Ext 2](https://user-images.githubusercontent.com/22336391/122131460-0e414080-cdee-11eb-8bfd-7236d3eb9041.png)

**Comment by abchatra** [comment]
@jaustin

**Comment by jaustin** [comment]
Thanks for this! I see I was too slow today to respond but we have the 'works with' badges that we'd really like to overlay on the image (either directly, or in MakeCode when showing the tile?)

https://microbit.org/brand-guidelines/

![image](https://user-images.githubusercontent.com/147113/122275156-4b373100-cedb-11eb-8899-13bc48527931.png)

The icon itself looks great!

**Comment by soniakandah** [comment]
@jaustin How is this? 
![Data_Logger_Ext 3](https://user-images.githubusercontent.com/22336391/122284066-15c22180-cea2-11eb-9a18-137daf3f7163.png)

@jwunderl reopening

**Comment by jaustin** [comment]
Hi @soniakandah thanks, that's great - I still love the original but this one fits the requirements and sets the right example for other extensions.

Only thing to consider is that all the other extensions that are V2 only will likely follow what you have done here... For that reason, do we want to consider putting it bottom right hand corner more as an 'overlay'? 

If we were to do that, it'd probably make sense to move the micro:bit image up to balance the image?

<img width="441" alt="image" src="https://user-images.githubusercontent.com/147113/122368162-00f29600-cf55-11eb-8146-0e8e5a92ac70.png">

**Comment by soniakandah** [comment]
I personally lean towards the badge being in the top right corner so it's further away from the added title and description and thus doesn't get as lost. Maybe we can revisit next time I make another V2-only extension thumbnail?
