### ISSUE TITLE
Homepage Banner Images

### ISSUE THREAD

**Issue by soniakandah** [microsoft/pxt-microbit#4142]
### **The Problem**

Our current image carousel on the homepage needs some banner images to attract users. We have five items we need carousel images for: 

- [Microsoft MakeCode for the micro:bit](https://makecode.microbit.org/#tutorial:/projects/flashing-heart) 
- [Intro to the micro:bit](https://microbit.org/get-started/first-steps/introduction/)
- [Behind the MakeCode hardware](https://www.youtube.com/playlist?list=PLMMBk9hE-SeqDYtw9pGNPsQ10V_EGMyGe)
- [Send messages with your micro:bit](https://makecode.microbit.org/#tutorial:/projects/micro-chat)
- [Track the soil moisture of your plants](https://makecode.microbit.org/projects/soil-moisture)

@jwunderl @Jaqster for visibility

**Comment by soniakandah** [comment]
[Microsoft MakeCode for the micro:bit](https://makecode.microbit.org/#tutorial:/projects/flashing-heart)

Inspiration: 
![image](https://user-images.githubusercontent.com/22336391/121093107-71552680-c7a1-11eb-9dc8-74dd0b75ce61.png)

Banner Image: 
![mb-banner-01](https://user-images.githubusercontent.com/22336391/121093189-8467f680-c7a1-11eb-8dc0-2f39a8e17661.png)

**Comment by soniakandah** [comment]
[Intro to the micro:bit](https://microbit.org/get-started/first-steps/introduction/)

Inspiration: 
![image](https://user-images.githubusercontent.com/22336391/121093258-9fd30180-c7a1-11eb-9798-a78899007719.png)

Banner Image: 

![mb-banner-02](https://user-images.githubusercontent.com/22336391/121239734-77551100-c84e-11eb-8552-48c3c37830b7.png)

**Comment by soniakandah** [comment]
[Behind the MakeCode Hardware](https://www.youtube.com/playlist?list=PLMMBk9hE-SeqDYtw9pGNPsQ10V_EGMyGe)

Inspiration: 

![image](https://user-images.githubusercontent.com/22336391/121239968-b7b48f00-c84e-11eb-874c-b50174496987.png)

Banner Image: 

![mb-banner-03](https://user-images.githubusercontent.com/22336391/121240002-bc794300-c84e-11eb-9ab7-4315575557e2.png)

**Comment by soniakandah** [comment]
[Send messages with your micro:bit](https://makecode.microbit.org/#tutorial:/projects/micro-chat)

Inspiration: 

![image](https://user-images.githubusercontent.com/22336391/121240104-d87ce480-c84e-11eb-81a5-fd377bb277a3.png)

Banner Image:

![mb-banner-04](https://user-images.githubusercontent.com/22336391/121240120-dca90200-c84e-11eb-9f10-2a8b0bc4658f.png)

**Comment by abchatra** [comment]
@jwunderl do you have all the banner necessary? Can we update this for friday testing?

**Comment by jwunderl** [comment]
One more to go I believe, but I'll plug in the existing ones for friday after stream~

**Comment by microbit-giles** [comment]
The banners look great. We have a few requests on the use of colours so they align with the micro:bit visual brand: https://cdn.sanity.io/files/ajwvhvgo/production/24e458cd665a5a38128ae3f1c890c3e90707ad51.pdf?dl=MicroBit%20Foundation%20Brand%20Guidelines_2020.pdf 

There are 3 colour gradients in the micro:bit brand, 'lantern', 'dusk' and 'polar' and it would be great to see them applied here to support the brand identity of mb with MakeCode. Specifically the images for 'Intro to the micro:bit', 'Behind the MakeCode hardware' and 'Send messages' are currently inconsistent with the brand gradients.

Thank you!

**Comment by soniakandah** [comment]
Here are the updated banners! @microbit-giles let me know if the gradients are correct and take a look at the new character art for the communication banner. @jwunderl let me know if you need any adjustments to file size or anything! 

![Micro:bit_Banner_01](https://user-images.githubusercontent.com/22336391/121942296-2db06e80-cd05-11eb-874c-97661ee73038.png)
![Micro:bit_Banner_02](https://user-images.githubusercontent.com/22336391/121942307-30ab5f00-cd05-11eb-9325-6e22c8fd4300.png)
![Micro:bit_Banner_03](https://user-images.githubusercontent.com/22336391/121942312-3143f580-cd05-11eb-9ccb-fa00c035343e.png)
![Micro:bit_Banner_04](https://user-images.githubusercontent.com/22336391/121942317-32752280-cd05-11eb-9efa-05013b5232aa.png)
![Micro:bit_Banner_05](https://user-images.githubusercontent.com/22336391/121942320-33a64f80-cd05-11eb-8185-17d4383ed9e1.png)

**Comment by jwunderl** [comment]
These look so good, thanks! I'll upload them after lunch -- I'll be compressing them down to about 100-200kb but it shouldn't be noticeable (e.g. as the new banners currently look on https://makecode.microbit.org/beta)

**Comment by abchatra** [comment]
This looks good to me as well.

**Comment by soniakandah** [comment]
Comments from our team's design sync:

- Always have the banner images fixed to the left (vertically centered) so that screen size changes will clip the image from the right only. This will ensure that the image's blank space on the left is always the same width for the overlaid text. 

@jwunderl for visibility

**Comment by microbit-giles** [comment]
Hi there – these are looking good. We have some specific feedback on the gradients:
- Image 3 Dusk gradient – the orange on the right looks like it may be too transparent or brighter than the orange colour in the gradient.
- Image 4 The polar gradient looks wrong here, it should be purple to teal, but it looks like lantern blue on the right. Can we swap the blue for teal? Our brand guidelines don’t permit mixing and matching colours from different palettes.
- Image 5 Gradient should be green to blue, not blue to green. Also, can the tipping point between the colours be more central so there’s more of a block of each colour?
Many thanks, Giles
