### ISSUE TITLE
Science Experiments: Some links can't be opened

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4152]
**Describe the bug**
**Science Experiments**: Some links can't be opened

**Steps to reproduce the behavior**
1.Nabigate to https://makecode.microbit.org/courses/ucp-science/body-electrical/resources
2.Click the link behind  "**Utah Science with Engineering Education (SEEd)**"

**Actual behavior**
Some links  as shown below can't be opened.
![image](https://user-images.githubusercontent.com/59192069/121476013-bb841500-c9f8-11eb-8a4b-441e2a09103a.png)
![2](https://user-images.githubusercontent.com/59192069/121476592-714f6380-c9f9-11eb-9a22-f5fad7682f89.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.91
3.Microsoft MakeCode version: 6.13.49

**Comment by Jaqster** [comment]
The only broken link I saw was the 2nd one - https://schools.utah.gov/file/265a0b53-b6a7-48fb-b253-b6a5f38ffe19
We can remove this.

**Comment by Sheila111** [comment]
@Jaqster But I still can't open other 3 links.
![image](https://user-images.githubusercontent.com/59192069/124055980-78e1b580-da57-11eb-8791-570feccac6d2.png)
![1](https://user-images.githubusercontent.com/59192069/124056005-8434e100-da57-11eb-84aa-a1fd915a7ddb.gif)
