### ISSUE TITLE
Add information to windows app deprecation help page

### ISSUE THREAD

**Issue by livcheerful** [microsoft/pxt-microbit#4159]
We have to deprecate the windows app because Monaco no longer supports legacy Edge (and the windows app can only use legacy edge :( ). I made a help page for users to go to from the app in the deprecation banner if they want more info.

I created a preliminary page here https://github.com/microsoft/pxt/blob/master/docs/windows-app.md but wasn't sure what level of information would be good enough.

I think we need to explain how they can export their projects, maybe point them to the Electron app? And maybe talk about the differences between the Windows app and the website? I think the only one is serial logging/file system access?

**Comment by abchatra** [comment]
Done.
