### ISSUE TITLE
Beta: Datalogging - Expanded array items do not have default text

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4161]
When clicking + to add an array item, the initial values are not populated, making it harder for the user to add more columns

![Image 2021-06-11 at 9 40 33 am](https://user-images.githubusercontent.com/31242877/121658295-15d4b280-ca99-11eb-9206-26f81427491e.jpg)

Ref https://github.com/microsoft/pxt-microbit/pull/4146

**Comment by jwunderl** [comment]
Yup, good catch -- I had mentioned this in the notes in https://github.com/microsoft/pxt-microbit/pull/4146, working on it / should get a fix early next week but good to have a bug to track it :)

**Comment by abchatra** [comment]
This is fixed
