### ISSUE TITLE
Simulator stops auto-running in text editing

### ISSUE THREAD

**Issue by livcheerful** [microsoft/pxt-microbit#4166]
**Describe the bug**
When editing text in Javascript, the simulator stops itself and you have to push play to start it again.

**To Reproduce**
1. Go to Javascript editor
2. The simulator is going
3. Make a code change
4. The simulator is stopped
5. Press the play button to run code

**Expected behavior**
The simulator updates as you write new code like in blocks.

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome

**Comment by abchatra** [comment]
This is by design. We didn't want to run auto run in the text as it hogs the CPU for pretty much every stroke it would restart. It is ok for advanced users as they know how to start.
