### ISSUE TITLE
Partner links in the top left do not work 

### ISSUE THREAD

**Issue by b-buckler** [microsoft/pxt-microbit#4168]
**Describe the bug**
When clicking the Microsoft or micro:bit logos, nothing happens, I believe it should navigate to the respective websites

**To Reproduce**
1. Go to https://makecode.microbit.org/beta# using Chrome
2. Click on Microsoft or micro:bit logos in the top left, nothing happens

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abchatra** [comment]
We have decided not to link back to websites as this is confusing for students.

**Comment by martinwork** [comment]
@abchatra The micro:bit logo behaves like the Home button on all browsers I tried.

**Comment by abchatra** [comment]
In the editor view, that is how it was.

**Comment by abchatra** [comment]
before as
