### ISSUE TITLE
Data logger console formatting is confusing

### ISSUE THREAD

**Issue by livcheerful** [microsoft/pxt-microbit#4170]
**Describe the bug**
The logged data isn't always creating a new line for each time entry

**To Reproduce**
1. Run this on microbit: https://makecode.microbit.org/_Lhf19HVxe1Hb
2. Check the device's console log
3. Sometimes the time isn't on a new line 

**Expected behavior**
There's a fresh line for each new time entry

**Screenshots**
![image](https://user-images.githubusercontent.com/18712271/121730196-33f3e000-caa4-11eb-95f5-78e5fe27039f.png)

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome

**Comment by jwunderl** [comment]
moving to https://github.com/microsoft/pxt-microbit/issues/4171
