### ISSUE TITLE
Serial Data format to match Data Logging format

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4171]
Let's align the Serial Data logging format to match how we do it for the new Data Logging blocks.

Data Logging:
![image](https://user-images.githubusercontent.com/22108954/121730899-1ecb8100-caa5-11eb-915f-1ec8043ff2ca.png)

Serial Data:
![image](https://user-images.githubusercontent.com/22108954/121731041-47ec1180-caa5-11eb-8222-ff61ad9a458d.png)

**Comment by abchatra** [comment]
Is this the bug on existing serial data or the new data logging?

**Comment by Jaqster** [comment]
Bug to fix the existing serial data - make it match the new data logging format

**Comment by jwunderl** [comment]
Fixed with https://github.com/microsoft/pxt-microbit/pull/4182, codal side will come with a bump later today most likely
