### ISSUE TITLE
Data logger logging extra entries

### ISSUE THREAD

**Issue by livcheerful** [microsoft/pxt-microbit#4173]
**Describe the bug**
I wrote a program that logs values every three seconds. However I see on start that it logs a couple of extra times 

**To Reproduce**
1. Run this program on microbit: https://makecode.microbit.org/_f3YEErXFp1de
2. After a bit, open the MY_DATA.HTM file
3. There's a couple of logs within the first second

**Expected behavior**
There should only be one log in the first second

**Screenshots**
![image](https://user-images.githubusercontent.com/18712271/121733046-d6619280-caa7-11eb-98bc-9347b0756fd6.png)

**micro:bit version (please complete the following information):**
V2, running 0254 firmware

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser: Chrome

**Comment by abchatra** [comment]
Nice bug
