### ISSUE TITLE
Set Columns block - potentially confusing to use

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4174]
We should think about a better way to do data logging using the Set Columns block.
Lots of opportunities for students to misuse this - not using the right column names, or the right number of columns when logging data.
Idea - infer column names once they're set in the Log Data name/value pairs.
![microbit-screenshot (14)](https://user-images.githubusercontent.com/22108954/121733274-204a7880-caa8-11eb-943d-055e3502036c.png)

**Comment by abchatra** [comment]
Lets try to do the prepopulated string values atleast.

**Comment by abchatra** [comment]
@jwunderl did you end up implementing prepopulated string values?

**Comment by microbit-mark** [comment]
Had someone report that logging wasn't working, on a closer inspection of the problem, it was this issue. A simple case of using mixed cases in declaring and using the variable.

![image](https://user-images.githubusercontent.com/31242877/128978793-668d0768-5d50-415a-8992-191b93b3bb5a.png)

I could see this being a really common problem.

**Comment by microbit-mark** [comment]
In our user study, another user tried to replace the column headers with inputs. 
![Image 2021-11-16 at 9 19 41 am](https://user-images.githubusercontent.com/31242877/141957592-4ad32db4-0b94-449f-95eb-1ba7ac4a9e19.jpg)

This errors and they identified that this would not work and so they started again.

**Comment by aorczyk** [comment]
When I used it first time in JS and hadn't seen blocks before, I tried to use it exactly this way. Imho ColumnValue is an unnecessary complication, but maybe there are cases where it is a better solution (ex. many columns).

**Comment by abchatra** [comment]
Idea of columns is useful if you have to just log one column sometimes and still want to get the entire row of data and the column value to be at the right place.

**Comment by abchatra** [comment]
Here is what we are planning to improve the discoverability of the column names

- we will build intellisense into the column names. Something like following
![image](https://user-images.githubusercontent.com/6107272/148420997-48ebc1a0-dc32-45c1-834a-f9056a172dd4.png)
 

Even if the user doesn't use _set columns_  api, intellisense would work if the column value is used once before.

**Comment by abchatra** [comment]
This has an added benefit that in text we can build similar feature for column names.

Other option we brainstormed was enum for column names, however this is hard transition for students from blocks to text.

**Comment by aorczyk** [comment]
Ok, now I know where is a problem. I have another view, maybe because I accustomed to a spreadsheet. In Google Spreadsheet Api, method which appends new row has as parameter an array of values ([appendRow](https://developers.google.com/apps-script/reference/spreadsheet/sheet#appendrowrowcontents)). I have to know which column is right, but when I use it one time, this is not a problem. The problem for a student will be for example logging data from sensor one every second and from sensor two every five seconds because he have to think about a row in a table. I think your solution is better because student should think about a data not a way it should be logged.

**Comment by abchatra** [comment]
Another possible improvement to the blocks discussed is to move the array version to the bottom and make simple column value pairs blocks. This is pending feasibility of blocks to text transition.

**Comment by jaustin** [comment]
My preference would be to deprecate the 'array of' blocks rather than move them to the bottom. We've been holding back taking datalogging out of beta so we could do that when the blocks were improved.

**Comment by abchatra** [comment]
This is fixed.
