### ISSUE TITLE
Data logger HTML times ordered incorrectly

### ISSUE THREAD

**Issue by livcheerful** [microsoft/pxt-microbit#4175]
**Describe the bug**
For <1 values, it's not ordered in increasing time values.

**To Reproduce**
1. Run this code https://makecode.microbit.org/_f3YEErXFp1de on microbit
2. Check out the MY_DEVICE.HTM
3. For the values under 1.0, they are ordered incorrectly

**Screenshots**
![image](https://user-images.githubusercontent.com/18712271/121733406-4e2fbd00-caa8-11eb-951f-5d832e150cba.png)

**micro:bit version (please complete the following information):**
0254, v2 board

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome

**Comment by jwunderl** [comment]
This looks like the microbit ran for < 3 seconds and then restarted? The data / table persists through restarts. (it's not possible for it to be ordered wrong otherwise as it's always just appended)

**Comment by abchatra** [comment]
Yes time resets across the restart. But it should display in that order in the HTM. I am not sure how this can happen.

**Comment by abchatra** [comment]
@finney @jaustin ?

**Comment by jwunderl** [comment]
in this case it looks like it was logged at .53 seconds in one run followed by .20 seconds in the second run -- not out of order, just two different runs

**Comment by abchatra** [comment]
Oh I see. Then it is as designed.
