### ISSUE TITLE
Log Data - use multi-line as default

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4177]
This block is too long.
Let's do multi-line wrapping by default (one name/value pair per line)
![microbit-screenshot (15)](https://user-images.githubusercontent.com/22108954/121734410-97344100-caa9-11eb-879d-d2ef5979eb52.png)

**Comment by abchatra** [comment]
Probably we need to make multi-line or not as part of the block attributes.

**Comment by abchatra** [comment]
Implemented.
