### ISSUE TITLE
Edit default values for every block

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4185]
The default values have been re-used from another dropdown. It might be useful, eg for the data logging feature in https://github.com/microsoft/pxt-microbit/pull/4146 to change these defaults to longer periods eg 1 minute/ 1 hour? Adding @microbit-giles for comment.

It would also be useful as stated in the original request to have this block show up in a search for 'time' or 'timer'.

 ![87F94D50-1D4F-45D3-BAA6-B72225B74262](https://user-images.githubusercontent.com/31242877/121657332-39e3c400-ca98-11eb-89d8-958f2462398e.jpg)

_Originally posted by @microbit-mark in https://github.com/microsoft/pxt-microbit/issues/4068#issuecomment-859389624_

**Comment by microbit-giles** [comment]
To facilitate longer data logging experiments a list like:
100ms
200ms
500ms
1 second
1 minute
1 hour
would be useful. At the moment it would be quite hard to explain to a young student how to set it up to log every hour.
