### ISSUE TITLE
Blocks dissapear when using localised extensions

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4186]
https://support.microbit.org/helpdesk/tickets/45672

**Describe the bug**
When adding an extension in MakeCode in the French locale eg Neopixel or Sonar, the blocks dissapear.

**To Reproduce**

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 
<img width="802" alt="image" src="https://user-images.githubusercontent.com/31242877/122210703-d396e100-ce9d-11eb-8dd6-9aba570f4961.png">

![image](https://user-images.githubusercontent.com/31242877/122210821-f628fa00-ce9d-11eb-973c-b99b0f6de80c.png)

**Desktop (please complete the following information):**
 - OS: Win 10/7
 - Browser Firefox
 - Version 89

**Additional context**

**Comment by riknoll** [comment]
I can't reproduce this in Chrome or Firefox on my mac... @abchatra can you reproduce this on Windows?

**Comment by abchatra** [comment]
I am also unable to repro in edge on windows. Sorry I should have tried this before.
@microbit-mark can you ask the user to share the program? Are you able to repro?

**Comment by microbit-mark** [comment]
I can't repro on Win 10 or 7 Firefox 89, so closing until we can get a reproducer.
