### ISSUE TITLE
Reference docs for datalogger apis

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#4188]
Hey Galen, we have a new extension providing blocks for the datalogger apis that we need reference docs for https://github.com/microsoft/pxt-microbit/blob/master/libs/datalogger/datalogger.ts for this release. If it helps these are the related pull requests: https://github.com/microsoft/pxt-microbit/pulls?q=is%3Apr+datalogger+is%3Aclosed . Thanks!

**Comment by abchatra** [comment]
@ganicke is it possible to take a look at building this documentation?

**Comment by ganicke** [comment]
I can. I've run out of hours for FY21 so I've been doing just small things for the remaining few days.

**Comment by abchatra** [comment]
Sounds good. This is not urgent now as we have made it searchOnly due to other bugs. Next month is good.
