### ISSUE TITLE
Sharing a Project using the Data Logging extension problem

### ISSUE THREAD

**Issue by dsssssssss9** [microsoft/pxt-microbit#4189]
**Describe the bug**
When sharing the link to a project including the Data logging extension the supplied link does NOT include the "beta#" in the link
so when someone opens the link they get errors

**To Reproduce**
1. Go to 'https://makecode.microbit.org/_Fcc86X1q89Ft'

2. See error -  manually adding "beta#" after the last "/" seems to work

**Expected behavior**
The share link should do this automatically?

**Screenshots**
![image](https://user-images.githubusercontent.com/30810847/122293024-82fba400-ceee-11eb-8965-75f97560faed.png)

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - V2.0

**Desktop (please complete the following information):**
 - OS: Linux / windows
 - Browser ALL
 - Version ALL

**Comment by abchatra** [comment]
This will be fixed once we release the /beta to live. Share page always points to live and datalogger is not present there. If you import the URL into /beta it should work. Try and let us know.

**Comment by dsssssssss9** [comment]
Thanks for letting me know..

Yes the workaround works 

Any timescale on releasing /beta to live ?

**Comment by abchatra** [comment]
Plan is to ship in 2 week
