### ISSUE TITLE
Mac: All contents in homepage disappeared after clicking "Reset"

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4191]
**Describe the bug**
**Mac**: All contents in homepage disappeared after clicking "**Reset**"

**Steps to reproduce the behavior**
1.Nabigate to https://makecode.microbit.org/beta#
2.Settings----->**Reset**

**Expect behavior**
All **projects** are deleted and homepage's content still exist
![1](https://user-images.githubusercontent.com/59192069/122364861-c0167380-cf8c-11eb-9eb4-0976428ed940.gif)

**Actual behavior**
All contents in homepage disappeared after clicking "**Reset**". You can restore it by **refreshing** the page.
![2](https://user-images.githubusercontent.com/59192069/122364875-c3116400-cf8c-11eb-94d2-17fe12ab1f2c.gif)

**Additional context**
1.OS: Mac
2.makecode.microbit.org version: 3.1.93
3.Microsoft MakeCode version: 6.13.53

**Comment by Sheila111** [comment]
@abchatra It also happened in **Windows** in new beta version **v4.0.2**. And it **can't restore** even if **refreshing** the page.
![1](https://user-images.githubusercontent.com/59192069/123189370-4ae8f800-d4d0-11eb-9bf8-d2a5f9facd0e.gif)

**Comment by abchatra** [comment]
@Sheila111 can't repro. If this still happens let me know.
