### ISSUE TITLE
Both "Make it: code it" and "Networking with the micro:bit" jump to the same link

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4192]
**Describe the bug**
Both "**Make it: code it**" and "**Networking with the micro:bit**" jump to the same link

**Steps to reproduce the behavior**
1.Nabigate to https://makecode.microbit.org/beta#
2.Courses----->**Make if: code it**------->Show Instructions
3.Courses----->**Networking with the micro:bit**------->Show Instructions

**Actual behavior**
Both "**Make it: code it**" and "**Networking with the micro:bit**" jump to the same link (https://microbit.org/projects/make-it-code-it/)
![3](https://user-images.githubusercontent.com/59192069/122372855-99a80680-cf93-11eb-8c6e-6b4a29f227b6.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.93
3.Microsoft MakeCode version: 6.13.53

**Comment by ganicke** [comment]
@Sheila111 - Nice adhoc testing, good find. Thanks!
