### ISSUE TITLE
Expanded delete log block has black background in dropdown

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4194]
Drag in this block and press `+.` The initial background is black. I would expect it to be green 

<img width="261" alt="image" src="https://user-images.githubusercontent.com/31242877/122427633-2f8a6400-cf89-11eb-96da-188ccb27d906.png">

Chrome 91
Mac OS 11

**Comment by abchatra** [comment]
Fixed in /beta
