### ISSUE TITLE
No response when clicking "Support" and "Buy"

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4200]
**Describe the bug**
No response when clicking "**Support**" and "**Buy**"

**Steps to reproduce the behavior**
1.Nabigate to https://makecode.microbit.org/beta#editor
2.Help------->"**Support**" and "**Buy**"

**Actual behavior**
No response when clicking "**Support**" and "**Buy**"
![1](https://user-images.githubusercontent.com/59192069/122493905-116d4400-d01b-11eb-8e64-c1ee0b46e33b.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.93
3.Microsoft MakeCode version: 6.13.53

**Comment by abchatra** [comment]
Nice bug @Sheila111
