### ISSUE TITLE
TypeScript -> Python doesn't generate valid code

### ISSUE THREAD

**Issue by jaydeetay** [microsoft/pxt-microbit#4201]
**Describe the bug**
This might, at its heart, be a dupe of some of the other Python issues , especially to do with classes such as:
https://github.com/microsoft/pxt-microbit/issues/3456

I have a simple bit of code that works fine in JavaScript.  It creates a class with a single method.  When I hit the Python tab it converts it to (AFAICT) legal Python, but MakeCode doesn't like it.  You can make a trivial change to it (e.g. changing the value of an argument) and MakeCode won't allow you to switch back to JavaScript.

**To Reproduce**
1. Import this project: https://github.com/jaydeetay/pythontest
2. The TypeScript file should be just fine.
3. Switch to Python.
4. Note the errors.
5. (Optional): Change the arg in showNumber and you'll be unable to switch back to JS.

**Expected behavior**
You should be able to roundtrip this code from JS to Python and back.

**Screenshots**

![image](https://user-images.githubusercontent.com/16431883/122497992-5b730d00-cfbc-11eb-87cf-34f8c658ac91.png)

**micro:bit version (please complete the following information):**

N/A - not deploying to hardware.

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome
 - Version [e.g. 22]  91.0.4472.81

**Comment by jaydeetay** [comment]
@microbit-mark

**Comment by abchatra** [comment]
We don't good support for class conversion from typescript to python yet.  We have provided an error message in /beta for this for now.

![image](https://user-images.githubusercontent.com/6107272/122506362-0a125000-cfb3-11eb-8c6d-f541677796c1.png)

**Comment by microbit-mark** [comment]
> We don't good support for class conversion from typescript to python yet. We have provided an error message in /beta for this for now.
> 
> ![image](https://user-images.githubusercontent.com/6107272/122506362-0a125000-cfb3-11eb-8c6d-f541677796c1.png)

For clarity @jaydeetay this is referring to the beta version of MakeCode available at  https://makecode.microbit.org/beta due to be made live in the next couple of weeks.

**Comment by jaydeetay** [comment]
Thanks for the update folks. I was just super excited to see Python support there at all - one of my mentees is keen to learn it.

OK - well we can use MakeCode to get started and maybe move the 'full' Python editor at https://python.microbit.org/v/2 once we need to get a bit more advanced.  I was just hoping to use the excellent emulator and GitHub integration.

BTW - although I posed this as a problem with the TypeScript->Python conversion, it seems less the conversion that's the problem (the converted code LGTM) but more that valid Python isn't accepted.  I think you know that, just wanted to clarify for any other people who stumble on this.
