### ISSUE TITLE
Data log does not update when WebUSB is connected in MakeCode

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4203]
**Describe the bug**
Originally raised in CODAL https://github.com/lancaster-university/codal-microbit-v2/issues/124, but this might be a MakeCode related bug.

It seems to be the case that the MY_DATA.HTML page does not update whilst MakeCode is using the WebUSB connection. When the micro:bit is disconnected from MakeCode using the webUSB disconnect process and the data logging activity is undertaken again, the page will update as expected when the micro:bit is disconnected then reconnected.

**To Reproduce**
This was my first reproducer, but doesn't seem consistent.

1. Open this program and flash via webUSB
![image](https://user-images.githubusercontent.com/31242877/122526604-63f63280-d012-11eb-9bdc-c31ff8c85484.png)
[microbit-Data-logger.hex.zip](https://github.com/microsoft/pxt-microbit/files/6675504/microbit-Data-logger.hex.zip)
2. Press button A to log some data
3. Open MY_DATA file on the micro:bit. No data is visible
4. Press button A to log more data and reload page. No data is visible.
5. Disconnect and reconnect micro:bit USB
6. Reload MY_DATA page. No data is visible
7. Unpair micro:bit WebUSB in MakeCode and reload MakeCode page
8. Reload MY_DATA. No data is visible.
9. Disconnect and reconnect micro:bit USB
10. Reload MY_DATA. Data is visible in table

The second time I tried to reproduce the page does not load as expected, but some data is still logged.

![image](https://user-images.githubusercontent.com/31242877/122528326-18448880-d014-11eb-8a57-13dca4b9ea63.png)

**Expected behavior**
Table should always update when micro:bit is disconnected and reconnected

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abchatra** [comment]
This is a codal bug.
