### ISSUE TITLE
How is the data storage part working in this project ?

### ISSUE THREAD

**Issue by znyrsam** [microsoft/pxt-microbit#4204]
How is the data storage part working in this project and which file it has been written?

**Comment by abchatra** [comment]
We will have documentation on how this is working before the release. Data logger extension will create a file in microbit which you can access when connected to the computer.

**Comment by znyrsam** [comment]
please, share the documentation link and what do you mean by data logger extension we need to manually install these extensions or not?

**Comment by dsssssssss9** [comment]
https://microbit.org/get-started/user-guide/data-logging/
