### ISSUE TITLE
Changing data log timestamp format always adds an extra column

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microsoft/pxt-microbit#4206]
**Describe the bug**

On MakeCode beta with the data logging extension enabled, calling `datalogger.includeTimestamp(FlashLogTimeStampFormat.Minutes)` before logging adds a new column to the output in addition to the "Time (seconds)" column.

I would have expected the "Time (seconds)" to column to have been replaced.

The output gets pretty weird. In this case I called `includeTimestamp` twice with minutes and milliseconds:

![image](https://user-images.githubusercontent.com/44397098/122580591-04b61380-d04e-11eb-955b-a5aa89ecf113.png)

Looking at the code, it seems CODAL's default is no timestamp. MakeCode calls `includeTimestamp(FlashLogTimeStampFormat.Seconds)` on datalogger init to set its preferred default (includeTimestamp calls MicrobitLog::setTimestamp).

In CODAL, `MicroBitLog::setTimeStamp` always calls `MicroBitLog::addHeading` which always adds a new heading if there isn’t one with equal text. The timestamp headings have the unit as a suffix so it always adds extra headings rather than replacing them.

Some possible options:
- Add timestamps column deduplication to CODAL (at least before logging starts, not so clear what to do after)
- Move the default of seconds into CODAL and accept that calling includeTimestamp more than once makes a mess
- Avoid calling setTimeStamp in includeTimestamp until just before logging at the MakeCode level and accept that calling includeTimestamp more than once makes a mess
- ...?

**Expected behavior**
Setting the timestamp at start-up should replace any default timestamp column.

**Screenshots**
See above.

**micro:bit version (please complete the following information):**

V2

**Comment by microbit-matt-hillsdon** [comment]
This situation also means that `datalogger.includeTimestamp(FlashLogTimeStampFormat.None)` has no effect.

**Comment by finneyj** [comment]
Hmm... Thanks @microbit-matt-hillsdon.

This doesn't look ideal... I think adding a new column is probably right if the user changes timestamp format half way through the log, but doing this at the start is just confusing. Especially if there's a default being set.

I could look at an optimisation on the CODAL side to ensure no more than one timestamp is ever added BEFORE any data is logged? Also could fix the bug to remove the column if no timestamp is requested - even is this is after a default has been set?

What do you think @jwunderl ?

**Comment by abchatra** [comment]
@finneyj that sounds right to me.

**Comment by microbit-carlos** [comment]
I believe this has been deployed to the latest beta already.

**Comment by abchatra** [comment]
This is fixed.

**Comment by abchatra** [comment]
@microbit-matt-hillsdon please try latest and let us know

**Comment by microbit-matt-hillsdon** [comment]
Just checked and the "set timestamp" block is now working as I expect on live and beta 🎉
