### ISSUE TITLE
'Play sound [  ]until done' blocks the program from running indefinitely on iPad

### ISSUE THREAD

**Issue by kiki-lee** [microsoft/pxt-microbit#4212]
**Describe the bug**
When using iPad, adding 'play sound [ ] until done' doesn't play, then stops the program at that point.
![image](https://user-images.githubusercontent.com/1633958/122601138-b42ac000-d025-11eb-8e78-66428db1e542.png)

**Expected behavior**
Sound should play and program should continue when it's finished.

**Tablet (please complete the following information):**
 - Device: [iPad Pro]
 - OS: [ iOS14.6]
 - Browser [Chrome]
 - Version [91.0.4472.80]

**Comment by jwunderl** [comment]
Also repros on mac safari14.0.1
