### ISSUE TITLE
Disable Immersive Reader in Offline

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4213]
Right now the Immersive Reader buttons are all enabled when you're offline.
Clicking them does nothing.
We should explicitly disable or hide them when you are offline.
![ImmersiveReaderOffline](https://user-images.githubusercontent.com/22108954/122601342-fd7b0f80-d025-11eb-8225-8522677b5c69.png)

**Comment by abchatra** [comment]
Throw an error if the internet is not available.
