### ISSUE TITLE
Don't show this again doesn't work for offline

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4215]
The "Don't show this again" toggle in the Download confirmation dialog doesn't seem to do anything when using the electron app offline.
Repro:
- Click to Download as File
- Toggle "Don't show again" in download confirmation
- Make some changes to project
- Click to Download as File
- You see the Download Confirmation dialog again
![DownloadDontShowAgain](https://user-images.githubusercontent.com/22108954/122602036-07e9d900-d027-11eb-859e-66826b5465fa.png)

**Comment by riknoll** [comment]
download as file always shows the dialog, it was intended to be the "escape hatch" to make it show up again

**Comment by abchatra** [comment]
Can we not show this if this comes through path? It is confusing.

**Comment by riknoll** [comment]
@abchatra what about the shared device scenario? this was the way to consistently get the dialog to show up
