### ISSUE TITLE
TextEncoder is not defined in the Microbit windows app

### ISSUE THREAD

**Issue by aznhassan** [microsoft/pxt-microbit#4220]
**Describe the bug**
Using the data logger extension in the Makecode for Microbit windows app results in a "TextEncoder is not defined" error.

**To Reproduce**
1. Load beta in the Makecode for Microbit windows app
2. Download the data logger extension
3. Use the `log data` block to log the device acceleration in the x and y
4. Hit the play button on the simulator
5. Note the message: `Program Error: 'TextEncoder' is not defined`
6. The simulator will be greyed out as well

**Expected behavior**
If you run the same program in the browser at makecode.microbit.org/beta you'll see that there is no "TextEncoder" error and the data is logged as expected. You also "Show Console" simulator button as well.

**Screenshots**
![MakeCode-for-micro-bit-2021-06-1](https://user-images.githubusercontent.com/6496798/122605360-2f8f7000-d02c-11eb-985b-49c957f24b61.gif)

**micro:bit version (please complete the following information):**
makecode.microbit.org version:  3.1.95
Microsoft MakeCode version:  6.13.57
microbit runtime version:  v2.2.0-rc6
codal-microbit-v2 runtime version:  v0.2.29

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]
This is not hardware related

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 19043.1052
 - Browser Makecode for Microbit app
 - Version Unclear

**Comment by jwunderl** [comment]
fix should be https://github.com/microsoft/pxt-microbit/pull/4219
