### ISSUE TITLE
Microbit offline app : It shows blank when clicking "Hello JavaScript" twice

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4235]
**Describe the bug**
**Microbit offline app** : It shows blank when clicking "**Hello JavaScript**" **twice**

**Steps to reproduce the behavior**
1.Download Microbit offline app: https://makecode.com/api/release/microbit/v3.1.95/win64
2.Blocks To JavaScript------->**Hello JavaScript**------>Show Instructions
3.Retrun to homepage and click it again

**Actual behavior**
**Microbit offline app** : It shows blank when clicking "**Hello JavaScript**" **twice**
![4](https://user-images.githubusercontent.com/59192069/123188755-280a1400-d4cf-11eb-807b-687533a6a38d.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.95
3.Microsoft MakeCode version: 6.13.57

**Comment by Sheila111** [comment]
All instructions under "**Blocks To JavaScript**" have the same issue.

**Comment by abchatra** [comment]
This is fixed in offline app 
https://makecode.com/api/release/microbit/v4.0.10/win64

**Comment by abchatra** [comment]
@Sheila111 please verify.

**Comment by Sheila111** [comment]
@abchatra It has been fixed.
