### ISSUE TITLE
Update docs for WebUSB

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4237]
Hey Galen,
Can you update the download docs for the micro:bit?

- [ ] Add information about using WebUSB:
    - https://makecode.microbit.org/device/usb
    - https://makecode.microbit.org/device/usb/windows-edge

Here's a gif in case it's helpful 
![WebUSB](https://user-images.githubusercontent.com/22108954/123206347-615f6700-d470-11eb-9d98-41c31a9673ee.gif)

**Comment by abchatra** [comment]
@ganicke is this on your radar?
