### ISSUE TITLE
Beta has While False block

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4240]
![image](https://user-images.githubusercontent.com/31242877/123248239-9a82f000-d4df-11eb-8b99-a3fbdaa06c72.png)

This should be While True as in current makecode release

**Comment by abchatra** [comment]
This change is by design. Students are dropping the while <true> which hangs the microbit as it is busy loop. Idea is they have add a condition if necessary or use a break block, both are teaching momments..

**Comment by microbit-mark** [comment]
For reference, the original request for this was in MakeCode Arcade https://github.com/microsoft/pxt-arcade/issues/1849 and has been propagated to the other editors.
