### ISSUE TITLE
Functions with Array Parameter - doesn't like images

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4241]
For some reason, this code errors out - 

function showSomething (list: any[]) {
    for (let value of list) {
        value.showImage(0)
        basic.pause(200)
    }
}
showSomething([images.iconImage(IconNames.Heart), images.iconImage(IconNames.Happy), images.iconImage(IconNames.Ghost)])

But number and text arrays seem to work - 

function doSomething (list: any[]) {
    for (let value of list) {
        basic.showNumber(value)
    }
}
doSomething([0, 1, 2])

Checking the debugger, there's definitely something weird going on - 
![image](https://user-images.githubusercontent.com/22108954/123292235-b4183d80-d4c7-11eb-9749-8728e424a25e.png)

**Comment by Jaqster** [comment]
Oh, also there's some funky decompilation issues going on...
![image](https://user-images.githubusercontent.com/22108954/123294289-91872400-d4c9-11eb-9570-df5890c5bf40.png)

**Comment by abchatra** [comment]
I can repro this.  Following works
```javascript 
let list = [images.iconImage(IconNames.Heart), images.iconImage(IconNames.Yes)]
for (let value of list) {
    value.showImage(0)
    basic.pause(100)
}
```

But encapsulating the same code in function doesn't work

```javascript
function doSomething (list: any[]) {
    for (let value of list) {
        value.showImage(0)
        basic.pause(100)
    }
}
let list: Image[] = []
list = [images.iconImage(IconNames.Heart), images.iconImage(IconNames.Yes)]
doSomething(list)

```

**Comment by riknoll** [comment]
This is specific to images, which iirc are a special type in the compiler. Will investigate.

For reference, this code runs fine:

```typescript
function doSomething(list: any[]) {
    for (let value of list) {
        value.move(1);
        basic.pause(100)
    }
}

let list: game.LedSprite[] = [];
list = [game.createSprite(2, 2), game.createSprite(1, 1)]

doSomething(list)
```

**Comment by riknoll** [comment]
Minimal repro: 

```ts
let x: any = images.iconImage(IconNames.Heart)
x.showImage(0);
```

**Comment by riknoll** [comment]
The PR fixes this in blocks, but doesn't fix the TS issue. I don't think there is much we can do to fix the TS; I think the only proper fix would be to tear the image stuff out of the compiler so that it's no longer a special type.

**Comment by riknoll** [comment]
not really sure what the implications of that would be... @mmoskal

**Comment by riknoll** [comment]
related to https://github.com/microsoft/pxt-arcade/issues/2161

**Comment by mmoskal** [comment]
This is because of https://github.com/microsoft/pxt-arcade/issues/1436 (just like @riknoll is saying)

You could wrap the native C++ Image type in a TypeScript class and not ever show the native Image to the user. It would have some perf implications, hard to say how much.

Implementing real vtables in C++ classes is quite a bit of tricky compiler work.
