### ISSUE TITLE
Chromebook copy/paste block shows an error

### ISSUE THREAD

**Issue by livcheerful** [microsoft/pxt-microbit#4245]
**Describe the bug**
When copy/pasting a block, an error toast shows up when pasting the block, but the block pastes correctly. The error says "Oops, don't know how to load this file!"

**To Reproduce**
1. Select a block, Ctrl-C
2. Ctrl-V
3. See that the block appears, but also an error

**Screenshots**
![image](https://user-images.githubusercontent.com/18712271/123309802-39a4e900-d4da-11eb-92cd-943c90f9f05b.png)

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome

**Comment by abchatra** [comment]
No repro.
