### ISSUE TITLE
BLE flash to V2 from the iOS micro:bit app of files from MakeCode beta fails

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#4246]
**Describe the bug**
With the released mico:bit app, Bluetooth flashing a MakeCode beta hex to a V2 using drops the micro:bit into the bootloader.

It's OK with V1 and OK with files created on MakeCode live.

**To Reproduce**
1. Flash a hex from MakeCode beta to V2 using the app.

**Expected behavior**
Flashing works.

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]
V2

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - 
![image](https://user-images.githubusercontent.com/989126/123309742-341cc280-d51d-11eb-9f4d-24c22412e2c1.png)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by martinwork** [comment]
Created https://github.com/lancaster-university/codal-microbit-v2/issues/134

**Comment by abchatra** [comment]
Should be fixed now.
