### ISSUE TITLE
Fun with Radio Content issue 

### ISSUE THREAD

**Issue by ElizabethRiffle** [microsoft/pxt-microbit#4247]
In the first few steps of the Fun with Radio tutorial, the instructions are to simply send a message (without specifying what the message is). On step 5 it talks about a ":)" message. It confusing to me that we switched from generic to specific message and think we should change that.

**Comment by abchatra** [comment]
@ElizabethRiffle Add screenshots if you can.

**Comment by abchatra** [comment]
@anzhou5 is this fixed?

**Comment by anzhou5** [comment]
@abchatra thanks for the reminder! Looking into it now

**Comment by anzhou5** [comment]
Tutorial in question doesn't seem to be live anymore. No action needed
