### ISSUE TITLE
Green Screen causes screen shake

### ISSUE THREAD

**Issue by aznhassan** [microsoft/pxt-microbit#4249]
**Describe the bug**
Enabling green screen and move around the editor area by dragging with your mouse. The scrollbar on the right of the screen will repeatedly and quickly disappear causing all the elements left of the scrollbar to shake left and right. This is even worse if you use the console simulator (via the data logger for example) which causes the whole screen to shake.

**To Reproduce**
1. Go to makecode.microbit.org/beta
2. Open a project (new or old)
3. Enable `Green Screen` in the settings
4. Drag around the block space and see the right scroll bar disappear and reappear
5. Optionally use the data logger extension with the `log data` block
6. Open up the console simulator and see the entire screen shake since the scrollbars on the right and bottom now flash in and out of existence.

**Expected behavior**
The scrollbar on the right and bottom should stay present even when green screen mode is enabled.

**Screenshots**
![Microsoft-MakeCode-for-micro-bit](https://user-images.githubusercontent.com/6496798/123314036-f39e5400-d4de-11eb-820c-4ccb576d7cde.gif)

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
Not hardware related

**Desktop (please complete the following information):**
 - OS: Windows 10 19043.1052
 - Browser Edge
 - Version 91.0.864.48

**Additional context**
versione makecode.microbit.org:  4.0.4
versione Microsoft MakeCode:  7.0.5
versione microbit runtime:  v2.2.0-rc6
versione codal-microbit-v2 runtime:  v0.2.29

**Comment by abchatra** [comment]
This seems to be fixed now in edge. I can't repro. If you can please reopen
