### ISSUE TITLE
[Windows App] Projects don't show up/open immediately on creation

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#4250]
**Describe the bug**
![bug-create-wapp](https://user-images.githubusercontent.com/34112083/123314301-45df7500-d4df-11eb-86c7-659b772f38a9.gif)

Appears to happen pretty consistently with every other project

**To Reproduce**
1. Open the micro:bit Windows app
2. Create a project
3. Exit this project and create another project
4. See that the second project doesn't load/appear
5. Exit the app and reopen, the new project should be there

**Comment by abchatra** [comment]
@livcheerful take a peek?

**Comment by livcheerful** [comment]
@shakao did you use /@beta in extensions to get the editor into beta or something else? I can't make my windows app do this D:

**Comment by shakao** [comment]
yep, i used the extensions dialog! hmm.... it does seem like it could be a perf thing; it repros very easily when i'm on a teams call, but i also saw it when i wasn't running teams

**Comment by livcheerful** [comment]
OOooo hm I will try messing with perf

**Comment by abchatra** [comment]
Won't fix as we already shipped the update
