### ISSUE TITLE
Microbit offline app :No image on "Spark Videos" when offline

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4251]
**Describe the bug**
Microbit offline app :No image on "**Spark Videos**" when offline

**Steps to reproduce the behavior**
1.Download Microbit offline app: https://makecode.com/api/release/microbit/v3.1.95/win64
2.**Disconnect** the internet
3.Courses----->**Spark Videos**

**Actual behavior**
Microbit offline app :No image on "**Spark Videos**" when **offline**
![image](https://user-images.githubusercontent.com/59192069/123389793-d5168680-d5cc-11eb-9bc2-4e92697ada07.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.95
3.Microsoft MakeCode version: 6.13.57

**Comment by abchatra** [comment]
This is fixed.
