### ISSUE TITLE
misleading name of @acceleration (mg)" block

### ISSUE THREAD

**Issue by semionenkov** [microsoft/pxt-microbit#4256]
Hello, 
I would like to ask to change a name of the block "acceleration (mg)" because it's misleading and does not reflect a user meaning  of the value returned by the sensor.
Acceleration is a characteristic of changing speed, The sensor returns data about orientation of micro:bit, static.
It should be something like slope, because it's actually a measure of angle between a micro:bit axis and horizontal plane.
I assume, it's about sin of the angle*1000.

**Comment by abchatra** [comment]
The sensor is known as accelerometer and the output of it is acceleration. This is simple for students to understand. 
https://microbit.org/get-started/first-steps/sensors/

This is also legacy  and we don't intend to change it.
