### ISSUE TITLE
Radio examples need a set radio group block for V1/V2 compatibility

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4261]
As a workaround for #3421, MakeCode tutorials need a set group block 

For example https://makecode.microbit.org/projects/multi-dice would not work between board variants.

An alternative, until the issue is resolved is to note that the group must be set if you are working with both board variants, as described in https://support.microbit.org/support/solutions/articles/19000121980-using-radio-with-micro-bit-v1-and-micro-bit-v2

**Comment by abchatra** [comment]
Can we change the tutorial to use block setgroup always
