### ISSUE TITLE
Microbit offline app :Turtle can’t open when offline

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4266]
**Describe the bug**
Microbit offline app :**Turtle** can’t open when **offline**

**Steps to reproduce the behavior**
1.Download Microbit offline app: https://makecode.com/api/release/microbit/v3.1.95/win64
2.Disconnect the internet
3.Turtle--->**Square**
4.Turtle--->**Sprial**
5.Turtle--->**Scanner**

**Actual behavior**
Microbit offline app :**Turtle** can’t open when **offline**
**Square:**
![image](https://user-images.githubusercontent.com/59192069/124872504-efeaf100-dff7-11eb-998c-2c2e20baa498.png)
**Sprial**/**Scanner**:
![image](https://user-images.githubusercontent.com/59192069/124872563-0002d080-dff8-11eb-9354-4ca6b8a705a6.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.95
3.Microsoft MakeCode version: 6.13.57

**Comment by Sheila111** [comment]
**Micro:Coin** (Radio Games) , **Kitronik RC Car Hack** (Toys) can’t load the code either when **offline**. 
![image](https://user-images.githubusercontent.com/59192069/124899536-cee3c980-e012-11eb-9dab-59c75d4d1065.png)

**Comment by riknoll** [comment]
This behavior is expected, as all of those tutorials/examples rely on extensions that don't come bundled with the editor. We should probably handle this a little more elegantly, though!

**Comment by abchatra** [comment]
Won't fix as offline doesn't have access to extensions.
