### ISSUE TITLE
Extension's language will be English

### ISSUE THREAD

**Issue by matsujirushi** [microsoft/pxt-microbit#4274]
**Describe the bug**
In a Japanese environment, when I load the Grove Extension and then reload the browser, the Extension turns to English.
Please see [this video](https://youtu.be/9Qkvi5jNQh4).

**To Reproduce**
1. Run a browser(chrome) in secret-window and open MakeCode for micro:bit site.
2. Create a project.
3. Add `Grove` extension.
4. Reload a browser.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome 91.0.4472.124

**Additional info.**
 - [Translation of Grove and microbit extensions (Makecode)](https://forum.seeedstudio.com/t/translation-of-grove-and-microbit-extensions-makecode/259557)

**Comment by riknoll** [comment]
Thank you for the very helpful video!
