### ISSUE TITLE
Immersive reader can't be launched in offline app

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#4281]
**To Reproduce**
1. Install offline app 
https://makecode.com/api/release/microbit/v4.0.10/win64
2. Launch 'flashing heart' tutorial
3. Click on immersive reader
4.  See error

**Screenshots**]
![image](https://user-images.githubusercontent.com/6107272/126743471-0fd8643b-c14a-47f9-a98a-5f4693ab0002.png)

**Comment by livcheerful** [comment]
fixed
