### ISSUE TITLE
Tutorials for the v2 are called "new micro:bit"

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#4285]
This might be confusing as a kid might have just bought the v1 microbit. 

Is it better to call micro:bit V2? 

**Screenshots**
![image](https://user-images.githubusercontent.com/6107272/126821913-11f15925-4d96-45d8-84b4-00d071b400f8.png)

**Comment by anzhou5** [comment]
@abchatra, I named them "new" micro:bit after Jacqueline reached out to Giles from micro:bit who said "We usually refer to the board as ‘the new micro:bit’ or ‘the micro:bit with sound’, and use the ‘V2’ label in the context of hardware accessory and software compatibility (e.g. blocks listed under ‘micro:bit (V2)’ in MakeCode)."

What are your thoughts?

**Comment by abchatra** [comment]
@jaustin for opinion here.

**Comment by Jaqster** [comment]
Guidance from the Micro:bit Foundation is to use "new micro:bit" instead of "micro:bit v2"

**Comment by microbit-mark** [comment]
I think this might be confusing out of context. The images of the micro:bits in the tutorial do not have the notched edge connector and a 'new' micro:bit to a child could be a V1 or V2 if they have not used either before.

I would suggest we use `Tutorials for the new micro:bit (V2)` as people contacting support use the version number in the majority of cases now.

**Comment by pelikhan** [comment]
Eventually the "new micro:bit" won't be so new and you'll have to reword materials to refer it to as the micro:bit. IMO, it's easier to consistently call it V2 everywhere.

**Comment by pelikhan** [comment]
>  The images of the micro:bits in the tutorial do not have the notched edge connector and a 'new' micro:bit to a child could be a V1 or V2 if they have not used either before.

@abchatra that's a fair point, can we tweak the images to add notches?

**Comment by microbit-giles** [comment]
We'd be happy with 'Tutorials for the new micro:bit (V2)' as the heading.

I agree the micro:bits should have notches.

**Comment by anzhou5** [comment]
> > The images of the micro:bits in the tutorial do not have the notched edge connector and a 'new' micro:bit to a child could be a V1 or V2 if they have not used either before.
> 
> @abchatra that's a fair point, can we tweak the images to add notches?

@soniakandah for visibility on this

**Comment by anzhou5** [comment]
@pelikhan, @microbit-giles, @microbit-mark, @abchatra - I opened a request for notches: https://github.com/microsoft/pxt-microbit/issues/4306

**Comment by soniakandah** [comment]
Added notches, images can be found here: https://github.com/microsoft/pxt-microbit/issues/4181
