### ISSUE TITLE
Feature Request: Language selector for code printouts

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4291]
When selecting to print the code from MakeCode, the Javascript is listed, followed by the MakeCode Python 'main.py'.

If you are only working in MakeCode Python, you might not want to print the Javascript too and it's unclear why this is printed first or at all.

It's also not clear what `main.py` is in this context. It would be better to have section headings for `Javascript` and 'MakeCode Python` in the printout and/or have a selector to allow people to pick which language they want the printout in.

https://user-images.githubusercontent.com/31242877/126995766-b06e2df6-ca51-4cbb-b745-ee4fab247b20.mp4

**Comment by abchatra** [comment]
This is a good one. We just should print the language like python or javascript and nothing else.
