### ISSUE TITLE
Some homepage carousels broken in non-english locales

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#4300]
**Describe the bug**

it looks like the translated versions of homepage galleries broke after microsoft/pxt-microbit#4288 (this is an issue on either our upload or crowdin side, not in the pr)

![image](https://user-images.githubusercontent.com/5615930/127445605-b3eed39c-15e8-426d-8fac-753f310523b3.png)

In some of the galleries, it's dropping the `---` separators and instead marking the last lines as headers; e.g. https://crowdin.com/translate/kindscript/5124/en-fr?filter=basic&value=3

![image](https://user-images.githubusercontent.com/5615930/127418402-874e4ab5-e8e2-4bb1-9789-fffcf44c7d38.png)

where others are fine https://crowdin.com/translate/kindscript/10292/en-fr?filter=basic&value=3

![image](https://user-images.githubusercontent.com/5615930/127445832-a2868a11-2562-4935-9f66-3d76c04abdc5.png)

I'm gonna put up some a few whitespace only changes in the files currently broken on crowdin to see if it will force through a reupload and fix it, a few of these will be broken for 24hrs at least though.

**To Reproduce**
1. Go to microbit homepage in french
2. see error

**Comment by abchatra** [comment]
This is fixed.
