### ISSUE TITLE
Live Coding empty tiles

### ISSUE THREAD

**Issue by anzhou5** [microsoft/pxt-microbit#4305]
**Describe the bug**
The Live Coding carousel has no tiles in it

**Screenshots**
![image](https://user-images.githubusercontent.com/42353804/127542842-1e9cc893-fa87-4e6c-9c9a-a8f09dae014e.png)

**To Reproduce**
1. Go to 'https://makecode.microbit.org/'
2. Scroll down to 'Live Coding' (under the new micro:bit tutorials)
3. See error

**Expected behavior**
I'd imagine you would need to either populate the tiles or remove the title altogether.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 20H2

**Comment by jwunderl** [comment]
This was due to a spacing issue fixed here: https://github.com/microsoft/pxt-microbit/pull/4298 (but then reverted with the other changes as well) -- just need to wait for cache to clear now.
