### ISSUE TITLE
Micro:bit V2 tutorial tiles need notches in the images

### ISSUE THREAD

**Issue by anzhou5** [microsoft/pxt-microbit#4306]
**Describe the bug**
The images for the V2 tutorials have smooth bottoms rather than notches.

**To Reproduce**
1. Go to https://makecode.microbit.org/
2. Scroll down to Tutorials for the new micro:bit (V2) tutorials

**Expected behavior**
The images should reflect the V2 design and have notches on the bottom

**Screenshots**
![image](https://user-images.githubusercontent.com/42353804/127543526-c387fc67-6e05-4e50-a925-77353dadf6d7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 20H2

**Comment by kaithdd** [comment]
Excuse me,do you have a .hex doc to make sure Micro:bit V2 successfully connect Scratch

**Comment by microbit-mark** [comment]
@kaithdd You can find information on using scratch with the micro:bit at https://scratch.mit.edu/microbit. Get in touch via support.microbit.org if you have any issues

**Comment by kaithdd** [comment]
> @kaithdd You can find information on using scratch with the micro:bit at https://scratch.mit.edu/microbit. Get in touch via support.microbit.org if you have any issues

Thank you for your reply. Due to regional restrictions, I can't log in to the website. I'm thinking about other ideas. I hope to have direct download resources on GitHub.

**Comment by soniakandah** [comment]
Added the notches, images can be found here: https://github.com/microsoft/pxt-microbit/issues/4181
