### ISSUE TITLE
Every loop does not behave as expected when a pause is used

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4308]
The following program would be expected to light the LED for 4s every 5s, but it lights the LED for 4s, then pauses for 5s. The loop does not execute every 5s.

![image](https://user-images.githubusercontent.com/31242877/127878909-cb2159b6-3975-4cfb-82d2-ecf90bb9d96a.png)

```
loops.everyInterval(5000, function () {
    led.toggle(0, 0)
    basic.pause(4000)
    led.toggle(0, 0)
})
```

**Comment by martinwork** [comment]
@jwunderl The fix https://github.com/microsoft/pxt-microbit/pull/4309 doesn't seem to have made it to beta yet.

AIUI, this spawns a fiber for the body of the loop at every iteration.
If the body takes longer than the interval, could this lead to multiple copies of the loop body running in parallel?
