### ISSUE TITLE
Data logging: New tab claiming WebUSB interface stops logging activity

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4310]
I know that connecting to WebUSB automatically is by design, but raising this to discuss, as it could be confusing when trying out data logging applications.

As an example:

1. Flash this program to a micro:bit

<img width="571" alt="image" src="https://user-images.githubusercontent.com/31242877/127985324-90c43393-6b76-4d2c-be2a-2ebfdec4cd3b.png">

https://makecode.microbit.org/_U6Dep001y0zh

2. Logging starts.
3. Open a new MakeCode program, the editor claims the WebUSB interface
4. Program and Logging restarts with no indication that this is the case

If data logging is triggered as part of the program, then changing tabs has the effect of stopping the activity eg 

<img width="572" alt="image" src="https://user-images.githubusercontent.com/31242877/127986264-da6ae8c1-3290-450f-9a18-57a2ee293423.png">

https://makecode.microbit.org/_ickPDr477P9r

I don't think this will affect a large number of people, but if you are multi-tasking in MakeCode and want to leave your program running on the device you would need to disconnect WebUSB

**Comment by abchatra** [comment]
I am not sure I understand the issue. Logging will continue irrespective of webusb is connected or not. Only view of the log in the MakeCode editor is impacted. 

You can open the excel and see all the logs.

**Comment by microbit-mark** [comment]
I think you're right. Logging does continue. I think I was expecting the serial indicator LED on the hardware to keep flashing when I move between tabs, but it does not. Perhaps we just need to be clear on that.

It looks like the program restarts as the LED screen cycles off and on.

Closing for now as I can't get a solid reproducer
