### ISSUE TITLE
Feature: Improve `round()` to allow user to define number of decimal places

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4314]
>  From https://support.microbit.org/a/tickets/46961(private)

>  There are many occasions where more control other than the full precision of the internal number representation or the enforced 2 decimal places of ‘show number’ is required e.g. serial output.
> 
> The existing “round()” function probably would be better named as “int()” as it only rounds to the nearest integer value. This would enable the “roundWithprecision()” function available in JavaScript to be called “round(number,places)” as a block.

**Comment by abchatra** [comment]
No plans to implement.
