### ISSUE TITLE
Add month to data log file output .csv

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4316]
> From https://support.microbit.org/a/tickets/46941 (private)

>  The log file name is in the format “microbit-data-DD-YYYY-” followed by a time stamp & serial number.
> 
> There is no number for the month, so confusing as there are 12 months in a year, many share the same day numbers.
> 
> A better format would be to use “YYYY-MM-DD” so they can be identified in chronological order.

Download a file from the serial console view eg `microbit-data-05-2021-14-11-26-0100.csv` should be `microbit-data-2021-08-05-14-11-26-0100.csv`

**Comment by abchatra** [comment]
We should add month. Download log file has no month information. 
microbit-data-28-2022-10-43-13-0800.csv
