### ISSUE TITLE
Change web USB "Pair now" to button instead of link

### ISSUE THREAD

**Issue by halspeed** [microsoft/pxt-microbit#4317]
Web USB is a great new feature, but some teachers are overlooking the "Pair now" link in the following dialog box:
![image](https://user-images.githubusercontent.com/29285304/128358552-6ef27988-13a9-4381-896e-e33419051fe3.png)

Consider enhancing the visibility of "Pair now" by changing it to a button style like the "Done" button (white text on purple background).

Also, USB should be capitalized in the text box.

**Comment by jwunderl** [comment]
I hadn't noticed this was a bug, already fixed this in the first webusb flow clean up:
![image](https://user-images.githubusercontent.com/5615930/236894444-6918783a-4090-41e2-b267-39882fc3df6a.png)

put up a quick pr fixing the other side note here https://github.com/microsoft/pxt/pull/9503, good call out. closing~
