### ISSUE TITLE
Serial mode: chart cursor does not operate when chart is paused

### ISSUE THREAD

**Issue by microbit-josephine** [microsoft/pxt-microbit#4327]
**Describe the bug**
In serial mode, chart cursor does not operate when chart is paused

**To Reproduce**
1. Go to program https://makecode.microbit.org/_ePEK1YW0HcWH
2. Click on show console simulator
3. See how chart cursor works whilst running
4. pause simulator
4. See how chart cursor no longer appears.

**Expected behavior**
users may wish for the chart cursor to show up whilst the simulator is paused.

**Screenshots**
this is the box we wish to see even when not running:
<img width="383" alt="Screenshot 2021-08-11 at 09 57 02" src="https://user-images.githubusercontent.com/54458430/128991908-75bdc4b4-e0c9-4697-b4f3-640093ebda5c.png">

**Desktop (please complete the following information):**
 - OS:macOS
 - Browser chrome
 - Version 92.0.4515.131

**Additional context**
this issue was raised in a micro:bit support ticket https://support.microbit.org/a/tickets/47026

**Comment by abchatra** [comment]
This is simulator serial chart. If the simulator is paused there is no one to generate data. 

Device data chart will not stop if you stop the simulator.
