### ISSUE TITLE
Where is the projects folder?

### ISSUE THREAD

**Issue by iwanglian** [microsoft/pxt-microbit#4333]
I run the server ,and create project in local server ,but I cannot find any file in  `projects` folder. 
Where is the project  saved?

**Comment by jwunderl** [comment]
if you're using an up to date pxt, the default storage method for local serve was changed a while ago to match the website (to saving in browser locale storage). If you want to have them saved in the projects view, you can use the `ws=fs` query parameter, e.g. `https://localhost:3232/index.html?ws=fs` to override the default workspace and use file system storage instead (from here: https://github.com/microsoft/pxt/blob/49ff69d2e3367431246eccc7919e76bb3e7d2f3b/webapp/src/app.tsx#L4985)

**Comment by iwanglian** [comment]
Thanks.
And then, where is the cached .hex file of the project ?
