### ISSUE TITLE
Where is the cached .hex file of the project ?

### ISSUE THREAD

**Issue by iwanglian** [microsoft/pxt-microbit#4334]
if you're using an up to date pxt, the default storage method for local serve was changed a while ago to match the website (to saving in browser locale storage). If you want to have them saved in the projects view, you can use the `ws=fs` query parameter, e.g. `https://localhost:3232/index.html?ws=fs` to override the default workspace and use file system storage instead (from here: https://github.com/microsoft/pxt/blob/49ff69d2e3367431246eccc7919e76bb3e7d2f3b/webapp/src/app.tsx#L4985)

_Originally posted by @jwunderl in https://github.com/microsoft/pxt-microbit/issues/4333#issuecomment-900529480_

**Comment by iwanglian** [comment]
When I click the "Save" buttom, it show a dialog to download the hex file. Where  does the hex file store ?

**Comment by abchatra** [comment]
This is stored in the file system in the local box.
