### ISSUE TITLE
Feature: Load extension directly in MakeCode URL

### ISSUE THREAD

**Issue by halspeed** [microsoft/pxt-microbit#4341]
Is there a way to load an extension directly from Github in the URL, something like:

makecode.microbit.org/#package:github:kidspark/pxt-sparkbit

I can save a project URL with the extension loaded, but I'd rather load directly from Github if possible.

**Comment by abchatra** [comment]
You can have an empty project with the extension. It is same as deafault project.

**Comment by halspeed** [comment]
If I understand correctly, that's a project URL. If the extension gets updated, will the empty project use the latest version of the extension? I thought it would be safer to load the extension directly from the extension repo.

**Comment by abchatra** [comment]
Yes it will load the latest extension as long as the version of the extension is not hardcoded in the pxt.json.
