### ISSUE TITLE
In the MakeCode editor, editing the Javascript of a program with custom functions made with blocks that have an array as a parameter causes any custom function with an array parameter to grey-block

### ISSUE THREAD

**Issue by jernwerber** [microsoft/pxt-microbit#4348]
**Describe the bug**
In the MakeCode editor, editing the Javascript of a program with custom functions made with blocks that have an array as a parameter causes any custom function with an array parameter to grey-block.

**To Reproduce**

1. Create a new project in MakeCode.
2. Using blocks, create a custom function (Advanced > Functions > Make a Function...) has 1 array as a parameter.
3. Using blocks, create a custom function (Advanced > Functions > Make a Function...) has 1 number as a parameter. (Screenshot 1)
4. Switch to JavaScript view.
5. Go to the last line of the code and press Enter/Return to add a line. (Screenshot 2)
6. Switch back to blocks view. (Screenshot 3)

**Expected behavior**
Custom functions with array parameters should not be grey blocked.

**Screenshots**
Screenshot 1 (setup)
![image](https://user-images.githubusercontent.com/3218047/131160278-ad15756d-77ce-4525-abf2-567f8be1017c.png)
Screenshot 2 (1 new line added at the end of the code)
![image](https://user-images.githubusercontent.com/3218047/131160430-9bee32db-818d-441a-acd3-5abc5e1cf50b.png)
Screenshot 3 (in blocks view, function with array parameter is now grey blocked)
![image](https://user-images.githubusercontent.com/3218047/131160507-711821a5-9ec9-4f57-84a9-889ae3800bb1.png)

**micro:bit version (please complete the following information):**
Tested in MakeCode Editor (online) on 2021-08-27
makecode.microbit.org version:  4.0.11
Microsoft MakeCode version:  7.0.8
microbit runtime version:  v2.2.0-rc6
codal-microbit-v2 runtime version:  v0.2.32

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 92.0.4515.159 (Official Build) (64-bit)

**Additional context**

1. If you switch back to blocks view after step 4 without editing the code, the function remains the same (editable in blocks).
2. If you only add whitespace (e.g. spacebar or tab, in step 5) instead of something that changes the code, the function remains editable.
2. Using Javascript to define a function with an array parameter creates a grey block, even if the code is identical to a custom function created using blocks.

**Comment by riknoll** [comment]
Fixed by https://github.com/microsoft/pxt/pull/8729
