### ISSUE TITLE
Serial write raw data

### ISSUE THREAD

**Issue by cn-toven** [microsoft/pxt-microbit#4353]
**Is your feature request related to a problem? Please describe.**
I'm tring to use serial port of microbit to cotnrol a third module via uart, and it needs specific hex data to communicate with. I've tried "serial write number, serial write value, serial write string", none of them works.
I used "serial write number (72)", it sends out "0x37 0x32" actually, it's the asc code for each number. i want the raw data 72 be sent.
**Describe the solution you'd like**
serial write raw data (0x10 0xff 0x33 ... )
**Describe alternatives you've considered**
NO
**Additional context**
NO

**Comment by abchatra** [comment]
You can use serial.writeBuffer for this.
