### ISSUE TITLE
Request to add Javascript/blocks facility to check a device is connected to I2C

### ISSUE THREAD

**Issue by keble6** [microsoft/pxt-microbit#4356]
Javascript/blocks have no means of checking an I2C device is connected via ACK testing.

However you can manage device acknowledgement in the DAL https://github.com/lancaster-university/mbed-classic/blob/427f56863c9f9a9132a213ec583469dfc61c6244/api/I2C.h#L78 but this is not surfaced in the higher level languages.

Ground work covered in https://support.microbit.org/helpdesk/tickets/47455

**Comment by abchatra** [comment]
@keble6 you can create an extension to the same.

**Comment by keble6** [comment]
Good idea, thanks
