### ISSUE TITLE
Keyword search for data logging extension

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4357]
The data logging extension only appears in search when you use the words 'datalogger' or 'data'

![image](https://user-images.githubusercontent.com/31242877/132464704-c97150bb-0e0c-49f2-b030-895fecbe161c.png)

![image](https://user-images.githubusercontent.com/31242877/132464777-38a882ff-765c-40bd-bc91-ec1b4870e132.png)

Whilst it isn't listed in the top ten, it would be useful if we could add some more keywords to aid search eg

`data logging`, `data logger`, `log data`, and maybe `files`, `data science`, `serial` `filesystem`(for people who used to use this deprecated extension)

**Comment by pelikhan** [comment]
Add tutorials for it...

**Comment by aznhassan** [comment]
You can no longer search for terms with space in them in the extensions search box. Pressing space is the same as pressing enter and will initiate the search. Searching for both "data" and "logger" brings up the datalogger extension first among the result. Searching "logging" or "datalogging" does not bring up the right results. So there is still room for improvement.

**Comment by abchatra** [comment]
I am closing this as fixed for now.
