### ISSUE TITLE
Tutorial in Extension not loading as main.ts too large, but Extension works properly

### ISSUE THREAD

**Issue by AlasdairAtKitronik** [microsoft/pxt-microbit#4360]
**Describe the bug**
I have written an Extension for a new product which includes four MakeCode online tutorials. The Extension has been fully tested and works absolutely fine with complete functionality. However, when a tutorial is attempted to be opened, it always fails and pops up this error:
"Please check your internet connection and check the tutorial is valid."

To get more detail, I opened the console in Chrome to see what was going on:
```
[Deprecation] Application Cache API manifest selection is deprecated and will be removed in M85, around August 2020. See https://www.chromestatus.com/features/6192449487634432 for more details.
/#tutorial:e53216a0-9466-4517-3e5f-b2cd83675fc5:a_ReadBME688:1 Creating Application Cache with manifest https://makecode.microbit.org/---manifest
/#tutorial:e53216a0-9466-4517-3e5f-b2cd83675fc5:a_ReadBME688:1 Application Cache Checking event
pxtapp.js:1 Browser: chrome 92.0.4515.159 on windows
main.js:1 cloud init
pxtapp.js:1 workspace: browser
pxtapp.js:1 PouchDB adapter: idb
/#tutorial:e53216a0-9466-4517-3e5f-b2cd83675fc5:a_ReadBME688:1 Application Cache Error event: Invalid or missing manifest origin trial token: https://makecode.microbit.org/---manifest
text:1 Failed to load resource: the server responded with a status of 404 ()
pxtapp.js:1 github proxy error: Bad HTTP status code: 404 at https://pxt.azureedge.net/api/gh/kitronikltd/pxt-kitronik-air-quality/master/text?cdn=20210908; message: {"message":"maximum file size in package is ~64k; file main.ts; size 84013"}
api.github.com/repos/kitronikltd/pxt-kitronik-air-quality/git/refs/tags/master?rnd=0.13146145047135538:1 Failed to load resource: the server responded with a status of 404 ()
pxtapp.js:1 Downloading kitronikltd/pxt-kitronik-air-quality/master -> 598a2ef23b19d0011445882070c018ff4300d35f
text:1 Failed to load resource: the server responded with a status of 404 ()
pxtapp.js:1 github proxy error: Bad HTTP status code: 404 at https://pxt.azureedge.net/api/gh/kitronikltd/pxt-kitronik-air-quality/master/text?cdn=20210908; message: {"message":"maximum file size in package is ~64k; file main.ts; size 84013"}
pxtapp.js:1 GET https://api.github.com/repos/kitronikltd/pxt-kitronik-air-quality/git/refs/tags/master?rnd=0.4231818094962736 404
(anonymous) @ pxtapp.js:1
e.Util.httpRequestCoreAsync @ pxtapp.js:1
h @ pxtapp.js:1
i @ pxtapp.js:1
r @ pxtapp.js:1
s @ pxtapp.js:1
g @ pxtapp.js:1
githubLoadPackageAsync @ pxtapp.js:1
loadPackageAsync @ pxtapp.js:1
async function (async)
loadPackageAsync @ pxtapp.js:1
loadPackageAsync @ main.js:1
y @ pxtapp.js:1
(anonymous) @ pxtapp.js:1
t.cacheProjectDependenciesAsync @ pxtapp.js:1
async function (async)
t.cacheProjectDependenciesAsync @ pxtapp.js:1
q @ main.js:1
createProjectAsync @ main.js:1
async function (async)
createProjectAsync @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
startTutorialAsync @ main.js:1
startActivity @ main.js:1
pe @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
(anonymous) @ main.js:1
DevTools failed to load source map: Could not load content for https://pxt.azureedge.net/commit/c861b42aeb5461ff95ab4e995cba06cf21e32366/dapjs.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
trg-microbit.userpxt.io/---simulator#sim-frame-0090464199262818210.5765563183126774:2 [Deprecation] Application Cache API manifest selection is deprecated and will be removed in M85, around August 2020. See https://www.chromestatus.com/features/6192449487634432 for more details.
pxtsim.js:1 Simulator ServiceWorker registration successful with scope:  https://trg-microbit.userpxt.io/
pxtapp.js:1 Error: Cannot find text for package 'f8101f7d-081a-4cbc-856e-bd5822b8b5c9' in the workspace.
    at main.js:1
    at async le.loadHeaderAsync (main.js:1)
    at async le.createProjectAsync (main.js:1)
e.reportException @ pxtapp.js:1
e.reportException @ pxtapp.js:1
(anonymous) @ main.js:1
Promise.catch (async)
startTutorialAsync @ main.js:1
startActivity @ main.js:1
pe @ main.js:1
(anonymous) @ main.js:1
Promise.then (async)
(anonymous) @ main.js:1
pxtapp.js:1 {tutorialId: "e53216a0-9466-4517-3e5f-b2cd83675fc5:a_ReadBME688"}
pxtapp.js:1 warning: Please check your internet connection and check the tutorial is valid.
---serviceworker:1 Received disconnect for undefined
```
In amongst all that is this error message:
```
github proxy error: Bad HTTP status code: 404 at https://pxt.azureedge.net/api/gh/kitronikltd/pxt-kitronik-air-quality/master/text?cdn=20210908; message: {"message":"maximum file size in package is ~64k; file main.ts; size 84013"}
```
To me, this looks like it is saying the main.ts file in my extension is too large for MakeCode to run, however, as previously mentioned, the extension works without any issues when brought into MakeCode. It seems there must be an issue with how MakeCode sets limits for file sizes specifically in tutorials.

This is the GitHub repo for the extension:
https://github.com/KitronikLtd/pxt-kitronik-air-quality

**To Reproduce**
1. Follow this link to the tutorial: https://makecode.microbit.org/#tutorial:github:kitronikltd/pxt-kitronik-air-quality/a_ReadBME688
2. Turn on the console to find out more details about the error message.
3. See error

**Expected behavior**
The tutorial should run without failing at the start, taking the user through a code build etc.

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Edge
 - Version: Chrome - 92.0.4515.159, Edge - 93.0.961.38

**Additional context**
The suggestion to simply get round this by reducing the file size of main.ts down to <64k is not possible in this scenario. The extension has already been heavily reduced in functionality in order to actually run on the micro:bit and as such is down to the bare minimum of functionalty for the product it supports. As it works on the micro:bit, it really should be able to run with the tutorials.

**Comment by AlasdairAtKitronik** [comment]
### Additional Details
I have tried adding just the extension to MakeCode (as it has just been through the micro:bit approval process) but after first telling me it couldn't find any extensions matching what I searched, it also gives me the same error as with the tutorials in the console: 
```
pxtapp.js:1 Error: Bad HTTP status code: 404 at https://pxt.azureedge.net/api/gh/KitronikLtd/pxt-kitronik-air-quality?cdn=20210909; message: {"message":"maximum file size in package is ~64k; file main.ts; size 84013"}
    at pxtapp.js:1
    at async T (pxtapp.js:1)
    at async Promise.all (/index 0)
```

This extension has been throroughly tested in both a fully up to date offline MakeCode environment, and through the MakeCode/GitHub integration for creating extensions and in its current state has worked with no problems.
The extension works, so surely it should pull in? 

The product is about to go live, so really needs the extension to be available ASAP.
@pelikhan @abchatra Please could you look at this and see what needs to be changed in MakeCode to allow the extension to run? Thanks.

**Comment by abchatra** [comment]
Maximum size has been increased to 128k.

**Comment by abchatra** [comment]
Fixed
