### ISSUE TITLE
Translation bug in Smiley Buttons tutorials

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4362]
In Norwegian Bokmal language, the Input category is not rendered in the toolbox

![Image 2021-09-08 at 1 12 09 pm](https://user-images.githubusercontent.com/31242877/132507073-6ec502ec-a600-428e-a155-ce91609c4f7f.jpg)

**Comment by abchatra** [comment]
@jwunderl fyi

**Comment by abchatra** [comment]
This is likely a incorrect translation in the crowdin.

**Comment by ganicke** [comment]
This looks like it's fixed now. I'll close this one.

![image](https://user-images.githubusercontent.com/27789908/141596173-f21085c1-e740-4895-9813-fd68c2b57c48.png)
