### ISSUE TITLE
Cannot open external links from the extension  https://github.com/KittenBot/pxt-neomatrix

### ISSUE THREAD

**Issue by hogan96** [microsoft/pxt-microbit#4363]
https://github.com/KittenBot/pxt-neomatrix
The extension 'neomatrix‘ we made has a button to jump to external links, it can quickly create image for neopixel matrix which is very convenient. But after the platform is updated, it seems to be unavailable.
help please ~
![neomatrix](https://user-images.githubusercontent.com/40231510/132620008-dda1b1e3-7023-470b-9ce7-8040005939fb.png)
![neomatrix2](https://user-images.githubusercontent.com/40231510/132620098-a9f5395d-5839-4fa8-8aa9-9ab73a34c4d3.png)

**Comment by abchatra** [comment]
Editor extension is an experimental features. We don't guarantee support for experimental feature. We have taken down that feature as it was not working well.
