### ISSUE TITLE
Feature: Allow text fields to be draggable in column headers

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4367]
It would be useful to be able to move the column headers, maybe even the columns around in the data logger arrays where we might want to rearrange the order that the data is logged.

![Screen Recording 2021-09-10 at 03 02 01 pm](https://user-images.githubusercontent.com/31242877/132865751-1e7f8d44-79d5-4b05-8ad4-e4e267c5d566.gif)

It is possible to replace the headers with a text field, but not that intuitive. It is also possible to re-order the values for the data that is logged, eg moving a light level block around, but that would mean re-labling the headers

**Comment by abchatra** [comment]
This block is going to be changed.

**Comment by abchatra** [comment]
This is fixed. We don't have array no more.
