### ISSUE TITLE
Feature: Data logging start/stop block

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4368]
Currently, you have to use something like a condition if you want a way to start and stop logging on a micro:bit:

![image](https://user-images.githubusercontent.com/31242877/132866821-1ecfd7b0-70ba-4c9c-8228-7600bbeeb244.png)

It would be useful to have a `start logging` and `stop logging` block

**Comment by abchatra** [comment]
Same logic applies for all different types of output. For example: Serial write on\off. Digital write on\off. 
Adding a boolean variable is the right way to check a condition if the logging is required.

No plans to implement
