### ISSUE TITLE
Project Idea: Covid-19: safety wearable device , face touch early warning system using BBC: Microbit.

### ISSUE THREAD

**Issue by akshitagupta15june** [microsoft/pxt-microbit#4370]
**Is your feature request related to a problem? Please describe.**

One line that we are hearing every time in the current covid-19 crisis is "Don't Touch Your Face" but according to some studies we all touch our face 23 times an hour. So it's quite difficult to train yourself not to touch your face unnecessarily.
Covid-19: safety, face touch early warning system using Microbit.

**Describe the solution you'd like**

I have to propose a project "Face Touch Early Warning System" that warns you by showing led signals and alarm whenever you bring your hands towards your face.

**Describe alternatives you've considered**

We are going to use an inbuilt accelerometer present in Microbit to know which side the micro bit is facing. I have used the MakeCode online editor. A micro bit can detect a bunch of gestures but we have used the OnShake gesture. Whenever the micro: bit detects the up gesture then it will show the sad face led light and warns the user, not to touch your face. 

**Additional context**

![image](https://user-images.githubusercontent.com/57909583/133196452-002899fb-5144-4e5c-b074-b86deeb08fcf.png)

![image](https://user-images.githubusercontent.com/57909583/133196465-75a89196-dbcd-4afc-b22b-c432bc219e90.png)

**Comment by abchatra** [comment]
Feel free to do a PR on documentation with project ideas.
