### ISSUE TITLE
Input errors

### ISSUE THREAD

**Issue by microbitpron** [microsoft/pxt-microbit#4373]
Whenever I put input blocks its showing errors, why?  Its showing errors for the input blocks when I try to download it to my micro:bit . Currently I'm using the online editor on my pc. screenshot is below 
![Microbit error](https://user-images.githubusercontent.com/90964542/133886735-484bdf79-934d-4fe4-96a4-db433e0f3928.png)

**Comment by abchatra** [comment]
@microbitpron can you share your program using the share button. There are issues with the extension you are using. We need to contact the extension author. I can help here if you share your program.

**Comment by abchatra** [comment]
No additional information given.
