### ISSUE TITLE
Links on v2 project page are broken

### ISSUE THREAD

**Issue by onewheeltom** [microsoft/pxt-microbit#4374]
On the v2 projects page : https://makecode.microbit.org/v2tutorials

The links on the v2 projects page - https://makecode.microbit.org/v2tutorials

are broken and return a "Sorry the page is missing" message

There is an extra "v2" after makecode.microbit.org in each URL

The Pet Hamster link is : https://makecode.microbit.org/v2/projects/v2-pet-hamster

It should be : https://makecode.microbit.org/projects/v2-pet-hamster

All 5 links are broken the same way.

**Comment by abchatra** [comment]
Thanks @onewheeltom. @anzhou5 can you please address these?

**Comment by anzhou5** [comment]
this might be due to my being less familiar with the codebase, but I'm not sure what could be injecting the extra v2 into the URL. The project page itself doesn't contain it: https://github.com/Microsoft/pxt-microbit/blob/master/docs/v2tutorials.md

**Comment by shakao** [comment]
i think this is a bug caued by the file starting with "v2", it looks like it's messing up the relative paths because it thinks this is using our v2 microbit editor (makecode.microbit.com/v2)
