### ISSUE TITLE
Extension merge -- lost images and render script

### ISSUE THREAD

**Issue by halspeed** [microsoft/pxt-microbit#4379]
After extension merge https://github.com/microsoft/pxt-microbit/pull/4366, images and block renders are not appearing on https://makecode.microbit.org/pkg/KidSpark/pxt-sparkbit

Original README.md located here: https://github.com/KidSpark/pxt-sparkbit/blob/master/README.md

**Comment by microbit-mark** [comment]
@abchatra browser console suggests that the GitHub API call is not working here:

![image](https://user-images.githubusercontent.com/31242877/138250312-29783dba-80e4-4113-afa9-8272c170acc9.png)

**Comment by abchatra** [comment]
This is a bug in the extensions. 

Tags must be in **v**0.1.1 but the extension tags are just 0.1.1 and missing _v_. Please add new tags with the right format. 

Documentation is here: https://makecode.com/extensions/versioning
![image](https://user-images.githubusercontent.com/6107272/138354818-3d0846bc-b819-4c43-890d-90ba5a122426.png)
