### ISSUE TITLE
iOS Safari hangs in live/beta

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4384]
**Describe the bug**
When using the iOS app or safari on iOS12.5.4, the editor appears to hang when adding a new block to a new project. It stalls with the block slightly transparent and the trash can showing. It does not reproduce in makecode.microbit.org/v2

**To Reproduce**
Open MakeCode ins Safari on iOS 12.5.4, blocks cannot be moved

**Screenshots**

![Simulator Screen Shot - iPad Air iOS 12 4 - 2021-09-23 at 18 06 21](https://user-images.githubusercontent.com/31242877/134666375-8282c60b-7cbb-44a6-adf7-a6c0038e6bc7.png)
**micro:bit version (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPad Air A1474
 - OS: [e.g. iOS8.1] iOS 12.5.4
 - Browser [e.g. stock browser, safari] safari

**Comment by abchatra** [comment]
@microbit-mark these are safari issues.  They are fixed in the latest version of safari. It is hard for us to workaround these. We are not going to fix from our end.

**Comment by martinwork** [comment]
@abchatra
makecode.microbit.org/v2 seems to work.
I believe users with iPad Air A1474 are stuck at iOS 12.

**Comment by abchatra** [comment]
Old version might work as it doesn't have all the new code we have added in. We have tried fixing these bugs in the past, unfortunately we can't make it work without removing all the features (like we are on latest blockly, can't go back to old blockly without causing tons of other issues)
