### ISSUE TITLE
Music notes go back to defaults when switching to Norwegian Bokmal

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4385]
Note values return to Middle C rather than retaining their set values

![ezgif com-gif-maker](https://user-images.githubusercontent.com/31242877/134694726-a8cb47dd-230b-4e33-af67-f9f000461679.gif)

**Comment by jwunderl** [comment]
It looks like this stems from this mistaken translation in `microbit/core-strings.json`:

![image](https://user-images.githubusercontent.com/5615930/145483736-ceb01a37-0ff9-407c-a7e2-f7277fa39f7e.png)

I have deleted that broken translation so it should be good in ~24-48hrs

**Comment by jwunderl** [comment]
Translation fix is out now, note that fixing these translation bugs can cause one time resetting of the values for the affected languages.

We should expand on https://github.com/microsoft/pxt/pull/7413 to account for situations like these (where parameter names in % translated sections are mismatched) and ignore the translations (or even just ignore the parameter name & use the existing one)
