### ISSUE TITLE
Feature: Add sim support for power saving blocks

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4389]
For consideration as part of a future MakeCode release

A power-saving extension for the micro:bit (V2) was approved in https://github.com/microsoft/pxt-microbit/pull/4365

It will be useful to add simulator support for these blocks, so that when added to the program the simulator reflects the low power state of the micro:bit, ie not running the code until the device is woken to full power mode again.

It may be useful to add power saving support to the core MakeCode blocks, as we have done with data logging, as opposed to having them in an extension.

I'm also including here the request for the design work in updating the extension icon.
>Also for consideration of @soniakandah. We'd love a better icon than https://github.com/microbit-foundation/pxt-microbit-v2-power/blob/master/icon.png that shows that the extension can be used to save battery power / sleep and wake the micro:bit, if you're able to take a look.

**Comment by abchatra** [comment]
No plans to implement this.
