### ISSUE TITLE
Error: Argument of type 'RegExp' is not assignable to parameter of type 'string'

### ISSUE THREAD

**Issue by joshkordek3** [microsoft/pxt-microbit#4395]
I'm not able to use regular expressions for string replacement.

**To Reproduce**
1. Go to '[makecode](https://makecode.microbit.org)'
2. Create a new project
3. Paste 'console.log(JSON.stringify({value: "idk"}).replace('\\"', 'aksjasijaihjkdhskdhsjdjskdhskjdjskdhksdjsdlkshkjdksdhjskdjkshdkshdjsjkdgsjkdjskds').replace(/\"(.+)\":/g, '$1:').replace(/: ?\"(.+)\"/g, ': $1').replace('aksjasijaihjkdhskdhsjdjskdhskjdjskdhksdjsdlkshkjdksdhjskdjkshdkshdjsjkdgsjkdjskds', '"'))'

**micro:bit version:**
Not hardware-related.

**Desktop (please complete the following information):**
Browser: chrome
System Details: Chrome OS Version 93.0.4577.107

**Comment by jwunderl** [comment]
Regular expressions are not supported per https://makecode.com/language (primarily due to hardware restrictions)

**Comment by joshkordek3** [comment]
Hmmm, could it be supported in the simulator though?
