### ISSUE TITLE
Video on Script Page

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#44]
Go to script...

https://codemicrobit.com/fkayhbkytt

Go to Project Settings - YouTube video inserted

https://youtu.be/TCAlAKvMx2M?list=PLE8XLCpSej07SC0CKPLsfhKNVelPXjBS4

The video is not noticeable. Does this feature work? 

![image](https://cloud.githubusercontent.com/assets/11206682/14658291/886bd5ba-0647-11e6-85ab-9a7fcbe28ca2.png)

**Comment by pelikhan** [comment]
There is no YouTube file information in that script.

**Comment by mebrauns** [comment]
Here is the screenshot of the video link for script /fkayhbkytt

![image](https://cloud.githubusercontent.com/assets/11206682/14659853/5ac840c8-0654-11e6-949c-03e11fe03331.png)

**Comment by pelikhan** [comment]
Did you share the script after adding the YouTube link? It is not in that script.

https://codemicrobit.com/api/zadchltsql/text

**Comment by pelikhan** [comment]
Michal, we seem to be loosing the card information when publishing.

**Comment by pelikhan** [comment]
We don't support that feature anymore. You can put the YouTube link in the Readme.
