### ISSUE TITLE
Extension gallery only lists top 24 extensions

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4406]
@KitronikLtd have ~27 extensions available for MakeCode, but only 24 are listed.

![image](https://user-images.githubusercontent.com/31242877/138847913-e8bdc314-ce16-4ab7-a469-40c6b016c705.png)

Is this a limitation of the gallery?

Could we display all extensions and/or have pagination to scroll through them all

Related #4405 #3353

**Comment by abchatra** [comment]
Search for kitronik here: https://github.com/microsoft/pxt-microbit/blob/master/targetconfig.json
