### ISSUE TITLE
Feature: Add calibrate temperature API

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4409]
As the thermometer uses the temperature on the nRF and not the ambient temperature, it is not always completely accurate. If you wanted to make this more accurate, you could measure the temperature using an external device and then calibrate the temperature accordingly on the micro:bit

The DAL exposes a set Calibration API which we could add to MakeCode

https://lancaster-university.github.io/microbit-docs/ubit/thermometer/#setcalibration

Whilst we are at it, could we also have a way to represent the value in Fahrenheit without using a separate calculation?

**Comment by abchatra** [comment]
This can be an extension.

**Comment by abchatra** [comment]
Won't fix as this is advanced scenario.
