### ISSUE TITLE
Python class declarations are not recognised without a constructor function

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4416]
> micro:bit support #48668

> Python class declarations are not recognised without a constructor function.  Even when this is provided, the system gives the compiler error "Type annotation cannot appear on a constructor declaration"

``` python
#  example of failing class def
a = 0
b = 0

class FRED: 
    def __init__(self, a, b):
        self.a = a
        self.b = b
```

![image](https://user-images.githubusercontent.com/31242877/139651640-1574035b-377d-4a9b-b7e5-addb74908e1f.png)

**Comment by martinwork** [comment]
@riknoll The "Type annotation" error no longer appears in beta.

Unfortunately, the "implicitly has 'any' type" errors are still shown until an instance of the class is created.

This code works in beta, but has the confusing "any" errors when the class definition is first created 
```
class FRED:
    def __init__(self, a, b):
        self.a = a
        self.b = b
        
ab = FRED(1,2)

def on_forever():
    basic.show_number(ab.a)
    basic.show_number(ab.b)

basic.forever(on_forever)
```
