### ISSUE TITLE
Feature: Extend long press/touched API to buttons and pins

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4418]
> micro:bit support: 48707

**Is your feature request related to a problem? Please describe.**
When creating a morse program to transmit across micro:bit V1s, often the A button is used to transmit a dot and the B button for a dash. With V2, we can use touch, press and long press on the logo thereby using only one input feature.

**Describe the solution you'd like**
It would be useful to extend this functionality to the buttons and pins 0,1,2

**Describe alternatives you've considered**

**Additional context**

We have definitely talked about this, but I can't find a duplicate feature request, so raising here.

**Comment by abchatra** [comment]
No plans to implement.

**Comment by jaustin** [comment]
For anyone else looking for this feature, there is also https://makecode.microbit.org/pkg/bsiever/microbit-pxt-clicks which gives greater control of the click behaviour, including a 'click' and a 'hold' event
