### ISSUE TITLE
Error when building using GitHub Actions: "program too big"

### ISSUE THREAD

**Issue by fredster33** [microsoft/pxt-microbit#4421]
**Describe the bug**
When I try to use the GitHub action to build my program, it outputs this error:

```
Error: pxt_modules/pxt-sonar/main.ts(1,1): error TS9200: program too big by 3612 bytes!

Error: Process completed with exit code 1.
```
The program works fine on the web version of MakeCode.

**To Reproduce**
1. Go to https://github.com/fredster33/bike-new/runs/4128083160?check_suite_focus=true
2. Click on 'build"

**Expected behavior**
The program builds properly.

**Screenshots**
N/A

**micro:bit version (please complete the following information):**
Not related to hardware.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge Dev
 - Version: 97

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by abchatra** [comment]
We have doubled the size of the file. This should be fixed. If not let us know.

**Comment by fredster33** [comment]
Thanks!
