### ISSUE TITLE
Feature: Add "Duplicate project" action within the editor

### ISSUE THREAD

**Issue by hovavo** [microsoft/pxt-microbit#4422]
Currently the flow of creating a variation for an existing project is not ideal. It us possible in the "My projects" view, but not inside the editor.

It would be extremely useful to have a "Duplicate project" action in the more actions menu inside the editor.  

Use cases:
- As a teacher I have a lot of example projects which are incremental. Creating them is currently a pain. 
- Students will be more open for exploration and experimentation once this (duplicating, "saving as"...) is made easier

**Comment by abchatra** [comment]
We don't plan to add duplicate in the editor, following is the way.
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/6107272/222792926-4ca7f5a2-2df9-46c9-a2c2-fc6bf0f8c994.png">

However, if you want version history you could use github integration and get version history from github. 

<img width="409" alt="image" src="https://user-images.githubusercontent.com/6107272/222793216-45dd7849-d9f5-444b-9365-c1376e096aa4.png">
