### ISSUE TITLE
Can't add custom .asm file (or any non-".ts" file)

### ISSUE THREAD

**Issue by arduino12** [microsoft/pxt-microbit#4426]
**Describe the bug**
When adding a custom file - the ".ts" extension always gets added-
So one can't create a .cpp, .h, .asm custom files...

**To Reproduce**
1. Go to 'JavaScript'
2. Click on the '+' sign inside 'Explorer'
3. Enter 'test.asm' and click 'Go Ahead'
4. See the bug - a file named: 'test.asm.ts' was added (should be only 'test.asm')

**Expected behavior**
Create a new file named 'test.asm', not 'test.asm.ts'.

**Screenshots**
![image](https://user-images.githubusercontent.com/11454280/141612155-d79444e2-f92b-40e0-82f6-e1953d6573c7.png)
![image](https://user-images.githubusercontent.com/11454280/141612176-bfe55cda-ad2a-4621-8461-df4765d8f495.png)
![image](https://user-images.githubusercontent.com/11454280/141612452-420b7923-48fe-441d-a166-4fb0a25365e2.png)

**micro:bit version (please complete the following information):**
makecode.microbit.org version:  4.0.16
Microsoft MakeCode version:  7.0.12
microbit runtime version:  v2.2.0-rc6
codal-microbit-v2 runtime version:  v0.2.32

**Comment by abchatra** [comment]
We only support typescript files at this point of time.

**Comment by arduino12** [comment]
The makecode microbit web editor supports .asm .h .cpp .ts .py files..
![image](https://user-images.githubusercontent.com/11454280/142257027-e73f88a5-5448-4b3f-8b2c-5ee4a1ab0ad8.png)

When I develop my own lib I can use any one of the files and edit it inside the web editor as well..

**The bug here is that the "Go Ahead" button automaticly adds the ".ts" without cheacking if the user have already gave a file extention of its own...**

**Comment by abchatra** [comment]
We don't plan to support non typescript\python files as authoring experience in the editor at this point of time.
