### ISSUE TITLE
Include info on tutorial localisation in docs

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4435]
Originally raised via Slack https://microbit-community.slack.com/archives/C0225TSC0SD/p1621926376027900

> In some files, we can find some words/sentences which refers to corresponding Blocks, like “forever” block, “on start” block, etc.
> For example, in the “Tutorials > Flashing Heart” page
> 
> 1. Open https://makecode.microbit.org/#
> 2. Click Flashing Heart
> 3. Click Blocks(Start Tutorial)
> 4. Click OK
> 
> Then you will see the actual tutorial content in your browser
> In the instruction section of the page(at the almost top of the page), you will find the instruction sentence below,
> 
> `"Place the "show leds" block in the "forever" block and draw a heart.`
> 
> The quoted 2 strings “show leds” and “forever” are backgrounded(blue color).
> In the corresponding translatable file,
> https://github.com/microsoft/pxt-microbit/blob/d573587bdf3d1bcc0a8ad2048cce800055d10b44/docs/projects/spy/flashing-heart.md
> Actual source text fragment is like below.
> 
> `Put a ||basic:show leds|| in the ||basic:forever|| block and draw a heart.`
> 
> Those `||basic:show leds||`   and `||basic:forever||` needs to be localized carefully, because they refer to Blocks, meaning that they are not just a normal words, and how they appear in actual simulator/editor screen (background color of those text) are decided by the first part of the text “||basic:  “, I guess.
> So I think we need to translate the latter part of `|| basic: forever||`, in this case “forever”, but we need to preserve the former part of the text, in this case “basic: “.

I think it would be helpful for translators if this is in the FAQ https://makecode.com/translate#faq

**Comment by microbit-mark** [comment]
@ganicke can you take a look to see if this fits in with your docs, othwerwise/also we can add the info to our knowledge base

**Comment by ganicke** [comment]
I should add another small section the translate page to explain some of the translation aspects of tutorials.

**Comment by ganicke** [comment]
A new section about block highlights is added at https://makecode.com/translate#block-highlights.
