### ISSUE TITLE
`pxt serve --local` fails

### ISSUE THREAD

**Issue by bsiever** [microsoft/pxt-microbit#4446]
**Describe the bug**

I'm trying to test an extension via `pxt serve --local`, so I've followed the instructions in the [README.md](https://github.com/microsoft/pxt-microbit/blob/master/README.md#local-server-setup) to setup the local server and do a local build.  When I try to start the server it shows some errors in the terminal and a page showing only a puzzle piece. Details of errors are below in **Additional context**.  

The `serve` command fails with local builds, but I can do local builds with `build`/`deploy` for both docker and native build.  I can also do `pxt serve` without `--local`

I've tried several combinations of options, but mainly `PXT_COMPILE_SWITCHES=csv---mbcodal pxt serve --local` and `PXT_NODOCKER=1 PXT_COMPILE_SWITCHES=csv---mbcodal pxt serve --local`

Tangent 1: Following the README and doing just `pxt serve` in the `pxt-microbit` directory seems to be modal and ignores uses of `--local` until a `pxt clean`. 

Tangent 2: The [Developer Setup](https://github.com/microsoft/pxt-microbit/blob/master/README.md#local-server-setup) has two items numbered 8.  Should the `pxt link` step be before the `npm install` step?

**To Reproduce**

1. Follow the [Developer Setup](https://github.com/microsoft/pxt-microbit/blob/master/README.md#developer-setup) steps. 
2. Try to do some variation of `pxt serve --local`

**Expected behavior**

MakeCode running locally and able to do local builds :) 

**Desktop (please complete the following information):**
 - OS: macOS 11.4 (M1 Macbook Air)
 - Browser Chrome
 - Version 96.0

**Additional context**

Here are some parts of what's shown in the terminal indicating some possible problems:
```
... 
copying common-sim...
/Projects/microbit/serve2/pxt-microbit/node_modules/@types/node/index.d.ts(35,1): error TS1084: Invalid 'reference' directive syntax.
/Projects/microbit/serve2/pxt-microbit/node_modules/@types/node/index.d.ts(43,30): error TS1005: '=' expected.
/Projects/microbit/serve2/pxt-microbit/node_modules/@types/node/index.d.ts(46,30): error TS1005: '=' expected.
...
building bundled libs/blocksprj
[run] git clone https://github.com/lancaster-university/microbit built/codal

***
*** Build failed: target build failed: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
Cloning into 'built/codal'...
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at Hash.update (node:internal/crypto/hash:105:11)
    at Object.sha256 (/Projects/microbit/serve2/pxt-microbit/node_modules/pxt-core/built/nodeutil.js:226:10)
    at Object.buildHexAsync (/Projects/microbit/serve2/pxt-microbit/node_modules/pxt-core/built/buildengine.js:241:20)
    at Host.getHexInfoAsync (/Projects/microbit/serve2/pxt-microbit/node_modules/pxt-core/built/pxt.js:158672:22)
    at fillExtInfoAsync (/Projects/microbit/serve2/pxt-microbit/node_modules/pxt-core/built/pxt.js:112325:69)
    at MainPackage.getCompileOptionsAsync (/Projects/microbit/serve2/pxt-microbit/node_modules/pxt-core/built/pxt.js:112371:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
***
```

Thanks for any help/pointers/fixes!

**Comment by abchatra** [comment]
Can't repro
