### ISSUE TITLE
help

### ISSUE THREAD

**Issue by riadh-tn** [microsoft/pxt-microbit#4452]
![269490195_10159749214954559_3251726304860668239_n](https://user-images.githubusercontent.com/97065873/147986378-3d672907-ec39-47fc-a893-aa6c460ed0f2.jpg)
windows 10

**Comment by abchatra** [comment]
@jwunderl Looks like more issues with the electron app.

**Comment by jwunderl** [comment]
Hey @riadh-tn,

It looks like you're using v3.0.19 of the offline app, which had an error start popping up when a download failed to complete. (same as https://github.com/microsoft/pxt-microbit/issues/4451, https://github.com/microsoft/pxt-microbit/issues/3746); newer versions should not fail in this way even if the autoupdate fails, so if possible could try download the new version from here https://makecode.microbit.org/offline-app (direct link for windows is https://makecode.com/api/release/microbit/v4.0.11/win64)? Allowing the update to go through should also work, but depending on network / computer conditions might be slow / error prone if this reproduces consistently.

**Comment by abchatra** [comment]
Fixed
