### ISSUE TITLE
Clean up Music API's

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4454]
Request to standardize, and simplify Music/Sounds API's

Blocks representation - 
![MusicBlocks](https://user-images.githubusercontent.com/22108954/150388381-aa488d31-cc70-47a2-9b17-5a24b10dbae6.png)

TS representation - 
![MusicTS](https://user-images.githubusercontent.com/22108954/150388401-1832d792-19fc-4770-ac13-f422348173fe.png)

Play Sound should be in the Music namespace.  
There are 3 different ways to represent a note/melody and 2 different ways to represent tempo...
Is there a way to standardize/simplify?

**Comment by jaustin** [comment]
I'd like to add the following to consideration:
<img width="457" alt="image" src="https://user-images.githubusercontent.com/147113/164488526-0f10cc25-37df-4939-9581-d48701adb1a1.png">
```typescript
music.playMelody("- - - - - - - - ", 120)
music.startMelody(music.builtInMelody(Melodies.Dadadadum), MelodyOptions.Once)
music.playTone(262, music.beat(BeatFraction.Whole))
music.ringTone(262)
soundExpression.giggle.playUntilDone()
soundExpression.giggle.play()
soundExpression.playSoundEffect(soundExpression.createSoundEffect(WaveShape.Sine, 2000, 0, 1023, 0, 500, SoundExpressionEffect.None, InterpolationCurve.Linear))
pins.analogPitch(200, 100)
```

**Comment by abchatra** [comment]
This is implemented.
