### ISSUE TITLE
Consolidate on core extension designs and brand

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4457]
Describe your design or art need by answering the questions below: 

## What are the requirements for the project? 
Update `icon.png`s and descriptions for extensions published by Microsoft so that they are inline with MakeCode and micro:bit branding

## Please share any existing references, screenshots, links, etc. here that will help us better understand your requirements 
Extensions here eg servo, sonar, neopixel look pretty messy and inconsistent. Some of the other branded stuff looks clearer
![image](https://user-images.githubusercontent.com/31242877/151175583-33dd758a-aaa4-4394-8e78-1567df2b04da.png)
![image](https://user-images.githubusercontent.com/31242877/151176105-6d5f6bd7-fcef-4122-85cb-a641ee4211b2.png)

It would be great to update the images and make them seem more MakeCode-like as it would help teachers understand what they are and be more confident in using them if they know they are published by the MakeCode team

### Who are the stakeholders that need to sign off on this design? Tag them here.
@Jaqster? @microbit-mark 

### What audience is this request for? 
Teachers, Kids

### What does success look like?
Extensions published by the Microsoft MakeCode team have a consistent brand feel to them 

### How will we measure if this is successful or not?
Ask users to tell us what the extension does, who published it, do we see more use

**Comment by unthinkmedia** [comment]
@BeckHaru will this be part of our branding work?

**Comment by abchatra** [comment]
Wont fix. No design bandwidth :-(
