### ISSUE TITLE
Feature: Link to tutorials from extension gallery

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4458]
Maybe depends on #4434 

It would be really great for those extensions that have one, to link people directly to a tutorial with a button in the gallery. Something like this:

![image](https://user-images.githubusercontent.com/31242877/151180102-d38c77ed-8972-41be-8752-d136e153cec0.png)

This would let people experiment with the extension and help onboard them. It's potentially less scary than clicking on the 'Learn More' button which links out to the GitHub readme rendered in MakeCode.

**Comment by abchatra** [comment]
Decided not to fix. Currently there is a way to add tutorial in the learn more markdown. Also this wouldn't scale for multiple tutorials for the same extension.
