### ISSUE TITLE
Ringtone command plays negative frequencies

### ISSUE THREAD

**Issue by imanousar** [microsoft/pxt-microbit#4460]
The ring tone command won't allow you to play directly a negative frequency. However, if you modify the input and don't give a number, the code will execute and won't send any errors.

Steps to reproduce the behaviour:
1. Select a Ring tone command.
2. Select from math the subtraction function 
3. If you type for ex. 0 - 10 the command executes normally and doesn't show a warning

**Comment by riknoll** [comment]
What is the desired behavior here?

I just checked the implementation, and we clamp it to 0 when the frequency is negative. That seems like the right behavior to me; we generally have a policy of not throwing exceptions for bad inputs.

**Comment by imanousar** [comment]
I see. I was expecting to see a warning or an error though after executing the following code when the input was negative:

``` python
def on_forever():
    for index in range(900):
        music.ring_tone(randint(55, 444) + index)
        control.wait_micros(randint(55, 555))
    for index2 in range(900):
        music.ring_tone(randint(55, 444) - index2)
        control.wait_micros(randint(55, 555))
 ```
If this is how it is supposed to work, okay. I just noticed it and wanted to let you know.

**Comment by abchatra** [comment]
This is by design.
