### ISSUE TITLE
Operator '==' cannot be applied to types 'number' and 'string'.

### ISSUE THREAD

**Issue by MinecrasfsftMan** [microsoft/pxt-microbit#4462]
**Describe the bug**
Upon adding a "set" or "change" block for a `variable,` then adding a `if ([name of var] == "input")` it says "Operator '==' cannot be applied to types 'number' and 'string'." 

**To Reproduce**
1. Go to makecode.microbit.org/
2. Click on 'New Project, Create (Make sure it's block mode)'
3. Scroll down to Variables
4. Click on 'Make a Variable, Ok'
5. Add a " 'set' or 'change' [Variable] block by 1"
6. Add an 'if true' condition
7. Get a '0 = 0' block
8. Add your value to one of the zeroes.
9. See error

**Expected behavior**
It's supposed to check the score for both players to trigger the game over screen.
**Screenshots**
![image](https://user-images.githubusercontent.com/71991306/151731469-7901c7ce-6dc6-4412-8440-96cf9560e7e1.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [20H2]

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy A42]
 - OS: [Android]
 - Browser [Chrome]
 - Version [12]

**Comment by abchatra** [comment]
For strings you need to use includes block to compare

![image](https://user-images.githubusercontent.com/6107272/155244956-0fe995b9-3a59-428c-bb00-64d579435b3b.png)
