### ISSUE TITLE
Concurrency processing question

### ISSUE THREAD

**Issue by samlcy1997** [microsoft/pxt-microbit#4464]
Hello everyone,

I am working on a project which is using 2~4 "forever loop",
one of the loop have a function that is Time-dependent ( DHT11 need to read a sequential bits in microsecond level )
I have tried on a simple program with only reading and show the DHT11 result, it is fine.
But once I add more "forever" to get other sensors result, the reading become incorrect, the check sum progress show that bit data was corrupted.
I am guessing about other forever loop interrupt the reading and cause the reading of bit get wrong (maybe delay cause the time line shifted?)
Is that any way to make the reading function become exclusive?

Following the instruction from https://makecode.microbit.org/device/reactive
I guess each "forever loop" will use the basic.pause() to trigger the thread switching, 
if I use control.waitMicros() to replace the basic.pause() function, will is able to keep my DHT11 reading function exclusive?
If you have any suggestion, please help me.

Thank you very much.

**Comment by martinwork** [comment]
@samlcy1997 Other forever loops will not "interrupt". Each forever loop allows others to run by blocking in pause() or during some other operations, such as display or serial output.

Other forever loops will not run during control.waitMicros(), but the exact time that passes may be affected by the low level system interrupts that keep track of time and support background operations, which could be affected by previous actions in other forever loops.

When working with microsecond timings, it's necessary to be very careful about the code used, as everything takes time to execute. Even reading the time with input.runningTimeMicros() takes time and could affect the operation being timed. Timings may vary on different hardware. 

Could you share code for simple examples of cases when it is working fine and when the readings become incorrect, and say what  micro:bit models you have tried?

Ultimately I suspect it may be necessary to allow for failures and return the last good value obtained.

**Comment by abchatra** [comment]
question answered
