### ISSUE TITLE
Block rendering in blocks for extensions in broken

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#4466]
None of the block samples in extension documentation pages (https://makecode.microbit.org/pkg/makecode-extensions/LPS22) render to blocks. Something changed and we're not rendering the snippets anymore.

Expected:
![image](https://user-images.githubusercontent.com/4175913/152077629-02511405-9d7f-47b8-83dd-00fd614a7b07.png)

Actual
![image](https://user-images.githubusercontent.com/4175913/152077636-0ae9ba7b-d2d5-465b-a152-4505d6a325ae.png)

**Comment by abchatra** [comment]
This is a bug in the extension markdown. I have done a quick PR: https://github.com/makecode-extensions/LPS22/pull/1
