### ISSUE TITLE
Variable numbers not rounding up

### ISSUE THREAD

**Issue by microbit-pauline** [microsoft/pxt-microbit#4468]
**Describe the bug**
Issue raised through Micro:bit support 50561
Variable numbers in MakeCode not rounding up on all number by giving a 8 decimal response.

**To Reproduce**
Steps to reproduce the behaviour:
1. In MakeCode the user created a variable, on start to 16.9. 
2. On shake, change variable by -1.3. 
3. The result was 15.59999999

The user expected the value to be rounded to 15.6. 

4. The teacher then changed the starting variable value. Setting to start at 17.9 or 18.9 produced similar results, ending in .5999999. 
5. The teacher then changed the starting variable to 14.9 and this rounded the number to 13.6.

**Expected behaviour**
The variable number to round up on all numbers.

**Screenshots**
![image](https://user-images.githubusercontent.com/29146842/152554733-b27e3a2e-0b66-4dff-80ee-e4648612ef3a.png)

![image](https://user-images.githubusercontent.com/29146842/152554699-be97ad3a-05cf-4f9b-aefb-ca18b06fe7a3.png)

**MakeCode code**
https://makecode.microbit.org/59974-72853-03637-48461

**micro:bit version**
Not provided

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.7 
 - Browser is Chrome
 - Version 97.0.4692.99

**Question: Is this intentional or a bug?**

**Comment by abchatra** [comment]
Unfortunately we can't fix this. This is due to floating point representation in javacript

Read here:
https://stackoverflow.com/questions/3439040/why-does-adding-two-decimals-in-javascript-produce-a-wrong-result
