### ISSUE TITLE
`control.waitMicros(0)` does not work on V2

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4469]
```
basic.showIcon(IconNames.No)
control.waitMicros(0)
basic.showIcon(IconNames.Yes)
```
works on a V1 board, but not on a V2, the check/tick mark is not displayed.

changing the value in waitMicros resolves this eg this works on both boards

```
basic.showIcon(IconNames.No)
control.waitMicros(1)
basic.showIcon(IconNames.Yes)
```
Tested in live and beta

**Comment by abchatra** [comment]
@microbit-mark is this a CODAL issue?

**Comment by martinwork** [comment]
@abchatra @microbit-mark Created CODAL issue https://github.com/lancaster-university/codal-microbit-v2/issues/174
