### ISSUE TITLE
Feature: Add scroll speed API in blocks

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4470]
https://support.microbit.org/a/tickets/50797 (private)

**Is your feature request related to a problem? Please describe.**

> Unfortunatelly there is no scroll speed control in blocks for the "show string" function although the JS version seems to understand it when you append it as second parameter. For children starting to learn to code in particular this is unfortunate as they tend to be slow readers. 

**Describe the solution you'd like**

> Is there a way to add that function to blocks?

**Describe alternatives you've considered**

**Additional context**

**Comment by TheNeoBurn** [comment]
Thanks @microbit-mark for the redirection of this request!

Here an image for clarification:

![MiroBitShowString](https://user-images.githubusercontent.com/28660590/153085119-c1eeb9fa-490c-4c66-8e0f-044dc709264b.png)

**Describe alternatives you've considered**
The functionality could either be added to the existing `show string` element, as a seperate `show string with speed` element or the element implements the `basic.showString()` funtion with a globally settable variable (but I think that might be too abstract).

The alternative at the moment is to enter the `JavaScript` mode and edit the code which results in an un-editable block and is not quite beginner friendy.

**Comment by abchatra** [comment]
This can be done in the extension. We plan to keep this block simple and not add this feature at this point of time.
