### ISSUE TITLE
Sound effect field editor

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#4473]
This has already been discussed in #4049 but that was really about an interim solution, whereas we'd really like a full field editor.

We'd like a field editor for creating, previewing and helping users understand sound effects:
* We'd like a "gallery" of named sounds that populates the values required to get a range of interesting sounds.
* We'd like it to be part of a block that can still have multiple parameters take variables instead of values (it's important that the sounds can be modified by input, eg accelerometer values changing the frequency)
* It's important for students to be able to visualise the waveform of the sound (eg frequency through time)
* We'd like most of the parameters that are available on the SoundEmojiSynth to be exposed if possible.
* We'd like it to allow users to create things like the microbit sounds (eg "yawn", "hello", etc) - these 'sounds' are actually lists of sound effects (so, perhaps making lists of these sounds is important)

We have some examples of blocks without field editors that do this here:
https://github.com/JoshuaAHill/prototypesoundblocks
(see also https://github.com/microsoft/pxt-microbit/issues/3962 as a feature request that emerged from that)

![image](https://user-images.githubusercontent.com/147113/154109923-dfdb93e7-7464-417f-966f-f4b8f2c0fdc1.png)

Here's a rough concept drawing worked out in The Foundation after some interviews with teachers and the education team:
![image](https://user-images.githubusercontent.com/147113/154109984-783a523c-fda0-4341-85d7-f87de57859ef.png)

Josephine has done some work integrating these requirements and interpreting the drawing into something we could test:

https://github.com/microsoft/pxt-microbit/pull/4376
https://github.com/microsoft/pxt/pull/8504

@JohnVidler was going to look at spinning this up to take some screenshots of the prototype, but @abchatra it would be great to have a version deployed on MS's build system so we can test this with users. The plotly library dependency mentioned in the PR above shouldn't be an issue (https://github.com/microsoft/pxt/pull/8504#discussion_r742970286 ) but I don't know if there are other beyond that.

CC @finneyj @microbit-mark

**Comment by jaustin** [comment]
Some followup thoughts on the relationship between single sound multiple

I don't think making the field editor natively edit lists is necessarily a good idea, and so the gallery should be of single frames.

If students want to chain frames, it should be by either:
Multiple blocks:
![image](https://user-images.githubusercontent.com/147113/154467181-d91ddb47-a241-4d0e-9e8d-ecd792b37cca.png)

Use an array into the play sound block (not supported in Josh's sample extension:

![image](https://user-images.githubusercontent.com/147113/154468262-54ac1d65-6a76-4524-8430-907576a1b544.png)

Ideally there'd be no gap between subsequent sounds if using successive blocks and there MUST be no gap if using an array
(some questions and proposed answers:
 * should `play sound` block until the sound is complete by default? YES 
 * should `play sound` have an option to be overlapped with another sound?: YES if they're played in two fibers (🧐)
  )

**Comment by riknoll** [comment]
in beta now
