### ISSUE TITLE
Data Logger not working?

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4480]
@microbit-mark - maybe you can try on your end too?
I just tried data logging with 2 new micro:bit v2's and it didn't work (Bootloader Version: 0256).
![microbit v2](https://user-images.githubusercontent.com/22108954/156233137-74c40c94-f8b3-494f-ba44-61d3cb0411cf.jpg)

Using this program - https://makecode.microbit.org/_3bjYD0FvW8W2

I downloaded to the micro:bit
I didn't disconnect
I pressed B and then A a bunch of times
Then I opened the MY_DATA.HTM file on the micro:bit and got an empty page

Did we regress?

**Comment by abchatra** [comment]
@Jaqster did you try /beta or live?

**Comment by Jaqster** [comment]
This was live

**Comment by microbit-mark** [comment]
I think beta has the most current version of CODAL that supports the latest board revision, so we should test there. I don't have a V2.20 board to test at the moment.

I expect you would always need to disconnect and reconnect on USB to see the updated data in MY_DATA.HTM

**Comment by jwunderl** [comment]
Sounds like this has been fixed, or at least improved significantly -- if we run into the issue again it's likely to be a different cause / new issue~

**Comment by LeonWenbu** [comment]
Looks like V2.00 board highest firmware version is 0255, so this can never be fixed.
Interface Version: 0255
Bootloader Version: 0255

**Comment by microbit-mark** [comment]
There is a beta of 0258 here

https://tech.microbit.org/software/daplink-interface/#beta-releases

It would be great if you wanted to try that :)

--
Please excuse brevity and typos, this was sent from a phone

From: ***@***.***
Sent: 29 December 2023 16:16
To: ***@***.***
Reply to: ***@***.***
Cc: ***@***.***; ***@***.***
Subject: Re: [microsoft/pxt-microbit] Data Logger not working? (Issue #4480)


Looks like V2.00 board highest firmware version is 0255, so this can never be fixed.
Interface Version: 0255
Bootloader Version: 0255
