### ISSUE TITLE
Feature: Simulator support for data logging

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4492]
We should improve the simulator to provide better support for the data logging feature.

Currently:

- Data log output in the simulator is very different from a log on the real device,
learning how to use one doesn’t translate to the other
![image](https://user-images.githubusercontent.com/31242877/158865256-c9798f1f-79a6-4674-bbf0-75faaea69e06.png)

- It is not clear that data logging is an untethered technology, that you can log on battery and return to the computer later.
- If the ‘header’ rows are missed the serial mirroring doesn’t give any context
of the kind of data being logged
- If you’ve collected a lot of data from your log and plug your micro:bit back in and open up MakeCode console view, it looks like your data is missing.
- Using the simulator to log doesn’t help you find the real data in the MY_DATA.HTM file

We would like:

1.  the sim experience to reflect the MY_DATA.HTM experience
![image](https://user-images.githubusercontent.com/31242877/158866041-4c56782d-23d2-4a5b-9c07-8e51b6b06b17.png)
2. The sim/editor to tell people where to find the MY_DATA.HTM file/how to access the data
3. Fetch live data over WebUSB and update the MY_DATA style experience

**Comment by jaustin** [comment]
@abchatra are there any updated designs for this?
