### ISSUE TITLE
Extension: Sound Recording/Playback

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4493]
**Is your feature request related to a problem? Please describe.**
We are implementing a way to record nad playback sound in CODAL

**Describe the solution you'd like**
We would like an extension to support recording and playback of sound in MakeCode

**Additional context**
This is a tracker for the next MakeCode release. The extension work will be carried out outside of pxt-microbit, but we need a way to track.

**Comment by abchatra** [comment]
Sure

**Comment by Jaqster** [comment]
Feature request to also add Simulator record/playback sound and try to mimic the hardware

**Comment by Jaqster** [comment]
@finneyj

**Comment by jaustin** [comment]
@Jaqster is this issue to be used for simulator as well or shall we have a separate issue?

**Comment by Jaqster** [comment]
Same issue.  Sarah's on it!

**Comment by abchatra** [comment]
This is completed and we will take bugs as they come in.
