### ISSUE TITLE
Morse Chat: Can't grab the receivedNumber input

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4498]
**Describe the bug**
**Morse Chat**: Can't grab the **receivedNumber** input

**Steps to reproduce the behavior**
1.Nabigate to https://makecode.microbit.org/beta#editor
2.Tutorials for the new micro:bit(V2)----->**Morse Chat**----->Blocks Start Tutorial
3.Excute **step 6**

**Expect behavior**
It should be: Drag **receivedNumber** from **Variables**

**Actual behavior**
Can't grab the **receivedNumber** input from **on radio received [receivedNumber]**. This step need user to grab **receivedNumber** input, but **receivedNumber** input is in the drop down box. So it can't grab the **receivedNumber** input. 
![image](https://user-images.githubusercontent.com/59192069/161233282-92d1237a-b808-4416-ad5e-10309eacfa18.png)
![1](https://user-images.githubusercontent.com/59192069/161231702-d763e929-87b9-4836-928f-9818f5a57af5.gif)

**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 4.1.14
3.Microsoft MakeCode version: 7.5.4

**Comment by ganicke** [comment]
Grab/pull of parameters from events seems to now work with the latest release. Please test again, thanks.

![image](https://user-images.githubusercontent.com/27789908/163049884-033d2547-e6df-49e5-9a19-e8d2d66ede0a.png)

![image](https://user-images.githubusercontent.com/27789908/163050200-e9502300-6bdc-437f-ab7f-9cbc92dfe336.png)
