### ISSUE TITLE
Share dialog fonts don't match IDE

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#4501]
It's a bit weird, the fonts used in the share dialog are slightly different from the rest of the editor.

![image](https://user-images.githubusercontent.com/4175913/162528125-577c939a-70e3-43aa-aa08-def3a53d97b4.png)

**Comment by riknoll** [comment]
@pelikhan I believe this is the font we use everywhere (roboto)

**Comment by riknoll** [comment]
It does not match the code font (consolas), but is consistent with our other dialogs
