### ISSUE TITLE
Raeding analog Potentiometer value

### ISSUE THREAD

**Issue by Essalsolami** [microsoft/pxt-microbit#4502]
Hi guys,

Im using Arm robot controlled by 4 servo using 4 potentiometers.
The 4 potentiometers connected to pins 0,1,2,3
I got analog reading values of the pins 0,1,2 correct, but the pin 3 i got the value wrong, even when i changed it to pin 4 and 10.
I use microbit V2.
I used led off block.
Any help plz.

**Comment by abchatra** [comment]
This is a hardware issue. Can you please contact microbit support or forum.makecode.com?
