### ISSUE TITLE
The Logarithmic parameter of Interpolation shown incompletely

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4515]
**Describe the bug**
The **Logarithmic** parameter of **Interpolation** shown incompletely

**Steps to reproduce the behavior**
1.Nabigate to https://makecode.microbit.org/beta#editor
2.Drag the block "play sound" from Music
3.Open the **sound Editor**
4.Click dropdown menu of **Interpolation** 
5.View the parameter of **Interpolation**

**Expect behavior**
Every parameter should show completely

**Actual behavior**
The **Logarithmic** parameter of **Interpolation** shown incompletely
![image](https://user-images.githubusercontent.com/59192069/163556413-88720226-6f47-4bba-92bd-5a4e908de4fb.png)

**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 4.1.21
3.Microsoft MakeCode version: 7.5.13

**Comment by abchatra** [comment]
Fixed
