### ISSUE TITLE
No help page for block "play sound effect"

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4516]
**Describe the bug**
No help doc for block "**play sound**"

**Steps to reproduce the behavior**
1.Nabigate to https://makecode.microbit.org/beta#editor
2.Drag the block "**play sound**" from **Music**
3.Right-click on it and choose **'Help'**

**Expect behavior**
Show the help doc for block "**play sound**"

**Actual behavior**
No help doc for block "**play sound**"
![2](https://user-images.githubusercontent.com/59192069/163557664-bb8be438-308b-41ca-9536-aa3d4b11749e.gif)

**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 4.1.21
3.Microsoft MakeCode version: 7.5.13

**Comment by abchatra** [comment]
@riknoll fyi. Please provide info to @ganicke
