### ISSUE TITLE
Make Volume values consistent

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4520]
Volume values in the new Play Sound Effect block go from 0 to 1023.
But our existing volume values only go up to 255.
It would be great to be consistent with Volume values across blocks.
![image](https://user-images.githubusercontent.com/22108954/163603589-2f1409e2-f769-4189-bfcb-e1899b6e4ec4.png)

Ideally, would be great to be consistent with other values too - right now light goes to 255 and acceleration goes to 1023.

**Comment by riknoll** [comment]
@Jaqster @jaustin @abchatra I'm switching this to be 0-255 to match the other volume and the sensor blocks from input (sound level, light level)
