### ISSUE TITLE
Rename new Play Sound block

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4523]
Rename this block to "Play Sound Effect" or something, so we don't have 2 Play Sound blocks...

![image](https://user-images.githubusercontent.com/22108954/163603860-99035391-ac00-46cb-bb82-241caf669c58.png)

**Comment by abchatra** [comment]
Another idea is to have the giggle and other effects as a drop down in an get block which can be dragged into the the play sound block.
