### ISSUE TITLE
Nit-pick: Space between blocks in Toolbox

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4525]
The last sound effect block seems like it's not aligned on the left with other blocks, and there's a bigger space between the previous block.

![image](https://user-images.githubusercontent.com/22108954/163604171-636d13c3-492d-40eb-974d-7e7e3135b819.png)

**Comment by riknoll** [comment]
I opened a PR fixing the block spacing. The left alignment is consistent with all of our other reporter blocks, I think it's always been that way:

<img width="603" alt="Screen Shot 2022-04-15 at 2 44 26 PM" src="https://user-images.githubusercontent.com/13754588/163635551-4322ef5c-8b3d-4ec0-a752-f65053e1c926.png">

Also the same way on micro:bit live
