### ISSUE TITLE
Play melody only plays a few notes

### ISSUE THREAD

**Issue by livcheerful** [microsoft/pxt-microbit#4528]
**Describe the bug**
The simulator doesn't play all the notes in my melody. If I push play in the melody editor, it plays everything, but when the simulator runs the code, it only plays three notes at a waaaay faster speed and wrong octave. It works fine in the old editor, and doesn't repro on my Windows machine (only ChromeOS)

**To Reproduce**
1. Drag out a play melody block
2. Set it to be the reverse scale
3. Let the simulator run
4. The scale isn't playing correctly

This is the program I used, I'm not sure if I can get a video with sound from the Chromebook?
https://makecode.microbit.org/63588-62854-69643-66481

**Desktop (please complete the following information):**
 - OS: Chrome OS
 - Browser Chrome

**Comment by abchatra** [comment]
This is a nice bug. Regression from live. I can repro on /beta on Edge on windows.
