### ISSUE TITLE
new share dialog doesn't show url

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#4529]
**Describe the bug**

![image](https://user-images.githubusercontent.com/5615930/163604717-8e53c63a-09ab-410f-9f1a-efbb2be27d1d.png)

* doesn't show url, which makes it feel like it didn't work to me (after using share button forever)
* the title / description look editable since their just disabled text inputs

**To Reproduce**
1. Go to beta editor
2. open share dialog

**Expected behavior**

* should probably show url unless people are very opposed
* shouldn't look editable as title / description are locked at this point for this share

**Comment by jwunderl** [comment]
new share dialog also lost the ability to click to zoom on the qr code; this was useful when demoing (e.g. help kid make game at bett and pop it up so it's easy for parent in background to grab real quick) but I'm not sure how much it was used in practice.

**Comment by Jaqster** [comment]
I like the old dialog better - shows the link and the QR code clearly, social icons are more colorful, and the new dialog duplicates the project Name and Description fields in 2 windows.
![image](https://user-images.githubusercontent.com/22108954/163608632-05944639-89d7-46f7-9c76-3e9096eca639.png)

**Comment by abchatra** [comment]
@unthinkmedia can we make sure the new one is closer to older one? 

I also like the QR code to be shown by default .

**Comment by unthinkmedia** [comment]
The copy button is missing feedback after click.
![Apr-21-2022 12-59-47](https://user-images.githubusercontent.com/57981398/164512877-26af0e23-ffad-4be4-8d8a-f629b8b9fa45.gif)

**Comment by abchatra** [comment]
@unthinkmedia this is micro:bit we don't have this UI flow here. Please file this on the arcade repo.

**Comment by abchatra** [comment]
What we want is the link shown as before. Micro:bit foundation also wants the link and the QR code shown by default.

**Comment by unthinkmedia** [comment]
Here is an updated design.

![image](https://user-images.githubusercontent.com/57981398/164550628-7787c4bc-21a5-4192-9332-5f8b8c0543d5.png)
 
Figma file can be found here.
https://www.figma.com/file/Jnt1N2yu0OaGKrvRDXhw4L/Share-Flow?node-id=618%3A3607

**Comment by Jaqster** [comment]
Looks good.  And the first dialog remains the same?
![image](https://user-images.githubusercontent.com/22108954/164558946-51171091-bd99-42ff-b6d8-fc914041bd8f.png)

**Comment by unthinkmedia** [comment]
@Jaqster yes that is fine with me, unless there is a reason to change it.  Seems fine to me though.
