### ISSUE TITLE
Sound Effect field editor design polish

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4532]
A few things we could polish up in the new Sound Effect field editor:

1) Can we put the value labels for Frequency and Volume on the outside of the axis?  Sometimes the graph overlays these labels and it looks messy
![image](https://user-images.githubusercontent.com/22108954/163604548-98b77a14-4d9f-4d20-9a20-44dfaea4f7e6.png)

2) Lots of empty space at the bottom of this field editor sometimes (depending on screen size)
![image](https://user-images.githubusercontent.com/22108954/163604614-faf98e1b-6e82-4f04-b937-7e8c61d1b86b.png)

3) Fit the Gallery to the existing Field Editor size.  We've got double scrollbars going on and we could probably shrink the size of each of these gallery items
![image](https://user-images.githubusercontent.com/22108954/163605100-46ac4433-9ada-4f89-9869-8d2cadba7656.png)

4) Also suggest making the Gallery consistent with the Play Melody gallery (play button on right, same look & feel)
![image](https://user-images.githubusercontent.com/22108954/163605209-bff491b4-b3b4-44c4-98ac-6bf6efaf5231.png)

**Comment by abchatra** [comment]
@unthinkmedia FYI
