### ISSUE TITLE
Remove headphone jack wires from Simulator for v2 sound blocks

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4539]
For the v2 sound blocks, remove the wires in the Simulator - it's confusing to show this when we have an onboard speaker that the sound is playing on.
![image](https://user-images.githubusercontent.com/22108954/163606613-50f91a19-12d4-4ce0-aea4-0be09251b436.png)

**Comment by riknoll** [comment]
Fixed!
