### ISSUE TITLE
Dragging to delete a new 'play sound' block doesn't work (beta)

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#4546]
**Describe the bug**
When deleting the new sound effect block, it seems to remain on the canvas and dragging other blocks doesn't work after this.

**To Reproduce**
1. Drag in a sound block
2. try to delete it by dragging

... block doesn't get deleted

**Expected behavior**
As with all other blocks, MakeCode continues working

**Screenshots**
![deleteerror](https://user-images.githubusercontent.com/147113/164240562-14c771c4-c39f-45d6-95cb-cca5e745ec11.gif)

**Comment by jaustin** [comment]
@riknoll

**Comment by riknoll** [comment]
Ah, this is fixed! I just need to bump beta

**Comment by riknoll** [comment]
Live on beta now
