### ISSUE TITLE
3rd view for Tutorial layout

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4553]
Let's cost out adding a 3rd view to the new tutorial layout that shows the Simulator - similar to the old layout.
![image](https://user-images.githubusercontent.com/22108954/164517401-a7c3c97b-e6cb-436f-8684-ef44b5bcc2de.png)

**Comment by abchatra** [comment]
This is implemented by falling back to old layout in tutorial. Implemented for now.
