### ISSUE TITLE
Play Sound sample project on Home Page

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4555]
Hi Galen,
Can you create a short instruction page for this cool project Jonny created to showcase the new Play Sound block?
https://makecode.microbit.org/beta#pub:56912-06342-38446-84712

Thinking it can go in the Music row on the Home Page...
![image](https://user-images.githubusercontent.com/22108954/164566379-b166222e-efee-47c7-8f9b-0159975eba37.png)

Wouldn't publish until we release in June...

**Comment by ganicke** [comment]
Sure, but I hope his code is still valid since @riknoll has changes inflight - #4554.

**Comment by Jaqster** [comment]
Yeah, maybe wait a little bit before doing this - we're not going to publish until June anyways.  I just wanted to put in the queue before I forgot...
