### ISSUE TITLE
Tutorial: Simulator button disappears when switching from tutorial to simulator

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4561]
**Describe the bug**
**Tutorial**: Simulator button disappears when switching from **tutorial** to **simulator**

**Steps to reproduce the behavior**
1.Nabigate to https://makecode.microbit.org/beta#
2.Open any tutorial
3.Click **simulator button** to switch from **tutorial** to **simulator**

**Expect behavior**
Simulator button still exists when switching from **tutorial** to **simulator**
![image](https://user-images.githubusercontent.com/59192069/165015083-6db17b1d-3ae1-4e11-b7cc-00343e77cc6f.png)

**Actual behavior**
Simulator button disappears when switching from **tutorial** to **simulator**
![2](https://user-images.githubusercontent.com/59192069/165015176-fe8480a0-723c-4d46-9b58-364f52205253.gif)

**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 4.1.24
3.Microsoft MakeCode version: 7.5.19

**Comment by abchatra** [comment]
We moved back to old tutorial layout. This bug doesn't exist anymore.
