### ISSUE TITLE
"play sound" blocks are expanded when JS is changed

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#4562]
**Describe the bug**
When editing in blocks...

By switching to JS, editing the JS file and then switching back to blocks all 'play sound' filed editor blocks are expanded to their 'full' setup.

This can be confounding for a user who didn't even know what was happening, and also tricky for a teacher that might want to make small javascript edits and then distribute a simple looking file (as when there are many sounds, it's a long manual process involving lots of clicks to restore them all to the 'minimal' view.

**To Reproduce**
Use a new sound effect field editor block
Switch to JS
Edit the code
Switch back

![soundexpansion](https://user-images.githubusercontent.com/147113/165046979-f2578467-8842-4935-9e15-39615940f2ba.gif)

**Expected behavior**

I think users will expect the blocks to go back to the same level of expansion as they were before the switched to JavaScript.

If this is not possible I think it's probably preferable to restore to the minimal form not the maximal one, but I think we should ask some teachers about that if there's not clear consensus here.

**Comment by riknoll** [comment]
Yeah, it's pretty tough to preserve the collapse state since it's not present in the TS. I can certainly switch it to be collapsed if that's preferable
