### ISSUE TITLE
Show LED's block is missing from Flashing Heart Japanese version

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4566]
Repro - 
- Open Flashing Heart tutorial in Japanese
- In the first step, expected behavior is to see the Show LED's block in the Toolbox

![image](https://user-images.githubusercontent.com/22108954/165136675-92101803-853b-4652-bcba-d77c3afb0236.png)

Reported by a customer: https://twitter.com/Meso_blog/status/1513404033599668224

**Comment by ganicke** [comment]
Removed translation of the code snippet.
