### ISSUE TITLE
extensions: search for jacdac does not find package

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#4568]
**Describe the bug**
The pxt-jacdac package should be found when searching for "jacdac"

**To Reproduce**

- search 'jacdac' in extensions dialog

![image](https://user-images.githubusercontent.com/4175913/165364148-288c12d0-6386-475c-9503-83d27ad8e3cc.png)

**Comment by abchatra** [comment]
Fixed
