### ISSUE TITLE
extensions: image distorded

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#4569]
**Describe the bug**
The bitbot image is squished

![image](https://user-images.githubusercontent.com/4175913/165364565-b9037cad-6221-4ed3-8605-79b61598f901.png)

and it shoud look like this https://github.com/4tronix/BitBot/blob/master/icon.png

![image](https://user-images.githubusercontent.com/4175913/165364668-85140e51-276d-4ba9-9e5c-2f6545523fee.png)

**Comment by riknoll** [comment]
Fixed by https://github.com/microsoft/pxt/pull/8853
