### ISSUE TITLE
extensions: missing icon should be handled gracefully

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#4570]
The bluetooth-temperature-sensor is missing an icon; which then looks ugly on the web site. We should have some kind of skeleton filling.

![image](https://user-images.githubusercontent.com/4175913/165364829-5c450eb9-039e-4ef5-a33b-523370612646.png)

**Comment by jwunderl** [comment]
This one still repros as an infinite spinner

![image](https://user-images.githubusercontent.com/5615930/170317679-5a9cb5cc-8023-4167-903e-91920caba89e.png)

Also, worth a note that for unapproved extensions it ends up trying to request `https://makecode.microbit.org/null` ~~

**Comment by aznhassan** [comment]
Thoughts on just using the font awesome image icon if the extension card image doesn't load?
![image](https://user-images.githubusercontent.com/6496798/172724876-b264207b-208d-4776-9588-539e649bfd81.png)

@jwunderl

**Comment by jwunderl** [comment]
I like it~

**Comment by aznhassan** [comment]
Are there other examples of what we do when content is missing?

**Comment by jwunderl** [comment]
I can't think of any right away -- the home screen carousels just use a gray fill in place of the image until it loads / if there's an error

![image](https://user-images.githubusercontent.com/5615930/172728924-147e4342-4e1c-4ed9-8b95-217659cd263b.png)

but icon seems just as good / better~
