### ISSUE TITLE
extensions: jacdac defeats the "remove blocks" logic

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#4573]
Not sure how the heuristic works to specifc which extensions should be removed from the toolbox, but Jacdac introduces a "Modules" folder and there is no X button.

![image](https://user-images.githubusercontent.com/4175913/165366369-9a48863b-3f8d-4fbc-9120-27777f1b48c0.png)

**Comment by abchatra** [comment]
Removed the option to delete for now.
