### ISSUE TITLE
extensions: (minor) empty search results messaging needs improvement

### ISSUE THREAD

**Issue by eanders-ms** [microsoft/pxt-microbit#4577]
When there are no search results, it shows a "Home" link. It isn't clear where this would navigate to. Instead, show "No results found".

![image](https://user-images.githubusercontent.com/12176807/165392738-e8a469f0-3807-42a4-8782-e471d241615c.png)

**Comment by aznhassan** [comment]
@eanders-ms we now let the user know that we couldn't find any extensions matching their search term. Is that enough, or are you asking to remove the _home_ link?

![image](https://user-images.githubusercontent.com/6496798/167942181-70581137-ac1c-4228-80b7-b96a9962e8ff.png)

**Comment by eanders-ms** [comment]
Looks perfect!

**Comment by aznhassan** [comment]
Sweet, I'll go ahead and close this bug then!
