### ISSUE TITLE
Searching data streamer keyword doesn't result in any results

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#4578]
1. Go to 'extensions'
2. Search for "data streamer"
3. No results

**Expected behavior**
Data streamer extension shows up.
![image](https://user-images.githubusercontent.com/6107272/165393027-661b74fb-3c53-456c-b4f2-6cdebced849c.png)

**Comment by aznhassan** [comment]
This is similar to (or a duplicate of) #4568

**Comment by abchatra** [comment]
Fixed
