### ISSUE TITLE
Flashlog extension should be hidden

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#4582]
**To Reproduce**
1. Go to 'Extensions'
2. See 'filelog extensino'

This extension should be an hidden extension.

**Screenshots**
![image](https://user-images.githubusercontent.com/6107272/165393556-b121a304-17af-4342-b62d-0dd5270532c8.png)

**Comment by jwunderl** [comment]
(it's currently ignoring the 'searchOnly' flag in pxt.json for the built in extensions: https://github.com/microsoft/pxt-microbit/blob/master/libs/flashlog/pxt.json#L13)

**Comment by aznhassan** [comment]
Fixed this with my most recent pull request. Ended up bring back the logic to:
* hide _searchOnly_ extensions unless we are searching
* hide extensions that are already included with the program
* sort the bundled extensions using the same comparator we did in the old extension modal
