### ISSUE TITLE
Share Project description doesn't get changed on new share dialog

### ISSUE THREAD

**Issue by dmonroym** [microsoft/pxt-microbit#4584]
When you go to share a project and insert new text on the description dialog it seems like it's not getting stored anywhere.

<img width="484" alt="image" src="https://user-images.githubusercontent.com/3288375/165394030-24c07e1d-77d1-4d3a-a5d7-96b6c4ad1d72.png">
It should be overwritting the "Made with ❤️ in Microsoft MakeCode for micro:bit." but when sharing the link https://makecode.microbit.org/_AzKfKaL4s2Wa I get this:
<img width="439" alt="image" src="https://user-images.githubusercontent.com/3288375/165394549-f85f1f92-2b19-4500-8336-c5ca11c1d8ad.png">

**Comment by riknoll** [comment]
@abchatra I think we should remove this one from the release. I'm not really sure what the fix entails

**Comment by abchatra** [comment]
I am taking this away from this release.

**Comment by abchatra** [comment]
Text box is removed now. Fixed
