### ISSUE TITLE
Bluetooth extension missing icon

### ISSUE THREAD

**Issue by ElizabethRiffle** [microsoft/pxt-microbit#4586]
![image](https://user-images.githubusercontent.com/14082525/165395897-a7aa3c40-77ca-4b7c-954d-16f4bd3053af.png)

**Comment by Sheila111** [comment]
**Robotbit** extension also missing icon
![image](https://user-images.githubusercontent.com/59192069/165452839-f619e2ae-92e9-4e95-88ae-b09d25e821ea.png)
