### ISSUE TITLE
Most extensions don't have "learn more"- makes it less usable

### ISSUE THREAD

**Issue by ElizabethRiffle** [microsoft/pxt-microbit#4587]
![image](https://user-images.githubusercontent.com/14082525/165396402-df03ed1e-a8d9-46cf-9226-5a00f154bc44.png)

**Comment by aznhassan** [comment]
These are built-in extensions, where would one find the learn-more for them? @abchatra

**Comment by abchatra** [comment]
This is not a regression. I will unmark from this release. We will figure out in the future.
