### ISSUE TITLE
extensions cards: long descriptions overflow into learn more on cards

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#4593]
**Describe the bug**

**To Reproduce**
1. Go to extensions page robotics category
2. scroll down to find `CooCoo` extension card

**Expected behavior**

should clip text within div or maybe make it scrollable?

**Screenshots**

![image](https://user-images.githubusercontent.com/5615930/165399109-d1cb49f9-7d5f-49f9-b2db-75596f9d6a3a.png)

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).

**Comment by abchatra** [comment]
This is interesting. We seem to display different information than before. 
![image](https://user-images.githubusercontent.com/6107272/165420534-05d479e1-c163-431a-958a-a69c959e4b82.png)

**Comment by riknoll** [comment]
Fixed by https://github.com/microsoft/pxt/pull/8853
