### ISSUE TITLE
new script button size different from my scripts

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#4597]
- use client size 720px x 880px
- notice that buttons have different sizes

<img width="732" alt="image" src="https://user-images.githubusercontent.com/4175913/165551692-f6a5843e-4567-44ef-8b97-329dc66999b0.png">

**Comment by Jaqster** [comment]
dup of https://github.com/microsoft/pxt-microbit/issues/4557 ?

**Comment by abchatra** [comment]
Yes dupe of #4557
