### ISSUE TITLE
view all list mode selection does not show highlight

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#4598]
- open editor
- click view all
- click on a row and see that toolbar is selectd
- none of the buttons work, corner is not visibl
![2022-04-27 08 16 12](https://user-images.githubusercontent.com/4175913/165552391-39ff1a5b-644d-43c2-9157-956132e3723f.gif)
e

**Comment by kimprice** [comment]
I can't repro this on the latest version. We must've already fixed this bug.

**Comment by kimprice** [comment]
Actually, I'm seeing it in beta now.

**Comment by pelikhan** [comment]
I really prefer the list view btw, imo we should simplify and just support that one. For a future design meeting.
________________________________

**Comment by kimprice** [comment]
Maybe the list view should also have the icon for whether it's a blocks, JavaScript, or Python project.
