### ISSUE TITLE
Removing dependency fails (crash)

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#4599]
- import https://github.com/pelikhan/yahboom-microbit-led-jacdac/tree/deleterepo
- open explorer
- try to remove neopixel

<img width="430" alt="image" src="https://user-images.githubusercontent.com/4175913/165552946-7b5d6237-20df-4c40-b0d0-8ecc40325af4.png">

**Comment by abchatra** [comment]
Removed the option to delete for now.
