### ISSUE TITLE
60% of extension screen is search + category chips

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#4600]
This is a screenshot of my retina screen; most of the UI is search + chips and we're only able to show 3 extensions before scrolling.

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/4175913/165553742-a64ec1a4-e233-4dcd-bfd8-0560289e27d8.png">

**Comment by Jaqster** [comment]
@unthinkmedia / @BeckHaru - for small screens this will be an issue.  Can we make the top of the page shorter?

**Comment by pelikhan** [comment]
not just small, 15' macbookpro
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/4175913/165588701-a014508a-0e7c-4e25-8add-610c400fc309.png">

**Comment by unthinkmedia** [comment]
Yes, I will tighten all this up at Chromebook dimensions tomorrow.

**Comment by BeckHaru** [comment]
can we have responsive designs based on the device?
________________________________

**Comment by unthinkmedia** [comment]
Here is a tighter implementation. That increases the space by around 120
px. You will notice that I also reduced the header size to 32 from 36px.

[image: image.png]
