### ISSUE TITLE
Top level extension dialogue contains odd things

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#4604]
With the new extension dialogue, extensions that are already in your projects are there...

In this screenshot I think:
* radio, microphone,  shouldn't be there (because they're already in)
* flashlog, shouldn't be there #4582 
* servo and bluetooth maybe have precedence too high.
* neopixel maybe should have an icon to match the style of the others?

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/147113/165791710-de4426ff-4371-48ec-9ec7-e12fd6b10902.png">

**Comment by aznhassan** [comment]
I have a PR out that will fix the first three, but I suggest creating another bug for the last one since it does not pertain to the extension page itself but rather the neopixel extension.
