### ISSUE TITLE
image missing in unpair dialog

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt-microbit#4611]
![image](https://user-images.githubusercontent.com/10767146/165647088-ef934304-04e8-4e23-8550-22a0bdb54664.png)

**Comment by kimprice** [comment]
I'm unable to repro. Looks like it's working fine.
![image](https://user-images.githubusercontent.com/15070078/169567486-07b1f4e2-c91f-40b7-9c27-afa36a3d406b.png)
