### ISSUE TITLE
Snapshotof sound is dark rather than light

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4613]
Snapshot (right click > Snapshot)
![sound-screenshot](https://user-images.githubusercontent.com/31242877/166706816-1f4c04cb-a84e-4547-894b-20d21327166b.png)

Screenshot
<img width="362" alt="image" src="https://user-images.githubusercontent.com/31242877/166706998-6356ab93-f34b-4d30-9215-a65f30d37d4a.png">

**Comment by Jaqster** [comment]
Duplicate: https://github.com/microsoft/pxt-microbit/issues/4602 and this is fixed.
