### ISSUE TITLE
New extension dialog: SSD1306_OLED extension accumulates as I click tags

### ISSUE THREAD

**Issue by eanders-ms** [microsoft/pxt-microbit#4617]
In the new extensions dialog, when I click the "Display" category, the SSD_1306_OLED extension card is included in the filtered results, as expected. But when I then click a different category, the results are cleared and replaced with the new set of cards, _except the OLED extension remains_. Each time I click the "Display" category and then click away to a different category, another OLED card is accumulated.

Testing in @aznhassan's uploaded target: https://microbit.staging.pxt.io/app/7d4f2cbcdc290eee97e1adf36a18cdb11eab985d-09292bbbde (from PR https://github.com/microsoft/pxt/pull/8819).

Repro steps:
```basic
10 PRINT "Open the microbit target above"
20 PRINT "Create a new project"
30 PRINT "Go to the extensions dialog"
40 GOSUB 90
50 GOSUB 90
60 GOSUB 90
70 PRINT "Notice each time you click the 'Display' category, an SSD_1306_OLED card is accumulated"
80 END
90 PRINT "Click the 'Display' category"
100 PRINT "Click on a different category"
110 RETURN
```

![hhhhhnjjjjjj](https://user-images.githubusercontent.com/12176807/166845574-25e598aa-6727-4dfa-9e4e-839746920e0f.gif)

**Comment by aznhassan** [comment]
I was giving extension cards keys based on the extension's name. There are two different SSD1306_OLED extensions on the page leading to a key collision followed by the oddness you see in the gif above. Changing the keys to just be based of the extension's index fixes the issue. Good catch!

**Comment by pelikhan** [comment]
the extension URL should be unique unless you plan to have duplicate cards

**Comment by aznhassan** [comment]
We're using the ExtensionMeta which contains a ParsedRepo, neither object has the URL of the extension. There is `fullName` which matches the GitHub slug of the extension. Is there a benefit to using the slug as the key instead of just an index?

**Comment by pelikhan** [comment]
It helps React reconcile the threes when switching categories, not critical here.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
