### ISSUE TITLE
Sound Editor: Add setting to set same volume or frequency to time slot

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4619]
Highlighting this feedback here.

Needs understanding/scoping a little more as a feature request for improvement

![image](https://user-images.githubusercontent.com/31242877/166894704-7439d456-430b-4526-ac2a-19ea375394a9.png)

Further context:

It would be cool if I could set the same value to both sides of the frequency slider or volume slider somehow. I think it would be better if you could make an area where you can type in the value for the frequency or volume for the new sound blocks, so you don't have to use your mouse to set the precise frequency or volume. Just a suggestion, but I think it would be useful.

**Comment by microbit-mark** [comment]
^ Some nice initial feedback on the sound editor @Jaqster @unthinkmedia @riknoll 🎉

**Comment by abchatra** [comment]
We have decided not to fix this as current behavior seems most discoverable.

**Comment by abchatra** [comment]
We will address some of it in https://github.com/microsoft/pxt-microbit/issues/4704
