### ISSUE TITLE
New extension dialog: Search returns fewer results

### ISSUE THREAD

**Issue by eanders-ms** [microsoft/pxt-microbit#4621]
In the current extension dialog: a search for "kitronik", returns 25 results.
In the new dialog: a search for "kitronik" returns 10 results.

Many extensions are not just missing from search results, they're completely undiscoverable. For example, one of the omitted results was "kitronik-game-controller". Searching for this extension by exact name yields nothing.

**Comment by martinwork** [comment]
Related: https://github.com/microsoft/pxt-microbit/issues/4596#issuecomment-1119811614
I don't think that fix is in beta yet.

**Comment by eanders-ms** [comment]
Ah thanks @martinwork. I will test again once that change hits beta.

**Comment by abchatra** [comment]
This is going to be fixed soon as soon as we bump today.
