### ISSUE TITLE
Extension button in toolbox in different places

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#4622]
Top level in blocks, advanced in text editors.

**Comment by abchatra** [comment]
Basically we elevated extensions to above advanced in the blocks and we need to do the same in javascript toolbox as well
![image](https://user-images.githubusercontent.com/6107272/167957918-c52cb5a7-c83c-48ad-b20e-95ecf3da1d52.png)

**Comment by abchatra** [comment]
![image](https://user-images.githubusercontent.com/6107272/167957980-bda125fb-523d-46ba-be4e-63362b8adddd.png)
