### ISSUE TITLE
How to search extension in the specific tag?

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4624]
**Describe the bug**
How to search **extension** in the specific **tag**?

**Steps to reproduce the behavior**
1.Nabigate to https://makecode.microbit.org/beta#editor
2.Click **Extensions**
3.Select a **tag**
4.Type some key words in search box and search

**Expect behavior**
Search result is under this **tag**

**Actual behavior**
Search result is under **all extensions**
![1](https://user-images.githubusercontent.com/59192069/167567931-f235cf82-770d-4b93-a4dd-360650027f09.gif)

**Additional context**
1.OS: Windows10
2.makecode.microbit.org version: 4.1.32
3.Microsoft MakeCode version: 7.5.29

**Comment by abchatra** [comment]
The selected tag should be cleared when you type on search or atleast when the search results are displayed.
