### ISSUE TITLE
Extension: Installed list is empty

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4625]
**Describe the bug**
**Extension**: **Installed list** is empty

**Steps to reproduce the behavior**
1.Nabigate to https://makecode.microbit.org/beta#editor
2.Click **Extensions**
3.Click "**Installed"**

**Expect behavior**
There shows "Radio" extension under **Installed list**

**Actual behavior**
**Installed list** is empty but '**Radio**' extension has been installed
![2](https://user-images.githubusercontent.com/59192069/167595508-c1cc04ea-56d5-4737-8e64-ea2bed8c4106.gif)

**Additional context**
1.OS: Windows10
2.makecode.microbit.org version: 4.1.32
3.Microsoft MakeCode version: 7.5.29

**Comment by abchatra** [comment]
We removed Installed for now and this is fixed.
