### ISSUE TITLE
Orientation is forced to portrait which is odd for many Android tablets

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#4629]
I'm not sure whether I've found the actual reason for this, but I've just installed the PWA using Chrome on Android.

I suspect this line is implicated: https://github.com/microsoft/pxt-microbit/blob/46003450ddb5720aa3fc280f83e227bad52160bb/webmanifest.json#L4

When I open the PWA, I get the tablet forced to portrait mode, independent of the orientation of the device. This is annoying because most tablet keyoards expect the device to be in Landscape, and programming with a tablet makes much more sense with a keyboard.

Is there a reason to force portrait mode?

**Comment by abchatra** [comment]
@jaustin did you try /beta?

**Comment by martinwork** [comment]
Reported in ticket https://support.microbit.org/helpdesk/tickets/60493 (private)

@abchatra If I go to beta in Chrome on Android and install the PWA, the installed app launches live stuck in portrait.

"orientation" is still "portrait"
https://github.com/microsoft/pxt-microbit/blob/master/webmanifest.json#L4
