### ISSUE TITLE
Extension repositories with main instead of master cannot be imported

### ISSUE THREAD

**Issue by JohnVidler** [microsoft/pxt-microbit#4633]
**Describe the bug**
Importing a repository which uses `main` rather than the legacy `master` causes the import to fail.

**To Reproduce**
1. Create a new extension using the now-default `main` branch
2. Push this repository to github
3. Use the github URL in the homepage -> import -> import-URL menu
4. The extension/repository fails to be added

**Expected behavior**
The project is imported into the users workspace

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome and/or Firefox
 - Version Firefox: 100, Chrome 101.0.4951.64

**Makecode Versions:**
- makecode.microbit.org version:  [4.1.35](https://github.com/Microsoft/pxt-microbit/releases/tag/v4.1.35)
- Microsoft MakeCode version:  [7.5.33](https://github.com/Microsoft/pxt/releases/tag/v7.5.33)
- microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
- codal-microbit-v2 runtime version:  [v0.2.37](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.37)

**Comment by JohnVidler** [comment]
For anyone hitting this, for now the kludge is to create a new branch in your repo called `master` and develop there. MakeCode then allows you to import this into the editor like any other repository.

**Comment by eanders-ms** [comment]
Fixed via https://github.com/microsoft/pxt/pull/8886
