### ISSUE TITLE
Touch screen control for the sound effect editor is finicky

### ISSUE THREAD

**Issue by kimprice** [microsoft/pxt-microbit#4650]
**Describe the bug**
It is very difficult to move the endpoints of frequency and volume in the sound effect editor via touchscreen.

**To Reproduce**
1. Open the sound effect editor
2. Click on the endpoints for the Frequency and Volume

**micro:bit version (please complete the following information):**
    - makecode.microbit.org version:  [4.1.35](https://github.com/Microsoft/pxt-microbit/releases/tag/v4.1.35)
    - Microsoft MakeCode version:  [7.5.33](https://github.com/Microsoft/pxt/releases/tag/v7.5.33)
    - microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
    - codal-microbit-v2 runtime version:  [v0.2.37](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.37)

**Desktop (please complete the following information):**
 - OS: Chrome OS Version 
 - Browser: chrome
 - Version 98.0.4758.107

**Comment by riknoll** [comment]
this should be fixed by https://github.com/microsoft/pxt/pull/8836
