### ISSUE TITLE
Python basic.show_leds() indents the string incorrectly

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#4665]
https://support.microbit.org/a/tickets/53675 (private)

**Describe the bug**
In the Python code editor, the `basic.show_leds()` string argument is not aligned correctly.
This is not an issue with the JavaScript code view.

**To Reproduce**
1. Go to https://makecode.microbit.org
2. Drop the "show LEDs" block
3. Switch to Python code
4. See the string alignment:

```python
basic.show_leds("""
    # . . . .
        # . . . .
        # . . . .
        # . . . .
        # . . . .
""")
```

**Expected behavior**
Each line of the string to have the same indentation.

**Screenshots**

<img width="422" alt="image" src="https://user-images.githubusercontent.com/29712657/169298774-0ea7bdc6-6b92-4b67-9ca8-0027edfa287f.png">

<img width="413" alt="image" src="https://user-images.githubusercontent.com/29712657/169298190-5b30f9b5-9b78-4a2f-b99a-fc9ad3e7ebe6.png">

**micro:bit version (please complete the following information):**

N/A

**Desktop (please complete the following information):**
 - OS: macOS 11
 - Browser: Chome
 - Version: 101

**Smartphone (please complete the following information):**
N/A

**Additional context**

makecode.microbit.org version:  [4.0.18](https://github.com/Microsoft/pxt-microbit/releases/tag/v4.0.18)

Microsoft MakeCode version:  [7.0.14](https://github.com/Microsoft/pxt/releases/tag/v7.0.14)

microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)

codal-microbit-v2 runtime version:  [v0.2.32](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.32)

**Comment by microbit-carlos** [comment]
This is somewhat related to https://github.com/microsoft/pxt-microbit/issues/3116, but not misalignment is not the same.

**Comment by abchatra** [comment]
I can reproduce this. The indentation differs in intelligence and when you go to blocks and back. Ideally it should be consistent.

**Comment by abchatra** [comment]
Likely fix in blocks->text compiler and the pyhon intelliense

**Comment by abchatra** [comment]
Also evaluate moving to pywrite intellisense instead of our own.

**Comment by jwunderl** [comment]
closing as dup of https://github.com/microsoft/pxt-microbit/issues/4891 (this one was filed first, but the other one has a few more samples with it being extra bad & @benvillalobos already assigned himself that one~)
