### ISSUE TITLE
web USB reset of micro:bit upsets data logging programs

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#4681]
When data logging, the micro:bit has a timestamp which is 'time since boot' - this is nice for quickly previewing data. 

If you plug in a battery and then do things over a long period of time the time stamps are reliable, except if you are using MakeCode and web USB - in which case the micro:bit gets arbitrarily reset in a set of cases - certainly when you plug the micro:bit back in while web USB is connected.

The result is that your data doesn't have continuous time stamps.

Is it possible to avoid resetting the micro:bit so often with web USB? 

CC @martinwork who noticed that beta does this more than live in https://github.com/microsoft/pxt-microbit/issues/4676#issuecomment-1133945430

**Comment by martinwork** [comment]
Related: https://github.com/microsoft/pxt-microbit/issues/3418

**Comment by pelikhan** [comment]
This is a daplink issue, it resets when setting the baudrate.

**Comment by jaustin** [comment]
Do you have to set the buadrate? If MakeCode is always 115200 and the micro:bit defaults to that, is it actually necessary?

**Comment by pelikhan** [comment]
We don't know if the user flashed a program using another environment or changed the baudrate

**Comment by jaustin** [comment]
But if they have serial at a different baudrate, MakeCode doesn't support that anyway (eg #3537) , and if they changed the baudrate somewhere else, that's a pretty uncommon use-case to drive resetting everyone's board (and therefore resetting all timestamps on data logging programs).

**Comment by pelikhan** [comment]
Any change in this space would require testing accross (1) V1 vs V2 (2) data logger vs not data logger (3) all versions of DapLink in circulation.

**Comment by pelikhan** [comment]
Added flags to skip those resets: https://github.com/microsoft/pxt-microbit/commit/347f1e11e66fb3001f644435b83592c76e133d6f

**Comment by abchatra** [comment]
Fixed

**Comment by abchatra** [comment]
We reset while setting the baud rate for logging.

**Comment by abchatra** [comment]
For the next release get rid of the second reset.
