### ISSUE TITLE
V1 Yotta target needs to be updated

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#4684]
Basically this line:

https://github.com/microsoft/pxt-microbit/blob/09c107825802d77f8659fc84113fc910bcfc127e/pxtarget.json#L140

Should be updated to `bbc-microbit-classic-gcc@https://github.com/lancaster-university/yotta-target-bbc-microbit-classic-gcc`, as the Yotta registry is no longer operational and it needs to download the target directly from a GitHub repo.

Without this change I wasn't able to build locally for V1.

**Comment by abchatra** [comment]
@microbit-carlos can you produce a PR?

**Comment by microbit-carlos** [comment]
https://github.com/microsoft/pxt-microbit/pull/4687
