### ISSUE TITLE
Beta: Can't add unnaproved extensions

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4690]
Latest beta seems to get stuck adding extensions

![Screenshot2022_05_25_105439](https://user-images.githubusercontent.com/31242877/170270831-9b3475a1-fe33-4ab4-9c93-45f12212ac82.jpg)

Try adding https://github.com/lancaster-university/pxt-codal-audio or https://github.com/carlosperate/pxt-banana to extensions

They appear in search with a spinning wheel instead of the icon, you can click on them to add but they do not appear in the toolbox and there does not appear to be any error.

**Comment by microbit-carlos** [comment]
From the JS console I get:
```
pxtapp.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'upgrades')
    at P (pxtapp.js:1:207545)
    at U (pxtapp.js:1:207579)
    at Object.y [as downloadPackageAsync] (pxtapp.js:1:204726)
    at async Object.t.downloadLatestPackageAsync (pxtapp.js:1:210725)
    at async R (main.js:1:584998)
```

<img width="537" alt="image" src="https://user-images.githubusercontent.com/29712657/170271304-1cdb34e3-24e8-4c0e-931b-8239a474c671.png">

**Comment by jwunderl** [comment]
(whoops, fix will be out with next beta bump in a little bit, thanks for pointing this out)
