### ISSUE TITLE
Extension will load if opening at the first time

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4698]
**Describe the bug**
**Extension** will load if opening at the first time

**Steps to reproduce the behavior**
1.Nabigate to https://makecode.microbit.org/beta#editor
2.Click **Extensions**
3.Click a tag

**Actual behavior**
**Extension** will load if opening at the first time
![2](https://user-images.githubusercontent.com/59192069/170455677-d5c4dbeb-0361-44ed-a964-1a5eb4e47e33.gif)

**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 4.1.44
3.Microsoft MakeCode version: 7.5.443

**Comment by abchatra** [comment]
@Sheila111 I do not understand this bug. Images take time to load as we fetch lazily. There is not much we can do to load it faster.

**Comment by Sheila111** [comment]
The issue is that I think it takes time to load Extensions' image at the first time. And I understand what you mean. So, is this by design?

**Comment by abchatra** [comment]
Yes by design
