### ISSUE TITLE
Frequency and Volume sliders in Play Sound block field editor

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4704]
From our usability study, we found that it was hard for students to select a specific value (i.e. 500Hz) from the Frequency and Volume sliders in the Play Sound block field editor.  Ideas to solve:
- 'Snap' sliders to round number increments
- Display a text input field on click

![image](https://user-images.githubusercontent.com/22108954/170769762-084dd90b-dfb5-4c57-942a-23d3b52fccf8.png)

**Comment by microbit-mark** [comment]
A text input field was also requested by a user in micro:bit support

**Comment by jaustin** [comment]
I think a text input field would be brilliant - perhaps clicking on that handle? This would allow us to also display things like variables too - I know I've posted something a bit like this before but something that the user could interact with would be great...
<img width="633" alt="image" src="https://user-images.githubusercontent.com/147113/171009467-c5b397f8-8bd7-4b9f-bd92-eeebc5373bea.png">

For example, if the text box was removed when there was a variable it would help...
<img width="631" alt="image" src="https://user-images.githubusercontent.com/147113/171009747-993f3300-4ab8-410e-9c2d-21d26f8802a9.png">

**Comment by clkantner** [comment]
@abchatra assigned, based on design crit discussion we will pause and see how current release feedback validates this as something to revisit
