### ISSUE TITLE
Increase discoverability of Generate Similar Sound

### ISSUE THREAD

**Issue by ElizabethRiffle** [microsoft/pxt-microbit#4709]
When asked to create a similar sound 4/5 Insiders manually created their own sound instead of using the Generate Similar Sound function most likely because it didn't stick out to them amongst the rest of the sound editor UI.
![image](https://user-images.githubusercontent.com/14082525/170803883-eb8ff7d5-2738-4ff3-ab67-b5fc7fd4ec7b.png)

**Comment by clkantner** [comment]
@abchatra assigned, based on design crit discussion we will pause and see how current release feedback validates this as something to revisit
