### ISSUE TITLE
Data Logger block too long

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4716]
For small screens, very hard to work with the block.
Suggest moving to multi-line split after 2 fields.
![image](https://user-images.githubusercontent.com/22108954/171918666-6c214a91-a928-4380-a9bf-38888c7e2c53.png)

**Comment by asmeets** [comment]
On the iOS side, the set columns block drops to a vertical view after five column names. The log data block does as well, as referenced by @Jaqster, but given the size of the original block, this does present a challenge.
