### ISSUE TITLE
Spacebar does not work in Extension Search block

### ISSUE THREAD

**Issue by unthinkmedia** [microsoft/pxt-microbit#4717]
**Describe the bug**
When on the extensions window I was trying to type "data logger", but the spacebar was not being recognized and forcing me to type "datalogger".  This happens regardless of what I am typing.

**To Reproduce**
1. Go to makecode.microbit.com/beta
2. Click on 'Extensions
3. Type a few characters and then hit space and try to type more charectors
4. See how there is no space that was recognized

**Expected behavior**
I should be able to add any space I want to my search

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome and Safari

**Additional context**
I noticed that when I hit Space the window refreshes. It may be mapped to the return key?

<img width="1607" alt="Screen Shot 2022-06-03 at 1 50 39 PM" src="https://user-images.githubusercontent.com/57981398/171919328-6ebb065d-da27-43f8-8b8b-8e23d2195b65.png">

**Comment by aznhassan** [comment]
I believe this is by design, @riknoll?
