### ISSUE TITLE
Play Sound block not reliably playing on hardware

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4720]
Repro - I have a bunch of music sounds in a Button pressed event
When I download (through Web USB) to the micro:bit and press button A, I don't hear the second Play Sound block.  Then when I press button A again, nothing plays.
I am on Windows, Edge, with a micro:bit V2.2
test project - https://makecode.microbit.org/_FA8hVFe49e9u

**Comment by jaustin** [comment]
@JohnVidler this looks similar to the issue we saw on support that @microbit-pauline couldn't get to reproduce in /beta. 

@Jaqster I think this sample program gets munged because the link doesn't open in /beta - can I modify the URL to load it in /beta or can you please share the TypeScript?

Does this need specific parameters in play sound? I've been using it a lot in programs and haven't seen this. However we did notice some interesting timing issues earlier this week that could be related. CC @microbit-carlos

**Comment by Jaqster** [comment]
Can't you just go to https://makecode.microbit.org/beta then click the Import button to copy/paste this URL?

**Comment by jaustin** [comment]
Yes, thanks. Didn't know that route. I wonder if the issue here is the combo of 'old' music blocks and new, which I think gives us multiple mixer channels.

**Comment by jaustin** [comment]
@Jaqster querying the P2 label on this - seems more like a P1 or P0 to me. Is there a mitigation for this or does it only happen in a subset of situations?

**Comment by JohnVidler** [comment]
I've boiled this down to a minimal program with just a play sound block in a button event:

![image](https://user-images.githubusercontent.com/537325/172178494-8ff3246e-8eb8-490e-b6e4-4d050915a9f2.png)

It appears that if I set _anything_ else, it works fine, but setting the interpolation to log results in the behaviour described here, so there's definitely something funky with the synth log generator.

Will investigate further.

**Comment by JohnVidler** [comment]
Additional note - playing both audio routes (melody and sound) works just fine, provided that the sound generator isn't using log interpolation.

**Comment by jaustin** [comment]
So if this is limited to log interpolation, I'm happy with the P2 label too.

**Comment by JohnVidler** [comment]
After further investigation, it seems that the log effect generator results in extreme values at both ends of the scale. Super high values from an effect result in the board locking up, and negative values result in unpleasent clicks from the speaker.

For now, as time is short for the 2022 Makecode release, I've implemented some hard stops for just this effect ( see https://github.com/lancaster-university/codal-microbit-v2/blob/master/source/SoundSynthesizerEffects.cpp#L102 ) which anyone wanting to test this can pull in right now, but ultimately this probably means we need to check the edge cases for each generator just in case.

This does avoid the hard stop that @Jaqster originally reported, and works for testing on the next tag.

I'm going to leave this open for now, however, but demote its priority back down to P3 so we can track testing the other generators.

**Comment by pelikhan** [comment]
Pushed

**Comment by abchatra** [comment]
Fixed.
