### ISSUE TITLE
Banner at the top of the page is difficult to navigate

### ISSUE THREAD

**Issue by clkantner** [microsoft/pxt-microbit#4721]
Describe your design or art need by answering the questions below: 

## What are the requirements for the project? 
Explore other ways of having the banner content accessible. 

## Is there a deadline or date this is needed by? 
No

## Please share any existing references, screenshots, links, etc. here that will help us better understand your requirements 
<img width="1578" alt="Screen Shot 2022-06-03 at 11 41 19 AM" src="https://user-images.githubusercontent.com/106267801/171926598-6a0fbcae-9277-4091-a81c-765d39c2ca38.png">

breaking the pattern used with below content, where arrows are used to move, and the circle buttons are very small to click and don't look clickable

### What audience is this request for? 
All users

### How will we measure if this is successful or not?

Conduct user testing

**Comment by abchatra** [comment]
@clkantner please add additional details in this issue. Ideally anyone reading this should have complete picture to go and address the issue. Screenshots and step by step repro steps are great to add to this issue.
