### ISSUE TITLE
The button hover states have design inconsistencies

### ISSUE THREAD

**Issue by clkantner** [microsoft/pxt-microbit#4722]
The buttons are inconsistent and buggy, particularly in 'closing' scenarios
<img width="1246" alt="Screen Shot 2022-06-03 at 11 22 30 AM" src="https://user-images.githubusercontent.com/106267801/171924548-dc582dbd-9553-446a-a930-2ca649553b6e.png">

<img width="873" alt="Screen Shot 2022-06-03 at 11 23 10 AM" src="https://user-images.githubusercontent.com/106267801/171924565-5167a64e-da72-4e3e-8000-09f597930c04.png">
<img width="1256" alt="Screen Shot 2022-06-03 at 11 24 42 AM" src="https://user-images.githubusercontent.com/106267801/171924578-8780acaf-6fb6-4d08-aada-ccc08c4b97ff.png">
<img width="1336" alt="Screen Shot 2022-06-03 at 11 26 44 AM" src="https://user-images.githubusercontent.com/106267801/171924592-93ec906d-8c1c-4fde-a067-5a4312838638.png">
<img width="1191" alt="Screen Shot 2022-06-03 at 11 26 50 AM" src="https://user-images.githubusercontent.com/106267801/171924599-ffae942a-375b-4561-aa69-5147561af3e7.png">

Describe your design or art need by answering the questions below:

**Comment by abchatra** [comment]
I agree they are inconsistent. Can you please explain why they are buggy? Do they not close?
