### ISSUE TITLE
Remove hover highlight and button for microbit logo on V1 board simulator

### ISSUE THREAD

**Issue by kimprice** [microsoft/pxt-microbit#4723]
**Describe the bug**
V1 boards in the simulator show the microbit logo as clickable, but this is not accurate. 

**To Reproduce**
1. Open new workspace (do not include any V2 blocks)
2. Hover on the microbit logo in the simulator
3. See the highlight on hover and the cursor indicate it is clickable

**Expected behavior**
We should disable this attribute when the board is V1 since the logo is not clickable on V1 boards.

![image](https://user-images.githubusercontent.com/15070078/171922876-a9883854-04ed-4d9f-a244-c8c57cdeafa6.png)

**Comment by kimprice** [comment]
Also, when the logo is clickable, we should support clicking anywhere within the logo, not just on the outline of the logo.

**Comment by abchatra** [comment]
@jwunderl can you take over this issue for tomorrow?
