### ISSUE TITLE
micro:bit specific text strings in extension screen

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#4730]
**Describe the bug**

Some of the recent extension UI changes for micro:bit seem to have left micro:bit specific strings in Maker.

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/147113/172890775-3eb627f8-ad11-4f80-912a-121bc266f6d5.png">

**To Reproduce**
Try to add an extension in maker.makecode.com

**Comment by abchatra** [comment]
We shouldn't have micro:bit specific strings in pxt or atleast it should be parameterized for the target.

**Comment by aznhassan** [comment]
This is using quite an old version of the extension page. The "Do more with your x" text no longer exists in the extension page. Bumping pxt-core should solve the issue.

**Comment by aznhassan** [comment]
pxt-maker is now using the most recent pxt-core and no longer has micro:bit-specific text: 
![image](https://user-images.githubusercontent.com/6496798/173940942-54f66880-8a4f-4ce1-8655-e0f401b4081e.png)
