### ISSUE TITLE
Tags for Extension page

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4731]
Here are the tags for the extension page:
1.	Robotics – kits and accessories that use the micro:bit in robots
2.	Science – STEM-based accessories for environmental sensors and science experiments
3.	Networking – augment the micro:bit for communication over networks and in the cloud, including IoT capabilities
4.	Lights and Display – accessories to expand the micro:bit lights or display screen capabilities
5.	Gaming – turn your micro:bit into a game controller or gaming platform!
6. 	Software – no additional hardware required!  These extensions are software-only customizations for the micro:bit

**Comment by abchatra** [comment]
Done
