### ISSUE TITLE
Queue of simulated sounds to play isn't cleared when the sim is reset.

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#4736]
**Describe the bug**

If you (perhaps accidentally) queue a lot of sounds onto the simulator (which is possible because of #4735 ) then they don't stop playing/the queue isn't cleared until the page is reloaded.

**To Reproduce**
1. Run this program for about 10 seconds

<img width="543" alt="image" src="https://user-images.githubusercontent.com/147113/173103439-691317d7-a15f-4274-ab6b-83401f9768e3.png">

2. Change the wave type and frequency ramp so you can hear the sound difference

<img width="562" alt="image" src="https://user-images.githubusercontent.com/147113/173103602-5820990b-2f8e-4fd9-aea4-4417f9cd6061.png">

Notice that the first sound keeps playing for a long time (or until you refresh the page)

Clicking the reload button the simulator doesn't help
@abchatra I think this is a worse issue than #4735 that we just discussed because it's really confusing when you change the sound in the code editor but the old sounds keeps playing.

**Comment by jaustin** [comment]
CC @riknoll

**Comment by abchatra** [comment]
@riknoll we need to clear the queue on reload
