### ISSUE TITLE
New sound block move up

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#4737]
Move new sound block (and deprecate old giggle block somehow)

![image](https://user-images.githubusercontent.com/4175913/173104076-1ff671a4-ee18-4ff7-8fd6-5ba893d64cf3.png)

**Comment by Jaqster** [comment]
People like the giggle block.  Why would we deprecate?
We also talked about this and decided not to move it to the top of the Toolbox menu yet - install base of v2 isn't quite mainstream yet.  We can do this mid-year if we feel the need, or wait until next year.

**Comment by pelikhan** [comment]
Sorry I meant the top of the v2 category.
________________________________

**Comment by abchatra** [comment]
I think moving to top of v2 subcategory makes sense. Keep the older one below.
