### ISSUE TITLE
Play Melody block - all notes show up black in Snapshot

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4739]
Repro - take a snapshot of code that includes a Play Melody block.
Looks like all the notes are black on the block (instead of colored).
![image](https://user-images.githubusercontent.com/22108954/173163837-320aadce-1246-4712-b794-88fb64e40a22.png)

**Comment by microbit-matt-hillsdon** [comment]
Spotted this one when testing with micro:bit classroom. Would be great to fix. Something similar (from a user perspective at least) was fixed in 2020, see #3398.
