### ISSUE TITLE
Docs for Play Sound block

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4744]
https://makecode.microbit.org/reference/music/play-sound-effect

- [ ] Rename this to "play sound"
- [ ] Update sample
![image](https://user-images.githubusercontent.com/22108954/173451769-38ec96a2-4848-4018-aa60-d8f8a3be5d7b.png)

- [ ] Include a view of the block expanded
- [ ] Include the version that has pre-built sounds (giggle)

**Comment by ganicke** [comment]
The old `playUntilDone()` method for the static sound expressions is set to deprecate in favor of `playSoundEffect()` with the built-in sound effect as a parameter - #4554. The docs are setup for the new sound effect functions.

```typescript
// new method
music.playSoundEffect(music.builtinSoundEffect(soundExpression.giggle), SoundExpressionPlayMode.UntilDone)

// old method
soundExpression.giggle.playUntilDone()
```

![image](https://user-images.githubusercontent.com/27789908/173464138-d57000f8-3396-44cc-85c7-fecc4129c090.png)

The current beta build is now showing the new block in the Toolbox:

![image](https://user-images.githubusercontent.com/27789908/173465223-12a6bde0-4444-4d8c-a3d9-5106f12261eb.png)
