### ISSUE TITLE
Include time stamp by default

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4746]
Right now we don't include a time stamp in the Simulated Data Log view.
I would like to propose that we include a second timestamp by default in the table view - 
![image](https://user-images.githubusercontent.com/22108954/173452807-98fb7810-f85c-40ca-a594-330e49d925b1.png)

The My_Data table shows this

**Comment by jwunderl** [comment]
Mentioned the not mirroring it here: https://github.com/microsoft/pxt/pull/8901

I'm fixing that, it's being called in the same way so just need to fix the bug here & also change the default to match hw

**Comment by abchatra** [comment]
nice catch
