### ISSUE TITLE
Insert message for getting data file from micro:bit

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4748]
Repro - 
- Use Data Logger and Serial blocks in a program
- Download program to micro:bit
- Click Show console Device
- Toggle to Data Log view

This view is currently blank.  In the future we could show the MY_DATA file contents, but for now, let's include some messaging and a link to information for how people can open this file.  
Proposed messaging:
"To get device data from your micro:bit, you will need to access the MY_DATA.HTM file on your micro:bit device.  To learn more about how to do this, see https://support.microbit.org/support/solutions/articles/19000127398-my-data-htm"

**Comment by Jaqster** [comment]
@jaustin - FYI.  Also, probably need to update that support article.

**Comment by abchatra** [comment]
This is waiting on the codal changes. @jaustin @JohnVidler

**Comment by abchatra** [comment]
This is not relevant after we implement https://github.com/microsoft/pxt-microbit/issues/4916
