### ISSUE TITLE
Alternate wording for data/console view buttons

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4749]
Now that we have both Serial and Data Log view in this page, thinking of using alternate wording for these buttons:
![image](https://user-images.githubusercontent.com/22108954/173458296-b156b7a3-ddc0-4eb0-b0f9-1678279271d6.png)
![image](https://user-images.githubusercontent.com/22108954/173458325-120565b6-52ea-44b8-8876-006ef137d308.png)

Maybe "Show Simulator Data" and "Show Device Data" ?

**Comment by abchatra** [comment]
@Jaqster whom should this bug go to? 

Also interesting we changed this before. Instructions here say "show data device"
https://makecode.microbit.org/courses/ucp-science/data-collection/setup-procedure

**Comment by Jaqster** [comment]
Oh funny!  I wonder why we changed it to "console"...
I'd like to get customers to weigh in here, but not sure we have time - let me post to Forum.

**Comment by abchatra** [comment]
@pelikhan did that :-) https://github.com/microsoft/pxt/pull/3438

**Comment by pelikhan** [comment]
it's an old change.
![image](https://user-images.githubusercontent.com/4175913/173497000-4ba11975-3dff-4dd7-b63c-bfc93668861f.png)

**Comment by abchatra** [comment]
Ya but we did change it he he.

**Comment by Jaqster** [comment]
but why did we change it?  I don't want to change it back if there was some good reason we did that...

**Comment by pelikhan** [comment]
If you follow the trail, it is here https://github.com/microsoft/pxt-adafruit/issues/469 .

The console view lets you see console messages, which is the name of the category. It's unclear that mixing the data logger output and console view into a single concept is a good idea imo. It could/show be 2 separate views; then "show data log" makes sense. The tags are going to be overlooked.

**Comment by abchatra** [comment]
Oh no its me :-(

**Comment by Jaqster** [comment]
Well, the name of the Toolbox Category is "Serial" (did it used to be called "Console"?)
A "console" is usually used to describe some sort of output window.
I think of both Serial and Data Logger blocks as ways to collect data from the micro:bit - it makes sense to me to have these views together.  It would make even more sense if we just had 1 set of Data blocks.  If someone asked me the difference between these two blocks, I couldn't tell you...
![image](https://user-images.githubusercontent.com/22108954/173499910-0a518d71-98d9-4791-a245-7dca7b67dd30.png)

**Comment by abchatra** [comment]
It is console in arcade and adafruit
![image](https://user-images.githubusercontent.com/6107272/173500589-84355bf8-f95b-4b8b-ae31-44969a1f195e.png)

**Comment by jaustin** [comment]
would "show output" cover things and remain clear? I guess it requires the leap from both data and serial to 'output'...

**Comment by jwunderl** [comment]
@abchatra Ahh, I think this can be closed unless we want to change it again? we had decided on 'show data {simulator/hardware}' at lunch w/ jacqueline and that was changed here: https://github.com/microsoft/pxt/pull/8916
