### ISSUE TITLE
Once the user interacts with the scroll, it is not possible to lock the view to the bottom

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#4765]
When the datalogger view is pumping data, it locks the view to the last entry by default. Once the user scrolls once, it is not possible to lock again on the view. 

Expectation:

scrolling back to the bottom locks the view to seeing the last entries again.

**Comment by jwunderl** [comment]
Hm, what device are you on? If the last entry is visible it's supposed to 'lock' back into auto scroll again / "it does on my machine" :)

The check for that happens [here](https://github.com/microsoft/pxt/blob/master/webapp/src/serial.tsx#L282) so maybe it's window.innerHeight being inconsistent in other browsers, I think I've seen that, though I should probably also just add a bit more padding (e.g. 'within 2 of bottom auto scroll') and we can think about a 'view latest...' button that floats at the bottom when you're not looking at newest stuff.

**Comment by pelikhan** [comment]
The simulator is too fast to reach that point.

![image](https://user-images.githubusercontent.com/4175913/174350580-aa15c763-2874-4d98-b92a-5ec7986dab4c.png)
