### ISSUE TITLE
Windows Store App is broken

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#4772]
**To Reproduce**
1. Install micro:bit app from Windows Store
2. Click on 'about' -> 'experiments'
3. Select 'Beta editor'
4.  Beta loads
5. See the error
  - Simulator is broken   
  - Download is broken
  - Tutorials are broken

**Comment by abchatra** [comment]
Things to be done
- [ ] Produce a PWA and list on the store. - 06/28 -> Abhijith
- [ ] Foundation to take down the existing app -> 09/1. -> Abhijith.
- [ ] User interface in /v4 to download the new app for 2 months -> 09/01 -> Joey 
- [ ] Enable user to download all the projects from the windows app -> 09/01.  (Investigation what is the best way?). Couple of ideas -> Multiple downloads & show windows app file path. -> Richard.

**Comment by pelikhan** [comment]
Allow to download all selected projects from project manager?

**Comment by abchatra** [comment]
Related https://github.com/microsoft/pxt-microbit/issues/4814

**Comment by abchatra** [comment]
@jaustin please take down the app. It is going to cause confusion leading to the hour of code week.
