### ISSUE TITLE
Play Sound Editor - changing Duration value doesn't persist

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4779]
Nit-picky bug.
When changing the value in the Duration field, then clicking outside of the editor to close the window, the changed value doesn't persist.  Note that if you tab outside the Duration field, or click the X to close the window the changed value does stay.

https://user-images.githubusercontent.com/22108954/174713241-9580bff1-537f-4b6e-a4c8-e8605e394b3d.mp4

**Comment by abchatra** [comment]
@riknoll will take hot fix if we can repro\fix this.
