### ISSUE TITLE
Jacdac: An empty page shows after clicking "User guide"

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4782]
**Describe the bug**
**Jacdac:** An empty page shows after clicking "**User guide**"

**Steps to reproduce the behavior**
1.Nabigate to https://makecode.microbit.org/beta#editor
2.**Jacdac**---->Button smasher----->Show Instructions
3.Scroll down to the bottom of page
4.Click "**User guide**"

**Expect behavior**
Navigate to "**User guide**" page

**Actual behavior**
**Jacdac:** An empty page shows after clicking "**User guide**"
![2](https://user-images.githubusercontent.com/59192069/176134584-e84577c1-742e-45be-8176-68e88e10c239.gif)

**Additional context**
1.OS: Win10
2.makecode.microbit.org version: 5.0.7
3.Microsoft MakeCode version: 8.0.4

**Comment by pelikhan** [comment]
Great bug! Fix coming.
