### ISSUE TITLE
Offline app: Dragging a hex from the website triggers error "Oops, this project is too new!"

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#4785]
**Describe the bug**
A hex file saved from the website cannot be loaded into the offline app.

The offline app shows the error message  "Oops, this project is too new!"

Clicking the "Get latest" button just opens the website.

Reported via support https://support.microbit.org/a/tickets/54832 (private)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '[...](https://makecode.microbit.org/)'
2. Create a new project
3. Save project as a hex file
4. Drag the hex file to the offline editor window

**Expected behavior**
The project loads, or clicking "Get latest" updates the installed offline app.

**micro:bit version (please complete the following information):**

not hardware related

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows

**Comment by martinwork** [comment]
Is there an ETA for a new version of the offline app?

**Comment by abchatra** [comment]
Thanks for the ping. We plan to release before end of the next week.

**Comment by martinwork** [comment]
Thanks @abchatra, I'll let them know.

**Comment by abchatra** [comment]
@jwunderl FYI

**Comment by martinwork** [comment]
@abchatra 
Another enquiry about this: https://support.microbit.org/helpdesk/tickets/56727 (private)

I just installed from Microsoft Store and got v4.0.22. What is the best way to get the offline app?

**Comment by abchatra** [comment]
@martinwork 

If the requirement is offline app, they can install: https://makecode.microbit.org/offline-app
Please point to them.

**Comment by martinwork** [comment]
Thanks @abchatra. On my Windows 10 machine, the installer makecode-microbit-setup-win64.exe goes through a long "Installing" process which ends by running MakeCode, but doesn't seem to create any shortcuts to run it again after I quit it. For example, typing "makecode" into the search box finds nothing. Restarting the computer doesn't seem to help. Is it just me? What am I missing? It is in Settings/Apps & Features. I reinstalled and checked in TaskManager to find the program exe is in  C:\Users\<user>\AppData\Local\makecode_microbit\app-5.0.12. If I run makecode-microbit-setup-win64.exe again after installing, it goes through the installing process again.

**Comment by abchatra** [comment]
Searching for the app should show the app:
![image](https://user-images.githubusercontent.com/6107272/189211724-971c6d8a-fe67-41a0-90cc-881881226ad5.png)

Also you can right click on the icon at the taskbar when it is running and pin to the startbar.

**Comment by martinwork** [comment]
@abchatra It doesn't find anything for me, probably because I changed start menu settings a long time ago. It still finds every other app I can think of - just not MakeCode!
