### ISSUE TITLE
Screen resizing

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4790]
We saw this issue on one of the demo machines at ISTE, although I haven't been able to reproduce.
This person was in a tutorial, and then I think resized the browser window.  The screen didn't resize appropriately and part of the UI was cut off.  They then exited the tutorial, but the window sizing issue persisted.
![image](https://user-images.githubusercontent.com/22108954/176947554-e2086c40-01b5-44a9-a477-19a9d7b945e5.png)

**Comment by abchatra** [comment]
I think the user touch zoomed it. This is a browser feature and they have to unzoom it.

**Comment by abchatra** [comment]
This feature in browser is known as pinch zoom

**Comment by abchatra** [comment]
This is not a bug in the editor but how the browser behaves in pinch zoom scenario. Can't fix from our end.
