### ISSUE TITLE
Need title card for new micro:bit tutorial "Cat Napping"

### ISSUE THREAD

**Issue by anzhou5** [microsoft/pxt-microbit#4791]
Describe your design or art need by answering the questions below: 

## What are the requirements for the project?

Need one of these for the new data logger tutorial.

![image](https://user-images.githubusercontent.com/42353804/176978029-15e4a320-7593-4c8c-a750-e236e961fa60.png)

The tutorial involves a cat named Lychee who wants the learner to track light and temperature data at their home, with the goal of seeing if she can cat nap in a sun spot.

## Is there a deadline or date this is needed by? 

7/15

### Who are the stakeholders that need to sign off on this design? Tag them here. 

@anzhou5 

### What audience is this request for?

Grade school

### What does success look like? 

We have a micro:bit home page card that makes people want to click to log data for Lychee the cat!

**Comment by abchatra** [comment]
Implemented
