### ISSUE TITLE
Pin 0 touch is not working micro:bit v2

### ISSUE THREAD

**Issue by Nitesh-AI** [microsoft/pxt-microbit#4794]
when setting pin 0 to capacitive touch it is not detecting any touch and resistive touch also it is not happen. using pin p0 press command 
![image](https://user-images.githubusercontent.com/18595551/177085653-5817141a-93e3-4d0e-8bf9-ca0a2e685ce4.png)
 it is always showing value 1 means the pin is pressed. Is it a bug or hardware issue?

**Comment by martinwork** [comment]
I used this project to test: https://makecode.microbit.org/_CL5dp1cX6DFT
All combinations seem to work for me except logo + resistive (https://github.com/microsoft/pxt-microbit/issues/3724)
I'm connecting a crocodile clip lead to P0 (and one to ground for P0 + resistive).
Just holding the plastic of one lead can trigger P0 + capacitive.

**Comment by Nitesh-AI** [comment]
my pin 0 is not responding for resistive as well as capacitive touch. logo
is working fine.

**Comment by Nitesh-AI** [comment]
> when setting pin 0 to capacitive touch it is not detecting any touch and resistive touch also it is not happen. using pin p0 press command ![image](https://user-images.githubusercontent.com/18595551/177085653-5817141a-93e3-4d0e-8bf9-ca0a2e685ce4.png) it is always showing value 1 means the pin is pressed. Is it a bug or hardware issue?

When I  am using digital write and analog write command for pin 0 is giving led is very dim as compared to pin 1, pin 2

**Comment by martinwork** [comment]
@Nitesh-AI Is this still an issue, or is it a fault with your micro:bit?

**Comment by abchatra** [comment]
No additional information given.

**Comment by microbit-carlos** [comment]
We've looked into this in CODAL and the final solution will require a change in MakeCode. I can submit the change in a PR with the next CODAL tag, but in the meantime it'd be good to reopen this issue to be able to track it.

**Comment by microbit-carlos** [comment]
sorry, reopened the wrong issue.
