### ISSUE TITLE
Projects described as 'games' when shared

### ISSUE THREAD

**Issue by microbit-giles** [microsoft/pxt-microbit#4795]
**Describe the bug**
Shared project description field relates to Arcade.

**To Reproduce**
1. Go to micro:bit MakeCode editor https://makecode.microbit.org/#editor
2. Click on 'Share project'
3. See words 'Tell others about your game' in Description box
![Screenshot2022_07_04_142624](https://user-images.githubusercontent.com/42380137/177178502-00753b8a-6e32-44ae-93b3-81489f305bde.jpg)

**Expected behavior**
It should say 'Tell others about your project' or 'Tell others about your code' rather than 'game'

**micro:bit version (please complete the following information):**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
 Possible templating bug of the opposite type to #4730

**Comment by abchatra** [comment]
@riknoll change to "project"
