### ISSUE TITLE
The While button pressed inside a forever loop does not exit when button released

### ISSUE THREAD

**Issue by djwarn** [microsoft/pxt-microbit#4798]
A simple program Using a forever block containing a while button A is pressed do loop containing a show icon statement  will show the icon when the button is pressed, but will not remove it when the button is released.

![image](https://user-images.githubusercontent.com/97265186/177437877-f1029112-7b93-49d1-9200-8bdf83b762a3.png)

'while button A is pressed do whatever' should stop doing whatever when the button is released.

The problem arises because 'show icon' is used to mean 'switch icon display on' . To 'switch the icon off' it is necessary to switch a blank (or space) icon on.

Within a while loop, the icon should only display while the while condition exists.

The same issue occurs on pin pressed, etc.

The Python code from the above is:
  def on_forever():
      while input.pin_is_pressed(TouchPin.P0):
          basic.show_icon(IconNames.HAPPY)
  basic.forever(on_forever)

I'd suggest it should be;
  while True:
    while input.pin_is_pressed(TouchPin.P0):
        basic.show_icon(IconNames.HAPPY)

(though I'm not a Python programmer.

**Comment by Nitesh-AI** [comment]
![image](https://user-images.githubusercontent.com/18595551/177481526-46e0bb43-1dbf-4cea-85dc-aebcd54479bc.png)
add clear screen command outside while to instruct micro:bit to what to do if button A is not pressed. Hope this will solve your issue.

**Comment by abchatra** [comment]
Thanks @Nitesh-AI . This is the right answer. Microbit display will not clear on its own once set, there is a need for explicit clear.
