### ISSUE TITLE
Helpful message to open very old hex files in the v0 editor is missing after V3

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#4802]
**Describe the bug**
Arising from support ticket https://support.microbit.org/helpdesk/tickets/54940 (private)

From v1 to v3 there was a helpful message when attempting to open a very old hex file.
The message from v4 and after is not so helpful.

Here is an example old file: [microbit-clock-step-7a.zip](https://github.com/microsoft/pxt-microbit/files/9066378/microbit-clock-step-7a.zip)

**To Reproduce**
1. Go to 'https://makecode.microbit.org/'
2. Drag an old file into the window
3. See message

**Expected behavior**

Could the helpful message be reinstated?

**Screenshots**

Message from v4+
![v4](https://user-images.githubusercontent.com/989126/177842438-929ac3f1-a601-44db-a97e-495724627500.PNG)

Message from v3
![v3](https://user-images.githubusercontent.com/989126/177842478-77a46e39-7969-4494-ad44-6953134a64f1.PNG)

Message from v1 and v2
![v2](https://user-images.githubusercontent.com/989126/177842528-07409353-e531-4b80-b838-e90f45dbe371.PNG)

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]
not hardware related

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 103

**Comment by abchatra** [comment]
We have removed the code to recognize old touch develop scripts from v4. We can't fix this at this point of time.
