### ISSUE TITLE
Microsoft MakeCode [Web] - Add compliance notice to comply with Italy digital accessibility requirements.

### ISSUE THREAD

**Issue by testingmakecode** [microsoft/pxt-microbit#4810]
After reviewing this issue, it is invalid. Hence, Closing the bug.

**Comment by abchatra** [comment]
We are localized in Italian
![image](https://user-images.githubusercontent.com/6107272/178657765-39429ee5-c4ca-40b4-b46e-1cd16b2f2ff0.png)

**Comment by abchatra** [comment]
@testingmakecode why is this closed?

**Comment by v-prahu** [comment]
@abchatra - This bug was logged in Github ADO by mistake, we will follow up on this requirement on mail for further tracking.
