### ISSUE TITLE
Request for assets for PWA app of micro:bit in the windows store

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#4814]
Guidance here: https://docs.microsoft.com/en-us/windows/uwp/publish/app-screenshots-and-images#store-logos

Sonia generated similar thing for arcade app here: https://github.com/microsoft/pxt-arcade/issues/4355#issuecomment-987379126
See arcade app ms-windows-store://pdp/?productid=9NWH29B68GTH for reference

**Comment by abchatra** [comment]
This is for micro:bit

**Comment by clkantner** [comment]
Hi @abchatra @Jaqster , this is where we landed at the end of last week with designs. Please let me know what format you will need these files and how to best deliver to you. Or if you have any last minute thoughts on design. We shared with micro:bit team and so far they haven't asked for us to change anything so I think we are good. 
<img width="859" alt="Screen Shot 2022-08-29 at 9 38 48 AM" src="https://user-images.githubusercontent.com/106267801/187251141-2d93822f-1bfb-49e8-9f13-799a22967fac.png">

**Comment by abchatra** [comment]
These look great. Thanks so much @clkantner. Can you share the zip of these images?

**Comment by clkantner** [comment]
Yes, here is the zip file 
[microbit-banners.zip](https://github.com/microsoft/pxt-microbit/files/9447057/microbit-banners.zip)

**Comment by abchatra** [comment]
This is completed. Thank you @clkantner
