### ISSUE TITLE
Adding a Electric guitar using Microbit project documentation in docs

### ISSUE THREAD

**Issue by akshitagupta15june** [microsoft/pxt-microbit#4818]
### What it does?

When you touch pin 1 or pin 2 and GND it will play a broken chord, but now you can move the chord down an octave (lowering its pitch) by pressing button A and move it up an octave (raising its pitch) by pressing button B.

The pitch (frequency) of a note doubles when you move up one octave: middle A has a frequency of 440Hz (440 vibrations per second), high A has a frequency of 880Hz. This is why making the vibrating part of guitar strings different lengths with your fingers changes the pitch of the note being played.

**Comment by abchatra** [comment]
I am closing this issue as no action required. PR will be reviewed. Thanks for the PR and issue.
