### ISSUE TITLE
What does (sad face) error code 914 indicate?

### ISSUE THREAD

**Issue by kiate** [microsoft/pxt-microbit#4821]
micro:bit V2 shows sad face and error code 914 while I'm working on a line following robot code. I couldn't find this error code in the list here:
[https://support.microbit.org/support/solutions/articles/19000016969-micro-bit-error-codes](https://support.microbit.org/support/solutions/articles/19000016969-micro-bit-error-codes)

Unfortunately I can't reproduce it with the same code. I would like to know how to prevent this from happening again and an explanation on what the code indicates would be very helpful. Thank you.

**Comment by riknoll** [comment]
That particular error is:
```
 (PANIC_CALLED_FROM_ISR): the current code isn’t allowed to run in an interrupt service routine (ISR)
```
and I have to admit, this is the first time I've seen it as well! Perhaps @mmoskal could shed some light on this one.

Also, could you share the project in which this occurred?

**Comment by kiate** [comment]
@riknoll Thank you so much for the reply! That's a really helpful indicator for me to continue troubleshooting. 

I was using MakeCode PulseIn continuously to read 3x IR sensor pairs connected in R-C mode as shown in the pic below. 
![image](https://user-images.githubusercontent.com/1186201/182987832-fc7f4043-70d9-41cd-a507-6f7b1380ed14.png)
P0-P2 are used for other purposes, that's why the rather odd method here. Unfortunately, I couldn't reproduce the error consistently...

**Comment by mmoskal** [comment]
If someone can get me a reasonable repro I could look at this. This is either someone trying to run MakeCode code from an interrupt or (more likely) someone trying to allocate stuff on GC heap from an interrupt. Not sure how either of these could happen though...

**Comment by abchatra** [comment]
No repro.

**Comment by JShull** [comment]
For what it's worth hit the same issue: Was running the log through the browser and got some information - hope it helps.
@mmoskal 
![Screen Shot 2022-09-25 at 1 20 28 PM](https://user-images.githubusercontent.com/12342337/192156649-84b1a711-2bef-4c1a-9fbc-b9664e7da5b2.png)
