### ISSUE TITLE
Add extension problem

### ISSUE THREAD

**Issue by crouse12** [microsoft/pxt-microbit#4825]
I try to add extension into makecode.
So, I add "kaise-ksrobot/pxt-KSB030-4WD" into makecode.
However, I get some errors when I open makecode.
From these errors, I find that Makecode extension open a url for pxt-KSB030-4WD.
https://www.makecode.com/api/gh/kaise-ksrobot/pxt-KSB030-4WD
When I open this url, I get the following messages.
{"message":"repo info response: 404"}
However, when I use this [url](https://www.makecode.com/api/gh/) to open another url. 
I get the following message.
{"kind":"script","id":"gh/kaise-ksrobot/pxt-KSR030","time":1615045397,"name":"KSR030","description":"Extension for KAISE KSRobot KSR030 Robot","version":"1.3.0","hash":"997515d44631a26d4dda23f47d891af3c0c9704415d265f5fe1f6507efb69026","defaultBranch":"master"}
May I know what this "https://www.makecode.com/api/gh/" is?
Is it a check  mechanism?
May I know how to pass this check mechanism?

**Comment by jwunderl** [comment]
That api fetches pxt extensions from the given github repo. Since https://github.com/kaise-ksrobot/pxt-KSB030-4WD results in a 404 for me, there is either a typo in the repo name or (more likely) you have the repo set to private so it cannot be used.

**Comment by abchatra** [comment]
Question answered.
