### ISSUE TITLE
Python: assignment to global variable within multiple targes only acts locally

### ISSUE THREAD

**Issue by coproc** [microsoft/pxt-microbit#4826]
**Describe the bug**
An assignment within a function of the form `g_value,... = ...` does not respect a prior global declaration `global g_value` (at least in the simulator Microsoft MakeCode Version:  8.0.7)

**To Reproduce**
1. Enter this Python code:
```
def initValue():
    global g_value
    g_value,_ = 1,0

g_value = 0
initValue()
basic.show_number(g_value)
```
2. Run code in simulator
3. The LEDs show number `0`

**Expected behavior**
The LEDs should show number `1`.

Note that with these program variants the LEDs do show number `1`:
```
def initValue():
    global g_value
    g_value,_ = 1,0
    basic.show_number(g_value)

g_value = 0
initValue()
```
or
```
def initValue():
    global g_value
    g_value = 1

g_value = 0
initValue()
basic.show_number(g_value)
```

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10478747/184796474-6bdc9779-a118-482f-877a-4ab1559bc5c8.png)

**Environement, Version:**

**Desktop:**
 - OS: Windows, Linux
 - Browser: current Microsoft Edge, Firefox
 - Version: Makecode 8.0.7

**Comment by riknoll** [comment]
you're right, we're definitely messing up the semantics here
