### ISSUE TITLE
MakeCode editor converts variables always to global variables

### ISSUE THREAD

**Issue by StaelensJarne** [microsoft/pxt-microbit#4830]
How can I declare a local variable in the MakeCode editor?

As I define my variables these are always global variables, even if I only need them locally.
I am a professional developer, so I know there is a huge difference between a local and a global variable!
For example:
![function doSomething](https://user-images.githubusercontent.com/26405591/185460845-add84b7e-6b7e-4cab-912a-66d94816c744.png)
I only need ix in my function doSomething.
But If I switch to python I see that this is a global variable:
```
ix = 0
def doSomething():
    global ix
    ix = 1
```
I modified the code to make it a local variable.
But I switch back to blocks and then back to python, it forces the variable to be defined globally.
This is wrong, I only need ix locally.

How can I define local variables, or disable that (wrong) behaviour that it always converts variables to global variables?

**Comment by riknoll** [comment]
@StaelensJarne one of the limitations of block coding in MakeCode (and most other block based code editors that I know of) is that all variables are global. There is no concept of local variables in our blocks editor except for function parameters and loop indices.

Unfortunately, that means that we have to convert variables to global when switching from JavaScript/Python to blocks. We try our best to maintain the program semantics when making this conversion but there is a lot more that's possible in text vs blocks so the conversion will never be perfect.

**Comment by THEb0nny** [comment]
I think this is such a big limitation for teaching kids how to program.
I also do not understand why there is no such thing as a constant in JS and blocks. Everything is converted into a variable.

**Comment by StaelensJarne** [comment]
Thank you for your answer!
This is indeed a big limitation. If I use VC Code than it is not converted anymore.
This issue can be closer.
