### ISSUE TITLE
Some extension "Learn more" snippet Edit buttons don't work

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#4832]
**Describe the bug**

The **Edit** buttons on some extensions' **Learn more** pages, fail to create a working project.

There's a dialogue offering to fix the problem, which doesn't work. The JavaScript mode Explorer shows multiple errors

The errors are often due to duplication of the extension with different package names. Once this has happened, adding the extension to the original project fails: it appears in the Explorer, but not on the blocks categories panel. This seems to be quite persistent. I ended up resetting MakeCode and using F12/Application/Storage/Clear site data.

Example extensions: kitronik-servo-lite, iot-environment kit, Environment-and-Science-IoT, bluetooth-max6675

**NB: USE AN INCOGNITO WINDOW TO TEST THIS**. Close all incognito windows for a fresh start. The error occurs in normal windows, but I'm not sure it's recoverable without resetting MakeCode. 

**To Reproduce**
1. Go to https://makecode.microbit.org/
2. Create a new project
3. Open the extensions dialogue
4. Click an extension's **Learn more** button
5. Wait for the blocks to load
6. Click an **Edit** button

**Expected behavior**
A valid project is created.

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]
not hardware related

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Comment by abchatra** [comment]
I can reproduce this.

**Comment by kimprice** [comment]
The duplication of the extensions is happening because the extensions repo's READMEs include a package list which includes the extension itself or a duplicate with a different package name. When we parse the README, we import all the packages that are listed, hence the duplication. I will file bugs on those repos.

**Comment by martinwork** [comment]
Arising from https://support.microbit.org/helpdesk/tickets/63962 (private)

@kimprice @abchatra 

Although snippets in the **Learn more** page display blocks properly with the package list removed, it does not work when the **README** is viewed from MakeCode's Javascript Explorer.

Based on other examples, I think the **README** snippets display properly when the package list includes the extension's repo.

Could the self-reference be filtered out in the **Learn more** case?

I don't know how this applies to tutorials or other documentation files inside or outside the extension repo. 

See https://github.com/microsoft/pxt-bluetooth-max6675

**Learn more**
![image](https://github.com/microsoft/pxt-microbit/assets/989126/c2507c2a-8e89-41ea-accc-aea2302ff1d9)

**README**
![image](https://github.com/microsoft/pxt-microbit/assets/989126/6290eea5-afe6-46e6-ab27-c1b0b081a293)
