### ISSUE TITLE
makecode pin documentation is only for V1

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt-microbit#4834]
As seen at https://tech.microbit.org/hardware/edgeconnector/#pins-and-signals, there are some differences between the pin maps for micro:bit V1 and V2. Furthermore, if you look at the table for V2 vs V1 on the above page, you will notice that there are some different features available on the V2. 

The page https://makecode.microbit.org/device/pins needs to be updated to describe the differences.

**Comment by ganicke** [comment]
@abchatra - Sure, I'll give it an update.
