### ISSUE TITLE
led enable error on microbit v1

### ISSUE THREAD

**Issue by crousekimo** [microsoft/pxt-microbit#4837]
led enable block  has an error on microbit v1.
If anyone uses digitalWrite blocks before using led enable block, they cannot use digitalWrite anymore.
However, microbit v2 does not have such problem.
![image](https://user-images.githubusercontent.com/43980978/187024559-9711edf9-1285-46ad-b1ce-67f42e571e32.png)

**Comment by abchatra** [comment]
@crousekimo can you elaborate what you mean by you can't use digital write anymore?

**Comment by abchatra** [comment]
No additional information given.
