### ISSUE TITLE
Contrain block blanks out when changing language to Norwegian

### ISSUE THREAD

**Issue by gomakekit** [microsoft/pxt-microbit#4847]
**Describe the bug**
Any code containing the Math.constrain() function will be blanked out when changing from English to Norwegian (bokmål) language.

**To Reproduce**

In javascript or blocks: make a statement with constrain:

let test = 0
let number = 0
basic.forever(function () {
    test = Math.constrain(number, 20, 100)
})

Go to blocks, switch to Norwegian (bokmål)

**Expected behavior**
The constrain block is now empty:
test = Math.constrain(0, 0, 0)

**Screenshots**

<img width="797" alt="Screenshot 2022-09-09 at 13 55 10" src="https://user-images.githubusercontent.com/56154537/189345076-4a7c3e79-042b-436a-9acc-6692ffd7b869.png">

**micro:bit version (please complete the following information):**
Latest makecode and micro:bit V2, but I have seen the bug for at least one year

makecode.microbit.org version:  [5.0.12](https://github.com/Microsoft/pxt-microbit/releases/tag/v5.0.12)
Microsoft MakeCode version:  [8.0.7](https://github.com/Microsoft/pxt/releases/tag/v8.0.7)
microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
codal-microbit-v2 runtime version:  [v0.2.40](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.40)

**Desktop (please complete the following information):**
Mac os, Chrome 105, seen on other platforms too

**Comment by abchatra** [comment]
@ganicke issue with crowdin translation?

**Comment by ganicke** [comment]
@abchatra - indeed it is!

![image](https://user-images.githubusercontent.com/27789908/189764028-362e5b93-0f25-42b2-99b5-8dcc4e0baefb.png)

Parameter names fixed in:

https://crowdin.com/translate/makecode/65/en-nb?filter=basic&value=0#284788

**Comment by abchatra** [comment]
Thank you so much @ganicke
