### ISSUE TITLE
The hex file is not available, please connect to internet and try again.

### ISSUE THREAD

**Issue by dsssssssss9** [microsoft/pxt-microbit#4848]
**Describe the bug**
When i try to download as hex file i get this error ....
The hex file is not available, please connect to internet and try again.

**To Reproduce**
1. Go to https://makecode.microbit.org/_3UjdXDa30Y8e
2. Click on Download As File
3.  See error

**Expected behavior**
Save hex file to my Computer

**Screenshots**
![error](https://user-images.githubusercontent.com/30810847/189550707-0ade6e2b-7eef-4c7d-9924-6e906e7450eb.png)

**micro:bit version (please complete the following information):**

it's not hardware related ]

**Desktop (please complete the following information):**
 - OS: Linux & Windows
 - Browser: Brave / Chrome
]

**Comment by martinwork** [comment]
Related: https://github.com/microsoft/pxt-microbit/issues/4812

**Comment by abchatra** [comment]
There is an issue with the extension. Create a new share link by copy paste the code from this program and add the latest extensions lzty634158/yahboom_mbit_en and YahboomTechnology/Yahboom_IR

**Comment by abchatra** [comment]
Issue is already fixed in the latest extension.

**Comment by dsssssssss9** [comment]
@abchatra 
Many thanks for this 
I completely missed seeing the updated extensions - sorry!

**Comment by MarioWindows** [comment]
Edit in the V0 Editor https://makecode.microbit.org/v0
