### ISSUE TITLE
Can microbit v2 be used for data visualization over cloud platforms like thingspeak or qubitro?

### ISSUE THREAD

**Issue by akshitagupta15june** [microsoft/pxt-microbit#4858]
I need to ask that can I connect my microbit v2 with cloud platforms for data visualisation like if I ahve to send data to thingspeak platform of the various sensors?

@riknoll @abchatra

**Comment by abchatra** [comment]
MakeCode doesn't support cloud connection today. However there are hardware IOT accessories to microbit which connect to cloud. See https://makecode.microbit.org/extensions for all extensions.

Forum.makecode.com is a better place for questions. This issue tracker is for bugs and enhancement requests.
