### ISSUE TITLE
Czech translation shows P7 as P5

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#4859]
**Describe the bug**

From support ticket https://support.microbit.org/helpdesk/tickets/56965 (private)

In Czech, P7 is shown as P5.

**To Reproduce**
1. Go to 'https://makecode.microbit.org/#editor'
2. Drag on 'analog write pin' and choose P7
3. Change language to Czech and check popup

**Expected behavior**
P7 is shown as P7

**Screenshots**

![image](https://user-images.githubusercontent.com/989126/191253021-920ac5ff-1716-48a7-b2a2-aa5f086b8e0a.png)

![image](https://user-images.githubusercontent.com/989126/191252860-48b7c6b3-2686-4036-b716-4b1420add008.png)

**micro:bit version (please complete the following information):**
 not hardware related

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Comment by ganicke** [comment]
Fixed at: https://crowdin.com/translate/makecode/65/en-cs?filter=basic&value=0#31720
