### ISSUE TITLE
Sound hangs if tones are played too quickly

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#4862]
**Describe the bug**
Reported in support ticket https://support.microbit.org/helpdesk/tickets/57130 (private)

Sound stops on micro:bit V2 if tones are played too quickly.
This project demonstrates the error: https://makecode.microbit.org/_ThWV01bxEe8r.
The heart keeps beating, but sound stops after 3 tones.

If the pause is increased to 110ms, it's OK.

**To Reproduce**
1. Go to 'https://makecode.microbit.org/_ThWV01bxEe8r'
2. Download to micro:bit V2
3. Hear error

**Expected behavior**
Tones keep playing

**Screenshots**
![image](https://user-images.githubusercontent.com/989126/192268427-909785ec-9c0b-44bc-bb5e-05ecb1418b61.png)

**micro:bit version (please complete the following information):**
tested with v2.21

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Comment by thsparks** [comment]
I can repro this on the live site, but not with the new sound blocks, so I think this was fixed as a side effect of https://github.com/microsoft/pxt-microbit/pull/5123
