### ISSUE TITLE
Inconsistency in Tempo slider values

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4865]
Reported by an educator - 
The slider values for the Tempo field go from 40 - 500 in the Play Melody block vs. 4 - 400 in the Set Tempo block.
Request is to keep the slider values consistent across blocks.
![image](https://user-images.githubusercontent.com/22108954/194112808-cb6545f9-f999-48d1-b503-ab1b7e4048cd.png)
![image](https://user-images.githubusercontent.com/22108954/194112853-1550b087-76bd-4092-bae8-71858fb02a0d.png)

![image](https://user-images.githubusercontent.com/22108954/194112922-13552b7d-421e-484b-8005-8c02a4613c36.png)
![image](https://user-images.githubusercontent.com/22108954/194112970-cc7f03cf-fe4d-4881-b2c5-396f2ca5799a.png)

**Comment by thsparks** [comment]
Closing as duplicate to https://github.com/microsoft/pxt-microbit/issues/4906
