### ISSUE TITLE
FAQ Test Domains check appears to be missing some requirements

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#4870]
**Describe the bug**
Arising from support ticket https://support.microbit.org/helpdesk/tickets/57604 (private)

The list of domains at https://makecode.microbit.org/faq and the "Test Domains" check appears to be missing some requirements.

With Chromebooks passing the Test Domains tests, the simulator failed to appear with the message
"The person who set up this computer has chosen to block this site".
and the Chrome console has multiple repeats of
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('<URL>') does not match the recipient window's origin ('null').

It is reported as working after allowing all the domains listed here
https://support.microbit.org/en/support/solutions/articles/19000030385-firewall-requirements-for-micro-bit-editors

**Expected behavior**
Test Domains tests all required domains.

**micro:bit version (please complete the following information):**
not hardware related

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Chrome OS
 - Browser [e.g. chrome, safari] Chrome

**Comment by abchatra** [comment]
I am not sure I understand this bug. List below is the same except pxt.microbit.org & www.pxt.io. Both of which we don't use anymore.
https://support.microbit.org/en/support/solutions/articles/19000030385-firewall-requirements-for-micro-bit-editors

**Comment by martinwork** [comment]
The original report had two photos of the Chromebook screen, showing the failed simulator, and makecode.microbit.org/domains with success for all domains. I asked them to capture console output.

A few days later, I suggested https://support.microbit.org/en/support/solutions/articles/19000083125-makecode-microbit-org-doesn-t-load-on-chromebook which links to https://support.microbit.org/en/support/solutions/articles/19000030385-firewall-requirements-for-micro-bit-editors.

They replied that they found that all io websites were being blocked, and it worked when they added exceptions to allow the specific io domains. I have asked them if they changed anything else and they have confirmed that the only change was to whitelist the specific URLs, after finding that the whole top level domain io was being blocked by the URL blacklist.

**Comment by martinwork** [comment]
@abchatra Sorry for commenting on something I know little about, but... I read at https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch "The Promise returned from fetch() won't reject on HTTP error status even if the response is an HTTP 404 or 500."

Could it be that the Test Domains fetch() checks reported success though the io domains were blocked?

Below are console logs from machines that can access MakeCode, and report success for all URLs. The console reports error 404 for 2 URLs, but the fetch test logs reachable.

[chromebook-1666185949880.log](https://github.com/microsoft/pxt-microbit/files/9821068/chromebook-1666185949880.log)
[windows10-edge-1666186568275.log](https://github.com/microsoft/pxt-microbit/files/9821069/windows10-edge-1666186568275.log)
[windows10-chrome-1666186356155.log](https://github.com/microsoft/pxt-microbit/files/9821070/windows10-chrome-1666186356155.log)

**Comment by abchatra** [comment]
404 error is ok. It means server is reachable, but the page is not. This is true for simulator domains when we query: https://www.lifewire.com/404-not-found-error-explained-2622936#:~:text=A%20404%20error%20is%20an,showing%20the%20error%20is%20not.

**Comment by abchatra** [comment]
It is kind of hard to test this. However, you can use devtools to block a domain and see the page working correct. 
![image](https://user-images.githubusercontent.com/6107272/196815018-15bd948c-cd44-4dfd-abe1-f7ac94903ec0.png)



>> @abchatra Sorry for commenting on something I know little about, but.

Your feedback is greatly welcome. Always good to question these things.

**Comment by pelikhan** [comment]
Some “hotel firewalls” don’t return 404/500, they return a valid HTML page. You could sniff the html for some "makecode-ish" markers
________________________________

**Comment by abchatra** [comment]
Check is done in a way that any response from the server, then domain is reachable. This should work for hotel firewalls, right?

**Comment by abchatra** [comment]
No repro
