### ISSUE TITLE
German language: error in translation of writeBuffer, and failure to save a valid private GitHub repo

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#4873]
**Describe the bug**
Arising from support ticket https://support.microbit.org/helpdesk/tickets/57610 (private)

writeBuffer is not translated when the language is German. 
![image](https://user-images.githubusercontent.com/989126/198295896-fbc73d01-4499-457d-b47f-4a3f47afd793.png)

If I create a new project in German, save it to a private repo, then delete the project, the repo fails to import.
No error is displayed, but there is a message like this in the console.
![image](https://user-images.githubusercontent.com/989126/198311967-5ee6ee33-162a-4a92-b63b-5674d7331637.png)
![image](https://user-images.githubusercontent.com/989126/198298634-b5ddc127-7a6d-4e70-8caa-167c0bb277d9.png)

When saving the repo, no errors are reported, and I can't see any difference in the console messages compared to English.

If a project is created in English, and saved to a private repo, it can be imported with the language set to German.

**To Reproduce**
1. Create new project
2. Open Console
3. Change language to German

**Expected behavior**
writeBuffer is translated.
A private repo can be saved and reimported despite a translation error.
Errors while saving and importing trigger an error message.

**micro:bit version (please complete the following information):**
not hardware related

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 107

**Comment by MKleinSB** [comment]
![grafik](https://user-images.githubusercontent.com/37311672/219445651-d0c915ce-0ae9-4bcf-b748-f113ff676f4e.png)

Translation bug should be fixed now!

**Comment by abchatra** [comment]
This is fixed.
