### ISSUE TITLE
Microbit app: No option shows when clicking “Show device share options” button

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4874]
**Describe the bug**
**Microbit app**: No option shows when clicking “**Show device share options**” button

**Steps to reproduce the behavior**
1. Open microbit app 
2. Open a project and click Publish button to enter into **share screen**
3. Click "**Publish to share**" button
4. Click “**Show device share options**” button

**Actual behavior**
**Microbit app**: No option shows when clicking “**Show device share options**” button
![1](https://user-images.githubusercontent.com/59192069/198536458-0ca1b019-07c3-4037-8309-c2fc8381e9d1.gif)

**Expect behavior**
Show other device share options when clicking “**Show device share options**” button
![2](https://user-images.githubusercontent.com/59192069/198536415-e83e1c0d-052b-476e-a0fa-e88014a6ada5.gif)

**Additional context**
1.OS: Win11
2.makecode.microbit.org version: 5.0.12
3.Microsoft MakeCode version: 8.0.7

**Comment by abchatra** [comment]
@Sheila111  can you revalidate and see. If it reproes please reopen.

**Comment by Sheila111** [comment]
@abchatra Can you give a new version of offline build so that I can revalidate this bug.

**Comment by abchatra** [comment]
https://makecode.com/api/release/microbit/v5.0.12/mac64

**Comment by Sheila111** [comment]
@abchatra Button “**Show device share options**” has been removed. I am not sure if this is considered fixed.
![image](https://user-images.githubusercontent.com/59192069/225498798-7de6a2df-9b0d-4acf-a9ac-81d16dd9d56e.png)

**Comment by abchatra** [comment]
Yes, we removed this intentionally. So we are ok to remain as closed. Thank you!
