### ISSUE TITLE
microphone sound level threshold evaluation uses ==, should use >=

### ISSUE THREAD

**Issue by rharbird** [microsoft/pxt-microbit#4887]
**Describe the bug**
In file microphone.cpp onSound(), the threshold type (LOW/HIGH) is set depending on whether it is equal to DetectedSound::Loud. This means that threshold will not be set to LEVEL_THRESHOLD_HIGH unless it is exactly the value DetectedSound::Loud. This can cause unexpected behaviour. 

**To Reproduce**
N/A

**Expected behavior**
thresholdType should be LEVEL_THRESHOLD_HIGH when sound is equal to or above DetectedSound::Loud

**Screenshots**
N/A

**micro:bit version (please complete the following information):**

Not hardware related 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Version 107.0.5304.107 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
/**
* Registers an event that runs when a sound is detected
*/
//% help=input/on-sound
//% blockId=input_on_sound block="on %sound sound"
//% parts="microphone"
//% weight=88 blockGap=12
//% group="micro:bit (V2)"
void onSound(DetectedSound sound, Action handler) {
#if MICROBIT_CODAL
    pxt::getMicrophoneLevel(); // wake up service
    const auto thresholdType = sound == DetectedSound::Loud ? LEVEL_THRESHOLD_HIGH : LEVEL_THRESHOLD_LOW;
    registerWithDal(DEVICE_ID_MICROPHONE, thresholdType, handler);
#else
    target_panic(PANIC_VARIANT_NOT_SUPPORTED);
#endif
}

**Comment by martinwork** [comment]
The comparison is to convert from the enum values DetectedSound::Loud/Quiet to the CODAL LEVEL_THRESHOLD event values, specifying the type of sound event (loud/quiet=>high/low) that should trigger a call to the handler.
https://github.com/microsoft/pxt-microbit/blob/master/libs/microphone/microphone.cpp#L44
https://makecode.microbit.org/reference/input/on-sound

The actual thresholds used for loud and quiet event detection can be set with "set loud/quiet sound threshold" under ...more.
https://makecode.microbit.org/reference/input/set-sound-threshold
https://github.com/microsoft/pxt-microbit/blob/master/libs/microphone/microphone.cpp#L73

**Comment by abchatra** [comment]
question answered
