### ISSUE TITLE
iframe issue

### ISSUE THREAD

**Issue by bmoran23** [microsoft/pxt-microbit#4892]
**Describe the bug**
Using Make code for micro:bit. When I share a project and copy the code for embedding the editor my webpage auto scrolls my page to the iframe.  
I can't figure out why.  It is really annoying because all of the background gets skipped and a new user is staring at the editor.  

**To Reproduce**
1. Go to https://booleanu.com/lesson/start-a-lego-motor/
2. Notice that the page auto scrolla down to the iframe. 

**Expected behavior**
When you open the page it should stay at the top of the page.

**Desktop (please complete the following information):**
 - OS: V 12.2
 -  Browser chrome
 - Version 107.0.5304.110

Thanks

**Comment by martinwork** [comment]
Related to support ticket https://support.microbit.org/helpdesk/tickets/58890 (private)

@bmoran23 We need to login to see it happen. Does it scroll in Chrome for you? I guess you mean macOS 12.2?

When I have tested this, it worked OK in Windows Chrome v107 and v108, but scrolls to the editor in Windows Edge v107 and v108.

**Comment by abchatra** [comment]
no repro
