### ISSUE TITLE
Multi-dimensional arrays are not returning the proper type

### ISSUE THREAD

**Issue by RobertVS-MS** [microsoft/pxt-microbit#4893]
When trying to use a for / of with a multi-dimensional array, the type return is not an array as expected, but rather just the base type causing an error

`input.onButtonPressed(Button.A, function () {
    for (let ledGroup of allColors[Math.randomRange(0, 3)]) {
        for (let leds of ledGroup) {
            
        }
    }
})
basic.forever(function () {
	
})

function setup() {
    redLEDs = [0, 1, 2]
    greenLEDs = [2, 3, 4]
    blueLEDs = [5, 6, 7]
    yellowLEDs = [7, 8, 9]
    allColors = [redLEDs, greenLEDs, blueLEDs, yellowLEDs]
}

let allColors: number[][] = []
let yellowLEDs: number[] = []
let blueLEDs: number[] = []
let greenLEDs: number[] = []
let redLEDs: number[] = []
setup()

forever(function () {
})`

RESULT:
    // Expecting a return of number[]
    for (let ledGroup of allColors[Math.randomRange(0, 3)]) {

ACTUAL
    Getting a return of a number which causes the subsequent for / of to fail

**Comment by tballmsft** [comment]
The type of ledGroup is correct.  The for loop is iterating over the array allColors[Math.randomRange(0,3)], which is of type number[], so the iteration variable ledGroup is of type number.

**Comment by tballmsft** [comment]
Try replacing the for loop with this code instead
```
let group = allColors[Math.randomRange(0, 3)]
for (let led of group) {
    
}
```
this semantically the same as the loop you wrote, but extracts the inner array before iterating over it

**Comment by tballmsft** [comment]
the other does work. I am not sure what the error you are referring to is.
