### ISSUE TITLE
Makecode server platform capacity

### ISSUE THREAD

**Issue by moseslee2022** [microsoft/pxt-microbit#4895]
We are a Hong Kong company. Our company will hold an event having 10000 students code with make code at the same time. Is the make code server have enough capacity to handle those computers requirement?

**Comment by abchatra** [comment]
Yes, we have ability to do much more users than that. Let us know the date and time for the event. We will keep a watch on the servers.

We also have an offline app: https://makecode.microbit.org/offline-app if you want to keep a backup in usb drives (Works for windows and mac)

I am assuming your scenario is not a private network with single ip address.

**Comment by abchatra** [comment]
Good luck for your event.

**Comment by BeckHaru** [comment]
thank you A!!
________________________________
