### ISSUE TITLE
Extension Requires Updated CODAL

### ISSUE THREAD

**Issue by bsiever** [microsoft/pxt-microbit#4898]
**Describe the bug**

An approved and listed extension, https://makecode.microbit.org/pkg/bsiever/microbit-pxt-rotate (https://github.com/bsiever/microbit-pxt-rotate), requires features that were introduced in CODAL 0.2.43 (see [PR here](https://github.com/lancaster-university/codal-microbit-v2/pull/227)).

Because MakeCode still relies on CODAL v0.2.40, compilation fails.  The error message (due to not having a .hex) is "Cannot read properties of undefined (reading `toString`)".   

On a related note, that error message doesn't really help the user pin down the source of the problem or give any idea how to get help.

**To Reproduce**

Simple:  
Open https://makecode.microbit.org/_g1zRzj2qCU7u and try to download. 

Detailed:
1. Go to MakeCode: https://makecode.microbit.org/#editor
2. Click on `+ Extensions`
3. Search for "rotate".
4. Select the card/tile for `microbit-pxt-rotate`.
5. Add in the block from the `Rotate display` palette. 
6. Try to compile and download. 
8. See error

**Expected behavior**

Successful compilation / download.

**micro:bit version (please complete the following information):**

All (1.5, 2.0, 2.21)

**Desktop (please complete the following information):**

All

**Comment by bsiever** [comment]
By the way, this is mostly a question of "when will a CODAL update happen"?  Is there any guidance on the the MakeCode for microbit release and update schedule?

**Comment by abchatra** [comment]
We release new CODAL for every yearly release (once a year). However, we do take hotfixes and opportunistically release if it is stable. @JohnVidler FYI

I will discuss with John in our next call and see if the bits are stable or not.

**Comment by abchatra** [comment]
@jaustin fyi

**Comment by bsiever** [comment]
As mentioned, I've already got an approved extension that's using https://github.com/lancaster-university/codal-microbit-v2/pull/227 .   If CODAL isn't updated soon, the extension should be removed until it is. 

I'm nearly done with an extension that uses another update: https://github.com/lancaster-university/codal-microbit-v2/pull/177 .  

Both updates seem lightweight an unlikely to impact other things.  I'd sincerely appreciate if both could be included, but I understand if you're not able to test either/both sufficiently to do a hotfix.  

The second one is for BLE access to logs: https://github.com/bsiever/microbit-pxt-blehid .   I could do probably some hack to read directly from flash...but the public read in the PR would be a lot better.

Thanks!

**Comment by jaustin** [comment]
@bsiever I didn't realise the extension had been updated to use the newer CODAL.
I think realistically we won't push a new CODAL to live with these changes until the next MakeCode release. 

However, I am very keen for /beta to start tracking latest CODAL ASAP

Can we either
* use MakeCode's extension versioning so that the extension loads at an older version (before `rotateTo` is required in CODAL) and then have the latest version in /beta 
* mark the extension as 'beta' so there's a cue it will only work in the beta editor? (@abchatra is there any way yet to only have it show in /beta?)

**Comment by bsiever** [comment]
@jaustin A /beta using more recent version of CODAL would be great for me.  It would allow me to have a few additional people test things without the overhead of a local install.   Keep me posted on whether that happens. 

For what it's worth, I have a version of the rotate extension that _does_ work in CODAL 0.2.40: https://github.com/bsiever/microbit-pxt-rotate/releases/v0.1.3 (written before Martin added the `rotateTo()` to CODAL). 

The v2 support relies on two hacks:  replacing a member object in-place and a sketchy use of `delete` to overcome a memory leak (bad practice, but it think it's reliable in this context).  One v2 it only rotates between things being displayed, like after an entire message has scrolled by, rather than entirely dynamically.  On 1.5 it rotates as they are scrolling, which is also what the CODAL update will do in v2.   
 
Off topic: Is there any way to add a specific version of an extension by URL?  I took a quick look at docs and forums and didn't spot anything.

**Comment by martinwork** [comment]
@jaustin @bsiever @abchatra At the time of the PR https://github.com/microsoft/pxt-microbit/pull/4866, the extension had a dependency on makecode.microbit.org 5.1.1.
I assumed MakeCode beta would bump CODAL to 0.2.43.

**Comment by martinwork** [comment]
@bsiever Could you revert the change https://github.com/bsiever/microbit-pxt-rotate/commit/58b6a85ce480f1cf95e6506787e29f3186448b66 to the MakeCode version dependency? Perhaps make it after the current beta (5.1.2)?

**Comment by bsiever** [comment]
@martinwork Do you mean that if `target` in pxt.json is 5.1, the live version of the editor (5.0.12) will use the last extension version of the extension that referred to the MakeCode 5.0.12?

Would this need to be an official git revert or could it just be a new commit?  (I'm assuming official revert and/or removal of the release?)

**Comment by martinwork** [comment]
@bsiever That's a good question! I was just thinking to put back the dependency on a later MakeCode for the current version, hoping that would mean it's not visible in live anymore.

**Comment by bsiever** [comment]
The recent update to production MakeCode,  which now uses CODAL v0.2.55, has resolved this, so I'm closing the issue.
