### ISSUE TITLE
Organization of Music Blocks

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4899]
As we are adding more and more audio blocks, I think it may be time to take a look at how we're organizing these blocks.
Attaching the current list here - and including the Arcade sound blocks as well, as it would be great to have some consistency across.

It seems to me that we have 2 different sets of blocks:
1.  Sounds and sound effects (based on frequency values)
2.  Music (based on musical note values) 
And blocks that affect both (volume, tempo values).
[Music Blocks.pdf](https://github.com/microsoft/pxt-microbit/files/10338452/Music.Blocks.pdf)

Let's discuss how we can best represent these blocks to users.  This issue may be related...https://github.com/microsoft/pxt-microbit/issues/4482.

**Comment by jaustin** [comment]
It's also worth noting that the language across some of these blocks is a bit confusing in the way they now relate to each other. 
<img width="479" alt="image" src="https://user-images.githubusercontent.com/147113/210671282-4645afc1-0e03-4394-9940-9996394d0e60.png">

What's the difference between "play" a melody or "start" a melody, when we "play" a sound (but we can start it in the background, too...). The melodies we "start" are different to the ones we can "play"!
For example the relationship between these options, and then
<img width="426" alt="image" src="https://user-images.githubusercontent.com/147113/210671330-f5066337-d993-4916-bf2c-3cb59cdee9c0.png">

"until done" and "in background" 

More detail in [#4735 ](https://github.com/microsoft/pxt-microbit/issues/3823)

**Comment by abchatra** [comment]
Lets port the play paradigm from the arcade which solves various issues.

**Comment by abchatra** [comment]
@srietkerk  I am assigning this issue to @thsparks
