### ISSUE TITLE
Language telemetry

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4901]
We're looking at micro:bit language telemetry, and it seems a bit fishy - only 2% of users in Japan using Japanese?
Let's investigate that we're accurately sending telemetry events to represent the language of users.
RawEventsCustomEvents 
| where timestamp > ago(60d)
| where cookie == "true"
| where target == "microbit"
| where client_CountryOrRegion == "Japan"
| summarize dcount(user_Id) by lang = tostring(customDimensions.lang)

**Comment by abchatra** [comment]
Fixed by https://github.com/microsoft/pxt/commit/725ce4e142705fa8b9b09aef2dd0b8c6b9b1c456
