### ISSUE TITLE
Error code 909 appearing on my micro:bit v2 and in simulator

### ISSUE THREAD

**Issue by ArleauxMakecode** [microsoft/pxt-microbit#4903]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abchatra** [comment]
Need repro steps
