### ISSUE TITLE
Rename “More…” button to “Settings”

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4919]
**Describe the bug**
Rename “**More…**” button to “**Settings**”

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#editor
2.Mouse over gear button at the top right corner 

**Expect behavior**
It's better to rename “**More…**” button to “**Settings**”

**Actual behavior**
It shows the name “**More…**” when mouse over it

**Screenshot**
![image](https://user-images.githubusercontent.com/59192069/215690716-22c00ee6-a31c-422c-b743-129c48958c07.png)

**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 5,.1.2
3.Microsoft MakeCode version: 8.2.6

**Comment by abchatra** [comment]
Closing P3 issues.
