### ISSUE TITLE
MakeCode V5 seems to ignore dv:mbcodal setting that enables V4 to build some extensions to build for micro:bit V1

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#4926]
Arising from support tickets (private)
https://support.microbit.org/helpdesk/tickets/60032
https://support.microbit.org/helpdesk/tickets/60470

**Describe the bug**

Projects using the bluetooth-midi extension fail to build, though they build on the previous MakeCode.
https://makecode.microbit.org/pkg/microsoft/pxt-bluetooth-midi

**v4.0.24** builds the project for V1 only, and shows in console: 
```
auto-disable mbcodal due to targetconfig entry for microsoft/pxt-bluetooth-midi#v2.0.13
auto-disable mbcodal due to targetconfig entry for github:microsoft/pxt-bluetooth-midi#v2.0.13
```
**v5.0.12** attempts and fails to build for V2 and displays error `Cannot read properties of undefined (reading 'toString')`

Both versions have targetconfig entries for pxt-bluetooth-midi in sections approvedRepos and upgrades (dv:mbcodal)

**v5.0.12** has an additional targetconfig entry in section **approvedRepoLib**
https://github.com/microsoft/pxt-microbit/blob/97491d6832cccab6b5bdc05b58e4c6b5dcc18cdd/targetconfig.json#L356

**To Reproduce**
1. Create a project using the extension
2. Try to build
3. See error

**Expected behavior**
Extension builds as it did on the previous version.

**micro:bit version (please complete the following information):**
not hardware related

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome

**Comment by martinwork** [comment]
@abchatra This issue has been raised again. They are trying to use the Bluetooth midi extension with micro:bit V1.
Support ticket https://support.microbit.org/helpdesk/tickets/60470 (private)

**Comment by abchatra** [comment]
I can reproduce this issue. I will mark for this release.

**Comment by abchatra** [comment]
However, I should say we have found various issues with all bluetooth extensions and recommend not using them at all.

**Comment by martinwork** [comment]
@abchatra Could it be simply that MakeCode no longer looks at the "upgrades" section of targetconfig and the "dv:mbcodal" tag has been missed in "approvedRepoLib"?

**Comment by jwunderl** [comment]
That should be the case, yes

**Comment by abchatra** [comment]
Yes old section is deprecated.

**Comment by martinwork** [comment]
Thanks @abchatra @jwunderl The good news is I think there are only 30 "dv:mbcodal" in the file, of which 14 are in approvedRepoLib. I'll figure out what the other missing one is and make a PR.
