### ISSUE TITLE
Built-in docs in some languages don't load correctly

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#4933]
**Describe the bug**
Showing a block help page inside MakeCode works fine in English, but in Japanese it shows an error message.

**To Reproduce**
1. Go to MakeCode
2. Add the volume block to the workspace
3. Right click > help
4. The help loads correctly
5. Change the language to Japanese
6. Right click > help
7. The help doesn't load

<img width="803" alt="image" src="https://user-images.githubusercontent.com/29712657/217319976-6029aaae-9013-4697-be5e-c61e2fa541af.png">

**Expected behavior**
To show the docs in Japanese.

With the language set to Japanese this page does show the partial translation:
https://makecode.microbit.org/reference/music/volume
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/29712657/217320989-1fb7e476-fc3d-429c-a39d-fecf7f0f91c3.png">

**Screenshots**
Added to the respective sections

**micro:bit version (please complete the following information):**
 Not relevant

**Desktop (please complete the following information):**
 - OS: macOS 12
 - Browser: Chrome
 - Version: 109

**Smartphone (please complete the following information):**
N/A

**Additional context**

makecode.microbit.org version:  [5.0.12](https://github.com/Microsoft/pxt-microbit/releases/tag/v5.0.12)
Microsoft MakeCode version:  [8.0.7](https://github.com/Microsoft/pxt/releases/tag/v8.0.7)
microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
codal-microbit-v2 runtime version:  [v0.2.40](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.40)

**Comment by abchatra** [comment]
I can reproduce this. We seems to be pointing here for loading the side docs.
src="/beta---docs#doc:/reference/basic/show-number:blocks:live-ja"
