### ISSUE TITLE
WebUSB Download fails when micro:bit is attached to robot 

### ISSUE THREAD

**Issue by LabSpace01** [microsoft/pxt-microbit#4940]
**Describe the bug**
When using Micro:bit with SparkFun and Yaboom robots, the MicroBit will pair and download.  When the robot is unplugged from the USB and then plugged back multiple times without powering down the robot, the download becomes stuck.  We had to unplug the Micro:bit and download the code and then plug the Micro:bit back in and drag the code onto it.  This worked.

1. Pair and download code to Micro:bit attached to robot
2. Unplug MicroBit from usb to run robot
3. Plug USB back into Micro:bit, download (Repeat steps 2 and 3 twice)
4. The download becomes stuck

**Expected behavior**
I expected downloads to continue as they did when I first attached the Micro:Bit.

The workaround:  before hooking the USB back to the Micro:Bit, remove power from the robot so the Micro:bit has no power.  Plug in USB and the download works properly.

**micro:bit version 2.2**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]

Windows 10, Chrome , multiple laptops and desktops

**Comment by abchatra** [comment]
This is firmware issue and tracked by the foundation. @microbit-carlos if you have link to any issue report can you add it here.

**Comment by microbit-carlos** [comment]
- https://github.com/microbit-foundation/DAPLink/issues/17
