### ISSUE TITLE
Question - analog set period - sets the same frequency on all pins, even if API call specifies different freq

### ISSUE THREAD

**Issue by lafar6502** [microsoft/pxt-microbit#4950]
**Describe the bug**
Made a simple initialization program that sets P1 and P2 pins to analog
but specifies different period for each pin.
But when checking the signal frequency (with a speaker and also with some cheap oscilloscope) i get the same frequency on both pins, about 1.66 kHz

There's another issue apart from the main one - when I use a servo-related function on another pin (P0, for example), then all PWM frequencies change to about 50Hz - same frequency as on the servo pin.

**To Reproduce**
here is my code from the makecode editor

```
pins.analogWritePin(AnalogPin.P2, 512)
pins.analogWritePin(AnalogPin.P1, 512)
pins.analogSetPeriod(AnalogPin.P1, 1000)
pins.analogSetPeriod(AnalogPin.P2, 600)

```
second example, with servo call:

```
pins.analogWritePin(AnalogPin.P2, 512)
pins.analogWritePin(AnalogPin.P1, 512)
pins.analogSetPeriod(AnalogPin.P1, 1000)
pins.analogSetPeriod(AnalogPin.P2, 600)
pins.servoWritePin(AnalogPin.P0, 180)

```

**Expected behavior**
The frequency of generated signals on P1 and P2 should be different
And setting the frequency on one pin should not affect the frequency of other pins.
Using servo-related functions should not affect other pins as well.

**micro:bit version (please complete the following information):**

V2.21

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome

wersja makecode.microbit.org:  [5.0.12](https://github.com/Microsoft/pxt-microbit/releases/tag/v5.0.12)
wersja Microsoft MakeCode:  [8.0.7](https://github.com/Microsoft/pxt/releases/tag/v8.0.7)
wersja środowisko uruchomieniowe microbit:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
wersja środowisko uruchomieniowe codal-microbit-v2:  [v0.2.40](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.40)

**Comment by lafar6502** [comment]
closing - all pwm outputs on microbit share the same frequency

**Comment by fabianhugo** [comment]
Could this be fixed somehow? Or is there a workaround? In applications where PWM signals with different speeds are needed this can lead to problems, e.g. one high frequency PWM for a motor driver and one slower frequency PWM for a servo.
