### ISSUE TITLE
Assertion error building extension with C++ shim with more than 4 parameters

### ISSUE THREAD

**Issue by adamish** [microsoft/pxt-microbit#4951]
**Describe the bug**
If you call a shim method with more than 4 parameters you get an assertion error.
I cannot seem to find this documented.

**To Reproduce**

main.ts
```
/**
 */
//%
namespace foons {
    /**
     */
    //% shim=foons::fooNative
    export function foo(a : Number, b : Number, c : Number, d : Number, e : Number): void {
        console.log("test")
    }
}
foons.foo(1, 2, 3, 4, 5);
```

foo.cpp
```
namespace foons {
	/**
	 *
	 */
	//%
	void fooNative(int a, int b, int c, int d, int e) {
	}
}
```

**Actual behaviour**
```
main.ts(1,1): error TS9200: Assertion failed
```

**Expected behaviour**
* Successful build

PXT microbit 5.1.2

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Additional context**
Note same code works if  you change to use 4 parameters (remove e from both typescript and .cpp)

**Comment by mmoskal** [comment]
Yes, ARM calling convention changes when there is more than 4 arguments and the current code generator doesn't support this.

**Comment by abchatra** [comment]
Can't fix without lot of compiler changes. Sorry!
