### ISSUE TITLE
Is it possible to persist kids’ code into a backend database?

### ISSUE THREAD

**Issue by syang** [microsoft/pxt-microbit#4958]
I am thinking of building a local community where kids can share their code with each other.

I understand that Makecode does not support Cloud (or self-hosted backend) persistence. Can this be done? 

I am not super familiar with the architecture of makecode, but if this is something aligned with the community, I’d love to be guided to contribute to this idea (if the core team does not have the bandwidth to work on it)

**Comment by eanders-ms** [comment]
We are enabling cloud save for microbit pretty soon. This will enable users to sync their projects to any browser. But what's described here sounds different; more like kids sharing code through a service. @syang can you elaborate on what you'd like to see?

**Comment by abchatra** [comment]
We have share 
<img width="196" alt="image" src="https://user-images.githubusercontent.com/6107272/224384809-7534de00-a06a-4ca1-91b0-f12f1fd814c9.png">
