### ISSUE TITLE
Blocks mode error text colour change since v4 makes errors hard to read 

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#4965]
**Describe the bug**

The text colour in blocks mode error popups has changed since v4, making them hard to read. 

The error popup now disappears after about 2s, which isn't really long enough. In v4 the popup seems to be toggle on/off by clicking the warning triangle. 

**Screenshots**

https://makecode.microbit.org/v4
![image](https://user-images.githubusercontent.com/989126/222128609-982ac89a-2d3e-455e-870b-e6ca029c2e42.png)

https://makecode.microbit.org
![image](https://user-images.githubusercontent.com/989126/222129064-8ff90391-5181-4442-b901-a8f5660679ca.png)

**micro:bit version (please complete the following information):**
not hardware related

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Comment by abchatra** [comment]
This is fixed in beta. Also please share the repro with the exact blocks to verfiy.

**Comment by martinwork** [comment]
Thanks @abchatra . Here's an example https://makecode.microbit.org/_CKU1h17WUKVM. It is fine in beta.
![image](https://user-images.githubusercontent.com/989126/224136681-b80ccb1c-09d2-4af5-b99b-520755b1f7a5.png)

**Comment by abchatra** [comment]
Thanks so much!
