### ISSUE TITLE
Cannot change P0 to any other in RTL languages like Arabic or Hebrew

### ISSUE THREAD

**Issue by schafman** [microsoft/pxt-microbit#4967]
**Describe the bug**
in https://makecode.microbit.org/#editor 
If adding a Pin like "analog write to pin" or any other of the pins, and changing the language to any right to left language like Arabic or Hebrew, the P0 cannot be changed and it keeps "escaping"

**To Reproduce**
1. Go to https://makecode.microbit.org/#editor
2. Click on 'Advanced'
3. Click on 'Pins'
4. add 'analog write to pin P0 to 1023' to either 'on start' or 'forever'
5. on the settings button choose language
6. choose either Arabic, or Hebrew (the problem is on both RTL languges)
7. try to change the P0 - it cannot be changed 

**Expected behavior**
P0 should be accessible also in RTL languages

**Screenshots**
![image](https://user-images.githubusercontent.com/123621966/222414030-eb4240a4-8864-49f4-a26e-348e0040ead8.png)

**micro:bit version (please complete the following information):**
![image](https://user-images.githubusercontent.com/123621966/222414096-3b3f8697-33b1-43fe-910b-7a4b7e90e82f.png)

**Desktop (please complete the following information):**
 - OS: Either Windows 11 or Windows 10
 - Browser : either Chrome or Edge
 - Version Edge: Version 110.0.1587.46 (Official build) (64-bit) / Chrome: Version 110.0.5481.100 (Official Build) (64-bit)

**Additional context**
This is for Arab and Israeli students in the Weizmann institute of science that are suffering from this bug

**Comment by martinwork** [comment]
Related: https://github.com/microsoft/pxt-microbit/issues/4815

**Comment by schafman** [comment]
Hi, why do you reference #4815? Is it under work for fixing?
Thanks

**Comment by martinwork** [comment]
I think that is the same issue. It has been fixed. The fix is available to test in https://makecode.microbit.org/beta.

**Comment by schafman** [comment]
Yes, it is working as expected in the Beta. When do you expect to have it committed into production? 
I am asking, as all the PCs in the institute have a stateless OS, and if it will be too far ahead they will need to change all the images to have the Beta URL instead of the production one. What would you suggest doing?

**Comment by martinwork** [comment]
@abchatra ?

**Comment by abchatra** [comment]
We plan to do a full release in June. However, if need this before that I can do a hotfix. Please let me know.

**Comment by abchatra** [comment]
Verified this is fixed in beta and will be shipped in June.

**Comment by schafman** [comment]
Thanks, Abhijith, I have been waiting for feedback from my contact at the Weizmann Institute. They will wait for the official release in June.
