### ISSUE TITLE
microbit speaker

### ISSUE THREAD

**Issue by naim514** [microsoft/pxt-microbit#4978]
hi there,i want to listen to my mp3 file
 using mp3 player and microbit v2 speaker
help please
thx in advance
kind regards

**Comment by abchatra** [comment]
Unfortunately we don't support mp3 as the memory footprint of microbit is really small and won't fit mp3

**Comment by naim514** [comment]
thx a lot for your answer please can you help me to connect potentiometer to a speaker with 3 pins and microbit to control the sound volumethx in advance kind regards

Envoyé à partir de Yahoo Courriel sur Android 
 
  Le jeu., mars 9 2023 à 18:37, Abhijith ***@***.***> a écrit :   


Closed #4978 as completed.

**Comment by dsssssssss9** [comment]
I gueeing you are the person who asked this on the Makecode Forums as well as my YouTube channel?

If you are using the DFPlayer extension from 51Bit…
https://github.com/51bit/dfplayermini

it has a SETVOLUME block that you can use to control the volume from within your program

I think the other extensions i know about also have some sort of volume control block.

if this is not suitable for your setup please let me know a few more details on your project & i will work out some sort of physical hardware control.

**Comment by naim514** [comment]
hi again no i don´t use dfplayer so i just want to work a simple project to control sound volume by microbit and potentiometer and you can use microbit speaker or an external speaker no pb
so i tried but i don´t succeed
help please and if possible share me the right circuit
by the way i want to let you know that i have speaker v1.1 with 4 pins (gnd,vcc,Nc,sig)
thx in advance 
kind regards

**Comment by dsssssssss9** [comment]
Hi 

I've replied to your question about this in the makecode forums ....
