### ISSUE TITLE
potentiometer with speaker and microbit

### ISSUE THREAD

**Issue by naim514** [microsoft/pxt-microbit#4980]
please can you help me to connect potentiometer to a speaker with 3 pins (gnd,vcc and sig)and microbit to control the sound volume

 thx in advance

 kind regards

**Comment by dsssssssss9** [comment]
I guessing you are the person who asked this on the Makecode Forums as well as my YouTube channel?

If you are using the DFPlayer extension from 51Bit…
https://github.com/51bit/dfplayermini

it has a SETVOLUME block that you can use to control the volume from within your program

I think the other extensions i know about also have some sort of volume control block.

if this is not suitable for your setup please let me know a few more details on your project & i will work out some sort of physical hardware control.

**Comment by abchatra** [comment]
Question answered. Thanks @dsssssssss9 for answering.
