### ISSUE TITLE
Radio drops first message while loading second simulator

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#4986]
**Describe the bug**

When using radio for the first time, we spin up a second simulator to show it working

**To Reproduce**
1. Go to https://makecode.microbit.org/_KPJbgURehgML
2. Click A a single time
3. see second simulator load in response to the radio message
4. see second simulator does not show a smiley face once it is loaded

**Expected behavior**

It'd be nice to queue up the messages that are sent while the second sim is loading (or even just the one that caused it to load in the first place), and make sure they run after the handlers are registered (maybe in initAsync send them over and keep the queue in micro:bit sim).

**Comment by dsssssssss9** [comment]
Hi

Try this code....

https://makecode.microbit.org/_Kh2cpwboHCif

it sends the  string "Dummy" from the ONSTART block which in this case we ignore but it does cause the 2nd  simulator to start so that both simulators are synchronised

Now pressing buttons works as expected

I hope this helps?

**Comment by jwunderl** [comment]
@dsssssssss9 Thanks for the suggestion and for helping out around here :) That's definitely a good work around for now, but this feels like something that would be nice for us to fix so first time users aren't confused by it / don't have to learn a workaround.

Thanks again!

**Comment by dsssssssss9** [comment]
You're most welcome ...
