### ISSUE TITLE
Project thumbnail keeps loading in share dialog

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4987]
**Describe the bug**
**Project thumbnail** keeps loading in **share dialog**

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#
2. Create a project and share the project

**Actual behavior**
**Project thumbnail** keeps loading in **share dialog**

**Expect behavior**
Show the **project thumbnail** in share dialog

**Screenshot**
![1](https://user-images.githubusercontent.com/59192069/225220010-6f4ded38-a92b-4bee-9840-a0ac00dbcd13.gif)

**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 5.1.5
3.Microsoft MakeCode version: 8.6.12

**Comment by abchatra** [comment]
@Sheila111  seems like fixed in 5.1.38. If not reopen.

**Comment by Sheila111** [comment]
Fixed
