### ISSUE TITLE
Two overlapping simulators show if you update a new thumbnail

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4988]
**Describe the bug**
**Two overlapping simulators** show if you **update a new thumbnail**

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#
2. Create a project and **share the project**
3. **Update project thumbnail**
4. Click **Screenshot** or **Record**

**Actual behavior**
**Two overlapping simulators** show if you **update a new thumbnail**

**Expect behavior**
**Only one simulator** shows if you **update a new thumbnail**

**Screenshot**
![image](https://user-images.githubusercontent.com/59192069/225235173-24203a43-65a0-4b40-bbf3-1668b0bce57d.png)
![3](https://user-images.githubusercontent.com/59192069/225234725-ff2b15a4-9b3e-4c3c-81a0-dbd413c39e40.gif)

**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 5.1.5
3.Microsoft MakeCode version: 8.6.12

**Comment by abchatra** [comment]
Either we should fix these issues or remove the record thumbnail feature from the microbit release.
