### ISSUE TITLE
Customize the simulator iframe from an extension

### ISSUE THREAD

**Issue by ross-inksmith** [microsoft/pxt-microbit#4993]
We would like to customize the `makecode-simulator` and `makecode-editor-extension` as provided by [jacdac-docs](https://github.com/microsoft/jacdac-docs), but we are having trouble making these changes to the simulators work outside the local environment. The issue seems to be that there isn't yet a way to make the simulator iframe source from a different url.

What changes I have made so far do work locally when using `?localeditorextensions=1&localhostmessagesims=1`. Hosting our `jacdac-docs` fork on github.io in the same manner as [microsoft.github.io/jacdac-docs]() works locally with `pxt-microbit` when `targetconfig.json` and `simulator.messageSimulators.jacdac.url` in `pxtarget.json` were updated with the fork's url.

Unfortunately, there doesn't appear to be an existing way to configure the simulator iframe from the package like there already is for the editor-extension. 

To create a PR to follow up on this, I'd like some insight in where best to edit. Digging into issue I've tried creating a new item in `simulator.messageSimulators` and updating our fork of `pxt-jacdac` to use that as the type/channel, but [sendCustomEventAsync](https://github.com/microsoft/pxt/blob/master/pxtlib/hf2.ts#L292) checks specifically for a "jacdac" type and therefore throws an error. Given that the simulator is spawned based on the "channel" of the message, I've tried making the extension emmit "jacdac" type messages on a differently named channel but I'm not sure if there's an actual distinction between these fields since they get used Interchangeably.

I'm looking on some guidance on how best make the iframe simulator configurable.

(Originally posted in microsoft/jacdac. Moved here per @pelikhan)

**Comment by ross-inksmith** [comment]
Bump. I'm looking to create a PR to address this issue; would allowing the package to select a different URL in the package pxt.json from a list of approved URLs specified in pxtarget/targetconfig be an acceptable solution?

**Comment by pelikhan** [comment]
Currently, the mapping between a channel type and the simulator is 1-to-1, and defined at https://github.com/microsoft/pxt-microbit/blob/master/pxtarget.json#L219 . There is no support to dispatch channel message to different simulator frames.

**Comment by tballmsft** [comment]
See also: https://github.com/microsoft/jacdac/issues/1373
