### ISSUE TITLE
requesting magnetometer (x,y,z) values triggers a calibration

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#4995]
**Describe the bug**

The magnetometer supports a number of different modes of operation. It is possible to read the raw x/y/z values of the compass without calibrating first, and this gives a good experience to anyone wanting to use the magnetometer to measure local strong magnets (for example making a wand game, etc)

**To Reproduce**
call `input.magneticForce(Dimension.X)` (or any dimension)
-->calibration starts

**Expected behavior**

Uncalibrated X,Y,Z values reported

It looks like MakeCode is enforcing the calibration here https://github.com/microsoft/pxt-microbit/blob/4375b988b21e7fea5188e982205dc184b54e52d7/libs/core/input.cpp#L352-L354 - we don't do this in MicroPython and seems to be fine.

**Comment by abchatra** [comment]
@jaustin feel free to do a PR.

**Comment by abchatra** [comment]
@jaustin to do a PR here.

**Comment by abchatra** [comment]
@jaustin do you want us to take over this change?

**Comment by abchatra** [comment]
Thanks @davidhoness. I have a put up a PR to address this. This should be in /beta soon and will be in product once we release in mid June.

**Comment by abchatra** [comment]
Fixed in beta https://makecode.microbit.org/beta#editor

**Comment by abchatra** [comment]
@davidhoness can you share your program just to make sure we are testing the right scenario?

**Comment by davidhoness** [comment]
Here's the program I am using; https://makecode.microbit.org/_5tb4Du97PY7R

**Comment by abchatra** [comment]
@davidhoness this program has compas heading which will trigger calibration. AFAIK There is no way to do that without calibration.  Fix is only for magnetic force block.

<img width="361" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/6107272/22cb7e5e-9bb1-4778-ac1e-5b836b9918ad">

**Comment by abchatra** [comment]
@jaustin to confirm
