### ISSUE TITLE
Layout inconsistencies in tutorial mode for beta

### ISSUE THREAD

**Issue by kiki-lee** [microsoft/pxt-microbit#5005]
The instructions seem to have nearly twice as much padding at the bottom as they do at the top. Can we shrink that up a bit (or average them out?

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/1633958/227589564-cbe881c5-8f90-4265-8e7e-ac416082978a.png)

Also, can we make the back button the same height as the Next button?
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/1633958/227589529-d84f200f-4a27-4c9f-992f-83f857e88f95.png)

**Comment by thsparks** [comment]
I'm closing this bug, created new bugs for individual issues just so I can track them more easily:

1. Next/back same height: https://github.com/microsoft/pxt-microbit/issues/5029
2. Even out padding around tutorial controls: https://github.com/microsoft/pxt-microbit/issues/5032
