### ISSUE TITLE
Play recording on the sim should have similar reactions to play melody

### ISSUE THREAD

**Issue by kiki-lee** [microsoft/pxt-microbit#5007]
When `play recording` is in the workspace, it should either trigger the v2 sim or add the connection points for the speaker like the `play melody` block does. 

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/1633958/227591121-7dc3f1c5-3b2b-4f31-a902-53ea55fd2dca.png)

**Comment by jwunderl** [comment]
@srietkerk here's how you set the parts so we can detect that a function requires v2 just so you know  `//% parts="microphone"` e.g. https://github.com/microsoft/pxt-microbit/blob/master/libs/microphone/microphone.cpp#L56

**Comment by srietkerk** [comment]
Closed via https://github.com/microsoft/pxt-microbit/pull/5057
