### ISSUE TITLE
local makecode offline help 

### ISSUE THREAD

**Issue by Ricoh-2A03** [microsoft/pxt-microbit#5011]
Offline makecode build help.

Greetings. Our pc lab has win7 32bit installed, each pc is networked but there is no Internet access in the lab. The makecode offline installer doesn't work as it requires a 64bit system, from searching it seems to me that there will be no 32bit support but digging around the github page I came across steps on how to copy makecode locally and run a server. At first it didn't work on the network but I had to use, pxt serve --hostname 0.0.0.0 to have other computers on network to access pc I'm hosting from.

My problem is that when the learners connect actual microbits to the pc's and try to download their code it gives the error, "hex file not available, please connect to Internet and try again.

I think my mistake was somewhere when I initially built the local makecode.

How do I get code download feature to work correctly? 

update : after more reading, I tried using the staticpkg option and then serving that via pxt. seems to be working. Will test in lab tomorrow. 

Thank you.

**Comment by abchatra** [comment]
Just to confirm, @Ricoh-2A03 there are very few 32 bit hardware out there.  Can you try running the x64 on 32 bit and see if they work?

**Comment by Ricoh-2A03** [comment]
> Just to confirm, @Ricoh-2A03 there are very few 32 bit hardware out there. Can you try running the x64 on 32 bit and see if they work?

unfortunately our lab lacks funding for newer hardware but I did manage to resolve the issue by creating a static version of makecode and using that to serve via pxt. now I need to figure out how I add extensions like neopixel to the static build.
