### ISSUE TITLE
Editor tour: "Tour" menu item missing from mobile layout

### ISSUE THREAD

**Issue by eanders-ms** [microsoft/pxt-microbit#5020]
In small-width layout, the help menu contents are moved to the gear menu. Should "Tour" appear here?
Consider moving help contents to a sub-menu if vertical height is an issue.

![image](https://user-images.githubusercontent.com/12176807/227600344-afeb6843-b87b-400c-a3d2-7655d973fcc0.png)

**Comment by abchatra** [comment]
We decided to cut tour from mobile view.
