### ISSUE TITLE
Record and playback doesn't sound right on the hardware

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#5021]
**To Reproduce**
1. Import the project: https://makecode.microbit.org/_Y7kKCLcYKMvc
2. Download to v2 hardware 
3. Press A to and say "hello"
4. Press B to hear back what you have recorded

You hear gibberish

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge

**Comment by abchatra** [comment]
![image](https://user-images.githubusercontent.com/6107272/227600794-08436fb7-4853-48f5-ba25-778d988152b8.png)

**Comment by abchatra** [comment]
@jaustin tracking bug for sound quality.

**Comment by Jaqster** [comment]
I'm still getting quite a lot of whining background noise when I playback the audio on the micro:bit speaker.  @jaustin - any way we can improve the sound quality?

**Comment by jaustin** [comment]
I agree that the current quality in /beta doesn't seem to match the best we've had from the extension in the past.

I think two things would help
1) @JohnVidler or @finnneyj to produce a C++ "reference hex" that they think does record (button A), playback (button B) with the best quality we can for 'medium' microphone sensitivity.  This would allow us to get a reference when we update the MakeCode extension
2) A quick review of the current pipeline setup in the extension. Based on #5063 I wonder if we've still got some issues around the gain

**Comment by abchatra** [comment]
I am going to drop this from the release for now as there is no action from MakeCode side here.

**Comment by abchatra** [comment]
This is completed. Please retest.
