### ISSUE TITLE
Suggestion: Make tutorial area sizable

### ISSUE THREAD

**Issue by eanders-ms** [microsoft/pxt-microbit#5024]
On my screen I have a ton of block canvas real estate, but very little for the tutorial content. I'd love to be able to extend the tutorial area and read all the instructions without having to scroll.

![image](https://user-images.githubusercontent.com/12176807/227604144-e3c2bc90-6dfe-458e-af21-853ad3b42d09.png)

**Comment by jwunderl** [comment]
fwiw I made a quick version of that for tutorials before we can probably reuse https://github.com/microsoft/pxt/pull/9102
