### ISSUE TITLE
Tour: Share icon should be selected by white frame

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#5034]
**Describe the bug**
Tour: **Share icon** should be selected by **white frame**

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#
2. Create a project
3. Help---->**Tour**

**Actual behavior**
**Tour:** The **share icon** should be selected by the **white frame** to be consistent with the other icons

**Screenshot**
![无标题](https://user-images.githubusercontent.com/59192069/228416656-0b85f72b-9ad4-41b1-b6ac-f6b47a5e1d2e.png)
**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 5.1.11
3.Microsoft MakeCode version: 8.6.17

**Comment by kimprice** [comment]
It's not that it's a white frame, it's that everything else has an overlay. I think it's clear enough the way it is now for what it is pointing to and it will be even more clear once I implement the bubble transitions/animations.
