### ISSUE TITLE
Downloading the record project to hardware failed

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#5046]
**Describe the bug**
Downloading the **record** project to **hardware** failed

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#
2. Create a project and add **Record** extension
3. Drag blocks from **Record**
4. **Download** the project to **hardware V2**

**Actual behavior**
Downloading the **record** project to hardware is successful

**Expect behavior**
Downloading the **record** project to hardware failed

**Screenshot**
It shows the error as below:
![image](https://user-images.githubusercontent.com/59192069/231931205-ed77e792-07cf-4404-84a7-24de5b6a51a8.png)
![1](https://user-images.githubusercontent.com/59192069/231931137-6340da10-e1d1-4c3a-958e-a9f0d470fc90.gif)

**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 5.1.15
3.Microsoft MakeCode version: 8.6.20

**Comment by Sheila111** [comment]
1.Here’s my project URL for reference: https://makecode.microbit.org/_Y8kMhm3VC5FP.
2.The test hardware is **V2**.

**Comment by srietkerk** [comment]
Hi! This should be resolved by https://github.com/microsoft/pxt-microbit/pull/5041

Please let me know if there is still an issue!

**Comment by Sheila111** [comment]
Fixed
