### ISSUE TITLE
When using audio recording 'on loud sound' does not work

### ISSUE THREAD

**Issue by microbit-giles** [microsoft/pxt-microbit#5048]
The following program should trigger an audio recording when a loud sound is detected.
Instead, recording starts immediately the program runs, regardless of ambient sound level, and recording is never then triggered when loud sounds are made near the micro:bit:

![image](https://user-images.githubusercontent.com/42380137/232096124-d9917739-ba42-4329-9ff1-78ba232e0f0d.png)

**Comment by martinwork** [comment]
In beta, with CODAL 0.2.50, on loud sound always fires just once at reset, then can't be triggered.
https://makecode.microbit.org/_5YsapEEbcFH1
![image](https://user-images.githubusercontent.com/989126/232102991-52f516a5-da89-4af3-9984-1d8689ffc217.png)

**Comment by microbit-carlos** [comment]
I haven't tested the MakeCode code to confirm, but it looks like these issues might be cause by these CODAL bugs:
- https://github.com/lancaster-university/codal-microbit-v2/issues/301
- https://github.com/lancaster-university/codal-microbit-v2/issues/300
- https://github.com/lancaster-university/codal-microbit-v2/issues/283

**Comment by microbit-giles** [comment]
I'd really like a 'Parrot' project like the one at the top of this issue as the first 'Make it: code it' project using sound recording and playback.

If CODAL bugs are stopping it working, we know if / roughly when a CODAL fix might happen? Should we plan a different project?

**Comment by microbit-carlos** [comment]
This is @JohnVidler's current top priority, so we are planning to do a fix and a tag for MakeCode this week.
