### ISSUE TITLE
Sound level doesn't seem to function during audio playback in beta

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#5060]
**Describe the bug**

In beta, playing back audio seems to block the 'sound level' from updating:
<img width="519" alt="image" src="https://user-images.githubusercontent.com/147113/233650507-18f37beb-e9a3-4eea-80e3-4c3880f08da6.png">
In this examples the sound level doesn't change during playback.

In live, this works in that the sound level continues to update during playback:
<img width="519" alt="image" src="https://user-images.githubusercontent.com/147113/233650062-ddd5748b-0a06-4819-9f0c-c8acead94453.png">

I don't think it's about blocking behaviour or display locking up, as this works fine in beta
<img width="342" alt="image" src="https://user-images.githubusercontent.com/147113/233649377-53c0f450-26ae-4dfe-ac3c-d3b1d66e13c9.png">

Same issue with the audio playback too, but sound level still updates during recording, just not playback:
<img width="386" alt="image" src="https://user-images.githubusercontent.com/147113/233651440-f37c7b75-6346-4134-95a7-7c47b07f09d2.png">
(this doesn't work during playback)

@JohnVidler @finneyj does this look like audio pipeline stuff or something higher level?

**Comment by finneyj** [comment]
Hmmm... I'd be a little surprised, as the input and output audio pipelines are quite independent. I'll do a quick code review though, in case there is some sort of policy in there.

**Comment by microbit-carlos** [comment]
I think what we are seeing, at least with the first example is this:
- https://github.com/lancaster-university/codal-microbit-v2/issues/300
- https://github.com/lancaster-university/codal-microbit-v2/issues/283

With this programme, the sound level get's stuck, but it works after resetting the micro:bit twice.
- [microbit-no-soundlevel.hex.zip](https://github.com/microsoft/pxt-microbit/files/11343848/microbit-no-soundlevel.hex.zip)
- https://makecode.microbit.org/_Y6pLks0bucDe
<img width="547" alt="image" src="https://user-images.githubusercontent.com/29712657/234872147-b2723cf1-902d-4604-871f-1ee5f416c24e.png">

**Comment by jaustin** [comment]
@microbit-carlos I think this is fixed now (as per the OOB) but can you confirm please?

**Comment by microbit-carlos** [comment]
Yes, this can be closed as fixed 👍
