### ISSUE TITLE
No discernable difference in audio when setting microphone sensitivity

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5063]
Changing the microphone sensitivity between low, medium and high - doesn't result in any discernable difference in sound output.
Repro - try recording 3 different sound clips on 3 different micro:bits using Low, Medium and High microphone sensitivity levels.  Play back the audio on all 3 micro:bits.  Notice no difference in sound recording.
![image](https://user-images.githubusercontent.com/22108954/233700215-a1c0caa4-3134-4df4-90c8-a28361a47b24.png)

**Comment by jaustin** [comment]
@finneyj @JohnVidler Could you please test the gain values that @srietkerk is using from C++ and confirm you think they're a good set for the range?

**Comment by srietkerk** [comment]
Will do more investigation and resolve this after the changes from this issue: https://github.com/lancaster-university/codal-microbit-v2/issues/324

**Comment by abchatra** [comment]
@srietkerk are you tracking this one?
