### ISSUE TITLE
Bug with Robobit extension

### ISSUE THREAD

**Issue by harwalan** [microsoft/pxt-microbit#5069]
**Describe the bug**
Using the Robobit extension, code will not download to device.  

**To Reproduce**
Create new project
Add Robobit extension
Download code to device
Error flashes on bottom of screen:

  -> Line 1 ('sendBufferAsm:'), error: label redefinition

**Expected behavior**
No error, and a code download.

**Screenshots**
![Screenshot 2023-04-23 at 4 08 16 PM](https://user-images.githubusercontent.com/443365/233869177-4789ccf5-9e26-451d-afa3-b59ab9906c9c.png)

**micro:bit version (please complete the following information):**
1.3 version of code is being used with Mk3 version of Robo:bit

**Desktop (please complete the following information):**
 - Mac
 - Chrome
 - 112.0.5615137.

**Comment by abchatra** [comment]
@harwalan you need to file the issue on the extension repo here: https://github.com/4tronix/Robobit
