### ISSUE TITLE
Disappearance of code created in MakeCode beta when using the share option

### ISSUE THREAD

**Issue by microbit-lucy** [microsoft/pxt-microbit#5070]
**Describe the bug**
When sharing code from MakeCode beta some of the code was missing when the URL was opened. 

**To Reproduce**
1. This is the code I was trying
![image](https://user-images.githubusercontent.com/102724242/234007930-5d5793c0-f4df-476f-9aec-22dbd2a65994.png)

2. I used 'share' to create a shareable URL
![image](https://user-images.githubusercontent.com/102724242/234008150-2d152a39-b1dd-4347-b5ab-402986a134b4.png)

3. Note that the thumbnail never loads (this may be another bug?)
4. Check the code in the URL shared: in this case https://makecode.microbit.org/_1bh5xqWwW1rf
5. This code does not match the original - lots of code is missing, not just the beta features. The code is missing in the preview and in the 'edit code' whether you open it in live MakeCode or beta. 
![image](https://user-images.githubusercontent.com/102724242/234008770-2996fb59-b4e6-4310-81cb-8dda80ee20bd.png)

**Expected behavior**
The original code shared via the share link should be available when the shared URL is opened. 

**Screenshots**
Included above

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.6.1
 - Browser: Chrome 112.0.5615.137

**Comment by abchatra** [comment]
This is using new beta features like record extension. If you import the project into /beta editor you should be able to see all the right blocks. Live doesn't understand the new extension and gives up half way. Try importing the same link into /beta and see if you can get back all the bugs. 

We don't support beta version for share links.

**Comment by abchatra** [comment]
We have a separate tracking bug for https://github.com/microsoft/pxt-microbit/issues/4987

**Comment by microbit-lucy** [comment]
Great, thanks. I suspected that might be the case.
