### ISSUE TITLE
Simulator doesn't change to V2 after adding record block

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#5073]
**Describe the bug**
Simulator doesn't change to **V2** after adding **record** block

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#
2. Add extension **Record** and drag a **record** block
3. Observe the simulator

**Actual behavior**
Simulator doesn't change to **V2** after adding **record** block

**Expect behavior**
Simulator changes to **V2** after adding **record** block. Because record block is V2 only

**Screenshot**
![image](https://user-images.githubusercontent.com/59192069/234228538-17036f52-e1e9-45db-8c93-2e2e841e1aa1.png)

**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 5.1.21
3.Microsoft MakeCode version: 8.6.27

**Comment by srietkerk** [comment]
Closed via https://github.com/microsoft/pxt-microbit/pull/5057
