### ISSUE TITLE
Ringbit: Brick Cars link issue

### ISSUE THREAD

**Issue by tracyknapik** [microsoft/pxt-microbit#5074]
**Describe the bug**
This link on the Ring:Bit page doesn't work.
**Website URL**: [](http://wiki.elecfreaks.com/en/microbit/building-blocks/ringbit-bricks-pack/ringbit_bricks_pack_case_02/)
**The link that doesn't work**: [](https://makecode.microbit.org/_4vHR21E92J0J)

**To Reproduce**
1. Go to ['...'](http://wiki.elecfreaks.com/en/microbit/building-blocks/ringbit-bricks-pack/ringbit_bricks_pack_case_02/)
2. Scroll down to '....' in the CODE section.
3. Click on the link in the CODE section that takes you to the code to download.
4. See error - Link doesn't work.

**Expected behavior**
I am supposed to see the code.

**Screenshots**
![image](https://user-images.githubusercontent.com/105086818/234292772-da4b8a4c-2fd3-4186-b535-c3f0b1838eef.png)
![error](https://user-images.githubusercontent.com/105086818/234293278-a4ec8db0-d9f7-4219-8c43-79a49006d7f3.PNG)

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 -  not hardware related 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 112.0.5615.138

**Comment by abchatra** [comment]
Seems fixed now.
