### ISSUE TITLE
Can't change language if not sign in

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#5079]
**Describe the bug**
Can't **change language** if **not sign in**

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#
2. **Change language**
3. **Sign in** account and **change language**

**Actual behavior**
Can't **change language** if **not sign in**

**Expect behavior**
Language can be changed whether signing in or not

**Screenshot**
![1](https://user-images.githubusercontent.com/59192069/234514226-eff20e52-8398-4489-b2ad-ac03bda568e2.gif)

**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 5.1.21
3.Microsoft MakeCode version: 8.6.27

**Comment by jwunderl** [comment]
Related: https://github.com/microsoft/pxt-microbit/issues/5076
