### ISSUE TITLE
Extension graphics in gallery

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5088]
Update some of the images for the Recommended extensions in the gallery:
![image](https://user-images.githubusercontent.com/22108954/234986255-62c42f7e-55f8-46c6-a6ed-65d46092d572.png)

**Comment by jaustin** [comment]
Images are here
[MakeCodeExt_Thumbnails.zip](https://github.com/microsoft/pxt-microbit/files/11759675/MakeCodeExt_Thumbnails.zip)

**Comment by jaustin** [comment]
Have updated the record/playback and the datalogging extensions here https://github.com/microsoft/pxt-microbit/pull/5315

**Comment by abchatra** [comment]
Fixed
