### ISSUE TITLE
Web USB: Downloading doesn't work if you have another session open on different browser

### ISSUE THREAD

**Issue by srietkerk** [microsoft/pxt-microbit#5090]
**To Reproduce**
1. Open the editor in one browser
2. Click download and complete the flow so the code downloads to the device
3. Open the editor in a separate browser 
4. Click download and go through the steps
5. The download button stays the way it looks before the download works
6. If you click download again, it will take you through the flow again

In Chrome:
<img width="537" alt="image" src="https://user-images.githubusercontent.com/49178322/234986443-03a4b661-9a7d-4dfb-b1ce-ba34466a8b79.png">

In Edge, at the same time:
![image](https://user-images.githubusercontent.com/49178322/234987329-eba1b6d9-99f5-4dc1-8682-eb96c7f3a3bd.png)

https://user-images.githubusercontent.com/49178322/234987781-685d3d92-3de5-4000-a045-f7f3b9c1e96a.mp4

What happens in Chrome when Edge has the download session running:
https://user-images.githubusercontent.com/49178322/234988086-ce349e12-1af4-4407-9db8-9354bc857dbd.mp4

Not sure if this is helpful or if it would change anything, but I was downloading to a micro:bit V2.

**Expected behavior**
If you have multiple sessions of the micro:bit editor open, you should be able to download.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Edge

**Comment by srietkerk** [comment]
For added context, I get this error in Chrome, which makes sense. We just might want to default to the "download failed" branch and allow for just downloading the hex if the device is already being used.

<img width="620" alt="image" src="https://user-images.githubusercontent.com/49178322/234989851-a0713049-7b10-4f5c-84db-113a9d689ddc.png">

**Comment by jaustin** [comment]
This also affects other tools that use web USB and the micro:bit
