### ISSUE TITLE
Record icon in browser tab does not disappear when audio recording is finished

### ISSUE THREAD

**Issue by thsparks** [microsoft/pxt-microbit#5091]
While recording audio, this red icon appears in my browser tab (in Edge):
<img width="103" alt="image" src="https://user-images.githubusercontent.com/69657545/234988561-bef09a1a-b060-4c8d-a883-b3065b9b6c8e.png">

I think the icon is expected during recording, but it doesn't go away once recording is finished, and I'd guess it probably should?

**Comment by abchatra** [comment]
May be fixed by this? https://github.com/microsoft/pxt-microbit/pull/5103

**Comment by srietkerk** [comment]
No, this is something different.
