### ISSUE TITLE
"oops, no device was paired" message on pairing with new flow in /beta

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#5098]
I went through a pairing flow as follows:
* Start with a V1 that had very old firmware (0234) so didn't show up in the dialog
* fail to find it twice
* swap to a V2 micro:bit with new firmware
* pair successfully

I got a little "oops, no device was paired" message. But pairing was fine. (though the first flash didn't work, about to file that as a new issue)

I wasn't quick enough to catch it as a screenshot, but it was a blue popup message.

**Comment by jwunderl** [comment]
Same as https://github.com/microsoft/pxt-microbit/issues/5099, fix is in https://github.com/microsoft/pxt/pull/9493
