### ISSUE TITLE
Chrome lock icon (for unpairing micro:bit) will change in September

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5109]
The chrome lock icon, used to disconnect the micro:bit from MakeCode, will change with Chrome 117 in September 2023.

https://blog.chromium.org/2023/05/an-update-on-lock-icon.html

This icon is described and  shown in the "How to unpair your micro:bit" modal:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/29712657/235868527-ff8fd9f2-c387-4cb8-9140-4cfe97ef7bbc.png">

**Comment by abchatra** [comment]
There is an api to forget the device https://wicg.github.io/webusb/#dom-usbdevice-forget

We should use it instead of showing the gif.
