### ISSUE TITLE
recording extension sim: audio is playing block not working

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5127]
With this programme, the `[audio is [playing]]` block doesn't seem to work. The animation inside the while loop never executes, but the display is cleared immediately after the recording starts playing:
<img width="398" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/b7710f57-c50e-4e2c-91c1-1ed133ada3b3">

> makecode.microbit.org version:  [5.1.26](https://github.com/Microsoft/pxt-microbit/releases/tag/v5.1.26)
> Microsoft MakeCode version:  [8.6.33](https://github.com/Microsoft/pxt/releases/tag/v8.6.33)
> microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
> codal-microbit-v2 runtime version:  [v0.2.50](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.50)

**Comment by abchatra** [comment]
I can reproduce this issue.
