### ISSUE TITLE
Data logger simulator: Delete block does not remove data from sim

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5129]
**Describe the bug**
When the `[delete log]` block is meant to be executed, the simulator does not erase the data displayed.

**To Reproduce**
1. Open the https://makecode.microbit.org/_P5sX7p7ALT4q project
2. Go to the simulator
3. Data entries are appended and nothing is erased

<img width="585" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/56a516dd-f781-454f-85f2-9c89484086f7">

```ts
datalogger.mirrorToSerial(false)
basic.forever(function () {
    datalogger.deleteLog(datalogger.DeleteType.Fast)
    datalogger.log(datalogger.createCV("A", randint(0, 10)))
    basic.pause(1000)
})
```

**Expected behavior**
Every `forever` iteration it's meant to erase the data, and only display a single entry.

**Screenshots**

<img width="710" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/f87127aa-b50e-4a7c-bee3-fc7a36259da4">

**micro:bit version (please complete the following information):**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
makecode.microbit.org version:  [5.1.26](https://github.com/Microsoft/pxt-microbit/releases/tag/v5.1.26)
Microsoft MakeCode version:  [8.6.33](https://github.com/Microsoft/pxt/releases/tag/v8.6.33)
microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
codal-microbit-v2 runtime version:  [v0.2.50](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.50)

**Comment by JohnVidler** [comment]
The simulated log _also_ includes everything for the CSV download as well.
