### ISSUE TITLE
A comment block is very much needed

### ISSUE THREAD

**Issue by HanaZimmermanKarl** [microsoft/pxt-microbit#5135]
Comments within an instruction block, help explain decisions about that block, if one looks for the comment.
But comments are many times about a whole section of instructions.

A new block, that will be a comment block and not an instruction block, can be of great help.
It could be used to explain a solution, and clarify some decisions made in a section or the hole program.

If it could be designed in such a way that it can "show" the section that it "comments", that could be even greater,
(maybe something like the loop or if or event "arms", but making it very distinctive of instructions "arms")

Comment blocks can help in the design of a program, and be used to write "pseudocode"  that can easily be replaced later by real code.

Thanks!

**Comment by abchatra** [comment]
We have comment block in workspace (right click) and on each block.

**Comment by HanaZimmermanKarl** [comment]
@jaustin thanks much for your detailed reply!
@abchatra Thank you too!
I was looking for a comment block that would look something like this:
![image](https://github.com/microsoft/pxt-microbit/assets/112929044/4b11adbe-9002-4866-a12c-89bc1e02a651)
A block that can be left their or replaced by a function call.
Any way, I did not know about the ability to add comments in the canvas.
It is a cool option!
Thanks much!
