### ISSUE TITLE
If statements that have return statements causing the return statement to clip into the bottom of the if-statement

### ISSUE THREAD

**Issue by ProjectHSI** [microsoft/pxt-microbit#5142]
**Describe the bug**
The return statement clips into the bottom of the if statement when it is inside of the if statement.

**To Reproduce**
1. Create a function.
2. Put a if statement in that function.
3. Grab a return statement in that block. This might happen with other ending blocks, although this is not tested.
4. The return statement now intersects the bottom of the if statement.

**Expected behavior**
The return statement terminates the if statement cleanly. That being there isn't any clipping going on.

**Screenshots**
<img width="377" alt="Screenshot 2023-05-16 095558" src="https://github.com/microsoft/pxt-microbit/assets/57279339/0b4f9a82-096f-478a-98e4-d0d5775e2eef">

**micro:bit version (please complete the following information):**
Not hardware related.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox 
 - Version 113.0.1 (64-bit)

**Additional context**
This issue also affects MakeCode Arcade and likely other MakeCode editors.

I'm not entirely sure about the [Issues Policy](https://github.com/microsoft/pxt/blob/master/CONTRIBUTING.md#issue-tracker-guidance), this is my first issue for a PXT repo so please tell me if I did something wrong, I promise to have read the issues policy entirely and I _think_ this is the right repo for this issue.

**Comment by ProjectHSI** [comment]
**NOTE: REPLACED BY https://github.com/microsoft/pxt/issues/10013. IF THAT ISSUE IS CLOSED FOR BEING A DUPLICATE, THIS ISSUE SHALL BE RESOLVED HERE, OTHERWISE, THIS ISSUE SHALL REFLECT THE STATUS OF THAT ISSUE.**

**Comment by ProjectHSI** [comment]
Issue Clarification: Return statement visuals are buggy in general, and don't just occur with if statements.

**Comment by abchatra** [comment]
This is fixed in /beta.
