### ISSUE TITLE
WebUSB dialog clean up suggestions

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5156]
Step 2 Dialog - 
![image](https://github.com/microsoft/pxt-microbit/assets/22108954/e1b6e7c7-52a7-48b3-95c9-ebe95dad9c2a)

- Can we add a border around the gif?  Or maybe crop the top a bit so we don't see the chopped-off browser address?  Just trying to polish this up a bit...
- Remove "We recommend pairing for easy downloads" - we're already pushing them down this path, we don't need to justify it, and there's no action for the user.
- Wording suggestion: "Press the Pair button below. A window will appear in the top left of your browser. Select the micro:bit device and click Connect."

Connect to micro:bit Dialog - 
![image](https://github.com/microsoft/pxt-microbit/assets/22108954/7c849dcb-ef2c-4f0f-b2ca-04105a49a967)

- Suggest removing the text "If you need to unpair this micro:bit, you can do so through the '...' menu next to the 'Download' button".  It's confusing, and not helpful at this moment.

**Comment by jwunderl** [comment]
![selecting-microbit-take-four](https://github.com/microsoft/pxt-microbit/assets/5615930/51517d78-81fe-4733-af48-bd86287b15ef)

drew over the url, maybe looks better? for what it's worth I was semi-intentionally including it to give a minor visual association of "this'll most likely show up near the navigation bar," but probably too subtle / just ends up looking a little 'off'

And with the text changes: 

![image](https://github.com/microsoft/pxt-microbit/assets/5615930/b5bc2290-b581-491c-8f8d-f50face02a50)

![image](https://github.com/microsoft/pxt-microbit/assets/5615930/1a655c67-9323-438e-a51e-16ef8a95e8ef)

I trimmed the top left as I've been seeing it a bit inconsistent across devices; sometimes a bit more centered, on some screens full width, and I'm not certain on behavior in rtl -- I feel like top should be enough though with the gif / etc as back up? (good chance the students will just skim over it anyways)

**Comment by Jaqster** [comment]
Looks great!  Thanks Joey!
