### ISSUE TITLE
Clicking mute button in safari is not unmuting the simulator

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#5158]
Seems like Safari is getting even more strict about this! If you click inside the iframe (like on the microbit itself) then the sound starts playing. To work around this, we will likely need to add an unmute button that is inside the iframe itself.

Tested in Safari Version 16.4 (18615.1.26.110.1)
On macOS 13.3.1 (a)

**Comment by abchatra** [comment]
I vaguely remember this being done before in arcade.
