### ISSUE TITLE
Remove default blocks from tutorials that don't need them

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5167]
Hi Galen, can you go through and remove the default On Start and Forever blocks from the tutorials that don't use them?
Just taking a look, at the first row:
- Flashing Heart: remove On Start
- Name Tag: remove On Start
- Smiley Buttons: remove On Start and Forever
- Dice: remove On Start and Forever
- Love Meter: remove Forever
- Micro Chat: remove Forever

@jwunderl or @kiki-lee - do you know what the markdown is for removing these default blocks from the workspace in a tutorial?

**Comment by jwunderl** [comment]
````
```template
//
```
````
will show only on start,

````
```template
basic.forever(() => {

})
```
````

will show only forever. I don't believe there is one that covers Smiley Buttons and Dice by completely removing both to have a complete empty workspace now as typescript always decompiles to at least an on start if nothing else is present; maybe leaning towards having the event in for the first step might be better there, or just leave the extra on start I guess (empty workspace feels a little bad either way)

That said @thsparks minor fix needed for ` ```template` tutorials in new layout: 
![image](https://github.com/microsoft/pxt-microbit/assets/5615930/daf2eb9c-d5b2-4998-a3f7-f9ae6025c735)
need to hide that button 'replace my code' button when not in a skillmap

**Comment by kiki-lee** [comment]
I think I was able to (accidentally and to my dismay) get `on start` to go away in Arcade by declaring a kind in the template.  There may be a similar hack we can employ here?

**Comment by ganicke** [comment]
The best way at the moment is to seed the workspace with the first block...

````
```template
basic.forever(function() {})
```
````
