### ISSUE TITLE
Add code validation rules

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5169]
Hi Galen, can you help us add code validation to a few of the micro:bit tutorials?
@kiki-lee and @thsparks know how to do this and can show you...

**Comment by kiki-lee** [comment]
Happy to help. 
@ganicke Code validation is a lot like adding blockconfig.global or local.  

Here's the documentation page for it (it's at the bottom)
https://dev.makecode.com/writing-docs/tutorials/basics

Or, you can see how it's used in the Collect the Clovers tutorial:
https://github.com/microsoft/pxt-arcade/blob/master/docs/tutorials/collect-the-clovers.md
