### ISSUE TITLE
Changing tempo value in melody dialog doesn't take effect 

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#5179]
**Describe the bug**
Changing **tempo value** in **melody** dialog doesn't take effect 

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#
2. Drag block "**play melody at tempo until done**" 
3. Click on the music note to open the music editor
4. Change **tempo value** and see if it takes effect

**Actual behavior**
Changing **tempo value** in **melody** dialog doesn't take effect 

**Expect behavior**
Change **tempo value** in **melody** dialog successfully

**Screenshot**
![1](https://github.com/microsoft/pxt-microbit/assets/59192069/b8675c3b-7136-404c-bf66-0036e960b84f)

**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 5.1.30
3.Microsoft MakeCode version: 8.6.39

**Comment by abchatra** [comment]
Seems like recent regression.
