### ISSUE TITLE
WebUSB fail

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5189]
Windows with Edge and v2 micro:bit.
Paired with WebUSB and did a first program download fine.
On a subsequent download, I get an error message and it fails to download via webUSB - automatically creates a file download.
Project - https://makecode.microbit.org/_1LuLR9KTYUAA
![image](https://github.com/microsoft/pxt-microbit/assets/22108954/22c053c8-b29e-431c-b372-c8e8210fe457)

**Comment by abchatra** [comment]
Can this be resolved now?

**Comment by abchatra** [comment]
Assuming fixed.
