### ISSUE TITLE
It will download as file if close the download dialog

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#5210]
**Describe the bug**
It will **download as file** if close the download dialog

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#
2. Create a project
3. **Connect your microbit** to computer
4. Click **Download** button 
5. Click **Next** to get into step2 in the **download dialog**
6. **Close the dialog**

**Actual behavior**
It will **download as file** if you close the download dialog

**Expect behavior**
The file **won't be downloaded** if you close the download dialog

**Screenshot**
![1](https://github.com/microsoft/pxt-microbit/assets/59192069/ee4789bf-0846-4451-ae01-1f7098a2946c)

**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 5.1.35
3.Microsoft MakeCode version: 8.6.48

**Comment by abchatra** [comment]
@Sheila111 this is expected as they clicked on download we want to download the file if they close the webusb dialog.
