### ISSUE TITLE
Screenshot button keeps spinning if you share project

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#5224]
**Describe the bug**
**Screenshot** button keeps spinning if you **share project**

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#
2. Create a project 
3. Click **share** button to enter the share dialog

**Actual behavior**
**Screenshot** button keeps spinning if you **share project**. The issue always repro whether you share or not, once you enter the share dialog.

**Expect behavior**
**Screenshot** button won't spin if you share project.

**Screenshot**
![2](https://github.com/microsoft/pxt-microbit/assets/59192069/09a7413c-e8e2-4351-bb85-f79403afcc30)

**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 5.1.37
3.Microsoft MakeCode version: 8.6.48

**Comment by Sheila111** [comment]
The issue can restore if you refresh the page

**Comment by abchatra** [comment]
@kimprice resolve if fixed.

**Comment by kimprice** [comment]
Yea this should be fixed. I just need to bump pxt and then microbit, which I'm doing now.
