### ISSUE TITLE
New project thumbnail can't be generated

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#5225]
**Describe the bug**
New **project thumbnail** can't be generated

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#
2. Create a project and **share** the project
3. Click "**Update project thumbnail**"
4. Click **Screenshot** or **Record** to generate new project thumbnail

**Actual behavior**
New **project thumbnail** can't be generated no matter you click **Screenshot** or **Record**

**Expect behavior**
It can generate new **project thumbnail** if you click **Screenshot** or **Record**

**Screenshot**
![4](https://github.com/microsoft/pxt-microbit/assets/59192069/ac43b5d8-e89d-4478-a515-c9a69c33c440)

**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 5.1.5
3.Microsoft MakeCode version: 8.6.12

**Comment by abchatra** [comment]
@kimprice resolve if fixed.

**Comment by kimprice** [comment]
Yea this should be fixed. I just need to bump pxt and then microbit, which I'm doing now.
