### ISSUE TITLE
Docs for the recording extension

### ISSUE THREAD

**Issue by srietkerk** [microsoft/pxt-microbit#5240]
Right now, the recording extension's "Learn More" page will give users a 404; we want users to be able to visit that docs page. 

I'm not a huge fan of how I wrote these, so please modify, but I wanted to give a bit more context on what each block does:

**Record block:** records user audio for a short period of time. Recording "until done" will wait until the audio buffer is full before executing any code after it. Until done can still be interrupted by events, though! Recording "in the background" will start recording and will continue to fill the audio buffer but will also continue executing sequential code as the buffer fills. This means if you have record in background right before play, you won't hear any sound because the audio immediately stopped recording!
 
**Play block:** plays whatever recorded audio is in the audio buffer. If there is nothing in the buffer, nothing will happen. Playing "until done" and "in the background" behaves similarly as the record block.
 
**Audio is block:** checks the state of the audio buffer. Will return true or false to tell the user if the audio is playing, recording, stopped or has nothing in it. 
 
**Set sample rate block:** modifies the speed at which the audio buffer collects or plays back data. Modifying this up and down for playback or recording will make your recording sound fast or slow!
 
**Set microphone sensitivity block:** modifies how much sound the microphone on the micro:bit will pick up. Setting the microphone to low sensitivity will make the microphone pick up louder sounds. Setting the microphone to high sensitivity will make the microphone pick up all sorts of noise that you might not hear!

**Comment by ganicke** [comment]
I got a stub branch going for this. It's the next task on my list.

https://github.com/microsoft/pxt-microbit/compare/audio-recoding-ref-pges

RE: #5222
