### ISSUE TITLE
radio examples like chuck-a-duck broken in beta simulator

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#5243]
**Describe the bug**
The radio chuck-a-duck program doesn't work on /beta on the simulator, as far as I can see

I notice that there's a change in when the simulator appears between live and beta.

Take this program:
<img width="328" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/147113/5d477d2f-b738-4924-b19a-7e9442da0797">

Normally this will allow you to try 'chuck-a-duck' in the simulator, however in the current /beta the radio message never appears to be received by the 'top' micro:bit

Here's the simulator on /beta
![beta sim radio broken](https://github.com/microsoft/pxt-microbit/assets/147113/88bd9724-6b68-47ae-a8d2-2bbb2fdb1611)

Here's the simulator on live (working)
![live sim radio working](https://github.com/microsoft/pxt-microbit/assets/147113/4d732372-26c3-4468-a802-ef72920bb1d5)

cc @abchatra this is a very common/popular example commonly used as a live demo

**Comment by microbit-carlos** [comment]
I can confirm I can replicate this issue on /beta:

> makecode.microbit.org version:  [6.0.1](https://github.com/Microsoft/pxt-microbit/releases/tag/v6.0.1)
> Microsoft MakeCode version:  [8.6.52](https://github.com/Microsoft/pxt/releases/tag/v8.6.52)
> microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
> codal-microbit-v2 runtime version:  [v0.2.54](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.54)

```ts
radio.onReceivedNumber(function (receivedNumber) {
    basic.showIcon(IconNames.Duck)
})
input.onGesture(Gesture.Shake, function () {
    basic.clearScreen()
    radio.sendNumber(1)
})
radio.setGroup(1)

```

**Comment by abchatra** [comment]
@jwunderl regression from your change to spin the simulator early?

**Comment by jaustin** [comment]
I can confirm that this fix works for me too
