### ISSUE TITLE
Beta editor: SPI communication & beta highlighting

### ISSUE THREAD

**Issue by jxns** [microsoft/pxt-microbit#5246]
Hello,
just wanted to inform you here that there is obviously something wrong with the SPI communication in the beta editor.
I am currently developing a library for an Analog-Digtal-Converter and noticed that its working good in normal editor and not in the beta.

Another small wish:
Please work on the visibility in the beta editor. I just spend a full week searching for the bug in my SPI communication, not knowing that I somehow switched to the beta editor. It looks excactly like the normal editor. A little highlighting would be very helpful...

**Comment by abchatra** [comment]
@jaustin @carlosperate anything in codal? @jxns is there a repro you can share?

**Comment by microbit-carlos** [comment]
The only related change was this one, to be able to reassign pins:
- https://github.com/lancaster-university/codal-microbit-v2/issues/226

@jxns could you share more info about how it is failing?

**Comment by jxns** [comment]
Of course.
The file is this one: https://github.com/joy-it/pxt-RB-JoyPi-Advanced/blob/main/ADC-TLA2518.ts

It is working fine in the normal version, but is producing almost only wrong readings in beta version.

I checked the communication with a logic analyzer and the bytes sent looked good. But the answers on MISO looked off.
My guess was that there is something wrong with the `pins.spiFormat(8, 0);` but I can not verify my guess.

**Comment by microbit-carlos** [comment]
Hi @jxns, Thanks for sending the SPI code to help us debug it!

MakeCode 2023 was released this week: https://makecode.com/blog/microbit/2023-release

In the meantime, while we look into this issue, you can use the previous MakeCode release with this URL: https://makecode.microbit.org/v5


Would you be able to also test your project in these MakeCode test deployments? They have different CODAL version (the micro:bit abstraction layer), and will help us narrow down the release that introduced the issue.
MakeCode v5 uses CODAL 0.2.40, and v6 uses 0.2.55, so checking these intermediate releases would be quite useful:
- CODAL 0.2.42: https://makecode.microbit.org/app/7a9d7cf0337ed8d53fc507a899a5d414ee59a54d-9c844136fb
- CODAL 0.2.43: https://makecode.microbit.org/app/37f6efa929bcadb89d3f5b689c0cf3cae27e49d1-df227f1388
- CODAL 0.2.48: https://makecode.microbit.org/app/62bd528c2aa51e6342a764c506492937d31ba568-a9bfe06ee6


Thanks!

**Comment by jxns** [comment]
Hi @microbit-carlos 
Thank you very much for the link! This will help me to continue my development.
Of course, I will be happy to help in finding the issue!

CODAL 0.2.42: No issues - SPI is working fine
CODAL 0.2.43: No issues - SPI is working fine
CODAL 0.2.48: SPI is NOT working correct here

If there is anything more I can do narrowing things down, just let me know!

**Comment by microbit-carlos** [comment]
Thanks @jxns!

The next step for us would be to find a SPI device to test with and try to replicate with a CODAL C++ programme.

If you are able to create a simple (the smaller the better) C++ CODAL programme that replicates the issue that might also be quite useful. If we have a C++ example that we know fails it's possible we might be able to find the bug even if we don't try it directly with the real hardware.

**Comment by jxns** [comment]
@microbit-carlos Unfortunately I have never worked with CODAL. Do you might have a short introduction or something to know where to quick start?

**Comment by jxns** [comment]
@microbit-carlos any updates on this?

**Comment by abchatra** [comment]
@jaustin @carlosperate  possible to address this in aug release?

**Comment by microbit-carlos** [comment]
We'll see if we can fit it in the next CODAL tag, but will depend on external factors as we don't have a dedicated codal person at the moment.

**Comment by abchatra** [comment]
@carlosperate does this needs to be tracked for this release?

**Comment by microbit-carlos** [comment]
For the post-release hotfix, yes.

**Comment by microbit-carlos** [comment]
Hi @jxns, I'm looking at this at the moment and struggling to replicate with other SPI devices.

I don't have a https://www.joy-it.net/en/products/RB-JoyPi-Note or a TLA2518 ADC to be able to test directly, but I've noticed that the JoyPi Note does have other SPI devices on board. Is the issue only experience with the TLA2518?
Do the other SPI devices like the gyroscope, TFT and RFID work correctly?

Have you tried increasing the 40 microsecond delays between transactions in the TLA2518 drive in case that helps?

**Comment by abchatra** [comment]
@jxns still an issue?

**Comment by jxns** [comment]
Sorry, I am currently not active in this project so I cannot test anything at the moment.

**Comment by microbit-carlos** [comment]
Hi @jxns 
Thanks for letting us know. Just in case you still remember, when testing the extension at the time you found the issue, did you also have SPI problems with the other SPI devices like the gyroscope, TFT and RFID? or was it just the TLA2518?
