### ISSUE TITLE
offline app: built-in extensions should work offline (audio recording, for example)

### ISSUE THREAD

**Issue by eanders-ms** [microsoft/pxt-microbit#5252]
1. Run the offline app without internet connection.
2. Make a simple program using the audio recording blocks.
3. Click download.

Notice the compilation error message.

The audio recording/playback blocks are not usable without an internet connection.

Suggestion: precompile and include hex files for builtin extensions.

**Comment by jwunderl** [comment]
Ahh I think it's probably not checking for https://github.com/microsoft/pxt-microbit/blob/master/libs/audio-recording/pxt.json#L14 when building or something, that's the only thing I can think of as different vs datalogger; code is here https://github.com/microsoft/pxt/blob/master/cli/cli.ts#L2441, can point you to where it builds in offline app devops build.

**Comment by jwunderl** [comment]
Combination of https://github.com/microsoft/pxt-microbit/pull/5259 and https://github.com/microsoft/pxt/pull/9579 fixed this (5259 for removing disables variant, 9579 for packing in a matching hex file correctly)~
