### ISSUE TITLE
With the new micro:bit layout, we need to hide all the step titles using { }

### ISSUE THREAD

**Issue by kiki-lee** [microsoft/pxt-microbit#5266]
@ganicke  Would you be willing to go through the prominent micro:bit tutorials and hide all of the step titles?  They're too large for the small amount of space in the instructions (and generally, they are only "Step 1", "Step 2", etc.)

![Screenshot by Dropbox Capture](https://github.com/microsoft/pxt-microbit/assets/1633958/6bb8567a-41de-4f19-98a2-01e502ef24ae)

## {Step 1}

We need 3 pieces of code: one to detect a throw (shake), another to pick a random number, and then one to show the number.

Use the ``||input:on shake||`` block you see in the editor workspace. It runs code when you shake the @boardname@.

**Comment by abchatra** [comment]
Isn't that space any way wasted due to the space at the top with immersive reader? Not sure we will gain any space by deleting the steps.

**Comment by Jaqster** [comment]
But it's also confusing because the Step title is different from the actual Tutorial step.  We can't push up the tutorial instructions to the top of the window?
![image](https://github.com/microsoft/pxt-microbit/assets/22108954/887b5963-a0bf-4138-a53b-da2fd041cd5d)
