### ISSUE TITLE
On Touch - opening Tutorial Hint expands instruction pane

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5280]
Reported by a partner:  When using a touchscreen device (Edge, Surface), opening the tutorial hint and closing it will automatically expand the tutorial instruction pane.  May be related to https://github.com/microsoft/pxt-microbit/issues/5215?

https://github.com/microsoft/pxt-microbit/assets/22108954/fc1c6c6b-282a-4eb7-b718-1ffc549a7792

Sample tutorial: https://bit.ly/fwdag

**Comment by abchatra** [comment]
@thsparks
