### ISSUE TITLE
Recording extension: Running multiple "record audio clip in background" in the sim throws dev console errors

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5285]
**Describe the bug**

This programme constantly throws the same error to the JS console:
<img width="397" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/1de62699-b986-4076-956d-dfe2ee87e8e8">

```
GET blob:https://trg-microbit.userpxt.io/e3ee2040-115e-4d0d-a2ee-9a724aa7eecc net::ERR_REQUEST_RANGE_NOT_SATISFIABLE
```

**To Reproduce**
1. Add recording extension
2. Add the code below
3. Open the Chrome developer console
4. Errors appear in rapid succession

```ts 
basic.forever(function () {
    record.startRecording(record.BlockingState.Nonblocking)
})
```

**Expected behavior**
No errors in the console

**Screenshots**
<img width="399" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/a907d7bc-839d-4f66-a894-a2f9d2949385">

**micro:bit version (please complete the following information):**

N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome 114

**Smartphone (please complete the following information):**
N/A

**Additional context**
makecode.microbit.org version:  [6.0.10](https://github.com/Microsoft/pxt-microbit/releases/tag/v6.0.10)
Microsoft MakeCode version:  [9.0.7](https://github.com/Microsoft/pxt/releases/tag/v9.0.7)
microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
codal-microbit-v2 runtime version:  [v0.2.55](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.55)

**Comment by microbit-carlos** [comment]
Similarly having the `[play audio clip]` block immediately after a `[record audio clip [in background]]` also throws:

```
Uncaught (in promise) DOMException: Failed to load because no supported source was found.
```


<img width="428" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/5f5cb218-c0b0-45ed-9e51-9a36fc2b09bd">

**Comment by jwunderl** [comment]
Fixed
