### ISSUE TITLE
Offline app: Downloading record project to hardware shows compile error when offline

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#5300]
**Describe the bug**
**Offline app**: Downloading **record project** to hardware shows **compile error** when **offline**

**Steps to reproduce the behavior**
1. Download Microbit offline app: https://makecode.com/api/release/microbit/v6.0.5/win64
2. Open the offline app and create a record project
3. Download the project to hardware

**Expect behavior**
Downloading **record project** to hardware shows **compile error** when **offline**

**Actual behavior**
Downloading **record project** to hardware succeed when **offline**

**Screenshot**
![1](https://github.com/microsoft/pxt-microbit/assets/59192069/de3d13f3-720e-4a33-abad-96871922beb9)

**Additional context**
1.OS: Win11
2.makecode.microbit.org version: 6.0.5
3.Microsoft MakeCode version: 9.0.5

**Comment by jwunderl** [comment]
@Sheila111 please retry / validate on the new version from https://makecode.microbit.org/offline-app ([v6.0.15](https://makecode.com/api/release/microbit/v6.0.15/win64)), this should be fixed there. Thankyou!

**Comment by Sheila111** [comment]
@jwunderl Yes. Fixed on version v6.0.15
