### ISSUE TITLE
Simulator missing in Android tablet portrait orientation with MakeCode V6 only

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#5305]
**Describe the bug**
Arising from support ticket https://support.microbit.org/helpdesk/tickets/64595 (private)

The simulator is absent in portrait orientation, but appears as expected in landscape orientation.

This was originally noticed in the micro:bit app which is limited to portrait only.

The simulator is missing in MakeCode V6, but not MakeCode V5.

The tablet is a Lenovo Tab M10 HD with Android 11.

I have not been able to reproduce the problem in my Android 8 tablet or Android 12 phone.

**Expected behavior**
The simulator appears as it did in MakeCode V5.

**Screenshots**
In Chrome, missing in portrait orientation, present in landscape
![image](https://github.com/microsoft/pxt-microbit/assets/989126/de9739a2-aafd-4c24-9c52-b0d800f8a2a7)
![image](https://github.com/microsoft/pxt-microbit/assets/989126/145e8441-dd08-4f82-b552-4bda787fb07c)

Missing in the micro:bit app
![image](https://github.com/microsoft/pxt-microbit/assets/989126/61abe702-5d09-4296-8df1-0efd1de69d84)

OK in MakeCode V5
![image](https://github.com/microsoft/pxt-microbit/assets/989126/1ae20c26-7f06-489e-a2f8-c7153cf7ba9d)

**micro:bit version (please complete the following information):**
not hardware related

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Lenovo Tab M10 HD
 - OS: [e.g. iOS8.1] Android 11
 - Browser [e.g. stock browser, safari] Chrome

**Comment by jwunderl** [comment]
I'm also not seeing a repro for this on my end either unfortunately, for reference the device mentioned appears to be 800x1200 screen resolution, I tried with variations around that size / different devices / etc.

Could we check if we can get the exact version info of the device? In chrome it should be top right corner dropdown menu -> `settings` -> `About Chrome` which will give application version / operating system.

(as a side note, is there a particular reason to lock the app to portrait mode? I know ~ 2-3 years back it had a pretty poor layout on phone size / landscape which could have required it, but a year or two back I did some optimizations to make better use of space where we can so might be worth revisiting that decision, unrelated to this issue.)

**Comment by martinwork** [comment]
Thanks @jwunderl. I have alerted @vsbogd through the support ticket.

I don't know about the Android app's limitation to portrait mode. I had been assuming it was following the PWA (https://github.com/microsoft/pxt-microbit/issues/4629). If I am looking in the right place now, it seems it was intentional:
https://github.com/microbit-foundation/microbit-android/blob/918d6933ec7cb46874f861357f61a53e2f8f7454/app/src/main/AndroidManifest.xml#L142

**Comment by vsbogd** [comment]
@jwunderl, here the information from Chrome About screen:
Chrome version: 87.0.4280.141
OS: Android 11; Lenovo TB-X306F Build/RP1A.200720.011

**Comment by jwunderl** [comment]
I still have not be able to get a repro, haven't been able to find a roughly matching tablet. If possible @vsbogd could you check https://makecode.microbit.org/v6.0.5#editor, I poked around the css changes and they looked reasonable but there was a minor diff there that could be related.

Either way, if possible I would suggest updating your browser / os on that device to make sure it's safe and secure (which would probably fix the issue in this case, though being able to reproduce it and and actually fix it would be ideal)

**Comment by vsbogd** [comment]
Thanks @jwunderl, I checked https://makecode.microbit.org/v6.0.5#editor and can confirm it works properly in browser and in Android app when link to the editor is replaced manually.
