### ISSUE TITLE
Sim missing at exactly 991px width

### ISSUE THREAD

**Issue by jwunderl** [microsoft/pxt-microbit#5328]
**Describe the bug**

at exactly 991px width simulator disappears:
![image](https://github.com/microsoft/pxt-microbit/assets/5615930/33e78744-6498-4a23-b9be-6178ea2f9293)

991px is the breakpoint we switch between computer & tablet sizing (e.g. https://github.com/microsoft/pxt/blob/master/react-common/styles/react-common-breakpoints.less#L9), almost certainly we have some styling with a media query based off `> largestTabletScreen` and some based off `< @largestTabletScreen` or something to the effect

**To Reproduce**
1. Go to dev tools
2. toggle device toolbar, dimensions responsive, set width to 991px
3. open https://makecode.microbit.org/#editor

**Expected behavior**

We shouldn't lose sim

**Comment by emoltz** [comment]
See above but I was able to pinpoint the issue and the sim shows up at 991px wide now. 
https://github.com/microsoft/pxt/pull/9621

**Comment by abchatra** [comment]
Fixed
