### ISSUE TITLE
bluetooth problem

### ISSUE THREAD

**Issue by crouse12** [microsoft/pxt-microbit#5336]
If I upload following hex, my computer can find my microbit via bluetooth without clicking any button.
This hex is download from network, I think this hex may be generated from old version makecode.
https://drive.google.com/file/d/19yKI5Vb0cWwgfDmLuoh12RclIHTZDmzL/view?usp=drive_link
![image](https://github.com/microsoft/pxt-microbit/assets/25700616/7d0bb9d0-9534-49c0-8fce-daa922b6522a)

However, if I use version 6.0.17 makecode to generate hex, and then upload to my microbit.
My computer cannot find microbit via bluetooth.
https://makecode.microbit.org/_Dy2MiM3Ra0C1
![image](https://github.com/microsoft/pxt-microbit/assets/25700616/405ff32e-f0b3-4e6f-a496-c0daec70889d)

I don't know why the new makecode cannot provide the same feature.

**Comment by martinwork** [comment]
I suspect this might be related to https://github.com/microsoft/pxt-microbit/issues/4378

Both examples have "no pairing required" in Project Settings. When I generated a hex from the second example, it seemed to behave correctly, but I can easily believe that changing to no pairing required didn't make it build with the right flags.

I haven't yet figured out a trick to guarantee a correct build, One possibility:
- Create a new project
- Change to "no pairing required"
- Add Bluetooth extension
- Add or copy & paste code

**Comment by crouse12** [comment]
Your method can solve the bluetooth flag problem.

**Comment by crouse12** [comment]
@abchatra Does pxt-microbit not correct this error?

**Comment by abchatra** [comment]
I thought this was dupe of #4378. If not let me know I will reopen.
