### ISSUE TITLE
Issue with variables appearing and disappearing when moving between block and python modes

### ISSUE THREAD

**Issue by shabysheik** [microsoft/pxt-microbit#5338]
**Describe the bug**
I am teaching future teachers how to help transition year 7/8 students from block code to general purpose language like python. Using microbit is a logical choice, Unfortunately, weird stuff happens when moving between blocks and general purpose code (python). **On Start** block that initialises variables will disappear, variable initialisation within Python appears to double up, and cats and dogs start hooking up on Tynder! There are two examples below. I hope the links work. 

**To Reproduce**
Steps to reproduce the behavior: Here are two examples:

Open [([https://makecode.microbit.org/_WoRW460VpT5A](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmakecode.microbit.org%2F_WoRW460VpT5A&data=05%7C01%7Cshane.byrne%40acu.edu.au%7C600c5b1b09774b7e745f08dba5a0847c%7C429af009f196448fae7958c212a0f2ce%7C0%7C0%7C638285881076478275%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hjUywcBBxwyuVfobHuOx%2FOdlT9fVUNZJ1MbEwQO6KFw%3D&reserved=0)))]

**Notice initialiser in on start
Switch to Python mode
Notice one initialiser at the top of the script
Change the increment to 2
Switch to Blocks mode
Notice on start has gone**

Second example:

Open [[https://makecode.microbit.org/_6i6Y4ue8bFaa](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmakecode.microbit.org%2F_6i6Y4ue8bFaa&data=05%7C01%7Cshane.byrne%40acu.edu.au%7C600c5b1b09774b7e745f08dba5a0847c%7C429af009f196448fae7958c212a0f2ce%7C0%7C0%7C638285881076634519%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=D5Wwh%2FMH6ICq9n0%2Fv%2B9NIK2v79mudnK82URhuVG6cwU%3D&reserved=0)](url)

**Switch to Python mode
Notice repeated initialiser for count = 0 at the bottom of the script
Delete the second initialiser
Switch to Blocks mode
Notice on start has gone
Switch to Python mode
Notice a single initialiser, moved to the top of the script
Change the initial value to 1
Switch to Blocks mode
Notice on start is back
Switch to Python mode
Notice count = 0, count = 1 moved to bottom**

**Expected behavior**
There needs to be a clear similarity between the block code and the python if possible, or added descriptions/comments to indicate what the 2nd initialiser is for

**Screenshots**
Original block code

![image](https://github.com/microsoft/pxt-microbit/assets/48341843/4f98ecf9-373e-48bd-a9d2-44f1d1424fd2)

Original as python

![image](https://github.com/microsoft/pxt-microbit/assets/48341843/3826e291-36ba-4191-9436-dbff09c2c028)

change increment to 2 in python

![image](https://github.com/microsoft/pxt-microbit/assets/48341843/401d1597-facc-48af-9d2e-e35cef6eaf19)

resulting block code

![image](https://github.com/microsoft/pxt-microbit/assets/48341843/733e705f-035f-4610-bf84-cc79d93023ae)

note that the start block has completely disappeared - this will really confuse the students...and me - why?

Second example

original blocks

![image](https://github.com/microsoft/pxt-microbit/assets/48341843/b80aafb9-f473-4529-8985-1af47f77ade0)

original as python

![image](https://github.com/microsoft/pxt-microbit/assets/48341843/d0733456-2e97-4168-87f3-742f68009984)
 note the two count = 0 at the bottom (at least an explanation might help)

delete the second initialiser
![image](https://github.com/microsoft/pxt-microbit/assets/48341843/48f1fdde-e6a8-4c74-824c-2bf09ff96c80)

switch to block mode
![image](https://github.com/microsoft/pxt-microbit/assets/48341843/0a93d89d-0b4d-4649-b87d-c7572104f52d)

note the onstart block has disappeared

switch back to Python
![image](https://github.com/microsoft/pxt-microbit/assets/48341843/b4e9307a-2e05-45d6-be80-021b54bf022b)
note single initialiser moved to the top

change the initial value to 1 in python

![image](https://github.com/microsoft/pxt-microbit/assets/48341843/26f3a013-007a-4629-a221-518d2bc93c40)

back to blocks and on start has reappeared

![image](https://github.com/microsoft/pxt-microbit/assets/48341843/4bd85163-398d-4a0d-ba48-4759c098fad8)
now go back to python and look

![image](https://github.com/microsoft/pxt-microbit/assets/48341843/886b06a5-ffb3-44a5-945e-906d76c2aad1)
 initial value moved to bottom and it equals 0 and then equals 1

as videos - similar issues (videos are very short

[[Variables not appearing in block code - YouTube](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dx8u8k0ogkbc&data=05%7C01%7Cshane.byrne%40acu.edu.au%7C600c5b1b09774b7e745f08dba5a0847c%7C429af009f196448fae7958c212a0f2ce%7C0%7C0%7C638285881076634519%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=54aqgLXIA8G6x6Jf5G97%2B1Bd7aVHDteQ1v%2BbxcqQyJU%3D&reserved=0)](url)

and
[[Variables repeating - YouTube](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DQNUWICQQd3s&data=05%7C01%7Cshane.byrne%40acu.edu.au%7Ca4ff49e5ca7548c00b1808dba59cefbf%7C429af009f196448fae7958c212a0f2ce%7C0%7C0%7C638285865692363681%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=imfVFOTcX%2BSELLdFCMsax12K01EL4m5VIj0yH55OUuw%3D&reserved=0)](url)

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]
 - version 2.0
 - I will try it with version1 and see what happens when I get back to Uni

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 and Windows 11
 - Browser [e.g. chrome, safari] edge and chrome
 - Version [e.g. 22] **edge** Version 116.0.1938.54 (Official build) (64-bit)
 - chrome Version 116.0.5845.111 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
I really love the micro:bits as a teaching tool. I introduce almost a thousand preservice teachers to them every year in the hope they go into schools confident to do some physical coding. The micro:bit is ideal for that journey between block and general purpose coding. If it doesn't make sense when swapping between the two then it just leads to confusion and that "I don't understand what is going on so I am not going to try. Coding is too hard". I want to avoid that at all cost because it taints the discipline of coding and also taints the utility of micro:bits.
If you could fix this, it would be great. Happy to talk: shane.byrne@acu.edu.au
 thanks in advance

Martin Williams <help@microbit.org> helped reproduce the issues with me. His help is much appreciated.

**Comment by abchatra** [comment]
@shabysheik thanks for feedback. We will take a look at this soon.

**Comment by riknoll** [comment]
This is working as expected.

In blocks, we implicitly set the default values of variables for primitive types (e.g. numbers are initialized as 0). When you switch to a text language, those implicit variable declarations are emitted, either as a `let` statement in TypeScript or an assignment at the top of the file in Python. When we decompile from that text language back to blocks, we omit any variable declaration that could be replaced by the implicit declaration that our block compiler generates.

In order to prevent variable assignments present in blocks from being omitted when switching back from a text language, we emit both the implicit declaration and the assignment in on-start.

This behavior looks a little more natural in TypeScript, because declarations look different than assignments:

```ts
let count = 0;
count = 0;
```

But in Python it looks a bit silly since declarations and assignments look the same:

```py
count = 0
count = 0
```

The only way to improve this would probably be to keep some sort of metadata around from blocks compiles and use it to inform which variable declarations are kept or omitted. I hesitate to do that, though, since it would make our decompiler less predictable. The current behavior is certainly not the prettiest solution, but it does keep our decompiler "pure", which is to say that the same input TypeScript/Python program will always produce the same result.
