### ISSUE TITLE
Regression - we lost the block clicks!

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5350]
In the latest version, we've lost the sound of blocks clicking together!!!
Let's bring it back!

**Comment by abchatra** [comment]
@riknoll  I will take hotfix for this as this is a regression from v5.

**Comment by Jaqster** [comment]
I think also the throwing away sound when dragging blocks to the Toolbox

**Comment by abchatra** [comment]
@riknoll good one to fix when you have free cycles
