### ISSUE TITLE
Is the cloud C++ compiler down?

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5353]
**Describe the bug**

Trying to build a MakeCode project with C++ code (or macros set up in `pxt.json`) fails in the online editor and using the `pxt` cli tool.

**To Reproduce**
A few ways to reproduce this issue.

**Reproduce adding macros to `pxt.json`:**
1. Go to https://makecode.microbit.org
2. Start a new project
3. Click on project settings and "edit as text"
4. Add `"yotta": { "config": "RANDOM_MACRO": 1 }` to the json
5. Click on the "Blocks" or "Javascript" tabs for the settings to be saved
6. Try to download the project.
7. MakeCode will start using the online compiler
8. After a few minutes it will stop and show the following error on the js console

```
waiting 8s for C++ build...
pxtapp.js:1 abandoning C++ build
pxtapp.js:1 TypeError: Cannot read properties of null (reading 'length')
    at pxtapp.js:1:164948
    at pxtapp.js:1:165400
    at async r (pxtapp.js:1:299994)
    at async e.MainPackage.getCompileOptionsAsync (pxtapp.js:1:300685)
    at async de.compile (main.js:1:145808)
e.reportException @ pxtapp.js:1
e.reportException @ pxtapp.js:1
(anonymous) @ pxtapp.js:1
pxtapp.js:1 {sha: 'a3ab4c6a2d4d6860feabd2b612ac61e02c0f2d93202d5091784f9ebea523d79d'}
pxtapp.js:1 error: pxt_modules/core/math.ts(1,1): error TS9043: The hex file is not available, please connect to internet and try again.

pxtapp.js:1 warning: The hex file is not available, please connect to internet and try again.
```

**Reproduce adding an extension that uses C++:**
1. Go to https://makecode.microbit.org
2. Start a new project
3. Add this GitHub repo extension: https://github.com/carlosperate/pxt-banana/
4. Add any of the extension blocks to your project
6. Try to download the project.
7. MakeCode will start using the online compiler
8. After a few minutes it will stop and show the same error as before

**Reproduce with the `pxt` cli tool:**
```bash
$ git clone https://github.com/microbit-carlos/makecode-macrotest
$ cd makecode-macrotest
$ npm install pxt
$ npx pxt target microbit
$ npx pxt install
$ npx pxt
```

Output from the last command (repeated messages cut out):
```
Using target microbit with build engine yotta
  target: v6.1.5 /Users/microbit-carlos/workspace/mbef/macrotest/node_modules/pxt-microbit
  pxt-core: v9.1.11 /Users/microbit-carlos/workspace/mbef/macrotest/node_modules/pxt-core
running 'pxt deploy' (run 'pxt help' for usage)
building /Users/microbit-carlos/workspace/mbef/macrotest
polling C++ build https://makecode.com/compile/ef05acd38c37a8ffc922b0ee0ecf85ec410ba60ea6073f77cc9b0a6da76f0cb6.json (attempt #1)
waiting 8s for C++ build...
polling C++ build 

...

https://makecode.com/compile/ef05acd38c37a8ffc922b0ee0ecf85ec410ba60ea6073f77cc9b0a6da76f0cb6.json (attempt #8)
waiting 8s for C++ build...
abandoning C++ build
TypeError: Cannot read properties of null (reading 'length')
    at compressHex (/Users/microbit-carlos/workspace/mbef/macrotest/node_modules/pxt-core/built/pxt.js:105209:37)
    at /Users/microbit-carlos/workspace/mbef/macrotest/node_modules/pxt-core/built/pxt.js:105138:36
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async fillExtInfoAsync (/Users/microbit-carlos/workspace/mbef/macrotest/node_modules/pxt-core/built/pxt.js:114012:51)
    at async MainPackage.getCompileOptionsAsync (/Users/microbit-carlos/workspace/mbef/macrotest/node_modules/pxt-core/built/pxt.js:114057:33)
{
  sha: 'ef05acd38c37a8ffc922b0ee0ecf85ec410ba60ea6073f77cc9b0a6da76f0cb6'
}
polling C++ build https://makecode.com/compile/1bbad6fb432068adc028ab1b7c9b63099ae4dadf3e9099ed68257554f0f13013.json (attempt #1)
waiting 8s for C++ build...

...

polling C++ build https://makecode.com/compile/1bbad6fb432068adc028ab1b7c9b63099ae4dadf3e9099ed68257554f0f13013.json (attempt #8)
waiting 8s for C++ build...
abandoning C++ build
TypeError: Cannot read properties of null (reading 'length')
    at compressHex (/Users/microbit-carlos/workspace/mbef/macrotest/node_modules/pxt-core/built/pxt.js:105209:37)
    at /Users/microbit-carlos/workspace/mbef/macrotest/node_modules/pxt-core/built/pxt.js:105138:36
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async fillExtInfoAsync (/Users/microbit-carlos/workspace/mbef/macrotest/node_modules/pxt-core/built/pxt.js:114012:51)
    at async MainPackage.getCompileOptionsAsync (/Users/microbit-carlos/workspace/mbef/macrotest/node_modules/pxt-core/built/pxt.js:114057:33)
{
  sha: '1bbad6fb432068adc028ab1b7c9b63099ae4dadf3e9099ed68257554f0f13013'
}
pxt_modules/core/math.ts(1,1): error TS9043: The hex file is not available, please connect to internet and try again.
```

Using the local tooling with the `pxt` cli does work (have to force "no docker" due to the docker image not being publicly available https://github.com/microsoft/pxt-microbit/issues/5313):
```
PXT_FORCE_LOCAL=1 PXT_NODOCKER=1 npx pxt
```

**Expected behavior**

The MakeCode project cloud compilation to produce a valid hex file. 

**Screenshots**
N/A

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

Same issue with MakeCode live:
makecode.microbit.org version:  [6.0.18](https://github.com/Microsoft/pxt-microbit/releases/tag/v6.0.18)
Microsoft MakeCode version:  [9.0.12](https://github.com/Microsoft/pxt/releases/tag/v9.0.12)
microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
codal-microbit-v2 runtime version:  [v0.2.57](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.57)

And MakeCode beta:
makecode.microbit.org version:  [6.1.5](https://github.com/Microsoft/pxt-microbit/releases/tag/v6.1.5)
Microsoft MakeCode version:  [9.1.11](https://github.com/Microsoft/pxt/releases/tag/v9.1.11)
microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
codal-microbit-v2 runtime version:  [v0.2.57](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.57)

**Comment by microbit-carlos** [comment]
@abchatra if the cloud compiler is down it means that all MakeCode projects using an extension with C++ will fail to build.
It also takes a long time to fail, the message quickly disappears (I've never actually seen it, as after a couple of minutes waiting for the compilation I ended up paying attention to other things) and, even if you do catch to see it, it's not very user friendly.

**Comment by abchatra** [comment]
@aznhassan can you investigate?

**Comment by aznhassan** [comment]
The C++ Cloud Compilation server is back up. Restarting it resolved the issue, some kind of early warning system should be made so we're aware when this happens. @abchatra

**Comment by abchatra** [comment]
Thank you @aznhassan

**Comment by microbit-carlos** [comment]
I can confirm this works on my end as well 🎉

I'll close this issue as resolved, assuming that any work to add an early warning system would be tracked in a different issue, but feel free to reopen if you'd like to do that here.

Thanks everyone!

**Comment by ggstephenlau** [comment]
Hi,
I find that martinwork's post on 13Sept2023 happens again.
Could you help on this issue?
Thank you very much.
