### ISSUE TITLE
P3,P4,P6,P7,P10 of digital input is not working properly.

### ISSUE THREAD

**Issue by itibanbosi** [microsoft/pxt-microbit#5371]
P3,P4,P6,P7,P10 of digital input is not working properly.
Always returns 1.
The program looks like this:

led.enable(false)
pins.setPull(DigitalPin.P3, PinPullMode.PullNone)
basic.forever(function () {
    serial.writeLine("" + (pins.digitalReadPin(DigitalPin.P3)))
})

This phenomenon started occurring with MakeCode editor version 6.0.18-.
P0, P1, P2, P13, P14, P15, P16 return 0, so it is normal.
It occurs at P3, P4, P6, P7, and P10.Always returns 1.
It may be related to the matrix LED.
I checked on Windows and iPad (microbit app).

makecode.microbit.org version:  [6.0.19]←[6.0.18]
Microsoft MakeCode version:  [9.0.12]
microbit runtime version:  [v2.2.0-rc6]
codal-microbit-v2 runtime version:  [v0.2.61]

micro:bit V2.00
Windows10 or 11
Chrome or iPad (microbit app)

**Comment by abchatra** [comment]
@itibanbosi thanks for reporting. @carlosperate  @JohnVidler new codal update?

**Comment by microbit-carlos** [comment]
Thanks for the report!
@itibanbosi could you provide an example MakeCode programme we can use to replicate with MakeCode v6.0.18 and v6.0.19?

**Comment by itibanbosi** [comment]
There is a correction. Pin9 was normal.
P3,P4,P6,P7,P10 will return 1 no matter what you do.
I created three linked files.
Returns data serially.

MakeCode v6.0.19( always returns 1)
https://makecode.microbit.org/_iJ37oc5YXW3X

MakeCode v5(nomal  returns 0)
https://makecode.microbit.org/v5/_FDpKxq6jcdVK

MakeCode v6.0.19(Explore all pins)
https://makecode.microbit.org/_27V36VA74KFX

**Comment by itibanbosi** [comment]
This is a supplement to the above.

This bug can be reproduced with a downloaded micro:bit.

Returns 0 on the simulator (Show data simulator).
After downloading, (Show data device) returns 1.

**Comment by martinwork** [comment]
@carlosperate This problem appears in CODAL 0.2.59.

```
#include "MicroBit.h"

MicroBit uBit;

void forever()
{
  uBit.display.disable();

  while (true)
  {
    ManagedString str( (int) uBit.io.P3.getDigitalValue());
    uBit.serial.send( str + "\r\n");
    uBit.sleep(200);
  }
}

int main()
{
    uBit.init();

    create_fiber( forever);
    release_fiber();
    return 0;
}
```

**Comment by microbit-carlos** [comment]
Thanks @itibanbosi and @martinwork!

The changes between v0.2.58 and v0.2.59:
- https://github.com/lancaster-university/codal-microbit-v2/compare/v0.2.58...v0.2.59
- https://github.com/lancaster-university/codal-core/compare/2658178aade744af248b116c2e4277b94a242b69...32cc87c3298a49663c3b3b7b1881ec7aeb3d73a5
- https://github.com/lancaster-university/codal-nrf52/compare/84b1aeec870addcfb6027a924dbfe83f1f10c6db...2dbf5aa214c7432c0b1b8a19e92a3f9a4fc4b9da

My guess is: https://github.com/lancaster-university/codal-microbit-v2/commit/03c05e2c881b5db73be04d3cb8b9da1a37144061

@martinwork could you uncomment that loop in your test programme and try again?

**Comment by martinwork** [comment]
@microbit-carlos Yes, uncommenting the loop makes the difference. What about timer.disableIRQ()?

With a clean 0.2.59, I added clear before disable. P3 still returns 1.
```
  uBit.display.clear();
  uBit.display.disable();
```

**Comment by microbit-carlos** [comment]
Thanks Martin!
We'll need to try again to disable enough of NRF_GPIOTE without causing the excessive power consumption during sleep.

Basically the GPIO events are still firing and I'm guessing that changes the pin state.

We saw the GPIOTE events causing some additional power consumption when the board was asleep, only happening if an image was configured to be displayed. Since clearing the display before going to sleep did reduce the power consumption, I was hoping maybe doing that somehow disabled the events some other way, but that doesn't look to be the case.

**Comment by martinwork** [comment]
Maybe disable() should clear the NRF_PPI channels?

**Comment by martinwork** [comment]
@microbit-carlos 

**Testing current MakeCode with V2...**

With the original test, setting pull none, P3 is stuck at 1. Connecting P3 to GND has no effect,
https://makecode.microbit.org/_1rRaADfqP24J
It's the same with pull down
https://makecode.microbit.org/_ggXF1mDVT9T8
and no pull specified (the default should be down)
https://makecode.microbit.org/_PJU8WMLuf8XY

**The same tests with micro:bit V1** behave as expected. With pull none the pin varies between 0 and 1 when not connected, and stays at 0 when connected to GND, 1 when connected to 3V, and varies again when disconnected.

**The same 3 tests in C++** using the code below, show the same results.

**After uncommenting this loop**
https://github.com/lancaster-university/codal-microbit-v2/blob/master/source/NRF52LedMatrix.cpp#L197
V2 behaves as follows:-

When the pull mode is set to none, V2 behaves as expected. When the pin is disconnected V2 is less variable than V1, tending to stick with one value unless disturbed. When disconnecting from 3V or GND it sometimes sticks with the same value and sometimes switches to the opposite.

When the pull mode is set to down, V2 behaves as expected. The pin reads 0 unless connected to 3V.

**NB: When the pull mode is not explicitly set, V2 behaves like pull mode none.** I tested V1 again and it behaved as expected.

See also
https://github.com/lancaster-university/codal-microbit-v2/blob/master/source/NRF52LedMatrix.cpp#L297

See the paragraph starting "As long as a SET[n]" in
https://infocenter.nordicsemi.com/index.jsp?topic=%2Fps_nrf52833%2Fgpiote.html&cp=5_1_0_5_8_0&anchor=concept_tyh_czw_lr

```
#include "MicroBit.h"

#ifndef MICROBIT_CODAL
#ifdef CODAL_CONFIG_H
#define MICROBIT_CODAL 1
#else
#define MICROBIT_CODAL 0
#endif
#endif

MicroBit uBit;

void forever()
{
  uBit.display.clear();
  uBit.display.disable();

//#if MICROBIT_CODAL
//  uBit.io.P3.setPull(PullMode::None);
//#else
//  uBit.io.P3.setPull(PullNone);
//#endif

//#if MICROBIT_CODAL
//  uBit.io.P3.setPull(PullMode::Down);
//#else
//  uBit.io.P3.setPull(PullDown);
//#endif

  while (true)
  {
    ManagedString str( (int) uBit.io.P3.getDigitalValue());
    uBit.serial.send( str + "\r\n");
    uBit.sleep(100);
  }
}

int main()
{
    uBit.init();

    create_fiber( forever);
    release_fiber();
    return 0;
}


```

**Comment by martinwork** [comment]
This has been reported in support ticket https://support.microbit.org/helpdesk/tickets/68217 (private)

The ticket gave me an idea for another test, to show that Pin P3 cannot be set as output either.
Connect P3 to P0 to read P3's output.
https://makecode.microbit.org/_htJ0CyTAaDxH
After setting P3 to 0, P0 sees 0 on V1 but 1 on V2.

**Comment by microbit-carlos** [comment]
Okay, so @JohnVidler will release a CODAL tag to revert the power consumption "fix" that introduced this issue (which will increase sleep power consumption), so that we can do a hot fix Makecode release for this ticket.

We'll then look into ways to disconnect the display pins from GPIOTE while working around whatever triggers the extra power consumption, so that a future CODAL tag can be released with a reduced the sleep current consumption again.

**Comment by microbit-carlos** [comment]
@itibanbosi https://makecode.microbit.org/beta has been updated with a fix, in case you'd like to try it.

**Comment by abchatra** [comment]
https://makecode.microbit.org/stable for just the fix and you don't want other beta changes.

**Comment by abchatra** [comment]
Once you confirm we will release the fix.

**Comment by itibanbosi** [comment]
Thank you.
The issues related to P3, P4, P6, P7, and P10 have been resolved by upgrading MakeCode(Ver6.0.22).
It was very helpful.
I hope to work with you in the future

**Comment by abchatra** [comment]
Fixed
