### ISSUE TITLE
Code missing on shared project preview

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5378]
When visiting this shared project page, the MakeCode preview doesn't show any code:
https://makecode.microbit.org/_Mjw1p2JsUUUE
https://makecode.microbit.org/53348-04838-45575-63401
<img width="48%" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/2ebcdeb8-a78d-4653-8545-1ea978d96564"> <img width="48%" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/e1850435-b750-46be-89ab-cbf02e66eb13">

But when clicking on "Edit Code" and opening the project in the MakeCode editor, there is code there:
<img width="48%" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/b08c62a5-9621-45b1-a4b7-eaf2a1f06038"> <img width="48%" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/7c0cbf35-7ef1-425a-be60-4ab759865c8e">

makecode.microbit.org version:  [6.0.19](https://github.com/Microsoft/pxt-microbit/releases/tag/v6.0.19)
Microsoft MakeCode version:  [9.0.12](https://github.com/Microsoft/pxt/releases/tag/v9.0.12)
microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
codal-microbit-v2 runtime version:  [v0.2.61](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.61)

**Comment by riknoll** [comment]
this appears to be some sort of exception being thrown while Blockly is rendering. i tried on the beta share page (via localhost) and it worked just fine, so i think this will likely be fixed when we release.

**Comment by abchatra** [comment]
Ok closing
