### ISSUE TITLE
User tutorials do not ignore main.ts when published via GitHub

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#5385]
**Describe the bug**

Arising from support ticket https://support.microbit.org/helpdesk/tickets/68239 (private)

The **User tutorials** documentation, under **Authoring**, says "code content (main.blocks, main.ts) is ignored".
https://makecode.com/writing-docs/user-tutorials#:~:text=code%20content%20(main.blocks%2C%20main.ts)%20is%20ignored

But that is only the case when using the shared project route. When a tutorial is published in a GitHub repository, main.ts is used.

Much further down, under **Repository as extension** it says "If the tutorial repository contains JavaScript files (.ts), it will automatically be added to the dependencies of the program used during the tutorial. This allows you to package custom blocks in your tutorials or teach your extensions via tutorials.".

It's not clear that "JavaScript files" includes main.ts, despite the previous understanding that it is ignored, or that "program used during the tutorial" includes the project created by following the tutorial.

It may also not be understood by tutorial authors that **Repository as extension** applies simply by using GitHub.

As I understand it, "code content (main.blocks, main.ts) is ignored" should be moved into the **Share** section. Does this actually mean all code in the project (e.g. custom.ts)?

I think **Repository as extension** should be more prominent in the **GitHub repository** section, and make it clear that main.ts should be empty unless it contains code to be included in the tutorial and the project created by following the tutorial.

**To Reproduce**
1. Create a new project 
2. Add beating heart code in forever
3. Create tutorial in README
4. Save to GitHub
5. Run repo as tutorial
6. See beating heart in simulator

**micro:bit version (please complete the following information):**
not hardware related

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Comment by abchatra** [comment]
Request to ignore main.ts & main.blocks in the github repo for tutorials.
