### ISSUE TITLE
"Rock Paper Scissors": Hint of step2 are inconsistent with the content

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5386]
**Describe the bug**
**"Rock Paper Scissors"**: Hint of step2 is inconsistent with the content
**Steps to reproduce the behavior:**
1.Navigate to  https://makecode.microbit.org/beta#
2.Games->Rock Paper Scissors->Blocks Start Tutorial
3.Go to **step2** and click hint.

**Actual behavior:**
Content only mentioned create the variable but hint has extra drag blocks actions.

**Expected behavior:**
Hint of step2 is consistent with the content, no other actions.

**Screen Recording:**
![hint2 repro video](https://github.com/microsoft/pxt-microbit/assets/148834117/6e28688e-f99e-457e-b332-9a9bb21d5617)

**Additional context:**
1.OS: Windows 11
2.makecode.microbit,org version: 6.1.6
3.Microsoft MakeCode version: 9.1.11

**Comment by abchatra** [comment]
Won't fix. Next step has the drag instructions and it is ok to show bit of extra info in the hints
