### ISSUE TITLE
"Rock Paper Scissors": Hint of step9 doesn't match with the actual results

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5387]
**Describe the bug**
**"Rock Paper Scissors":** Hint of step9 doesn't match with the actual results

**Steps to reproduce the behavior:**
1.Navigate to  https://makecode.microbit.org/beta#
2.Games->Rock Paper Scissors->Blocks Start Tutorial
3.Go to **step9** and click hint, compare the hint and the actual results in workspace.

**Actual behavior:**
Hint of step9 shows _else if false then_, but actual results in workspace shows _else if blank then_.

**Expected behavior:**
Hint of step9 matches with the actual results.

**Screenshot:**
![image](https://github.com/microsoft/pxt-microbit/assets/148834117/994a8b4c-ceb9-4b71-b503-1a2a4e5452e7)

**Additional context:**
1.OS: Windows 11
2.makecode.microbit,org version: 6.1.6
3.Microsoft MakeCode version: 9.1.11

**Comment by abchatra** [comment]
Fix the block to have a default.

**Comment by v-katherine** [comment]
@srietkerk I have verified this bug **still reproduced in the latest build** makecode microbit.org version: 7.0.13, so I **reopen** this bug. Will close this bug once the bug was not reproduce in the latest build.
![image](https://github.com/microsoft/pxt-microbit/assets/148834117/b611d016-af45-4559-a625-a0671c952076)

**Comment by srietkerk** [comment]
Hi @v-katherine! I just bumped beta, the latest version should now be 7.0.14 and this is fixed there. Please let me know if it's still giving you the incorrect behavior.

**Comment by v-katherine** [comment]
Hi @srietkerk I have verified this bug in the latest build: 7.0.15 and it has been fixed.
![image](https://github.com/user-attachments/assets/477f7158-640a-46bf-9e12-ce998e83ddee)
