### ISSUE TITLE
Request for en-uk localization

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5388]
https://twitter.com/MathsTeacherKYP/status/1720360601103343983

**Comment by ganicke** [comment]
Let's see what [Emma](https://crowdin.com/profile/microbit-emma) thinks about it...

**Comment by ganicke** [comment]
There, fixed:

![image](https://github.com/microsoft/pxt-microbit/assets/27789908/dac101f9-6cd8-4c07-9516-e230eeca98f3)

**Comment by abchatra** [comment]
@ganicke I am confused. How is this fixed? I thought we didn't have en-uk at all

**Comment by ganicke** [comment]
@abchatra - sorry, that's actually a bad joke - 'math' ---> 'maths' and that's it! Not really.

In that same vain, we need to change 'center' to 'centre' also. Maybe all instances of "Then, click on..." to "Right! Now click on..." and "Quickly press the A button" to "Straight away, press the A button".

**Comment by abchatra** [comment]
ha ha you got me...

**Comment by ganicke** [comment]
If you want to add 'en-UK' I'm OK with it. Actually, Minecraft Edu wanted it in their localization mix for HoC too.

**Comment by abchatra** [comment]
Won't fix at this point of time.
