### ISSUE TITLE
getting 521 from Daplink on copy of Hex file

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt-microbit#5393]
After updating Windows 11 (build 22631, 10.0.22631) , I am still getting the 521 Daplink error when copying a hex file (produced by arcade.makecode.com) to the micro:bit V2.   This affects the experience with the three Arcade shields on Windows. The problem is reproducible on makecode.microbit.org, but only with extremely large programs. Also, all the HEX files produced below do transfer fine when copied from a Chromebook to micro:bit V2, so it appears we still have a problem with Windows. 

Repro via command line

1. git clone https://github.com/microsoft/microcode
2. install makecode/mkc
3. mkc
4. go to built/n3
5. plug in micro:bit 
6. copy binary.hex to micro:bit drive
7. If the copy happens quickly (< 5 seconds) you will get the 521

Repro via https://arcade.makecode.com

1. import https://github.com/microsoft/microcode
2. choose any of the arcade shields for micro:bit
3. click download
4. copy arcade-microcode.hex to micro:bit drive

**Comment by abchatra** [comment]
@microbit-carlos can you please investigate this issue. This may be different than windows bug.

**Comment by microbit-carlos** [comment]
Is this an occasional DAPLink 5xx error on Windows 11, or does it happen on every flash?

I've flashed the hex files from the zip file in https://github.com/microsoft/pxt-microbit/issues/5393#issuecomment-1799766528, 3 times each on macOS 12 and couldn't replicate.

**Comment by tballmsft** [comment]
It happens about 50% of the time.

**Comment by microbit-carlos** [comment]
And the problem is not replicable with hex files generated from https://makecode.microbit.org ?

I guess arcade doesn't generate Universal Hex files, so when the those files are 1.2MBs it's all for V2 (in micro:bit MakeCode with Universal Hex, 1.2MB files are normal, but half the file is ignored), maybe the issue is more replicable with these large files.

Could we generate a file of similar size in https://makecode.microbit.org/?compile=csv---mbcodal (with that flag it generates V2 only hex files) to check if that's replicable there?

**Comment by tballmsft** [comment]
Right, Arcade doesn't generate Universal Hex files. The problem can be reproduced with makecode.microbit.org using this program: https://makecode.microbit.org/_9KKHE4WyyUM3

**Comment by abchatra** [comment]
@microbit-carlos try on windows 11 and see if you are able to reproduce this.

**Comment by eanders-ms** [comment]
FWIW, here are my results when I try to copy the hex file generated by @tballmsft's large microbit program "largeSwitch":

OS: Windows 11 (Build 22631.2506)
Microbit: V2.00 
Method of hex generation: Import the above project to makecode.microbit.org, then download as file.
Method of file copy: drag/drop to the MICROBIT drive in File Explorer.

Observations from ten copy operations:
* At no time did I get a 521 error or any other error code. Each copy seemed to complete without issue.
* Each copy took about 15 seconds to complete, with the indicator light rapidly flashing during the entire process.
* The program never worked correctly on the microbit. As per the code, I expected a number to display when the logo button was touched or a sound detected, but the device would not respond to any inputs.
* About 30% of the time, after the copy completed, the microbit would show an animation, then what appeared to be a bluetooth icon, then an icon that might be an emoji or a sailboat. (I wonder what this is, and where it came from.)


DETAILS.TXT:
```
# DAPLink Firmware - see https://mbed.com/daplink
Unique ID: 9904360258434e45001d400e00000035000000009796990b
HIC ID: 9796990b
Auto Reset: 1
Automation allowed: 0
Overflow detection: 0
Incompatible image detection: 1
Page erasing: 0
Daplink Mode: Interface
Interface Version: 0255
Bootloader Version: 0254
Git SHA: 1436bdcc67029fdfc0ff03b73e12045bb6a9f272
Local Mods: 0
USB Interfaces: MSD, CDC, HID, WebUSB
Bootloader CRC: 0x23cc2063
Interface CRC: 0x5b5cc0f5
Remount count: 7
URL: https://microbit.org/device/?id=9904&v=0255
```



This microbit has been shown to be reliable in the past.
* It has worked fine for other microbit programs.
* Has been used a lot with microcode.
* Has recently been used to play Arcade games on a shield.

**Comment by tballmsft** [comment]
I tried to download https://makecode.microbit.org/_9KKHE4WyyUM3  over WebUSB and got the message: error: 

> main.ts(1,1): error TS9283: program too big by 164532 bytes! 

I don't know if this was related to V1.  This may be a different bug (failing on WebUSB when program is too large for V1.  However, the micro:bit doesn't do anything.

**Comment by tballmsft** [comment]
Here is a smaller version of the program that works when downloaded over USB: https://makecode.microbit.org/_Chq7538rzeDL

**Comment by tballmsft** [comment]
OK, with the "medium program" (https://makecode.microbit.org/_Chq7538rzeDL). I still get 521 on file copy.

**Comment by eanders-ms** [comment]
Confirmed that mediumSwitch works on my microbit. It seems you have uncovered a different bug here with largeSwitch.

**Comment by ramseyball** [comment]
Yes, I filed two more issues related to large files:
- https://github.com/microsoft/pxt-microbit/issues/5396
- https://github.com/microsoft/pxt-microbit/issues/5395

**Comment by ramseyball** [comment]
Did anyone see a 521?

**Comment by abchatra** [comment]
@jaustin -> Chatted with Jonny in this morning call.

**Comment by microbit-carlos** [comment]
> OK, with the "medium program" (https://makecode.microbit.org/_Chq7538rzeDL). I still get 521 on file copy.

> Did anyone see a 521?

I've added an icon on startup (to easily confirm the programme started successfully, although the microphone LED does that as well) to that programme, flashed it over 20 times on Windows 11 22621.2506 and could not replicate.

Edition	Windows 11 Home
Version	22H2
Installed on	‎25/‎04/‎2023
OS build	22621.2506
Experience	Windows Feature Experience Pack 1000.22677.1000.0

I've used a micro:bit V2.2 with DAPLink 0257

@tballmsft just to double check, I assume this hex file triggers a 5xx error on your environment?
[microbit-mediumSwitchHeart.zip](https://github.com/microsoft/pxt-microbit/files/13319149/microbit-mediumSwitchHeart.zip)

**Comment by ramseyball** [comment]
Yes, but I am away from my windows machines until Wednesday. I will test again when back

**Comment by microbit-carlos** [comment]
That'd be great, thanks!
Are you running Windows insider builds? I wonder if this is due to an update not release yet to the public channel.

**Comment by microbit-carlos** [comment]
I've tried the [microbit-mediumSwitchHeart.zip](https://github.com/microsoft/pxt-microbit/files/13319149/microbit-mediumSwitchHeart.zip) file from comment https://github.com/microsoft/pxt-microbit/issues/5393#issuecomment-1805636843 in a Windows 11 insider build 23565.1000 and could not replicate there either.

I'd be really interesting to know what might be the trigger in your environment @ramseyball / @tballmsft, as you've mentioned you could replicate it in two different computers?

**Comment by ramseyball** [comment]
I will dig into this more this evening, when I have access to Windows computer again.

**Comment by tballmsft** [comment]
OK.  I am successful in copying 
[microbit-mediumSwitch.zip](https://github.com/microsoft/pxt-microbit/files/13357713/microbit-mediumSwitch.zip) over multiple times. 

But I am able to put the same micro:bit's DAPlink in a "bad state" by copying over this hex file for micro:bit produced by Arcade:
[arcade-tilecode.zip](https://github.com/microsoft/pxt-microbit/files/13357721/arcade-tilecode.zip)

When I next try to copy the microbit-mediumSwitch over, I get a 521.

**Comment by tballmsft** [comment]
At work, on desktop I am seeing a 521 about 50% of the time when copying mediumSwitch

**Comment by ofaurax** [comment]
With a new microbit v2, I had this error 521 when I tried to flash my first program, with *Linux* (online makecode, download, drag'n'drop).
Then everything went fine and I didn't see any 521 since.

**Comment by abchatra** [comment]
This is fixed.
