### ISSUE TITLE
should have a "program-too-large" dialog when downloading over WebUSB

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt-microbit#5395]
1. Connect a micro:bit V2 to Makecode via Web USB
2. load program: https://makecode.microbit.org/_Chq7538rzeDL
3. download program

See error message appear:

> error: main.ts(1,1): error TS9283: program too big by 107508 bytes!

Download continues anyway and program works as expected.

**Comment by abchatra** [comment]
I can reproduce this issue on v2. It shows up as error in javascript but continues to flash anyway. 
On v1 it correctly shows up as a error. (V1 compatible program -> https://makecode.microbit.org/_EvtUct4K3XYy) 

Issue here is it shouldn't show error for v2 when v2 size is not an issue.

**Comment by abchatra** [comment]
Remove the console.log for v2.

**Comment by abchatra** [comment]
Won't fix as this is error from v1 and hard to isolate.
