### ISSUE TITLE
Magic URL to open a project directly in a text based editor(JavaScript or Python)

### ISSUE THREAD

**Issue by Vegz78** [microsoft/pxt-microbit#5398]
**Is your feature request related to a problem? Please describe.**
It would be nice sometimes, even for block based projects, to be able to open shared projects directly in a text based editor(JavaScript or Python).

**Describe the solution you'd like**
I'd like to be able to make a link that opens a shared project directly in a text based editor using a custom magic URL, maybe like this:
https://makecode.microbit.org/_YTbKYAAimAxz#JavaScript

**Describe alternatives you've considered**
I have found no alternatives.

**Additional context**
The feature has been discussed on the forum:
https://forum.makecode.com/t/editor-magic-url-flags/10743/5?u=vegz78

**Comment by microbit-carlos** [comment]
If the project is shared when the code view is opened, the preview and the editable project should open in the same view.

For example, from that project: https://makecode.microbit.org/_gJof4qbXLK2C

I believe this is controlled via the `preferredEditor` key in pxt.json, which changes every time you change between code and bloques:

<img width="1132" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/e921a4a0-4d31-443c-ab3e-43dec2677e1d">

**Comment by abchatra** [comment]
There is a way to generate text based URL using a project which is a text based project. 

<img width="391" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/6107272/e5f5f3a7-f95f-47c2-b73b-d2018ef93fb4">

**Comment by Vegz78** [comment]
@abchatra: Your answer does not really apply, since the problem at hand was to share a regular project(Blocks, JavaScript and Python) in the JavaScript or Python "view", not to make it a "JavaScript only" project.

However, @microbit-carlos' solution does apply, thank you for the explanation! Never thought it was that easy and already supported, hehe...
