### ISSUE TITLE
Share page has two edit links, only one works as expected

### ISSUE THREAD

**Issue by eanders-ms** [microsoft/pxt-microbit#5399]
The microbit share page has two edit links, but they differ in behavior. See image below.
* The top one works as expected, loading the project into the editor.
* The bottom one navigates the user to makecode.microbit.org home page.

![image](https://github.com/microsoft/pxt-microbit/assets/12176807/f6a5bc24-30ba-4adb-a63a-ab3c65578f13)

**Comment by abchatra** [comment]
Both work for me.

**Comment by eanders-ms** [comment]
Can you elaborate? Do they both open the program in the editor? Backing up a little, why do we need to links?

**Comment by abchatra** [comment]
Yes both open in the editor. One inside the iframe is for other embed scenarios (not a share page). We could hide it in the share page.

**Comment by abchatra** [comment]
Won't fix. Both load for me in /beta
