### ISSUE TITLE
data does not reflect the actual simulator

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#54]
here is a snapshot of .XLS. The data on .xls does not reflect the fluctuating ligtht level adjusted on the simulator. 

code in JS
```
basic.forever(() => {
    led.plotBarGraph(input.lightLevel(), 0);
});


```

adjusted light level on simulator several times...

Opened data.xls file ....

![image](https://cloud.githubusercontent.com/assets/11206682/14756248/c52d6eee-089c-11e6-82fd-72659cd30475.png)

what is the issue? why is the changing of the light level on the simulator not reflected in Excel?

**Comment by pelikhan** [comment]
Is this still an issue?

**Comment by mebrauns** [comment]
yes. time should only be recorded in seconds. teachers will have no idea how to run any science experiments with this decimal place showing time to milliseconds. we need to only record a second and not give data that is showing every millisecond.

**Comment by pelikhan** [comment]
From an engineering point of view, this makes no sense.

If you measure the acceleration data of a jump, it is going to be in milliseconds.

For plants growing, it is going to be in days. Excel should deal with the intervals.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________
