### ISSUE TITLE
Remove duplicate map block

### ISSUE THREAD

**Issue by THEb0nny** [microsoft/pxt-microbit#5413]
Why was it necessary to create the map block/method a second time if it was originally in Math?
Maybe we should remove it from pins?
![image](https://github.com/microsoft/pxt-microbit/assets/13646226/3f94a5f1-52c5-4eb8-a4ee-1ed747787763)

**Comment by abchatra** [comment]
The PINS map is a legacy blcok and we don't want to remove  as there might be programs dependent on it.

**Comment by THEb0nny** [comment]
@abchatra then you can set the attribute to obsolete for it so that it does not appear in the editor.

**Comment by abchatra** [comment]
We have printed material\books\youtube videos in micro:bit. This doesn't help.

**Comment by abchatra** [comment]
To be fair we do deprecate blocks but are very cautious.
