### ISSUE TITLE
Documentation of Cooperative Passing of Control gives the wrong impression

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#5415]
**Describe the bug**

Arising from support ticket https://support.microbit.org/helpdesk/tickets/69177 (private)

The documentation wrongly gives the impression that control only passes between subprograms at the end of a loop or handler, unless the programmer inserts a pause.

https://makecode.microbit.org/device/reactive#:~:text=Cooperative%20passing%20of%20control

> The programmer inserts a call to the pause function to indicate a point in the subprogram where control of execution passes to the scheduler. Also, when a subprogram ends execution, control passes to the scheduler.

And, with regard to the pause added in the implementation of "forever"...

> If the while loop did not contain the call to pause, then once control passed into the while loop, it would never pass back to the scheduler and no other subprogram would be able to execute (unless the body subprogram contained a call to pause itself).

**To Reproduce**
1. Go to https://makecode.microbit.org/_Vi0FM7eTgFgd
2. Download to hardware (V2 for easy sound output)
4. Observe that the documentation gives the wrong impression

**Expected behavior**

Should it mention that blocks may include a pause or wait, that will allow control to pass?

Should it mention that subprograms may queue for access to some resources, such as the display, and be locked out of some resources, such as serial output?

**micro:bit version (please complete the following information):**
not hardware related

**Comment by abchatra** [comment]
@ganicke  we should mention some blocks may contain pause as well
