### ISSUE TITLE
Different behaviour for serial write between hardware, simulator, debugger and slow-mo

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#5417]
**Describe the bug**

Arising from support ticket https://support.microbit.org/helpdesk/tickets/69177 (private)

Related: https://github.com/lancaster-university/codal-microbit-v2/issues/398

In the hardware serial write may allow frequent context switches, and locks out other subprograms from serial write.

The simulator, and debugger step mode, never context switch in serial write, so behave as if serial output is always transmitted without waiting.

Slow-mo behaves as if every serial write call causes a context switch and other subprograms are not locked out from serial write.

Note that V1 always waits for transmission, while V2 only waits when the buffer is full.

**To Reproduce**
1. Go to https://makecode.microbit.org/_K5bLjsHMyHtg
2. Try in hardware, debugger and slow-mo
3. See differences in execution order, LEDs and serial output

**Expected behavior**
Simulator, debugger and slow-mo match each other, and the hardware as far as is practical. 

**micro:bit version (please complete the following information):**
not hardware related

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Comment by abchatra** [comment]
Won't fix. It is hard to accurately context switch in threads and for practical purposes there is not enough value add.
