### ISSUE TITLE
Micro:bit save file got mostly wiped

### ISSUE THREAD

**Issue by AudibleBuckle18** [microsoft/pxt-microbit#5423]
**Describe the bug**
I was swapping between programs, and my save file, which had over 1,000 blocks, wouldn't load for about 10 minuites. I reloaded my page, and all that was left was a single loop with a half filled if block.

**To Reproduce**
1. Make two very large programs
2. swap between them quickly
3.  Error may take multiple swaps to manifest.

**Expected behavior**
The loading screen for a program just keeps on going, not stopping.

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 
<img width="320" alt="Screenshot 2023-12-06 at 5 22 24 PM" src="https://github.com/microsoft/pxt-microbit/assets/153052818/bc534073-b7ae-484d-ba8e-91b267b19278">

micro:bit version: V2

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 119

**Additional context**
This may not be replicatable as I believe the server may have crashed, as my other makecode tab also froze at around the same time. I believe the animation was already cached.

**Comment by abchatra** [comment]
We have version control introduced to save the history in a project. If you are able to reproduce again in /beta please let us know and share the program through share link.
