### ISSUE TITLE
Update First Lessons description on Courses page

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5425]
Looks like the first paragraph for the First Lessons course is copied over from the Intro to Computer Science course.
https://makecode.microbit.org/courses
![image](https://github.com/microsoft/pxt-microbit/assets/22108954/72aa2de5-29f1-423b-ad74-b678187b5540)

Let's either just remove this sentence, or replace with something like this, "A sequence of six lessons that provide a pathway through six projects, ideal for getting started with the micro:bit. Students will develop their use of some core computing concepts through coding and making practical projects."

**Comment by ganicke** [comment]
Oh, ugh, ugly...
