### ISSUE TITLE
Comment in workspace still shows deleted words when collapse

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5433]
**Describe the bug**
Comment in workspace still shows deleted words when collapse
 
**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#.
2.Create a project with **block editor**.
3.Right-click workspace->Add Comment, enter something and then collapse comment.
4.Expand the comment and **delete all words.**
5.**Collapse the comment** and observe.
 
**Actual behavior:**
The deleted words still shows in collapse comment bar.
 
**Expected behavior:**
No words show in collapse comment bar.
 
**Screen Recording:**
![collapsecomment](https://github.com/microsoft/pxt-microbit/assets/148834117/00ebb9e7-fd00-4f91-8fd2-cb531e3c0ea9)

**Additional context:**
1.OS: Windows 11
2.makecode.microbit,org version: 6.1.8
3.Microsoft MakeCode version: 9.3.7

**Comment by abchatra** [comment]
I don't see the minimize icon anymore to reproduce this.

**Comment by riknoll** [comment]
i need to merge the blockly updates i made now that blockly has released v11. will do now and update this issue if it still repros

**Comment by v-katherine** [comment]
@abchatra I noticed that there is no minimize icon in the latest build. So I cannot reproduce this bug in the latest version, maybe this is new change for the comment.

**Comment by v-katherine** [comment]
I have verified this bug in the latest build: 7.0.15 and it has been fixed.
