### ISSUE TITLE
Unable to get tooltip for some LEDs

### ISSUE THREAD

**Issue by ofaurax** [microsoft/pxt-microbit#5434]
**Describe the bug**
On hover-ing LEDs in the simulator, one can get their coordinates.
Like this:
![Capture d’écran du 2023-12-29 11-01-40](https://github.com/microsoft/pxt-microbit/assets/271723/10abc2be-a302-41ca-96c4-2cd3f2953613)

But for certain LEDs, this is not possible, as it seems there is a sim-head forward:
![Capture d’écran du 2023-12-29 11-02-02](https://github.com/microsoft/pxt-microbit/assets/271723/2c16ecd7-c456-40d6-bca6-98d7d7480207)

**To Reproduce**
1. Create a project from a computer
2. Put your mouse on the first LED, you'll see the tooltip (0,0)
3. Put your mouse on the second LED (same line), you won't see the tooltip

**Expected behavior**
See the (1,0) tooltip

**micro:bit version (please complete the following information):**
V2.21, but it's not hardware related

**Desktop (please complete the following information):**
 - OS: Linux Mageia 9
 - Browser: Firefox
 - Version 115.5.0esr

**Smartphone (please complete the following information):**
None

**Additional context**
I need to mention microbit-support

**Comment by ofaurax** [comment]
I forgot to mention microbit-support

**Comment by abchatra** [comment]
Here is the sample program where one can repro: https://makecode.microbit.org/_h7xiwA6Pqe9t
Some of the top row leds don't have tooltips when hovered.
