### ISSUE TITLE
Function hats disappear on page refresh

### ISSUE THREAD

**Issue by thsparks** [microsoft/pxt-microbit#5442]
If you create a function and then refresh the page, the hat disappears off the top of the function block. (You may have to select the function after refresh for it to repro.)

<img width="139" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/69657545/ad5cb8d4-8a60-4493-8f00-cf0a19f22f8b">

<img width="132" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/69657545/e43c04d5-246f-4ef0-b22c-801f5b05b881">

**Comment by abchatra** [comment]
This is fixed. Please verify.

**Comment by thsparks** [comment]
Still repros in beta but not locally, so I'm guessing fixed but not released to beta yet.
