### ISSUE TITLE
inconsistent behavior with flashlog due to logString

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt-microbit#5449]
**Problem**: the flashlog interface (wraps ubit.log in MakeCode) used by the datalogger extension exposes the C++ method MicroBitLog::logString at the JavaScript level, which can lead to inconsistent and strange results. logString is not even used for datalogger, nor is it used outside of MicroBitLog in codal-microbit-v2.

**Recommendation**: remove logString from flashlog interface.

**Program**:

```
flashlog.setSerialMirroring(true)
flashlog.beginRow()
flashlog.logData("foo", "bar")
flashlog.logString("hello!")
flashlog.endRow()
flashlog.beginRow()
flashlog.logString("goodbye!")
flashlog.logData("foo", "baz")
flashlog.endRow()
```

**Repro**: 

1. load above program (for V2 micro:bit): https://makecode.microbit.org/_isU0HWbvcTyW
2. run and see behavior in simulator
3. compile to micro:bit and run
4. open drive and see following (where output of logString is intermingled with headers and data with no separators):

![image](https://github.com/microsoft/pxt-microbit/assets/10767146/0da1f702-f1df-4d84-913e-520df3b26b64)

```

**Comment by abchatra** [comment]
Flashlog namespace is not exposed in blocks or text toolbox. Won't fix. Use datalogger namespace instead.
