### ISSUE TITLE
Deploy to my own server

### ISSUE THREAD

**Issue by rafaeliga** [microsoft/pxt-microbit#5463]
Hello there,

Can I deploy a version of this project to my own server?

I tried using pxt staticpkg, it works, but I'm having issues configuring login/authentication(client id, redirect url).

Thanks,

**Comment by abchatra** [comment]
This is open source so feel free. We don't offer official support or help for this scenario.

**Comment by xuandac** [comment]
@rafaeliga You deploy a version of this project to  server success ?
I also need to deploy the project to  server. Can you help me how to implement it ?

**Comment by rafaeliga** [comment]
@xuandac Yes, I used [pxt staticpkg](https://makecode.com/cli/staticpkg) to generate it compiled, but I cant get around the social network / login issues.

**Comment by xuandac** [comment]
@rafaeliga Thank you. I did it but now I can't connect to the device. Can you help me with this problem
