### ISSUE TITLE
Naming when making an editor extension

### ISSUE THREAD

**Issue by Dan4P** [microsoft/pxt-microbit#5482]
**Describe the bug**
I thought that the naming convention for extensions only applies to the name of the extension, but i think it actually applies to the whole path including github username. 

I am trying to make an editor extension for this makecode editor and I am running my own local server. When adding my repo to the approvedRepoLib in targetconfig.json i included the capital letters of my username and the extenson refused to let me use the button within the editor extension saying this extension is not allowed. Once i changed all the letters of the path to lower case it started working correctly. The naming convention guidence in https://makecode.com/extensions/naming-conventions says that only lower case letters are allowed but it suggests that this is only the case for the name of the extension and not the full path.

**Desktop (please complete the following information):**
windows
chrome

**Comment by abchatra** [comment]
@Dan4P github is case insensitive. You can name the repo in any case. However adding to the config we string index in javascript which is a case sensitive language and hence lower case should be used. It will work even if the repo name is of different case. This is limitation of target.config.
