### ISSUE TITLE
microbit code 999

### ISSUE THREAD

**Issue by bren-uijl** [microsoft/pxt-microbit#5492]
I have an error code (999) and the internet does not say what is going on.
[https://makecode.microbit.org/S55839-79015-77008-83299](url) controller code
[https://makecode.microbit.org/S57923-04463-91129-01264](url) maqueen code

 - OS: windows 11
 - Browser: edge
 - Microbit v2 + dfrobot maqueen v3.0
 - microbit v1.5 + dfrobot gamepad

**Comment by abchatra** [comment]
999 == UNHANDLED_EXCEPTION This is likely coming from the dfrobot extension. Please contact DFRobot support or their github.com/DFRobot/pxt-gamePad repo
github.com/DFRobot/pxt-maqueen
