### ISSUE TITLE
I would like to be able to know which extensions are used in a Microbit MakeCode project / hex file

### ISSUE THREAD

**Issue by yossiy66** [microsoft/pxt-microbit#5493]
I am a Computer Sciences and Robotics teacher in Junior High and High School.
I am using a lot of 3rd party hardware with Microbit, and they almost always require an extension. These extensions often have newer versions over time. 

I would like to know (i.e. get a written list) which extensions were used in a given MakeCode project / hex file (preferrably the exact links, but I could make do with a unique name that will enable me to locate them in the Extensions).
Possible solutions are: 
1. When an extension is added, a comment with the link is automatically added to the MakeCode blocks.
2. For existing projects I suggest you add a button to the MakeCode UI which will scan the code and add a Comment Block with the list of extensions.
3. An alternative solution would be to build separate software tool which will take a hex file as input and will extract the list of extensions into a text file or a list on the screen I could copy (and then manually paste wherever I want).

Thank you
Yossi

Example of comment (the HTML editor turned the astrisks into bullets...):
/**
 * Extensions:
 * SuperbitV2: https://github.com/YahboomTechnology/SuperBitLibV2
 * IR Remote: https://makecode.microbit.org/pkg/1010technologies/pxt-makerbit-ir-receiver
 */

**Comment by microbit-carlos** [comment]
You can currently see what extensions are loaded in the pxt.json file.

To view it:
- Click on the settings cog and go to the "project settings"
<img width="565" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/9f0288fc-8402-4977-8585-040c5e7bf0cd">

- Click on the "Edit settings as text" button

<img width="705" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/29de91c5-7662-4d40-9e73-f48df2246e15">

- The JSON file shows the extensions used and their version:
<img width="1164" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/a2acffb4-9816-4e66-8b7d-52f2e9e62caf">

**Comment by abchatra** [comment]
Question answered.
