### ISSUE TITLE
regression: yellow block connector "tooth" indicator no longer visible

### ISSUE THREAD

**Issue by eanders-ms** [microsoft/pxt-microbit#5515]
When dragging a block to connect it to another block, the yellow connection point indicator on the receiving block is no longer rendering.

I am running on localhost with latest repos. 

Here's what it looks like in production:
![connector-prod](https://github.com/microsoft/pxt-microbit/assets/12176807/14dfdb34-e95c-497d-8e96-852c62fd0da2)

Here it is on localhost:
![connector-beta](https://github.com/microsoft/pxt-microbit/assets/12176807/94306061-2948-4639-bdca-7636212fefb1)

**Comment by riknoll** [comment]
this is already fixed in beta
