### ISSUE TITLE
v3-beta :  Compiler compiles only blocks, not phyton code.

### ISSUE THREAD

**Issue by 6a5h4** [microsoft/pxt-microbit#5519]
I programmed in phyton until now, and it seems to work, but every change was not applied to the .hex-file, so i ever copied the same phyton software to the micro:bit-v2, so it couldn't work as expected. I needed 3 days to discover that the compiler only compiles the blocks-Programm, never the phyton program editor changes... so one project had more than one software version in it!
I switched above back to blocks and was wondering to see my blocks-program that was 3 days old (!!) ... think you need to rework a lot of the makecode-editor before you can leave the beta status...
@microbit-carlos

**Comment by abchatra** [comment]
Is there more context to this? Are you saying in only /beta python programs are not saved when you download?

**Comment by abchatra** [comment]
@carlosperate any context here?

**Comment by abchatra** [comment]
No additional information given.
