### ISSUE TITLE
Microbit Blutooth doesn't work after adding Jacdac extension

### ISSUE THREAD

**Issue by arijitx** [microsoft/pxt-microbit#5521]
**Describe the bug**

I'm able to pair microbit with an android smartphone and display the data sent via bluetooth to microbit led display. 
```
bluetooth.onUartDataReceived(serial.delimiters(Delimiters.NewLine), function () {
    basic.showString(bluetooth.uartReadUntil(serial.delimiters(Delimiters.NewLine)))
})
bluetooth.startUartService()
basic.forever(function () {
	
})
```

Once I add the jacdac extension, can't pair with the microbit or connect already paired. Seems like adding the jacdac extension disables the BLE of the microbit. Jacdac extension version for makecode "microsoft/pxt-jacdac 1.8.22"

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Edge

**Smartphone (please complete the following information):**
 - Device: Android

**Comment by tballmsft** [comment]
If you are using pxt-jacdac, you will note it disables BLE:

https://github.com/microsoft/pxt-jacdac/blob/ae08f5b64f655be7a89325fc917058520dbd7b60/pxt.json#L110

**Comment by Amerlander** [comment]
Sorry, I just saw, that the Issue Author had in scope to use Jacdac with Bluetooth. So disabled BLE was/is the issue for him and this thread, but not for the continuing discussion.

Shall we create a new issue for "Jacdac breaking DFU services" or is the focus of this issue already changed and we continue here?
For the initial focus of "using Jacdac with BLE" there is also this new issue: https://github.com/microsoft/pxt-microbit/issues/5520

**Comment by tballmsft** [comment]
What pxt-jacdac disables is BLE during app execution. So this issue won't be fixed until Jacdac and BLE can both run during app execution: https://github.com/microsoft/pxt-microbit/issues/5520

**Comment by martinwork** [comment]
After sending a program including the jacdac extension via USB, the iOS app is able to connect, but unable to pair because it does not find any DFU characteristic in Bluetooth pairing mode. As noted above, nRF Connect sees only partial flashing, device information and event services.

After sending a simple hex via USB, then using the iOS app to pair and send a program with the jacdac extension, micro:bit becomes unconnectable. It is advertising, but neither iOS app nor nRF Connect can connect. After deleting the pairing in Settings/Bluetooth both apps can connect, but as before, the app can't pair because there is no DFU service.

This jacdac program also has an extension that dumps the config options to serial on startup
https://makecode.microbit.org/_E6mVARC8LRVr

The program seems to have "MICROBIT_BLE_DFU_SERVICE = 1" but nRF Connect doesn't find micro:bit or Nordic DFU services.

Could the jacdac program corrupt the pairing information at address 0x73000, or corrupt SoftDevice's gatt table?

**Comment by martinwork** [comment]
@tballmsft I used ubittool to download flash contents after a drag & drop transfer of a simple hex and a jacdac hex.

Correction! 0x73000 is scratch. The pairing info is in the pages at 0x75000 and 0x76000, just before the bootloader.

Apart from lots of FFs, with a jacdac hex there is some data before and after 0x73000 and in page 0x76000, that isn't there with a simple hex
```
:102FF000FFFFFFFFFFFFFFFFCCA81000010015003F
:10300000DAE076770080000002000000FFFFFFFF9B
:103010002372756E000100002373636F7065006A90
:103020006163646163300000FFFFFFFFFFFFFFFF8C

:106FD000FFFFFFFFFFFFFFFFCCA810000180101193
:106FE000CCA8100001800811CCA81000018000116D
:106FF000F6C8180007001F00CCA8100001001500FB
```

After pairing Windows with a simple hex, I see pairing information (presumably!)
```
:10500000DEC0ADDEFF011EF1FFFFFFFFFFFFFFFF70

:10600000DEC0ADDEFE011EF107C0140000C00000BE
:106010000100000001A54631B25BBE7D16EC5B3885
:106020007CCD895A1700E09A558C03F000000000DF
:106030000000000000000000000000000000000060
:106040000000000000000000EACBE84F6F951C66DE
:10605000D5E9C805BA80C76340004518C22DDD39AF
:10606000AF84A66D06C0010000C000000200000061
:106070000100000008C00A0000C00000030000008A
:106080000300000020000D000200020011000200C9
:1060900000001500020000002000020000002700A0
:1060A00002000000FEF0000009C0010000C0000076
:1060B0000400000000000000FFFFFFFFFFFFFFFFE4
```

Pairing Windows with a jacdac hex fails. After that, page 0x75000 is still blank and 0x76000 still contains
```
:106FD000CCA8100001801811CCA81000018010115D
:106FE000CCA8100001800811CCA81000018000116D
:106FF000F6C8180007001F00CCA8100001001500FB
```

**Comment by jaustin** [comment]
@mmoskal any idea whether Jacdac is deliberately using this space? Interoperability with Bluetooth flashing is a must for micro:bit compatibility as an increasing number of users are iPad-only. (Compatibility with Bluetooth at runtime co-existing with Jacdac is also important, but not as critical as co-existence with BLE as a conduit for flashing)

**Comment by martinwork** [comment]
https://github.com/lancaster-university/codal-microbit-v2/blob/master/docs/MemoryMap.md

uBit.storage controls 0x74000. Used for compass calibration and partial flashing service.
https://github.com/lancaster-university/codal-microbit-v2/blob/master/source/MicroBitCompassCalibrator.cpp#L417https://github.com/lancaster-university/codal-microbit-v2/blob/master/source/bluetooth/MicroBitPartialFlashingService.cpp#L365

Nordic SDK FDS controls 0x75000 and 0x76000.
https://github.com/microbit-foundation/codal-microbit-nrf5sdk/blob/master/nRF5SDK/components/libraries/fds/fds.h
Using FDS may limit the number of devices that can be paired.

**Comment by tballmsft** [comment]
Thanks for this investigation @martinwork. @jaustin, I need to dig deeper into the Jacdac extension.  I will coordinate with @mmoskal and look for a resolution.

**Comment by tballmsft** [comment]
@jamesadevine - could this be what you were seeing those years ago - that somehow we are running out room in reserved flash space?

> Could the jacdac program corrupt the pairing information at address 0x73000, or corrupt SoftDevice's gatt table?

**Comment by tballmsft** [comment]
The only explicit writing that pxt-jacdac does to flash is via settings: https://github.com/microsoft/pxt-jacdac/blob/ae08f5b64f655be7a89325fc917058520dbd7b60/rolemgr.ts#L5

-- Tom

**Comment by mmoskal** [comment]
the settings package, which is imported by pxt-jacdac uses space 32k before the start of the bootloader.

https://github.com/microsoft/pxt-common-packages/blob/master/libs/settings/settings.cpp#L33

**Comment by tballmsft** [comment]
Wait so does this mean there could be a conflict? Martin said:

> The pairing info is in the pages at 0x75000 and 0x76000, just before the bootloader.

**Comment by tballmsft** [comment]
OK. I will implement test the following solution:
- when DEVICE_BLE is 1, make sure to place the settings used by pxt-jacdac lower in flash so it doesn't conflict with the micro:bit memory map
- reduce the size of the settings from 32kB to 8K.

**Comment by tballmsft** [comment]
https://github.com/microsoft/pxt-common-packages/pull/1473

**Comment by tballmsft** [comment]
The above PR fixes the problem of flashing over BLE! Tested lightly with Jacdac.  Will do more testing.
