### ISSUE TITLE
use of settings consumes more flash (V2) - need to reflect this in available flash for app

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt-microbit#5535]
- Context: the use of the settings feature (from pxt-common-packages) in pxt-jacdac reduces the amount of flash for the user code
- Problem: the web app and compiler are likely unaware of this, so may produce a binary (that uses settings) and overwrites the setting area in flash.
- Solution: need a way to adjust the amount of available flash in compile check for "user code too large", when settings is included in binary

**Comment by tballmsft** [comment]
There are target-specific settings for end of flash
```
        "flashUsableEnd": 242688,
        "flashEnd": 242688,
```
There is no way to override on a package basis, so we would need some special case coding somewhere for this...

**Comment by tballmsft** [comment]
Or we just bump it down by 32K to 454,656 = 0x6F000

**Comment by tballmsft** [comment]
On further reflection, it seems rather severe to take away 32k for settings. On the other hand, most micro:bit programs are tiny! Thoughts?

**Comment by tballmsft** [comment]
Do we have a set of test programs we can benchmark on?

**Comment by tballmsft** [comment]
@carlosperate - can you please give me a set of the largest MakeCode programs for the micro:bit.

**Comment by tballmsft** [comment]
See https://github.com/microsoft/pxt-microbit/issues/5548

**Comment by microbit-carlos** [comment]
> * the use of the settings feature (from pxt-common-packages) in pxt-jacdac reduces the amount of flash for the user code

Is that the CODAL MicroBitStorage (or similar) settings.

If not, this could be also related:
- https://github.com/microsoft/pxt-microbit/issues/5403

> @carlosperate - can you please give me a set of the largest MakeCode programs for the micro:bit.

I don't have anything specifically created for this purpose, mostly just encountered some examples (also from your own testing) like these:
- https://github.com/microsoft/pxt-microbit/issues/5396
- https://github.com/microsoft/pxt-microbit/issues/4788

**Comment by abchatra** [comment]
I am assuming this doesn't need to be tracked as an issue. Closing. If not let me know.
