### ISSUE TITLE
There is no garbage bin when drag the code box to Toolbox

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5543]
**Describe the bug**
There is no **garbage bin** when drag the code box to Toolbox
 
**Steps to reproduce the behavior**
1.Navigate to **https://makecode.microbit.org/beta**.
2.Create/Open a **JavaScript/Python** project.
3.Select a code box in Toolbox.
4.Drag the **code box to the Toolbox** and observe.
  
**Actual behavior:**
There is no garbage bin in the Toolbox, the code box was deleted.
 
**Expected behavior:**
There is a garbage bin in the Toolbox when drag the box to it.
 
**Screen Recording:**
![Garbadgebin](https://github.com/microsoft/pxt-microbit/assets/148834117/787ff9c4-60bb-4e94-a7e4-e33449058153)

**Additional context:**
1.OS: Windows 11
2.makecode.microbit,org version: 7.0.4
3.Microsoft MakeCode version: 10.0.11

**Comment by abchatra** [comment]
This is expected. We don't expect code to be dragged back in text. It can be easily deleted using delete key. It is not same as blocks.
