### ISSUE TITLE
'Smiley Buttons' Python: The content step7 is duplicated with step6

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5544]
**Describe the bug**
'Smiley Buttons' **Python**: The content step7 is duplicated with step6
 
**Steps to reproduce the behavior**
1.Navigate to **https://makecode.microbit.org/beta**.
2.Tutorial->**Smiley Buttons**->**Python** Start Tutorial.
3.**Compare** the content of **step6 and step7**.
 
**Actual behavior:**
The content of step7 is duplicated with content of step6.
 
**Expected behavior:**
Should move the step7.
 
**Screenshot:**
![Duplicate](https://github.com/microsoft/pxt-microbit/assets/148834117/a3135d89-a6bb-4246-a2ad-b28f0a316ab9)

**Additional context:**
1.OS: Windows 11
2.makecode.microbit,org version: 7.0.4
3.Microsoft MakeCode version: 10.0.11

**Comment by ganicke** [comment]
Yeah, that's dumb. I'll remove that last step.
