### ISSUE TITLE
'Love Meter' Blocks: The hint of step3 didn't match with the result

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5546]
**Describe the bug**
**'Love Meter' Blocks**: The **hint of step3** didn't match with the result
 
**Steps to reproduce the behavior**
1.Navigate to **https://makecode.microbit.org/beta**.
2.Tutorial->**Love Meter**->**Blocks Start Tutorial**.
3.Execute to **step3**.
4.**Compare the hint and the actual result**.
 
**Actual behavior:**
The hint of step3 didn't match with the results.
 
**Expected behavior:**
Please update the content of step3, add change the values from 0 to 100.

**Screenshot:** 
![step3](https://github.com/microsoft/pxt-microbit/assets/148834117/326d889b-5b64-45fb-82d5-c9679bd80c9b)

**Additional context:**
1.OS: Windows 11
2.makecode.microbit,org version: 7.0.4
3.Microsoft MakeCode version: 10.0.11

**Comment by ganicke** [comment]
This was fixed in #5354 with the addition of blockconfig:

````
```blockconfig.global
randint(0, 100)
```
````

**Comment by v-katherine** [comment]
Verified this bug was **fixed**
