### ISSUE TITLE
'Love Meter' JavaScript:  Extra ; in the hint of step6

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5549]
**Describe the bug**
'Love Meter' JavaScript:  Extra **;** in the hint of step6
 
**Steps to reproduce the behavior**
1.Navigate to **https://makecode.microbit.org/beta**.
2.Tutorials->**Love Meter**->**JavaScript** Start Tutorial.
3.Compare the **hint of step5 and step6**.
 
**Actual behavior:**
Extra ; in the hint of step6.
 
**Expected behavior:**
No extra ; in the hint.
 
**Screenshot:**
![Extra](https://github.com/microsoft/pxt-microbit/assets/148834117/051b9d60-1f67-4801-bfa4-3ebb1f92d5c9)

**Additional context:**
1.OS: Windows 11
2.makecode.microbit,org version: 7.0.4
3.Microsoft MakeCode version: 10.0.11

**Comment by abchatra** [comment]
Won't fix. Semicolon is optional in javascript and it is ok to show it.
