### ISSUE TITLE
"Course: Networking with the micro:bit": Show 'This site can't be reached' when open Show Instructions

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5550]
**Describe the bug**
"Course: Networking with the micro:bit": Shows 'This site can't be reached' when open Show Instructions
 
**Steps to reproduce the behavior**
1.Navigate to **https://makecode.microbit.org/beta.**
2.**Course->Networking with the micro:bit**->Show Instructions.
3.Observe.
 
**Actual behavior:**
Cannot open the doc, shows 'This site can't be reached'.
 
**Expected behavior:**
Can open the doc successfully.
 
**Screen Recording:**
![Networking](https://github.com/microsoft/pxt-microbit/assets/148834117/17df8e98-cd98-43fc-9896-baf9dab0053d)

**Additional context:**
1.OS: Windows 11
2.makecode.microbit,org version: 7.0.4
3.Microsoft MakeCode version: 10.0.11

**Comment by bsiever** [comment]
Maybe update the link to either https://www.digitaltechnologieshub.edu.au/search/networking-with-the-micro-bit/ or https://www.digitaltechnologieshub.edu.au/media/gxzlurar/networking_with_the_microbit.pdf or https://github.com/nominetresearch/microbit-networking-book/ ?
