### ISSUE TITLE
Some characters of tutorials content are overwritten by Launch Immersive Reader button

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5551]
**Describe the bug**
Some **characters** of tutorials content are **overwritten by Launch Immersive Reader button**
 
**Steps to reproduce the behavior**
1.Navigate to **https://makecode.microbit.org/beta**.
2.Banner->**Send messages with your micro:bit**->Start Tutorial.
3.Go to **step9** and observe the content.
 
**Actual behavior:**
The 'r' in word 'transfer' is overwritten by Launch Immersive Reader button.
 
**Expected behavior:**
No text is overwritten by button.

**Screenshot:**
![Overwritten](https://github.com/microsoft/pxt-microbit/assets/148834117/474baa92-1415-4034-aac1-b7fd16cd81a8)

**Additional context:**
1.OS: Windows 11
2.makecode.microbit,org version: 7.0.4
3.Microsoft MakeCode version: 10.0.11
4.Browser: Edge

**Comment by v-katherine** [comment]
This bug also reproduced in Tutorials->**Flashing Heart**->Blocks Start Tutorial, **step5**

**Comment by abchatra** [comment]
Minor P3. Won't fix.
