### ISSUE TITLE
"Games: Rock Paper Scissors JavaScript" The hint of step2 to step4 need to be updated

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5557]
**Describe the bug**
"Games: Rock Paper Scissors **JavaScript**" The hint of **step2 to step4** need to be updated
 
**Steps to reproduce the behavior**
1.Navigate to **https://makecode.microbit.org/beta**.
2.Games->**Rock Paper Scissors**->**JavaScript** Start Tutorial.
3.Execute to **step2** and compare the results and hint from step2 to step4.
 
**Actual behavior:**
The hint of step2 didn't match with the result.
 
**Expected behavior:**
The hint and result are same.
 
**Screenshot:**
![hint2](https://github.com/microsoft/pxt-microbit/assets/148834117/aa7de7fb-c4cf-4f46-b791-7f80a3f70828)

**Additional context:**
1.OS: Windows 11
2.makecode.microbit,org version: 7.0.4
3.Microsoft MakeCode version: 10.0.11

**Comment by v-katherine** [comment]
This bug also reproduced in **Games->Coin Flipper->JavaScript Start Tutorial**

**Comment by fionama100** [comment]
I verified this bug in the latest build:7.0.19 and it has been fixed.
