### ISSUE TITLE
Simple Teacher Request: Allow pin parameters to be variables instead of (as well as?) drop-down.

### ISSUE THREAD

**Issue by kiki-lee** [microsoft/pxt-microbit#5558]
Would love the pin blocks to be parameterized.  Would love to be able to have the Pin be a variable…instead of a drop-down.  
![image](https://github.com/microsoft/pxt-microbit/assets/1633958/c00885a3-6099-42d3-b5e0-0f23bd883c06)

**Comment by nevergone** [comment]
I would be very happy to have a general solution that can also be used for extensions. Maybe wherever there is a dropdown.

**Comment by nevergone** [comment]
Maybe [/microsoft/pxt-microbit/milestone/7 ?](https://github.com/microsoft/pxt-microbit/milestone/7) ?

**Comment by abchatra** [comment]
This is fixed in /beta @jaustin  fyi
