### ISSUE TITLE
There is no sub menu when right-click 'change by 1' block

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5562]
**Describe the bug**
There is no sub menu when right-click 'change by 1' block
 
**Steps to reproduce the behavior**
1.Navigate to **https://makecode.microbit.org/beta**.
2.Create a new project.
3.Create a new variable, such as rope.
4.Drag _**'Change rope by 1'**_ block to workspace and **right-click it.**
 
**Actual behavior:**
There is no sub menu when right-click 'change by 1' block
 
**Expected behavior:**
There is sub menu when right-click the block.
 
**Screen Recording:**
![nosubmenu](https://github.com/microsoft/pxt-microbit/assets/148834117/d8c7a631-e62c-43eb-8a72-85ff20ba2993)

**Additional context:**
1.OS: Windows 11
2.makecode.microbit,org version: 7.0.4
3.Microsoft MakeCode version: 10.0.11

**Comment by v-katherine** [comment]
Hi @riknoll, I have verified this bug in https://makecode.microbit.org/beta, this bug still reproduced, so reopen this bug. Will close it once the bug was fixed in the latest build.

**Comment by v-katherine** [comment]
Hi @riknoll, I have verified this bug in https://makecode.microbit.org/beta, this bug still reproduced, so reopen this bug. Will close it once the bug was fixed in the latest build.

**Comment by abchatra** [comment]
@v-katherine this is fixed. Can you please validate?

**Comment by v-katherine** [comment]
Hi @abchatra , I have verified this bug **was fixed**, there is sub menu when right-click the block.
![image](https://github.com/user-attachments/assets/6590646b-8356-4825-8067-7aeff2b3df01)
