### ISSUE TITLE
Change of color of bpm slider label in beta

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5564]
**Describe the bug**
Change of color of bpm slider label in beta
 
**Steps to reproduce the behavior**
1.Navigate to **https://makecode.microbit.org/beta**.
2.Create a new project.
3.Drag '_play melody at tempo bpm until done_' and '_set tempo to bpm_' into workspace.
4.Click the **number** in the block.
 
**Actual behavior:**
The slider background is blue in beta.
 
**Expected behavior:**
The slider background is red like live release.
 
**Screenshot:**
![bpmcolor](https://github.com/microsoft/pxt-microbit/assets/148834117/39cbf172-889a-4532-b1c2-dcfccbc4d61f)

**Additional context:**
1.OS: Windows 11
2.makecode.microbit,org version: 7.0.4
3.Microsoft MakeCode version: 10.0.11

**Comment by v-katherine** [comment]
Hi @riknoll, I have verified this bug in https://makecode.microbit.org/beta, this bug still reproduced, so reopen this bug. Will close it once the bug was fixed in the latest build.

**Comment by abchatra** [comment]
Fixed. Verfied.

**Comment by v-katherine** [comment]
Hi @abchatra , I have verified this bug was **fixed** in the latest version.
![image](https://github.com/user-attachments/assets/61a892d9-c6a6-4aac-a9b7-6774972dcad6)
