### ISSUE TITLE
There is no slider when click the number in 'change tempo by bpm' block

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5565]
**Describe the bug**
There is **no slider** when click the number in 'change tempo by bpm' block
 
**Steps to reproduce the behavior**
1.Navigate to **https://makecode.microbit.org/beta**.
2.Create a new project.
3.Drag '_change tempo by bpm_' into workspace.
4.Click the **number** in the block.
 
**Actual behavior:**
There is no slider to change the number.
 
**Expected behavior:**
There is slider like others that can change the number.
 
**Screen Recording:**
![slider](https://github.com/microsoft/pxt-microbit/assets/148834117/6b35dfed-be43-44b2-b67b-15f3bc6315fe)

**Additional context:**
1.OS: Windows 11
2.makecode.microbit,org version: 7.0.4
3.Microsoft MakeCode version: 10.0.11

**Comment by abchatra** [comment]
Set temp has slider, but change tempo doesn't.  This is expected as we don't know the range of tempo user want to change. Won't fix.
