### ISSUE TITLE
How to edit pxt-micro:bit iframe block?

### ISSUE THREAD

**Issue by jackKimGoorm** [microsoft/pxt-microbit#5566]
**Is your feature request related to a problem? Please describe.**

hello

If you build pxt-microbit with the pxt staticpkg command and display the resulting index.html as an iframe,

Blocks cannot be modified as shown in the attached image

How can I solve this?

**Describe the solution you'd like**

https://makecode.microbit.org/#editor

When using an iframe, I would like to see all the editing UI as shown in the URL above.

**Describe alternatives you've considered**

**Additional context**

![screenshot1](https://github.com/microsoft/pxt-microbit/assets/122429247/ecd24655-cff1-4abe-a456-82e20e2bfc61)

**Comment by riknoll** [comment]
add `?editorlayout=ide` to the url (before the `#editor`)

**Comment by abchatra** [comment]
Question answered
