### ISSUE TITLE
[iPad] 'Show Instructions' display incomplete on iPad vertical screen

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5572]
**Describe the bug**
[iPad] **'Show Instructions'** display incompletely on iPad vertical screen
 
**Steps to reproduce the behavior**
1.Navigate to **https://makecode.microbit.org/beta on iPad**.
2.Set **iPad vertical screen**.
3.Open any tutorial has **'Show Instructions' card**, such as Games->Reaction Time->Show Instructions.
4.**Observe 'Show Instructions'**.
 
**Actual behavior:**
'Show Instructions' display incompletely on iPad vertical screen.
 
**Expected behavior:**
'Show Instructions' display completely.
 
**Screenshot:**
![ShowInstructions](https://github.com/microsoft/pxt-microbit/assets/148834117/632b79c0-d4cb-4fcf-8c83-cacc80759e3a)
**Additional context:**
1.OS: iPad 8th 17.4
2.makecode.microbit,org version: 7.0.4
3.Microsoft MakeCode version: 10.0.11

**Comment by abchatra** [comment]
P3 won't fix.
