### ISSUE TITLE
[iPad] 'Fashion: Name Badge': 'Download' is so large that truncates above words

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5573]
**Describe the bug**
[iPad] 'Fashion: Name Badge': 'Download' is so large that truncates above words
 
**Steps to reproduce the behavior**
1.Navigate to **https://makecode.microbit.org/beta** on iPad.
2.**Fashion->Name Badge->Show Instructions**.
3.Observe the **content under 'Download'** section.
 
**Actual behavior:**
The 'y' is truncated by beneath 'Download'.
 
**Expected behavior:**
'Download' updated small that won't truncated other words.

**Screenshot:**
![Truncated](https://github.com/microsoft/pxt-microbit/assets/148834117/9a9fada8-6d5c-4bf7-842d-39acb82e09a5)

**Additional context:**
1.OS: iPad 8th 17.4
2.makecode.microbit,org version: 7.0.4
3.Microsoft MakeCode version: 10.0.11

**Comment by v-katherine** [comment]
This bug also reproduced in **Mac Safari** browser.

**Comment by abchatra** [comment]
P3 won't fix.
