### ISSUE TITLE
Cannot open Immersive Reader and pops-up an error when click 'Launch Immersive Reader' button

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5574]
**Describe the bug**
Cannot open Immersive Reader and pops-up an error when click 'Launch Immersive Reader' button
 
**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta.
2.Open any tutorial, such as 'Tutorials->Flashing Heart->Start Tutorial'
3.Click the **'Launch Immersive Reader' button** in ReactModal or content.
 
**Actual behavior:**
Cannot open Immersive Reader, pops-up 'Immersive Reader could not be launched' error.
 
**Expected behavior:**
Open Immersive Reader normally with no error.
 
**Screen Recording:**
![ImmersiveReader](https://github.com/microsoft/pxt-microbit/assets/148834117/525dc48c-82b4-4c9c-b630-9be425338a23)

**Additional context:**
1.OS: Windows11, iPad 8th 17.4
2.makecode.microbit,org version: 7.0.4
3.Microsoft MakeCode version: 10.0.11

**Comment by v-katherine** [comment]
Hi @abchatra, please notice this bug, **cannot open immersive reader in both live & beta version**.

**Comment by abchatra** [comment]
Thanks for catching this. Great bug.

**Comment by v-katherine** [comment]
Have verified this bug in the latest build, this bug was fixed.
