### ISSUE TITLE
[iPad] There is no response when click 'Try in MakeCode' in Jacdac tutorials

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5575]
**Describe the bug**
[iPad] There is no response when click **'Try in MakeCode**' in **Jacdac** tutorials
 
**Steps to reproduce the behavior**
1.Navigate to **https://makecode.microbit.org/beta on iPad**.
2.Open tutorial under **Jacdac section**, such like  Button smasher->Show Instructions.
3.Click **Try in MakeCode** and observe.
 
**Actual behavior:**
There is **no response**, didn't open Micro:bit editor in new tab.
 
**Expected behavior:**
Open Micro:bit editor in new tab.
 
**Screen Recording:**
https://github.com/microsoft/pxt-microbit/assets/148834117/29ed3339-f3da-4dca-95b2-467557db780f

**Additional context:**
1.OS: **iPad 8th 17.4.1**
2.makecode.microbit,org version: 7.0.4
3.Microsoft MakeCode version: 10.0.11

**Comment by abchatra** [comment]
@pelikhan  this is issue on the jacdac site and not makecode.

**Comment by pelikhan** [comment]
Button hidden on mobile.
