### ISSUE TITLE
There is no Connect Device in Safari browser

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5576]
**Describe the bug**
There is no Connect Device in **Safari** browser
 
**Steps to reproduce the behavior**
1.Navigate to **https://makecode.microbit.org/beta on Safari**.
2.Create or open a project.
3.Click the **ellipsis behind 'Download**' and observe.
 
**Actual behavior:**
There is no Connect Device in Safari browser.
 
**Expected behavior:**
There is Connect Device option in Download.
 
**Screenshot:**
![Connectdevice](https://github.com/microsoft/pxt-microbit/assets/148834117/e321aa2f-38b8-4064-9d07-68282c597b98)

**Additional context:**
1.OS: Mac OS 13.6.6, iPad 8th OS 17.4
2.makecode.microbit,org version: 7.0.4
3.Microsoft MakeCode version: 10.0.11
4.In the same machine, there is 'Connect Device' in Edge browser.

**Comment by v-katherine** [comment]
@abchatra This bug also reproduced in iPad platform, does this is a bug in iPad platform or by design?

**Comment by abchatra** [comment]
There is no WebUSB technology to connect to device in iPad. This is by design.

**Comment by v-katherine** [comment]
@abchatra This bug also reproduced in **Mac Safari** browser, but not reproduced in Edge browser, is that by design for Safari browser?

**Comment by abchatra** [comment]
Yes safari doesn't support webusb.

**Comment by v-katherine** [comment]
@abchatra Thanks for your confirmation, will test connect device function in Edge browser.
