### ISSUE TITLE
[Teacher Tools] Pops error 'Unable to evaluate some criteria' when run the rubric

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5583]
**Describe the bug**
[Teacher Tools] Pops error **'Unable to evaluate some criteria'** when run the rubric
 
**Steps to reproduce the behavior**
1.Finished **'Micro Chat'** in **Micro:bit**https://makecode.microbit.org/beta and click Publish button to get project link.
2.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval) and choose **'Micro Chat' rubric**.
3.**Copy and paste project link** to 'Enter' box and click submit.
4.Click 'Evaluate' button.
 
**Actual behavior:**
Pops error 'Unable to evaluate some criteria'.
 
**Expected behavior:**
No error pops-up, can evaluate each criteria.
 
**Screen Recording:**
![unableevaluate](https://github.com/microsoft/pxt-microbit/assets/148834117/294a8f29-3d5f-4868-97a2-07b02b002430)

**Additional context:**
1.OS: Windows11
2.makecode.microbit,org version: 7.0.4
3.Microsoft MakeCode version: 10.0.11

**Comment by abchatra** [comment]
@v-katherine this looks fixed. Can you validate?

**Comment by v-katherine** [comment]
Hi@abchatra， I have verified this bug was **fixed.**
