### ISSUE TITLE
docs: recommended browser for macOS should be one with webUSB?

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#5586]
On https://makecode.microbit.org/browsers/mac we state that the recommended browser for macOS is Safari.

Is this still true? With web USB now the default I think it might make sense to recommend a browser with webUSB instead. 

I'd be fine with it being Edge, my preference would be to recommend Chrome as many will already have it.

**Comment by ganicke** [comment]
Addressed by https://github.com/microsoft/pxt/pull/10044.
