### ISSUE TITLE
Cannot Use Google Log-In In Micro:Bit Beta Android App

### ISSUE THREAD

**Issue by thsparks** [microsoft/pxt-microbit#5590]
If I try to login with google while using the micro:bit beta android app, I get this error:

![image](https://github.com/microsoft/pxt-microbit/assets/69657545/d837d93e-7080-4bb0-a702-15a83d8a8db6)

**Comment by abchatra** [comment]
@jaustin  fyi

**Comment by abchatra** [comment]
There is a tracking bug on other repository. Closing this.
