### ISSUE TITLE
Is the cloud C++ compiler down again?

### ISSUE THREAD

**Issue by ggstephenlau** [microsoft/pxt-microbit#5594]
I find that closed issue #5353 happens again

when I compile the default extension audio-recording, I have got the following,

<img width="945" alt="Screenshot 2024-04-18 at 12 19 05 PM" src="https://github.com/microsoft/pxt-microbit/assets/46183580/7314d1b1-a739-4858-b0a1-5090ac3bda86">

Could you help on this issue?
Thank you very much!!

**Comment by microbit-carlos** [comment]
@abchatra I can replicate this with the MakeCode live deployment.

Adding a C++ extension to an empty project and the clud compiler does not seem to be responding:
https://makecode.microbit.org/_i0XhLAKrrH6C
<img width="754" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/fb723287-22e9-4f7c-b1c3-ba7ee44b274b">

@aznhassan I think it's possible Abhijith might be away this week, if that's the case is that something you could look into, or raise internally? Thanks!

**Comment by eanders-ms** [comment]
Compiler VM restarted. Can you please try again?

**Comment by ggstephenlau** [comment]
Hi eander-ms,

Yes, the compiler works now.
Thank you very much!

**Comment by Jaqster** [comment]
Thanks Eric!

**Comment by ggstephenlau** [comment]
Hi,

I want to state that this problem occurred again.

<img width="700" alt="Screenshot 2024-08-01 at 12 33 40 PM" src="https://github.com/user-attachments/assets/74ff41f8-ccc1-4bf9-8886-5d67f437bc69">

Would you help on this?
Thank you very much.
