### ISSUE TITLE
Extensions don't work when I publish in Azure WebApp 

### ISSUE THREAD

**Issue by humberto-jezus** [microsoft/pxt-microbit#5595]
**Describe the bug**

Hello friends, I am facing difficulties with the extensions in the makecode editor. I downloaded the pxt project from github and all the dependencies to my computer. When running the project on localhost, everything works normally; however, when publishing on a cloud host, the application becomes unable to call the extensions in the makecode editor (see image). First image local host , with the extensions working and second image with the custom url cloudhost not working. Can someone help me? Thanks

First Image - LocalHost 
![image](https://github.com/microsoft/pxt-microbit/assets/148150932/e8b71e8c-890c-449e-bb79-8fdd136cbbf5)

Second Image - Cloudhost - Custom URL 
![image (1)](https://github.com/microsoft/pxt-microbit/assets/148150932/4bfefa62-0ab0-4928-a24a-6bd7241ddc1b)

https://xbytex.azurewebsites.net/#editor

Image with the call errors 

![Captura de tela 2024-04-18 083325](https://github.com/microsoft/pxt-microbit/assets/148150932/8cd323f7-c5a7-493a-af40-19c942c7a6c1)

my question is : There is a file that I need update to enable my custom url call the extensions apis? I tried to find but , I dont have sucess with this 

Thank you

**Comment by StanislavJochman** [comment]
Did you find the solution? Facing same issue.

**Comment by humberto-jezus** [comment]
> Did you find the solution? Facing same issue.


No @StanislavJochman
I opened a ticket support for microbit but anybody can't helped me , they only indicate other similar issues here in github
my new approach is trying to fill the extension directly in the editor bar like this image:

![image](https://github.com/microsoft/pxt-microbit/assets/148150932/111855a8-508b-48b5-a44b-64520ee7d31a)

This way maybe will working and not needed to search  for a external api , because I'm almost sure that we  have a "cors" rules blocking my custom url

![image](https://github.com/microsoft/pxt-microbit/assets/148150932/76f9c775-954f-43b5-a347-222189d1e78b)

If I get success , I will return to help as well 
Thank you

**Comment by abchatra** [comment]
This is your own website. You will have to build a backend which supports importing extensions from github. Extensions are built on github and needs to be ingested to your backend. This is nothing to do with makecode site.
