### ISSUE TITLE
docs: Technical information about browser support is out of date

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#5596]
I think this is out of date - 
https://makecode.microbit.org/browsers/technical

e.g. Mobile OS for Mobile Safari should be 13
see https://github.com/microsoft/pxt-microbit/issues/4384

**Comment by jaustin** [comment]
See also https://github.com/microsoft/pxt-microbit/issues/5586

**Comment by abchatra** [comment]
Lets try to update the documentation in this release.
