### ISSUE TITLE
Top menu

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5602]
I'm not a huge fan of this menu design - feels like it's not discoverable enough and not part of the core user flow.
![image](https://github.com/microsoft/pxt-microbit/assets/22108954/5a05bdf6-6656-446a-b4b0-8a87c45fe36f)

I feel like the Run button really only needs to be shown in the Rubric window, and the Print button only in the Results window.
How can we make these more clear and surface them in the right place at the right time?

**Comment by thsparks** [comment]
This was addressed by @eanders-ms's recent change: https://github.com/microsoft/pxt/pull/10103
