### ISSUE TITLE
Teacher Tools: Cannot create a new rubric from action menu when there is an already 'in progress' checklist

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5616]
**Describe the bug**
Teacher Tools: **Cannot create a new rubric from action menu** when there is an already '**in progress' checklist**
 
**Steps to reproduce the behavior**
1.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval).
2.Click the 'New Rubric' card, **type a name**.
3.Via **More Actions->New Rubric to create a new rubric**.
4. Click Home and back to Rubric tab, **observe the name**.
 
**Actual behavior:**
Didn't create a new rubric, the name still displayed as created in step2.
 
**Expected behavior:**
Create a new rubric successfully, **have the same behavior as create a new rubric form 'New Rubric' card**.
 
**Screen Recording:**
![newrubric](https://github.com/microsoft/pxt-microbit/assets/148834117/4b6d74b9-5257-4510-80a0-5999a54b9bf4)

**Additional context:**
1.OS: Windows11
2.makecode.microbit,org version: 7.0.6
3.Microsoft MakeCode version: 10.0.18

**Comment by v-katherine** [comment]
Create a new rubric **from 'New Rubric' card successfully** when there is an already checklist:
![correct](https://github.com/microsoft/pxt-microbit/assets/148834117/e764b99e-3665-4f3a-aca3-30f2afcf7d59)

**Comment by v-katherine** [comment]
This bug also reproduced in when **import a new checklist via More Actions**, the name won't change.

**Comment by thsparks** [comment]
No longer repros, since the action menu was removed in @eanders-ms's recent change: https://github.com/microsoft/pxt/pull/10103

**Comment by fionama100** [comment]
I verified this bug in the latest version: 7.0.21 and it has been fixed.
