### ISSUE TITLE
Teacher Tools: The results incorrect when set result as N/A or Needs work and then turn on the Auto-Run

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5617]
**Describe the bug**
Teacher Tools: The results incorrect when **set result as N/A or Needs work** and then **turn on the Auto-Run**
 
**Steps to reproduce the behavior**
1.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval) and **make sure the turn off the Auto-Run.**
2.Enter Project Link and submit.
3.Choose the Rubric, and **switch to Results tab**.
4. **Change some rubrics results as N/A or Needs work.**
5.**Turn on Auto-Run and observe the results.**
 
**Actual behavior:**
The **results which changed to N/A or Needs work are incorrect after turning on Auto-Run**.
 
**Expected behavior:**
All rubrics will be evaluated and **outcome correct results.**
 
**Screen Recording:**
![resultincorrect](https://github.com/microsoft/pxt-microbit/assets/148834117/7d54762f-b6b4-44b0-b2d2-f1cd8875b2c6)

**Additional context:**
1.OS: Windows11
2.makecode.microbit,org version: 7.0.6
3.Microsoft MakeCode version: 10.0.18

**Comment by v-katherine** [comment]
The results are correct when set results as N/A or Needs work and then **click Run**
![Runincorrect](https://github.com/microsoft/pxt-microbit/assets/148834117/779dd27b-e6eb-4a72-afe3-a33b2a70faaa)

**Comment by thsparks** [comment]
This is by design, if the teacher specifically sets a result then it gets priority. But we can chat about this as a team, since it does feel a bit inconsistent that pressing "run" does overwrite it but auto-run does not.

**Comment by abchatra** [comment]
Lets be consistent for both auto-run and run.

**Comment by eanders-ms** [comment]
Proposal:

**Make Run and Auto-run status-aware**
After the user has manually set the status of a criteria to anything other than Not Started, Run and Auto-run will no longer evaluate that criteria. Manually setting status back to Not Started clears the flag, allowing Run and Auto-run to evaluate and re-evaluate the criteria in question.

**Exception for single-criteria evaluation**
If the user clicks the Run button on the criteria itself (single-criteria run), then we will evaluate the criteria regardless of status.

Thoughts?

**Comment by abchatra** [comment]
Move the autorun to the right and name auto run on load.

**Comment by fionama100** [comment]
I verified this bug in the latest version:7.0.29 and it has been fixed.
