### ISSUE TITLE
Teacher Tools: There is no blockly Toolbox in project view when turn on debug mode

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5619]
**Describe the bug**
Teacher Tools: There is **no blockly Toolbox in project view** when turn on **debug mode**
 
**Steps to reproduce the behavior**
1.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval).
2.Enter Project Link and submit.
3.Click **Toggle Debug Mode in project view and observe**.
 
 
**Actual behavior:**
There is no blockly Toolbox in project view when turn on debug mode.
 
**Expected behavior:**
There is blockly Toolbox when turn on the debug mode.
 
**Screen shot:**
![debug](https://github.com/microsoft/pxt-microbit/assets/148834117/8bed8b35-88fb-41f8-8400-d31faac5f5d9)

**Additional context:**
1.OS: Windows11
2.makecode.microbit,org version: 7.0.6
3.Microsoft MakeCode version: 10.0.18

**Comment by abchatra** [comment]
Hide debug buttons if not necessary.

**Comment by fionama100** [comment]
I verified this bug in the latest version:7.0.29 and it has been fixed.
