### ISSUE TITLE
Teacher Tools: Shows 'Sorry, the page is missing' when click 'Learn More'

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5622]
**Describe the bug**
Teacher Tools: Shows 'Sorry, the page is missing' when click **'Learn More'**

**Steps to reproduce the behavior**
1.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval).
2.Click **'Learn More'** and observe.
 
**Actual behavior:**
Shows 'Sorry, the page is missing' in new tab.
 
**Expected behavior:**
Open the help docs with no error.
 
**Screen Recording:**
![Learnmore](https://github.com/microsoft/pxt-microbit/assets/148834117/3f182f04-b973-4f3e-9ac3-8ba890643c97)

**Additional context:**
1.OS: Windows11
2.makecode.microbit,org version: 7.0.6
3.Microsoft MakeCode version: 10.0.18

**Comment by fionama100** [comment]
I verified this bug in the latest version: 7.0.34 and it still reproduces, so I reopen it.

**Comment by ganicke** [comment]
Waiting to be published - https://github.com/microsoft/pxt-microbit/blob/master/docs/teachertool.md

**Comment by Ramanan0530** [comment]
I verified this bug in the latest version: 7.0.36 and it has been fixed.
