### ISSUE TITLE
Teacher Tools: The columns of criteria table are not aligned when resizing checklist view to small size

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5623]
**Describe the bug**
Teacher Tools: The **columns of criteria table are not aligned** when resizing **checklist view to small size**
 
**Steps to reproduce the behavior**
1.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval).
2.Open a Rubric.
3.**Resize the checklist view to a small size**.
4.**Observe the delete button columns**.
 
**Actual behavior:**
The **columns of Criteria table are not aligned**.
 
**Expected behavior:**
The lines of Criteria table aligned all time.
 
**Screen Recording:**
![Tablelines](https://github.com/microsoft/pxt-microbit/assets/148834117/a85fcc1e-cb0a-4182-9b79-e49021e4825a)

**Additional context:**
1.OS: Windows11
2.makecode.microbit,org version: 7.0.6
3.Microsoft MakeCode version: 10.0.18

**Comment by thsparks** [comment]
Closing this but noting that we should address it as a part of https://github.com/microsoft/pxt-microbit/issues/5614
