### ISSUE TITLE
Teacher Tools: More actions button is disable in Results tab

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5624]
**Describe the bug**
Teacher Tools: **More actions button is disable in Results tab**

**Steps to reproduce the behavior**
1.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval) and **make sure Auto-Run is off.**
2.**Enter Project link** or Share ID and submit.
3.Choose one rubric and switch to **Results tab**.
4.**Observe the More actions button and click**.
 
**Actual behavior:**
The More actions button is grey and disable.
 
**Expected behavior:**
The **More actions button is able in Results tab.**

**Screen Recording:**
![moreactions](https://github.com/microsoft/pxt-microbit/assets/148834117/7a492f1c-29ae-4773-b1ae-7787aa897be2)

**Additional context:**
1.OS: Windows11
2.makecode.microbit,org version: 7.0.6
3.Microsoft MakeCode version: 10.0.18

**Comment by abchatra** [comment]
This should be solved by combining the checklist and results page.

**Comment by thsparks** [comment]
Addressed by @eanders-ms' recent change: https://github.com/microsoft/pxt/pull/10103
