### ISSUE TITLE
Teacher Tools: Missing N/A outcome in print page

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5625]
**Describe the bug**
Teacher Tools: **Missing N/A outcome in print page**
 
**Steps to reproduce the behavior**
1.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval).
2.**Enter Project link or Share ID and submit.**
3.Switch to **Results tab** and **set some rubric results as N/A.**
4.Click **Print button and observe the results.**
 
**Actual behavior:**
Missing N/A outcome in print page.
 
**Expected behavior:**
There is N/A outcome in print page.
 
**Screen Recording:**
![NA](https://github.com/microsoft/pxt-microbit/assets/148834117/a9f7131f-e45d-48dd-afff-b5975cda2244)

**Additional context:**
1.OS: Windows11
2.makecode.microbit,org version: 7.0.6
3.Microsoft MakeCode version: 10.0.18

**Comment by thsparks** [comment]
This was initially by design (the idea being, the teacher can provide feedback and just not have a pass/fail result attached), but perhaps we should show N/A still if there's no feedback. Or just always show it.

**Comment by fionama100** [comment]
I verified this bug in the latest version: 7.0.22 and it has been fixed.
![Fixed](https://github.com/user-attachments/assets/07cddf45-c50e-4aa6-b5a2-81a7184d5368)
