### ISSUE TITLE
Block/Workspace Search turning blocks grey

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5629]
When doing a workspace search using Ctrl-F, the selected blocks turn grey instead of being highlighted

Live - 
![image](https://github.com/microsoft/pxt-microbit/assets/22108954/6380f148-4ac6-46cc-9219-459826d94931)

Beta - 
![image](https://github.com/microsoft/pxt-microbit/assets/22108954/62f3de24-7a88-4d3a-826f-99beca502822)

**Comment by abchatra** [comment]
I can reproduce this issue
