### ISSUE TITLE
Teacher Tools: The Header bar UI display error when set rubric name too long

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5634]
**Describe the bug**
Teacher Tools: The **Header bar UI display error** when set **rubric name too long**
 
**Steps to reproduce the behavior**
1.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval).
2.Create a new Rubric.
3.**Set the new Rubric name too long.**
4.Observe the **Header bar**.
 
**Actual behavior:**
The Header bar UI displays error when the rubric name too long.
 
**Expected behavior:**
The Header bar will adaptive the size when the rubric name too long.
 
**Screen Recording:**
![nametoolong](https://github.com/microsoft/pxt-microbit/assets/148834117/5d236042-401a-4b93-b7d8-55a872915390)

**Additional context:**
1.OS: Windows11
2.makecode.microbit,org version: 7.0.8
3.Microsoft MakeCode version: 10.0.20

**Comment by thsparks** [comment]
We should probably just remove the rubric name from the header bar. I recall a conversation where this may not be allowed per branding guidelines anyway.

**Comment by v-katherine** [comment]
Hi @thsparks, I have verified this bug **still reproduced** in the latest build, so **reopen** this bug.
![image](https://github.com/microsoft/pxt-microbit/assets/148834117/af38885f-c96f-45fe-9791-b1bc99af6a51)

**Comment by thsparks** [comment]
It still repro's because we haven't bumped beta yet. Will go away once beta is running pxt version > 10.0.20

**Comment by thsparks** [comment]
Re-opening until beta is released

**Comment by thsparks** [comment]
Bumped beta, fix should be there now.

**Comment by v-katherine** [comment]
Verified this bug was **fixed** in makecode.microbit,org version: 7.0.9, Microsoft MakeCode version: **10.0.21**
