### ISSUE TITLE
Teacher Tools: The comment icon is missing in project view when the comment is empty in editor

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5635]
**Describe the bug**
Teacher Tools: The **comment icon is missing in project view** when the **comment is empty in editor**
 
**Steps to reproduce the behavior**
1.Create a **project with a blank comment of block**, copy the project link.
2..Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval).
3.Enter Project link or Share ID and submit.
4.**Observe the block which added the comment in editor.**
 
**Actual behavior:**
There is no comment icon in project view when the comment is empty in editor.
 
**Expected behavior:**
There is comment icon in project view even though the comment is empty.

**Screen Recording:**
![comment](https://github.com/microsoft/pxt-microbit/assets/148834117/2cd1efa3-0da0-4e80-928f-4daa375397c2)

**Additional context:**
1.OS: Windows11
2.makecode.microbit,org version: 7.0.8
3.Microsoft MakeCode version: 10.0.20

**Comment by abchatra** [comment]
Comment icon will be present, only if there is a comment. I don't see any comment added in the repro. This is by design.
