### ISSUE TITLE
Teacher Tools: Didn't warp text in comment box in project view when the texts are long

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5636]
**Describe the bug**
Teacher Tools: **Didn't warp text in comment box** in project view when the texts are long
 
**Steps to reproduce the behavior**
1.Create a project with **long texts comment of block**, copy the project link.
2.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval).
3.Enter Project link or Share ID and submit.
4.**Observe the comment.**
 
**Actual behavior:**
**Didn't warp text** in comment box.
 
**Expected behavior:**
**Warp text in the comment box like editor.**
 
**Screen Recording:**
![warptext](https://github.com/microsoft/pxt-microbit/assets/148834117/8ef6a2ff-12f5-49c9-b922-964e7f6ee70d)

**Additional context:**
1.OS: Windows11
2.makecode.microbit,org version: 7.0.8
3.Microsoft MakeCode version: 10.0.20

**Comment by v-katherine** [comment]
The **comment of workspace works well**, warp text in the comment box.
![image](https://github.com/microsoft/pxt-microbit/assets/148834117/2a2c28d5-2889-49c7-a95a-b7da59a0676c)

**Comment by abchatra** [comment]
As comment is one of the important aspect of evaluation. This is good to fix. Probably embed isue.
