### ISSUE TITLE
Teacher Tools: The block 'every NaN ms' in project view needs to be updated

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5637]
**Describe the bug**
Teacher Tools: The **block 'every NaN ms' in project view** needs to be updated
 
**Steps to reproduce the behavior**
1.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval).
2.Open or create a rubric, click Add Criteria.
3.Choose **'block used count times'.**
4.Click **block->Loops** and **observe block 'every NaN ms'.**
 
**Actual behavior:**
The block 'every NaN ms' in project view **needs to be updated.**
 
**Expected behavior:**
Should **update to 'every 500 ms' like editor.**
 
**Screen Recording:**
![block](https://github.com/microsoft/pxt-microbit/assets/148834117/005206ba-abb0-45f0-a5fd-29a2cdf2b0c2)

**Additional context:**
1.OS: Windows11
2.makecode.microbit,org version: 7.0.8
3.Microsoft MakeCode version: 10.0.20

**Comment by riknoll** [comment]
No longer repros

**Comment by riknoll** [comment]
ah, i see this is referring to the teacher tool. reopened

**Comment by fionama100** [comment]
I verified this bug in the latest version:7.0.29 and it has been fixed.
