### ISSUE TITLE
Teacher Tools: Print view broken for long rubric name and project link

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5638]
**Describe the bug**
Teacher Tools: Print view **broken for long rubric name and project link**
 
**Steps to reproduce the behavior**
1.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval).
2.Open or create a rubric, **set a long rubric name.**
3.Enter Project Link or Share ID.
4.Switch to Results tab.
5.Click **Print button and observe**.
 
**Actual behavior:**
The rubric name and project link displayed incompletely.
 
**Expected behavior:**
The rubric name and project link display completely.
 
**Screen Recording:**
![pintview](https://github.com/microsoft/pxt-microbit/assets/148834117/1c2b06cd-8308-4f0b-af49-8a51a85b0257)

**Additional context:**
1.OS: Windows11
2.makecode.microbit,org version: 7.0.8
3.Microsoft MakeCode version: 10.0.20

**Comment by fionama100** [comment]
I verified this bug in the latest version: 7.0.34 and it still reproduce, so I reopen it now.

**Comment by eanders-ms** [comment]
I do see a regression where the project name and qr code are not printing. Will address this.
