### ISSUE TITLE
When running with hostname=0.0.0.0 extensions are not loading

### ISSUE THREAD

**Issue by StanislavJochman** [microsoft/pxt-microbit#5645]
When running using pxt serve --hostname 0.0.0.0 extensions are not loading.

**Comment by abchatra** [comment]
We don't support this scenario.

**Comment by StanislavJochman** [comment]
And how it is possible to load extensions that are not official. Or how can I add them to be official?

**Comment by martinwork** [comment]
Hi @StanislavJochman Please see this article...
https://support.microbit.org/support/solutions/articles/19000054952-makecode-extension-and-tutorial-approval
