### ISSUE TITLE
Teacher Tools: Can input float number and plus & minus characters before number in numeric parameters

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5648]
**Describe the bug**
Teacher Tools: Can input **float number** and **plus & minus characters before number** in **numeric parameters**
 
**Steps to reproduce the behavior**
1.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval).
2.Open or create a Checklist.
3.Click Add Criteria, choose some **criteria which has count parameters**.
4.Input minus, plus characters before number in numeric parameters. (such like: -3, +4)
5.Input float in numeric parameters. (such like: 1.5)
 
**Actual behavior:**
Can **input float number** and **plus, minus characters before number** in **numeric parameters.**
 
**Expected behavior:**
**Only allow number inputs**, no other characters.
 
**Screenshot:**
![numbers](https://github.com/microsoft/pxt-microbit/assets/148834117/8f920952-7a2a-4726-8e31-6660871b50ef)

**Additional context:**
1.OS: **Windows**11 **iMac** Ventura 13.6.6
2.makecode.microbit,org version: 7.0.9
3.Microsoft MakeCode version: 10.0.21

**Comment by Ramanan0530** [comment]
I verified this bug in the latest version: 7.0.40 and it has been fixed.
