### ISSUE TITLE
Teacher Tools: Can input long number in numeric parameters

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5649]
**Describe the bug**
Teacher Tools: Can **input long number in numeric parameters**

**Steps to reproduce the behavior**
1.Navigate to MakeCode Teacher Tool (microbit.org).
2.Open or create a Checklist.
3.Click Add Criteria, choose some **criteria which has count parameters**.
4.Input a **long number** in numeric parameters

**Actual behavior:**
Can input a long number in numeric parameters.

**Expected behavior:**
Numeric parameters have a **small input**, cannot input long number.

**Screen Recording:**
![inputlongnumber](https://github.com/microsoft/pxt-microbit/assets/148834117/1e3f06e1-d866-4b54-9b12-72d13fb2673f)

**Additional context:**
1.OS: **Windows**11 **iMac** Ventura 13.6.6
2.makecode.microbit,org version: 7.0.9
3.Microsoft MakeCode version: 10.0.21

**Comment by Ramanan0530** [comment]
I verified this bug in the latest version: 7.0.40 and it has been fixed.
