### ISSUE TITLE
Teacher Tools: No warning appears when there is already unnamed checklist and then create or open checklist

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5650]
**Describe the bug**
Teacher Tools: **No warning appears** when there is **already unnamed checklist** and then **create or open checklist**
 
**Steps to reproduce the behavior**
1.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval).
2.**Create a new checklist with unnamed.**
3.**Create or open an existed checklist**, observe.
 
**Actual behavior:**
No warning appears.
 
**Expected behavior:**
A warning will appear to ask if overwriting it.
 
**Screen Recording:**
![warning](https://github.com/microsoft/pxt-microbit/assets/148834117/3ac63d12-1ddd-46c4-a82e-9929976a2915)

**Additional context:**
1.OS: Windows11 iMac Ventura 13.6.6
2.makecode.microbit,org version: 7.0.9
3.Microsoft MakeCode version: 10.0.21

**Comment by v-katherine** [comment]
Also **reproduced in import** a checklist when there is already unnamed checklist
![import](https://github.com/microsoft/pxt-microbit/assets/148834117/7c6f61c6-e5cb-4c56-8105-34857e37022e)

**Comment by abchatra** [comment]
This is by design. If there is no criteria added it is treated as empty and ok to override. If I am mis understanding this bug let me know.
