### ISSUE TITLE
Teacher Tools: Can input 'e' in numeric parameters

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5651]
**Describe the bug**
Teacher Tools: Can **input 'e' in numeric parameters**

**Steps to reproduce the behavior**
1.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval).
2.Create or open a checklist.
3.Click Add Criteria and choose **some criteria with numeric parameters.**
4**.Input 'e' in numeric parameters**, **try others letter** and observe.
 
**Actual behavior:**
**Can input 'e' in numeric parameters, cannot put other letters**.
 
**Expected behavior:**
**Cannot input any letter** in numeric parameters, only allows inputs number.
 
**Screen Recording:**
![e](https://github.com/microsoft/pxt-microbit/assets/148834117/435f8974-6d67-4a4e-84dc-80470d2d935b)

**Additional context:**
1.OS: **Windows**11 **iMac** Ventura 13.6.6
2.Browser: **Edge, Chrome**
3.makecode.microbit,org version: 7.0.9
4.Microsoft MakeCode version: 10.0.21

**Comment by Ramanan0530** [comment]
I verified this bug in the latest version: 7.0.40 and it has been fixed.
