### ISSUE TITLE
[Safari & Firefox] Teacher Tools: Can input letters and characters in numeric parameters

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5652]
**Describe the bug**
Teacher Tools: Can **input letters and characters in numeric parameters**

**Steps to reproduce the behavior**
1.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval).
2.Create or open a checklist.
3.Click Add Criteria and choose **some criteria with numeric parameters.**
4.**Input letters and characters** in numeric parameters and observe.
 
**Actual behavior:**
Can input letters and characters in numeric parameters
 
**Expected behavior:**
**Cannot input any letter or character** in numeric parameters, **only allows input number**.
 
**Screen Recording:**
![allcharacters](https://github.com/microsoft/pxt-microbit/assets/148834117/1d176fc2-732e-427b-a2e6-0b5903f4a23d)

**Additional context:**
1.OS: **Windows**11 **iMac** Ventura 13.6.6
2.**Browsers: Safari, Firefox**
3.makecode.microbit,org version: 7.0.9
4.Microsoft MakeCode version: 10.0.21

**Comment by Ramanan0530** [comment]
I verified this bug in the latest version: 7.0.40 and it has been fixed.
