### ISSUE TITLE
Missing blocks in tutorials when language is German

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#5654]
Arising from support ticket https://support.microbit.org/helpdesk/tickets/74921 (private)

**Describe the bug**

When some tutorials are started with German selected, some blocks are missing.

Tested Clap Lights and Morse Chat - the LEDs blocks are missing.

**To Reproduce**
1. Select language German
2. Start a tutorial
3. Check the blocks

**Expected behavior**
The blocks should not be missing

**Screenshots**

**Clap Lights in English**

![image](https://github.com/microsoft/pxt-microbit/assets/989126/c714d633-cd8c-4bab-8bfb-bbdd77962aa0)

==============================================

**Clap Lights in German**

![image](https://github.com/microsoft/pxt-microbit/assets/989126/3dcbcc06-6bce-42d1-a5cf-fd5cb880f6ca)

**micro:bit version (please complete the following information):**

not hardware related ]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] tested macOS and Windows
 - Browser [e.g. chrome, safari] Chrome

**Comment by microbit-carlos** [comment]
Is it possible that the translation itself has accidentally removed the blocks?

**Comment by abchatra** [comment]
I can reproduce the problem.

**Comment by srietkerk** [comment]
Just for clarity, it was a problem with the translation. In German, the LED grid for the `showLEDs` had a couple of spots where there were extra columns/rows. The translation has been updated now and is fixed on live.

**Comment by martinwork** [comment]
Thanks @srietkerk, I have informed the owner of the support ticket.
