### ISSUE TITLE
Teacher Tools: Block 'Middle C' border need to be bold in 'Select Block' modal

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5657]
**Describe the bug**
Teacher Tools: **Block 'Middle C' border need to be bold** in 'Select Block' modal

**Steps to reproduce the behavior**
1.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval).
2.Create or open a checklist.
3.Click Add Criteria and _'block used count times'_.
4**.Block->Music**, **observe the border of 'Middle C'**.
 
**Actual behavior:**
**Mac:** The border is **not complete**
**Windows:** The **border of 'Middle C' is not clear.**
 
**Expected behavior:**
Should make the border of 'Middle C' bold, or change the background color.
 
**Screenshot:**
![border](https://github.com/microsoft/pxt-microbit/assets/148834117/e2fc318e-e464-45b4-a2b1-ab69c50cacd5)

**Additional context:**
1.OS: **Windows**11, **iMac** Ventura 13.6.6
2.makecode.microbit,org version: 7.0.9
3.Microsoft MakeCode version: 10.0.21

**Comment by abchatra** [comment]
P3 Won't fix.
