### ISSUE TITLE
Teacher Tools: Criteria 'block used count times' display wrong order in Results List

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5658]
**Describe the bug**
Teacher Tools: **Criteria 'block used count times' display wrong order** in Results List

**Steps to reproduce the behavior**
1.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval).
2.Open a checklist, enter Project Link or Share ID and submit.
3.Add **Criteria 'block used count times' without choosing block** and any other criteria.
4.Click **Evaluate** button and observe the results.
5.**Choose the block in criteria 'block used count times'** and **evaluate again**.
6.**Observe the order of results** list.

**Actual behavior:**
Criteria 'block used count times' **display wrong order** in Results List

**Expected behavior:**
Should display same order with Checklist.

**Screen Recording:**
![order](https://github.com/microsoft/pxt-microbit/assets/148834117/b4ab4156-b937-4631-99e0-eeb971312b52)

**Additional context:**
1.OS: Windows11, iMac Ventura 13.6.6
2.makecode.microbit,org version: 7.0.9
3.Microsoft MakeCode version: 10.0.21

**Comment by eanders-ms** [comment]
We combined these tabs into a single view.

**Comment by fionama100** [comment]
I verified this bug in the latest version: 7.0.25 and it has been fixed. These tabs have been combined into a single view.
![image](https://github.com/user-attachments/assets/a573d53f-fb41-4e18-961e-1f1fa9e189f3)
