### ISSUE TITLE
Variable rule doesn't seem to be working

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5660]
Repro - 
Add the Variable exists rule
![image](https://github.com/microsoft/pxt-microbit/assets/22108954/e1b01e77-5132-4214-803d-2d6f1fbdc13d)

Run the checker, results don't include rule output
![image](https://github.com/microsoft/pxt-microbit/assets/22108954/9c70da6f-30e4-4f20-a7e4-549728de191e)

**Comment by v-katherine** [comment]
There is **'Unable to run evaluation' error pops-up** in the right-lower corner when **evaluate 'Uses at least count variables'** criteria.
This issue also **reproduced on Mac** Safari.

**Comment by abchatra** [comment]
I cant reproduce the bug. However even if I have variables, the it says needs work.

**Comment by thsparks** [comment]
@abchatra Did you set *and use* the variables? This criteria requires both to pass.
![image](https://github.com/user-attachments/assets/d969d2bd-d357-47fd-b3ab-36217e21c762)

**Comment by abchatra** [comment]
This is fixed. Verfied.
