### ISSUE TITLE
Comments rule only seems to apply to block comments

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5661]
Repro - 
Add the Comments Exist rule
Run it against a program with a Workspace comment
Fails the rule
![image](https://github.com/microsoft/pxt-microbit/assets/22108954/b68cc581-6b40-466d-a757-095fa2ca9202)

**Comment by abchatra** [comment]
Dupe of https://github.com/microsoft/pxt-microbit/issues/5607
