### ISSUE TITLE
Beta 'is sprite touching' block blank style need to be updated

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5663]
**Describe the bug**
**Beta** _'is sprite touching'_ block **blank style** need to be updated
 
**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Create or open a project.
3.Toolbox->**Game**, observe the block _'is sprite touching'._
 
**Actual behavior:**
The style of the blank in the block is **different with live version**.
 
**Expected behavior:**
Update the blank style that keep same with live version.
 
**Screenshot:**
![block](https://github.com/microsoft/pxt-microbit/assets/148834117/7246bd78-78ce-4bdd-82e0-ae12ea949c00)

**Additional context:**
1.OS: Windows11, iMac Ventura 13.6.6
2.makecode.microbit,org version: 7.0.9
3.Microsoft MakeCode version: 10.0.21

**Comment by abchatra** [comment]
@riknoll  if intentional close the bug.

**Comment by riknoll** [comment]
not intentional

**Comment by v-katherine** [comment]
Verified this issue on the lasted makecode.microbit version: 7.0.15, it still reproduces, so I reopen it now.

**Comment by srietkerk** [comment]
I don't see a repro of this on the latest version, 7.0.35. @v-katherine, can you check beta to confirm? If it looks good to you, I can close this issue.

**Comment by fionama100** [comment]
Hi @srietkerk , I verified this bug on the latest version: 7.0.35 and it has been fixed.
![3](https://github.com/user-attachments/assets/7908fee3-4dbb-4475-af4f-22dd1d072b5d)
