### ISSUE TITLE
Cannot load the help documentation of block 'resume' and 'set audio pin enabled false'

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5664]
**Describe the bug**
**Cannot load the help documentation** of block **'resume' and 'set audio pin enabled false'**
 
Steps to reproduce the behavior
1.Navigate to https://makecode.microbit.org/beta
2.Create or open a project.
3.Toolbox->**Game more**, open the **help documentation of block 'resume'.**
4.Toolbox->**Pins**, open the **help documentation of block 'set audio pin enabled false'.**
 
**Actual behavior:**
Shows 'Oops We could not load the documentation, please check your internet connection'.
 
**Expected behavior:**
Open the help documentation correctly.
 
**Screen Recording:**
![Cannotopenhelpdoc](https://github.com/microsoft/pxt-microbit/assets/148834117/9c1861aa-c988-4cd1-89cc-9e76721104fa)

**Additional context:**
1.OS: Windows11, iMac Ventura 13.6.6
2.makecode.microbit,org version: 7.0.9
3.Microsoft MakeCode version: 10.0.21

**Comment by v-katherine** [comment]
Verified this issue on the lasted makecode.microbit version: 7.0.13, it still reproduces, so I reopen it now.

**Comment by ganicke** [comment]
Will have to wait to test again until Beta is updated.

**Comment by abchatra** [comment]
Fixed in 7.0.14

**Comment by v-katherine** [comment]
@abchatra Thanks for your information. I have verified this issue in the latest build: 7.0.15 and it has been fixed.
