### ISSUE TITLE
Missing '0' in 'serial write buffer serial read buffer 0' help documentation

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5665]
**Describe the bug**
**Missing '0'** in 'serial write buffer serial read buffer 0' **help documentation**
 
**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Create or open a project.
3.Toolbox->**Serial more**, open the **help documentation of block 'serial write buffer serial read buffer 0'.**
4.Compare the block in **Toolbox and help documentation**.
 
**Actual behavior:**
**Missing '0'** in 'serial write buffer serial read buffer 0' help documentation
 
**Expected behavior:**
Should **update the block in doc that same with in the Toolbox.**
 
**Screenshot:**
![block0](https://github.com/microsoft/pxt-microbit/assets/148834117/c4a4b6fa-55b8-4794-bc9d-0d090f79ad1e)

**Additional context:**
1.OS: Windows11, iMac Ventura 13.6.6
2.makecode.microbit,org version: 7.0.9
3.Microsoft MakeCode version: 10.0.21

**Comment by ganicke** [comment]
@abchatra, @riknoll - somehow number parm is dropped after decompile to blockly render:

````
```sig
serial.writeBuffer(serial.readBuffer(0))
```
````

![image](https://github.com/user-attachments/assets/918e0c99-4e16-453c-a096-fe6745f1a10f)

**Comment by v-katherine** [comment]
Verified this issue on the lasted makecode.microbit version: 7.0.15, it still reproduces, so I reopen it now.

**Comment by riknoll** [comment]
@v-katherine this is fixed, but you won't be able to see it because our docs pages are always tied to the live released version. The fix will show up once beta is released to live

**Comment by v-katherine** [comment]
Okay, Thanks for your information, I will track this issue and update the result once the fix show up in beta version.

**Comment by fionama100** [comment]
I have verified this bug in the latest build: 7.0.16 and it has been fixed. Close it now.
![Fixed](https://github.com/user-attachments/assets/a240de48-eda5-4aab-8acf-026dee2619dc)
