### ISSUE TITLE
Beta open blocks' help documentation in Python or JavaScript editor doesn't open a new tab

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5670]
**Describe the bug**
**Beta** open **blocks' help documentation** in **Python or JavaScript** editor **doesn't open a new tab**
 
**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Create or open **JavaScript/Python editor**.
3.Choose any block, open the block's **help documentation and observe.**
 
**Actual behavior:**
Open the **help documentation in editor not in a new tab.**
 
**Expected behavior:**
Open the help documentation **in a new tab like the behavior in Live version.**
 
**Screen Recording:**
**Beta:**
![Betahelpdoc](https://github.com/microsoft/pxt-microbit/assets/148834117/27455b90-3140-41b9-8903-92ba08c05022)

**Live:**
![Livehelpdoc](https://github.com/microsoft/pxt-microbit/assets/148834117/a68e689c-bc8c-43b1-8dc1-12dc319de7c9)

**Additional context:**
1.OS: **Windows**11, **iMac** Ventura 13.6.6
2.makecode.microbit,org version: 7.0.11
3.Microsoft MakeCode version: 10.0.23

**Comment by abchatra** [comment]
I believe beta behavior is desired.
