### ISSUE TITLE
Failed to connect when reconnect the device

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5672]
**Describe the bug**
**Failed to connect** when **reconnect the device**
 
**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Complete a tutorial and then **connect the device to computer,** the **device connected automatically**.
3.Click **Disconnect** in download options, and **still plug in the device USB**.
4.Click '**Connect the device'** in the download options and reconnect the device.
 
**Actual behavior:**
Shows **'Failed to connect' dialog**.
 
**Expected behavior:**
Reconnect the device successfully.
 
**Screen Recording:**
![connectdevice](https://github.com/microsoft/pxt-microbit/assets/148834117/4714e7bb-f9bf-4af3-8df2-945301e56158)

**Additional context:**
1.OS: **Windows**11, **iMac** Ventura 13.6.6
2.makecode.microbit,org version: 7.0.11
3.Microsoft MakeCode version: 10.0.23

**Comment by jwunderl** [comment]
Clarifying here as pr had reasoning, closing this one for now as made mild improvement to behavior but for the time being expectation is to disconnect & reconnect device before trying to pair again, which is suggested by the modal that popped up after pairing / got clicked through. This edge case may get addressed a bit more as a side effect of fixing other webusb reliability issues, though
