### ISSUE TITLE
The first time in version history of a Save a copy project is wrong

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5673]
**Describe the bug**
The **first time in version history** of a **Save a copy project** is **wrong**
 
**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Create or open a project.
3.More->Version History->Now, **click Save a copy**.
4.Back to homepage and then **open the project you saved in step3.**
5.More->Version History, **observe the first time.**
 
**Actual behavior:**
The **first time is the project in step2 created time**.
 
**Expected behavior:**
The **first time should be the Save a copy project created time**.
 
**Screen Recording:**
![versionhistorytime](https://github.com/microsoft/pxt-microbit/assets/148834117/3ca6057c-106a-4147-8b0f-ec03d0679620)

**Additional context:**
1.OS: **Windows**11, **iMac** Ventura 13.6.6
2.makecode.microbit,org version: 7.0.11
3.Microsoft MakeCode version: 10.0.23

**Comment by abchatra** [comment]
May be by design, where we want to preserve the history. @riknoll  to close if by design.

**Comment by riknoll** [comment]
by design
