### ISSUE TITLE
Version History: Didn't record the update of the workspace in Version History

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5674]
**Describe the bug**
Version History: **Didn't record the update** of the workspace in Version History
 
**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Create or open a project.
3.Add some blocks or code in workspace.
4.**More->Version History**, click the time and **observe the workspace.**
 
**Actual behavior:**
**Version History didn't record the change in the workspace**.
 
**Expected behavior:**
Version History record the changes in the workspace, the workspace matches with the chosen version.
 
**Screen Recording:**
![VersionHistory](https://github.com/microsoft/pxt-microbit/assets/148834117/eef22b63-9db6-407b-95ed-781c45a2ec6f)

**Additional context:**
1.OS: Windows11, iMac Ventura 13.6.6
2.makecode.microbit,org version: 7.0.11
3.Microsoft MakeCode version: 10.0.23

**Comment by v-katherine** [comment]
Hi @abchatra, please have a look this bug about **Version History**, I think this bug's **priority is higher**. The version didn't save the update in workspace in time. And the bug about Version History also **reproduced in Arcade (https://github.com/microsoft/pxt-arcade/issues/6312) and Minecraft Education.**

**Comment by abchatra** [comment]
Thanks @v-katherine @riknoll fyi
