### ISSUE TITLE
Can't edit Hz number in ringtone block in apps (keyboard doesn't pop up)

### ISSUE THREAD

**Issue by microbit-lucy** [microsoft/pxt-microbit#5676]
**Describe the bug**
When you use the ring tone (Hz) block it should be possible to tap the number (e.g. 262 in the example below) and type in a number. However, on a mobile device (whether in a browser or in the iOS or Android apps), the user can't edit that number - no keyboard pops up and cut/paste doesn't work either. 
<img src="https://github.com/microsoft/pxt-microbit/assets/102724242/c79d68c6-0493-4b80-bc3b-44e649b12fa1" width="50%" alt="IMG_658AD7ED7150-1">

[Note, tapping a note on the keyboard does change this number, it just can't be edited manually.] 

**To Reproduce**
1. Go to MakeCode on a mobile device - either in a Chrome browser or on the Android or iOS micro:bit app
2. Add the ring tone (Hz) block
3. Tap the number and try to change it - this isn't possible. 

**Expected behavior**
Tapping the number field in the ring tone (Hz) block, should pop up the keyboard in Android and iOS and allow the user to enter a number.

**Mobile only issue (please complete the following information):**
- MakeCode in a browser on a mobile device
- MakeCode inside the iOS or Android apps

**Additional context**

This bug is a particular problem at the moment as it prevents a number of key projects (e.g. https://microbit.org/projects/make-it-code-it/conductivity-tester/) from being completed on a mobile device. One of these projects is part of the programme in a big roll out where tablets will be used so there is some urgency to get it fixed.

**Comment by abchatra** [comment]
I have verified in iOS and this is fixed in /beat. Possible to valide?

**Comment by microbit-carlos** [comment]
Tested on an iPhone 15 with iOS 17.5 in the latest Safari and Chrome 127 and can confirm beta works.
Also on Android 13 with Chrome 127 and can confirm beta works there too.
