### ISSUE TITLE
Clicking Back button in the browser from a MakeCode project doesn't go back to project list/home page

### ISSUE THREAD

**Issue by microbit-grace** [microsoft/pxt-microbit#5678]
**Describe the bug**
Clicking Back button in the browser from a MakeCode project doesn't go back to project list/home page. 
It takes a couple clicks to go back and it doesn't go to the MakeCode homepage/project list.

**To Reproduce**
1. Go to https://makecode.microbit.org/ (homepage)
2. Create a new project or navigate to an existing project
3. Click "Back" in the browser

**Current behavior**
4. The browser remains in the same page, only the URL changes
5. Click the "Back" in the browser again
6. The browser navigates back to a page before the original navigation to the homepage in step 1. 

**Expected behavior**
Clicking "back" once from the project should navigate to the MakeCode homepage.

**Desktop:**
 - Browser: Chrome (though may not be limited to this)

**Smartphone:**
 - Device: Android (though may not be limited to this)
 - Browser: Google Chrome (though may not be limited to this)

**Comment by abchatra** [comment]
Way the website is designed, need to use Home button to go back to the home screen as it is designed as one app. Won't fix.
