### ISSUE TITLE
Undo wrong when click undo after clicking '+' in block 'play until done'

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5681]
**Describe the bug**
**Undo wrong** when click undo after clicking '+' in block 'play until done'
 
**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Create or open a project.
3.Drag _**'play until done'**_ from **Music category** into workspace.
4.**Click '+' in block of _'play until done_'.**
5.**Click 'Undo'** button and **observe.**
 
**Actual behavior:**
Undo wrong, shows incorrect blocks.
 
**Expected behavior:**
Undo successfully, back to last step.
 
**Screen Recording:**
![undotwice](https://github.com/microsoft/pxt-microbit/assets/148834117/875a9037-7fa2-44eb-a566-55b7dc1f3e89)

**Additional context:**
1.OS: Windows11, iMac Ventura 13.6.6
2.makecode.microbit,org version: 7.0.12
3.Microsoft MakeCode version: 10.0.23

**Comment by abchatra** [comment]
This is P3 won't fix.
