### ISSUE TITLE
"Sprial": There are errors when copy the code from Instructions to workspace

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5682]
**Describe the bug**
"Sprial": There are errors when copy the code from Instructions to workspace
 
**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.**Turtle->Sprial->Show Instructions.**
3.Click **JavaScript or Python to show code**.
4.**Copy and paste the code into workspace**.
 
**Actual behavior:**
There are errors.
 
**Expected behavior:**
There are no errors.
 
**Screen Recording:**
![error](https://github.com/microsoft/pxt-microbit/assets/148834117/9d62e2bc-fbec-48d0-83fc-69e03c8a5600)

**Additional context:**
1.OS: Windows11, iMac Ventura 13.6.6
2.makecode.microbit,org version: 7.0.12
3.Microsoft MakeCode version: 10.0.23

**Comment by v-katherine** [comment]
This issue also reproduced in **Turtle->Scanner**

**Comment by abchatra** [comment]
Instructions say you need to add microturtle extension. This is not a bug.
```
create a new project
click on the gearwheel menu and click Extensions
select the microturtle extension
```
