### ISSUE TITLE
Didn't import the code when import file in Extensions page

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5686]
**Describe the bug**
Didn't import the code when import file in Extensions page
 
**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Open or create a project.
3.**More…->Extensions.**
4.Click **Import File**, **choose a file and click Go ahead!**
5.**Observe the simulator and workspace.**
 
**Actual behavior:**
Simulator play the imported file but didn't import the code into the workspace.
 
**Expected behavior:**
Import the whole file into the editor, involved simulator and code.
 
**Screen Recording:**
![import](https://github.com/microsoft/pxt-microbit/assets/148834117/5954f03f-8473-4033-9c17-130778d0cb12)

**Additional context:**
1.OS: Windows11
2.Browsers: Edge & Firefox
2.makecode.microbit,org version: 7.0.12
3.Microsoft MakeCode version: 10.0.23

**Comment by abchatra** [comment]
@v-katherine this is as designed. Unless the hex has block definitions for  new blocks, only code is imported as an extension and it  is run. You can see the code in javascript explorer tab
