### ISSUE TITLE
"Clap Lights": The hint of step4 & step7 need to be updated

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5690]
**Describe the bug**
"Clap Lights": The **hint of step4 & step7** need to be updated
 
**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.**Tutorials for the new micro:bit(V2)->Clap Lights**->Block Start Tutorial.
3.Execute to **step4 and step7**, **compare the hint and actual results** in workspace.
 
**Actual behavior:**
The 'lightsOn' style is different between hint and results.
 
**Expected behavior:**
The hint displays same with actual results.

**Screenshot:** 
![style](https://github.com/microsoft/pxt-microbit/assets/148834117/16e261de-5f69-4509-bfe2-b8a589b00096)

**Additional context:**
1.OS: Windows11
2.Browsers: Edge & Firefox
2.makecode.microbit,org version: 7.0.12
3.Microsoft MakeCode version: 10.0.23

**Comment by v-katherine** [comment]
This issue about the **variables displays different style between hint and results** also reproduced in tutorial **“Cat Napping", hint of step3, step4 & step9.**

**Comment by abchatra** [comment]
@riknoll once we release, this will be automatically fixed.

**Comment by riknoll** [comment]
this won't be automatically fixed when we release. i can reproduce this, need to investigate what's going on here though.

**Comment by v-katherine** [comment]
I have verified this bug in the latest build: 7.0.15 and it has been fixed.
