### ISSUE TITLE
Doc: Building the offline app

### ISSUE THREAD

**Issue by MFHSchool** [microsoft/pxt-microbit#5693]
**Describe the solution you'd like**
As I am using a modified code for a more locked down editor, i am not able to use the available offline app.
I would like a documentation of the process to build the offline app, so that I can build my own offline app.

**Describe alternatives you've considered**
Running a local server is possible. But the WebUSB connection is a lot more instable in the browser than with the offline app.

**Comment by abchatra** [comment]
We don't support this scenario.
