### ISSUE TITLE
`textdropdown` field editor doesn't work as expected in live and broken in beta

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5695]
**Describe the bug**

**To Reproduce**
1. Go to https://makecode.com/playground#field-editors-dropdowns
2. Ensure the Dropdowns sample is loaded in the micro:bit editor
3. Drop the [say [hello]] block to the workspace and click the dropdown 
4. Dropdown generates an entry per letter instead of word
  <img width="1785" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/cfabcb59-1867-4c0e-a0c7-b50c121b737a">
5. Change the editor to micro:bit BETA
6. Drop the [say [hello]] block to the workspace
7. Click on the "hello" dropdown
8. The click acts as if the block is being dragged and cannot be "unclicked"
  <img width="1785" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/4846d4bd-5058-4c54-b46f-0873314cd6bd">

**Expected behavior**
The dropdown to show an entry per word.

**Screenshots**
N/A

**micro:bit version (please complete the following information):**
N/A

**Desktop (please complete the following information):**
N/A
**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by riknoll** [comment]
I don't think anyone actually uses this field (we certainly don't in any of our code), so i'm tempted to just remove the references to it from the docs.

@microbit-carlos do you have a scenario where you want to use this?

**Comment by microbit-carlos** [comment]
We were looking at a way to dynamically create block dropdown with an editor extension that takes an external input and automatically generates the blocks (+ a "normal" extension with additional code to run on the device), so we were looking at this, and all the other ways to generate block dropdowns. In the end we went with the "fixedInstance" method, so we don't have a direct use for this one right now.

The main question I'd have is if this method has been used by any existing extension.

**Comment by riknoll** [comment]
fixedInstance is indeed the way to go here! it's better for tree shaking too
