### ISSUE TITLE
Download using WebUSB fails to find device after putting up correct name and pairing

### ISSUE THREAD

**Issue by stevejclay** [microsoft/pxt-microbit#5696]
Using WebUSB feature in MakeCode editor fails.

Steps to reproduce the error:
1. Write a program in the MakeCode editor. 
2. Press the Download button. 
3. Go through the steps to pair to the microbit.
4. It fails at the final step with the error message "Failed to Connect. We could not find your micro:bit".

(https://github.com/microsoft/pxt-microbit/assets/64484724/fc4ce69f-cd91-4be9-b8cf-9ed137412699)

When I try again I see that the device has the word -paired next to it:
![image](https://github.com/microsoft/pxt-microbit/assets/64484724/221145a2-56ac-444a-abc5-3c58db262145)

However, it still fails, with the same error message.

The micro:bit is V.21 and has firmware 0257.
I am using Chrome version 125.0.6422.112 (Official Build) (64-bit)
The OS is Ubuntu 22.04 (Linux)

**Comment by martinwork** [comment]
@stevejclay Please check
https://support.microbit.org/en/support/solutions/articles/19000105428-webusb-troubleshooting
Especially the Linux section.

**Comment by stevejclay** [comment]
MartinThank you very much, I followed the linux instructions and it all worked. I can now setup "Download" on all the code club laptops the same way. The children in the code club will find it easier than dragging a downloaded file.Many thanksSteveOn 25 May 2024, at 23:55, Martin Williams ***@***.***> wrote:﻿
@stevejclay Please check
https://support.microbit.org/en/support/solutions/articles/19000105428-webusb-troubleshooting
Especially the Linux section.
