### ISSUE TITLE
"Command Responder": Copied JavaScript code from instruction cannot convert to python

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5698]
**Describe the bug**
"Command Responder": Copied **JavaScript code** from **instruction** that **cannot convert to python**
 
**Steps to reproduce the behavior**
 1.Navigate to  https://makecode.microbit.org/beta
 2.**Block to JavaScript->Command Responder**->Show Instructions.
 3.Copy **JavaScript Code** above 'Try it!'.
 4. **Paste the code** into workspace and **switch to Python.**
 
**Actual behavior**
Pops up error 'We are unable to convert your code to Python'.
 
**Expect behavior**
Successfully switch to Python editor

**Screen Recording:**
![revert](https://github.com/microsoft/pxt-microbit/assets/148834117/73053b21-07cb-4085-b1c4-24f90892a143)

**Additional context**
1.OS: Windows 11 Enterprise
2.Browser: Edge
3.makecode.microbit,org version: 7.0.12
4.Microsoft MakeCode version: 10.0.23

**Comment by abchatra** [comment]
This is expected. We don't have 1-1 parity with python and javascript. Sometimes we won't be able to convert to. This is one such exmaple.
