### ISSUE TITLE
C++ Cloud compiler might be down/broken

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5705]
### Description
Updating and building a C++ extension locally using `PXT_FORCE_LOCAL=1 pxt build` in the CLI works.

Building the same extension in the CLI using the cloud compiler via `pxt build` fails.
It shows the `waiting 8s for C++ build...` message multiple times and then it gives up with `abandoning C++ build`, terminating with this error:
```
error TS9043: The hex file is not available, please connect to internet and try again.
```

The thing we found odd is that in some cases, importing an extension as a C++ project into the MakeCode editor (via import of GH URL, or by drag&drop a locally built hex file) did successfully re-build the C++ code and produced a hex file.

However, creating a new project and adding the same extension using exactly the same tag, then building the new project does fail with the same `abandoning C++ build` error shown in the browser console. 

### Reproduce

This simple project is using a simple C++ extension [pxt-banana](https://github.com/carlosperate/pxt-banana) to replicate the issue:

https://makecode.microbit.org/_FtsJVkTamUDr
<img width="1707" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/663e1ebf-a208-47eb-af9c-c5e968f5db57">

### Versions

Tested with MakeCode live:
- makecode.microbit.org version:  [6.0.28](https://github.com/Microsoft/pxt-microbit/releases/tag/v6.0.28)
- Microsoft MakeCode version:  [9.0.19](https://github.com/Microsoft/pxt/releases/tag/v9.0.19)
- microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
- codal-microbit-v2 runtime version:  [v0.2.63](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.63)

And beta:
- makecode.microbit.org version:  [7.0.12](https://github.com/Microsoft/pxt-microbit/releases/tag/v7.0.12)
- Microsoft MakeCode version:  [10.0.23](https://github.com/Microsoft/pxt/releases/tag/v10.0.23)
- microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
- codal-microbit-v2 runtime version:  [v0.2.63](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.63)

**Comment by microbit-carlos** [comment]
@abchatra could somebody have a look at this please?

**Comment by abchatra** [comment]
@riknoll

**Comment by riknoll** [comment]
it's back up! sorry for the trouble!

**Comment by microbit-carlos** [comment]
Thanks everyone!
