### ISSUE TITLE
The TypeScript `control.onEvent()` `flags` argument is not passed to the DAL/CODAL event listener

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5709]
The `control.onEvent()` C++ function checks if any flag is provided, and if not it set the `EventFlags::QueueIfBusy` by default:
https://github.com/microsoft/pxt-microbit/blob/5b0d30fae81e856f98a17b7f1db60843bd438dcd/libs/core/control.cpp#L304-L307

However, the `registerWithDal()` function then ignores the `flags` argument:
https://github.com/microsoft/pxt-microbit/blob/5b0d30fae81e856f98a17b7f1db60843bd438dcd/libs/core/codal.cpp#L99-L104

So, it ultimately depends on the CODAL default beings set to `MESSAGE_BUS_LISTENER_QUEUE_IF_BUSY` via the `EVENT_LISTENER_DEFAULT_FLAGS` config:
- [codal-core/inc/core/EventModel.h#L229](https://github.com/lancaster-university/codal-core/blob/df05db9e15499bd8906618192a4d482e3836c62f/inc/core/EventModel.h#L229)
- [codal-core/inc/core/CodalConfig.h#L113](https://github.com/lancaster-university/codal-core/blob/df05db9e15499bd8906618192a4d482e3836c62f/inc/core/CodalConfig.h#L113)

**Comment by abchatra** [comment]
@microbit-carlos what is the impact of this bug?

**Comment by microbit-carlos** [comment]
We are working around it in the extension by creating a custom `onEvent` TS function that calls a custom `registerWithDal` C++ function that passes the extra argument to `uBit.messageBus.listen()`. So it's not a blocker, but I would consider this a bug in pxt-microbit, as it's only missing passing the flags argument forward.

```patch
- uBit.messageBus.listen(id, event, dispatchForeground, a); 
+ uBit.messageBus.listen(id, event, dispatchForeground, a, flags); 
```
