### ISSUE TITLE
micro:bit V2 may hang when WebUSB connected to MakeCode

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#5710]
**Describe the bug**
Arising from support ticket https://support.microbit.org/helpdesk/tickets/77229 (private)

Suppose micro:bit is connected to a single MakeCode tab open in the browser, having just downloaded a program via WebUSB.

The program may be very simple, just displaying an icon in on start (https://makecode.microbit.org/_VbkaFR833iUJ), though the scenario affected by the issue is datalogging by sending serial data to display in MakeCode via "Show data Device".

In some circumstances, micro:bit may hang (display goes and stays blank), which doesn't happen without being connected to MakeCode.

In the support ticket, @edbye reports that, with Edge 125.0.2535.79 on Windows 11:
"On the hour, or 15 past, or 30 past or 45 past, the icon will disappear (device turns off). On the Editor, the Microbit Icon on the “download” block will be seen flashing, when paired it will be steady. Pressing the Microbit reset button (to turn on) returns MIcrobit operation, however the Editor (webusb) gets confused. Subsequent attempt to download results in a hang and constant spinning trying to download. Un-plugging and re-plugging the USB cable restored correct operation to the Editor/webusb. With careful observation, at times at the cardinal points a flicker of the icon can be observed."

I cannot repeat the above problem on Windows 10 or 11 with Edge or Chrome.

However, I do find that refreshing the MakeCode webpage causes micro:bit V2.21 or V2.00  to hang about 30-50% of the time. I expect micro:bit to reset, but not hang. I suspect this might be changed behaviour - I think it didn't happen when I briefly tried Chrome 123 before it upgraded itself.

Can anyone reproduce the 15 minute clock-time synchronised glitch? How can we track down the trigger?

**To Reproduce**
1. Set computer sleep time to several hours
2. Download https://makecode.microbit.org/_VbkaFR833iUJ via WebUSB to micro:bit V2.
3. Leave the MakeCode tab open
4. Leave the computer untouched
5. Wait for up to an hour or so, observing 15 minute intervals
6. See error

**Expected behavior**
micro:bit does not hang

**micro:bit version (please complete the following information):**

micro:bit V2.21 (firmware 0257)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Edge (Version 125.0.2535.79)

**Comment by brian-forwardedu** [comment]
We're experiencing a very similar issue to this one.  See #5734

**Comment by jwunderl** [comment]
Improvements made but closing this issue in favor of https://github.com/microsoft/pxt-microbit/issues/5734 as they are the same.
