### ISSUE TITLE
"Import": There is no alert pops up when click "Go ahead! " without choosing file

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5714]
**Describe the bug**
"Import": There is no alert pops up when click "Go ahead!" without choosing file
 
Steps to reproduce the behavior
 1.Navigate to https://makecode.microbit.org/beta.
 2. Click Import button.
 3. Click Import file card.
 4. Click 'Go ahead!' without choosing any file and observe
 
**Actual behavior:** 
Never pops alert when you click 'Go ahead!' without importing file.

**Expect behavior:**
Successfully pops up alert when you click 'Go ahead!' without importing file.

**Screen Recording:**
![alert](https://github.com/microsoft/pxt-microbit/assets/148834117/1a943aee-89aa-490b-bbd7-886a27859405)

**Additional context**
1.OS: Windows 11 Enterprise
2.Browser: Chrome
3.makecode.microbit,org version: 7.0.13
4.Microsoft MakeCode version: 10.0.23

**Comment by abchatra** [comment]
P3 won't fix.
