### ISSUE TITLE
Some sections are missing in Portugal & Polski

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5716]
**Describe the bug**
Some sections are missing in Portugal & Polski
 
**Steps to reproduce the behavior**
 1.Navigate to https://makecode.microbit.org/beta
 2. Switch language to **Portugal.**
 4. Move to **Course and Science Experiment sections** and **compare with English home page**.
 
**Actual behavior**
Just 2 blank image cards in Course section, Science Experiment section is missing.
 
**Expect behavior**
No section is missing when switch language.

**Screenshot:**
![Portugal](https://github.com/microsoft/pxt-microbit/assets/148834117/2d8830f0-9d1e-4b04-bce3-a62ae878c044)

**Additional context**
1.OS: Windows11, iPad 8th 17.5.1
2.Browser: Chrome, Safari
3.makecode.microbit,org version: 7.0.13
4.Microsoft MakeCode version: 10.0.23

**Comment by v-katherine** [comment]
This bug also reproduced in **Polski language** in below sections: 
**Fashion** section missing
**Jacdac** section only have 1 cards, others missing
 **Microcode for the new micro: bit(V2)** section missing

**Comment by abchatra** [comment]
@ganicke documentation issue or product issue?

**Comment by ganicke** [comment]
My guess is that the json embedded in the markdown (in Crowdin) is goofed up by the translators for those languages.

**Comment by ganicke** [comment]
There was some invalid json in the course cards for these two languages. The fixes are here:

https://crowdin.com/editor/makecode/1887/en-pl?view=comfortable&filter=basic&value=0
https://crowdin.com/editor/makecode/1887/en-pt?view=comfortable&filter=basic&value=0

Also, it seems that `./docs/courses.md` is not current with GitHub since the "First Lessons" card is not in the Crowdin source.

**Comment by v-katherine** [comment]
Verified this issue on the lasted makecode.microbit version: 7.0.13, it still reproduces, so I reopen it now.

**Comment by ganicke** [comment]
@v-katherine - please check again. The missing cards should show up now in 7.0.15. Thanks.

**Comment by v-katherine** [comment]
Hi @ganicke, I have verified this bug, and it still reproduces in the latest build makecode microbit.org version: 7.0.15.
![image](https://github.com/user-attachments/assets/b940c5de-59ab-4af8-b23f-5a12b75350de)

**Comment by ganicke** [comment]
@abchatra, @v-katherine - unfortunately, there are multiple, unrelated bugs in this issue. I've fixed the translation related errors that prevented the missing cards from showing in Polish and Portuguese. However, we are still seeing the problem that the gallery files are not updating to Crowdin with the minor releases. Is there some rule that excludes their upload (being a home screen item)? In the instance shown with the comment above, there is a new card section in [./docs/courses.md](https://github.com/microsoft/pxt-microbit/blob/master/docs/courses.md) that isn't yet reflected in Crowdin causing a missing section ("First Lessons").

Compare:
----
GitHub: https://github.com/microsoft/pxt-microbit/blob/master/docs/courses.md

Crowdin: https://crowdin.com/editor/makecode/1887/en-en?view=comfortable&filter=basic&value=0

**Comment by abchatra** [comment]
@ganicke thanks for letting me know. We will investigate.

**Comment by abchatra** [comment]
@jwunderl it is likely because there is major version change between live and beta. See if porting the changes to live major branch will fix the issue.

**Comment by jwunderl** [comment]
@ganicke crowdin updated properly after https://github.com/microsoft/pxt-microbit/pull/5807. There's a translation issue that popped up as well after the changes went through https://github.com/microsoft/pxt-microbit/issues/5812 in https://crowdin.com/editor/makecode/1887/en-pl?view=comfortable&filter=basic&value=0#q=networking , i'll fix that on crowdin side real quick though.

**Comment by fionama100** [comment]
I verified this bug in the latest version: 7.0.22. Most of sections have been fixed and they can be display. 
But the **Science Experiment** section still is missing after switching to **Portugal** language. So I reopen this bug, please have a look it, thank you.
![Science Experiment section is missing](https://github.com/user-attachments/assets/8427f74e-5e3d-429a-8a98-d1580ed0c8c7)

**Comment by jwunderl** [comment]
courses category; typo in translation, replaced 'j' with a space in .jpg
![image](https://github.com/user-attachments/assets/05ba331f-d1d7-4905-80e6-48740c5dcc73)

science experiment card list was broken because the translation removed a [, making the json invalid.

both fixed, should propagate to live in ~48 hours

**Comment by fionama100** [comment]
Hi@jwunderl, the previous two issues still reproduced in the latest: 7.0.34. Please have a look it if you have free time, thank you.

**Comment by jwunderl** [comment]
hm, it propagated to https://github.com/microsoft/pxt-translations/blob/master/dist/pt-PT/microbit/docs/courses.md a week ago,  but the markdown doesn't seem to be synced 
![image](https://github.com/user-attachments/assets/842a2a6f-dd93-45b8-a665-3e49bdd075ca)
 @thsparks any ideas if the syncing has been running?

**Comment by thsparks** [comment]
Filed support ticket with azure yesterday. Despite a min count of 1, it's been running on 0 workers for 100% of the time, so it hasn't been running. Will update once I learn more.

**Comment by thsparks** [comment]
The sync ran last night, so this should hopefully be resolved now.

**Comment by Ramanan0530** [comment]
I verified this bug in the latest version: 7.0.38 and it has been fixed.
