### ISSUE TITLE
Cannot reopen Project Settings after opening Edit Settings As text

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5718]
**Describe the bug**
Cannot reopen Project Settings after opening Edit Settings As text
 
**Steps to reproduce the behavior**
1.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval)
2.Create or open a project.
3.Open **Project Settings** under More menu.
4.Click **Edit Settings As text**.
5.Click the **Project Settings** and **observe**.
 
**Actual behavior:**
There is **no response when click Project Settings in Edit Settings As text page**.
 
**Expected behavior:**
Can reopen Project Settings page correctly.
 
**Screen Recording:**
![projectsettings](https://github.com/microsoft/pxt-microbit/assets/148834117/9bb8fa8f-4daf-47fa-ac0d-c27c3141db9b)

**Additional context:**
1.OS: Windows11, iPad 8th 17.5.1
2.Browsers: Edge, Safari
3.makecode.microbit,org version: 7.0.13
4.Microsoft MakeCode version: 10.0.23

**Comment by abchatra** [comment]
P3 won't fix.
