### ISSUE TITLE
'Hot Potato': The hint of step6 didn't match with the instruction

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5720]
**Describe the bug**
'Hot Potato': The hint of step6 didn't match with the instruction
 
Steps to reproduce the behavior
1.Navigate to  https://makecode.microbit.org/beta
2. Games>**Hot Potato**>Start **Block** Tutorial.
3. Go to step 6, compare the instruction with hint.
 
**Actual behavior**
There is no 'Pause' block in the instructions, but it is in the hints.

**Expect behavior**
The hints matched with the instruction.

**Screenshot:**
![pauseblock](https://github.com/microsoft/pxt-microbit/assets/148834117/ac32b5fa-83c4-4bb6-b6cb-51a4faa2005c)

**Additional context:**
1.OS: Windows 11, iPad 8th 17.5.1
2.makecode.microbit,org version: 7.0.4
3.Microsoft MakeCode version: 10.0.11

**Comment by v-katherine** [comment]
This issue also reproduced in the **step3** of **Games->Tug of LED**->**Block, Python and JavaScript** Tutorials.

**Comment by ganicke** [comment]
There is no **pause** in the "Tug of LED" tutorial.

**Comment by v-katherine** [comment]
Verified this bug was **fixed.**
![image](https://github.com/user-attachments/assets/bf686fbb-c7a5-43fb-aec7-c0255c6a9342)
