### ISSUE TITLE
Cannot load the project when drag the image into the editor

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5729]
**Describe the bug**
Cannot load the project when drag the image into the editor
 
**Steps to reproduce the behavior**
1.Navigate to [Micro:bit](https://makecode.microbit.org/beta#)
2.Open or create a project in the editor.
3.**Take Screenshot.**
4.Create a **new project** and **drag the screenshot in step3 to the editor.**
 
**Actual behavior:**
Cannot load the project, **shows 'Oops, don't know how to load this file!'**
 
**Expected behavior:**
Load the project in editor as the screenshot.
 
**Screen Recording:**
![cannotload](https://github.com/user-attachments/assets/ccb10fdc-a8b2-4a48-b84f-965148cd1d13)

**Additional context:**
1.OS: Windows11
2.Browsers: Chrome, Edge
3.makecode.microbit,org version: 7.0.13
4.Microsoft MakeCode version: 10.0.23

**Comment by v-katherine** [comment]
Hi @abchatra , please have a look this bug about **cannot load the project** by dragging a image into the editor, it's **worked well in [Arcade beta version](https://arcade.makecode.com/beta).**

**Comment by abchatra** [comment]
This is as expected in microbit. The image doesn't contain the programs in micro:bit. It is just the image. This is different from arcade
