### ISSUE TITLE
Font and font size in the `DigitalPin`/`AnalogPin` dropdrown has been changed in beta

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5730]
Maybe it was introduced in the blockly update? Mostly wanted to check if it was done or purpose, and if so, maybe suggest we reduce the font size slightly or increase the dropdown widget width so that the analog pin `(write only)` options don't overflow to 3 lines?

This also affects the `DigitalPin`, but as there isn't long strings there it doesn't look change the shape of the dropdown that much.
Might be worth checking if other blocks with a similar dropdown widget are affected?

| v6 | v7.0.12 * |
|--------|--------|
| <img width="99%" alt="image" src="https://github.com/user-attachments/assets/123763b6-d9da-42bd-9962-d3aabbe09f4a"> | <img width="99%" alt="image" src="https://github.com/user-attachments/assets/b7c5c2a7-94c0-475d-bd1d-3db0beea14bd"> | 

*Using v7.0.12 as it was the last version before the pin changes from https://github.com/microsoft/pxt-microbit/pull/5700.

**Comment by abchatra** [comment]
V6 looks better to me. @riknoll let me know if this is hard to fix.
