### ISSUE TITLE
Block duplication glitch

### ISSUE THREAD

**Issue by JustablockCode** [microsoft/pxt-microbit#5732]
**Describe the bug**
When I created code with button a+b I wanted to duplicate it but my code just how can I say... disconnected? But after I refreshed page blocks came back to normal.

**To Reproduce**
1. Go to editor
2. Create code with button a+b
3. Duplicate it.
4. Refresh page after saving to make block back to normal.

**Screenshots**
![image](https://github.com/user-attachments/assets/1ff510b5-5c3d-49f6-be95-44b4df3cff0f) 
![image](https://github.com/user-attachments/assets/ad972f32-fe78-4b32-8bfa-4546c9180763)
![image](https://github.com/user-attachments/assets/bc7705a4-4af2-41d9-a8d3-f2e5125568e3)

**Desktop:**
 - OS: Windows 11 Home
 - Browser: Chrome
 - Version: 126.0.6478.183(Latest Chrome Version)

**Comment by JustablockCode** [comment]
also when i move this strange block it also moves the disconnected part

https://github.com/user-attachments/assets/bea05fbd-2ce4-4b8e-83ba-61e2b9722329

**Comment by abchatra** [comment]
@JustablockCode  this doesn't reproduce for me. Can you please share your program if you are able to reproduce?
