### ISSUE TITLE
Some cards image has missing in Polski

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5744]
**Describe the bug**
Some cards image has missing in Polski
 
**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2. Switch language to Polski.
3. Move to deep drive section and compare with English home page.
 
**Actual behavior**
There are no images for **'GitHub**' and **'Custom blocks'** cards in Polski language.

**Expect behavior**
The card shows correctly.

**Screenshot:**
![image](https://github.com/user-attachments/assets/3e601b32-c2db-402a-8a3a-3a36cf46d834)

**Additional context**
1.OS: Windows 11, iMac Ventura
2.makecode.microbit,org version: 7.0.13
3.Microsoft MakeCode version: 10.0.23

**Comment by abchatra** [comment]
@ganicke  again a documentation issue or product?

**Comment by ganicke** [comment]
Paths for some card images were inadvertently translated. The fixes are here:

https://crowdin.com/editor/makecode/10328/en-pl?view=comfortable&filter=basic&value=0
