### ISSUE TITLE
Allow simulator extensions to know the current language for translations

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microsoft/pxt-microbit#5746]
**Is your feature request related to a problem? Please describe.**

The Foundation would like to ship a simulator extension alongside our machine learning tool work so that users can trigger ML events in the sim.

We've modelled our prototype on the jacdac simulator extension.

So far as I can tell there's no way to get at the language configured in MakeCode and therefore use suitable translations.

This issue also affects editor extensions with the embedded iframe accessible from the extension's toolbox section. It would be good for there to be a consistent solution for both extension types.

**Describe the solution you'd like**
Language is communicated to the extension on load and when it changes if the extension isn't reloaded at that point.

This could be a URL parameter or some postMessage-based messaging.

CC @jaustin @abchatra

**Comment by jaustin** [comment]
@pelikhan, @abchatra thought that this might already be done? Do you know the way to translate simulator extensions?

**Comment by microbit-matt-hillsdon** [comment]
I had a look and can't see how this can be done right now so I've open a PR. But totally possible I missed something so please let me know.
