### ISSUE TITLE
"Reset" the MakeCode editor does not work in beta

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5758]
**Describe the bug**
Using the reset functionality in beta doesn't work.

**To Reproduce**
1. Go to https://makecode.microbit.org/beta
2. Click on the cog > Reset
3. Editor reloads and the existing projects are still there 

**Expected behavior**
The editor projects to be deleted

**Screenshots**

https://github.com/user-attachments/assets/3013c789-2885-4bc1-a233-344474f413f8

**micro:bit version (please complete the following information):**

N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 126

**Smartphone (please complete the following information):**
N/A

**Additional context**

makecode.microbit.org version:  [7.0.13](https://github.com/Microsoft/pxt-microbit/releases/tag/v7.0.13)
Microsoft MakeCode version:  [10.0.23](https://github.com/Microsoft/pxt/releases/tag/v10.0.23)
microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
codal-microbit-v2 runtime version:  [v0.2.63](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.63)

**Comment by abchatra** [comment]
I can reproduce this problem.
