### ISSUE TITLE
Teacher Tools: The shape of show leds can be changed arbitrarily and the breakpoint can be added when the project loaded in read-only mode.

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5759]
**Describe the bug:** 
Teacher Tools: The shape of show leds can be changed arbitrarily and the breakpoint can be added when the project loaded in read-only mode.

**Steps to reproduce the behavior:**
1.Navigate to [MakeCode Teacher Tool (microbit.org)](https://makecode.microbit.org/beta--eval)
2.Enter the project (with **show leds**) link and submit.
3.Try to change the shape for the **show leds** in Teacher Tools.
4.Click **Toggle debug mode** in Teacher Tools.
5. Try to add the breakpoint for the project.
 
**Actual behavior:**
Step 3: The shape of show leds can be changed arbitrarily.
Step 5: The breakpoint can be added successfully.

**Expect behavior:**
Cannot edit the project, the project loaded in read-only mode. 

**Screen Recording:**
![Actual Result](https://github.com/user-attachments/assets/dbba5efb-2999-4daa-9e74-95f921b7a610)

**Additional context:**
1.OS: Windows11 & Mac
2.makecode.microbit,org version: 7.0.9
3.Microsoft MakeCode version: 10.0.23

**Comment by thsparks** [comment]
Not specific to teacher tool, I think this is just a bug with our read-only mode.

**Comment by thsparks** [comment]
@riknoll If you have time, I thought you might have context on this one. Seems to affect readonly modes in general (like debug), not just teacher tool. Feel free to assign back to me if I'm wrong!

**Comment by riknoll** [comment]
question: should we allow debug mode in a readonly editor? we allow the simulator to run. also, i don't think it actually causes any issues with editing the program

**Comment by thsparks** [comment]
I think debugging in readonly is potentially useful (though likely not a very common scenario). I would say it's worth supporting if it isn't too much extra work.

But I think the main issue I took away from this bug was that we can change the LEDs in the "Show LEDs" block even in readonly mode. Maybe we should separate the issue into two?

**Comment by riknoll** [comment]
yeah, lets separate them

**Comment by thsparks** [comment]
After our conversation in Stand-Up, we've decided to allow debug mode & breakpoints in readonly and it looks like https://github.com/microsoft/pxt/pull/10105#event-13935934249 fixes the "Show LED" issue, so I think we can just close this one now.

**Comment by fionama100** [comment]
I verified the latest version:7.0.25. The "Show LED" issue has been fixed and it can't be edited now. The breakpoint can be added successfully is expected result.
