### ISSUE TITLE
Approved extension has been moved or the GH org has been renamed

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5760]
Found via CI running the `testghpkgs` pxt command:
https://github.com/microsoft/pxt-microbit/actions/runs/10153131737/job/28075895576

For the extension `e-radionicacom/pxt-wifi`:
```
e-radionicacom/pxt-wifi
  release: v1.1.0
github proxy error: Bad HTTP status code: 404 at https://makecode.com/api/gh/e-radionicacom/pxt-wifi/v1.1.0/text; message: {"message":"repo info response: 301"}
error: https://github.com/e-radionicacom/pxt-wifi build error
```

The log generated by `pxt testghpkgs ` also provide this info:

```
Bad HTTP status code: 301 at https://api.github.com/repos/e-radionicacom/pxt-wifi/git/refs/heads/v1.1.0?rnd=0.5133494254264042; message: {"message":"Moved Permanently","url":"https://api.github.com/repositories/179577166/git/refs/heads/v1.1.0?rnd=0.5133494254264042","documentation_url":"https://docs.github.com/rest/guides/best-practices-for-using-the-rest-api#follow-redirects"}
```

Trying to navigate to https://github.com/e-radionicacom/pxt-wifi does indeed redirect to https://github.com/SolderedElectronics/pxt-wifi, so it's likely the `e-radionicacom` GH org has been renamed to `SolderedElectronics` or the repo has been moved.

The original PR that added this extension:
- https://github.com/microsoft/pxt-microbit/pull/2026

**Comment by microbit-carlos** [comment]
Trying to add the extension in MakeCode, but it doesn't appear in the extension gallery.
It should have this icon:
https://github.com/SolderedElectronics/pxt-wifi/blob/master/icon.png

![](https://github.com/SolderedElectronics/pxt-wifi/raw/master/icon.png)

But it's not there:
<img width="1357" alt="image" src="https://github.com/user-attachments/assets/8a2434b2-f607-4c4b-973c-0daedf85f883">

**Comment by abchatra** [comment]
Fixed. .
