### ISSUE TITLE
Reinstate sparkfun/pxt-gamer-bit extension as V2 compatible

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5764]
Currently the `sparkfun/pxt-gamer-bit` approved extension is marked a V1-only:

https://github.com/microsoft/pxt-microbit/blob/bd4bda19f33ba30ea61e3620c8fa069b8306d07e/targetconfig.json#L94-L97

So, when it is loaded in the MakeCode and flashed on a micro:bit, the error code 927 scrolls on the display.

I can confirm this builds locally, and it also builds succesfully in the ci `testghpkgs` workflow:
https://github.com/microsoft/pxt-microbit/actions/runs/10153131737/job/28075895576

Looking at this issue in the extension repo, it should be working with V2:
- https://github.com/sparkfun/pxt-gamer-bit/issues/5#issuecomment-2034793178

And SparkFun has been providing a workaround by providing a hex with the extension and asking users to load that hex into MakeCode: https://learn.sparkfun.com/tutorials/microarcade-kit-experiment-guide/troubleshooting-the-extension

@loricrotser, just to double check, could you confirm that this accessory and extension is working in micro:bit V2?
Are there any other extensions working in V2 that needed the workaround linked above?

**Comment by abchatra** [comment]
@loricrotser if you confirm we will enable this for v2.

**Comment by loricrotser** [comment]
Confirmed. This works with V2.
