### ISSUE TITLE
Is the `packages.upgrades` section in `targetconfig.json` used? Settings don't seem to be applied

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5765]
For example, the `sparkfun/pxt-gator-particle` extension is present in `packages.approvedRepoLib` already contains an "upgrades" section:
https://github.com/microsoft/pxt-microbit/blob/87593b18684a8978a528a68aadb7e3fd8d8cd37c/targetconfig.json#L223-L226

And the extension also has an entry in `packages.upgrades` (further down the file), which should make this extension micro:bit V1-only:
https://github.com/microsoft/pxt-microbit/blob/87593b18684a8978a528a68aadb7e3fd8d8cd37c/targetconfig.json#L495

However, loading the extension in MakeCode and flashing the programme in a micro:bit V2 does work (so, it does **not** throw the 927 panic code): https://makecode.microbit.org/_bAFRzR83wDMe

So, the `dv:mbcodal` upgrade from `packages.upgrades` is not being enforced (which in this case it's a good thing, but probably not the expected thing?).

Is it possible the `packages.upgrades` section in targetconfig.json is no longer needed, since these upgrades can already be included in `packages.approvedRepoLib`?
Or is there still a reason to keep `packages.upgrades`?

Either way, if the section will be kept, some of the entries in `packages.upgrades` have contradictory settings than those listed in  `packages.approvedRepoLib`.

The "upgrades" inside `packages.approvedRepoLib` was introduced in this PR, maybe @jwunderl knows the answer?
- https://github.com/microsoft/pxt-microbit/pull/4677

**Comment by martinwork** [comment]
@microbit-carlos I think upgrades is no longer used
https://github.com/microsoft/pxt-microbit/issues/4926#issuecomment-1435740685
