### ISSUE TITLE
Is the cloud C++ compiler down again?

### ISSUE THREAD

**Issue by ggstephenlau** [microsoft/pxt-microbit#5772]
I find that closed issues https://github.com/microsoft/pxt-microbit/issues/5353 and https://github.com/microsoft/pxt-microbit/issues/5594 happens again

when I compile the extension, I have got the following,

<img width="700" alt="Screenshot 2024-08-01 at 12 33 40 PM" src="https://github.com/user-attachments/assets/134673b8-9050-4d16-95e5-6135b36d8cb8">

Could you help on this?
Thank you very much.

**Comment by ggstephenlau** [comment]
After idle for 2 hours, I could compile the extension again.
Thank you very much.

**Comment by THEb0nny** [comment]
This problem also started about 10 hours ago, but now I was finally able to assemble it after several attempts.

**Comment by riknoll** [comment]
i'll investigate
