### ISSUE TITLE
All the blocks can't be deleted when deleting all the blocks for the project with at least 2 blocks separately.

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5774]
**Describe the bug:** All the blocks can't be deleted when deleting all the blocks for the project with at least 2 blocks separately.

**Steps to reproduce the behavior:**
1.Navigate to https://makecode.microbit.org/beta
2.Create a Blocks project with at least 2 blocks separately.
3.Right-click on workspace and choose **Delete All Blocks**
4.Click **Yes**.
5. Observe the **Workspace**.
 
**Actual behavior:**
Step 3: There are some blocks in the **Workspace**.

**Expect behavior:**
All the blocks should be deleted in the **Workspace**.

**Screen Recording:**
![noresponding](https://github.com/user-attachments/assets/6131805c-f4c6-4c7b-b17e-c63f06f5d294)

**Additional context:**
1.OS: Windows, Mac
2.Browser: Firefox, Chrome, Edge and Safari.
3.makecode.microbit,org version: 7.0.15
4.Microsoft MakeCode version: 10.2.4

**Comment by v-katherine** [comment]
I have verified this bug, and it still reproduced in the latest build makecode microbit.org version: 7.0.15, so I reopen this bug. Will close this bug once the bug was not reproduced in the latest build.

**Comment by fionama100** [comment]
Verified this bug on the lasted version: 7.0.16 and it has been fixed. Close it now.
