### ISSUE TITLE
"Infection": Copied JavaScript code from instruction that cannot convert to python

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5778]
**Describe the bug**
"Infection": Copied JavaScript code from instruction that cannot convert to python
 
**Steps to reproduce the behavior**
 1.Navigate to https://makecode.microbit.org/beta
 
 2.**Radio Games**->**Infection**->**Show Instructions**.
 
 3.Copy JavaScript Code
 
 4. Paste the code into workspace and **Switch to Python**
 
**Actual behavior**
Pop Error 'We are unable to convert your code to Python'.
 
**Expect behavior**
Successfully switch to Python editor

**Screen Recording:**
![Error](https://github.com/user-attachments/assets/e55936fe-ff5f-4333-a245-6cb93845a11b)

**Additional context**
1.OS: Windows 11 Enterprise
2.Browser: Edge, Firefox, Chrome
3.makecode.microbit,org version: 7.0.15
4.Microsoft MakeCode version: 10.2.4

**Comment by abchatra** [comment]
Expected, not all the javascript will convert to python
