### ISSUE TITLE
“Radio Bridge: Comments Not in the Same Position in Block Editor When Switching to Python/JavaScript

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5780]
Describe the bug
“Radio Bridge: Comments Not in the Same Position in Block Editor When Switching to Python/JavaScript
 
**Steps to reproduce the behavior**
 1.Navigate to https://makecode.microbit.org/beta
 
 2.**Tools** ->**Radio Bridge**->**Open Example**
 
 3. **Switch Editor** -> **Python/JavaScript** ->back to Block
 
 4. Observe the **Comment**
 
**Actual behavior**
The comment underlaying behind the 'On start' block
 
**Expect behavior**
Successfully comment stay in the same position

**Screen Recording:**
![Comment](https://github.com/user-attachments/assets/4e4c7d9d-14f5-4c2b-a2e7-fdb48cc59ddc)

**Additional context**
1.OS: Windows 11 Enterprise
2.Browser: Edge, Firefox, Chrome
3.makecode.microbit,org version: 7.0.15
4.Microsoft MakeCode version: 10.2.4

**Comment by fionama100** [comment]
I have verified this bug in the latest build: 7.0.19 and it has been fixed.
