### ISSUE TITLE
Melody field editor shadow block doesn't copy or replace correctly

### ISSUE THREAD

**Issue by kimprice** [microsoft/pxt-microbit#5785]
**Describe the bug**
When grabbing the melody editor shadow block, instead of copying, it grabs the current shadow block and leaves an empty shadow block behind. When trying to put the shadow block back, it doesn't connect to the block.

**To Reproduce**
1. Go to https://makecode.microbit.org/beta#editor
2. Drag out melody block.
3. Create a melody
4. Drag out the shadow block
5. See that it leaves behind an empty shadow block
6. Try to put the shadow block back on the block.
7. See that the block doesn't accept the shadow block.

**Screenshots**
![melodyShadow](https://github.com/user-attachments/assets/7a57d934-9f02-4335-9035-6767716994a7)

**Comment by kimprice** [comment]
The same behavior happens with the sound effect editor.

**Comment by microbit-carlos** [comment]
I was about to report this as well for the sound effect editor. Video showing the issue:

https://github.com/user-attachments/assets/a75e9018-c591-4c57-ae9e-69cad8290ead

Beta editor versions:

makecode.microbit.org version:  [7.0.15](https://github.com/Microsoft/pxt-microbit/releases/tag/v7.0.15)
Microsoft MakeCode version:  [10.2.4](https://github.com/Microsoft/pxt/releases/tag/v10.2.4)
microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
codal-microbit-v2 runtime version:  [v0.2.67](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.67)
