### ISSUE TITLE
Front End Feature Flag for Copilot Eval

### ISSUE THREAD

**Issue by thsparks** [microsoft/pxt-microbit#5790]
Setup a feature flag in target config to show/hide the "Ask Copilot" option in teacher tool.

**Comment by abchatra** [comment]
Also change "Ask Copilot"

**Comment by thsparks** [comment]
@abchatra It just occurred to me, the catalog of available criteria is already stored in docs, so we can remove the "Ask AI" criteria option with a simple docs change. With that in mind, I think an additional front-end feature flag in target config would be redundant. Okay to close this?

**Comment by abchatra** [comment]
Sounds good.
