### ISSUE TITLE
The blocks underlaying behind another blocks when switch back block editor from JavaScript/Python

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5795]
**Describe the bug:**
“Writing Functions": Blocks underlaying behind with another block when switch back block from JavaScript/Python

**Steps to reproduce the behavior:**
 1. Navigate to https://makecode.microbit.org/beta
 2. **Block to JavaScript** ->**Writing Function**->**Show Instruction**
 3. Copy the fourth JavaScript/Python code.
 4. Paste the code in the workplace and **Switch back block** from **JavaScript**

**Actual behavior:**
The blocks underlaying behind another blocks when switch back block editor from JavaScript/Python

**Expect behavior:**
The block shouldn't be underlaying with each other blocks.

**Screenshot:**
![Java error](https://github.com/user-attachments/assets/a4e6456a-6f8b-4bbe-bccc-7ede04badebc)

**Additional context**
1.OS: Windows 11, MAC
2.Browser: Edge, Firefox, Chrome, Safari
3.makecode.microbit,org version: 7.0.15
4.Microsoft MakeCode version: 10.2.4

**Comment by abchatra** [comment]
Decompiler seems to overlap blocks

**Comment by fionama100** [comment]
I verified this bug in the latest version: 7.0.20 and it has been fixed.
