### ISSUE TITLE
Audio recording length went from 4.5 seconds to 1.3 seconds in beta

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5796]
This simple programme measures how long we can record audio until hitting the default limit:

<img width="805" alt="image" src="https://github.com/user-attachments/assets/97280be2-8e56-4395-8eea-4de60b04e73d">

```ts
let t = 0
input.onButtonPressed(Button.A, function () {
    t = input.runningTime()
    record.startRecording(record.BlockingState.Blocking)
    basic.showNumber(input.runningTime() - t)
})
input.onButtonPressed(Button.B, function () {
    record.playAudio(record.BlockingState.Blocking)
})
```

On MakeCode live it records around 4.5 seconds of audio: [microbit-recording-live.hex.zip](https://github.com/user-attachments/files/16510401/microbit-recording-live.hex.zip)
- makecode.microbit.org version:  [6.0.28](https://github.com/Microsoft/pxt-microbit/releases/tag/v6.0.28)
- Microsoft MakeCode version:  [9.0.19](https://github.com/Microsoft/pxt/releases/tag/v9.0.19).
- microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6).
- codal-microbit-v2 runtime version:  [v0.2.63](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.63)

<br>

On MakeCode beta less than 1.5 seconds: [microbit-recording-beta.hex.zip](https://github.com/user-attachments/files/16510406/microbit-recording-beta.hex.zip)
- makecode.microbit.org version:  [7.0.15](https://github.com/Microsoft/pxt-microbit/releases/tag/v7.0.15)
- Microsoft MakeCode version:  [10.2.4](https://github.com/Microsoft/pxt/releases/tag/v10.2.4)
- microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
- codal-microbit-v2 runtime version:  [v0.2.67](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.67)

**Comment by riknoll** [comment]
is this on hardware or in the simulator?

**Comment by abchatra** [comment]
@carlosperate is this on hardware? Can CODAL update be the reason if on hardware?

**Comment by microbit-carlos** [comment]
This difference is on hardware.

It could be CODAL, but I can't think of something specific in the v0.2.63 to v0.2.67 transition that could cause this.
We are using v0.2.67 in MicroPython and we don't have the same memory limitation (although MicroPython is using a lower level API).

The `CODAL_DEFAULT_STREAM_RECORDING_MAX_LENGTH` in `StreamRecording` is still set to 50K https://github.com/lancaster-university/codal-core/blob/509086cc8590465041b15493ab52b56e7071c110/inc/streams/StreamRecording.h#L9, which should result in the 4.5 seconds we see in MakeCode v6.

**Comment by microbit-carlos** [comment]
I've created a branch with MakeCode [v6.0.28](https://github.com/Microsoft/pxt-microbit/releases/tag/v6.0.28) and CODAL v0.2.67 (latest).
The [CI](https://github.com/microsoft/pxt-microbit/actions/runs/10266714021) has created this test deployment:
- https://makecode.microbit.org/app/f2719e82c11f4bff59584e719b2edbf1217bcc33-86a5d0727c

On initial test it looks like it yields similar results to MakeCode v7 with the same latest CODAL.
So it looks related to the CODAL update.

I've pushed branches with the in-between CODAL versions to see if we can narrow it down, but there has been several issues:
- v0.2.63: CI builds correctly
    - https://makecode.microbit.org/app/ebe1449535c86e6a8cb04ae0c8c4b47882de0c5f-1bead1a6cb
    - ~4.5s recording time
- There isn't a v0.2.64 tag 
- v0.2.65: CI builds successfully
    - https://makecode.microbit.org/app/134e1a256376e01e23911f3bdb4e7da337927e6d-abdab27977
    - However, when when trying to compile recording code the cloud compiler returns an error
    - https://makecode.com/compile/22eb424d1dae57c78cd26a2773e564283811415c34a7e88e13fcc06e846a62f8.json
    - https://makecode.com/compile/22eb424d1dae57c78cd26a2773e564283811415c34a7e88e13fcc06e846a62f8.log
- v0.2.66: CI doesn't build
    - Build output is not very useful, the cloud compiler results in "504.0 GatewayTimeout"
    - CI job: https://github.com/microsoft/pxt-microbit/actions/runs/10282431056/job/28454622812
- v0.2.67: CI builds correctly
    - https://makecode.microbit.org/app/f2719e82c11f4bff59584e719b2edbf1217bcc33-86a5d0727c
    - ~1.3s recording time

**Comment by microbit-carlos** [comment]
I've tried building locally the v0.2.66 branch and that worked: https://github.com/microsoft/pxt-microbit/commit/86cd987df1a4c53ad9287a2b13261041915cc539

Using `pxt buildtarget --local` and `pxt buildtarget --cloud`  both finish successfully.
`pxt ci` also run successfully.

Not sure why the `pxt-buildpush` is failing with:
https://github.com/microsoft/pxt-microbit/actions/runs/10282431056/job/28454622812
```
waiting 8s for C++ build...
polling C++ build https://makecode.com/compile/3bec9d0618871b4b8c832c205460247f433817a995fb2b80d96a84a89416f387.json (attempt #31)
build log https://makecode.com/compile/3bec9d0618871b4b8c832c205460247f433817a995fb2b80d96a84a89416f387.log
build failed
Code: 504 / 504.0 GatewayTimeout
TypeError: Cannot read property 'length' of null
    at compressHex (/home/runner/work/pxt-microbit/pxt-microbit/node_modules/pxt-core/built/pxt.js:105209:37)
    at /home/runner/work/pxt-microbit/pxt-microbit/node_modules/pxt-core/built/pxt.js:105138:36
{
  sha: '3bec9d0618871b4b8c832c205460247f433817a995fb2b80d96a84a89416f387'
}
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async fillExtInfoAsync (/home/runner/work/pxt-microbit/pxt-microbit/node_modules/pxt-core/built/pxt.js:1[137](https://github.com/microsoft/pxt-microbit/actions/runs/10282431056/job/28454622812#step:5:138)73:51)
    at async MainPackage.getCompileOptionsAsync (/home/runner/work/pxt-microbit/pxt-microbit/node_modules/pxt-core/built/pxt.js:1[138](https://github.com/microsoft/pxt-microbit/actions/runs/10282431056/job/28454622812#step:5:139)19:33)
    at async /home/runner/work/pxt-microbit/pxt-microbit/node_modules/pxt-core/built/pxt.js:162510:19
    at async /home/runner/work/pxt-microbit/pxt-microbit/node_modules/pxt-core/built/pxt.js:99437:42
    at async Promise.all (index 0)
    at async promisePoolAsync (/home/runner/work/pxt-microbit/pxt-microbit/node_modules/pxt-core/built/pxt.js:99443:21)
    at async buildTargetCoreAsync (/home/runner/work/pxt-microbit/pxt-microbit/node_modules/pxt-core/built/pxt.js:162492:5)
    at async Object.ciAsync [as _callback] (/home/runner/work/pxt-microbit/pxt-microbit/node_modules/pxt-core/built/pxt.js:160821:9)
```

@riknoll is it possible the cloud compiler is still having sporadic issues?

**Comment by microbit-carlos** [comment]
PR with the fix raised:
- https://github.com/microsoft/pxt-microbit/pull/5805
