### ISSUE TITLE
'Kitronik RC Car Hack': Extension shows Moto driver instead of Kitronik in toolbox

### ISSUE THREAD

**Issue by Ramanan0530** [microsoft/pxt-microbit#5808]
**Describe the bug**
'Kitronik RC Car Hack': Extension shows **Moto driver** instead of **Kitronik** in toolbox
 
**Steps to reproduce the behavior**
 1.Navigate to  https://makecode.microbit.org/beta
 2. Toys>Kitronik RC Car Hack>Show Instruction>Scroll below and click **Let's make it!**
 3.Scroll below>Click **code**
 4. Follow the **Step 1 : Add the Kitronik extension**
 
**Actual behavior**
Shows motor driver instead of Kitronik in the toolbox
 
**Expect behavior**
It should show Kitronik instead of motor driver

Screenshot :  

![image](https://github.com/user-attachments/assets/6f26907b-9fb2-4d6b-87cc-a02448959bf2)

Additional context
1.OS: Windows 11
2.Browser: Edge, Firefox, Chrome
3.makecode.microbit,org version: 7.0.16
4.Microsoft MakeCode version: 10.2.5

**Comment by abchatra** [comment]
This is by design. Extensions choose the name of their category. There can be even multiple category. Some extensions add to existing category as well. Platform leaves this flexibility to students.
