### ISSUE TITLE
[Mac Safari]:  "Add comment" box not fit with border

### ISSUE THREAD

**Issue by Ramanan0530** [microsoft/pxt-microbit#5817]
**Describe the bug**
[Mac Safari]:  "Add comment" box not fit with border

**Steps to reproduce the behavior**
1.Navigate to  https://makecode.microbit.org/beta
2. Open or create any project 
3. Add comment in workplace and observe the border fit of comment box
 
**Actual behavior**
Comment box doesn't fit with border of box

**Expect behavior**
Comment box should fit with border of box

**Screenshot:** 
![Border](https://github.com/user-attachments/assets/c78a98ab-e13f-4cd9-a164-63d085c72ecb)

**Additional context**
1.OS: MAC, iPad
2.Browser: Safari
3.makecode.microbit,org version: 7.0.19
4.Microsoft MakeCode version: 10.2.10

**Comment by riknoll** [comment]
fixed!

**Comment by Ramanan0530** [comment]
I verified this bug in the latest version: 7.0.34 and it has been fixed.
