### ISSUE TITLE
teacher tool: Auto-run evaluates AI criteria while it is being edited

### ISSUE THREAD

**Issue by eanders-ms** [microsoft/pxt-microbit#5833]
When auto-run is enabled, while I'm editing my AI criteria question, the criteria will be evaluated multiple times while I refine my question. Perhaps auto-run should skip AI criteria that have their edit box focused?

**Comment by abchatra** [comment]
Make Debounce 30 sec.

**Comment by thsparks** [comment]
If we make changes recommended in https://github.com/microsoft/pxt-microbit/issues/5617 then this issue becomes obsolete

**Comment by abchatra** [comment]
Closing.
