### ISSUE TITLE
Teacher Tool: Button & Form for General Feedback

### ISSUE THREAD

**Issue by thsparks** [microsoft/pxt-microbit#5835]
We should have a button somewhere for teachers to submit general feedback while using the teacher tool. Ideally, it'll go to a form they can fill out.
```[tasklist]
### Tasks
- [x] implement button
- [ ] implement form
```

**Comment by eanders-ms** [comment]
@Jaqster feedback button has been added. It opens the url https://aka.ms/teachertool-feedback. Can we link that to the feedback form?

**Comment by Jaqster** [comment]
Done.
