### ISSUE TITLE
pxt compiler ignores STS sim functions provided by extension 

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt-microbit#5838]
This pertains to the extension https://github.com/microsoft/pxt-arcadeshield. First trying to describe what is going on abstractly. We have a C++ function stuff:foo exposed to PXT as follows
```
namespace stuff {

//%
void foo() { 
 ...
}

}
```
The above function will be accessed from STS using code like this:
```
//% shim=stuff::foo
export function bar(): void;

bar();
```
The call above will be translated into JavaScript as follows:
```
pxsim.stuff.foo()
```

Now, here is where things get interesting in our extension. We provide the STS version of stuff.foo as follows
```
namespace pxsim.stuff {
   export function foo() { }
}
```
Note that function foo is not explicitly called anywhere in the STS of our solution.   It appears that. as a result, tree shaking removes foo, so it doesn't end up in the generated JS and we get a compile error on the call above.

**Comment by tballmsft** [comment]
@eanders-ms  - I've tried to capture the pattern of code leading to the bug.  I will try to create a small repro later.

**Comment by tballmsft** [comment]
Note that the above problem does not exist when we are building a target; only when we are doing C++ and simulator in extension.

**Comment by martinwork** [comment]
@tballmsft Is this related? https://github.com/microsoft/pxt-microbit/issues/4292. The ts foo cannot be empty.

**Comment by tballmsft** [comment]
@martinwork -  This was a big mistake on my part. An extension should never try to add stuff to the pxt namespace.  There should be some check and early failure.

**Comment by tballmsft** [comment]
@martinwork  - sorry - I am reopening as problem is still there - I am not sure it is the same (body is not empty in the real repro). Will need to investigate more

**Comment by abchatra** [comment]
Thanks @tballmsft  for the repro.
