### ISSUE TITLE
"Array block": There are 2 same blocks in the Toolbox

### ISSUE THREAD

**Issue by Ramanan0530** [microsoft/pxt-microbit#5846]
**Describe the bug**
"Array block": There are 2 same blocks in the Toolbox
 
**Steps to reproduce the behavior**
1.Navigate to  https://makecode.microbit.org/beta
2. Open or create a project and hover to **Toolbox**
3. Click **Advanced** and choose **Array** block
4. Hover to **List insert () at beginning** block and observe it

**Actual behavior**
There are 2 same **List insert () at beginning** block with different design.
**Expect behavior**
There should be only 1 block with actual design.

**Screenshot:**
![block array](https://github.com/user-attachments/assets/897f52df-77e2-4586-bcc9-8b096da936bf)

**Additional context**
1.OS: Windows 11, MAC, iPad
2.Browser: Edge, Firefox, Chrome, Safari
3.makecode.microbit,org version: 7.0.21
4.Microsoft MakeCode version: 10.2.11

**Comment by riknoll** [comment]
This is as intended. One of these returns the value and the other can be used as a statement. There is currently no way to create a block that can do both of those simultaneously
