### ISSUE TITLE
Version History - Save a Copy invalid date

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5853]
In Edge, open Version History of a project.
Select "Save a Copy"
It will create a copy of the project with the Title followed by the string "Invalid Date Invalid Date"
![image](https://github.com/user-attachments/assets/e92307e0-c4fe-47b9-ab06-0f3440f46a27)

**Comment by riknoll** [comment]
i actually can't reproduce this

**Comment by Jaqster** [comment]
okay, I think you need to click on the "Now" version of the project and then Save a Copy...  
![image](https://github.com/user-attachments/assets/14e22bc4-77ac-4822-8036-198f6f7d1334)
