### ISSUE TITLE
Version History - top nav bar color

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5855]
Can we use an existing micro:bit color here instead of introducing a new color?  for a more consistent experience
![image](https://github.com/user-attachments/assets/4a6bd799-5f88-4996-b60d-32e9615d667d)

**Comment by riknoll** [comment]
what color do we want here?

**Comment by Jaqster** [comment]
I'm open.  @jaustin or anyone from Foundation have opinions?

We could keep it blue - 
![image](https://github.com/user-attachments/assets/aabb2fd1-45ea-418b-92e2-658799b1fd3c)
but if we want to differentiate it from the core editor experience, we could 

Use the debug yellow - 
![image](https://github.com/user-attachments/assets/155c42d9-d38b-4c46-bddd-829130f71cd5)

Use the accent purple - 
![image](https://github.com/user-attachments/assets/6e6fa73e-e4a6-4d42-ba57-af4f1f663cbc)

Or use the footer white pattern with dark buttons - 
![image](https://github.com/user-attachments/assets/0dd7fdb7-95dc-4fa5-9b6b-dd5e36933e66)

**Comment by riknoll** [comment]
i don't think the debug yellow is color contrast friendly, so i'd like to avoid spreading it.

**Comment by abchatra** [comment]
@Jaqster  pick a color. We need to ship today :-)

**Comment by Jaqster** [comment]
Okay, could we do Blue, but put the title in the header bar so it's clear this is not the editor (like the Code Eval tool treatment).  Something like this?  
![image](https://github.com/user-attachments/assets/d9cb9e0f-883c-4ff1-873e-bf0536a337b6)
