### ISSUE TITLE
Version History timestamps seem erratic?

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5862]
We say that Version History saves your code automatically every 5 minutes, but the timestamps don't seem to mirror this.
I see 1 minute between saves, 8 and 9 minutes...  Do we create a timestamp every time the project gets opened?  Or every time there's a change?

![image](https://github.com/user-attachments/assets/f39b81c7-a453-409f-8106-cdb5d0155fef)

**Comment by riknoll** [comment]
we create a diff entry every ~10 minutes and a full project snapshot every ~30 minutes. sometimes those timers can go out of phase with each other and result in entries that look like they're closer together than they should be.

really, i don't think there's any reason to tell people exactly how often they should see versions taken. when messaging this feature, we should just say "frequent" or something like that
