### ISSUE TITLE
Help document hide toolbox when switch to JavaScript/python code

### ISSUE THREAD

**Issue by Ramanan0530** [microsoft/pxt-microbit#5864]
**Describe the bug**
Help document **hide** toolbox when switch to JavaScript/python code
 
**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2. Open any project and **switch** editor to **JavaScript/python**
3. Select any code and **click (?) in the code**
4. Observe the help document
 
**Actual behavior**
The help document cover half of the toolbox when click (?) JavaScript/python code
**Expect behavior**
The help document should not cover the toolbox when click (?) JavaScript/python code.

**Screen Recording:** 
![tool](https://github.com/user-attachments/assets/144aabb8-a211-4baa-8da9-d2400a4bbfd9)

**Additional context**
1.OS: Windows, Mac
2.Browser: Safari, Chrome, Edge, Firefox
3.makecode.microbit,org version: 7.0.25

**Comment by abchatra** [comment]
This is by design. As the javascript\python code truncates (shows multiline) compared to blocks. They open wider in javascript
