### ISSUE TITLE
404 on Microbit.org

### ISSUE THREAD

**Issue by rmclean45** [microsoft/pxt-microbit#5866]
**Describe the bug**
There is a 404 on URL: https://makecode.microbit.org/reference/music/builtin-melody

**To Reproduce**
1. Open browser
2. Navigate to https://makecode.microbit.org/reference/music/builtin-melody

**Expected behavior**
Page displays the reference page

**Screenshots**
![Screenshot 2024-08-27 at 2 32 54 PM](https://github.com/user-attachments/assets/0237217c-3300-407a-a574-5482f578f1e7)

**micro:bit version (please complete the following information):**

**Desktop (please complete the following information):**
 - OS: macOS 14.5
 - Browser: Safari
 - Version 14.5

**Additional context**
None Required

**Comment by abchatra** [comment]
@rmclean45 where did you get the link from? Is this link listed in any of the other webpages?

**Comment by jwunderl** [comment]
![image](https://github.com/user-attachments/assets/2b2a8ab8-e554-4505-9958-90a2a38e0b83)
it's referenced as help docs for the builtin melodies (e.g. disabled block in the screenshot above)
