### ISSUE TITLE
Comment rendering is different in firefox & no delete button

### ISSUE THREAD

**Issue by thsparks** [microsoft/pxt-microbit#5890]
Comment bar appears on the bottom instead of the top, no delete button, and the colors seem slightly off.

Comments in firefox:
![image](https://github.com/user-attachments/assets/658a5a57-ca07-4bb1-8657-9f095c419b72)

Comments normally:
![image](https://github.com/user-attachments/assets/83eeac8b-bbb2-481d-915e-6d619869a9e5)

**Comment by eanders-ms** [comment]
My experience with comments in Firefox is different, so will add it here as a data point.

Workspace comments do not have a header when unfocused:
![image](https://github.com/user-attachments/assets/c42ed1c6-cd86-41ba-814f-06b51853d4eb)

Block comments work fine.
