### ISSUE TITLE
Teacher tool: - The word "feedback" is missing in print view

### ISSUE THREAD

**Issue by Ramanan0530** [microsoft/pxt-microbit#5897]
**Describe the bug**
Teacher tool: - The word **"feedback"** is **missing** in print view

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta--eval#
2. **Create** or open a **checklist** and enter project link
3. **Write feedback** in feedback field and **click print**
4. **Observe** the print view

**Actual behavior**
The word feedback is missing in print view once give feedback to criteria
**Expect behavior**
The word feedback should appear in print view

**Screenshot:** 
![Feed](https://github.com/user-attachments/assets/0ed2b49a-ddca-4740-90a2-2fc1f778c997)

**Additional context**
1.OS: Windows, Mac, iPad
2.Browser: Safari, Chrome, Edge, Firefox
3.makecode.microbit,org version: 7.0.35
4.Microsoft MakeCode version: 10.2.31

**Comment by abchatra** [comment]
@eanders-ms  is this intentional?

**Comment by eanders-ms** [comment]
Yes, it was intentional. In the UI the "feedback" label is useful to instruct the user what the text area is for. In print, it is already obvious that the content is feedback.

The two views (UI and print) aren't intended to be identical.
