### ISSUE TITLE
"Download as a file": - Different display in micro: bit and teacher tool

### ISSUE THREAD

**Issue by Ramanan0530** [microsoft/pxt-microbit#5898]
**Describe the bug**
"**Download as a file**": - Different display in micro: bit and teacher tool
 
Steps to reproduce the behavior
1.Navigate to https://makecode.microbit.org/beta
2. **Open any project** and **hover mouse** to bottom download
3. **Click (…)** and **Observe** the Download as a file
4. Then **navigate** to https://makecode.microbit.org/beta--eval# and **enter any project** link
4. **Click (…)** in the bottom and **observe** the "Download"
 
**Actual behavior**
Incomplete display of button names" Download as a file in micro: bit & "Download" in teacher tool
**Expect behavior**
The buttons name should be same in both micro: bit and teacher tool

**Screenshot**
![Down](https://github.com/user-attachments/assets/d3b868ae-885c-4831-b12b-c2102c0c503d)

**Additional context:** 
1.OS: Windows, Mac, iPad
2.Browser: Safari, Chrome, Edge, Firefox
3.makecode.microbit,org version: 7.0.35
4.Microsoft MakeCode version: 10.2.31

**Comment by abchatra** [comment]
Minor P3 won't fix
