### ISSUE TITLE
stop/start should control data reading on microbit

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#59]
1 enter this code

```
basic.forever(() => {
    led.plotBarGraph(input.acceleration(Dimension.Strength) - 1023, 0);
});
```
2. plug in a micro:bit, black line appears, starts reading data points immediately

3. START/STOP should control when the data is being streamed onto a CSV file. 

4. data is automatically starting on XLS... the students/teachers have no control. the time variable is endless. teachers will only run acceleration experiments by having the control of start/stop when running acceleration experiments with examples.

![seismograph5](https://cloud.githubusercontent.com/assets/11206682/15162360/4cf99c6c-16b7-11e6-99e4-ae37f392be4c.PNG)

**Comment by pelikhan** [comment]
> data is automatically starting on XLS

Please explain what XLS you are referring to.

**Comment by mebrauns** [comment]
Does the 5 instances of time 00:00 represent 5 instances of pressing STOP/PLAY? (see attached .xls)

[line charts.xlsx](https://github.com/Microsoft/pxt-microbit/files/258202/line.charts.xlsx)

**Comment by pelikhan** [comment]
Please attach the original file. How did you get this spreadsheet?

**Comment by mebrauns** [comment]
data is in milliseconds: teachers generally help students analyze data in seconds. i would suggest only showing time as measured in seconds. currently, the data (measuing milli-seconds) is too difficult for students to analyze in in the classroom

**Comment by mebrauns** [comment]
instance of measuring in milli-seconds (teachers will not like to use this data - must be in seconds)

![image](https://cloud.githubusercontent.com/assets/11206682/15188929/14465666-175d-11e6-8019-8fd370ef9a3c.png)

instance of measuring in seconds (very clean for teachers) 

![image](https://cloud.githubusercontent.com/assets/11206682/15189004/5c3c9106-175d-11e6-98ec-9f7b1260f336.png)

**Comment by pelikhan** [comment]
This does not make sense - you are getting multiple entires per second, so decimal seconds make more sense.
