### ISSUE TITLE
Tutorials Using Deprecated Blocks

### ISSUE THREAD

**Issue by thsparks** [microsoft/pxt-microbit#5909]
Some of our tutorials use deprecated blocks. For example, Pet Hamster uses the old sound blocks. This makes it challenging to create teacher tool checklists for the tutorials because deprecated blocks are filtered from the block picker (and if the teacher selects the new block, it will be shown as missing since the project itself has the deprecated blocks).

It'd be nice if we could update these tutorials to use the newer blocks.

**Comment by thsparks** [comment]
Also hit issue with countdown tutorial sound blocks

**Comment by srietkerk** [comment]
Cat Napping is also using the deprecated version of `play sound`.

**Comment by Jaqster** [comment]
And Morse Chat

**Comment by abchatra** [comment]
@ganicke is it possible to update these tutorials? Thanks so much!
