### ISSUE TITLE
Version History: Saving a copy doesn't show up in your projects automatically

### ISSUE THREAD

**Issue by srietkerk** [microsoft/pxt-microbit#5926]
When saving a project at a specific time in version history, I would expect that the project is automatically visible in the "My Projects", but it is not.

**To Reproduce**
1. Go to https://makecode.microbit.org/beta
2. Create a project and add blocks for about 10 minutes
4. Open version history
5. Click on a past version of the project
6. Select save a copy for that time slot
7. Go back to the home page to see your saved copy
8. See that the copy of the project isn't there
9. Go back into the project that you were working on
10. Go back to the home page
11. See the copy of the project

I expect the copy of my project to show up in the "My Projects" list on the first time that I look for it. 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Chrome

**Comment by Jaqster** [comment]
This is most likely because the Home Page doesn't refresh very often.  If you do a hard reload on the Home Page, you should see it show up.
