### ISSUE TITLE
[Firefox] teacher tool: criteria misaligned

### ISSUE THREAD

**Issue by kimprice** [microsoft/pxt-microbit#5927]
**Describe the bug**
On Firefox, the criteria in the checklist is misaligned.

**To Reproduce**
1. Go to https://makecode.microbit.org/beta---eval
2. Click on Rock Paper Scissors or Blow Away or Micro Chat
3. See misalignment

**Expected behavior**
The criteria should all be left aligned.

**Screenshots**
![image](https://github.com/user-attachments/assets/c90145ff-7738-4cbd-8a46-e7782f68df21)
![image](https://github.com/user-attachments/assets/afa30f81-1424-4162-8eb7-91fc08315a39)

**Comment by Ramanan0530** [comment]
This bug also reproduces after **creating a new checklist.**
![image](https://github.com/user-attachments/assets/6dfe7f14-088c-45c3-899d-3399cb670646)

**Comment by thsparks** [comment]
Also looks weird & centered in firefox when checklist window is wide:
![image](https://github.com/user-attachments/assets/621c0410-060a-42ec-a729-82d5cf071984)
