### ISSUE TITLE
Text-> char code from doesn't have help

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#5929]
Text-> char code from doesn't have help

<img width="474" alt="image" src="https://github.com/user-attachments/assets/619899c0-599d-4ad9-aec9-8d3de25c3693">

<img width="917" alt="image" src="https://github.com/user-attachments/assets/e3ac1ef1-2c33-4ba9-b457-da4fff9cf4b9">

**Comment by ganicke** [comment]
Fixed in https://github.com/microsoft/pxt/pull/10151. Might not show up until the next core release.

**Comment by abchatra** [comment]
@ganicke  we did the release of version

**Comment by abchatra** [comment]
This is a bug on our end. I will take care

**Comment by abchatra** [comment]
Fixed
