### ISSUE TITLE
Incorrect Code Validation Error in Hamster Tutorial

### ISSUE THREAD

**Issue by thsparks** [microsoft/pxt-microbit#5940]
On step 4 of the hamster tutorial (or any other step expecting `play sound` blocks), we get a code validation failure popup even if the correct block is in place. Probably something to do with the switch to non-deprecated blocks, though the hint looks correct so I'm not sure yet where the issue lies, if it's just updating tutorial content or some issue with the compilation/block parsing.

![image](https://github.com/user-attachments/assets/74a102d7-a4f5-4b61-b1f1-564696af9b69)

![image](https://github.com/user-attachments/assets/41131442-d5c6-4c1c-853b-020002ef2c13)

**Comment by ganicke** [comment]
@thsparks, @abchatra - the problem here is that the blocks decompile doesn't match the hint code source in ```` ```blocks ````. You see that the hint contains:

```typescript
basic.showIcon(IconNames.Asleep)
input.onLogoEvent(TouchButtonEvent.Pressed, function () {
    basic.showIcon(IconNames.Happy)
    //@highlight
    music.play(music.builtInPlayableMelody(Melodies.JumpUp), music.PlaybackMode.UntilDone)
})
```

...but the result for the code dragged over from the workspace has the `play()` method converted into the helper of `_playDefaultBackground()`:

```typescript
input.onLogoEvent(TouchButtonEvent.Pressed, function () {
    basic.showIcon(IconNames.Happy)
    music._playDefaultBackground(music.builtInPlayableMelody(Melodies.JumpUp), music.PlaybackMode.UntilDone)
})
basic.showIcon(IconNames.Asleep)
```

I've verified that the validation succeeds when I replace `play()` with `_playDefaultBackground()`.

This is even visually evident when you look at the "Show Me" and see the difference in the melody parameter:

![image](https://github.com/user-attachments/assets/e6d8eeb0-5ad9-4721-8a87-dc99ed1979f6)

So, what's the fix here? Replace the all the occurrences of `play()` with `_playDefaultBackground()`?

**Comment by abchatra** [comment]
@riknoll ?

**Comment by thsparks** [comment]
Seems odd to me that it's compiling to _ blocks like that, so we probably want to see about fixing that...But I'd still say we should fix the tutorials for now. Bug is pretty annoying if you're going through the tutorials, and it's out in live right now. We can switch them back later if needed, if we do decide to switch it to a non-hidden function.

**Comment by thsparks** [comment]
Probably a result of my changes to these blocks from last year
