### ISSUE TITLE
Transmit audio recording

### ISSUE THREAD

**Issue by gblessed** [microsoft/pxt-microbit#5944]
Hi I am able to record and play audio recordings using the record extension.
But I cant find a way to access the audio buffer to transmit the audio sample values over serial. Please any guide?

````

def on_button_pressed_a():
    record.set_sample_rate(10000, record.AudioSampleRateScope.RECORDING)
    basic.show_icon(IconNames.SMALL_SQUARE)
    record.start_recording(record.BlockingState.BLOCKING)
    basic.clear_screen()
input.on_button_pressed(Button.A, on_button_pressed_a)

def on_button_pressed_b():
    record.set_sample_rate(20000, record.AudioSampleRateScope.PLAYBACK)
    basic.show_leds("""
        . # . . .
        . # # . .
        . # # # .
        . # # . .
        . # . . .
        """)
    record.play_audio(record.BlockingState.BLOCKING)
    basic.clear_screen()
input.on_button_pressed(Button.B, on_button_pressed_b)```

**Comment by abchatra** [comment]
@jaustin 
@carlosperate ?

**Comment by martinwork** [comment]
Also raised in support ticket  https://support.microbit.org/helpdesk/tickets/82442 (private)

**Comment by gblessed** [comment]
Hi please any update on this?

**Comment by martinwork** [comment]
Here's an example to try
https://makecode.microbit.org/_Uy36jA4WDCkx  

The example uses this experimental replacement for the usual audio-recording extension, with a send to serial block added.
https://github.com/martinwork/pxt-audio-recording

I could not figure out how to access the recording buffer without duplicating the extension code.

To replace the audio-recording extension in an existing project (back up the project first!), remove it by using the Explorer, then paste the repo URL into the extension dialogue search box.

I strongly suggest not using my extension repo directly. I might change it or delete it at any time.

Create your own fork. Then if my sendToSerial function isn't quite what you need you can change it, or add your own!

The serial code is not properly integrated with the recording and playing states. Recording and playing can happily interrupt each other. sendToSerial won't start if recording is in progress, and stops at the end of a buffer if it sees recording has started. It could crash if recording has actually started and stopped while a buffer was being sent.

**Comment by gblessed** [comment]
Thank you 
Let me try it

**Comment by gblessed** [comment]
It works !
Thank you so much
This is well appreciated.
