### ISSUE TITLE
Electron app: Can't share projects

### ISSUE THREAD

**Issue by thsparks** [microsoft/pxt-microbit#5951]
Get a network request failed error.

![image](https://github.com/user-attachments/assets/445f2bcd-1861-4e1c-b62f-1c9389cc37b9)

From console, looks like it's trying to go to localhost:
![image](https://github.com/user-attachments/assets/5a687d2a-5c64-44f3-846c-d0415eacf686)

**Comment by jwunderl** [comment]
looks fixed in 7.0.43 build
