### ISSUE TITLE
Size and shape of array block has changed

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#5958]
**Describe the bug**
Arising from support ticket https://support.microbit.org/helpdesk/tickets/82439 (private)

Is this change in size and shape intentional?

**Screenshots**
Previously

![image](https://github.com/user-attachments/assets/25d0e5ac-7cca-44cf-97c3-52ab3033bd81)

Now

![image](https://github.com/user-attachments/assets/11c81fe3-a241-45fb-ae3d-26077be23315)

**micro:bit version (please complete the following information):**
not hardware related

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 128

**Comment by riknoll** [comment]
yup, this is intentional! this was something that was brought in by the stock blockly zelos renderer which imo looks much better/more consistent with the other block shapes

**Comment by abchatra** [comment]
New one looks better. Won't fix
