### ISSUE TITLE
audio-recording - low sample rate causes out of memory

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#5960]
**Describe the bug**

This program causes error 020.
https://makecode.microbit.org/_6bt5oMbpbKEw
![image](https://github.com/user-attachments/assets/586d8730-73e0-49d2-a687-e516b9442e58)

It's OK at 11000Hz.

**micro:bit version (please complete the following information):**
V2.X

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 128

**Comment by abchatra** [comment]
@martinwork is this is a regression from last version? Looks more due to codal changes. @carlosperate

**Comment by martinwork** [comment]
@abchatra @carlosperate I haven't looked into the cause yet. I can't think what relevant changes in CODAL there have been. Maybe there's a bit less RAM left in v7?

This example is created in v6, and seems to work there, but runs out of memory in v7.
https://makecode.microbit.org/_TTzHUsEaz3gb

**Comment by martinwork** [comment]
@abchatra is right. I think the v6/v7 difference is the CODAL default sample rates.

I created: https://github.com/lancaster-university/codal-microbit-v2/issues/450
