### ISSUE TITLE
Cannot translate string in download window

### ISSUE THREAD

**Issue by THEb0nny** [microsoft/pxt-microbit#5969]
Cannot translate string in download window.
![Screenshot_11](https://github.com/user-attachments/assets/04384c0b-fe02-4fc2-99fb-18c0a5ffff46)

**Comment by abchatra** [comment]
@jwunderl ?

**Comment by jwunderl** [comment]
hm it is set for translation as expected (e.g. same as the other lines in the screenshot) https://github.com/microsoft/pxt/blob/master/webapp/src/webusb.tsx#L266, is crowdin translation upload down in pxt perhaps? String isn't there either.

**Comment by jwunderl** [comment]
Confirmed re-enabling upload fixed made this translatable.
