### ISSUE TITLE
When using Image and controlling brightness of LEDs then other LED's brightness changes, too

### ISSUE THREAD

**Issue by brmarkus** [microsoft/pxt-microbit#5971]
**Describe the bug**
Using the Python editor in MakeCode under "https://makecode.microbit.org/#editor".
First, creating an empty `Image` and manually turning all 25 LEDs on with two nested loops, then showing the image.
Waiting a short time.
Then animating the last line LED's brightness - and suddenly all LEDs change their brightness, instead only of the last line.

**To Reproduce**
EDIT 2024-09-24: local variable `screen` renamed to `myimage`
Small Python program:
```
myimage = images.create_image("")
for row in range(5):
    for col in range(5):
        myimage.set_pixel(col, row, True)
myimage.show_image(0)
basic.pause(2000)
i = 245
while i > -1:
    for pos in range(5):
        led.plot_brightness(pos, 4, i)   # hard-coded last line 4
    basic.pause(10)
    i += -10
```

**Expected behavior**
Only the last line LED's brightness should change, no other LEDs.
However, when NOT using an `Image`, but turning all LEDs on and then changing the last line LED's brightness, then only the last line changes its brightness.

**Screenshots**
Wrong behavior, all LEDs have changed its brightness:
![image](https://github.com/user-attachments/assets/132c1a0f-d954-4bdd-a1d6-e18d76072937)
Expected behavior, only the last line should have changed its brightness:
![image](https://github.com/user-attachments/assets/dae8816c-a23d-49e4-bf57-d42ab451e879)

**micro:bit version (please complete the following information):**
makecode.microbit.org version:  [7.0.42](https://github.com/Microsoft/pxt-microbit/releases/tag/v7.0.42)
Microsoft MakeCode version:  [10.2.39](https://github.com/Microsoft/pxt/releases/tag/v10.2.39)
microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
codal-microbit-v2 runtime version:  [v0.2.68](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.68)

Using micro:bit in version V2.

**Desktop (please complete the following information):**
 - OS: MS Windows 11 Pro
 - Browser Chrome
 - Version 129.0.6668.59, 64bit

**Comment by abchatra** [comment]
This program is mixing screen  and led.plot_brightness API. Does the program work with just screen APIs?  Does it behaves differently in hardware?

**Comment by martinwork** [comment]
The simulator starts in BLACK_AND_WHITE display mode and is changed to GREYSCALE by led calls,  but not image calls.

This JavaScript shows the display mode: hardware 1 1 1; simulator 0 0 1
```
basic.showNumber(led.displayMode())
basic.pause(1000)
basic.clearScreen()

let myimage = images.createImage(".........................")
myimage.setPixel(0, 0, true)
myimage.setPixelBrightness(0, 0, 32)
myimage.showImage(0)
basic.pause(1000)
basic.clearScreen()

basic.showNumber(led.displayMode())
basic.pause(1000)
basic.clearScreen()

led.plot(0,0)
led.plotBrightness(0, 0, 32)
basic.pause(1000)
basic.clearScreen()

basic.showNumber(led.displayMode())
```

The first pixel display is dimmed on hardware, but not simulator. Calling set_display_mode fixes that

Python:
```
led.set_display_mode(DisplayMode.GREYSCALE)

myimage = images.create_image(".........................")
myimage.set_pixel(0, 0, True)
myimage.set_pixel_brightness(0, 0, 32)
myimage.show_image(0)
basic.pause(2000)
basic.clear_screen()

led.plot(0, 0)
led.plot_brightness(0, 0, 128)
```

**Comment by martinwork** [comment]
In the simulator, after myimage.set_pixel_brightness(), myimage.pixel returns the pixel brightness number, although it's documented to be a boolean.

This is another hardware/simulator difference.

As a workaround, maybe test pixel() != False or use pixelBrightness?

hardware: true|true
simulator:1|254
```
myimage = images.create_image(".........................")
myimage.set_pixel(0, 0, True)
before = myimage.pixel(0, 0)
myimage.set_pixel_brightness(0, 0, 254)
after = myimage.pixel(0, 0)
basic.show_string(str(before) + "|" + str(after))
basic.show_string(str(after != False))
basic.show_number(myimage.pixel_brightness(0, 0))
```

**Comment by martinwork** [comment]
@brmarkus Perhaps you should reopen the issue?
