### ISSUE TITLE
Offline app: "Pet Hamster" pops alert even though the code is correct

### ISSUE THREAD

**Issue by Ramanan0530** [microsoft/pxt-microbit#5973]
**Describe the bug**
Offline app: "Pet Hamster" pops alert even though the code is correct
 
**Steps to reproduce the behavior**
1.Navigate to offline app:  https://makecode.com/api/release/microbit/v7.0.45/win64 or https://makecode.com/api/release/microbit/v7.0.45/mac64
2.Hover to **Tutorials for new micro: bit (v2)** and Select **Pet hamster**
3.**Start** tutorial and **Observe** step 4 
 
**Actual behavior**
Pops alert message" This code doesn't look the way we expected" even though the code is correct
**Expect behavior**
There should be no any alert messages if the code is correct.
**Screen Recording:** 
![alert](https://github.com/user-attachments/assets/770c7a5e-43ea-42cc-b3df-933424a8edba)

**Additional context**
1.OS: Windows , Mac
2.Browser: Offline app
3.makecode.microbit,org version: 7.0.45
4.Microsoft MakeCode version: 10.2.42

**Comment by ganicke** [comment]
Fixed in #5961. Offline app may need a new release to pick up this change.
