### ISSUE TITLE
Micro:bit CuteBot issue

### ISSUE THREAD

**Issue by EpiksStudio** [microsoft/pxt-microbit#5974]
Hey,

I bought a micro:bit about a week ago and my micro:bit robot just arrived to add it. In the manual, it says that i need to get an extension called Cutebot. But when I searched nothing came up. Please help me fix this.

Sincerely,
Epik

**Comment by dsssssssss9** [comment]
Hi 

Start make code editor 

Create a new project 

Goto the extension by clicking the ⚙️ at the tup ...

Type Cutebot into the search box ..

Versions of the extension fior the differing models of Cutebot should be shown .

Make sure to select the correct version that matches the actual model you have 

Have a look at the wiki ...

https://www.elecfreaks.com/learn-en/microbitKit/smart_cutebot/cutebot_car.html


Hope this helps ...

**Comment by Jaqster** [comment]
In a project, open the Extensions section on the Toolbox.  You can find the Cutebot extension in the Robotic category.
![image](https://github.com/user-attachments/assets/39cfa86e-537e-42c7-9cf8-93cc460b60d5)
![image](https://github.com/user-attachments/assets/7988d9d3-b0da-48ce-86e2-0095d8354cb2)
![image](https://github.com/user-attachments/assets/c31b7903-0463-4152-8386-d33f5cfc7303)
