### ISSUE TITLE
Phantom or orphaned `false` blocks created during interaction with if/else-if/else block

### ISSUE THREAD

**Issue by microbit-robert** [microsoft/pxt-microbit#5984]
**Describe the bug**
After adding several `else if` sections to an `if` block (at least three), removing them using the `-` button leaves phantom / orphaned false blocks on the canvas. These can't be interacted with or removed by the user. These also don't appear in the JavaScript.

The following error appears in the developer console:
```
Uncaught TypeError: Cannot read properties of null (reading 'isShadow')
    at ad.setTargetBlock (main.js:7:230288)
    at ad.setTargetBlock (main.js:7:230304)
    at ad.setStartBlock (main.js:7:230249)
    at ad.handleBlockStart (main.js:7:227938)
    at ep.onMouseDown_ (main.js:7:433042)
    at SVGGElement.o (main.js:7:42156)
```

The following warning appears in the developer console:
```
Shadow block of type 'logic_boolean' found at top level. Converting to non-shadow block
```

**To Reproduce**

1. Open the microbit-phantom-false-blocks.hex file in the following [microbit-phantom-false-blocks.zip file](https://github.com/user-attachments/files/17311143/microbit-phantom-false-blocks.zip)
2. Click the `+` button in the `if` block to add another `else if` section
3. Click the `-` button on the same section just added
4. Note that there is now a 'phantom' `false` block hidden **behind** the `every` block and observe the errors in the developer console
5. This can be repeated subsequent times

Please see the gif below if these steps to reproduce aren't clear.

**Expected behavior**
Phantom false blocks should not be left behind in this way.

**Screenshots** 
![Image](https://github.com/user-attachments/assets/ab2c7a29-54e2-4b05-9344-cbc9cc415293)

**micro:bit version (please complete the following information):**
Not hardware related

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 129.0.6668.90

**Additional context**
None

**Comment by riknoll** [comment]
minimal repro steps:

![Image](https://github.com/user-attachments/assets/135ecac7-3487-425c-b66b-c133097a53b4)

you need to have something attached to the first two condition inputs for the third input to exhibit the bug

**Comment by microbit-robert** [comment]
It seems highly likely that this is cause of top-level shadow blocks noted in this separate fix -> https://github.com/microsoft/pxt/pull/10177

**Comment by Jaqster** [comment]
Related issue - https://github.com/microsoft/pxt-microbit/issues/5899
