### ISSUE TITLE
Multiple forever loops have access to the common resource, concurrency

### ISSUE THREAD

**Issue by maxxlife** [microsoft/pxt-microbit#5988]
If a multiple forever loops have access to the common resource, how do to they define who is gonna take it first?
![Image](https://github.com/user-attachments/assets/51c87848-3bba-4a0b-86c7-33e2901db7ad)

**Comment by abchatra** [comment]
If you go to text you will see the order of the forever loops. However each forever loop as a yield and gives the control back to another at the end of one iteration. So all 3 loops will run once at a time. 

System is single thread non-preemptive system. Only one works at the time but can yield to others on its own. We put a yield at the end of forever as per design.

**Comment by abchatra** [comment]
question answered
