### ISSUE TITLE
Duplicating a forever loop loses parameters on enclosed blocks

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#5989]
**Describe the bug**
Duplicating a forever loop loses parameters on enclosed blocks

In the example, It seems the function call below the variable change is the trigger. A similar function call above also loses it's parameters, but does not trigger the issue on it's own. 

The JavaScript seems OK, so it's fixed by switching to JavaScript mode and back.

**To Reproduce**
1. Go to https://makecode.microbit.org/_EhHfLr7iT1hX
2. Right click on 'forever'
3. Choose 'Duplicate'

**Expected behavior**
The enclosed blocks are duplicated.

**Screenshots**

Before:

![Image](https://github.com/user-attachments/assets/85edd3b1-0d5c-4b24-934b-9d6e3f41b60e)

After:

![Image](https://github.com/user-attachments/assets/6f47d792-4139-4146-9b3f-dab511b7ba5d)

**micro:bit version (please complete the following information):**
not hardware related

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 129

**Comment by abchatra** [comment]
@riknoll  this one seems good to fix.
