### ISSUE TITLE
Resetting the editor does not delete the local storage projects

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#6002]
When resetting the editor using the `settings > reset` menu, it does not delete any of the saved projects.

https://github.com/user-attachments/assets/e6b37971-7ef3-45db-a576-b26c2ccf531c

I'm not logged in and there isn't any error printed to the console.

- makecode.microbit.org version:  [7.0.51](https://github.com/Microsoft/pxt-microbit/releases/tag/v7.0.51)
- Microsoft MakeCode version:  [11.1.5](https://github.com/Microsoft/pxt/releases/tag/v11.1.5)
- microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
- codal-microbit-v2 runtime version:  [v0.2.68](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.68)

**Comment by microbit-carlos** [comment]
Ah, if I create a new project, and then reset MakeCode, then it does delete the new project, but it keeps everything else I've shown in that video.

I could try to reset a slightly different MakeCode v6 deployment to see if that works, but it might be better to leave it like this in case there is anything else you'd like me to try? or anything you'd like me to check about the current state of the editor?

**Comment by abchatra** [comment]
I can reproduce the bug. It is probably because we implemented a feature to move away from pouch db and probably it will import back from pouch db if it finds none imported.

Nice bug @microbit-carlos 

@riknoll
