### ISSUE TITLE
bad interaction between radio and jacdac proxy mode

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt-microbit#6005]
See https://makecode.microbit.org/_Eei0YxUotXsy

The program uses the Jacdac extension and sends a radio message. The bad behavior:
1. the second microbit sim starts up and then disappears
2. the first microbit sim goes into jacdac proxy mode, which also causes a reset of micro:bit sim (via control.reset)

Expected behavior:
1. the second micro:bit sim stays up
2. the first micro:bit sim does not go into jacdac proxy mode

**Comment by tballmsft** [comment]
There is some bad interaction, perhaps due to messaging and iframes.  If you don't have the JD extension then the program brings up two mbit simulators as expected.

**Comment by tballmsft** [comment]
@eanders-ms - this error popped up recently - i wonder if it is a result of the new logic for simx extension you did.

**Comment by tballmsft** [comment]
The other thing I wonder if there is some baked in assumption to pxt about the second frame being a "board" simulator (so that when the mbit appears in the third frame, things go awry).

**Comment by tballmsft** [comment]
I found this code in simdriver.ts, which is what I believe creates the second mbit sim
```
                            isDeferrableBroadcastMessage = true;
                            // start secondary frame if needed
                            const mkcdFrames = frames.filter(frame => !frame.dataset[FRAME_DATA_MESSAGE_CHANNEL]);
                            if (mkcdFrames.length < 2) {
                                this.container.appendChild(this.createFrame());
                                frames = this.simFrames();
                                // there might be an old frame
                            } else if (mkcdFrames[1].dataset['runid'] != this.runId) {
                                this.startFrame(mkcdFrames[1]);
                            }
```
Looks a little suspicious. In our case, the second frame is the Jacdac sim.

**Comment by tballmsft** [comment]
My thesis is the following
- the 2nd mbit simulator is created, but not started, so it appears
- the start message that was supposed to go mbit, goes to jacdac, putting it in proxy mode

**Comment by tballmsft** [comment]
@abchatra - i don't think this is a problem with Jacdac; it is a problem with the treatment of multiple mbit simulators (due to radio), when another simulator is taking the second slot.

**Comment by tballmsft** [comment]
OK. Here's what's going on:
- the radio message starts the new mbit sim
- the new mbit sim runs a second instance of jacdac, so now there are two mbits on the bus
- the first mbit goes into proxy mode, which also causes reset, so the second mbit goes away

Sigh...

**Comment by tballmsft** [comment]
I think the solution here is for the Jacdac extension to have a way to specify that only one code (mbit) simulator is allowed.

**Comment by tballmsft** [comment]
See https://github.com/microsoft/pxt/pull/10263 and https://github.com/microsoft/pxt-common-packages/pull/1486

**Comment by tballmsft** [comment]
The above changes provide a function to turn off multiple simulators (for the rest of a program execution). See following program
```
input.onButtonPressed(Button.A, function () {
    radio.sendNumber(0)
})
input.onButtonPressed(Button.B, function () {
	control.reset()
})
input.onButtonPressed(Button.AB, function () {
    control.singleSimulator()
})
```

**Comment by tballmsft** [comment]
approved and committed (will need to bump pxt, pxt-common-packages, pxt-microbit): @abchatra

**Comment by abchatra** [comment]
Done
