### ISSUE TITLE
`pxt deploy` reports `Error: cannot find any drives`

### ISSUE THREAD

**Issue by lobodpav** [microsoft/pxt-microbit#6022]
**Describe the bug**
`pxt deploy` reports `Error: cannot find any drives to deploy to` even though the micro:bit is connected and working well in MakeCode online.

**To Reproduce**
1. Follow the [official instructions](https://makecode.com/cli) to setup a project. I.e.:
    ```shell
    npm install -g pxt
    mkdir makecode
    cd makecode
    pxt target microbit
    ```
2. Pull your Git code to `./projects/microbit-christmas-tree`
3. Connect the board to your Mac
4. Run `cd ./projects/microbit-christmas-tree`
5. Run `pxt deploy`
6. You'll get the output below
    ```shell
    Using target microbit with build engine yotta
      target: v7.1.15 /Users/pavel/Microbit/makecode/node_modules/pxt-microbit
      pxt-core: v11.3.3 /Users/pavel/Microbit/makecode/node_modules/pxt-core
    building /Users/pavel/Microbit/makecode/projects/microbit-christmas-tree
    INTERNAL ERROR: Error: cannot find any drives to deploy to
        at /Users/pavel/Microbit/makecode/node_modules/pxt-core/built/buildengine.js:562:23
    ```

**Expected behavior**
The program shall be deployed to micro:bot.

**micro:bit version (please complete the following information):**

V2.21

**Desktop (please complete the following information):**
 - Computer: MacBook Pro M2 Max
 - OS: macOS Sequoia 15.1.1
 - pxt-core: v11.3.3

**Comment by martinwork** [comment]
I think this will be because it's looking for a drive named MICROBIT,
https://github.com/microsoft/pxt-microbit/blob/d1c862a75ef62224be8e0647c67ead4d34751383/pxtarget.json#L74

but currently on Sequoia the drive is named NO NAME
https://github.com/ARMmbed/DAPLink/issues/1082

**Comment by lobodpav** [comment]
> I think this will be because it's looking for a drive named MICROBIT,
> but currently on Sequoia the drive is named NO NAME

Thanks for the hint! I have renamed the volume to `MICROBIT` and `pxt deploy` went well.

However, right after deployment, the volume name was reverted back to `NO NAME` 😢

Any clue what could cause the name changes?

**Comment by martinwork** [comment]
Good idea - I didn't think of renaming the volume! The micro:bit resets and remounts, so the name would revert (see the DAPLink issue for the cause). I don't know how to override the default name. Maybe a script to rename the volume then pxt deploy?

**Comment by lobodpav** [comment]
> Good idea - I didn't think of renaming the volume! The micro:bit resets and remounts, so the name would revert (see the DAPLink issue for the cause). I don't know how to override the default name. Maybe a script to rename the volume then pxt deploy?

Yep, a custom `pxt` shell alias would do the trick. I just hope I won't rename some other flash drive by accident 😊

**Comment by tballmsft** [comment]
Thanks for the resolution!

**Comment by lobodpav** [comment]
For reference, I used these commands to rename the flash drive:
```shell
MICROBIT_DEVICE=$(diskutil list external physical "/Volumes/NO NAME" | awk '/NO NAME/ {print "/dev/" $NF}')
diskutil rename "$MICROBIT_DEVICE" "MICROBIT"
```

When running
```shell
pxt build --deploy
```

It ends successfully and outputs:
```
Using target microbit with build engine yotta
  target: v7.0.54 /Users/pavel/Microbit/microbit-christmas-tree/node_modules/pxt-microbit
  pxt-core: v11.1.10 /Users/pavel/Microbit/microbit-christmas-tree/node_modules/pxt-core
building /Users/pavel/Microbit/microbit-christmas-tree
copying binary.hex to /Volumes/MICROBIT/
```

However, in a short while, the device:
1.  Displays error `504`
2. The drive is unmounted and re-mounted
3. The drive name is changed back to `NO NAME` 
4. There is a file called `FAIL.TXT` which says
    ```
    error: The transfer timed out.
    type: transient, user
    ```
