### ISSUE TITLE
issue - black line showing acceleration 

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#61]
enter this code

```
basic.forever(() => {
    led.plotBarGraph(input.acceleration(Dimension.Strength), 0);
});
```

when you compile the following code onto the micro:bit, i would expect the black line to follow the same logic as the colored red line (micro:bit simulator). however, this is not the case. The black line is constantly moving while the micro:bit is stationary

![image](https://cloud.githubusercontent.com/assets/11206682/15190127/28aa5e30-1763-11e6-9852-fad62f59cc3a.png)

![image](https://cloud.githubusercontent.com/assets/11206682/15190060/cd31db96-1762-11e6-95f6-b3d47d0da474.png)

That being,  you must move the micro:bit in a certain direction to trigger a waving black line. The black line should represent the amount of g's on the micro:bit. Since we subtracted gravity from Magnitude/Strength, a teacher would not want to see a wavering black line without moving the micro:bit.

**Comment by mebrauns** [comment]
i really do not like the way the acceleration of strength is constantly registering a number. after we account for gravity and the 2nd micro:bit is not moving, the 2nd micro:bit should be at 0. 

here is the code...

```
basic.forever(() => {
    radio.sendNumber(input.acceleration(Dimension.Strength) - 1023);
});
radio.onDataReceived(() => {
    led.plotBarGraph(radio.receiveNumber(), 0);
});
```

here is a screenshot. 

![image](https://cloud.githubusercontent.com/assets/11206682/15222127/17b42104-1823-11e6-9c1f-a9f00f9a47fc.png)


the black line should be flat and the number should be 00 unless the micro:bit is moving. that would be my assumption. Am I missing something?

**Comment by mebrauns** [comment]
maybe the number is changing because of the LED display. Is that why there is a constant black data on the second micro:bit ?

**Comment by pelikhan** [comment]
Physical sensors have noise in the data. you are seeing that. Agreed I could change slightly the charting to smooth it out.

**Comment by pelikhan** [comment]
It’s probably some small variations of data but it looks bigger because of different scales.
