### ISSUE TITLE
Extended choice of languages

### ISSUE THREAD

**Issue by marekmansell** [Microsoft/pxt-microbit#617]
Hi everyone,

The microbit blockly strings have been translated on crowdin to many other languages besides the 12 ones which are displayed in the top right menu of the app (https://makecode.microbit.org/). Is there a friendlier way of opting for one of these other languages besides the process of changing your browser's page language settings, deleting your cookies and refreshing the site? If not, this is a feature many would appreciate.

**Comment by jangondol** [comment]
Possible ways to implement this:

1) https://makecode.microbit.org/sk for the Slovak language (easy to remember, clean URL)

2) https://makecode.microbit.org/?lang=sk_SK (including language code in the query string) -- advantage: could be appended to any URL, so it would be useful for forcing a specific language for embeds etc.

If you come up with something even better, please leave a comment.

**Comment by pelikhan** [comment]
There are two ways in place already:

1) option (2) is live already
2) change your browser language and we’ll serve the language automatically

We have a backlog to assess and enable the languages that are sufficiently translated. Any particular in mind?

**Comment by marekmansell** [comment]
Thanks! This will definitely help :-)
maybe it is just me, but I was not able to find this link (where is it mentioned?)

@pelikhan the language we had in mind is Slovak

**Comment by pelikhan** [comment]
Update coming soon.

**Comment by abchatra** [comment]
This is addressed.
