### ISSUE TITLE
cards: not working with radio

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#62]
1 enter this code as a card macro

```
basic.forever(() => {
    radio.sendNumber(input.acceleration(Dimension.Strength) - 1023);
});
radio.onDataReceived(() => {
    led.plotBarGraph(radio.receiveNumber(), 0);
});
```

2. only 2 cards are produced. there should be cards that represent all the functions in the code above
![image](https://cloud.githubusercontent.com/assets/11206682/15221030/9a13c438-181e-11e6-92c0-938cd09754cd.png)

**Comment by pelikhan** [comment]
Only top level statements supported for cards.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by pelikhan** [comment]
Try 
```
input.acceleration(Dimension.Strength)
radio.sendNumber(0);
basic.forever(() => {
});
radio.onDataReceived(() => {
}); 
radio.receiveNumber()
led.plotBarGraph(, 0);
