### ISSUE TITLE
How to add Blocks to a HTML page

### ISSUE THREAD

**Issue by stritti** [Microsoft/pxt-microbit#623]
Is ist possible to add source examples in Block-style to a web page?
I would prefer this instead of creating unchangeable screenshots.

**Comment by pelikhan** [comment]
See https://makecode.microbit.org/blocks-embed .

**Comment by stritti** [comment]
Great, haven't  saw it. THX!

**Comment by stritti** [comment]
I was not able to understand the mentioned docu. I have reverse enngineered the rendering in of the documentation itselfe and created a gist: https://gist.github.com/stritti/e47d780cedc0146e9c3b7e7c0e8eee68

**Comment by stritti** [comment]
You are right, @pelikhan. But I was not really able to follow the documentation you provided.
Maybe a small vanilla JS example could really help.

**Comment by pelikhan** [comment]
Let me see if i can fiddle one.

**Comment by pelikhan** [comment]
See https://jsfiddle.net/ndyz1d57/1/

**Comment by stritti** [comment]
Awesome, many thanks @pelikhan! This helped me a lot! Really simple solution. 
I thought far too complicated.

**Comment by pelikhan** [comment]
Which web site are you instrumenting ? :)

**Comment by stritti** [comment]
I am currently set up a HTML5-presentation for the "GirlsDay" in Germany: https://github.com/stritti/girlsday-einfuehrung-informatik

It is currently very basic, I just wanted to see, that I need not to screenshot the Blocks first :)

**Comment by stritti** [comment]
Now I updated rendering successfully and could start in the next days adding the useful content. The frame is ready.

**Comment by dnowba** [comment]
> Now I updated rendering successfully and could start in the next days adding the useful content. The frame is ready.
But how if I just want to show one block?  for example, a "input.lightLevel()" block ???

**Comment by stritti** [comment]
> > But how if I just want to show one block?  for example, a "input.lightLevel()" block ???

Have a look at https://github.com/stritti/girlsday-einfuehrung-informatik there are some examples.

**Comment by dnowba** [comment]
I've test it, but it is not working when rendering single Circle Shape Block.

**Comment by stritti** [comment]
in my environment it works fin. Have a look on this (German) slide: https://stritti.github.io/girlsday-einfuehrung-informatik/#/Blocks-Variablen 
associated sources: https://github.com/stritti/girlsday-einfuehrung-informatik/blob/a65e4e2460b1e09ad24e05c339d464175bf5985f/src/index.html#L483

Maybe you could provide a source example.
