### ISSUE TITLE
Infection game does not seem to translate into blocks

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#629]
micro:bit-support:4078
@riknoll @pelikhan @abchatra  The code still does not convert to blocks,

https://makecode.microbit.org/94575-30587-68669-98014

As with original request here https://github.com/Microsoft/pxt/issues/2340 the docs should be updated if this project can only run from Javascript.

**Comment by pelikhan** [comment]
Added, https://makecode.microbit.org/projects/infection
