### ISSUE TITLE
yotta warning during build  invalid enum initializer, PIN_CAPABILITY_AD...

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-microbit#63]
info: download nrf51-sdk@v2.2.0+mb4 from GitHub lancaster-university/nrf51-sdk
rebuilding dal.d.ts...
built/yt/yotta_modules/microbit-dal/inc//drivers/MicroBitPin.h(85): invalid enum initializer,     PIN_CAPABILITY_AD = PIN_CAPABILITY_DIGITAL | PIN_CAPABILITY_ANALOG,
built/yt/yotta_modules/microbit-dal/inc//drivers/MicroBitPin.h(85): invalid enum initializer,     PIN_CAPABILITY_AD = PIN_CAPABILITY_DIGITAL | PIN_CAPABILITY_ANALOG,
*** C:\yotta\python\Scripts\yotta.exe build

**Comment by abchatra** [comment]
If you still see this issue reopen
