### ISSUE TITLE
Windows 10 MakeCode BETA - not downloading to micro:bit

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#633]
micro:bit-support:[4151](https://support.microbit.org/helpdesk/tickets/4151)

Using Chrome 63 and a Windows 10 machine with the BETA release of MakeCode for the micro:bit:
 - Create a simple program, plugged in micro:bit and selected Download.
 - Error displayed "Oops, we couldn't find your micro:bit"

![image](https://user-images.githubusercontent.com/31242877/35908649-3a21c1fe-0be9-11e8-8d01-ed0e5463e428.png)

User followed the troubleshooting guide, the cable is correct and the firmware is updated to 0243. The error still occurs.

This may be machine specific
Tagging @Lorrainbow and @jaustin to add any further info.

**Comment by pelikhan** [comment]
Is this happening in Chrome or in the Windows app?

**Comment by Lorrainbow** [comment]
This is the Windows app.
Jonny traced the problem to a driver problem on Lenovo. He took this screenshot for reference

![screenshot1](https://user-images.githubusercontent.com/5673444/35909103-6d101e0c-0bea-11e8-92d3-d55de2958f59.png)

**Comment by pelikhan** [comment]
We are going to document this. It is unlikely we can fix this soon.

________________________________

**Comment by microbit-mark** [comment]
In beta

**Comment by microbit-mark** [comment]
duplicate of #636 which has more info
