### ISSUE TITLE
Filesystem: settings read number, add one and save it crashes at 10

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt-microbit#635]
Moved from: https://github.com/Microsoft/pxt/issues/3272
___
microbit.org-ticket: 3006

The following program uses the File system "settings" block to store a number and add one on each reset. After 10 resets my the micro:bit crashes. 

**Code:**

![microbit-screenshot](https://user-images.githubusercontent.com/29712657/31715816-271eb9b6-b3fd-11e7-92c9-0f0492031b36.png)

```
let cal = 0
cal = files.settingsReadNumber("cal")
basic.showNumber(cal)
cal = cal + 1
files.settingsSaveNumber("cal", cal)
basic.showNumber(cal)
```

https://makecode.microbit.org/_iPbajwAA0eT8

**Effect:**

The program reads the value saved, displays it, adds one, saves it, and then displays the number it just saved.
This works fine until it reaches the 9 to 10 transition. The following gif shows:
* 7->8
* reset
* 8->9
* reset
* 9 -> error
* reset, nothing happens
* reset, nothing happens
* reset, nothing happens

![fs_numbers-iloveimg-compressed](https://user-images.githubusercontent.com/29712657/31715605-71df2de2-b3fc-11e7-846b-9e975d0e9930.gif)

This is not explicity to storing the number 10, as if I change the `cal = cal + 1` line with any other value (like `cal = cal + 10`) it still fails after 10 resets.

**Comment by pelikhan** [comment]
At this point it is best to disable the file system package.

________________________________

**Comment by jaustin** [comment]
@carlosperate can we try to reproduce this with C/C++ only in the DAL and see if we see it there?

**Comment by pelikhan** [comment]
This might be an interaction with PXT and the DAL memory allocator as well.

________________________________

**Comment by microbit-carlos** [comment]
I've create a C/C++ program with the DAL using the same file system operations and haven't been able to replicate.
Source code and hexes here: 
[fs-test.zip](https://github.com/Microsoft/pxt-microbit/files/1744631/fs-test.zip)

**Comment by pelikhan** [comment]
This is because we tweak the allocatable memory locations in PXT so the scenario is slightly different.

________________________________

**Comment by finneyj** [comment]
Strange that this is only showing up on a MakeCode build, and not a native C build. It does make me wonder if the set of flash pages we are using is somehow unsafe.

@pelikhan is it possible to try a build of this app under MakeCode that puts the FileSystem in a static, "known safe" location (say, near the top of flash), and determine if this bug still persists?

p.s. The magic number "10" is kinda interesting. From memory, 10 is the number of file table entries in a directory entry... in other words, after ten open/close/delete cycles the file system will go looking for a new block of flash to use.

**Comment by jaustin** [comment]
I think looking at how the filesystem is allocated in PXT would be good. 

I tried the following program to see if it would have the same '10-based' issues - it's doing similar to what the save number is doing, though I guess with a smaller file each time.

https://makecode.microbit.org/_E9F6E9aTDLtz

I get to iteration ~60 and then it crashes and I have to reflash the micro:bit to make it run again.

**Comment by jaustin** [comment]
https://github.com/Microsoft/pxt-filesystem/blob/master/files.cpp#L33 this is where the filesystem is allocated in pxt-filesystem

**Comment by microbit-sam** [comment]
The changes in dal-integration seem to have solved this, I've reached 250 and I'm still going with this program
```
let cal = 0
cal = files.settingsReadNumber("cal")
basic.showNumber(cal)
cal = cal + 1
files.settingsSaveNumber("cal", cal)
basic.showNumber(cal)
control.reset()
```

**Comment by microbit-carlos** [comment]
Thank you Sam for testing this issue, since it looks like it has been resolved I'll close this ticket.
