### ISSUE TITLE
Windows 10 App: Direct download doesn't work on some Lenovo computers

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#636]
On some Lenovo computers the 'download' button in the Windows 10 app doesn't work work because the micro:bit can't be detected...

This may be due to a driver issue - Lenovo appears to have a different driver setup for HID devices compared to my Windows 10 machine, and others we've seen where the micro:bit works.

First, my machine where things work:
(OS Name	Microsoft Windows 10 Pro
Version	10.0.16299 Build 16299)
(View devices by container in Device Manager)
![image](https://user-images.githubusercontent.com/147113/35934400-68086a04-0c35-11e8-820a-b25f82333a32.png)

To confirm that this is the same device, here's the hardware ID of the 'HID Compliant Vendor Defined Device'
![image](https://user-images.githubusercontent.com/147113/35934452-939367c8-0c35-11e8-8991-09a007ad3862.png)
Here's the 'Driver' tab for that device
![image](https://user-images.githubusercontent.com/147113/35934542-ce585896-0c35-11e8-989c-5b3739d45e34.png)
And here's what I see when I click "Driver Details"
![image](https://user-images.githubusercontent.com/147113/35934570-e0781e30-0c35-11e8-810a-bf04fdec9f36.png)

Compare this to what @Lorrainbow sees:
Device Manager by container shows the DAPLink stuff *not* nested at a top level
![image](https://user-images.githubusercontent.com/147113/35934813-7dc52548-0c36-11e8-8a4c-69651222a5ad.png)
The 'HID Compliant Vendor Defined Device' matching DAPLink IDs
![image](https://user-images.githubusercontent.com/147113/35934877-af54ed14-0c36-11e8-8d1b-edfe197de28c.png)
The 'Driver' tab
![image](https://user-images.githubusercontent.com/147113/35934932-d41e51d0-0c36-11e8-8524-58c1b4c31dd9.png)
And this time clicking 'Driver Details' tells you more
![image](https://user-images.githubusercontent.com/147113/35934957-eff4597c-0c36-11e8-8ae9-154aa108e7ea.png)

@DaveAtKitronik has the same issue, also on a Lenovo machine (this may be a red herring, of course) so could also provide more debugging I hope.

I can't quite get my head around what the driver tab is telling me - it appears to be telling me I have the same HID driver at the same version, but when I click details, we see a different vendor...  We can get more detail but I'm not sure where to look at the moment.

**Comment by microbit-mark** [comment]
@pelikhan Did you say there was a fix for this in beta?

**Comment by pelikhan** [comment]
No repro, but we do show a "download" button now if the download fails.

**Comment by pelikhan** [comment]
We do not have a solution for this. However, when a download fails, we provide a button to download the .hex file as a file as usual.

**Comment by DaveAtKitronik** [comment]
Can reproduce on my Lenovo Win 10 laptop. 
![image](https://user-images.githubusercontent.com/25896029/36541215-1cdcbc28-17d5-11e8-84e8-929976f6fbf2.png)

Not sure which of the devices I need to put more details up on.
Download on the Win10 app gives:
![image](https://user-images.githubusercontent.com/25896029/36541431-c9e2a50e-17d5-11e8-825f-146614719dd5.png)

**Comment by abchatra** [comment]
We haven't heard this in the wild and there is a workaround to save the file manually. Closing this bug for now as we have no actionable work here.

**Comment by Fieel** [comment]
Same problem with my Lenovo Yoga 3rd Gen. running Win10 Can't detect the micro bit at all.

My desktop detects it no problem though.

No fixes?

**Comment by abchatra** [comment]
@Fieel what version of the firmware do you have? You need version 0241 or higher
Follow these instructions: https://makecode.microbit.org/device/windows-app/troubleshoot
