### ISSUE TITLE
W10 app: Excel data export only works when Excel is not open

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#641]
Steps to reproduce
Use this program:
https://makecode.microbit.org/_0Y5VMX004gfC

Using the simulator:
Click the 'a' button a number of times, changing the light level
Now click the 'A+B' button (the simulator data viewer should show up)
Once you've opened the serial data viewer, click the A+B button again
Click the 'export' button (blue disk)
IF Excel is not open, this works, if it's already open, it doesn't seem to do anything, although the 'exporting' message is shown

This is on Windows 10  version 1709  build 16299.192

**Comment by pelikhan** [comment]
Good catch

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/pull/3882

**Comment by pelikhan** [comment]
We now encode the date/time in the file name to avoid this issue.
