### ISSUE TITLE
Scrollbars cover the documentation drawer handle (Win 10, Chrome, Edge, App)

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#643]
If you close the documentation 'drawer' using the grey handle containing an arrow, then on an average sized project with scroll, the scrollbar covers the drawer.

![image](https://user-images.githubusercontent.com/147113/36220905-3479cafa-11b4-11e8-8ae8-cf1ebf65bcba.png)

Is there any control over the size of the drawer button? I think previously I never noticed this on macOS because the scrollbars autohide? Or were smaller?

**Comment by microbit-carlos** [comment]
Are you using a computer with a touch screen? It's possible the Blockly scroll bar size is increased in that scenario.

On a similar note, when the documentation drawer also has a scrollbar, it can become very difficult to scroll the documentation by trying to click its scrollbar with the mouse, as the Blockly scrollbar blocks most of that area (all that vertical space, not just the parts covered by the drawing of the blockly scrollbar itself).

**Comment by jaustin** [comment]
Yes, I am! I'm not in Tablet mode, but I am on a touch-enabled device.
