### ISSUE TITLE
Serial issue

### ISSUE THREAD

**Issue by myka-x** [Microsoft/pxt-microbit#66]
Serial port seems to lock up when using plotBarGraph and serial.WriteLine simultaneously. 

It works as expected using only plotBarGraph but does not work as expected using only serial.WriteLine, so I expect the issue is here. 

Here is the project: https://m.pxt.io/rgmitxlxag

And here is the code: 
```
let voltage = 0;
let higherLimit = 200;
basic.forever(() => {
    voltage = pins.analogReadPin(AnalogPin.P0);
    led.plotBarGraph(voltage, higherLimit);
    serial.writeValue("voltage", voltage);
});
input.onButtonPressed(Button.A, () => {
    basic.showNumber(voltage);
    basic.pause(150);
});
```

**Comment by myka-x** [comment]
Input on P0 is 0-3V.

**Comment by myka-x** [comment]
I found another way this issue presents with a Radio test where I have 2 Microbits running two different bits of code: Transmitter and Receiver. 

The Transmitter reads analog P0 (0-3V) and sends the number via Radio and sends it via Serial. Button A shows the number. 

Receiver sets a variable to radio.receiveNumber and then sends that number to serial. Button A sows the number.

Again the serial data does not stream but instead comes out as a clump of data only when I unplug it from USB suggesting that it is getting through but perhaps not as a stream, line by line, of data. 

---CODE----

RadioTransmitter-03
https://m.pxt.io/jcoubwuudo

let voltage = 0;
basic.forever(() => {
    voltage = pins.analogReadPin(AnalogPin.P0);
    radio.setGroup(1);
    radio.sendNumber(voltage);
    serial.writeNumber(voltage);
});
input.onButtonPressed(Button.A, () => {
    basic.showNumber(voltage);
    basic.pause(150);
});

RadioReceiver-03
https://m.pxt.io/xuplkpqvjq

let data = 0;
radio.setGroup(1);
basic.forever(() => {
    data = radio.receiveNumber();
    serial.writeNumber(data);
});
input.onButtonPressed(Button.A, () => {
    basic.showNumber(data);
});

**Comment by pelikhan** [comment]
serial.WriteValue seems to be having issues. Investigating. Meanwhile, simply do

```
let voltage = 0;
let higherLimit = 200;
basic.forever(() => {
    voltage = pins.analogReadPin(AnalogPin.P0);
    led.plotBarGraph(voltage, higherLimit);
});
input.onButtonPressed(Button.A, () => {
    basic.showNumber(voltage);
    basic.pause(150);
});
```

**Comment by pelikhan** [comment]
Could you try again? We'll pulled in a fix from the C++ runtime around serial support.

**Comment by myka-x** [comment]
This seems to work now as expected with plotBarGraph and serial.writeValue. 

serial.writeNumber() outputs all the numbers on one line without any break in between (for example '\n'). It used to work the same as the serial output from plotBarGraph. Is this by design?

**Comment by pelikhan** [comment]
Right, writeNumber just writes the number, no new line.
