### ISSUE TITLE
serial.writeBuffer() got error

### ISSUE THREAD

**Issue by lioujj** [Microsoft/pxt-microbit#664]
18 FEB I found there is some problem on serial.writeBuffer() block. It worked well on 17 FEB. But on 18 FEB , everytime I wanted to edit the code or download the hex from makecode, the error message prompted up "Program error: pxsim.serial.writeBuffer is not a function". What is the problem? Thanks.
![buff1](https://user-images.githubusercontent.com/34760803/36383080-06dc0480-15c6-11e8-92d6-67aa965ad10d.png)

**Comment by pelikhan** [comment]
write buffer is fixed in beta, try MakeCode.microbit.org/beta

________________________________

**Comment by lioujj** [comment]
The beta is OK. Thanks.
![20180220_005828](https://user-images.githubusercontent.com/34760803/36389268-7d51141c-15d9-11e8-9dea-9207d7c1858b.jpg)
