### ISSUE TITLE
Dropdown visibility

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#666]
micro:bit-support:4615

When selecting from long dropdown lists in (for example, the Control Package 'On Event' block) parts of the list will often not be visible, and there is no scroll bar to enable them to be accessed. 

Even zooming out, or making sure the block is at the edge of the display area does not affect this - there are still options unavailable. The options are accessible if you use the JavaScript editor, but not in the blocks environment. 

This shows the blocks editor with the limited list
![image](https://user-images.githubusercontent.com/31242877/36422413-c95252d6-1633-11e8-97c8-991f37c7d026.png)

This shows the Javascript editor with different options, and the presence of a scroll bar to access all of them, regardless of where you are on the screen. 
![image](https://user-images.githubusercontent.com/31242877/36422385-af24c1c8-1633-11e8-82bc-51ded96a5ce4.png)

This bug is not limited to the Control Package block, but has been noted on any long dropdown list and on Firefox 58 and Chrome 64

**Comment by microbit-mark** [comment]
@abchatra Can you take a look at this one? Is it possible to introduce a scroll bar  in blocks?

**Comment by abchatra** [comment]
@samelhusseini can you take a look when you have some cycles?

**Comment by samelhusseini** [comment]
Fixed in latest Blockly, marking for next release.

**Comment by abchatra** [comment]
I don't want to take new blockly for this Friday release. Lets keep this for the next release.

**Comment by abchatra** [comment]
This is fixed in alpha
