### ISSUE TITLE
Win10 App - navigation error on load

### ISSUE THREAD

**Issue by myka-x** [Microsoft/pxt-microbit#67]
Running Win10 Enterprise 
codemicrobit app gives the following upon loading:

![codemicrobit-navigationerror](https://cloud.githubusercontent.com/assets/18334030/15373900/98927f90-1cfc-11e6-9220-774cede33c11.JPG)

**Comment by pelikhan** [comment]
This app is outdated. You have to build it from the sources. We’re waiting for the app to come into the store officially.

**Comment by pelikhan** [comment]
The codemicrobit app is outdated and will be removed.
