### ISSUE TITLE
Editor appends variable and errors 'packet has no property Serial2'

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#671]
This is similar behaviour to https://github.com/Microsoft/pxt/issues/3399 but doesn't appear to have been fixed.
Steps.
 - Add on radio received block
 - Add serial variable
 - serial is renamed as serial2 and throws error
![serial2](https://user-images.githubusercontent.com/31242877/36532109-c8311ba0-17b7-11e8-9880-2d175d4c4fc9.gif)

**Comment by abchatra** [comment]
@riknoll is going to port this.

**Comment by pelikhan** [comment]
Fix in v0.14.22.
