### ISSUE TITLE
Bluetooth UART send string limit

### ISSUE THREAD

**Issue by marukqs** [Microsoft/pxt-microbit#679]
Hello,

It is impossible to send long text strings using BLE UART. According to https://makecode.microbit.org/reference/bluetooth/start-uart-service there is 20 characters  string limitation for receiving and sending strings via UART.

Is there any way to send longer strings using visual blocks: for example during the lesson students sometimes need to send their full names or URLs and for beginners splitting strings is too complex.

1) Could you please advice why there is such a limit?
2) I would appreciate ideas how to modify or create a new BLE UART component to fix this issue?

Thank you for great software!

KR

Marijus

**Comment by abchatra** [comment]
This is a system limitation of the bluetooth. Only way to solve is multiple strings and concat them using join block. There
