### ISSUE TITLE
documentation - broken links and not well defined for Boolean

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#68]
Issues with Boolean: less than symbol. 

1. broken link to go to the docs

2. not well defined for the Boolean block in the editor

![image](https://cloud.githubusercontent.com/assets/11206682/15400739/73c14db8-1da1-11e6-8119-9900b55170a4.png)

**Comment by thomasdenney** [comment]
The link is no longer broken but the documentation doesn't change when the operator changes.

**Comment by thomasdenney** [comment]
Resolved by [this pull request](https://github.com/Microsoft/pxt/pull/123)
