### ISSUE TITLE
Mobile: Simulator popup button doesn't work after dragging a block

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#681]
Steps to reproduce:
* Visit makecode.microbit.org on an Android phone
* click the simulator show button immediately - it works. 
* hide the simulator again
* place a block on the canvas
* click the simulator show button again. It doesn't work this time

Clicking back into the block gallery and then trying the simulator button again works
(@carlosperate this is a workaround to what we were seeing earlier)

**Comment by microbit-mark** [comment]
This seems to be fixed in v1
[ali_nOPS27.82-87mark10162018163637.mp4.zip](https://github.com/Microsoft/pxt-microbit/files/2483840/ali_nOPS27.82-87mark10162018163637.mp4.zip)

**Comment by abchatra** [comment]
Fixed
