### ISSUE TITLE
Android Chrome: opening help/more dropdown doesn't close already opened dropdown

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt-microbit#682]
Android 7.0.0
Chrome 64.0.3282.137

http://makecode.microbit.org/beta
makecode.microbit.org version: 0.14.20
Microsoft MakeCode version: 0.17.10
C++ runtime version: v2.0.0-rc11

Opening the "help" or "more" dropdown doesn't close an already opened dropdown:

To reproduce:
* Go to http://makecode.microbit.org/beta
* Open the "more" (cog) dropdown
* Open the "help" dropdown

![e](https://user-images.githubusercontent.com/29712657/36742018-83c24aea-1bde-11e8-840b-c926117c4ef1.jpg)

**Comment by microbit-mark** [comment]
@microbit-carlos  can't recreate this on Android 7.1.2 with same setup

**Comment by microbit-carlos** [comment]
Weird, I can consistently replicate on my device (Samsung S8).

**Comment by pelikhan** [comment]
Help and cog have been merged in mobile view.

**Comment by microbit-carlos** [comment]
Good call, the top bar is not longer cramped as before, thanks @pelikhan!
