### ISSUE TITLE
Code completion suggestion dropdown/widget covered by bottom row

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt-microbit#683]
When the suggestions widget with code completion is displayed below the code the widget can be covered by the editor tools bottom row:

<img width="1510" alt="screen shot 2018-02-27 at 17 02 47" src="https://user-images.githubusercontent.com/29712657/36742865-af61ddee-1be0-11e8-8e8b-4335a76fb665.png">

**Comment by abchatra** [comment]
fixed in alpha
