### ISSUE TITLE
ability to define procedures and functions that are non-unit typed

### ISSUE THREAD

**Issue by bennytheshap** [Microsoft/pxt-microbit#689]
@pelikhan just showed me that the Minecraft chat blocks have the ability for users to define functions that have a non-Unit domain.  Can we please get that for user-defined functions in micro:bit? 

And, as a bonus, can functions be made to return values so that they can be used to build expressions?

Thank you!

**Comment by abchatra** [comment]
We have functions in microbit.

**Comment by bennytheshap** [comment]
Sure, but, unless I'm missing something, right now they'd unit typed. Is it possible to create functions that take or return values via blocks?

**Comment by abchatra** [comment]
Request is for parameters and return values for functions.

**Comment by jaustin** [comment]
If you're going to add parameters and return values (yes! please!) I'd like to consider doing it before v1 comes out of beta - @abchatra is that at all likely?

**Comment by abchatra** [comment]
This is the most requested feature. We plan to add as soon as we have some bandwidth for features. Tricky part is designing parameter types in  blocks (we are static typed). This is likely immediately after v1 release. As they will be new blocks, should be totally backward compatible.

**Comment by jaustin** [comment]
Excellent, thanks for the update

**Comment by abchatra** [comment]
@guillaumejenkins FYI

**Comment by abchatra** [comment]
Fixed in makecode.microbit.org/beta

return semantics are not supported yet. I will file a separate issue for the same.
