### ISSUE TITLE
drop down for play tone... too long

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#69]
you shoul dhave a drop down and a sub drop down after selecting the individual key... right now, too many options for various notes, doesn't appear organized. 

![image](https://cloud.githubusercontent.com/assets/11206682/15410557/4295a44a-1dcf-11e6-8862-8e5873a6eed2.png)

**Comment by pelikhan** [comment]
Not supported. The only thing we can do is reduce the number of notes.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by abchatra** [comment]
We have a plan to do piano picker (https://github.com/Microsoft/pxt/issues/198) which is on our plans. Closing this for now.
