### ISSUE TITLE
Game of life example

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#691]
microbit-support:4783
There are a couple of bugs in the Game of Life in Examples:
Using Firefox 52.6.0.

- click button A in the simulator
- the LEDs go blank
  Sometimes just one LED stays on, depending on the random starting pattern.
  It is meant to display another generation of the Game of Life,
  ie another random-looking pattern.
  On repeated clicking of button A, it is meant to settle down
  to a fixed pattern of a repeating sequence.
  What it actually does is stay blank.

To fix:
This is best done in JavaScript view.
These are two separate errors.
1. In function gameOfLife at line 31, right at the top, before:
  for (let b = 0; b <= 5 - 1; b++) {
add:
  result = [];
2. At about line 35 after:
  // Count the live cells in the next row
add:
  count = 0;
Explanation:
1. The first is quite subtle, and makes the program
produce the wrong patterns.
The reason is that the assignment:
  state = result;
does not copy the value of result, but makes state
refer to the same array as result.
So on the next pass, when you set values in result, you are
actually changing state.  This gives the wrong answers.
Setting result to a fresh empty array fixes the problem.
2. The second bug should be obvious: the count variable just increases on every time round the loop.  It is over 3, so the whole pattern goes blank.

Code in example is not the same as docs, which doesn't exhibit the issue, unless you change to blocks:
https://github.com/Microsoft/pxt-microbit/blob/master/docs/examples/gameofLife.md

The problem is with two "let" statements which define and initialise variables.  The statements seem to be automatically moved out of the function they are in, and put into the initialisation code.  Then they are only executed once, when the algorithm requires that the assignment part should be executed multiple times.  Perhaps it could be fixed by manually copying the "let" statements out of the function, and changing the statements in the function into simple assignments.

Related:

"When converted back to blocks the declaration of weapon is moved out into global scope (as are all non-loop variables in blocks)" (https://github.com/Microsoft/pxt-microbit/issues/149).
Perhaps the cause was the example was changed from being labelled JavaScript to Blocks (https://github.com/Microsoft/pxt-microbit/commit/c6c2167a730b5d742367bee1096e4aa14ae6be8c) and it used to work when JavaScript.
See also https://github.com/Microsoft/pxt/issues/151

**Comment by pelikhan** [comment]
Can you send a PR?

**Comment by microbit-mark** [comment]
@pelikhan I can, just want to check that it should be made against https://github.com/Microsoft/pxt-microbit/blob/master/docs/examples/gameofLife.md as that is not the same code that appears in the browser example

**Comment by abchatra** [comment]
I am closing in favor of https://github.com/Microsoft/pxt-microbit/issues/871
