### ISSUE TITLE
W10 app: serial capture for complex data is confusing

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#695]
Consider a user that would like to be able to log the accelerometer data in x,y,z with time, and then read that out over serial

The following program attempts to do that:
https://makecode.microbit.org/_auL9Jk0fz9Es

(the checkAndErase function is there to let you hold down the A button while rebooting to erase the output file).

To use this, press button A to start logging, then button B to stop logging. Then press A+B to send the file over serial.

This is fine if you just care about one thing, but if you want to export something more CSV-like then the current data capture options don't work very well.

![image](https://user-images.githubusercontent.com/147113/37040789-8d763140-2152-11e8-9e1b-6a1934bb1991.png)

The 'time,x,y,z' comes into the 'data' buffer and the rest of the data ends up in the graph, but the export doesn't include anything except the first column

You can workaround this by adding, say, some arbitrary text to the start of the line like a comma.
![image](https://user-images.githubusercontent.com/147113/37041177-7d0c115c-2153-11e8-93e1-4f19ebf20cba.png)

But this is a bit of a kludge

(The simulator actually behaves differently, I'm about to file an issue for the difference, but the simulator puts text direct in the data buffer not on the graph).

If we remove the timestamps that I have added but keep the comma (IE so there is chance of duplicate data) then there's a further problem of grouping and being unable to graph that easily by copy/pasting the data out:
![image](https://user-images.githubusercontent.com/147113/37041536-595fae66-2154-11e8-9b04-f603780ff899.png)

Some suggestions that would resolve this for me
1: We should special-case comma separated values and plot them all, and allow them to be all exported via the CSV feature
2. We should *also* put complex data into the buffer.
3. We should allow a simple 'raw' data export from that box. A simple .txt file without the 'repeated data joining' would be great. 

I still think presenting 'file' objects to download (even drag into the filesystem) from the 'read to serial' block would be ideal too.

**Comment by jaustin** [comment]
[microbit-Fast-Data-Collection-graph-eating.zip](https://github.com/Microsoft/pxt-microbit/files/1785810/microbit-Fast-Data-Collection-graph-eating.zip)

**Comment by pelikhan** [comment]
CSV support in https://github.com/Microsoft/pxt/pull/3876

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-microbit/issues/695

**Comment by jaustin** [comment]
Thanks Peli, that was super quick! ⏩ ⏩

**Comment by pelikhan** [comment]
serial->writeNumbers will generate a CSV line entry. https://github.com/Microsoft/pxt-microbit/pull/699

**Comment by mobluse** [comment]
Maybe the serial data for Show Data Simulator and Show Data Device could be compatible with Arduino IDE Serial Plotter, which has recently been updated to handle labels for both CSV and name-value pairs, see the bottom of the page on https://github.com/arduino/Arduino/issues/4180 .

**Comment by pelikhan** [comment]
@mobluse do they have docs? what is the format?

**Comment by abchatra** [comment]
The original issue is fixed. Please file a new feature request with details if this is still relevant.
