### ISSUE TITLE
W10 app: Simulator and device behave differently WRT logging text with numbers

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#696]
Consider the following program

https://makecode.microbit.org/_dqmcAMcXbL4T

On the simulator the data all ends up in the bottom box (IE not the graph)

When run on the micro:bit it gets eaten by the graph
![image](https://user-images.githubusercontent.com/147113/37042548-8f4ebfb0-2156-11e8-992d-b9b385bf4c05.png)

I think the same thing should happen in both situations, and the simulator behaviour is better.

**Comment by pelikhan** [comment]
This script is deleted too.

**Comment by jaustin** [comment]
[microbit-Fast-Data-Collection---simulator-different.zip](https://github.com/Microsoft/pxt-microbit/files/1785706/microbit-Fast-Data-Collection---simulator-different.zip)

**Comment by abchatra** [comment]
I don't see any serial write in the attached hex file. Original link is lost. Please provide the repro
