### ISSUE TITLE
Serial view erases undo/redo history

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#697]
Switching to the serial output view seems to break the undo flow.

![serial view removes undo](https://user-images.githubusercontent.com/147113/37043117-c6db8232-2157-11e8-9d15-71c2845c8ba5.gif)

**Comment by pelikhan** [comment]
Undo/redo across editors is currently not supported.

**Comment by jaustin** [comment]
I think it's reasonable that for the user, switching to serial view doesn't feel like switching 'editor' - is there a way to preserve the edit history for blocks alone when switching to serial view? As it isn't an editor, it seems more straightforward?

I can see that trying to maintain undo when switching between actual editors is hard/not sane, but this seems like a different case?
