### ISSUE TITLE
break tag does not work

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#7]
1 click on a quiz

2 http://localhost:3232/lessons/lucky-7/quiz

3 broken tag

![image](https://cloud.githubusercontent.com/assets/11206682/14092575/c4616e6a-f4fc-11e5-8948-58956a9de3fd.png)

4 would expect this tag is still available, so there is space for a student to write their answers

**Comment by pelikhan** [comment]
Try a line with 2 spaces.

Sent from Outlook Mobile<https://aka.ms/djubve>




On Mon, Mar 28, 2016 at 3:51 PM -0700, "Michael Elliot Braun" <notifications@github.com<mailto:notifications@github.com>> wrote:


1 click on a quiz

2 http://localhost:3232/lessons/lucky-7/quiz

3 broken tag

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fcloud.githubusercontent.com%2fassets%2f11206682%2f14092575%2fc4616e6a-f4fc-11e5-8948-58956a9de3fd.png&data=01%7c01%7cjhalleux%40microsoft.com%7cd362b09bb8c64565839508d3575b87b9%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=9BsYQRB1b%2f3%2bIy%2biHBT3w%2flbIkpciJHrkdikcPl3Aps%3d>

4 would appear this tag is still available, so there is space for a student to write their answers

-

**Comment by pelikhan** [comment]
Fixed.
