### ISSUE TITLE
Download fail from web - Edge/Acer

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-microbit#700]
Using Edge on an Acer Travel Mate Spin B (one of the cheap Win10 devices).
Download doesn't work.  Microbit shows up as a drive fine, and it looks like it's saving but nothing shows up on the hardware.  Tried both USB ports, different microbits, different cables.  Not sure what's going on...
![acer](https://user-images.githubusercontent.com/22108954/37169899-44dc79e0-22d7-11e8-9f6e-69fb39250264.jpg)

**Comment by abchatra** [comment]
@Jaqster Looks like a microbit hardware issue to me. Did you try different microbit?

**Comment by abchatra** [comment]
No further reports
