### ISSUE TITLE
Checking rotation in fibre blocks exection

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#703]
The following program works on the emulator but stops executing on the microbit when the button A is pressed: [hex.txt](https://github.com/Microsoft/pxt-microbit/files/1798059/microbit-issue-min.hex.txt)

![microbit-screenshot 1](https://user-images.githubusercontent.com/29712657/37224709-30804918-23cc-11e8-86fc-bf906733b9b6.png)

The top forever block shows an animation to be able to tell when the program stops executing.

The forever block on the left only executes when the button a is pressed via flag. This is the portion of the program that causes the issue.

The inactive blocks on the right side of the screenshot show versions of that forever fibre that do work, so it's some combination of the accelerometer and those two pause blocks inside the if staments.

If the `run` flag that's enabled on button pressed is removed (so the code starts running from start-up) then the program works fine as well.

The micro:bit doesn't actually crash, as the display still shows one of the heart icons (no animation) instead of the 3 or LEDs it would on a crash:
<img src="https://user-images.githubusercontent.com/29712657/37225103-7b8b75b2-23cd-11e8-9983-911fafd0fbb6.gif" width="50%">

**Comment by abchatra** [comment]
Closing more than an year old bugs. If this still reproduces please reopen.
