### ISSUE TITLE
Network request error when downloading packages

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#706]
microbit-support:#4902

Users are still reporting a network request error when using Neopixel
Relates to https://github.com/Microsoft/pxt/issues/3785

In this case 16 concurrent users Using Chrome 64 on Win10, 6 reported errors

@pelikhan was the fix made live?

**Comment by pelikhan** [comment]
The fix is live for a few weeks now. @Brahma<mailto:abchatra@microsoft.com> do we log when we send 429?

________________________________

**Comment by microbit-mark** [comment]
@Lorrainbow managed to capture the error on this and reported "in a class of 29 students about the first 10 managed to get them installed then it failed to load for anyone else."

![image](https://user-images.githubusercontent.com/31242877/37596993-e9a3b0e6-2b75-11e8-89e3-f14118b99582.png)

**Comment by microbit-mark** [comment]
@abchatra @pelikhan Any update on this. This is the third report of the issue, so it's a priority for us to fix.

**Comment by pelikhan** [comment]
Probably.

________________________________

**Comment by pelikhan** [comment]
Ask the logs :)

**Comment by abchatra** [comment]
I don't see 429 anywhere in my logs. Its quite possible we don't log it. 

I am able to reproduce the problem in private session with caching cleared.

Looks like we make lot of requests to backend around 10 per load of neopixel.
![image](https://user-images.githubusercontent.com/6107272/37857286-19eb402c-2eb7-11e8-963c-ec85ebffed93.png)

**Comment by abchatra** [comment]
I will take a look.

**Comment by pelikhan** [comment]
@microbit-mark in /beta (v0.14.29), the client caches github package information (offline cache actually) so the number of request should go down AND you should be able to reload the packages without internet connectivity.
This is ortogonal to the throttling investigation but it will help with robustifying the feature.

**Comment by microbit-carlos** [comment]
Waris has seen today an issue loading packages in about half of the computers in a class of around 30.

When adding a new package from Tinkercademy the editor get's stuck on this screen:

![image](https://user-images.githubusercontent.com/29712657/38242643-3afb1b74-372d-11e8-8226-1696fbedace4.png)

As this was today in the non-beta editor that would be version:
makecode.microbit.org version: 0.14.22
Microsoft MakeCode version: 0.17.12
C++ runtime version: v2.0.0-rc11

**Comment by pelikhan** [comment]
The fix is currently in beta. What package precisely did you try?

**Comment by microbit-carlos** [comment]
It was one of the Tinkercademy packages, but I wasn't present, so don't really know which one. I'll check with Waris in case he remembers.

**Comment by microbit-carlos** [comment]
It was the IOT Environment Kit.

**Comment by microbit-mark** [comment]
microbit-support:5295
Another user reports an issue with the [BitBot package](https://github.com/srs/pxt-bitbot) with same outcome as https://user-images.githubusercontent.com/29712657/38242643-3afb1b74-372d-11e8-8226-1696fbedace4.png

**Comment by microbit-mark** [comment]
Potential to release beta in next couple of weeks

**Comment by gr8ict** [comment]
microbit-support:5619
This a major problem for me teaching with bitbot robots in class.  About 10 can logon and install the bitbot package. Then the error appears and blocks all other requests.  Impossible to use 17 bitbots and for students to do independent work

**Comment by abchatra** [comment]
@gr8ict Sincere apologies. Looks like issue Is not completely fixed. We will immediately look into this.

**Comment by gr8ict** [comment]
Thank you.  You need to
look after those of us trying microbits with whole classes. There aren't many and I feel like giving up when big things like this get in the way.  I've had this unit planned for 8 months and it relies on individual work.


Chris Sharples
e: csharples@gr8ict.com<mailto:csharples@gr8ict.com>
m: 07411 283703
w: www.gr8computing.com<http://www.gr8computing.com>


On 14 May 2018, at 16:53, Abhijith Chatra <notifications@github.com<mailto:notifications@github.com>> wrote:


@gr8ict<https://github.com/gr8ict> Sincere apologies. Looks like issue Is not completely fixed. We will immediately look into this.

-

**Comment by abchatra** [comment]
This is fixed and fix deployed to our backend. @gr8ict please validate.

**Comment by gr8ict** [comment]
I did lesson yesterday with 18 and seemed fine.  big thanks for such prompt action.  May I ask (briefly) what the issue was - useful to be able to mention to students?

**Comment by microbit-mark** [comment]
Great to hear @gr8ict and thanks for fixing @abchatra. I will notify other users of the fix
