### ISSUE TITLE
screenshot in high contrast mode is not high contrast

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt-microbit#719]
If you have high contrast mode on in makecode editor and you right click save a screenshot, it shows as normal white, not high contrast black image.

**Comment by abchatra** [comment]
I am not sure I understand this bug. Can you try alpha and see if it repros? I see a black background.

**Comment by nielsswinkels** [comment]
This is how the editor looks:
![image](https://user-images.githubusercontent.com/5718354/42310000-8cf4120e-803a-11e8-8771-455c87c4ac7f.png)

This is what it looks like when you right click and save screenshot:
![microbit-screenshot 2](https://user-images.githubusercontent.com/5718354/42310060-b9699a84-803a-11e8-9dfd-ba520cb7204d.png)

Shouldn't the screenshot also get a dark background?

**Comment by abchatra** [comment]
Background is dependent on the png viewer. I see folloowing
![image](https://user-images.githubusercontent.com/6107272/42336451-93cc0e94-8038-11e8-8c35-881f4b284986.png)
