### ISSUE TITLE
Working with Strings (String block and concatination)

### ISSUE THREAD

**Issue by gbaman** [Microsoft/pxt-microbit#72]
A few things related to strings.
1 - I could be blind, but am not seeing anywhere to create an actual string block itself? You can easily get one from bottom of ```Math``` can can get a boolean from bottom of ```Logic```, but can't see anywhere to get a string block?
You can simply create the block itself with Javascript simply using
```Javascript
"Hello";
```
Which then creates the String block.
![screen shot 2016-05-24 at 22 15 40](https://cloud.githubusercontent.com/assets/833193/15520223/1dd833ac-21fd-11e6-8e00-ae65d6c4307e.png)

Although I very easily could be missing something, without it you can't for example set a variable to a string?
![screen shot 2016-05-24 at 22 19 56](https://cloud.githubusercontent.com/assets/833193/15520327/ac099738-21fd-11e6-84fb-b655b91af50f.png)

2 - Am not seeing any way to concatenate 2 strings with blocks?
Scratch for example has the join block
![join](https://cloud.githubusercontent.com/assets/833193/15520404/0fccdfd2-21fe-11e6-87e1-3e26f9f6226a.gif)
Could either go down the road of another block (join for example), or use the addition block, given is how the code is doing it underneath anyway, using the ```+``` symbol.
For example:
```Javascript
0 + 0;
"Hello " + "World";
```

**Comment by pelikhan** [comment]
The latest build of blockly changed the way shadow values work. They used to generate a new block when the default value was modified. Not the case anymore.
We're in the process of bringing text/string support in blocks but still a work in progress.

**Comment by gbaman** [comment]
Also as a bit of a side effect of this, there is no way that I can see to compare 2 strings. For example if you get a string from ```radio.receiveString()```, you can't do much with it other than display it.

**Comment by pelikhan** [comment]
Good point. In fact, it should be possible to drop a string in the logic_compare block but somehow the shadow values are misbehaving.

In blocks, we never really supported strings hence the lack of operators currently.

**Comment by abchatra** [comment]
We are moving issues to pxt repo which will be the central repo for issue management: https://github.com/Microsoft/pxt/issues/531
