### ISSUE TITLE
W10 app: Keyboard dissapears in tablet mode

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#726]
Whenyou tap a box to enter a value the keyboard flashes up then disappears, so you cannot enter values for variables, loops etc.

[Video.MOV.zip](https://github.com/Microsoft/pxt-microbit/files/1871094/Video.MOV.zip)

This exhibits on a Dell Inspiron 17 7000 with Windows 10 64 bit, but @jaustin tested on surface book pro and could not recreate.

**Comment by abchatra** [comment]
This should be fixed in new editor. Please validate and let us know.
