### ISSUE TITLE
magnetic-force.md sideloads wrong example onto micro:bit

### ISSUE THREAD

**Issue by tinfoilhatter** [Microsoft/pxt-microbit#73]
According to the existing docs and the embedded code example, I expect /input/magnetic-force.md to load a script that brightens and dims the central LED depending on whether the local magnetic force is getting stronger or weaker. However, it loads some kind of drawing program that displays "DRAW A CIRCLE" and then sketches a shape with the accelerometer.

**Comment by pelikhan** [comment]
When accessing the mangetometer, you first have to go through the calibration cycle. It's quite confusing... and worth explaining!
