### ISSUE TITLE
Bug in radio received signal strength in simulator

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt-microbit#733]
The docs for RSSI (signal) for the radio state:

```
signal - How strong the radio signal is from -128 (weak) to -42 (strong).
```

When I run code in the simulator, the signal is returned as 10.

Reproducible test case - press button A and the number 10 is scrolled on screen.

let signal = 0
radio.onDataPacketReceived( ({ receivedString, signal }) =>  {
    basic.showNumber(signal)
})
input.onButtonPressed(Button.A, () => {
    radio.sendString("TEST")
})
basic.showString("?")

![screen shot 2018-04-10 at 11 24 07](https://user-images.githubusercontent.com/25079586/38551671-b55c4e22-3cb1-11e8-9fb3-aa99c5b16000.png)

I would like this to return -42 instead please (strongest signal).

Thanks.

**Comment by riknoll** [comment]
Will be fixed in next release of beta
