### ISSUE TITLE
Get brightness

### ISSUE THREAD

**Issue by samelhusseini** [microsoft/pxt-microbit#742]
Transferring from pxt: https://github.com/Microsoft/pxt/issues/2849

There is a function to set the brightness of an LED:
led.plotBrightness(x, y, b) / plot [x] [y] brightness [b]

However there isn't a function to retrieve that value:
led.getBrightness(x, y) / get brightness [x] [y]

**Comment by abchatra** [comment]
Fixed. We have led.brightness()
