### ISSUE TITLE
Server time-outs severely delay loading cached MakeCode editor

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt-microbit#744]
Today I've experienced some server issues when loading pages from makecode.microbit.org.

Some of the files were timing out, not all though (as can be seen in the screenshot below), but it caused the http://makecode.microbit.org editor to get stuck in the loading screen for 8 minutes, until the files timed-out properly.
After that point the editor loaded and was working, which is great! Just wondering if there is a way to force a shorter time-out to show the offline editor earlier. 

![image](https://user-images.githubusercontent.com/29712657/38894381-fd6c603e-4284-11e8-9c55-68449856fb8c.png)

**Comment by pelikhan** [comment]
I see that pxtweb.js should have been cached. We can fix this.

**Comment by abchatra** [comment]
I am assuming this is fixed in the latest editor? If not reopen
