### ISSUE TITLE
Add "On pin P0 down" input

### ISSUE THREAD

**Issue by gquintana** [microsoft/pxt-microbit#746]
There is a "On pin P0 pressed" input which waits for P0 to go up then down:
```
1  _  
0_| |_
```
There is a "On pin P0 released" input which waits for P0 to go down:
```
1_  
0 |_
```
I'd like to have an input "On pin P0 down" input which waits for P0 to go up:
```
1  _  
0_| 
```
To compare with JavaScript browser events: there are 3 key events: keydown, keyup and keypressed (=keydown+keyup)

**Comment by abchatra** [comment]
Closing this as we tracking the issue in #963
