### ISSUE TITLE
pulseIn accuracy

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt-microbit#749]
The results from `pulseIn` don't seem very accurate. 

We have a user that tested the Microsoft Sonar package (https://makecode.microbit.org/pkg/microsoft/pxt-sonar), and the echo time was measured in an oscilloscope as 1168us, but the micro:bit reported it as 755us.

Sonar read pulse code is just a simple call to the `pulseIn()` method:
https://github.com/Microsoft/pxt-sonar/blob/master/main.ts#L33

So I've done a couple of simple tests connecting two micro:bits together, one sending a pulse and the other reading it.

For test 1 we have a micro:bit sending, once per second, a high pulse that last 20us (although sometimes it jitters up to 25us):

<img width="991" alt="pulse_1" src="https://user-images.githubusercontent.com/29712657/39063795-1902c8b0-44c4-11e8-9013-0f82462e9af6.png">

The other micro:bit is measuring it with the following code, and measures the pulse to be 15 or 16 us:

```js
while (true) {
    basic.showNumber(pins.pulseIn(DigitalPin.P0, PulseValue.High))
    basic.pause(1000)
}
```

On a second test, with a pulse of 1200us:

![image](https://user-images.githubusercontent.com/29712657/39125391-b5104e88-46f6-11e8-9e96-874ea974851c.png)

The other other micro:bit returns results varying from 774 to 791 us.

**Comment by microbit-mark** [comment]
@abchatra can you take a look at this one

**Comment by pelikhan** [comment]
We need to use the pulse event from microbit dal -- however they do not support time outs which is problematic with ultrasonic sensors.

**Comment by abchatra** [comment]
As per the comments, please open an issue on dal. I am closing this here and will reopen once we have the requisite changes in dal
