### ISSUE TITLE
Unknown label at 'numops::muls'

### ISSUE THREAD

**Issue by Gadgetoid** [Microsoft/pxt-microbit#750]
I seem to be  having trouble building code locally using pxt/yotta that built and ran verbatim in makecode.microbit.org.

I am running this setup in Git Bash on Windows 10, 

* npm 5.8.0
* node 8.9.4

Installed with:

* npm init (and just go with defaults)
* npm install pxt
* pxt target  microbit
* pxt init (again, defaults)
* pxt install

Is my local build environment at fault, or am I missing something?

```
$ cat test.ts
pins.sizeOf(NumberFormat.UInt16LE) * 1;
```

The main.ts code file is empty (I deleted the contents).

```
$ pxt build
Using target microbit with build engine yotta
  target: v1.1.10 C:\...\node_modules\pxt-microbit
  pxt-core: v3.10.16 C:\...\node_modules\pxt-core
main.ts(1,1): error TS9200:   -> Line 55 ('    bl numops::muls'), error: assembly error
   Maybe: bl    LABEL (unknown label at 'numops::muls')
   Maybe: bls   LABEL (opcode name doesn't match at '<name>')
```

And similarly:

```
$ cat test.ts
for(let x: number = 0; x < 10; x++){
    
}
```

```
$ pxt build
Using target microbit with build engine yotta
  target: v1.1.10 C:\...\node_modules\pxt-microbit
  pxt-core: v3.10.16 C:\...\node_modules\pxt-core
main.ts(1,1): error TS9200:   -> Line 53 ('    bl numops::lt'), error: assembly error
   Maybe: bl    LABEL (unknown label at 'numops::lt')
   Maybe: bls   LABEL (opcode name doesn't match at '<name>')
```

I am nothing if not completely baffled!

**Comment by mmoskal** [comment]
It looks like this is using tagged compilation strategy, but microbit should be using untagged - some problem with reading pxtarget.json?

**Comment by abchatra** [comment]
This doesn't repro in the hosted editor.

**Comment by pelikhan** [comment]
Maybe he checked out PXT master + microbit?

________________________________

**Comment by mmoskal** [comment]
`pxt-core: v3.10.16` - this is clearly wrong

To repro, go to empty folder and run:
`pxt target microbit`

If you try `pxt serve` (as suggested) you get a server crash (after you run the browser) - that's first bug

Then try `pxt init` and put `let x = 1 + 2` in `main.ts`, run `pxt build` - you get the unknown label error (because of wrong pxt-core version)

**Comment by pelikhan** [comment]
Sam had been publishing build from the vnext so it seems that our CLI might be picking those.

________________________________

**Comment by abchatra** [comment]
fixed
