### ISSUE TITLE
The team publish v1.1.10 version?

### ISSUE THREAD

**Issue by mashihua** [Microsoft/pxt-microbit#752]
When I use cli `pxt target microbit & pxt serve`, found the project can not run, then I investigate what's wrong going on and found the pxt-microbit version is v1.1.10. Please check it `curl   https://registry.npmjs.org/pxt-microbit`, Thanks.

**Comment by samelhusseini** [comment]
Fixed with a bump. @mashihua let us know if you are still having trouble.
