### ISSUE TITLE
Clear highlight state when exiting tutorial

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt-microbit#754]
The editor doesn't clear the highlight state when exiting a tutorial. 

Repro steps: 
1. Start the getting started tutorial
2. Enable tracing (slow mo)
 (Forever should be highlighted)
3. Continue through to the last step
4. Finish
5. Exit tutorial

Notice that the forever block is still highlighted:
<img width="450" alt="screen shot 2018-04-27 at 2 54 25 pm" src="https://user-images.githubusercontent.com/16690124/39380024-1e101864-4a2b-11e8-9000-5bb84889b12a.png">

Affects All browsers.

**Comment by abchatra** [comment]
Fixed
