### ISSUE TITLE
Dragging comments on Safari is broken

### ISSUE THREAD

**Issue by samelhusseini** [microsoft/pxt-microbit#755]
When dragging a comment on Safari it appears to be offset on drag, see gif.
We should verify if this affects the new workspace comments.

![safaricommentdrag](https://user-images.githubusercontent.com/16690124/39380155-95804900-4a2b-11e8-89e1-89fa13d24675.gif)

Safari v 11.1

**Comment by abchatra** [comment]
This doesn't look to be a microbit bug

**Comment by darzu** [comment]
![block-comments-dont-render-right-safari](https://user-images.githubusercontent.com/6453828/53674313-e8ee8f80-3c41-11e9-9d5a-af4423a37df4.gif)

Another example of probably the same issue.

**Comment by abchatra** [comment]
Fixed
