### ISSUE TITLE
Sharing embed view not compliant with HC theme

### ISSUE THREAD

**Issue by samelhusseini** [microsoft/pxt-microbit#756]
See screenshot. The embed textarea should have a black background with white text as per the rest of the HC theme.

<img width="809" alt="screen shot 2018-04-27 at 3 02 07 pm" src="https://user-images.githubusercontent.com/16690124/39380292-06dd6204-4a2c-11e8-8697-3bb663eba42d.png">

Tested on Safari 11.1

**Comment by jwunderl** [comment]
This is more of a theming consistency issue than an accessibly issue. Worth noting the whole dialog has changed to be black text on white at this point:  


![Screen Shot 2019-08-22 at 4 05 38 PM](https://user-images.githubusercontent.com/5615930/63555675-b50c6c80-c4f6-11e9-9fc1-68622931f2e1.png)
