### ISSUE TITLE
Undo / Redo state not immediately affected

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt-microbit#757]
We don't update the state when the undo / redo stack changes in Blockly, and therefore the Undo / Redo buttons in the editor toolbar don't reflect the state immediately, only until the next render happens. 

We should either reflect the state somehow, or not show them as disabled ever. 

Steps to repro: 
1. Start with a new project
2. Drag a block onto the workspace
3. Try to undo.. 
You won't be able to as the Undo button will be disabled.

**Comment by abchatra** [comment]
Closing P3 as won't fix.
