### ISSUE TITLE
Lists (and broken i2c-fram package)

### ISSUE THREAD

**Issue by gbaman** [Microsoft/pxt-microbit#76]
I was just playing around (mainly to add the Neopixel library) and by mistake added the ```i2c-fram``` package to my project. Site complained and locked up, so I refreshed and ended up being presented with this.
![screen shot 2016-05-25 at 15 31 17](https://cloud.githubusercontent.com/assets/833193/15543698/d34b4e96-228d-11e6-93fa-de441c9442a2.png)
So there does seem to be an issue with that module, but at the same time I also then was made aware that Blockly supports lists (hadn't previously noticed this). A teacher I was chatting with yesterday had specifically asked about lists and I had assumed they weren't supported, but here the blocks are, I am assuming they have just been hidden?

Any chance of getting them unhidden for normal use?

**Comment by pelikhan** [comment]
Lists are not done yet. You can try them out at sample.pxt.io<http://sample.pxt.io> . Still work in progress as text support.

In particular compilation/decompilation of array indexer needs to be implemented.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by pelikhan** [comment]
Related to https://github.com/Microsoft/pxt/issues/19

**Comment by abchatra** [comment]
Closing as separate issue is tracked in pxt repo Microsoft/pxt#19
