### ISSUE TITLE
Support for unsigned integer type

### ISSUE THREAD

**Issue by Gadgetoid** [Microsoft/pxt-microbit#765]
The lack of floating point mentioned here: https://github.com/Microsoft/pxt-microbit/issues/80 and here https://github.com/Microsoft/pxt-microbit/issues/205 is forgivable since @pelikhan's rationale makes sense, I quote:

> We made that decision early on to stay truthful to the "micro" aspect of the M0: there is no FPU on board - it is software emulated.

However, having an `int32_t` without a `uint32_t` type does not, in my opinion, satisfy this truthfulness. 

As an occasional embedded developer, and developer of libraries to support add-ons for the micro:bit I am running up against the lack of `uint32_t` as a significant barrier to implementing the compensation functions of commonly-used sensors.

In this instance, my problem is with the BME280, which uses the following `C` code to compensate pressure readings:

```
// Returns pressure in Pa as unsigned 32 bit integer. Output value of "96386" equals 96386 Pa = 963.86 hPa
BME280_U32_t BME280_compensate_P_int32(BME280_S32_t adc_P)
{
    BME280_S32_t var1, var2;
    BME280_U32_t p;
    var1 = (((BME280_S32_t)t_fine)>>1) – (BME280_S32_t)64000;
    var2 = (((var1>>2) * (var1>>2)) >> 11 ) * ((BME280_S32_t)dig_P6);
    var2 = var2 + ((var1*((BME280_S32_t)dig_P5))<<1);
    var2 = (var2>>2)+(((BME280_S32_t)dig_P4)<<16);
    var1 = (((dig_P3 * (((var1>>2) * (var1>>2)) >> 13 )) >> 3) + ((((BME280_S32_t)dig_P2) * var1)>>1))>>18;
    var1 =((((32768+var1))*((BME280_S32_t)dig_P1))>>15);
    if (var1 == 0)
    {
        return 0; // avoid exception caused by division by zero
    }
    p = (((BME280_U32_t)(((BME280_S32_t)1048576)-adc_P)-(var2>>12)))*3125;
    if (p < 0x80000000)
    {
        p = (p << 1) / ((BME280_U32_t)var1);
    }
    else
    {
        p = (p / (BME280_U32_t)var1) * 2;
    }
    var1 = (((BME280_S32_t)dig_P9) * ((BME280_S32_t)(((p>>3) * (p>>3))>>13)))>>12;
    var2 = (((BME280_S32_t)(p>>2)) * ((BME280_S32_t)dig_P8))>>13;
    p = (BME280_U32_t)((BME280_S32_t)p + ((var1 + var2 + dig_P7) >> 4));
    return p;
}
```

This very explicitly relies upon the increased range of a `uint32_t` to handle interim results.

While I believe it may be possible (albeit labour intensive) to convince this formula to work with just 16bit types, since the nRF51822 is a 32bit micro-controller, anyone expecting a truthful adherence to its architecture would logically expect an unsigned, 32bit integer.

Is this plausible, is it even possible? I'll admit I have not studied how the translation from typescript to ARM Thumb actually happens within PXT and I don't have the time to delve into it. Could an `unsigned` type, equivalent to number, but unsigned in nature, co-exist with the current `number` type?

I don't have time to wait for an answer here, so my interim solution will be to drop into C++ and simply do the compensation there. It's just one of those things that feels like a kludge, though. Thanks for reading this ;)

**Comment by pelikhan** [comment]
@mmoskal

**Comment by mmoskal** [comment]
You might be able to use `>>>` vs `>>` operator in TypeScript. Most operations have the same bitwise implementation in signed and unsigned math. But it indeed might be tricky.

In fact, we are far more likely to support floats dynamically, the way we do on CPX and other boards, than to add additional numeric types to the PXT flavor of TypeScript.

**Comment by Gadgetoid** [comment]
Unless I'm misunderstanding the purpose of the integer types detailed here: https://github.com/Microsoft/pxt/blob/master/docs/language.md#smaller-int-types

Then uint32 is already supported in PXT, just not pxt-microbit?

**Comment by mmoskal** [comment]
Well, yes and no :))

The `int`/`uint` types in PXT are for storage only. The computation in these other targets is performed using C `double` type, so it can easily fit `uint32_t`. The actual semantics of computation is the JavaScript semantics (i.e., `>>` works like `>>` on `int32_t` in C, but `>>>` like `>>` on `uint32_t`; we also have `Math.idiv`, `Math.imul` etc). In some sense this is similar to assembly.

We do it this way, since TypeScript only supports a single numeric type, and also it seems like a simpler model for beginners.

BTW, it's only conceptually `double` - we use 31 bit tagged signed integers, if the value fits.

**Comment by abchatra** [comment]
Question answered.
