### ISSUE TITLE
playTone on start loses ALL subsequent simulator audio (likely due to Chrome autoplay policy changes)

### ISSUE THREAD

**Issue by nbogie** [Microsoft/pxt-microbit#766]
In Chrome, loading a project with a "play tone" music block placed "on start" effectively loses the simulator's audio for all subsequent uses of play tone (at least).  
(I suspect this is in part due to recent changes in Google Chrome's autoplay policy.)

Simplest reproducible test case:

STEP 1: 

In google chrome (0.66) 

ensure that the url https://makecode.microbit.org/ in `chrome://media-engagement/` has a score of 0 (or at least is not rated high (a high rating would permit it to autoplay stuff under the new autoplay policy and would hide the issue).

STEP 2: 
Either A) visit this test project:

https://makecode.microbit.org/_cq05vqF81CiV

or 

B) make the same project anew, and - importantly - reload it:

    input.onButtonPressed(Button.A, () => {
        music.playTone(294, music.beat(BeatFraction.Whole))
    })
    music.playTone(262, music.beat(BeatFraction.Whole))

Expected behaviour:
* musical note is sounded by simulator on load (ideal)
* subsequent presses of button A should sound notes, *even if the on-start music fails*.

Observed behaviour:
* No note sounded on start
* No notes sounded on subsequent presses of button A
* Error appears (once) in console: "The AudioContext was not allowed to start. It must be resume (or created) after a user gesture on the page. https://goo.gl/7K7WLu"

Platform:
* Observed in Google Chrome 66.0.3359.139 on OSX 10.13.4
* Works fine in safari 11.1 on same OS

Hypothesis:
Recent Chrome autoplay policy changes* prevent the audio context being available to the simulator on autoplay on load (and I'd speculate that perhaps the simulator doesn't try to acquire the context again after this happens so that it can play future sound events, where perhaps it should try again to acquire it.)
* https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio

Testing the hypothesis:
I loosened chrome's autoplay-policy by setting the Chrome flag "Autoplay Policy" to "No user gesture is required" at `chrome://flags/#autoplay-policy` and then reloaded the above test project (after necessarily restarting chrome).  I then got the expected behaviour: the simulator plays music at start and subsequently.
If I then turn the policy back to "default", the issue reappears.

Misc thoughts:
Ideally, Chrome's "Media Engagement Index" of https://makecode.microbit.org/ would be very high after all the user's interaction with the site, permitting autoplay by the site for frequent users. But even were that the case for frequent users, for newcomers the above issue would persist, so the simulator should be robust in the face of having its attempted autoplay rejected, and seek to lose as little as possible.

**Comment by abchatra** [comment]
Chrome reverted their changes. This is fixed.
