### ISSUE TITLE
Serial Blocks/JavaScript

### ISSUE THREAD

**Issue by jpiay** [Microsoft/pxt-microbit#767]
Hi,

I’m trying to use the blocks/javascript editor for a serial communication between the microbit and another device (terminal, ESP8266…), but I can’t read more than 20 characters per line (video link below).

I would suggest improving the serial blocks/javascript since it's very limited if compared with the C++ runtime and can't be used even for simple applications.

Thank you very much.
https://www.youtube.com/watch?v=umzhnxZhjLc

**Comment by abchatra** [comment]
This is actually sending 22 characters including “\r\n”
There’s also a tx buffer size
The reason it’s 20 is because for most applications you don’t need more than that.

Fix here is to call to setRxBufferSize in the serial readBuffer implementation.

**Comment by jpiay** [comment]
Thanks for your reply. It would be really useful to have such a block (setRxBufferSize).

**Comment by philipphenkel** [comment]
@jpiay uBit.serial.setRxBufferSize has not been publicly exposed.

With serial.readBuffer(length) you can read more than 20 characters.

**Comment by abchatra** [comment]
There is serial.readBuffer(length) as a workaround.

**Comment by jpiay** [comment]
The block "serial.readBuffer(length)" does not allow length > 20 (or 21).
