### ISSUE TITLE
Unable to connect to paired device

### ISSUE THREAD

**Issue by ArduinoRob** [Microsoft/pxt-microbit#768]
I have managed to pair my Micro Bit with a smartphone but when I try to connect to it I get an error (Error 507 Unable to connect. Is the device switched on?). If I open my phone Bluetooth settings I can see that the Micro Bit is paired but doesn't show in "Available Devices"
I removed the pairing and the Micro Bit appeared in "Available Devices". I paired with the Micro Bit again but after the pairing it didn't appear in "Available Devices".
I launched the app that I had written and tried to connect to the Micro Bit but received the error message as before: "Error 507 Unable to connect. Is the device switched on?"
I have returned the Micro Bit to factory settings and paired with my phone but I still cannot connect via Bluetooth. I have also tried to connect using the Samsung Micro Bit app. I have successfully paired the device but when I try to connect I get an error "Please reset your Micro Bit and try again".

Any help will be greatly appreciated.
Thank you

**Comment by ArduinoRob** [comment]
Any ideas folks?

**Comment by pelikhan** [comment]
Please contact https://support.microbit.org , they have more experience with BLE issues.
