### ISSUE TITLE
Fly-out menu bug when creating a "subcategory" named "Advanced"

### ISSUE THREAD

**Issue by Gadgetoid** [Microsoft/pxt-microbit#769]
This is probably one of those "Well, don't do that then." bugs, but since it may have implications beyond this particular clash I thought it best to bring up.

## Steps to reproduce

Create at least one exported block tagged with:

```
//% subcategory="Advanced"
```

## Expected Result

An "Advanced" subcategory should appear in the list underneath the main title for the package. Clicking the "Advanced" subcategory should open its fly-out menu and allow individual blocks to be selected from that category.

## Actual Result

An "Advanced" subcategory *does* appear in the list. However, clicking on "Advanced" briefly flashes up the fly-out menu for the subcategory, and then additionally toggles the main "Advanced" category.

I theorise that categories are not given a globally unique identifier for directing events at the correct DOM element, so a "click" event is being triggered both on the "Advanced" subcategory, and then additionally on the "Advanced" primary category. Since a click on the primary category causes all fly-out menus to close, this would explain the "flash" of the correct menu.

<a href="https://cl.ly/2e08111H3G2H" target="_blank"><img src="https://drh2acu5z204m.cloudfront.net/items/2T1R1j0E3y1F031t1F2u/Screen%20Recording%202018-05-10%20at%2002.14.26.93%20PM.gif" style="display: block;height: auto;width: 100%;"/></a>

**Comment by lucas1677** [comment]
it looks funny.

**Comment by lucas1677** [comment]
hi bro, do you know how to build a electron app with pxt-microbit? and what's the official solution?

**Comment by CleoQc** [comment]
Just rename it "expert" :)

**Comment by pelikhan** [comment]
Advanced is special, avoid that subcategory...

**Comment by abchatra** [comment]
Yes Advanced is reserved. I am closing as the question is answered. Thanks for letting us know.
