### ISSUE TITLE
Music predefined melodies

### ISSUE THREAD

**Issue by gbaman** [Microsoft/pxt-microbit#77]
MicroPython has the [excellent set of melodies](http://microbit-micropython.readthedocs.io/en/latest/music.html#built-in-melodies) predefined within it. This has the advantage that a non musical student (or one who can't be bothered to copy out note names) can have something to start out with and see the potential of the music module. Or in the case of the fanfares, simply use within their programs without getting into the nitty gritty of the music module.
Any chance of getting something similar for PXT?
So perhaps a playMelody block with a dropdown menu to select which melody?

**Comment by pelikhan** [comment]
That sounds like a great idea. First we need to support the music notation, then we could have a dropdown that exposes various melodies.

**Comment by abchatra** [comment]
Ported to pxt repo which is the central issue management for pxt: https://github.com/Microsoft/pxt/issues/532
