### ISSUE TITLE
People often click on the 'A' and 'B' labels instead of the buttons

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#780]
Could we trigger a button press when the user clicks on the 'A' or 'B' label (or even when they press 'A' or 'B' on the keyboard?) and animate it as a button press. The idea is that making the action work but showing them it's the button that's 'active' will train them in the 'right' behaviour.

**Comment by abchatra** [comment]
Won;'t fix. Simulator mimics hardware and there is no way to click on A & B there.
