### ISSUE TITLE
The corresponding simulator of Projects "infection" loads blank on Edge & IE 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#785]
**Repro step:**
1. Navigate to https://makecode.microbit.org/projects/infection
2. Click the button "Start the simulator" at the bottom right corner of "JavaScript code" on this page.

**Expected result:**
![28815299-7cf918ac-76d3-11e7-9b6e-c86dc2d1dfac](https://user-images.githubusercontent.com/23466737/40709349-50d72318-63e5-11e8-82fb-f2a4d81db2b4.gif)

**Actual result:**
![2601](https://user-images.githubusercontent.com/23466737/40227301-9f611230-5a7d-11e8-865d-ac860df24db1.gif)

**Comment by Helen09** [comment]
Closed as fixed

**Comment by Helen09** [comment]
This issue still repros

**Comment by AimeeCao18** [comment]
The bug still repro

**Comment by abchatra** [comment]
Verified in Chrome. Fixed .

**Comment by Helen09** [comment]
@abchatra  This bug still repro on IE(11.316.17763.0) & Edge(44.17763.1.0)
