### ISSUE TITLE
The contents are out of border in tutorial

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#786]
**Repro step:**
• Navigate to https://makecode.microbit.org/beta#editor
• Click "?" and choose "Hardware"
• Scroll down to "Hint"
**Expected result:**
 All content should be within the given border.

**Actual result(Chrome, Edge&IE):**
![2835](https://user-images.githubusercontent.com/23466737/40227789-fca26b8c-5a7e-11e8-844f-b844547f7111.png)

**Comment by Helen09** [comment]
The same issue still exists on other page. When navigating to the document of "Serial", the content of Hint also are out of border.Details are as following:
 ["?"-->"Hardware"-->"Serial communication"]
![28352](https://user-images.githubusercontent.com/23466737/40227981-8d09442a-5a7f-11e8-9375-4f66cd021baf.png)

**Comment by Helen09** [comment]
This bug still reproes on Edge, Chrome, IE & Safari for Alpha

**Comment by AimeeCao18** [comment]
The bug still repro on Edge, Chrome and IE

**Comment by pelikhan** [comment]
@ganicke replace long URL with a "Read more..." link.
