### ISSUE TITLE
The error message shows differently on different browsers

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#787]
**Repro step:**
•Navigate to https://makecode.microbit.org/beta
•Drag block "show image item at offset 0" to "forever"

**Expected result:**
The error message should be same on different browsers

**Actual result:**
The error message shows differently on different browsers
On **Edge:**
![1](https://user-images.githubusercontent.com/23466737/38236409-951d6a72-3713-11e8-8ea4-4a44819374b6.png)
On **Firefox, IE, Chrome:**
![2](https://user-images.githubusercontent.com/23466737/38236425-9fa75322-3713-11e8-8794-98fbf5c3a5fd.png)

**Comment by abchatra** [comment]
Fixed in alpha. Albeit different error message
