### ISSUE TITLE
Switch to JavaScript when I add a function in another function there is no function explanation and argument 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#788]
**Repro steps:**
• Navigate to https://pxt.microbit.org/beta
• Click "JavaScript" and type "Math." in content pane
• Type "basic.showNumber( )" then add "Math." in "basic.showNumber( )"

**Except result:**
When I type "Math." in "basic.showNumber" there should show function explanations and argument

**Actual result:**
When I type "Math." in "basic.showNumber" there didn't show function explanations and function argument
![repro](https://cloud.githubusercontent.com/assets/23466737/24035714/a0662996-0b31-11e7-9fea-4137438e7980.gif)

**Comment by abchatra** [comment]
This is P3 closing.
