### ISSUE TITLE
Project "Dodge Ball Game" shows an error when clicking refresh button

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#789]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta 
• Drag document "Dodge Ball Game" blocks as below shared project 
   https://makecode.microbit.org/_Hty0XUCL73hr

**Expected result:**
This project shouldn't have error
**Actual result:**
This project has an error when clicking refresh button few times
![jul-07-2017 16-28-12](https://user-images.githubusercontent.com/23466737/27949881-f3252058-6331-11e7-924b-677f798a6e39.gif)

**Comment by Helen09** [comment]
This issue still repro on **IE(11.48.17134.0)** & **Firefox(61.0)**, but not very stable

**Comment by abchatra** [comment]
I can't repro this in alpha. Can you try again?

**Comment by abchatra** [comment]
marking backward-compat due to usage of random.

**Comment by Helen09** [comment]
This bug is not repro in Alpha, closed
