### ISSUE TITLE
Can't shake simulator

### ISSUE THREAD

**Issue by tinfoilhatter** [Microsoft/pxt-microbit#79]
Trying to run the following code in the online simulator. When I press Shake, the button lights up but nothing else happens. There is no shaking animation (if there should be), and the picture on the simulated LED screen does not change from paper to rock or scissors.

I created this code with the Blocks Editor and checked it visually. I don't see anything wrong with it.

Firefox 46.0.1 on Ubuntu 16.04.

```
let rps = 0;
input.onGesture(Gesture.Shake, () => {
    rps = Math.random(4);
});
if (rps == 0) {
    basic.showLeds(`
# # # # #
# . . . #
# . . . #
# . . . #
# # # # #`);
}
else if (rps == 1) {
    basic.showLeds(`
. . . . .
. # # # .
. # # # .
. # # # .
. . . . .`);
}
else {
    basic.showLeds(`
. . . # #
# # . # .
. . # . .
# # . # .
. . . # #`);
}
```

**Comment by pelikhan** [comment]
The ``onGesture`` scope is wrong, move ``})`` to the end...

**Comment by tinfoilhatter** [comment]
I stretched out the ``on shake`` block to encompass the ``if`` statement, and it worked.
