### ISSUE TITLE
Leds on block "create big image" will be off on Firefox 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#790]
**Repro Steps:**
• Navigate to https://makecode.microbit.org/beta on Firefox on Mac
• Drag block "create big image" and put it with block "set item to 0"
• Click on block "create big image"

**Expect Result:**
Click on block "create big image" and the LEDs should be on 
**Actual Result:**
Sometimes clicking the next led and the previous led will be off
![aug-15-2017 15-16-35](https://user-images.githubusercontent.com/23466737/29306249-36827af6-81cf-11e7-94e8-f1daa4b9eb36.gif)

**Comment by abchatra** [comment]
@Helen09 this is fixed in alpha as we have a new field editor
