### ISSUE TITLE
The documentation of "scrollImage(,)" can't be viewed under "{}JavaScript" 

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#792]
**Repro Step:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Create new project and drag blocks as following picture:
![368803](https://user-images.githubusercontent.com/23466737/40228854-009742b4-5a82-11e8-9cf3-9aa46ee1a089.png)
3. Switch to "{}JavaScript", select "picture.scrollImage()" and right click "help"

**Expected Result:**
 After clicking "help", it should display the instruction as following:
![368801](https://user-images.githubusercontent.com/23466737/40228869-0a7b4faa-5a82-11e8-8f1e-398e1471c5c1.gif)

**Actual Result:**
 After clicking "help", it displays "Oops we could not load the documentation... "
![368802](https://user-images.githubusercontent.com/23466737/40228885-1362e286-5a82-11e8-9649-4910f6139486.gif)

**Comment by ganicke** [comment]
This requires matching the namespace name to the instance name and then combining with the method name.

**Comment by AimeeCao18** [comment]
The bug still repro now.

**Comment by abchatra** [comment]
@riknoll @pelikhan  Is the fix easy here?  
I am assuming this bug is at multiple places when someone refers instance methods.

**Comment by pelikhan** [comment]
It's probably broken for all instance methods.

**Comment by ganicke** [comment]
Also depends on convention (or the lack of convention) for classes within or without a namespace to path to the doc: _./namespace/class/method.md_ versus the usual _./namespace/method.md_. Some docs for class methods are subfoldered (is that a word?) under the class name after the namespace in their doc tree.

**Comment by abchatra** [comment]
Closing more than an year old bugs. If this still reproduces please reopen.
