### ISSUE TITLE
Button "A"& "B" are also selected When Clicked “P0,P1,P2...”

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#794]
**Repro step:**
1. Navigate to https://makecode.microbit.org/beta#editor (IE)
2. Click " p0,p1,p2,p3... "

**Expected Result:**
![359801](https://user-images.githubusercontent.com/23466737/40229034-98636adc-5a82-11e8-85bf-e1676987afe1.gif)

**Actual Result:**
![359802](https://user-images.githubusercontent.com/23466737/40229041-9e9d95bc-5a82-11e8-96c0-9f6ca101a514.gif)

**Comment by Helen09** [comment]
This bug still reproes in Alpha on IE

**Comment by AimeeCao18** [comment]
The bug still repro on IE

**Comment by abchatra** [comment]
Over a year old bug. Won't fix.

**Comment by abchatra** [comment]
I guess we don't support IE
