### ISSUE TITLE
Show ranges of accelerometer input

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#799]
**Is your feature request related to a problem? Please describe.**
When using the micro:bit for the first time, a user doesn't know the range of values that the accelerometer is going to output

In the microbit.co.uk editors, this was shown using a status display below the simulator:
![image](https://user-images.githubusercontent.com/147113/40310056-7d6dc3d4-5d03-11e8-94fc-3cb4384ee257.png)

This was really helpful for quickly learning the values you wanted to use in a script. (IE the min/max to expect)

For many users, even the idea that the values will run from negative to positive isn't obvious until they see that display.

**Describe the solution you'd like**
I'd like to be able to see on the simulator somewhere the accelerometer values when the simulator is responsive to the accelerometer. 

**Describe alternatives you've considered**
We should also make sure the documentation for the accelerometer states the ranges.
Some other options
* We could display this in the tooltip when 'moving' the micro:bit using the mouse
* We could display it somewhere on the micro:bit itself, like we do the light level
* We could display it underneath the micro:bit

**Additional context**
This is especially relevant as we deprecate microbit.co.uk that included this feature, and where teachers had encouraged kids to use the simulator to explore the ranges of the sensors.

**Comment by abchatra** [comment]
Done
