### ISSUE TITLE
create sprites does not work..

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#8]
1 open KSF, click JS

2 type this code

```
let hero = game.createSprite(2, 2)
let food = game.createSprite(4, 4)
let ghost = game.createSprite(0, 0)

```

3 would expect for these sprites to appears on the simulator.

4 the error is shown in blocks too.. see example below

![image](https://cloud.githubusercontent.com/assets/11206682/14092782/287cb3c2-f4fe-11e5-8fb5-02e2e4636e4b.png)

4 nothing appears when pressing run

**Comment by pelikhan** [comment]
Fixed in PXT 0.2.68
