### ISSUE TITLE
More maths blocks

### ISSUE THREAD

**Issue by gbaman** [Microsoft/pxt-microbit#80]
Was working on a program that required rounding a number to closest whole number. With Scratch there is simply a ```round``` block, although right now there is no block (or ```Math.round()``` in code) way to do that, that I can see?

While on the topic of maths blocks in general, a way to do ```modulus``` in blocks would also be pretty useful.

Finally, perhaps something more to consider in the future. What about a block for all the rest of the maths functions, again similar to how Scratch does it? Aka, with a dropdown so only a single new block needed for them. Not saying all are needed, is just stuff like sin/cos/tan might come in useful for students.
![screen shot 2016-05-27 at 00 22 56](https://cloud.githubusercontent.com/assets/833193/15593120/4fc4317c-23a1-11e6-8506-440c80a2a4c3.png)

**Comment by pelikhan** [comment]
We only support integer arithmetic for te BBC microbit....

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by gbaman** [comment]
Haha, am noticing that now. I had been thrown off by the fact the editor does let you enter them without complaining, but then is quietly rounding them down in the background. Any particular reason not to support decimal numbers? (am used to using them with MicroPython without any issues)

**Comment by pelikhan** [comment]
We made that decision early on to stay truthful to the "micro" aspect of the M0: there is no FPU on board - it is software emulated.

The next drop of Blockly will have a number field that will allow to restrict the input. Will keep this open...

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by pelikhan** [comment]
Yes modulus is missing. I'll keep this issue open for it.

**Comment by thomasdenney** [comment]
@whaleygeek ^ is exponentiation in PXT.

**Comment by thomasdenney** [comment]
Modulus is available - it is called 'absolute of'

**Comment by abchatra** [comment]
We do have reminder of block. Closing this as we only have integer arithmetic.
