### ISSUE TITLE
Melody block does not wait for the process to complete 

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#801]
**Describe the bug**
If you trigger successive melodies, the block does not wait for the previous function to run before executing the next one.

**To Reproduce**
1. Go to https://makecode.microbit.org/_WyV35DR4C3ue
2. Second melody is heard and not first one

**Expected behavior**
I would expect the first melody to play once and then the second melody to play

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome/firefox
 - Version 66/60

**Additional context**
This is the same on the micro:bit. Either the docs should be clearer or maybe ther eis a way to run one melody and then the next that needs to be documented.

**Comment by abchatra** [comment]
New block cancels the old one and not bocking. This is an existing behavior for last two versions of editor. It is quite debatable if this is the right behavior. 

Not intending to change the behavior, otherwise, it will break existing programs.
