### ISSUE TITLE
Show String is confusing

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-microbit#808]
User feedback:  The concept of a "string" is confusing for 4th/5th graders who have never coded before.  It's unclear to them what the Show String block does.  Consider renaming to "Show text" or something beginners would understand.

**Comment by pelikhan** [comment]
This is a major API Change that will impact (most likely) all existing books/articles.

**Comment by pelikhan** [comment]
“String” is also used in a number of other places: serial, radio, Bluetooth...
We should adopt a unified terminology though as the blocks category is “text”
