### ISSUE TITLE
Broken send-number example

### ISSUE THREAD

**Issue by tinfoilhatter** [Microsoft/pxt-microbit#81]
```
radio.setGroup(99)
let max = 0
basic.forever(() => {
    let level = radio.receiveNumber()
    if (level > max) {
        let max = level
    }
    if (max > 10) {
        basic.showString("ALERT")
    }
})
```

This example is supposed to display an alert when a remote micro:bit broadcasting the light level suddenly sees an increase in brightness. However, the variable `max` never seems to rise above `0`, confirmed by another version of the code that is supposed to constantly display the remote light level as well.

An even simpler version of the code that _only_ displays the remote level correctly displays numbers from `0` through `255`. (See /radio/send-number.md.)

I'm guessing this is something simple I don't understand about our version of JavaScript.

**Comment by pelikhan** [comment]
You are redefining the variable in the nested if statement. Did we generate that code?

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by tinfoilhatter** [comment]
No, that was hand-coded.

I'll take out the other `let`. Thanks!

On Fri, May 27, 2016 at 4:50 PM, Peli de Halleux <notifications@github.com>
wrote:

> You are redefining the variable in the nested if statement. Did we
> generate that code?
>
> Sent from Outlook Mobile<https://aka.ms/djubve>
>
> ________________________________
> From: tinfoilhatter <notifications@github.com>
> Sent: Friday, May 27, 2016 11:39:56 PM
> To: Microsoft/pxt-microbit
> Subject: [Microsoft/pxt-microbit] Broken send-number example (#81)
>
>
> radio.setGroup(99) let max = 0 basic.forever(() => { let level =
> radio.receiveNumber() if (level > max) { let max = level } if (max > 10) {
> basic.showString("ALERT") } })
>
> This example is supposed to display an alert when a remote micro:bit
> broadcasting the light level suddenly sees an increase in brightness.
> However, the variable max never seems to rise above 0, confirmed by another
> version of the code that is supposed to constantly display the remote light
> level as well.
>
> An even simpler version of the code that only displays the remote level
> correctly displays numbers from 0 through 255. (See /radio/send-number.md
> .)
>
> I'm guessing this is something simple I don't understand about our version
> of JavaScript.
>
> -
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub<
> https://github.com/Microsoft/pxt-microbit/issues/81>, or mute the thread<
> https://github.com/notifications/unsubscribe/AD-4KZoxzcyBLsbLfpZuQ2L8hzLFiroqks5qF4DMgaJpZM4Io8DP
> >.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Microsoft/pxt-microbit/issues/81#issuecomment-222276282>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJ3kat9-8v6VFqMzUYSgfGEntYhk0A3Xks5qF4NRgaJpZM4Io8DP>
> .
>



-- 
Ron Hale-Evans ... http://ron.ludism.org
<http://ur1.ca/4iaf3>
