### ISSUE TITLE
 The documentation can't be opened in a new tab

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#815]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta#editor on firefox(Mac & VM), Edge and IE
• Click Reference in "?help"
• Open the documentation in a new tab

**Expected result:**
 The documentation can be opened in a new tab
**Actual result:**
 The documentation can't be opened in a new tab
![123](https://user-images.githubusercontent.com/23466737/40708289-a2571480-63e2-11e8-86af-da27a3d77b55.gif)

**Comment by Helen09** [comment]
This bug still reproes on Edge & Firefox

**Comment by Helen09** [comment]
This issue only reproes on Firefox now

**Comment by abchatra** [comment]
This are browser bugs. If you allow always, it will open from next time.  Closing as Can't fix
