### ISSUE TITLE
There is no simulator example on Edge and IE 

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#818]
**Repro Steps:**
• Navigate to https://makecode.microbit.org/beta on Edge & IE
• Scroll down to "Games"-> "Karel the LED" to open this project documentation

**Issue 1:**
Scroll to the bottom in the right documentation and click triangular label
**Expect Result:(Chrome & Firefox)**
![121](https://user-images.githubusercontent.com/23466737/40710293-cdb4c0dc-63e7-11e8-9315-cb6c7086e8a1.png)

**_Actual Result:(Edge & IE)_**
![122](https://user-images.githubusercontent.com/23466737/40710326-e222963e-63e7-11e8-8e57-c1bdeac3c316.png)

**Issue 2:**
Click the Edit label, there is no responding on each browser
![123](https://user-images.githubusercontent.com/23466737/40710334-ea04aa04-63e7-11e8-8b94-734b40c9498e.png)

**Comment by Helen09** [comment]
This issue still reproes on Edge & IE in alpha.

**Comment by AimeeCao18** [comment]
The bug still repro on Edge and IE

**Comment by abchatra** [comment]
Won't Fix old bugs on Edge or IE.
