### ISSUE TITLE
embedded mode doesn't seem to work on Mac Safari browser

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt-microbit#82]
I can't get the embed code to work on Safari on the mac:

http://blog.whaleygeek.co.uk/

Just sticks at the Loading... message

Safari Version 9.0 (10601.1.56.2)
OSX Yosemite Version 10.10.5
MacBook Air (11-inch, Early 2014)
Intel Core i5
Intel HD Graphics 5000

Works ok on Chrome for Mac Version 50.0.2661.102 (64-bit), and also on Safari Tech preview (beta)

**Comment by pelikhan** [comment]
Fixed now. Got bitten by "atob" not present in Safari web workers...
