### ISSUE TITLE
On Shake can only be triggered once with the mouse in the simulator

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#820]
**Repro steps:**
• Navigating to https://makecode.microbit.org/beta#editor
• Drag blocks "on shake", "show number" and "pick random 0 to 4"
• Shake the simulator and observe
**Expected Result:**
Shaking simulator should be same as clicking "SHAKE" button, block "pick ramdom" always works
![2](https://user-images.githubusercontent.com/23466737/34331731-5b4ea59c-e964-11e7-9575-6737c3b8c1a9.gif)
**Actual Result:**
When shaking the simulator, after block "pick random" works once and the number doesn't change anymore
![1](https://user-images.githubusercontent.com/23466737/34331737-622ced10-e964-11e7-9505-dc872304e765.gif)

**Comment by nbogie** [comment]
Experimenting here, It seems to be possible to trigger a shake event ONCE in the simulator this way but then not again until the "shake" button is pressed, after which time a shake can again be triggered ONCE (sometimes), and so on.

So this is not to do with the "pick random" block, rather the unintuitive way shake events are triggered, and not triggered, by manual movement of the simulated microbit.  

From my perspective, it would be better if such manual movement of the simulated microbit either NEVER triggered a shake event (just use the button instead), or ALWAYS triggered a shake event given the accelerometer data actually matched the gesture.

(experimented on chrome 67.0.3396.62 on mac os 10.13.4)

**Comment by Helen09** [comment]
This issue still reproes

**Comment by abchatra** [comment]
Fixed
