### ISSUE TITLE
Block "Serial write string" can't write string right now

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#821]
**Repro step:**
• Navigate to https://makecode.microbit.org/beta
• Open the below project
https://makecode.microbit.org/_FdKJce3eCCsD

**Expected Result:**
 When clicking "Show data", it should show string "JUMBO" right now

**Actual Result:**
 It can't show string "JUMBO" for a long time
![1](https://user-images.githubusercontent.com/23466737/35266778-1fe00cac-001c-11e8-9417-3b9133b67b9b.gif)

**Comment by Helen09** [comment]
This issue still reproes in alpha

**Comment by abchatra** [comment]
Use `serial write line`. `serial write string` requires \n at the end to flush the strings.
