### ISSUE TITLE
The list dialog of variables displayed above the layer of document

### ISSUE THREAD

**Issue by Helen09** [microsoft/pxt-microbit#826]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta#editor
• Drag blocks like the followed picture
• Click the list of variables and open the document

**Expected result:**
 The list dialog of variables should display under the layer of document
![2222](https://user-images.githubusercontent.com/23466737/40711319-6af2b212-63ea-11e8-9daa-951366ef7163.png)
 **Actual result:**
 The list dialog of variables displayed above the layer of document
![2223](https://user-images.githubusercontent.com/23466737/40711358-7fad4c12-63ea-11e8-802f-d5683e88d349.gif)

**Comment by Helen09** [comment]
This issue still reproes in alpha

**Comment by AimeeCao18** [comment]
The bug still repro now

**Comment by abchatra** [comment]
Z-axis issue. Still repros.

**Comment by abchatra** [comment]
Closing more than an year old bugs. If this still reproduces please reopen.
