### ISSUE TITLE
There is no Voice in the Video and the icon "Full Screen" didn't work on FireFox

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#827]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta
• Click "Projects" ->"Guitar"
• Play the video and click the icon "Full Screen"

**Expected result:**
1.There is Voice in the Video
2.The Video can be played with "Full Screen"
![pp](https://user-images.githubusercontent.com/23466737/40711560-0694f586-63eb-11e8-9816-011e0f9ae200.gif)

**Actual result:**
1.There is no Voice in the Video on FireFox
2.The Video can not be played with "Full Screen" on FireFox
![qq](https://user-images.githubusercontent.com/23466737/40711545-fea38f7c-63ea-11e8-9203-cd954e540cf8.gif)

**Comment by samelhusseini** [comment]
This is youtube doing it's thing. It says fullscreen is unavailable with "Learn more". What does the Learn more say? is it something we can do anything about?

**Comment by Helen09** [comment]
Closed as by design
