### ISSUE TITLE
radio.sendValue() usage/issues

### ISSUE THREAD

**Issue by gbaman** [Microsoft/pxt-microbit#83]
So I am not 100% sure how to use ```radio.sendValue()```, or more precisely how to receive it on the other end? Sending a name/value pair is something that could be pretty useful, but right now I can't seem to find a way to get both parts from another micro:bit?
I would have thought, to get it you simply use ```radio.receiveNumber()``` and ```radio.receiveString()``` one after each other in the ```radio.onDataReceived``` handler, but that always just gets the part I am requesting first.
For example, the below program will display ```42``` on the display, but nothing else when A button is pressed. The "Hello" seems to get lost in the ether.   
```Typescript
input.onButtonPressed(Button.A, () => {
    radio.sendValue("Hello", 42);
});
radio.onDataReceived(() => {
    basic.showNumber(radio.receiveNumber());
    basic.showString(radio.receiveString());
});
```
At the same time, if you switch around the 2 show lines, then Hello will be displayed on the display but no 42 then.
Is there a more correct way to be using it?

The only way I can seem to get both is by using ```radio.writeValueToSerial()```, but of course then that means I can't use it on that micro:bit itself.

**Comment by damianburrin** [comment]
The one thing that seems missing to me here is you are not setting the radio group

radio.setGroup(0); you need to ensure both the tx and rx are in the same group

**Comment by gbaman** [comment]
@damianburrin that shouldn't be an issue given it is the same hex file being copied onto both micro:bits. Means the same group is used for both even if you don't define it.

**Comment by pelikhan** [comment]
Correct, we automatically assign a group of based on the program hash.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by tinfoilhatter** [comment]
I just encountered the same issues while trying to document `sendValue`. Recommend we move both `sendValue` and `writeValueToSerial` -- at least out of the blocks editor for now, maybe into a separate "Advanced APIs" section.

**Comment by abchatra** [comment]
@riknoll Please take look if this will be fixed by your callback work on radio. If yes close this issue and tag it with the issue in pxt.

**Comment by riknoll** [comment]
Yep, see the proposed solution in https://github.com/Microsoft/pxt/issues/465
