### ISSUE TITLE
[v1] play tone connectors are not croc clips 

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt-microbit#831]
![screen shot 2018-06-01 at 9 18 56 am](https://user-images.githubusercontent.com/16690124/40851635-e45abeb8-657c-11e8-92d4-0097dc94e914.png)

Repro steps: 
add any music block and look at the connectors in the sim

**Comment by samelhusseini** [comment]
@pelikhan took a quick look into this. Something must've changed in the authoring of parts to have this different behaviour between master and v0. 

I found this PR which might be related: https://github.com/Microsoft/pxt/pull/3881/files

Let me know if you have any ideas?

**Comment by pelikhan** [comment]
I guess we need to update the parts definition with this pin style map. We should also be able to support Adafruit eventually.


________________________________

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-microbit/commit/785e180c53cfadf6ebb560f695d00999a8ffa00f
