### ISSUE TITLE
Comment is broken in IE11

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt-microbit#833]
**To Reproduce**
1. Right click add comment
2. UI is broken

**Screenshots**
![image](https://user-images.githubusercontent.com/6107272/40857336-b1600410-658f-11e8-9174-32dd8d68647c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: IE11

**Comment by samelhusseini** [comment]
We should disable click and delete icon in IE.

**Comment by pelikhan** [comment]
You need to be able to delete ?

**Comment by riknoll** [comment]
I just took a look at the implementation of the workspace SVGs and it looks like they are based around using `<foreignObject>` to embed an HTML `<textArea>` into the SVG workspace. IE doesn't support `<foreignObject>` so there is nothing we could do here except implement a `<textArea>` using pure SVG

**Comment by riknoll** [comment]
I'm going to make the comments readonly in IE11 (like they were in v0)
