### ISSUE TITLE
Plot bar graph (in the LED category) does not work with floating points

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt-microbit#837]
Try this code:

```typescript
let item = 0;
input.onButtonPressed(Button.A, function () {
   item += 0.1
})

basic.forever(function () {
    led.plotBarGraph(item, 1)
})
```

**Comment by samelhusseini** [comment]
@pelikhan the method does an value = Math.abs(value); on the value. 

Not sure how you want to adapt that method to support floating points.

**Comment by pelikhan** [comment]
This issue is that it is does Math.max(high, 16) for low values.
