### ISSUE TITLE
shuffle button

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#84]
we are currently creating programs for K-12 educators and students. a powerful way to learn the concepts is through a puzzle style method of understanding the logical flow in the code. i would like an easy way for teachers to shuffle their finished code so students could assemble the finished code. 

Here is an example of code that would be shuffled: 

```
basic.showLeds(`
    . . # . .
    . # # # .
    # # # # #
    . . # . .
    . . # . .
    `)
input.onButtonPressed(Button.A, () => {
    let random = Math.random(2)
    if (random == 1) {
        basic.showString("TRUTH")
    } else if (random == 0) {
        basic.showString("DARE")
    } else {
        basic.showString("SKIP")
    }
    basic.showLeds(`
        . . # . .
        . # # # .
        # # # # #
        . . # . .
        . . # . .
        `)
})

```

I would like any finished code to be shuffled by the teacher as in the example below. 

![asfsf](https://cloud.githubusercontent.com/assets/11206682/15720294/93f90200-27e8-11e6-9625-8dfa06cf8fa3.jpg)

**Comment by pelikhan** [comment]
Added in canvas context menu./
