### ISSUE TITLE
problem with round tripping

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt-microbit#85]
http://m.pxt.io/xedoqkninx 

When I click “fork” I get to blocks -> show code doesn’t round trip though. 

Is there a way I can go direct to JavaScript so I can see the code without the conversion to blocks?

**Comment by pelikhan** [comment]
Decompilation of instance methods not supported yet.

**Comment by abchatra** [comment]
http://m.pxt.io/xedoqkninx  does have any code for me to verify. Also per Peli comments I am closing the issue (_decompilation of instance methods are not supported_).
