### ISSUE TITLE
There is no download button for "Karel the LED" code in tutorial

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#851]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta
• Click "Projects" -> "Projects" -> Scroll down all projects -> choose "Karel the LED"
• Scroll down the project tutorial and observe

**Expected result:**
There should have a download button for this project code
**Actual result:**
There is no download button for this project code in tutorial
![issue2](https://user-images.githubusercontent.com/23466737/40910163-f1cfcb64-67da-11e8-83ed-f55ef45a99a2.PNG)

**Comment by ganicke** [comment]
Due to it's complexity, the Karel project code is JavaScript only (no view in blocks) and as such the `typescript` section doesn't render with a download button.

See #862
