### ISSUE TITLE
Project "Karel the LED" tutorail text error

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#852]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta
• Click "Projects" -> "Projects" -> Scroll down all projects -> choose "Karel the LED"
• Observe the document text as the picture

**Expected result:**
The highlight text should be "Then use the program to introduce the micro:bit to new students"
**Actual result:**
The highlight text is "Then USE the program to introduce new students to the micro: bit"
![issue1](https://user-images.githubusercontent.com/23466737/40910497-cd458238-67db-11e8-8432-3ef87d1d651f.png)

**Comment by ganicke** [comment]
The emphasized "USE" is changed to "use".

See #862
