### ISSUE TITLE
There is no Green Screen mode on IE

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#859]
**Repro steps:**
• Navigate to https://makecode.microbit.org/alpha#editor
• Click "More..." to observe

**Expected result(Edge, Chrome & Firefox):**
There should have Green Screen mode on IE
![123](https://user-images.githubusercontent.com/23466737/40966171-4814fb7e-689f-11e8-9141-0c3bff878078.png)

**Actual result(IE):**
There is no Green Screen mode on IE
![123](https://user-images.githubusercontent.com/23466737/40966051-f7212526-689e-11e8-9343-426806178dab.png)

**Comment by pelikhan** [comment]
By design, IE does not support WebRTC.
