### ISSUE TITLE
Improve the "nudge"

### ISSUE THREAD

**Issue by andrewaxley** [Microsoft/pxt-microbit#864]
It appears the the "nudge" of the clock is missing a conditional. The microbit should only nudge the clock forward when it receives a radio message from another micro bit *and* the microbit doesn't currently have its light on. This allows the "fireflies" to stop trying to catch up with eachother when they reach synchronization.

The change clock by 1 should be withing a conditional "if clock <8". See adafruit's implementation for reference https://learn.adafruit.com/circuit-playground-fireflies-makecode/the-nudge

**Comment by pelikhan** [comment]
Thank you for reporting this!
