### ISSUE TITLE
micro:bit simlator disappear when package is loaded.

### ISSUE THREAD

**Issue by artec-kwaka** [Microsoft/pxt-microbit#867]
When our package is loaded micro:bit simlator disappeared.
Our package is [https://github.com/artec-kk/pxt-artecrobo](https://github.com/artec-kk/pxt-artecrobo).

JavaScript -> Explorer -> built -> output.txt says "Everything seems fine!".
But, Browser shows following error.

![error](https://user-images.githubusercontent.com/20764596/41137223-f90ae318-6b14-11e8-88fc-9f47b4f6bf9d.png)

How can we resolve this, please give us your advice.

**Comment by pelikhan** [comment]
I’ll take a peek.


________________________________

**Comment by kwaka1208** [comment]
Thanks.
I confirmed this error does not occur when  line 125 to 127 were commented out.
https://github.com/artec-kk/pxt-artecrobo/blob/master/artecrobo.ts

**Comment by artec-kwaka** [comment]
Thanks.
I confirmed this error does not occur when line 125 to 127 were commented out.
https://github.com/artec-kk/pxt-artecrobo/blob/master/artecrobo.ts

**Comment by pelikhan** [comment]
This is an issue with the simulator (https://github.com/artec-kk/pxt-artecrobo/blob/master/artecrobo.ts#L125) which will require a new release. Meanwhile, you can avoid this to using the low-level APIs instead of the Servo API.

**Comment by pelikhan** [comment]
A fix was deployed to /beta . It will be available once we release the main web site.
![image](https://user-images.githubusercontent.com/4175913/41188116-cb7fd972-6b6d-11e8-980a-d3ba3fd88853.png)

**Comment by artec-kwaka** [comment]
@pelikhan Thank you for your prompt action.
We don't need to add a c++ file (use "pxt add cpp") after once you release main web site.
If we need to take countermeasures immediately (before update main web site) )then we need to add c++ file.
Is that correct?

**Comment by pelikhan** [comment]
If you need your package to work ASAP, you could work around the current bug by writing the C++ that drives the servo. Or wait a couple weeks for the next update.

**Comment by abchatra** [comment]
Fixed in beta
