### ISSUE TITLE
alpha: import from microbit.co.uk doesn't preserve all blocks

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#868]
**Describe the bug**
When dropping a hex file from microbit.co.uk blocks that contains more than one 'unanchored' block they are not all preseved

They ARE all preserved on v0

Example program
![image](https://user-images.githubusercontent.com/147113/41166919-6033f7cc-6b39-11e8-88cd-686722210c01.png)

**To Reproduce**
[microbit-unearthly-script-3.zip](https://github.com/Microsoft/pxt-microbit/files/2085006/microbit-unearthly-script-3.zip)

Download this script
Drop into https://makecode.microbit.org/alpha

**Expected behavior**
All three blocks are stuck together in 'on start' like this
(screenshot from V0)
![image](https://user-images.githubusercontent.com/147113/41166991-9616c482-6b39-11e8-9bcf-6819f2d0f875.png)

**Screenshots**
Here's what actually happens on alpha
![image](https://user-images.githubusercontent.com/147113/41167023-aeef080c-6b39-11e8-9293-2a8dcb0958c4.png)

**Desktop (please complete the following information):**
 Windows 10, Chrome 66

**Comment by pelikhan** [comment]
Fixed.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-microbit/commit/e556c1afca06711c8416cb79a1206d33fd0e5880
