### ISSUE TITLE
Consider moving docs to its own repository?

### ISSUE THREAD

**Issue by kzu** [microsoft/pxt-microbit#869]
Currently, the `docs` folder is ~9x the size of everything else. For someone contributing just docs, it might be a bit overwhelming to have all the non-docs artifacts in a single repo.

Likewise, for someone contributing to the code, cloning the 70+ megs of docs may also be suboptimal.

So maybe a `pxt-microbit-docs` repo, potentially sub-moduled from this one if scripts depend on being able to reach it, would be best? When cloning the repo, you could decide whether you want the docs submodule cloned too or not.

**Comment by abchatra** [comment]
This is good idea. Although note this is substantial work for us in the build and backend to clone\version etc.

**Comment by kzu** [comment]
yep, I realize it surely is. it would be a nice to have, definitely not a must or urgent in any way. 👍

**Comment by abchatra** [comment]
We don't plan to do this due to the amount of work involved. Valid feedback though.
