### ISSUE TITLE
Example project's name error

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#870]
**Repro steps:**
• Navigate to https://makecode.microbit.org/alpha
• Scroll down to the bottom of the Home page
• Click "Game of Life" -> "Open Example" to open this example
• Observe the project name on the bottom of the editor page
**Expected result:**
It should be "game of life"

**Actual result:** 
It shows "gameof life"
![issue1](https://user-images.githubusercontent.com/23466737/41274025-6a582f32-6e0b-11e8-824c-fe2c7acb4ae2.PNG)

**Comment by Helen09** [comment]
This issue also exists on other example projects such as "Name Tag", "Pi Monte Carlo", "Plot Acceleration"...

**Comment by abchatra** [comment]
@samelhusseini @pelikhan did we change the behavior here?

**Comment by pelikhan** [comment]
We’ve done work in that space for EV3. Something might have changed.
