### ISSUE TITLE
Project "Plot Light Level" opened on alpha is different with on beta

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#872]
**Repro steps:**
• Navigate to https://makecode.microbit.org/alpha
• Scroll down to the bottom of the Home page
• Click "Plot Light Level" -> "Open Example" to open this example

**Expected result:(beta)**
The project opened on beta should be same as on alpha
![compare3](https://user-images.githubusercontent.com/23466737/41344420-992329d0-6ef0-11e8-844d-b7ae765d38b4.gif)

**Actual result:(alpha)**
Project "Plot Light Level" opened on alpha is different with on beta
![issue3](https://user-images.githubusercontent.com/23466737/41344409-92fa90ca-6ef0-11e8-8a9f-a3ca72de98c2.gif)

**Comment by samelhusseini** [comment]
Looks like https://github.com/Microsoft/pxt-microbit/pull/855 fixes bar graph for floating points but breaks everything else. 

Assigning this to @pelikhan to track.
