### ISSUE TITLE
Project "Blinkly" opened on alpha is not same as on beta

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#873]
**Repro steps:**
• Navigate to https://makecode.microbit.org/alpha
• Scroll down to the bottom of the Home page
• Click "Blinky" -> "Open Example" to open this example

**Expected result(beta):**
This project opened on alpha should be same as on beta
![compare3](https://user-images.githubusercontent.com/23466737/41399462-f09e839e-6fa9-11e8-80ba-92719dbaf635.gif)

**Actual result(alpha):**
This project shows differently on beta&Alpha
![issue3](https://user-images.githubusercontent.com/23466737/41399447-e57649b6-6fa9-11e8-815a-08ef7acac561.gif)

**Comment by samelhusseini** [comment]
@pelikhan I investigated this and it looks like your legacy update script is breaking LED fields decompilation. 

Things I did to verify: 
- decompilation of image literal fields is working
- decompilation tests were passing
- importXml in blockly is returning a malformed xml like this (which is causing the issue): 
![screen shot 2018-06-18 at 10 38 44 am](https://user-images.githubusercontent.com/16690124/41552519-d2563e44-72e3-11e8-8c8a-c6fc674b8c55.png)
Notice how there's a duplicate field in the XML. (that's a product of patchBlocks). 

I'm not too familiar with that patch logic, so I'll leave this for you to fix (incase there are cases I haven't considered).
