### ISSUE TITLE
in lack of a better place to ask this I ask here as it seems the only official place for questions at all

### ISSUE THREAD

**Issue by StefanL38** [Microsoft/pxt-microbit#880]
Hello,

I know that THIS place has a different function as what I'm asking for. I decided to ask here because even after intensive googling I did NOT find a more appropriate place for my question.
If a goz just tomatos on my eyes pull them off through a short answer including the appriorate link.

So here it is:
What are the reasons why there does no new-bee userforum on how to code with blocks on the MicroBit? ? ? .... !! ? ? ? 
I really can't understand this.

I the admins here forgive me for asking this here. It is the truth I haven't found any better suited place to ask.

best regards  

Stefan

**Comment by CleoQc** [comment]
Are you on the Slack channel?

**Comment by CleoQc** [comment]
You can find some info here: https://makecode.com/about
There's a ReadTheDocs here: https://makecode.com/docs
But the easiest way to get started is here: https://makecode.microbit.org/blocks/custom

**Comment by abchatra** [comment]
Here is the list of forums particular to microbit: https://support.microbit.org/solution/folders/19000125933
