### ISSUE TITLE
There is no "C++ runtime version" info on alpha

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#881]
**Repro steps:**
• Navigate to https://makecode.microbit.org/alpha#editor
• Click "More..." -> About to observe micro:bit info

**Expected result(beta):**
![compare1](https://user-images.githubusercontent.com/23466737/41710120-6b7024bc-7534-11e8-9161-2c1dcf8599f3.PNG)

**Actual result(beta):**
There is no "C++ runtime version" info on alpha
![issue1](https://user-images.githubusercontent.com/23466737/41710104-632b62da-7534-11e8-9b48-48b9fd8a6653.PNG)

**Comment by pelikhan** [comment]
By design, we removed it.
