### ISSUE TITLE
When clicking on the blank area of the select box, select file window can be opened

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#883]
**Repro steps:**
• Navigate to https://makecode.microbit.org/alpha
• Click "Import" -> "Import File" -> click in the select box

**Expected result:**
When clicking on the blank area of the select box, there should be no response
**Actual result:**
When clicking on the blank area of the select box, select file window can be opened
![issue3](https://user-images.githubusercontent.com/23466737/41712490-2fe28ab0-753a-11e8-860b-4125f5ffcfea.gif)

**Comment by pelikhan** [comment]
This is by design.
