### ISSUE TITLE
Cannot load a package via direct link

### ISSUE THREAD

**Issue by CleoQc** [Microsoft/pxt-microbit#884]
**Describe the bug**
I can no longer load my (in development) package, although it was just fine 24 hours ago. 

**To Reproduce**
Go to https://makecode.microbit.org/
Click Advanced/Add Package
enter https://github.com/CleoQc/pxt_gigglebot and Press enter key, or click on the Search icon

No error at all.
Of the default packages that are being displayed when you first click on Add Package, only the Neopixel one stays.

**Expected behavior**
GiggleBot package was loading just fine for weeks. 

**Screenshots**
Default "Add Package" look:
![default](https://user-images.githubusercontent.com/4965628/41725609-3dfb3f94-753e-11e8-988f-9ad69d10d01d.png)
After pressing Enter key:
![after](https://user-images.githubusercontent.com/4965628/41725616-409bdd1c-753e-11e8-9308-22467c855b9c.png)

**Desktop (please complete the following information):**
Windows 10 Home Insider circle (17134.112)
Firefox 60.0.2

**Additional context**
custom.ts is now a pretty big file. We're rushing to get it out in time for ISTE. We'll clean up after. Could it be related to the size of the file? (the fail happens after the big merge)

**Comment by pelikhan** [comment]
By design, you need to run "pxt bump" to create a new release tag.

**Comment by CleoQc** [comment]
It seems my custom.ts file has reached a size limit.

**Comment by pelikhan** [comment]
It's a finite world :) 64k limit on package size.

**Comment by CleoQc** [comment]
splitting into 2 packages fixes this issue. but raises another one for me. This one can be closed while I try to fix the other one.
