### ISSUE TITLE
how to immediately refresh source code?

### ISSUE THREAD

**Issue by ouki-wang** [Microsoft/pxt-microbit#886]
**Describe the bug**
After updating the source code on github, makecode takes more than 10 minutes to complete the refresh, how to immediately refresh

**To Reproduce**
1. update my pxt packages on github(https://github.com/ouki-wang/pxt-ds18b20)
2. Click on 'advanced'
3. Click on ‘add package’ and input https://github.com/ouki-wang/pxt-ds18b20
4. See error：The source code did not refresh

**Expected behavior**
refresh source code immediately

**Comment by pelikhan** [comment]
We have a proxy to serve GitHub packages in order to avoid throttling in schools (many schools hide under a single IP). Thus, we maintain a cache and do not serve the repo directly.


________________________________

**Comment by ouki-wang** [comment]
@pelikhan 
Can I refresh it by building my own server?
Which parameters do I need to configure, or which version should I fall back to?

**Comment by pelikhan** [comment]
No this is handled by our cloud. You can serve your package from a local server if you need to do development on it without pushing code out.


________________________________

**Comment by ouki-wang** [comment]
@pelikhan 
How to add a package to a local server? Is there a reference document?

**Comment by pelikhan** [comment]
See step 5 of https://makecode.com/packages/getting-started .

**Comment by abchatra** [comment]
Question answered.
