### ISSUE TITLE
Broken hyperlinks on music page

### ISSUE THREAD

**Issue by tinfoilhatter** [Microsoft/pxt-microbit#90]
The **reference > music** page in the browser does not link correctly to several API pages. As well as 404s, there are some items that link to wrong pages that _do_ exist. For example, the **change tempo** item links to the **tempo** page.

I looked around at **music.md** and elsewhere, but it seems the web page is generated from the Markdown by back end magic.

**Comment by tinfoilhatter** [comment]
The **reference > loops** page does not link to **repeat** or **while**, but links to **for** twice.

**Comment by tinfoilhatter** [comment]
The **reference > input** page is missing a link to **pin is pressed**.

**Comment by pelikhan** [comment]
Hi Tim, please open a separate issue on the "pin is pressed"

**Comment by pelikhan** [comment]
Please open a separate issue for loops.

**Comment by tinfoilhatter** [comment]
We already have a separate issue for **pin is pressed**.

**Comment by tinfoilhatter** [comment]
The **music** page is still broken. **Loops** and **input** have their own bugs.

**Comment by abchatra** [comment]
Issue still repros. Bunch of links in music page lead to 404
