### ISSUE TITLE
Help system and screen resolution

### ISSUE THREAD

**Issue by gbaman** [Microsoft/pxt-microbit#91]
I have been really loving the new help system on the right side bar over past few days. But, I had my laptop attached to an external monitor while using it. Just noticed there while using the laptop on its own (and in turn, a smaller screen), am not seeing the help section. This is no issue and understandable for a smaller screen, but the general ```?``` help button disappears as well... So from what I can see, the only easy way to get to the help section is clicking on a block, opening its help page and then clicking the links at top of page from there.
Assuming this wasn't intentional?
<img width="1425" alt="screen shot 2016-06-08 at 20 52 26" src="https://cloud.githubusercontent.com/assets/833193/15908715/f5268a3e-2dba-11e6-9720-36f496cc899c.png">

**Comment by pelikhan** [comment]
Thanks for opening. Yes, we’re still tuning the CSS styles to fix this issue.

**Comment by pelikhan** [comment]
Should be fixed now. Reopen if needed.
