### ISSUE TITLE
Micro:bit crashes if serial data received and no receive handler

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt-microbit#917]
1st test case: when an attached device sends serial data to micro:bit is this code crashes micro:bit hanging display with only some LEDs 
![image](https://user-images.githubusercontent.com/7300405/32224325-e58f3372-be38-11e7-89be-9fd33ff1a5cf.png)

2nd test case, add receive handler works fine, does not crash.
![image](https://user-images.githubusercontent.com/7300405/32224397-2095b36a-be39-11e7-9d98-5de7d5e836b9.png)

Tested this with @DavidWhaleMEF who confirms the above.

**Comment by abchatra** [comment]
Moved from https://github.com/Microsoft/pxt/issues/3390

**Comment by philipphenkel** [comment]
I ran into this issue a while ago and started to investigate. My assumption is that the lazy initialization of RX read buffers in the serial implementation is causing an issue when data is incoming.
As a workaround, I did a single async read after the serial redirect (this was a fix I could easily apply on my end)

```
void redirectSerial(int tx, int rx, int baud) {
      MicroBitPin* txp = getPin((int)tx); if (!txp) return;
      MicroBitPin* rxp = getPin((int)rx); if (!rxp) return;
      uBit.serial.redirect(txp->name, rxp->name);
      uBit.serial.baud(baud);

      // Enforce initialization of serial RX buffers to prevent hang
      uBit.serial.read(MicroBitSerialMode::ASYNC);
}
```

**Comment by philipphenkel** [comment]
@DavidWhaleMEF @abchatra I'm confident that I found the root cause of this crash in the microbit-dal  lancaster-university/microbit-dal#363

**Comment by abchatra** [comment]
Thanks for the investigation @philipphenkel . Greatly appreciate. I will close this issue as we are tracking the other issue on dal.
