### ISSUE TITLE
"pin is pressed" API missing in editor and reference > input page

### ISSUE THREAD

**Issue by tinfoilhatter** [Microsoft/pxt-microbit#92]
The **pin is pressed** API does not appear in the blocks editor or the **reference > input** page. We do have a docs page for the API. We also have an **on pin pressed** API with similar functionality.

Did **on pin pressed** replace **pin is pressed**?

**Comment by pelikhan** [comment]
This API is currently only available in TypeScript.

**Comment by pelikhan** [comment]
The card renderer needs to deal with API that don't have a block equivalent.

**Comment by abchatra** [comment]
Ported to https://github.com/Microsoft/pxt/issues/536
