### ISSUE TITLE
After resetting this project, the project is in "High Contrast Off" mode

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#920]
**Repro steps:**
• Navigate to https://makecode.microbit.org/alpha#editor
• Click "More..." -> "High Contrast On" 
• Drag some blocks to content pane
• Click "More..." -> "Reset" to reset this project

**Expected result:**
After resetting this project, the project should be still in "High Contrast On" mode

**Actual result:**
After resetting this project, the project is in "High Contrast Off" mode
![issue70501](https://user-images.githubusercontent.com/23466737/42307587-80f15932-8065-11e8-82ab-368a1563d9ed.gif)

**Comment by abchatra** [comment]
Reset deletes all caches and resets all the settings. this is as per design.
