### ISSUE TITLE
"magnetic force" API seems to be non-functional

### ISSUE THREAD

**Issue by tinfoilhatter** [Microsoft/pxt-microbit#93]
I've run three different test apps, including the example in our reference docs, and the following minimal example, on two different micro:bits, and I can't get any response at all, even when I place the magnetometer directly against a piece of stainless steel, or a speaker playing some audio.

```
basic.forever(() => {
    basic.showNumber(input.magneticForce("x"));
});
```
I've tried a few other variants as well, such as substituting **Dimension.X**.

**Comment by pelikhan** [comment]
It should not be taking a string as argument. Let me check this.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by tinfoilhatter** [comment]
It does display properly as blocks on the page when you use a string (but not in the editor). Also, using **Dimension.X** doesn't make it work either.

**Comment by pelikhan** [comment]
This seems to work fine with me after passing the calibration phase.
```
basic.forever(() => {
    led.plotBarGraph(input.magneticForce(Dimension.Strength), 0);
});
```

I will remove the calibration for the Strength mode.

**Comment by tinfoilhatter** [comment]
What about x, y, and z?

**Comment by pelikhan** [comment]
Works for me as well. You need to use Dimension.X. Using a string should not compile….

**Comment by tinfoilhatter** [comment]
As shown by Peli, this API is completely broken.

**Comment by tinfoilhatter** [comment]
I think I closed this by accident. If it's fixed now, please close it again. :)
