### ISSUE TITLE
Need images for Examples, and Getting Started Tutorial on Home Page

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-microbit#933]
![images](https://user-images.githubusercontent.com/22108954/42395709-ae1786c6-8113-11e8-8bf8-2c58fe75465d.PNG)

**Comment by halspeed** [comment]
@abchatra can we fix Getting Started for release? FYI, @Jaqster @jaustin

**Comment by pelikhan** [comment]
Getting started has been deprecated.

**Comment by halspeed** [comment]
What, I use Getting Started all the time for workshops

**Comment by abchatra** [comment]
I think we need one getting started for folks to point to. Why was it removed?

**Comment by abchatra** [comment]
It is always good to have one tutorial to help the first time here, start this kind of message. @ganicke can you  help adding that first tutorial?

**Comment by pelikhan** [comment]
The first tutorial is "flashing heart"

**Comment by abchatra** [comment]
We need to add something like following
![image](https://user-images.githubusercontent.com/6107272/46638855-d0a59900-cb17-11e8-8efa-8c614b4f6b28.png)

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-microbit/commit/c6fa65763b492f05c5a9b7c36a0f2088e77637da

Ribbon color could probably be improved.

**Comment by pelikhan** [comment]
The fix is in but you'll need to bust the cache to see it or try an anonymous window
![image](https://user-images.githubusercontent.com/4175913/46639222-c2587c80-cb19-11e8-8ff6-8ad0d66e948a.png)

**Comment by Jaqster** [comment]
Looks good.  I have additional tweaks I'd like to make for Flashing Heart:
- Step 2: the second Show LED block should be blank.  Let's not get fancy here, blinking heart is fine
- Step 3: add the text "But we only see the heart blink once. To make it blink continuously, ..."
- Step 4: add the text "Now let's get fancy and place more Show LED blocks to create your own custom animation"

**Comment by abchatra** [comment]
This is fixed.
