### ISSUE TITLE
Music blocks silent on alpha editor.

### ISSUE THREAD

**Issue by xmeow** [Microsoft/pxt-microbit#942]
All music blocks won't output any sound on Alpha editor after downloading the hex to microbit, but works fine in simulator. 

It is also strange that `pins.analogPitch` works which implement the music blocks.

**Comment by abchatra** [comment]
@xmeow this is a nice find. 

Following code plays gibberish in alpha, but plays fine in the live editor.
```
music.beginMelody(music.builtInMelody(Melodies.Dadadadum), MelodyOptions.ForeverInBackground)
```

**Comment by riknoll** [comment]
Update: The issue is actually in `parseInt()` which the melody blocks use. It always returns NaN on the hardware and it's messing up the parsing of the melody strings

**Comment by riknoll** [comment]
Will be released soon
