### ISSUE TITLE
The icon on the comment box bottom-right corner is not clear on Firefox

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#946]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/alpha#editor
2. Drag one block to content pane and right click to add comment
3. Observe the comment box

**Expected result(Edge, Chrome&IE):**
![compare001](https://user-images.githubusercontent.com/23466737/42500845-e3f936fa-8464-11e8-83ef-5f636150ae24.PNG)

**Actual result(Firefox):**
The icon on the comment box bottom-right corner is not clear on Firefox
![issue710002](https://user-images.githubusercontent.com/23466737/42500857-ed07a074-8464-11e8-956f-988c13027a5f.PNG)

**Comment by riknoll** [comment]
This is a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=984312
