### ISSUE TITLE
Download Screenshot in Edge

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#951]
The downloaded screenshot image in Edge doesn't include the +, -, or drop down menu icons on the blocks.  It seems to work fine in Chrome.
Edge Download screenshot:
![ifthenelse](https://user-images.githubusercontent.com/22108954/42703827-8dfd7386-8682-11e8-91f8-74bd7e4a6b1c.png)
Chrome Download screenshot:
![microbit-screenshot](https://user-images.githubusercontent.com/22108954/42703869-ad566e18-8682-11e8-881e-8d8e25a53392.png)

**Comment by riknoll** [comment]
Well, I fixed the dropdown arrows at least. See https://github.com/Microsoft/pxt/pull/4583 for more info

**Comment by abchatra** [comment]
Won't Fix old bugs on Edge or IE.
