### ISSUE TITLE
The shape of block "Button is pressed" is different with the ellipse

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#952]
**Repro steps:**
1. Open https://makecode.microbit.org/alpha#editor
2.  Drag blocks as below .gif 

**Expected result:**
The shape of block "Button is pressed" should be same as the ellipse 

**Actual result:**
The shape of block "Button is pressed" is different with the ellipse
![capture145](https://user-images.githubusercontent.com/23466737/42874004-a42441ce-8ab2-11e8-81a1-339406897fa0.PNG)

![issue71802](https://user-images.githubusercontent.com/23466737/42873766-5d617a72-8ab2-11e8-936b-ad90fc99ec5d.gif)

**Comment by abchatra** [comment]
This is as designed. Button A is pressed is Boolean block used in if conditions, but set variable can accept all kinds of blocks.

**Comment by abchatra** [comment]
Yes I understand. Unfortunately variables need to accept all kinds of blocks. Including Boolean ones which have different shape.
