### ISSUE TITLE
String-style dimensions ("x") can be rendered but not run

### ISSUE THREAD

**Issue by tinfoilhatter** [Microsoft/pxt-microbit#96]
The code that renders blocks in the reference docs can still render dimensions specified as strings:

```blocks
basic.forever(() => {
    led.plotBarGraph(input.acceleration("x"), 1023)
})
```

However, this will not run. Only dimensions specified as enumerations, as in the following example, will both render and run:

```blocks
basic.forever(() => {
    led.plotBarGraph(input.acceleration(Dimension.X), 1023)
})
```

I realize the strings are deprecated and request that rendering them be disabled.

**Comment by abchatra** [comment]
Ported to https://github.com/Microsoft/pxt/issues/536
