### ISSUE TITLE
Pictures on prompt box is too big 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#960]
**Repro steps:**
1. Open https://makecode.microbit.org/alpha
2. Scroll down the scroll bar to "Tutorials" & "Projects"
3. Click any project and observe the prompt box

**Expected result:**
The picture on prompt box should be same as the same picture

**Actual result:**
Pictures on prompt box is too big 
![issue72402](https://user-images.githubusercontent.com/23466737/43125686-53db4c30-8f5d-11e8-9506-768133175ee2.gif)

**Comment by abchatra** [comment]
By design.
