### ISSUE TITLE
After clicking "Cancel" when adding package, page backs to editor page

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#961]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Click "More..." -> "Extension" -> "bluetooth" and then click "Cancel"

**Expected result:**
After clicking "Cancel", it should still stay on "Extensions" page

**Actual result:**
After clicking "Cancel" when adding package, page backs to editor page
![issue72403](https://user-images.githubusercontent.com/23466737/43130371-25842f08-8f69-11e8-82c1-06159413c223.gif)

**Comment by AimeeCao18** [comment]
The bug still repro

**Comment by abchatra** [comment]
Won't fix from our end.
