### ISSUE TITLE
The left part of the page backs to the top after clicking one item 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#962]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/projects
2. Scroll down the scroll bar and click one project

**Expected result:**
The left part of the page should not back to the top

**Actual result:**
The left part of the page backs to the top after clicking one item 
![issue72404](https://user-images.githubusercontent.com/23466737/43132848-a23bd284-8f6f-11e8-8832-b239a0d4797d.gif)

**Comment by abchatra** [comment]
Lets skip testing of v0. We need to move to v1 documentation testing. https://makecode.microbit.org/v1/docs

**Comment by Helen09** [comment]
This issue also reproes on v1 documentation https://makecode.microbit.org/v1/docs

**Comment by AimeeCao18** [comment]
The bug still reproduce

**Comment by Helen09** [comment]
Closed as fixed
