### ISSUE TITLE
Radio vs Bluetooth, a bit more flexibility? 

### ISSUE THREAD

**Issue by CleoQc** [Microsoft/pxt-microbit#966]
Our package includes ready-made remote control buttons that take advantage of the radio.
However, this renders the whole package incompatible with Bluetooth.  I understand that radio blocks and bluetooth are incompatible. That's not the issue I'm trying to address.  I was hoping to have a package that would have ready made blocks that use the radio and only those blocks would get removed when bluetooth is activated so that the rest of the package could still be used.

What would be the best way to package the radio-dependent blocks so that:
1. they load up automatically with the rest of the package
2. only the radio blocks get removed/disabled when Bluetooth is activated

I've attempted to make the radio blocks their own package, and pull that package with the main one, but installing bluetooth disables both packages instead of just the radio one because the dependency list has it as a requirement, instead of a suggestion.

**Comment by abchatra** [comment]
You will need to write two separate packages, one dependent on radio and other on Bluetooth. And specify the dependency in your package.
