### ISSUE TITLE
 Help document can't be opened in a new page unless you open it twice on IE

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#967]
**Repro steps:**
1. Navigate to https://makecode.microbit.org/alpha#editor
2. Click "Help" -> "Blocks" 
3. Click the arrow on the top-right of the help document

**Expected result(Edge, Chrome & Firefox):**
The document can be opened in a new page

**Actual result(IE):**
 Help document can't be opened in a new page unless you open it twice
![issue72501](https://user-images.githubusercontent.com/23466737/43195827-c78dd8ec-9038-11e8-959d-b021df2d903e.gif)

**Comment by abchatra** [comment]
This is IE limitation, can't fix.
