### ISSUE TITLE
No scrollbar in variable dropdown

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt-microbit#968]
**Describe the bug**
Can't access variables from 'set item' block popup menu if lots of variables defined

**To Reproduce**
Drop a 'set item to' and try to select 'AWasPressed' from the menu - can't

**Expected behavior**
Expect to be able to select my variable

**Screenshots**
![screen shot 2018-07-26 at 10 58 06](https://user-images.githubusercontent.com/25079586/43255926-09de48d2-90c3-11e8-9d8b-6c08d3e777e8.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OSX 10.5 (11 inch screen)
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 67

**Additional context**
This is a script I imported from touch develop. The script is attached.
[accel-TD.hex.zip](https://github.com/Microsoft/pxt-microbit/files/2231445/accel-TD.hex.zip)

**Comment by abchatra** [comment]
Fixed in alpha.

**Comment by abchatra** [comment]
Fixed in V1
