### ISSUE TITLE
When "A1" is released, the led on simulator is still on

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#969]
**Repro steps:**
1. Navigate to https://makecode.adafruit.com/beta#editor
2. Copy below code to content pane and press "A1" and then release

**Expected result:**
When "A1" is released, the led on simulator should be off
![issue72502compare](https://user-images.githubusercontent.com/23466737/43256602-cf358726-90ff-11e8-98a2-d1431ee7b0a2.gif)

**Actual result:**
When "A1" is released, the led on simulator is still on
![issue72502issue](https://user-images.githubusercontent.com/23466737/43256599-c934c602-90ff-11e8-966f-f41ff452cced.gif)

**Comment by abchatra** [comment]
This is not microbit.
