### ISSUE TITLE
Oops, something went wrong trying to convert your code

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt-microbit#971]
**Describe the bug**
Importing this script from touch develop into MakeCode. Press BLOCKS button and get 'oops,something went wrong trying to convert your code' - but there is no indication as to what went wrong and where in the code it went wrong.

**To Reproduce**
Save hex file from: https://www.microbit.co.uk/lfeunw
drag hex file into makecode.microbit.org
press BLOCKS button

**Expected behavior**
Code should render as blocks

**Screenshots**
![screen shot 2018-07-26 at 16 19 06](https://user-images.githubusercontent.com/25079586/43271520-a423ce4a-90ef-11e8-8d84-ceeb517397d4.png)

**Desktop (please complete the following information):**
Macosx 10.10.5 11inch
Chrome 68

**Additional context**
We are porting all scripts for one of our partner organisations from Touch Develop to MakeCode.

**Comment by DavidWhaleMEF** [comment]
Note, the code does 'run' as expected. But I want it rendered as blocks so that we can update our printed resources.

@abchatra can you get someone to investigate at your end please (FYI: this work I am doing is scheduled to be completed by end of Friday 27th July) - just a hint as to which line is failing to convert, so I can rewrite that line and get it rendered as blocks will save my bacon, thanks!

**Comment by abchatra** [comment]
Function return values are not decompileing: 

Short repro
```javascript
let gameTime = getGameTime();
function getGameTime(): number {
   let chosenGameTime = 7
    /*
    some code
    */
  return chosenGameTime
}
```
**Workaround** : Change to following

```javascript
let gameTime = 0
getGameTime()
function getGameTime() {
   let chosenGameTime = 7
    /*
    some code
    */
    gameTime = chosenGameTime
}
```
Fixed in alpha

**Comment by DavidWhaleMEF** [comment]
Super stuff, thanks @abchatra I will be able to finish porting this final resource now - thanks very much for your speedy help and the workaround too!

**Comment by DavidWhaleMEF** [comment]
@abchatra I have managed to get the script converted now, thanks. Parameters and return results don't transfer from TD that well. It turns out that direct references to globals solves both the return result error, and the horrible grey rendering where parameters are used (and the program still makes sense logically). Thank you very much for helping at short notice with this fix/workaround, it worked a treat thanks! I will close the ticket now.

**Comment by abchatra** [comment]
:-)
