### ISSUE TITLE
Controlled deprecation, with tool support

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt-microbit#972]
**Is your feature request related to a problem? Please describe.**
When breaking changes have to be done to the language or API's (e.g. in order to correct previous errors such as 'pressed' and 'clicked'), this stores up errors for the future. A teacher that has a pre-written exercise, perhaps with a working hex file, drags the hex file into a later editor and now it comes up with an error

**Describe the solution you'd like**
When breaking changes need to be made to API's and the language (for good reasons, to support innovation and progress), leave the API method present and mark it as deprecated. If a script uses a deprecated API call, there should be some warning that pops up, with a way for users to get advice on the new way to do things. After, say, 1 major release with deprecation, the next major release could remove the old API but leave the deprecation hints. A further major release could then remove these phantom deprecation hints as a way to spring clean.

**Describe alternatives you've considered**
An alternative is to never change or delete API methods (e.g CreateFile and CreateFileEx in the windows API is an example of this).

**Additional context**
It was thinking  about this issue and @abchatra 's reply about making a breaking change, that reminded me of how the java language very elegantly has a process to manage deprecation in a controlled and visible way.
https://github.com/Microsoft/pxt-microbit/issues/963

**Comment by abchatra** [comment]
Yes we do that already. We deprecate the API, but still available if you drag the old hex file.
