### ISSUE TITLE
Angle parameter missing in chinese translation

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#977]
microbit-support:6732

![image](https://user-images.githubusercontent.com/31242877/43310599-f04b5596-917f-11e8-960d-01230ae34270.png)

 item.turn(Direction.Right, 0)
The last parameter (the angle) is missing if you use Chinese language

**Comment by abchatra** [comment]
Fixed in alpha

**Comment by abchatra** [comment]
Fixed in v1
