### ISSUE TITLE
Pick Random block rendering on import

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-microbit#986]
I just imported a couple older .hex files with the Pick Random block.
It seems to translate it correctly to 'randomRange', but then it doesn't render the '0' value in blocks correctly:
v0
![randomv0](https://user-images.githubusercontent.com/22108954/43342149-8ef18056-9196-11e8-9fd2-3e14b81d293f.PNG)

v1
![randomv1](https://user-images.githubusercontent.com/22108954/43342156-9499e3fe-9196-11e8-9425-71eff1b870ea.PNG)

v1 Blocks
![randomv1blocks](https://user-images.githubusercontent.com/22108954/43342160-99847816-9196-11e8-8650-d17592340e76.PNG)

**Comment by riknoll** [comment]
Fixed!
