### ISSUE TITLE
Windows 10 Chrome Download & save not working with neopixel show block: Compilation failed

### ISSUE THREAD

**Issue by Lorrainbow** [Microsoft/pxt-microbit#991]
**Describe the bug**
Cannot download or save a program with neopixel code in it. Using Windows 10 and Chrome. I get an orange popup text saying "Compilation failed, please check your code for errors."

**To Reproduce**
1. Add the Neopixel package (Advanced > Extensions > Neopixel)
2. Setup the Neopixel strip in "on start"
3. Add a Neopixel command like "show color red" to an input button. e.g "on shake"
4. Select Download or the save icon
Result: See attached screenshot

**Expected behavior**
To be able to download the program 

**Screenshots**
![image](https://user-images.githubusercontent.com/5673444/43351053-8eca70ce-9204-11e8-8580-d499f7211c15.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 68.0.3440.75 (Official Build) (64-bit)

**Additional context**
It downloads when you add the library (step 1) and when you add the strip (step 2) it only fails when you try to "show color"

**Comment by abchatra** [comment]
This is a good bug. We will investigate. Thanks @Lorrainbow

**Comment by abchatra** [comment]
We should have full backward compat

**Comment by riknoll** [comment]
The second issue is actually unrelated; our share dialog seems to be generating incorrect URLs for the embed code.

@Lorrainbow here is a temporary fix for your blog post. Change this:


```

<iframe src="https://makecode.microbit.org/#pub:_EgeMgyPLqf0P" frameborder="0" style="position:absolute;top:0;left:0;width:100%;height:100%;" sandbox="allow-popups allow-forms allow-scripts allow-same-origin"></iframe>
```

To this:

```
<iframe src="https://makecode.microbit.org/beta#pub:_EgeMgyPLqf0P" frameborder="0" style="position:absolute;top:0;left:0;width:100%;height:100%;" sandbox="allow-popups allow-forms allow-scripts allow-same-origin"></iframe>
```

(Notice the missing `beta` in the `src` URL)

**Comment by CleoQc** [comment]
I'm having a similar issue so not opening a new issue but tagging on to this one.
I have pxt-giggle which pulls pxt-gigglebot and neopixels as dependencies. I get the same "Check your code for errors".

If I load pxt-gigglebot directly, without pxt-giggle and neopixels, then the code can be transferred to the microbit and work.

So just a "me too" on the neopixel issue.

**Comment by riknoll** [comment]
For the embed issue, it's filed here: https://github.com/Microsoft/pxt-microbit/issues/983

For the compilation issue, I'm handing this off to @mmoskal

**Comment by riknoll** [comment]
Fixed in next release
